### PR TITLE
Assorted trivial cleanups 5/2019

### PR DESCRIPTION
**Pull request by mcostalba**
Tablebases::rank_root_moves()

No functional change.

### CODE REVIEW

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp#L194
This description is wrong (and probably was never changed since kingring was made 8 squares always).
Should be something like 
//kingRing[color] are the squares adjacent to the king, plus (only for a
    // king on its first rank) the squares two ranks in front, plus (only for a king on A or H file) the squares two ranks to EAST or WEST (for A and H file respectively). For instance,
    // if black's king is on g8, kingRing[BLACK] is f8, h8, f7, g7, h7, f6, g6
// and h6, and if king is on h8, kingRing[BLACK] is f8, f7, f6, g8, g7, g6, h7 and h6
This can be written better than what I've wrote now.

**Comment by vondele** [comment]
```diff
diff --git a/src/search.cpp b/src/search.cpp
index bafc374ba..88cf6510b 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1056,7 +1056,7 @@ moves_loop: // When in check, search starts from here
               r -= ss->statScore / 20000 * ONE_PLY;
           }
 
-          Depth d = std::max(newDepth - std::max(r, DEPTH_ZERO), ONE_PLY);
+          Depth d = clamp(newDepth - r, ONE_PLY, newDepth);
 
           value = -search<NonPV>(pos, ss+1, -(alpha+1), -alpha, d, true);
 
```

**Comment by protonspring** [comment]
Evaluate.cpp, line 827, we should probably have separate lines for each piece type.  There is apparently some variation in compilers handing +a-b+c-d... in the same way.  This forces piece order and most likely makes all compilers behave the same.

// Evaluate pieces first and force piece order.  Also populates attack tables.
score += pieces<WHITE, KNIGHT>() - pieces<BLACK, KNIGHT>();
score += pieces<WHITE, BISHOP>() - pieces<BLACK, BISHOP>();
score += pieces<WHITE, ROOK  >() - pieces<BLACK, ROOK  >();
score += pieces<WHITE, QUEEN >() - pieces<BLACK, QUEEN >();

**Comment by ianfab** [comment]
The appveyor links at the top of the readme point to the most recent build (can also be a PR), but IMO should always point to the most recent build of master:
`
[Build Status](https://ci.appveyor.com/project/mcostalba/stockfish/branch/master)
`

**Comment by protonspring** [comment]
Position.cpp, line 496.  Since snipers is a subset of pieces(), i think the '^' operator is more appropriate here.  

Bitboard occupancy = pieces() ^ snipers;

**Comment by vondele** [comment]
```diff
diff --git a/src/search.cpp b/src/search.cpp
index f1136e3e5..2cdd980bc 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -240,17 +240,13 @@ void MainThread::search() {
           minScore = std::min(minScore, th->rootMoves[0].score);
 
       // Vote according to score and depth, and select the best thread
-      int64_t bestVote = 0;
       for (Thread* th : Threads)
       {
           votes[th->rootMoves[0].pv[0]] +=
                (th->rootMoves[0].score - minScore + 14) * int(th->completedDepth);
 
-          if (votes[th->rootMoves[0].pv[0]] > bestVote)
-          {
-              bestVote = votes[th->rootMoves[0].pv[0]];
+          if (votes[th->rootMoves[0].pv[0]] > votes[bestThread->rootMoves[0].pv[0]]);
               bestThread = th;
-          }
       }
   }
 
```

**Comment by WOnder93** [comment]
> ```diff
> +          if (votes[th->rootMoves[0].pv[0]] > votes[bestThread->rootMoves[0].pv[0]]);
> ```

Um... there is a semicolon at the end of that if-statement... :astonished:

**Comment by mcostalba** [comment]
Thanks. Updated.

**Comment by mstembera** [comment]
Just curious.. What does OFS stand for in DEPTH_OFS ?

**Comment by mstembera** [comment]
In the for loops on lines 92 and 99 in material.cpp the pt1 and pt2 variables would be better as PieceType instead of int.

**Comment by mcostalba** [comment]
@mstembera OFS is for offset. Technically this kind of translation constant is called an offset. The name depth_zero refers to the qsearch different kind of depths, but has no relation with a translation operation we are doing to use unsigned depths in TT.

**Comment by mstembera** [comment]
@mcostalba Makes sense.  Maybe DEPTH_OFFSET in case others don't understand OFS right away like me but no problem either way.

**Comment by Rocky640** [comment]
search.cpp lines 592 to 595: some tabulation were used instead of spaces.

**Comment by joergoster** [comment]
This commit https://github.com/official-stockfish/Stockfish/commit/3d076a0c50cae378c463fdd2a65a250eda55edab can be further simplified to:
```
      if (type_of(pc) == PAWN)
          si->pawnKey ^= Zobrist::psq[pc][s];

      else if (type_of(pc) != KING)
          si->nonPawnMaterial[color_of(pc)] += PieceValue[MG][pc];
```
The 'else if' statement already excludes `type_of(pc) == PAWN` which makes the check for
`type_of(pc) != PAWN` obsolete.

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1024
Missing a spacing between different reductions.

**Comment by protonspring** [comment]
Pawns.h, line 61, there is still a PawnsOnSquares[COLOR_NB][COLOR_NB].  These values are no longer used.

**Comment by joergoster** [comment]
Lines 909 - 916 in search.cpp (Singular Extension) do need some formatting care.
```
          if (value < singularBeta)
          {
              extension = ONE_PLY;
              singularExtensionLMRmultiplier++;

              if (value < singularBeta - std::min(3 * depth / ONE_PLY, 39))
              	  singularExtensionLMRmultiplier++;
          }
```

**Comment by protonspring** [comment]
search.cpp, line 1478, there is an extra space in the assignment.

**Comment by mcostalba** [comment]
Thanks, updated. 

I have found an imprtant issue that I missed when merging.

    Currently there is a consistency issue with this
    reduction, because we compare the value returned by
    a zero seacrh window with a threshold outside of the
    [alpha, beta] interval.
    
https://github.com/official-stockfish/Stockfish/blob/64088835e7db7b36d8dea4006817b98def60f4e5/src/search.cpp#L909

    This is wrong and should be removed.

**Comment by xoto10** [comment]
Whitespace correction in pawns.cpp:
```
diff --git a/src/pawns.cpp b/src/pawns.cpp
index 291d40b..f9187f5 100644
--- a/src/pawns.cpp
+++ b/src/pawns.cpp
@@ -78,8 +78,8 @@ namespace {
     Bitboard theirPawns = pos.pieces(Them, PAWN);
 
     e->passedPawns[Us] = e->pawnAttacksSpan[Us] = e->weakUnopposed[Us] = 0;
-    e->kingSquares[Us]   = SQ_NONE;
-    e->pawnAttacks[Us]   = pawn_attacks_bb<Us>(ourPawns);
+    e->kingSquares[Us] = SQ_NONE;
+    e->pawnAttacks[Us] = pawn_attacks_bb<Us>(ourPawns);
 
     // Loop through all pawns of the current color and score each pawn
     while ((s = *pl++) != SQ_NONE)
```

**Comment by mcostalba** [comment]
Started:  http://tests.stockfishchess.org/tests/view/5cebc1130ebc5925cf07b905

**Comment by mstembera** [comment]
Material::Entry could just store Score instead of int16_t value.  Entry::imbalance() could then return it directly instead of having to create it each time using make_score(value, value);  I can create a separate PR for this if it's easier.

**Comment by mstembera** [comment]
Line 816 in evaluate.cpp 
```C++
if (abs(v) > (LazyThreshold + pos.non_pawn_material() / 64))
```
can be just
```C++
if (abs(v) > LazyThreshold + pos.non_pawn_material() / 64)
```
or even
```C++
if (abs(v) * 64 > LazyThreshold  + pos.non_pawn_material())
```
with LazyThreshold redefined to 89600 (64 * 1400).

**Comment by Rocky640** [comment]
in pawns.cpp, line 104, a non functional simplification:
 ```
        // A pawn is backward when it is behind all pawns of the same color
        // on the adjacent files and cannot be safely advanced.
        backward =  !(ourPawns & pawn_attack_span(Them, s + Up))
                  && (stoppers & (leverPush | (s + Up)));
```

could be simplified (removing the first "+ Up") and comment can be improved as follow

 ```
        // A pawn is backward when it is behind all pawns of the same color
        // on the adjacent files and cannot be safely advanced.
        // Phalanx and isolated pawns will be excluded when the pawn is scored.
        backward =  !(ourPawns & pawn_attack_span(Them, s))
                  && (stoppers & (leverPush | (s + Up)));
```

**Comment by mcostalba** [comment]
Merged in d39bc2efa197ba2

**Comment by mcostalba** [comment]
@mstembera score is an integer while int16_t  is 16 bit, so the table would be bigger (2 times at least)

**Comment by mstembera** [comment]
@mcostalba I did some testing and the current Material:Entry is 40 bytes exactly no padding.  Changing the type of value from int16_t to Score should only add 2 bytes but due to padding it would actually add 8 bytes so the new size would be 48.  I agree it's probably not worth it.

**Pull request closed without merging**
