### PR TITLE
[RFC] AffineTransform simplification + speedup

### PR DESCRIPTION
**Pull request by mstembera**
Initially tested as a simplification
STC https://tests.stockfishchess.org/tests/view/6317c3f437f41b13973d6dff
LLR: 2.95 (-2.94,2.94) <-1.75,0.25>
Total: 58072 W: 15619 L: 15425 D: 27028
Ptnml(0-2): 241, 6191, 15992, 6357, 255

Elo gain speedup test
STC https://tests.stockfishchess.org/tests/view/63181c1b37f41b13973d79dc
LLR: 2.94 (-2.94,2.94) <0.00,2.00>
Total: 184496 W: 49922 L: 49401 D: 85173
Ptnml(0-2): 851, 19397, 51208, 19964, 828 

Simplify away AffineTransform specialization for large inputs.
Move simd.h from src to src/nnue/layers
No functional change
bench: 5609606

Please wait maybe 48 hours so @Sopel97 has a chance to comment.  Maybe the removed code should be kept but only used by AVX512 builds or the remaining code should include support for AVX512.  (FYI AMD Ryzen 7000 finally adds AVX512 support so it's actually more relevant than before.)  I don't think fishtest has many AVX512 machines so the test didn't catch this case properly.
If you think simd.h should not be moved let me know but it isn't used anywhere else in SF.

### CODE REVIEW

**Comment by Sopel97** [comment]
I'd like to see some fishbench results from different setups before I comment on this. Though, as you realized, the code path was mainly motivated by AVX512 which doesn't lend itself to a nice implementation here considering there are only 8 outputs and a full __m512i hold 16 int32s.

**Comment by mstembera** [comment]
This is what I get for an AVX512 compile on my old Skylake-X which is too much of a hit to take especially with AVX512 becoming more important.
```
Results for 100 tests for each version:

            Base      Test      Diff      
    Mean    807443    753018    54425     
    StDev   40094     50612     59930     

p-value: 0.182
speedup: -0.067
```
So I have pushed a version that gets the AVX2 speedup but doesn't affect AVX512.  What do you think?

**Comment by Sopel97** [comment]
What does the benchmark look like with AVX2?

**Comment by mstembera** [comment]
On my machine it's neutral which is why I initially tested a as simplification.  When the test finished +1elo it made me realize it could be a speedup on other machines so I retested as an elo gainer.
```
Results for 100 tests for each version:

            Base      Test      Diff      
    Mean    836488    832789    3699      
    StDev   54877     50918     66285     

p-value: 0.478
speedup: -0.004
```

**Comment by vondele** [comment]
I can confirm a speedup:
```
Result of  10 runs
==================
base (./stockfish.master       ) =    1674272  +/- 11688
test (./stockfish.patch        ) =    1686117  +/- 13932
diff                             =     +11845  +/- 3099

speedup        = +0.0071
P(speedup > 0) =  1.0000

CPU: 16 x AMD Ryzen 9 3950X 16-Core Processor

```

**Comment by mstembera** [comment]
@vondele Thanks for testing.  I'm happy w/ the current version so I leave it up to you if you prefer to wait for more comments from @Sopel97.  Let me know if I should squash or leave as is.

**Comment by Sopel97** [comment]
In this case I suggest a slightly different formulation for the condition. The only reason now for the second implementation to be used is that AVX512 requires a multiple of 16 outputs, so I'd condition it on `OutputDimensions % (SimdWidth / 4) != 0`, potentially also add a static assert that it only happens right now with SimdWidth==64

**Comment by vondele** [comment]
OK, please squash, including Sopel's comment, I think it's good to make it a little more generic.

**Comment by vondele** [comment]
and provide an updated comment, that I can copy and paste, please.

**Comment by mstembera** [comment]
@Sopel97 I'm happy to change but I don't quite understand exactly what you mean.  Can you please post or link the exact code?

**Comment by mstembera** [comment]
@Sopel97 To be clear when I write
```class AffineTransform<InDims, OutDims, std::enable_if_t<(OutDims % (SimdWidth / 4) != 0)>> {```
and
```class AffineTransform<InDims, OutDims, std::enable_if_t<(OutDims % (SimdWidth / 4) == 0)>> {```
for the two specializations both get used by AVX2 which is not what we want and I get a mod by 0 error for the AVX512 case.  Please write the full patch the way you want and post a link.  If it's easier just open a PR and I'll close this one.

**Comment by Sopel97** [comment]
Right... We can't define (correct) SimdWidth for AVX512 because of legacy issues.... It would take a little bit of a rewrite to do this well, so I guess we can settle on the current version for now.

**Comment by mstembera** [comment]
@Sopel97  Ok.  
@vondele  Squashed.
Commit message:
Optimize AVX2 by always selecting AffineTransform specialization for small inputs.
Move simd.h from src to src/nnue/layers

**Pull request closed without merging**
