### PR TITLE
Time management: Use the score from previous search to resolve fail l…

### PR DESCRIPTION
**Pull request by mbootsector**
Need some advice on what to do with this patch. I made a blunder when rescheduling the test with another value for Slow Mover.

With default Slow mover (80) we got STC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 4651 W: 961 L: 814 D: 2876
http://tests.stockfishchess.org/tests/view/564cb3140ebc5902cdc082a6

And LTC was yellow, with a positive score:
LLR: -2.95 (-2.94,2.94) [0.00,5.00]
Total: 57444 W: 8367 L: 8282 D: 40795
http://tests.stockfishchess.org/tests/view/564cc7590ebc5902cdc082b0

Then I recheduled with Slow Mover=84, STC:
LLR: 2.94 (-2.94,2.94) [0.00,5.00]
Total: 14495 W: 2903 L: 2711 D: 8881
http://tests.stockfishchess.org/tests/view/564ed8260ebc5902cdc0830c

Ongoing LTC  with Slow Mover=84:
LLR: 1.77 (-2.94,2.94) [0.00,5.00]
Total: 69421 W: 10766 L: 10435 D: 48220
http://tests.stockfishchess.org/tests/view/564efc4c0ebc5902cdc08314

The blunder is that LTC with default Slow mover was run with 60+0.4, the LTC for Slow Mover=84 is run with 40+0.4. The second test seems to do better, but this could be because of shorter time control, and not because of the modified Slow Mover value.
Is there any hope for first green+yellow patch to be committed? If there is, I'll schedule a test with default Slow Mover for 7 threads 5+05 because this patch is dependent on bestThread score.

### CODE REVIEW

**Comment by mcostalba** [comment]
A time management patch that introduce complexities should really prove
stronger before being committed IMO because current time management is
already messed up enough and especially because time management is very
difficult to test properly and with enough wide coverage.

I dream the day someone will come up with a very simple, understandable,
robust and reliable time management patch that will trash away all our
current code.

**Comment by mbootsector** [comment]
LTC with Slow mover 84 just passed.
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 75056 W: 11664 L: 11263 D: 52129

I'll schedule a 7-thread 5+0.05 test for slow mover 84.

**Comment by mcostalba** [comment]
Well, it is not strictly related to this, but refers to bestThread in general.

Currently we set completedDepth of a thread at the end of a succesful iteration, then suppose at the next iteration we change best root move and then we receive stop signal in the middle of the search with a broken and dirty root move, we return and because completedDepth is not reset we use the broken first move as best one: this is really broken.

I think we should firt fix bestThread logic before furthering adding mess above it (liek this patch does).

**Comment by lucasart** [comment]
@mcostalba: maybe the correct solution would be to store each thread's PV, and update it upon completing an iteration.

**Comment by mcostalba** [comment]
@lucasart at the moment I'd like just to fix it simply resetting completedDepth if PV move changes at root:

https://github.com/mcostalba/Stockfish/compare/79f3930...5c7d16f

Once lazy smp is fixed and logic is natural and makes sense (so without scores) we can move on. One of the reason I intuitively liked lazy over YBW, apart from huge code reduction, is that lazy has more potential for exploring improvements and now it seems this is indeed happening.

**Comment by lucasart** [comment]
@mcostalba: I am working on a complete solution. Solves the broken move problem, and the multi pv and skill level. It implements the "all threads are equal" paradigm, with PVInfo as above for UI synchronization. It's almost ready...

**Comment by lucasart** [comment]
@mcostalba: here is my code. please have a look
https://github.com/official-stockfish/Stockfish/compare/master...lucasart:equal_smp

**Comment by mbootsector** [comment]
@mcostalba Seems there are some issues with time management. The Ponder uci option defaults to true, and AFAIK fishtest doesn't send ponder=off when running tests, and in Timemanager.cpp we have this:
  if (Options["Ponder"])
      optimumTime += optimumTime / 4;
Seems SF always uses 25% more time than originally intended.
I'll cancel my 7-thread test... The patch is likely worth <1 ELO at very long time controls anyway.

**Comment by lucasart** [comment]
@mbootsector: good catch on pondering tm bug. but completely unrelated to this pull request.

IMO this pull request should be closed:
* Retesting a failed patch at LTC (even with Slow Mover slightly changed) is cheating statistics.
* And mixing SMP with TM is a big no no.
* As marco pointed out, the patch adds even more band-hacks, instead of offering a clean solution.

**Comment by lucasart** [comment]
typo: band-aid hacks

**Comment by mbootsector** [comment]
@lucasart Yes, it's unrelated, but I wanted to write this ponder finding somewhere so it won't get lost. It's of course better to add it as an Issue.

**Pull request closed without merging**
