### PR TITLE
Change Value type back to int

### PR DESCRIPTION
**Pull request by protonspring**
I'm not sure this enumeration/type does very much.  It's probably supposed to be self-documenting, but is a "value" any more clear than an int?  Also, any clarity lost can easily be fixed with an appropriate variable name.  This is a non-functional simplification.

Changing back to int, removes LOTS of preprocessor directives and type casts as well as special operators to add ints to Values (which is kind of annoying).  Removes about 10 lines of code and lots of noisy code in between.

On my machine, this is 1.5% faster as well (+17k nps).

Bench 5351765

### CODE REVIEW

**Comment by syzygy1** [comment]
The point of using C++ is to have strong type checking. I see no good reason to replace Value with int.

**Comment by leesailer** [comment]
"Value" is pretty generic.  Maybe a better name?  "Eval"?

For me, I thought Score was the eval for awhile, until I figured out it was two ints packed into one.

**Comment by syzygy1** [comment]
A Score is really two Values packed into one. That make_score() takes two ints seems to be a compromise (to reduce the number of Value casts just before making a Score). eg_value() and mg_value() return Value.

Eval seems to be a strange name as the type of e.g. alpha and beta.

**Comment by protonspring** [comment]
I'd be quiet curious if anyone else could verify the speed up.

**Comment by syzygy1** [comment]
Where would the speed up come from? You're replacing ints with ints.

**Comment by syzygy1** [comment]
On the assumption that Stéphane is not willing to trade code quality (from a C++ point of view) for a small reduction in line count, I think the patch would need to pass [0,5] instead of [-3,1] (which is now running).

A 1,5% speed up should pass [0,5] relatively easily.

**Comment by protonspring** [comment]
It doesn't look like the one on the framework is any faster than master. So
I doubt that will happen. Probably safe just to let this die.

**Comment by mcostalba** [comment]
@protonspring with all the due respect, but **why**  [-3, 1]?

Really this [-3, 1] thing is getting out of hand!

You claim is faster, well put your money where your mouth is and run something braver than a lame [-3, 1]

Of course the reason why it is an enum instead of an int has been already clarified above, so I won't repeat it.

**Comment by locutus2** [comment]
@protonspring 
I have her to backup @mcostalba. The type checking is a good thing.
Th enums makes it more clear for the developers what a variable means and the type checking helps to avoid messing thinks up. 
And a speed gain is not possible because internally enums also ints. The compiler does only at compile time some additionnal type checks for consistence.

**Pull request closed without merging**
