### PR TITLE
Move pruning at PV nodes

### PR DESCRIPTION
**Pull request by locutus2**
Allow move pruning in search at PV nodes.
Futility pruning in step 7 is included too (Thanks to Lucas for point out this to me).

STC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 21553 W: 4342 L: 4221 D: 12990

LTC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 7675 W: 1351 L: 1209 D: 5115

Bench: 8668014

### CODE REVIEW

**Comment by lucasart** [comment]
Shouldn't alpha be raised with `bestValue` ?

    bestValue = std::max(bestValue, futilityValue);
    alpha = std::max(alpha, bestValue);

**Comment by locutus2** [comment]
No, his i wrapped under
if(futilityValue <= alpha)
so alpha will not be raised trough futilityValue.

In quience search
if(futilityValue < beta)
is used.
Without PV nodes (so we have a minimal window search with alpha = beta-1) this the same as
if(futilityValue <= alpha)
So with PV nodes allowed the current condition seems wrong and <= alpha has to be used.

**Comment by lucasart** [comment]
ok. i missed the `if (futilityValue <= alpha)`.

PS: if you look at my patch, I'm doing it correctly (`<= alpha` is used).

**Comment by locutus2** [comment]
Ok, i see. But the alpha update is then not nessecary anymore.

**Comment by glinscott** [comment]
Unless I'm reading this wrong, we are pruning moves at the root here?  That seems incorrect.

Also, I'm not sure this should have been tested with simplification bounds, a lot of the restrictions on PV nodes aren't there for ELO, but for safety so we don't do things like starting to miss checkmates or give incorrect ones.

It's certainly an interesting idea, but it requires a fair bit of thought, and more testing IMO.

What are other peoples thoughts?

**Comment by locutus2** [comment]
In the past i had the same feeling that this PV exclusion is a safe guard and i find it reasonable.
So i tried in recent past different versions to extend this safety to nodes which are only 1 node away, but this failed (at best zero elo). On the mentioned talkchess thread the really intersting question is which logical reason account for different treatment of PV and non-PV nodes move pruning.
So i decide to measure the effect (instead of no-regression, because simplification is not my point). This test shows slightly edge for pruning at PV nodes, which seems get even bigger at longer tc.

In the end not pruning at PV nodes does delay the pruning only one ply. This seems not counter the node reduction which pruning on PV could give.

Perhaps not pruning at root seems reasonable (but that is possible gut feeling from me!).

I think a fixed games test with even longer tc (120+0.05 or 240+0.05) would be interresting, to see if the gain is bigger.

Then the conclusion that PV node pruning hurts only at very short tc seems right.

**Comment by joergoster** [comment]
@locutus2: and maybe also a test in smp mode to be safe it is no regression there?

**Comment by zamar** [comment]
I think that the patch is basically fine. There needs to be a justification for each condition (like !PvNode), and currently there isnt'

But just to be on the safe side, we could test the result with SMP (like 20k games, with 60+0.05 and 3 threads). If it isn't awfully bad (like a regression >95% probability), I would support committing.

**Comment by zamar** [comment]
@locutus2: Can you please schedule an SMP test?

**Comment by locutus2** [comment]
@zamar
I have your proposed test scheduled.

Another test idea would a comparison between the master and this patch against foreign engines like Komodo 8. This could possible best discover if safety in pruning plays a role. Could someone with enough machine power do such an test with a significant number of games? Perhaps Jens

**Comment by lucasart** [comment]
Patch is fine. Yes, we can prune moves at Root, but we can't prune the Root at Step 7. Pruning at root at shallow depth is not a problem, because the first move cannot be pruned, and these iteration are done well before you return a bestmove. The only use case where you could see a regression is if you use a shallow fixed depth testing instead of tc testing, but it will never crash and return an illegal move.

Now this business of "not pruning at PV nodes is safer" is yet another myth. What you do at non PV nodes impact PV nodes by back propagation. We must accept testing results only, never hand waving arguments. I don't see why this patch would be treated differently.

I don't understand why an SMP test is due here. What's the rationale ? Should every search patch be tested in SMP or just this one ? Same questions for testing against foreign opponents.

**Comment by glinscott** [comment]
@lucasart - no, we do not blindly accept changes.  Especially tested with no-regression parameters.  If we did do, we could easily simplify the engine down to nothing if persistent enough.  So, please stop saying it's handwaving to be concerned about changes to the search that don't increase strength.

I'm almost in favor of banning the simplification LLR parameters.  They are a much more attractive target, since the bar is much easier to clear, and are usually riskier changes as well.

**Comment by lucasart** [comment]
@glinscott: the burden of proof is on *you*. please show us why this patch causes an issue and I will listen.

**Comment by glinscott** [comment]
@lucasart - no, it's not.

**Comment by mcostalba** [comment]
I fully   agree with you, a patch cannot be blindly applied only because
passes the test. I also agree in this case it is more a conceptual
simplification than a technical one, and testing with (-3,1) it is a bit
border line, nevertheless in general simplification parameters are a
powerful tool that gave a lot of good patches to SF, impossible to get
otherwise. It is also a novelty introduced by SF testing, before that
people didn't were able to simplify an engine in a rigorous way (I remember
well when me and Joona were stuck with what we had, without any possibility
to remove useless stuff).   Fishtest, that is your great contribution,
allowed that, and it is a big plus for engine development. Before that
serious authors reached a point were they had to scrap all and start again
from scratch: Tord did it many times before Glaurung.




Odidn't n Tuesday, January 13, 2015, Gary Linscott <notifications@github.com>
wrote:

**Comment by zamar** [comment]
@lucasart: The reason I asked for SMP test is that we are changing here something just before the release that has a potential SMP impact:
- We split at root, and we start pruning at root. I just want to make sure that we haven't missed anything critical in this. So for me this is a more like crash test and a serious regression test than anything else.

**Comment by zamar** [comment]
@glinscott: It's a very valuable asset to be able to simplify. I think that every condition in SF code must be justified by something. E.g. there must always be a valid reason for doing things differently for PV nodes and non-PV nodes. This results in higher search instability and in general it should be avoided.

**Comment by lucasart** [comment]
@zamar: ok. my understanding was that, since we don't update alpha, there's no SMP related scenario that isn't already catered for. anyway SMP test shows that there's no issue with the patch.

**Comment by zamar** [comment]
@lucasart: That was my assumption as well, but I've learned the hard way to be extra careful with these things.

**Comment by Karlon** [comment]
This patch passed the test, and a SMP test performed by Lucas on fishtest affirms that there is no problem with this patch at all. So I will suggest that it gets merged into the official repo right away, rather than discussing rubbish and wasting time.

**Comment by mcostalba** [comment]
@Karlon : your account has been blocked and banned from this repo.

**Comment by zamar** [comment]
approved.

**Comment by glinscott** [comment]
@mcostalba @zamar - yes, i agree having the ability to simplify the engine is valuable.  I don't have an issue with this patch in particular, it's more with the overall simplification rules.  It just feels wrong to have the LLR bounds in the negative to accept a patch.

In a perfect world, every simplification that is a functional change would also need to be a strength improvement.  But I recognize this is not feasible, and can make the codebase fragile in the long term as it loses flexibility.

**Comment by glinscott** [comment]
Patch looks good after the LTC regression test shows no issues.

One thing that would be nice to investigate is if we are hurting mate analysis.  But this shouldn't push mates beyond the horizon.

**Comment by lucasart** [comment]
@glinscott: regarding simplification and risk of regression, we can test this patch in combination with the qsearch patch. if we are in that unlucky extreme scenario where each patch is a -1 elo regression that had lucky runs, then combining them should make that hypothetical regression -2 elo, hence mesurable.

Regarding mates, I'm not sure what you're asking for, who should do it and how? If we used tactical test suites as criteria in the past for validating search patches, SF would be nowhere near as strong as it is now.

**Comment by glinscott** [comment]
@lucasart - The analysis doesn't need to block the patch being merged.  Something like a before/after comparison on a mate testsuite would be good.  I will take a look at it if nobody beats me to it.

Also, I'm certainly not advocating test suites for testing patches.  We have a great way of validating patches, it's the [-1.5,4.5], [0,6] SPRT tests.  However, if we are using bounds that allow regressions with higher probability, the patch deserves more scrutiny.

**Comment by lucasart** [comment]
the best way to do the before/after mate finding test, is to let someone else do the work. and the best way to do that, is to merge both pull requests, so people can grab the executable on abrok.eu. grabbing branches from other repo and compiling, isn't something that most SF fans know how to do.

**Comment by zamar** [comment]
Regarding mate analysis: 
* In both steps we guard against unproven mate scores, so this shouldn't be an issue.
* Of course always when searching logic in the search, this can affect the performance of mate finding.

**Comment by zamar** [comment]
I'll commit this and #206 tonight (unless someone else is quicker)

**Comment by lucasart** [comment]
@zamar: It's even ok to prune the Root node in Step 7. The point is that even if Step 7 prunes the Root at depth 1, aspiration window will loop again until it doesn't happen, so even "go depth 1" will never return an uninitialized move. I'm the one who suggested that `!RootNode` condition to Stefan, but in fact, it's useless!

**Pull request closed without merging**
