### PR TITLE
consistent TT

### PR DESCRIPTION
**Pull request by mstembera**
STC 2MB
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 11301 W: 2176 L: 2038 D: 7087
http://tests.stockfishchess.org/tests/view/55a35cd40ebc590abbe1ba35

LTC 8MB
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 17732 W: 2870 L: 2745 D: 12117
http://tests.stockfishchess.org/tests/view/55a429d10ebc590abbe1ba5a

STC 16MB
LLR: 2.96 (-2.94,2.94) [-4.00,0.00]
Total: 17401 W: 3324 L: 3227 D: 10850
http://tests.stockfishchess.org/tests/view/55a489e60ebc590abbe1ba6a

This fixes an inconsistency bug where TT entries were valued differently depending on which pointer they were accessed through.  It should also qualify as a simplification.

### CODE REVIEW

**Comment by joergoster** [comment]
@mstembera Congrats!

**Comment by mcostalba** [comment]
The code you are going to remove was introduced here:

https://github.com/official-stockfish/Stockfish/commit/b366c7dc38145278a00c51a5

It is a 4 years ago commit, and was mostly related to cut-off upon a TT hit
even in PvNode, what currently we don't do anymore. So I don't see problems
with this patch.

**Comment by glinscott** [comment]
Looks good!

**Comment by zamar** [comment]
approved

**Pull request closed without merging**
