### PR TITLE
New default net nn-33c9d39e5eb6.nnue

### PR DESCRIPTION
**Pull request by vondele**
as the previous net, trained on Leela games, as provided by borg.
See also https://lczero.org/blog/2021/06/the-importance-of-open-data/

The particular data set, which is a mix of T60 and T74 data, is now available as a single binpack:
https://drive.google.com/file/d/1RFkQES3DpsiJqsOtUshENtzPfFgUmEff/view?usp=sharing

The training command was:
python train.py ../../training_data_pylon.binpack ../../training_data_pylon.binpack --gpus 1 --threads 2 --num-workers 2 --batch-size 16384 --progress_bar_refresh_rate 300 --smart-fen-skipping --random-fen-skipping 10 --features=HalfKAv2^   --lambda=1.0  --max_epochs=440 --seed $RANDOM --default_root_dir exp/run_2

passed STC:
https://tests.stockfishchess.org/tests/view/60c887cb457376eb8bcab054
LLR: 2.94 (-2.94,2.94) <-0.50,2.50>
Total: 12792 W: 1483 L: 1311 D: 9998
Ptnml(0-2): 62, 989, 4131, 1143, 71

passed LTC:
https://tests.stockfishchess.org/tests/view/60c8e5c4457376eb8bcab0f0
LLR: 2.95 (-2.94,2.94) <0.50,3.50>
Total: 11272 W: 601 L: 477 D: 10194
Ptnml(0-2): 9, 421, 4657, 535, 14

also had strong LTC performance against another strong net of the series:
https://tests.stockfishchess.org/tests/view/60c8c40d457376eb8bcab0c6

Bench: 5032320

### CODE REVIEW

**Comment by NightlyKing** [comment]
Congratulations! 

Excited to see if there's more elo in that data set. For now I concentrate on pure T74 data.

**Comment by vondele** [comment]
thanks, yes, I want to explore a bit as well, T60, T74, your mix, and your mix shuffled. Let's see what is the magic ingredient.

**Comment by snicolet** [comment]
merged via 8ec9e108664ce38fa98ccfb69f048d7d804f99f9, congrats :-)

Now we have to re-test all the other pull requests which passed Elo gaining bounds on the previous net?

**Comment by vondele** [comment]
yes, I think it would be wise to retest https://github.com/official-stockfish/Stockfish/pull/3556 also because it needs some additional code to deal correctly with the 'adjusted' flag.

**Pull request closed without merging**
