### PR TITLE
Update README.md

### LINKED ISSUE #4418: Docs request: default value and type of Skill Level, UCI_Elo, UCI_LimitStrength
### Describe the issue

From https://github.com/official-stockfish/Stockfish/issues/3358#issuecomment-781346012, I have gathered:
- `Skill Level: int`
- `UCI_Elo: int`
- `UCI_LimitStrength: bool = False`

It would be good to place this into the `README.md`.

### Expected behavior

It would be good for the `README.md` to detail the type and default values of each engine parameter.

### Steps to reproduce

n/a

### Anything else?

n/a

### Operating system

All

### Stockfish version

Stockfish 15.1

### PR DESCRIPTION
**Pull request by dav1312**
Update and simplify the readme, removing duplicated and outdated stuff and pointing to the new wiki

Closes #4418

No functional change

### CODE REVIEW

**Comment by vondele** [comment]
This looks good to me.

**Comment by dubslow** [comment]
I think it's an improvement over master, thanks Dave. I do think some further tweaks should be made as well.

Also, the UCI link points to a zip file, which is quite impractical. Perhaps it should be https://backscattering.de/chess/uci/, as in Discord.

**Comment by dubslow** [comment]
I've pushed my suggested further tweaks, and opened a PR into this branch (tho it was damned difficult due to useless Github UI). https://github.com/official-stockfish/Stockfish/commit/464a989a94871608214c4c422a071cfe4b2a13a8

For the record, the content removed from the README is now available in the wiki, correct?

**Comment by dav1312** [comment]
> For the record, the content removed from the README is now available in the wiki, correct?

Yes, I added all of that content to the wiki long time ago

**Comment by dav1312** [comment]
Should I add that Stockfish doesn't include a "chessboard" to be even more specific about not being a "complete chess program"?

**Comment by vondele** [comment]
maybe this can be reformulated indeed. For example, I don't think we should list GUIs there. Maybe something like 

`Stockfish is a free and strong UCI chess engine derived from Glaurung 2.1. Stockfish analyzes chess positions and computes optimal moves, however the Stockfish program does not include a graphical user interface (GUI) that is required to display a chessboard and to make it easy to input moves. These GUIs are developed independently from Stockfish and are available online. Read the documentation for your GUI of choice for information about how to use Stockfish with it.`

Consider to link directly to https://github.com/official-stockfish/Stockfish/wiki/Download-and-usage#download-stockfish under that paragraph, I assume it is the most important page.

**Comment by vondele** [comment]
Or maybe even more concise on the GUIs. Somehow, we shouldn't write more about what stockfish is not than about what it is :-)

**Comment by dav1312** [comment]
```
[Stockfish][website-link] is a **free and strong UCI chess engine** derived from
Glaurung 2.1 that analyzes chess positions and computes the optimal moves.

Stockfish **does not include a graphical user interface** (GUI) that is required
to display a chessboard and to make it easy to input moves. These GUIs are
developed independently from Stockfish and are available online. **Read the
documentation for your GUI** of choice for information about how to use
Stockfish with it.

See also the Stockfish [documentation][wiki-usage-link] for further usage help.
```

**Comment by vondele** [comment]
yes, please update in that way. I think this is about ready to merge.

**Pull request closed without merging**
