### PR TITLE
High res bench

### PR DESCRIPTION
**Pull request by Stefano80**
At the moment the command "bench 16 1 X default time" let the default fen file be analysed with X seconds for position. Is there a reason for this? I searched UCI specifications without success.

It seems much more reasonable to use milliseconds for resolution (in particular if one want to analyse automatically database of positions for tuning purposes).

### CODE REVIEW

**Comment by mcostalba** [comment]
Can you please provide a sensible example that shows msec is necessary?

**Comment by Stefano80** [comment]
You provided it yourself, actually. As I tried to implement, I noticed this problem. If you want to test endgame knowledge with tablebases for hundreds of positions on shallow depth, is actually more sensible to do it for a fixed time than for a fixed depth. And if you want to do it at say 100 ms (which on my desktop is depth 12+ in endgames), than you have to use python or bash scripts and pass all fens line by line (I did it for KPP KPP, no fun) and wait until the output is written.

Another alternative would be to replace:

limits.movetime = 1000 * atoi(limit.c_str());

by

limits.movetime = int(1000 * atof(limit.c_str()));

so to allow for floats without changing the interface.

**Comment by mcostalba** [comment]
Thx, actually also Uci uses milliseconds so it is also more consistent.

**Comment by erbsenzaehler** [comment]
You also have to change the pgo bench in makefile.

**Comment by Stefano80** [comment]
Thx, will do. A question as a git novice: if I now commit and push locally, will the pull request get updated?

**Comment by mcostalba** [comment]
Yes it will get updated.

**Comment by zamar** [comment]
It seems that stefano80 has updated the pull request with required PGO change. 
The change makes sense to me as sometimes millisecond precision is required for different kind of experiments.

Approved.

**Comment by glinscott** [comment]
Looks good!

**Pull request closed without merging**
