### PR TITLE
Annotate some branches in search with constexpr

### PR DESCRIPTION
**Pull request by swgillespie**
`if constexpr` is a C++17 hint that allows the compiler to enforce that the branch condition is itself `constexpr` and therefore known at the time of template instantiation. This commit annotates a few branches in `search` to be `if constexpr` as a hint to both the compiler and the reader.

As a side-effect, these annotations allow my compiler (gcc 9.4.0) to realize that stores to `maxValue` are dead in instantiations of `search` with `NonPV`, so this commit also annotates the declaration of `maxValue` with `[[maybe_unused]]` to suppress the compiler warnings that ensue. I would expect that "sufficiently smart" compilers would have figured out the const-ness of these branches anyway, but this hint is at least more explicit.

Bench before:
```
===========================
Total time (ms) : 2204
Nodes searched  : 3993611
Nodes/second    : 1811983
```

Bench after:

```
===========================
Total time (ms) : 2174
Nodes searched  : 3993611
Nodes/second    : 1836987
```

### CODE REVIEW

**Comment by Disservin** [comment]
For some more statistical proofs you can refer to the testing methods listed in the fishtest wiki.
[Fishtest Wiki#Speed-optimization](https://github.com/glinscott/fishtest/wiki/Creating-my-first-test#speed-optimization).
I also saw that you created a fishtest account so you can also launch a test there if you wish, the maintainer might require this.

**Comment by swgillespie** [comment]
>  I also saw that you created a fishtest account so you can also launch a test there if you wish, the maintainer might require this.

Great, I'll do that, my setup makes it a bit of a pain to run perf.

**Comment by swgillespie** [comment]
Fishtest STC: https://tests.stockfishchess.org/tests/view/631e3157b85daa436625eae7

**Comment by vondele** [comment]
the test failed, and in some of my (quick) local testing I actually see a slowdown. Could it be that the speedup is compiler version dependent?

**Comment by swgillespie** [comment]
yeah, maybe not. worth a shot!

**Pull request closed without merging**
