### PR TITLE
Use PieceToChar instead of switch

### PR DESCRIPTION
**Pull request by lucasart**
No functional change.

### CODE REVIEW

**Comment by lucasart** [comment]
Verified this with syzygy 5-men, as follows:
```
$ ./stockfish
Stockfish 100416 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
$ uci
...
uciok
$ setoption name SyzygyPath value /home/lucas/Chess/syzygy
info string Found 145 tablebases.
$ bench
...
Nodes searched  : 7378286
```
Same node count for both versions.

**Comment by mcostalba** [comment]
Sorry but I don't aknwoledge messing up Stocfish files to support TB.

TB should be _all_ self contained so pelase do copy PieceToChar into TB
code.

**Comment by lucasart** [comment]
@mcostalba: Messing up ? I just added one line of code in position.h, to make PieceToChar visible. I think PieceToChar is of general use, as it maps characters with Piece and PieceType. So it's not unreasonable to make it available to anyone compilation unit that includes position.h

TB self contained ? Are you kidding me ? TB code is actually full of SF specific code.

**Comment by mcostalba** [comment]
Please do copy PieceToChar in TB code. Thanks.

**Comment by lucasart** [comment]
@mcostalba: better now ?

**Comment by lucasart** [comment]
@mcostalba: Actually, I will close this pull request, and all other syzygy related ones. I will clean up syzygy code, and maintain a syzygy branch, and open a pull request when it's ready. The patch review/merge process is way too slow for this kind of work. I will need a hundred trivial patches like that...

**Comment by mcostalba** [comment]
@lucasart yes I think it is a better approach.

In case you want to dive into that mess I suggest to proceed function by
function, not in a traversal way as you are doing now, but start with one
function, fully clean that and proceed to the next: it is a much more
efficient process in case of terribly obfuscated code as is syzygy.

**Pull request closed without merging**
