### PR TITLE
Don't do unnecessary work during inference of affine transform layers when SIMD granularity allows for it.

### LINKED ISSUE #3352: Possible uninitialized variable read on inference with padded affine transform layers
The number of inputs of affine transform layers is padded with zeros to 32.

This causes two issues during inference for nets with affine transform layers that have kInputDimensions not being a multiple of 32.

1. Bug (at least for <AVX2) - While the weights are correctly padded with 0s, the output from the previous layer is not. For example here https://github.com/official-stockfish/Stockfish/blob/76daa88cf878b12a03755dc0550b3fa8e4d19cb1/src/nnue/layers/affine_transform.h#L333 with kInputDimensions of 16 will have the input_vector only having 16 values initialized. The second iteration will read the uninitialized part of the output of the previous layer. This might not be an issue for AVX2 and higher as the write to the output of a layer writes all 32 elements (with 16 high ones being 0). While it's technically accessing uninitialized memory it is multiplied by 0 and then added to the output, so it does not cause the result to become wrong.
2. Unoptimal code for <AVX2 - Since kPaddedInputDimensions is always >=32 it implies that even for layers with kInputDimensions == 16 the number of iterations is 2, while 1 would suffice. https://github.com/official-stockfish/Stockfish/blob/76daa88cf878b12a03755dc0550b3fa8e4d19cb1/src/nnue/layers/affine_transform.h#L326. Fixing this also solves the bug from 1.

### PR DESCRIPTION
**Pull request by Sopel97**
This patch changes affine transform inference code for architectures with `kSimdWidth < 32` and `kInputDimensions != 32` such that operations that would be exectured only on the zero padded weights are no longer executed. This improves the speed by avoiding unnecessary work and prevents reading of uninitialized values from the output of the previous layer, as described in the issue #3352.

Fixes #3352.
Suggestions of how to proceed with this change are welcome, since it only affects processor architectures that are a minority on fishtest and network architectures different from the default one.

### CODE REVIEW

**Comment by vondele** [comment]
as discussed on discord, this fixes some undefined behaviour and valgrind warnings for different archs (like 512x16), so we want it in. Might be useful in the future. I verified valgrind errors are fixed, and wait for STC non-regression to finish.

**Comment by Sopel97** [comment]
The test https://tests.stockfishchess.org/tests/view/602935797f517a561bc4997d indicates a possible slowdown, which is interesting because the AVX2 path didn't really change.

**Comment by Sopel97** [comment]
An alternative, less complicated fix could be considered. It would be enough to fill the buffer defined here https://github.com/official-stockfish/Stockfish/blob/40cb0f076a62115af030c4524825d9ba73d61023/src/nnue/evaluate_nnue.cpp#L124 with zeroes. This buffer is not very large so it might not impact the speed measurable. It would also allow us to keep the current implementation which is easier to maintain.

**Comment by snicolet** [comment]
So something like that:
```
   alignas(alignment) char buffer[Network::kBufferSize] = {0};
```

While we're at it, wouldn't it be a good idea to initialize also the the array for the other code path? And also the `transformed_features` array?

```
#if defined(ALIGNAS_ON_STACK_VARIABLES_BROKEN)
    TransformedFeatureType transformed_features_unaligned[
      FeatureTransformer::kBufferSize + alignment / sizeof(TransformedFeatureType)] = {0};
    char buffer_unaligned[Network::kBufferSize + alignment] = {0};

    auto* transformed_features = align_ptr_up<alignment>(&transformed_features_unaligned[0]);
    auto* buffer = align_ptr_up<alignment>(&buffer_unaligned[0]);
#else
    alignas(alignment)
      TransformedFeatureType transformed_features[FeatureTransformer::kBufferSize] = {0};
    alignas(alignment) char buffer[Network::kBufferSize] = {0};
#endif
```

**Comment by Sopel97** [comment]
The feature transformer arrays don't need to be initialized. The other code path needs to be modified too, yes.

**Comment by snicolet** [comment]
The version with only the buffer initialization with `= {0}` also failed non-regression bounds:
https://tests.stockfishchess.org/tests/view/603218987f517a561bc49f15

**Comment by Sopel97** [comment]
In this case I'll leave this PR hanging until it's actually needed.

**Comment by snicolet** [comment]
Probably better, yes. 
Probably means that the future 512x16 architectures will have to overcome this ~1 Elo speed handicap to compile without warnings

**Comment by Sopel97** [comment]
I've applied a different fix that should not impact the current codepaths (on compilation level). This involves using `InputDimensions` instead of `PaddedInputDimensions` for the actual iteration (and places more restrictions on allowed `InputDimensions`, but since the layout for >=SSSE3 changed we can do this for any reasonable arch.); and adding a special ClippedReLU path for when AVX2 is used but there's only 16 inputs.

**Comment by Sopel97** [comment]
this is now reduntant

**Pull request closed without merging**
