### PR TITLE
Remove moveMalus

### PR DESCRIPTION
**Pull request by TarasVuk**
Passed STC:
LLR: 3.15 (-2.94,2.94) <-1.75,0.25>
Total: 123008 W: 30973 L: 30831 D: 61204
Ptnml(0-2): 368, 14032, 32568, 14162, 374
https://tests.stockfishchess.org/tests/view/656e0bb86980e15f69c763fa

No functional change

### CODE REVIEW

**Review by Disservin — CHANGES_REQUESTED** [review]
can you run a ltc simplification test as well?

**Comment by cj5716** [comment]
no LTC required, because now quietMoveMalus = stat_malus(depth)

**Comment by peregrineshahin** [comment]
Yeah probably this only applies after this recent one https://github.com/official-stockfish/Stockfish/commit/7dc40ac6437ec96d312e387b76573e5c496bd0b6

> no LTC required, because now quietMoveMalus = stat_malus(depth)
> 
> so it simplified to
> 
> ```
> int moveMalus = bestValue > beta + 168 ? stat_malus(depth)  // larger malus
>                                        : stat_malus(depth);  // smaller malus
> ```

**Review by Disservin — APPROVED** [review]

**Comment by Disservin** [comment]
> no LTC required, because now quietMoveMalus = stat_malus(depth)
> 
> so it simplified to
> 
> ```
> int moveMalus = bestValue > beta + 168 ? stat_malus(depth)  // larger malus
>                                        : stat_malus(depth);  // smaller malus
> ```

Ah thanks I missed the fact that the bonus is now the same ty

**Pull request closed without merging**
