### PR TITLE
Adjust `improving` bound by `depth` + param tweaks

### PR DESCRIPTION
**Pull request by FauziAkram**
Param tweaks by @FauziAkram building on the `improving` idea of @XInTheDark and @Vizvezdenec

Passed STC: https://tests.stockfishchess.org/tests/view/63d14b41721fe2bff6929dfc
LLR: 2.94 (-2.94,2.94) <0.00,2.00>
Total: 117240 W: 31216 L: 30796 D: 55228
Ptnml(0-2): 331, 12817, 31927, 13191, 354

Passed LTC: https://tests.stockfishchess.org/tests/view/63d255db721fe2bff692cdf9
LLR: 2.94 (-2.94,2.94) <0.50,2.50>
Total: 166056 W: 44347 L: 43799 D: 77910
Ptnml(0-2): 68, 15987, 50368, 16539, 66

bench 4178044

### CODE REVIEW

**Comment by cngstefan** [comment]
This PR contains the small code change `improving = improvement > depth - 3;` combined with a massive tuning. This is dangerous because we have a good chance that the unrelated tuning gives the real elo and the new code have no or even a negative effect. So it should be tested if the tuned params alone pass the tests.

**Comment by locutus2** [comment]
This PR contains the small code change improving = improvement > depth - 3; combined with a massive tuning. This is dangerous because we have a good chance that the unrelated tuning gives the real elo and the new code have no or even a negative effect. So it should be tested if the tuned params alone pass the tests.

**Comment by mstembera** [comment]
Congrats!  Also this tune combines search and classical eval parameters.  Since the classical eval parameters play only a very small role with NNUE=true it may be easy to actually detune them while the whole still passes.  Would it at least be worth it to see if it can pass w/o the classical parameters perhaps directly to LTC?  Maintainer decision of course.

**Comment by XInTheDark** [comment]
Congrats on this success! 🎉

**Comment by dubslow** [comment]
> This PR contains the small code change improving = improvement > depth - 3; combined with a massive tuning. This is dangerous because we have a good chance that the unrelated tuning gives the real elo and the new code have no or even a negative effect. So it should be tested if the tuned params alone pass the tests.

This is what simplifications are for, are they not? Whether or not this change is neutral or negative, the fact is we have the passer now. We should simply commit the passer now, and if indeed we suspect one part to be neutral or negative, then reverting that alone will pass simplification bounds.

In other words, as far as I can see, the Stockfish process is already designed to handle this concern.

> Congrats! Also this tune combines search and classical eval parameters. Since the classical eval parameters play only a very small role with NNUE=true it may be easy to actually detune them while the whole still passes. Would it at least be worth it to see if it can pass w/o the classical parameters perhaps directly to LTC? Maintainer decision of course.

The history of the last year suggests that classical param tweaks are just fine, or at least, not a show-stopper for passers. Hardly the first time Fauzi has made a patch like this.

**Comment by mstembera** [comment]
@dubslow When we released SF 15 it was stronger w/ NNUE=false than the last SF classic version before NNUE by about 12 elo. 
See https://github.com/official-stockfish/Stockfish/pull/3986#issuecomment-1104618134  If you look at the current match at https://www.chess.com/computer-chess-championship you will see that the opposite is now true.

**Comment by locutus2** [comment]
@dubslow 
Sorry, this is not a simplification. The point is that everybody could simply make some random code which he want to be in SF (and which is not to bad) and do a massive unrelated tuning to push this over the elo bounds. That is not a procedure we supported in the past. One of our base rule is that a code addition has to be should gain elo by itself. A tuning (autoamtic or manual) for directly related constants or compensations is normal but not changeing also unrelated stuff because that masks the real gain of a idea. So the general question is if we now see this workflow as acceptable or not.

The other ways would be commit this and then try immediatly simply away the non-tuning part.

**Comment by dubslow** [comment]
> When we released SF 15 it was stronger w/ NNUE=false than the last SF classic version before NNUE by about 12 elo. See https://github.com/official-stockfish/Stockfish/pull/3986#issuecomment-1104618134 If you look at the current match at https://www.chess.com/computer-chess-championship#event=stockfish-classic-vs-stockfish-no-nnue you will see that the opposite is now true.

1) Those fishtest results were contradicted by external tests, so I don't think we should be worrying too much about CCC results when they contradict fishtest 

2) who even cares anyways? the `master` commit history in the last year has several instances of patches much like this one being merged. Our goal isn't to improve `UseNNUE=off` performance, since doing that conflicts with improving NNUE performance.

> Sorry, this is not a simplification.

No one said it was.

> That is not a procedure we supported in the past.

The commit history of `master` in the last year says that this is normal procedure, as far as I'm aware. Half a dozen others like this one have been merged with little fuss.

> The other ways would be commit this and then try immediatly simply away the non-tuning part.

Exactly as I suggested in my previous comment, and as is already the precedent.

**Comment by FauziAkram** [comment]
@locutus @cngstefan
To answer you quickly, the tuned parameters alone were tested, but did not passed LTC:
https://tests.stockfishchess.org/tests/view/63d107d6721fe2bff69291c7

So the Elo gain in this patch theoretically should come from both the main idea itself and the tuning.

**Comment by locutus2** [comment]
@dubslow 
I have checked all master commits from 01.01.2022 until now and there exists exactly 2 commits which fall in the same category:
https://github.com/official-stockfish/Stockfish/commit/98965c139df1483a3d684ee8bc7a60dc4b95efa1
https://github.com/official-stockfish/Stockfish/commit/39af98c807d236b6511b6e399caf40102398900c

The second is the reintroduction of a variation of the first one after a revert. So its not common. I wouldn't had merged this PRs but its seems we handle this a little bit sloppy (but that up to the maintainers). 

Some quote from the testing guidelines (https://github.com/glinscott/fishtest/wiki/Creating-my-first-test) from the parameter tweaks section and combo patches:
**"Each patch shall be trivial, like a parameter tweak. Patches that add/remove a concept/idea/feature shall pass individually."**
That is like we handles it mostly till 2013 (perhaps there are some exceptions).

But as said probably this has to be discussed and clarified for the future because my main point of pushing random changes over the bounds still stands.

**Comment by dubslow** [comment]
I see also 8bab09749dd009

(Examples of tweaking HCE params:
c25d4c488 
45f2416d)

**Comment by locutus2** [comment]
@dubslow 
Thank you i have overlooked https://github.com/official-stockfish/Stockfish/commit/8bab09749dd00951bfa9c5f89f6e35bded76c8a9.

But the two others are pure tunings, no code was added, so have nothing todo with the topic.

The overlooked changes only two unrelated params, so the chance that this alone would pass is less likely.

Again my main point is if we use tuning of very much variables this has really good chance that the tuned values alone are enough independent of a combined neutral code.

so make a massive tuning (even perhaps LTC), the two standard tests and then a simplifcation tests to verify we doesn't introduce useless code with seems much afford for this IMHO. I'am a fan of a more conserative approach (perhaps I'am becoming old ;-), i have not so many time and leasure to work at stockfish as in the early years). Some insights of the current maintainer would be nice @vondele.

**Comment by dubslow** [comment]
> Again my main point is if we use tuning of very much variables this has really good chance that the tuned values alone are enough independent of a combined neutral code.

I sympathize with this concern. At any rate, as per Fauzi, we've already confirmed that in this case, the tuned values alone are not enough.

I cannot speak to what the maintainers might choose in the future. If it were me, I would not be so concerned. Testing the simplification post-facto requires no more resources than independently testing the change and the tweaks pre-facto. The end result is the same, with the same resources, in either case.

**Comment by Vizvezdenec** [comment]
Well I think this is an okay thing to do since progress is pretty slow - stockfish is becoming so good that idea may need some surrounding tuning to pass even if it's gaining but somewhat overshadowed by everything else.

**Comment by mstembera** [comment]
I don't see that any of the commits mentioned above mix classical eval and search tune parameters.  This is for a good reason.  Since testing with NNUE=true is rather insensitive to changes in classical eval you can easily have bad HCE changes slip in without noticing.  As long as we have classical eval we should not nerf it.  Parameters can't be "simplified" back.  This is not in contradiction to NNUE being the priority.

**Comment by FauziAkram** [comment]
> I don't see that any of the commits mentioned above mix classical eval and search tune parameters. This is for a good reason. Since testing with NNUE=true is rather insensitive to changes in classical eval you can easily have bad HCE changes slip in without noticing. As long as we have classical eval we should not nerf it. Parameters can't be "simplified" back. This is not in contradiction to NNUE being the priority.

If this is the main concern, I will now launch a test without the classical tweaks, directly at LTC.
If it passes, we can open a new PR.
If it doesn't pass, then we stick to this patch.

**Comment by dubslow** [comment]
> I don't see that any of the commits mentioned above mix classical eval and search tune parameters. 

Did you miss the part where I mentioned two of these?

**Comment by dubslow** [comment]
Those two patches indeed mixed classical and NNUE parameter tweaks, and were accepted without fuss.

**Comment by mstembera** [comment]
Looking at the paused test it seems way too early to conclude what will happen.  It's related to an open PR so I don't think it's a waste of resource.  I would like to resume it if you don't object.

**Comment by fanzier** [comment]
Aside: In general, I don't get the point of stopping tests early. Isn't the point of SPRT that it uses statistical methods to decide when to stop a test (rather than a human having a "feeling" it should be stopped)?

**Comment by vondele** [comment]
So, let's see what happens with the submitted test. 

In general, I don't think it is a good idea to tune both classical and nnue and search parameters in addition to a code change.

**Comment by FauziAkram** [comment]
The test without the classical changes didn't pass, with the following result:
https://tests.stockfishchess.org/tests/live_elo/63d986b8bbadd17b3787c3ea
Elo: 0.11
@vondele

**Comment by dubslow** [comment]
I guess I see three obvious choices:

1) Accept this PR as is

2) Do another followup test (expensive) (either duplicate original LTC passer or...?)

3) Reject this PR

My preference is as ordered, 1 > 2 > 3. I'd rather just see it merged, and if maintainers want to impose a new moratorium on classical tweaks, then do that after accepting this.

**Comment by vondele** [comment]
closing, as this mixes parameters in search, nnue eval and classical eval with a code change. Has now become outdated as well.

**Comment by dubslow** [comment]
> mixes parameters in search, nnue eval and classical eval

is this now forbidden? just want to be clear here

**Comment by vondele** [comment]
it is not encouraged. For a 20 Elo patch, bending rules is definitely on the table.

**Comment by FauziAkram** [comment]
@dubslow Vondele informed me that mixing 3 elements together is a little too much, in this case:
1) New code
2) Pure Classical Parameters
3) Search Parameters

So he confirmed to me that any patch that has only two elements is ok, for example:
1) New code
2) Search Parameters

@vondele Can you please confirm.

**Pull request closed without merging**
