### PR TITLE
Prepare PSQT for tuning

### PR DESCRIPTION
**Pull request by lucasart**
The way the code is designed currently is not very tuning friendly. In order to
tune the PSQT, one first has to rearrange it and write some boiler plate code,
very much like this patch.

No functional change.

### CODE REVIEW

**Comment by lucasart** [comment]
To tune the PSQT, simply add in psqtab.cpp: `TUNE(Bonus, PSQT::init());`

**Comment by mcostalba** [comment]
Please don't introduce another file...

**Comment by lucasart** [comment]
@mcostalba: if I leave the table in psqtab.h, it has to be statically linked, which prevents tuning it. Do you have a better solution ?
Despite the line count, this patch adds no actual code, merely a proper structure (namespace with init function).

**Comment by mcostalba** [comment]
Yes, this one:

https://github.com/mcostalba/Stockfish/commit/psq_init

**Comment by lucasart** [comment]
Can you explain what is the logic of:
* putting the PSQT namespace in position.*, when the PSQT array is in psqtab.h ?
* putting the psq array in the anonymous namespace of position.cpp, instead of in PSQT namespace where it belongs ?

Also, can you also introduce the file symmetry in your patch?

**Comment by lucasart** [comment]
Another problem is the use of `static`. It means that every compilation unit has its own PsqTable array. So, when you write `TUNE(PsqTable, PSQT::init())` in position.cpp, you are generating options that will modify the PsqTable of position.cpp only. If another compilation unit includes psqtab.h, and uses it, it will not be modified by the UCI options generated. So that leaves room for subtle bugs, which is why I prefer the table to be defined in a **source** file, not in a header file.

**Comment by mcostalba** [comment]
Yes, static should be dropped. Regarding your other comments: only init() should have wide visibility for tuning, psq should never used directly for tuning, if it is needed for other reasons, like move ordering then it is enough to write where needed:

   namesapce PSQT {
      extern Score psq[COLOR_NB][PIECE_TYPE_NB][SQUARE_NB];
   }

And then access it, because namespaces items have global linkage.

I have updated my patch, please reload and have a look:

https://github.com/mcostalba/Stockfish/commit/psq_init

**Comment by lucasart** [comment]
It's much better except for this part:

    // WARNING: This file must be included only once, where PSQT::init() is defined.

psqtab.h is included by several compilation units already.

**Comment by lucasart** [comment]
really the table has to be in a source file, and the obvious choice would be psqtab.cpp.

**Comment by lucasart** [comment]
sorry psqtab.h is included only once, by position.cpp, so it works. it's awkward to prevent a header from being included several times though.

**Comment by mcostalba** [comment]
The theoretical correct implementation _would_ be to defne a class PSQT and
make BaseTable[] a private (static) member, while psq would be a public
(static) member. So that you can write all in psqtab.h header and include
it how much you want.

But I think this scheme would introduce a little slowdown because do_move()
is really performance critical, moreover it is a lot more code. So current
solution is the best compromise IMO...anyhow I will write something along
those lines, just to see how it turns out.

**Comment by mcostalba** [comment]
No luck!  I can define a static data member only of literal type (ie. not an array)

http://stackoverflow.com/questions/19744917/static-member-initialization-not-working-with-gcc-even-with-c11-enabled
http://www.stroustrup.com/bs_faq2.html#in-class

**Comment by lucasart** [comment]
You're creating problems for yourself, and then trying to find some super complicated solution to solve it. All that because you don't want to accept the obvious, that the PSQ table belongs in a **source** file, not a header file. If you really don't want to add a new file (I still don't understand why), then you could put it in position.cpp.

Also, you forgot the file symmetrization from my patch.

**Comment by mcostalba** [comment]
After pondering again on it, I admit you are right, the correct solution is to put the definition in a *.cpp file.

I have reworked your patch, split in 2 logic commits and open a pull request:

https://github.com/official-stockfish/Stockfish/pull/343

I suggest to pull form there and close this one.

**Comment by lucasart** [comment]
perfect!

**Pull request closed without merging**
