### PR TITLE
Cache SEE value: take 2

### PR DESCRIPTION
**Pull request by mcostalba**
This time use a per-thread hash with 256 entries
and cacth almost 30% of cases.

WARNING: at the moment it is a functional change,
but I have no time to further debug now :-)

**Updated: it is fixed now!**

### CODE REVIEW

**Comment by mcostalba** [comment]
Second attempt, even more general solution...

**Comment by gogamoga1** [comment]
2 PGO

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1649977   1676871   -26894    
    StDev   17788     11093     9141      

p-value: 0,998
speedup: 0,016

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1632845   1655579   -22734    
    StDev   14165     14159     9941      

p-value: 0,989
speedup: 0,014


**≈ +1,5%**

**Comment by mcostalba** [comment]
Ok, now it is fixed, could you please speed test this one?

Thanks

**Comment by mcostalba** [comment]
Here is my test, standard build:

./pyshbench ./stockfish_ms ./stockfish_see 10
run       base       test     diff
  1    1284915    1301873   +16958
  2    1267343    1319568   +52225
  3    1290065    1317862   +27797
  4    1290609    1291700    +1091
  5    1293612    1305764   +12152
  6    1283567    1302150   +18583
  7    1279272    1310239   +30967
  8    1112845    1126372   +13527
  9    1276868    1305206   +28338
 10    1291427    1296904    +5477

Result of  10 runs
==================
base =    1267052  +/- 33900
test =    1287764  +/- 35496
diff =     +20712  +/- 9150

speedup        = +0.0163
P(speedup > 0) =  1.0000

CPU: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz

**Comment by gogamoga1** [comment]
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1648642   1643936   4706      
    StDev   12706     12033     7416      

p-value: 0,263
speedup: -0,003

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1645386   1642053   3333      
    StDev   9653      11559     6726      

p-value: 0,31
speedup: -0,002

**Comment by mcostalba** [comment]
My tests were PGO builds, notnormal builds, sorry for teh confuions.

Results of @gogamoga1 show once again that bench speed tests are _really_ unreliable...we need something better. I will run my patch in fishtest with SPRT[0, 5] at LTC.

**Comment by nabildanial** [comment]
@mcostalba You mean STC, right? Because that's what you wrote in the wiki.

A little off topic but, I remember that I once questioned the team why we aren't using the fishtest for speedup patches like this, and Joona stated that the fishtest is not accurate for this, and the bench speedtests are the accurate ones. Do you agree with the statement?

**Comment by Yery** [comment]
Also could not measure a speedup. (Now with the new PGO build, the builds are much faster, so I wonder if the PGO's are less accurate? Longer PGO time should lead to more stable results. I understand the logic behind fixed depth, but perhaps that depth should be deeper).

`Results for 50 tests for each version:

            Base      Test      Diff      
    Mean    1811716   1793319   18397     
    StDev   24498     24264     4232      

p-value: 0
speedup: -0,01`

**Comment by ErnstDoerfert** [comment]
[0, 5] seems to me a bit exaggerated for a non-functional patch. Basically, this is a kind of tuning - not of parameters but of code. Isn't it?

**Comment by mcostalba** [comment]
Please check the patch and then tell me if it resembles a tuning to you.

**Comment by mcostalba** [comment]
@snicolet thanks.

Also fishtest failed. I am closing this now.

**Pull request closed without merging**
