### PR TITLE
Numa fixes

### PR DESCRIPTION
**Pull request by vondele**
test various PRs combined.

### CODE REVIEW

**Comment by Disservin** [comment]
merged

**Comment by mstembera** [comment]
Does TCEC and CCC know what settings to use with the latest NUMA patches?

**Comment by dubslow** [comment]
numafish is already playing the alt final at C.CCCC. AGE said it's just `auto`, no human config, and no particular noticeable speedup.

**Comment by mstembera** [comment]
> numafish is already playing the alt final at C.CCCC. AGE said it's just `auto`, no human config, and no particular noticeable speedup.

Right but is auto what we want there?

**Comment by dubslow** [comment]
as i wrote that, age decided to pause the alt final and do a bit of testing of `auto` vs `normal`.

(i cant comment on what we *want*, but my impression of skimming all the convos was that auto should pretty much do the right thing in most circumstances. further will have to involve age and people who know what they're talking about with the numa patch)

**Comment by dubslow** [comment]
> AGEthereal: Non NUMA version looking faster 
LUL
> AGEthereal: 250th 16GB go movetime 60000
> AGEthereal: Default ("auto" for Numa) 96248318
> AGEthereal: None ("none" for Numa) 94108169
> AGEthereal: could run a few more times and I imagine they stay very close together.
> AGEthereal: eyeball stats, but anything less than like 10% is hard to distingush from noise.
> AGEthereal: Repeating with 125 threads

**Comment by mstembera** [comment]
ok.  ```system``` is another option i believe.

**Comment by dubslow** [comment]
AGE confirms that auto/system did exactly what he would have done manually anyways:

> AGEthereal: [...] which matches what I would have done manually.
> AGEthereal: Stockfish indicated how it distributed the threads amongst the 2 numa nodes on the machine.
> AGEthereal: It was clear that they were evenly split 125/125 between the nodes; and 63/62 when doing the 125-thread test.

**Comment by Sopel97** [comment]
The `auto` setting will default to `system` in these conditions, so no changes needed.

**Pull request closed without merging**
