### PR TITLE
Update default net to nn-3678835b1d3d.nnue

### PR DESCRIPTION
**Pull request by vondele**
new net trained with nnue-pytorch, started from the master net on a data set of Leela (T60.binpack+T74.binpack)
and Stockfish data (wrongIsRight_nodes5000pv2.binpack), available as a single interleaved binpack:
https://drive.google.com/file/d/12uWZIA3F2cNbraAzQNb1jgf3tq_6HkTr/view?usp=sharing

The nnue-pytorch branch used is https://github.com/vondele/nnue-pytorch/tree/wdl, which has the new feature to
filter positions based on the likelihood of the current evaluation leading to the game outcome.
It should make it less likely to try to learn from misevaluated positions. Standard options have been used:
   --gpus 1 --threads 4 --num-workers 4 --batch-size 16384 --progress_bar_refresh_rate 300
   --smart-fen-skipping --random-fen-skipping 12 --features=HalfKAv2_hm^   --lambda=1.0
starting from the master net.

testing with games shows neutral Elo at STC, and good performance at LTC:

STC:
https://tests.stockfishchess.org/tests/view/619eb597c0a4ea18ba95a4dc
ELO: -0.44 +-1.8 (95%) LOS: 31.2%
Total: 40000 W: 10447 L: 10498 D: 19055
Ptnml(0-2): 254, 4576, 10260, 4787, 123

LTC:
https://tests.stockfishchess.org/tests/view/619f6e87c0a4ea18ba95a53f
ELO: 3.30 +-1.8 (95%) LOS: 100.0%
Total: 33062 W: 8560 L: 8246 D: 16256
Ptnml(0-2): 54, 3358, 9352, 3754, 13

passed LTC SPRT:
https://tests.stockfishchess.org/tests/view/61a0864e8967bbf894416e65
LLR: 2.94 (-2.94,2.94) <0.50,3.00>
Total: 29376 W: 7663 L: 7396 D: 14317
Ptnml(0-2): 67, 3017, 8205, 3380, 19

Bench: 7011501

### CODE REVIEW

**Comment by snicolet** [comment]
Merged via 9ee58dc7a75d7cdc09935f8782e927bb19700afe, congrats :-)

Note: I'll re-open and leave this pull request open a little bit longer, so that we can get feedback and discussion in the PR for your new filtering scheme and net training method, for future reference!

**Comment by snicolet** [comment]
Btw that's another Elo-gaining patch  (after the Optimism patch) which has lot more pairs which are double-losses compared to the number of double-wins. Of course this is compensated by a lot more wins overall — so probably the new net plays a little bit riskier, which is nice :-)

**Comment by mstembera** [comment]
Congrats!  
Just a curious question..  When I see SF play LC0 at TCEC or CCC the LC0 evals are consistently about 2x lower.   Do you therefore double or otherwise adjust the LC0 data before training on it so the net doesn't get confused by the different relative scaling?

**Comment by vondele** [comment]
We asked this today, the tool made by the leela devs to convert the data has an 'sf compatible' eval that is being: a fit from lc0 to sf scores from https://github.com/LeelaChessZero/lc0/pull/1477/commits/9e69f7c70062e93b8a45ffd8f11eb338926809ce https://github.com/LeelaChessZero/lc0/pull/1477/commits/9e69f7c70062e93b8a45ffd8f11eb338926809ce

**Comment by vondele** [comment]
closing this one now, as we have a new net PR ready #3816

**Pull request closed without merging**
