### PR TITLE
LMR_Captures

### PR DESCRIPTION
**Pull request by VoyagerOne**
Do LMR on captures

STC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 5361 W: 1086 L: 936 D: 3339
http://tests.stockfishchess.org/tests/view/57b31b0f0ebc591c761f643d

LTC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 54694 W: 7591 L: 7287 D: 39816
http://tests.stockfishchess.org/tests/view/57b3442b0ebc591c761f6450

### CODE REVIEW

**Comment by DamasClasicas** [comment]
Congratulations!!

**Comment by MichaelB7** [comment]
Sweet!

**Comment by sf-x** [comment]
This patch is TC sensitive (the first patch also passed STC very quickly but failed LTC).
Good quiet moves will eventually build up good history to get sorted up in the move list; captures, however, are sorted the same way regardless of depth, and so e.g. sacrifices will always get reduced when there's enough quiet moves. I'm afraid this patch will be a regression at even longer time controls.

**Comment by jhellis3** [comment]
Well.... moveCountPruning can only be true up to depth 15, so I doubt it will hurt matters terribly.  I'm a bit more concerned about possibly LMRing promotions (as SF doesn't respond well to that in my experience).

**Comment by lucasart** [comment]
There seems to be very strong diminishing returns between STC and LTC. This is also evidenced by other tests, on the same topic (that passed STC easily and failed LTC convincingly).

**Comment by mcostalba** [comment]
Merged with 8493c8c6b8da07

**Pull request closed without merging**
