### PR TITLE
Switch time management to 64-bit resolution

### PR DESCRIPTION
**Pull request by WOnder93**
Fixes issue #1498.

No functional change.

### CODE REVIEW

**Comment by lucasart** [comment]
I don't understand why we need 64 bit here.

And I dont like using unsigned arithmetic for no reason like here. See the code to handle underflow ? It just makes the code ugly and error prone for no reason. If we really 64 bit, I prefer using signed 64-bit.

**Comment by vondele** [comment]
@lucasart people report things like
```
info depth 63 seldepth 85 multipv 1 score cp 25 nodes 9873202161268 nps 0 tbhits 0 time -1598630131 pv g1f3 d7d5 g2g3 g7g6 d2d4 g8f6 f1g2 f8g7 e1g1 e8g8 c2c4 c7c5 d4c5 d5c4 b1a3 c4c3 a3b5 d8a5 b5c3 a5c5 f3d4 c5e5 d4b3 b8c6 c1f4 e5h5 e2e4 c8g4 f2f3 g4e6 d1c1 e6b3 a2b3 c6d4 a1a4 h5c5 f4e3 e7e5 a4c4 c5e7 e3d4 e5d4 c3d1 f6d7 d1f2 d7b6 c4c7 e7b4 f3f4 b4b3 c1d1 b3d1 f1d1 f8c8 c7c8 a8c8 e4e5 g7f8 g2b7 c8c2 f2e4 b6c4 b2b4 c4e3 e4f6 g8g7 d1d4 c2b2 d4d7 f8b4 b7f3 b2b1 g1f2
```
which would be fixed by this I assume.

**Comment by WOnder93** [comment]
@lucasart I could make `callsCnt` signed but the only reason why it would need to be is to allow the useless decrement to -1, which seems to be a rather weak reason to me.

Note that we already count nodes searched using an `uint64_t` and thus it makes sense for limits for nodes to be of the same type.

**Comment by snicolet** [comment]
My views on the subject:

• `callCnt` : I propose to keep it signed, as comparing to zero in that context is more natural than comparing to 1, and might well be faster too on most processors.
• passing the timer to 64 bits: yes. The best solution, if it is possible, would to change the TimePoint type itself to use a 64 bits signed integer, and then defining all the time variables to be of that type.

Is that possible with something like the following?
`````
   using TimePoint = std::chrono::duration<int64_t>;
````

**Comment by syzygy1** [comment]
Isn't it more logical to consistently use the TimePoint type instead of mixing TimePoint with int64_t or uint64_t (or with int as is currently the case)?

According to [http://en.cppreference.com/w/cpp/chrono/duration](url), std::chrono::milliseconds is a signed integer type of at least 45 bits. So it will probably be a 64-bit int in practice and in any event cover at least 2^44 milliseconds, which is more than 200,000 days instead of the less than 25 days covered by the current signed 32-bit int.

I agree with @lucasart that it is easier to stick to signed integers here. When you are comparing and subtracting unsigned numbers, it is easy to introduce errors.

**Comment by WOnder93** [comment]
Indeed, as @syzygy1 says, the compiler will already pick the right type for TimePoint automatically. All we need to do is to ensure that all related variables are of a sufficiently large type (and `[u]int64_t` is the safe choice here).

Since there is so much backlash against unsignedness (is that even a word?), I will try to switch it all to `int64_t` when I have time.

**Comment by WOnder93** [comment]
> Since there is so much backlash against unsignedness (is that even a word?), I will try to switch it all to `int64_t` when I have time.

OK, done. I switched also all node counters for consistency and cleaner comparison code. The range should be still more than enough, even if it is now 2^63 instead of 2^64...

**Comment by snicolet** [comment]
I have proposed another pull request there: https://github.com/official-stockfish/Stockfish/pull/1510 with a code very similar to your, but (1) using TimePoint everywhere and (2) not changing the node counter at all.

Please review, and tell me if I have forgotten anything :-)

**Comment by snicolet** [comment]
Closing this first PR about time management, as it seems to me that the solution in https://github.com/official-stockfish/Stockfish/pull/1510 is somewhat cleaner.

**Pull request closed without merging**
