### PR TITLE
Prune dangerous moves at low depth

### PR DESCRIPTION
**Pull request by ajithcj**
At very low depths prune captures, promotions and checks if see is negative.

STC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 6772 W: 1328 L: 1173 D: 4271

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 8917 W: 1270 L: 1122 D: 6525

### CODE REVIEW

**Comment by jcalovski** [comment]
Amazing

**Comment by anshulongithub** [comment]
Amazing Amazing patch this just made my day!!! awesome may SF rule the world of chess forever and for always :)

**Comment by anshulongithub** [comment]
Before this gets committed in i want Ajithc and Locutus2 to confirm if conditions that were removed from the original patch can INDEED be safely removed. here's a little analysis:
1. ( captureOrPromotion || givesCheck || pos.advanced_pawn_push(move)) == if at least one is true
2. (!captureOrPromotion && !givesCheck && !pos.advanced_pawn_push(move)) ==
!(captureOrPromotion && givesCheck && pos.advanced_pawn_push(move)) == not (if all is true)it’s not equivalent.  it’s only equivalent when there is a mix of true and false.  However when there are all true or all false it’ll mess up
Scenario: if all parameters is true
 1. will return true (true || true || true) = true
 2. will return false (!true && !true && !true) == false

Scenario: if all parameters is false
 1. will return true (false || false || false) = false
 2. will return false (!false &&  !false && !false) == true

Can we confirm if its safe to remove the conditions from the original patch that passed?

**Comment by gamander** [comment]
The latest version of this patch happens to work like the original patch but will cause bugs if a new condition is added to the if branch. Because the else-if branch never checks if captureOrPromotion || givesCheck || pos.advanced_pawn_push(move) is actually true. Assuming one of these conditions needs to be true.

The version given by locutus2 above seems safer.

**Comment by DamasClasicas** [comment]
Amazing patch!! Congratulations!!!

**Comment by anshulongithub** [comment]
Maintainers, developers, @mcostalba please advise, my understanding is that the original conditions shud be put back as it makes the conditions explicit in the else if part of the code and will be easier for the future developers to understand, it will be more readable, and it won't cause any unnecessary bugs as highlighted by @gamander

**Comment by DU-jdto** [comment]
@anshulongithub It is not the case that (!A && !B && !C) <=> !(A && B && C). Rather, (!A && !B && !C) <=> !(A || B || C).

I'd probably leave in the removed condition, but comment it out.

**Comment by lp--** [comment]
Congrats!

@snicolet: Nope! this one was faster http://tests.stockfishchess.org/tests/view/5796ee640ebc591c761f5b00 :)
Seriously though, there were some patches before passing in 4k-6k games. And highest elo gain is probably lazy smp patch

**Comment by arunsathya1309** [comment]
Sorry i think you should not remove the following condition

	      && (  captureOrPromotion
-		  || givesCheck
-		  || pos.advanced_pawn_push(move)
-		  )
-	

it shud either be in top level if ....

**Comment by arunsathya1309** [comment]
if ( !rootNode
&& !inCheck
&& bestValue > VALUE_MATED_IN_MAX_PLY)
{
if(!captureOrPromotion
&& !givesCheck
&& !pos.advanced_pawn_push(move))
{
.....
}
else if(depth < 3 * ONE_PLY
&& pos.see_sign(move) < VALUE_ZERO)
continue;
}

seems correct, but the actual file change does not reflect this 

sorry if i am wrong

**Comment by anshulongithub** [comment]
Friends, we need to make sure that the original patch and the new patch that is being committed here are exactly equivalent. Please make sure of that; changing code of a patch after it has passed the test shud be only be done if that change is absolutely obvious. I might be wrong but please evaluate it carefully or run the test again if needed to establish this. Please make sure that the committed patch and the patch that passed are semantically exactly equivalent.

**Comment by mcostalba** [comment]
Thanks for the head up, I will take care we commit the passed one.

I expect more tuning / reformat work on top of it in the near future, so we
can just commit as is the original patch.

**Comment by DU-jdto** [comment]
@anshulongithub They are equivalent. Factoring out (!inCheck && !rootNode && bestValue > VALUE_MATED_IN_MAX_PLY), what we have is equivalent to:

if (!captureOrPromotion && !givesCheck && !pos.advanced_pawn_push(move)) {}
else if (...)

A precondition for the else if (conditional on the factored bit) is !(!captureOrPromotion && !givesCheck && !pos.advanced_pawn_push(move)) <=> !(!(captureOrPromotion || givesCheck || pos.advanced_pawn_push(move))) <=> (captureOrPromotion || givesCheck || pos.advanced_pawn_push(move)).

This is precisely the removed condition.

**Comment by tthsqe12** [comment]
original patch with code at the bottom is not the same as this PR.
For example, if rootNode is true, we go straight to the else if with no knowledge of 
+	      && (  captureOrPromotion
+		  || givesCheck
+		  || pos.advanced_pawn_push(move)
+		  )


original patch:
+      else if(
+	      
+	          depth < 3 * ONE_PLY
+              && !inCheck
+	      &&  bestValue > VALUE_MATED_IN_MAX_PLY
+	      && !rootNode
+	      && (  captureOrPromotion
+		  || givesCheck
+		  || pos.advanced_pawn_push(move)
+		  )
+	      && pos.see_sign(move) < VALUE_ZERO
+	  )
+	{
+	    continue;
+	}

**Comment by DU-jdto** [comment]
@tthsqe12 If rootNode is true, the else if will be false anyway, because it checks !rootNode too. Same for inCheck and the mate value condition.

**Comment by tthsqe12** [comment]
oh, you may be right! Have you verified with a runs of bench at high depths?

**Comment by ajithcj** [comment]
Hi all, I verified that bench matches the passed version. So they are equivalent.

**Comment by tthsqe12** [comment]
be sure to check the bench at higher depths

**Comment by mcostalba** [comment]
Merged with 38428ada5459

I have merged the original patch because this PR is not mergeable as is (it is composed by 3 commits and one of them is even a merge!) In normal conditions I would have asked author to prepare a proper PR with a **single** commit. In this case I applied the original patch that passed the test and another one (d909d10f33) on top of it to reformat the code because I saw redundant conditions even in the last PR version, so I did it myself.

I understand the excitement for a great patch (+10 ELO http://tests.stockfishchess.org/tests/view/57d07ac40ebc59030fbe5033), possibly the best patch of this season! So big congrats to the author, but please people, do open a PR with a single commit otherwise I can't merge it. Thanks.

**Comment by anshulongithub** [comment]
Amazing! work @ajithcj many many congratulations for this patch :)

**Comment by pb00068** [comment]
Awesome ajithcj !!

**Pull request closed without merging**
