### PR TITLE
Introduce dual NNUE evaluation

### PR DESCRIPTION
**Pull request by XInTheDark**
Alongside the currently used NNUE net, introduce a much smaller L1-256 net that is used when the material imbalance in the position is high; an improvement over the previously used simple eval. This is then combined with search tuning (SPSA, 44k games at 120+1.2).

For more details, see the original PR: #4898.

Acknowledgements: Many thanks to @mstembera & @linrock for writing the original implementation code, and @linrock for training the net used in this patch!

VLTC: https://tests.stockfishchess.org/tests/view/657075336980e15f69c7998f
LLR: 2.95 (-2.94,2.94) <0.00,2.00>
Total: 81342 W: 20137 L: 19788 D: 41417
Ptnml(0-2): 13, 8678, 22933, 9041, 6 

VLTC SMP: https://tests.stockfishchess.org/tests/view/657288776980e15f69c7c7e7
LLR: 2.94 (-2.94,2.94) <0.50,2.50>
Total: 19796 W: 5038 L: 4772 D: 9986
Ptnml(0-2): 3, 1829, 5965, 2101, 0 

Bench: 1216398

### CODE REVIEW

**Comment by vdbergh** [comment]
There are some issues with this VVLTC testing (currently 480/48). What if next week someone "simplifies away" the extra net using the standard procedure STC+LTC.... ?

**Comment by mstembera** [comment]
Congrats!  I think we should also test just the parameter changes in search by themselves at the same VLTC to prove the gain isn't coming just from those alone.

**Comment by Disservin** [comment]
btw the makefile for net2 could be simplified a bit to something like this, to avoid the duplicated rules. 
```Makefile
define evaluate_network
	@echo "Default net: $(nnuenet)"
	@if [ "x$(curl_or_wget)" = "x" ]; then \
		echo "Neither curl nor wget is installed. Install one of these tools unless the net has been downloaded manually"; \
	fi
	@if [ "x$(shasum_command)" = "x" ]; then \
		echo "shasum / sha256sum not found, skipping net validation"; \
	elif test -f "$(nnuenet)"; then \
		if [ "$(nnuenet)" != "nn-"`$(shasum_command) $(nnuenet) | cut -c1-12`".nnue" ]; then \
			echo "Removing invalid network"; rm -f $(nnuenet); \
		fi; \
	fi;
	@for nnuedownloadurl in "$(nnuedownloadurl1)" "$(nnuedownloadurl2)"; do \
		if test -f "$(nnuenet)"; then \
			echo "$(nnuenet) available : OK"; break; \
		else \
			if [ "x$(curl_or_wget)" != "x" ]; then \
				echo "Downloading $${nnuedownloadurl}"; $(curl_or_wget) $${nnuedownloadurl} > $(nnuenet);\
			else \
				echo "No net found and download not possible"; exit 1;\
			fi; \
		fi; \
		if [ "x$(shasum_command)" != "x" ]; then \
			if [ "$(nnuenet)" != "nn-"`$(shasum_command) $(nnuenet) | cut -c1-12`".nnue" ]; then \
				echo "Removing failed download"; rm -f $(nnuenet); \
			fi; \
		fi; \
	done
	@if ! test -f "$(nnuenet)"; then \
		echo "Failed to download $(nnuenet)."; \
	fi;
	@if [ "x$(shasum_command)" != "x" ]; then \
		if [ "$(nnuenet)" = "nn-"`$(shasum_command) $(nnuenet) | cut -c1-12`".nnue" ]; then \
			echo "Network validated"; break; \
		fi; \
	fi;
endef

define netvariables =
$(eval nnuenet := $(shell grep $(1) evaluate.h | grep define | sed 's/.*\(nn-[a-z0-9]\{12\}.nnue\).*/\1/'))
$(eval nnuedownloadurl1 := https://tests.stockfishchess.org/api/nn/$(nnuenet))
$(eval nnuedownloadurl2 := https://github.com/official-stockfish/networks/raw/master/$(nnuenet))
$(eval curl_or_wget := $(shell if hash curl 2>/dev/null; then echo "curl -skL"; elif hash wget 2>/dev/null; then echo "wget -qO-"; fi))
$(eval shasum_command := $(shell if hash shasum 2>/dev/null; then echo "shasum -a 256 "; elif hash sha256sum 2>/dev/null; then echo "sha256sum "; fi))
endef

# evaluation network (nnue)
net:
	$(call netvariables, EvalFileDefaultNameBig)
	$(call evaluate_network)
	$(call netvariables, EvalFileDefaultNameSmall)
	$(call evaluate_network)
```

**Comment by Disservin** [comment]
btw test is running here https://tests.stockfishchess.org/tests/view/65731ccbf09ce1261f12246e

**Comment by Disservin** [comment]
I think we can close this in the meantime, since the gainer likely came from https://github.com/official-stockfish/Stockfish/pull/4912.

**Pull request closed without merging**
