### PR TITLE
Correct easy move fix for lazy smp (by @mbootsector)

### PR DESCRIPTION
**Pull request by mstembera**
I have started a test to confirm
http://tests.stockfishchess.org/tests/view/561c9fa20ebc597e4f23e887
but since this is not the main branch I'm opening the pull request now because this may affect other time management patches.
I'm undecided if a fixed number of games test w/ a minimum of 11(or more) threads is worth it?  Please advise.

### CODE REVIEW

**Comment by joergoster** [comment]
Great! ;-)
I wonder if we could play some 50 or 100 games with 15 (or 20) cores at TCEC time control. Only if possible for Gary to make them available, so that people might take a look to confirm it's working now. Maybe the time management is also being improved due to this fix?
Nevertheless, the safety margin when playing on increment only, must be increased for lazy smp.

**Comment by joergoster** [comment]
@mstembera Maybe you can add this small change in line 482.
```
          if (this != Threads.main())
              break;
```
change to
```
          if (!isMainThread)
              break;
```
Thanks!

**Comment by mstembera** [comment]
http://tests.stockfishchess.org/tests/view/561c9fa20ebc597e4f23e887
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 17351 W: 3054 L: 2927 D: 11370

**Comment by mstembera** [comment]
@joergoster 
I normally would and agree line 482 should be changed exactly as you say.  I just want to make sure there is no possible confusion about what exactly fixes the easy move issue.  Do you mind opening a separate request? or I'm happy to do it for you.

**Comment by mcostalba** [comment]
Thanks I will apply later this week.

**Comment by joergoster** [comment]
@mstembera Sure. I will include it in my lazy_smp_simple pull request.

**Pull request merged**
