### PR TITLE
Fix issues #638

### PR DESCRIPTION
**Pull request by aprijal-psrb**
See issues #638.

### CODE REVIEW

**Comment by mcostalba** [comment]
Do you have the hardware to test it? Does it work only with gcc or also with clang?

**Comment by aprijal-psrb** [comment]
Yes, it's work with gcc

**Comment by mcostalba** [comment]
Thanks, can you please test with clang too?

I see the same option is present also there.

**Comment by aprijal-psrb** [comment]
SF cannot be running since SF7 if compiled with clang

**Comment by mcostalba** [comment]
This is interesting, considering that gcc is going to be deprecated, see
revision 11 log:

http://developer.android.com/ndk/downloads/revision_history.html

Can you please provide the full clang compile output for Android NDK of the
current master? Thanks.

**Comment by aprijal-psrb** [comment]
The parameter of clang is not set properly so i set manually like gcc's parameter and building success. And while i run on my devices sf will terminated with error "no active exception". I'm using Crystax ndk gcc 5.3 and clang https://www.crystax.net/en/android/ndk. If you want i'll test it with google ndk.

**Comment by aprijal-psrb** [comment]
I've tested google ndk with libc++ stl.
Now, no problems on gcc and clang compilers

**Comment by mcostalba** [comment]
Thanks!  I am closing this PR then.

**Comment by aprijal-psrb** [comment]
so this PR not be merged?, it's work with my commit.

**Comment by mcostalba** [comment]
Sorry, I misunderstand, I thought it worked with google ndk with libc++ stl
even withouth any tweak

**Comment by mcostalba** [comment]
I have reopened the PR, although it seems a bit too invasive: I will check if all that options are really needed.

**Comment by KassiasGrandiel** [comment]
@mcostalba You didn't reopen the PR when you said you have

**Pull request closed without merging**
