### PR TITLE
Bitwise Operation Comment

### PR DESCRIPTION
**Pull request by FauziAkram**
Add a comment to explain the purpose and meaning of the following Bitwise Operation.

More self-explanatory, and developers who read the code later can quickly understand the intention and purpose of the bitwise operations without having to deduce it from the context
No Functional change.

### CODE REVIEW

**Comment by locutus2** [comment]
@FauziAkram 
Correction: its the last **two** bits

**Comment by fanzier** [comment]
Wouldn't it be clearer for the code to use `% 4` instead of `& 3`? I haven't checked but I think the compiler should optimize it to the same assembly.

**Comment by cj5716** [comment]
> Wouldn't it be clearer for the code to use `% 4` instead of `& 3`? I haven't checked but I think the compiler should optimize it to the same assembly.

clang 16 doesn't even at `-O3` compilation unfortunately.

**Comment by FauziAkram** [comment]
@locutus2 that's right, done.

**Comment by Sopel97** [comment]
it would result in the same assembly if `iterIdx` was unsigned

**Comment by cj5716** [comment]
Is it me, or is the indentation slightly off? 
image

**Comment by FauziAkram** [comment]
Done, fixed.

**Comment by mstembera** [comment]
IMO it's inconsistent to comment trivial code like this while we have lots of significantly more complex code uncommented.

**Comment by FauziAkram** [comment]
@mstembera I don't think that's a valid objection, I think that small and gradual improvements are better than none.

**Comment by Disservin** [comment]
I dont think we should comment these portions of the code. `bitwise and` is something programmers should understand and is rather trivial. If we were to comment every bitwise operation in the engine we'd have a long list and probably just make it more difficult read.

**Comment by FauziAkram** [comment]
Alright, I will close the PR

**Pull request closed without merging**
