### PR TITLE
Fix issue #1058

### PR DESCRIPTION
**Pull request by vondele**
the order of elements returned by std::partition is implementation defined (since not stable) and could depend on the version of libstdc++ linked.
As std::stable_partition was tested to be too slow (http://tests.stockfishchess.org/tests/view/585cdfd00ebc5903140c6082).
Instead combine partition with our custom implementation of insert_sort, which fixes this issue.
Implementation based on a patch by mstembera (http://tests.stockfishchess.org/tests/view/58d4d3460ebc59035df3315c), which suggests some benefit by itself.
Note that, contrary to master, entries are only sorted up to -VALUE_INFINITE, even though they can be more negative.

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 44997 W: 8145 L: 8065 D: 28787

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 18570 W: 2442 L: 2319 D: 13809

Bench: 5658907

### CODE REVIEW

**Comment by MichaelB7** [comment]
Nice , good to see that fixed !

**Comment by VoyagerOne** [comment]
Not a simplification.
This is a functional patch.
You added a new parameter that we now have to deal with when tweaking stats.

**Comment by mstembera** [comment]
Would using INT_MIN be acceptable?

**Comment by VoyagerOne** [comment]
@mstembera 
http://tests.stockfishchess.org/tests/view/58ef85490ebc59035df339c7

**Comment by ddugovic** [comment]
> Note that, contrary to master, entries are only sorted up to -VALUE_INFINITE, even though they can be more negative.

Might this be beneficial such that it would be reasonable to submit this as a functional patch?

**Comment by sf-x** [comment]
> Why sort values less than (more negative than) that value?

`-VALUE_INFINITE` is a evaluation minimum. It doesn't have an apparent meaning as a history score. In fact, history score can be less than `-VALUE_INFINITE`.

**Comment by vondele** [comment]
@sf-x the source of confusion was that history score are stored in a Value type, which doesn't make much sense. 

I'm seeing if a variant based on INT_MIN works as well to fix this bug, which would address the concern raised by VoyagerOne. I'd like to emphasise that I submit this as a bugfix and not a simplification.

**Comment by mstembera** [comment]
I also agree w/ @vondele that CounterMoveStats, HistoryStats, ExtMove, and functions like Value stat_bonus(Depth depth) and anything related should use type int instead of Value.

**Comment by vondele** [comment]
@mstembera I've put that Value -> int change here https://github.com/official-stockfish/Stockfish/commit/dbe62de27e03d714cc6981dd076c56da209304c6 let me know if you think anything is missing. It is on top of https://github.com/vondele/Stockfish/commit/9b25e729c1ad25fd2f342910d29dc47a49b4c3b9  , which is currently  being tested.

**Comment by vondele** [comment]
updated PR now based on INT_MIN.

**Comment by VoyagerOne** [comment]
@vondele 
Thanks for correcting this...

**Comment by zamar** [comment]
I'm a bit reserved about replacing our simple standard insertion algorithm with the proposed solution...

Rather I'd consider writing our own simple partition function... Here are a couple of examples:
http://en.cppreference.com/w/cpp/algorithm/partition
https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-4.4/a01347.html (line 1747)

**Comment by vondele** [comment]
I considered that, but that adds more code that duplicates stdlib functionality. 

The merged code seems to make sense for example for the change discussed here : https://github.com/vondele/Stockfish/commit/1a6dff2f2b955678b498c3f6eb0ade739a7da68c where all use of the insertion_sort will be partial_insertion_sort.

**Comment by zamar** [comment]
Avoiding duplicating code is of course a valid point, although copying a short function from stdlib is not an end of the World.

The concern with your function is that it gets a bit tricky to understand and validate. I've verified and validated your function and it seems correct to me.

However careful reader will notice that the first entry in the list (*begin) gets always inserted into sortedList (no matter what its value is). This raises questions if this behaviour is intentional (keep it simple) or just a plain oversight.

Of course the behaviour of function is still within spec, we are just doing a bit of extra work in this case (which is probably okay). But this behaviour at least requires a comment (or alternatively the behaviour should be fixed).

**Comment by vondele** [comment]
I have added the comment to clarify the implementation.

**Comment by VoyagerOne** [comment]
I am not really a fan of this "bug fix"

First off what is exactly the "bug" this patch is suppose to fix?
I read the description of the issue...but have never seen a case of different machines getting a different benches because of non-stable partition.

Maybe someone can provide an explicit example.

Furthermore...this patch fixes the "bug" by adding a bug.
As @zamar pointed out ... the begin* can be any value and be in the sorted partition.
Which is not ideal.

**Comment by VoyagerOne** [comment]
As @zamar suggested...

https://github.com/official-stockfish/Stockfish/pull/1073

**Comment by vondele** [comment]
@VoyagerOne please read zamar's message carefully or study the code. There is no bug in the new version of the function. *begin will be the first element of the unsorted list if belongs in the unsorted list, it will be in the proper place if it has to be in the sorted list. The implementation choice makes the algorithm more concise and likely faster.

The reason for the patch should be clear, if we want the bench to be reproducible between different implementations and versions of libstdc++ we need a well defined order of all elements in the list, which is not what std::partition guarantees.

**Comment by VoyagerOne** [comment]
@vondele 
Thanks...I see now.  
I am cool with your patch.

**Pull request closed without merging**
