### PR TITLE
[NNUE] Don't use std::aligned_alloc

### PR DESCRIPTION
**Pull request by dorzechowski**
Compile without std::aligned_alloc which is not supported by some popular compilers.
Tested in mingw 10.2.0, clang 10.0.0, gcc 9.3.0 on Windows, gcc 8.3.1 on Linux.

No functional change.

### CODE REVIEW

**Comment by vondele** [comment]
@dorzechowski thanks! Since _mm_alloc is not standard and seemingly related to SSE, I'd still rather use it in a wrapper. I'll give it a try with: 
```diff
diff --git a/src/misc.cpp b/src/misc.cpp
index ecaee23ee..b8b43868b 100644
--- a/src/misc.cpp
+++ b/src/misc.cpp
@@ -41,10 +41,6 @@ typedef bool(*fun3_t)(HANDLE, CONST GROUP_AFFINITY*, PGROUP_AFFINITY);
 }
 #endif
 
-#if defined(_MSC_VER)
-#include <malloc.h>
-#endif
-
 #include <fstream>
 #include <iomanip>
 #include <iostream>
@@ -305,8 +301,8 @@ void prefetch(void* addr) {
 void* std_aligned_alloc(size_t alignment, size_t size) {
 #if defined(__APPLE__)
   return aligned_alloc(alignment, size);
-#elif defined(_MSC_VER)
-  return _aligned_alloc(size, alignment);
+#elif defined(_WIN32)
+  return _mm_malloc(size, alignment);
 #else
   return std::aligned_alloc(alignment, size);
 #endif
@@ -315,8 +311,8 @@ void* std_aligned_alloc(size_t alignment, size_t size) {
 void std_aligned_free(void* ptr) {
 #if defined(__APPLE__)
   free(ptr);
-#elif defined(_MSC_VER)
-  _aligned_free(ptr);
+#elif defined(_WIN32)
+  _mm_free(ptr);
 #else
   free(ptr);
 #endif

```

**Comment by dorzechowski** [comment]
@vondele Yes, it might not work on some systems but perhaps it works as it is on MSVC? It's a function introduced by Intel long before C++17. Now std::aligned_alloc really should work everywhere, it's quite a bummer that it doesn't.

**Comment by vondele** [comment]
yes, it actually works on MSVC CI just turned green: https://ci.appveyor.com/project/mcostalba/stockfish/builds/34310633

I'll close this PR, thanks!

**Comment by dorzechowski** [comment]
@vondele That's great. I believe it should also work directly without using the wrapper, at least on x86. Would be nice to know if it works on MacOS as well.

**Comment by vondele** [comment]
CI on MacOS is OK with the current form (calling without 'std::') as well https://travis-ci.org/github/official-stockfish/Stockfish/jobs/711998252

**Comment by Zerbinati** [comment]
@vondele  Fantastic now compiles perfectly without errors and warnings of any kind.

**Pull request closed without merging**
