### PR TITLE
More robust bench extraction

### PR DESCRIPTION
**Pull request by vondele**
Bench: 5023593. (really).

### CODE REVIEW

**Comment by snicolet** [comment]
Why is it more robust, by the way?

**Comment by vondele** [comment]
It will remove trailing non-numeric characters from the extracted bench.

**Comment by mcostalba** [comment]
@vondele I don't understand why current regexp does grab non number chars

sed "s/[^0-9]*\([0-9][0-9]*\)/\1/g"

Maybe we want to fix that properly instead to bolt on a new one

**Comment by mcostalba** [comment]
Playing at https://regex101.com/ I have found this one:

[^0-9]*([0-9]+)

Captured group is correct, but for some reason it also substitutes '5023593. (really).'.....hmmm

**Comment by mcostalba** [comment]
Ok, I have found the correct one, is:

 sed "s/[^0-9]*\([0-9][0-9]*\)\(.*\)/\1/g"

**Comment by gadcam** [comment]
Wont this one be even better : 
```regex
[^0-9]([0-9]+)[^0-9]?
```
and so 
```batch
sed "s/[^0-9]\([0-9]\+\)[^0-9]\?/\1/g"
```

**Comment by mcostalba** [comment]
~~~~
$ echo "Bench: 5023593. (really)." | sed "s/[^0-9]\([0-9]\+\)[^0-9]\?/\1/g"
Bench:5023593 (really).
~~~~

**Comment by mcostalba** [comment]
Indeed sed seems a bit a 'difficult' guy, the only one that works for me is the below:

~~~~
$ echo "Bench: 5023593. (really)." | sed "s/[^0-9]*\([0-9][0-9]*\)\(.*\)/\1/g"
5023593
~~~~

**Comment by WOnder93** [comment]
How about:

    $ echo "Bench: 5023593. (really)." | grep -E -o '[0-9]+'
    5023593

**Comment by gadcam** [comment]
This one seems to work and to be a bit simpler :
```batch
$ echo "Bench: 5023593. (really)." | sed "s/[^0-9]*\([0-9]*\)./\1/g"
5023593
```
@WOnder93 I think we need to avoid using grep as we can not know if there will another number after like in
```batch
$ echo "Bench: 5023593. (really 3)." | grep -E -o '[0-9]+'
5023593
3
```

**Comment by mcostalba** [comment]
@WOnder93 nice!

I confirm it works on the somewhat limited mingw bash:

```
$ echo "Bench: 5023593. (really)." | grep -E -o "[0-9]+"
5023593
```

But the simpler version without -E fails for some reason (returns empty).

I confirm also this one works on mingw:

```
$ echo "Bench: 5023593. (really)." | sed "s/[^0-9]*\([0-9]*\)./\1/g"
5023593
```

**Comment by mcostalba** [comment]
I agree we should take care to pick only first number like in:

`bench: 123456 (it was 232132)`

**Comment by mcostalba** [comment]
Oooops

```
$ echo "bench: 123456 (it was 232132)" | sed "s/[^0-9]*\([0-9]*\)./\1/g"
123456232132
```

**Comment by mcostalba** [comment]
This passes all:

```
$ echo "Bench: 5023593. (really)." | sed "s/[^0-9]*\([0-9][0-9]*\)\(.*\)/\1/g"
5023593
$ echo "bench: 123456 (it was 232132)" | sed "s/[^0-9]*\([0-9][0-9]*\)\(.*\)/\1/g"
123456
$ echo "bench: 123456 (blha blah)" | sed "s/[^0-9]*\([0-9][0-9]*\)\(.*\)/\1/g"  
123456
$ echo "Bench:123456" | sed "s/[^0-9]*\([0-9][0-9]*\)\(.*\)/\1/g"
123456
$ echo "Bench: 123456. 567 something (453223) 563" | sed "s/[^0-9]*\([0-9][0-9]*\)\(.*\)/\1/g"
123456
```

**Comment by gadcam** [comment]
Do you want this behavior ?
```batch
$echo "bench: 123456 (it was 232132)" | sed "s/[^0-9]*\([0-9]*\)./\1/g"
123456
```

**Comment by WOnder93** [comment]
Ah, right!

Then how about replacing:

    git log HEAD | grep "\b[Bb]ench[ :]\+[0-9]\{7\}" | head -n 1 | sed "s/[^0-9]*\([0-9][0-9]*\)/\1/g" > git_sig

with just:

    git log HEAD | grep -o "\b[Bb]ench[ :]\+[0-9]\{7\}" | grep -o '[0-9]\+' | head -n 1

That should also catch lines like: "Take 3, Bench: 5023593. (really 3)."

**Comment by WOnder93** [comment]
@mcostalba Note that you need to escape the '+' in the version without -E.

**Comment by gadcam** [comment]
This version should be enough
```batch
$ echo "Bench: 123456. 567 something (453223) 563" | sed "s/[^0-9]*\([0-9]*\).*/\1/g"
123456
```

**Comment by mcostalba** [comment]
@gadcam yes, but on my limited minwg bash under windows your version does not work:

```
$ echo "bench: 123456 (it was 232132)" | sed "s/[^0-9]*\([0-9]*\)./\1/g"
123456232132
```

Indeed for some reason ([0-9]*) is different from ([0-9][0-9]*), it should be not, but now I remember why current code is like it is: I stumbled upon this mingw bash limit already when I wrote it in the past.

**Comment by gadcam** [comment]
Looks like you forgot the final star as I am also running a limited bash under windows.
[0-9][0-9]* seems to just be the same as [0-9]+ in other regex flavor.

**Comment by WOnder93** [comment]
@mcostalba @gadcam I also get this on a regular Ubuntu bash:
```
$ echo "bench: 123456 (it was 232132)" | sed "s/[^0-9]*\([0-9]*\)./\1/g"
123456232132
```

**Comment by mcostalba** [comment]
@WOnder93 your solution is a bit tricky because it relies on head being put at the end.

I have retested all with the simplest version:

```
$ echo "Bench: 5023593. (really)." | sed "s/[^0-9]*\([0-9]*\).*/\1/g"
5023593
$ echo "bench: 123456 (it was 232132)" | sed "s/[^0-9]*\([0-9]*\).*/\1/g"
123456
$ echo "bench: 123456 (blha blah)" | sed "s/[^0-9]*\([0-9]*\).*/\1/g"
123456
$ echo "Bench:123456" | sed "s/[^0-9]*\([0-9]*\).*/\1/g"
123456
$ echo "Bench: 123456. 567 something (453223) 563" | sed "s/[^0-9]*\([0-9]*\).*/\1/g"
123456
```

I confirm it works for me.

@vondele in case you update your PR, please add all these test cases to your log message as documenting.

**Comment by vondele** [comment]
we all like regexps its seems. 'grep -o' is not portable (non-posix), so we better stick to sed.

**Comment by snicolet** [comment]
Merged via https://github.com/official-stockfish/Stockfish/commit/312a248fa9123c48613dcadf2f17c6fd5e0d2a48. Thanks!

**Pull request closed without merging**
