### PR TITLE
Fix PGO Build for clang

### PR DESCRIPTION
**Pull request by MichaelB7**
This fixes https://github.com/official-stockfish/Stockfish/issues/167.
Also added -j flag for faster builds.

### CODE REVIEW

**Comment by MichaelB7** [comment]
Bridges the gap slightly. Clang builds are more compatible than gcc builds for macOS when sharing across multiple macs since Apple officially endorses clang by making it the default compiler in Xcode..

bench 16 1 22 - all three ran concurrently on a 12 core Mac Pro

clang(3.9) non pgo build:
Total time (ms) : 133492
Nodes searched  : 213390137
Nodes/second    : 1598523

clang(3.9) pgo build:
Total time (ms) : 127802
Nodes searched  : 213390137
Nodes/second    : 1669693

gcc(4.8) pgo build:
Total time (ms) : 125629
Nodes searched  : 213390137
Nodes/second    : 1698573

**Comment by mcostalba** [comment]
Sorry but it does not work for me (Linux Ubuntu)

```
Step 3/4. Building optimized executable ...
make ARCH=x86-64-modern COMP=clang objclean
make[1]: Entering directory `/home/marco/Documents/Stockfish/src'
make[1]: Leaving directory `/home/marco/Documents/Stockfish/src'
make ARCH=x86-64-modern COMP=clang clang-profile-use
make[1]: Entering directory `/home/marco/Documents/Stockfish/src'
llvm-profdata merge -output=stockfish.profdata *.profraw
/bin/sh: 1: llvm-profdata: not found
make[1]: *** [clang-profile-use] Error 127
make[1]: Leaving directory `/home/marco/Documents/Stockfish/src'
make: *** [profile-build] Error 2
```

In case you resubmit, please drop the -j option, it is useless and renders the output difficult to follow.

**Comment by vondele** [comment]
@mcostalba this is basically an packaging bug, ubuntu provides llvm-profdata-3.8 (assuming you have the llvm package and clang-3.8), but contrary to e.g. clang, which is a symlink to clang-3.8, the proper link is missing for llvm-profdata. This even hit python http://bugs.python.org/issue27983 . 

@MichaelB7 this fixes it for me on ubuntu, maybe you can try on OSX
```
...
        profile_make = clang-profile-make
        profile_use = clang-profile-use
        ifeq ($(shell which llvm-profdata),)
          # if llvm-profdata doesn't exist find a version by completion
          PROFDATA = $(shell /bin/bash -c "compgen -c llvm-profdata")
        else
          PROFDATA = llvm-profdata
        endif

....

clang-profile-use:
        $(PROFDATA) merge -output=stockfish.profdata *.profraw
```

My comment would be that the intermediate profiling files should be cleaned (see profileclean target).

I agree on not using '-j' inside the makefile, that is up to the user to specify it when calling.

**Comment by vondele** [comment]
@MichaelB7 more robust (in case of multiple clang installations) should be this definition, tested to work on ubuntu: 

```
          PROFDATA = $(shell /bin/bash -c 'echo $$(dirname $$(readlink -f $$(which clang)))/llvm-profdata')
```
which will pick the version that corresponds to the used clang version.

**Comment by vondele** [comment]
@MichaelB7 I have put all these changes on a branch. Let me know if you want to integrate it into yours and update this request, or if you want me to do a pull request:

https://github.com/vondele/Stockfish/tree/clangpgo

**Comment by MichaelB7** [comment]
@vondele  I just tested , yes,  please do the pull request.  Thank you.

**Comment by mcostalba** [comment]
Merged with fbb2ffacfdf10fc37d8ee2

Issues on Ubuntu were due to upstream packaging bugs, after fixing llvm-profdata everything worked.

**Pull request closed without merging**
