### PR TITLE
Stat score initialization: children

### PR DESCRIPTION
**Pull request by locutus2**
Let the parent node initialize stat score to zero once for all siblings.

STC:
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 22683 W: 5202 L: 4946 D: 12535
http://tests.stockfishchess.org/tests/view/5a93315f0ebc590297cc894f

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 48548 W: 8346 L: 8035 D: 32167
http://tests.stockfishchess.org/tests/view/5a933ba90ebc590297cc8962

Bench: 5332277

### CODE REVIEW

**Comment by mcostalba** [comment]
@locutus2 congratulations!

This definitely needs some well explained in comment code, because change is subtle and quite sensible.

**Comment by VoyagerOne** [comment]
Congrats!

**Comment by locutus2** [comment]
@mcostalba 
I add some comment to the initialization. Is this what you have in mind?

**Comment by locutus2** [comment]
This PR is superseded by PR #1440

**Comment by snicolet** [comment]
Congrats, merged via https://github.com/official-stockfish/Stockfish/commit/1463881153a20690871086208eaf76f20041effb

**Pull request closed without merging**
