### PR TITLE
Rename shift_bb() and directions names in code

### PR DESCRIPTION
**Pull request by snicolet**
Rename shift_bb() to shift(), and DELTA_S to SOUTH, etc. to improve code readability, especially in evaluate.cpp when they are used together:

- old `b = shift_bb<DELTA_S>(pos.pieces(PAWN))`
- new `b = shift<SOUTH>(pos.pieces(PAWN))`

No functional change

### CODE REVIEW

**Comment by lucasart** [comment]
I don't know about you, but it always takes me a couple of seconds to remember which of EAST or WEST is LEFT or RIGHT. What would make the code even more readable is to use the much more intuitive UP, DOWN, LEFT, RIGHT instead or NORTH, SOUTH, WEST, EAST.

**Comment by mcostalba** [comment]
@lucasart unfortunatley Up and Down are already used (see movegen and evaluation):

```
const Square   Up   =  (Us == WHITE ? DELTA_N  : DELTA_S);
const Square Down = (Us == WHITE ? DELTA_S   : DELTA_N);
```

The convention across SF sources is to use Up and Down as color dependent directions, while north, south, etc as color independent directions.

**Comment by lantonov** [comment]
LEFT and RIGHT are ambiguous: "Your left or my left?"

**Comment by Rocky640** [comment]
Mathematically inclined may like degrees DELTA_0, DELTA_45 ,DELTA_90...
`const Square Right = DELTA_45 + (Us == WHITE ? 0 : 180);`
Well, they might prefer radians, but this would not make nice names ;)

But it would not be so clear that DELTA_0 would mean moving EAST, 
(or "staying where you are", or going WEST..). 

Back to the PR, just my 5 cents, I think current master is just fine. 
Current names are short and clear enough.
I also prefer enums which all have the same prefix, when it is not too long.

And since shift_bb does not work with Square, only with Bitboards, the _bb suffix helps to prevent any confusion.

**Comment by mcostalba** [comment]
Personally I like this PR.

- DELTA_N vs NORTH: Here the N in DELTA_N stands exactly for NORTH, so it is better to use the full word

- DELTA_X here the DELTA_ prefix adds very small info, mainly to highlight that all refer to the same enum, IMO this is not enough to avoid dropping it, considering that NORTH, SOUTH, etc are all uppercase that in SF code style it means an enum value (although I admit this is not used consistently)

- shift_bb() -> shift() here the only reason for _bb is because usually all functions returning bitboards are suffixed _bb, this is due to some functions where this is really needed to avoid ambiguities like file_bb(), but here is not really needed and in general I don't like Hungarian notation style, where types are encoded in the name: to me this is a poor choice because type-checking is done by the compiler and it is crazy to encode it in the name.

So I probably will commit this, but I will leave this open still a bit to allow further comments.

**Comment by mcostalba** [comment]
Merged with 7ae3c05795e79c.

While there fix some small code style issues.

**Comment by snicolet** [comment]
@lucasart Try this, in clockwise order:

"*Never eat stockfish wastes*"

**Pull request closed without merging**
