### PR TITLE
Merge c++11 branch into master

### PR DESCRIPTION
**Pull request by zamar**
In this case, it is probably best to use 'git merge' to preserve the history of both branches.

### CODE REVIEW

**Comment by mcostalba** [comment]
Thanks Joona. I'd guess we should first prove c++11 SMP works on fishtest (read fix/workaround HT problem) before to merge.

**Comment by zamar** [comment]
Isn't the problem only with Spinlocks?

If we retire Spinlocks from C++11 branch for now, we could merge?

Or is there a problem also with C++11 mutexes?

**Comment by mcostalba** [comment]
If we retire spinlocks we retire a feature that gives +18% nps at high smp.
What's the deal with retiring it?

**Comment by mcostalba** [comment]
I have pushed a patch to fallback on mutex when compiling with -DNO_SPINLOCK flag

This could allow current c++11 branch to run on fishtest as is, as long on Gary's builder, the flag is set when compiling.

OTH on abrok and for other pople that compile SF by themsekves, they should not be affected (because they don't define -DNO_SPINLOCK) so they should have no slowdown.

Not that I like this workaround, but may be now can be merged

**Comment by zamar** [comment]
Spinlocks will of course go in - sooner or later.

My preference would be to do it in two stages
1) move to C++11 (without spinlocks)
2) Move from mutexes into spinlocks

So you could commit everything from c++11 branch (except spinlocks), and then just open a new pull request for spinlocks which will be committed when we are ready...

But it's up to you.

**Comment by zamar** [comment]
Anyhow, because you've been the maintainer of this branch, I think you are the right person to do the merge....

**Comment by mcostalba** [comment]
Ok i will unconditionally disable Spinlocks while merging.

If also Gary agrees, I ll go.

**Comment by glinscott** [comment]
It looks like the pthreads spinlock implementation is better than the C++11 for now, so maybe we can try that one out as well.  C++11 looks good though!

**Comment by zamar** [comment]
_mm_pause() is the way to go?!

**Comment by mcostalba** [comment]
Branch c++11 fully merged. Spinlocks unconditionally disabled now.

**Comment by mcostalba** [comment]
I have tested with _mm_pause() and, although I don't measure any slowdown,
I also don't see the speed up in HT case that for me is always very slow
when set threads is higher than physical cores.

**Pull request merged**
