### PR TITLE
Merge master into cluster, minor fixes and resolving conflict

### PR DESCRIPTION
**Pull request by noobpwnftw**
I suppose a merge PR should look like this?

### CODE REVIEW

**Comment by snicolet** [comment]
Merged in the official cluster branch via c80b19a05c9a1c1b01895362bb12c5eef1fdd76a, thanks!

To see the changes in your cluster branch locally and send them in your online GitHub repository, please do the following commands:

```
git fetch official
git checkout cluster
git reset --hard official/cluster
git push origin cluster --force
```

**Comment by snicolet** [comment]
Afterwards you can branch off the new cluster branch for your future work (and stop using the fix_pv_output branch, as pushing anything to fix_pv_output would have the effect of changing this pull request, which is a bad idea to keep a clean history of our actions).

**Comment by snicolet** [comment]
Note the three lines you will have to perform each time I make any change to the official/cluster branch to keep it in synch on your repositories:
```
git checkout cluster
git reset --hard official/cluster
git push origin cluster --force
```

**Comment by noobpwnftw** [comment]
Did it, thank you! @snicolet

**Pull request closed without merging**
