### PR TITLE
Cleanup code after dropping ICC support in favor of ICX

### PR DESCRIPTION
**Pull request by UniQP**
The commit removes all uses of ICC's __INTEL_COMPILER macro and other references to ICC. It also adds ICX info to the compiler command and fixes two typos in Makefile's help output.

No functional change

### CODE REVIEW

**Comment by UniQP** [comment]
@maximmasiutin I would appreciate if you can perform a quick test with ICX.

**Comment by maximmasiutin** [comment]
I no longer have a machine where I tested the ICX, cannot test now :-(

**Comment by vondele** [comment]
`make -j ARCH=x86-64-avx2 profile-build COMP=icx` 

works for me (after downloading and installing icx from https://www.intel.com/content/www/us/en/developer/tools/oneapi/toolkits.html#base-kit)

```
$ ./stockfish compiler
Stockfish dev-20230831-b095db8a by the Stockfish developers (see AUTHORS file)

Compiled by ICX 20230200 on Linux
Compilation settings include:  64bit AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: Intel(R) oneAPI DPC++/C++ Compiler 2023.2.0 (2023.2.0.20230721)

```

**Comment by maximmasiutin** [comment]
Thank you!

**Comment by snicolet** [comment]
I am fine with the patch.

If I remember correctly, ICC support was add by Marco back in the days but obviously not tested for years

**Comment by snicolet** [comment]
The only complain we might have is with somebody with a vintage machine unable to install GAV, but that’s very unlikely

**Pull request closed without merging**
