### PR TITLE
Don't update TT at excluded move ply

### PR DESCRIPTION
**Pull request by VoyagerOne**
Don't update TT at excluded move ply

STC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 38906 W: 7125 L: 6835 D: 24946

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 28600 W: 3752 L: 3543 D: 21305

### CODE REVIEW

**Comment by MichaelB7** [comment]
Very nice @VoyagerOne!

**Comment by lucasart** [comment]
Patch is half-cooked. What about TT Probe ?

**Comment by VoyagerOne** [comment]
@lucasart 
The logical thing to do is not probe the TT for excluded move.

**Comment by VoyagerOne** [comment]
I submitted a test for this...
https://github.com/VoyagerOne/Stockfish/commit/d7acea3f27e7c101671caf01daf6e3c1390f16ec

**Comment by mstembera** [comment]
@lucasart  It's a non functional speedup w/ same bench relative to the patch that passed [0,5].

**Comment by VoyagerOne** [comment]
So some insight for this patch:
Based on a few tests I experiment with the reason the ELO gain comes from not applying TT-cutoff at excluded move ply. (http://tests.stockfishchess.org/tests/view/58dbc7050ebc59035df333b0)
specifically if the excluded move fails lows. (http://tests.stockfishchess.org/tests/view/58d721b20ebc59035df33206)

So there is a few options we have:
A. We can submit this current patch along with not probing TT
or
B. Simply don't do TT cutoffs at excluded move. (http://tests.stockfishchess.org/tests/view/58dbc7050ebc59035df333b0)

In my opinion we should merge B.  It is simpler and we can try to test it against A to see if there is still some elo to gain.

**Comment by sf-x** [comment]
>In my opinion we should merge B. It is simpler

Not really. Option A allows also removing XORing hash key with `excludedMove`. It also means less shitting into TT.

**Comment by VoyagerOne** [comment]
@sf-x I agree... we don't want any shit in our TT.  :)

**Comment by zamar** [comment]
@VoyagerOne: I'd prefer the current version + patch where we are not probing TT for excluded moves (wasn't this a non-functional change).

**Comment by crossbr** [comment]
Would doing an ELO comparison at LTC between option A and option B _in advance_, make any difference in determining which option to adopt?

**Comment by VoyagerOne** [comment]
@zamar 
See:  https://github.com/official-stockfish/Stockfish/pull/1052

**Pull request closed without merging**
