### PR TITLE
Skip early pruning in singular search

### PR DESCRIPTION
**Pull request by TarasVuk**
This patch skips early pruning and updating of history based on static eval difference in singular search.

Passed STC:
LLR: 2.93 (-2.94,2.94) <-1.75,0.25>
Total: 387872 W: 97721 L: 97890 D: 192261
Ptnml(0-2): 1202, 46691, 98263, 46634, 1146
https://tests.stockfishchess.org/tests/view/6552660c136acbc57353490a

Passed LTC:
LLR: 2.95 (-2.94,2.94) <-1.75,0.25>
Total: 127518 W: 31399 L: 31285 D: 64834
Ptnml(0-2): 80, 14442, 34606, 14546, 85
https://tests.stockfishchess.org/tests/view/655502e5136acbc573537b9b

bench: 1498102

### CODE REVIEW

**Comment by Disservin** [comment]
I'm not particular fond of introducing a new goto jump. It also skips Probcut entirely, whereas before it only skipped a matching move inside probcut.

**Comment by vondele** [comment]
I also don't really see this as a simplification patch.

**Comment by Disservin** [comment]
Yeah, I'm closing it, thanks. Interestingly one might try to skip probcut in case there's a excluded move, with gainer bounds perhaps?

**Comment by peregrineshahin** [comment]
> Yeah, I'm closing it, thanks. Interestingly one might try to skip probcut in case there's a excluded move, with gainer bounds perhaps?

Was tried few days ago by cj5.

**Comment by TarasVuk** [comment]
> I also don't really see this as a simplification patch.

I also wasn't sure about it.

**Pull request closed without merging**
