### PR TITLE
Removing unused field ttMove in Stats struct.

### PR DESCRIPTION
**Pull request by loco-loco**
This is a not functional change that slightly improve the nodes per second speed (in my local machine by 0.4%)

### CODE REVIEW

**Comment by mcostalba** [comment]
Good catch!

**Comment by zamar** [comment]
approved

**Comment by DU-jdto** [comment]
While you're at it, you might want to consider getting rid of Search::Stack::reduction too, as it's not used for anything that would prevent it from being replaced by a local variable.

**Comment by glinscott** [comment]
looks good!

**Comment by mstembera** [comment]
@DU-jdto 
Please open a pull request if you don't mind.  Thanks.

**Pull request closed without merging**
