### PR TITLE
remove mate distance pruning.

### PR DESCRIPTION
**Pull request by vondele**
No benefit for playing games (and a small slowdown), but for finding shortest mates.

passed STC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 11997 W: 2172 L: 2036 D: 7789
elo =    3.939 +-    3.677 LOS:   98.2%

passed LTC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 46576 W: 5939 L: 5851 D: 34786
elo =    0.656 +-    1.585 LOS:   79.1%

Bench: 5878420

### CODE REVIEW

**Comment by mcostalba** [comment]
This is a very old and established rule. Don't think this stuff can evaporate with a (-3, 1)

**Comment by vondele** [comment]
well, since the framework is empty I have added a [0,4].

**Comment by vondele** [comment]
didn't pass [0,4]:
LLR: -2.96 (-2.94,2.94) [0.00,4.00]
Total: 76470 W: 13653 L: 13552 D: 49265

**Comment by zamar** [comment]
No reason to remove it...

**Comment by mstembera** [comment]
Can someone please explain what mate distance pruning does if it's not to gain elo?

**Comment by zamar** [comment]
Finds a mate quicker.

**Comment by MichaelB7** [comment]
A quote from Tord Romstad:
```"From the point of view of playing strength, I don't even think it helps in rare positions. It's a purely cosmetic little trick, that helps the engine search and move more quickly when a mate has been found. The engine appears a little more intelligent to the user, and wastes slightly less of the user's time, but it won't play even a single Elo point stronger. "```

http://www.talkchess.com/forum/viewtopic.php?topic_view=threads&p=255560&t=26995

This is an example of when common sense is over ruled by an old and established rule that has absolutely no merit.  

Better luck next time @vondele

**Pull request closed without merging**
