### PR TITLE
Reduce tt looping

### PR DESCRIPTION
**Pull request by jcalovski**
Consolidate tt probe work into a single loop.

Results for 50 tests for each version:

            Base      Test      Diff      
    Mean    1737887   1745378   -7491     
    StDev   17466     17606     2638      

p-value: 0.998

No functional change.

Resolves #642

### CODE REVIEW

**Comment by mcostalba** [comment]
This was slower last time I tried...

**Comment by jcalovski** [comment]
It seems good on the profile build for me

**Comment by joergoster** [comment]
gcc-Version 5.3.0 20151204 (Ubuntu 5.3.0-3ubuntu1~14.04)
25 runs each

make build ARCH=x86-64-modern
make strip
```
Engine                          | Nodes/second
test-TT                         | 1597178.0 +- 2068.16
base-TT                         | 1598908.0 +- 3179.24

Differences                     | -1036.0 +- 2132.0
Variance of the mean            | 426.4 ( -41.16 %)
Speed up                        | -0.06 %
```

make profile-build ARCH=x86-64-modern
make strip
```
Engine                          | Nodes/second
test-TT-pgo                     | 1825572.0 +- 6625.04
base-TT-pgo                     | 1820618.0 +- 2953.58

Differences                     | 4503.0 +- 3705.0
Variance of the mean            | 741.0 ( 16.46 %)
Speed up                        | 0.25 %
```

A small speedup for the pgo-build.

**Comment by mstembera** [comment]
Here is what I get on Win-64 mobile i7 gcc 5.3.0  make build ARCH=x86-64-modern COMP=mingw
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1007783   1012651   -4868     
    StDev   36540     34786     6719      

p-value: 0.766
speedup: 0.005
```
Bit surprising since the replacement policy now has to execute 3 times instead of just 2.

**Comment by zamar** [comment]
Can people please provide more benchmarks before we do the final call.

This one is not so clear.

**Comment by jcalovski** [comment]
@zamar IMO regardless of speed this is still a subtle non-functional simplification in an important area and so should be accepted.

**Comment by CoffeeOne** [comment]
Bench from my workstation: profile-build, modern, 100 runs each:
1 is corresponding master, 2 is test version:
Build Tester: 1.4.6.0
Windows 10 (Version 10.0, Build 0, 64-bit Edition)
AMD FX(tm)-9590 Eight-Core Processor           
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: Yes
CPU Warmup: Yes
Command Line: bench 16 1 16 default depth
Tests per Build: 100
ANOVA: n/a

                Engine# (NPS)                     Speedup     Sp     Conf. 95%    S.S.
1  (1.827.114,8   ) ---> 2  (1.827.005,0   ) --->  0,006%  5.836,9      No        No 

Further remark: These bench runs are really horrible, it is necessary, to not touch the computer at all during the run, otherwise results are crappy, even with 100 runs each.

so with profile build on this machine, the result is absolutely identical.

**Comment by zamar** [comment]
In my laptop when testing *non-profile build*, this is around 1% slowdown.

While I understand that a clever profiler can probably improve the situation, so that there is no slowdown, I think that we shouldn't be counting on too much on that. E.g. in next GCC-version things may be different.

Also the problem is that comparing different profile-builds using benchmark is known to be unreliably as profile builds are non-deterministic, and some speed changes are only by chance.

If this was a big simplification, I might take a different stand, but based on evidence presented so far, my decision is to reject the patch.

I'll leave this pull open for a while though if there is a need for further discussion...

Also I'm always willing to reconsider, if there are convincing arguments to do otherwise.

**Pull request closed without merging**
