### PR TITLE
tweak1

### PR DESCRIPTION
**Pull request by Vizvezdenec**
Tweak on top of latest elo gain by snicolet
STC
http://tests.stockfishchess.org/tests/view/5b830a810ebc5902bdbb7e9c
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 27797 W: 6113 L: 5842 D: 15842 
LTC 
http://tests.stockfishchess.org/tests/view/5b831f2c0ebc5902bdbb8038
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 13655 W: 2294 L: 2099 D: 9262 
I think that more elo can be found in tweaks of this parameters so I plan to further do some "hand-tuning", including increasing/decreasing ratio of 2 constants and making malus assimetric to 0.
Thx to @AndyGrant for helping with github and @jerrydonaldwatson for original idea.

Bench: 4172767

### CODE REVIEW

**Comment by Vizvezdenec** [comment]
And special thx to @AndyGrant for guiding me thru all my github troubles and his patience.

**Comment by Vizvezdenec** [comment]
Sorry but I have 0 idea why this builds fail so I will need some help :)

**Comment by Rocky640** [comment]
Build fail because you did not provide the bench number in the comment here:
https://github.com/official-stockfish/Stockfish/pull/1748/commits/ac529293ff7a08d80006131aaf6e8407b99baed9

**Comment by Vizvezdenec** [comment]
@Rocky640 and how to do it? I can't find a place to write the bench number :(

**Comment by Vizvezdenec** [comment]
I think I found the way https://help.github.com/articles/changing-a-commit-message/
Will do this at evening.

**Comment by Vizvezdenec** [comment]
Sorry but I was unable to fix checks with failing builds, so will wait for maintainers... :(

**Comment by NickolasReynolds** [comment]
Have no fear, Mindbreaker1, English is my native language. Congratulations on learning a new word! Since malus is unfamiliar to you, you may be interested in further reading: [http://languagelog.ldc.upenn.edu/nll/?p=867](http://languagelog.ldc.upenn.edu/nll/?p=867)

**Comment by MichaelB7** [comment]
Geez, do I detect malice!  -  for the record , “malus” was never a word in American lexicon - the fact that it was considered as “word of the year” by my alma mater  in 2008 will tell you it was hardly used if at all.  It appears to have made it across the big pond by non-American English speakers.  In how Stockfish uses the word,  any American would use the word “penalty”.   And I’m fine using the word “malus” here  , it’s understandable and it’s usage here reflects the European origins of Stockfish.   No need to direct any malice towards anyone. 😊

**Comment by snicolet** [comment]
Merged via 6307fd08e6e8c315802301fd35b22ca2a67071a9, congrats!

I have renamed the variable to "bonus" and changed the sign.

**Comment by Stefano80** [comment]
Hi Michael, you can trigger the build manually on Travis on your repo instead of close/reopen

**Pull request closed without merging**
