### PR TITLE
Introduce coordination between searching threads

### PR DESCRIPTION
**Pull request by vondele**
this patch improves threading performance by introducing some coordination between threads.

The observation is that threading is an area where a lot of Elo can potentially be gained:
https://github.com/glinscott/fishtest/wiki/UsefulData#elo-from-threading
At STC, 8 threads gain roughly 320 Elo, vs sequential at the same time,
however, loses 66 Elo against a single thread with 8x more time.
This 66 Elo should be partially recoverable with improved threading.

To improve threading, this patch introduces some LMR at nodes that are already being searched by other threads.
This requires some coordination between threads, avoiding however synchronisation.
To do so, threads leave a trail of breadcrumbs to mark the nodes they are searching.
These breadcrumbs are stored in a small hash table, which is only probed at low plies (currently ply < 8).

A couple of variants of this patch passed both STC and LTC threaded tests.
I picked the simpler, more robust version.
I expect that further tests can find further improvements.

STC (5+0.05 @ 8 threads):
LLR: 2.95 (-2.94,2.94) [0.50,4.50]
Total: 26209 W: 5359 L: 5079 D: 15771
http://tests.stockfishchess.org/tests/view/5d0a9b030ebc5925cf0a8e6f

LTC (20+0.2 @ 8 threads):
LLR: 2.96 (-2.94,2.94) [0.00,3.50]
Total: 34832 W: 5650 L: 5382 D: 23800
http://tests.stockfishchess.org/tests/view/5d0c67a20ebc5925cf0aafa7

other passed/tested variants:
http://tests.stockfishchess.org/tests/view/5d0a9b030ebc5925cf0a8e6f
http://tests.stockfishchess.org/tests/view/5d0c67ca0ebc5925cf0aafa9
http://tests.stockfishchess.org/tests/view/5d0c67810ebc5925cf0aafa3
http://tests.stockfishchess.org/tests/view/5d0958ca0ebc5925cf0a74c6

For the sequential code there is no change in bench, and an earlier version of this patch passed a non-regression test.
STC (10+0.1 @ 1 thread)
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 10471 W: 2364 L: 2220 D: 5887
http://tests.stockfishchess.org/tests/view/5d087ee20ebc5925cf0a6381

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
could you please run a fixed games test: 20k games, ltc (60 sec), 4 threads.

this patch is very sizeable so it's important to understand what it really brings on the table.

**Comment by vondele** [comment]
I would rather run with more threads, what about running 30 threads 20sec, the framework should be able to deal with it.

**Comment by vondele** [comment]
http://tests.stockfishchess.org/tests/view/5d107e7f0ebc5925cf0aeb00

**Comment by xoto10** [comment]
Nice PR! :-)
You've got a tab character in line 1062

**Comment by mcostalba** [comment]
@vondele sure, but I am more interested in a typical home-desktop case:  20k games, ltc (60 sec), 4 threads

**Comment by vondele** [comment]
@mcostalba to resolve the gain for just 4 threads 20000 games won't be enough, the gain at 8 threads was about 2Elo, at 30 threads it seems around 8 Elo.  It is reasonable to assume the gain is proportional to log2(#threads) (like Elo), so roughly 1 Elo at 4 threads. To measure that reliable we need ~160k games.

Having said that, the core count keeps growing quickly, a single socket 32 threads CPU will launch in the consumer market soon after summer (advertised for $799). High end servers will have a multiple of that. I think we should aim for that.

**Comment by Vizvezdenec** [comment]
Nowadays with HT typical desktop intel CPU is closing to 6-8 threads.
Also it's really hard to measure any gain on 4 threads imho.
Let's say your test on LTC and 4 cores shows +1/-1 +/- 4 elo, what would this mean? (and I'm giving like 90% of it finishing like this tbh).

**Comment by Alayan-stk-2** [comment]
Result of the 60+0.6 th4 test : ELO: -0.83 +-2.6 (95%) LOS: 26.3% (this is inconclusive because of the error bars, especially as the elo gain from better multi-threading on 4 threads only is expected to be small).

Result of the 20+0.2 th30 test : ELO: 4.01 +-2.5 (95%) LOS: 99.9% (clear improvement)

Considering these tests and the previous tests, the patch definitely makes SF stronger with many threads.

**Comment by snicolet** [comment]
Looks good to me, especially with the 20+0.2 th30 test result.

**Comment by lucasart** [comment]
@mcostalba has a point. This does not scale. You can argue that the standard use case is not 4 but 8 threads. And the counter argument is that 60+0.6 is not the standard use case. You will most likely see the same null effect with 8 threads in 120+1.2.

20+0.2 th 32 is completely artificial

**Comment by vondele** [comment]
The argument is not what the standard use case is. The argument is that as we use more threads the Elo loss is larger compared to the equivalent longer single threaded run. If the patch increases the parallel efficiency by the same % at any thread count, the Elo gain is larger for more threads. It could be the patch doesn't scale with TC, but I don't think there is an a priori reason for this.

**Comment by Vizvezdenec** [comment]
If this is the case we shouldn't test anything at all I guess since gains on 30 minutes/move can be 0.

**Comment by mcostalba** [comment]
You have done a non regression test for 1 thread case. Could you please run a non regression for 2 thread case too? Thanks.

**Comment by vondele** [comment]
started 
http://tests.stockfishchess.org/tests/view/5d18c6ea0ebc5925cf0b9568
and 
http://tests.stockfishchess.org/tests/view/5d18c6c30ebc5925cf0b9566

**Comment by MJZ1977** [comment]
I think that introducing coordination between threads is a good idea. We still don't know the potential of the idea with more ideas coming (and more CPU cores too).
Of course at higher TC, we will have less collisions between threads and this patch will be less efficient but lower TC are important too. We have just to verify that there is no significant regression is introduced to higher TC.

**Comment by vondele** [comment]
passed the additional non-regression tests at 2 and 4 threads 20+0.2 TC. The code was rebased on master prior to testing.

2 threads:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 218863 W: 40927 L: 41153 D: 136783 
http://tests.stockfishchess.org/tests/view/5d18c6c30ebc5925cf0b9566

4threads:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 16839 W: 3017 L: 2889 D: 10933 
http://tests.stockfishchess.org/tests/view/5d18c6ea0ebc5925cf0b9568

**Pull request merged**
