### PR TITLE
Tune null search reduction

### PR DESCRIPTION
**Pull request by lucasart**
**STC**

    LLR: 2.96 (-2.94,2.94) [-0.50,4.50]
    Total: 107289 W: 21851 L: 21325 D: 64113

**LTC**

    LLR: 2.96 (-2.94,2.94) [0.00,5.00]
    Total: 83837 W: 14378 L: 13916 D: 55543

bench 7604776

### CODE REVIEW

**Comment by mcostalba** [comment]
Instead of

3 + depth / 4 

We now have:

3.2 + depth / 3.8

**Comment by lucasart** [comment]
@zamar @glinscott: can you have a look ? I would like to test the 3 parameter tuned model against the new master: http://tests.stockfishchess.org/tests/view/54a895570ebc597e33447ece

**Comment by zamar** [comment]
It is a tuning patch and passed [0, 5], so

Approved.

**Comment by zamar** [comment]
@lucasart: You can test the 3 parameters version against 2 parameters even before 2 param version is committed. 

However I see one version where you hard coded max reductions to 10 plies. This is risky and I wouldn't recommed you doing that... The rule will kick in somewhere around depth 30, so we have no way of measuring the impact and it'll only affect very long time controls.

**Comment by glinscott** [comment]
Looks good!

**Pull request closed without merging**
