### PR TITLE
Improve spelling/grammar

### PR DESCRIPTION
**Pull request by BKSpurgeon**

### CODE REVIEW

**Comment by Rocky640** [comment]
Please leave this one for a while. We can improve a few comments as well.

**Comment by BKSpurgeon** [comment]
@syzygy1  :+1: 

chrs :P

**Comment by snicolet** [comment]
Merged with https://github.com/official-stockfish/Stockfish/commit/0f6f42cd8334603f6fdf22645c5860c2ce6bd82f

It worked :-p

**Comment by Rocky640** [comment]
However, it does not show like the other commits.
image

**Comment by snicolet** [comment]
Yes, I know, and I know what I will change next time in my Github->git->Github workflow.

I decided to begin with a light non-functional-change commit just for that reason, that it wouldn't be too irrespectful if something went strange...

**Comment by syzygy1** [comment]
@snicolet Don't forget to remove SF's version number in misc.cpp.

**Comment by snicolet** [comment]
Ah yes, thanks!

**Pull request closed without merging**
