### PR TITLE
Remove scalefactor dependency

### PR DESCRIPTION
**Pull request by jcalovski**
STC
http://tests.stockfishchess.org/tests/view/5764539e0ebc5972faa160a4
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 43878 W: 8289 L: 8208 D: 27381

LTC
http://tests.stockfishchess.org/tests/view/5764f0130ebc5972faa160c9
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 39338 W: 5408 L: 5313 D: 28617

bench: 7977279

### CODE REVIEW

**Comment by snicolet** [comment]
Congrats! It will now be easier to ameliorate the opposite colored bishop knowledge of SF.

**Comment by jcalovski** [comment]
@snicolet yes! Really looking forward to improving and expanding the scalefactor component of things

**Comment by joergoster** [comment]
Congrats!

**Comment by DamasClasicas** [comment]
Congratulations!!

**Comment by mcostalba** [comment]
Merged with 09efbf915e8f09d

**Pull request closed without merging**
