### PR TITLE
New Net Proposal

### PR DESCRIPTION
**Pull request by mathsy**
This is a pull request with a new net. The tests can be found here:

https://tests.stockfishchess.org/html/live_elo.html?603898727f517a561bc4a3ed //STC Test (+4,5 ELO)
https://tests.stockfishchess.org/html/live_elo.html?603529b87f517a561bc4a177 //LTC Test (+0,4 ELO)

I found that a bit more hash improves the strength of this net by a lot.
The LTC test has been made without increased Hash.

The net was trained based on the old net by a total of 1B training positions, where about 50M positions were opening moves from ply 4 to ply 14. That means that this net is a bit more opening specialized. All of the positions were depth 5. So a bigger advantage is made by shorter time controls, because (logically) with depth 1 an evaluation depth of 5 is immediatly reached, but also at long analysis time, the evaluation depth is a bit increased.

The net is just like the size before.

WHAT'S THE NEXT CHALLENGE?
Well, I think that the maximum strength of this net size hasn't been reached even closely. My opinion is that we are in a local minimum. My next project will be to train a complete new net just with data generated by the new net, if this one is the new one or not.

I would be proud if this change will be taken over by the official stockfish team. This are my two cents and a big thank you to the whole stockfish developer team for developing this engine. I want to apologize because I made the LTC test before the STC test, but I don't have much experience with fishtest before.

Best regards,
MiauiKatze alias Raberger Raphael from Austria

### CODE REVIEW

**Comment by locutus2** [comment]
I repeat here my comment from the other PR https://github.com/official-stockfish/Stockfish/pull/3371:

1.    the LTC doesn't pass, so i see no reason to commit this
2.   the increased hash size plays also no role because only the old net used 86 MB hash in the STC test. The new net used the default 16 MB (as i already said at the commit comment in your repo).

The second point is addressed. But this new net passed not LTC (at least not at the given test, perhaps there are some other). So no reason to commit.

**Comment by snicolet** [comment]
@mathsy @MiauiKatze
Hi Raphael,

I see that you are testing a new net in the following tests: https://tests.stockfishchess.org/tests/view/603a23e9e8971688486ffcc9
https://tests.stockfishchess.org/tests/view/603a22e3e8971688486ffcb9

However, then bench of your nnue2 branch is wrong, as can be seen in the following page:
https://tests.stockfishchess.org/actions

**Comment by BM123499** [comment]
Just to notify: I noticed that this proposed net just differ from current net by 57 bytes.
I used this command to check: `cmp ./nn-62ef826d1a6d.nnue ./nn-0e698aa9eb8b.nnue -l`

**Comment by vondele** [comment]
since the new net didn't pass LTC we won't merge it. 

However, in principle it is OK to tune a small fraction of the net to try to improve it.

**Pull request closed without merging**
