### PR TITLE
Time management fixes

### PR DESCRIPTION
**Pull request by mstembera**
Suggested by Joona and Lucas here:
https://github.com/official-stockfish/Stockfish/pull/456

### CODE REVIEW

**Comment by lucasart** [comment]
I would suggest a quick test, at fast tc, to make sure there's no problem. How about 20k games in 5+0.05 ?

**Comment by mstembera** [comment]
Sure.  Scheduled
http://tests.stockfishchess.org/tests/view/561cb6450ebc597e4f23e890

**Comment by mstembera** [comment]
Result: 
ELO: -7.47 +-3.1 (95%) LOS: 0.0%
Total: 20000 W: 3996 L: 4426 D: 11578
Please advise.

On a related note, I tested this
http://tests.stockfishchess.org/tests/view/5619864d0ebc597e4f23e7bc
patch by Vadim w/ [0,5] as an elo gain in the main branch and it finished yellow.
I think it also fixes our time out issues.  Do you think it's worth further testing as a fix?

**Comment by jhellis3** [comment]
I have pushed a test which implements Vadim's idea with further simplifications to the code, and included a limiter so that people using real world time controls never see/notice what is going on.

https://github.com/jhellis3/Stockfish/commit/34ebdbc6cd744d6917c696384d71969787ac2411

**Comment by lucasart** [comment]
@mstembera: This patch is fundamentally correct. A min is a min, not an add-on. No doubt about that.

The problem is that everything was tuned to death with the wrong code. So when you fix the wrong code, you lose elo, because the wrong code was creating a biais, and hiding problems in the time manager...

To cut a long story short, in order to commit this, one has to also retune the time manager. Quite an expensive undertaking...

**Comment by zamar** [comment]
As Lucas said, only way forward is to fix the issue and retune.

The patch is not committable as it currently stands, unfortunately.

**Comment by mstembera** [comment]
Makes sense.  The assert could still be applied but I'm fine either way.

**Comment by lucasart** [comment]
Actually, if we're going to have to retune the time manager, we may as well get rid of this min thinking time completely. I really don't like the idea of having a hardcoded value, independant of the time control. maybe a fraction of the remaining time should be used as min thinking time instead?

**Comment by mstembera** [comment]
I think we could get rid of it and just make sure we finish depth 1.  That's the true minimum.

**Comment by lucasart** [comment]
yes. but i think the reason for this min thinking time, is also to provide for the case when the time manager goes rogue (and it does, otherwise this min wouldn't be useful).

**Comment by mstembera** [comment]
I didn't know it can go rouge in a way to be too short but if so then I like your idea of a minimum fraction.

**Comment by ajithcj** [comment]
@mstembera There was an test to remove Min thinking time, but it proved expensive at low TC:
http://tests.stockfishchess.org/tests/view/53f3d7dc0ebc5927a2193fc1
http://tests.stockfishchess.org/tests/view/53f3d7ab0ebc5927a2193fbf

But using a fraction of available time probably makes more sense that a hardcoded value.

**Comment by lucasart** [comment]
That's the closest I got to fixing this. It's ok in 10+0.1, but regressive in 15+0:
http://tests.stockfishchess.org/tests/view/562033130ebc590be39e19f5
http://tests.stockfishchess.org/tests/view/5620d8b70ebc590be39e1a41

**Pull request closed without merging**
