### PR TITLE
Add bonus for pawn attack threats

### PR DESCRIPTION
**Pull request by locutus2**
Latent pawn attacks: Add a bonus to safe pawn pushes which attacks an enemy piece.
Based on an idea of Lyudmil Tsvetkov.

STC:
LLR: 2.95 (-2.94,2.94) [-1.50,4.50]
Total: 7925 W: 1666 L: 1537 D: 4722

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,6.00]
Total: 40109 W: 6841 L: 6546 D: 26722

Bench: 7323965

### CODE REVIEW

**Comment by locutus2** [comment]
The measurement between my passed versions indicate that my first version is around 1 elo stronger, so i do a pull request for this.

**Comment by mcostalba** [comment]
Congrats Stefan!

Just 2 comments. The first is regarding readibility: code is a bit complex
so I'd rewrite in this way:

// Add bonus for safe pawn pushes which attacks an enemy piece

    b = pos.pieces(Us, PAWN);

    b = shift_bb<Up>(b | (shift_bb<Up>(b & TRank2BB) & ~pos.pieces()));

    b &=  ~pos.pieces()

        & ~ei.attackedBy[Them][PAWN]

        & (ei.attackedBy[Us][PAWN] | ~ei.attackedBy[Them][ALL_PIECES]);


    b = (shift_bb<Left>(b) | shift_bb<Right>(b))

       & pos.pieces(Them)

       & ~ei.attackedBy[Us][PAWN];


    if (b)

        score += popcount<Max15>(b) * PawnAttackThreat;

Where

const Bitboard TRank2BB = (Us == WHITE ? Rank2BB  : Rank7BB);

The second one is that you should NOT consider pawns on 7th rank, so
the first line should be:

b = pos.pieces(Us, PAWN) & ~TRank7BB;

where

const Bitboard TRank7BB = (Us == WHITE ? Rank7BB  : Rank2BB);

Actually bench does not change, becuase the Left / Right shifts zero
out the corresponding bits in the bitbaord, but I'd suggest to add it
for consistency and clear reading.


P.S: I guess now your next step is to tune PawnAttackThreat, right?

P.P.S: It is interesting that between this version and the general one
there is no difference, it means that all the value of this idea is
related to pawns pushes and not to other latent threats.

**Comment by locutus2** [comment]
@mcostalba 
Your proposal seems good so i integrate it.

Yep i will doing tuning, but not now, because i prepare a patch which use the minor attack on queen concept from the same talkchess tread.
If this succeds too i prefer to tune the both paramters together.

**Comment by mcostalba** [comment]
Are you sure is the right approach?

What about if the patch succeeds just because pawn attacks are untuned?

I think an added feature should prove good against already well tuned
master to avoid artifacts.

**Comment by locutus2** [comment]
@mcostalba 
This could be a problem but its not likely because there probable only slightly correlated. Only in the case of a queen which could be attacked by a pawn and a bishop/knight at same time an overlap exists.
But as doubts exists i tune this patch first. If a later minor attack patch is succesful a common tuning can be done.

**Comment by glinscott** [comment]
Nice job!  This is quite an interesting idea, and it's passed the tests.  I think it's ready to go in, and if the tuning run turns out to better, then remove it then.

**Comment by zamar** [comment]
approved.

**Pull request closed without merging**
