### PR TITLE
Improving Simplification

### PR DESCRIPTION
**Pull request by VoyagerOne**
Remove unnecessary logic.
Non functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
I don't understand why that condition should be useless, care to explain?

**Comment by mcostalba** [comment]
Merged with 09efbf915e8f09dbca

**Comment by mcostalba** [comment]
Sorry, I have closed the wrong one. Reopening...

**Comment by VoyagerOne** [comment]
@mcostalba 
VALUE_NONE is the highest possible value (32002).

ss->staticEval >= (ss-2)->staticEval will always be true if ss->staticEval =VALUE_NONE

**Comment by Kingdefender** [comment]
It no longer works as intended if VALUE_NONE is for instance the smallest possible value, and the reason for removing it is not clear for those who do not know the value. I don't find it clearer with the condition removed.

**Comment by jjoshua2** [comment]
Maybe it can be changed to a comment then? I agree the explanation is useful.

**Comment by mcostalba** [comment]
It is bad programming practice to rely on the (hidden) value of a special
constant like VALUE_NONE.

We should not do it.

The values behind constants are supposed to be functionality-independent,
so these kind of tricks are very fragile and are prone to very subtle and
difficult to find bugs.

**Comment by stockfishdeveloper** [comment]
@mcostalba I don't understand what you're talking about? The very point of constants is to be able to rely on the value of a symbol. A constant is a constant. 

However, I don't understand why VALUE_NONE would equal the largest possible value instead of 0 as the name would suggest. 

Am I missing something in either of these observations?

**Comment by MichaelB7** [comment]
+1 - I have never seen a more obsfucated simplification.

**Comment by VoyagerOne** [comment]
@stockfishdeveloper 
VALUE_ZERO = 0
VALUE_NONE means we don't know the value.  So it has to be outside the value range.

@mcostalba @jjoshua2 
We did exactly that for SE

    singularExtensionNode =   !rootNode
                           &&  depth >= 8 * ONE_PLY
                           &&  ttMove != MOVE_NONE
                       /*  &&  ttValue != VALUE_NONE Already implicit in the next condition */
                           &&  abs(ttValue) < VALUE_KNOWN_WIN
                           && !excludedMove // Recursive singular search is not allowed
                           && (tte->bound() & BOUND_LOWER)
                           &&  tte->depth() >= depth - 3 * ONE_PLY;

**Comment by VoyagerOne** [comment]
It might be more clear if VALUE_NONE is relabeled as VALUE_UNKNOWN.

**Comment by stockfishdeveloper** [comment]
Yes, whoever named that variable to VALUE_NONE probably didn't think it would be used this way. 
IMO, VALUE_NONE should mean "no value" or 0.

**Comment by KassiasGrandiel** [comment]
@VoyagerOne I agree!

**Comment by mcostalba** [comment]
@VoyagerOne I missed the commented out code in singularExtensionNode definition. 

I still think this usage of special constants is tricky and should be avoided, we are not talking of something like MAX_THREADS or ARRAY_DIM that define a numeric value, and so it is correct to use them as numbers (comparing, etc.). In our case VALUE_NONE does not and should not imply any specific numerical value, the fact that is higher than VALUE_KNOWN_WIN is fully incidental and we should not rely upon this.

Said the above, because we already use that trick in singularExtensionNode, for consistency we cannot veto using it here, but please comment out the line, do not remove it. Something like:

`/* || ss->staticEval == VALUE_NONE Already implicit in the previous condition*/
`

**Comment by VoyagerOne** [comment]
See:  https://github.com/official-stockfish/Stockfish/pull/707

**Pull request closed without merging**
