### PR TITLE
Rank threats on pinned pawns 

### PR DESCRIPTION
**Pull request by locutus2**
Add for pinned pawns half of the standard rank based threat bonus.

STC:
LLR: 2.97 (-2.94,2.94) [0.00,5.00]
Total: 44010 W: 9987 L: 9635 D: 24388 
http://tests.stockfishchess.org/tests/view/5b58aa780ebc5902bdb88c7a

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 29475 W: 5089 L: 4847 D: 19539 
http://tests.stockfishchess.org/tests/view/5b58b56c0ebc5902bdb88f37

Bench: 4503866

### CODE REVIEW

**Comment by locutus2** [comment]
I have another promising thread and pinned pieces patch, for which i stopped LTC:
http://tests.stockfishchess.org/tests/view/5b58db500ebc5902bdb892f1

This test is at LLR 1.31 and had the same number of games as the patch of this PR. Also the PR shows the better scaling. So this PR seems better and the other patch will be retested against this PR.

**Comment by snicolet** [comment]
Merged via a4eda3056ef7f6f69ae15925255621cb32443de9, congrats again :-)

**Comment by Vizvezdenec** [comment]
I think with this patch (and if xoroshiro patch passes) it's about time to do a regression test since it was 5 elo gainers since the last one already.

**Comment by syzygy1** [comment]
@locutus2 @snicolet 
The division of a Score by an integer is rather expensive:
https://github.com/official-stockfish/Stockfish/blob/2660a9145ef23bb51daa4aa35ff502c5f935c9aa/src/types.h#L336-L339
It should be possible to remove it by replacing ThreatByRank by (say) SmallThreatByRank.

**Comment by Rocky640** [comment]
@syzygy1 maybe this line is not executed very often. 
An experiment could be to replace ThreatByRank (currently S(16, 3))
with S(8, 2) and multiply by 2 instead on the other lines.

However, if pinning an advanced pawn is really a good thing, then 
a ThreatByRankPawn = S(2, 8) (or some endgame bonus) would be worth a test

**Pull request closed without merging**
