### PR TITLE
Prune RootNode in Step 7 (8080602)

### PR DESCRIPTION
**Pull request by lucasart**
**STC:** http://tests.stockfishchess.org/tests/view/54b796ea0ebc5964db6b6d6d
**LTC:** http://tests.stockfishchess.org/tests/view/54b8fcbb0ebc597a947a50bb

Please read discussion in patch comments.

### CODE REVIEW

**Comment by mcostalba** [comment]
As already commented on the patch comments, as of today, nobody has still
understood _when_ and _why_ this patch introduces a functional change.

Because currently we never return from root search without updating
rootmoves, I think it is important to understand what we are doing here,
what kind of scenario this patch affects.

**Comment by zamar** [comment]
I'll take a look at this during weekend, but this is not material for SF6.

These kind of patches which are very difficult to verify and understand should be committed in the beginning of SF7 development rather than at the end of SF6 development.

**Comment by glinscott** [comment]
What is the intent behind this patch?  Is it just to remove the !RootNode condition?  I think that condition just makes things clearer, rather than allowing "pruning" the root node, which never makes any sense.  Yes, the aspiration saves us here, but that's a side effect, not a desired outcome.

I don't think we should merge this.

**Comment by lucasart** [comment]
@mcostalba: Here's the shortest repro I can get of the `assert(!RootNode)` firing:

    uci
    setoption name SyzygyPath value /home/lucas/Chess/syzygy
    setoption name SyzygyProbeLimit value 5
    isready
    ucinewgame
    position fen rnbqk1nr/ppppppbp/8/6p1/1P6/2P5/P1QPPPPP/RNB1KBNR b KQkq - 0 1 moves d7d5 d2d4 e7e5 e2e4 e5d4 g1f3 g8e7 c1g5 h7h6 g5d2 e8g8 f1d3 b8c6 b4b5 d4c3 d2c3 g7c3 c2c3 d5e4 d3e4 e7d5 c3c4 d5b6 c4c1 f8e8 e1g1 e8e4 b5c6 e4e6 f1d1 d8e7 c1f4 e6c6 b1d2 c6f6 f4d4 f6d6 d4f4 b6d5 f4d4 c8f5 d1e1 e7f6 e1e5 c7c5 d4c4 d5b4 c4f4 d6d2 f4d2 b4d3 e5e1 d3e1 a1e1 f5e6 f3e5 a8d8 d2e3 b7b6 e5c6 d8d7 c6b8 d7d4 b8c6 d4a4 a2a3 g8g7 e3d3 e6f5
    go wtime 505 btime 889 winc 40 binc 40
    position fen rnbqk1nr/ppppppbp/8/6p1/1P6/2P5/P1QPPPPP/RNB1KBNR b KQkq - 0 1 moves d7d5 d2d4 e7e5 e2e4 e5d4 g1f3 g8e7 c1g5 h7h6 g5d2 e8g8 f1d3 b8c6 b4b5 d4c3 d2c3 g7c3 c2c3 d5e4 d3e4 e7d5 c3c4 d5b6 c4c1 f8e8 e1g1 e8e4 b5c6 e4e6 f1d1 d8e7 c1f4 e6c6 b1d2 c6f6 f4d4 f6d6 d4f4 b6d5 f4d4 c8f5 d1e1 e7f6 e1e5 c7c5 d4c4 d5b4 c4f4 d6d2 f4d2 b4d3 e5e1 d3e1 a1e1 f5e6 f3e5 a8d8 d2e3 b7b6 e5c6 d8d7 c6b8 d7d4 b8c6 d4a4 a2a3 g8g7 e3d3 e6f5 d3g3 a4g4
    go wtime 461 btime 844 winc 40 binc 40

Note that you cannot reproduce ex-nihilo, with the last position+go command only.

Your assumption that the TT refined eval is the score of the last iteration must be wrong in this case. Which points straight to our complex TT replacement scheme. My *guess* is that when the previous iteration was stored in the TT, and then read again, it's not the same one that was read. I'm not familiar with the new TT implementation, but can we have several TT entries for the same position coexist ?

**Comment by lucasart** [comment]
@glinscott: the idea of the patch is simple. treat the root node like any other PV node. if we are going to fail high, and we can skip a search to find out, then do it, and move on to the next aspiration iteration without wasting time. admittedly this happens rarely, but it does make sense.

**Comment by zamar** [comment]
I can see valid arguments on both sides:

- Gary has a point that pruning root node does not sound sensible.
- Lucas is looking for perfect symmetry and wants to treat root node as any other node, relying on aspiration window to do a research.

I can see it work both ways, so my stance is pretty neutral. But in any case, this is not for SF6...

**Pull request closed without merging**
