### PR TITLE
Use more time if losing - how to progress?

### PR DESCRIPTION
**Pull request by xoto10**
It appears that stockfish could sometimes benefit from moving slower when in tricky positions - moving too quickly and making a fatal mistake seems like a bad idea. This idea was tuned at LTC and the following initial test at LTC has passed:

Initial LTC:
LLR: 2.94 (-2.94,2.94) <0.50,3.50>
Total: 61480 W: 2426 L: 2243 D: 56811
Ptnml(0-2): 31, 1930, 26628, 2127, 24
https://tests.stockfishchess.org/tests/view/6083d4e295e7f1852abd2786

How should we progress from here?

I can run STC, but based on earlier tests I suspect that will fail, it seems to need either the longer tc with higher quality games or the specific tc it was tuned at (no idea which part is the significant one).

[ Obviously this branch is messy at the moment, but I see no point in tidying it up yet, just creating the PR to get discussion / direction from maintainers ]

Edit: Also thanks to @QuackQuackBlah for doing the first ltc tune :-) I was thinking of doing that after trying at 20+0.2 but it's possible I would have given up without trying ltc

### CODE REVIEW

**Comment by vondele** [comment]
I suggest the second test could be LTC SMP, to see if it works under those conditions as well.

**Comment by locutus2** [comment]
@vondele 
That seems a good idea. I'am not a fan of committing patches which have only one passed test because we have an error of first and second order of 5% for our SPRT. One point of using normally a two stage testing is to avoid false positive better (the have to be two times lucky)

**Comment by vondele** [comment]
note that the chance of regression (<0 Elo) with the current SPRT testing setup based on normalized Elo is quite small. A 0 Elo patch has on 1.9% chance of passing a single LTC test. But yes, generally, patches should pass two tests.

**Comment by xoto10** [comment]
smp test failed - closing

**Pull request closed without merging**
