### PR TITLE
Tablebases root ranking

### PR DESCRIPTION
**Pull request by syzygy1**
This is my old root-ranking patch updated to current SF, for comparison with gcp's patch.
More changes, but also more deletions. The ranking code is much more straightforward than the current filtering code. has_repeated() is moved to position.cpp where it belongs.

If the root is a TB position, each root move is probed and assigned a TB score and a TB rank.
The TB score is the Value to be displayed to the user for that move (unless the search finds a mate score).
The TB rank determines which moves should appear higher in a multi-pv search. In game play, the engine will always pick a move with the highest rank.

Ranks run from -1000 to +1000:
901-1000: TB win
900: normally a TB win, in rare cases this could be a draw
1-899: cursed TB wins
0: draw
-1 - -899: blessed TB losses
-900: normally a TB loss, in rare cases this could be a draw
-901 - -1000: TB loss

Normally all winning moves get rank 1000 (to let the search pick the best among them).
The exception is if there has been a first repetition. In that case, moves are ranked strictly by DTZ so that the engine will play a move that lowers DTZ (and therefore cannot repeat the position a second time).

Losing moves get rank -1000 unless they have relatively high DTZ, meaning they have some drawing chances. Those get ranks towards -901 (when they cross -900 the draw is certain).

This patch corrects both MultiPV behaviour and "go searchmoves" behaviour.

### CODE REVIEW

**Comment by gcp** [comment]
The current code avoids spending any search effort on non-optimal moves when in normal (non Multi-PV mode). In my pull it's also done when MultiPV <= optimal moves.

It's not clear to me whether this proposal also preserves that behavior. This might be the PVLast logic but I'm not entirely clear what it does? Or maybe we don't actually need this behavior, as we'll always play the right move anyway?

**Comment by ceebo** [comment]
Here is my understanding of this code.

The rootMoves are sorted according to TB rank on line 1664/1665. This sorting will never be broken.

On line 351 (selDepth = 0) we will always have `PVFirst <= PVIdx < PVLast` and PVLast is either equal to the end of the rootMoves list or is the smallest integer such that `rootMoves[PVLast].TBRank < rootMoves[PVFirst].TBRank`.

On lines 856/857 we search all moves from `rootMoves[PVIdx]` up to before `rootMoves[PVLast]`. Or in words: skip all moves that are already proven worse due to previous searches (ie. those < PVIdx) and skip all moves that we know are worse due to TB Ranking (ie. those >= PVLast).

**Comment by gcp** [comment]
Thanks, that makes sense. PVLast indicates the last move which has a (TB) score equal or better than the worst move we had to search to satisfy the MultiPV count.

**Comment by syzygy1** [comment]
Exactly.

There might be a simpler way to implement the PVLast logic. I know that @ceebo's version does it differently.

**Comment by snicolet** [comment]
Thanks for the patch, I will look at it after the beginning of the TCEC super-finale.

In other words, I think that I will make a code freeze from now for a period of about 2-3 weeks for all the features related to tablebase, time management, etc, because I don't want to introduce any bug that we wouldn't have the time to fix before we sent the executable for the super-finale. Only the trivial usual evaluation or search patches during the freeze :-)

**Comment by snicolet** [comment]
I have merged Ronald's patch rather than Gian-Carlo's because Ronald's patch was a simplification in the number of lines.

@syzygy1 @gcp I had to do quite a bit of manual editing because of the merge conflicts. Could you check that the new multiPV behavior with tablebases is what you expected?

In particular, I had a small doubt about the call to `probe_dtz()` which is now in line 1473 of tbprobe.cpp, because of the change of the commit "Fix reported DTZ for mate-in-1-ply positions" which wasn't there when you originally wrote the ranking patch: has it any impact?
https://github.com/official-stockfish/Stockfish/blob/master/src/syzygy/tbprobe.cpp#L1473

And of course I think it would be nice to organize a match of this dev version of Stockfish against SF9, starting from positions which are close to using lots of tablebases, to hunt for tablebases bugs in the new algorithm -- I think that I saw some experiments like that in a talkchess thread a couple of months ago.

**Comment by syzygy1** [comment]
@snicolet
I'm not really a git/github expert, but I thought I had solved the conflicts (If there were any with this patch, I don't remember now). What I mean is that github seemed to report (a few days ago) that the PR could be merged without conflicts.

Maybe you applied my commits one by one, so that you did have intermediate conflicts? Perhaps that could have been avoided by squashing them into a single commit and splitting that one. But again, I'm no expert here. (Basically I'm just wondering if I could have done something better. I don't think I can easily squash the commits myself without creating a new branch and PR.)

**Comment by syzygy1** [comment]
I will check the code. The probe_dtz() change should make no difference.

**Comment by snicolet** [comment]
@syzygy1 Did you get the time to check to code, and confirm that I didn't break anything?

**Comment by syzygy1** [comment]
@snicolet 
The code looks fine, and everything works as expected on the positions I have tried.

**Comment by snicolet** [comment]
Thanks!

**Pull request closed without merging**
