### PR TITLE
[Cluster] merge master

### PR DESCRIPTION
**Pull request by vondele**
merges master, fixing a minor conflict.

No functional change.

### CODE REVIEW

**Comment by snicolet** [comment]
@vondele If you want, you could rebase your pull request on latest master and I would commit it in the cluster branch

**Comment by vondele** [comment]
@snicolet, welcome back, yes I can merge master once more.

**Comment by vondele** [comment]
@snicolet done...

**Comment by snicolet** [comment]
Merged in the cluster branch via 85327828c937c3dfa117ae96f58b833b9cd4719f , please tell me if everything is OK for you!

**Comment by vondele** [comment]
@snicolet thanks, yes, all looks fine.

**Pull request merged**
