### PR TITLE
Init movepick stage in constructor list where possible.

### PR DESCRIPTION
**Pull request by protonspring**
This is a non-functional tiny speed-up.

When MovePicker is initialized, stage is set to 0 in the initialization list because it is not included in the list.  Thus, usually, we set it to 0, then set it to a stage in the constructor implementation.  

This patch saves a few assignment operations by setting stage to a probably correct default value (instead of 0), then only assigning it to be different where necessary (if there are checkers).  There are a few more lines of code, but not really more code.  It is arguably more readable as well.

On my machine, executing (5 times) ./stockfish bench 128 1 7 current perft:
master averages 19650ms
patch averages 19540ms

### CODE REVIEW

**Comment by mcostalba** [comment]
@protonspring I apologize in advance with you because I am going to pick this one to make some arguments.

First of all a clarification of C++ standard: _stage_, being a primitive type, it is **not** zero initialized by default, but it is left uninitialized.

Admittedly C++ class member initialization is a mess: we have zero initialization, default initialization, value initialization and all of them differ in theory but in many cases are the same in practice, adding confusion to confusion. If you are interested, please read [this article](https://stackoverflow.com/questions/3127454/how-do-c-class-members-get-initialized-if-i-dont-do-it-explicitly) to get an idea.

Now the important topic: **Are micro-optimizations a good thing?**

If you have the chance to read the sources of an old engine, you will see tons of tricks, huge amount of (supposed) speed-ups and a mostly unreadable and unmaintainable code. Authors thought that the micro-opt was a clever way to make their engine stronger. Of course most of these tricks worked only in the head of their developers, but this is not the point.

Then came [Fruit](https://www.chessprogramming.org/Fruit), by Fabien Letouzey, and it was a revolution: a simple, small chess engine written in a clean and absolutely straightforward way....and it was stronger than his siblings!

Tord Romstad wrote [Glaurung](https://www.chessprogramming.org/Glaurung), taking **a very large** inspiration from Fruit, both in data structures, algorithms and code simplicity and eventually got an even stronger engine.

Stockfish, as you know, was born as a fork of Glaurung and we always kept the clean code and straightforward / no low level tricks as our mantra since then, and still we do because simple and readable code is the solid foundation above which you can build a fancy house.

So in our approach, micro-optimizations per se are **not** a good thing. They don't speed up anything sensible and the speed up when real is very compiler dependent. But they add complexity that instead is real and burdens the developers. 

So this means that we do not care about code efficiency? Well Stockfish is one of the fastest engines out there, so I guess we do. But we do not consider micro-optimizations per se: it should also be a code simplification and it should improve readability or it should be at least readability neutral.

Moreover **micro-optimizations cannot be proven in fishtest**, and this is a very strong point against them. I don't like micro-optimization patches because they take a lot of time and resources...to drop them down :-)

Someone could say that, although Fishtest is not suited, he could test in his local machine. But also this is not easy, the speed test is very tricky when you are talking of a possible 0.x% increase and the result is in many cases just noise, not reproducible on other computers. 

**So we simply do not apply micro-opt if are not also a code clean up.**


P.S: You used perft to measure the speed up, but MovePicker is not exercised by perft.

**Comment by protonspring** [comment]
The article was super helpful.  Thank you!  I was under the impression that if a member variable was not included in the initialization list, it was assigned 0, but that is NOT the case.  Even as old as I am, I learn something new every day.

**Comment by protonspring** [comment]
Oh. . could you please recommend a good way to test the speed of movepicker?  I didn't realize that perft does not test that part of the code.

**Comment by mcostalba** [comment]
@protonspring IMO nothing specific, just the full bench on default positions. Of course I would not expect to reliably detect any MovePicker speed change if not very big. You could think about some specific tests but IMO it would be misleading: MovePicker is just a part of a whole and speed improvments relative to MovePicker maybe are much smaller (and so useless) for the full engine.

**Pull request closed without merging**
