### PR TITLE
Fauzi b20

### PR DESCRIPTION
**Pull request by FauziAkram**
I am pretty sure that contempt 24 is way too high for SF, this have been seen in Tcec superfinal, and other occasions.

I have mainly 3 problems with current high contempt:

#1: I personally noticed in alot of occasions how this high contempt is making stockfish play sub-optimal moves, it might have been ok in the past, when the dominance of stockfish was undisputed, but now with Lcz strength increasing, that is not the case anymore, and with such a high contempt we are just hurting ourselves

#2: The method of determining which is the best contempt to use is far from optimized, when you check for the maximum value of contempt that does not regret against master, you are optimizing your score against weaker opponents, but you are not optimizing your real strength, neither in matches against yourself, neither against stronger opponents such as Lcz, the curve of strength vs contempt most likely is like the upper half of a circle, and by checking for the maximum value of contempt that does not regret against master, we are selecting the value at the end of that half circle, when its going down, and not the optimized value which is at the top of the curve

#3: I understand, that when we first implemented the contempt, there was only weaker engines, but now that there are engines stronger than stockfish, and soon there will be more than one, to choose the best contempt to use, we should not use only take into consideration the weaker engines, but we should take into consideration also the results against stronger engines, or at least against itself

So my goal is to bring down the contempt value, but in order to accomplish that, it will need to pass a 0,4 test, so I tuned alot of values to optimize them for the contempt = 20 , in order to pass a 0,4 test.

Passed STC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 11109 W: 2518 L: 2311 D: 6280

Passed LTC:
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 47503 W: 8022 L: 7717 D: 31764

Passed a non-regression test against master with contempt = 0
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 21419 W: 4222 L: 4101 D: 13096

VLTC check to check if it scales well:
ELO: 0.71 +-2.6 (95%) LOS: 70.1%
Total: 20000 W: 3030 L: 2989 D: 13981

Some extra tests:
Contempt 20 alone does not pass:
LLR: -2.95 (-2.94,2.94) [0.00,4.00]
Total: 34447 W: 7561 L: 7589 D: 19297

Evaluation values tuned alone does not pass:
LLR: -2.95 (-2.94,2.94) [0.00,4.00]
Total: 23195 W: 3918 L: 3997 D: 15280

If any extra test is needed let me know, or feel free to do it yourself.

### CODE REVIEW

**Comment by DamasClasicas** [comment]
Contempt 24, 20, or 16 is practically all the SAME. SF will have ''inflated high evaluations'' all the time.
The things are very simple and I do NOT understand why people get so complicated!

If opponent is **STRONGER** than SF, **DO NOT** use the contempt at all. 

If opponent is **WEAKER** than SF, **USE** the contempt!

**Contempt is ONLY designed to to get MORE points against WEAKER engines.**
Therefore it is strictly necessary to use it by default in order to obtain the BEST results in the ranking lists!

**Comment by Vizvezdenec** [comment]
I think that including contempt in combo tweaks is like opening the can with worms.
We all know that contempt 24 is probably like -0.3-0.5 elo to contempt 0 (it passed [-3;1] with big troubles on LTC and even failed it once).
So let's say we have contempt 20 which is 0.2 elo stronger.
Basically you can boost any combo probability passing by signifficant % with just adding contempt tweak.
After it we will change contempt to the highest value which will pass [-3;1] (which will still be near 24) and repeat this procedure. 
Basically with it you can even push some negative combos just with inclusion of contempt lowering - this loop needs to be broken somewhere. Currently we are breaking it at "don't allow contempt changes be part of a combo" (at least static part of contempt) and I think this is the way to go.
So I'm against (nothing personal) this patch.
All this arguements about contempt making sf play suboptimally in some positions are moot - even clean elo gains make sf play suboptimal moves sometimes because basically no patch improves play in every position.
Also impact of contempt between equal (or like 30 elo stronger engines) is 2-3 elo at best, which is not something that really matters at samples of TCEC superfinals and other stuff. I'm yet to see a single test that will show statistically signifficant superiority for contempt = 0 vs contempt = 24 vs leela, heck, I'm yet to see even 100 sample test at least once.

**Comment by FauziAkram** [comment]
"So let's say we have contempt 20 which is 0.2 elo stronger.
Basically you can boost any combo probability passing by signifficant % with just adding contempt tweak.
After it we will change contempt to the highest value which will pass [-3;1] (which will still be near 24) and repeat this procedure.
Basically with it you can even push some negative combos just with inclusion of contempt lowering - this loop needs to be broken somewhere."

Actually you are describing exactly the opposite, that loop can be done by increasing contempt, not by lowering it.

If I want to increase the chance of a tuning patch to pass, I just increase the contempt and test again, that will help, while decreasing contempt will not help.

It is helping in this patch just because those values was tuned using contempt of 20.

Anyway with the tests I have proven that this patch is stronger than master enough to pass tests at all time control, if you think that this needs to be rejected because it includes a change in the contempt feel free to reject it, but i think that this decision will make SF stalls in improvement in the long run.

**Comment by FauziAkram** [comment]
Also, if you say that " Currently we are breaking it at "don't allow contempt changes be part of a combo" "
My main intention of this patch was to lower the contempt, but obviously changing contempt alone will never pass a 0,4 test, so what are in your point of view, the ways that needs to be taken that can lead to a change of contempt ?
I know that TCEC, and chess.com tournaments are not our main and final goal, but if we don't change the way we look at rules in a strict way, we will keep on losing ALL the future events, some flexibility is needed along the way.

**Comment by Vizvezdenec** [comment]
Sure this will have contempt decrease.
And then we will have increase because we set it to highest value that is not regressing vs 0.
Sure, we can break this rule and set it to (???) value that will pass SPRT in combo. This will heavily depend on combo and on god only knows what and will bring just some randomness.
About SuFis of tournaments - contempt effect there is GREATLY overrated, even changing from 0 to 20 against opponent that is 110 stronger will lose 15~ extra elo (tests can be found on fishtest)... So changing by 1/5 of that will lose what, 3 elo? Against opponent that is 110 elo stronger?

**Comment by Alayan-stk-2** [comment]
> I am pretty sure that contempt 24 is way too high for SF, this have been seen in Tcec superfinal, and other occasions.

Your PR post basically explains that all the point of these parameter tunes you did is to try and get a lower contempt, because this contempt change alone do not pass.

I disagree with your points against the current contempt : 
- Of course contempt sometimes make SF play sub-optimal moves. It also make it sometimes play superior moves.
- There is no _good_ reason to always stick to default contempt in competitions like TCEC and CCCC, so the default contempt value doesn't have to be tuned to increase winning chances in those. We can simply ask the tournament to use a different contempt setting (like Viz, I'd like higher contempt in stage groups and lower one compared to default in finals). Besides, if SF is weaker on a given tournament setup, then going for a higher draw rate might increase the elo perf but decrease the win/loss ratio (e.g. 10%W 20%L has higher chance of winning a tournament than 3%W 10%L). The tournament winning chances depend directly on the win/loss ratio.
- Of course "the highest non-regressing contempt" is not the value tuned for highest self-play performance. Your point about the "curve of strength vs contempt" is obvious, and this was known when the "highest non-regressing" rule of thumb was adopted. What you are missing is that the loss compared to peak value is marginal in self-play (something like 1-2 elo against self) while it is significantly more efficient when it comes to beating up weaker opponents and doing well in rating lists. Look at Leela struggling at the TCEC champions bonus, with only about half the wins from S12 to S14 fishes : this is what playing "safe moves" can lead to.
- Even if SF is not the strongest engine, default contempt is useful in e.g. lowering the draw-rate at fishtest. It's hard to prove which value would be optimal there, but the default contempt influence at fishtest is certainly much more relevant than what it does in tournaments. In general, when a position is evaluated as somewhat better for one side, this side should try to not simplify too fast as even if it increases the mistake rate of both sides, mistakes of the weak side are much more likely to lead to a loss.

> If I want to increase the chance of a tuning patch to pass, I just increase the contempt and test again, that will help, while decreasing contempt will not help.

If lower contempt gives slightly better elo, then it follows that including a lower contempt should increase passing chances. Higher elo = higher passing chances.

> Anyway with the tests I have proven that this patch is stronger than master enough to pass tests at all time control

Sorry, but I'm not convinced that changing the contempt value from 24 to 20 (which is not that much) suddenly make these parameters 2 elo better. It may have been an unlucky run when testing the parameters alone with C24, but considering also the VLTC test is at +0.64 right now, it's likely that the initial STC/LTC tests were rather lucky. I'd guess they still are slightly superior overall, though.

Viz already explained why mixing a contempt change along with a parameter tweak is bad practice. Someone already attempt that kind of combo a few months back and it was rejected.

> so what are in your point of view, the ways that needs to be taken that can lead to a change of contempt ?

If someone could show that a lower contempt improve the patch testing process at fishtest, then that would definitely be a compelling reason to lower it. Otherwise, I don't think that there is a good reason to change the current "highest non-regressing compared to C0" rule of thumb.

**Comment by Vizvezdenec** [comment]
I think we expressed our points enough - now let's have maintainers do their part :)

**Comment by Rocky640** [comment]
This PR suggest another practical question

Should we run SPSA with
a) Contempt 0
b) Current Contempt
c) Some other contempt.

I'm inclined to think that Contempt 0 would give better SPSA results, 
but this would need many experiments to eventually find a conclusion.

And than test with default contempt.

**Comment by Vizvezdenec** [comment]
This PR failed fast w/o including contempt change in it. I'm not against SPSA sessions with different contempt but if anything this PR shows that they can only provide smth when you include actual contempt change you forced.

**Comment by adentong** [comment]
@snicolet I think we can close this since we all agree it's not a good idea to bundle some param tweaks with a contempt change.

**Comment by MichaelB7** [comment]
@adentong - agree - contempt should perhaps  always be tested separately and only when prepping for a worthwhile tournament or match or a planned release .  Once or twice a year.

**Comment by xoto10** [comment]
Contempt is a key part of sf's play now, and more and more strong opponents are appearing. I suggest we treat contempt like any other constant and optimise it for best play. This will:
- simplify the development process (good)
- give stronger play (good)
- introduce a few extra draws if the contempt value falls (possibly bad). Perhaps we would prefer more attacking play, but I don't think the difference will be huge, and I think the above 2 points are worth a slightly higher draw rate.

**Comment by Alayan-stk-2** [comment]
If the slightly higher draw rate increases the number of games needed at fishtest to get a significant result, then it's worse.

And a lower default contempt is bad for rating lists.

**Comment by Vizvezdenec** [comment]
@xoto10 I think you slightly don't get what I mean.
Contempt isn't a feature to give elo in selfplay.
It's a feature to play stronger vs weaker engines even by cost of minor (0.5 elo ~) loss in selfplay.
Including it in combo of parameter tweaks will help to push basically anything that isn't a big regression with pretty decent probability (we can basically confirm that 24 is like ~0.5 elo loss compared to master). Then if we do as we do now - increase contempt to the highest value that doesn't regress vs master - we can push some random stuff thru fishtest and continue like this.
This loop needs to be broken somewhere and in my opinion into "not allowing contempt change in parameter tweaks".
About tournaments - now we have alayant to manage which settings engine will have at them and we are not forced to play default contempt like anywhere.
Vs leela we should take 0 (not only from statistical point of view, but also from stylistical - the more contempt sf has the more positional it starts to play which mostly hurts vs NNs), vs big pool of opponent smth like 50 is perfectly fine (even 100 vs pool of Komodo - engines is absolutely okay, although style becomes kinda wacky) - this all has 0 connections with how we manage contempt being a parameter tweak.

**Comment by xoto10** [comment]
@Vizvezdenec "Then if we do as we do now - increase contempt to the highest value that doesn't regress vs master ..."

My suggestion is we stop doing this, just treat it like any other constant and go for the strongest setting in self-play. I realise contempt is mostly a weapon for gaining Elo against weak opponents, but that does come at a slight cost, and for me TCEC performance is the most important thing. If play is slightly stronger at a lower contempt setting, and then we can tune the rest of the constants to fit well with that contempt setting play gets slightly stronger again. Sure, these are only small gains, but I think every Elo point helps. If we lose very slightly in rating lists ... tbh I don't really care. I'm not sure it's a great idea to keep contempt as high as we can, tune everything to work with that, and then use 0 contempt in TCEC.

Just my 2p, others will have different opinions.

**Comment by AlexandreMasta** [comment]
> @xoto10 I think you slightly don't get what I mean.
> Contempt isn't a feature to give elo in selfplay.
> It's a feature to play stronger vs weaker engines even by cost of minor (0.5 elo ~) loss in selfplay.
> Including it in combo of parameter tweaks will help to push basically anything that isn't a big regression with pretty decent probability (we can basically confirm that 24 is like ~0.5 elo loss compared to master). Then if we do as we do now - increase contempt to the highest value that doesn't regress vs master - we can push some random stuff thru fishtest and continue like this.
> This loop needs to be broken somewhere and in my opinion into "not allowing contempt change in parameter tweaks".
> About tournaments - now we have alayant to manage which settings engine will have at them and we are not forced to play default contempt like anywhere.
> Vs leela we should take 0 (not only from statistical point of view, but also from stylistical - the more contempt sf has the more positional it starts to play which mostly hurts vs NNs), vs big pool of opponent smth like 50 is perfectly fine (even 100 vs pool of Komodo - engines is absolutely okay, although style becomes kinda wacky) - this all has 0 connections with how we manage contempt being a parameter tweak.

It was already tested long time ago and surprisingly contempt gave elo in selfplay. It looks weird, I know, but it is what it is. Contempt gives elo in selfplay. You can redo the test if you want.

**Comment by snicolet** [comment]
Contempt is also a feature to keep more pieces on the board, which is an important thing for fishtest because main Stockfish weakness at the moment is in midgame. Without contempt the games in fishtest go to endgame more easily, and we are only testing the endgame, basically (this is what we did during two years for SF8 and SF9, it was nice but now I think testing midgame is what matters most).

**Pull request closed without merging**
