### PR TITLE
Tuned individual threats + eg 10%.

### PR DESCRIPTION
**Pull request by Rocky640**
After Threat Weights had been successfully changed from {256, 256} to {350, 256} (after a bold test by snicolet) and major weights were successfully retuned by absimaldata (with new weight {404. 241}, 
nperson tried {450, 241} which passed STC but was yellow (neutral) at LTC.

It could be observed that some mg values which were originally much lower than eg values were now higher. So it was time to retune the individual threats.

I tuned using default magic SPSA tuner parameters, 
but run 120000 @ 10+0.1 th 1 using hash 128 and nodestime=600
(the recommended time control is however 20+0.2)

The tuned values passed STC 
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 13189 W: 2595 L: 2390 D: 8204

but struggled LTC.
LLR: -1.49 (-2.94,2.94) [0.00,4.00]
Total: 109058 W: 15765 L: 15532 D: 77761

Meanwhile I made another attempt, keeping the tuned mg values, 
but manually raising the tuned eg values by 10%.

It passed STC
http://tests.stockfishchess.org/tests/view/5669019a0ebc592d552a3f58
sprt @ 10+0.1 th 1
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 45239 W: 8913 L: 8591 D: 27735

and LTC
http://tests.stockfishchess.org/tests/view/566d88120ebc592d552a406d
sprt @ 60+0.6 th 1
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 21046 W: 3200 L: 2989 D: 14857

Compared to current master, mg values were raised on average by 5 %, 
and eg values by (2+10) %

Conclusion:

More tuning at a longer time control than 10+0.1 will eventually be useful to stabilize those individual threats,
and possibly there is still some room to tune our global weights.

### CODE REVIEW

**Comment by ajithcj** [comment]
Congrats!

**Comment by zamar** [comment]
approved.

**Comment by VoyagerOne** [comment]
Based on the latest passed weight patches.  It seems that the ones that passed LTC easily, are the ones that barely passes STC.  I wonder if we reduce the base and increase increments, might help reduce bias towards MG.

**Comment by glinscott** [comment]
Great job!  Approved :)

**Pull request closed without merging**
