### PR TITLE
Simplify away nnueComplexity in evaluation

### PR DESCRIPTION
**Pull request by XInTheDark**
Simplify away usage of NNUE complexity. This is a follow-up to #4530. 

Also includes a parameter tuning for NNUE evaluation.

Simplification STC: https://tests.stockfishchess.org/tests/view/6447ae09c05f2b136ed50196
LLR: 2.96 (-2.94,2.94) <-1.75,0.25> 
Total: 72832 W: 19516 L: 19340 D: 33976
Ptnml(0-2): 166, 8044, 19878, 8104, 224

Simplification LTC: https://tests.stockfishchess.org/tests/view/64485ffe5d29c10f4f213c9d
LLR: 2.93 (-2.94,2.94) <-1.75,0.25> 
Total: 76992 W: 20893 L: 20741 D: 35358
Ptnml(0-2): 20, 7425, 23473, 7539, 39

Bench: 3783553

### CODE REVIEW

**Comment by vondele** [comment]
can you rebase and retest this (LTC only) against master?

**Comment by XInTheDark** [comment]
> can you rebase and retest this (LTC only) against master?

Test submitted, with the previous set of values replacing the recently tuned values in 21d6b69: https://tests.stockfishchess.org/tests/view/645880fc8ab4042ca78947db

**Comment by XInTheDark** [comment]
Closing since the tests failed, will open another PR after the new tuning attempt passes :)

**Comment by pb00067** [comment]
@XInTheDark I think https://tests.stockfishchess.org/tests/view/645880fc8ab4042ca78947db was stopped to early ([LLR: -1.68])
I would let if finish.

**Comment by XInTheDark** [comment]
> @XInTheDark I think https://tests.stockfishchess.org/tests/view/645880fc8ab4042ca78947db was stopped to early ([LLR: -1.68])
> I would let it finish.

I'm not especially hopeful of it passing since the current master values were further tuned, but resumed the test anyways :)

**Pull request closed without merging**
