### PR TITLE
Piece values mp

### PR DESCRIPTION
**Pull request by Stefano80**
Hi,

I dont want to spam, but I implemented a [suggestion](https://github.com/Stefano80/Stockfish/commit/95c20b3c7dba9c01554eb00316ed3b69cb492af2#commitcomment-10747411) by mstembera and have got now a speed up of 5.4% (over 50x bench) and of 7.9% (starting from initial position) with unchanged bench.

Even if you do not intend to merge it, could any of you make an independent measurement?

I am also tuning the table, but I really think that the two ideas must be tested separatedly.

All credit goes obviously to mstembera.

### CODE REVIEW

**Comment by glinscott** [comment]
Which compiler were you using?  And did you use a profile build?  For me, on gcc 4.8.2, it was a small 0.5% speedup.

NPS Before:
Mean: 2415001.300000
Stddev: 1650.329546

NPS After:
Mean: 2426775.300000
Stddev: 2161.656543

**Comment by mcostalba** [comment]
Don't you have already tested this in fishtest?

http://tests.stockfishchess.org/tests/view/552d33d80ebc596367ee990b

**Comment by lucasart** [comment]
This is a slowdown for me:
* gcc 4.9.1 (linux 3.16)
* using PGO
* i7-3770k
```
stat        test     master     diff
mean   2,515,191  2,525,229  -10,739
stdev     15,082     15,293    4,341

speedup      -0.43%
P(speedup>0)   0.0%
```
And even if it was a small speedup, I don't like this code, because:
* **uglification** significantly harder to understand than the original
* **risk of misuse** introduces a magic array. I would bet money that fishtest people will start **tuning** this array! and once tuned, the logic is gone, and it becomes complete monkey-style.

**Comment by lucasart** [comment]
LOL. It's happening already:
 http://tests.stockfishchess.org/tests/view/552fe73d0ebc596367ee99be

**Comment by mstembera** [comment]
@lucasart 
FYI suggested by Marco & Joona here
https://github.com/official-stockfish/Stockfish/pull/333

**Comment by Stefano80** [comment]
gcc version 4.9.1 (Ubuntu 4.9.1-16ubuntu6)

Config:
debug: 'no'
optimize: 'yes'
arch: 'x86_64'
bits: '64'
prefetch: 'yes'
bsfq: 'yes'
popcnt: 'yes'
sse: 'yes'
pext: 'no'

2015-04-16 20:45 GMT+02:00 Gary Linscott <notifications@github.com>:

**Comment by Stefano80** [comment]
This was the version without mstembera suggestion to make the array size a
power of 2

2015-04-16 21:41 GMT+02:00 Marco Costalba <notifications@github.com>:

**Comment by mcostalba** [comment]
Stefano, we are really "climbing on the glass" here :-)

Test failed. Stop. If after tuning passes SPRT[0,6] then it is worth
further consideration.

**Comment by Stefano80** [comment]
Ok

2015-04-17 8:35 GMT+02:00 Marco Costalba <notifications@github.com>:

**Comment by Stefano80** [comment]
Did not pass, so I closing the pull request.

**Comment by Stefano80** [comment]
Hi Marco & others,

is this
<https://github.com/glinscott/fishtest/commit/e6ab0c302b421bffe83e8fbc0b18b8adeab73cfc>the
reason why I am seeing so a huge non confirmed speed-up?

2015-04-17 15:52 GMT+02:00 Stefano Cardanobile <
stefano.cardanobile@gmail.com>:

**Pull request closed without merging**
