### PR TITLE
Join common code in the stages of next_move().

### PR DESCRIPTION
**Pull request by vondele**
based on and tested against PR #1453
    
verified for speed, passed STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 43191 W: 9391 L: 9312 D: 24488
http://tests.stockfishchess.org/tests/view/5a99b9df0ebc590297cc8f04
    
No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Checked with perf against #1453 

```
PR #1453 

 Performance counter stats for 'system wide' (5 runs):

    12.851.641.316      cycles:u                               ( +-  0,05% )
    17.260.371.193      instructions:u # 1,34  insn per cycle  ( +-  0,02% )

       4,826789886 seconds time elapsed                        ( +-  0,15% )


This PR #1454 

 Performance counter stats for 'system wide' (5 runs):

    12.805.642.345      cycles:u                               ( +-  0,04% )
    17.296.430.947      instructions:u # 1,35  insn per cycle  ( +-  0,03% )

       4,809792288 seconds time elapsed                        ( +-  0,30% )

```

So, although number of instructions is higher (+0.2%), total number of cycles is lower, possibly becuase there is a better optimization by CPU, indeed critical insn per cycle metric goes from 1.34 to 1.35 with PR#1454

Anyhow this PR needs some coding style love, I will try to write something...

**Comment by vondele** [comment]
@mcostalba nice illustration for the fishcooking thread on cycles, instructions and IPC :-) the %  cycles reduction matches nicely the speedup I measured locally.

yes, I'm sure there are some follow-up changes possible for style, and possibly further simplifications.

**Comment by mcostalba** [comment]
@vondele I am trying to clarify the pach, but this is really tricky and **not** understandable:

```C++

  case QCAPTURES:
      if (   pick<Best>([&](){ return   depth > DEPTH_QS_RECAPTURES
                                     || to_sq(move) == recaptureSquare; })
          || depth <= DEPTH_QS_NO_CHECKS)
          return move;
      ++stage;
      /* fallthrough */

```

We need to rewrite it to make the patch commitable IMO.

**Comment by vondele** [comment]
equivalent, somewhat easier to understand, but somewhat redundant would be to write:

```c++
  case QCAPTURES:
      move = pick<Best>([&](){ return   depth > DEPTH_QS_RECAPTURES
                                     || to_sq(move) == recaptureSquare; })
      if (  move != MOVE_NONE
          || depth <= DEPTH_QS_NO_CHECKS)
          return move;
      ++stage;
      /* fallthrough */
```

**Comment by mcostalba** [comment]
@vondele I think this is better:

```c++
  case QCAPTURES:
      if (pick<Best>([&](){ return   depth > DEPTH_QS_RECAPTURES
                                  || to_sq(move) == recaptureSquare; }))
          return move;

      // If we didn't find any move and we don't have to try checks
      // then we have finished.
      if (depth != DEPTH_QS_CHECKS)
          break;

      ++stage;
      /* fallthrough */
```


...I will push something soon

**Comment by mcostalba** [comment]
@vondele I have pushed a [code stye patch](https://github.com/mcostalba/Stockfish/commit/simp) above your one. Please check and eventually add it to yours.

**Comment by vondele** [comment]
@mcostalba I like how you also got the good captures integrated (and some other goodies). I'll add it to mine.

**Comment by vondele** [comment]
rebased on master and added @mcostalba contribution.

**Comment by mcostalba** [comment]
@vondele thanks!  I have further improved on it, I have normalized stage names and microptimized a bit:

```
NEW

 Performance counter stats for 'system wide' (5 runs):

    12.885.600.415      cycles:u                              ( +-  0,06% )
    17.197.128.151      instructions:u # 1,33  insn per cycle ( +-  0,01% )

       4,825710310 seconds time elapsed                       ( +-  0,34% )


BASE


 Performance counter stats for 'system wide' (5 runs):

    12.997.382.113      cycles:u                              ( +-  0,03% )
    17.246.922.027      instructions:u # 1,33  insn per cycle ( +-  0,02% )

       4,874829943 seconds time elapsed                       ( +-  0,46% )

```

This is one of those rare cases where a 'goto' statement is better (even as readibility) than alternatives :-)

In case, you need to cherry-pick from [here](https://github.com/mcostalba/Stockfish/commit/simp)

**Comment by vondele** [comment]
@mcostalba I agree with the goto (in fact I also proposed this in the ryzen thread).

I propose to rename the stages _TTM instead of _HEAD ... OK ?

**Comment by mcostalba** [comment]
@vondele @snicolet withouth the odd recursive call to _next_move()_ maybe now it does not crash anymore...finger crossed :-)

**Comment by mcostalba** [comment]
@vondele what it means TTM?

**Comment by vondele** [comment]
transition table move (like the argument Move ttm to the class constructors)

**Comment by vondele** [comment]
*transposition

**Comment by mcostalba** [comment]
@vondele ok for me, maybe _TT is more common (across the code) than _TTM

**Comment by vondele** [comment]
OK

**Comment by vondele** [comment]
out of curiosity @noobpwnftw could you check behavior of this branch  on Ryzen.

**Comment by snicolet** [comment]
After all these fancy rewrites, the bench has changed at depth 22:

Total time (ms) : 90574
Nodes searched  : 182674768
Nodes/second    : 2016856
**master**

Total time (ms) : 95680
Nodes searched  : 193147549
Nodes/second    : 2018682
**testedpatch**

**Comment by snicolet** [comment]
Here is my try on the style to separate the logic clearly, writing each stage as a filter + a select:
https://github.com/snicolet/Stockfish/tree/filters_for_move_picker

The brackets around each "switch" cases are necessary to limit the scope of the "auto" variables.

**Comment by snicolet** [comment]
It is funny how this rewrite switches from one extreme to the other -- from the current master style for the MovePicker, which is almost like a assembler version of a jump table, to a functional style à la Haskell or Objective Caml, with filters, maps, lambda abstractions and the like.

Of course the question will be if the rewrite in functional style is clearer than the master code (hint: probably not.. :-)

**Comment by vondele** [comment]
@snicolet ... well found. There was a rare case where the changes made by @mcostalba were functional. I have reverted that change.

The reason is that the range of possible scores of captures in the evasions stage would overlap with the non-captures. For ep moves m.value is negative. This would lead to a different order of moves.

**Comment by snicolet** [comment]
More regular version:
https://github.com/snicolet/Stockfish/compare/master...snicolet:filters_for_move_picker

**Comment by vondele** [comment]
@snicolet I had a look at your branch, it is of course rather close to this PR, so more or less a matter of taste. Since it is quite common in C++11 to pass a lambda as an argument to e.g. an stl function (e.g. typical usage of std::count_if ) I think the current PR is quite readable. I do not like the additional scope blocks introduced in your variant, and I would keep the fallthrough comments.

Overall, I do think the code is significantly improved over the master in readability, in SF9 the movepicker switch statement was ~180 lines, now we're down to ~110 lines.

**Comment by vondele** [comment]
rebased on master (no changes).

**Comment by vondele** [comment]
rebased once more.

**Comment by vondele** [comment]
@snicolet what is the status of the PR ? Are there particular reservations you have that I can help address ?

**Comment by noobpwnftw** [comment]
@vondele The behavior on my Ryzen is random and it is not only causing segfaults, but also different kinds of weird crashes including general protection faults. I think it is not solvable with coding.

But I did run some tests and it didn't crash after 5000 STC games against itself.

**Comment by snicolet** [comment]
Ahhhh, if this rewrite doesn't crash the Ryzen then my interest level gained +10 points in one go :-)

@vondele 
The small reservations that I still had about the version in the PR are mostly stylistic:

a) the fact that ttm are filtered out is hidden in the MovePicker::pick() helper for some stages while we keep it obvious in some other stages. It would be more regular and clearer to either hide it always or expose it always.
b) some stages use lambda expression filtering, while some use filtering with if(). Again it would make the code more regular if all stages used the same programming style.

This is what I tried to do with my version above, of course.

Practical decision: with the new information that Bojun Guo (@noobpwnftw) brings about this patch passing the Ryzen test (thanks!) , I am now inclined to push the PR version in its current state, and we can improve on remarks (a) and (b) with other pull requests, if necessary.

**Comment by vondele** [comment]
@snicolet I indeed would prefer to improve on a/b with follow-ups. I think it is possible. Improved behavior on Ryzen is a bonus, but is obviously just luck.

**Comment by snicolet** [comment]
Merged via bd59560480cc4f43a4ba75dc827ba27bcebb92dd. Thanks!

**Pull request closed without merging**
