### PR TITLE
Allow us to see progress in TB positions before mate is found.

### PR DESCRIPTION
**Pull request by mstembera**
This is a follow up to https://github.com/official-stockfish/Stockfish/pull/4353   See comments after https://github.com/official-stockfish/Stockfish/pull/4353#issuecomment-1412703285
It allows us to see SF making progress instead of displaying a constant 200 score.

No functional change
bench: 4208265

### CODE REVIEW

**Comment by Disservin** [comment]
Personally I don’t really like this, there’s no progress in this positions unless you get mate announced. There’s no guarantee that the scores actually rise or anything else. So we could see some negative progress actually with this change. Also it adds zero information in my opinion.  The best score we know we can get is 20, the only other progress we can get is if we find mate

**Comment by mstembera** [comment]
I actually think the information is presented in a very elegant way.  You get the exact score SF would report w/o TB but the extra 200 signals that it's a TB win.

**Comment by dubslow** [comment]
I'm loosely in favor of this, tho it would be nice if we could somehow generate some comparison data to see the difference in action for us peabrains who don't understand the post-TB search (which seems to be most of us lul)

**Comment by Disservin** [comment]
> I actually think the information is presented in a very elegant way. You get the exact score SF would report w/o TB but the extra 200 signals that it's a TB win.

If the score reported by stockfish is negative but it’s a tb win, then the resulting score would be lower than 200? Which I think is very confusing and you reintroduce a dependency on the normalization which I wanted to remove.

**Comment by Disservin** [comment]
and then inside the TB you can get values like `287.95`, 200 + 87.95. which are very misleading imo. TB Win inside of TB? At that point you are again at the no progress point unless sf finds mate.

**Comment by vondele** [comment]
First m.tbScore is 

https://github.com/official-stockfish/Stockfish/blob/da8513f0eae439f526ab0a905a3433bdb44bcf66/src/syzygy/tbprobe.cpp#L1572-L1579

so mostly the expected value, with some special treatment of cursed wins. So values different from, but near to 0 in TB have already a meaning.

However, I don't quite see this patch as a good solution, it appears a bit hacky to me. 

Maybe it makes sense to make m.tbScore take dtz into account?

**Comment by mstembera** [comment]
I would be for displaying DTZ info if we can think of a good way to do it.  This is distinct from using DTZ for scoring.  Per Ronald, using DTZ for root move scoring/selection doesn't work well because you don't know what each DTZ value actually means. For example you may want to select a position with a DTZ of 5 over one with a DTZ of 10.  However the DTZ 5 may lead to a pawn move and the resulting position can then have a new DTZ of 20 before leading to mate. The DTZ 10 position may lead to mate in 10 directly.  Apparently he tried it w/o success. (Note all this refers to cases where the root position is in the TB.)

Regarding displaying UCI scores for WDL positions..  In a theoretical sense all won TB positions are equal because they are all won.  In the same sense all mates are equal because they are all mates.  In practice however we need to and do rank them in order to make progress.  If we can search to mate, we use the DTM.  If we can't solve mate, we use the eval.  However in the mate case we display the info but in the eval case  we suppress it which is inconsistent.  Secondly it's inconsistent because in the exact same scenario w/o TB access we would display the eval.   Probably more importantly though it blinds the user as to how to best make progress.  

I am not saying this patch is the best or only way to fix it and welcome all improvements and suggestions. I also would like to make it less hacky.  I think part of the complexity in UCI::value() is hard to simplify because we have to stitch together 3 separate ranges of scores and present them to the user as a single continuous range.

**Comment by mstembera** [comment]
@vondele So I took your suggestion and made the m.tbScore take dtz into account.

**Comment by vondele** [comment]
@mstembera I was expecting you would adjust rootMoves[i].tbScore so that there would be no need to pass anything around, given we have `v = tb ? rootMoves[i].tbScore : v;` already?

**Comment by mstembera** [comment]
@vondele I would but I don't know how to do that w/o messing up the ply calculation.
```const int ply = VALUE_MATE_IN_MAX_PLY - 1 - std::abs(v);  // recompute ss->ply```

**Comment by vondele** [comment]
Wouldn't it just do the right thing? I.e. ply would become dtz ?

**Comment by vondele** [comment]
IIUC that would mean that the score in TB would just mean the same, number of plies to a zeroing move.

**Comment by mstembera** [comment]
Hmm I am not sure I follow.  Can you post some code?  Also the comparisons ```abs(v) < VALUE_TB_WIN_IN_MAX_PLY``` and ```abs(v) < VALUE_MATE_IN_MAX_PLY``` still have to work.

**Comment by vondele** [comment]
well, not sure, but would current master with
```diff
$ git diff
diff --git a/src/syzygy/tbprobe.cpp b/src/syzygy/tbprobe.cpp
index bbfd819d3..dd5095203 100644
--- a/src/syzygy/tbprobe.cpp
+++ b/src/syzygy/tbprobe.cpp
@@ -1572,11 +1572,11 @@ bool Tablebases::root_probe(Position& pos, Search::RootMoves& rootMoves) {
         // Determine the score to be displayed for this move. Assign at least
         // 1 cp to cursed wins and let it grow to 49 cp as the positions gets
         // closer to a real win.
-        m.tbScore =  r >= bound ? VALUE_MATE - MAX_PLY - 1
+        m.tbScore =  r >= bound ? VALUE_MATE - MAX_PLY - 1 - dtz
                    : r >  0     ? Value((std::max( 3, r - (MAX_DTZ - 200)) * int(PawnValueEg)) / 200)
                    : r == 0     ? VALUE_DRAW
                    : r > -bound ? Value((std::min(-3, r + (MAX_DTZ - 200)) * int(PawnValueEg)) / 200)
-                   :             -VALUE_MATE + MAX_PLY + 1;
+                   :             -VALUE_MATE + MAX_PLY + 1 + dtz;
     }
 
     return true;
```
not do the right thing (maybe off-by-1) ?

**Comment by mstembera** [comment]
So what you posted "works" in showing dtz but the scores after the root position enters TB go back to below 200 instead of above.  This means you can't distinguish between # of ply to TB position vs  dtz in TB position.

**Comment by vondele** [comment]
well, seemingly a bug (dtz can be negative in the probing code).

Yes, no difference between being in TB and not, in both cases it would mean how many plies to a position that is in the TB and has is zeroing.

**Comment by vondele** [comment]
I'm still not quite sure this is the right behavior at the root.

**Comment by vondele** [comment]
Like the actual moves played will probably be different, i.e. following the PV this won't have a zeroing move at the distance predicted by the score (once one is in TB).

**Comment by mstembera** [comment]
Yes negative dtz confuses me.  In general encoding lots of info into one variable like m.tbScore is clever and less code but for me at least is much harder to follow than passing separate info around in separate variables.  Do you want me to change this PR to what you posted above?

**Comment by vondele** [comment]
well, I think if we have a tbScore, it makes sense to use it if that's what we output already. 
However, I'm not sure that an output different from what we have now is an improvement.
For example in MultiPV search, the order of the lines will be confusing.

**Comment by mstembera** [comment]
If we can implement UCI::value(Value v) inside of search.cpp instead of uci.cpp so it has access to the TB::RootInTB variable we can fix the ordering by negating the ply to make the scores go above 200 instead of below
```
const int ply = VALUE_MATE_IN_MAX_PLY - 1 - std::abs(v);  // recompute ss->ply
      if (TB::RootInTB)
          ply = -ply;
      ss << "cp " << (v > 0 ? 20000 - ply : -20000 + ply);
```
Or we can subtract the dtz from 21000.   The only way I know to get the precise ordering SF would actually play is to use the value and not dtz more or less as I used it in the original version of this.

**Comment by mstembera** [comment]
Also currently in MultiPV w/ all moves being at 200 there is effectively no ordering at all.

**Comment by vondele** [comment]
right, but at least no 'wrong' ordering. If the we output 200-dtz, (or 200+dtz), the moves would have an incorrect order.

**Comment by mstembera** [comment]
Right.  I was thinking 210-abs(dtz) and -210+abs(dtz) would be closest to correct.  That said a move w/ low dtz isn't necessarily always better than one w/ a higher dtz so the notion of dtz order is not very useful (and is why we don't use it for that purpose internally).  It's information for distance to 0 no more no less.

**Comment by vondele** [comment]
right, and when in TB, this TB distance to zero also doesn't necessarily correspond to what can be seen on the PV line.

**Comment by mstembera** [comment]
right again :)  I keep circling back to the eval because it both orders correctly and corresponds to the PV line.  I know you prefer dtz though so I support it as well.

**Comment by vondele** [comment]
so, I don't think this PR is a good solution, no real improvement over the current state. I will close this.

**Pull request closed without merging**
