### PR TITLE
Combine remove and add in update_accumulator_refresh_cache().

### PR DESCRIPTION
**Pull request by mstembera**
STC https://tests.stockfishchess.org/tests/view/662d96dc6115ff6764c7f4ca
LLR: 2.95 (-2.94,2.94) <0.00,2.00>
Total: 364032 W: 94421 L: 93624 D: 175987
Ptnml(0-2): 1261, 41983, 94811, 42620, 1341 

Combine remove and add in update_accumulator_refresh_cache().
Move remove before add to match other parts of the code.
This includes and was tested on top of [PR5194](https://github.com/official-stockfish/Stockfish/pull/5194).
No functional change
bench: 1836777

Please let me know if I should close https://github.com/official-stockfish/Stockfish/pull/5194 or something else to make it easier to commit on your end.

### CODE REVIEW

**Comment by cj5716** [comment]
I wonder if we can do something similar in update_accumulator_incremental

**Comment by mstembera** [comment]
@cj5716  I tried https://tests.stockfishchess.org/tests/view/662d97916115ff6764c7f4d7

**Comment by cj5716** [comment]
I see, thanks

**Comment by Disservin** [comment]
IMO the ideal thing would be two have 1 PR with 2 commits.
First commit would be the content of the other PR and the second commit has the combine remove/add part.
Can you do that @mstembera ?

**Comment by mstembera** [comment]
@Disservin Ok I committed this on top of https://github.com/official-stockfish/Stockfish/pull/5194 w/o squashing.  Let me know if you need anything else.

**Comment by Disservin** [comment]
Thanks. Then I'll close this one since your other pr will be merged then.

**Pull request closed without merging**
