### PR TITLE
Simplify Pawn Movegen

### PR DESCRIPTION
**Pull request by BM123499**
It simplifies `QUIET_CHECKS` pawn movegen by merging discovery check move generator with direct check move generator.
It also simplifies `emptySquares` instantiation.
In addition, I added a comment in `generate_moves()` to clarify Check branches.

STC:
LLR: 2.95 (-2.94,2.94) <-2.50,0.50>
Total: 112648 W: 9952 L: 9945 D: 92751
Ptnml(0-2): 369, 7682, 40195, 7729, 349
https://tests.stockfishchess.org/tests/view/6088226895e7f1852abd2978

LTC:
LLR: 2.93 (-2.94,2.94) <-2.50,0.50>
Total: 74656 W: 2797 L: 2765 D: 69094
Ptnml(0-2): 38, 2328, 32554, 2380, 28
https://tests.stockfishchess.org/tests/view/60884e5095e7f1852abd2994

No functional change

### CODE REVIEW

**Comment by lp--** [comment]
Bad simplification limits in general. Should have been {-2.25, 0.75}

**Comment by mstembera** [comment]
@lp-- Why?   The latest default simplification limits on fishtest are {-2.50, 0.50}.

**Comment by lp--** [comment]
Before for simplification patches probability for 0 elo patch to pass  was 80%. I thought that was  high enough. 

I don't know why limits for simplification patches were changed to make them easier to pass with more tolerance for elo  loss, while for elo gaining patches  limits were changed to make them harder to pass.  
I did not look what calculator says but I think  {-2.25, 0.75}  should give around 80%, as it keeps 3:1 ratio above and below 0 as was before.

**Comment by chuckstables** [comment]
For elo gaining patches the limits were changed to make them easier to pass. That was the purpose of going from 0.25,1.25 to 0.2,0.9. This makes them significantly easier to pass. Not sure why you think they were changed to make them harder to pass.

**Comment by BM123499** [comment]
I believe you all are not seeing the big pictures here.
 
Yes, indeed, at non-regression LTC it would have 87.7% chance of an 0 elo to pass. But this patch were tested with two testes. One STC non-regressive and a LTC non-regressive. Comparing with previous bounds, using SPRT Calculator given on fishtest:

| Chance of 0 elo patch passes | STC | LTC | Total |
| --- | --- | --- | --- |
| Current Bounds | 87.7% | 87.7% | 76.9% |
| Previous Bounds | 87.7% | 83.7% | 73.4% |

Note also that expected number of games have been increased as well.
Also note that restricting even more non-regression bounds will both reduce the change for 0 elo patches pass and increased the number of expected games.

Personally, I believe that, if the current patch was shown before, it shouldn't have this repercussion. Now the elo shown is 0.03 and before were -0.21. And current patch is equivalent if not worst than previous one.

In addition, receiving negative feedback for being a bit unlucky, whereas other patches with same -0.21 elo got really positive feedback, is at least discouraging.

**Comment by chuckstables** [comment]
@BM123499 I didn't mean to give a negative impression, I was just responding to lp's comment about current elo-gaining bounds making it harder for patches to pass. The only thing that could be seen as negative is the point where I stated that I think our non regression bounds are too generous (especially given that a small regression amounts to significant progress these days), but that was just a response to lp and wasn't directed at you. You ran the test at our current bounds, they passed, and it simplifies the code. These are all good things. Sorry if it came across as discouraging, it definitely wasn't meant that way!

**Comment by snicolet** [comment]
Merged via 84b42b3ab328e3f1b9829d8f5d967e4d45a45a39, thanks!

**Pull request closed without merging**
