### PR TITLE
[NNUE] Print correct engine info.

### PR DESCRIPTION
**Pull request by mstembera**
bench: 4578298
NNUE: 3377227

### CODE REVIEW

**Comment by vondele** [comment]
I've been wondering about this as well. However, should this be instead be part of the `compiler_info()` ? The Version string will otherwise likely grow indefinitely.

**Comment by mstembera** [comment]
Not sure.  Looking at the compiler_info() it uses only system defines and not things we define our selves in the Makefile.  Note we don't print AVX512 AVX2 SSE42 SSSE3.... all together.  We just print the highest one w/ or w/o bmi2 and popcnt.

**Comment by vondele** [comment]
IMO, to be really useful (i.e. to know how the code has been built), compiler_info should really document all defines that are being used to build the code, so maybe that would be a good point to start doing so, as the the defines have become many.

**Comment by mstembera** [comment]
I have no objections against rolling everything into compiler_info() however I apologize this isn't something I'm ready to dive deeper into.  I leave it to you if it's a worthwhile improvement over master as is for now.   Feel free to close either way.

**Comment by vondele** [comment]
I have made a PR that does that https://github.com/official-stockfish/Stockfish/pull/2855

**Comment by mstembera** [comment]
Thanks.  Closing.

**Pull request closed without merging**
