### PR TITLE
Minor cleanup to recent pvHit patch.

### PR DESCRIPTION
**Pull request by mstembera**
No functional change.
See https://github.com/official-stockfish/Stockfish/pull/1936
bench: 3399866

### CODE REVIEW

**Comment by mstembera** [comment]
Should PvNode  on line 50 of tt.cpp be cast to something other than bool before shifting it?

**Comment by snicolet** [comment]
You should explain the tricky part of your changes in the pull request message:

old code:
```
    tte[i].genBound8 = uint8_t(generation8 | tte[i].pv_hit() << 2 | tte[i].bound()); // Refresh
```

new code: 
```        
    tte[i].genBound8 = uint8_t(generation8 | (tte[i].genBound8 & 0x7)); // Refresh
```

**Comment by goodkov** [comment]
Maybe
      // nature we add 263 (256 is the modulus plus 7 to keep the unrelated
?

**Comment by mstembera** [comment]
@snicolet Do you mean here or in the code?  The generation is always just the 5 high bits so we simply want to keep the lower 3 bits.

@goodkov Yes thanks.  That was not supposed to get changed in the original either.

**Comment by goodkov** [comment]
Maybe
in tt.cpp
in function: TranspositionTable::hashfull()
string
          cnt += (table[i].entry[j].genBound8 & **_0xFC_**) == generation8;
replase
          cnt += (table[i].entry[j].genBound8 & **_0xF8_**) == generation8;
?

**Comment by mstembera** [comment]
@goodkov Nice catch!  Done.

**Comment by snicolet** [comment]
Merged via d07e782e22ca2ed0ec748ac38c33673baec28cc5, thanks!

**Pull request closed without merging**
