### PR TITLE
Simplify pawn promotions

### PR DESCRIPTION
**Pull request by protonspring**
This is non-functional.

Not sure, but it seems like this can be removed.

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 78020 W: 16978 L: 16967 D: 44075
http://tests.stockfishchess.org/tests/view/5c27b4fe0ebc5902ba135bb0

### CODE REVIEW

**Comment by ddugovic** [comment]
I guess if evading check involves a promotion this could be functional?  But I wonder how often that really occurs.

https://github.com/official-stockfish/Stockfish/blob/800031c94c655e64e436846911e599de6eb35a72/src/movegen.cpp#L364-L365

**Comment by mcostalba** [comment]
Could you figure out a fen position that triggers the condition and verify it actually matters? For instance doing a perft on that position

**Comment by mcostalba** [comment]
I have looked more in detail. Indeed the condition is just a shortcut to avoid evaluating:

```C++
        Bitboard b1 = shift<UpRight>(pawnsOn7) & enemies;
        Bitboard b2 = shift<UpLeft >(pawnsOn7) & enemies;
        Bitboard b3 = shift<Up     >(pawnsOn7) & emptySquares;
```

In case of EVASION with no target on 8th rank (the common case), we end up performing the 3 above statements for nothing because b1 = b2 = b3 = 0.

So indeed I am not sure the shortcut is worth it. Eventually the patch is ok: it removes a tricky optimzation in exchange for a simpler code, so good for me!

**Comment by DU-jdto** [comment]
I "think" this is safe. If Type == EVASIONS then enemies has already been ANDed with target when it was declared and emptySquares is ANDed with target just before the three bitboards are declared. If target doesn't intersect TRank8BB then b1, b2 and b3 should all be 0 anyway.

**Pull request merged**
