### PR TITLE
Remove inline from source files

### PR DESCRIPTION
**Pull request by lucasart**
Let the compiler decide whether to inline or not.

Very slight speedup on my machine (i7-3770k, GCC 4.9.1, Linux 3.16):

    stat        test     master   diff
    mean   2,471,235  2,466,164  4,394
    stdev     16,876     16,012  3,615
    
    speedup       0.18%
    P(speedup>0) 100.0%

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Perhaps FORCE_INLINE  was there for a reason?

**Comment by lucasart** [comment]
@mcostalba: perhaps... and perhaps that reason is not valid anymore. do you have something more specific in mind ?

**Comment by zamar** [comment]
Some time ago I measured tried replacing all FORCE_INLINE instructions with inline, and couldn't measure any speed difference with gcc...

So we can consider dropping these instructions all together (in the end compilers are not forced to obey these hints anyhow).

**Comment by lucasart** [comment]
You mean this b3545737fa573dec230e5395f36b86a4c1de0510 ?

There is no precise information in the comment comment: which MSVC version does not inline what function, and has there been any statistically significant bench measure to prove that a FORCE_INLINE is required ?

And it was 4 years ago. Let's wait for someone with a modern version of MSVC to post some proper bench results (eg. using fishbench).

Besides, I don't see why it's a problem to have a slight speed regression on MSVC. We do not use MSVC, we only use GCC (whether for abrok, official compiles, fishtest etc.). All we want from MSVC is that it produces correct compiles that run reasonably fast, so that people who use MSVC can contribute to SF dev as well.

**Comment by mcostalba** [comment]
With FORCE_INLINE compiler are forced to obey. I measured a speed up,
especially in move generation.

I can do some new tests, but I'd appreciate that who submits the patch at
least tests with and without FORCE_INLINE (not mixing the other stuff) by
himself. For move generation testing with perft is more sensible.

**Comment by lucasart** [comment]
@mcostalba: Sure, if you force the compiler to inline it will. And? What matters is not whether or not the compiler inlines. What matters is to get the fastest bench, removing any useless stuff along the way.

Typically one should never use inline unless it's a measurable gain, and not based on some "let's inline all we can to be on the safe side" reasoning. Compilers are often smarter than we think…

**Comment by lucasart** [comment]
@mcostalba: same patch without touching any FORCED_INLINE

    stat        test     master  diff
    mean   2,473,027  2,470,828  -441
    stdev     16,828     19,149 9,507
    
    speedup      -0.02%
    P(speedup>0)  41.8%

The only reason to use `inline` now is in header files, to not violate the one definition rule. But even that can be avoided, by declaring in header and implementing in source file, and relying on LTO to do its magic. That being said, we can't always rely on LTO. For example, Clang on Linux still cannot do LTO.

That's why I made the disctinction between *source* and *header* files. Not between *inline* and *FORCED_INLINE*. You will note that I left the FORCE_INLINE in `bitboard.h` untouched.

**Comment by lucasart** [comment]
Another test: this patch plus remove all FORCE_INLINE

    stat        test     master   diff
    mean   2,482,415  2,474,987  7,906
    stdev      4,603      5,644  2,497
    
    speedup       0.32%
    P(speedup>0) 100.0%

So we can safely remove all inlines from source files (including FORCE_INLINE) and FORCE_INLINE entirely.

**Comment by zamar** [comment]
I'm not surprised... gcc -O3 is going to do very aggressive inlining anyway (without any hints)

**Comment by mcostalba** [comment]
I will redo the test, so to have a second source.

**Comment by mcostalba** [comment]
This is my test with gcc 4.9.2 with MinGW-W64 under Windows.

Fishbench result is not significant IMO (it is also quite unstable between
different runs):

Results for 10 tests for each version:

            Base      Test      Diff
    Mean    1046697   1049289   -2592
    StDev   22429     21531     9307

p-value: 0,61
speedup: 0,002

Instead perft gives a small slowdown:

./stockfish bench 128 1 7 current perft

master: 144454070
test: 141155508

So I suggest to _not_ remove force inline from movgen.cpp because in that
case _all_ the generation sub-functions should be inlined, perhaps with the
only exception of generate_castle.

**Comment by lucasart** [comment]
http://tests.stockfishchess.org/tests/view/552dba2f0ebc596367ee9924

**Comment by lucasart** [comment]
I ran `./stockfish bench 64 1 6 current perft` on both master and inline branch, `20` times each:

    stat          test       master        diff
    mean   207,282,511  171,563,510  35,471,007
    stdev    2,930,954    2,361,776   2,986,699
    
    speedup       20.68%
    P(speedup>0)  100.0%

Looks like your last "argument" backfired on you...

To summarize:
* this pull request shows a small speedup on both my machine (+0.3%) and yours (+0.2%). This is tiny, alright, but there's certainly no proof of a speed regression (if anything, a speed increase).
* fishtest, it shows `ELO: 1.09 +-1.8 (95%) LOS: 88.3%`. After the 60k finish, and purge kicks in, we should be around +0.4 ELO. Again no proof of a clear gain, but certainly no proof of a regression either. fishtest is important, because it is made of a blend of compilers, although the blend is skewed towards the mingw cross compiler used by Gary's server for Windows machines.
* even on perft tests, this is a clear speedup on Linux + gcc 4.9, and is equal on Windows + Mingw. Note that it matters, because these perft raw speed is not relevant to chess playing. Bench is more appropriate. In particular, perft uses bulk counting at the leaves, while typically in seach you have to play the move to stand pat in the qsearch (ie. do_move is very important, more than movegen I guess).

It is your dogmatic belief that everything that is on the hot path that is wrong. First of all, the compiler does not obey even when you order it to inline, it still does what it wants. Secondly, inlining is a subtle tradeoff, and not the miracle solution to apply everytime: who better than the compiler should know when to inline and when not to inline ?

**Comment by mcostalba** [comment]
Have you compiled with PGO on?

**Comment by lucasart** [comment]
Yes. Every result I posted is with PGO. I would expect a world class compiler like GCC to use PGO info to figure out what functions are candidates for inlining.

**Comment by mcostalba** [comment]
I think that's teh reason why compiler "knows"....I have tested with -O3
but without PGO.

Anyhow, seeing all the results, I admit patch is fine and should not harm
unless in some corner case (like perft without PGO), not sensible for
release binary.

**Comment by lucasart** [comment]
When it collects profile info, gcc must know which functions are hot and how hot they are. Based on that information, it know which functions are **candidates** for inlining. But inlining is always a tradeoff. It's not because a function is on the hot path that inlining it is best. By forcing the compiler to inline you're crippling the optimizer, which actually does a better job than you at deciding what should be inlined or not (see perft results with PGO).

**Comment by glinscott** [comment]
Thanks for the great investigation, and good discussion here!  Patch looks good to me.  Great to see compilers getting better and better :).

**Pull request closed without merging**
