### PR TITLE
New default net nn-3b20abec10c1.nnue

### PR DESCRIPTION
**Pull request by xoto10**
This net was created by @pleomati, who manually edited with an hex editor 10 values randomly chosen in the LCSFNet10 net (nn-6ad41a9207d0.nnue) to create this one. The LCSFNet10 net was trained by Joost VandeVondele from a dataset combining Stockfish games and Leela games (16x10^9 positions from SF self-play at depth 9, and 6.3x10^9 positions from Leela games, so overall 72% of Stockfish positions and 28% of Leela positions).

STC 10+0.1 :
LLR: 2.94 (-2.94,2.94) <-0.50,2.50>
Total: 50888 W: 5881 L: 5654 D: 39353
Ptnml(0-2): 281, 4290, 16085, 4497, 291
https://tests.stockfishchess.org/tests/view/60cbfa68457376eb8bcab49a

LTC 60+0.6 :
LLR: 2.94 (-2.94,2.94) <0.50,3.50>
Total: 25480 W: 1498 L: 1338 D: 22644
Ptnml(0-2): 36, 1155, 10193, 1325, 31
https://tests.stockfishchess.org/tests/view/60cc4af8457376eb8bcab4d4

Bench: 4904930

### CODE REVIEW

**Comment by NightlyKing** [comment]
I suggest we wait until this test is done https://tests.stockfishchess.org/html/live_elo.html?60cc7828457376eb8bcab4fa
It test on top of that net and it looks like it will pass.

**Comment by xoto10** [comment]
Sure. I created it so that maintainers have the option of merging this one, and then the net from SFisGOD if they choose. If this one isn't needed, then that's no loss, it was easy to create.

**Comment by snicolet** [comment]
Merged via 14b673d90f7f486becda4622eb1e8f4b63bb0785, so congrats to @pleomati and thanks to @xoto10 for creating the pull request :-)

**Comment by xoto10** [comment]
No problem.

Apologies to @pleomati for not adding you to the Authors file - I did think of it, but must have got distracted by something because I completely forgot :-(
But congrats for a great first patch! :-)

**Pull request closed without merging**
