### PR TITLE
Overlapping comparison in syzygy

### PR DESCRIPTION
**Pull request by mstembera**
Fix for issue
https://github.com/official-stockfish/Stockfish/issues/394
Credit and thanks to syzygy1 and lantonov !

### CODE REVIEW

**Comment by zamar** [comment]
So, did I get this right?

v = value without ep capture being considered
v1 = value of the ep capture

The correct logic is:
if without e.p. capture we are losing, and the value of e.p is either draw, or win or a loss, but 50 move rule saves us", then we should use the value of ep capture.

If you can confirm this, then I'm happy to approve this patch.

**Comment by mstembera** [comment]
@Joona
I have asked the people who understand it better than me to confirm since I'm not very comfortable with this code and don't just want to give a half informed nod.  Clearly the current code has to be wrong because it's always true.  Hope we can give them a couple of days to respond.  Thanks!

**Comment by syzygy1** [comment]
Joona's logic is correct. See also my explanation in #394.

**Comment by lantonov** [comment]
Below is the RdM's explanation for "cursed win" and "cursed loss" in syzygy which are indeed connected with the 50-move rule.

"Anyway, this is all not a problem for my tablebases. If the engine wants to ignore the 50-move rule for tablebase positions, it can ignore the 50-move rule when using my tablebases. This is because my tablebases do not store a draw by the 50-move rule as a draw, but as a "cursed win" or "cursed loss". The engine can simply treat "cursed wins" as real wins and "cursed losses" as real losses. Or it can honor the 50-move rule and treat both of them as draws. Or it can bluff and treat cursed wins by the engine as wins and cursed losses as draws."

So, RdM's explanation for what this patch does:

"This is part of en passant handling. v1 is the DTZ score after the en passant capture, v is the DTZ score of the position assuming no ep is possible (the tables don't store en passant positions). The code then takes the "best" of v and v1 (unless the position without ep is stalemate!).
We are in the case that v indicates a loss (-100 <= v < 0). That means v1 is "better" if it is a draw or (cursed) win (>= 0) or a "cursed(/blessed) loss" (< -100)."

is indeed correctly understood by Joona who describes it more clearly.

I wanted to test this patch on the framework but it does not test syzygy at present. Another option is to find positions close to endgame that include en passant moves and test with or w/o the patch.

**Comment by zamar** [comment]
Okay, thx for everybody for their explanations.

I approve this patch.

**Pull request closed without merging**
