### PR TITLE
More accurate 'go nodes' searches at low count.

### PR DESCRIPTION
**Pull request by vondele**
Makes the actual number of nodes searched match closely the number of nodes requested, by increasing the frequency of checking the number of nodes searched at low node count. All other searches retain the default checking frequency of once per 4096 nodes, and are thus unaffected.

On master the number of nodes searched vs requested looks like:
```
 # requested       actual       %error
        1000         7379       637.90
        2000         7379       268.95
        4000         7379        84.47
        8000        14138        76.72
       16000        21185        32.41
       32000        36079        12.75
       64000        65371         2.14
      128000       131819         2.98
      256000       259799         1.48

This patch changes this into:

 # requested       actual       %error
        1000         1000         0.00
        2000         2001         0.05
        4000         4008         0.20
        8000         8002         0.03
       16000        16014         0.09
       32000        32035         0.11
       64000        64109         0.17
      128000       128097         0.08
      256000       256210         0.08
```
passed STC single threaded

LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 32410 W: 5644 L: 5542 D: 21224

with no noticeable slowdown on 32 threads

nodecount: 40139952 +- 218708 Nodes/second
master: 40091022 +- 118310 Nodes/second

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
The aim of this patch is just cosmetic but he impact is real, adding another shared global variable like Limits.callsCnt is not good.

We should limit the shared variables to the bare minimum needed, especially on such hot path.

**Comment by vondele** [comment]
@mcostalba I ran into this for a project where I use very low nodecount for analysis (which surprisingly works well in that context).

I will do a test for no regression to see if this indeed introduces a measurable slowdown.

**Comment by mcostalba** [comment]
I don't think you have machine with 48 or 64 CPU, are you?

The problem is that testing in single thread or with few threads will not
work. This kind of shared variable are a well known scalability issues (it
is the reason we do the check logic more complicated than what we would
like it to be), but you can't spot it with normal tests.

On Mon, Nov 7, 2016 at 1:09 PM, Joost VandeVondele <notifications@github.com

**Comment by vondele** [comment]
I could test on a quad socket 32 cores, but not more, unfortunately. I really doubt I will be able to measure any difference, but I can try. As it is only reading in the hot path it is better than a read/write variable.

Alternatively, the value could be stored on a per thread basis.

**Comment by vondele** [comment]
With 32 threads on a 4xE7-8837, as measured with 10 times './stockfish bench 4096 32 26 default depth' for both master and nodecount branches I see no significant difference in nodes/second:

nodecount: 40139952 +-       218708 Nodes/second
master: 40091022 +-       118310 Nodes/second

raw numbers:
```
benchmark_master_1:Nodes searched  : 5461337693
benchmark_master_1:Nodes/second    : 40241816
benchmark_master_10:Nodes searched  : 5186438948
benchmark_master_10:Nodes/second    : 40168832
benchmark_master_2:Nodes searched  : 6131954794
benchmark_master_2:Nodes/second    : 40124291
benchmark_master_3:Nodes searched  : 6415221392
benchmark_master_3:Nodes/second    : 39927438
benchmark_master_4:Nodes searched  : 5266071917
benchmark_master_4:Nodes/second    : 40089464
benchmark_master_5:Nodes searched  : 6354052623
benchmark_master_5:Nodes/second    : 40059342
benchmark_master_6:Nodes searched  : 6255396052
benchmark_master_6:Nodes/second    : 40126729
benchmark_master_7:Nodes searched  : 5996288039
benchmark_master_7:Nodes/second    : 40461602
benchmark_master_8:Nodes searched  : 5597045185
benchmark_master_8:Nodes/second    : 39709437
benchmark_master_9:Nodes searched  : 5803743875
benchmark_master_9:Nodes/second    : 40001267
benchmark_nodecount_1:Nodes searched  : 5445923739
benchmark_nodecount_1:Nodes/second    : 40230807
benchmark_nodecount_10:Nodes searched  : 6331139495
benchmark_nodecount_10:Nodes/second    : 39419826
benchmark_nodecount_2:Nodes searched  : 6252003130
benchmark_nodecount_2:Nodes/second    : 39720477
benchmark_nodecount_3:Nodes searched  : 5987674071
benchmark_nodecount_3:Nodes/second    : 40319408
benchmark_nodecount_4:Nodes searched  : 5585369678
benchmark_nodecount_4:Nodes/second    : 40166044
benchmark_nodecount_5:Nodes searched  : 6136181624
benchmark_nodecount_5:Nodes/second    : 40215895
benchmark_nodecount_6:Nodes searched  : 7023542238
benchmark_nodecount_6:Nodes/second    : 40524488
benchmark_nodecount_7:Nodes searched  : 5428831467
benchmark_nodecount_7:Nodes/second    : 40565434
benchmark_nodecount_8:Nodes searched  : 5646009301
benchmark_nodecount_8:Nodes/second    : 39869005
benchmark_nodecount_9:Nodes searched  : 5754194817
benchmark_nodecount_9:Nodes/second    : 40368133
```

**Comment by syzygy1** [comment]
One could also initialise to Limits.callCnt and count down to 0.

**Comment by mcostalba** [comment]
@syzygy this is a good idea

**Comment by vondele** [comment]
@syzygy1 @mcostalba yes, I'm testing the patch right now

**Comment by mcostalba** [comment]
Obsoleted by new PR

**Pull request closed without merging**
