### PR TITLE
Stockfish 11

### PR DESCRIPTION
**Pull request by snicolet**
Official release version of Stockfish 11.

Bench: 5156767

### CODE REVIEW

**Comment by snicolet** [comment]
_And now for the release message, please comment and improve (while keeping it short and sweet)!_

-----------------------

If it our pleasure to announce the official release of version 11 of Stockfish.

blah

blah

blah

On behalf of the Stockfish team,
Stéphane Nicolet

**Comment by MichaelB7** [comment]
**If it** our pleasure to announce that Stockfish 11 is out. 
s/b "**It is**"
perhaps ?
**It is our pleasure to release Stockfish 11 to our fans and supporters.**

**Comment by crossbr** [comment]
Not for the release message, but just an observation:

What I found fascinating and attractive about SF when I first started participating here a number of years ago was the open-source nature of the project. I found it beautiful that anyone from around the world could participate and contribute, that it was all entirely voluntary, and that SF was keeping up and even surpassing the for-profit engines, even though those private developers could take any ideas from SF, while keeping their own ideas and discoveries private. I realized that SF as an open-source project is an example of human solidarity and cooperation that transcends borders, ethnicities, religions, markets, and politics, as all those different country flags on the testing page show. That's what persuaded me to contribute to the project. I want SF to win, because I want that expression of our humanity to win.

**Comment by MichaelB7** [comment]
Nicely said Bryan @crossbr. My hope and dream is that Stockfish open source is alive and well long after my earthly days are over.

**Comment by Vizvezdenec** [comment]
I like 
"blah 
blah 
blah"
not gonna lie :)
We can always write smth like "a lot of improvements in search and evaluation, estimated elo difference in selfplay is greater than 50 elo".

**Comment by Vizvezdenec** [comment]
well, "most notable improvements" are wrong since this are "most notable improvements in evaluation" which are like 30% of elo diff actually.
Most notable improvements are in SMP and in search, breadcrumbs, futility pruning, LMR, tthitrate, extensions, constants - everything.

**Comment by karolm2** [comment]
To sum up:
====================================================
It is our pleasure to release Stockfish 11 to our fans and supporters.

Downloads are available at http://stockfishchess.org/download/

There have been 306 patches commited since our previous release in all parts of the codebase by 35 individual contributors fixing bugs (rare crash in razoring ans threading, incorrect mate anouncements) and improving both search and evaluation. The most notable improvements are in SMP, breadcrumbs, futility pruning, LMR, tthitrate, extensions, constants, move ordering, probcut, null move pruning and stats updates. In total, we estimate that Stockfish 11 should have a rating approximately 50 elo stronger than the previous version. Our testing suite fishtest has also been improved allowing us to continue to search for further improvements. If you would like to contribute to that effort, it is as easy as installing our fishtest client from https://stockfishchess.org/get-involved/

On behalf of the Stockfish team,
Stéphane Nicolet

**Comment by Vizvezdenec** [comment]
I honestly don't like to specify "the most notable improvements" - it's kinda disrespectful to other improvements.
Imho, the best way will be smth like "a lot of improvements of search, evaluation and multiprocessing, resulting in approximately 50 elo in self-play on 1 core and 60 elo on 8 cores" - this will be enough.
With usual thx for eveyone involved, be it developers or hardware contributors.

**Comment by hazzl** [comment]
I offer the following compromise solution. In the end, it's Stéphane's decision to pick and choose whatever he sees fit.
________________________________

It is our pleasure to release Stockfish 11 to our fans and supporters.

Downloads are available at http://stockfishchess.org/download/.

Some notable changes include improvements to SMP, futility pruning, late move reduction, TT-hitrate, extension logic, null move pruning, king danger and initiative evaluation . But in total 306 patches have been commited since our previous release in all parts of the codebase by 35 individual contributors. All changes contributed to the improvement in playing strength, fixing bugs (for example rare crash in razoring and threading, incorrect mate anouncements) and keeping our code base maintainable and readable. In total, we estimate that Stockfish 11 should have a rating approximately 50 elo higher than the previous version in self-play. Our testing suite fishtest has also been improved allowing us to continue to search for further improvements. If you would like to contribute to that effort, it is as easy as installing our fishtest client from https://stockfishchess.org/get-involved/.

We would also like to thank everyone that has contributed suggestions for improvements, filed bug reports or contributed CPU-cycles to test the numerous code contributions.

On behalf of the Stockfish team, 
Stéphane Nicolet

**Comment by 31m059** [comment]
Should we run a progression/regression test for the final release?  I think we've had four Elo-gainers since the last one.

**Comment by Yery** [comment]
I think we should - as otherwise the regression page cannot be updated correctly (at least the bottom graph, if the next regression test is vs SF11)

**Comment by Alayan-stk-2** [comment]
What about this : 

The Stockfish team is happy to announce to all chess enthusiasts Stockfish 11's release.

Downloads are available at https://stockfishchess.org/download/

This new version, after a year of work and 306 commits, was only made possible by the dedication of our developers and all the people donating CPU time to fishtest.

Standard testing against SF10 shows an improvement of about 50 elo on a single-core and about 60 elo on 8 threads.

Around one third of the gain comes from enhanced evaluation, most notably king safety and endgame initiative ; while the rest comes from improved search and multithreading, including a number of conceptual novelties. Some very rare bugs (crashes, incorrect mate announcements) and limitations (max depth) have also been fixed.

Our testing framework has also seen its share of improvements to continue propelling Stockfish forward. Along with a lot of small enhancements, fishtest has switched to new SPRT bounds to increase the chance of catching elo gainers, along with a new testing book and the use of pentanomial statistics to be more resource-efficient.

Stockfish lives through its community. You too can help our ongoing efforts to keep improving it : https://stockfishchess.org/get-involved/

________

> Should we run a progression/regression test for the final release? I think we've had four Elo-gainers since the last one.

Yes, obviously.

**Comment by 31m059** [comment]
@Alayan-stk-2 Excellent commit message!  For what it's worth, you have my full endorsement.  :)

The only thing I would change is "conceptual novelties."  "Novelty" has two definitions, one of which simply means "something new" but one that carries connotations of being small, cheap, or dubious.  I would say something clearer, like "improvements," "innovations," or "enhancements."

**Comment by Alayan-stk-2** [comment]
I meant to say that things like using the tt-hit rate for reductions (and some others) are completely new concepts that have never before been seen in chess engines.

"Improvement" or "enhancement" don't work to carry the intended idea that it's not just continuously refining existing techniques, but also exploring new areas. "Innovation" might work.

**Comment by Vizvezdenec** [comment]
Even our excessive usage of LMR for captures is not really something that is hurt about a lot, "classical" LMR is disabled for captures and promotions, and from sf 10 we added 3 different cases in which LMR can be used for such moves (bad static eval, cutnodes, low tthit rate).
Something like stats update after LMR or mixing up futility pruning with moves history or using conthist 5 in move ordering is also not something I've seen or heard anywhere. This are for sure novelties and this is something that shogi and xiangqi engines will use (and not only them probably). :)

**Comment by Alayan-stk-2** [comment]
Stephane wrote this over at fishcooking (it's rather impractical to have one discussion split over two places, so I'm copying it all here) : 

> 
> I have been visiting my local chess club this week, and realized
> than the chess players over there have no idea of the real strength of
> Stockfish, most of them telling me that engines play "at least at 3000 Elo". 
> So I would like to boast a little bit in the release message about the 
> Elo level of Stockfish 11, whatever that means.
> 
> I still have in the back of my mind the claim in the AlphaZero preprint
> that "AlphaZero is playing at 3600 Elo level" based on unpublished
> and non-repeatable data, and all the journalists boldly copying this claim. 
> It seems to me that we could now in turn claim about this level on a
> normal desktop computer with 4 or 8 CPU -- note that the last
> digit of accuracy is not necessary here, I would happily take the
> responsibility of an error of +/- 50 Elo in the claim as I am well aware
> that Elo calculations depends so much of the testing conditions and the 
> anchor points.
> 
> Do we have any data for how much Elo playing with 8 threads
> compared to 1 thread? Then I would happily add this margin to the
> curves of Stefan Pohl in https://www.sp-cc.de/index.htm, and easily
> reach 3600 :-)
> 
> Stéphane

Trying to assign a given elo value to Stockfish and having it be "objective" is unworkable.

The core issue is that elo is a relative measurement compared to other players, not an absolute strength measurement. If one engine with one given hardware setup, fixed settings, and one specific TC is assigned an anchor value, then it's possible to measure everything relatively to it and get absolute strength values for different hardware and TCs, but the starting value we give it in the first place

Just trying to assign one value to one entity across TCs (and settings and hardware) is a fail because the elo differences are not independent.

At fastGM, using the same hardware at different TCs, we can see the gap between Critter (the anchor) and SF10 goes from 452 elo at 60s+0.6 to 375 at 60m+15s. This doesn't mean that SF scales worse. In time-to-elo, SF scales much better. But because there is much more room for improvement with more time for the weaker engine, the pure elo gap nonetheless shrinks.

If we say "SF is 3600 elo", what do we compare to ? CCRL blitz ? CCRL 40/15 ? FIDE ? (SPCC or FastGM are niche and have arbitrary anchors) When it comes to boasting towards the general chess public, any number will be interpreted as relative to FIDE, but of course it's impossible to have SF play GMs or to get any meaningful elo difference from it. Because human strength-scaling with TC is also quite different than that of engines, it gets even more murky.

I wouldn't fret too much over exactness, but we need to understand that even "an error of +/- 50 Elo in the claim" is smaller than what we can do.

**In the end, my take from Stephane's message is that he'd like some boasting about SF's strength. If others share his view, I can easily add this to my suggested release message.**

**Comment by vondele** [comment]
I also agree that assigning an Elo rating to SF that is meaningful for humans (i.e. would compare to their human FIDE or similar rating) is a difficult exercise and hard to do objectively. My personal preference would be to not put it in release message. A statement like 'SF is currently the strongest CPU chess engine' would be less controversial, and is still a strong message.

Related, we now have the UCI_Elo option, which would allow for anchoring SF to human Elo. In particular, if we could have a bot SF11_UCI_Elo_1800 play at a site like lichess at a fixed TC against humans it would presumably get a reasonable lichess Elo anchor. Is that something somebody with relevant experience could set up ?

**Comment by Vizvezdenec** [comment]
I also don't really like elo estimates. I honestly want to have a release already (with RT) and to start a new chapter that has new version as a base for regression tests :)

**Comment by vdbergh** [comment]
I have no experience with lichess but on FICS my experience was that ratings vary wildly over time

https://www.ficsgames.org/cgi-bin/search.cgi?pID=278777;prgraph=2;year=9999

**Comment by vondele** [comment]
interesting, but +- 100 Elo is still reasonably accurate. I guess it is more difficult to get something reliable near 2500 however, which is why I suggested UCI_Elo 1800.

**Comment by vdbergh** [comment]
I also depends on the rating system of course. FICS uses Glicko (or perhaps Glicko-2?)

https://en.wikipedia.org/wiki/Glicko_rating_system

which is Bayesian based in a rather sophisticated way. According to the Wikipedia article it seems that lichess uses something similar.

**Comment by ddugovic** [comment]
Lichess uses some form of Glicko (using the Glicko-2 codebase but with a fuzzy notion of a "rating period" for performance reasons).

**Comment by snicolet** [comment]
Friday, 18:01 (GMT time): new version of the proposed message.

If you see something wrong, please comment :-)

I plan to push the commit at midnight, GMT time.

**Comment by Alayan-stk-2** [comment]
Well, I mean, do as you wish.

**Comment by Vizvezdenec** [comment]
I think that you somehow should mention that noobpwnftw did not only set one-time core record but also that he is basically soloing 70+% of fishtest power ON A CONSTANT BASIS.
This is, imho, even more important.
Otherwise I like this message even if it's really long :)

**Comment by snicolet** [comment]
@Vizvezdenec Thanks, duration of noobpwnftw added

**Comment by 31m059** [comment]
@snicolet Small typo in the current version
> it was a vertiginous experience to see Fishtest pikes with 17466 cores connected playing 25600 games/minute

_pikes_ should be _spikes_

**Comment by Vizvezdenec** [comment]
peaking * is more appropriate ?

**Comment by Alayan-stk-2** [comment]
Ok, some comments.

I have regularly written blog posts without much input from the community I did them for. That's fine. But if you ask other people to suggest something, it's better to react more directly to that feedback.

> This year Stockfish has regained its crown in the TCEC competition, beating in the superfinal of season 16 an evolution of the neural-network engine that had won last year.

There were 3 TCEC seasons in 2019. SF won 2 and lost 1. Your release message gives the impression that the S15 that SF lost happened in 2018.

> This version 11 of Stockfish is 50 Elo stronger than last year, and 150 Elo stronger than the version which famously lost a match to AlphaZero two years ago.

I don't like this phrasing. The AlphaZero match was done behind closed doors, and while the Leela project proves that they succeeded to beat SF8, that quote makes it seem much fairer than it was.

> This makes Stockfish the strongest chess engine running on your smartphone or normal desktop PC, now surpassing the human chess champion by 700-900 Elo points depending of the speed of the computer and number of cores you use (we estimate reaching 3600 Elo even with 4 or 8 cores).

The strength difference compared to human players also depends massively on the time control, but the difference is so huge that elo's non-transitivity becomes a big issue. The range could easily be extended to 1000+ (If we look at https://tcec-chess.com/ordo.txt ; Stockfish on TCEC hardware gets 4000+ ordo elo with Fritz in Bahrain at 2849).

I advise against giving a precise elo number like 3600, because it doesn't stem from a proper methodology and would tie us in the future.

If we want to make an impressive boast, I'd rather suggest talking about time odds.

On a modern 4 core CPU, Stockfish 11 could give 1:1000 time odds to Magnus Carlsen having classical TC, and be on par with him (give or take a few dozen elos).

L. Kaufman wrote : 
> We actually have some real data for Komodo. About 2 or 3 years ago Komodo played a four game match with GM Sergei Erenburg, with Komodo running on 1 laptop core, no ponder, giving 30 to 1 time odds (3' + 1" vs 90' + 30"). Komodo also gave him White every game, only 3 move opening book, and no TBs. His FIDE rating was a bit under 2600. Komodo on one core probably ran a bit under 2 million NPS, but dividing by the 30 to 1 odds maybe about 60 KNSP. Result was 3.5 to 0.5 in favor of Komodo. Given the other handicaps and the result, I think it's reasonable to say that Komodo then at about 10 knps was around FIDE 2600 level in standard chess. Presumably Stockfish 11 now would reach that level at perhaps 5 knps.

I've also ran some low fixed node counts games because of a discussion at talkchess, and they support that this 1:1000 time odds estimate is reasonable.

Back to your release message : 

> Compared to Stockfish 10, we have made literally hundreds of improvements to the [codebase](https://github.com/official-stockfish/Stockfish), from the evaluation function (improvements in king attacks, middlegame/endgame transitions, and many more) to the search algorithm (better coordination between the searching threads, better pruning of unsound tactical lines, etc), and fixed a couple of bugs en passant.

**Remove "literally".** It carries no meaning and is ugly.

I also suggest adding the mention of innovations in our search methods.

The danger when starting to go in a list is to either give a too long list compared to what the target audience would be interested in, or to cut the list short in a way that undersells the actual changes. Sometimes, omitting completely the details work out better, because you let the reader fill in the unsaid, instead of seeing a thing or two that don't impress him very much (even if he's wrong), and then thinking that if other things were not even talked about, they must be even less important.

Not that much to say about the rest, Viz already said it about noob's contribution.

One small thing : 
> More specific data, including nice cumulative curves for the progression of Stockfish strength over the last seven years, can be found [our progression page](https://github.com/glinscott/fishtest/wiki/Regression-Tests), [Stefan Pohl site](https://www.sp-cc.de/index.htm) or [NextChessMove](https://nextchessmove.com/dev-builds).

I think it would be better english to have : 
> can be found on our progression page, on Stefan Pohl's site or at NextChessMove

**Comment by ddugovic** [comment]
> I advise against giving a precise elo number like 3600, because it doesn't stem from a proper methodology and would tie us in the future.

I agree.

**Comment by dorzechowski** [comment]
I would move a paragraph about TCEC a bit lower because this is not the most important message, the one about Elo progress should be first. Also we could mention Leela by name, I see no reason not to, for instance "an evolution of the open source neural-network engine Leela Chess Zero" or something similar.

The new testing book on fishtest is not necessarily better then the old one if it comes to fishtest efficiency, unlike the other improvements but it's maybe nitpicking.

**Comment by snicolet** [comment]
@Alayan-stk-2 @dorzechowski Thanks for the feedback :-) I have removed any reference to Elo in the release message and re-ordered the paragraphs.

It was a fun experience to write a collaborative release message, and I apologize if I could not put in all the excellent suggestions -- but at least I am confident that the result is better that what I would have written alone :-)

**Comment by snicolet** [comment]
Merged via c3483fa9a7d7c0ffa9fcc32b467ca844cfb63790, thanks :-)

**Comment by Alayan-stk-2** [comment]
Some small nitpicks : 
- "Stefan Pohl site" should be "Stefan Pohl's site". The possessive 's is needed.
- Leela was eliminated in divP in S16. While Allie is heavily Leela-based, the current wording let the reader think that the SuFi was SF-Leela like in S15 and S14. If we mention AlphaZero by name, certainly we should Leela too, but some tweak is needed for clarity. Tbh, I don't have a ready-made fix.
- "an neural-network" should be "a neural network"

> but this year Bojun Guo made it a little bit special by plugging a whole data center during the whole year: it was a vertiginous experience to see Fishtest spikes with 17466 cores connected playing 25600 games/minute

Noob powered 70%+ of the cores during the whole year, and at the peak of his contribution had 16K+ cores on, but this statement gives the feeling that we had 10K+ cores during the whole year, which is misleading.

**Comment by mstembera** [comment]
@snicolet Many thanks for your hard work and dedication!

**Comment by Vizvezdenec** [comment]
now we only need to update official site and stuff :)

**Comment by magicon175** [comment]
i will love to contribute but it's just too difficult, i thought i could just download the fistest and start contributing straight away, no need for signup or typing code because i don't know anything at all about coding

**Comment by Vizvezdenec** [comment]
you can download portable fishtest worker and the only thing you will need is to register at fishtest.

**Comment by Atahan-Turkoglu** [comment]
@daylen 

Please update [stockfishchess.org](https://stockfishchess.org/)

**Comment by Atahan-Turkoglu** [comment]
@peterosterlund2

Please update [DroidFish Chess](https://play.google.com/store/apps/details?id=org.petero.droidfish)

**Comment by peterosterlund2** [comment]
> @peterosterlund2
> 
> Please update [DroidFish Chess](https://play.google.com/store/apps/details?id=org.petero.droidfish)

Done! It might take a few hours until it has spread to all google download servers though. If you cannot wait you can download manually from here:

https://www.dropbox.com/s/mjj406i4vdxj9jg/DroidFish.apk?dl=1

**Comment by Vizvezdenec** [comment]
so, ahem, will official site be updated? :D and blog?

**Comment by magicon175** [comment]
@Vizvezdenec or anyone, i have downloaded portable fishtest worker and created account what next?

**Comment by magicon175** [comment]
this is what i'm seeing now is it working well? (Worker version 59 connecting to http://tests.stockfishchess.org:80
Updating worker version to 71) ?

**Comment by Vizvezdenec** [comment]
you should probably reboot it, it should've updated by now. In case it doesn't do so ask @ppigazzini

**Comment by magicon175** [comment]
@Vizvezdenec now this is what i'm seeing, so many codes and the last one is Indexing opening suite, is it working?

**Comment by Vizvezdenec** [comment]
yes, if you got to "indexing opening suite" it's probably okay, but to be sure you should 
Simply delete this folder (adjust according your installation path)
"D:\Fishtest-Worker-Portable\fishtest\worker\testing" and relaunch worker - this should do.

**Comment by magicon175** [comment]
@Vizvezdenec you mean i should delete the testing folder from the worker folder?

**Comment by Atahan-Turkoglu** [comment]
@daylen

Just to point out that when a new version of Stockfish is 'officially' released engine file names should also be renamed to Stockfish 11, not stockfish_20011801_x64_bmi2. Otherwise when you install an engine in a GUI engine name will be Stockfish 20011801 instead of Stockfish 11.  An 'official' release should not have a development version number. 

[https://groups.google.com/d/msg/fishcooking/uJUcbNtnZI4/IG2hU9yiDQAJ](https://groups.google.com/d/msg/fishcooking/uJUcbNtnZI4/IG2hU9yiDQAJ)

**Comment by vdbergh** [comment]
@Atahan-Turkoglu I would imagine that a GUI worth its salt derives the (default) GUI engine name from the ```id name``` attribute. For the version I just compiled this is

```id name Stockfish 11 64 BMI2```

**Comment by Vizvezdenec** [comment]
Stockfish 11

Strong open source chess engine
Download Stockfish 10 for Windows

**Comment by snicolet** [comment]
I got news from Daylen by email, he's just finished a long bike ride this week-end. He is only on an iPad at the moment, will have access to his Mac on Monday night. 

So a little bit of patience will get us there for the web site :-)

**Comment by ppigazzini** [comment]
Great work @snicolet !
I suggest to write a short tasklist (e.g. in the first post) to be used for SF12

**Pull request closed without merging**
