### PR TITLE
Slight decrease of overload value

### PR DESCRIPTION
**Pull request by snicolet**
Set overload value to S(13,6)

STC:
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 27606 W: 6371 L: 6094 D: 15141
http://tests.stockfishchess.org/tests/view/5b5455840ebc5902bdb82425

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 112435 W: 19442 L: 18921 D: 74072
http://tests.stockfishchess.org/tests/view/5b546d4a0ebc5902bdb82741

Bench: 4937000

### CODE REVIEW

**Comment by snicolet** [comment]
This is a pull request on behalf of "double-beep". Please don't take it for granted that I will open a pull request for you in the future, it is only because it is vacation time and double-beep is probably lost somewhere in the middle of nowhere without an internet connection :-)

**Comment by FauziAkram** [comment]
Maybe decreasing to even lower values might be even better as tested by goodkov:
http://tests.stockfishchess.org/tests/view/5b563d700ebc5902bdb8582f
My suggestion would be to run a 20000/40000 games between the 2 patches at LTC and pick the one which do better

**Comment by snicolet** [comment]
@FauziAkram The value S(10,5) failed at STC against current master, so I am committing  double-beep's value S(13,6)

**Comment by snicolet** [comment]
Merged via 38471697b7e414f4509fb7dbf41f3f679711edb4, congrats to all :-)

**Comment by double-beep** [comment]
@snicolet, @FauziAkram, @Stefano80, @Rocky640 and @locutus2 thank you all for the great feedback. 

@snicolet it is correct, I did not have the time to open this pull request thanks for doing that for me.

**Pull request closed without merging**
