### PR TITLE
Use unsigned int for nodes in Limits.

### PR DESCRIPTION
**Pull request by vondele**
No functional change.

### CODE REVIEW

**Comment by lucasart** [comment]
did you check all the "nodestime" code ? you need to be very careful with unsigned arithmetic, it's so easy to screw up (for no real benefit in this case).

**Comment by vondele** [comment]
Limits.nodes is always positive AFAICT, which is good, since it is being casted to unsigned already in master. The patch basically removes the cast, which is useless. 

Time.availableNodes is another case, since that could get negative indeed.

**Comment by mcostalba** [comment]
Limits fields strictly mimic the original UCI parameter (see go() in uci.cpp) and UCI defines only integers, not unsigned. Yes, there is a reason why nodes is int, you were not expecting it was, don't you :-) ?

And this is the correct way to do it: Limits.nodes just stores the UCI "nodes" value and if "nodes" is int then this has to be int too. If we use nodes as an unsigned, float or whatever this is another thing and we should handle it where we use it, but the definition is: "Limits.nodes stores UCI "nodes" and we should be consistent with it.

**Comment by vondele** [comment]
@mcostalba can you point to specification of the uci protocol, I only find http://wbec-ridderkerk.nl/html/UCIProtocol.html where no types are mentioned. 'go nodes x' is described as 'search x nodes only'. Which only makes sense for x>=0 ? The code just goes in an infinite loop for 'go nodes -1'.

**Comment by mcostalba** [comment]
@vondele one thing is the number 'type' and one thing is the number semantic. UCI defines values as numbers as integers, see for instance spin value type in definition of option in UCI protocol.

Admittedly the UCI standard is very informal and even loose compared from usual way to define formalized protocols. But that's it and assuming all values as integers is safe and consistent and IMO the best approach given the infromal way UCI is defined.

BTW  The code just goes in an (almost) infinite loop for 'go nodes -1' even if 'nodes' is defined internally as an unsigned !!

**Comment by vondele** [comment]
yes, UCI is informal at best, for spin value type it mentions 'an integer in a certain range' so while the the type (integer) is specified, it doesn't specify the value range, so it could be signed or unsigned, 4 byte, or 8 byte. The latter freedom is already used in master.

But yes, I don't care much about this patch, feel free to close.

**Pull request closed without merging**
