### PR TITLE
Outpost Endgame values.

### PR DESCRIPTION
**Pull request by Rocky640**
Remove the recent rank based Outpost array by using a weighted average value computed using a frequency analysis by rank from a large set of middle game positions.

The higher eg values introduced by the new Outpost array (which were about twice the previous masters) are thus preserved.

STC
http://tests.stockfishchess.org/tests/view/5dd05c870ebc5902579e1f7f
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 42466 W: 9232 L: 9151 D: 24083

LTC
http://tests.stockfishchess.org/tests/view/5dd146e342928ff08153dab1
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 66968 W: 10921 L: 10873 D: 45174

It was first tried to also use this new outpost value for the reachable outpost, but this failed.
Can't find the test anymore, but code is here
https://github.com/Rocky640/Stockfish/commit/c3c58daf916004bfe591b834d8d4e8d5cb7aeae2

bench 4917631

### CODE REVIEW

**Comment by SFisGOD** [comment]
>Can't find the test anymore, but code is here

I am confused by this statement since I found out that you deleted the test yourself.
deleted

Link to the deleted test: http://tests.stockfishchess.org/tests/view/5dd0518f0ebc5902579e1ed7

You mentioned it so maybe that was just a mistake?

**Comment by Rocky640** [comment]
My intent was to stop the mentioned test, not to "delete" it. And this morning could not filter out the deleted tests in the Actions screen.

Thank you for providing the link.

**Comment by SFisGOD** [comment]
Honestly, I'm disappointed this got simplified right away. . .
Well, time to set sail my simplification adventures then. . .

**Comment by Vizvezdenec** [comment]
It's not simplified "away".
It's simplified into completely different values that are quite different from what we had in master previously, thus your work is not useless whatsoever.
I think like half of my patches were eventually simplified into something more compact which is perfectly normal cycle of sf development, some of them really in no time after passing.

**Comment by AlexandreMasta** [comment]
@SFisGOD your work was not in vain. This simplification and code enhancement was possible due to it. Everybody praise your work.
Hope you continue the good job.

**Comment by snicolet** [comment]
@Rocky640 Merged via 37698b0396e26a0f1364912dd1feae5dae5892ef, thanks!

The method you used ("using a weighted average value computed using a frequency analysis by rank from a large set of middle game positions") is interesting, could you tell us more about it?

**Comment by snicolet** [comment]
@SFisGOD Please don't let you feel by sadness, we are all doing it for the good of chess! 

My constant advice to evaluation simplificators has been to try to tune to death *before* attempting simplification (either by hand of by the tuner), because the fact that a common-knowledge chess idea can be simplified away may just be symptom that the relevant term is currently slightly untuned rather that not useful.

**Comment by Rocky640** [comment]
Sorry for the verbosed and inflated description.
I just wanted to say I did not simply average the 3 values in the array.

Instead I used a set of 1000 middlegame positions which was created by sg
I also have a modified dbg_meanX(int statno, int value)  which can compute more than one statistic 
and similarly dbg_hitX(int statno,  bool condition)

Running the previous master (the one  with the outpost array), I changed the code as follow
and collected 5 statistics. 
```
if (s & bb)
{
                dbg_meanX(1, mg_value(OutpostRank[relative_rank(Us, s)]);
                dbg_meanX(2, eg_value(OutpostRank[relative_rank(Us, s)]);
                dbg_hitX(3,relative_rank(Us, s) == RANK_4);
                dbg_hitX(4,relative_rank(Us, s) == RANK_5);
                dbg_hitX(5,relative_rank(Us, s) == RANK_6);
                score += OutpostRank[relative_rank(Us, s)] * (Pt == KNIGHT ? 2 : 1);
}

```
and run the following command

bench 16 1 4 pos1000.fen

I think i simply used stat 1 and 2.

**Comment by snicolet** [comment]
@Rocky640 thanks!

**Comment by 31m059** [comment]
@Rocky640 @snicolet Would you be willing to merge `dbg_meanX(int statno, int value)` and `dbg_hitX(int statno, bool condition)` into master?  I know I've had many cases where I've wanted to measure more than one value, and simply had to recompile each time.  I think a lot of other developers would also find these methods very helpful.

**Comment by Rocky640** [comment]
marco wanted to keep the debug tools very simple in the master branch.

However, there are a few more statistical features in the tune branch.
we could add it there. Stéphane probably have some nice code too for this.

**Pull request closed without merging**
