### PR TITLE
TTComment

### PR DESCRIPTION
**Pull request by mstembera**
Better document entry age calculation used in TT replace.
No functional change.

Thanks to Marco and Joona!

### CODE REVIEW

**Comment by lucasart** [comment]
pedantic nit-picking: shouldn't the 259 be unsigned here ?

**Comment by mstembera** [comment]
I don't think it makes any difference here but I'm happy to change it if you think there is a reason.

**Comment by zamar** [comment]
There is no need for 259 to be unsigned. 

Bitwise operators work just fine for signed integers as long as the value they hold is positive...
However if the value is negative (which is not the case here) the result may be implementation specified.

**Comment by zamar** [comment]
approved.

**Comment by mcostalba** [comment]
See my comments on other
 pr

**Comment by mstembera** [comment]
Comment updated.

**Comment by glinscott** [comment]
Looks good!

**Comment by zamar** [comment]
approved.

**Pull request closed without merging**
