### PR TITLE
Add spaces in syzygy UCI options

### PR DESCRIPTION
**Pull request by arjuntemurnikar**
Add spaces in syzygy's UCI options for consistency with other stockfish UCI options.

No functional change.

### CODE REVIEW

**Comment by arjuntemurnikar** [comment]
It's a very simple renaming. "SyzygyProbeDepth" etc. looks a bit unprofessional in a production build.

**Comment by glinscott** [comment]
SyzygyPath is consistent with other engines that have implemented Syzygy, I think we should probably just go with consistency here.

**Comment by zamar** [comment]
Agreed with Gary. We should stay consistent with other engines. Thus I'm closing the request.

**Comment by arjuntemurnikar** [comment]
Alright

**Pull request closed without merging**
