### PR TITLE
Use correct chess terms + fix spelling.

### PR DESCRIPTION
**Pull request by ddobbelaere**
Use correct chess terms + fix spelling.
- "discovered check" (instead of "discovery check")  _(except at one place to avoid merge conflicts with #3292)_
- "en passant" (instead of "en-passant")
- "pseudo-legal" before a noun (instead of "pseudo legal")
- "3-fold" (instead of "3fold")

No functional change.

### CODE REVIEW

**Comment by MichaelB7** [comment]
If you want to be truly  correct , one uses hyphens before a noun and not after.
_**Chocolate-covered peanuts**_ or _**The peanuts were chocolate covered**_  are both correct,
similarly   _**pseudo-legal move**_  and  _**whether the move is pseudo legal**_  are both correct.

[https://owl.purdue.edu/owl/general_writing/punctuation/hyphen_use.html](https://owl.purdue.edu/owl/general_writing/punctuation/hyphen_use.html)

I applaud your effort for the corrections you submitted.

**Comment by ddobbelaere** [comment]
Thanks for the feedback, English is not my native language :)

Are you sure that in this case the rule applies? According to https://www.oxfordlearnersdictionaries.com/definition/english/pseudo?q=pseudo, pseudo- is listed as a "combining form"...

I guess "en passant capture" is an exception to this rule (no hyphen)? Both https://www.chess.com/terms/en-passant and https://www.chessprogramming.org/En_passant never use a hyphen and seem authoritative sources.

**Comment by ddobbelaere** [comment]
To add to the confusion: pseudolegal is given by https://en.m.wiktionary.org/wiki/pseudolegal (and some other sources), pseudo-legal by CPW: https://www.chessprogramming.org/Pseudo-Legal_Move

What do you think of it?

**Comment by MichaelB7** [comment]
I would follow the standard convention:

```
Use a hyphen to join two or more words serving as a single adjective before a noun:
a one-way street
chocolate-covered peanuts
well-known author
However, when compound modifiers come after a noun, they are not hyphenated:
The peanuts were chocolate covered.

```

**Comment by MichaelB7** [comment]
> Thanks for the feedback, English is not my native language :)
> I guess "en passant capture" is an exception to this rule (no hyphen)? Both https://www.chess.com/terms/en-passant and https://www.chessprogramming.org/En_passant never use a hyphen and seem authoritative sources.

en passant is French and roughly translates  to "by the way" or "in passing" , and I never seen seen it hyphenated, possibly because it is French and in English , people do not think of it as two adjectives - it is a one word adjective for chess move . that has space in it,  The is no _**en move**_ , or  _**passant move**_, it is always **_en passant_** together,  No hyphen , end of story.

**Comment by ddobbelaere** [comment]
@MichaelB7 Thanks, I'll try to update the PR shortly.

**Pull request closed without merging**
