### PR TITLE
Small cleanups 03

### PR DESCRIPTION
**Pull request by vondele**
Starting with an empty PR to collect suggestions for small cleanups.

No functional change.

### CODE REVIEW

**Comment by protonspring** [comment]
endgame.cpp, line 773.  Seems like this should be SQ_A3 -> SQ_C1 (NOT SQ_C3) ?

**Comment by vondele** [comment]
@protonspring can you clarify (and is the line/file right?)

**Comment by protonspring** [comment]
> @protonspring can you clarify (and is the line/file right?)

Sry.  tbprobe.cpp, line 773.  This is flipping over the A1H8 diagonal.  A3 probably goes to C1.  Correct?

**Comment by protonspring** [comment]
endgame.cpp, line 27, there is a:  using std::string

I have no idea what that would be used for and removing it does nothing on my machine.  Is this safe to remove?

**Comment by OuaisBla** [comment]
The variable PopCnt16 in bitboard.h can be fully excluded from builds when USE_POPCNT is enabled.

#ifndef USE_POPCNT
extern uint8_t PopCnt16[1 << 16];
#endif

and in bitboard.cpp

#ifndef USE_POPCNT
uint8_t PopCnt16[1 << 16];
#endif

and also in Bitboards::init()

#ifndef USE_POPCNT
  for (unsigned i = 0; i < (1 << 16); ++i)
      PopCnt16[i] = std::bitset<16>(i).count();
#endif

Saving few bytes of memory and few millisecond of initialization time in those cases.

**Comment by vondele** [comment]
@OuaisBla this has been discussed in the past, the consensus was that it is not worth adding the code / ifdefs to comment those out.

**Comment by ddugovic** [comment]
Either fix the typo or extract a diagonal-flip function:

https://github.com/official-stockfish/Stockfish/blob/960d59d54143d84aab26deae65279a611fc989f4/src/syzygy/tbprobe.cpp#L772

**Comment by protonspring** [comment]
endgame, line 163:  I missed this loserKsq in the flipping consolidation.
~loserKsq should be changed to flip_rank(loserKsq)

**Comment by TerjeKir** [comment]
uci.cpp line 263: VALUE_MATE - MAX_PLY can be simply VALUE_MATE_IN_MAX_PLY

**Comment by joergoster** [comment]
Line 44 in tt.h is missing one blank to correctly align with the other lines.

`  bool is_pv()  const { return (bool)(genBound8 & 0x4); }`

**Comment by man4** [comment]
* (endgame.cpp, lines 343, 347, 350, 373, 374) `strongpawns` should be capitalized as `strongPawns`
* (endgame.cpp, lines 344, 359) `allpawns` -> `allPawns`
* (endgame.cpp, lines 351, 354) `weakkingSq` -> `weakKingSq`

**Comment by silversolver1** [comment]
I think this should say "THEIR PIECES" (no quotes) based on its location:
https://github.com/official-stockfish/Stockfish/blob/37e38639279bf58558b92932739da57e7c2e3bdc/src/material.cpp#L49

**Comment by vondele** [comment]
@silversolver1 I think the comment (OUR PIECES) is correct, it reflects which side is used in the quadratic term, once it is ours x ours, once it is ours x their.

**Comment by silversolver1** [comment]
@vondele Sounds good, thanks for clarifying :)

**Comment by silversolver1** [comment]
I don't mean to double post but I think that in both the following two lines assigning the value of true or false to bool didLMR should be moved to the next line. 

I think it would eliminate any ambiguity as to whether or not doFullDepthSearch was somehow a function taking two arguments despite being a bool. I also think it would just be more clear to have the two assignments (with potentially different assignment results) take place on separate lines.

Of course, the decision is up to you ;)
https://github.com/official-stockfish/Stockfish/blob/37e38639279bf58558b92932739da57e7c2e3bdc/src/search.cpp#L1204

https://github.com/official-stockfish/Stockfish/blob/37e38639279bf58558b92932739da57e7c2e3bdc/src/search.cpp#L1207

In addition, in the second line
!PvNode || moveCount > 1
can probably be changed to
(!PvNode || moveCount > 1)
for consistency (so basically adding the parentheses at the beginning and end of the conditions).

Thanks.

**Comment by protonspring** [comment]
I assume this doesn't need testing. Please let me know if I am mistaken.

https://github.com/protonspring/Stockfish/tree/ps_kbpkb2

**Comment by protonspring** [comment]
and

https://github.com/protonspring/Stockfish/compare/c077bfb...4fd6d9c

**Comment by protonspring** [comment]
Bitboard.h, comment on line 384.  It's probably important to say that the given Bitboard must be non-zero.

**Comment by OuaisBla** [comment]
Function Position.is_draw could be simplified like this:

bool Position::is_draw(int ply) const {

  if (st->rule50 > 99 && (!checkers() || MoveList<LEGAL>(*this).size()))
      return true;

  // Return a draw score if a position repeats once earlier but strictly
  // after the root, or repeats twice before or at the root.
  return st->repetition && st->repetition < ply;
}

**Comment by silversolver1** [comment]
@vondele Hello!

Sorry this might be a bit of a beginner question but how come you didn't have to push the reference bench number using the commit message like we did in the other PR? 

Is it because the bench was effectively the same? Or is Travis/AppVeyor set to accept either a bench number or the phrase "no functional change"?

I'm not sure if I'm asking the right question either. Any help would be appreciated :)

**Comment by vondele** [comment]
yes, non of the changes here changed the bench number (anything changing bench would not fit 'small cleanups'), in that case it is not necessary to provide a Bench: xxxx, the CI will find the one of an earlier commit.

**Comment by silversolver1** [comment]
@vondele Ok sounds good, thanks!

**Pull request closed without merging**
