### PR TITLE
fix wasted copies

### PR DESCRIPTION
**Pull request by protonspring**
As suggested by vondele, I've identified situations where moves are being copied unnecessarily.  This patch fixes the wasted copies.  There should be no functional change. same bench numbers, etc.

My pybench numbers are:
base = 1551873 +/- 52520
test = 1564765 +/- 53476
diff =  +12892  +/- 1318

speedup = +.008
P(speedup > 0) = 1.000

CPU 2xIntel(R) i7-2640M @ 2.8GHz

I'm not sure, but it looks like almost a 1% speedup.  I can clean up the patch a bit, but how should I proceed?

### CODE REVIEW

**Comment by mstembera** [comment]
The continue clause kicks in about 3% of the time during bench.  However, I can't measure a speedup.
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    920264    919582    682       
    StDev   32533     32194     4081      

p-value: 0.434
speedup: -0.001
```

**Comment by mcostalba** [comment]
I'd prefer to leave that sort simple and easy, to add complexity we need a sensible speed up, I don't see this is the case.

**Comment by protonspring** [comment]
Makes sense. I have tried many different things and that algorithm is
actually very fast and simple.

**Comment by mcostalba** [comment]
@protonspring ok, thanks, so closing it.

**Pull request closed without merging**
