### PR TITLE
Increase pawn mg psqt values for 4th and 6th ranks on h file.

### PR DESCRIPTION
**Pull request by xoto10**
Encourage h-pawn pushes for attack or defence by increasing the mg psqt values on rank 4 and rank 6.

Tested using the closedpos book:

STC:
LLR: 2.95 (-2.94,2.94) {-0.50,1.50}
Total: 18112 W: 3707 L: 3491 D: 10914
Ptnml(0-2): 305, 2016, 4208, 2212, 315
https://tests.stockfishchess.org/tests/view/5ed78189f29b40b0fc95a8dc

LTC:
LLR: 2.94 (-2.94,2.94) {0.25,1.75}
Total: 39296 W: 5637 L: 5352 D: 28307
Ptnml(0-2): 254, 3731, 11468, 3866, 329
https://tests.stockfishchess.org/tests/view/5ed7b3e6f29b40b0fc95a8f9

Bench 4625376

### CODE REVIEW

**Comment by FauziAkram** [comment]
I would suggest running also a non-regression test using the standard opening book

**Comment by vondele** [comment]
@xoto10 yes, please test non-regression STC on the noob book. I'm not expecting this to be difficult to pass.

The patch is interesting however... I would guess this has been tried a few times in the last year or so, but seemingly some changes made this suddenly succeed.

**Comment by dorzechowski** [comment]
I tried something similar recently but with standard book and I put more changes at the same time, what was not good apparently as it ended with exactly 0 Elo.

One thing that bothers me is the strange hole on d5, there is no reason for this.

**Comment by xoto10** [comment]
STC non-regression with noob book started at https://tests.stockfishchess.org/tests/view/5ed8ff18f29b40b0fc95a9c7

**Comment by adentong** [comment]
Nonregression is not looking good.

**Comment by Chess13234** [comment]
Maybe it could be a specific pawn bonus for these ranks in closed positions instead?

**Comment by xoto10** [comment]
Yeah, the non-regression is not looking good, currently at -1.23 LLR after 27k games.

I've started some other tests, [pawnh3](https://tests.stockfishchess.org/tests/view/5ed92db9f29b40b0fc95a9ed) is coded in pawns.cpp and tests for blocked center files (but not number of pieces left on board) before awarding a bonus for a pawn on the relevant square. That one looks hopeful so far.
Just started, [pawnh4](https://tests.stockfishchess.org/tests/view/5ed978a8f29b40b0fc95aa32) updates the psqt when the position is set via uci.

**Comment by NKONSTANTAKIS** [comment]
I believe that a full specialization of parameters regarding position type is worth tons of elo. By using what works on average everything will be subpar but the minorities will suffer most. In our case the closed positions are both radically different, and with weak signal at the normal book.

Also I would like to note that closed positions should be more needy of evaluation love, as due to their positional nature search is less efficient than in open ones. Therefore I expect that deeper searches will mitigate a slight misoptimization at open positions much more than closed ones. This could be checked with non-regression LTC.

**Comment by NKONSTANTAKIS** [comment]
If preserving simplicity is valued, maybe a golden balance for optimization could be attained via a book which uses 50% open and 50% closed positions.

**Comment by dorzechowski** [comment]
@NKONSTANTAKIS One thing to try would be to use two different mg values for open and closed positions and interpolate between them depending on "closedness" of a position in similar way as we interpolate between mg and eg values right now. So define evaluation Score as (mgo, mgc, eg) triplet instead of current (mg, eg) pair. To do this we need however a good definition of a "closedness" degree of any mg position and I don't believe we have one.

**Comment by FauziAkram** [comment]
I love your idea @dorzechowski

**Comment by vondele** [comment]
@xoto10 since the non-regression test against noob_3moves failed, we shouldn't merge the PR in this form. 

The results, however, are very interesting and hopefully give inspiration on how to tackle this problem. 

So, I'm going to count that as another success of the closedpos book, since generating insight is very valuable as well.

**Comment by locutus2** [comment]
@dorzechowski 
I have tried something like this in the past but without success (but closepos.epd doesn't exists at this time).

Closedness where defined following:
```
Closedness Position::closedness() const {
  return Closedness(      popcount(pieces(PAWN)) 
                    + 2 * popcount(pieces(WHITE, PAWN) & shift<SOUTH>(pieces(BLACK, PAWN))));
}
```

and the closedness scores were also interpolated by phase and added:
```
Closedness closedness = pos.closedness();
  v += (  closed_value(score) * int(closedness)
        + open_value(score)   * int(CLOSED_GAME - closedness)) / CLOSED_GAME;
```

Par example here i tuned mobility:
https://tests.stockfishchess.org/tests/view/58c5bb0d0ebc59035df32cf6

But i think too that there is potenital.

**Comment by dorzechowski** [comment]
@locutus2 Yes, that's more or less what I had in mind in terms of interpolation. But we see now that mg score may be significantly different in psq and perhaps also in more eval terms like king safety, space, etc. So may be bigger eval overhaul would be worth trying.

I'm afraid your closedness definition was not perfect as blocked center is much more impactful than blocked e.g. a and b file and you don't distinguish between files.

Perhaps we should take the discussion elsewhere, it will be lost and forgotten here.

**Comment by xoto10** [comment]
Yes, interesting ideas. Maybe create an issue that can stay open for a while?

**Comment by Alayan-stk-2** [comment]
I made some experiments with Ethereal that could be relevant to the discussion (more interpolation points, closedness definition), but I think a closed PR has too little visibility, only people that get pinged by notifications will notice it. Better open an issue.

**Pull request closed without merging**
