### PR TITLE
Always allow singular extension.

### PR DESCRIPTION
**Pull request by joergoster**
It is also a bugfix of a bugfix.

Everything started with Eelco's patch https://github.com/official-stockfish/Stockfish/commit/55a3e0af8d0d1e169cc8b16541ffeb41e157b66e, after which the condition "abs(ttValue) < VALUE_KNOWN_WIN" had been removed from singular extension search, and condition "abs(beta) < VALUE_KNOWN_WIN" was added to the SingularExtensionNode definition.
This could lead to problems especially in positions where a mate is due.
For example, this position 5rk1/4K1pp/8/5PPP/8/8/8/1R6 w - - 12 1 triggered an assert.
This was fixed with this patch https://github.com/official-stockfish/Stockfish/commit/ffedfa33542a7de7d87fd545ea0a4b2fef8f8c6e but in a quite thoughtlessly way. Because then singular extensions were not allowed in way more positions than needed.

Dividing the triggered assert into 3 separate asserts reveals the real problem:
stockfish: search.cpp:552: Value {anonymous}::search(Position&, Search::Stack*, Value, Value, Depth, bool) [with {anonymous}::NodeType NT = (<unnamed>::NodeType)0u]: Assertion `-VALUE_INFINITE <= alpha' failed.

Because we subtract 2 * depth from ttValue during singular exclusion search
``` Value rBeta = ttValue - 2 * depth / ONE_PLY; ```
and call search() with rbeta-1, rbeta, we must take care that rbeta-1 is at least -VALUE_INFINITE.
``` Value rBeta = std::max(ttValue - 2 * depth / ONE_PLY, -VALUE_MATE); ``` does exactly that.

Now we can always use singular extensions which seems to be especially helpful in finding mates.

Passed STC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 25655 W: 4578 L: 4465 D: 16612

and LTC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 66247 W: 8618 L: 8557 D: 49072

bench: 6335042

### CODE REVIEW

**Comment by lucasart** [comment]
If I understand correctly:
* the tested patch, is not the proposed patch. Doesn't that defy the whole point of testing?
* the patch proposed is not a simplification, but was tested in `(-3,1)`, based on a claim that it helps find mates. Has this claim been quantified?

**Comment by Yery** [comment]
For what it is worth; I tested this patch against current master on the 6500+ Chest mate suite:
with 200K fixed nodes:
- shortest mates found: master: 1206        patch:1205
- any mate found: master:    1903       patch: 2003

with 1 sec time:
- shortest mates found: master:  2667      patch:  2628
- any mate found: master:   3585      patch: 3646

Clearly helps finding faster mates, but can take a little longer to find the shortest mate.

**Comment by mcostalba** [comment]
@lucasart the reason why this is a SPRT[-3, 1] it is because it removes an artificial and ad-hoc limit (Jörg defines it "thoughtless" and I think he has a point).

abs(ttValue) < VALUE_KNOWN_WIN

and instead uses one that is understandable.

@Yery thanks for your tests, I will add them in the commit message.

**Comment by mcostalba** [comment]
@joergoster with the aim of making the condition even more clear and self documenting, why simply don't just set in singular search:

`Value rBeta = std::max(ttValue - 2 * depth / ONE_PLY, -VALUE_MATE);`

and just use 

` ttValue != VALUE_NONE`

in singularExtensionNode condition?

**Comment by joergoster** [comment]
@mcostalba Yes, I thought of this, too. But it's clearly slower for me. Maybe then another sprt(-3, 1) needs to be run?
But I agree, it's more clear and in line with other similar cases, like in ProbCut.
Should I change it and run a sprt test?

**Comment by mcostalba** [comment]
I don't understand how can be slower because singular search is tested only
for high depth nodes and in those cases an additional std::max should not
even be measurable.

Yes please run another sprt test.

**Comment by joergoster** [comment]
@mcostalba Done. Thanks for your support and advice.
@Yery Thanks for running the test.

**Comment by lucasart** [comment]
I think there is a problem with the "self documenting solution": rBeta can be higher than beta.

**Comment by mcostalba** [comment]
@lucasart before the patch was not possible? The patch does not change nohing in this regard I think...

**Comment by joergoster** [comment]
@lucasart This is all about correctly fixing the possibility the assert
```assert(-VALUE_INFINITE <= alpha && alpha < beta && beta <= VALUE_INFINITE);```
gets triggered.
Like I said, the last time this was done in a somewhat 'thoughtless' way by me, by simply re-inserting the statement previously in place.
Making rbeta <= beta looks like a possible idea to try, but as a tuning patch.

**Comment by lucasart** [comment]
@mcostalba: No. In master, rBeta is simply `beta - 2 * depth`.

**Comment by mcostalba** [comment]
@lucasart can you please point out where, becuase I can't find it

**Comment by lucasart** [comment]
@mcostalba: Sorry, I got mixed up between beta and ttValue. But my point remains. With your max formula, you can end up with a singular search above ttValue, instead of below ttValue. This makes no sense, because the whole idea of singular search is to test all other moves to see if they fall "well below" ttValue, then decide the ttMove is singular and should be extended.

I think that a more correct, and equally self documenting fix is simply to skip the singular search when `rBeta =< VALUE_MATE_IN_MAX_PLY`. No need to butcher the rBeta formula.

**Comment by joergoster** [comment]
@mcostalba Both tests passed and I updated the initial comment with the correct results. Let me know if I need to do anything further.

**Comment by mcostalba** [comment]
Merged with 351844061ed

@lucasart maybe you have a point, but in the meantime just merge and close this one.

**Pull request closed without merging**
