### PR TITLE
Tweak time management

### PR DESCRIPTION
**Pull request by lp--**
10+0.1:
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 18970 W: 4268 L: 4029 D: 10673

60+0.6:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 72027 W: 12263 L: 11878 D: 47886

Sudden death 60s:
LLR: 2.95 (-2.94,2.94) [-4.00,0.00]
Total: 14444 W: 2715 L: 2608 D: 9121

Bench: 5882274

### CODE REVIEW

**Comment by mcostalba** [comment]
@lp-- congrats!

Being a TM tweak, do we want to test also with other TC?

**Comment by lp--** [comment]
@mcostalba : yes. waiting for Stephane to say which tests he wants.

**Comment by Vizvezdenec** [comment]
I think that "other tests" should become a standart thing in TM tweaks and be written somewhere in wiki.
My guess is that it should be smth like 40/20, 1+1, 15+0, 100+0 with [-4;0] SPRTs and with autopurging turned off. But ofc it's up to Stephane to decide :)

**Comment by lp--** [comment]
IMO, there is absolutely zero reason to test at fancy time controls like 1+1 or short tc as they can be hugely inefficient by a lot and a  line code which brings something like 7 elos  is not accepted for them anyway. 
Like https://github.com/official-stockfish/Stockfish/pull/480

**Comment by mcostalba** [comment]
Maybe a regression testing for other sensible tc could make sense.

**Comment by DamasClasicas** [comment]
Lp: Interesting change! Are you really sure there is no risks with ''no increment'' time controls?

**Comment by lp--** [comment]
@mcostalba , @DamasClasicas 
Other sensible TCs are sudden death and 40/time.  LTC sudden death certainly should be checked.   Changes include move importance curve, which  influence  average time for move during game, and for increment tc and sudden death objectives are different.  For this tweak it may be better or worse, I don't know.  For 40/time I don't expect anything special. But everything is up to Stephane.

**Comment by lp--** [comment]
Added result of sudden death non-regression test to the header

**Comment by snicolet** [comment]
Thanks for the sudden death test.

What are the other time controls used by external testers on public rating lists and public forums like Talkchess?

**Comment by lp--** [comment]
@snicolet:   ccrl -  40 moves repeating, cegt -  incremental and 40 moves repeating, ipon -  incremental, spcc - increamental, fastgm - incremental and very long sudden death

**Comment by snicolet** [comment]
@lp-- So maybe a 40/time test, what do you think? 
I let you choose a reasonable time limit, and between SPRT[-5..0] or [-4..0]

Congrats for the patch :-)

**Comment by snicolet** [comment]
What would be nice, now that I think of it, is to have some documentation in the commit message for the expected influence of the variable changes (a sort of small dictionary: this variable augment, so the effect will be blah. This variable drops, so the effect will be blah).

Time management is a little bit of a black box at the moment, with very few experts (yourself, @IIvec, @vondele), it would serve as a reference for the community to learn the code management code and hopefully simplify it in the long run.

**Comment by lp--** [comment]
Running http://tests.stockfishchess.org/tests/view/5a9566ec0ebc590297cc8be1

**Comment by lp--** [comment]
@snicolet  With spsa tuning it is not always possible to say where improvements came from.  Maybe .some variables changed randomly or because result was not sensitive enough to them. 
So my explanation of changes would not be necessarily correct, but here it is. 
When decrease of thinking time was added if best move has not changed for several plies by vondele, one more competing indicator was introduced for the same purpose along with increase in score and absence of fail low at root.  It seems that tuning put relatively more importance on that new indicator what allowed to save time. Some of saved time was distributed proportionally between all moves and some more time were given  to moves when score dropped  a lot or best move changed.   Looks also that some other changes in variables redistributed more time from the beginning to later stages of game -  maybe because contempt made game to last longer or for whatever reason. All of this is just single percentages here and there.

**Comment by snicolet** [comment]
@lp-- 
Thanks a lot for the explanations, I have edited the commit message and merged via https://github.com/official-stockfish/Stockfish/commit/ad5d86c7714ae3eaad71e8b3630d38c29dd2c3fe

**Pull request closed without merging**
