### PR TITLE
Simplify non-quiet pruning

### PR DESCRIPTION
**Pull request by locutus2**
STC: http://tests.stockfishchess.org/tests/view/5842be140ebc5903140c5619
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 16014 W: 2839 L: 2710 D: 10465

LTC: http://tests.stockfishchess.org/tests/view/584316a50ebc5903140c5638
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 182360 W: 22830 L: 22914 D: 136616

Bench: 5516626

### CODE REVIEW

**Comment by locutus2** [comment]
The bench is recalculated based on current master.

I have myself some concerns about my patch because its scales very badly with tc. So i'am a little bit afraid that this goes bad at even longer tc.

I would rejoice about comments about this.

**Comment by stockfishdeveloper** [comment]
STC was a very good result--probably about +1-2 ELO.
At LTC, there have been patches committed before that had worse results.....
Overall, I think that at the very least this is a decent simplification.
It would be good to run an ELO test though.

**Comment by ddugovic** [comment]
@locutus2 I too am a bit concerned and hopeful that it passes LTC.

**Comment by mcostalba** [comment]
@locutus2 this is a simplification but the scaling is really bad. Maybe it is just a statistical fluke, but I am afraid to introduce a regression at very long TC (where for us is impossible to test). Eventually re-run at LTC and if it fails or it still passes in so long time then discard it.

**Comment by locutus2** [comment]
@mcostalba 
I try a retest at LTC with lower throughput

**Comment by VoyagerOne** [comment]
If we are rejecting a passed test...then we need to rethink our simplification bounds.
Otherwise we are just consuming resources for no reason.

**Comment by Stefano80** [comment]
Actually, the sensible thing would have been to test at VLTC, let us say 180+1.8, which would correspond to a 18 threads STC test, which we have done in the past.

**Comment by lucasart** [comment]
IMO, this patch is tuning, not simplification. We still have an equivalently complex function of depth and PvNode, but now we manage to write it without an if statement…

**Comment by anshulongithub** [comment]
@mcostalba if you feel and as can be seen that if this patch can possibly introduce regression at LTC then please don't commit this or otherwise we need to have a strong visible reason that confirms that yes this patch is making SF better, only and ONLY THEN.

**Comment by Stefano80** [comment]
I really dont know: repeating a SPRT test with same bounds and same tc is really meaningless and defeats the whole goal of SPRT...

**Comment by ddugovic** [comment]
IMHO from my reading of code this isn't functionally equivalent so calling it a "simplification" seems quite generous if not mistaken!  I agree it would have been reasonable to test for scaling, since the functional change may have a more pronounced effect (than the speedup) at VLTC:

> Actually, the sensible thing would have been to test at VLTC, let us say 180+1.8, which would correspond to a 18 threads STC test, which we have done in the past.

**Comment by muxel** [comment]
I think this is very wrong. Removing PvNode checks should be no simplification, like in asmFish.

IF removing PvNode checks are a simplification then the compiler fails to globally optimize this.
There should be separate code paths for White and Black and PvNode=0 / 1,
greatly reducing branch mispredictions

**Comment by locutus2** [comment]
@mcostalba 
The retest at LTC seems way faster then the last.
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 45502 W: 5821 L: 5732 D: 33949

But regarding the discussion i have no problem with not commiting this.

**Comment by joergoster** [comment]
@locutus2 Congrats!
I see no reason not to commit, to be honest. The first LTC test which took way more games to pass, was most likely simply bad luck.
And the calculation still distuingishes between pv nodes and non-pv nodes.

**Comment by mcostalba** [comment]
@locutus2 the test passed, so patch is OK, but OTH, following the discussion, I see that it is not a real simplification, the conditions are just shuffled, but not simplified. I am sorry for have not noticed it before. Considering the tests have already been done on my request I will commit it anyhow, but I agree with @lucasart , it is not a simplification I commit due to my mistake of not realizing it before.

**Pull request merged**
