### PR TITLE
Stockfish 15 release candidate

### PR DESCRIPTION
**Pull request by vondele**
Todo:

- [x] draft release notes

- [x] finish progression tests:
    https://tests.stockfishchess.org/tests/view/625d156dff677a888877d1be
    https://tests.stockfishchess.org/tests/view/625d1586ff677a888877d1c5

- [x] no issues reported

Bench: 8129754

---

### CODE REVIEW

**Comment by vondele** [comment]
consider this PR the release candidate for the next release.

Comment here if any serious issues are found.

**Comment by stevemaughan** [comment]
Based on this site's thorough tests:

[https://nextchessmove.com/dev-builds](url)

There was a statistically significant drop of 30 ELO in strength between 220207 and 220217. I assumed this would get corrected before a full release. Any comments?

**Comment by vondele** [comment]
yes, that was discussed quite in detail, see https://github.com/official-stockfish/Stockfish/pull/3937 basically the same patch that was a significant gain at VLTC (roughly 1s per move and more), regressed in very fast games. A large number of patches/tests were afterwards tried on fishtest to improve simultaneously at STC and LTC but nothing suitable was found. This was known at the time of merging, and the decision was to merge it as using >1s per move is typical usage.

**Comment by stevemaughan** [comment]
OK — great! As long as you're aware of it and it's been discuss.

**Comment by vondele** [comment]
merged with https://github.com/official-stockfish/Stockfish/commit/e6e324eb28fd49c1fc44b3b65784f85a773ec61c

**Comment by mstembera** [comment]
I thought it would be interesting to measure current SF15 Classical strength versus the last SF version before NNUE was introduced.  The results are:
Elo: 11.81 +-1.8 (95%) LOS: 100.0%
Total: 40000 W: 11072 L: 9713 D: 19215
Ptnml(0-2): 222, 4167, 9870, 5512, 229
nElo: 22.12 +-3.4 (95%) PairsRatio: 1.31
https://tests.stockfishchess.org/tests/view/625ddddce7b02dbe28c999b9
Since Classical is sometimes still used (ex. exhibition matches at CCC) hopefully this datapoint will be useful to switch from the old SF to the latest just with NNUE=false set instead.

**Pull request closed without merging**
