### PR TITLE
Improve testing coverage and remove unused

### PR DESCRIPTION
**Pull request by vondele**
add further tests to CI to cover most features
    
This uncovered a potential race in case setoption was sent between two searches.
As the UCI protocol requires this sent to be went the engine is not searching, setoption now ensures that this is the case.
    
Remove unused code
    
No functional change

### CODE REVIEW

**Comment by snicolet** [comment]
I would be in favor to keep the "combo" implementation in `ucioptions.cpp`, as it is present in the seminal UCI specification document https://wbec-ridderkerk.nl/html/UCIProtocol.html

**Comment by vondele** [comment]
We don't change the UCI interface we present to the user though. 

We haven't had any option that requires a combo style input in the past few years, so this is just an implementation detail IMO. If one day we would add an option that requires combo style input, we could restore the code.

**Comment by mstembera** [comment]
If I was adding an option needing a UCI combo box I would likely not know how to implement it w/ this code gone.   Only someone specifically remembering this removal would know to go back through the history to learn how to restore it.

**Comment by vondele** [comment]
so I've reverted the changes to `ucioption.cpp` ... not sure I agree with the arguments really, but I think it is better to move in steps. We can always remove later.

**Comment by vondele** [comment]
CI seems to run into this issue https://github.com/orgs/community/discussions/63391

**Comment by snicolet** [comment]
Merged via 8192945870967fb9c8801247d0b040b2bc657443, thanks!

**Pull request closed without merging**
