### PR TITLE
Cmh pp

### PR DESCRIPTION
**Pull request by VoyagerOne**

### CODE REVIEW

**Comment by joergoster** [comment]
@VoyagerOne and @locutus2: Congrats to both of you!

**Comment by glinscott** [comment]
Very nice idea!  Congratulations.  The code needs a tiny bit of spacing fix-up, but I can do that when applying it.  Approved!

**Comment by VoyagerOne** [comment]
@glinscott 
Thanks!
This is the very first time I wrote C++ code.  I figured it will get cleaned up...

**Comment by mcostalba** [comment]
@glinscott please while there also squash the commits in a single one and write a proper log message reporting the fishtest results. Eventually I will take care of the code style once committed.

BTW congratulations for the successful patch ! :-)

**Comment by zamar** [comment]
approved.

**Comment by VoyagerOne** [comment]
@mcostalba and @zamar 

Thanks!  Now I can test some more ideas that will compliment with this commit.  Such as cmh_lmr.

**Pull request closed without merging**
