### PR TITLE
Interpolate King Shelter (or Danger)

### PR DESCRIPTION
**Pull request by protonspring**
I was bored this morning, and came up with an interpolation of ShelterWeakness.

It's a bit shorter and an equation is probably preferred over a slew of numbers.  is this useful?  If so, I can do the same for StormDanger.

How should I test this?

### CODE REVIEW

**Comment by snicolet** [comment]
Ah yes, that would be incredible if it worked!

Testing with [0..4] is fine.

**Comment by Hanamuke** [comment]
[-3,1] i'd say, since you want to do a simplification.

**Comment by protonspring** [comment]
I can't figure out how to tune.  Could someone tune these values?
ShelterRANK1
ShelterBase
ShelterInc

**Comment by syzygy1** [comment]
Wouldn't this be a simplification for which [-3,1] is sufficient?

Since file would no longer be used, the array can be simplified further.

**Comment by protonspring** [comment]
Like that?  Is this now a simplification?

**Comment by Hanamuke** [comment]
@protonspring Now i have to agree with ronald yeah.

**Comment by WOnder93** [comment]
Since the formula is so simple now, perhaps you could go one step further and compute it in-place (without precomputing a table).

**Comment by protonspring** [comment]
I think I figured out tuning.  I will play with this for a bit.

**Comment by protonspring** [comment]
@WOnder93 Good idea.  I did a few bench tests, but it was -20k nps slower on my machine.

**Comment by syzygy1** [comment]
But I think you have some experience now that speedups or slowdowns in the order of 20knps as measured on one machine are essentially meaningless.

**Comment by protonspring** [comment]
So, should I just test both versions (The precomputed array vs. the calculate on the fly)?

**Comment by snicolet** [comment]
@protonspring  
I am closing the pull request for now, as the original question has been answered. FGood luck with your tests!

**Pull request closed without merging**
