### PR TITLE
Introduce yielding spin locks

### PR DESCRIPTION
**Pull request by zamar**
Implementation by Stéphane Nicolet

7 threads 15+0.05
ELO: 3.54 +-2.9 (95%) LOS: 99.2%
Total: 17971 W: 2976 L: 2793 D: 12202

### CODE REVIEW

**Comment by zamar** [comment]
Naturally we need to rename mutex -> spinlock.

**Comment by mcostalba** [comment]
I suggest to rename allocMutex -> spinlock

and lock->acquire, unlock->release because it is more idiomatic with
spinlocks, see for instance

https://msdn.microsoft.com/en-us/library/windows/hardware/ff548114%28v=vs.85%29.aspx

**Comment by glinscott** [comment]
Nice, looks good!!

**Comment by zamar** [comment]
I've merged the patch, but haven't yet done the renaming.

I'll leave this request open as a reminder until the renaming has been done.

**Comment by mcostalba** [comment]
Here is the renaming:

https://github.com/official-stockfish/Stockfish/pull/292

**Comment by zamar** [comment]
Closing this as Marco has opened up a new pull request...

**Pull request closed without merging**
