### PR TITLE
Fix #2737 syzygy memcopy

### LINKED ISSUE #2737: Syzygy compile error
```
Flags:
CXX: clang++
CXXFLAGS: -Werror -Wall -Wcast-qual -fno-exceptions -std=c++11  -pedantic -Wextra -Wshadow -m64 -g -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2
LDFLAGS:  -latomic -m64 -lpthread

Testing config sanity. If this fails, try 'make help' ...

make ARCH=x86-64-bmi2 COMP=clang all
make[1]: Entering directory '/home/dand/Desktop/Stockfish/src'
clang++ -Werror -Wall -Wcast-qual -fno-exceptions -std=c++11  -pedantic -Wextra -Wshadow -m64 -g -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -Wall -Wcast-qual -fno-exceptions -std=c++11  -pedantic -Wextra -Wshadow -m64 -g -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2   -c -o tbprobe.o syzygy/tbprobe.cpp
syzygy/tbprobe.cpp:1203:22: error: loop variable 'move' has type 'const Move &' but is initialized with type 'const ExtMove' resulting in a copy [-Werror,-Wrange-loop-construct]
    for (const Move& move : moveList)
                     ^
syzygy/tbprobe.cpp:1203:10: note: use non-reference type 'Move' to keep the copy or type 'const ExtMove &' to prevent copying
    for (const Move& move : moveList)
```

Environment info:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

### PR DESCRIPTION
**Pull request by ddugovic**
Please advise whether I should file a ticket with clang in case the compiler warning is faulty.

### CODE REVIEW

**Comment by Sopel97** [comment]
the warning has its merits

**Comment by snicolet** [comment]
Is there a way to implement iterating the move list during these tablebase accesses with the copying?

**Comment by vondele** [comment]
actually, I introduced this after fixing another clang warning for that line. The problem is the moveList is ExtMove, while we want Move. I guess we need to use const Move ?

**Comment by ddugovic** [comment]
Ah, I hadn't considered that possibility and am out of my element here.

**Comment by vondele** [comment]
Actually, I didn't commit this yet, but is part of the small cleanups:
https://github.com/official-stockfish/Stockfish/pull/2695/commits/12d8b68760379cfa7418b4cb483c7ff1b1b9929a

**Comment by ddugovic** [comment]
Thanks, looks good to me.

**Comment by Sopel97** [comment]
> Is there a way to implement iterating the move list during these tablebase accesses without the copying?

`operator const Move&` in `ExtMove` instead of `operator Move`

**Pull request closed without merging**
