### PR TITLE
Assorted code style issues

### PR DESCRIPTION
**Pull request by mcostalba**
I have removed the check for

 pieceCount[PAWN] > FILE_NB

because totally useless.

No functional change.

### CODE REVIEW

**Comment by joergoster** [comment]
@mcostalba Please feel free to include the changes from here https://github.com/joergoster/Stockfish/commit/adbdcfecfbf59c9a06b94d6db59d0b0d5ad972a8 which you consider to make sense.

**Comment by snicolet** [comment]
Also: 

• the `else`in line 774 of evaluate.cpp is useless since the previous `if`block always returns
• there are trailing spaces in line 655 of endgame.cpp

**Comment by mcostalba** [comment]
@joergoster @snicolet Thanks!

I have incorporated most of your suggestions. I have left out the 'else if -> if' changes because it is more clear the control flow as is now IMO: if first condition is not true then move to second one, realizing that if first condition is true then function returns is an extra logical step imposed on the human reader. Note that the non-human reader (e.g. the compiler) will easily realize it by itself and generate optimized code anyhow.

**Comment by mstembera** [comment]
Nice! 
Could we also fix line 568 in search.cpp to avoid this MSVC warning
"search.cpp(568): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data"
```C++
thisThread->callsCnt = Limits.nodes ? std::min(4096, int(Limits.nodes / 1024))
                                            : 4096;
```
is one way.

**Comment by mcostalba** [comment]
@mstembera thanks. Updated.

**Comment by Rocky640** [comment]
In evaluate.cpp, line 183, there is a misaligned S(-4, 7) (can replace with S( -4, 7))

Line 214-217, the QueenContactCheck was recently removed, leaving some extra blanks that can be removed.

in evaluate_pieces, the following 2 lines can be switched. 
const PieceType NextPt = (Us == WHITE ? Pt : PieceType(Pt + 1));
const Color Them = (Us == WHITE ? BLACK : WHITE);

**Comment by mcostalba** [comment]
@Rocky640 thanks! Updated.

**Comment by zamar** [comment]
@mcostalba: Looks fine. Feel free to rebase and push!

**Comment by Rocky640** [comment]
In evaluate_threats, since we do not enumerate the safeThreats anymore, 
the following line order is more natural:

       `safeThreats = (shift<Right>(b) | shift<Left>(b)) & weak;

        score += ThreatBySafePawn * popcount(safeThreats);

        if (weak ^ safeThreats)
            score += ThreatByHangingPawn;`

**Comment by mcostalba** [comment]
Merged with b48439e90643cb6f65f9

**Pull request closed without merging**
