### PR TITLE
Remove redundant condition from capture_stage()

### PR DESCRIPTION
**Pull request by mstembera**
No functional change
bench: 4747020

### CODE REVIEW

**Comment by mstembera** [comment]
I would also like to change this line in position.cpp https://github.com/official-stockfish/Stockfish/blob/39da50ed23ee3f1bd32a58c8f02471faa9a9fd63/src/position.cpp#L572 to an assert() if maintainers agree.

**Comment by vondele** [comment]
I wonder if we have capturing under promotions right.

**Comment by dubslow** [comment]
How do you mean? This PR is nonfunctional, and the reason we reverted from `capture` to `capture_or_qpromo` was because of duplicate move generation, which was confirmed to be fixed. (And in search, reverting to simply `capture` failed nonreg, altho as I understand that would also have fixed the duplicate generating.)

**Comment by vondele** [comment]
I'm think that maybe the right way to write capture_stage() is 

`(type_of(m) != PROMOTION && capture(m)) || promotion_type(m) == QUEEN;`

but I'm not quite sure where capturing under promotions are being generated, and if there could be duplicates in that case.

**Comment by peregrineshahin** [comment]
> I'm think that maybe the right way to write capture_stage() is
> 
> `(type_of(m) != PROMOTION && capture(m)) || promotion_type(m) == QUEEN;`
> 
> but I'm not quite sure where capturing under promotions are being generated, and if there could be duplicates in that case.

It seems that your observation is correct to my eyes.
here is the place we make promotions based on type regardless of the `to` if it is UP or UpRight or UpLeft.

```
  ExtMove* make_promotions(ExtMove* moveList, [[maybe_unused]] Square to) {

    if constexpr (Type == CAPTURES || Type == EVASIONS || Type == NON_EVASIONS)
        *moveList++ = make<PROMOTION>(to - D, to, QUEEN);

    if constexpr (Type == QUIETS || Type == EVASIONS || Type == NON_EVASIONS)
    {
        *moveList++ = make<PROMOTION>(to - D, to, ROOK);
        *moveList++ = make<PROMOTION>(to - D, to, BISHOP);
        *moveList++ = make<PROMOTION>(to - D, to, KNIGHT);
    }

    return moveList;
  }
  ```

**Comment by mstembera** [comment]
Nice catch.  I also think excluding non queen promotions from captures is correct.  Perhaps the order
```(capture(m) && type_of(m) != PROMOTION) || promotion_type(m) == QUEEN;```
is slightly more optimal speed wise because type_of(m) != PROMOTION is almost always true not allowing us to skip the capture(m) but vice versa we can skip the second condition more of the time.  But that's just a tiny nit pick.

Perhaps we should confirm w/ the original author of https://github.com/official-stockfish/Stockfish/pull/4405 @Vizvezdenec

**Comment by peregrineshahin** [comment]
I tried the non-obvious fix but it failed for some reason.
https://tests.stockfishchess.org/tests/view/641394c665775d3b539e1ebe

I think the obvious fix should be tried also.
> I'm think that maybe the right way to write capture_stage() is
`(type_of(m) != PROMOTION && capture(m)) || promotion_type(m) == QUEEN;`

**Comment by mstembera** [comment]
I started https://tests.stockfishchess.org/tests/view/6414203565775d3b539e3aed

**Comment by peregrineshahin** [comment]
I'm starting a take 2 https://tests.stockfishchess.org/tests/view/6415579f65775d3b539e7537 just in case if [mstembera](https://github.com/mstembera) test failed LTC.

**Comment by peregrineshahin** [comment]
Luckily enough .. after lots of debugging, I don't think we have any issue regarding exactly duplicate moves generating in move picker or in search as we did for queen promotions, that being said I would still be in favor of merging any of the fixes proposed for consistency regarding pruning and updating history stats so I will submit a PR at any rate.

**Comment by mstembera** [comment]
https://github.com/official-stockfish/Stockfish/pull/4454

**Comment by vondele** [comment]
closes this again as other PRs take care of the issue mentioned.

**Comment by mstembera** [comment]
@vondele ok but https://github.com/official-stockfish/Stockfish/pull/4454 is still sitting there after I already rebased it twice.  Should I do something else?

**Comment by vondele** [comment]
nothing particular, I need some clear mind to look at both alternative PRs.

**Pull request closed without merging**
