### PR TITLE
History Table Split

### PR DESCRIPTION
**Pull request by VoyagerOne**
Split history table based on material captured relative to the root position. 

STC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 12466 W: 2330 L: 2152 D: 7984

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 23014 W: 3180 L: 2985 D: 16849

### CODE REVIEW

**Comment by Rocky640** [comment]
Congratulations !

Probably another of my stupid comments...but can we imagine having many more history tables,
say 32, one for each possible piece + pawn count on the board, and have less aging (or none) on each of these tables ? Often, engines are "just shuffling" for many moves ...but one single exchange (or pawn move...) changes the whole position.

**Comment by VoyagerOne** [comment]
@Rocky640 
Not stupid at all.  I had the same thinking...

This is just the foundation to build/simplify on.  My next step on this idea is to consider pawns...which is a small tweak.  From there we can try to divide the table up a bit based on material/capture piece etc.  Like majority of chess features it will be an evolving process...

**Comment by joergoster** [comment]
Congrats!

**Comment by mstembera** [comment]
Congrats!

**Comment by lucasart** [comment]
@Rocky640: I would prefer to have 2 history tables. 1 for opening, 1 for endgame. Interpolate history score out of the 2 tables using game phase. More continuous, and more elegant.

**Comment by zamar** [comment]
My recommendation would be to measure the ELO value of this change... This is quite a fundamental change, and so the patch should prove to be worth more than usual. Let's say if we measure the patch to be worth at least 3-4 ELO in long time control, I'd be happy to commit this.

If it is worth less than 3-4 ELO, we should try to improve the idea before committing.

**Comment by mcostalba** [comment]
Also a smp test is needed IMO because this as an impact too.

**Comment by VoyagerOne** [comment]
@zamar 
Agreed.

I will try to tinker with this a bit to improve it before running an ELO test.

**Comment by AlexandreMasta** [comment]
I think that 3-4 elo is in fact too high. No patch will pass. Seems that SF team is throwing away nice patches nowadays. In this stage of engines...with the level of accuracy achieved by all engines an elo gain is more and more difficult to be gained. 3-4 elo is in fact a super patch in this level because more and more draws are happening.

**Comment by IIvec** [comment]
Maybe there is no need for LTC SPRT then. Maybe this ELO measure can replace SPRT?
For example, to set ELO 2.5 after 60000 games as a passing criterion.

**Comment by lucasart** [comment]
@zamar @IIvec: Resorting to fixed game testing is never the correct solution. SPRT is always going to be more efficient (on average) for a given testing resolution. If you want to impose a stricter passing standard for ugly or complicated patches, you should instead shift the bounds. For example SPRT(2,7) would make sense here. 2 BayesElo at LTC is about 1 Elo (and BayesElo <-> Elo can be assumed linear around zero, so 7 BayesElo = 3.5 Elo).

**Comment by lucasart** [comment]
More generally, we should be using `SPRT(U, U+R)`, where:
* R is the resolution. Currently 5 BayesElo.
* U is the uglyness add-on. The uglier the patch, the larger U should be.

**Comment by IIvec** [comment]
I think that current testing methodology is just fine. I was the first one for improving things, but now I see that our resources are not unlimited, and current tc and bounds seems OK for me. If we change something, SPRT(1,6) is enough.

**Comment by zamar** [comment]
I'm closing this pull request as the patch needs to be improved before merging.

**Pull request closed without merging**
