### PR TITLE
Small clean-up, April 2021

### PR DESCRIPTION
**Pull request by snicolet**
No functional change

### CODE REVIEW

**Comment by QuackQuackBlah** [comment]
Would it be better to say instead of "These informations", to say "This information" on line 246?

**Comment by snicolet** [comment]
Both the Stockfish version and the name of the compiler are relevant :-)

**Comment by ddobbelaere** [comment]
Don't want to start a linguistic discussion here, but "these informations" is never correct in English, as "information" is an uncountable noun. See https://dictionary.cambridge.org/dictionary/english/information (note the [U] next to "noun").

This is in contrary to e.g. French, where "ces informations" is possible. However, in e.g. Dutch, "deze informaties" is likewise nonsense, as "informatie" is uncountable, just as in English.

**Comment by mstembera** [comment]
Line 1130 in evaluate.cpp
```
if (   largePsq && !strongClassical
```
should be split into two to align with the third expression below it
```
if (   largePsq
    && !strongClassical
```

**Comment by snicolet** [comment]
Merged via b862c8d4be2cf6245360a8072ab910a67eb5bc00

**Pull request closed without merging**
