### PR TITLE
Miscelleneous optimization

### PR DESCRIPTION
**Pull request by ajithcj**
Optimize If statements to use the simplest conditions first.
Also fix size of KingDanger array.
 
Gives a small speedup after 10 bench runs on my machine:
New master
=========
Nodes/second    : 1837579
Nodes/second    : 1842637
Nodes/second    : 1860995
Nodes/second    : 1861858
Nodes/second    : 1853266
Nodes/second    : 1842637
Nodes/second    : 1853694
Nodes/second    : 1881484
Nodes/second    : 1870094
Nodes/second    : 1864451

Mean value: 1856869.6

Current master
==========
Nodes/second    : 1837999
Nodes/second    : 1844753
Nodes/second    : 1831712
Nodes/second    : 1841792
Nodes/second    : 1840948
Nodes/second    : 1851984
Nodes/second    : 1861858
Nodes/second    : 1849000
Nodes/second    : 1851557
Nodes/second    : 1839683

Mean value: 1845128.6

Speedup: 0.64%

No functional change

### CODE REVIEW

**Comment by gogamoga1** [comment]
Confirm speedup with 2 different PGO compils

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1769734   1784725   -14991    
    StDev   31500     32098     5718      

p-value: 0,996
speedup: 0,008


Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1788466   1800530   -12064    
    StDev   12863     12654     5856      

p-value: 0,98
speedup: 0,007

**Comment by saproj** [comment]
I tested your changes to search.cpp in OSX. It turns out that only one of them reliably contributes to the speed-up.

All changes in search.cpp except the last one (TT conditions):
Result of  30 runs
```
base =    1818884  +/- 6534
test =    1814063  +/- 5409
diff =      -4821  +/- 2871

speedup        = -0.0027
P(speedup > 0) =  0.0005
```

All changes in search.cpp:
```
Result of  30 runs
base =    1819616  +/- 5830
test =    1824887  +/- 5726
diff =      +5271  +/- 767

speedup        = +0.0029
P(speedup > 0) =  1.0000
```

**Comment by mcostalba** [comment]
I am very confident only a small part of these changes contribute to the speed up. Please remove all the useless changes and just leave what has a measured positive contribution.

**Comment by ajithcj** [comment]
@mcostalba, I tried locally adding/removing some terms and have raised a new pull request https://github.com/official-stockfish/Stockfish/pull/778

You can consider whichever one is faster based on tests by others.

**Comment by mcostalba** [comment]
@ajithcj thanks!

I have quickly checked the new PR and I agree these are the only ones that make some sense to me.

I have some doubts about shrinking of KingDanger size. For sure it doe snot speed up anything, so I would like to ask why you did that.

**Comment by ajithcj** [comment]
The KingDanger array is initialized only for 400 entries in evaluate.cpp.
  for (int i = 0; i < 400; ++i)
  {
      t = std::min(Peak, std::min(i * i - 16, t + MaxSlope));
      KingDanger[i] = make_score(t * 268 / 7700, 0);
  }
and only these entries are used:
        score -= KingDanger[std::max(std::min(attackUnits, 399), 0)];

I don't see any reason why we should use up 512 entries. Ofcourse I agree that this might not speedup anything. But i don't see why we should declare 512 when we use only 400 entries.

**Comment by ajithcj** [comment]
I don't really know why KingDanger is declared with more entries than required. It used to be 128 entries(of which only 100 were used). Later this patch increased it to 512 while using up only 400 entries:
http://tests.stockfishchess.org/tests/view/54a7c91a0ebc596d9eff515a

**Comment by mcostalba** [comment]
Closing this, I will merge #778 instead

**Pull request closed without merging**
