### PR TITLE
eliminate "goto moves_loop statement"

### PR DESCRIPTION
**Pull request by MichaelB7**
Simplification : no functional change, slight speed pickup under clang and gcc for both build and pgo build, reduction in code, search and signature (bench)  remains the same.

### CODE REVIEW

**Comment by MichaelB7** [comment]
also , before we commit this, I believe  line 824 in search.cpp can also be deleted as I do not receive a compiler error using gcc - can others confirm?

` line 824:                    value = bestValue; // Workaround a bogus 'uninitialized' warning under gcc`

**Comment by lantonov** [comment]
gcc (4.7.3 and 6.2.0) and gdb do not complain on removing search.cpp:824

**Comment by Rocky640** [comment]
IMO Current master code is more readable.

**Comment by MichaelB7** [comment]
That's fine.  Everybody has a right to their own opinion.  https://en.m.wikipedia.org/wiki/Goto

**Comment by Rocky640** [comment]
Indeed ! I know it is controversial. From the same source:
"Situations in which goto is often useful include:
◾To make the code more readable and easier to follow[28][29]
◾To make smaller programs, and get rid of code duplication 
"
A single, well thought, goto label in a procedure is all right to me. 
But I would avoid at all costs having more than one goto label in the same procedure.

**Comment by stockfishdeveloper** [comment]
I think it would be better to finally get rid of the goto statement.....

**Comment by syzygy1** [comment]
I may be misreading the patch, but breaking proper indentation just to get rid of a goto is not making things better.

In my view this particular goto is the right solution in the right place and in no way harms the code. That a famous computer scientist in a pre-structured-programming era warned against the use of goto where it leads to spaghetti code does not make this goto bad.

**Comment by ddugovic** [comment]
While "reduction in code" may be accurate from a character-count perspective (ignoring whitespace were code properly indented) compilers should be intelligent enough to perform optimizations such as this, and the real concern is ease of maintenance & understanding.

From a maintenance perspective, if any of the conditional expressions change then dozens of lines of nested code might need to move around.  (On the other hand, as it currently stands if any of the conditional expressions change then multiple lines of code might need to change.)

**Comment by MichaelB7** [comment]
As far as indentation goes , if I used proper indentation , almost every line after this would have re-indented and then every line changed would show as a plus and minus - at least it did for me. So I figure indentation would be fixed prior to merging but after the approval to move forward. You might be talking about something else and if you are , my apologies for not understanding you correctly.  Appreciate your opinion, to me a goto statement should be avoided in most cases and I feel both of these can be removed safely with no lack of understanding except perhaps to the documentation wording to show that "incheck skips this section" as opposed to saying "incheck starts here" since all the other non incheck moves are also getting processed here as well where we say incheck starts here.

**Comment by ddugovic** [comment]
Indeed, it makes sense to review this diff before making further changes.  Sorry for being late to chime in on this but until this PR it was too difficult to understand the changes.

IMHO [complexity](http://en.wikipedia.org/wiki/Cyclomatic_complexity) is difficult to measure for [arrow code](http://blog.codinghorror.com/flattening-arrow-code/).  This function is too cohesive to extract a new function as Atwood would suggest, and yet "indenting" 100 lines of code affects ease of understanding (since the developer when making a change needs to scroll up many lines to understand the context).

Perhaps the simplest solution would be for the original author to add a comment explaining the `goto` label.

**Comment by lucasart** [comment]
The "cure" is worse than the "disease". Code is fine as is.

**Comment by MichaelB7** [comment]
Closing is the consensus .

**Pull request closed without merging**
