### PR TITLE
PopCnt speedup(about 3.5%) using lookup table for 32-bit compiles

### PR DESCRIPTION
**Pull request by mstembera**
My reasons for opening this are the same as what I wrote here
https://github.com/official-stockfish/Stockfish/pull/618

```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    699600    724358    -24758    
    StDev   215732    222883    16532     

p-value: 0.933
speedup: 0.035
```

### CODE REVIEW

**Comment by mstembera** [comment]
Note to anyone compiling this to verify:  Somewhat counter intuitively, specifying ARCH=x86-32 does NOT produce a 32-bit binary if you are on a 64-bit OS.   Adding COMP=mingw CXX=i686-w64-mingw32-c++ does work if you have the right tools installed.

**Comment by mcostalba** [comment]
The reason you point out to accept this patch is to allow to helping
removing piecelist, but popcount has nothing to do with piecelist.

You are trying to optimize an obsolete platform as 32bit for no real reason.

I' prefer to keep the code optimized for mainstream 64 bit and simple for
other cases. You are filling sources with a bunch of ifdef, while instead I
am doing my best to remove as much ifdef as possible.

**Comment by mstembera** [comment]
> The reason you point out to accept this patch is to allow to helping
> removing piecelist, but popcount has nothing to do with piecelist.

I never made this claim.  Please read my comment again.

> You are trying to optimize an obsolete platform as 32bit for no real reason.

Yes 32-bit is obsolete. I have known about this optimization for over a year but never submitted it till your and Lucas tests showed me 32-bit machines still have a strong effect on fishtest.  Unfortunately we still allow 32-bit on fishtest.  Therefore ANY low level functionality that is very different speed wise from 64-bit affects/skews fishtest results.  As an example here is a patch that perhaps got it's results skewed by slow 32-bit popcnt.
https://github.com/official-stockfish/Stockfish/pull/600

> I' prefer to keep the code optimized for mainstream 64 bit and simple for
> other cases. You are filling sources with a bunch of ifdef, while instead I
> am doing my best to remove as much ifdef as possible.

Yes I don’t like it either but removing/reducing any 32-bit bias from fishtest is more important IMO precisely because 32-bit is obsolete.  I will make an attempt to make it work uniformly for 64-bit as well though so stay tuned…

**Comment by mstembera** [comment]
Ok here is a version that's actually also a simplification and as a bonus also about a 1% speedup on 64-bit w/o a hardware popcnt instruction.  I would like someone to please verify of course.  Also note that this allows further simplification because we can now get rid of the distinction between Full and Max15 if we want.

ARCH=x86-64 results(x86-64-modern is unchanged)
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    916990    930853    -13863    
    StDev   228171    231512    4757      

p-value: 0.998
speedup: 0.015
```

**Comment by mcostalba** [comment]
I will test it this week end when I will be able to setup a proper 32 bit
environment.

**Comment by lucasart** [comment]
@mstembera: I confirm the speed-up on 32-bit
```
x86-32        nps    +/-
test    1,996,002  1,213
master  1,936,857  3,006
diff       59,145  3,065
diff%       3.05%  0.16%
```

**Comment by lucasart** [comment]
@mstembera: I also confirm the speed-up on 64-bit w/o popcorn
```
x86-64        nps    +/-
test    2,631,700  2,191
master  2,554,873  6,228
diff       76,828  6,390
diff%       3.01%  0.25%
```
Nice work!

**Comment by mcostalba** [comment]
@mstembera please add this one https://github.com/mcostalba/Stockfish/commit/PopCnt32 to your patch. Thanks.

**Comment by mcostalba** [comment]
@mstembera @lucasart now that we don't require 2 popcount functions at run time anymore (Max15 and Full), but just one (hw or sw) that we can define at compile time, we don't need anymore all the template stuff in bitcount.h, indeed we don't need anymore even bitcount.h, so I have retired it and moved popcount() to bitboard.h

Now the patch is a massive simplification so it is ok for me to commit as is, without further testing the 32 bit case that I don't care in this case, considering the huge removal of code.

**Comment by lucasart** [comment]
@mcostalba: nice!

**Comment by MichaelB7** [comment]
+1!

**Comment by mstembera** [comment]
@mcostalba 
Done.  Thanks!

**Comment by joergoster** [comment]
Great stuff! It's like learning from the best.

**Pull request closed without merging**
