### PR TITLE
[NNUE] Update default net to nn-03744f8d56d8.nnue

### PR DESCRIPTION
**Pull request by sergiovieri**
Equivalent to 20200914-1520

STC:
LLR: 2.93 (-2.94,2.94) {-0.25,1.25}
Total: 7504 W: 1003 L: 836 D: 5665
Ptnml(0-2): 34, 614, 2322, 715, 67
https://tests.stockfishchess.org/tests/view/5f5f36d361bdd7a0007e7772

LTC:
LLR: 2.94 (-2.94,2.94) {0.25,1.25}
Total: 20400 W: 1433 L: 1261 D: 17706
Ptnml(0-2): 34, 1049, 7871, 1203, 43
https://tests.stockfishchess.org/tests/view/5f5f43cf61bdd7a0007e7775

Bench: 4222126

### CODE REVIEW

**Comment by FauziAkram** [comment]
Congrats mate, I really wish you give us some insights on how you build the new nets, much respect for your work

**Comment by MichaelB7** [comment]
Thank you Sergio!

**Comment by vondele** [comment]
Unfortunately, I forgot to paste the test results in the commit message. Nice results, however!

**Comment by vondele** [comment]
Looks even stronger against SF7: https://nextchessmove.com/dev-builds#20200915-0521

**Pull request closed without merging**
