### PR TITLE
Reformat code

### PR DESCRIPTION
**Pull request by XInTheDark**
No functional change

### CODE REVIEW

**Comment by Disservin** [comment]
In my opinion this is not the correct way to do this.
I have started a similar discussion some time ago at https://github.com/official-stockfish/Stockfish/discussions/4227

**Comment by snicolet** [comment]
Thanks for the PR! You may find https://tirania.org/blog/archive/2010/Dec-31.html an interesting read.

**Comment by XInTheDark** [comment]
> Thanks for the PR! You may find https://tirania.org/blog/archive/2010/Dec-31.html an interesting read.

Hi, I agree that it may not be beneficial to reformat everything, although fixing indentation issues could be a good idea.

**Comment by XInTheDark** [comment]
> Thanks for the PR! You may find https://tirania.org/blog/archive/2010/Dec-31.html an interesting read.

Hi, I agree that it may not be beneficial to reformat everything, although fixing indentation issues could be a good idea.

**Comment by vdbergh** [comment]
I think it would be best to use autoformatting for stockfish. Fishtest uses this and it greatly simplifies maintenance.

**Comment by ppigazzini** [comment]
Open Issue for auto formatting, see https://github.com/official-stockfish/Stockfish/issues/3608

**Comment by roim** [comment]
IMO, if reformatting will happen, #3608 is the way to go, and then let CI test/format vs reviewing to be sure nothing bad is coming in this PR.

**Comment by vondele** [comment]
so, I'll close this PR. Eventually some automatic formatting might make sense.

**Pull request closed without merging**
