### PR TITLE
multiPV lazy SMP bug fix

### PR DESCRIPTION
**Pull request by mstembera**
The helper threads were not doing any multiPV at all under lazy SMP.  If there is a reason for the code to be the way it is please let me know.  Also please advise if any test is necessary.

### CODE REVIEW

**Comment by joergoster** [comment]
@mstembera Nice catch! This one is not so obvious to verify, because nps and total searched nodes are very close. But with the fix the search depth is higher!

startpos, MultiPV 10, 7 threads,
without the fix:
info depth 22 seldepth 33 multipv 10 score cp -6 nodes 1054121670 nps 7140294 hashfull 999 tbhits 0 time 147630 pv h2h3 g8f6
info depth 23 currmove h2h3 currmovenumber 10
info depth 23 currmove b2b4 currmovenumber 11
info depth 23 currmove h2h4 currmovenumber 12
info depth 23 currmove b1a3 currmovenumber 13
info depth 23 currmove a2a4 currmovenumber 14
info depth 23 currmove b2b3 currmovenumber 15
info depth 23 currmove g2g4 currmovenumber 16
info depth 23 currmove f2f4 currmovenumber 17
info depth 23 currmove g2g3 currmovenumber 18
info depth 23 currmove f2f3 currmovenumber 19
info depth 23 currmove g1h3 currmovenumber 20
info depth 23 currmove h2h3 currmovenumber 10
info nodes 1070737504 time 150001
bestmove g1f3 ponder e7e6

and with the fix:
info depth 24 seldepth 38 multipv 10 score cp -7 nodes 1069862757 nps 7204220 hashfull 999 tbhits 0 time 148505 pv d2d3 d7d5 g1f3 e7e6 c1f4 g8f6 b1d2 f8e7 e2e3 e8g8 f1e2 b7b6 e1g1 c7c5 c2c4 b8c6 f3e5 c8b7 c4d5 c6e5 f4e5 f6d7 e5g3 e6d5
info depth 25 currmove d2d3 currmovenumber 10
info nodes 1080487070 time 150000
bestmove e2e4 ponder e7e6

**Comment by mcostalba** [comment]
This is quite subtle because has an impact also in usual case with SMP. Can you please run a test with 7 threads, STC[-3, 1] is enough, thanks.

**Comment by mstembera** [comment]
I believe this is completely non functional in the normal SMP single PV case.  Instead of exiting at the original break we still exit immediately on line 435 instead because of the PVIdx < multiPV condition.   If you want me to run the test anyway I will,  only worried about wasting resources and possible false negatives.  Just let me know. Thanks.

**Comment by mcostalba** [comment]
@mstembera please run the test. Thanks. With SMP stuff better safe than sorry.

**Comment by mstembera** [comment]
Test scheduled
http://tests.stockfishchess.org/tests/view/572b24060ebc59301a354b83

**Comment by VoyagerOne** [comment]
This test is just wasting resources as the tested code will never be reached...
Multi-PV is not set in Fishtest.
Please stop this test.

**Comment by mstembera** [comment]
@VoyagerOne I agree with you but as I said you need to convince @mcostalba

**Comment by joergoster** [comment]
@VoyagerOne This is simply not true! Changed code will **always** be triggered, even with multipv==1. Many non-functional patches turned out to be a loss in the past, especially in case of SMP. But I admit LazySMP is much less tricky than YBW implementation was, and eventually less tightened bounds like [-4, 0] ot even [-5, 0] would have been sufficient in this case ...

**Comment by theo77186** [comment]
@VoyagerOne I also support the fact that we need to test this with MultiPV=4 or anything like this, with the bounds [-4, 0]. If the current test passes [-3, 1], then maybe we have to consider the SPRT with the MultiPV.

**Comment by KassiasGrandiel** [comment]
The test that mstembera scheduled is already done. Can we merge now?

**Comment by mstembera** [comment]
@KassiasGrandiel The test is not done.  Please don't inject noise.

**Comment by mstembera** [comment]
Test results:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 73918 W: 11891 L: 11853 D: 50174

**Comment by KassiasGrandiel** [comment]
Now it's done

**Comment by mcostalba** [comment]
Merged with 0784bd542bf17679fe

**Pull request closed without merging**
