### PR TITLE
Futility Simplification

### PR DESCRIPTION
**Pull request by VoyagerOne**
Futility Simplification:
Don't update bestValue when futility pruning.

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 21933 W: 4031 L: 3912 D: 13990

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 46225 W: 6115 L: 6028 D: 34082

Bench:  7226540

Note:
I consider updating the bestValue at futility pruning a bug.  Since we use futility pruning far away from the leaves and the move that updates the bestValue may even be illegal.

### CODE REVIEW

**Comment by locutus2** [comment]
Congrats too!

**Comment by KassiasGrandiel** [comment]
@Nikita-Guskov I fixed this bug at https://github.com/KassiasGrandiel/Stockfish/tree/patch-1

**Comment by VoyagerOne** [comment]
@Nikita-Guskov 
Thanks, made the change.

**Comment by sf-x** [comment]
Why was the comment "Futiliy pruning..." removed from source? This removal does not simplify anything.

**Comment by zamar** [comment]
The comment should be put back.

Updating bestValue in futility pruning is not a bug, but based on carefully work-out logic. Whether we are close to leaves or not, doesn't have any impact on it.

However, it has been a long on-going debate whether it's better to update bestValue in futility pruning or not.
You can arguments for it and against it.

So, I'm fine with this change.

**Comment by VoyagerOne** [comment]
@zamar 
Comment is put back in now.

FYI:
I did a local test where I place futility pruning first (before moveCount pruning)...the idea is that if updating bestValue is beneficial we should prune with futility first since it will have a higher chance of updating the bestValue.  The local test showed a clear regression.  This convinced me that updating bestValue was not ideal.

**Comment by lucasart** [comment]
@zamar: agree. The important part is the bestValue > -Inf condition, that prevents search from returning -Inf, if all moves are pruned. Indeed, a -Inf return value can eventually leak, by fail soft, to PV nodes, and who wants to see a PV with bogus infinite score?

**Comment by mcostalba** [comment]
Could it happen that all the moves are pruned and we return with bestValue = -infinite?

Search seems easy but is full of subtle traps, especially regarding these cases.

**Comment by snicolet** [comment]
@mcostalba: isn't it prevented by the last condition on line 956?

**Comment by lucasart** [comment]
@mcostalba: As I said above, bestValue > -Inf prevents this.

**Comment by mcostalba** [comment]
@snicolet @lucasart ok, thanks. In this case I will commit it.

@VoyagerOne coul dyou please squash teh commits in a single one and rebase (not merge!) above current master? Thanks.

**Comment by VoyagerOne** [comment]
See:  https://github.com/official-stockfish/Stockfish/pull/688

**Pull request closed without merging**
