### PR TITLE
Fix StateInfo leak

### PR DESCRIPTION
**Pull request by gvreuls**
Fix the StateInfo memory leak reported by the address sanitizer:

> ==473916==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 2432 byte(s) in 1 object(s) allocated from:
>     #0 0x7f55e13c0067 in operator new(unsigned long, std::align_val_t) (/lib64/libasan.so.6+0xad067)
>     #1 0x469426 in Stockfish::Position::set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, Stockfish::StateInfo*, Stockfish::Thread*) /home/gv/prog/workspace/Stockfish/src/position.cpp:279
>     #2 0x4a5a37 in Stockfish::ThreadPool::start_thinking(Stockfish::Position&, std::unique_ptr<std::deque<Stockfish::StateInfo, std::allocator<Stockfish::StateInfo> >, std::default_delete<std::deque<Stockfish::StateInfo, std::allocator<Stockfish::StateInfo> > > >&, Stockfish::Search::LimitsType const&, bool) /home/gv/prog/workspace/Stockfish/src/thread.cpp:208
>     #3 0x4bad5c in go /home/gv/prog/workspace/Stockfish/src/uci.cpp:150
>     #4 0x4bb2f6 in bench /home/gv/prog/workspace/Stockfish/src/uci.cpp:178
>     #5 0x4bc43a in Stockfish::UCI::loop(int, char**) /home/gv/prog/workspace/Stockfish/src/uci.cpp:276
>     #6 0x44c2d6 in main /home/gv/prog/workspace/Stockfish/src/main.cpp:49
>     #7 0x7f55e0e051e1 in __libc_start_main (/lib64/libc.so.6+0x281e1)> 
> 
> SUMMARY: AddressSanitizer: 2432 byte(s) leaked in 1 allocation(s).

No functional change.

### CODE REVIEW

**Comment by snicolet** [comment]
Is your code thread safe? What happens if two threads use the static sentinel at the same time?

**Comment by noobpwnftw** [comment]
There shouldn't be more than one UCI thread so it should be fine, however is there any other way to deal with it instead of a static global variable?

**Comment by snicolet** [comment]
I was thinking of one sentinel per Thread, but that may be over-engineering, dunno.

If we go for one static variable to be used only via the UCI thread, then we should add an assert to ensure that condition.

**Comment by gvreuls** [comment]
@snicolet I was thinking the same as @noobpwnftw . The only way to really find out is by running a multithreaded test.

@noobpwnftw The standard way is by using a smart pointer but you'd have to restructure StateInfo usage completely.

**Comment by BM123499** [comment]
we have `rootState` on thread, maybe we just add something like `extraState` on it as well?

**Comment by snicolet** [comment]
The leak was introduced in https://github.com/official-stockfish/Stockfish/commit/9f8058bd26df1c3ca37b85f811026f1eb82e6524

**Comment by snicolet** [comment]
> we have `rootState` on Thread, maybe we just add something like `extraState` on it as well?

In fact Position::set() is used from various places in the code, either directly of via the overload version in https://github.com/official-stockfish/Stockfish/blob/d53071eff4e75bc77dc86f65c52358d8014cb71c/src/position.cpp#L387

So sometimes in Position::set() the `th` pointer will be `nullptr`, so we can't rely on accessing a StateInfo sentinel stored in the current thread.

**Comment by BM123499** [comment]
> The leak was introduced in [9f8058b](https://github.com/official-stockfish/Stockfish/commit/9f8058bd26df1c3ca37b85f811026f1eb82e6524)

my bad... 😔

**Comment by snicolet** [comment]
It happens :-)

**Comment by joergoster** [comment]
> The leak was introduced in https://github.com/official-stockfish/Stockfish/commit/9f8058bd26df1c3ca37b85f811026f1eb82e6524

@snicolet Maybe reverting https://github.com/official-stockfish/Stockfish/commit/9f8058bd26df1c3ca37b85f811026f1eb82e6524 is the better fix then?

**Comment by vondele** [comment]
revert certainly could be considered.

**Comment by BM123499** [comment]
it seems it was a slight speed up on Vondele's machine: https://github.com/official-stockfish/Stockfish/pull/3325#issuecomment-770255740

**Comment by snicolet** [comment]
Why do we need to always recreate st->previous, in fact?

Wouldn't it be sufficient to write something like this?
```
   if (!st->previous)
      st->previous = new StateInfo();
```

**Comment by snicolet** [comment]
@gvreuls Could you check if this version still leaks?

```
 if (!st->previous)
      st->previous = new StateInfo();
```

**Comment by gvreuls** [comment]
@snicolet as long as we don't match every ``new`` with a ``delete`` there will be a leak/
I
 took @BM123499 's advice and put the ``StateInfo`` sentinel in ``Thread``. I put in an ``assert(th != nullptr)`` to ensure the en passant code is never entered without a valid thread pointer and this runs bench just fine.

**Comment by vondele** [comment]
BTW, it is unfortunate that this is not picked up by our CI, in principle valgrind lists the leaks already, it should just error out on it. I'll see if I can get a patch for it.

**Comment by BM123499** [comment]
> Why do we need to always recreate st->previous, in fact?
> 
> Wouldn't it be sufficient to write something like this?
> 
> ```
>    if (!st->previous)
>       st->previous = new StateInfo();
> ```

St is zeroed beforehand, so we always have to (re)link a existing StateInfo.

**Comment by vondele** [comment]
The following should fail on CI as long as this is not solved https://github.com/official-stockfish/Stockfish/pull/3525

**Comment by noobpwnftw** [comment]
Since it is only needed per `Position::set` on en-passants, can you do something like allocating two `StateInfo` at calling site and pass both to the `set()` function?
```
    StateListPtr states(new std::deque<StateInfo>(2));
    Position p;
    p.set(pos.fen(), Options["UCI_Chess960"], &states->back(), &states->front(), Threads.main());
```
Somewhere along this line?

**Comment by gvreuls** [comment]
@noobpwnftw How do i fix this without having to add a sentinelState to ``Thread``?

https://github.com/official-stockfish/Stockfish/blob/d53071eff4e75bc77dc86f65c52358d8014cb71c/src/thread.cpp#L208

**Comment by noobpwnftw** [comment]
By making this have 2 elements and pass along the lines?

https://github.com/official-stockfish/Stockfish/blob/d53071eff4e75bc77dc86f65c52358d8014cb71c/src/uci.cpp#L235

**Comment by gvreuls** [comment]
I've allocated all ``StateInfo`` objects at the call site where applicable, this makes for quite an intrusive patch.

@noobpwnftw I could create a new ``StateListPtr`` but I'd have to create one for every thread launched so it makes more sense to put the en passant sentinel in ``Thread`` just like ``rootState``.

**Comment by noobpwnftw** [comment]
I support your current version although it adds an extra `StateInfo` per thread. This is foolproof so that everyone calling `Position::set()` will see what it requires and no manual allocation is performed.

**Comment by gvreuls** [comment]
I'm quite unsure if what I did in ``Position::flip()`` is correct.

https://github.com/gvreuls/Stockfish/blob/c655b0f2c2aacff36bec09c420bb78905ce87581/src/position.cpp#L1276

Can someone look into this?

**Comment by BM123499** [comment]
Would it better to zero the sentinel as well?

> I'm quite unsure of what I did in `Position::flip()` is correct.
> 
> https://github.com/gvreuls/Stockfish/blob/c655b0f2c2aacff36bec09c420bb78905ce87581/src/position.cpp#L1276
> 
> Can someone look into this?

I believe it's correct, if it's `nullptr` then there is no enpassant, so it won't be used.

**Comment by snicolet** [comment]
This is getting quite complicated...

I am wondering if there could be a way to avoid relying on st->previous at all for checking legality of en-passant moves...

**Comment by snicolet** [comment]
In fact is is not even clear to me why https://github.com/official-stockfish/Stockfish/commit/9f8058bd26df1c3ca37b85f811026f1eb82e6524 was correct in the first place (maybe it is, but not obvious): in current master we have code like that:

```
   if (enpassant) {
      st->previous = new StateInfo();
      remove_piece(st->epSquare - pawn_push(sideToMove));
      st->previous->checkersBB = attackers_to(square<KING>(~sideToMove)) & pieces(sideToMove);
      st->previous->blockersForKing[WHITE] = slider_blockers(pieces(BLACK), square<KING>(WHITE), st->previous->pinners[BLACK]);
      st->previous->blockersForKing[BLACK] = slider_blockers(pieces(WHITE), square<KING>(BLACK), st->previous->pinners[WHITE]);
      put_piece(make_piece(~sideToMove, PAWN), st->epSquare - pawn_push(sideToMove));
  }
```

i.e. we (1) remove the captured pawn (2) calculate checkers and blockers for kings (3) put the captured pawn back.

But step (1) is not a complete undo of the pawn push, as undoing the pawn push should also put the pawn back in raw 2/7...

So I don't understand how the code in master works.

**Comment by BM123499** [comment]
Okay, this is a deep understanding of how it can be done.

I moved the complexity from the hot path (check legality and if gives check) to cold path (initialization).

Note that, if the double-pushed pawn was a blocker before the push, the move would be illegal, or en passant would cover the check afterwards.

We only need the following on a `st->previous` to do all the current work, we just need to know if the pawn in blocking a check, or if the pawn that is making an en passant was blocking a check before the double push. So, we don't have to initialize all values correctly, just the parts that are related to these.

In a perfect way, we would set the position before the double push and then do the double push. This lines try to simulate this behavior.

I tested reverting the move and then doing it again, but it failed non-regression. So I tried this simplified version and passed.

**Comment by snicolet** [comment]
So, that means that we should rename the array 
```
blockersForKing
``` 
should be renamed
```
blockersFoKingExceptIfTheNextMoveIsAnEnPassantCaptureAndTheNextPositionHasBeenSetViaFenWithAnEmptyPreviousState```

?

I don't think that we should go the way where fields in structures have no defined semantic, 99.9% correct depending on the code path, to be honest.

**Comment by BM123499** [comment]
Hey, can't we check if there is a `st->previous` before zeroing `st`, and, if yes, we delete it?

**Comment by BM123499** [comment]
@snicolet, I don't think so, it's a blocker for the King either way, I'm only creating a partial StateInfo that is just used twice (...?).
Other than the Initialization, it makes complete sense. It just requires the previous move to work properly.

**Comment by gvreuls** [comment]
@snicolet @vondele To be clear, I'm not vying for this patch to be accepted instead of a revert, I thought the fix was a lot less complicated than this patch turned out to be. I just want the leak fixed.

**Comment by snicolet** [comment]
Indeed, the original patch (Simplify En Passant, https://github.com/official-stockfish/Stockfish/pull/3523 ) was tested with simplification bounds, but now the code with the fix is much more invasive that the master code before the "simplification" patch.

**Comment by vondele** [comment]
@BM123499 can you prepare the revert of the patch as a PR? I think we should go back to the simpler form.

**Comment by gvreuls** [comment]
I've opened #3527 with the revert.

**Comment by snicolet** [comment]
Closing since 58307562b66597aeed9b5a7d76d2edeff53cf714 has been merged.

**Pull request closed without merging**
