### PR TITLE
Optimize the TT replacement policy implementation for speed.

### PR DESCRIPTION
**Pull request by mstembera**
No functional change.

gcc 4.9.2 
make profile-build ARCH=x86-64-modern COMP=mingw

```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1037545   1045727   -8182     
    StDev   304161    306417    3512      

p-value: 0.99
```
0.8% faster

Can someone please verify?

### CODE REVIEW

**Comment by mcostalba** [comment]
Patch is far uglier than original.

I really don't see any reason to uglify and obfuscate the code (that is
already difficult at that point) for nothing.

Even if result of speed test would be confirmed IMO it is wrong to pass the
concept that a hack can be committed just because it happens to very
slightly speed up the code, measured with a simple speed test: these are
too CPU / compiler dependent, especially when speed up is minimal as in
this (possible) case and give no guarantee that result is valid also in the
future, instead what is guaranteed is that the new code is worst and lower
quality than the original one.

So the bottom line is not only that this patch means no sense, but IMO we
should clearly state that lower quality code can be perhaps introduced only
if proved to be really stronger, and for this a fishtest session SPRT[0, 6]
is required, not a volatile speed test (but also in that case I have
doubts).

**Comment by lucasart** [comment]
@mcostalba: I agree with everything you said, except for the `SPRT(0,6)` part. A zero elo patch still has `5%` chance of passing that test. I think ugly patches should run for `SPRT(0,5)+SPRT(1,6)`. And I also think that most patches being tested in the framework are ugly. But I digress now...

**Comment by lucasart** [comment]
I can confirm a small speedup on bench:
* i7-3770k, gcc 4.9.2, linux 3.19
* 20 run (master and test concurrently and synchronized to reduce noise)
```
stat       test     master    diff
mean  2,611,912  2,603,248  11,239
stdev    16,141      9,925  11,535

speedup       0.43%
P(speedup>0) 100.0%
```

**Comment by mstembera** [comment]
Thanks for taking the time to comment and measure!

In general..
I am all for the prettiest and cleanest code possible in all cases when functionality and efficiency is the same.  IMO it starts to be a slippery slope when we sacrifice efficiency for the sake of less ugliness.  The biggest reason is that ugliness is a purely subjective opinion whereas efficiency is a measurable fact and we need to be able to judge all patches(not just this one) consistently and fairly.  Indeed Marco abuses the ugly criticism so much one starts to get the impression all code not written by him is ugly.  Anyway, if someone finds a piece of code ugly I would simply challenge them to write an equally efficient version they find less ugly.

To this patch specifically..
My esthetic bias aside, the original code is more compact.  4 of the 5 extra lines of the new patch are just { or } braces though.  There is exactly one more line of actual code.  The speed up comes from the fact that each entry is accessed exactly only once and it happens in a 0, 1, 2 order determined at compile time.  The original code accesses some entries multiple times through the replace pointer the order of which is unpredictable.  This is independent of any compiler instability.  I would not have bothered to rewrite it this way if it wasn't code on the hot path.

**Comment by mcostalba** [comment]
It is very fair to state that original code is better than the new proposed
one.

If you are not able to see this, that's your problem, not a lack of
objectivity (FYI, everybody see this, so at least accepts the comments of
people that knows better than you what is ugly code and what is not).

To maintainers: the problem I raised is even more confirmed after this last
post. The problem is the following: someone arrives with a patch that is
clearly lower quality but _happens_ to be _very slightly_ better on a pure
speed test. Than he says he does not see that his code is lower quality and
that people that says that are subjective and not objective, than he starts
a pseudo-argumentation regarding number of code lines and similar
non-sense, then he spends time and words to try to force his patch in, and
we spend time and words to keep his patch out.

This behavior IMO is very bad and should be avoided. How to do that?

In the past I proposed to test these pseudo-speed up patches in fishtest
with proper limits (they can go from SPRT[0,4] to SPRT[0,6] according to
patch invasivity and ugliness).

I think my idea is still valid and has the (big) benefit to avoid these
kind of annoying threads.

**Comment by lucasart** [comment]
@mcostalba: A zero elo patch still has `5%` chance to pass an `SPRT(0,X)` test, for any `X > 0`. This patch, which is most likely a 1 elo gain in our testing conditions, has a significant chance of passing either of those tests you propose.

Also, fishtest results are **unreliable** in this instance, because Windows machines do not use PGO compiles, while Linux machines do! And that's big problem when you want to measure this kind of thing.

SPRT is just a statistical tool. Statistics can say what they have to say, but eventually, maintainers have to make an **arbitrary** decision between: 1/ small gain for ugly code 2/ no gain no ugly code. 

Then come the philosophical questions:
* can uglyness be quantified ?
* how much elo gain is needed for how much uglyness ?

I'm glad I'm not a moderator anymore, and this is not my problem :-)

**Comment by mcostalba** [comment]
@lucasart your argumentation makes sense. If I were still a maintainer this would have been a no-brainer for me because I value code quality as a long term improvement, meaning that clean code is easier to improve upon and widens the potential developer base also to people with very low / almost zero C++ skills (and this is something we witness every day here in fishtest).

Talking of philosophy, to me SF has is today is an interesting experiment of Darwinian approach to chess engine development, where improvements are achieved through a series of almost random changes in an almost monkey style fashion. This works just because testing procedure is very strict and sound and is amazingly and reliably able to discard most of the changes and just allows in the "evolutionary" good steps. This is the approach that Nature has adopted and it seems to work very well out there (although it requires long times), so why not use it for engines?

We already use SPSA for tuning parameters, and here the approach is the same: "try and verify". Most of the patches running on fishtest are just a tad bit above the SPSA manipulation level, indeed if SPSA would be improved to change source code conditions in "if" statements and not only parameters values, we could have totally automated the process that today requires developer manual intervention.

.....sorry for the digression.

**Comment by mstembera** [comment]
@mcostalba:
Despite your accusation to the contrary, I'm not trying to force my patch in and I will not hold it against the maintainers in any way if they choose not to accept it.  You commented on my pull request, so I simply thought it appropriate to respond to you.

However much you may dislike it, speed tests verified on multiple machines are demonstrably more accurate for non functional patches than fishtest.

**Comment by zamar** [comment]
I don't understand this... I applied your patches on top of the current master and got a different bench:
Total time (ms) : 5546
Nodes searched  : 9699589
Nodes/second    : 1748934

Is it just me? 

gcc --version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mstembera** [comment]
@zamar 
I confirm after rebasing on latest master I also get a wrong bench of 9699589.  I'm investigating why and will report as soon as I have an answer.  (Sorry if it may not be till tomorrow because of my schedule today.)

**Comment by mstembera** [comment]
So the patch is in fact functionally different.  It is subtle so that when it was based on the master before the LMR tweak commit the benches were identical.  The root of the problem lies in how/when we test for tte[i].bound() == BOUND_EXACT.
Basically the original code compares the entries to each other in an inconsistent way.   They get valued differently depending whether they are accessed through tte[i] or through the replace pointer.  Even the same entry can get evaluated one way taking bound()==BOUND_EXACT into account then get assigned to the replace pointer and be evaluated another way w/o taking bound() into account in a subsequent iteration.  (The patch fails in matching this inconsistent behavior exactly.)  I think this is a bug because an entry should not become more or less valuable based on how it's accessed.  Forgetting this patch, I would like to fix the original code in this way
```c++
if (  ((  tte[i].genBound8 & 0xFC) == generation8 ||   tte[i].bound() == BOUND_EXACT)
    - ((replace->genBound8 & 0xFC) == generation8 || replace->bound() == BOUND_EXACT)
    - (tte[i].depth8 < replace->depth8) < 0)
```
Of course this can only happen if others acknowledge it's a bug and it will have to pass some test.  Please advise on how you would like me to proceed.

**Comment by zamar** [comment]
For me the change you have proposed would make perfect sense... So if it passes regression test, I'd be fine with committing it.

Of course this is somewhat subjective, so others might disagree...

**Comment by mstembera** [comment]
I have scheduled the regression test
http://tests.stockfishchess.org/tests/view/5593185c0ebc590abbe1b7fd

**Comment by mstembera** [comment]
The bug fix failed LTC
http://tests.stockfishchess.org/tests/view/559955480ebc590abbe1b8aa
As a result I think this patch is also dead as a pure speed up so I'm closing the pull request.

**Pull request closed without merging**
