### PR TITLE
Fix usage of B1 square after null moves.

### PR DESCRIPTION
**Pull request by Vizvezdenec**
Current master in multiple places uses to_sq(move) after null move which returns B1 square so randomly assigns stats bonuses or uses countermoves to moves that land at this square.
This patch fixes this behaviour - in place where it matters.
Some usage of previous square being B1 after null move remains but it's in 2 places - 
1) qsearch with prevSq going to movepicker - which doesn't matter since qsearch can be used after null move but it will always have depth 0 which is > DEPTH_QS_RECAPTURES and thus prevSq is actually never used;
2) in bonus penalty for previous moves after search - there it's also impossible to have this move being a null move since it needs to be either killer or have moveCount >= 1 both of which are impossible for null move.
Fixes issue https://github.com/official-stockfish/Stockfish/issues/4333
passed STC:
https://tests.stockfishchess.org/tests/view/6405e3162644b62c33937b9d
LLR: 2.94 (-2.94,2.94) <-1.75,0.25>
Total: 83872 W: 22255 L: 22090 D: 39527
Ptnml(0-2): 264, 9345, 22556, 9504, 267 
passed LTC:
https://tests.stockfishchess.org/tests/view/6406991e2644b62c33939de9
LLR: 2.94 (-2.94,2.94) <-1.75,0.25>
Total: 268024 W: 71762 L: 71792 D: 124470
Ptnml(0-2): 119, 26005, 81803, 25957, 128 
bench 4445793

### CODE REVIEW

**Comment by Vizvezdenec** [comment]
Side note - I have an idea to rewrite update_continuation_histories function to put is_ok inside it instead of having it in 3-4 different places in search, but will try this probably after this one will get merged/rejected :D

**Comment by mstembera** [comment]
Congrats and thanks for fixing it!  Eventually it would be nice if we could put an assert(m !=  MOVE_NULL) inside to_sq() and from_sq().

**Comment by Vizvezdenec** [comment]
> Congrats and thanks for fixing it! Eventually it would be nice if we could put an assert(m != MOVE_NULL) inside to_sq() and from_sq().

I'm planning on doing some modification so we will be able to do this - but at current stage it's impossible.
Will have to go for some extra brainstorm :)

**Comment by locutus2** [comment]
@Vizvezdenec 
As discussed yesterday in discord i think the cleanest way for this problem would to set prevSq correctly (meaning to SQ_NONE for MOVE_NONE and MOVE_NULL) and then guard some lines against SQ_NONE.

See here my fix based on this idea: https://github.com/locutus2/Stockfish/tree/fixPrevSq

**Comment by peregrineshahin** [comment]
> @Vizvezdenec As discussed yesterday in discord i think the cleanest way for this problem would to set prevSq correctly (meaning to SQ_NONE for MOVE_NONE and MOVE_NULL) and then guard some lines against SQ_NONE.
> 
> See here my fix based on this idea: https://github.com/locutus2/Stockfish/tree/fixPrevSq

I agree it is the cleanest, However it is functionally identical to what Viz tested with bench 4445793
So I think there is no need to retest that given this is not a functional change but a cleaner way to write things!

**Comment by peregrineshahin** [comment]
Oops sorry it seems that it differs in couple of nodes.

**Comment by Vizvezdenec** [comment]
> @Vizvezdenec As discussed yesterday in discord i think the cleanest way for this problem would to set prevSq correctly (meaning to SQ_NONE for MOVE_NONE and MOVE_NULL) and then guard some lines against SQ_NONE.
> 
> See here my fix based on this idea: https://github.com/locutus2/Stockfish/tree/fixPrevSq

It has more operations (I guess?) since it's more or less the same what fisherman did and it failed simplification bounds.
Feel free to try to pass it on top of current patch - I think one simplification SPRT should be enough.

**Comment by peregrineshahin** [comment]
> > @Vizvezdenec As discussed yesterday in discord i think the cleanest way for this problem would to set prevSq correctly (meaning to SQ_NONE for MOVE_NONE and MOVE_NULL) and then guard some lines against SQ_NONE.
> > See here my fix based on this idea: https://github.com/locutus2/Stockfish/tree/fixPrevSq
> 
> It has more operations (I guess?) since it's more or less the same what fisherman did and it failed simplification bounds. Feel free to try to pass it on top of current patch - I think one simplification SPRT should be enough.

I assume extra operation is not what mattered in comparison to what fisherman tried
As discussed on discord yesterday what fisherman tested guards agisnt null moves and no guard against move none for counterMoves thus functionally different and results with different bench

The extra operation part is actually optimized by compiler If I'm not wrong since the values declared are not used.

But what sg suggests is actually identical checks for both null move and move none for root node.

**Comment by mstembera** [comment]
There is a reasonable chance my version failed as a false negative because when I first tested it as an elo gainer it actually finished yellow after over 200K games.  https://tests.stockfishchess.org/tests/view/63b24a91e28ed36c814bdb98

**Comment by vondele** [comment]
waiting a bit with this one, I prefer https://tests.stockfishchess.org/tests/view/640fb39965775d3b539d2a78

**Comment by vondele** [comment]
closing in favor of https://github.com/official-stockfish/Stockfish/pull/4448

**Pull request closed without merging**
