### PR TITLE
Tweak queen values for midgame and endgame

### PR DESCRIPTION
**Pull request by Stefano80**
Queen MG -1% EG +1%. 

The tests for this patch are still running, I open the PR in case @snicolet wants to make a emergency merge.

The [STC](http://tests.stockfishchess.org/tests/view/5ab6b66b0ebc5902932cbd19) failed, the [LTC](http://tests.stockfishchess.org/tests/view/5ab73faa0ebc5902932cbdca) is looking good so far.

I am on leave today, so I open here to make this small improvement possible (if this turns to be one, of course).

### CODE REVIEW

**Comment by syzygy1** [comment]
Why was LTC started if STC failed?
Clearly this cannot be committed since LTC could just be luck.

**Comment by NKONSTANTAKIS** [comment]
STC is only used as a filter to save resources, and it is a poor one for TC dependent patches.
The testing methodology is generally useful but if used too strictly it becomes limiting.
Speculative LTC's in the past have often brought success despite always being discouraged.
On the other hand I agree that some flexibility around the rules is a good thing, but too much could be harmful, i.e. if everyone starts ignoring the rules.
However, I think that 75% LOS should always be committed for such patches which just change 2 numbers. Those numbers change all the time.

This patch also helps a little on a spotted strategical weakness of SF to overvalue the Q in some middlegames where it has lost quite a few Q for 3 minors.

@syzygy1 You would always be correct to bet 1 to 4 on a coin flip even if you lose by luck, so luck is not important here. With added code/complexity you would be right to be worried about luck.

**Comment by syzygy1** [comment]
We could all day randomly change some value and play a single game. If the game is won, the change has LOS > 50%, so should be committed. Right?

Your way of looking at it contains a basic flaw. The current values are the result of intensive tuning in the past. A single inconclusive test that, only when considered in isolation, suggests that another value might be better is simply inconclusive as it ignores the knowledge that the current value was found by that intensive tuning.

It would be different if this value had never been tuned before.

**Comment by syzygy1** [comment]
If it is really believed that this change works at LTC even if not at STC, then we could simply run another LTC. It should pass easily, if it indeed works.

**Comment by Stefano80** [comment]
Hi, there is also some discussion on the original commits (access from the tests page) where I have explained the idea behind this.

**Comment by NKONSTANTAKIS** [comment]
@syzygy1 Yes from a theoretical point of view even a 50.1% LOS would be helpful, however such an extreme approach holds 2 drawbacks: 
1. It introduces too much fluctuation, ie regression regression progress progress etc
2. From a practical point of view its not worth the effort, its like picking up 1 cent coin from the street.

For such simple patches I would say 60-65% is worth it for my taste, hence I consider an 75% suitable even for the conservative people. If we are not willing to do 3 steps forward 1 step backward we get stuck.

Everyone should realise that by approaching perfection the elo gets harder and harder to get, so you need to settle for small gains. That's also why I think that those bounds that we used for so long time should be softened. Contempt played a positive role on this area but its not enough.

For code adding patches I still think its good to be conservative because they can limit your long run freedom (promoting the getting stuck on a local high effect)

But tuning patches imo are a safe playground that could use some liberation, demanding 2/2 (0,4) passes on 2 different TC's is too harsh.

**Comment by NKONSTANTAKIS** [comment]
Also the current values, even if acquired through intensive tuning, lose status with every change in other areas, hence they require periodical retuning to sync up with master.

**Comment by vdbergh** [comment]
> Yes from a theoretical point of view even a 50.1% LOS would be helpful, however such an extreme approach holds 2 drawbacks:

You are interpreting LOS as a probability which is completely wrong.

In Bayesian statistics LOS is "likelihood of superiority" _with (in this case) a uniform prior_. This is a purely theoretical concept as the real prior is unknown and it is certainly not uniform.

The frequentist interpretation of LOS (in this case) is 1-p. A p-value of 49.9% means that the observations have 49.9 probability under the null hypothesis (no elo gain). This is extremely flimsy evidence for rejecting the null hypothesis.

**Comment by snicolet** [comment]
> This is extremely flimsy evidence for rejecting the null hypothesis.

Just curious: what do you mean by "extremely flimsy evidence for rejecting the null hypothesis"? Do you propose to accept the patch, or to reject the patch?

**Comment by vdbergh** [comment]
@snicolet The null hypothesis is that there is no elo gain. So rejecting the null hypothesis means accepting the patch. This should only be done when there is sufficient evidence that the null hypothesis is false. I.e. when we have observed an event which is highly unlikely if the null hypothesis were true. An event which can occur with 49.9% probability is **not** highly unlikely. So we do not consider it sufficient evidence for rejecting the null hypothesis.

**Comment by NKONSTANTAKIS** [comment]
@vdbergh The 50.1% was an extreme example that I used just to make a point. The proposition has ample room for mediating and targets the middle ground:
Between caring too much too make sure that a tuning patch is a clear gain and being too uncertain, ie there are the 4:1, 3:1 and 2:1 ratios which I consider nice and balanced:
4 steps forward 1 backward (80% in my imagination)
3 steps forward 1 backward (75%)
2 steps forward 1 backward (66%)

Therefore even if the individual regress probability is likely, the sum will definitely be progressing.

The 19 steps forward 1 backward (95%) is way too conservative.

**Comment by Vizvezdenec** [comment]
Looking at LTC with fixed amount of games I don't see any elo gain, and there is a quite possible elo regression there.
My guess is that LTC was just a lucky run and can not be commited as is. Maybe in combination with some other tuning patches...

**Comment by 31m059** [comment]
@snicolet I hesitate to get involved here, but as the maintainer, I hope you can clarify when speculative LTC is permissible and when it is not.  As far as I can tell, there doesn't appear to be any firm policy, and since we gained considerably more resources on fishtest, more and more people appear to be attempting these tests.  The reason some STC yellows are tested at LTC and others not is rarely clear.

**Comment by NKONSTANTAKIS** [comment]
0.5 +/- 1.5 means that the patch ranges from -1 to +2. By accepting 10 such patches the average elo gain will be +5. Maybe that's not good enough, but its also possible that the values are already too good to leave room for something better than that. Waiting and waiting to hit bullseye or get lucky works too I guess. The combination system though is a good alternative if someone does not want to risk a regression at all costs.

**Comment by Chess13234** [comment]
The idea that STC is a necessary step is wrong imho. 
It measures how Stockfish performs in blitz where many variables are optimized for depth/speed instead of eval quality. Consider any form of pruning:
imagine pruning method A that increases speed x2, but same engine given x2 time without A pruning will perform better than just engine with A pruning given(because it will not prune some critical moves that may win some games).

**Comment by vdbergh** [comment]
@NKONSTANTAKIS
> 4 steps forward 1 backward (80% in my imagination)
> 3 steps forward 1 backward (75%)
> 2 steps forward 1 backward (66%)

Once again this depends on interpreting LOS as a true empirical probability of superiority which is not correct.

In your line of thought accepting all patches with LOS >= 50% would be elo neutral (it would be if LOS were a probability) but in reality it would be disastrous as most patches are regressions due to the extremely highly tuned nature of SF. 

Assume (as an extreme example) that every patch is a small regression so that no patch should be accepted. Then still about 50% of the tests will end with a LOS of >= 50%. So the policy would actually lead to a linear decline in elo over time.

The issue is that the uniform prior which is implicitly assumed in the definition of LOS does not correspond to reality.

**Comment by noobpwnftw** [comment]
The assumption that a better shallow search leads to a better deeper search is generally correct.
What usually happens with STC passing but LTC failing or the reverse is that the progression/regression is too small to make a difference. And due to the nature of the possibilities the maintainers need to ensure that all merged patches are at more likely to be non-regressions.

My suggestion is you can try to bundle a group of patches to see if they can make their way to green.

**Comment by mcostalba** [comment]
The idea of STC is to optimize resources filtering out clearly bad stuff, not to validate a good patch. Patch validation is always and only at LTC.

Eventually test can be run again at LTC with SPRT[0, 4] to balance statistics.

**Comment by Stefano80** [comment]
So what you want me to do? Close, rerun LTC?

**Comment by mcostalba** [comment]
@Stefano80 it's up to @snicolet

**Comment by jerrydonaldwatson** [comment]
Maybe we should combine it with another positive tuning patch as @noobpwnftw suggested. Recent potential positive tuning patches are:
(Evaluation)
- Stephane's pawns in connectivity (66k yellow STC)
- Stephane's yellow LTC resonance patch
- One of Ivan's STC 60k yellow atan contempt patches
- Increase pure pawn ending term to 64 (75k yellow STC)

(Search)
- Stephane's yellow LTC reduce IID margin to 50

**Comment by mcostalba** [comment]
Functional patches should be tested indipendently: one idea per test.

This has always been a pillar of fishtest to avoid neutral garbage to be pulled in by good stuff: functional tests should walk on their legs alone.

This is clearly written in the wiki.

**Comment by jerrydonaldwatson** [comment]
@mcostalba 
Apologies for asking, I just wanted to clarify: I thought that parameter tweaks (and only parameter tweaks) could be combined in a combination patch?

**Comment by Stefano80** [comment]
I also thought so Marco. It is ok to combine tuning patches. What you say is perfectly right if you somehow change the logic, of course.

**Comment by mcostalba** [comment]
https://github.com/glinscott/fishtest/wiki/Creating-my-first-test#parameter-tweaks-tests

**Comment by NKONSTANTAKIS** [comment]
@mcostalba Since STC is only used to filter really bad stuff, wouldn't it make sense to be less demanding from it than LTC? As there are often patches which succeed STC and fail LTC, the reverse should also often happen but we can not see it unless we do speculative LTC. So we deprive the development from such patches.

My proposition is:
1. To keep a high (0,5) standard for code adding LTC because it can limit further options.
2. Lower STC resolution both for code adding and param tweaks to filter less patches but with less STC resources. This way a few more patches will be tested at LTC. High resources are also in line with this.
3. Lower the (0,4) parameter tweak LTC standard, because they are harmless, always interchangeable, and most importantly because due to SF being very well tuned, big improvements seldom exist.

I know that the SF recipe worked for many years and still bring progress but as SF now is several hundreds elo better than before and much closer to the theoretical elo ceiling, I am certain that adjustments should be made in order to be able to pick the small improvements. Again I am talking only about parameter tweaks, for simplification and adding code its good to be conservative.

I'm wondering if such static things like rules can be touched at all, is it open for debate and consensus like with default contempt?

**Comment by Vizvezdenec** [comment]
Okay, second LTC SPRT passed, so this patch is not a regression on LTC with 99,75% probability and can be commited it seems. Congrats then!

**Comment by mcostalba** [comment]
@NKONSTANTAKIS to make this kind of discussions useful we need some support data:

Up to this [regression test](http://tests.stockfishchess.org/tests/view/5aa8e2540ebc5902978101c8) we committed 18 functional patches (both [0, 5] or [0, 4]).

Test gives a +13 ELO vs SF 9, it means less then 1 ELO improvement for patch on average. So I would say we already apply very low ELO patches, maybe even neutral patches that successfully passed the test (false positives).

To make a discussion serious and not just a random talk, a quantitative approach should be taken: what is the ratio of false positives with current tests? What is the ratio of accepted 1 ELO patches? And of 2 ELO patches?

I will not do the homework of finding the data (that exists already btw), but I warmly invite people that suggest to change SPRT parameters to present quantitative tabular data with _before_ the change and _after_ the change, or, in case people lacks skills to calculate _after_ parameter, just what should be the different accept/reject probabilities for different known ELO values of the patches.

Without this I have some difficult to seriously consider these kind of argumentation.

**Comment by Hanamuke** [comment]
Someone needs to edit the PR message to include the bench number.

**Comment by snicolet** [comment]
The patch has failed STC, but passed LTC twice with [0..4] bounds, so I will commit it.
Approved!

**Comment by snicolet** [comment]
Merged via 5ce630584ca243ad0f4739bb7615702f36b9f818

**Comment by snicolet** [comment]
@Stefano80 
Oops, just realize that I forgot to change the --author flag of the merged commit, so that you would appear as the author. Sorry about that!

**Comment by Stefano80** [comment]
No need to be sorry as no harm has been done.

Keep up the good work Stephane, you are giving so much to this project.

**Pull request closed without merging**
