### PR TITLE
Passed pawns

### PR DESCRIPTION
**Pull request by locutus2**
Add file based bonus for passed pawns. Values tuned by SPSA.

STC:
LLR: 3.33 (-2.94,2.94) [0.00,5.00]
Total: 36889 W: 6805 L: 6507 D: 23577

LTC:
LLR: 2.97 (-2.94,2.94) [0.00,5.00]
Total: 32301 W: 5101 L: 4858 D: 22342

bench: 8690843

### CODE REVIEW

**Comment by Rocky640** [comment]
Congrats !

**Comment by locutus2** [comment]
@VoyagerOne, lantonov
I used negative and positive values because i don't want raise the average passed pawn eval only differ between the files.
500 games are not much (i know because this gives for me many false positives) but go on and test against my parameters. We can only gain elo!

**Comment by lantonov** [comment]
@Stefan,
Further tuning may show better. Anyway, this is an elo gainer for sure.

**Comment by snicolet** [comment]
Congrats :-)

**Comment by glinscott** [comment]
Congratulations, looks great!

**Comment by zamar** [comment]
approved.

**Pull request closed without merging**
