### PR TITLE
King safety tuning with CLOP

### PR DESCRIPTION
**Pull request by joergoster**
Tuning session on checks and attack units.

Passed LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 27199 W: 3859 L: 3636 D: 19704

bench: 7980886

### CODE REVIEW

**Comment by Rocky640** [comment]
Well done Jörg !

As captain Obvious would say, the winner of the game is the last one who say "check !",
and a QueenContactCheck with a King on the side is certainly a big threat.

Some of these CLOP values are quite interesting, and I'm very happy about this experiment.
You have been trying all kind of tuning strategies in the last few years, and this is great !
Well tuned parameters will make many other obsolete, and this is wonderful.

However the test was red at STC 
http://tests.stockfishchess.org/tests/view/57481ba60ebc59301a355135
and if we accept this, we are opening a can of worms, 
and/or will have to find a way to put a safe cover on the can for the future !
(this means new test guidelines)

I see a can of worms because:

a) we all want to improve LTC, but how can we submit new STC tests 
relating to King Safety anymore, knowing that the current state is not "STC compatible" ?

b) Will people start to retest every red STC relating to passed pawns, or King safety, or pawn structure at LTC ? (and I'm not mentioning other tests relating to search ?)

**One easy solution could be the following**

Maybe your STC run was "unlucky".
If we run the STC again, say 40000 games, and find out that it is not too bad,
this would make things more clear.

So this was my 5 cent.

**Comment by joergoster** [comment]
@Rocky640 I just did a comparison of the 2 successful runs, STC and LTC. Both have in common the significantly increased values for Bishop and Knight checks, and the decreased factor for undefended squares.
How about trying to find the best out of both passed runs, see https://github.com/joergoster/Stockfish/commit/bf0e4a092cce2506f58a050ed8cf8d9ff6a876cb
What do you think?

**Comment by Rocky640** [comment]
Those values are more familiar, it could be an interesting experiment if it is some kind of average of 2 successful tests.

**Comment by jcalovski** [comment]
Well done! Although in general I am skeptical of these targeted tuning patches where we tune for LTC and kind of bypass the scaling side of the patch. I mean how does this perform at 90+0.9 for instance?

**Comment by mcostalba** [comment]
Indeed this is an interesting case.

Personally I have no problem to commit a king safety patch that just passed
LTC because (1) I know king safety is TC dependent (2) STC is a kind of
pre-filter introduced for efficiency before the _real_ test that is LTC.

Nevertheless I am a bit worried about people that would start to skip STC
and go directly to LTC when they _think_ patch is TC dependent. This can be
very dangerous and very difficult to block. Of course maintainers can
overrule and decide which patches are valid just with a successful LTC and
which should go the usual way, but this would be very difficult to manage
in practice and would expose the maintainers to criticism (more than what
they already are).

I am for committing this in, but I will keep the PR open for some more days
to let people to comment. I also would love to have Joona's comment on this.

**Comment by locutus2** [comment]
@joergoster 
Congrats!

@mcostalba 
I' am also a bit worried that this speculative LTC tests get out of control. Here all developers are responsible to use this way in a wise manner.
Perhaps it is even time to raise the STC to 20+0.2. Additionally LTC could be raised to 80+0.8 to get a tc ratio of four. But i think a ratio of three would also enough.

So i' am absolutely for committing

**Comment by pb00068** [comment]
My 2 cents on this: 
If there are good reasons to believe a patch performs well on LTC, then IMO it should be allowed to test it at LTC but with fixed games (not SPRT) and low throughput, in order to prove that is has some potential. Only if that performs good one should be allowed to proceed to SPRT. In this way we may filter out 0-Elo-patches earlier and thus avoid long running useless LTC-SPRT tests.

**Comment by ofry** [comment]
Maybe do STC more larger? For example, STC 20+0.2, LTC 120+1.2?

**Comment by sf-x** [comment]
A compromise would be,for TC sensitive (king safety,etc.) changes only, to make STC longer.

**Comment by burak13** [comment]
I think there is no reason to complicate things. If a test fails at standard STC and developer believes the patch should scale better in LTC, then something like sprt 40+0.4 could be tried, and then finally LTC test. Therefore, if the patch is successful, it still hast to pass 2 tests separately without risking lucky runs.

**Comment by pb00068** [comment]
@sf-x You're right, I better had chosen 'annoying' instead of 'useless': SPRT-tests on Zero-Elo-patches aren't useless (in the end only the SPRT itself will demask them as such): knowing that a certain approach doesn't work is for sure a valuable information too. But I hope you agree that multiple unsuccessful LTC-Tests may slow down the whole framework and thus harm the entire SF-development, time is ELO.

**Comment by zamar** [comment]
King safety is known to be highly sensitive to time control and I understand that new values were obtained using automated parameter tuning.

I think that in this specific case, an exception should be made, and this patch should be committed.

**Comment by joergoster** [comment]
@zamar Indeed, those values were obtained by CLOP, tuning against a pool of opponents.

Would you say this http://tests.stockfishchess.org/tests/view/574cfd510ebc59029919b0ce test, where I try to find some values that may pass both time controls, is obsolete?

**Comment by mstembera** [comment]
Another plus this patch has going for it is that it adds zero complexity being a tuning patch.

**Comment by Rocky640** [comment]
I like sf-x and burak proposals.
The 2 pass system is not only to pre qualify for LTC, but also reduce the risk of lucky runs.
The confidence level calculations were done based on 2 pass.

In this case:
a) maybe the STC was unlucky
b) may the LTC was lucky
c) we do not know !!!

CLOP has some strength that SPSA does not have, (it will not get stuck in local optimums)
but is also known to produce some freaky results.

Frankly, here we have some queen and rook values which are double of what they were before.
It is hard to believe that those already big values were completely off.
This is possibly outscaling our finely tuned KingDanger array.

I would rather wait to see if joerg newest experiment works
http://tests.stockfishchess.org/tests/view/574cfd510ebc59029919b0ce 

And if not, then let's commit. 
At least now, the fish spsa seems to work fine again, so we 
can tune this whole king safety thing which is overdue for a big long tuning, 
considering the many adjustments made to king safety in the last months.

**Comment by mcostalba** [comment]
@joergoster can you please squash all the commits in a single one and rebase above current master? Thanks.

**Comment by lucasart** [comment]
@mcostalba @joergoster: Can we wait for this one to run at LTC ?
http://tests.stockfishchess.org/tests/view/574cfd510ebc59029919b0ce
I am ready to bet it will also pass LTC, proving that LTC gains on king safety don't have to be STC regressions...

**Comment by IIvec** [comment]
I vote for this patch because of good scalability. Maybe to retest at 150+1.5?

**Comment by joergoster** [comment]
I'm really happy the so-called 'middle ground patch' did pass both time controls! Thanks to all for your support and patience.
I'm closing this pull request.

**Pull request closed without merging**
