### PR TITLE
[cluster] Extra output & documentation

### PR DESCRIPTION
**Pull request by vondele**
These two commits add documentation and an additional line of output giving KPIs for the cluster performance.

No functional change.

### CODE REVIEW

**Comment by noobpwnftw** [comment]
Might also add that run-time configurations are for each MPI process, so that the total amount of "Threads" and "Hash" needs to be aggregated.

**Comment by vondele** [comment]
@noobpwnftw thanks ... comments welcome of course. 
 
You would at that https://github.com/official-stockfish/Stockfish/blob/8da50d5e341c9308da32b2a5863bb6cc835f966f/src/cluster.h#L33 or https://github.com/official-stockfish/Stockfish/blob/8da50d5e341c9308da32b2a5863bb6cc835f966f/src/uci.cpp#L192

**Comment by noobpwnftw** [comment]
I think in `cluster.h`.
”In cluster mode, values of Threads and Hash are for each node. This applies to both input and output of various UCI options, e.g. Threads, Hash."

**Comment by vondele** [comment]
Done.. not sure what you mean with 'applies to input and ouput' ? The output bit refers to what exactly.

I'll also provide an update to the readme, since some of this info needs to be user-facing.

**Comment by vondele** [comment]
Ah, yes, I think that is now sufficiently clear.

**Comment by snicolet** [comment]
Merged via 10a920d7d752ba9ca155eb324b7904e95766fc7c, thanks!

**Pull request closed without merging**
