### PR TITLE
Pawn flank attacks

### PR DESCRIPTION
**Pull request by snicolet**
This patch tweaks some pawn values to favor flank attacks. 

The first part of the patch increases the midgame psqt values of external pawns to launch more attacks (credits to user GuardianRM for this idea), while the second part increases the endgame connexion values for pawns on upper ranks.

Passed STC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 34997 W: 6328 L: 6055 D: 22614

and LTC:
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 13844 W: 1832 L: 1650 D: 10362

Bench: 5884767

### CODE REVIEW

**Comment by ajithcj** [comment]
Congrats!

**Comment by DamasClasicas** [comment]
Amazing STRONG patch!!! Congratulations!

**Comment by Rocky640** [comment]
Congrats ! The wizard strikes again !

For the follow-up, I'm a bit skeptical about the change in psqt.cpp.
Have you tried the change in pawns.cpp alone in one of your previous tests ?

**Comment by snicolet** [comment]
@Rocky640: thanks :)

The changes in pawns.cpp alone got a yellow: http://tests.stockfishchess.org/tests/view/58406bd90ebc5903140c558f

**Comment by locutus2** [comment]
Congrats! A strong and well scaling patch!

**Comment by Rocky640** [comment]
Ah, thanks, I missed that test.
So this was an excellent combo of two more or less independent yellow.

One which was changing mg values
http://tests.stockfishchess.org/tests/view/58406bd90ebc5903140c558f
One which was changing eg values
http://tests.stockfishchess.org/tests/view/583ed6c40ebc5903140c54eb

It might be a good strategy to always check for any combo possibility of such mg + eg strong yellows. Maybe we should check older yellows too...

Congrats again !

**Comment by VoyagerOne** [comment]
Nicely Done.

**Pull request merged**
