### PR TITLE
Check score bonus

### PR DESCRIPTION
**Pull request by jcalovski**
Score bonus for checks. 

Second attempt of a patch by Joona Kiiski.

STC:
LLR: 2.97 (-2.94,2.94) [0.00,5.00]
Total: 14531 W: 2765 L: 2576 D: 9190

LTC:
LLR: 3.20 (-2.94,2.94) [0.00,5.00]
Total: 52518 W: 8107 L: 7782 D: 36629

bench: 7556477

Resolves #435

### CODE REVIEW

**Comment by Nakel** [comment]
Congratulations, this is a wonderful patch.

**Comment by mcostalba** [comment]
Congrats for the patch!

Please reformat your patch according to SF coding style, don't force someone else to do this for you. Thanks.

**Comment by jcalovski** [comment]
Thank you all, I am getting some weird formatting from my end. Please let me know if it is still off as I have tried to correct it.

**Comment by locutus2** [comment]
@jcalovski:
the score bonus is not correct formatted. Use only spaces and no tabs for indentation.

**Comment by jcalovski** [comment]
OK... I hope that's looking better now!

**Comment by joergoster** [comment]
Congrats!

**Comment by glinscott** [comment]
Nice!  Looks good :)

**Comment by zamar** [comment]
approved.

**Pull request closed without merging**
