### PR TITLE
reduce scope of variables

### PR DESCRIPTION
**Pull request by vondele**
small cleanup TranspositionTable:clear().

No functional change.

### CODE REVIEW

**Comment by joergoster** [comment]
How about this one?
```
void TranspositionTable::clear() {

  const size_t requested = (size_t)Options["Threads"];
  const size_t stride = clusterCount / requested;
  std::vector<std::thread> threads;

  for (size_t idx = 0; idx < requested; idx++)
  {
      const size_t start = stride * idx,
                     len = idx != requested - 1 ? stride
                                                : clusterCount - start;

      threads.push_back(std::thread([this, idx, requested, start, len]() {
          if (requested >= 8)
              WinProcGroup::bindThisThread(idx);
          std::memset(&table[start], 0, len * sizeof(Cluster));
      }));
  }

  for (std::thread& th: threads)
      th.join();
}
```
Not as compact as yours, but also very clean, imho.
At least, it seems to make sense to only lookup 'Options["Threads"]' into 'requested' once at the beginning of the function.

**Comment by vondele** [comment]
This is somewhat orthogonal, but I also considered replacing ```Options["Threads"]``` by a local variable. However,  as this required adding one more variable to the lambda, I decided not to do it. It is a matter of taste, I'd say.

**Comment by snicolet** [comment]
I am not sure that this makes the code easier to understand :-/

**Comment by Hanamuke** [comment]
Does this patch produce a different binary ?

**Comment by vondele** [comment]
@Hanamuke yes, but the code is equivalent of course.

@snicolet it just limits the scope of variables.. I've changed/added a bit the comments to make clear why it does what. The code is not particularly complex, IMO.

**Comment by snicolet** [comment]
Merged via 8c4f0ffa1d1cc6952874ee30fff9f826646b1aeb, thanks!

**Pull request closed without merging**
