### PR TITLE
Scale time reduction by depth differential

### PR DESCRIPTION
**Pull request by protonspring**
This is functional simplification.  If we simply scale the time reduction according to the depth difference between completedepth and lastBestMoveDepth, the equation is more simple (removes the 10 constant, the comparison, and the conditional).

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 17802 W: 3940 L: 3811 D: 10051 
http://tests.stockfishchess.org/tests/view/5c58cdca0ebc592015e0efc1

LTC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 22858 W: 3832 L: 3715 D: 15311 
http://tests.stockfishchess.org/tests/view/5c5904cc0ebc592015e0f1d2

Bench 3653942

### CODE REVIEW

**Comment by snicolet** [comment]
@vondele, @mcostalba 
Opinions about this patch? Should we test at more time controls?

**Comment by xoto10** [comment]
I'm comfortable with it as is. Removes a conditional, gives a graded result instead of all-or-nothing, and test results appear positive, not just roughly equal. 
I think the timeman.cpp code needs care when updating but this code is not such a worry.

**Comment by Stefano80** [comment]
Maybe a [-4,0] with sudden death?

**Comment by vondele** [comment]
I like the idea that the reduction is now more gradual, this is presumably the reason for the somewhat better performance. 

I'm slightly concerned that the time reduction can become 'unbounded'. For example, at depth 60, timeReduction can be 4.0 (which is not bad per se, since the move is very stable), but it also means on the next iteration we'll be giving std::pow(mainThread->previousTimeReduction, 0.528) (i.e. > 2 ) more time, so over the two moves combined, we actually lose time, which likely isn't good.

I think it would be good to use timeReduction = std::min(2.0, ...), or even something like std::min(1.5, ...). Most of this would not matter at STC/LTC as we're unlikely to reach the critical depths.

**Comment by mcostalba** [comment]
It seems a tweak to me, I'd give a try at sprt[0, 4] and also test on suddeng death (a time control tweak requires tests on broader conditions than teh standard ones).

**Comment by vondele** [comment]
I've started a couple of [0, 4] tests, with the std::min in place.
http://tests.stockfishchess.org/tests/view/5c7012330ebc5925cffceb4a
http://tests.stockfishchess.org/tests/view/5c7012460ebc5925cffceb4d
http://tests.stockfishchess.org/tests/view/5c70125d0ebc5925cffceb4f

**Comment by vondele** [comment]
all 3 [0, 4] tests failed.

**Comment by vondele** [comment]
Since the [0, 4] tests failed, I would rather close this one.

**Pull request closed without merging**
