### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by mcostalba**
Merge files in a big single one: the most practical solution for active working on them

### CODE REVIEW

**Comment by mcostalba** [comment]
@lucasart The first commit of the series get rid of '#include tbcore.cpp', the other 2 commit go ahead and merge them in a single file with some small cleanup at the end. This is just the beginning, now it is much easier to proceed from the top to the bottom, cleaning up in a consistent and efficient way: there is a a lot to do!

**Comment by lucasart** [comment]
@mcostalba: approved.

**Comment by lucasart** [comment]
@mcostalba: can you commit this patch on top ? https://github.com/lucasart/Stockfish/commit/81f821d5fe84a8eb843e63f81e5539f369ca0107

**Comment by mcostalba** [comment]
@lucasart done.

**Pull request merged**
