### PR TITLE
update links in license

### PR DESCRIPTION
**Pull request by robertnurnberg**
Update `Copying.txt` with a recent version of the license file. Only changes are the links.

No functional change.

### CODE REVIEW

**Comment by ddobbelaere** [comment]
Maybe it's a good idea to stick to the line ending to CRLF (instead of LF in the PR).
The diff is gigantic because of this. It's not completely clear that only the links have changed.

**Comment by vondele** [comment]
add `?w=1` to the URL
https://github.com/official-stockfish/Stockfish/pull/4813/files?w=1

Having said that, we should probably use the preferred line endings, whatever that might be.

**Comment by robertnurnberg** [comment]
Github highlights the changed strings in the diff. 

I must say I nicked a copy of `LICENSE` from https://github.com/vondele/cdbexplore, so line ending encodings are from there. It might be the default license file that github provides for new repos?

PS: Renaming `Copying.txt` to `LICENSE` is also an option.

**Comment by vondele** [comment]
Copying.txt is the FSF preferred name, I vaguely recall.

**Comment by UniQP** [comment]
The `Copying.txt` of the PR matches https://www.gnu.org/licenses/gpl-3.0.txt, including line endings.

**Comment by robertnurnberg** [comment]
https://www.fsf.org/bulletin/2022/spring/verifying-free-software-the-basics

> A copy of the license is also a file typically found in the main directory of the source code, but it may be stored in a sub-directory like doc/ or LICENSES/. The title of the file may vary. Look for a name like COPYING or LICENSE, or it might be the name of the license itself like GPL or APACHE.

According to that we should change the name to `COPYING` or `LICENSE`?

**Comment by vondele** [comment]
hm, anyway, I'd just keep the name, there are things that depend on this already (like CI etc). I think the PR is good as is.

**Review by vondele — APPROVED** [review]

**Pull request closed without merging**
