### PR TITLE
x86 TT hash --- suboptimal 0x66 instruction prefix generated

### PR DESCRIPTION
**Pull request by sqrmax**
Some compilers, like gcc (Gentoo 9.2.0-r2 p3) 9.2.0, emit code like this in TT::probe():

test dx, dx
je ...
cmp bx, dx
je ...

Similar behavior was observed with gcc 10.1 and gcc trunk at godbolt.org.

This is suboptimal because the instructions contain 0x66 LCP prefixes.  Said prefixes should be avoided as per the Intel optimization manual (in this particular case, because shorter instructions are better).  For some reason, gcc refuses to perform the operations in 32 bit arithmetic.  With these changes, the following code is emitted instead.

test edx, edx
je ...
cmp ebx, edx
je ...

Note that this code now also benefits from avoiding REX prefixes (by not typecasting the operations to 64 bits), which is better as per the Intel optimization manual (shorter instructions are better).

Thanks go to skiminki for helpful assistance.

### CODE REVIEW

**Comment by vondele** [comment]
@sqrmax thanks for the PR. However that will need some more testing to see if the added code brings a significant speedup. There are some suggestions for testing here: 
https://github.com/glinscott/fishtest/wiki/Creating-my-first-test#speed-optimization
Maybe you can report an observed speedup  based on perf.

**Comment by Chess13234** [comment]
<stdint.h> has uint_fast16_t which is cross-platform.

**Comment by sqrmax** [comment]
> <stdint.h> has uint_fast16_t which is cross-platform.

That's the first thing I tried.  But looking at the disassembly, you get unnecessarily big instructions again because the arithmetic is promoted all the way to 64 bits.

**Comment by sqrmax** [comment]
> @sqrmax thanks for the PR. However that will need some more testing to see if the added code brings a significant speedup. There are some suggestions for testing here:
> https://github.com/glinscott/fishtest/wiki/Creating-my-first-test#speed-optimization
> Maybe you can report an observed speedup based on perf.

Thanks for the info vondele.  I do not have a linux box to do that test properly right now, and the Apple box I have has a clang compiler that is already a bit smarter about instruction selection.  So, on this box, the changes make no difference.

I did the work in collaboration with someone else who did have access to a linux box.  From the measurements taken, we could not see a performance win.  I can check this out some more later and report back then (and also try with gcc 10.x).

**Comment by protonspring** [comment]
I'd be careful about using types like uint_fast16_t.  SF is pretty dependent on type sizes and I'm not sure uint_fast16_t is the same size on every machine.  I may be wrong.

**Comment by vondele** [comment]
so, as there is no observable speedup, I'll close this. Feel free to reopen if there is a significant speedup possible. Since hash probing is quite performance critical, that's well possible.

**Comment by sqrmax** [comment]
> so, as there is no observable speedup, I'll close this. Feel free to reopen if there is a significant speedup possible. Since hash probing is quite performance critical, that's well possible.

@Vondele: I submitted a ticket with GCC, and so far it has been triaged as "missed optimization".  Addressing this issue that way is a more comprehensive fix.  I'll keep track of the GCC bug, maybe soon we won't need to change the code here at all.

**Pull request closed without merging**
