### PR TITLE
Bind each thread to its own CPU on Linux

### PR DESCRIPTION
**Pull request by vegard**
Binding each thread to a specific CPU can prevent threads from bouncing
around from one CPU to another. This is especially damaging on NUMA
computers with many CPUs, as each jump to another CPU may essentially
cause cache thrashing.

### CODE REVIEW

**Comment by oherbst** [comment]
Hi vegards

is this patch (for binding threads to their own CPU) already available for Stockfish code for Windows?
I assume the patched sources cannot just applied to the windows-build, or is it only the different line-endings?

Best Regards

**Comment by vegard** [comment]
Yes, Windows already has the code to do this and it's using a completely different mechanism/OS interface.

**Comment by vegard** [comment]
My performance evaluation is here: https://github.com/official-stockfish/Stockfish/pull/893#issuecomment-263052961

**Comment by mcostalba** [comment]
@vegard I am pondering a lot on your patch:

Pro
- Improve a special case NUMA under Linux
- Patch is minimal and not invasive

Cons
- Improvement is marginal and special case is really special, very few users would be affected, even less would notice any difference (you need hundreds of games to spot an ELO advantage with just a +3% speed-up)
- Introduce another chunk of platform specific code that is almost impossible to verify/test for most users (maintainers included)
- Patch is really ad-hoc and covers a specific case: you bound the thread to the CPU at the time of thread creation, and never change it again. This is very inflexible and IMO is a bit fragile because at thread's startup the OS could pick a sub-optimal choice, then, when running it could migrate the thread to a better affinity, based on the dynamic OS sched policy: I would not forbid this possibility.

Summarizing, your patch does not guarantee  to allocate the thread to the best CPU, but it just disables threads migration: IMO this is quite hacky and could be sub-optimal under many scenarios. Moreover the advantage is really minimal, more so considering the specificity of the patch and difficulty to test/maintain.

I am for closing this, I will let it open for a while eventually for author's reply.

**Comment by oherbst** [comment]
Hi, meanwhile I could build it with the patched misc.cpp under Windows (using mingw compiler).
It works fine as such. However, what I would need to have, would be a "NodeAffinity", where I could
define which 2 nodes share per-node-memory.

I have a CPU with 4 Core-Modules running 2 Nodes (Threads) per each core module.
So I want to be able to set node-affinity such that:
  
node 1 shares per-node memory with node 0
node 3 shares per-node memory with node 2

Meaning pair-wise node-memory sharing:
 nodes 0 and 1 share node memory
 nodes 2 and 3 share node memory 
 nodes 4 and 5 share node memory
 nodes 6 and 7 share node memory

I had that feature with a special edition of "asmFish", supporting this kind of NodeAffinity.
Unfortunately, the repository got deleted.

Could you give me an idea how to accomplish the same thing in the CPP code?
Any hints are welcome.

Kind Regards

PS:
On my hardware I observed about 15-20% performance gain with NodeAffinity (as described above) in asmFish (in comparison to asmFish with no node-affinity).

**Comment by CoffeeOne** [comment]
I checked this patch on my system: Opteron 64 Core, 8 Nodes:
Ubuntu 16.04.1 LTS, native gcc. I use latest master, and changed misc.cpp for the patched version.
5 Runs of bench 2048 64 24 for each version:
Master: 59,9/61,7/61,6/63,9/62,9
Patched: 63,9/64,7/65,2/65,3/63,5
=> 4% speedup

**Comment by syzygy1** [comment]
I haven't tried to see if bindToThread() is called in all circumstances, but I'd like to note that binding SF search threads to CPUs or cores will have bad effects when testing many single-threaded instances at the same time, for example on fishtest. So it should be configurable (at least between binding / not binding).

**Comment by vegard** [comment]
Fine, do what you like. I won't spend any more effort on this.

**Pull request closed without merging**
