### PR TITLE
Bench: 5903207

### PR DESCRIPTION
**Pull request by VoyagerOne**
QS Pruning Tweeks:

Yellow Combo:
http://tests.stockfishchess.org/tests/view/591daaa80ebc59035df3483e
http://tests.stockfishchess.org/tests/view/5913ae940ebc59035df34503

STC:
LLR: -2.96 (-2.94,2.94) [0.00,5.00]
Total: 80562 W: 14816 L: 14596 D: 51150

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 11928 W: 1613 L: 1457 D: 8858

Bench: 5903207

### CODE REVIEW

**Comment by VoyagerOne** [comment]
Note-  My intuition thought this patch will do well at LTC, since the changed logic will get hit more often earlier in the game since SF will be searching deeper.

**Comment by MichaelB7** [comment]
Excellent !! 👍👍

**Comment by Rocky640** [comment]
@VoyagerOne 
This is a great result !
But can you provide links to the 2 original tests that went into this combo ?
Would it make sense to test them separately at LTC ?

**Comment by VoyagerOne** [comment]
@Rocky640 
updated description

**Comment by zamar** [comment]
@VoyagerOne: You've taken too much freedom in your testing methodology.

1) Patch A fails
2) Patch B fails
3) Patch A+B fails
4) Patch A+B passes

At this point the chance of a lucky run is just a way too high.

Please stick with the testing guidelines as everybody else does.

Patch rejected.

**Comment by jhellis3** [comment]
More like:
1. Wins more than it loses
2. Wins more than it loses
3. Wins more than it loses
4. Passes LTC 0-5

If you want extra assurances of a non-lucky run... just repeat the LTC 0-5 test.

Needlessly bming the most prolific and productive contributor to the project over the last 2 years is probably not the best idea in the world, but wtf do I know....

**Comment by Vizvezdenec** [comment]
I have to agree, maybe this patch is just really good at LTC for some reason, smth like truncated to 20000 games [0,5] sprt wouldn't hurt anyone, framework is not extremely busy at moment.

**Comment by IIvec** [comment]
This is a clear message: No more speculative LTC.

**Comment by AlexandreMasta** [comment]
Rules are very important. But we have to understand that we are not automatos...we are not robots. We have commom sense and inteligence in a way that still cannot be reproduced by machines and this is what makes us humans. I really think that if we have a very good reason to test the patch at LTC we should do it. That was the case. V1 didnt do the test without an understanding of what he was doing, he had a motif, and he explained why. This is not passing by the rules but being smart to see where and when it is applied on the concrete case.

It is a pity a uncontested elo gain patch be rejected just because it is not following estrictely the general rules.

**Comment by Rocky640** [comment]
@zamar 
Would it make sense to test them separately at LTC ?

**Comment by Stefano80** [comment]
We are not talking about arbitraty rules but about the fact that not
fpllowing them undermines the assumptions of SPRT
Il 28/mag/2017 16:05, "AlexandreMasta" <notifications@github.com> ha
scritto:

**Comment by AlexandreMasta** [comment]
It is not a question about arbitrary rules. It is a questions about why the rules exist. The whole obective of the rules is to control the enviroment and promote order and consistency for the project and engine evolution/improvement. This is why it should exist.
You are giving more importance to the rule than its goal. In this concrete case it is detrimental to the improvement of the engine. That's why every rule should have its exception. In this case like in some others, following blindly the rule leads to stagnation of the improvement process. 
The right way should be a discussion among all mantainers and maybe another way to address this patch so you should have assurance about the elo gain that the patch provides. 
Looks very nonsensical to me just discard a clearly/uncontested elo gainer patch.
At least, this episode shows that you must have some flexibility about the rules. Otherwise, how many more good patches will be lost or even the possibility of good patches that improves the engine at LTC and will only be detected at this Time control will never happen? 
Food for thought.

**Comment by AlexandreMasta** [comment]
@zamar and others ...Put your egos aside and think carefully about the objectives of the rules. In any scenario of human life...rules are for good of the society...when a rule is detrimental to this goal you always make an exception.

**Comment by theo77186** [comment]
I think rules are important and some participants already made a point on it. This patch testing is perhaps pushing to the edge of the rules but we should take as is. However I've some points to make.
First, though SPRT is mathematically sound and approved, it remains a mathematical tool. It doesn't take account about patch interaction nor about scaling with time control. If we really want to be sure for no regression, we can respin a SPRT with alpha=0.01 and beta=0.05 (asymmetrical, this makes a [-2.99,4.55] SPRT test). So adding exceptions for cases like this makes sense.
Second, LTC is the reference TC. No good STC patches that failed LTC, even +9 elo one, are ever commited However, there are already yellow STC patches but good at LTC that are commited. This makes LTC the de facto standard for SF testing, though some people doesn't like the so-called speculative LTCs. And most engine testing from 3rd party testers are (easily) beyond 30" TC.

So I don't think rejecting a +4.5 elo LTC patch by the rules is the best decision. I plead everyone to take the wisest decision to increase Stockfish's strength. Just my two cents.

**Comment by Vizvezdenec** [comment]
I think that firmly rejecting is a bad choice.
If you think that it can be a false-positive patch, you can retest it. It's not like framework is ultrabusy with smth important now. If it passes [0,5] LTC SPRT twice, probability of it being false-positive is not greated than any other patch.

**Comment by mstembera** [comment]
@zamar I completely agree w/ your decision, reasoning, and your message for future testing.  Since this patch already got this far however, would you object to an LTC retest or maybe some fixed number of games test?

**Comment by AlexandreMasta** [comment]
@mstembera you have the right to agree, but you are wrong along with @zamar. And the why is that how are you supposed to deal with the current situation and not throw a known elo gainer patch in the trashcan? Because it doesn't address the fact that you are LOSING ideas and elo with the current method. You are too stucked in the rule proccess idea that you are not seeing the problem that you are making for the project itself, like rules were a kind of religion. 
Now there will be no way to improve the engine in some niches because it is a no no to test some ideas that only kick in at LTCs.
Pls think carefully. As I said, pls put your egos aside and think carefully about what you are doing just because "the rules didnt predict this...so we throw this nice idea in the garbage" . This makes no sense to me at all.

**Comment by anshulongithub** [comment]
Let's stop pointing fingers at anyone here, please. The one and only and ONLY objective here shud be to make SF strong. V1 has been one of the most prolific contributors and I'm sure he wud have put enough thought into this patch. Having said that, I think one thing that really needs to be ascertained is whether this successful run was not just a lucky run. A retest of this patch with stricter controls can help in finding this out. We shud also try to understand just why this patch did well at LTC and logically try to get answers to this question. I want to quote V1 to reason about this patch, "My intuition thought this patch will do well at LTC, since the changed logic will get hit more often earlier in the game since SF will be searching deeper." If we can have logical reasons that prove that this patch was not just a lucky run and has really improved SF's play, then why shudn't it be committed? Maintainers @zamar and @mcostalba  I kindly request you to reconsider this patch and please advise on how to move forward in a way which will benefit SF.

**Comment by MichaelB7** [comment]
Let's run it again at LTC to remove any doubt...if it fails at LTC, the patch was correctly rejected.  If it passes, it should be committed.  Just my $.02.

**Comment by IIvec** [comment]
@MichaelB7 : the point is that maintainers obviously believe that following rules will give more benefit to Stockfish than speculative LTC tests, and I guess this is the way to stop them. I'm sorry for approving this patch...

**Comment by Vizvezdenec** [comment]
Imho, STC SPRT is done to filter complete garbage, which is like 90-95% of incoming patches, but there are some patches that can't pass STC, but can pass LTC and probably VLTC, so I personally don't see a lot of reason not to try them and commit them if they pass. % of patches that pass STC but don't pass LTC is like 80-90%, % of patches that don't fail STC in 80-200k games but pass LTC is like 10%, so basically probability of patch failing yellow with big amount of games and then passing LTC is almost the same as passing STC and then passing LTC.

**Comment by MichaelB7** [comment]
@llvec please , you do not have to explain the maintainers point to me , as you say, it is pretty obvious...  the results of the fishtest process speak for itself and one cannot really argue against the decision, but having run thousands of game with this patch included @ game 5 min /3 sec , I am fairly certain it was not a lucky run. I believe the maintainers have made their decision and it is fruitless to continue the discussion.

**Comment by vdbergh** [comment]
The general solution is simple though.

(1) Make STC a bit easier to pass e.g. SPRT(-1,4) to account for the fact that LTC is considered more important than STC. It seems currently LTC is a bit easier to pass than STC (I can explain this if anyone is interested).

(2) Disallow running patches at LTC if they have not passed STC. That way there can never be any discussion afterwards.

**Comment by IIvec** [comment]
@vdbergh : I completely agree with your solution, and I'm interested in your explanation.

**Comment by vdbergh** [comment]
The recent test at STC,LTC and VLTC shows that Stockfish has nearly perfect scaling for "normalized elo" (elo/sigma(elo) ). See this post http://talkchess.com/forum/viewtopic.php?t=63875&start=23 . Of course this was only a single test but since it involved a mix of patches, one may hope it is representative for the general case.

Taylor series expansions show that this implies that BayesElo "super scales". See the post by Jesus Munoz in the above thread. Hence when using the same bounds for STC and LTC, LTC is easier to pass.

**Comment by IIvec** [comment]
@vdbergh : Of course, I completely agree. I already tried to explain that STC and LTC are not independent events and that probability of bad patch is not 0.05 * 0.05 = 0.25%.

So, you have my +1 for SPRT[-1,4] at STC, but I don't know how to convince maintainers.
I hope they'll say few words about this.

**Comment by vdbergh** [comment]
@livec : The STC and LTC tests are independent events. But the BayesElo value of a patch changes from STC to LTC .  Thanks to the STC-LTC-VLTC test we now have idea what might be the average behaviour (and maybe the behaviour tout court, but this is much harder to decide). Note that this is only a side issue
and unimportant if speculative LTC were simply outlawed.

**Comment by lantonov** [comment]
I do not agree that LTC is easier to pass than STC. Both theory and practice show that the opposite is true. Just a cursory look at Fishtesting shows that there are much more patches that passed STC and failed LTC than vice versa. As to the STC-LTC-VLTC test, it showed very similar Elo gains at STC and LTC but a markedly lower Elo gain at VLTC. There can be many hypotheses why this is so, but IMO the most plausible cause is that most patches, especially those that gain Elo were tested to pass STC and LTC, and not tested to pass VLTC.
For the concrete patch discussed here, the converging opinion is that it should be tested once again at LTC. I join this majority.

**Comment by vdbergh** [comment]
@lantonov The claim "Just a cursory look at Fishtesting shows that there are much more patches that passed STC and failed LTC than vice versa." is meaningless since if a patch fails STC it is usually not tested at LTC. Also note that fishtest not does not use Elo but BayesElo and BayesElo went indeed up from STC to LTC to VLTC in the STC-LTC-VLTC test. This was explicitly verified by Lucas (if you do not believe my explanation).

**Comment by vdbergh** [comment]
Special casing the current patch is pointless if no assurances are made that this situation cannot be reproduced. That's why I proposed a general solution above.

**Comment by lantonov** [comment]
@vdbergh You are right that the example with Fishtest is meaningless. However, there is another direct way to compare STC and LTC passers by looking at the "Greens". Take the last, say, 50 patches that has passed both STC and LTC and record the number of games needed to pass in 2 vectors (one for STC and one for LTC). Calculate the means of the 2 vectors and test for significant difference with a paired t test. My thesis is that mean(LTC) - mean(STC) is significantly greater than 0.
The above thread discusses differences between wilo (no draws), BayesElo, and normal Elo, and doesn't touch directly on SPRT. Lucas calculates that the regression test shows more Elo gain (both BayesElo and wilo) for LTC than for STC but this can mean that the patch needs more Elo to pass the LTC SPRT. If we included in Fishtesting VLTC SPRT (I hope not), we can have more Elo difference between LTC and VLTC (more Elo for VLTC)

**Comment by IIvec** [comment]
I see no more patches from VoyagerOne :(

**Comment by Vizvezdenec** [comment]
I think he is frustrated with this situation.

**Comment by SapphireBrand** [comment]
I have struggled for months without finding a single way to improve Stockfish, despite investing enormous amounts of personal and computer time to measure or tune all kinds of ideas. Perhaps I will eventually succeed.

V1 has 51 commits. He's my idol.

**Comment by Vizvezdenec** [comment]
Just some interesting stats.
Since 1st january of this year there were 24 elo-gaining patches ([0,5] or [0,4] SPRT). 8 of them were from VoyagerOne.

**Comment by lantonov** [comment]
If zamar accepts vdbergh's proposal to relax the STC we can test again the patch at (-1,4) and it will pass. After that, all patches will be at (-1,4).

**Comment by IIvec** [comment]
This would be great because some patches indeed trigger on higher depths, but let's wait for some official
decision.

**Comment by AlexandreMasta** [comment]
The official decision was already taken.

**Comment by zamar** [comment]
Since people seem to be getting really emotional about this patch, we can do the following:
- We can spin it one more time at LTC, to prove that we didn't just have a lucky run. And if it passed, we can commit...

**Comment by anshulongithub** [comment]
@VoyagerOne I request you to **please** come back and resume development on Stockfish. Please schedule the test at LTC.

**Comment by ElbertoOne** [comment]
Currently 3 variants of this patch are being tested in the framework (by @snicolet). It seems the original run was a lucky one.

**Comment by Vizvezdenec** [comment]
Sorry for being emotional...
I think we should somewhat formalize speculative LTC to avoid such a situations in future. I think speculative LTC are more or less OK for stockfish development since in reality there are some ideas that kick in at higher depths but that can't pass STC SPRT. But for sure passing one SPRT gives less insurance than passing two of them...
My proposition sounds like that - speculative LTC can be run for patches which fail STC in a certain amount of games or more (60k, 80k, I don't really know, probably we should ask someone who understands SPRT better), but if they pass LTC, they need to be retested at LTC to check if it was not just a lucky run.
Why it's OK for testers? Because usually testers run speculative LTCs when they are currently out of ideas and network is somewhat idle, but they can bring some elo this way. It's also OK for maintainers since we have insurance of double SPRT of that patch being non-regression. It's also OK in terms of using fishtest resources - since 1st january there were 2 or 3 patches that passed speculative LTC, I think that running 1 extra LTC once in 2 months wouldn't hurt fishtest whatsoever. And usually speculative LTCs are run anyway and fail pretty quickly anyway. And it's for sure good for engine development, since there are patches that start to kick in at higher depths. Also it's good in terms of avoiding such a situations in future.

**Comment by AlexandreMasta** [comment]
@ElbertoOne ...variants...
seems to me that variants are not the original one...so you cant get any conclusions with variants about the original one that passed with less than 15k games.

**Comment by ElbertoOne** [comment]
@AlexandreMasta one of the 3 patches is the same as the original: http://tests.stockfishchess.org/tests/view/592daba40ebc59035df34ded
LLR is -0.78 after almost 11K games

**Comment by Vizvezdenec** [comment]
Indeed it looks like we had false-positive result, but I think that in case of speculative patches we do need extra insurance, since they are getting approved from time to time... But one SPRT can be just a lucky run. I think that my suggestion will be a great solution for that cases which is probably okay for everyone.

**Comment by burak13** [comment]
It seems that zamar was right about his judgement, after all he is one of the most experienced guys around here. 3 failed results against 1 successful result which ended too quickly (elevated chance for a lucky run rather than great scaling). 
However, he was a little bit rude by outright rejecting the patch which comes from one of the most successful developers in recent years. IMO, Zamar should have asked for an additional test to get rid of the doubt (he did in the end), maybe he is busy nowadays and didn't want to spend extra time, who knows. I hope VoagerOne returns after recovering from his possible frustration&disappointment. We really need him.

**Pull request closed without merging**
