### PR TITLE
Update our continuous integration machinery

### PR DESCRIPTION
**Pull request by erbsenzaehler**
Ubuntu 16.04 can now be used with travis. Updating all the other stuff
when there.

No functional change.

### CODE REVIEW

**Comment by vondele** [comment]
in this form, this disables the sanitizer checks since they look for an exact match to g++-7 you might want to fix this. However, with a sufficiently recent environment we might be able to avoid installing a compiler and just go with the system one, and have sanitizers nevertheless. I think skipping these additional tests is what speeds up the testing, unfortunately.

**Comment by erbsenzaehler** [comment]
I missed that. But I noticed the speed up for the clang build only.

The compilers coming with Ubuntu 16.04 are quite old already, so I do not know if we want to use them.

https://packages.ubuntu.com/search?suite=xenial&section=all&arch=any&keywords=gcc&searchon=names

https://packages.ubuntu.com/search?suite=xenial&section=all&arch=any&keywords=clang&searchon=names

**Comment by vondele** [comment]
Thanks for fixing..

from the link it looks like this is still gcc 5.3 ... if so, no we want something more recent.

**Comment by vondele** [comment]
This is also ready for merging IMO

**Comment by mcostalba** [comment]
Ok thanks

**Pull request merged**
