### PR TITLE
Top CPU contributors as of November 2018

### PR DESCRIPTION
**Pull request by mibere**
Old list was last updated 9 months ago

### CODE REVIEW

**Comment by Vizvezdenec** [comment]
I think you can add up two chinese DB worker pools and call them "noobpwnftw".

**Comment by noobpwnftw** [comment]
Yes, please summarize my 2 accounts under nickname "noobpwnftw", thanks!

**Comment by Vizvezdenec** [comment]
well the thing is that top-2 users are basically the same user and second one was created due to some fishtest base crash so chineseDBworkerpool couldn't login for some time. It's kinda stupid to have 2 different contributors for 1 person which happened only because of database crash :)

**Comment by snicolet** [comment]
Merged via 05aa34e00ed78adfa943242026a00dc497acd563, thanks!

Note: nickname 'noobpwnftw' consolidated.

**Pull request closed without merging**
