### PR TITLE
Fix build error on OSX

### PR DESCRIPTION
**Pull request by vondele**
include needed header

fixes https://github.com/official-stockfish/Stockfish/issues/3573

No functional change

### CODE REVIEW

**Comment by snicolet** [comment]
Maybe just simplifying lines 235 and 264 to the following would do (without having to  `#include <cmath>` )

```
int cp = std::abs(100 * v / PawnValueEg);
```

**Comment by vondele** [comment]
I'm fine with that if we can verify this fixes it? @yuzisee

**Comment by vondele** [comment]
we usually have types.h included which includes cstdlib which provides the function as well, so we're not adding anything exotic.

**Comment by snicolet** [comment]
I have verified that the cp value calculated this way is equivalent to the cp value calculated with floating point numbers, by comparing the versions in regular eval in evaluate.cpp and running bench (so a large number of use):

```
      int cp1 = (int)(std::abs(100.0 * double(v) / PawnValueEg));
      int cp2 = std::abs(100 * v / PawnValueEg);
      dbg_mean_of(cp1 == cp2);
```

They are the same for 1004107 use:
```
Total 1004107 Mean 1
```

**Comment by vondele** [comment]
equivalence is OK, however, does it fix the compilation problem?

**Comment by yuzisee** [comment]
`int cp = std::abs(100 * v / PawnValueEg);` compiles just fine on OSX, yes

**Comment by vondele** [comment]
OK, thanks, I'll update the PR for that variant.

**Comment by snicolet** [comment]
> Maybe just simplifying lines 235 and 264 via the following would do (without having to `#include <cmath>` ):
> Replace (twice)
> ```
> int cp = (int)(std::abs(100.0 * double(v) / PawnValueEg));
> ```
> with
> ```
> int cp = std::abs(100 * v / PawnValueEg);
> ```

Hmm, there were two occurrences of the non-compiling code, one remains?

**Comment by vondele** [comment]
thanks for spotting that... let me check again.

**Comment by vondele** [comment]
will be fixed in the merge commit.

**Pull request closed without merging**
