### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by johnsonr**
Add .gitignore file so binaries don't show up in git

### CODE REVIEW

**Comment by Sopel97** [comment]
The incremental GCC linker also produces `*.s` files

**Comment by johnsonr** [comment]
Could add an exclude for `*.s` files. Might also want to consider IDE files such VS Code `.settings.json` and IntelliJ files. Should I add all those?

**Comment by liamlim** [comment]
Maybe ignore .vs folder as well? I think that's a good thing to do if you ignore specific files for Visual Studio Code and IntelliJ to also ignore specific files for Visual Studio.

**Comment by kraktus** [comment]
Local IDE files should not be ignored at the project level, but at the global level of each contributor, see [Sof](https://stackoverflow.com/questions/7335420/global-git-ignore#7335487) .

**Comment by johnsonr** [comment]
Doesn't that risk users accidentally adding their IDE files to their repos if they don't choose to do this? Also, I find that for different projects I work on I make different choices. E.g. if working alone on a project on >1 machine, I might check in IDE files. If collaborating with others, I do not.

**Comment by liamlim** [comment]
Isn't this one of the purposes of .gitignore to make life of developers easier? Every project that I can think of has .gitignore except Stockfish. Maybe I am all wrong and in that case I will gladly learn how to do things correctly and what are benefits of it

**Comment by BM123499** [comment]
what about Windows version?

**Comment by johnsonr** [comment]
I'm a bit out of date on my Windows C++ :-) What object files are produced? I can add a pattern.

**Comment by BM123499** [comment]
@johnsonr those are the files that appeared on my windows build and that `.gitignore`:

- src/-lstdc++.res
- src/stockfish.exe
- src/stockfish.exe.lto_wrapper_args
- src/stockfish.exe.ltrans.out

you can simply change `src/stockfish` to `src/stockfish*` and add `src/-lstdc++.res`

**Comment by BM123499** [comment]
if you could add to `make clean` remove those files as well, it could be a good idea.

**Comment by johnsonr** [comment]
> if you could add to `make clean` remove those files as well, it could be a good idea.

I've added a new issue for this

**Comment by BM123499** [comment]
@johnsonr My apologies, all files except `stockfish.exe` appeared on my files because I was building with `make build` instead of `make -j build`.

**Comment by vondele** [comment]
so, one question is how to limit what we put in the .gitignore, any IDE files can be there, or only files generated during the build process?

**Comment by johnsonr** [comment]
I think the minimum for an open source project should be files generated during the build process.

However, I think that it's reasonable to include common IDE files. Here's [an example](https://github.com/spring-projects/spring-framework/blob/cfae40afb456c98b2a11be600096da89b8aacafd/.gitignore#L35) from the Spring Framework, one of the leading open source projects in Java. The only reason _not_ to do this would be to ensure consistent IDE config and I don't think that's reasonable in an open source community.

**Comment by johnsonr** [comment]
I think the best path would be to merge this and subsequently refine it wrt IDEs. _Not_ having any `.gitignore` is highly unusual. I've run a quick query for top Github repos by stars and all the top C++ repositories have one. Most seem to exclude IDEs.

Ultimately I think it makes sense to expand the excludes to include IDEs used by all contributors.

Here's the [.gitignore for grpc](https://github.com/grpc/grpc/blob/master/.gitignore). Excludes for multiple technologies including XCode and VS Code.

**Comment by vondele** [comment]
I'll merge without the editors section. Since that section will grow unbounded, give the variety of editors out there.

**Pull request closed without merging**
