### PR TITLE
New shell scripts for testing, used for travis CI

### PR DESCRIPTION
**Pull request by vondele**
perform more complex verification and validation.

- signature.sh : extract and optionally compare Bench/Signature/Node count.
- perft.sh : verify perft counts for a number of positions.
- instrumented.sh : run a few commands or uci sequences through valgrind/sanitizer instrumented binaries.
- reprosearch.sh : verify reproducibility of search.

These script can be used from directly from the command line in the src directory.

Update travis script to use these shell scripts.

No functional change.

### CODE REVIEW

**Comment by vondele** [comment]
The appveyor failure on the original pull requests seems to be a known issue (the second commit was unrelated but caused a new round of CI testing):

http://help.appveyor.com/discussions/problems/4830-stuck-on-appveyor-was-unable-to-build-non-mergeable

**Comment by mcostalba** [comment]
@vondele thanks! I have gladly merged it.

What about using

git log | grep -i bench | head -n 1

or even

git log | grep -i bench | head -n 1 | sed -n 's/[^0-9]*\([0-9]*\)/\1/p'

extracting the last bench number and verify the signature against it? This should work also with non functional change patches.

**Comment by vondele** [comment]
@mcostalba thanks for merging, I think this will be useful in the current form, but should also be easy to extend.

I see you already committed your suggestion, however I wanted actually to propose to add a file to the repository that stores the bench. I think this is to be preferred over parsing the git log, for example it would be available if a tarball is distributed (allowing for example for a 'make test' that verifies a correct build.), and is likely less fragile. Any pull requests that are functional changes would include the new signature in that file, and travis would automatically check that the bench number is up to date.

**Comment by mcostalba** [comment]
@vondele I think it is a bit too complex, moreover I'd like the patch to be just about the sources, without any other reference. Finally, in the current way we are sure that the bench number in the log message is correct (otherwise this triggers an error in Trevis). It is important log message bench is verified because it is usually used by people to submit new test. For instance I look at current master log message to fetch the bench that I paste in fishtest.

**Comment by vondele** [comment]
@mcostalba I agree the work flows are different, not sure it is more/needlessly complex. In the scheme I propose (see also example implementation #960) the bench doesn't need to be in the log anymore, and is also verified in Travis as part of the PR. By making this info part of the sources, we actually increase its status, in my opinion.

**Pull request merged**
