### PR TITLE
Rework King Evasion

### PR DESCRIPTION
**Pull request by BM123499**
It removes all position attacked by checkers (except knight checker attacks). Though it's just differ to queen and rook adjacent attacks, it seems it's good enough for speeding up.

Note: Including `KNIGHT` on `attackers` seems to lead to [regression](https://tests.stockfishchess.org/tests/view/6044346e33eb56b2e8566d62), and excluding `PAWN` didn't pass [STC](https://tests.stockfishchess.org/tests/view/6043e8b633eb56b2e8566d40).

Trivia: it solves #3171 (crash by illegal check made by two checkers in the same line)

```
Build Tester: 1.4.7.0
Windows 10 (Version 10.0, Build 0, 64-bit Edition)
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: Yes
CPU Warmup: Yes
Command Line: bench 16 1 5 default perft
Tests per Build: 10
ANOVA: n/a

                    Engine# (NPS)                          Speedup     Sp     Conf. 99.5%  S.S.
patch  (246.778.658,0 ) ---> master  (235.710.987,7 ) --->  4,695%  357.715,8    Yes       No 
```

passed STC:
LLR: 2.93 (-2.94,2.94) {-0.25,1.25}
Total: 50056 W: 4541 L: 4357 D: 41158
Ptnml(0-2): 139, 3445, 17717, 3547, 180
https://tests.stockfishchess.org/tests/view/604425e633eb56b2e8566d53

yellow LTC:
LLR: -2.93 (-2.94,2.94) {0.25,1.25}
Total: 34704 W: 1272 L: 1264 D: 32168
Ptnml(0-2): 15, 1082, 15143, 1104, 8
https://tests.stockfishchess.org/tests/view/604433af33eb56b2e8566d60

Non-functional change

### CODE REVIEW

**Comment by vondele** [comment]
For me this patch appears to be a slowdown when applied to current master:
```
Result of  30 runs
==================
base (./stockfish.master       ) =    2303401  +/- 6464
test (./stockfish.patch        ) =    2283198  +/- 7441
diff                             =     -20204  +/- 5809

speedup        = -0.0088
P(speedup > 0) =  0.0000

CPU: 16 x AMD Ryzen 9 3950X 16-Core Processor
```
I haven't investigated yet what the reason for CI failure is. It was repeatable however.

**Comment by BM123499** [comment]
For the first patch, as you can see, I tested with perft for speed up to concentrate the path more in movegen. It also has a passed STC test and a yellow LTC test. Given those evidences, I can't find myself on thinking that it would be a slowdown. But, of course, it could be a fluke in all test with a low probability.

For the second patch, I can't test with perft because QUIET_CHECKS is just called in a search, even though it seems to be better on STC test, it could be a fluke since I can't provide more info.

**Comment by vondele** [comment]
so, if I understand correctly, this PR contains 2 patches, tested independently. That's generally not a good idea.
Additionally, CI fails and I test no speedup on the combo. 
What I would propose is you close this PR, but test the combo on a clean branch on fishtest again. If it passes you create a new PR.

**Comment by BM123499** [comment]
@vondele I can speak with property about the second patch, so I'll remove it to avoid any issue.

**Comment by gvreuls** [comment]
The CI error is a strange memory leak in search that only occurs with clang/llvm so it's probably due to the second patch.

**Comment by BM123499** [comment]
@gvreuls Strange, because it had no problem, I just updated `pop_lsb()` to avoid conflict.

**Comment by gvreuls** [comment]
@BM123499 My previous comment was a bit hasty because CI already failed on the first commit. Let's wait and see what travis says :)

**Comment by BM123499** [comment]
@gvreuls it failed on the first commit due to assert. I intended to return a empty value from the function, but it has an assert to avoid using that function for pawn attacks. That's why the next commit passed with only changing that assert.

**Comment by vondele** [comment]
Same performance for me after the revert:
```
Result of  10 runs
==================
base (./stockfish.master       ) =    2298874  +/- 6820
test (./stockfish.patch        ) =    2277302  +/- 9643
diff                             =     -21572  +/- 14608

speedup        = -0.0094
P(speedup > 0) =  0.0019

CPU: 16 x AMD Ryzen 9 3950X 16-Core Processor

```

**Comment by BM123499** [comment]
I tested on my machine as well:
```
Build Tester: 1.4.7.0
Windows 10 (Version 10.0, Build 0, 64-bit Edition)
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: Yes
CPU Warmup: Yes
Command Line: bench
Tests per Build: 100
ANOVA: n/a

                Engine# (NPS)                              Speedup     Sp     Conf. 95%    S.S.
patch  (1.510.882,8   ) ---> master  (1.501.639,6   ) --->  0,616%  51.253,9     No        No 
```

It may be a compile-dependent patch. Because of the nature of `index()` used in `attacked_bb()`.
I believe this may explain such difference in results.

**Comment by vondele** [comment]
In that case, I would prefer to close the PR.

**Pull request closed without merging**
