### PR TITLE
Assorted trivial cleanups 3/2019

### PR DESCRIPTION
**Pull request by mcostalba**
No functional change.

### CODE REVIEW

**Comment by protonspring** [comment]
Position.h: line 416:  Since the SquareBB have only one bit a piece, to me, the | operator is much more clear than the ^ operator.

Bitboard fromTo = SquareBB[from] \| SquareBB[to];

**Comment by xoto10** [comment]
Not sure if this is appropriate for this PR, I tried moving some variable declarations later in search(), see [here](http://tests.stockfishchess.org/tests/view/5c7ed7430ebc5925cffe0969), perhaps there is a minor positive effect from this? 
In bench ~62% of calls to search() exit before moves_loop (also very similar number for bench to depth 20).

**Comment by protonspring** [comment]
bitboard.cpp, line 27, there is a remnant ForwardRanksBB, which is no longer used.  This can be removed, right?

**Comment by protonspring** [comment]
Movepick.cpp, around line 85.

The stage = PROBCUT_TT can be moved to the initializer list because there are no conditions.  It's probably a little faster there as well.

**Comment by mcostalba** [comment]
Thanks applied. Regarding stage = PROBCUT_TT, I'd prefer to leave as is for consistency with teh other c'tors (speed is the same).

@xoto10 no, there is no positive effect, the variables are allocated on the stack in one go in C/C++, for example:

```
int x, b, c  // Assume 4 bytes * 3
float fff; // Assume 8 bytes 
```

yields in the compiled binary to the stack pointer (sp) increment (actually a decrement):

`sp -= 20
`

**Comment by mstembera** [comment]
Lines 80 to 83 in endgame.cpp can be replaced by
```C++
return strongSide == WHITE ? sq : ~sq;
```

**Comment by mcostalba** [comment]
@mstembera thanks. Done.

**Comment by protonspring** [comment]
Position.cpp line 839.  This line is rather cryptic:
if (   (int(to) ^ int(from)) == 16 . . 

Isn't this more clear?
if ((abs(to - from) == 16) . . .

**Comment by protonspring** [comment]
This is too small a change for it's own PR, so I post here:
src/position.cpp -629,7 +629,7

Change       if (rank_of(to) == relative_rank(us, RANK_8))
TO:              if ((Rank8BB | Rank1BB) & to)

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 75467 W: 16700 L: 16685 D: 42082

**Comment by protonspring** [comment]
I'm not sure if this got missed intentionally, or on purpose, but in movegen.cpp, lines 32+, these lines can be consolidated.  Would this need testing?

if (Type == QUIETS || Type == EVASIONS || Type == NON_EVASIONS)
for (PieceType pt : {ROOK, BISHOP, KNIGHT)
*moveList++ = make<PROMOTION>(to - D, to, pt);

**Comment by xoto10** [comment]
Typo "alredy" at line 35 in thread.cpp

**Comment by mcostalba** [comment]
Thanks! done.

@protonspring I'd prefer to explicitly unroll the loop in movgen. Maybe the compiler is smart enough to unroll it for us, eventually we should check the assembly to verify the loop is correctly unrolled.

**Comment by mstembera** [comment]
I noticed that SquareBB[SQ_NONE] currently results in an out of bound access.  Would it make sense to extend SquareBB from SquareBB[SQUARE_NB]; to SquareBB[SQUARE_NB + 1]; and assign SquareBB[SQ_NONE] = 0; to avoid this issue?

**Comment by protonspring** [comment]
I would just set SQUARE_NB to 65.

**Comment by mstembera** [comment]
@protonspring Since SquareBB[] is just an optimization for 32-bit it should not change the definition of SQUARE_NB which would otherwise not be necessary.  (Besides 65 feels quite unnatural compared to 64 for chess anyway.)

**Comment by mstembera** [comment]
Line 56 in misc.h
```C++
std::vector<Entry> table = std::vector<Entry>(Size);
```
in misc.h can simply be
```C++
Entry table[Size];
```

**Comment by mstembera** [comment]
Lines 155 to 157 in material.cpp could be changed from
```C++
  const EndgameBase<ScaleFactor>* sf;
  if ((sf = pos.this_thread()->endgames.probe<ScaleFactor>(key)) != nullptr)
```
to
```C++
  const EndgameBase<ScaleFactor>* sf = pos.this_thread()->endgames.probe<ScaleFactor>(key);
  if (sf)
```
so we don't have to assign inside the if statement and use extra parentheses to clarify it.

**Comment by protonspring** [comment]
Would it be good if I went through and made as many constexpr as possible?

**Comment by protonspring** [comment]
Also. . any opinions on this?

http://tests.stockfishchess.org/tests/view/5c93f2cf0ebc5925cfff4191

**Comment by mcostalba** [comment]
@mstembera thanks, updated. Because HashTable becomes a data member of Thread, it is better to allocate its giant table on the heap, I have added a comment to clarify this.

@protonspring we could, but it seems a bit too invasive to me.

**Comment by Rocky640** [comment]
missing a space before the = in pawns.cpp
`e->passedCount= popcount(e->passedPawns[WHITE] | e->passedPawns[BLACK]);`

**Comment by mstembera** [comment]
@mcostalba Thanks for the heap explanation.
We should probably add the initialization
```C++
SquareBB[SQ_NONE] = 0;
``` 
on line 85 in bitboard.cpp

**Comment by mstembera** [comment]
Alternately we could not extend the SqyareBB[] array at all and just use an accessor  function with an assert.
```C++
inline Bitboard make_bb(Square s) {
  assert(s < SQUARE_NB);
  return SquareBB[s];
}
```
Not sure which is preferable.

**Comment by mcostalba** [comment]
@mstembera extending is easy and straightforward. SquareBB[] is already zero initialized (actually zero allocated) as any global variable with no specific constructor.

**Comment by Rocky640** [comment]
An array of size 65 seems odd indeed.
assert(s != SQ_NONE); or assert(s < SQUARE_NB) would do the job.

**Comment by mcostalba** [comment]
@Rocky640 yes, but they will not remove the warnings that I have under my mingw compiler :-)

**Comment by protonspring** [comment]
I think in pawns Entry , a better name for "kingSquares[]" to "kingEvalSquare[]" ?

**Comment by protonspring** [comment]
since phalanx is 0 or 1, this conditional could be removed:

v += (Seed[r] + (phalanx ? (Seed[r + 1] - Seed[r]) / 2 : 0)) >> opposed;

Could be simplified to:

v += (Seed[r] + (phalanx * (Seed[r + 1] - Seed[r]) / 2)) >> opposed;

**Comment by Rocky640** [comment]
@mcostalba  and no such warning for DistanceRingBB or other arrays with [SQUARE_NB]  ?
We can also get rid of the SquareBB array using a sq_bb(Square s) accessor
which would return DistanceRingBB[s][0];

**Comment by protonspring** [comment]
Test to remove SquareBB using DistanceRingBB (looks good to me!).
http://tests.stockfishchess.org/tests/view/5c9b9df00ebc5925cfff9b2d

**Comment by mcostalba** [comment]
@protonspring  actually kingSquares[] stores the king squares(!) for both colors:

`kingSquares[Us] = ksq;
`

**Pull request merged**
