### PR TITLE
Fix processor group binding under Windows.

### PR DESCRIPTION
**Pull request by noobpwnftw**
Old code only worked because there was probably a limit on how many cores/threads can reside within one NUMA node, and the OS creates extra NUMA nodes when necessary, however the actual mechanism of core binding is done by "Processor Groups"(https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups). With a newer OS, one NUMA node can have many such "Processor Groups" and we should just consistently use the number of groups to bind the threads instead of deriving the topology from the number of NUMA nodes.

No functional change.

### CODE REVIEW

**Comment by noobpwnftw** [comment]
I can confirm locally that this is required to spread threads on all cores on Windows 11 with a 3990X CPU. It has only 1 NUMA node with 2 groups of 64 threads each.

Other OS/CPU combinations are not yet tested, hopefully nothing breaks.

**Comment by vondele** [comment]
thanks, maybe somebody with an older version of windows and a 64+ threads machine could give this a test as well.

**Comment by noobpwnftw** [comment]
Behavior change of the API is documented here:
https://docs.microsoft.com/en-us/windows/win32/procthread/numa-support
Read "Behavior starting with Windows 10 Build 20348".

**Comment by vondele** [comment]
```
Creating "fake" nodes to accommodate a 1:1 mapping between groups and nodes 
has resulted in confusing behaviors where unexpected numbers of NUMA nodes 
are reported and so, starting with Windows 10 Build 20348, the OS has changed [...]
```
who would have guessed

**Comment by vondele** [comment]
There hasn't been any negative feedback, so I'll proceed with merging. We'll see if it causes problems with older windows OS on large core hardware.

**Comment by g3g6** [comment]
I think that this code doesnt work right way. I have system 2xXeon E5 2697 v2 (24 cores, 48 treads) and since this version, when i set number of cores to 24, then Stockfish use 1CPU to 100% and second CPU is idle. Previous versions works right way, 12 cores running for both CPU's.

**Comment by vondele** [comment]
Thanks for the feedback... I think we'll need to understand if this windows version is from before of after `Windows 10 Build 20348` , i.e. before the change in Windows API concerning NUMA or not (see link above).

**Comment by noobpwnftw** [comment]
> I think that this code doesnt work right way. I have system 2xXeon E5 2697 v2 (24 cores, 48 treads, Windows 10 21H2, x64 ) and since this version, when i set number of cores to 24, then Stockfish use 1CPU to 100% and second CPU is idle. Previous versions works right way, 12 cores running for both CPU's.

As per 14.1 release(before the patch):
https://github.com/official-stockfish/Stockfish/blob/7262fd5d14810b7b495b5038e348a448fda1bcc3/src/misc.cpp#L551-L555

If in your system, "12 cores running for both CPU's" is the wrong behavior and now "use 1CPU to 100% and second CPU is idle" works as intended.

**Comment by Ipmanchess** [comment]
@g3g6 Can you run this bench with Stockfish 14.1 and also with last version to see the difference : [http://ipmanchess.yolasite.com/amd--intel-chess-bench-stockfish.php](url) Thanks!

**Comment by g3g6** [comment]
> Thanks for the feedback... I think we'll need to understand if this windows version is from before of after `Windows 10 Build 20348` , i.e. before the change in Windows API concerning NUMA or not (see link above).

Win 10 x64, 21H2, build 19044.1348

**Comment by g3g6** [comment]
> http://ipmanchess.yolasite.com/amd--intel-chess-bench-stockfish.php

Benchmark:
14.1: 
===========================
Total time (ms) : 180287
Nodes searched  : 3299797749
Nodes/second    : 18303026


the last dev:
===========================
Total time (ms) : 281867
Nodes searched  : 3195021430
Nodes/second    : 11335209

**Comment by noobpwnftw** [comment]
https://github.com/official-stockfish/Stockfish/pull/3798 will restore old NUMA assignment behavior.

**Pull request closed without merging**
