### PR TITLE
Do not skip non-recapture ttMove when in check

### PR DESCRIPTION
**Pull request by syzygy1**
The qsearch() MovePicker incorrectly skips a non-recapture ttMove when in check (if depth <= DEPTH_QS_RECAPTURES). This is clearly not intended and can cause qsearch() to return a mate score when there is no mate. (Incorrect mate scores reported to the user should be extremely rare though, if possible at all.)

The bug seems to have been present in hidden form since this patch:
https://github.com/official-stockfish/Stockfish/commit/cad300cfab869a4e8dcc6b286f9b2e60d2827bed
Hidden, because the skipped ttMove would still be played when it was generated.

The bug was "activated" by this patch (and detected by @joergoster in #3171 and #3198):
https://github.com/official-stockfish/Stockfish/commit/6596f0eac0c1d25a12bfd923907bfc78beedbc90

This PR fixes the bug by not skipping the non-recapture ttMove when in check.

Passed non-regression STC:
https://tests.stockfishchess.org/tests/view/5f9867ea6a2c112b60691b10
LLR: 2.98 (-2.94,2.94) {-1.25,0.25}
Total: 27112 W: 2943 L: 2842 D: 21327
Ptnml(0-2): 127, 2170, 8878, 2237, 144 

Passed non-regression LTC:
https://tests.stockfishchess.org/tests/view/5f9967326a2c112b60691bb0
LLR: 2.99 (-2.94,2.94) {-0.75,0.25}
Total: 18392 W: 807 L: 738 D: 16847
Ptnml(0-2): 9, 655, 7802, 718, 12 

Bench: 3870606

### CODE REVIEW

**Comment by syzygy1** [comment]
I think this still needs LTC, but I'd first like to know if we want to fix it like this or revert the patch that activated the bug.

**Comment by syzygy1** [comment]
Looks like I've figured out the problem.

**Comment by vondele** [comment]
thanks for the analysis, I think this is the better fix, so please run an LTC test.

**Comment by joergoster** [comment]
I can confirm that with this fix applied the assert doesn't fire.

@vondele Please note, as I already pointed out in #3171 this is only one part of the bugfix.
This commit https://github.com/official-stockfish/Stockfish/commit/843a961a8c10d5949e04718b829e3b3d5adeedb4 also triggers the assert.

**Comment by vondele** [comment]
yes, we need to fix the other bit as well. We can deal with it separately, however. I have been wondering if even https://github.com/official-stockfish/Stockfish/issues/3196 is related (but this PR alone doesn't fix it).

**Comment by joergoster** [comment]
@vondele Started a [test](https://tests.stockfishchess.org/tests/view/5f9918796a2c112b60691b80) with a fix on top of Ronald's fix.

**Comment by syzygy1** [comment]
I see @vondele is also running a test, so I should probably not start LTC for now.

**Comment by vondele** [comment]
@syzygy1 I think might be useful nevertheless, at least that will be enough to fix part 1 of this regression. Seems like the additional pruning in qsearch might be more tricky to fix without Elo loss.

I'm getting more and more convinced that #3196 is a bug that results from this. At least the assert is triggered quickly on that case, and I don't see the wrong scores in the first round of testing (2000 searches on the input I provided in that issue) with the combined two patches in place.

**Comment by syzygy1** [comment]
@vondele That would be a very welcome side effect and doesn't seem impossible. I have started an LTC test. Bench is wrong again, but we already know that it compiles (and I see no good space to remove just to fix the commit message ;)).

(Well, I could negate the ||s back into &&s as it was before. Not sure why I changed that.)

**Comment by syzygy1** [comment]
LTC passed.

I have made the code a bit nicer (and fixed bench). Feel free to reformat to your liking.

**Pull request closed without merging**
