### PR TITLE
Tune time management for LTC

### PR DESCRIPTION
**Pull request by lp--**
60+0.6:
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 102533 W: 14270 L: 13842 D: 74421

### CODE REVIEW

**Comment by mcostalba** [comment]
1.01 ?

At this point please remove the coeff completely (1.00) and at least is
also a nicer simplification patch.

**Comment by zamar** [comment]
approved.

I'm not sure if we want that coefficient to be removed. It's quite critical in tuning time management. Even though the ideal value is currently very close to 1.00, future changes are likely to change the optimum, and then we want to retune this coefficient again... IMHO it's better to keep it explicitly there.

**Comment by lp--** [comment]
@mcostalba:  1.00 likely would not pass improvement test.  But as simplification it seems too little and unimportant especially considering that current structure looks a little arbitrary anyway  in how and where it defines  things.

I rewrote here to even more  compact form:
https://github.com/lp--/Stockfish/compare/tm_scaling...tm_min
It still needs to be additionally tested though due to very small rounding.
 
Or , maybe for better clarity, 
(1 + mainThread->bestMoveChanges) * ( 640  
          - 160 * !mainThread->failedLow - 126 * (bestValue >= mainThread->previousMoveScore)  
          - 124 *(bestValue >= mainThread->previousMoveScore && !mainThread->failedLow))/634
as a whole,  can be moved up to timeman.cpp as function. But it will have additional lines of code.

But I am fine with whatever maintainers decide is the best structure to have.

**Comment by lp--** [comment]
I even before ran as a simplification test like this 
http://tests.stockfishchess.org/tests/view/568377c40ebc5966b711a9bc

but later understood, that it is not really simplification and should be tested as improvement

**Comment by Stefano80** [comment]
But indeed Marco is right. We have three parameters:
1) The age-out factor 0.505
2) This multiplication factor 1.01
3) And the (implicitly defined) additive factor of 1 which is added to bestMoveChanges every time you have a change in best moves.

1) and 3) are defined and used in search.cpp, while 2) is defined in timeman. Would it not be better to replace the implicit additive factor in Step 18 of search? Instead of adding 1 there we could add 1.01 there and we could get rid of a multiplicative factor here which actually belongs somewhere else. It is not exactly the same but almost.

Or alternatively, one could tweak the XScale in move_importance and achieve a very similar effect. We have more than 10 constants for time management, it would be nice if we could remove one...

**Pull request closed without merging**
