### PR TITLE
Monthly Update  Top CPU Contributors.txt automatically

### PR DESCRIPTION
**Pull request by Pablohn26**
With this workflow, "Top CPU Contributors.txt" file is updated the first day of each month automatically based on the info of https://tests.stockfishchess.org/contributors using script contributors-update.py.

### CODE REVIEW

**Review by Disservin — CHANGES_REQUESTED** [review]
a) this won't work because permissions are missing
b) configuring git with your own name and email is perhaps weird, it's not you who is doing this.. it is the ci
c) i think this doesn't include some manually adjustments that we have in the current script (found somewhere on discord)
d) the way the current workflow is written has security flaws and uses very old action version

**Comment by Disservin** [comment]
@vondele the matetrack ci failed here, is this a known issue?

**Comment by peregrineshahin** [comment]
This branch is 41 commits ahead and 107 commits behind of official master

**Comment by robertnurnberg** [comment]
```
Engine ID:     Stockfish dev-20240620-5485a132
Total FENs:    2000
Found mates:   1239
Best mates:    997

Parsing the engine's full UCI output, the following issues were detected:
Bad PVs:       3487   (from 871 FENs)
```

**Comment by Disservin** [comment]
ah good point well okay that explains it then xd

**Pull request closed without merging**
