### PR TITLE
Fix comments in thread.cpp

### PR DESCRIPTION
**Pull request by mcostalba**
And reshuffle a bit the functions to place
them in a consistent order.

No functional change.

### CODE REVIEW

**Comment by glinscott** [comment]
Looks good.  Additional lock added when thread shutting down?

**Comment by zamar** [comment]
I've reviewed the patch and it looks fine for me. You even fixed one race condition at program shutdown, excellent :-)

However I know from experience that it's so easy to go wrong with SMP changes that I think we should do basic crash testing before committing (run 10k games with 3 threads and verify that it doesn't crash).

If it passed the crash test, it's fine for me to commit the patch.

**Comment by mcostalba** [comment]
@Gary

Yes, is more theoretical than real because when we toggle exit flag search
is already stopped, but anyhow I have fixed it for documenting purposes.

@Joona

Ok, I will schedule a test: 10k games with 3 threads

**Comment by mcostalba** [comment]
Test finished: no crashes, no regressions.

ELO: 3.76 +-4.4 (95%) LOS: 95.4%
Total: 8408 W: 1501 L: 1410 D: 5497

Patch applied. Thanks.

**Pull request closed without merging**
