### PR TITLE
8x8 PSQT for Kings.

### PR DESCRIPTION
**Pull request by Kurtbusch**
STC: 
LLR: -2.95 (-2.94,2.94) [0.00,5.00]
Total: 8128 W: 1701 L: 1792 D: 4635
http://tests.stockfishchess.org/tests/view/5be0ff980ebc595e0ae2da4a

LTC: 
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 28178 W: 4625 L: 4394 D: 19159
http://tests.stockfishchess.org/tests/view/5be0ff980ebc595e0ae2da4a

Thanks to @Rocky640 for helping me set up the tuning session.

As shown above, this failed STC extremely quickly but passed LTC relatively easily. To be honest, I'm not sure why this is; it might just be a fluke, or the TC might really important for this. Please let me know if I should run another test to confirm the ELO gain.

Obvious next steps for this are more tuning (which is underway, but possibly even more as values have yet to converge) and 8x8 PSQTs for other pieces, although I think the 8x8 is most effective for kings due to queenside vs kingside castling.

Thanks!

Bench: 3582896

### CODE REVIEW

**Comment by NKONSTANTAKIS** [comment]
This is great, the sloppy average values were leading to inferior setup selections. Its great to see how efficient SPSA is at tuning many values at once. The values keep changing and we could see the 150K ones ,or the extrapolated, gain clear elo over this. I regard that through even more specialization of PSQT's, the eval accuracy will raise the elo ceiling of SF. Now we could try 8x8 for all pieces (not sure if 1 by 1 is better or all at once). Also Rocky's idea of 4 x 4x8 specialized for King-Pair positions could carry even higher potential.

**Comment by MichaelB7** [comment]
Very nice , congrats ! 👊

**Comment by 31m059** [comment]
To reuse an earlier comment I made on another PR:

I recommend you make the following small changes.

- Move "Bench: 3582896" to the very end of the PR message.
- Make sure this is also at the end of the most recent commit message. You can make another commit without changing the code like this:
`git commit --allow-empty -m "your message here. Bench: 3582896"`
and then push it to the same GitHub branch as this PR like any other commit.

That should be enough for AppVeyor and Travis CI to pass.

**Comment by 31m059** [comment]
Odd. AppVeyor and Travis CI appear to be misinterpreting something; based on their errors, they read your commit message and expected the bench to be 8.
`signature mismatch: reference 8 obtained: 3582896 .`

Maybe remove "8x8" and replace it, for example, with "eight-by-eight"?

**Comment by GuardianRM** [comment]
Good patch. It looks like the asymmetric setting can give a more accurate result. An even more precise setting is possible, such as [SquarePt-1] [SquarePt-2] will get even more accurate values, but these are 64x64 tables that will be set up for a long time. Nevertheless, it seems that there is potential. Perhaps someone will be able to integrate a 64x64 table in a fairly simple form so that it can be customized in parts. It would also be interesting if someone checked the 8x8 mobility coverage table, i.e. if a field is included in the mobility area [Pt], it receives a bonus by analogy with psqt, perhaps this would help improve existing mobility, since with the same values ​​of popcount [mobility area] different values ​​could be obtained.

**Comment by FauziAkram** [comment]
For both the patches that we have, that failed STC but passed LTC, I would suggest two runs with (-3,1) bounds, one at STC and one at VLTC just to make sure that we are not losing any elo there.
And if they pass, then merge them because they already proved to be very good in the LTC test, while if they fail any of the two (-3,1) run , then reject the patch.

**Comment by Rocky640** [comment]
First, congrats for the experiments and the results.

However I would not commit this before we have more data.
Maybe the STC test was unlucky, or the LTC test was lucky.

The pass-rate table and ELO expectations on https://github.com/glinscott/fishtest/wiki are based on tests which passed both STC and LTC.

All the other king safety parameters passed STC (or were at least yellow).
Why would only these (new) parameters make an exception ?

Starting to make exceptions for a [0, 5] test will open a can of worm.

Looking at the experiment more closely:

I will start another experiment soon.
I might be completely wrong, but I believe that for the King asymmetry, only the mg values, and only for the first 2 home ranks are useful.

Why would a White Kh6 be better or not than a White Ka6. Really ?
Can SPSA, even with 150000 games, be powerful enough to tell us which, between a Ka6 and a Kh6 
is better in the endgame ?  I don't believe this.

**Comment by NKONSTANTAKIS** [comment]
@Rocky640 In fact SPSA seems so successful that we could totally skip both STC and LTC, just tune at VLTC and copy-paste the values!

The Ka6 - Kh6 and all similar differences are probably related to how often statistically a K is reaching a6 in a won game than a lost one. ie Given that K-side castling happens in the vast majority of games, a K reaching h6 in endgame could mean that it is more likely to supporting pawns for queening than a6 where it could be more often being chased for mate. Such things are incomprehensible, its just what the engine needs to fill up the gaps that we create by injecting wise bias. The NN's do just that and nobody knows what they are doing. Similarly we will also have no clue on why those psqt numbers work for the engine but they do! And the more variety of tables we use for each specialized situation the more appropriate the values will be for it. And as we add or remove code elsewhere, those numbers will adapt to what is needed for balancing it out. They don't have to make sense to us, they are the product of automated tuning, whatever wins.

**Comment by Alayan-stk-2** [comment]
With the last test at red by 4 games : http://tests.stockfishchess.org/tests/view/5be4d2de0ebc595e0ae30814

Over the 119K of the 3 tests, 96% it's not a regression, 52% it gains 1+ ELO, 5% it gains 2+ ELO, which is worse than the previous estimate.

The 150K test failed at red, even if not by that much.

**Comment by Kurtbusch** [comment]
Closing pull request as this is obviously not commitable. It does certainly raise questions about the volatility of even LTC tests though.

**Comment by NKONSTANTAKIS** [comment]
@Kurtbusch  I would like to see a final STC here and, if red, a VLTC. The logic for this is that a 2nd red SPRT would bring high confidence in contrasting the 2 LTC's, vastly increasing the possibility of a very high scaling curve. Given that we already used 300K LTCs and an STC sprt, I think a final sprt is cheap enough. If it is on yellow or green track we can terminate the test early and never look back, it is a red that we want for not giving up on this just yet. I take full responsibility for this, I was big believer of the 8x8 and I also need it on psychological grounds.

**Comment by NKONSTANTAKIS** [comment]
In fact I also consider the closing premature anyway, since it is by 90% between +1 and +2 elo and 98% non-regression which is higher than our usual 95%. 
The red LTC test uses different values so it better not be mixed with the successful test.

I regard that the combination of 28K green and 61K yellow LTCs offers a lot of confidence on the positive side, hence justifying a VLTC as a final call without need for a 2nd red STC as indication for superb scaling.

Are there any objections to this? @mcostalba @snicolet @Rocky640

**Comment by Rocky640** [comment]
@NKONSTANTAKIS 
I think you are insisting too much, and you are getting annoying. 

Meanwhile there was a recent patch by @vondele which helped improved the decision about first king move. New PR will have to be tested against latest master.

This is not the first SPRT[0, 5] that barely miss the mark.
Next thing to do is to try to improve it.

**Comment by NKONSTANTAKIS** [comment]
@Rocky640 The @vondele patch had very strong performance STC, barely passed LTC, it does nothing for depth >12 or am I wrong? The proposed test is VLTC.

**Comment by Alayan-stk-2** [comment]
> The red LTC test uses different values so it better not be mixed with the successful test.

No, no. Kurtbusch did a 150K LTC which failed _and_ a 3rd 100K LTC which was red by a mere 4 games. I only mixed the second of those with the previous results.

That said, I do agree that it is still highly likely to be a small elo-gainer, and considering the huge amount of games already sunk into it, I'd really like to see a VLTC. The fundamental idea behind the 8x8 PSQT make complete sense.

**Comment by NKONSTANTAKIS** [comment]
Thanks, I was not aware of 3rd red LTC, probably a VLTC was a better choice. Anyway now we can relax easier :)

**Pull request closed without merging**
