### PR TITLE
Fix Makefile for compilation with Clang on Windows w/ MSYS2

### LINKED ISSUE #3872: Build problems on Windows with MSYS2 and Clang
I have encountered two build problems using Windows 10, MSYS2 and Clang 13 trying to build current HEAD of Stockfish. (Compiling with GCC 11.2 works fine, though)

1) Linkage fails due to use of -latomic
2) When I work around this problem (either by changing the Makefile, or by additionally specifying "RTLIB=compiler-rt"), the build succeeds, but the resulting binary cannot run outside of MSYS/Clang env because it is NOT statically linked. It gives the error message, that it can't find libc++.dll

More details:

1.

```
Peter@bolide CLANG64 ~/repos/official-stockfish/Stockfish/src
$ uname -s
MINGW64_NT-10.0-19043

Peter@bolide CLANG64 ~/repos/official-stockfish/Stockfish/src
$ uname -o
Msys

Peter@bolide CLANG64 ~/repos/official-stockfish/Stockfish/src
$ clang++ --version
clang version 13.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clang64/bin

Peter@bolide CLANG64 ~/repos/official-stockfish/Stockfish/src
$ make -j profile-build ARCH=x86-64-modern COMP=clang
Default net: nn-ac07bd334b62.nnue
Already available.

Config:
debug: 'no'
sanitize: 'none'
optimize: 'yes'
arch: 'x86_64'
bits: '64'
kernel: 'MINGW64_NT-10.0-19043'
os: 'Windows_NT'
prefetch: 'yes'
popcnt: 'yes'
pext: 'no'
sse: 'yes'
mmx: 'no'
sse2: 'yes'
ssse3: 'yes'
sse41: 'yes'
avx2: 'no'
avxvnni: 'no'
avx512: 'no'
vnni256: 'no'
vnni512: 'no'
neon: 'no'
arm_version: '0'

Flags:
CXX: clang++
CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -fuse-ld=lld
LDFLAGS:  -latomic -m64 -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -fuse-ld=lld

Testing config sanity. If this fails, try 'make help' ...


Step 1/4. Building instrumented executable ...
make ARCH=x86-64-modern COMP=clang clang-profile-make
make[1]: Entering directory '/home/Peter/repos/official-stockfish/Stockfish/src'
make ARCH=x86-64-modern COMP=clang \
EXTRACXXFLAGS='-fprofile-instr-generate ' \
EXTRALDFLAGS=' -fprofile-instr-generate' \
all
make[2]: Entering directory '/home/Peter/repos/official-stockfish/Stockfish/src'
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -fuse-ld=lld   -c -o benchmark.o benchmark.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -fuse-ld=lld   -c -o bitbase.o bitbase.cpp
.
.
.
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -fuse-ld=lld   -c -o evaluate_nnue.o nnue/evaluate_nnue.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -fuse-ld=lld   -c -o half_ka_v2_hm.o nnue/features/half_ka_v2_hm.cpp
clang++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o tune.o tbprobe.o evaluate_nnue.o half_ka_v2_hm.o -fprofile-instr-generate -latomic -m64 -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -fuse-ld=lld
lld: error: unable to find library -latomic
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:913: stockfish] Error 1
make[2]: Leaving directory '/home/Peter/repos/official-stockfish/Stockfish/src'
make[1]: *** [Makefile:916: clang-profile-make] Error 2
make[1]: Leaving directory '/home/Peter/repos/official-stockfish/Stockfish/src'
make: *** [Makefile:786: profile-build] Error 2
```

After reading through the LLVM/Clang docs at [https://clang.llvm.org/docs/Toolchain.html#compiler-runtime](https://clang.llvm.org/docs/Toolchain.html#compiler-runtime) and reviewing the Makefile, I additionally specified RTLIB=compiler-rt (leading to not adding "-latomic" to the LDFLAGS) and then the build succeeds. In the CLANG64 env in MSYS2, libatomic.a is not available. It is only installed in the MINGW64 env with the GNU toolchain and GCC.
Is this supposed to work this way? Then I think, at least it should be documented in the build instructions for Windows. What also confused me is that the RTLIB variable is not used anymore in the Makefile beyond that. I.e. it is not passed "-DLIBCXX_USE_COMPILER_RT=YES" to the compiler, as the LLVM Clang docs state. Or is this the default anyway? Sorry if this question is dumb - I'm not a C or C++ dev...

2.

I make with 

```
Peter@bolide CLANG64 ~/repos/official-stockfish/Stockfish/src
$ make -j profile-build ARCH=x86-64-modern COMP=clang RTLIB=compiler-rt
```

and the build succeeds, however the binary only runs in the CLANG64 env, due to not linking -static:

```
.
.
.
clang++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o tune.o tbprobe.o evaluate_nnue.o half_ka_v2_hm.o -fprofile-use  -m64 -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-instr-use=stockfish.profdata -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -fuse-ld=lld
make[2]: Leaving directory '/home/Peter/repos/official-stockfish/Stockfish/src'
make[1]: Leaving directory '/home/Peter/repos/official-stockfish/Stockfish/src'

Step 4/4. Deleting profile data ...
make ARCH=x86-64-modern COMP=clang profileclean
make[1]: Entering directory '/home/Peter/repos/official-stockfish/Stockfish/src'
make[1]: Leaving directory '/home/Peter/repos/official-stockfish/Stockfish/src'

Peter@bolide CLANG64 ~/repos/official-stockfish/Stockfish/src
$ ldd stockfish.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fff95410000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fff93550000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fff92f20000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fff92df0000)
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7fff948b0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fff94a70000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7fff934b0000)
        libwinpthread-1.dll => /clang64/bin/libwinpthread-1.dll (0x7fff82230000)
        libc++.dll => /clang64/bin/libc++.dll (0x7fff6b4b0000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fff94b90000)
        libunwind.dll => /clang64/bin/libunwind.dll (0x7fff82220000)

Peter@bolide CLANG64 ~/repos/official-stockfish/Stockfish/src
```

When e.g. I try to run the binary from a new CMD.exe command prompt, it displays this error message:

grafik

I think on Windows, it needs to be statically linked. When I add these lines to the Makefile in the Clang section, the built executable works fine:

```
Peter@bolide CLANG64 ~/repos/pschneider1968/Stockfish/src
$ git diff
diff --git a/src/Makefile b/src/Makefile
index f00df79f..09be46ac 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -420,6 +420,11 @@ ifeq ($(COMP),clang)
                CXXFLAGS += -m$(bits)
                LDFLAGS += -m$(bits)
        endif
+
+       ifeq ($(findstring MINGW,$(KERNEL)),MINGW)
+               LDFLAGS += -static
+       endif
+
 endif

 ifeq ($(KERNEL),Darwin)
```

```
.
.
.
Step 4/4. Deleting profile data ...
make ARCH=x86-64-modern COMP=clang profileclean
make[1]: Entering directory '/home/Peter/repos/pschneider1968/Stockfish/src'
make[1]: Leaving directory '/home/Peter/repos/pschneider1968/Stockfish/src'

Peter@bolide CLANG64 ~/repos/pschneider1968/Stockfish/src
$ ldd stockfish.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fff95410000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fff93550000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fff92f20000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fff92df0000)
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7fff948b0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fff94a70000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7fff934b0000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fff94b90000)

Peter@bolide CLANG64 ~/repos/pschneider1968/Stockfish/src
$

```
grafik

### PR DESCRIPTION
**Pull request by pschneider1968**
Fixes #3872

### CODE REVIEW

**Comment by vondele** [comment]
can somebody check that this is the right solution to use clang under msys2 ? I'm somewhat surprised this is needed?

**Comment by pschneider1968** [comment]
Maybe it would be a good idea to add a Windows/MSYS2/Clang build test to the CI checks to catch this kind of issues.

**Comment by vondele** [comment]
a PR for such an extension would be welcome :-)

**Comment by pschneider1968** [comment]
Ok, give me some time, I'll try to figure out how to this. Did I mention I'm not a C/C++ developer?  ;-)
But I'm trying to learn new stuff during the pandemic... So please bear with me ;-)

**Comment by ppigazzini** [comment]
I confirm that msys2 clang requires these changes. I suggest to add this too:
```diff
diff --git a/src/Makefile b/src/Makefile
index 406f029f..0e889888 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -404,12 +404,14 @@ ifeq ($(COMP),clang)
        ifneq ($(KERNEL),Darwin)
        ifneq ($(KERNEL),OpenBSD)
        ifneq ($(KERNEL),FreeBSD)
+       ifneq ($(findstring MINGW,$(KERNEL)),MINGW)
        ifneq ($(RTLIB),compiler-rt)
                LDFLAGS += -latomic
        endif
        endif
        endif
        endif
+       endif
```

**Comment by pschneider1968** [comment]
Yes, that makes sense to me, as it saves you from specifying RTLIB=compiler-rt on M_SYS2/Clang. Should I add this on top of my change and send a new pull request?

BTW, on which platforms which require atomics constructs by a library implementation (instead of relying on native atomic intrinsics in silicon) does it make sense anyway to build with Clang and NOT want to use the LLVM compiler-rt but instead use the GNU libatomic ? This looks kind of strange to me...

**Comment by ppigazzini** [comment]
IMO if the suggestion has no contraindications you can add a commit and then squash the commits, here are the cli instructions:
```
git checkout master
# edit the new changes
git commit -a -m "Drop lib atomic"
git fetch -p upstream
# rebase against the GitHUb upstream master because you are using the local master branch for the PR
git rebase -i upstream/master
# this open an editor, change the second "pick" to "squash" and save
# in the next editor write the final commit message and save
# force push local master to your GitHub origin upstream, this will update this PR
git push -f origin master
```

I view that you opened a PR with your master, for the next PR better to create a new branch:
```
git checkout master
git fetch -p upstream
git fetch -p origin
git reset --hard upstream/master
git push origin master

git checkout -b branch_for_the_new_pr

# edit the changes for the fisrt commit
git commit -a -m "first commit"
# edit the changes for the second commit
git commit -a -m "second commit"
# edit the changes for the third commit
git commit -a -m "third commit"
# squash the commits after a proper test and before the merge
git rebase -i master
# this open an editor, change all the "pick" to "squash" but the first one and save
# in the next editor write the final commit message and save
# force push the branch on your GitHub upstream
git push -f origin branch_for_the_new_pr
```

**Comment by pschneider1968** [comment]
> IMO if the suggestion has no contraindications you can add a commit and then squash the commits, here are the cli instructions:

I tested it, and it works fine.

> ```
> git checkout master
> # edit the new changes
> git commit -a -m "Drop lib atomic"
> git fetch -p upstream
> # rebase against the GitHUb upstream master because you are using the local master branch for the PR
> git rebase -i upstream/master
> # this open an editor, change the second "pick" to "squash" and save
> # in the next editor write the final commit message and save
> # force push local master to your GitHub origin upstream, this will update this PR
> git push -f origin master
> ```
> 
> I view that you opened a PR with your master, for the next PR better to create a new branch:

Thanks for your help, much appreciated! I will do this in the future, in case I find something to contribute again!

**Comment by pschneider1968** [comment]
I added your suggestion on top of my change, and amended/rebased my commit. Please review my PR, thanks!

**Comment by ppigazzini** [comment]
msys2 clang builds successfully Stockfish with this PR, here si the speedup for `bench 16 1 20 default depth nnue` :
```
$ bash bench_parallel.sh ./stockfish-mingw.exe ./stockfish-clang.exe 20 10
run   sf_base   sf_test      diff
  1   1005611   1050819    +45208
  2   1014681   1067714    +53033
  3   1020283   1074497    +54214
  4   1014037   1065570    +51533
  5   1023647   1074314    +50667
  6   1021549   1071163    +49614
  7   1018237   1069141    +50904
  8   1018237   1069254    +51017
  9   1027499   1078105    +50606
 10   1020302   1073765    +53463

sf_base =  1018408 +/- 3718
sf_test =  1069434 +/- 4669
diff    =    51025 +/- 1553
speedup = 0.050104
```

**Pull request closed without merging**
