### PR TITLE
Weak queen protection

### PR DESCRIPTION
**Pull request by MJZ1977**
Extra penalty if weak piece is only protected by a queen.

STC:
http://tests.stockfishchess.org/tests/view/5e53c6ab84a82b4acd4148fa
LLR: 2.96 (-2.94,2.94) {-0.50,1.50}
Total: 44630 W: 8615 L: 8359 D: 27656
Ptnml(0-2): 746, 5156, 10323, 5276, 814 

LTC:
http://tests.stockfishchess.org/tests/view/5e54e05d84a82b4acd414947
LLR: 2.94 (-2.94,2.94) {0.25,1.75}
Total: 175480 W: 23085 L: 22409 D: 129986
Ptnml(0-2): 1264, 16494, 51678, 16910, 1394 

Bench: 4923286

### CODE REVIEW

**Comment by vondele** [comment]
Thanks!

**Comment by Vizvezdenec** [comment]
I propose to make a regression test now :)

**Comment by vondele** [comment]
would be fine with me.

**Comment by Vizvezdenec** [comment]
@Alayan-stk-2 :)

**Comment by Alayan-stk-2** [comment]
I was thinking the same thing. We didn't have that much patches but there is almost a month since the previous test.

**Pull request closed without merging**
