### PR TITLE
Tweak beta update formula + Tuning

### PR DESCRIPTION
**Pull request by FauziAkram**
Tweak beta update formula : Thanks to @cj5716 for this idea, and if possible, add him as co-author of this PR
Tuning various parameter : manually chosen by @FauziAkram based on the observations derived from the tuning patches:
https://tests.stockfishchess.org/tests/view/65ba41c2c865510db02782d8
https://tests.stockfishchess.org/tests/view/65ba418dc865510db02782ce

Passed STC:
LLR: 2.93 (-2.94,2.94) <0.00,2.00>
Total: 123296 W: 32261 L: 31807 D: 59228
Ptnml(0-2): 515, 14684, 30841, 15048, 560
https://tests.stockfishchess.org/tests/view/65c2a84dc865510db0282484

Passed LTC:
LLR: 2.95 (-2.94,2.94) <0.50,2.50>
Total: 34308 W: 8801 L: 8482 D: 17025
Ptnml(0-2): 21, 3764, 9263, 4087, 19
https://tests.stockfishchess.org/tests/view/65c368e9c865510db02833da

### CODE REVIEW

**Comment by locutus2** [comment]
Congrats, but always as some additional code change is combined with a big tuning a verification should be done that this is not slipped in only of the tuning. So here is the simplification test based on this PR: https://tests.stockfishchess.org/tests/view/65c3f43cc865510db0283ec4

**Comment by Disservin** [comment]
@locutus2 since this came from @cj5716 he already had a passer stc,  
https://tests.stockfishchess.org/tests/view/65b5b490c865510db02731e9 (stc)
https://tests.stockfishchess.org/tests/view/65b6d25ac865510db027464f (ltc). 
Thus your test isn't enough to answer your initial question..
@FauziAkram why did you mix this in? Is there a test without the patch by @cj5716? 
 
If there isn't, please remove it and resubmit the patch minus the beta update vs patch at LTC non regression bounds. Aka locutus test but just as LTC... and please dont mix in random patches into one in the future, unless there proof that these only pass together.

**Comment by FauziAkram** [comment]
Here is the requested test: https://tests.stockfishchess.org/tests/view/65c668a1c865510db0286b92

So If I understand correctly, if this test fails, we will merge the patch as it is.
If this test passes, we will merge only the tuning part without the beta update, correct?

**Comment by FauziAkram** [comment]
@Disservin the LTC test is taking forever (flactuating between -0.2 to -0.4 Elo), I think that now we have a clear indication that simplifying the beta update part would not be as easy as one might assume, so can we please proceed in merging the PR?

**Comment by FauziAkram** [comment]
This is outdated now, I will close it, to save time for the maintainer.

**Pull request closed without merging**
