### PR TITLE
Fix Knight Spaces

### PR DESCRIPTION
**Pull request by KassiasGrandiel**
I'm fixing Knight Spaces

### CODE REVIEW

**Comment by mcostalba** [comment]
Thanks for your patch but the original version is conforming to SF coding
style, this one is not.

Please take a look at the others tables definitions and you will see
yourself.

**Comment by KassiasGrandiel** [comment]
Now this should confirm since I fixed the mistake.

**Comment by zamar** [comment]
approved.

**Comment by lucasart** [comment]
the original was fine. i don't see the point of this pull request.

**Comment by zamar** [comment]
Actually the original version is fully in line with the SF's coding style. No need for change.

Thus I'm closing this request.

**Pull request closed without merging**
