### PR TITLE
Pick best2

### PR DESCRIPTION
**Pull request by Hexik**
Second attempt to speedup the MovePicker::pick_best(), now with better evidence of speedup.
Superfluous assignment in std::swap() is omitted

Points: 36207.5/72234
Elo gain: +0.87
Speedup : 1.45% assuming +60 Elo by 100% speedup

http://tests.stockfishchess.org/tests/view/57ff949c0ebc5910626b941c

LLR: -2.97 (-2.94,2.94) [0.00,5.00]
Total: 72234 W: 13085 L: 12904 D: 46245

### CODE REVIEW

**Comment by mcostalba** [comment]
Sorry but you can't stretch statistics to your own. Spsa test failed. It is
not sound to deduce elo from that result.

**Comment by Hexik** [comment]
Hi @mcostalba ,
this was STC: SPRT(0, 5) test. I did not expect to finish it in green. I made speedup measurments on my computers I expected gain around 1 elo. 

So I run the test to collect game results, my idea was that I can calculate/confirm estimated elo +/- from earned points.

I still believe (maybe I am only stubborn ;-) that this commit is healthy and valid. It does less work, runs quicker, cfish uses something similar. Please give me a advice how to make evidence of it, which kind of test is suitable for this task.

**Comment by syzygy1** [comment]
I think the main question is: does Stockfish want to be an efficient program or just a "beautiful" program?

If the answer is "just a beautiful program", then people can stop wasting their time trying to speed up the program.

If efficiency is considered to be important at all, then why not test simple changes like this as a reverse simplification: [-1,3]. If it passes, the speedup is real and a slight uglification is worth it. If it does not pass, then its removal would pass a simplfication test so it is not worth applying it.

If [0,5] for all alleged speed ups is the final word, then so be it. People looking for speed ups can then look for other projects to spend their time on.

Note that I am talking about simple non-functional changes (but that do add bytes of code).

**Comment by Hexik** [comment]
@syzygy1 It depends how you define beauty vs. ugly. Is beautiful code good looking printed on the paper vs. the code squeezing out the last CPU cycle? 

For example just above pick_best() is function insertion_sort(). Its implementation can be called as optically ugly, especially if you take into account, that the same functionality can be achieved by simple call to std::sort/std::stable_sort. From another point of view is insertion_sort() beautiful, its performance is nearly unbeatable...

If I return back to this small patch, it's worth call it ugly when correcting apparently not 100% optimal code ;-)

**Comment by syzygy1** [comment]
@Hexik 
Yes it is subjective, but in this case it is clear what Marco thinks is more beautiful.

I am pretty sure he would also prefer using std::sort over insertion_sort (and btw I don't see why it would need to be stable... std::partition is not stable either). But using std::sort would impact performance quite a lot. It would quite likely not pass a [-3,1] simplification test.

So there we are: a 13-line "chunk of old-style C code that has completely another readability level" (not my words) remains in Stockfish only because removing it would not pass a [-3,1] simplifciation test.

Is the presence of that chunk of old-style insertion_sort() C code a problem? Not at all. Someone needing to sort something does not need to look at the implementation.

Why not have the same test for small, local improvements? Why impose the [0,5] test for non-functional **speed** improvements that a small but real speedup will never pass? Real speedups (as opposed to arbitrary reordering that just happen to trigger compiler luck on someone's local machine) are real Elo improvements, even if small.

Anyway, I am starting to doubt that contributions other than 3-line search or evaluation tweaks are appreciated at all nowadays.

**Comment by mcostalba** [comment]
@Hexik the SPRT test failed and I am going to close this one.

The rationale of SPRT[0, 5] for these kind of patches is that any patch that adds complexity / logic / code /<you name it> should prove to be worth it, so a functional changing patch should pass SPRT[0, 5] at both STC and LTC.

Speed optimizations in my view are exactly the same, with the only difference that, because they cannot regress at long TC, then LTC pass is not needed. Note that this already gives an advantage to optimization patches compared to standard ones because it is statistically easier to pass a single SPRT[0, 5] than a double SPRT[0, 5].

So the bad news (for you) is that I consider SPRT[0, 5] the proper test for optimizations that are not a simplification and I will enforce this rule during my maintenance period. 

The good news is my maintenance period ends on November 1th, according to our 6 months rotating policy, and SF maintenance will return to Joona. Eventually feel free to discuss with him about changing policy for optimization patches (I hope he will not, but of course starting with November and for the following 6 months will be up to him).

@syzygy1 personally I prefer "beautiful" to **non-measurable/insignificant** efficiency. I think this is a long term success point (there are a lot of _efficient_ open sources engines out there, but very few people willing to dive into all that _efficiency_). Regarding insertion sort, it is is like this because it is (measurably) faster than any std::sort, even the unstable one. This is due because std::sort is designed to be general purpose, instead in our case (short vectors of moves), a cache-friendly algorithm like insertion-sort is better (btw even many implementations of std::sort use insertion-sort when remaining list is very short).

**Comment by syzygy1** [comment]
@mcostalba
I don't take issue with preferring beautiful over non-measurable speedup. I just think [0,5] is too much to ask for this type of improvement. If the change somehow made it more difficult to use pick_best() it would be different, but here we're talking about a small localized change. But I will stop repeating myself.

I wasn't aware of the rotating maintenance policy. But I'd hope testing guidelines are discussed and agreed upon by the maintainers together.

**Comment by Hexik** [comment]
@mcostalba 
I agree with you, application should be kept clean and consistent. I do not agree at which level it should be enforced. If you will comply with consistency at level of classes and functions interfaces, it is OK. In the single line level it is a little bit strict.

Basically you have 2 ways how to improve the performance

**Group 1 Speedup in computational sense**
If there is a pure speedup patch - non functional (same node count, bestmove, evaluation), passing the SPRT[0,5] is nearly mission impossible for simple local patch. SF is really mature project I am not sure if there are such places in the code. You need aprox 1.6 elo or 2.5% speedup. 

I am still not convinced, that SPRT[0,5] is the right selection filter, you know that it is non functional change, all you need is to compare the raw speed in terms of nps.
For this situation it will be better to run some set of representative benchmarks on different machines/OS/CPU/toolchains. If you got measurable speedup on majority of runs, you can approve the patch. This way you can catch lot of small speedups which added together can give significant elo boost. 

Two or more of small local speedup are orthogonal, so you can cumulate the gain without the worry they cancel each other. The same holds if you combine speedups with single patch from group 2. 

**Group 2 Formula, parameter tweaking**   
You can go from engineering way up to Darwinism x voodoo way, so here is the STC, LTC barrier full in place

Here can be a catch, two or more patches of these group can be correlated in both ways, positive or negative.

Darwinism in my perception is not negative word on the contrary, applied in the right way can lead to good/excellent results. You can tune the big parameters set together to overcome correlation issues. 

You need patches from both group to push performance as high as possible, now is group 1 actually cut off from the opportunity to improve performance 

I apologize for the long post, I wrote more than I originally intended

@syzygy1 
Thanks for your support :-)

**Comment by mstembera** [comment]
I think everyone agrees w/ Marco that code quality has to be kept at a high level for the overall good of the project in the long run.  We should also respect that it is especially important for the maintainers who have the difficult job of maintaining everything.

That said I do agree w/ others here who posted that [0,5] is simply too much to expect from a simple speed optimization.  Some optimizations are complex and in those cases [0,5] is appropriate.  But something like a 1 line addition for a 0.5% speedup or a 3 line addition for a 1% speed up seems reasonable.  Many small speed patches add up and they are guaranteed not to be regressions.  Obviously not all lines are the same and counting some cryptic expression the same as a simple { is why all patches are reviewed individually and the maintainers always have final veto power.  

I had this https://github.com/official-stockfish/Stockfish/pull/832 pull request closed with the comment that there is "no measurable speed difference" when the p-value was 0.994 saying the opposite.  On the other hand Marco thought the new code was less clear which is something I have to respect from him as a maintainer so for that reason I have no problem w/ the closing.

Finally while speed testing is not 100% noise free it is still much more precise than fishtest error bars especially when verified independently.  Also we should not waste fishtest resources on things that can be measured more precisely and cheaply just because those resources seem "free" to us.  Personally I'm not too happy donating cpu time for non functional speedup patches.

**Comment by atumanian** [comment]
> We should also respect that it is especially important for the maintainers who have the difficult job of maintaining everything.
If this the problem, we can have multiple maintainers who are responsible for their component of the program. No one needs to know all the program code to work on it.

**Pull request closed without merging**
