### PR TITLE
Rook PSQT Tuned

### PR DESCRIPTION
**Pull request by SFisGOD**
This patch uses about half the changes of the SPSA tuning run:
http://tests.stockfishchess.org/tests/view/5dba93d30ebc5925b64ed3bf

About a month ago, xoto10's patch raised the mg value of the third rank center files from -1 to 7 to encourage rook lifts to the third rank. About three days later, Rocky's patch lowered this value from 7 to 3. This patch raises that again from 3 to 12 and ends up greater than the original rook lift patch.

Passed STC:
LLR: 2.95 (-2.94,2.94) [-1.50,4.50]
Total: 104094 W: 22573 L: 22161 D: 59360
http://tests.stockfishchess.org/tests/view/5dbc77f20ebc5925b64ef1d0

Passed LTC:
LLR: 2.96 (-2.94,2.94) [0.00,3.50]
Total: 168291 W: 27410 L: 26777 D: 114104
http://tests.stockfishchess.org/tests/view/5dbd9f1e0ebc5925b64f0647

Bench: 4693620

### CODE REVIEW

**Comment by snicolet** [comment]
Merged via 3804effb341b3008326a1613923177eb83d02826, congrats! :-)

Not that if we wanted to be 100% rigorous, then we could say that this patch was tested against quite an old version of master which didn't include the other PSQT changes of 474d133565564146ec28878afca54739cc4e22d2 for the other pieces, and there *might* be some interactions between the PSQT tables. 

If you feel like it, you can check this version (Rook PSQT Tuned) against the very previous master (Remove shuffle extension ) with [-3..1] bounds at LTC.

**Comment by SFisGOD** [comment]
Link to the test 
http://tests.stockfishchess.org/tests/view/5dc0ba1d0ebc5904493b0112

**Comment by ssj100** [comment]
> Link to the test
> http://tests.stockfishchess.org/tests/view/5dc0ba1d0ebc5904493b0112

Thanks for doing the test.  It failed.  Does that mean a revert is necessary?

**Comment by 31m059** [comment]
@snicolet Given that the LTC [-3, 1] failed, (unfortunately) we may need to revert this commit...

**Comment by SFisGOD** [comment]
@snicolet 
LLR: -2.96 (-2.94,2.94) [-3.00,1.00]
Total: 95536 W: 15047 L: 15347 D: 65142
http://tests.stockfishchess.org/tests/view/5dc0ba1d0ebc5904493b0112

It failed non-regression.
Please revert thanks.

**Comment by snicolet** [comment]
Patch reverted via 9f312c80d918c6f669dcf83df3d4332e02bfa1d9

Sorry about it, I think I know how you feel about it and how hard it is to improve Stockfish these days...

**Pull request closed without merging**
