### PR TITLE
Separate contempt for white and black

### PR DESCRIPTION
**Pull request by ChessMan3**
The main idea of ​​this patch is to use different values ​​of contempt depending on what color we play.
For example, we can set contempt 30 for the game with white color and contempt 10 if we have black. When playing black we should not be as aggressive as if we were playing white.

No functional change

### CODE REVIEW

**Comment by ChessMan3** [comment]
Some tests:

2x Intel® Xeon® Processor E5645 (12M Cache, 2.40 GHz)

Games Completed = 31230 of 40000 (Avg game length = 33.183 sec)
Settings = RR/32MB/Book/10000ms+100ms/M 1000cp for 12 moves, D 120 moves/
Time = 44532 sec elapsed, 12506 sec remaining
 1.  Contempt_0_0             	7864.5/15616	2548-2435-10633  	(L: m=448 t=0 i=0 a=1987)	(D: r=7354 i=1473 f=314 s=78 a=1414)	(tpm=226.5 d=16.50 nps=901780)
 2.  Contempt_20_20           	7897.0/15616	3033-2855-9728  	(L: m=604 t=0 i=0 a=2251)	(D: r=6898 i=1351 f=213 s=102 a=1164)	(tpm=225.5 d=16.31 nps=902761)
 3.  Contempt_20_15           	8754.0/15614	4092-2198-9324  	(L: m=484 t=0 i=0 a=1714)	(D: r=6707 i=1223 f=205 s=74 a=1115)	(tpm=225.3 d=16.32 nps=899590)
 4.  Contempt_20_-15          	6714.5/15614	1673-3858-10083  	(L: m=872 t=0 i=0 a=2986)	(D: r=7521 i=1177 f=230 s=86 a=1069)	(tpm=230.2 d=16.32 nps=895844)

===================
 Program                          Elo    +   -   Games   Score   Av.Op.  Draws

  1 Contempt_20_15                 : 3332    3   3 15614    56.1 %   3289   59.7 %
  2 Contempt_20_20                 : 3303    3   3 15616    50.6 %   3299   62.3 %
  3 Contempt_0_0                   : 3302    3   3 15616    50.4 %   3299   68.1 %
  4 Contempt_20_-15                : 3263    3   3 15614    43.0 %   3312   64.6 %
==============
Individual statistics:

1 Contempt_20_15            : 3332  15614 (+4092,=9324,-2198), 56.1 %

Contempt_0_0                  : 5205 (+972,=3457,-776), 51.9 %
Contempt_20_-15               : 5204 (+1736,=2954,-514), 61.7 %
Contempt_20_20                : 5205 (+1384,=2913,-908), 54.6 %

2 Contempt_20_20            : 3303  15616 (+3033,=9728,-2855), 50.6 %

Contempt_0_0                  : 5206 (+873,=3431,-902), 49.7 %
Contempt_20_15                : 5205 (+908,=2913,-1384), 45.4 %
Contempt_20_-15               : 5205 (+1252,=3384,-569), 56.6 %

3 Contempt_0_0              : 3302  15616 (+2548,=10633,-2435), 50.4 %

Contempt_20_15                : 5205 (+776,=3457,-972), 48.1 %
Contempt_20_-15               : 5205 (+870,=3745,-590), 52.7 %
Contempt_20_20                : 5206 (+902,=3431,-873), 50.3 %

4 Contempt_20_-15           : 3263  15614 (+1673,=10083,-3858), 43.0 %

Contempt_0_0                  : 5205 (+590,=3745,-870), 47.3 %
Contempt_20_15                : 5204 (+514,=2954,-1736), 38.3 %
Contempt_20_20                : 5205 (+569,=3384,-1252), 43.4 %

======================
Games        :  31230 (finished)

White Wins   :   4958 (15.9 %)
Black Wins   :   6388 (20.5 %)
Draws        :  19884 (63.7 %)
Unfinished   :      0

White Perf.  : 47.7 %
Black Perf.  : 52.3 %

=============
In my opinion contempt 20/10 or 25/10 could be even better

**Comment by AlexandreMasta** [comment]
In fact this makes total sense.

**Comment by snicolet** [comment]
I like the fact that this patch covers, with a very natural way, all the scenarii discussed in the last couple of days (https://github.com/official-stockfish/Stockfish/pull/1376). 
Let **x** = contempt for White and **y** = contempt for Black. As NKONSTANTAKIS said:

> Everything is useful for the chess player:
> • If he needs to prepare for a win with White he would benefit from contempt to White. 
       Set (x,y)=(20, -20), scenario A.
> • If he needs to win with Black he would like to use it for Black. 
       Set (x,y)=(-20, 20), scenario B.
> • Contempt for both sides would be best for exploring the active possibilities of each side. 
       Set (x,y)=(20,20), scenario C.
> • No contempt would be useful for neutral evaluation. 
       Set (x,y)=(0,0), scenario D.

All this can be easily explained in the commit message and the release notes. We can even think about better names like replacing "Contempt for White (for Black)" by one of the following propositions, to be more explicit for the average chess player:
• "Draw Avoidance for White (for Black)"
• "Active style for White (for Black)"
• "Dynamism for White (for Black)"

If, moreover, we manage to get different hash paths for the searches with root-as-White and root-as-Black _when x is not the opposite of y_, then it seems we would also cover all the technical concerns. In scenario A,B and D the hash table is coherent and stores the search tree only once. In scenario C, the hash table is coherent and stores two independent search trees (but will get filled at 100% with the search if the user decides to start a long think in one position, of course).

**Comment by syzygy1** [comment]
The problem remains that switching from game play to analysis requires the user to change the settings. Normal settings would be +20 contempt for both sides. When analysing, if the user wants contempt at all(!!!), he would have to switch to +20/-20 (or -20/+20 if black needs contempt).

Btw, for gameplay it seems to me that contempt is more important for black than for white. White will normally anyway have an advantage early in the game, so runs little risk of going for a draw when playing a weaker opponent. The real gain comes from avoiding draws as black.

**Comment by AlexandreMasta** [comment]
@syzygy I disagree. What makes contempt good is the fact that you have a prior advantage. In one hand/case you have the assumption that the engine is better than the opposition (engine1 vs engine2). So the better engine should have a positive contempt to avoid draws since the assumption is that it plays better. In the other hand/case you have an advantage of colors. This is a game advantage. White has the advantage in the game. This is well known and all statistics prove that. So white should have a higher contempt than black.

Contempt always helps the stronger side. As Black starts in disadvantage is ok to have a lower contempt.

**Comment by Maratka2** [comment]
Hi!

I think that we need to understand whether we are playing according to the book, or by random positions (like 2_moves test database).
When we play by a good book (like TCEC), whites always get an advantage. When we play at a random position, half the time Black will have an advantage.

For this reason, one must understand:
1) How do we plan to test it?
2) How are we going to use this new feature?

I am sure that the maximum benefit from this patch will be in "game mode", when two equal engines play each other (for example StockFish vs. Komodo) in the TCEC final.
For example, we set +20 for white, and 0 (or negative) for Black, and win many games with white, having a many draw in black.

But if we begin to test this new function on the 2_moves database, the advantage will not be noticeable.


Sorry for my English.

**Comment by syzygy1** [comment]
Yes, white had the advantage. SF does not need contempt to see that. That's the point.

**Comment by vdbergh** [comment]
@syzygy1 Correct! Contempt expresses an advantage/disadvantage which cannot be deduced from the position. For example this should also apply for if you are ahead or behind in time. Long ago a patch of this type passed but it may have been a lucky run. Probably there is not much to be gained in self play from this idea as the two engines will use the same time management.

**Comment by snicolet** [comment]
I have implemented the "use distinct hash paths for root-as-White and root-as-Black" idea in this branch:

https://github.com/snicolet/Stockfish/commits/Separate_contempt
https://github.com/snicolet/Stockfish/compare/master...Separate_contempt

Hope this helps,
Stéphane

**Comment by AlexandreMasta** [comment]
Just your logic seems backward...because the correct one is "the more advantage (deduced or not from the position e.g. the engine is better) you have the more contempt you can get".

**Comment by syzygy1** [comment]
It seems backward to you... can't help that.

**Comment by syzygy1** [comment]
Contempt is just increasing all scores by a value that scales down with the gamePhase. It does not have a psychological effect on the engine's mind or anything like, which is what a lot of people seem to think.

The question is what is the effect of increasing those scores. If you increase all scores by the same amount, there is no effect at all. In particular if the score is positive anyway, because then draw scores (which remain 0.00) don't play a role.

Since contempt is scaled down with gamePhase, there is an effect. The effect is that SF when having an advantage as white and playing with contempt will be more reluctant to trade pieces. That is against the rule that if you're ahead you should trade pieces. And remember that Stockfish evaluation has been carefully tuned to an optimum... contempt is disturbing that optimum.

The reason contempt helps against weak opponents is that, when behind, it is good for Stockfish to be more reluctant to trade pieces (delaying the game and giving the opponent more time to blunder) and it is good for Stockfish to avoid draw by repetition. Neither is applicable if Stockfish is ahead anyway.

**Comment by atumanian** [comment]
@syzygy1 is absolutely right. It's also important to add that the contempt isn't intended to make the engine stronger against a player of the same strength. On the contrary, it should theoretically make it weaker. There have been claims that the contempt makes the engine stronger, but it still need to be verified. Passing the [-3, 1] test doesn't yet mean it's not a regression.

**Comment by AlexandreMasta** [comment]
In fact the rule is not like this. When under heavy attack the rule is again to trade pieces that are in the attack to undermine the attack. You trade pieces only when that trade will amplify the advantage. This is a rule that has a subtle bias towards the position or what is happening on the board and that´s why you can´t just generalize it and maybe why you are having this idea about contempt. 

Let me be more clear...when you are attacking you don´t want to trade your attacking (or even your heavy pieces) pieces without solving the position in advantage. The less piece you have the less play you have...and this is why contempt works.

**Comment by atumanian** [comment]
@AlexandreMasta, let's put aside the statement about trading pieces when being ahead as a rule. Do you agree with everything else?

**Comment by atumanian** [comment]
I would like to remind that this patch doesn't fix the bug of having different contempt values for white and black in analysis.

**Comment by Mindbreaker1** [comment]
I think it is silly to assume you have advantage just because you have the white pieces.  Better to characterize those advantages that are typical, so you only assume the advantage is there when it is.

**Comment by AlexandreMasta** [comment]
You have the advantage as white just because of a tempo (translated in this case in the possession of initiative)...thought you knew that. BTW is known by a fact (statistics) that white win more than black. 
So yeah...white has an advantage by default.

**Comment by xoto10** [comment]
I have tried some tests to look at the performance of separate contempt values for black/white near to 20. See
http://tests.stockfishchess.org/tests/view/5a7090020ebc590297c36cde (roughly 18 for black, 22 for white)
http://tests.stockfishchess.org/tests/view/5a70ace10ebc590297c36ced (15 for black, 20 for white)
http://tests.stockfishchess.org/tests/view/5a70c2ba0ebc5902972a9648 (tune a symmetrical offset from 20)
http://tests.stockfishchess.org/tests/view/5a7193320ebc590f2c86e9ab (just requested)
As mentioned in the git comments to the first one, it may be that any gains from this mostly come from increasing white contempt from 20 to 21 or 22, masking the effects of the change to the black contempt. If I was doing more tests I would tune separate black/white contempts starting both at 20 to see if they tune differently.

**Comment by atumanian** [comment]
@AlexandreMasta, yes, white has an advantage at the start of the game, but this doesn't apply to all positions occurred later in the game or ones analysed in the search tree. The evaluation function already

**Comment by AlexandreMasta** [comment]
@atumanian sure.

**Comment by ChessMan3** [comment]
@snicolet 
I liked your implementation. Could you start test in framework?

**Pull request closed without merging**
