### PR TITLE
Small cleanups 13

### PR DESCRIPTION
**Pull request by snicolet**
Start with an empty message

No functional change

### CODE REVIEW

**Comment by mstembera** [comment]
Line 1026 in evaluate.cpp
```C++
    int mat = pos.non_pawn_material() + PieceValue[MG][PAWN] * pos.count<PAWN>();
```
is technically incorrect because the PieceValue array should be indexed by Piece not PieceType.
```C++
   int mat = pos.non_pawn_material() + PawnValueMg * pos.count<PAWN>();
```
should fix it.
This also points out that we depend on the Piece enums and the PieceType enums to be in sync.  ```PieceType type_of(Piece pc)``` is a good example of this dependence.  I would therefore propose we also make this
https://github.com/mstembera/Stockfish/commit/afd7bd4ad988a92a212b4c02a93f2b4a8dd9dbb2
change in types.h to guarantee it explicitly.

**Comment by xoto10** [comment]
Indenting:
```
diff --git a/src/evaluate.cpp b/src/evaluate.cpp
index 25e3bdc1e2..a5c5c17f7d 100644
--- a/src/evaluate.cpp
+++ b/src/evaluate.cpp
@@ -1039,10 +1039,10 @@ Value Eval::evaluate(const Position& pos) {
       // For the case of opposite colored bishops, switch to NNUE eval with
       // small probability if the classical eval is less than the threshold.
       if (   largePsq
-          && (abs(v) * 16 < NNUEThreshold2 * r50
-          || (   pos.opposite_bishops()
-              && abs(v) * 16 < (NNUEThreshold1 + pos.non_pawn_material() / 64) * r50
-              && !(pos.this_thread()->nodes & 0xB))))
+          && (   abs(v) * 16 < NNUEThreshold2 * r50
+              || (   pos.opposite_bishops()
+                  && abs(v) * 16 < (NNUEThreshold1 + pos.non_pawn_material() / 64) * r50
+                  && !(pos.this_thread()->nodes & 0xB))))
           v = adjusted_NNUE();
   }
 
```

**Comment by mstembera** [comment]
Currently we free and reallocate the TT each  time TranspositionTable::resize() is called even if the size remains the same.  As an example this happens 3 times when just running bench.
https://github.com/mstembera/Stockfish/commit/48cd4545865a4aa80e2d21d8529aa80a8f768846

**Comment by unaiic** [comment]
Line 590 in misc.cpp: `string separator;` is not used.

Lines 223 and 259: `return select<Next>([](){ return true; });` is repeated twice.

```
diff --git a/src/misc.cpp b/src/misc.cpp
index a16a6e90a3..f30519902d 100644
--- a/src/misc.cpp
+++ b/src/misc.cpp
@@ -587,7 +587,6 @@ string pathSeparator;    // Separator for our current OS
 
 void init(int argc, char* argv[]) {
     (void)argc;
-    string separator;
 
     // extract the path+name of the executable binary
     argv0 = argv[0];
diff --git a/src/movepick.cpp b/src/movepick.cpp
index 153d323e8b..bbd0fb16a7 100644
--- a/src/movepick.cpp
+++ b/src/movepick.cpp
@@ -220,6 +220,7 @@ Move MovePicker::next_move(bool skipQuiets) {
       [[fallthrough]];
 
   case BAD_CAPTURE:
+  case QCHECK:
       return select<Next>([](){ return true; });
 
   case EVASION_INIT:
@@ -254,9 +255,6 @@ Move MovePicker::next_move(bool skipQuiets) {
 
       ++stage;
       [[fallthrough]];
-
-  case QCHECK:
-      return select<Next>([](){ return true; });
   }
 
   assert(false);
```

**Comment by GoldenRare** [comment]
A few potential small changes:

Changing lines 852-853 of evaluate.cpp:
```
bool pawnsOnBothFlanks =   (pos.pieces(PAWN) & QueenSide)
                        && (pos.pieces(PAWN) & KingSide);
```
to
```
bool pawnsOnBothFlanks =   pos.pieces(PAWN) & QueenSide
                        && pos.pieces(PAWN) & KingSide;
```
since the parenthesis are unnecessary. Similarly, lines 1148-1149 of position.cpp:
```
attackers |=  (attacks_bb<BISHOP>(to, occupied) & pieces(BISHOP, QUEEN))
            | (attacks_bb<ROOK  >(to, occupied) & pieces(ROOK  , QUEEN));
```
can be changed to 
```
attackers |=  attacks_bb<BISHOP>(to, occupied) & pieces(BISHOP, QUEEN)
            | attacks_bb<ROOK  >(to, occupied) & pieces(ROOK  , QUEEN);
```
however with this one, during make it seems to suggest the parenthesis despite it not being necessary.
A slightly bigger change can be made to lines 114-118 of endgame.cpp:
```
if (   pos.count<QUEEN>(strongSide)
    || pos.count<ROOK>(strongSide)
    ||(pos.count<BISHOP>(strongSide) && pos.count<KNIGHT>(strongSide))
    || (   (pos.pieces(strongSide, BISHOP) & ~DarkSquares)
        && (pos.pieces(strongSide, BISHOP) &  DarkSquares)))
```
to 
```
if (   pos.count<QUEEN>(strongSide)
    || pos.count<ROOK>(strongSide)
    ||(pos.count<BISHOP>(strongSide) && pos.count<KNIGHT>(strongSide))
    || pos.bishop_pair(strongSide))
```
and adding the declaration `bool bishop_pair(Color c) const;` somewhere in postion.hpp (maybe after line 137) and the definition:
```
inline bool Position::bishop_pair(Color c) const {
  return   pieces(c, BISHOP) & ~DarkSquares 
        && pieces(c, BISHOP) &  DarkSquares;
}
```
somewhere in position.hpp as well (maybe after pawns_on_same_color_squares at line 327). The reasons for this change
being that the concept of the bishop pair is well known in Chess and maybe in the future the explicit check for the bishop pair may be needed again rather than the cheaper check of `pos.count<BISHOP>(/*INSERT COLOR*/) > 1` used in say the imbalance function. 
Lastly, in the AUTHORS file since it's supposed to be in alphabetical order, at lines 65-67:
```
Gian-Carlo Pascutto (gcp)
Deshawn Mohan-Smith (GoldenRare)
Gontran Lemaire (gonlem)
```  
the 'D' got mixed up with the 'G's where it should be placed after line 45.

**Comment by mstembera** [comment]
Line 233 in nnue_feature_transformer.h
```C++
int gain = popcount(pos.pieces()) - 2;
```
can be
```C++
int gain = pos.count<ALL_PIECES>() - 2;
```

**Comment by Lolligerhans** [comment]
`evaluate.cpp:909` Ends with redundant whitespace.

**Comment by Lolligerhans** [comment]
Prabably easier to use `RANK_N` macro instead of integer literal when using ranks in `pawns.cpp::174`.
[Branch](https://github.com/Lolligerhans/Stockfish/tree/cleanup) | [Commit](https://github.com/Lolligerhans/Stockfish/commit/17964b249f0f3cd3dc526fc308ff1eb691d26c05)

**Comment by mstembera** [comment]
Clean up MakeIndex()
https://github.com/mstembera/Stockfish/commit/e9b90a4238c9d5328403ffd0755ee5299d03fb38
The index order in kpp_board_index[][] is reversed to be more optimal for the access pattern but it's not enough to pass as a pure speed up.

**Comment by snicolet** [comment]
> Clean up MakeIndex()  mstembera@e9b90a4  The index order in kpp_board_index[][] is reversed to be more optimal for the access pattern but it's not enough to pass as a pure speed up. I can open a separate PR if that's better.

@mstembera 
That's interesting indeed! Let's do it it in a separate PR, and for me it would be enough to see your patch passing simplification bounds.

**Comment by snicolet** [comment]
I have applied most of the suggestions in 027626db1e449597ba2211a0819f251beda37b88, thanks everybody !

**Comment by mstembera** [comment]
@snicolet No problem.  Normally we don't do tests for non functional simplifications but I will.

Also what about https://github.com/mstembera/Stockfish/commit/48cd4545865a4aa80e2d21d8529aa80a8f768846 from above?

**Comment by snicolet** [comment]
> Also what about mstembera@48cd454 from above?

@mstembera Could you please make a separate PR for 48cd454 too, so that we can discuss the idea / improve on the code and get @vondele feedback?

From a quick glance, I would:
• initialize the old cluster count to -1 somewhere so that the logic is more robust
• use a distinct variable for the new target cluster count

something like:

```
clusterCount = -1;  (somewhere)


[...]

newClusterCount =  mbSize * 1024 * 1024 / sizeof(Cluster);
if (clusterCount != newClusterCount)
   {
       aligned_large_pages_free(table);
       clusterCount = newClusterCount;

       table = static_cast<Cluster*>(aligned_large_pages_alloc(clusterCount * sizeof(Cluster)));

       if (!table)		       
       {
           std::cerr << "Failed to allocate " << mbSize
                          << "MB for transposition table." << std::endl;	
            exit(EXIT_FAILURE);		 
       }
   }	
```

**Comment by vondele** [comment]
one reason to reallocate is when thread count changes but the size remains the same. That should allocate memory on the right to main with first touch policy. At least that's the theory.

**Comment by mstembera** [comment]
Ah ok.  I will leave it alone then.

**Pull request closed without merging**
