### PR TITLE
VVLTC search tune

### PR DESCRIPTION
**Pull request by XInTheDark**
This patch is the result of two tuning stages:
1. ~32k games at 60+0.6 th8: https://tests.stockfishchess.org/tests/view/662d9dea6115ff6764c7f817
2. ~193k games at 80+0.8 th6, based on PR #5211: https://tests.stockfishchess.org/tests/view/663587e273559a8aa857ca00. Based on extensive VVLTC tuning and testing both before and after #5211, it is observed that introduction of new extensions positively affected the search tune results.

Passed VVLTC 70+0.7 th7 1st sprt: https://tests.stockfishchess.org/tests/view/6636c6f04b68b70d85801409
LLR: 2.94 (-2.94,2.94) <0.00,2.00>
Total: 18566 W: 4864 L: 4620 D: 9082
Ptnml(0-2): 0, 1608, 5827, 1844, 4 

Passed VVLTC 70+0.7 th7 2nd sprt: https://tests.stockfishchess.org/tests/view/6636d4b84b68b70d85802ab7
LLR: 2.94 (-2.94,2.94) <0.50,2.50>
Total: 43142 W: 11141 L: 10838 D: 21163
Ptnml(0-2): 4, 3915, 13427, 4224, 1 

Passed VVLTC 70+0.7 3rd sprt: https://tests.stockfishchess.org/tests/view/66376b4f9819650825aa230b
LLR: 2.94 (-2.94,2.94) <0.50,2.50>
Total: 40322 W: 10374 L: 10076 D: 19872
Ptnml(0-2): 1, 3660, 12544, 3952, 4 

The first two sprts were run against passed #5211. The third sprt was run against latest master.

Bench: 2180675

### CODE REVIEW

**Comment by vondele** [comment]
please rebase on master, and test once more. You can use throughput 400.

**Comment by XInTheDark** [comment]
VVLTC has finished, I've updated the PR description and rebased

**Comment by Disservin** [comment]
btw this isnt entirely clean rebased.. ideally it should be squashed and/or all commits should be above the latest one which is in master. The history looks like a merge 

image

**Comment by Disservin** [comment]
Rebased it correctly locally and merged.
I am running this when merging a branch into master locally, `--ff-only` basically ensures that the commit history is linear, which is what we want.  `git merge --ff-only vvltc_search_tune_040524_4`

**Pull request closed without merging**
