### PR TITLE
Improve comments in uci.h

### PR DESCRIPTION
**Pull request by PedanticHacker**
I have touched the comments and made them a little bit more non-robotic.

### CODE REVIEW

**Comment by PedanticHacker** [comment]
I hope these comments are better now. What do you think?

**Comment by dsmsgms** [comment]
You are adding nuances that are not really right or missing the key detail being commented.

New "UCI options must contain key-value pairs", No it is the container that hold key-value pairs. An UCI option is handled just a a key value pair.

The old "Define a custom comparator, because UCI options should be case-insensitive" is actually explanatory rather than the new one.

Better the old declarative "The Option class implements an option as defined by the UCI protocol" than stating a obligation.

The old "Our options container is actually a std::map" is the pertinent observation, you can hold key-value pair by other means.

**Comment by PedanticHacker** [comment]
Maybe we should just remove all the comments in `uci.h`?

**Comment by snicolet** [comment]
> Maybe we should just remove all the comments in ici.h?

No, thanks.

My two cents: I’ve got the feeling that you are about to go through  all the comments in The Stockfish codebase and propose to reword all of them, just because you can. While this is a perfectly fine thing to do in a specific branch of your fork for your personal pleasure, it is probably counter-productive to do this in official-stockfish, as it takes lots of energy from the maintainers and the other developers to review your changes (and correct your English sometimes, btw).

Better would be to  focus on the (hopefully very few) comments that are technically false, and propose minimal changes.

Note also that other parts of the project could  benefit more from a documentation effort, for instance there was a proposal a couple of days ago to write a wiki page with UCI examples for stockfish :-)

Stéphane

**Comment by PedanticHacker** [comment]
@snicolet, you are right.

So, I have brought the comments back and I think they now should be okay. Yes?

**Pull request closed without merging**
