### PR TITLE
Pull

### PR DESCRIPTION
**Pull request by lucasart**
for syzygy

### CODE REVIEW

**Comment by mcostalba** [comment]
@lucasart I have all my scripts based on a fixed bench number. I'd ask if possible to pelase avoid syncying with master, there is really no need for this and only complicates the tree. If you agree we will sync back once is finished (or if a major bug in master is fixed). I will pull the other 3 commits.

**Comment by mcostalba** [comment]
Pulled.

**Comment by lucasart** [comment]
@mcostalba: I wanted to sync, because non trivial merge conflicts started to arise, and because functional changes were committed to master. I like to be able to compare with master for correctness and speed.

**Comment by mcostalba** [comment]
OK, I will sync with master then.

**Pull request closed without merging**
