### PR TITLE
Some simplified code in initialization.

### PR DESCRIPTION
**Pull request by protonspring**
I hope I'm not wasting your time, but I think these initialization lines are cleaner.

### CODE REVIEW

**Comment by protonspring** [comment]
Maybe I should just post something in the RENAMING thread instead of a PR?

**Comment by Hanamuke** [comment]
Looks better to me. I'm not sure about the third one but the other two will also be faster (not that it matters) since the depedency chain is broken.

**Comment by snicolet** [comment]
The current code in master seems fine to me, closing this one without committing. Thanks anyway ! :-)

**Comment by protonspring** [comment]
But is it as cool? No problem. Thx.

**Comment by snicolet** [comment]
The reason I didn't commit your changes is because they rely on File and Rank to be convertible to integers at compile time. By contract, the code in current master does not rely on this and seems thus to be more robust to me!

**Comment by protonspring** [comment]
Just another few questions on this one, because I still think it's cleaner than master.  Regarding robustness, master addresses the FileBB array with [f - 1] while this base just shifts.

Master converts to an integer to index the array, so how is that more robust than this patch?

Also, If the base value of Files are offset in any way, master may write out of bounds while this patch will just erroneously shift (much less dangerous).  If I understand that correctly, doesn't that suggest that this patch is more robust than master?

**Pull request closed without merging**
