### PR TITLE
Remove FileBB and RankBB

### PR DESCRIPTION
**Pull request by protonspring**
This is a non-functional simplification.  These FileBB and RankBB values are simple enough to calculate on the fly. The arrays don't seem to add any value.  I can't detect any performance difference.

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 62532 W: 13720 L: 13679 D: 35133
http://tests.stockfishchess.org/tests/view/5c4689b50ebc5902bb5d67f0

### CODE REVIEW

**Comment by mcostalba** [comment]
It is ok for me.

**Comment by protonspring** [comment]
It seems like there are several other arrays that could be removed.  In order to make sure there is no regression, it seems like it would be better to test them all in combination.    Should I combine them all into one PR and resubmit?

**Comment by joergoster** [comment]
@protonspring Testing them all in combination for no regression seems like the better way, imho.

**Comment by mstembera** [comment]
Nice patch.  I hope SquareBB is one of those removed.

**Comment by protonspring** [comment]
I have tried SquareBB in the past. It would not pass -3,1, which honestly
surprised me.

**Comment by mcostalba** [comment]
Regarding SquareBB, for 32 bit machines the slowdown has always been sensible.

For instance, the only reason why we use still piece lists is because using pop_lsb() is a slow down in 32 bit machines. In the past many times we have tried to remove it (there are still some patches around, mine and of Lucas Braesch): that would be a **big** simplification, around 80 lines of code! But it always failed due to 32 bit machines (slowdown there is around 5%).

**Comment by joergoster** [comment]
@protonspring I found this one: http://tests.stockfishchess.org/tests/view/581da6850ebc5910626b9b78

**Comment by protonspring** [comment]
Closing.  I will submit a PR after I assemble a few arrays that can be removed.  Looks like there are at least 3.

**Comment by mstembera** [comment]
@mcostalba 
I agree removing SquareBB is slower on 32 bit machines.  The reason is that shifting a 64 bit value on a 32 bit machine requires many instructions which is slow.  I don't particularly care about SquareBB by itself but since removing RankBB and FileBB, rank_bb() and file_bb() are now also doing the same slow shifts we should be consistant.  We should either allow all these shift simplifications or none.  (BTW I think fishtest likely has so few 32 bit machines any more that none of this is an issue there.)  What do you think?

**Pull request closed without merging**
