### PR TITLE
Replace Position::see and Position::see_sign by Position::see_ge

### PR DESCRIPTION
**Pull request by atumanian**
This patch includes the patch by Stèphane Nicolet (https://github.com/official-stockfish/Stockfish/pull/819)

Stèphane's patch removes the only usage of Position::see, where the returned value isn't immediately compared with a value. So I replaced this function by its optimised and more specific version see_ge. This function also supersedes the function Position::see_sign.

bool Position::see_ge(Move m, Value v) const;

This function tests if the SEE of a move is greater or equal than a given value.

The overall speed of the engine is about 1% higher.

No functional change (relative to Stèphane's patch).

### CODE REVIEW

**Comment by gogamoga1** [comment]
PGO 

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1573101   1598692   -25591    
    StDev   11078     10478     12007     

p-value: 0,983
speedup: 0,016

**Comment by mcostalba** [comment]
@atumanian thanks for your efforts, but a PR is not a local work in progress branch. A PR is use to open a Pull Request with a patch in a final form, rebased above master and in a single commit.

In your case it should be also verified with a SPRT[0, 5] that it is worth it.

I am closing this now. Feel free to reopen after your work has passed fishtest.

**Comment by atumanian** [comment]
Sorry for inconvenience. Why should it be verified with a SPRT[0, 5]? Should every speed optimization be tested with SQRT? Or just because my patch is quite complex?

**Comment by mcostalba** [comment]
Yes to both things :-)

For a longer comment please have a look to the updated testing conditions
in the wiki.

**Comment by atumanian** [comment]
@mcostalba, do you mean this wiki?
https://github.com/glinscott/fishtest/wiki/Creating-my-first-test
It doesn't say every speed patch should be tested with SPRT, only one which haven't passed three steps.

**Comment by snicolet** [comment]
@atumanian Indeed the changes are complex, non local since they imply that we rewrite code in other files, etc.

**Comment by mcostalba** [comment]
@atumanian yes but I didn't want to veto the patch altogether, so I granted
you the first 2 :-) moreover the speed test with bench is usually very
noisy and I am not confident it can reliable detect 1% variations.

**Comment by atumanian** [comment]
@saproj, replied in the new pull request.

**Comment by atumanian** [comment]
The patch passed the Fishtest and I've made a new pull request: https://github.com/official-stockfish/Stockfish/pull/822

**Comment by atumanian** [comment]
@mcostalba, thank you, but 

> Yes to both things :-)

is incorrect, because the first thing is incorrect.

**Pull request closed without merging**
