### PR TITLE
Syntactic sugar to loop across pieces

### PR DESCRIPTION
**Pull request by mcostalba**
Also add some comments to the new operator~(Piece).

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
I have pushed a new commit above the first one. The new one is more a "study" than something meant to be merged in master: it allows improved readability in for loops but using some advanced C++ concept.

I am interested to have your feedback ...

**Comment by Rocky640** [comment]
I like this.
And I'm sure you can find something for bitboard.cpp line 137 ;)

**Comment by Stefano80** [comment]
I like this too. Is bad to use advanced c++ concepts?

**Comment by joergoster** [comment]
Once you get the concept, it's really nice and simple. I like it, too!

**Comment by snicolet** [comment]
If I should vote, on balance I would vote against including that code, as the part in types.h is really hard to understand.

**Comment by VoyagerOne** [comment]
I like the original version better.... it's less "cryptic".

**Comment by mcostalba** [comment]
Partially merged with e340ce221cc2911

I have merged first commit but not the "cryptic" :-) second one. Indeed plain, good old "for" loops may be a bit out of fashion days days but at least everybody understands them. The new code would have been justified to make more readable a difficult part, like endgame code, that without templates would be very messy and much more verbose. But here it is really overkill/over-engineered.

In C++ it is easy to indulge in fancy code just because we can: this is misleading most of the times.

**Comment by lucasart** [comment]
I suppose the second commit is of interest to people who want to learn some of the arcanes of C++. But the cost to benefit of such code is clearly negative. The benefit is zero. And the cost is huge: cryptic template code that nobody understands, actually adds lots of do nothing code, make a tiny typo in code like that and you get insulted by hundreds of line of cryptic compiler error messages… C for loops are much simpler to understand, both for humans reading the code, and for the compiler parsing it.

**Comment by lucasart** [comment]
Sometimes, template magic is a good solution to a problem that has no clean C-style solution. A good example is the tune branch, which is awesome. But here it's really not worth it.

**Comment by mcostalba** [comment]
@lucasart I agree. For documentation purposed I explain a bit what the code does.

We want to build a compile time sequence of integers (simpler than enum).

The key ingredients here are:

1) Variadic templates that accept a variable number of parameters (0 or more).

2) Compile time recursion. This is very common in template meta-programming and very powerful.

So here I have a struct that accepts a first integer value plus any number of additional integer parameters:

```
template<int N, int... Seq>
struct make_sequence {};
```

So far so good. I can use it like:

```
auto s1 = make_sequence<2>();
auto s2 = make_sequence<2, 5, 0>();
auto s3 = make_sequence<0>();
```

Now I want to build a sequence starting from an initial number N and going down to 0.  What can I do?

Here the trick is to add one number to the sequence at each step (using variadic templates expansion), the steps are implemented like a long recursion chain of following inheritances:

```
template<int N, int... Seq>
struct make_sequence : make_sequence<N - 1, N, Seq...> {};
```

Please read carefully the above because if you understand that, you understand all.

Take auto s1 = make_sequence<2>(); and explode all the inheritance steps:

`auto s1 = make_sequence<2> :  make_sequence<2-1, 2> : make_sequence<0, 1, 2> : : make_sequence<-1, 0, 1, 2> : and so on...`
`

Now we just need to tell the sequence **when** to stop, otherwise recursion goes on unlimited. Say we want to stop at 0, for this we add a template specialization of make_sequence that is evaluated with highest priority of base template when parameters match:

```
template<int... Seq>
struct make_sequence<0, Seq...> {}; // Specialization when first parameter is zero
```

This is a specialization, i.e. a special case of the general template that catch the case the first parameter is 0. When the compiler, expanding the templates at compile-time, finds that the fist number of the sequence is 0 than calls this specialization instead of base one, and the specialization, that does nothing, terminates the sequence.

The fill sequence is now available in the parameter pack Seq, that I could use inside the specialization body, for instance adding a function member called range() that uses that to fill a std::array,  so here it is the full solution:

```
template<int N, int... Seq>
struct make_sequence : make_sequence<N - 1, N, Seq...> {};

template<int... Seq>
struct make_sequence<0, Seq...> {

    typedef std::array<int, sizeof...(Seq)> Ret;

    Ret range() { return Ret{ Seq... }; } // Seq... it means that parameter pack Seq is expanded in its values
};
```

**Comment by lucasart** [comment]
This is more than syntactic sugar. It's syntactic LSD !!!

**Pull request closed without merging**
