### PR TITLE
Stat Formula Tweak

### PR DESCRIPTION
**Pull request by VoyagerOne**
bonus = d * d + 2 * d - 2

STC:
LLR: 2.94 (-2.94,2.94) [0.00,4.00]
Total: 99444 W: 18274 L: 17778 D: 63392

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 89757 W: 12285 L: 11896 D: 65576

### CODE REVIEW

**Comment by MichaelB7** [comment]
Was this a simplification ?  With a 0.004 difference in score equates to less than a 1 ELO gain in self-play  and the plus/minus ELO for 90,000 games is 1.5

**Comment by lantonov** [comment]
@Michael, the bounds are for a tuning patch, not for simplification

**Comment by MichaelB7** [comment]
Made an error in my comment - test results showed a 3 ELO gain - not less than 1.  Of course the plus and minus 1.5 allows for this to potentially be a net of zero.  Almost 200,000 games ( resources used) and potentially a zero gain.  Not your issue , but I would suggest that we cutoff testing at 50,000 games or so if there is no confirmed gain at that point with a tuning patch.

**Comment by DamasClasicas** [comment]
Congratulations Voyager One! 

Keep your excellent work and continue with the good streak!

**Comment by ajithcj** [comment]
Congrats VoyagerOne!

**Comment by mcostalba** [comment]
Merged with 7d2a79f0372d

**Pull request closed without merging**
