### PR TITLE
Revert incorrect pruning in qsearch

### LINKED ISSUE #3171: Segmentation fault
In the last stable build, and also in the last development build (stockfish_20092822_x64_modern), the following UCI commands cause a segmentation fault more than 50% of the times:
`position fen r7/3R2kQ/5p2/4p3/8/7P/8/5K2 b - - 2 3`
`go depth 14`
(It does not matter if I type "uci" "isready", "setoption name Threads value 2" before that or not)

### LINKED ISSUE #3196: Endgame score
SF and its clones give strange results when playing and analyzing.
 7k/3K2p1/6Pp/7P/8/8/8/7B b - - 0 68 

https://live.staticflickr.com/65535/50522628868_e0ff54c620_o.jpg

50522628868_e0ff54c620_o

The engine uses six-figure tables.
Seven-figure tables are not involved, but if they are included, the score is correct: 0.0.

[Game.txt](https://github.com/official-stockfish/Stockfish/files/5433046/Game.txt)

My SF plays black.

### PR DESCRIPTION
**Pull request by vondele**
This patch reverts code (started as 843a961a8c) that incorrectly prunes moves if in check,
and adds an assert to make sure no wrong mate scores are given in the future.

Initially discussed in #3171 (pointed out by joergoster) and later in #3199 and #3198.
This PR effectively closes #3171
It is also likely fixes #3196 where this causes user visible incorrect TB scores, which
probably result from these incorrect mate scores.

Just adding the additional code that checks for being inCheck failed in multiple variants:
https://tests.stockfishchess.org/tests/view/5f9be2f76a2c112b60691cfe
https://tests.stockfishchess.org/tests/view/5f6b5b62c7759d4ee307d006
https://tests.stockfishchess.org/tests/view/5f9a78856a2c112b60691c3f
https://tests.stockfishchess.org/tests/view/5f99f4ab6a2c112b60691bfc
https://tests.stockfishchess.org/tests/view/5f992f346a2c112b60691b89
https://tests.stockfishchess.org/tests/view/5f9918796a2c112b60691b80

However, as the fixed code doesn't pass Elo-gaining bounds wrt. the revert:
https://tests.stockfishchess.org/tests/view/5f9a7e8a6a2c112b60691c46
this patch justs reverts to the correct state.

Bench: 4151139

### CODE REVIEW

**Comment by joergoster** [comment]
I'd suggest to wait how this [test](https://tests.stockfishchess.org/tests/view/5f9eb624bca9bf35bae7f61d) turns out. This seems to be the most basic and least restrictive fix.

**Comment by syzygy1** [comment]
@joergoster That looks like a logical bugfix given that moveCount is necessarily at least 1 there anyway. (So the current test is superfluous.)

**Comment by vondele** [comment]
I agree the current `&& moveCount` is superfluous, and I see how adding `moveCount > 1` is sufficient to not trigger the assert. It also seems sufficient to fix  #3196 (at least I don't observe wrong TB score). 

I'm not quite sure how/if this prevents possible false mate scores. Makes me wonder what conditions needs to be fulfilled not to report false mate scores (forgetting about TT, but in the presence of pruning and depth reduction, etc.)

**Comment by joergoster** [comment]
@syzygy1 Not sure I understand. If you mean the current check in master `&& moveCount` is obsolete, then I agree.

@vondele We only return a mate score (`mated_in()`) when in check and there is no legal move left. With this patch we're now back to this logic. With the general risk we may prune some important move(s) occasionally, like with any other pruning method.
However, if you prefer to remove this altogether, I'm more than fine with it. ;-)

**Comment by vondele** [comment]
@joergoster right now your patch is looking good, and I agree that it fixes the case which the assert checks. 

However, I try to understand if or why this is sufficient to avoid incorrect mate scores. In the main search early pruning is disabled in check, shallow pruning is disabled till we have found a non-mate-scored move (but LMR is not).

**Comment by syzygy1** [comment]
@joergoster I mean that "moveCount" is never zero there anyway. The proper test condition seems to be moveCount > 1.

@vondele Whenever in check, search at least one legal move if there is one to make sure bestValue is raised.
I guess one could also return the static score if in check and we might have pruned all moves (except that we don't have one when in check).

**Comment by vondele** [comment]
@syzygy1 but is raising to a mate score (a deeper one) sufficient? I guess I have to think about that a bit.

**Comment by syzygy1** [comment]
OK, I have to think about that too :)

**Comment by joergoster** [comment]
Another possible 'fix' which I considered was this one:
```
      // CounterMove based pruning
      if (  !captureOrPromotion
          && bestValue > VALUE_TB_LOSS_IN_MAX_PLY
          && (*contHist[0])[pos.moved_piece(move)][to_sq(move)] < CounterMovePruneThreshold
          && (*contHist[1])[pos.moved_piece(move)][to_sq(move)] < CounterMovePruneThreshold)
          continue;
```

Maybe this a bit more safe regarding TB/Mate scores, in general.

**Comment by vondele** [comment]
Could you test that as well, please ?

**Comment by joergoster** [comment]
@vondele Sure.

Thinking about it, since we don't probe TBs in qsearch(), checking for
`          && bestValue > VALUE_MATED_IN_MAX_PLY`
seems more logical.

Any concerns?

**Comment by syzygy1** [comment]
How about not pruning any move when in check and bestValue <= VALUE_TB_LOSS_IN_MAX_PLY and, to reduce the impact, setting bestValue to aplha in line 1458?
https://github.com/official-stockfish/Stockfish/blob/dfc7f88650bf8bda4a381d36e209209cf63a9bcc/src/search.cpp#L1454-L1460
Then the check on moveCount can probably go.

**Comment by syzygy1** [comment]
We don't probe TBs in qsearch(), but qsearch() can still return a TB score from the TT.

**Comment by joergoster** [comment]
Right. Then I will go with my 1st proposal.

**Comment by syzygy1** [comment]
I guess instead of `bestValue = alpha` it would be `bestValue = max(alpha, mated_in(ss->ply))`. Then the check around line 1600 can go.

**Comment by joergoster** [comment]
@syzygy1 I would prefer to keep the fix as simple as possible.

**Comment by snicolet** [comment]
@vondele I'm fine with the revert. We are not in a hurry, so after that we can start from a sane base and calmly test again the different safe versions, keeping the simplest form that passes Elo gaining tests.

**Comment by syzygy1** [comment]
@joergoster I was mostly talking to myself :)

If your fix passes, that should fix the mate problem. If it does not, we can try my idea.

**Comment by syzygy1** [comment]
Well done, it passed.
As far as I can tell, this should solve all qsearch() mating problems and most likely without losing Elo.

**Comment by vondele** [comment]
right, I think this version is https://tests.stockfishchess.org/tests/view/5f9f0caebca9bf35bae7f666 is ready for a PR and to be preferred over this one.

**Comment by snicolet** [comment]
Indeed Jörg's fix passed and seems correct to me too (this one: https://tests.stockfishchess.org/tests/view/5f9f0caebca9bf35bae7f666 )

• it removes the movecount test, which was a no-op in master
• for positions with check, lines 1455-1459 ensure that the condition `bestValue > VALUE_TB_LOSS_IN_MAX_PLY` is equivalent to having found a non-mating move
• for position without check, `bestValue` could be raised via the TT before the move loop, but if anything this is only safer,  leads to less pruning, and seems not hurt Elo.

**Comment by joergoster** [comment]
Thanks!
I will submit a PR later today.

**Comment by vondele** [comment]
closing in favor of #3214

**Pull request closed without merging**
