### PR TITLE
Tuned nullmove search

### PR DESCRIPTION
**Pull request by lantonov**
Tuning was done with Bayesian optimisation and sequential use of GP regressor and GP classifier. The latter is used in lieu of ordinal categorical modelling. Details will be given in Fishcooking topic https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/b3uhBBJcJG4

STC
http://tests.stockfishchess.org/tests/view/5e0ba4159d3fbe26f672d4e6
LLR: 2.96 (-2.94,2.94) {-1.00,3.00}
Total: 10248 W: 2361 L: 2233 D: 5654
Ptnml(0-2): 191, 1153, 2303, 1276, 194

LTC
http://tests.stockfishchess.org/tests/view/5e0bb8519d3fbe26f672d4fd
LLR: 2.94 (-2.94,2.94) {0.00,2.00}
Total: 16003 W: 2648 L: 2458 D: 10897
Ptnml(0-2): 121, 1595, 4394, 1718, 153

Bench 5169250

### CODE REVIEW

**Comment by joergoster** [comment]
Congrats, again!

**Comment by drabel** [comment]
Nullmove patch WoW ! Congrats :)

**Comment by MichaelB7** [comment]
+4 Elo, that is a pretty impressive patch to start off with in 2020

**Comment by snicolet** [comment]
Interesting method, congrats :-)
Merged via 44f79bdf5a092c3acec0a8bf8f2c1440e5a9da90

**Pull request closed without merging**
