### PR TITLE
Added COMP=icx, removed COMP=icc, dit not alter GIT_DATE and GIT_SHA

### PR DESCRIPTION
**Pull request by maximmasiutin**
This pull request is an fourth alternative to add icx support. The other alternatives are the following:

1) https://github.com/official-stockfish/Stockfish/pull/4464 - added icx, updated icc, added git params for Makefile (for Windows)
2) https://github.com/official-stockfish/Stockfish/pull/4468 - added icx, removed icc, added git params for Makefile (for Windows)
3) https://github.com/official-stockfish/Stockfish/pull/4474 - added icx, removed icc, modified the way to display git data for Makefile to work for Windows
4) https://github.com/official-stockfish/Stockfish/pull/4475 - (current one) - added icx, removed icc, no changes to address the issues of git parameters in Makefile for Windows

A separte pull request to address Makefile issues is at https://github.com/official-stockfish/Stockfish/pull/4476

### CODE REVIEW

**Comment by vondele** [comment]
it is not OK to expose another option (pthread), again we would like to keep things simple for the users. While I can see that we could replace icc by icx, this IMO, should not need all these workarounds for the Makefile.

**Comment by maximmasiutin** [comment]
@vondele pthread is required to make it compile for Windows. I will remove pthread, but it will not be able to compile under Windows in that case. I have removed all these workarounds for the Makefile from this pull request.

**Comment by maximmasiutin** [comment]
I made an alternative pull request that does not touch pthread, but it will work under Linux only because for Windows icx will give be an error that pthread.h is missing. That pull request is at https://github.com/official-stockfish/Stockfish/pull/4478

**Comment by maximmasiutin** [comment]
Closed, as @vondele suggested to move pthread to a separate pull request, which I did at https://github.com/official-stockfish/Stockfish/pull/4478

**Pull request closed without merging**
