### PR TITLE
[cluster] Cluster fix

### PR DESCRIPTION
**Pull request by vondele**
fix compile of the cluster branch in the non-mpi case.

Add a TODO as a reminder for the new voting scheme.

No functional changes

### CODE REVIEW

**Comment by mcostalba** [comment]
Why not:

`  void sum(uint64_t&) { }`

**Comment by snicolet** [comment]
Merged via 878856abe50605fd6767799481f42baf50a7ce27, thanks!

@vondele @noobpwnftw Do we have any idea of the Elo progress of the cluster branch? For instance, is there a crossing point where the cluster with N machines is superior to a multi-core single machine with P cores? This could be relevant if we have to prepare for the big match against a neural network chess engine, or if we decide to enter Stockfish in a tournament like IGGA where each participant provides their own hardware.

**Comment by noobpwnftw** [comment]
If you skip the specifics involved in order to run this(or anything in general) efficiently in a real cluster, along with several major improvements made by @vondele, I think now it does provide a good enough starting point. He might have more to say about performance after the recent changes. My initial measurement was the factor of about 9:1 compared to local cores to get roughly equal ELO performance(1000 games).

However, almost every supercomputer on this planet have their own software stack, and they do that for a good reason. If there is a big match or a major event that we need to prepare for, I'd like to know how much we and our opponents committed to it, that'd be very useful to enlighten people from the virtual world about real life, where we can't always get the best hardware available for free but our opponents usually do.

**Comment by vondele** [comment]
@snicolet yes there is good progress (mostly the earlier patches), but doing some expectation management might be in order. First, we need the branch to be feature complete before we can talk performance (e.g. the counting of visited nodes feature might introduce a bit of a slowdown). 

My goal is to have 2 compute nodes with P cores each running the cluster branch to outperform 1 node with P cores using the master, with good scaling in the number of nodes afterwards. So far, I've only tested on a local SMP node, so I don't want to speculate much. As @noobpwnftw mentions this s pretty hardware & software stack sensitive. Nevertheless, at this point, I'm quite optimistic. I'll continue to work on this as time allows.

**Comment by snicolet** [comment]
Cross-posting to the Fishcooking forum thread about the progress of the cluster branch: 
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/JOw8Mxtpy6Q

**Pull request merged**
