### PR TITLE
Small cleanups 10

### PR DESCRIPTION
**Pull request by vondele**
a PR to collect small changes.

No functional change

### CODE REVIEW

**Comment by Chess13234** [comment]
Merge both prevScore loops into one
https://github.com/Chess13234/Goldfish/tree/FixBestScoreLoop

**Comment by shooreek** [comment]
Typo in the recent commit https://github.com/official-stockfish/Stockfish/commit/ca41ee6632368676a2fb98fd2970ac9b183f0aa9:

https://github.com/official-stockfish/Stockfish/blob/ca41ee6632368676a2fb98fd2970ac9b183f0aa9/src/Makefile#L353

-> "are known to work"

**Comment by snicolet** [comment]
> Merge both prevScore loops into one
> https://github.com/Chess13234/Goldfish/tree/FixBestScoreLoop

This is a case where the master code, while a bit longer, seems a little bit more readable to me :-)

**Comment by Rocky640** [comment]
evaluate.cpp
```
    bool infiltration = rank_of(pos.square<KING>(WHITE)) > RANK_4
                     || rank_of(pos.square<KING>(BLACK)) < RANK_5;
```
can be aligned as we do in other places:
```
    bool infiltration =   rank_of(pos.square<KING>(WHITE)) > RANK_4
                       || rank_of(pos.square<KING>(BLACK)) < RANK_5;
```

**Comment by Rocky640** [comment]
code style change, use arrays in evaluate.cpp whenever we can, and always use Pt-2 for consistency
https://github.com/Rocky640/Stockfish/commit/0cf2fe0be9f0d2a57e7efa259296a3357f59d2bb

Tested for non regression
on the safe checks
https://tests.stockfishchess.org/tests/view/5ef8b75c020eec13834a9596
LLR: 2.95 (-2.94,2.94) {-1.50,0.50}
Total: 22256 W: 4283 L: 4143 D: 13830
Ptnml(0-2): 291, 2439, 5588, 2459, 351

safe checks, outposts and king protectors
https://tests.stockfishchess.org/tests/view/5ef8e543020eec13834a95e7
LLR: 2.95 (-2.94,2.94) {-1.50,0.50}
Total: 28400 W: 5382 L: 5253 D: 17765
Ptnml(0-2): 394, 3078, 7119, 3223, 386

**Comment by snicolet** [comment]
@Rocky640 
I like the arrays, but prefer the versions with padding {0} at the beginning rather than the Pt-2 trick. It seems strange to read KNIGHT-2, BISHOP-2, etc everywhere in evaluate.cpp

**Comment by vondele** [comment]
@Rocky640 can you make the change suggested by @snicolet and open this as a full PR... it is easier to avoid future merge conflicts if the larger cleanups are merged separately.

**Comment by protonspring** [comment]
Denormalize KRKP (and probably many others).  Normalization makes sense for the KPK bitbase, but if it's not necessary, it's just unnecessarily complicated.  Should I do this for others as appropriate?

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_krkp10

**Comment by MichaelB7** [comment]
The last position in benchmark  

  "setoption name UCI_Chess960 value true",
 "bbqnnrkr/pppppppp/8/8/8/8/PPPPPPPP/BBQNNRKR w KQkq - 0 1 moves g2g3 d7d5 d2d4 c8h3 c1g5 e8d6 g5e7 f7f6",

should actually be 
"bbqnnrkr/pppppppp/8/8/8/8/PPPPPPPP/BBQNNRKR w **__HFhf__** - 0 1 moves g2g3 d7d5 d2d4 c8h3 c1g5 e8d6 g5e7 f7f6"

to illustrate with a position a where castling has occurred: 

$ stockfish
Stockfish 290620 64 POPCNT by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
setoption name UCI_Chess960 value true
position fen bbqnnrkr/pppppppp/8/8/8/8/PPPPPPPP/BBQNNRKR w KQkq - 0 1 moves f2f4 c7c5 e2e4 b7b5 d2d3 d7d6 e1f3 d8c6 f1e1 c8b7 g1h1

d
```
 +---+---+---+---+---+---+---+---+
 | b | b |   |   | n | r | k | r | 8
 +---+---+---+---+---+---+---+---+
 | p | q |   |   | p | p | p | p | 7
 +---+---+---+---+---+---+---+---+
 |   |   | n | p |   |   |   |   | 6
 +---+---+---+---+---+---+---+---+
 |   | p | p |   |   |   |   |   | 5
 +---+---+---+---+---+---+---+---+
 |   |   |   |   | P | P |   |   | 4
 +---+---+---+---+---+---+---+---+
 |   |   |   | P |   | N |   |   | 3
 +---+---+---+---+---+---+---+---+
 | P | P | P |   |   |   | P | P | 2
 +---+---+---+---+---+---+---+---+
 | B | B | Q | N | R | R | K |   | 1
 +---+---+---+---+---+---+---+---+
   a   b   c   d   e   f   g   h
```
Fen: bb2nrkr/pq2pppp/2np4/1pp5/4PP2/3P1N2/PPP3PP/BBQNRRK1 b **__hf__** - 5 6
Key: 0F72B03D6E0CC18B
Checkers:

**Comment by snicolet** [comment]
@protonspring 
This kinds of changes are quite big and worth their separate pull requests, where they can be discussed and tested.
The PR series "Small clean-ups" is best for trivial clean-ups, as Joost explained :-)

**Comment by MichaelB7** [comment]
The recent changes to the Makefile broke compiling on the 32 bit Pi.  Specifically, this item which combines 32 bit and and 64 ARM processors and results in the 32 bit armv7 being being built with bits set at 64, and naturally it fails.

```
	ifeq ($(ARCH),$(filter $(ARCH),armv7 armv8))
		ifeq ($(OS),Android)
			CXXFLAGS += -m$(bits)
			LDFLAGS += -m$(bits)
		endif
	else
		CXXFLAGS += -m$(bits)
		LDFLAGS += -m$(bits)
	endif
```
this fixes it:
```
	ifeq ($(ARCH),armv7)
		ifeq ($(OS),Android)
			CXXFLAGS += -m$(bits)
			LDFLAGS += -m$(bits)
		endif
	else
		CXXFLAGS += -m$(bits)
		LDFLAGS += -m$(bits)
	endif

	ifeq ($(ARCH),armv8))
		ifeq ($(OS),Android)
			CXXFLAGS += -m$(bits)
			LDFLAGS += -m$(bits)
		endif
	else
		CXXFLAGS += -m$(bits)
		LDFLAGS += -m$(bits)
	endif
```

**Comment by Rocky640** [comment]
About Chess 960 and our last benchmark position

For the given position, both KQkq and HFhf are both correct and unambiguous.
Ambiguity can arise with KQkq notation only in positions where, after some moves, more than one rook on same side of the King.

No real need to change, but it cannot harm, since 
Shredder-fen is clearly a better notation for chess 960, and by design, always unambiguous.

So I agree with 
"bbqnnrkr/pppppppp/8/8/8/8/PPPPPPPP/BBQNNRKR w **HFhf** - 0 1 moves g2g3 d7d5 d2d4 c8h3 c1g5 e8d6 g5e7 f7f6"

**Comment by vondele** [comment]
@MichaelB7 could you take the makefile bug as a separate issue or PR, since that has the potential of breaking/fixing stuff, it is not a small cleanup.

**Comment by MichaelB7** [comment]
@vondele - will do.

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp#L782
instead of attacks_bb<KING>(pos.square<KING>(~strongSide)) we should just probably write attackedBy[~strongSide][KING]

**Comment by mstembera** [comment]
Line 127 in bitboard.h should probably change from
```C++ inline Bitboard  operator|(Square s, Square s2) { return square_bb(s) | s2; }```
to
```C++ inline Bitboard  operator|(Square s1, Square s2) { return square_bb(s1) | s2; }```

**Comment by joergoster** [comment]
Lines 266 - 270 in search.cpp should be formatted like
```
  if (    int(Options["MultiPV"]) == 1
      && !Limits.depth
      && !(Skill(Options["Skill Level"]).enabled() || int(Options["UCI_LimitStrength"]))
      &&  rootMoves[0].pv[0] != MOVE_NONE)
      bestThread = Threads.get_best_thread();
```
We always put '&&' at the beginning, not at the end of a line.

**Comment by protonspring** [comment]
Since Depth is typedef as an int, this enum seems pretty pointless.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_depth5

**Comment by protonspring** [comment]
pawns.cpp, line 41 claims the BlockedPanws are a "bonus," but they seems like a penalty.  change to:
"Penalty for blocked pawns at 5th or 6th rank."

**Comment by protonspring** [comment]
Consider more consistent pawn scoring.  Make all of the scores clearly penalties or bonuses based on their pos/neg values.
Always ADD the bonus/penalty to the score.  This just makes it more clear whether a value is a bonus or a penalty.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_pawnsigns4

**Comment by Rocky640** [comment]
well, if you want them to qualify as penalty, you would have to change the score signs, 
and when you use it, you would have to subtract.

**Comment by Rocky640** [comment]
comment on

> Consider more consistent pawn scoring.


When you read the code without looking at the actual score values,
I think it is quite natural to expect `score -=Doubled;`

**Comment by protonspring** [comment]
Makes sense. . just some of the penalties/bonuses aren't really clear by name, so you do have to look at the application to determine whether the value is a penalty or a bonus.  If we always added, it's clear just by looking at the values.  No big difference either way.

**Comment by Rocky640** [comment]
I recommend to merge Viz change as well, in evaluate.cpp we take the trouble to calculate the attackedBy bitboard  so it makes sense to use them whenever we can.

https://github.com/official-stockfish/Stockfish/pull/2772#issuecomment-653851084

**Comment by mstembera** [comment]
@protonspring I find it easier to just add bonuses and subtract penalties.  If we add everything I have to scroll all the way up to the value definition instead of seeing the + or - right where it's being used.

**Comment by protonspring** [comment]
make some constexpr in bitboard.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_constexpr4

**Comment by snicolet** [comment]
Line 673 of search.cpp: develop the conditions

```
if (   ttPv
    && depth > 12
    && ss->ply - 1 < MAX_LPH
    && !priorCapture 
    && is_ok((ss-1)->currentMove))
```

**Pull request closed without merging**
