### PR TITLE
Isolated pawn simplification

### PR DESCRIPTION
**Pull request by snicolet**
STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 117822 W: 21697 L: 21744 D: 74381

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 92307 W: 12330 L: 12305 D: 67672

Bench: 8813983

### CODE REVIEW

**Comment by snicolet** [comment]
Thanks to Lucas for running the LTC test :-)

**Comment by IIvec** [comment]
Congratulations and very interesting simplification. However, I think this is a sign that these values were not tuned well. I'll try something about this.

**Comment by joergoster** [comment]
Congrats!

**Comment by AlexandreMasta** [comment]
Why does this test started so badly and changed after so many games? Really strange. Careful with some results.

**Comment by theo77186** [comment]
@AlexandreMasta This is the weirdness of the unpredictable Fishtest. I have a test which was +1.40 after 5k games then goes red after 36k.

**Comment by zamar** [comment]
approved.

**Comment by theo77186** [comment]
When this will be commited?

**Comment by locutus2** [comment]
Congrats too!

**Pull request closed without merging**
