### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by snicolet**
Small code and comment cleanup (references to splitpoints, c'tor and d'tor).

No functional change

### CODE REVIEW

**Comment by zamar** [comment]
approved

**Comment by Rocky640** [comment]
Is there a possibly better memory (re)alignment that can done here for struct Stack ?

**Comment by lucasart** [comment]
@Rocky640: what do you mean? The compiler will always align so as to not have any unaligned memory access in any member of the struct. Can you provide some sample code to clarify?

**Comment by Rocky640** [comment]
I thought we should not take this last minute change too casually.

There might be some programming hacks which will not work anymore if you remove one data member of a struct. I do not know if we are using such hacks

Some (old posts) claims that hand tuned alignments might be faster, 
and also talk about using/not using some pragma directive

See for example the first answer on:
http://stackoverflow.com/questions/9086656/bit-aligning-for-space-and-performance-boosts

http://stackoverflow.com/questions/16548059/how-to-trap-unaligned-memory-access?rq=1

I just raised a question. I'm not really knowledgeable on these things.
If there is nothing to worry, then I'm all fine with this.

**Comment by snicolet** [comment]
I have compared the speed of the patch against the speed of the current master, by running ten benches of each, alternating between the two versions, excluding the fastest run and the slowest run of each version and taking the average of the eight other runs (Mac OS X 10.9.5, Clang compiler clang-600.0.57)
------------
Master:

4692  
4709  (*)
4681
4656
4656
4667
4682
4637  (*)
4693
4700

Average: 4678,4  milliseconds

----------
Patch (without SplitPoint* splitPoint):

4657
4662
4670
4656
4697  (*)
4669
4647
4622  (*)
4645
4677

Average: 4660,4 milliseconds
--------------------

So, if any, the patch version (without the SplitPoint pointer in the Stack structure) could be slightly faster on my system.

**Comment by mstembera** [comment]
@Rocky640 
The first example you link makes the first struct slow only because they force
#pragma pack( push, 1 )
We are ok here.

**Comment by glinscott** [comment]
Looks good!

**Pull request closed without merging**
