### PR TITLE
clarified flow in Eval::evaluate()

### PR DESCRIPTION
**Pull request by mattginsberg**
This change clarifies the flow through Eval::evaluate() that is responsible for choosing between classical and NNUE eval. Both LTC and STC showed small (~0.25 ELO) improvement which is possible because the new code is slightly cleaner (although I would have expected the compiler to sort this out). The primary purpose of the pull request, however, is to allow evaluate() to be split into a variety of coherent cases based on the caller.

STC:
LLR: 2.93 (-2.94,2.94) {-1.25,0.25}
Total: 22952 W: 2097 L: 2020 D: 18835
Ptnml(0-2): 56, 1569, 8183, 1578, 90
https://tests.stockfishchess.org/html/live_elo.html?6005e0f56019e097de3efa46

LTC:
LLR: 2.93 (-2.94,2.94) {-0.75,0.25}
Total: 39296 W: 1470 L: 1433 D: 36393
Ptnml(0-2): 10, 1195, 17206, 1222, 15
https://tests.stockfishchess.org/html/live_elo.html?6005f35f6019e097de3efa60

### CODE REVIEW

**Comment by snicolet** [comment]
The simplification bounds were not correct for this patch.

**Comment by mattginsberg** [comment]
I had a long discussion w/ Viz about exactly this question.  This really *isn't* a functional change in any way, just cleaning up the code so that mortals can understand it.  It's unlikely (I expect) to pass the normal LTC test because the gain is too small.  But I (and others?) definitely need the change in order to work productively on this section of the code.

**Comment by NKONSTANTAKIS** [comment]
Following the discord, I understand that this is a preparatory step to a vision. The codebase over time tends to get excessively interlinked and get stuck at a local high. Big reworks are very hard to undertake all at once. At those sterile times, attracting experienced coders is very fortunate. I think its a bad idea to put obstacles about trivial and at least equally good changes.

**Comment by snicolet** [comment]
Beware that you cannot claim that the patch is 0.25 Elo improvement :-)

When a patch passes a SPRT run with {-1.25,0.25} bounds, the only conclusion we can draw is that, given the games in the test, the likelihood of the patch value being < -1.25 Elo is much lower (1/20, to be precise) than the likelihood of the patch value being > 0.25 Elo.

Nothing more, nothing less.

In particular, Elo estimates given by the patch statistics are almost meaningless for all practical purposes (except maybe for yellow results after very very long runs, about 100.000 games, but that is another story), and we never base our decisions on them. If we added all the Elo "gains" of all merged patches, Stockfish Elo would be in the zillions :-)

**Comment by mattginsberg** [comment]
I understand about the meaning of the bounds.  :)

There were a couple of runs.  On both, the win/loss score was about +50.  So it looks like it's a little better.  A *little* better.

But I totally understand that actually validating a +0.25 ELO is going to take a ridiculous number of tests.  And as I said in a comment somewhere, this was not intended to be a functional change.  But it *did* involve reordering some code, and in a way that might lead to a small performance improvement if the compiler were stupid.  Modern compilers are anything *but* stupid, so I don't know if I believe the +0.25 ELO myself.  :)

Mostly, I took a piece of code that struck me as very obscure and tried to clean it up a bit.  I've been asking everyone who will answer whether such things merit PRs.  My personal preference (whether I'm a coder or a maintainer) would be to keep the PRs as small as possible, which means that there will be more of them.  So that's why I've submitted it.

**Comment by vondele** [comment]
I don't think this is a real improvement here, also not really formatted as the surrounding code. So I'll close this.

**Pull request closed without merging**
