### PR TITLE
Update default net to nn-6762d36ad265.nnue

### PR DESCRIPTION
**Pull request by SFisGOD**
SPSA 1: https://tests.stockfishchess.org/tests/view/612cdb1fbb4956d8b78eb5ab
Parameters: A total of 256 net biases were tuned (hidden layer 2)
Base net: nn-fe433fd8c7f6.nnue
New net: nn-5f134823db04.nnue

SPSA 2: https://tests.stockfishchess.org/tests/view/612fcde645091e810014af19
Parameters: A total of 64 net biases were tuned (hidden layer 1)
Base net: nn-5f134823db04.nnue
New net: nn-8eca5dd4e3f7.nnue

SPSA 3: https://tests.stockfishchess.org/tests/view/6130822345091e810014af61
Parameters: 256 net weights and 8 net biases (output layer)
Base net: nn-8eca5dd4e3f7.nnue
New net: nn-4556108e4f00.nnue

SPSA 4: https://tests.stockfishchess.org/tests/view/613287652ffb3c36aceb923c
Parameters: A total of 256 net biases were tuned (hidden layer 2)
Base net: nn-4556108e4f00.nnue
New net: nn-6762d36ad265.nnue

STC:
LLR: 2.96 (-2.94,2.94) <-0.50,2.50>
Total: 162776 W: 41220 L: 40807 D: 80749
Ptnml(0-2): 517, 18800, 42359, 19177, 535
https://tests.stockfishchess.org/tests/view/6134107125b9b35584838559

LTC:
LLR: 2.95 (-2.94,2.94) <0.50,3.50>
Total: 41056 W: 10428 L: 10156 D: 20472
Ptnml(0-2): 30, 4288, 11618, 4564, 28
https://tests.stockfishchess.org/tests/view/6134ad6525b9b3558483857a

Closes https://github.com/official-stockfish/Stockfish/pull/3691

Bench: 5300725

### CODE REVIEW

**Comment by TopoIogist** [comment]
Congrats

**Comment by Sopel97** [comment]
You might be interested in this https://github.com/glinscott/nnue-pytorch/pull/150 :)

**Comment by snicolet** [comment]
Merged via be63ce1bb59d24cce3346be0e41923204ffcca13, congrats :-)

**Comment by SFisGOD** [comment]
> Merged via [be63ce1](https://github.com/official-stockfish/Stockfish/commit/be63ce1bb59d24cce3346be0e41923204ffcca13), congrats :-)

@snicolet Thanks Stéphane! Glad you're back! :)

**Comment by anshulongithub** [comment]
@snicolet!! so so happy to see you back with merging patches, Stockfish and we all in the chess fan community have a humble request to you to please never ever step down as a maintainer.

**Comment by MichaelB7** [comment]
@snicolet Welcome back!

**Comment by MichaelB7** [comment]
@SFisGOD awesome work!

**Pull request closed without merging**
