### PR TITLE
[tools] Merge branch 'upstream/master' (4c7de9e8abd8d5dc71d0c85dddd75a7b244600d7) into tools

### PR DESCRIPTION
**Pull request by Sopel97**
Update for the tools branch. This is a merge instead of a rebase because rebasing it is pretty much impossible with all the historical conflicts.

### CODE REVIEW

**Comment by Sopel97** [comment]
What do we do about CI failing for android?

https://github.com/android/ndk/issues/609

Forcing v22 for ndk doesn't work. Do we drop it from CI for tools (since it should not be very relevant anyway)?

**Comment by vondele** [comment]
yes, that seems a LLVM compiler bug. I'm fine with skipping that CI as well (or updating the version if it is possible).

**Comment by vondele** [comment]
yes, I think it is fine. I tried having a quick look at the diff to master, but it really is a serious diff... 
```59 files changed, 16547 insertions(+), 168 deletions(-)```
It compiles without warnings here, and gives the same bench as master, so that's pretty good. I'll do some more light testing and merge.

**Comment by Sopel97** [comment]
Okay. I squashed the CI changes.

**Pull request merged**
