### PR TITLE
Don't print fail-high or fail-lows in MultiPV mode

### PR DESCRIPTION
**Pull request by zamar**
Supposed to give a better user experience when using MultiPV mode

No functional change

### CODE REVIEW

**Comment by mcostalba** [comment]
The only advantage of this patch (but is a big advantage) compared to Gary's one is that this is much simpler.

Being both ugly (and useless) hacks, of course the preference goes to the less invasive of the 2 (as is always the general rule with hacks).

Of course the _real_ solution is to consciously choose between only correct PV (leave as is), or always show something (revert to 'retrieve from TT').

**Comment by zamar** [comment]
Here we are not showing any wrong information to the user...

We just wait that all fail-highs and fail-lows are resolved, and only after that update the score. I think that in multiPV mode this is acceptable as we've already taken a performance hit of 100-200 ELO points anyway...

My preference (I'm thinking from scientific perspective) would be to leave the output as it is.
However from practical perspective most GUIs do not seem to cope well with it, here we modify the output so that GUIs can actually interpret and show it better.

**Comment by zamar** [comment]
Gary said that he is fine with this patch, so I plan to commit before freeze.

If something turns out to be badly wrong with the change, the patch can easily be reverted during the freeze

**Comment by glinscott** [comment]
Yes, I think this is a good compromise.

**Pull request closed without merging**
