### PR TITLE
update default net to nn-4f56ecfca5b7.nnue

### PR DESCRIPTION
**Pull request by vondele**
New net trained with nnue-pytorch, started from a master net on a data set of Leela
(T60.binpack+T74.binpck) Stockfish data (wrongIsRight_nodes5000pv2.binpack), and
Michael Babigian's conversion of T60 Leela data (including TB7 rescoring) (farseer.binpack)
available as a single interleaved binpack:

https://drive.google.com/file/d/1_sQoWBl31WAxNXma2v45004CIVltytP8/view?usp=sharing

The nnue-pytorch branch used is https://github.com/vondele/nnue-pytorch/tree/wdl

passed STC:
https://tests.stockfishchess.org/tests/view/61a3cc729f0c43dae1c71f1b
LLR: 2.95 (-2.94,2.94) <0.00,2.50>
Total: 49152 W: 12842 L: 12544 D: 23766
Ptnml(0-2): 154, 5542, 12904, 5804, 172

passed LTC:
https://tests.stockfishchess.org/tests/view/61a43c6260afd064f2d724f1
LLR: 2.96 (-2.94,2.94) <0.50,3.00>
Total: 25528 W: 6676 L: 6425 D: 12427
Ptnml(0-2): 9, 2593, 7315, 2832, 15

Bench: 6885242

### CODE REVIEW

**Comment by snicolet** [comment]
Congrats :-)

**Comment by snicolet** [comment]
Which version of the nnue-pytorch trainer should be considered the most "official", in your opinion? 

I see that the ReadMe.md file of official-stockfish still points to the nodchip repository, and as I understand it this is no longer the recommended trainer, so it would be nice to point to the best nnue-pytorch trainer at this point.

**Comment by vondele** [comment]
https://github.com/glinscott/nnue-pytorch/ is the official trainer... I'll prepare a PR to merge my wdl as soon as get some time.

I agree we should update the readme.md file, giving credit to the original nodchip trainer, while pointing to the current official.

**Comment by vondele** [comment]
the readme has been adjusted

**Pull request closed without merging**
