### PR TITLE
Remove unused return type from propagate()

### PR DESCRIPTION
**Pull request by mstembera**
Remove unused return type from propagate()
Make two AffineTransform and AffineTransformSparseInput static methods constexpr
No functional change
bench: 1601764

### CODE REVIEW

**Comment by snicolet** [comment]
Looks good to me.

Any speed measurement for the impact of the constexpr?

**Comment by Torom** [comment]
`ARCH=x86-64-bmi2 COMP=clang`
```
Result of  50 runs
==================
base (...es/stockfish) =    1055354  +/- 4079
test (...pagateReturn) =    1057386  +/- 3494
diff                   =      +2032  +/- 6834

speedup        = +0.0019
P(speedup > 0) =  0.7197

CPU: 4 x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Hyperthreading: on
```

**Comment by mstembera** [comment]
Thanks.  There should be no speed difference because the static get_index methods only get called at startup to load the weights.  I mostly made them constexpr just because they can be and for consistency with the other static get_hash_value() method right above.

**Comment by snicolet** [comment]
merged via cb22520a9c7e1d716a56f08390aa638a23a597b2, thanks!

**Pull request closed without merging**
