### PR TITLE
Allow first three threads to stop SMP search.

### PR DESCRIPTION
**Pull request by lp--**
10+0.1 th 3:
LLR: 2.94 (-2.94,2.94) [0.00,5.00]
Total: 36614 W: 6189 L: 5921 D: 24504

40+0.4 th 3:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 176721 W: 23187 L: 22497 D: 131037

5+0.05 th 7:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 48521 W: 8185 L: 7869 D: 32467

### CODE REVIEW

**Comment by ErnstDoerfert** [comment]
10+0.1 th 3:
LLR: 2.94 (-2.94,2.94) [0.00,5.00]
Total: 36614 W: 6189 L: 5921 D: 24504

40+0.4 th 3:
LLR: 2.94 (-2.94,2.94) [0.00,5.00]
Total: 36614 W: 6189 L: 5921 D: 24504

Really identical results for both TCs?

**Comment by lp--** [comment]
now it got copied

**Comment by mcostalba** [comment]
I am sorry but still didn't had time to properly check this one: it is a
complex patch and cannot be evaluated with just a quick glance at it.

My first comment is that we really don't want easy move to be triggered by
other threads: it is already quite risky as is, no need to add additional
risk making it even less predictable. So I would say that for reducing risk
of losing a game due to a bad move, only main thread should be allowed to
detect an easy move. If the easy move is really "easy", this has no
performance impact but is more reliable.

**Comment by lp--** [comment]
Yes, easy move is triggered only by main thread. I guess your comment is due to variable doEasyMove, copies of which are currently  defined and calculated  in every thread but used for making easy moves only in main thread. Maybe it is  better to define one copy  in MainThread class and explicitly prevent other threads from accessing it. 

I also comment on other variables, as I was moving them to easier explore different options, and they got left there.  

easyMovePlayed is still logically belong to MainThread as it is used only there.
There is only one copy of bestMoveChanges and failedLow which are changed by only main thread but accessed by all threads. Possibly the best place to define it is  ThreadPool class

**Comment by mcostalba** [comment]
@lp-- ok I have checked it, but it seems to me _really_ complex and obscure: I don't understand it.

@zamar please can you look at it? I am not sure we want to be so smart. This patch makes a complex and difficult to test part of the code even more complex and difficult to test. I fear the code will quickly became unmaintainable here.

**Comment by lucasart** [comment]
Shouldn't time management patches also be tested with no increment, and at tournament tc ? (eg. 15+0 and 40/10).

**Comment by zamar** [comment]
@mcostalba: I agree, this gets too complicated. I wouldn't commit this patch without evidence that it is a big ELO boost (I doubt it)

**Comment by lp--** [comment]
@zamar: what elo boost this should be ? which tc and how many threads?

**Comment by zamar** [comment]
Well, we would be talking something like +5 ELO in multithread mode that would make this patch worth committing.

**Pull request closed without merging**
