### PR TITLE
[NNUE] Fix redundant loading data

### PR DESCRIPTION
**Pull request by nguyenpham**
Whenever a user turns on NNUE mode (`setoption name Use NNUE value true`) the default network is autoloaded immediately. If the user wants to run the engine with another network he has to load again, making redundancy and confusion.

- Delete the default network may avoid that loading but create an error message.
- Change the order of commands for setting options (say `EvalFile` before `Use NNUE`) is good but not the solution since it depends on chess GUIs

In this PR, the initialization of the network is removed when setting the option `Use NNUE` and add to command `go` instead (there is an existent place to init in command `ucinewgame`).

### CODE REVIEW

**Comment by vondele** [comment]
@nguyenpham probably not OK, as the time needed to initialize the network would be part of the thinking time. We have to think about on how to deal with the nets, and when to load them.

**Comment by nguyenpham** [comment]
It is OK since for standard condition the command `ucinewgame` always sent first so SF can init the data already. We initialize the data in `go` command just for being convenient when testing manually.

**Comment by vondele** [comment]
It is one of the things a random/synthetic default/internal network would fix (https://github.com/official-stockfish/Stockfish/issues/2823#issuecomment-665002156)
We would only need to take action on a EvalFile command.

**Comment by vondele** [comment]
I've instead gone for the solution in https://github.com/official-stockfish/Stockfish/pull/2893

**Pull request closed without merging**
