### PR TITLE
Fix compiling 32-bit executable on 64-bit host

### LINKED ISSUE #516: Broken cross compiling to 32-bit on 64-bit host
Under 64-bit OS 64-bit compiler creates a working executable when make is invoked with ARCH=x86-32. But this executable is working only under 64-bit OS and not working under 32-bit OS.

### PR DESCRIPTION
**Pull request by braich**
Fixes #516

### CODE REVIEW

**Comment by mstembera** [comment]
I get the below error when compiling like this
make build ARCH=x86-32
or
make build ARCH=x86-32 COMP=mingw
under Windows.

g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -Wextra -Wshadow -DN
DEBUG -O3 -m32 -msse   -c -o benchmark.o benchmark.cpp
In file included from c:/MinGW/mingw64/x86_64-w64-mingw32/include/c++/random:49:
0,
                 from c:/MinGW/mingw64/x86_64-w64-mingw32/include/c++/bits/stl_a
lgo.h:66,
                 from c:/MinGW/mingw64/x86_64-w64-mingw32/include/c++/algorithm:
62,
                 from movepick.h:23,
                 from thread.h:31,
                 from benchmark.cpp:28:
c:/MinGW/mingw64/x86_64-w64-mingw32/include/c++/bits/random.h:106:26: error: exp
ected unqualified-id before '__int128'
       { typedef unsigned __int128 type; };
                          ^
make[1]: *** [benchmark.o] Error 1
make[1]: Leaving directory `/c/Projects/StockfishOF6/src'
make: *** [build] Error 2

Maybe the solution is to invoke x86_64-w64-mingw32-c++ for 64 bit compiles and i686-w64-mingw32-c++ for 32 bit compiles instead of g++.  I haven't tested that though.

**Comment by zamar** [comment]
I don't think that we should go down this path... There is no good reason to officially support cross-compiles. Very few people need it, and people who do are usually skilled even to modify the Makefile themselves based on their needs.

**Comment by braich** [comment]
@zamar It is not only cross-compile issue. Currently, when you invoke ```make``` with e.g. ```build ARCH=x86-32``` under 64-bit Linux you will get an executable that IS WORKING under 64-bit Linux and IS NOT working under 32-bit Linux.
@mstembera errors mean that your compilers are not supporting 32-bit build. 
Let's take for example, Ubuntu 15.04:
```
make build ARCH=x86-32
make ARCH=x86-32 COMP=gcc config-sanity
make[1]: Entering directory '/home/user/Stockfish/src'

Config:
debug: 'no'
optimize: 'yes'
arch: 'i386'
bits: '32'
prefetch: 'yes'
bsfq: 'no'
popcnt: 'no'
sse: 'yes'
pext: 'no'

Flags:
CXX: g++
CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto
LDFLAGS:  -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto

Testing config sanity. If this fails, try 'make help' ...

make[1]: Leaving directory '/home/user/Stockfish/src'
make ARCH=x86-32 COMP=gcc all
make[1]: Entering directory '/home/user/Stockfish/src'
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o benchmark.o benchmark.cpp
In file included from /usr/include/c++/4.9/ios:38:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from benchmark.cpp:20:
/usr/include/c++/4.9/iosfwd:38:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
<builtin>: recipe for target 'benchmark.o' failed
make[1]: *** [benchmark.o] Error 1
make[1]: Leaving directory '/home/user/Stockfish/src'
Makefile:409: recipe for target 'build' failed
make: *** [build] Error 2
```
To fix errors g++-4.9-multilib is needed.

```
sudo apt-get install g++-4.9-multilib
```
and then
```
make build ARCH=x86-32
make ARCH=x86-32 COMP=gcc config-sanity
make[1]: Entering directory '/home/user/Stockfish/src'

Config:
debug: 'no'
optimize: 'yes'
arch: 'i386'
bits: '32'
prefetch: 'yes'
bsfq: 'no'
popcnt: 'no'
sse: 'yes'
pext: 'no'

Flags:
CXX: g++
CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto
LDFLAGS:  -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto

Testing config sanity. If this fails, try 'make help' ...

make[1]: Leaving directory '/home/user/Stockfish/src'
make ARCH=x86-32 COMP=gcc all
make[1]: Entering directory '/home/user/Stockfish/src'
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o benchmark.o benchmark.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o bitbase.o bitbase.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o bitboard.o bitboard.cpp
^C<builtin>: recipe for target 'bitboard.o' failed
make[1]: *** [bitboard.o] Interrupt
Makefile:409: recipe for target 'build' failed
make: *** [build] Interrupt

user@ubuntu:~/Stockfish/src$ make build ARCH=x86-32
make ARCH=x86-32 COMP=gcc config-sanity
make[1]: Entering directory '/home/user/Stockfish/src'

Config:
debug: 'no'
optimize: 'yes'
arch: 'i386'
bits: '32'
prefetch: 'yes'
bsfq: 'no'
popcnt: 'no'
sse: 'yes'
pext: 'no'

Flags:
CXX: g++
CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto
LDFLAGS:  -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto

Testing config sanity. If this fails, try 'make help' ...

make[1]: Leaving directory '/home/user/Stockfish/src'
make ARCH=x86-32 COMP=gcc all
make[1]: Entering directory '/home/user/Stockfish/src'
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o bitboard.o bitboard.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o endgame.o endgame.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o evaluate.o evaluate.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o main.o main.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o material.o material.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o misc.o misc.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o movegen.o movegen.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o movepick.o movepick.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o pawns.o pawns.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o position.o position.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o psqt.o psqt.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o search.o search.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o thread.o thread.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o timeman.o timeman.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o tt.o tt.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o uci.o uci.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o ucioption.o ucioption.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto   -c -o syzygy/tbprobe.o syzygy/tbprobe.cpp
g++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o  -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -m32 -msse -flto
make[1]: Leaving directory '/home/user/Stockfish/src'
```
i.e., ```make build ARCH=x86-32``` works fine.

Under Windows the source of errors is the toolchain targeting Win64. To fix an error you must install [one of the toolchains targeting Win32](http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/).

**Comment by zamar** [comment]
I don't know what the official definition for cross-compiling is, but for me compiling 32-bit binary on 64-bit system is already kind of cross-compiling. Why would generally do that?

**Comment by braich** [comment]
If I understand your question right. 
You have 64-bit computer with an installed development environment that is used to compile binaries for customers. Currently, when you try to compile binary for customers with 32-bit computers you will get it without any errors, but the binary will be unusable on 32-bit computers.

**Comment by zamar** [comment]
Yes,

That's the way it has always been. Stockfish Makefile doesn't support
cross-compiling out of the box.

There are so few of us who need to "compile binary for the customers".

**Comment by braich** [comment]
Getting expected results is another issue beside cross-compiling. For example If you try to compile 32-bit binary under 64-bit Mac OS, you will get an error if the compiler doesn't support it, or will get working 32-bit binary. This is because of -arch=i386 option that is used in Makefile for Mac OS targets. 64-bit Linux and Windows gcc lack -arch option so you will always get unexpected results. (64-bit executable instead of 32-bit).

**Comment by mstembera** [comment]
@braich 
I do have a toolchain targeting Win32 installed but of course I have a Win64 toolchain installed as well.  The problem is that if you generically invoke g++ it will simply run whichever g++ is found first in the path.  Here is a version that fixes at least the COMP=mingw case under Windows.
https://github.com/official-stockfish/Stockfish/compare/master...mstembera:make32

**Comment by braich** [comment]
@mstembera
I think it would be better to remove the check of the variable $(UNAME) for Linux https://github.com/official-stockfish/Stockfish/compare/master...braich:patch-1%5E to get the same results.
And I think that adding -m32 option is not enough. We should also use -march option to specify needed instruction set. 
Default value of the gcc -march option is set when gcc itself compiled. So it can be e.g. core2 for 64-bit gcc. If we build x86-32 and x86-32-old targets and invoke gcc with -m32 option only we will get 32-bit binary that uses 32-bit instruction set of core2 (with MMX, SSE, SSE2, SSE3 and SSSE3). Obviously that code will not be working with old hardware.
Therefore I added lines that specify correct instruction set for x86-32 and x86-32-old targets. 
https://github.com/official-stockfish/Stockfish/compare/master...braich:patch-1 
Pentium3 (the first CPU with SSE instruction set) is used for x86-32, i486 (with -march=i386 I get compiler errors) for x86-32-old.

**Comment by mstembera** [comment]
@braich 
I don't think you can count on "shell" and "which" to be valid commands under Windows so that is why the "ifeq ($(UNAME),Linux)" is there.

**Comment by zamar** [comment]
Once again:
I don't think that we want to commit anything along these lines. Supporting all kind of cross-compiles is difficult/impossible.
 
- There are so many different kind of linux systems, so many different kind of setups, and so many different kind of compilers.

- People who want to do cross-compiles (<1% of people compiling Stockfish), can tweak the Makefile based on their individual setup and needs.

- Linux -> Windows cross-compiles are an exception I'm willing to make, because it's something that is used by a plenty of people.

I'm planning to close this request.

**Comment by braich** [comment]
@mstembera To build Stockfish using current Makefile you need something like MSYS or Cygwin. Usually such environments have "which" tool. "shell" is part of Make tool,as far as I remember. I don't see a problem here.
@zamar I'm agree with you that current pull request must be closed. It does not resolve the problem. 
But I think that the problem still exists. And can be easily solved.
"There are so many different kind of linux systems" - in Makefile they all treated as one - Linux 
"many different kind of setups" - have not  caught you here.
"so many different kind of compilers" - in Makefile I see only four gcc,clang,mingw,icc
"People who want to do cross-compiles (<1% of people compiling Stockfish),"  <1% or >99% does not matter. All that matters is the result they will get and whom they will blame.
"can tweak the Makefile based on their individual setup and needs." - if they know what and where is wrong.
"Linux -> Windows cross-compiles are an exception I'm willing to make" I want to think that was not the last exception you make.

**Pull request closed without merging**
