### PR TITLE
Use arrays 

### PR DESCRIPTION
**Pull request by Rocky640**
Non functional change, use array for safe checks, outposts and king protectors
in evaluate.cpp

Tested for non regression on the safe checks
https://tests.stockfishchess.org/tests/view/5ef8b75c020eec13834a9596
LLR: 2.95 (-2.94,2.94) {-1.50,0.50}
Total: 22256 W: 4283 L: 4143 D: 13830
Ptnml(0-2): 291, 2439, 5588, 2459, 351

Tested for non regression on the safe checks, outposts and king protectors
https://tests.stockfishchess.org/tests/view/5ef8e543020eec13834a95e7
LLR: 2.95 (-2.94,2.94) {-1.50,0.50}
Total: 28400 W: 5382 L: 5253 D: 17765
Ptnml(0-2): 394, 3078, 7119, 3223, 386

updated with latest master
bench: 4523573

### CODE REVIEW

**Comment by snicolet** [comment]
Two small remarks:

• SafeCheck could use {} for the padding zeros at the beginning of the array:

```
constexpr int SafeCheck[][2] = {
      {}, {}, {792, 1283}, {645, 967}, {1084, 1897}, {772, 1119}
  };
```

• Reading the comments in the checking part of king danger analysis, I noticed that the comments are wrong. They use "we" in the same sentence with two different meanings (one of them wrong), and anyway"we" is confusing because of the template parameter "Us". Better to remove all occurence of "we", as follows:

```
// Enemy queen safe checks: count them only if the checks are from squares from
// which opponent can't give a rook check, because rook checks are more valuable.
```

```
// Enemy bishops checks: count them only if they are from squares from which
// opponent can't give a queen check, because queen checks are more valuable.
```

**Comment by FauziAkram** [comment]
Can't wait for it t get merged, so I can start to test some tuning

**Comment by vondele** [comment]
@FauziAkram I want to merge this together with the first functional change, so that not all devs have to update their branches for a non-functional change. However, if you want to tune this you can easily get this in your own branch, just do something like:

```
git checkout -b Rocky640-ArrayStyle4 master
git pull git://github.com/Rocky640/Stockfish.git ArrayStyle4
```

and you'll be having a new branch with the name `Rocky640-ArrayStyle4` on which you can work.

**Comment by vondele** [comment]
Thanks!

**Pull request closed without merging**
