### PR TITLE
Tuned PSQT

### PR DESCRIPTION
**Pull request by lucasart**
**STC**
```
LLR: 3.11 (-2.94,2.94) [-0.50,4.50]
Total: 58764 W: 11530 L: 11185 D: 36049
```
**LTC**
```
LLR: 0.66 (-2.94,2.94) [0.00,4.50]
Total: 261603 W: 42881 L: 41930 D: 176792
```
Never ending SPRT run, which is now beyond the theoretical 0.5% worst case of
longest runs for an SPRT(0,4.5). Theory predicts that SPRT stops in finite time,
with probability 1. But fishtest only uses a limited opening set, and we are
probably repeating many of the same games in shuffled order: not sure playing
another 260k games will add any valuable information.

In any case, this is more than enough resources we can afford to spend on a 1-2
elo patch, so I recommend we just commit and be done with it.

bench 8512947

### CODE REVIEW

**Comment by joergoster** [comment]
Finally passed, congrats!

**Comment by lucasart** [comment]
@zamar @glinscott @mcostalba: when merging, can you please edit the commit message with the final LTC result ?

**Comment by glinscott** [comment]
Nice!  Looks good :).

**Comment by zamar** [comment]
It passed, so approved. Never stop a stochastical test :-)

LLR: 2.96 (-2.94,2.94) [0.00,4.50]
Total: 282710 W: 46339 L: 45209 D: 191162

**Pull request closed without merging**
