### PR TITLE
Better naming in endgame code

### PR DESCRIPTION
**Pull request by mcostalba**
And small clean-up of magic bitboards code.

No functional change.

### CODE REVIEW

**Comment by mstembera** [comment]
In case you like it magic_index() could further be reduced to this.
```C++
template<PieceType Pt>
inline unsigned magic_index(Square s, Bitboard occupied) {

  const Magic& M = Pt == ROOK ? RookMagics[s] : BishopMagics[s];

  if (HasPext)
      return unsigned(pext(occupied, M.mask));

  if (Is64Bit)
      return unsigned(((occupied & M.mask) * M.magic) >> M.shift);

  unsigned lo = unsigned(occupied) & unsigned(M.mask);
  unsigned hi = unsigned(occupied >> 32) & unsigned(M.mask >> 32);
  return  (lo * unsigned(M.magic) ^ hi * unsigned(M.magic >> 32)) >> M.shift;
}
```

**Comment by mcostalba** [comment]
@mstembera thanks. Patch updated.

**Comment by mcostalba** [comment]
I have found a possible speed-up  de-templetizing magic_index(), but I would like a confirmation because my testing environment is very noisy.

It is anyhow a possible simplification.

**Comment by vondele** [comment]
For me the branch is performance neutral up to 01b0d23 but a little (0.3%) slower at 07583d9

**Comment by CoffeeOne** [comment]
I compared patched version commit De-templetize magic_index() (Build 1)
with current master.
Master is Build 2
Windows 10, gcc 7.1.0 profile-build (modern) Amd FX CPU, 8 Threads
No speed up for me, too.

Command Line: bench 16 1 15 default depth
Tests per Build: 100
ANOVA: n/a
                Engine# (NPS)                     Speedup     Sp     Conf. 95%    S.S.
2  (1.962.059,9   ) ---> 1  (1.953.856,7   ) --->  0,420%  19.857,6     Yes       No

**Comment by mstembera** [comment]
For me the templetized vs non-templetized versions are very similar.
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    372605    373214    -609      
    StDev   20483     20951     2251      

p-value: 0.607
speedup: 0.002
```

**Comment by CoffeeOne** [comment]
@mstembera 
372605 Nodes?? I do not want to offend you, but this seems to be a really slow CPU, no?

**Comment by mstembera** [comment]
@CoffeeOne 
Nice catch and no offense taken.  It is an old 2 core laptop but yes I usually get higher than above.  My guess is either some service was running in the background or it throttled itself back due to heat.  The nice thing is that the above result is still valid because Fishbench runs both versions concurrently.  Indeed it is statistically the same as my new fresh result below. 

```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    774686    775338    -652      
    StDev   83484     82944     8139      

p-value: 0.532
speedup: 0.001
```

**Comment by mcostalba** [comment]
Thanks to all for testing!

Probably this kind of change could be better detected with a perft test more than standard bench.

Anyhow I assume patch is speed neutral.

**Comment by snicolet** [comment]
• tbprobe.cpp, line 541: `defintion` -> `definition`
• search.cpp, line 337: `for(int` -> `for (int`

**Comment by mcostalba** [comment]
@snicolet thanks.

I have unified the commits into a single one, ready for merging.

**Pull request closed without merging**
