### PR TITLE
Do not use SEE in evasion scoring

### PR DESCRIPTION
**Pull request by snicolet**
Idea by Aram Tumanian (atumanian)

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 43889 W: 7849 L: 7767 D: 28273

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 29333 W: 3809 L: 3700 D: 21824

Bench: 6421663

### CODE REVIEW

**Comment by snicolet** [comment]
@atumanian: I _supposed_ that your complete name is "Aram Tumanian" based on your github login (atumanian) and the beginning of you gmail address as shown in the forum (aram.t...@gmail.com). Is that guess correct? :-) Congrats for the original idea!

**Comment by atumanian** [comment]
Yes, it's my name. Thank you!
The idea appeared while I was working on optimisation of the Position:see function. I had even decided to run your exact test after my test would have completed.
It's a very important simplification because it's the only place where the value returned by see isn't immediately compared with a value.
My optimisation is ready and gives about 2% to the overall speed of the engine: https://github.com/atumanian/Stockfish/tree/see
I'll create a pull request after yours is merged. (Or create it now?)

**Comment by atumanian** [comment]
I've created a pull request for my optimisation which includes your patch: https://github.com/official-stockfish/Stockfish/pull/820

**Comment by mcostalba** [comment]
Merged with 1e586288ca

**Pull request merged**
