### PR TITLE
Increase value of pawns on fifth rank

### PR DESCRIPTION
**Pull request by snicolet**
This patch increases the endgame value of pawns on the fifth rank.
The increase is very small (+1 evaluation point, about 0.005 pawn)
for the pawns on external columns (a-b-c-f-g-h) and a bit bigger
(+7 evaluation points, about 0.033 pawn) for the pawns on d5/e5.

STC:
LLR: 2.93 (-2.94,2.94) {-0.50,1.50}
Total: 79864 W: 15331 L: 15027 D: 49506
Ptnml(0-2): 1336, 9284, 18433, 9498, 1381
https://tests.stockfishchess.org/tests/view/5ef73e2ef993893290cc0c47

LTC:
LLR: 2.94 (-2.94,2.94) {0.25,1.75}
Total: 47240 W: 5927 L: 5630 D: 35683
Ptnml(0-2): 320, 4133, 14440, 4384, 343
https://tests.stockfishchess.org/tests/view/5ef7c0c4f993893290cc14b7

closes https://github.com/official-stockfish/Stockfish/pull/2776

Bench: 4260499

### CODE REVIEW

**Comment by snicolet** [comment]
@vondele There are two running tests at the moment with even more increase for d5/e5, which I would favor over this PR if they passed:
https://tests.stockfishchess.org/tests/view/5ef812df020eec13834a945c
https://tests.stockfishchess.org/tests/view/5ef81280020eec13834a9459

With the fleet on it should be only a couple of minutes to know if they are good

**Comment by vondele** [comment]
looks like neither of these two tests passed STC. Let's go with this one.

**Comment by snicolet** [comment]
OK :-)

**Comment by vondele** [comment]
Thanks!

**Pull request closed without merging**
