### PR TITLE
Introduction-To-Stockfish

### PR DESCRIPTION
**Pull request by TheNanik**
When I started exploring stockfish, even with some programming experience it was a bit difficult to figure out the architecture using the Wikipedia docs(I think they are more detailed then they should be for a basic description), so I decided to write one myself so that after reading the document, not much further theory is required and people can straightaway get into reading the code and improving it with a basic understanding of programming.

### CODE REVIEW

**Comment by MichaelB7** [comment]
It might need some edits, but good suggestion

**Comment by Sopel97** [comment]
Incomplete, misleading, and in most places blatantly wrong. This is useless for developers and can be harmful for non-developers.

**Comment by TheNanik** [comment]
> Incomplete, misleading, shallow, and in most places blatantly wrong. This is useless for developers and can be harmful for non-developers.

I am new to programming and what I wrote is what I think can be understood by non-devs, I know I am wrong so can you please specify what part you found "Blatantly wrong". I just want to improve my skills and get better, would be grateful for any help.

**Comment by vondele** [comment]
I haven't read the text, but of course, criticism should be constructive. I would agree we miss a good introduction to the code for non-experts. Probably the best place to have that would be a wiki page.(maybe near https://github.com/glinscott/fishtest/wiki/Creating-my-first-test)

**Comment by Sopel97** [comment]
Since I have some more time now

> Stockfish can be classified into 3 main parts: 1. [...] 2. [...] 3. [...]

Stockfish codebase has definitely more than 3 main parts. Arguably one could consider search, classic evaluation, nnue evaluation, uci handling, TB probing, time management, game state tracking, and move generation as all being distinct main parts.

> 1.Evaluation Function: This is designed for resolved positions(no captures or checks)

"resolved" is more commonly named "quiet". It would be good to have a reasonable explanation of why it's not made for any position.

> if the position is not resolved we basically go down in the move tree and reach a resolved position which can be evaluated using the evaluation function. 

This could be expanded to explain qsearch or at least explain how the quiet position is reached. It's not just any going down in the move tree, it's well defined and tries to reach sensible quiet position.

> Stockfish has different Opening/Midgame and Endgame evaluation function which smoothly transition as the game progresses. 

Not really. Disregarding NNUE here (as it's not the point) Stockfish has a single [classical] evaluation function. This single evaluation function always produces two values. These two values are interpolated based on scale factor which is rough estimate of how advanced the stage of the game is.

> What Evaluation function basically does is, it looks at a position and just like human(but more critically) evaluates different strategic advantages like:

"but more critically" is vague. No strategic advantages are evaluated. It's a **static** evaluation. It evaluates patterns it sees on the board and lacks the understanding of the dynamism of chess.

> 1.King Safety      2.Pawn Structure      3.Material Imbalance       4.Space advantage/Piece mobility etc.

This is severly oversimplified. Classical evaluation consists of: material (psqt), imbalance (which is evaluation of material diffence as opposed to just material), evaluation of separate major pieces (which considers not only piece placement but also attacks and whether a piece is defended) going from least to most valuable, evaluation of pawn structure which should be a separate topic in itself (there's also a whole bit dedicated solely to passed pawns), evaluation of the king (in particular king safety), threat evaluation (like immediate checks, pieces threatened by pawns immediately or in the next move, harassed queens), space/mobility, complexity/initiative (which affects scale factor too).

> 2. Minimax algorithm:

Putting this as a supposed part of stockfish is at least disrespectful. While minimax is the basis for alpha-beta it's nowhere relevant to stockfish. This point could only fit as a preliminary and nothing else.

> 3. Alpha-Beta pruning:

> you would know that the engine asks for how many lines to look for, this is where this algorithm comes in, lets say you chose 3 lines

umm? what? That would be multiPV and is completely irrelevant

> what Alpha-Beta pruning does is, it choses and limits the search to only favourable lines.(Ex: You have 3 lines leading to a significant advantage, then there is no point of searching further in the losing lines, you can simply reject the losing lines and focus on winning ones, that is what Alpha-Beta pruning does.)

I'm not sure this is quite right either. Alpha-beta is about removing the unnecessary search for refutations. If one refutation is found there's no need to look for a better one so many subtrees are cut. The cuts happen when considering opponent's moves and after at least one was considered. What you describe sounds more like futility pruning or move count pruning.

With that said alpha-beta is only one of many pruning techniques in stockfish and I wouldn't be surprised if it was not the most impactful one now. Not talking about other pruning techniques used is ignoring years of development and gives only a glimpse of what stockfish's search is.

> We can form a roadmap to selecting the best move:
Move tree     >    Evaluation function evaluates different positions   >   Minimax choses the best possible moves.       Simulatneously Alpha-Beta pruning limits the branches to be further evaluated.

It's not a sequence, it's not the whole picture, there's no such thing as a "move tree". "Minimax choses the best possible moves.       Simulatneously Alpha-Beta pruning limits the branches to be further evaluated." is like saying that that mathematics proves all conjectures and humans choose which.

> When Stockfish was written, its evaluation function was written according to strategies humans use to analyze a position all it did was just do it more critically and accurately. But as one would guess, there can be some flaws with human methods of evaluating a position and some unturned stones in this process.

Ironically stockfish's evaluation is not more accurate than human evaluation, stockfish needs thousands/millions of nodes evaluated to match human performance. Again "more critically" is vague. One could maybe say that it's more systematic and wide in scope.

> With advancement in AI and Neural Networks, it became clear from DeepMind's research that Stockfish does not have the best evaluation function and there are some flaws to it, which in my opinion is not a surprise, after all we are humans.

It was always known that stockfish's evaluation function was simple and bad and that making it better would make the engine better. No rocket science here. The continuous improvements of it were the manifestation of that. What deepmind's research shown is only that more accurate evaluation functions are viable. It's still not clear whether they are better.

> This is the method Alpha Zero and Lc0 use and learning from it, we introduce Stockfish's own Neural Evaluation function NNUE. 

this is just disrespectful to the authors of NNUE and doesn't serve any other purpose.  

> NNUE not only improved Stockfish's chess strength but also marks a new Stockfish era making it stronger than it ever was.

This is something that you could put into an opinionated book, not into a documentation.

> Stockfish    - Classical Evaluation Function        =    Stockfish NNUE(Much stronger than Classical Stockfish)
             + NNUE Evaluation Function

???

**Comment by TheNanik** [comment]
>Stockfish codebase has definitely more than 3 main parts. Arguably one could consider search, classic evaluation, nnue evaluation, uci handling, TB probing, time management, game state tracking, and move generation as all being distinct main parts.

ofc, but for a beginner, TB probing, time management, game state tracking etc. are not something which needs to be part of "Introduction", I thought the introduction just gives you a "Basic" overview of how from a given position, it finds the next move, I felt that for beginners Less is More, i.e. I simplified as much as I could.

>"resolved" is more commonly named "quiet". It would be good to have a reasonable explanation of why it's not made for any position.
I completely agree, I realize this is something I could have worked on better. 

>Not really. Disregarding NNUE here (as it's not the point) Stockfish has a single [classical] evaluation function. This single evaluation function always produces two values. These two values are interpolated based on scale factor which is rough estimate of how advanced the stage of the game is.

Well, this is something I was not so sure about, so adopted from Wiki, which clearly states eval. functions being different.

>"but more critically" is vague. No strategic advantages are evaluated. It's a static evaluation. It evaluates patterns it sees on the board and lacks the understanding of the dynamism of chess.

yeah "more critically" was meant to sate that in a more mathematical way, strategic advantage may not be the right term, positional advantage(how different pieces are set up relative to each other) can be used.

>This is severly oversimplified. Classical evaluation consists of: material (psqt), imbalance (which is evaluation of material diffence as opposed to just material), evaluation of separate major pieces (which considers not only piece placement but also attacks and whether a piece is defended) going from least to most valuable, evaluation of pawn structure which should be a separate topic in itself (there's also a whole bit dedicated solely to passed pawns), evaluation of the king (in particular king safety), threat evaluation (like immediate checks, pieces threatened by pawns immediately or in the next move, harassed queens), space/mobility, complexity/initiative (which affects scale factor too).

agreed, but again, you don't teach everything in introductory class, when you took your Calculus class, did you instructor taught you everything from Taylor series to Leibniz work to Vector Calculus and its physical meaning, No, right, he must have just taught you some terms like gradient, minima, maxima etc., that's what I tried to do, just giving a simplified version, and you may be right, but to me writing every intricacy did not feel right. 

>I'm not sure this is quite right either. Alpha-beta is about removing the unnecessary search for refutations. If one refutation is found there's no need to look for a better one so many subtrees are cut. The cuts happen when considering opponent's moves and after at least one was considered. What you describe sounds more like futility pruning or move count pruning.

With that said alpha-beta is only one of many pruning techniques in stockfish and I wouldn't be surprised if it was not the most impactful one now. Not talking about other pruning techniques used is ignoring years of development and gives only a glimpse of what stockfish's search is.


have you ever taken an introductory class in anything? if yes what did they taught you, a basic idea and a primitive way of working or directly the state of the art tech and told you every possible thing in a single lesson?

>It's not a sequence, it's not the whole picture, there's no such thing as a "move tree". "Minimax choses the best possible moves. Simulatneously Alpha-Beta pruning limits the branches to be further evaluated." is like saying that that mathematics proves all conjectures and humans choose which.

ok you write a roadmap, II will follow it.

>Ironically stockfish's evaluation is not more accurate than human evaluation, stockfish needs thousands/millions of nodes evaluated to match human performance.

So you are saying a human can evaluate any given position better than stockfish?

>this is just disrespectful to the authors of NNUE and doesn't serve any other purpose.

hundred percent agreed, I believe the NNUE part is not properly written, but all the flaws you pointed out in Classical Eval. can be more or less compiled in one sentence "Not deep enough intro", bro it is intro. 

I am just being respectful so why don't you calm down and think that an Intro is not meant to be deep, I wrote it to be understandable by the common public, the people with 0 understanding of any programming language.

**Comment by Sopel97** [comment]
So you seem to have changed your goals midway. Initially it was about helping developers in understanding and improving the codebase. Now it's about teaching general public about the core ideas behind stockfish. Though half of my points about correctness still stand as incorrect information is harmful to both groups of recipents regardless of how you look at this.

Now I don't really understand your comparisons to teaching maths so I won't address these points one by one. Do you really consider this writing to be on par with an introductory course to calculus?

**Comment by TheNanik** [comment]
>helping developers in understanding and improving the codebase.
 not the people already working on it, but the people who are new and have no knowledge whatsoever might find it helpful although it is primitive.

>correctness still stand as incorrect information is harmful to both groups of recipients regardless of how you look at this.
Well, most of your points about correctness just refer to Alpha-beta which I thought although primitive is easy to understand. 

The calculus part was just an example that passed over your head.

>Though half of my points about correctness still stand

what you want is just writing the features and giving definitions to different algorithms. Which was the part I was trying to avoid, anyway drop it, I accept that what I wrote obviously had some flaws but what I am saying is it would be great if some document teaching architecture to common people would be useful.

**Comment by adentong** [comment]
Honestly I think sf's codebase is complex enough that an introductory one-pager just isn't gonna make it any clearer. Like if you just gloss over a bunch of concepts then when new sf developers starts reading the code they're still gonna be confused. And if you want this to be a detailed document that's useful to seasoned developers then I agree with Sopel97, even if his words may have been a little harsh, that this needs a lot of edits to be complete, accurate, and useful. It's not like I don't understand why you decided to write this document, but ultimately reading, trying to understand, and exprimenting with the codebase is the best way to get started, and there are lots of resources online (such as the chessprogramming wiki) to help with any unfamiliar concept or techniques that sf uses.

**Comment by TheNanik** [comment]
The point I accept the flaws, but Tomasz was being straight up disrespectful which I don't think anyone likes, even now I agree with him, but man there is a proper way to put up things.

**Comment by Sopel97** [comment]
> The calculus part was just an example that passed over your head.

That's aside the point, but why do make comparisons to prove your point and later claim the comparison is irrelevant?

**Comment by TheNanik** [comment]
Dude do you understand what "Agreed" means I am not saying that use what I have written or anything, I am just saying a similar thing is much needed. If you think you can do it better, please go ahead.

**Comment by Sopel97** [comment]
See that's something I don't like. You act disrespectfully towards me just because you _think_ I'm disrespectful towards you. You went defensive because I criticisized your work as if I was attacking you personally. "ok you write a roadmap, II will follow it." [triggered me](https://en.wikipedia.org/wiki/Ad_hominem) enough to pursue this thread further than it should have lasted.

**Comment by TheNanik** [comment]
I am sorry on my part and this is the last message from my side, move on.

**Pull request closed without merging**
