### PR TITLE
Use multiple threads for bestMoveChanges (test thread sanitizer)

### PR DESCRIPTION
**Pull request by xoto10**
PR created to test if this code does pass Travis and AppVeyor builds. See #2065

### CODE REVIEW

**Comment by xoto10** [comment]
I've updated the code to remove the mutex, move variables into Threads, etc. Store and load seem ok with atomic<double> but I'm not sure how to do the fetch_add and fetch_mult :-(
I can see cppreference.com and so on, but can't quite grasp if this can be done, and how :-(

**Comment by xoto10** [comment]
Latest commit uses a mutex again, but bmcUpdateLimit is removed and now using Threads struct instead of MainThread. atomic doesn't appear to work well with doubles, and even if bestMoveChanges is made an int, I can't see an atomic operation to divide it by 2.

**Comment by xoto10** [comment]
I've created a new branch [timeall6ts2](https://github.com/xoto10/stockfish-xoto10/commits/timeall6ts2) that passes thread sanitizer using atomics. See [diff](https://github.com/xoto10/stockfish-xoto10/compare/7133598...b02b3c8). It uses an atomic integer bestMoveChanges variable on each thread, "incrementing" by 16 and then dividing by 2 to do the fade.

The first commit does some simple assignments to the changes variable and passes thread sanitizer, the second includes some order specifications, but these are really just guesses from me. Both show promise on very short local tests (unlike the latest push on this PR branch) so any comments gratefully received. I will run some local tests and wait a day or two for comments (and any further thoughts of my own) before trying more tests on fishtest ...

**Comment by mcostalba** [comment]
Can we close this one for the time being? It is mainly a WIP.

**Comment by xoto10** [comment]
Yes, sure. I created it for discussion ... but efforts are focused
elsewhere atm.

Perhaps I'll open a thread in fishcooking instead, that is maybe more
appropriate ...

**Pull request closed without merging**
