### PR TITLE
Stockfish 15.1 release candidate

### PR DESCRIPTION
**Pull request by vondele**
Todo:

- [x] draft release notes

- [x] finish progression tests
* https://tests.stockfishchess.org/tests/view/638a4dd7d2b9c924c4c6297b (LTC) 
* https://tests.stockfishchess.org/tests/view/638a4ddfd2b9c924c4c6297e (SMP) 
* https://tests.stockfishchess.org/tests/view/638a5361d2b9c924c4c62a68 (FRC) 
* https://tests.stockfishchess.org/tests/view/638a6170d2b9c924c4c62cb4 (DFRC) 
* https://tests.stockfishchess.org/tests/view/638a5275d2b9c924c4c62a3c (UHO)

- [x] watch out for release blocking new issues

Bench: 3467381

### CODE REVIEW

**Comment by Disservin** [comment]
`watch out for release blocking new issues` run matetrack for latest merged patches?

**Comment by vondele** [comment]
> `watch out for release blocking new issues` run matetrack for latest merged patches?
looks good https://github.com/vondele/matetrack

**Comment by XInTheDark** [comment]
Congrats on the progress made so far! 🎉

**Comment by mstembera** [comment]
FYI https://github.com/official-stockfish/Stockfish/pull/4220#issuecomment-1336263806

**Comment by joergoster** [comment]
@vondele Why not Stockfish 16? There is plenty of time since the last release and a good bunch of improvements. The next full version number seems justified, IMHO.

**Comment by vondele** [comment]
There is definitely enough to release to users, the progress in standard chess is there, but smaller than what would usually be major version update. We have no pressure to 'market' a major version update IMO.

**Comment by joergoster** [comment]
Lol. I expected that answer. No problem.

**Comment by Armand012** [comment]
Congrats, great work 🎉

**Comment by vondele** [comment]
closing with 758f9c9350abee36a5865ec701560db8ea62004d

**Pull request closed without merging**
