### PR TITLE
Nolocks2

### PR DESCRIPTION
**Pull request by zamar**
Original test passed:
http://tests.stockfishchess.org/tests/view/54f3956e0ebc5902160ebee8

This is supposed to be a cleaner implementation, but functionally identical

Opening up the pull request for discussion. Confirmation test is running:
http://tests.stockfishchess.org/tests/view/54faca180ebc5902160ebfd1

### CODE REVIEW

**Comment by glinscott** [comment]
Awesome stuff, thanks Joona and Marco!  Removing the global mutex should be a big win as SF scales up to more cores.

**Comment by AlexandreMasta** [comment]
The stuff without clean up seems to be stronger.
http://tests.stockfishchess.org/tests/view/54f3956e0ebc5902160ebee8

**Comment by zamar** [comment]
@AlexandreMasta:

- Please wait until the test is finished.
- These kind of comments are just useless noise.

**Comment by zamar** [comment]
Unfortunately the cleaned up version did quite badly:

ELO: 1.55 +-2.9 (95%) LOS: 85.7%
Total: 19009 W: 3230 L: 3145 D: 12634

Compared to the original test:

ELO: 6.64 +-2.8 (95%) LOS: 100.0%
Total: 20000 W: 3482 L: 3100 D: 13418

Again this shows the difficulty of fine-tuning SMP code.
The cause might just be that a different set of machines was used, but still the difference is suspiciously big.

The only real functional difference was the number of mutexes. I'll convert the cleaned up version back to two mutex version and let's see what happens...

**Pull request closed without merging**
