### PR TITLE
Set bits instead of clearing bits in semiopenfiles

### PR DESCRIPTION
**Pull request by protonspring**
Instead of setting semiopenFiles to 0xFF and clearing bits for existing pawns, it seems faster to set bits for existing pawns and ~ at the end.  Hard to believe it makes much difference, but it seems faster on my machine.  I'm just posting here to see if others see the same (which is what the README says to do).

200 runs of psybench:
base: 1271642 +/- 6216
test: 1294405 +/- 6458
diff:     +22763 +/ 751.
speedup   = 0.0179
P(speedup > 0) = 1.000

### CODE REVIEW

**Comment by CoffeeOne** [comment]
It's a small slowdown for me:
Windows gcc7.3 profile-build with lto, engine1 master engine2 test-repo branch ps_semiopen
AMD FX(tm)-9590 Eight-Core Processor           
Command Line: bench 16 1 16  default depth
Tests per Build: 30
                Engine# (NPS)                     Speedup     Sp     Conf. 95%    S.S.
1  (1.593.740,1   ) ---> 2  (1.590.752,6   ) --->  0,188%  7.994,1      No        No 
**

**Comment by snicolet** [comment]
Yes, please run a sprt[0..4]

**Comment by protonspring** [comment]
In the future, wouldn't be better for everyone's time to do a 0,4 on the framework first?  If it passes, then we can all think about it.  If not, it's dead, no PR and I don't waste people's time.

**Comment by Rocky640** [comment]
We need a clarification here.
Wiki stills says [0, 5] for speed ups...

I also think that if the "speed up " add complexity, [0, 5] is called for.
Rationale is that "complexity", once added, might not be strong enough to resist a [-3, 1] simplification later. So it might also make sense to directly run a reverse [-3, 1]  (test against master) in some cases.

There is also the uglification factor.

**Comment by vondele** [comment]
As a data point, there was a long discussion in https://github.com/official-stockfish/Stockfish/pull/1113 about speedups and sprt bounds.

**Comment by CoffeeOne** [comment]
I think (especially for non functional patches) we really need a new fishtest option, for "speedtest", it seems really a waste of resources to measure a speedup / slowdown via playing games. And indvidual bench runs of a small amount of users are very often misleading.

**Comment by protonspring** [comment]
The test failed yellow.  Therefore, there does not seem to be any appreciable speed difference.  With the patch being not as pretty, I'll close this PR.
http://tests.stockfishchess.org/tests/view/5adf3a390ebc590331056b68

**Pull request closed without merging**
