### PR TITLE
Download the default NNUE net in AppVeyor

### PR DESCRIPTION
**Pull request by gvreuls**
This is a partial PR concerning NNUE CI and PGO builds requested by
@vondele, it modifies the appveyor script so it downloads the default
NNUE net before the stockfish bench is run.

If have avoided using aliases like cat and echo because I don't know if
these are defined in the appveyor environment.

Note: I can't guarantee 100% that this works because to my knowledge
there is no way of testing the script before making the PR.

No functional change.

### CODE REVIEW

**Comment by vondele** [comment]
@gveuls probably the net needs to be put in `cd src/%CONFIGURATION%` since that seems to be where the engine is put.

**Comment by gvreuls** [comment]
@vondele I cant get the %CONFIGURATION% stuff to work, appveyor refuses to replace it with Debug/Release in my script. This is something for the appveyor specialists.

**Comment by vondele** [comment]
could it be you have to create the directory pre-download time, it doesn't exist, presumably, till the build has started.

**Comment by gvreuls** [comment]
@vondele The problem seems to be that %CONFIGURATION% isn't a real powershell variable but something appvayor replaces on the fly in some places but not in others. I've wasted six commits trying to get it to work and I'm at the end of my wits here, we really need somebody who knows how you're supposed to do this in appveyor.

**Comment by vondele** [comment]
Seems you found it, great!

**Comment by gvreuls** [comment]
@vondele Never mind my last post, it's working now, %CONFIGURATION% is a windows environment variable that must be accessed as ${env:CONFIGURATION} in powershell.

**Comment by vondele** [comment]
I'll close this, will be part of https://github.com/official-stockfish/Stockfish/pull/2931

**Pull request closed without merging**
