### PR TITLE
Non-quiet pruning tweak

### PR DESCRIPTION
**Pull request by locutus2**
Count in the difference of static evaluation and alpha for pruning threshold.

STC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 16885 W: 3061 L: 2866 D: 10958

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 33566 W: 4428 L: 4202 D: 24936

Bench: 5513149

### CODE REVIEW

**Comment by VoyagerOne** [comment]
@locutus2 
Congrats!  Clearly the original formula is far from optimized.
I am hoping your simplified version will pass.

**Comment by locutus2** [comment]
@VoyagerOne 
Sorry, the simplification failed.

**Comment by VoyagerOne** [comment]
@locutus2 
One experiment you may try is to use a different weight/equation for PV nodes

**Comment by locutus2** [comment]
@VoyagerOne 
Interresting idea, but first i will do some measurements.
But in the meantime i would commit this patch.

**Comment by mcostalba** [comment]
Merged with a90fc4c877b39769

**Pull request closed without merging**
