### PR TITLE
Fix code indentation and other whitespace issues

### PR DESCRIPTION
**Pull request by UniQP**
This mainly fixes the code indentation in search.cpp but also contains some other whitespace-related code formatting fixes.

No functional change

### CODE REVIEW

**Comment by Sopel97** [comment]
Honestly, in the current state I think this is not a positive change. We don't have any actual guidelines, so it's possible that this effort will be overwritten in the future, and makes it harder to git blame.

**Comment by UniQP** [comment]
The code indentation is pretty consistent within `search.cpp` except for this one while loop (line 930+) that uses 2 rather than 4 spaces for indentation (and a few lines with 3 space indentation within this while loop).

**Comment by UniQP** [comment]
> […] it also makes it harder to git blame.

`git blame -w` ignores whitespace changes. So there is a nice solution for this (at least on the command line).

**Comment by ddobbelaere** [comment]
IMHO at some point (the sooner the better maybe), we should bite this bullet: https://github.com/official-stockfish/Stockfish/issues/3608 and be done with it. In the exceptional cases, manual formatting between `clang-format off/on` is still possible. At least the PSQT tables that are atrociously auto-formatted are now gone :)

**Comment by snicolet** [comment]
There are opinions that the code change in this commit is too invasive for a single pull request, so I'll close it for now. 
Thanks anyway, maybe some parts (the most horrible whitespace issues) can be integrated in SF codebase step by step in the future?

**Pull request closed without merging**
