### PR TITLE
Improve Readme.md about compiling

### PR DESCRIPTION
**Pull request by nguyenpham**
Reparagraph, add an example how to compile on Unix-like systems

### CODE REVIEW

**Comment by vondele** [comment]
It would be better to use `make -j profile-build ARCH=x86-64-modern` in the example, that will be suitable for most users.

**Comment by nguyenpham** [comment]
I use `make build ARCH=x86-64` from the first example when a user types `make help`. Do you want me to modify Makefile too for being consistent (all will be `make -j profile-build ARCH=x86-64-modern`)?

**Comment by vondele** [comment]
yes, updating help would be good. Also, move `profile-build` to the first line of supported targets, and call it `> standard build`, while `build` could be `> non-PGO build`.

**Comment by nguyenpham** [comment]
I have just tried to build with all `profile-build` commands: `make -j profile-build ARCH=x86-64-modern` and `make profile-build ARCH=x86-64-bmi2 COMP=gcc COMPCXX=g++-4.8`. They all failed on my computer (iMac 2017, Catalina). I have called `make clean` before calling them to make sure they wouldn't be affected by other compiling.

I may solve/ask help to solve that problem later. However, it looks like that kind of building has a higher chance of failing for newcomers. Thus I suggest keeping the current first example (`make build ARCH=x86-64`) since it is the safer one.

**Comment by vondele** [comment]
OK, interesting, let's keep in the form you have right now. 

Maybe file an issue for that, together with info on the compiler used, and the output of the compilation. I'm guessing this is specific to mac.

**Comment by nguyenpham** [comment]
In my computer gcc is actually clang and it is Apple clang version 11.0.3 (clang-1103.0.32.62) - quite up to date. I guess it is not the problem of too old compilers but too new ones ;)

**Comment by vondele** [comment]
so also the `g++-4.8` in the make command above links to clang? Anyway, that's most likely the reason. I can get clang to profile-build with the following:
```
make -j ARCH=x86-64-modern COMP=clang profile-build
```
with the following change to the makefile (providing the specific version of llvm-profdata):
```diff
diff --git a/src/Makefile b/src/Makefile
index 016aafec1..c42edcf4d 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -510,7 +510,7 @@ clang-profile-make:
        all
 
 clang-profile-use:
-       llvm-profdata merge -output=stockfish.profdata *.profraw
+       llvm-profdata-10 merge -output=stockfish.profdata *.profraw
        $(MAKE) ARCH=$(ARCH) COMP=$(COMP) \
        EXTRACXXFLAGS='-fprofile-instr-use=stockfish.profdata' \
        EXTRALDFLAGS='-fprofile-use ' \

```

**Comment by vondele** [comment]
see also https://github.com/official-stockfish/Stockfish/issues/2053

**Comment by nguyenpham** [comment]
My computer links g++ to clang but doesn't know g++-4.8. Your command `make -j ARCH=x86-64-modern COMP=clang profile-build` failed too:

```
nguyenpham@iMac src % make clean
nguyenpham@iMac src % make -j ARCH=x86-64-modern COMP=clang profile-build

Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: 'x86_64'
bits: '64'
kernel: 'Darwin'
os: ''
prefetch: 'yes'
popcnt: 'yes'
sse: 'yes'
pext: 'no'

Flags:
CXX: clang++
CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto
LDFLAGS:  -m64 -arch x86_64 -mmacosx-version-min=10.9 -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto

Testing config sanity. If this fails, try 'make help' ...


Step 1/4. Building instrumented executable ...
/Library/Developer/CommandLineTools/usr/bin/make ARCH=x86-64-modern COMP=clang clang-profile-make
/Library/Developer/CommandLineTools/usr/bin/make ARCH=x86-64-modern COMP=clang \
	EXTRACXXFLAGS='-fprofile-instr-generate ' \
	EXTRALDFLAGS=' -fprofile-instr-generate' \
	all
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o benchmark.o benchmark.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o bitbase.o bitbase.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o bitboard.o bitboard.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o endgame.o endgame.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o evaluate.o evaluate.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o main.o main.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o material.o material.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o misc.o misc.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o movegen.o movegen.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o movepick.o movepick.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o pawns.o pawns.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o position.o position.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o psqt.o psqt.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o search.o search.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o thread.o thread.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o timeman.o timeman.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o tt.o tt.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o uci.o uci.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o ucioption.o ucioption.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o tune.o tune.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o tbprobe.o syzygy/tbprobe.cpp
clang++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o tune.o tbprobe.o -fprofile-instr-generate -m64 -arch x86_64 -mmacosx-version-min=10.9 -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-instr-generate  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto

Step 2/4. Running benchmark for pgo-build ...
./stockfish bench > /dev/null

Position: 1/47

Position: 2/47

Position: 3/47

Position: 4/47

Position: 5/47

Position: 6/47

Position: 7/47

Position: 8/47

Position: 9/47

Position: 10/47

Position: 11/47

Position: 12/47

Position: 13/47

Position: 14/47

Position: 15/47

Position: 16/47

Position: 17/47

Position: 18/47

Position: 19/47

Position: 20/47

Position: 21/47

Position: 22/47

Position: 23/47

Position: 24/47

Position: 25/47

Position: 26/47

Position: 27/47

Position: 28/47

Position: 29/47

Position: 30/47

Position: 31/47

Position: 32/47

Position: 33/47

Position: 34/47

Position: 35/47

Position: 36/47

Position: 37/47

Position: 38/47

Position: 39/47

Position: 40/47

Position: 41/47

Position: 42/47

Position: 43/47

Position: 44/47

Position: 45/47

Position: 46/47

Position: 47/47

===========================
Total time (ms) : 3473
Nodes searched  : 4582693
Nodes/second    : 1319520

Step 3/4. Building optimized executable ...
/Library/Developer/CommandLineTools/usr/bin/make ARCH=x86-64-modern COMP=clang objclean
/Library/Developer/CommandLineTools/usr/bin/make ARCH=x86-64-modern COMP=clang clang-profile-use
llvm-profdata merge -output=stockfish.profdata *.profraw
/bin/sh: llvm-profdata: command not found
make[1]: *** [clang-profile-use] Error 127
make: *** [profile-build] Error 2

```

**Comment by vondele** [comment]
yes, you'll need to figure out how to get the `llvm-profdata` tool to run. Seemingly doesn't work (see issue above, or workaround I posted for ubuntu).

**Comment by MichaelB7** [comment]
Make an alias called “llvm-profdata” have it set to the actual llvm-profdata exe - name will vary by version name - add the path to the folder where the exe is located. My guess is that you are running  Catalina that upgraded from a Mac that was running Mojave.

**Comment by vondele** [comment]
Thanks!

**Pull request closed without merging**
