### PR TITLE
Simplify outpost code

### PR DESCRIPTION
**Pull request by mcostalba**
No functional change.

### CODE REVIEW

**Comment by Rocky640** [comment]
We have other masks that could enjoy a similar change
SpaceMask could be moved into evaluate_space
CenterBindMask could be moved into Pawns::evaluate

**Comment by zamar** [comment]
approved.

**Comment by mcostalba** [comment]
@Rocky640 Thanks! I have verified that the produced assembly has just the constants inlined, so it is even faster (although hardly measurable).

Pull updated.

**Comment by zamar** [comment]
re-approved.

**Pull request merged**
