### PR TITLE
Add Workflows for Make Windows Binaries

### PR DESCRIPTION
**Pull request by SriMethan**
This Pr allows to download latest Windows Binaries from workflow 
example - https://github.com/SriMethan/Stockfish/actions/runs/1265231322

### CODE REVIEW

**Comment by Sopel97** [comment]
A couple of issues I see with this:

- One .zip for all executables will quickly become a burden for users
- There are issues with the license and source not being provided with this distribution, which may be seen as a violation of the GPLv3 license. 
- A very small subset of builds is done
- No PGO
- It's too much for pull requests imo, should only happen on master commits. Possibly also only the ones that are functional?

Perhaps could be combined with https://github.com/official-stockfish/Stockfish/pull/3377 which tests the builds and packages them as required?

**Comment by vondele** [comment]
I think the time used in actions is not a problem if we're only doing this for commit to master. This is definitely a step in the right direction but I agree that aspects like PGO, and zipping with license and sources are important. Would be great if this could be combined with #3377 so that ultimately we have continuous releases.

**Comment by SriMethan** [comment]
I have a workflow file for releasing its not a python script and yes I can include license and the source code etc when downloading Windows Binaries from workflow. I will test and change

**Comment by vondele** [comment]
but have a look at the mentioned python script. It takes care of these things already, in addition to allowing for building PGO optimized binaries on architectures not supporting the instruction set.

**Comment by SriMethan** [comment]
I will send a new Pr with new changes

**Pull request closed without merging**
