### PR TITLE
Rank based threats.

### PR DESCRIPTION
**Pull request by mbootsector**
STC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 19404 W: 3581 L: 3374 D: 12449

LTC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 16204 W: 2194 L: 2023 D: 11987

Bench: 5757843

### CODE REVIEW

**Comment by AlexandreMasta** [comment]
COngrats! Nice scalability!

**Comment by MichaelB7** [comment]
This one looks real nice - good job!

**Comment by mcostalba** [comment]
Merged with e7289465b9ecb2ab93b

**Comment by ajithcj** [comment]
Congrats!! Very nice.

**Pull request closed without merging**
