### PR TITLE
Simplify extensions condition

### PR DESCRIPTION
**Pull request by XInTheDark**
This condition was originally added to guard against search explosions (as pointed out here: https://github.com/XInTheDark/Stockfish/commit/a4e90aca6599b539dd6acd0dea64f19ad2e95c79#commitcomment-112201835). In my local testing there does not seem to be degraded performance on test suites, although further verification of this is much appreciated.

Simplification STC: https://tests.stockfishchess.org/tests/view/645756faeb75932ccfec02ae
LLR: 2.96 (-2.94,2.94) <-1.75,0.25> 
Total: 261408 W: 69294 L: 69318 D: 122796
Ptnml(0-2): 616, 27810, 73824, 27890, 564

Simplification LTC: https://tests.stockfishchess.org/tests/view/6459ba9d8ab4042ca78960e6
LLR: 2.94 (-2.94,2.94) <-1.75,0.25> 
Total: 315774 W: 84894 L: 84969 D: 145911
Ptnml(0-2): 116, 29845, 98017, 29816, 93

Bench: 3802859

### CODE REVIEW

**Comment by locutus2** [comment]
I have checked this PR for the problematic position (`8/Pk6/8/1p6/8/P1K5/8/6B1 w - - 37 130`) from the original search explosion commit https://github.com/official-stockfish/Stockfish/commit/73018a03375b4b72ee482eb5a4a2152d7e4f0aac.

I stopped after 5 minutes and get only to depth 14:
```
info depth 1 seldepth 1 multipv 1 score cp -19 nodes 27 nps 27000 hashfull 0 tbhits 0 time 1 pv c3b3
info depth 2 seldepth 2 multipv 1 score cp -19 nodes 45 nps 45000 hashfull 0 tbhits 0 time 1 pv c3b3
info depth 3 seldepth 2 multipv 1 score cp -14 nodes 82 nps 41000 hashfull 0 tbhits 0 time 2 pv a7a8b b7a8
info depth 4 seldepth 4 multipv 1 score cp -3 nodes 147 nps 73500 hashfull 0 tbhits 0 time 2 pv g1b6
info depth 5 seldepth 3 multipv 1 score cp 14 nodes 477 nps 238500 hashfull 0 tbhits 0 time 2 pv c3b4
info depth 6 seldepth 4 multipv 1 score cp 29 nodes 827 nps 275666 hashfull 0 tbhits 0 time 3 pv g1b6 b7a8 c3b4
info depth 7 seldepth 5 multipv 1 score cp 36 nodes 1167 nps 389000 hashfull 0 tbhits 0 time 3 pv c3b3 b7a8 g1b6 a8b7
info depth 8 seldepth 6 multipv 1 score cp 36 nodes 5881 nps 840142 hashfull 1 tbhits 0 time 7 pv c3b3 b7a8 g1b6 a8b7 b3b4
info depth 9 seldepth 11 multipv 1 score cp 212 nodes 7988 nps 887555 hashfull 2 tbhits 0 time 9 pv c3b3 b7a8 g1b6 a8b7 b3c3 b7a8 c3b4
info depth 10 seldepth 13 multipv 1 score cp 473 nodes 8473 nps 847300 hashfull 2 tbhits 0 time 10 pv c3b4 b7c7 b4a5
info depth 11 seldepth 8 multipv 1 score cp 805 nodes 9082 nps 908200 hashfull 3 tbhits 0 time 10 pv c3b4 b7c7 b4a5
info depth 12 seldepth 14 multipv 1 score cp 423 nodes 9876 nps 897818 hashfull 3 tbhits 0 time 11 pv c3b4 b7a8 b4a5 a8b7 a7a8q b7a8 a5a6 a8b8 g1b6 b8c8 a6a7 c8d7
info depth 13 seldepth 19 multipv 1 score cp 342 nodes 12927 nps 923357 hashfull 3 tbhits 0 time 14 pv c3b4 b7a8 b4a5 a8b7 a7a8b b7a8 a5a6 a8b8 g1a7 b8c7 a7f2 c7c6 a6a7 c6c7 f2c5 c7c8 c5b6
info depth 14 seldepth 19 multipv 1 score cp 343 nodes 15234 nps 952125 hashfull 3 tbhits 0 time 16 pv c3b4 b7a8 b4a5 a8b7 a7a8b b7a8 a5a6 a8b8 g1a7 b8c7 a7f2 c7d7 a6b7 d7d6 f2b6 d6d5
```

For comparison i tried also the current master which is a little better (depth 16) but not really good:
```
info depth 16 seldepth 29 multipv 1 score cp 86 upperbound nodes 364057361 nps 2844109 hashfull 166 tbhits 0 time 128004 pv g1b6 b7a8
info depth 16 currmove g1b6 currmovenumber 1
info depth 16 currmove a7a8q currmovenumber 2
info depth 16 currmove c3b4 currmovenumber 3
info depth 16 currmove a7a8r currmovenumber 4
info depth 16 currmove a7a8b currmovenumber 5
info depth 16 currmove a7a8n currmovenumber 6
info depth 16 currmove c3b3 currmovenumber 7
info depth 16 currmove c3b2 currmovenumber 8
info depth 16 currmove g1h2 currmovenumber 9
info depth 16 currmove a3a4 currmovenumber 10
info depth 16 currmove c3d4 currmovenumber 11
info depth 16 currmove g1e3 currmovenumber 12
info depth 16 currmove g1f2 currmovenumber 13
info depth 16 currmove g1d4 currmovenumber 14
info depth 16 currmove c3d2 currmovenumber 15
info depth 16 currmove g1c5 currmovenumber 16
info depth 16 currmove c3c2 currmovenumber 17
info depth 16 currmove c3d3 currmovenumber 18
info depth 16 seldepth 29 multipv 1 score cp 82 upperbound nodes 1228894131 nps 2957292 hashfull 179 tbhits 0 time 415547 pv g1b6 b7a8
info depth 16 currmove g1b6 currmovenumber 1
```

So i tried some variations and come up with following which goes at least to depth 30 before it stucked:
=> add as additional explosion check the condition `2 * ss->doubleExtensions < thisThread->rootDepth`.
```
info depth 28 seldepth 57 multipv 1 score cp 43 nodes 31449355 nps 2494396 hashfull 651 tbhits 0 time 12608 pv c3b4 b7a8 b4a5 a8b7 g1b6 b7a8 a5b5 a8b7 b5a4 b7a8 a4b3 a8b7 b6f2 b7a8 b3c2 a8b7 f2e3 b7a8 e3b6 a8b7 c2d2 b7a8 d2e1 a8b7 e1f1 b7a8 a3a4 a8b7 f1e1 b7a8 b6f2 a8b7 e1e2 b7a8 a4a5 a8b7 e2d3 b7a8 f2b6 a8b7 b6d4 b7a8 d4f2 a8b7 d3c2 b7a8 c2b2 a8b7 f2c5 b7a8 c5b6 a8b7 a7a8b b7a8
info depth 29 currmove c3b4 currmovenumber 1
info depth 28 currmove a7a8q currmovenumber 2
info depth 28 currmove c3b3 currmovenumber 3
info depth 28 currmove a7a8r currmovenumber 4
info depth 28 currmove a7a8b currmovenumber 5
info depth 28 currmove a7a8n currmovenumber 6
info depth 28 currmove g1e3 currmovenumber 7
info depth 28 currmove g1h2 currmovenumber 8
info depth 28 currmove c3d4 currmovenumber 9
info depth 28 currmove c3d2 currmovenumber 10
info depth 28 currmove g1c5 currmovenumber 11
info depth 28 currmove g1d4 currmovenumber 12
info depth 28 currmove c3d3 currmovenumber 13
info depth 28 currmove g1b6 currmovenumber 14
info depth 28 currmove c3b2 currmovenumber 15
info depth 28 currmove a3a4 currmovenumber 16
info depth 28 currmove c3c2 currmovenumber 17
info depth 28 currmove g1f2 currmovenumber 18
info depth 29 seldepth 58 multipv 1 score cp 43 nodes 34876693 nps 2485156 hashfull 694 tbhits 0 time 14034 pv c3b4 b7a8 b4a5 a8b7 g1b6 b7a8 a5b5 a8b7 b5a4 b7a8 a4b3 a8b7 b6f2 b7a8 b3c2 a8b7 f2e3 b7a8 e3b6 a8b7 c2d2 b7a8 d2e1 a8b7 e1f1 b7a8 a3a4 a8b7 f1e1 b7a8 b6f2 a8b7 e1e2 b7a8 a4a5 a8b7 e2f1 b7a8 f2c5 a8b7 f1e1 b7a8 e1f2 a8b7 f2f3 b7a8 f3e3 a8b7 e3d2 b7a8 d2d3 a8b7 d3c3 b7a8 c5g1 a8b7 c3b2 b7a8 b2a3
info depth 30 currmove c3b4 currmovenumber 1
```

Because i think we can't really gain elo here i will test this idea as non-regression.

**Comment by locutus2** [comment]
Here is the test to my above idea: https://tests.stockfishchess.org/tests/view/645f6420d55cccb2e64234eb

**Comment by locutus2** [comment]
Here i try a variation of my first idea which simply combine the two conditions by adding up the parts. This is a little bit worse but reaches at least depth 27:

https://tests.stockfishchess.org/tests/view/645f69d1d55cccb2e6423555

```
info depth 26 seldepth 56 multipv 1 score cp 47 nodes 137806878 nps 2856278 hashfull 617 tbhits 0 time 48247 pv c3b4 b7a8 g1b6 a8b7 b6f2 b7a8 b4b5 a8b7 b5a4 b7a8 a4b3 a8b7 f2e3 b7a8 b3b2 a8b7 e3d4 b7a8 b2b1 a8b7 b1c2 b7a8 c2d2 a8b7 d2e1 b7a8 d4f2 a8b7 e1f1 b7a8 f1g2 a8b7 g2h1 b7a8 f2g1 a8b7 g1c5 b7a8 a3a4 a8b7 c5g1 b7a8 h1g2 a8b7 g2f3 b7a8 g1b6 a8b7
info depth 27 currmove c3b4 currmovenumber 1
info depth 26 currmove a7a8q currmovenumber 2
info depth 26 currmove c3b3 currmovenumber 3
info depth 26 currmove a7a8r currmovenumber 4
info depth 26 currmove a7a8b currmovenumber 5
info depth 26 currmove a7a8n currmovenumber 6
info depth 26 currmove a3a4 currmovenumber 7
info depth 26 currmove g1d4 currmovenumber 8
info depth 26 currmove g1h2 currmovenumber 9
info depth 26 currmove c3b2 currmovenumber 10
info depth 26 currmove g1b6 currmovenumber 11
info depth 26 currmove g1f2 currmovenumber 12
info depth 26 currmove g1c5 currmovenumber 13
info depth 26 currmove c3d2 currmovenumber 14
info depth 26 currmove c3d3 currmovenumber 15
info depth 26 currmove c3c2 currmovenumber 16
info depth 26 currmove c3d4 currmovenumber 17
info depth 26 currmove g1e3 currmovenumber 18
info depth 27 seldepth 43 multipv 1 score cp 47 nodes 144141581 nps 2827969 hashfull 636 tbhits 0 time 50970 pv c3b4 b7a8 g1b6 a8b7 b6f2 b7a8 b4b5 a8b7 b5a4 b7a8 a4b3 a8b7 f2e3 b7a8 b3b2 a8b7 e3d4 b7a8 b2b1 a8b7 b1c2 b7a8 c2d2 a8b7 d2e1 b7a8 d4f2 a8b7 e1f1 b7a8 f2b6 a8b7 f1g2 b7a8 a3a4 a8b7 g2f1 b7a8 b6c5 a8b7 c5g1 b7a8 f1g2
info depth 28 currmove c3b4 currmovenumber 1
info depth 27 currmove c3b3 currmovenumber 2
info depth 27 currmove g1h2 currmovenumber 3
info depth 27 currmove a7a8r currmovenumber 4
info depth 27 currmove a7a8b currmovenumber 5
info depth 27 currmove a7a8n currmovenumber 6
info depth 27 currmove c3d2 currmovenumber 7
```

**Comment by locutus2** [comment]
Two variants of my search explosion fixes passed STC and LTC non-regression test.

Version 1 (that seems the better version):
```
if (       ss->ply              < 2 * thisThread->rootDepth
          && 2 * ss->doubleExtensions <     thisThread->rootDepth)
```
STC: https://tests.stockfishchess.org/tests/view/645f6420d55cccb2e64234eb
LTC: https://tests.stockfishchess.org/tests/view/646047e1299f05d3ac7cf99e

Version 2:

`if (ss->ply + 2 * ss->doubleExtensions < 3 * thisThread->rootDepth)`

STC: https://tests.stockfishchess.org/tests/view/645f69d1d55cccb2e6423555
LTC: https://tests.stockfishchess.org/tests/view/64608e57299f05d3ac7cfe9f

For the test position 8/Pk6/8/1p6/8/P1K5/8/6B1 w - - 37 130 following depth are reached in resonable time:
```
master:       depth 16
PR:           depth 14
Version 1:    depth 30
Version 2:    depth 27
```

It would be good if we have a test suite especially for search explosions but in the absence of one i used the matetrack suite for further validation. There Version 1 seems also the best (except master).

master:
```
Total fens:    6566
Found mates:   3478
Best mates:    2351
```

PR:
```
Total fens:    6566
Found mates:   3484
Best mates:    2323
```

Version 1:
```
Total fens:    6566
Found mates:   3481
Best mates:    2331
```

Version 2:
```
Total fens:    6566
Found mates:   3461
Best mates:    2317
```

@vondele 
should i open a PR for my Version 1? What is the opinion of the other devs?

**Comment by vondele** [comment]
I don't think the condition should be simplified away. I would think that a PR with @locutus2 version instead would be OK. I have a slight preference for version 2, since it is a single condition, rather than two conditions. To more objectively judge which version is best, we would need a testsuite, which we don't really have.

**Pull request closed without merging**
