### PR TITLE
Build SF as a shared library. Handle errors with exceptions. Example of using SF with JNI

### PR DESCRIPTION
**Pull request by ab-chesspad**

### CODE REVIEW

**Comment by Sopel97** [comment]
This is a lot of unrelated changes. Also, what's the point of this when there's UCI? Any why is it only restricted to linux and Java?

**Comment by ab-chesspad** [comment]
Actually, there are only two 'unrelated' changes. The main goal is to build
SF as a shared library. This is needed because the latest Android does not
allow running SF as a separate process (this is why Droidfish and my own
ChessPad cannot be updated in PlayStore anymore).
Using exceptions is the result of this architectural change, because we
cannot allow an Android program to crash, it's considered the program
defect.
The second issue is nnue. This option increases the program size x10 and
for my purposes is unnecessary. The existing macro NNUE_EMBEDDING_OFF is
not used consistently, there is no option to control its value with build
parameters and the large nnue file is being downloaded anyway.
Lastly, I do not have a Windows machine, so I have not touched anything
Windows-related in SF.
Cheers
Alex Bootman

**Comment by Sopel97** [comment]
sounds like an android issue, not stockfish issue

**Comment by ab-chesspad** [comment]
Probably, but what is your point? To have two separate code bases? Then why
have the same codebase for Windows, Linux, Mac?

Thank you
Alex Bootman

**Comment by MichaelB7** [comment]
The changes are quite invasive, more so than the typical OS differences.  The lastest Android OS does allow running SF as a separate process , it is simply the PlayStore that no longer accepts programs that do that.  There are many users of Android devices who do use the Playstore for obtaining their apps, in essense you change are not needed universally by all Androird users , just those who relied upon the Playstore. I'm not in favor of this patch

**Comment by ab-chesspad** [comment]
The problem is that the current Android SDK 30 (and 29 as well, if I am not
mistaken) does not allow using SF as a separate process. Playstore is just
enforcing this policy, requiring apps to be build with the latest SDK.
As far as I know, Playstore is the only legacy way to obtain/install
Android apps for the regular users. Of course, it's possible to install
Android development tools and install apps via adb, but I would not rely on
that.
My opinion is, that unless you want to cut off Android users from
Stockfish, SF should have an option to run in shared library.
In fact, the related changes are not that big. I just introduced Outstream
class and replaced sync_cout macro. The rest was just the consequences.
Thank you
Alex Bootman

**Comment by MichaelB7** [comment]
Building with SDK 28 works fine.  It's not the end of the world.

**Comment by MichaelB7** [comment]
> Apps built with sdk 28 are not accepted in Play Store. As I have said, if you don't care about android users, you can ignore all the required efforts. Of course, it's not the end of the world, it's just the end of good programming practice. Cheers Alex Bootmam

Why do you buttress your argument with a personal attack "if you don't care about android users, you can ignore all the required efforts."

You know  nothing about me or what my intentions are.  
My latest release of my  Droidfish fork on July 7th, 2021 (which includes Stockfish and Stockfish forks) has been downloaded nearly 200 times without the benefit of the PlayStore.  Your Android app ab.chesspad, updated on  April 12th, 2020 has been downloaded about 100 times with the benefit PlayStore.  Just pointing out that PlayStore is not the end all be all. 

<a href="https://ibb.co/YRwxf9b">downloads</a><br /></a><br />

Google can change the Play Store requirements at anytime, are we supposed to jump through hoops for Google, when there is alternative solution that is easily available.  In fact, from my perspective  your PR is really designed just for you. A classic example for you to maintain your own fork as I do with my multiple forks.

I suggest the following when you have a chance:

https://css-tricks.com/open-source-etiquette-guidebook/  

Please note, I'm not attacking you personally, I am simply expressing my opinion that your suggested PR is not appropriate.  The maintainers may have a completely different perspective on your PR, and that would be fine with me. I would never take it personally.

Cheers. 
MichaelB7

**Comment by ab-chesspad** [comment]
Accept my congratulations on Droidfish great success. Just don't forget
that Droidfish is advertised on Stockfish websites while ChessPad is not.
Also, obviously Droidfish's audience is much greater than ChessPad's.
I did not get why you took my comment so personally. I think that if a
developer does not follow the rules that are set by the umbrella company,
he/she does not care about the users, nothing personal here. And yes, I
believe that if a software becomes incompatible with the latest OS
releases, it is the developer's responsibility to make the updates.
The point is that you are stuck with SDK 28 while new SDKs are being
released.
In any case, I do not get it. I am tired of arguing with SF developers who
insist on preserving the existing architecture and say that SF crashes are
normal. That's why I did all the work myself. Do you have any specific
issues with my work except for saying that the update is 'invasive'?
Thank you
Alex Bootman

**Comment by MichaelB7** [comment]
Just FYI, my forks of Droidfish is labeled the Harmon Chess app and it has nowhere near the distribution or mentions as the original Droidfish app.  
A common technique to cancel or minimize someone today is to say one does not matter, you saying "if you don't care about android users, you can ignore all the required efforts" is a form of a cancellation technique commonly used today and it is a form of a personal attack whether you think it may be or not.  The statement had nothing to with the merits of your PR, it was used simply to minimize my voice.  I have been around a long time, and there is nothing new under the sun.
I have no ill feelings towards you, you sound like a decent chap and one is never to late or too old to learn from someone else.  I wish you all the best.

**Comment by ab-chesspad** [comment]
Well, isn't it a sort of cancellation saying that somebody's work is
invasive without giving any specifics?

Cheers
Alex Bootmam

**Comment by MichaelB7** [comment]
> Well, isn't it a sort of cancellation saying that somebody's work is invasive without giving any specifics? Cheers Alex Bootmam

My apologies, 22 files changes would normally be quite invasive, although that is often the case with a significant change.  I will let the maintainers make the final judgement, perhaps they will view your PR in a more favorable light,  Best wishes.

**Comment by snicolet** [comment]
The page https://css-tricks.com/open-source-etiquette-guidebook/ is excellent, thanks! 
Added to the wiki in https://github.com/glinscott/fishtest/wiki/Creating-my-first-test

**Comment by vondele** [comment]
as said elsewhere, I'm sympathetic to the idea of having SF reusable, but the PR is too large and by now outdated. I'll close the PR

**Pull request closed without merging**
