### PR TITLE
Changing the sliding_attack function to constexpr

### PR DESCRIPTION
**Pull request by FauziAkram**
Changing the sliding_attack function to constexpr

No Functional change

### CODE REVIEW

**Comment by Sopel97** [comment]
stop making changes you don't understand

**Comment by Disservin** [comment]
@FauziAkram your pr here #4949 was fine for me because it allows `square_bb` to be used in a constant expression and it prevents undefined behaviour when used in a constant expression. 

`sliding_attack` will never be used in a constexpr expression, aka our attack initialization currently is done completely at runtime. This change also doesnt make much sense because the subsequent function calls arent constexpr either.
> To be eligible for compile-time evaluation, a function must have a constexpr return type and not call any non-constexpr functions when evaluated at compile-time. Additionally, a call to the function must have constexpr arguments (e.g. constexpr variables or literals).

https://www.learncpp.com/cpp-tutorial/constexpr-and-consteval-functions/

(forget about consteval because we arent using c++20)

**Comment by FauziAkram** [comment]
My initial idea was to change it to inline

**Comment by Disservin** [comment]
Inline makes no sense either.

**Pull request closed without merging**
