### PR TITLE
Tuning of assorted values.

### PR DESCRIPTION
**Pull request by Stefano80**
Passed STC

LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 45401 W: 8590 L: 8274 D: 28537

Passed LTC

LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 36089 W: 5589 L: 5331 D: 25169

I have moved some variables away from their original place for more transparency. If you don't like it thiw way, I can move them back. If you mantainers like it, I will qualify them as const and change some names to something more understandable.

### CODE REVIEW

**Comment by locutus2** [comment]
Congrats too!

**Comment by mcostalba** [comment]
Congratulations! Not easy to find an improvement with tuning these days.

I'd suggest to directly use numerical values in the code, considering that it will be difficult they will change again and that using values directly removes a lot of clutter and arbitrary named stuff: you'll see the code will be slimmer and easier to read.

**Comment by Stefano80** [comment]
Thanks. Then I will follow Marco's suggestions and move the numbers back in place. I hope I can do it today, otherwise it must be tomorrow in the evening.

**Comment by Stefano80** [comment]
Done. Branch has the original flavour.

**Comment by zamar** [comment]
approved.

**Comment by glinscott** [comment]
Looks good!

**Comment by glinscott** [comment]
Congratulations btw :)

**Pull request closed without merging**
