### PR TITLE
Stockfish 16

### PR DESCRIPTION
**Pull request by vondele**
Release candidate

Bench: 2593605

### CODE REVIEW

**Comment by CamPCatDev** [comment]
Ok cool.

**Comment by anshulongithub** [comment]
@vondele, just wanted to confirm if the passed [new net](https://tests.stockfishchess.org/tests/view/649a21fedc7002ce609d0c7d) be committed before SF 16 is released? 
Thank you.

**Comment by dav1312** [comment]
> @vondele, just wanted to confirm if the passed [new net](https://tests.stockfishchess.org/tests/view/649a21fedc7002ce609d0c7d) be committed before SF 16 is released? Thank you.

No, master is frozen

**Comment by vondele** [comment]
merged with 68e1e9b3811e16cad014b590d7443b9063b3eb52

**Pull request closed without merging**
