### PR TITLE
Document HalfDensityMap

### PR DESCRIPTION
**Pull request by mcostalba**
No functional change.

### CODE REVIEW

**Comment by pb00068** [comment]
Maybe we could also eliminate the constant 20 (= num of rows in map) by calculating it dynamically.
Maybe something like following would work...
#include <type_traits>
 ... int rows = std::extent<decltype(array), 0>::value;

**Comment by pb00068** [comment]
http://stackoverflow.com/questions/14795860/finding-the-amount-of-rows-and-columns-for-a-2-d-array-in-c

**Comment by mcostalba** [comment]
This seems quite obscure :-)

Maybe it is easier and also consistent with how we use Row, to simply
define:

const std::vector<Row> HalfDensityMap = ....

And use HalfDensityMap.size()

**Comment by pb00068** [comment]
If it works, I completely agree with this approach ;-)

**Comment by mcostalba** [comment]
It didn't :-(

So I went with yours...

**Comment by zamar** [comment]
approved.

**Pull request closed without merging**
