### PR TITLE
Update Makefile for Android x86-64 Builds

### PR DESCRIPTION
**Pull request by topse**
For developing an Android GUI it can be helpful to use the Emulator on Windows. Therefor an android_x86-64 library of Stockfish is needed. It would be nice to compile it "out-of-the-box".

This change is originally suggested by Craftyawesome

https://github.com/Craftyawesome/Stockfish/commit/bd997a22b57e04ba5a3293db014d037b1af9b24a

### CODE REVIEW

**Comment by Disservin** [comment]
will you add yourself to the authors please? I know it's a minor commit but still

**Comment by topse** [comment]
I am really sorry ... this is my first contribution to a living project on github and I don't know what you mean. The commit itself seems to be referenced to me, so this would show me as author. I don't find any option where I could add me anywhere as author. Could you give me a hint?

**Comment by PGG106** [comment]
at the root of the repository there's a file called "AUTHORS", add yourself in there.

**Comment by topse** [comment]
Thanks and done!

Best Regards,
Tobias

**Comment by cj5716** [comment]
I think you need to move the order... right above Tomasz Sobczyk

**Comment by topse** [comment]
Sorry again... I swear I know the alphabet :-/

**Pull request closed without merging**
