### PR TITLE
Tweak reductions formula

### PR DESCRIPTION
**Pull request by locutus2**
Replace the depth part in the reduction formula for higher depths with a slower growing linear function. So for depth > 3 less reductions are used.

What we can try next:
- move the break point to even higher depths
- tweak the slope for lower and higher depth
- possible even use a further higher depth threshold for a another even slower growing function 

STC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 25317 W: 5763 L: 5505 D: 14049
http://tests.stockfishchess.org/tests/view/5b54f9f70ebc5902bdb840ed

LTC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 7451 W: 1320 L: 1167 D: 4964 
http://tests.stockfishchess.org/tests/view/5b54feeb0ebc5902bdb84244

Bench 4617359

### CODE REVIEW

**Comment by locutus2** [comment]
The patch seems good to scale. But it uses general for more higher depth less reduction. Par example a depth=19 (median LTC depth) search now the reductions of a depth=17 of the old master used. And for even higher depth like 30 only the reduction from depth 26-27 would be used.

So for safety and to my comfort i would test this also at VLTC (180+1.8) with low throughput.

**Comment by locutus2** [comment]
@snicolet 
I have branch and bench updated with the commited 'Simplify condition for ThreatByRook' patch.

Also you could merge this PR. My VLTC is purely for safety, i don't expect a problem (and if we can revert later).

**Comment by snicolet** [comment]
Merged via 50287a55d3b07623120d938a4159d051e32d852d, congrats!

**Comment by anshulongithub** [comment]
@locutus2 @snicolet was this patch really ELO gaining based on VLTC results? Just wanted to confirm.

**Pull request closed without merging**
