### PR TITLE
Fix psqt format and use smaller numbers in king psqt

### PR DESCRIPTION
**Pull request by hxim**
Fix minus sign in pawn psqt and use smaller numbers in king psqt.

No functional change.

### CODE REVIEW

**Comment by stockfishdeveloper** [comment]
Was this tested in Fishtest?
You're changing values in the tables--that must be tested.

**Comment by ddugovic** [comment]
> You're changing values in the tables--that must be tested.

Correct, changing values is a functional change.

**Comment by MichaelB7** [comment]
hate to tell you this, but when I tested this fix ( fixing the minus signs ) it was regressive, when the original match was approved , it was approved  and tested with the the 3 minus signs as they are, just letting know.

**Comment by Rocky640** [comment]
a) It is a non functional and cosmetic change. Bench is the same.   
    There is always 2 kings on the board.
    For example, you could add S(1000, 1000) to each square of the king psqt, they will cancel out, and bench will be the same.

b) - 1 or -1 is compiled exactly the same thing.

**Comment by hxim** [comment]
@stockfishdeveloper @ddugovic @MichaelB7 
@Rocky640 is right it is completely non-functional king psqt change cancels out and moving minus sign changes nothing

**Comment by ddugovic** [comment]
Thanks @Rocky640 .  I think if both conditions are satisfied this implementation change is functionally equivalent:

1.  Values are never compared to values not similarly affected by this change
2.  Values are never divided (I would be surprised if they are)

(It would surprise me if this change were not functionally equivalent.)

**Comment by stockfishdeveloper** [comment]
Then why have this PSQT at all? If we can change values drastically and have no effect, then it's completely worthless.
Can someone explain to me before this is closed?

**Comment by Rocky640** [comment]
@stockfishdeveloper 
If you change all the values of the king psqt by the same quantity say S(x, y),
white king will have + S(x, y) and Black King will also get + S(x, y).

The evaluation of a position is eval for white pieces minus eval for black pieces.
So the S(x, y) cancels out.

Here the author chose to add S(-31, -28) to every squares,
which could provide nice 0 anchor points for tuning,

But the relative values they have is very important indeed. King psqt is worth about 66 ELO
http://tests.stockfishchess.org/tests/view/5852933d0ebc5903140c5cb2

**Comment by FauziAkram** [comment]
I had some tests where I inserted the fix of the spaces in pawn psqt in addition of my original changes, I was pretty optimist about the tests, but all those 3 tests strangely failed miserably as red.
So same as MichaelB7 I think that this fix might be a regression.

My suggestion is to test this patch in fishtest to make sure its not a regression.
And if the test fail then it means that removing that space is a functional change and therefore I might need to retest those 3 tests:
http://tests.stockfishchess.org/tests/view/58593be10ebc5903140c5f6e
http://tests.stockfishchess.org/tests/view/585916570ebc5903140c5f5f
http://tests.stockfishchess.org/tests/view/585968800ebc5903140c5f89

**Comment by lucasart** [comment]
This patch consists of two parts:
* fix spacing. no problem with that. It's amazing some of the things we can read here, with people arguing whether moving the space character before the minus sign can be an Elo regression. Sure with `sprt(-3,1)` you could test lots of patches like that and a quarter of them would fail (much more with STC+LTC). With the same methodology you could also "prove" that modifying a comment or the name of a source files is regressive. That's why testing results aren't the only thing: people also need to understand what they're doing…
* shift king pst by `S(-31,-28)`. also non-functional. but unrelated, and the choice of `(31,28)` is totally arbitrary, which is why I don't like it. After that, anyone can start opening pull requests shifting king pst by random values.

**Comment by mcostalba** [comment]
@lucasart shifting king values to start from 0 IMO gives a better idea at first glance of the amplitude of the other values, for instance is now easier to spot squares with scores 300 above base line. Of course we are not talking of a biggie here....

**Pull request merged**
