### PR TITLE
Small cleanups 09

### PR DESCRIPTION
**Pull request by vondele**
start with an empty PR to collect small changes

No functional change

### CODE REVIEW

**Comment by mstembera** [comment]
"Multiplication of a Score by a boolean" uses a branch which is unnecessary and inconsistent with "Multiplication of a Score by an integer" just above.  I would change lines 344 and 345 in types.h from
```C++
inline Score operator*(Score s, bool b) {
  return b ? s : SCORE_ZERO;
}
```
to
```C++
constexpr Score operator*(Score s, bool b) {
  return Score(int(s) * b);
}
```
I measure no speed difference.  Here is the emitted code before and after.
https://godbolt.org/z/2u2XAE

**Comment by snicolet** [comment]
@mstembera 
Was change in "small cleanup" patch of April, 12th :-) https://github.com/official-stockfish/Stockfish/commit/f83cb95740de019db6ff5567d6f84f218b18cd9e

**Comment by mstembera** [comment]
@snicolet I see and wonder why?  I still think the * version is better for the reasons I gave above but you and @vondele decide of course.

**Comment by vondele** [comment]
@mstembera I can't measure any performance difference between the two versions, even not in a micro benchmark. So I went with the one that reads for me most easily, i.e. having no casts instead of three (two + one).

**Comment by snicolet** [comment]
A round of blank lines and comment formatting: https://github.com/official-stockfish/Stockfish/commit/a8827d77d673d9b5b845a1d39e69b3725e57c94a

**Comment by Vizvezdenec** [comment]
We should reorder evaluate.cpp bonuses in alphabetical name, currently BishopOutpost is somewhere in the middle while it should be close to 1st.

**Comment by Lolligerhans** [comment]
The just-commited patch contains whitespace error. `evaluate.cpp:380`

**Comment by mstembera** [comment]
This is non functional and removes some unused constants as well as 12 table lookups and 6 multiplies in the imbalance() calculation for each color.  However it's not on a hot path(material eval is hashed) and doesn't pass elo gaining bounds.  I leave it to you whether it qualifies as a cleanup.
https://github.com/mstembera/Stockfish/commit/55b812dc30e10da4de2cc7108be5041d717d61d9

**Comment by vondele** [comment]
I'm closing that early since the diff has gotten big already with first conflicts to be fixed.

**Pull request closed without merging**
