### PR TITLE
Fauzi Tuning

### PR DESCRIPTION
**Pull request by FauziAkram**
Bench: 5952965

A tuning patch which cover the following changes:
- increase the importance of (queen and rook mobility in endgame) and decrease it in mg, since if we use the heavy pieces too early in the game we will just make opponent develop their pieces by threatening ours.
- King Psqt: 1)King will be encouraged more to stay in the first ranks in the MG 2)and will be encouraged more to go to the middle of the board/last ranks in the EG
- Bishop scale better in EG
- Logical changes on various psqt tables
- 1/6 of the changes of the last tuning session on mobility tables

STC: LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 227879 W: 41240 L: 40313 D: 146326
LTC : LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 167047 W: 21871 L: 21291 D: 123885

### CODE REVIEW

**Comment by MichaelB7** [comment]
Nice work 👍

**Comment by Kingdefender** [comment]
I don't think Marco would approve this because it is way too many changes for a single patch. You don't know if you are not introducing noise with so many changes in one go. I think you have to at least test if some changes are not the only ones that really make a difference. If not you could make a case that they work together. But with so many I doubt that is true, sorry just my opinion seeing this.

**Comment by FauziAkram** [comment]
Why is Travis CI build test failed?
Do I have to do something from my side?

**Comment by FauziAkram** [comment]
@Kingdefender no don't worry, in the patch there is no change to the code at all, just change in numbers in  psqt tables and mobility tables, any tuning patch could give these results, but the points that I mentioned are just some steps which I slowly made until I was able to bring out this successful patch, in other words they are the "numbers changed" translated to "words for human to interpret", but at the end they are just numbers changed from the same tables.

**Comment by lantonov** [comment]
Bench is wrong and that's why the Travis build fails. The master has changed meanwhile and you have to rebase your test branch on the new master.

**Comment by FauziAkram** [comment]
I made the changes starting from the latest master this morning, before opening the pull request, so what should I do now exactly? (This is my first time opening a pull request)

**Comment by Rocky640** [comment]
Edit your commit comments, and on a separate line, indicate the new bench number as follow
Bench: XXXXXXX

**Comment by ddugovic** [comment]
[0,4] bounds seem inappropriate for so many functional changes.  It is possible some of the changes weaken SF and we cannot identify which ones without additional tests.

**Comment by locutus2** [comment]
@ddugovic 
There are changed only constants so this is a pure tuning patch and the bounds [0,4] are perfectly fine.

@FauziAkram 
In the travis tests a check for the bench number exists. A bench run is done and the obtained number is compared to the last commit who contains a bench number in the commit message.
So add only a commit (par example add or remove a space) and put somewhere in the message the text 'bench 5952965'. Before or after this bench marker any additional text is allowed, so you can add the bench number also for your regular commit.

**Comment by locutus2** [comment]
And i forgot: Congratulations for your first passed patch :-)!

**Comment by Stefano80** [comment]
Hi Fauzi,

try to follow these instructions:

1) use in your directory git commit --amend
2) go to the last line of your commit comment and add
Bench: 5952965
3) push to your remote branch

This should solve the problem.

**Comment by vondele** [comment]
@FauziAkram if you directly use the github website (didn't even now that this was possible!), you should be able to add this to the 'Commit changes' text box where it is written 'Add an optional extended description...' . Most people will use the workflow @Stefano80 described (i.e. some local modifications that are 'pushed' to github using an additional git program)... which is much more convenient ultimately.

**Comment by FauziAkram** [comment]
Thanks all,
Finally I was able to solve the bench fix.

**Comment by Kingdefender** [comment]
@Locutus2 They seem to be more changes than you could do with a single machine tuning (to me at least but have no experience with it). If you did machine tuning in one area that just isn't elo sensitive enough to pass [0, 4], the test would fail. And the machine tuning process would ensure more randomness, trying all changes. How are you going to know which of these changes help without testing? It is up to Joona of course.

**Comment by locutus2** [comment]
@Kingdefender
A tuning patch is a patch which changes only constants. How the tuning is done (automatic, guessing, mixture of methods etc.) is not important (the tuning method probably influence to success chance of a set of parameters but this is another topic). As i understand part of the values are based on tuned values and handmade values which at least partial tested on fishtest (i have see some tests around this). If some of this tests could not pass the [0,4] test but seems promising (yellow) combining them for a new test is common and allowed (because complexity is not increased). The only problem (like for all test series of an idea) is that the more tests done the likelihood of a false test result increases. But this effect is already reduced because we use two passing stages (patch have to be two times lucky).

Coming to your last question: Only through testing (but not for sure, because the tests go wrong too). But this plays only a role for patches that add code, because we prefer code which is simpler. But this argument holds not for tuning patches because all of them have the same complexity.

**Comment by stockfishdeveloper** [comment]
@FauziAkram I am positive Marco would not commit this. There are too many values changed.
As many people have already pointed out, one or two of those values may lose, for example, 2 ELO while the rest of the patch may gain 6 ELO without them.

All this is not to say that your patch is bad in and of itself. It has been proven at least likely that there is an ELO gain from your changes, congrats!
In the interests of improving Stockfish as much as we can, though, we want to make sure that we are getting all of the ELO that can be gained from your ideas.

Therefore, I suggest we close this and tune pieces of it at a time. We may find something worth more than 4 ELO by rejecting some of the tuned value changes.

Though I cannot speak for @zamar I would advise against committing this.

**Comment by mcostalba** [comment]
Just for the records: I would _do_ commit this.

It is a parameters tweak patch, so SPRT[0, 4] is appropriate. In parameters tweak the number of parameter is not important, Indeed our tuning system sometime it seems works better with many parameters to tune than with few and in the past we committed patches with tens if not hundreds of parameters tweaked.

As long as it is just changes to numbers, it is ok.

Of course Joona will do what he thinks is the best.

**Comment by FauziAkram** [comment]
Thanks Marco,
Perfect logic in yours and in locutus answers, that is what I considered in my mind for the whole time.
Just to briefly answer stockfishdeveloper, I have tested all the mentioned changes separately and they are all good changes even individually (Yellow or Green patches).
Can't wait for the patch to be merged so I can start some new tests.
Thanks to all who supported me and specially Rocky.

**Comment by Kingdefender** [comment]
@Fauzi I'm sorry if I misunderstood the first post and your reply to me and all those parameters were actually tuned with some tuning system. It just was not clear to me how much tuning was involved. Comforting to know that separate tests werre also in the green. Congratulations to Fauzi of course and it is great to see a green [0, 4} again.

**Pull request closed without merging**
