### PR TITLE
Use avx2 instruction set if pext is on

### PR DESCRIPTION
**Pull request by braich**

### CODE REVIEW

**Comment by lucasart** [comment]
why?

**Comment by braich** [comment]
pext implies CPUs with AVX2 instruction set. For those CPUs AVX2 is native instruction set and SSE is emulated for compatibility with the old programs. Emulation is always slower.

**Comment by zamar** [comment]
But we don't use practically any SSE instructions... Any benchmarks that this makes any difference?

**Comment by mstembera** [comment]
If I understand correctly, we don't use any SSE explicitly but we let the compiler decide what instructions it thinks are best to emit.  If no CPUs exist with bmi2 and w/o AVX2 there should be no point in restricting the compilers choices even if currently there may be no measurable speedup.  Sorry but I don't have the right hardware to bench this.

**Comment by joergoster** [comment]
Intel® Core™ i5-4570 CPU @ 3.20GHz × 4
Linux Mint 17.2, gcc 4.9.3
50 runs each

make build ARCH=x86-64-bmi2
make strip
```
Engine                          | Nodes/second
test                            | 2226839.5 +- 2513.0
base                            | 2220886.0 +- 2598.58

Differences                     | 6276.0 +- 375.0
Variance of the mean            | 53.03 ( 0.85 %)
Speed up                        | 0.28 %
```

make profile-build ARCH=x86-64-bmi2
(PGOBENCH = ./$(EXE) bench 16 1 500 default time)
make strip
```
Engine                          | Nodes/second
test-pgo                        | 2272370.5 +- 2672.06
base-pgo                        | 2272698.0 +- 4587.5

Differences                     | -654.0 +- 1314.0
Variance of the mean            | 185.83 ( -28.41 %)
Speed up                        | -0.03 %
```

A small yet noticeable speedup with normal build, no gain with profile build.

**Comment by joergoster** [comment]
And with another profile-build:
```
Engine                          | Nodes/second
test2-pgo                       | 2278604.0 +- 3067.28
base-pgo                        | 2275975.0 +- 2951.5

Differences                     | 3285.0 +- 663.0
Variance of the mean            | 93.76 ( 2.85 %)
Speed up                        | 0.14 %
```

**Comment by zamar** [comment]
I'm pretty neutral around this patch.

As @mstembera said if there are no CPUs with bmi2 and w/o avx2, then it should be fine to make this change, even though impact is minimalistic at best...

So, approved.

**Comment by mstembera** [comment]
Just a quick question...  Should we also add -mavx before the -mavx2 ?  The reason I ask is because of this this pull request 
https://github.com/mcostalba/Stockfish/pull/198
where -bmi had to also be added even though -bmi2 was already there.

**Comment by Krgp** [comment]
Adding -mavx2 or -mavx -mavx2 both actually give me a slowdown on i7 4790k Windows 10 x64 (make build ARCH=x86-64-bmi2 on GCC 530. Standard build because PGO is non-deterministic)

Base = Master and Test = -mavx or mavx2 or both as the case may be

A. -mavx -mavx2 (both)

Results for 50 tests for each version:

                     Base           Test              Diff      
    Mean     2841728     2830177        11551     
    StDev          7176           8415        14545     

p-value: 0.214
speedup: -0.004

B.  -mavx2 (only -mavx2 as in the pull request)

Results for 50 tests for each version:

                      Base           Test               Diff      
    Mean      2837881      2835249         2632      
    StDev           6179            5888         8920      

p-value: 0.384
speedup: -0.001

**Comment by zamar** [comment]
I'm neutral around this patch, I'll leave it up to @mcostalba to decide.

**Comment by mcostalba** [comment]
According to @Krgp the patch shows a slowdown in his machine, and @joergoster didn't measured any speed up in profiled case (that is the one used by public release). So considering that the PR adds a flag, instead of removing and simplifying I am going to close this PR becuase it adds a useless flag.

**Pull request closed without merging**
