### PR TITLE
Score and Select Best Thread in same loop

### PR DESCRIPTION
**Pull request by protonspring**
This is a non-functional simplification that combines vote counting and thread selecting in the same loop.

It is possible that the best thread would be updated more frequently than master, but I'm not sure it matters here.  Perhaps "mostVotes" is a better name than "bestVote?"

STC (stopped early).
LLR: 0.70 (-2.94,2.94) [-3.00,1.00]
Total: 10714 W: 2329 L: 2311 D: 6074 
http://tests.stockfishchess.org/tests/view/5ccc71470ebc5925cf03d244

### CODE REVIEW

**Comment by ddugovic** [comment]
Is this thread-safe?

**Comment by mstembera** [comment]
Since auto bestVote in now initialized from 0 instead of votes[this->rootMoves[0].pv[0]] it is now an int instead of int64_t which is a problem since it can overflow.  It should be
```C++
int64_t bestVote = 0;
```

**Comment by protonspring** [comment]
@ddugovic Well. . it's certainly not any less safe than master.

I guess it is possible that the thread could be updating it's root move at the same time the main thread is reading it.  I guess it's possible that this could result in a bogus move which wouldn't likely get selected as the best.  I doubt this is a problem, but I guess it is a possibility.

**Comment by xoto10** [comment]
All helper threads should have finished at this point. See line 217

**Comment by vondele** [comment]
yes, thread safety is fine. Patch looks good to me. Failing CI is a Travis issue.

**Comment by mcostalba** [comment]
@protonspring could you pleae rebase above current master? Thanks.

**Pull request merged**
