### PR TITLE
Pawns count imbalance table

### PR DESCRIPTION
**Pull request by joergoster**
Instead of having a continuous increasing bonus for our number of pawns when calculating imbalance, use a separate lookup array with tuned values.
Idea by GuardianRM.

STC
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 16155 W: 2980 L: 2787 D: 10388

LTC
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 100478 W: 13055 L: 12615 D: 74808

Bench: 6128779

### CODE REVIEW

**Comment by Rocky640** [comment]
Removing the "2" in the QuadraticOurs table will have some impact.

But I don't see the contribution of this PawnSet table. I might be missing something ?

According to table below, the maximum score difference due to the PawnSet table will be at most S(1, 1),
since the maximum bonus difference is 20, and that we divide at the end by 16
e->value = int16_t((imbalance<WHITE>(PieceCount) - imbalance<BLACK>(PieceCount)) / 16);

Furthermore, the most probable imbalance are +1 or +2 and there are only 3 cases where this might round up to S(1, 1)
 
2017-03-12_09h19_39
 comment

**Comment by DamasClasicas** [comment]
Finally it passed! Congratulations!

**Comment by joergoster** [comment]
@Rocky640 Well, by setting QuadraticOurs[PAWN][PAWN] to zero, the calculation of 'v' inside the second for-loop will always be zero for our pawns. This is now replaced with a simple lookup when 'bonus' is initialized.

Regarding the values, the old ones would have looked like this:
```{ 0, 2, 8, 18, 32, 50, 72, 98, 128 }```
And the new ones:
```{ 24, -32, 107, -51, 117, -9, -126, -21, 31 }```

So the impact is the same more or less.

**Comment by Rocky640** [comment]
@joergoster 

I deleted my previous comment, since it was wrongly based on the following PawnSet values
0, 5, -1, 3, 21, -5, -11, 1, 9 (3rd commit in this PR)

So your committed values are
24, -32, 107, -51, 117, -9, -126, -21, 31 (6th commit in this PR)

With this, we can see the following contribution of the PawnSet for the strongside
(and to see the end result in score unit, we must divide the values by 16)

Still a bit weird, but an interesting start.

2017-03-12_11h47_57

**Comment by ddugovic** [comment]
Should there be an assertion somewhere that a position may have no more than 8 pawns?

**Comment by zamar** [comment]
Good idea. Create a PR?

**Comment by lantonov** [comment]
Why `const int PawnsSet[9] = {` and not `const int PawnsSet[] = {` ?

**Pull request closed without merging**
