### PR TITLE
Uci compliance tests

### PR DESCRIPTION
**Pull request by Stefano80**
This is more a preliminary proposal for Marco than a real PR.

In view of SF9, I was thinking of implementing a test for uci functionality. Would you be willing to merge? I started an implementation a learned a lot from Joosts scripts, so I think I could take the time and go through this, if you want to merge in the end.

Btw, what do we do if I discover that we do not actually comply with UCI? (https://github.com/official-stockfish/Stockfish/issues/1371)

### CODE REVIEW

**Comment by mcostalba** [comment]
@Stefano80 I think idea is correct, but I fear we will write  a lot of rules that will always pass.

These kind of testing make sense to me for code that changes often, for code under active development you want to ensure do not introduce regressions. But UCI options are hardly under active development. They change a couple of time per year at best and in those rare cases we already make good testing, to validate and commit the patch and also after patch has been committed, because SF dev is regurarly download and used by a big user base.

So, although idea is correct, I am not sure SF is the ideal posterchild for this kind of testing framework, especially on UCI options.

**Comment by Stefano80** [comment]
Hi Marco, what you say makes perfectly sense. I just used the UCI options to check whether I correctly understood how the Travis framework works.

Do you mind whether I keep it open for some time? I would like to write some reason tests to search stopping with different time controls, maybe this is more useful.

**Comment by vondele** [comment]
I think more automated testing is the way to go. In particular, doing a release should not require any manual testing. So, as such I think this is a good direction. This particular patch is not so valuable yet, as it would be best to test some of the functionality, at least for basic correctness. For example, testing things like skill level, or non-default hash size under valgrind and the sanitizers.

**Comment by Stefano80** [comment]
Hi @mcostalba , @vondele 

I gave a try on testing skill levels. What I do is pick 3 skill levels (1,5,9) and analyze start position on a shallow depth 50 time. At the end I check that I always got 4 different moves.

I also checked (manually) that a skill level 20 one get one single move.

Is this the kind of test you think is valuable?

**Comment by Stefano80** [comment]
And I learned a lot about bash in the process, which is also fun!

**Comment by vondele** [comment]
@Stefano80 I believe the failing CI test is related to using non-posix options to grep, some of which fail on OSX. For a list of standard options see:
http://pubs.opengroup.org/onlinepubs/009695399/utilities/grep.html
You can use something like:
```
expect uci.exp $i | grep bestmove | cut -c10-13 >> skilllevel$i.exp
``` 
Since the test takes some time, maybe just test 2 skill levels (1 and 5), which should also allow for reducing 50 to some smaller number. Maybe that '50' needs a comment in the script as well, since it just guarantees with high likelihood that the test passes.

Other than that, I think that's a reasonable why to test skill.

**Comment by Stefano80** [comment]
Hi @vondele @mcostalba ,

I implemented Joost's suggestions (along with some renaming). Assuming that the we understand why the bench test fails, I would assume this is a status in which it could be merged.

If you merge, my next step would be to test whether changing has say from 1 to 4 does change the search behaviour.

**Comment by Stefano80** [comment]
@snicolet: given the change of mantainer: should I keep this open, close it, or move it to a new PR with a different message?

**Comment by mcostalba** [comment]
@Stefano80 at the moment I'd suggest to close it and open a specific branch on your repo were interested people can add useful tests. Then, once is ready, it means containing sensible tests, i.e. tests on parts of code that change not very seldom and that current tests do not find, you may want to open a new PR.

**Comment by Stefano80** [comment]
Sounds like a sensible approach.

**Pull request closed without merging**
