### PR TITLE
Software MSB/LSB

### PR DESCRIPTION
**Pull request by protonspring**
I did a reasonably fast and simple software implementation of MSB/LSB.  There are some faster versions, but they are pretty ugly.

This would allow SF to be easily built on any little-endian system.

Is this of any interest to anyone?

### CODE REVIEW

**Comment by mstembera** [comment]
I thought this was only a compiler compatibility issue and current master can be built for little-endian.  Is that not the case?

**Comment by protonspring** [comment]
Yes, this is a compiler compatibility issue.   Master will build for gcc and windows compilers, but nothing else.  This at least provides msb and lsb for any other c++ compiler on a little-endian system.

**Comment by niklasf** [comment]
Relevant edf4c07d251f1d6c709d47969bfe1452194d9430:

> Use intrinsics only for LSB/MSB
>  
> The NO_BSF does not cover any real life use-case today. The only compilers that
> can compile SF today, with the current Makefile and no source code changes, are
> either GCC compatible (define __GNUC__) or MSVC compatible (define _MSC_VER). So
> they all support LSB/MSB intrinsics.
>
> This patch simplifies away the software fall-backs of LSB/MSB that were still
> in Stockfish code, but unused in any of the officially supported compilers.
>
> Note the (legacy) MSVC/WIN32 case, where we use a 32-bit BSF/BSR solution, as
> 64-bit intrinsics aren't available there.
>
> Discussed in: https://github.com/official-stockfish/Stockfish/pull/1447
> and:          https://github.com/official-stockfish/Stockfish/pull/1479
>
> No functional change.

**Comment by protonspring** [comment]
I guess it is appropriate to ask, "Is anyone aware of a desired compiler that currently is not supported by the current code?"

If no, then there is nothing useful here.
If yes.  someone say so and we can talk about.

Perhaps if we hear nothing in the next few days, just close it.

**Comment by protonspring** [comment]
I think I'l just close this.  If we want something in the future, we can always add in the previous code which was probably faster than this anyways.

**Pull request closed without merging**
