### PR TITLE
Little fix for cygwin&msys2 environment

### PR DESCRIPTION
**Pull request by proukornew**

### CODE REVIEW

**Comment by vondele** [comment]
I'll merge this one shortly

**Comment by vondele** [comment]
seems like this again broke something now compiling under linux within fishtest. Might need another revert https://github.com/glinscott/fishtest/issues/952

**Comment by gvreuls** [comment]
It's unfortunate this silently breaks fishtest because the solution was tested after the revert of the original patch and seemed to work perfectly.

I think this isn't our bug per se but something going wrong with what the ffishtest worker assumes is its current working directory, either because of a bug in ``games.py`` (where some directory juggling is going on) or perhaps even in the python interpreter itself (Python 3.9.5 on my workers).

**Comment by proukornew** [comment]
` subprocess.check_call(
            MAKE_CMD + ARCH + " -j {}".format(concurrency) + " profile-build",
            shell=True,
            env=dict(os.environ, CXXFLAGS="-DNNUE_EMBEDDING_OFF"),
        )
        try:  # try/pass needed for backwards compatibility with older stockfish, where 'make strip' fails under mingw.
            subprocess.check_call(
                MAKE_CMD + ARCH + " -j {}".format(concurrency) + " strip", shell=True
            )
        except:
            pass

        shutil.move("stockfish" + EXE_SUFFIX, destination)` Look consistent and no directory juggling

**Comment by gvreuls** [comment]
```Python
   tmp_dir = tempfile.mkdtemp(dir=worker_dir)

    try:
        os.chdir(tmp_dir)
        with open("sf.gz", "wb+") as f:
            f.write(
                requests.get(
                    github_api(repo_url) + "/zipball/" + sha, timeout=HTTP_TIMEOUT
                ).content
            )
        zip_file = ZipFile("sf.gz")
        zip_file.extractall()
        zip_file.close()

        os.chdir(glob.glob(os.path.join(tmp_dir, "*/src/"))[0])
```

Looks like directory juggling to me, and I don't know if ``os.chdir()`` changes the python working directory too, I'm not a python specialist.

**Comment by gvreuls** [comment]
The error with the fishtest worker only occurs if the ``ccache`` compiler cache is installed and disabling the cache for the worker fixes the problem, so this is due to ``ccache`` incorrectly assuming that the instrumented object files created during the ``make profile-build`` process are cacheable and reusable in later builds.

The patch is fine but exposes a ``ccache`` bug that's easily mitigable by disabling the cache for the worker (by setting ``CCACHE_DISABLE="1"`` in the worker's environment).

**Pull request closed without merging**
