### PR TITLE
Simplify away a useless TTEntry::read() when we don't hit.

### PR DESCRIPTION
**Pull request by mstembera**
No functional change
bench: 1038234

### CODE REVIEW

**Comment by dubslow** [comment]
I believe this is a functional change, even if perhaps it doesn't change on a standard bench. Standard bench clears the TT between each search yes? Whereas this could well give different results after TT reuse (i.e. the "replacement strategy"), or indeed in a multithreaded race scenario.

To be clear, I strongly doubt it loses elo, but it I believe it *is* a functional change. In fact I think it's quite similar to #5184 in that regard. At that time, it was suggested that we improve the bench to account for changes to TT reuse strategies, such as this PR, but we haven't yet made that improvement.

**Comment by mstembera** [comment]
Hmm, if we return ttHit as false it should make no difference what the data is because search should not use it.  I also don't follow how clearing the TT makes any difference in this regard.

**Comment by peregrineshahin** [comment]
> Hmm, if we return ttHit as false it should make no difference what the data is because search should not use it. I also don't follow how clearing the TT makes any difference in this regard. Replacement strategy should also be unaffected because we return the same replacement pointer as before.

True, the data returned is a copy and it is not used anyways.. it's the same.
The only difference would be that the older code is less efficient which fixing that could make the difference in a multithreaded environment indeed. but it's fixing the code back to how it should be.

**Comment by dubslow** [comment]
The search does use such data. `ttData.value`, `ttData.move`, `ttData.eval` and `ttData.is_pv` are guarded against `ttHit`, but `bound` and `depth` are not so guarded. If they don't change the standard bench, that's more luck then not. (Obviously, it's easy to argue that search *shouldn't* use this data, per the PR, but it *does* at present.)

(The reuse/replacement may be affected because the search uses the returned data, and which data is returned depends on the `relative_age` of the nonmatching entries.)

**Comment by dubslow** [comment]
To be clear, I think this PR is a very logical and desirable change, I just believe it is functional in rare/edge cases, since search doesn't fully guard `ttData` against `!ttHit`. And, since it's functional, it should be passing some non-reg tests to be merged.

**Comment by mstembera** [comment]
If depth and bound are not guarded by ttHit in search that seems like a preexisting bug in search that should be fixed either way.

**Comment by peregrineshahin** [comment]
Okay good point, search in many places check for VALUE_NONE as ttData.value and thus no ttHit to assume that a hit is false but there was some code which uses bounds and depth without this implicit check included... I see your point now..
The problem is that even if such places still there and are fixed there is no obvious way to force the developer to do it

**Comment by dubslow** [comment]
> If depth and bound are not guarded by ttHit in search that seems like a preexisting bug in search that should be fixed either way.

Yes I quite agree.

**Comment by peregrineshahin** [comment]
These LMR stuff looks like the only ones used without a guard for ttHit being false, but assuming depth is 0 then these always resolve to false, ofc this looks very shaky.. but how to not gurantee it's not abused it as usual, not sure that's possible which is a bit unfortunate

```c++
        // Decrease reduction if position is or has been on the PV (~7 Elo)
        if (ss->ttPv)
            r -= 1 + (ttData.value > alpha) + (ttData.depth >= depth)
               - (PvNode && ttData.value < alpha && ttData.depth >= depth);
        ...
        // Increase reduction for cut nodes (~4 Elo)
        if (cutNode)
            r += 2 - (ttData.depth >= depth && ss->ttPv)
               + (!ss->ttPv && move != ttData.move && move != ss->killers[0]);
```

**Comment by mstembera** [comment]
BTW separately from the search conversation above and alternate version of this patch is
```C++
constexpr TTData nullData = {Move::null(), VALUE_NONE, VALUE_NONE, DEPTH_ENTRY_OFFSET, BOUND_NONE, false};
return {false, nullData, TTWriter(tte)};
```
Is this preferable to returning uninitialized TTData()?

**Comment by peregrineshahin** [comment]
> BTW separately from the search conversation above and alternate version of this patch is
> 
> ```c++
> constexpr TTData nullData = {Move::null(), VALUE_NONE, VALUE_NONE, DEPTH_ENTRY_OFFSET, BOUND_NONE, false};
> return {false, nullData, TTWriter(tte)};
> ```
> 
> Is this preferable to returning uninitialized TTData()?

looks reasonable to me indeed to use such safe values in case the ttData used without ttHit, btw beware it should be `Move:none()` because `Move::null()` resloves to true, it's for null move search.

**Comment by dubslow** [comment]
> Is this preferable to returning uninitialized TTData()?

Very fugly to me.

The language guarantees default initialization, and Stockfish uses default initialization *everywhere* in the codebase, at least hundreds of times, if not thousands.

And, even if we decided to use explicit defaults (contrary to codebase convention), better to do it in the struct proper, assigning directly to the declaration, rather than this adhoc form, imo.

(That said, I'd be in favor of explicit defaults on a codebase-wide basis, but that's a whole nother can of worms.)

**Comment by dubslow** [comment]
If one wanted to add explicit defaults, this would be the way to spell it:

```// A copy of the data already in the entry (possibly collided). `probe` may be racy, resulting in inconsistent data.
struct TTData {
    Move  move = Move::none();
    Value value = VALUE_NONE, eval = VALUE_NONE;
    Depth depth = DEPTH_ENTRY_OFFSET;
    Bound bound = BOUND_NONE;
    bool  is_pv = false;
};
```

**Comment by mstembera** [comment]
Ok after more thought I think it's best to not initialize here since that takes extra instructions which are wasted.

**Comment by mstembera** [comment]
Related https://github.com/official-stockfish/Stockfish/pull/5766

**Pull request closed without merging**
