### PR TITLE
Support for 7 piece syzygy

### PR DESCRIPTION
**Pull request by jjoshua2**
I get a message saying 533 syzygy tablebases were found with this patch, instead of the 510 6 man files.

### CODE REVIEW

**Comment by jjoshua2** [comment]
Perhaps it is wise to instead only have 6 be the default ucioption, but allow to be raised to 7

**Comment by snicolet** [comment]
Thanks for the patch, I will look at it after the beginning of the TCEC super-finale.

In other words, I think that I will make a code freeze from now for a period of about 2-3 weeks for all the features related to tablebase, time management, etc, because I don't want to introduce any bug that we wouldn't have the time to fix before we sent the executable for the super-finale. Only the trivial usual evaluation or search patches during the freeze :-)

**Comment by syzygy1** [comment]
This is way too early to commit.

**Comment by lucasart** [comment]
This patch puts the carriage in front of the horse. First we need a 7-men sygyzy generator (which isn't available yet). Second we need machines on which such 7-men generation can be done (1TB or RAM? months of computation? years?). Then we can think about probing such tables...

**Comment by jjoshua2** [comment]
There already is a machine with over 1tb of ram that has already generated
23 different 7 piece endings in 46 files that are available as a torrent.
The generator is still in progress since it doesn't work for all 7 piece
combinations yet but hopefully by the end of the year we will have most of
it generated.

**Comment by syzygy1** [comment]
But the format will have to be changed and what has been generated may have to be regenerated from scratch.

**Comment by MichaelB7** [comment]
Way to early to commit and generate.  I would strongly heed Ronald’s coaching here - he is our Syzygy guru here without question. Your energy and time might be better utilized on some other endeavor.  But if you do have an over abundance of time and resources , it is your call if you choose to waste them.

**Comment by ik4u** [comment]
Any idea how much storage space will be required for 7 piece syzygy TB

**Comment by jjoshua2** [comment]
It's too early to do more than an educated guess of 10gb for wdl and 10gb
for dtz. Syzygy compresses better and has less information than lamonstov
dtm of 140tb

**Comment by ik4u** [comment]
If <=20 TB, than I would say we in good times...intel scalable processors with 28/56 cores per processor (X4 on a quad cpu) together with intel Vroc technology which can RAID 0 M2 drives giving you >20gb/s Read/Writes and upto 2TB ram...pretty certain 7piece TB will be compiled very quickly

**Comment by Nordlandia** [comment]
@jjoshua2: based on replies in this thread, do you still plan to generate more 7-piece combinations?

Certain 7-piece sets can add endgame strength over existing 6-man.

**Comment by mstembera** [comment]
IMO a chicken and egg analogy is more applicable here than the horse and carriage.  This will happen sooner than later and I'm glad someone has started working on it.   If we have to change the format later or make other improvements why should we let that block any work from starting now?

**Comment by syzygy1** [comment]
@mstembera
Isn't the answer obvious?
If I had released intermediate versions of my generator instead of what was essentially the final version, the internet would now be littered with incompatible versions of the TB files.

Experimenting is fine, but distributing them without considering what happens next is not helpful.

**Comment by jjoshua2** [comment]
@Nordlandia See [here](url) for progress on fixing generator and generating more sets.

**Comment by mstembera** [comment]
@syzygy1 That's a good point.  So defining the format should be step 1.  I realize it's your choice of what you work on and when but I hate discouraging someone else who is willing to put in some work from being able to do anything.  If(big IF of course) @jjoshua2 defined the format first would you still object?

**Comment by jjoshua2** [comment]
@mstembera I don't think I will do much more for a while, Bojun Guo on talkchess is working on it now and is making progress.

**Comment by snicolet** [comment]
Reading the various reactions here, it is clear there is still an active debate about the format (!) of the 7 men database, so I am closing this pull request for the moment.

Feel free to re-open another PR once Ronald and everybody involved give a thumb up :-)

**Pull request closed without merging**
