### PR TITLE
Unify scoring functions in MovePicker

### PR DESCRIPTION
**Pull request by mcostalba**
Original patch and idea from Joost, I have just rewritten in a non-functional change patch. Any further simplification could be tested above this one.

I have kept original author name in the PR.

No functional change.

### CODE REVIEW

**Comment by VoyagerOne** [comment]
@mcostalba 
The original code is much cleaner and easier to work with...in addition it had useful comments that are now removed.

Reducing LOC is not a simplification if it tends to make the code cumbersome and difficult to work with.
Please reconsider...

**Comment by mcostalba** [comment]
@VoyagerOne I consider current master in a temporary state: code now is ready to be further simplified unifying the different scoring rules, for instance there is no reason for EVASION captures to be treated differently. In current form it  is easier to test for simplifications that will yield to a simpler code, really simpler not just in LOC, that I agree with you is only a first order metric, but does not tell the full story.

If code will not be simplified I will consider to revert to original form.

**Comment by mstembera** [comment]
My vote would be to at least separate the CAPTURES and EVASIONS.

**Comment by VoyagerOne** [comment]
The code is now being butchered to hell.

**Comment by mcostalba** [comment]
@VoyagerOne @mstembera what about [this one](https://github.com/mcostalba/Stockfish/blob/62fe0449cacf7f4f2a64e51310488e93b4e67917/src/movepick.cpp#L127)?

**Comment by mcostalba** [comment]
There is a somewhat related discussion going on [here](https://github.com/official-stockfish/Stockfish/pull/1201), if interested.

**Comment by mstembera** [comment]
I like the one you linked better than current.  I would further change the line
```C++
else if (pos.capture(m))
```
to 
```C++
else if (Type == EVASIONS && pos.capture(m))
```
which for me makes the evasion code even clearer.

**Comment by mstembera** [comment]
Actually never mind my change above but yes I like your new version better than current master.

**Pull request merged**
