### PR TITLE
Fix indentation in movepicker.cpp

### PR DESCRIPTION
**Pull request by mcostalba**
Also move PickType out of global space.

No functional change

### CODE REVIEW

**Comment by snicolet** [comment]
Nice, shorter names are better indeed.

We could go one step further and harmonize the (cur, endMoves) pointer preparations all over the class, like in this commit: https://github.com/snicolet/Stockfish/commit/4d3f2e5448366b8564807fcd6933bc06ddbe2526

**Comment by mcostalba** [comment]
@snicolet yes, ideally we may want to call it 'end', not 'last' because it points to one element after the last one.

In STL library (and practically in almost all libraries) it is idiomatic to refer to:

- end: one element past the last one
- last: the last element of the range/array/etc.

So in our case it should be 'end', due to how moves are generated and moveList returned:

`*moveList++ = m;
`

Unfortunately it clashes with the same named member function MovePicker::end()

**Comment by Rocky640** [comment]
While being there, can you fix the spacing in evaluate.cpp
```
    constexpr Bitboard Camp = (Us == WHITE ? AllSquares ^ Rank6BB ^ Rank7BB ^ Rank8BB
                                       : AllSquares ^ Rank1BB ^ Rank2BB ^ Rank3BB);

```

**Comment by snicolet** [comment]
@Rocky640 Corrected, thanks.

Merged via 280022baf78a52e9a5c34ef2aec6927aace3e83f.

**Pull request closed without merging**
