### PR TITLE
7-piece Syzygy tablebase support

### PR DESCRIPTION
**Pull request by noobpwnftw**
Add support for 7-piece Syzygy tablebases.

No functional change if SyzygyTB is not used.

Bench: 4734881

### CODE REVIEW

**Comment by Rocky640** [comment]
First, congratulations for your 7-men creation project. This is a huge undertaking.

Most users have 3-4-5 syzygy. A few have 6-men syzygy,
I did not look at this 7-men syzygy code, but is it possible that this more general code would unfortunately be a slow down for such users ?

**Comment by noobpwnftw** [comment]
As a part of "bug fix", this patch would add one byte-read, one AND, one SHIFT and one OR operation in order to retrieve a potential full 12-bit symbol properly, which may or may not have existed in the past, and removing an integer overflow problem that only happens when dealing with large tables.
Then it adds one more branch operation when reconstructing DTZ values to check if the table uses the 16-bit format. The rest of the modifications are either executed once per initialization or once per file.

I would argue that the speed difference from this patch is too insignificant to raise any concern, or worth any effort to introduce quite a few LOC of template functions for a new `TBTable<DTZ16>` type.

**Comment by DragonMist** [comment]
This is an amazing achievement, generating and being able to use 7 men syzygy on the fly. Thank you for your efforts @noobpwnftw !!
Looking forward how this will work in real life, and expecting some trade off between gaining perfect play and slow disc Access, but once the disc speed and space is not a problem, I expect 7 men to yield something like 30 elo at least.

**Comment by MichaelB7** [comment]
This is a great achievement , but it does appear to be out fo reach for most of us when one considers the disk space required.
```
151G    ./3-6men
3.2T    ./7men_testing/4v3_pawnful         (ongloing)
2.4T    ./7men_testing/4v3_pawnless
2.3T    ./7men_testing/5v2_pawnful
660G    ./7men_testing/5v2_pawnless
117G    ./7men_testing/6v1_pawnful
87G     ./7men_testing/6v1_painless
```

**Comment by MichaelB7** [comment]
... to download just one file from your link will take ~85 days: 
```
Mac-Pro:~ $ wget ftp://ftp.chessdb.cn/pub/syzygy//7men_testing/4v3_pawnless/KRBNvKRB.rtbw
--2018-07-28 13:33:40--  ftp://ftp.chessdb.cn/pub/syzygy//7men_testing/4v3_pawnless/KRBNvKRB.rtbw
           => ‘KRBNvKRB.rtbw’
Resolving ftp.chessdb.cn (ftp.chessdb.cn)... 112.73.74.24
Connecting to ftp.chessdb.cn (ftp.chessdb.cn)|112.73.74.24|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/syzygy//7men_testing/4v3_pawnless ... done.
==> SIZE KRBNvKRB.rtbw ... 46163484752
==> PASV ... done.    ==> RETR KRBNvKRB.rtbw ... done.
Length: 46163484752 (43G) (unauthoritative)

KRBNvKRB.rtbw       0%       219.18K  5.39 KBKRBNvKRB.rtbw       KRKRBNvKRB.rtbw         KRBNvKRB.rtbw   0%     518.96K  3.77KB/s    eta 85d 2h 
```
I have 300 Mbs service , but obviously that is not the speed I'm getting with your link.  FYI, I killed the connection.  I found the lichess link the fastest - but still not ideal, about ~10Mbs.

**Comment by noobpwnftw** [comment]
@MichaelB7 That is why there are mirrors or probably the best if you can build them locally.

**Comment by MichaelB7** [comment]
No,  that would not be best - I had built the 6 man in about 72 hours , this would take   ~7200 hours if the 20 TB is accurate.   I have downloaded two I thought would be interesting to test the code.

**Comment by snicolet** [comment]
@noobpwnftw Thanks for the pull request, as others have pointed out it looks like a really nice feature to have 7-pieces tablebase support in Stockfish :-)

I have a clarification question, and a technical question :

1. clarification:
> As a part of "bug fix", this patch would add one byte-read, one AND, one SHIFT and one OR operation in order to retrieve a potential full 12-bit symbol properly, which may or may not have existed in the past [...]

Can you elaborate a bit about this bug fix? where could we find discussion about this bug, and what lines of the patch are the bug fix?

2. technical question: you have simplified the Huffman tree decoding in lines 156 and 577. Is this related to the "bug" you were referring to, and is your simplification compatible with the current 6-pieces tablebase files?

**Comment by noobpwnftw** [comment]
@snicolet The same answer for both 1 & 2: in the Huffman decoding, a symbol should have never passed 1 byte(since there should not exist more than 256 symbols in the past), so a shortcut was used not to reconstruct the higher bits of it. Now it is no longer true for a few "wide" tables where DTZ values are 16 bits long. It is a simplification in code, but more operations in practice, and a proper way to handle the Huffman decoding without relying on assumptions of data, thus "bug fix" in quotes.

This will not break the decoding of other tables, but if we are to keep the current shortcut and do it right only when necessary, then it looks like we will need a full set duplicated of lines with very little changes which I think not worth the effort (introducing a new template member DTZ16 for TBTable).

**Comment by snicolet** [comment]
Merged via 9afa03b80ea4610729427ee8287a5bbadba03e02. Thanks for everything, Bujun Guo !!

**Comment by mstembera** [comment]
@noobpwnftw   @syzygy1  Sorry to bother you both through here but is there any information available on the win draw loss percentages for each TB file?  The reason I ask is that I would like to attempt to incorporate this purely statistical knowledge into Stockfish evaluation.

**Comment by noobpwnftw** [comment]
@mstembera This site shows a histogram of WDL distribution:
https://syzygy-tables.info/endgames

**Comment by mstembera** [comment]
@noobpwnftw Thanks that is what I was looking for!  Unfortunately it will take a lot of manual clicking since they don't seem to just have a single list for all of them. 
@Rocky640 If you feel like trying any of this yourself please don't hesitate.  I won't have time right away.

**Comment by noobpwnftw** [comment]
@mstembera Stat files generated by the Syzygy generator(*.txt) are also available for each file on my FTP.

**Comment by mstembera** [comment]
Just FYI https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/7XPt3vJztxk

**Pull request closed without merging**
