### PR TITLE
Singular extension search tweak

### PR DESCRIPTION
**Pull request by unaiic**
STC https://tests.stockfishchess.org/tests/view/5f2d22ec61e3b6af64881f40
LLR: 2.94 (-2.94,2.94) {-0.50,1.50}
Total: 17984 W: 2603 L: 2441 D: 12940
Ptnml(0-2): 133, 1751, 5094, 1849, 165

LTC https://tests.stockfishchess.org/tests/view/5f2d5a6a61e3b6af64881f7f
LLR: 2.95 (-2.94,2.94) {0.25,1.75}
Total: 85808 W: 5956 L: 5621 D: 74231
Ptnml(0-2): 149, 4748, 32785, 5063, 159

bench: 4321778

Tweak depth.

### CODE REVIEW

**Comment by vondele** [comment]
@unaiic please squash all commits in the PR.

**Comment by unaiic** [comment]
I don't know why it doesn't let me. Will keep trying...

**Comment by vondele** [comment]
thanks, that makes my work easier. The alternative if the diff of the branch looks fine is to do `git reset --soft master` + (git commit IIRC).

**Comment by Vizvezdenec** [comment]
Just do as I do :) 
Use force master script from https://github.com/glinscott/fishtest/wiki/Creating-my-first-test
Make new branch with identical code changes
Push it
Use this script again
Then in your repo find this branch and make a PR
It will look as following : 
https://github.com/official-stockfish/Stockfish/pull/2946
This is the most easy way to do it if you are (like me) complete monkey in all this git commands and stuff.

**Comment by unaiic** [comment]
Thank you so much @Vizvezdenec. I think I'll continue that way :)
@vondele I opened a new PR in #2949. Closing this one...

**Comment by vondele** [comment]
@unaiic one more refinement... if you make your commit message what you normally put in the pull request (i.e. title tests),  it is even better (no need for me to copy and paste). When you create the pull request, with a single commit in the PR, it will automatically fill the PR comment

**Comment by vondele** [comment]
yes, this helps a lot to save some time merging PRs... thanks!

**Comment by unaiic** [comment]
@vondele Do you mean having the same title for both the PR and the commit it references to?

**Comment by vondele** [comment]
when you write the commit message (i.e. the thing you write when you do `git commit`) try to have it the complete story like:

```
Tweak futility pruning depth.
    
STC https://tests.stockfishchess.org/tests/view/5f2d237161e3b6af64881f43
LLR: 2.96 (-2.94,2.94) {-0.50,1.50}
Total: 12712 W: 1823 L: 1664 D: 9225
Ptnml(0-2): 122, 1166, 3627, 1313, 128
    
LTC https://tests.stockfishchess.org/tests/view/5f2d473061e3b6af64881f6f
LLR: 2.96 (-2.94,2.94) {0.25,1.75}
Total: 12104 W: 912 L: 788 D: 10404
Ptnml(0-2): 13, 665, 4582, 769, 23
        
bench: 4271421
```
In that case, I don't have to do any copy and paste from the web browser (i.e. github).

**Comment by vondele** [comment]
Just in case you can use `git commit --amend` to rewrite the commit message.

**Comment by unaiic** [comment]
Okay, I understand. And is the change in the README in #2939 necessary, or is it lowercase for some reason?

**Comment by vondele** [comment]
README change is fine

**Pull request closed without merging**
