### PR TITLE
Wtime and btime values

### PR DESCRIPTION
**Pull request by johndoknjas**
Nodes searched : 6237567

- If it's White's turn and something like "go btime 50000" is given, SF currently sets White's remaining time to 0 (and vice versa if only wtime is specified). This patch would make SF search for White the same way it would if just "go" were given - i.e., without wtime being a factor.

- If it's White's turn and "go wtime 0" is given, SF searches without stopping. This patch makes it stop instantly, which was the behaviour before commit a84e3ac (June 24, 2020). I think that changing this part of SF's behaviour wasn't part of the commit's intention.

No functional change

### CODE REVIEW

**Comment by Disservin** [comment]
Hmm, I guess this falls under the category of “the user is supposed to enter the correct commands“.

Though point two might be valid in my opinion since go wtime 0 is a valid command and the result should be that stockfish doesn’t search.

**Comment by johndoknjas** [comment]
@Disservin Agreed, the second point was what I was originally working on, then I just noticed the first point as well. Technically though, I'm not sure if it's wrong to do "go btime 5000" if it's White's turn.

**Comment by vondele** [comment]
I don't think this is needed. GUIs send both btime and wtime,  and something like `go wtime 0` is not a useful command.

**Comment by johndoknjas** [comment]
@vondele The command "go wtime 0" may not be useful (most of the time), but it's still a legal command. If it's given, isn't it better for SF to match the expected behavior by returning a move immediately, rather than calculating as if white had endless time left? Stockfish itself already behaved this way before a84e3ac.

While any benefits of my changes might be small, I also feel they don't affect efficiency at all, nor do they add to the complexity of the codebase. It's really just two extra lines of code in uci.cpp, and adding a bool to a struct that's rarely instantiated.

**Comment by xefoci7612** [comment]
Why not simply

```C++
  bool use_time_management(Color stm) const {
    return time[stm];
  }
```

The above IMHO is more explicit about what we are doing, then adding an extra variable _time_management_ that you need to look up for definition.

**Comment by johndoknjas** [comment]
@xefoci7612 This works well to deal with the first point, but the problem is the second point. If "go wtime 0" is sent, time[WHITE] will still equal 0, so the function will return false and time management won't be used.

**Comment by xefoci7612** [comment]
@johndoknjas I see.

From technical POW the correct solution would be to use std::optional for SearchLimits fields, **but** I guess it's up to the maintainers to decide it the change is justified enough, considering that "go wtime 0" is just a theoretical case.

**Comment by johndoknjas** [comment]
@xefoci7612 Optional would work too. Basically just the time value and boolean rolled into one type.
Like u touched on, this patch mainly just covers edge cases, so I was trying to make my change as small as possible.

One possible use case of "go wtime 0" though might be if someone wanted SF to return a move right away. My patch seems to make SF behave the same as if it received "go depth 1" - basically just calculate the minimum allowed.

**Comment by vondele** [comment]
The patch doesn't really fix the UCI command for a case that makes sense to support, as far as I can tell. I'll close it for now.

**Pull request closed without merging**
