### PR TITLE
New History Stat Formula

### PR DESCRIPTION
**Pull request by VoyagerOne**
New History Stat Formula
value=d*d+d-1

STC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 5916 W: 1199 L: 1046 D: 3671

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 21225 W: 3196 L: 3000 D: 15029

### CODE REVIEW

**Comment by VoyagerOne** [comment]
YEAHHHH!!!!  It passed LTC!
CHECKMATE Master!

**Comment by glinscott** [comment]
Congratulations!  Looks good.

**Comment by mcostalba** [comment]
I am worried it can overflow with maxply+1

**Comment by VoyagerOne** [comment]
@mcostalba 
Well we can either do:
A.  Increase the size of the array.
B.  Don't use lookup array and just compute the bonus as we do currently.

**Comment by zamar** [comment]
Let's go for B.

The computation is so simple, that no lookup array really makes sense... Please convert the code to do a direct calculation...

**Comment by VoyagerOne** [comment]
Ok.
The reason I used an array is that during testing I can just modify the formula once.  Not three different times.

**Comment by VoyagerOne** [comment]
@zamar 
@mcostalba 

See: 
https://github.com/official-stockfish/Stockfish/pull/484

**Comment by zamar** [comment]
Closing this one.

**Pull request closed without merging**
