### PR TITLE
Blocked pawn storm

### PR DESCRIPTION
**Pull request by locutus2**
In pawn structures like white pawns f6,h6 against black pawns f7,g6,h7 the attack on the king is blocked by the own pawns. So decrease the penalty for king safety.

STC:
LLR: 2.94 (-2.94,2.94) [0.00,5.00]
Total: 16467 W: 3750 L: 3537 D: 9180
http://tests.stockfishchess.org/tests/view/5a92102d0ebc590297cc87d0

LTC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 64242 W: 11130 L: 10745 D: 42367
http://tests.stockfishchess.org/tests/view/5a923dc80ebc590297cc8806

Bench: 5643527

### CODE REVIEW

**Comment by mcostalba** [comment]
@locutus2 congrats for the succesful patch....but I really don't understand what your patch does.

Coudl yuo please do some example? You write:

"the attack on the king is blocked by the own pawns. So decrease the penalty for king safety."

Which king? Which are the own pawns?

The code is extremely convoluted and out of context: it is a bolt on an already resisting code and very ad-hoc, not orthogonal with previous code.

...nevertheless the patch succeed so we have to cope with this, but we should find a way to rewrite it in a way reader can understand it.

**Comment by mcostalba** [comment]
One idea could be to rewrite using bitboard masks, for instance:

```c++

int r = relative_rank(Us, rkUs) * 8;

if (  (ourpawns & A_MASK[Us] << r) && (theirpawns & A_MASK[Them] << r)
   || (ourpawns & H_MASK[Us] << r) && (theirpawns & H_MASK[Them] << r)
{

  .......
}

```

**Comment by Rocky640** [comment]
@mcostalba 
A sample position that this patch wants to avoid is the following
1rr2bk1/3q1p1p/2n1bPpP/pp1pP3/2pP4/P1P1B3/1PBQN1P1/1K3R1R w - - 0 1

White pawn storm on the king side was a disaster, it locked the king side completely.

The patch is doing exactly this: it penalise storming pawns f6 h6 against black f7 g6 h7 and Kg8 of Kh8

master was giving V(79) to pawn for the blocked pawn h6 and V(161) for the blocked pawn on f6, a total of V(240). The patch is lowering this to V(140)

**Comment by jerrydonaldwatson** [comment]
@Rocky640 Yes, that's the sample position I posted in the FishCooking forum. I believe that not only can White not win, but White is actually lost here.

If I'm not wrong, the safety bonus is 300 in this patch, so the total effect is actually V(-60) now. That's why this patch is worth Elo even though the situation is extremely rare. It's basically a huge penalty for a particular type of useless pawn storm which is massively overvalued at present.

**Comment by mcostalba** [comment]
@Rocky640 thanks! Very clear explanation.

I tried to use Bitboards, but results were not good, so I suggest the following simple tidy up:

```c++
// Enemy pawn storm is less effective in case our shelter blocks them, like
// when enemy has pawns in a3,c3 and our pawns are in a2,b3,c3.
if (   d == 0
    && rkThem == RANK_3
    && rkThem == rkUs + 1
    && (ourPawns   & make_square(f == FILE_A ? FILE_B : FILE_G, relative_rank(Us, rkThem)))
    && (ourPawns   & make_square(f == FILE_A ? FILE_C : FILE_F, relative_rank(Us, rkUs  )))
    && (theirPawns & make_square(f == FILE_A ? FILE_C : FILE_F, relative_rank(Us, rkThem))))
    safety += 300;
```

**Comment by Vizvezdenec** [comment]
I've seen at least 3 games lost/drawn on YLCET because sf locks it own attack by closing pawn structure near enemy king, with this patch it probably will no longer be the case.

**Comment by Rocky640** [comment]
@Vizvezdenec If you can post some links or simple include the full 3 game pgn, that would be very helpful to find other remedies.

**Comment by Vizvezdenec** [comment]
http://chess.my2dollars.ca/ylcetarchivefix.html?s=2
games 63 and 66 sf played horrible plan a4-a5-a6 and lost them both in almost identical manner - it had shown scores like 0.00 or -0.6 in position that was dead lost, It's somewhat similar to what this patch prevents.

**Comment by Rocky640** [comment]
bench should be 5227128

**Comment by jerrydonaldwatson** [comment]
@Rocky640 am I missing something, or are you forgetting the shelter g3/b3 or g6/b6 pawn that's required in Stefan's original patch?

Without that pawn the attack could be very dangerous indeed.

**Comment by Rocky640** [comment]
@jerrydonaldwatson  @mcostalba 
Indeed, I updated the code.

**Comment by Rocky640** [comment]
My code still does not give the same bench. I don't see why
https://github.com/Rocky640/Stockfish/commit/426d6260d9087664f435294ea5a44bc28ac8e35f

**Comment by jerrydonaldwatson** [comment]
@Rocky640 your code is correct, it's simply based on a different master to the one on which bench: 5227128 applies. There is one slight difference in the handling of illegal positions (i.e. if there's a shelter pawn on g2/7 or b2/7) but the bench is identical.

Both your patch and the original give bench: 5401451 when both rebased to the correct master.

**Comment by locutus2** [comment]
@Rocky640 
A nice rewrite of my patch. I commit your version to this branch.

@Vizvezdenec 
We can try to remove the f6/c6 stroming pawn from this pattern to cover your two games.
Or use different penalties dependent of the existence of the f6/c7 pawn (this is probably necessary because the penalty of the f6/c6 pawn is now missing and we overshot with +300)
I will try this idea's against this patch.

**Comment by mcostalba** [comment]
Please check speed is the same: @Rocky640 is nicer but I guess is slower because in your case the first 2 conditions are very cheap and almost always false.

**Comment by locutus2** [comment]
@mcostalba 
I have done speed measurements with FishBench.

Intel core i5-2500 @3.30 GHz
g++ (Rev1, Built by MSYS2 project) 7.2.0
make build-profile ARCH=x86-64-modern COMP=mingw

Base = my implementation
Test = Alains implementation

```
         Mean     StdDev      Diff
Base    1584282   29462      -5491
Test    1589773   29749       6815

p-value: 0,79
speedup: 0,003
```
Surprisingly Alain's version seems a little bit faster. This reason is perhaps that Bitboard operations and popcount are fast. This could be different for 32-bit and non popcount architercture.

Perhaps we should try a retest of this new implementation at STC.

**Comment by locutus2** [comment]
For safety i started a non-regression test of Alain's version and my old original implementation which passed nicely (seems to confirm my measured small speed gain).
http://tests.stockfishchess.org/tests/view/5a95d19c0ebc590297cc8c70

**Comment by snicolet** [comment]
If everybody think that we have converged to the best version, I will commit with Alain's improvements before the master progression test of tomorrow against SF9.

A fun project would be to write a variadic macro to be able to express the masks at compile time like this:

````
const Bitboard ShelterMask = (Us == WHITE ? Pattern(A2,B3,C2) | Pattern(F2,G3,H2)
                                                                            :  Pattern(A7,B6,C7) | Pattern(F7,G6,H7));
const Bitboard StormMask = (Us == WHITE ? Pattern(A3,C3) | Pattern(F3,H3)
                                                                            :  Pattern(A6,C6) | Pattern(F6,H6));
````

**Comment by mcostalba** [comment]
@snicolet even better:

```c++
const Bitboard ShelterMask = Pattern<Us>(SQ_A2, SQ_B3, SQ_C2) | Pattern<Us>(SQ_F2, SQ_G3, SQ_H2);
const Bitboard StormMask = Pattern<Us>(SQ_A3, SQ_C3) | Pattern<Us>(SQ_F3, SQ_H3);

```

I leave it to young C++ heroes :-)

**Comment by mcostalba** [comment]
One possible bug with Alain implementation is the case where we have pawns in A2, B3, C2 and opponent in F3, H3  -> condition is erroneously triggered in this case.

As stated before, current bench is not able to catch this because the only 4 occurrences are all of the same kind.

**Comment by ceebo** [comment]
>A fun project would be to write a variadic macro to be able to express the masks at compile time like this:

Actually I had a go at this last night. Here is the stuff I came up with:

```
#include "types.h"
#include "bitboard.h"

constexpr Bitboard make_bitboard() { return 0; }

template<typename... Squares>
constexpr int make_bitboard(Square s, Squares... squares) {
  return (1ULL << s) | make_bitboard(squares...);
}

constexpr Bitboard flip_bitboard(Bitboard b) {
  return   ((b & Rank1BB) << 56) | ((b & Rank2BB) << 40)
         | ((b & Rank3BB) << 24) | ((b & Rank4BB) <<  8)
         | ((b & Rank5BB) >>  8) | ((b & Rank6BB) >> 24)
         | ((b & Rank7BB) >> 40) | ((b & Rank8BB) >> 56);
}

constexpr Bitboard flop_bitboard(Bitboard b) {
  return   ((b & FileABB) << 7) | ((b & FileBBB) << 5)
         | ((b & FileCBB) << 3) | ((b & FileDBB) << 1)
         | ((b & FileEBB) >> 1) | ((b & FileFBB) >> 3)
         | ((b & FileGBB) >> 5) | ((b & FileHBB) >> 7);
}

constexpr Bitboard flip_symmetrise(Bitboard b) {
  return b | flip_bitboard(b);
}

constexpr Bitboard flop_symmetrise(Bitboard b) {
  return b | flop_bitboard(b);
}

constexpr Bitboard symmetrise(Bitboard b) {
  return flip_symmetrise(b) | flop_symmetrise(b);
}
```

**Comment by jerrydonaldwatson** [comment]
@mcostalba Alain's patch does not have that bug since both theirPawns and ourPawns are limited to the files around our king.

```
Bitboard b =   pos.pieces(PAWN)
               & (forward_ranks_bb(Us, ksq) | rank_bb(ksq))
               & (adjacent_files_bb(center) | file_bb(center));
Bitboard ourPawns = b & pos.pieces(Us);
Bitboard theirPawns = b & pos.pieces(Them);
```

**Comment by mcostalba** [comment]
@jerrydonaldwatson nice :-) you did it.

Adding color is easy at this point:

```c++
constexpr Bitboard make_bitboard() { return 0; }

template<Color C, typename... Squares>
constexpr Bitboard make_bitboard(Square s, Squares... squares) {
  return (1ULL << relative_square(Us, s)) | make_bitboard(squares...);
}
```

...flipping is nice, but maybe not needed.

**Comment by mcostalba** [comment]
Ooops, sorry I made some mistake: it is @ceebo that had fun with variadic templates and @jerrydonaldwatson reporting that there is no bug in Alain's code: my mystake.

**Comment by ceebo** [comment]
@mcostalba Yes, that looks like a good way of doing it. But maybe rename to `relative_bitboard` since it is not obvious that `make_bitboard<BLACK>(SQ_A1)` should return `SquareBB[SQ_A8]`.

**Comment by snicolet** [comment]
Merged via https://github.com/official-stockfish/Stockfish/commit/59d10374ca647feebf9323b21031e47012572fb6.

I keep this pull request open to let the discussion about the variadic Pattern() bloom.

**Pull request closed without merging**
