### PR TITLE
Remove endgame KQvKP

### PR DESCRIPTION
**Pull request by protonspring**
This endgame can be removed.  It is a trivial solution and my tests indicate that it does not contribute anything to playing strength.

After 40k games (tc = 5+0.1), this patch is dead even with master running strictly on KQvKP positions.

This can be validated by downloading my KQvKP fen file and use it as an opening book with cutechess. Set to random and depth to 1.
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/ZXzi8K0CcxU

bench 3729967

### CODE REVIEW

**Comment by vdbergh** [comment]
I assume that endgame is there since otherwise SF will mis evaluate the special cases of the a and c pawn on the 7th rank. They occur rarely but when they do they make an engine look silly if it does not know about them.

**Comment by protonspring** [comment]
Yes, they are unique to KQ vs KP because of stalemates, but I find it hard to believe that sf couldn't figure that out from the normal searching.

**Comment by vdbergh** [comment]
> Yes, they are unique to KQ vs KP because of stalemates, but I find it hard to believe that sf couldn't figure that out from the normal searching.

Try it. Normally engines cannot recognize no progress draws.

**Comment by ddugovic** [comment]
I assume another concern is ensuring that more complex endgames (which may reduce into K+Q versus K+P) fail to detect stalemate opportunities (as either the attacker or defender).

**Comment by protonspring** [comment]
I tested the position:

3Q3K/8/8/8/8/8/p7/k7 w - - 0 1

Master identifies this as a draw (as it should).  The patch still claims an 11.0 advantage, which is obviously incorrect because white cannot win the position.

Sorry for the false alarm.

**Pull request closed without merging**
