### PR TITLE
syzygy clean-up + unit test

### PR DESCRIPTION
**Pull request by lucasart**
This is the current state of my syzygy branch, an effort to clean-up the syzygy code.

I've also created a proper unit test for syzygy: 50acaa3987ab7796be9fc881d7b84f9396987c58.

No functional change.

### CODE REVIEW

**Comment by lucasart** [comment]
@zamar @mcostalba: This is going to be work in progress for a while, similarly to the c++11 branch a while ago. Could you pull it in a new syzygy branch ? Being in the official repo, the syzygy branch is more likely to be looked, tested, and improved by the community.

**Comment by erbsenzaehler** [comment]
I decided to give your branch a shot at Windows but unfortunately I ran into trouble. On Linux it compiles fine with clang/gcc

In file included from syzygy/tbprobe.cpp:18:0:
syzygy/tbcore.h:15:0: warning: "NOMINMAX" redefined
 #define NOMINMAX
 ^
In file included from c:/MinGW/mingw64/x86_64-w64-mingw32/include/c++/x86_64-w64-mingw32/bits/c++config.h:482:0,
                 from c:/MinGW/mingw64/x86_64-w64-mingw32/include/c++/utility:68,
                 from c:/MinGW/mingw64/x86_64-w64-mingw32/include/c++/algorithm:60,
                 from syzygy/tbprobe.cpp:10:
c:/MinGW/mingw64/x86_64-w64-mingw32/include/c++/x86_64-w64-mingw32/bits/os_defines.h:45:0: note: this is the location of the previous definition
 #define NOMINMAX 1
 ^
In file included from syzygy/tbprobe.cpp:20:0:
syzygy/tbcore.cpp: In function 'void* open_tb(const string&, const string&)':
syzygy/tbcore.cpp:58:67: error: cannot convert 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}' to 'LPCSTR {aka const char*}' for argument '1' to 'void* CreateFileA(LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE)'
                         OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
                                                                   ^
make[1]: *** [syzygy/tbprobe.o] Error 1

**Comment by lucasart** [comment]
Seems like a bogus warning from your compiler. Why would it be forbidden to redefine something ?

I will "fix" it nonetheless, because it's important to compile w/o warnings on all major platforms.

**Comment by lucasart** [comment]
@erbsenzaehler: Can you try again ? I pushed a patch that removes the `#define NOMINMAX`. I don't have Windows to test, but looking at the code, I can't see any use for it.

**Comment by erbsenzaehler** [comment]
@lucasart The warning disappeard, but the error is still in place. I get this error with mingw on Linux, too.

In file included from syzygy/tbprobe.cpp:20:0:
syzygy/tbcore.cpp: In function ‘void* open_tb(const string&, const string&)’:
syzygy/tbcore.cpp:58:67: error: cannot convert ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘LPCSTR {aka const ch
                         OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
                                                                   ^
<builtin>: recipe for target 'syzygy/tbprobe.o' failed

**Comment by lucasart** [comment]
@erbsenzaehler: Thank you! Should be fixed now.

If you have syzygy 5-men, can you run on Windows (with this branch):
```
$ ./stockfish
$ setoption name SyzygyPath ../syzygy
$ bench 16 1 10 ./src/syzygy/syzygy.epd
```
Of course you need to adapt to your path. In the SyzygyPath folder must be all 5-men syzygy, and only 5-men. I don't have 6 so we can't compare if you have 5 and 6 in the same folder, best have them in 2 separate folders).

It will bench 2016 randomly generated endgame positions, and you should get:
```
Nodes searched  : 56147723
```
This is basically the syzygy unit test. The only thing missing is to remove stdout spamming, to be able to use it not only as a proof of correctness, but also a performance measure (see #634).

**Comment by joergoster** [comment]
Looks ok here.
Linux Mint 17.2, gcc 4.9.3
```
===========================
Total time (ms) : 20940
Nodes searched  : 56147723
Nodes/second    : 2681362
```

**Comment by erbsenzaehler** [comment]
@lucasart 

The windows build works fine and I get the same bench as you.

I applied your patch on top of both the master and the syzygy branch compiled 6 pgo builds and ran your benchmark 5 times each. Here is the result. To me the results are just fine.

image

**Comment by lucasart** [comment]
Thank you both!

**If** #634 gets merged, we will be able to do much less noisy measures, to measure speed (not only correctness) with better precision. Of course, that wont happen until marco stops crapping on everything I do…

So far: no bug (correctness), no significant speed regression (need less noisy measure to confirm). I will try to run some SMP syzygy test as well.

**Comment by zamar** [comment]
@lucasart: I'm happy to maintain a separate branch for your project. I'll create the branch at some point during the weekend...

**Comment by lucasart** [comment]
@zamar: Thanks. But I need to do 2 things in master, in order to be able to test syzygy properly. Please consider:
- #634
- instead of a syzygy.epd file, better generate it on the fly. that means adding `Position::random()` method, and teaching bench to parse a special file "syzygy", on top of "default". i don't want to waste my time writing and testing all that code, just for marco to crap on it, so i need to know if there is a chance it will be merged in master or not. if not, i keep a syzygy.epd file.

**Comment by lucasart** [comment]
Another benefit of `Position::random()` is that we could also replace the hardcoded set of bench positions, by one generated on the fly. And we control the positions, in terms of nb of pieces, probability of occurence, etc. Much more elegant and flexible, IMO.

**Comment by mcostalba** [comment]
Regarding #634 I have NOT understood what that patch means, I have asked
you to please better elaborate on the issue you are trying to fix (do some
example) but no answer.

Regarding Position::random(), yes definitely I will crap on that: it is a
very bad idea. Current bench positions are NOT random and for a reason,
they are made so to coverage a wide number of cases in middlegame and
especially to cover almost all endgames types so to exercise endgame code.

**Comment by Rocky640** [comment]
We have a set of "natural" positions for the PGO build profiling
The same is used to establish a signature and compare speed.

Generating random positions which are "natural" for middlegame, and even for endgame, is quite a challenge. I'm worried especially about the pawn configurations.

Generate random positions for endgames will certainly be useful for your syzygy testing.
 
If you provide a seed when calling the random generator, you want the same positions to be generated in exactly the same order. So most of the time you will call position::random(0)

If you call with seed -1, you let the random generator choose the seed for you which might be useful in the following context.

If (one day) someone starts to work seriously on sf internal endgame "knowledge", this random generator could be used to create opening books "on the fly" which could be used by fishbench.
A random seed would be used for each worker, and thus more positions would be covered.

For this one would have to be able to specify the endgame of interest.
Either by providing exact number of pieces, or more generally bounds to number of pieces/pawns for each side
//by color, piece type and lower/upper bound
piececonfig[COLOR_NB][PIECE_NB][2]

Nothing is perfect or easy...
One would discard results from games which are adjudicated in less than x moves.

**Comment by zamar** [comment]
Branch syzygy created.

**Pull request closed without merging**
