### PR TITLE
Remove classical psqt

### PR DESCRIPTION
**Pull request by linrock**
Based on vondele's deletepsqt branch: https://github.com/vondele/Stockfish/commit/369f5b051

Replace usage of psqt with weighted material differences in the semi-classical complexity calculation. Tuned weights using spsa at 45+0.45 with:

```c++
int pawnMult = 100;
int knightMult = 325;
int bishopMult = 350;
int rookMult = 500;
int queenMult = 900;
TUNE(SetRange(0, 200), pawnMult);
TUNE(SetRange(0, 650), knightMult);
TUNE(SetRange(0, 700), bishopMult);
TUNE(SetRange(200, 800), rookMult);
TUNE(SetRange(600, 1200), queenMult);
```

Passed non-regression STC:
https://tests.stockfishchess.org/tests/view/64c37d3ddc56e1650abbcaa0
LLR: 2.94 (-2.94,2.94) <-1.75,0.25>
Total: 161664 W: 41267 L: 41184 D: 79213
Ptnml(0-2): 551, 18900, 41811, 19055, 515

Passed non-regression LTC:
https://tests.stockfishchess.org/tests/view/64c48ec9dc56e1650abbe516
LLR: 2.94 (-2.94,2.94) <-1.75,0.25>
Total: 88560 W: 22478 L: 22327 D: 43755
Ptnml(0-2): 54, 9596, 24831, 9743, 56

bench 1375057

### CODE REVIEW

**Comment by snicolet** [comment]
This patch is quite incredible, because:
- in master the `psq_eg_stm()` function is calculated from the side to move point of view (positive if the side to move has material advantage) and then we calculate the absolute distance  to `nnue` which is also side-to-move point of view;
- but in the patch the `material` variable is calculated from the White point of view (positive if White has material advantage), and then we calculate the absolute distance to `nuue`, which is side-to-move point of view.

So this patch is not symmetrical in White vs Black strategy. 

I wonder if it would work so well on a book where the positions out of book would be biased for Black rather than biased for White as in our current testing book.

**Comment by cj5716** [comment]
> This patch is quite incredible, because:
> 
> * in master the `psq_eg_stm()` function is calculated from the side-to-move point of view (positive if the side to move has material advantage) and then we calculate the absolute distance  to `nnue` which is also side-to-move point of view;
> * but in the patch the `material` variable is calculated from the White point of view (positive if White has material advantage), and then we calculate the absolute distance to `nnue`, which is side-to-move point of view.
> 
> So this patch is not symmetrical in White vs Black strategy.
> 
> I wonder if it would work so well on a book where the positions out of book would be biased for Black rather than biased for White as in our current testing book. In other words, I have the fear that the asymmetry introduced by the patch leads to overfitting because almost 100% of our positions in our testing book have a White bias.

I don't think so, because if white has material advantage the score would be positive while if black had material advantage the material score would be negative due to the `pos.count<(piece)>(WHITE) - pos.count<(piece)>(BLACK)` term

**Comment by snicolet** [comment]
I would be more confident in the patch if the model you tuned had the following form:

```
     Color stm = pos.side_to_move();
     int material =   A * (pos.count<PAWN>(stm)   - pos.count<PAWN>(~stm))
                             + B * (pos.count<KNIGHT>(stm) - pos.count<KNIGHT>(~stm))
                             + C * (pos.count<BISHOP>(stm) - pos.count<BISHOP>(~stm))
                             + D * (pos.count<ROOK>(stm)   - pos.count<ROOK>(~stm))
                             + E * (pos.count<QUEEN>(stm)  - pos.count<QUEEN>(~stm));
```

**Comment by snicolet** [comment]
Merged via 0ad9b51deaaa1f2a8273ed064fbf6425cfbbe4f2, thanks :-)

**Pull request closed without merging**
