### PR TITLE
Thread voting reopened

### PR DESCRIPTION
**Pull request by mstembera**
My apologies for opening this again but my original pull request 
https://github.com/official-stockfish/Stockfish/pull/507
was closed before I had any chance to respond.

@mcostalba
It's difficult for me to respond to you as constructively as I would like since you weren't specific about what parts of the patch you don't understand.  For example it would be helpful if you could say whether you think the algorithm itself is too complex or its implementation?  I'm happy to attempt a rewrite based on your suggestions.   I have since committed a simplified version.  I will only be happy if Lucas can come up with something better or simpler to fill that hole.

@zamar
What is the proper test to determine a >5 ELO gain?  Please advise and I will schedule.  I would like to run it with a high number of threads if possible.

### CODE REVIEW

**Comment by zamar** [comment]
@mstembera: A fixed number game test, e.g. 40k games should do.

**Comment by mstembera** [comment]
@zamar 
Scheduled https://github.com/mstembera/Stockfish/compare/07e0741...3fef9cb
We can stop it sooner of course if it looks like it has no chance.  I scheduled w/ 10 threads to maximize the use of the two 11 core and one 31 core machines currently on fishtest.  Thank you.

**Comment by zamar** [comment]
ELO: 0.45 +-3.0 (95%) LOS: 61.7%
Total: 17048 W: 2762 L: 2740 D: 11546

Passing > 5.0 ELO criterion would be a miracle.

I'm closing this pull, but if the test miraculously recovers, please reopen the request once more.

**Comment by mstembera** [comment]
I completely agree.  I have already parked the test at priority -1 before you closed and was going to ask if it was ok that I don't let it finish and close myself.  Thanks for letting me run it!

**Comment by mstembera** [comment]
@zamar 
I now see that you changed the test priority back from -1 to 0.  I leave it completely up to you whether you want to let the test finish or kill it.  I have seen enough.  Thanks.

**Pull request closed without merging**
