### PR TITLE
Fix comment

### PR DESCRIPTION
**Pull request by lucasart**
We always probe, but we do not prune at PV nodes.

No functional change.

### CODE REVIEW

**Comment by glinscott** [comment]
Looks good!

**Comment by zamar** [comment]
I'm not sure what's the right word here... Usingvalue from the previous search is not really 'pruning'.

However 'probing' is also wrong, because we _do_ probe, we just ignore the value...

**Comment by mcostalba** [comment]
Perhaps:

// At non-PV nodes we check TT value for a fail high/low, and immediately return in this case

**Comment by lucasart** [comment]
@zamar: anytime you cut the search tree, for whatever reason, it's called pruning. at least that's what the word pruning means in English.

Some pruning are accurate (beta cutoff), and some are speculative. TT pruning is in fact speculative, because we rely on deeper entries not only exact depth match.

**Comment by zamar** [comment]
whatever...

**Pull request closed without merging**
