### PR TITLE
Prune PV nodes in qsearch (8852247)

### PR DESCRIPTION
**Pull request by lucasart**
**STC**

    LLR: 4.20 (-2.94,2.94) [-3.00,1.00]
    Total: 85573 W: 17195 L: 17125 D: 51253

**LTC**

    LLR: 2.94 (-2.94,2.94) [-3.00,1.00]
    Total: 43385 W: 7298 L: 7214 D: 28873

bench 8852247

### CODE REVIEW

**Comment by zamar** [comment]
The patch is fine. However I'd prefer to commit this together with #205 to stay consistent across the codebase.

**Comment by lucasart** [comment]
ok. should I schedule an SMP test also?

**Comment by zamar** [comment]
I don't think so. We don't split in qsearch, so I don't see a risk for SMP impacts here.

**Comment by Karlon** [comment]
Enough of the drama. This patch is fundamentally beneficial for SF, and must be approved.

**Comment by zamar** [comment]
approved.

**Comment by glinscott** [comment]
Looks good.  As @zamar says, let's commit at the same time as #205.

**Pull request closed without merging**
