### PR TITLE
Simplification: use Arctan for the optimism S-curve

### PR DESCRIPTION
**Pull request by IIvec**
This was idea of Gontran Lemaire (gonlem), but graphs provided didn't seem accurate to me.
I did my own graphs, get my own constants and here is the result:

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 42179 W: 8704 L: 8622 D: 24853

LTC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 17737 W: 2702 L: 2577 D: 12458

Bench 6568181

### CODE REVIEW

**Comment by IIvec** [comment]
Thank you! @DragonMist: Hvala majstore! :)

**Comment by gonlem** [comment]
Congratulations!

Here is the schema comparing current logarithmic optimism and this version of arctan optimism :
comparingoptimismformula

Should optimism be tuned in order to gain ELO against SF8 ? Most of stockfish opponents (all except Houdini and Komodo) are on par or below SF8 level; Tuning stockfish against this level should probably bring stockfish higher in the rating list?

**Comment by IIvec** [comment]
@gonlem: thanks for the graphs, they are good, but it seems that numbers on y axis are doubled. I'm not fond of testing each contempt patch against weaker engines, although I expect good result for this patch.

**Comment by snicolet** [comment]
Merged via 82697f1193cc8c99c99c282361a3ada25c758243.

I am a little bit concerned by the new draw rate after this patch: 70%, which is 10% more than the previous master. This means that we have gone from draw rate 57% one week ago to 70% now. 

In fact "a little bit concerned" is a euphemism, it my biggest fear that we lose somehow, while trying to optimise contempt, the newly introduced willingness of SF10-dev for complexity. 

If in each game played in the framework we see simplifications, simplifications, simplifications, then we will come back to the situation where all the games will be Knight+Rook endgames by move 30, and we will never again be able to pass patches targeting complex searches and complex middlegame positions.

This complexity is BY FAR THE MOST IMPORTANT THING FOR THE SF DEVELOPMENT that I have witnessed in as long time, and we must not come back to Drawfish.

**Comment by IIvec** [comment]
The draw rate at LTC was 67.7%:
http://tests.stockfishchess.org/tests/view/5a9456a80ebc590297cc8a89

and here the draw rate at LTC is 70.2%.

This is 2.5%, and it seems to me that 18K games is low to distinguish this with statistical significance.

**Comment by DragonMist** [comment]
Thinking out loud, and seeing how we still have problems feeding the framework with so much CPU power, here is my suggestion for the maintainer:
In order to better understand the changes introduced by various contempt patches, why not measure it against last 3 official versions (SF7, SF8 and SF9)? It would give us both elo differences as well as draw rates to observe and discuss. In fact, I would make this a standard for the time being, for any patch that changes anything about contempt. For now, it is "only" 9 tests (SF dynamic contempt, SF S curve contempt, SF atan contempt). Granted, I have no idea how to exclude the elo influence of the patches merged in the meantime. Just an idea.

**Comment by IIvec** [comment]
@snicolet: and in your LTC test the draw rate was 69,1%:
http://tests.stockfishchess.org/tests/view/5a9e6e620ebc590297cb617f

By the way, I have nothing against stricter bounds for simplification tests, like [-2,2].

**Comment by snicolet** [comment]
@IIvec OK, maybe I have a little bit over-reacted on the draw rate.

But it is still my biggest fear :-)

**Comment by IIvec** [comment]
@snicolet But, I think that you didn't over-react on simplifications. I do think that simplifications are important, but it seems to me that sprt[-3,1] is not good any more on today's level of computer chess.

**Comment by lp--** [comment]
@IIvec  It is not 2.5% , it is 3% in self-play games.  
@snicolet  After flurry of contempt patches stop, I think it would be right to  measure how this 2(or more if any other gets committed) recently committed patches do against master. If they  don't bring 2-3 elo, 3% in draw rate does not worth it, and patches should be reverted.  I actually doubt there is any elo gain in them as one of the measurement with 80K LTC games did not show any,

**Comment by vdbergh** [comment]
@lp I have already said on multiple occasions that it would be a good idea to have a hard look at the real value of "dynamic contempt" and "contempt+dynamic contempt" in self play.

I have run privately two long tests (160000) games at 40/10 and they did not not show any elo gain for "dynamic contempt" and "contempt+dynamic contempt". I am currently running another  test at 40/20 for the S-version but it will take a long time to complete. It would be of course much easier to do this in the framework but people are strangely reluctant about this. 

Note that SPRT(-3,1) is completely unsuitable for this kind of testing since the result is worthless if the test fails.

**Comment by sf-x** [comment]
Why wasn't this tested against, say SF7? It's probably possible to remove contempt altogether with just (-3,1) tests against master.

**Comment by DragonMist** [comment]
my point, too @sf-x that's why I say it should be tested against SF7 and SF8, too, if pertaining to contempt

**Comment by Stefano80** [comment]
@sf-x no it isn't and has been already tried out several times.

**Pull request closed without merging**
