### PR TITLE
Profile Make

### PR DESCRIPTION
**Pull request by mstembera**
This is essentially a resubmit of
https://github.com/official-stockfish/Stockfish/pull/223
(see comments there) as agreed after SF6 but with the added benefit of fixing both
issue 197
https://github.com/official-stockfish/Stockfish/issues/197
and 167
https://github.com/official-stockfish/Stockfish/issues/167

FYI, clang does not recognize -fno-peel-loops and -fno-tracer.

### CODE REVIEW

**Comment by zamar** [comment]
When compiling with clang after your patch, I just get warnings:
clang: warning: argument unused during compilation: '-fprofile-generate'
clang: warning: optimization flag '-fprofile-use' is not supported
clang: warning: argument unused during compilation: '-fprofile-use'

Which means that clang is basically not doing profiling at all... Am I missing sth?

**Comment by mstembera** [comment]
I was a bit careless and only checked that the clang compile completed with this patch instead of halting as it does with master.  Looking at the output, I also get the "argument unused during compilation: '-fprofile-generate' " warnings but strangely not the '-fprofile-use' warnings.  I use clang 3.4 under Ubuntu.  So the question is whether it's better to leave the clang profile build broken as it is now or have it complete with warnings?  I can see pros and cons both ways.  Just let me know if you want me to remove the clang part of the patch which would make it identical to the original
https://github.com/official-stockfish/Stockfish/pull/223
Thanks!

**Comment by mcostalba** [comment]
It is better to fix properly or not fix at all.

An half fix is not the way to go.

**Comment by mstembera** [comment]
No problem.  Clang changes removed.

**Comment by glinscott** [comment]
Ok, great, so no change for clang?  Change then looks good to me.

**Comment by zamar** [comment]
approved.

**Pull request closed without merging**
