### PR TITLE
Update types.h

### PR DESCRIPTION
**Pull request by ASUSWIN**

### CODE REVIEW

**Comment by MichaelB7** [comment]
Any fishtest results to support the change ?

**Comment by ASUSWIN** [comment]
yes .

Is it obvious to you from the comparison.

I think you can see
And for the reluctance of the clouds

2017-04-10 3:57 GMT+03:00 Michael Byrne <notifications@github.com>:

**Comment by ASUSWIN** [comment]
​

2017-04-10 5:29 GMT+03:00 ali ahmad <al.zhrani.one@gmail.com>:

**Comment by lucasart** [comment]
@MichaelB7: He's just a troll. Have a look at his other PR #1061, that he created under a sock-puppet account. We shouldn't waste time with people like and just close the PR, without further justification.

**Pull request closed without merging**
