### PR TITLE
Do not create option when min == max

### PR DESCRIPTION
**Pull request by lucasart**
Often, we want to tune hollow arrays, where lots of values are zero. In that
case, we would be generating lots of options with trivial intervals min=max=0.

More generally, when min=max, there's nothing to tune, so we may as well not
generate the variable.

### CODE REVIEW

**Comment by lucasart** [comment]
PS: Please note that this pull request is not for the master branch, but for Marco's tune branch.

**Comment by mcostalba** [comment]
Thanks. Idea is good, but the problem is that option is still read anyhow, what happens is that Options[name] is created anyhow in value = Options[name];

**Comment by zamar** [comment]
Then it's Marco who can either approve or reject it...

**Comment by lucasart** [comment]
@mcostalba: It seems to work though. For example, with `TUNE(Outpost)`I get:
**56 options printed**:
```
mThreat_0_0_2,19,9,38,10,0.0020
eThreat_0_0_2,37,18,74,10,0.0020
mThreat_0_0_3,24,12,48,10,0.0020
eThreat_0_0_3,37,18,74,10,0.0020
mThreat_0_0_4,44,22,88,10,0.0020
eThreat_0_0_4,97,48,194,10,0.0020
mThreat_0_0_5,35,17,70,10,0.0020
eThreat_0_0_5,106,53,212,10,0.0020
mThreat_0_1_2,9,4,18,10,0.0020
eThreat_0_1_2,14,7,28,10,0.0020
mThreat_0_1_3,9,4,18,10,0.0020
eThreat_0_1_3,14,7,28,10,0.0020
mThreat_0_1_4,7,3,14,10,0.0020
eThreat_0_1_4,14,7,28,10,0.0020
mThreat_0_1_5,24,12,48,10,0.0020
eThreat_0_1_5,48,24,96,10,0.0020
eThreat_1_0_1,32,16,64,10,0.0020
mThreat_1_0_2,33,16,66,10,0.0020
eThreat_1_0_2,41,20,82,10,0.0020
mThreat_1_0_3,31,15,62,10,0.0020
eThreat_1_0_3,50,25,100,10,0.0020
mThreat_1_0_4,41,20,82,10,0.0020
eThreat_1_0_4,100,50,200,10,0.0020
mThreat_1_0_5,35,17,70,10,0.0020
eThreat_1_0_5,104,52,208,10,0.0020
eThreat_1_1_1,27,13,54,10,0.0020
mThreat_1_1_2,26,13,52,10,0.0020
eThreat_1_1_2,57,28,114,10,0.0020
mThreat_1_1_3,26,13,52,10,0.0020
eThreat_1_1_3,57,28,114,10,0.0020
eThreat_1_1_4,43,21,86,10,0.0020
mThreat_1_1_5,23,11,46,10,0.0020
eThreat_1_1_5,51,25,102,10,0.0020
mThreatenedByPawn_2,107,53,214,10,0.0020
eThreatenedByPawn_2,138,69,276,10,0.0020
mThreatenedByPawn_3,84,42,168,10,0.0020
eThreatenedByPawn_3,122,61,244,10,0.0020
mThreatenedByPawn_4,114,57,228,10,0.0020
eThreatenedByPawn_4,203,101,406,15,0.0020
mThreatenedByPawn_5,121,60,242,10,0.0020
eThreatenedByPawn_5,217,108,434,16,0.0020
mThreatenedByHangingPawn,40,20,80,10,0.0020
eThreatenedByHangingPawn,60,30,120,10,0.0020
```
**56 options generated**
```
option name Outpost_0_18 type spin default 3 min 1 max 6
option name Outpost_0_19 type spin default 9 min 4 max 18
option name Outpost_0_20 type spin default 9 min 4 max 18
option name Outpost_0_21 type spin default 3 min 1 max 6
option name Outpost_0_25 type spin default 4 min 2 max 8
option name Outpost_0_26 type spin default 18 min 9 max 36
option name Outpost_0_27 type spin default 25 min 12 max 50
option name Outpost_0_28 type spin default 25 min 12 max 50
option name Outpost_0_29 type spin default 18 min 9 max 36
option name Outpost_0_30 type spin default 4 min 2 max 8
option name Outpost_0_32 type spin default 4 min 2 max 8
option name Outpost_0_33 type spin default 9 min 4 max 18
option name Outpost_0_34 type spin default 29 min 14 max 58
option name Outpost_0_35 type spin default 38 min 19 max 76
option name Outpost_0_36 type spin default 38 min 19 max 76
option name Outpost_0_37 type spin default 29 min 14 max 58
option name Outpost_0_38 type spin default 9 min 4 max 18
option name Outpost_0_39 type spin default 4 min 2 max 8
option name Outpost_0_40 type spin default 2 min 1 max 4
option name Outpost_0_41 type spin default 9 min 4 max 18
option name Outpost_0_42 type spin default 19 min 9 max 38
option name Outpost_0_43 type spin default 15 min 7 max 30
option name Outpost_0_44 type spin default 15 min 7 max 30
option name Outpost_0_45 type spin default 19 min 9 max 38
option name Outpost_0_46 type spin default 9 min 4 max 18
option name Outpost_0_47 type spin default 2 min 1 max 4
option name Outpost_1_16 type spin default 2 min 1 max 4
option name Outpost_1_17 type spin default 4 min 2 max 8
option name Outpost_1_18 type spin default 3 min 1 max 6
option name Outpost_1_19 type spin default 8 min 4 max 16
option name Outpost_1_20 type spin default 8 min 4 max 16
option name Outpost_1_21 type spin default 3 min 1 max 6
option name Outpost_1_22 type spin default 4 min 2 max 8
option name Outpost_1_23 type spin default 2 min 1 max 4
option name Outpost_1_24 type spin default 1 min 0 max 2
option name Outpost_1_25 type spin default 9 min 4 max 18
option name Outpost_1_26 type spin default 9 min 4 max 18
option name Outpost_1_27 type spin default 13 min 6 max 26
option name Outpost_1_28 type spin default 13 min 6 max 26
option name Outpost_1_29 type spin default 9 min 4 max 18
option name Outpost_1_30 type spin default 9 min 4 max 18
option name Outpost_1_31 type spin default 1 min 0 max 2
option name Outpost_1_32 type spin default 2 min 1 max 4
option name Outpost_1_33 type spin default 8 min 4 max 16
option name Outpost_1_34 type spin default 21 min 10 max 42
option name Outpost_1_35 type spin default 24 min 12 max 48
option name Outpost_1_36 type spin default 24 min 12 max 48
option name Outpost_1_37 type spin default 21 min 10 max 42
option name Outpost_1_38 type spin default 8 min 4 max 16
option name Outpost_1_39 type spin default 2 min 1 max 4
option name Outpost_1_41 type spin default 4 min 2 max 8
option name Outpost_1_42 type spin default 6 min 3 max 12
option name Outpost_1_43 type spin default 6 min 3 max 12
option name Outpost_1_44 type spin default 6 min 3 max 12
option name Outpost_1_45 type spin default 6 min 3 max 12
option name Outpost_1_46 type spin default 4 min 2 max 8
```
Obviously, the same exercise with the current tune branch, gives me 128 options (printed and generated).

**Comment by mcostalba** [comment]
Thanks. Applied with minor modifications in read_option(), to avoid
creating a non exsisting option.

**Pull request closed without merging**
