### PR TITLE
PSQT

### PR DESCRIPTION
**Pull request by mstembera**
Tuned PSQT using a custom tuner.
bench: 5795214
(rebased)

STC
LLR: 3.51 (-2.94,2.94) [0.00,4.00]
Total: 76036 W: 13793 L: 13351 D: 48892
http://tests.stockfishchess.org/tests/view/5963d9020ebc5916ff649aa5

LTC
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 134383 W: 17486 L: 16993 D: 99904
http://tests.stockfishchess.org/tests/view/5967a5a10ebc5916ff649b84

### CODE REVIEW

**Comment by mcostalba** [comment]
Please add test results and bench number in commit message.

**Comment by mstembera** [comment]
@mcostalba Sorry forgot.  Done.

**Comment by snicolet** [comment]
Congrats!

Very curious to learn the details of the new tuner :-)

**Comment by mstembera** [comment]
@snicolet 
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/vQfb8dD_8SI

**Comment by Rocky640** [comment]
Interestingly, the most significant change was square a1/h1 for the knight, which is a rare guest, yet your procedure was able to improve on it.

**Pull request closed without merging**
