### PR TITLE
Move CheckInfo under StateInfo

### PR DESCRIPTION
**Pull request by mcostalba**
This greately simplifies usage because hides to the
search the implementation specific CheckInfo.

No functional change and no speed change.

### CODE REVIEW

**Comment by mcostalba** [comment]
I got no speed difference, but I'd love to have some third party confirmation on this becuase the code affected by this patch is very performance critical.

**Comment by Krgp** [comment]
This is what I (i7 4790k Windows 10 x64 (make build ARCH=x86-64-bmi2 on GCC 530. Standard build & not PGO) got

A. Base = **Master**  vs   Test = PR716

Results for 50 tests for each version:

            Base      Test      Diff      
    Mean    2663807   2657647   6160      
    StDev   5533      3019      7309      

p-value: 0.2
speedup: -0.002

B. Base = PR716  vs  Test = **Master**

Results for 50 tests for each version:

            Base      Test      Diff      
    Mean    2657189   2663061   -5872     
    StDev   3784      5650      8122      

p-value: 0.765
speedup: 0.002

**Comment by joergoster** [comment]
Linux MInt 17.2, gcc 5.3.0
make build ARCH=x86-64-modern
make strip
```
Result of  25 runs
==================
base =    1510644  +/- 7658
test =    1508889  +/- 12589
diff =      -1755  +/- 14897

speedup        = -0.0012
P(speedup > 0) =  0.4088

CPU: x86_64
```

make profile-build ARCH=x86-64-modern
make strip
```
Result of  25 runs
==================
base =    1775984  +/- 2736
test =    1756190  +/- 5326
diff =     -19794  +/- 5783

speedup        = -0.0111
P(speedup > 0) =  0.0000

CPU: x86_64
```

**Comment by Stefano80** [comment]
Measured 20x PGO, 50x concurrent samples against master, got consistently ca. 1% speed-up, see 
[attachment](https://github.com/official-stockfish/Stockfish/files/345283/compare.txt)

**Comment by mstembera** [comment]
x86-64-modern gcc 5.3.0 Win7-64 i7 mobile
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    700802    705723    -4921     
    StDev   231870    233531    7988      

p-value: 0.731
speedup: 0.007
```

**Comment by tthsqe12** [comment]
if you really want to try something, try merging the CheckInfo, StateInfo and the search Stack all together. If Stefano80's results are to be believed, moving pointers around does take a little bit of time.

**Comment by pb00068** [comment]
x86-64-modern gcc 4.8.1 Win7-64 i7-3770 @ 3.4GHz
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1907309   1934100   -26791    
    StDev   8455      12741     6499      

p-value: 1
speedup: 0,014
```

**Comment by MichaelB7** [comment]
both base and test were ran concurrently on a 12 Core Mac Pro
Added 50 Counter loop to benchmark.cpp and then run and summarize

Base 50 Consecutive Runs  - total
Total time (ms) : 96037
Nodes searched  : 190106719
Nodes/second    : 1979515
===========================

Test 50 Consecutive Runs  - total
Total time (ms) : 95273
Nodes searched  : 190106719
Nodes/second    : 1995389

Test was 0.8 % faster

**Comment by mcostalba** [comment]
Thanks to all you guys for thesting it, I will add some more stuff before to merge it. Id' like to better integrate the 2 structs.

**Comment by mcostalba** [comment]
I have further rearranged the code and avoided a costly pinned_pieces() call in evaluation. Now it should be a bit faster and ready to be merged....

**Comment by snicolet** [comment]
Nice job, congrats! 

You can avoid the second costly pinned_pieces() call in eval_init(), going from 3 to 2 calls to  slider_blockers() as follows, if you want:

1) in line 299 of position.cpp, call slider_blockers() for both kings instead of pinned_pieces and discovered_check_candidates(), and store the results in the CheckInfo structure:

````
    ci->blockers[WHITE] = slider_blockers(pieces(), pieces(BLACK), square<KING>(WHITE));
    ci->blockers[BLACK] = slider_blockers(pieces(), pieces(WHITE), square<KING>(BLACK));

    ci->pinned = ci->blockers[sideToMove] & pieces(sideToMove);
    ci->dcCandidates = ci->blockers[~sideToMove] & pieces(sideToMove);
````

2) in line 234 of evaluate.cpp, use these blockers to find the pinned pieces for both colors (this would also eliminate the test at run time against pos.side_to_move()):

````
    ei.pinnedPieces[Us] = pos.check_info().blockers[Us] & pos.pieces(Us);
````

**Comment by joergoster** [comment]
x86-64-bmi2 gcc 4.9.3 LinuxMint 17.2 64bit i5-4570 @ 3.2GHz
standard build
```
Result of  30 runs
==================
base =    2153301  +/- 2790
test =    2172780  +/- 2476
diff =     +19478  +/- 2384

speedup        = +0.0090
P(speedup > 0) =  1.0000

CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
```
pgo-build:
```
Result of  30 runs
==================
base =    2233892  +/- 4129
test =    2234261  +/- 4135
diff =       +370  +/- 1550

speedup        = +0.0002
P(speedup > 0) =  0.6798

CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
```

**Comment by mcostalba** [comment]
@snicolet I don't avoid a pinned_pieces() call, I just move it from one place to another early on.

**Comment by snicolet** [comment]
It seems that in current master we call the "slow" slider-blockers() four times for each move generation + evaluation pair :

a) one call for pinned-pieces() during move generation
b) one call for discovered-check-candidates() during move generation
c) one call for pinned-pieces(us) during evaluation
d) one call for pinned-pieces(them) during evaluation.

As I understand it, your merging of the structures allows to avoid (c) by reusing (a), I just remarked that we can also avoid (d) by reusing (b) since they use the same slider-blockers() under the hood.

Hope this helps, Stephane

**Comment by lucasart** [comment]
@mcostalba: here are my PGO results
```
$ ./pyshbench ../Stockfish/master ../Stockfish/pull 20
run base     test     diff
1   1816449  1815677  -772
2   2833348  2860847  27499
3   2363343  2340693  -22650
4   2836168  2861805  25637
5   1825370  1828494  3124
6   1830452  1831628  1176
7   2385103  2403208  18105
8   1822257  1821481  -776
9   1827321  1821093  -6228
10  2828660  2867565  38905
11  1823035  1831236  8201
12  2823055  2871418  48363
13  1966914  1968273  1359
14  1821093  1821481  388
15  2825855  2786249  -39606
16  1824981  1817994  -6987
17  2826789  2862763  35974
18  2328578  2331118  2540
19  1829277  1827712  -1565
20  2403208  2425712  22504

base = 2242062 +/- 200069
test = 2249822 +/- 200069
diff = 7759 +/- 9242

speedup = 0.0035
P(speedup > 0) = 0.9501
```

**Comment by mcostalba** [comment]
@snicolet ok thanks.
@lucasart thanks for testing and confimring the speed up.

Unfortunately I got a sensible slowdown in perft...

**Comment by DU-jdto** [comment]
@mcostalba Isn't that to be expected? Discovered check candidates aren't currently computed during perft, whilst they will be with this change. This would result in a perft slowdown, but with no corresponding search slowdown.

@snicolet You should be able to go further. Remove the 'target' parameter from slider blockers (should be a non-functional change with your adjustment), remove the 'pinned' and 'dcCandidates' fields from CheckInfo and simply & the appropriate 'blockers' field with the necessary target in Position::pinned_pieces and Position::discovered_check_candidates, and remove the set_check_info call from Position::do_null_move.

**Comment by lucasart** [comment]
@mcostalba: why not merge this ? perft is only a unit test for board/movegen code. it's not perft, but bench speed we care about. sure, if we find a trivial way to speedup perft w/o complicating code, let's do it. but, we shouldn't care about perft speed.

**Comment by mcostalba** [comment]
I am closing now. Interested people are invited to take this code and further improve it with their ideas, as presented in this thread.

**Pull request closed without merging**
