### PR TITLE
Remove temporary shelter array

### PR DESCRIPTION
**Pull request by mstembera**
Remove temporary shelter array and avoid iterating over it each time to find max.
Work done on top of https://github.com/official-stockfish/Stockfish/pull/2277
No functional change.
bench: 4012371

### CODE REVIEW

**Comment by mstembera** [comment]
@protonspring 
Yes, I did benchmark and could not measure any difference.

**Comment by joergoster** [comment]
@mstembera Well, I guess your solution is definitely more elegant than what I had in mind!
```
  // If we can castle use the score after the castling if it is bigger
  if (pos.can_castle(Us & KING_SIDE))
  {
      Score kingsideShelter = evaluate_shelter<Us>(pos, relative_square(Us, SQ_G1));

      if (mg_value(kingsideShelter) > mg_value(score))
          score = kingsideShelter;
  }

  if (pos.can_castle(Us & QUEEN_SIDE))
  {
      Score queensideShelter = evaluate_shelter<Us>(pos, relative_square(Us, SQ_C1));

      if (mg_value(queensideShelter) > mg_value(score))
          score = queensideShelter;
  }
```

However, speedwise I can't measure any difference. ;-)

**Comment by snicolet** [comment]
Merged via 5d1568632ca42b400dff73f5e74ae613e73ed889, thanks :-)

**Comment by snicolet** [comment]
The compare function used in the patch would change bench, I have corrected it in the commit 328bdd0947ea7903ee1061c8eb60bc3121a4eb19 .

**Pull request closed without merging**
