### PR TITLE
Set option Use NNUE to true

### PR DESCRIPTION
**Pull request by nguyenpham**
Implementation for issue https://github.com/official-stockfish/Stockfish/issues/2861

### CODE REVIEW

**Comment by vondele** [comment]
the more challenging part is the CI aspect. In particular, needs somebody who knows Microsoft PowerShell https://github.com/official-stockfish/Stockfish/issues/2823#issuecomment-668389463

**Comment by gvreuls** [comment]
The most challenging aspect is to not give in to the hype and promote new and untested code to the stockfish default. How will this proposed new default perform on ARM/phones for instance?

**Comment by vondele** [comment]
@gvreuls will probably be strong on all ARM chips supporting NEON intrinsics, but this will need something like https://github.com/official-stockfish/Stockfish/pull/2892 to be merged. 

Generally, the project is missing some people that can dedicate some time to ARM / Android etc, to clean up the build support and integrate that in CI. If there is no automatic testing, it is very hard to support.

**Comment by vondele** [comment]
@peterosterlund2 and @daylen do you have a feel for the complexity of integrating / performance of  NNUE on phones ?

**Comment by daylen** [comment]
NNUE branch running on iPhone would run fairly fast now that https://github.com/official-stockfish/Stockfish/pull/2909 is merged (iPhone uses the `apple-silicon` target which enables NEON intrinsics)

NNUE for Android…we would need to follow up on the `armv8` target as you point out in https://github.com/official-stockfish/Stockfish/pull/2892#issuecomment-669191803 and see if we can include `neon = yes` for that target. I'll do some research to see what the most popular processors in Android phones support. But @peterosterlund2 might know already.

**Comment by vondele** [comment]
OK, armv8-neon works as pointed out https://github.com/official-stockfish/Stockfish/issues/2823#issuecomment-669306405
(and I checked my (old) phone would indeed support armv8-neon). Performance would probably be below classical nevertheless.

**Comment by daylen** [comment]
Per https://developer.android.com/ndk/guides/cpu-arm-neon "All ARMv8-based devices support Neon." So rather than make a new target `armv8-neon` I'll submit a quick pull request that just adds `neon = yes` for the `armv8` target. For `armv7` we _could_ add a new `armv7-neon` target…but pretty much every Snapdragon chip since 2016 is `armv8` so I would prefer to keep `armv7` simple (i.e. we don't spend too much effort on `armv7`).

**Comment by domschl** [comment]
I don't know a counter-example of armv8 that doesn't support neon/
According to Android DDK [[1]](https://developer.android.com/ndk/guides/cpu-arm-neon) NEON is optional: "ARM Advanced SIMD, commonly known as Neon, an optional instruction set extension for ARMv7 and ARMv8".
How relevant that is in practice, I dont't know.

It would be a clear advantage, if we can safely set NEON as default for ARMv8: I saw performance improvements of 3x to >4x with NEON, which is a *lot*.

For armv7, I wasn't able to built with NEON on Raspberries.

**Comment by sf-x** [comment]
> According to Android DDK [[1]](https://developer.android.com/ndk/guides/cpu-arm-neon) NEON is optional: "ARM Advanced SIMD, commonly known as Neon, an optional instruction set extension for ARMv7 and ARMv8".
> How relevant that is in practice, I dont't know.
> 
> It would be a clear advantage, if we can safely set NEON as default for ARMv8: I saw performance improvements of 3x to >4x with NEON, which is a _lot_.
> 
> For armv7, I wasn't able to built with NEON on Raspberries.

The same document states:
> All ARMv8-based devices support Neon.

a few lines below. I guess that means Google refuses to support Android on ARMv8 without NEON.

**Comment by domschl** [comment]
Also all apple devices since armv8 do support NEON.
So I guess for all practical purposes, it's a reasonable decision to enable NEON by default for ARMv8.

**Comment by vondele** [comment]
https://en.wikipedia.org/wiki/Comparison_of_ARMv8-A_cores seems to suggest the same: All chips of this type have [...] NEON. 
https://en.wikipedia.org/wiki/ARM_architecture#Armv8-A : Armv8-A makes VFPv3/v4 and advanced SIMD (Neon) standard.

**Comment by TesseractA** [comment]
When people use Stockfish on lichess or other places, they expect to be able to use it on custom positions or variants. For example:
https://lichess.org/editor/rnbqkbnr/pppppppp/8/8/PPPPPPPP/RNBQKBNR/pppppppp/rrrrrrrr_w_-_-_0_1
Eric Rosen played a game against someone else on this position and was curious to see what stockfish would think. NNUE doesn't even run on this position. To avoid porting conflicts (e.g. to javascript) could there be a failsafe that when NNUE crashes, regular Stockfish is applied?

**Comment by vondele** [comment]
@TesseractA also stockfish master stops on this position (with error message if compiled with `debug=yes`), that's basically the invalid fen category. I think lichess runs a fork of stockfish that allows for variants, which they might (or might not) adapt to NNUE:

```
Stockfish/src (master)$ ./stockfish
Stockfish 050820 64 POPCNT by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
position fen rnbqkbnr/pppppppp/8/8/PPPPPPPP/RNBQKBNR/pppppppp/rrrrrrrr w - - 0 1
go depth 3
stockfish: pawns.cpp:106: Score {anonymous}::evaluate(const Position&, Pawns::Entry*) [with Color Us = BLACK]: Assertion `pos.piece_on(s) == make_piece(Us, PAWN)' failed.
Aborted (core dumped)

```

**Comment by nguyenpham** [comment]
@gvreuls: can you explain why did you vote this PR down? I want to understand to improve.

**Comment by gvreuls** [comment]
@nguyenpham I think it's simply too early to make the NNUE evaluation the default. Sure it's qualitatively better than the classic evaluation but we don't know how the code will perform on all platforms and architectures we support yet. Also the new default might surprise a lot of unsuspecting users who just want to upgrade to the new version of stockfish and end up with a configuration that performs miserably (or worse) on their machines. IMO the NNUE evaluation is a big change so it should be introduced gradually.

**Comment by vondele** [comment]
I'll close this PR for now, as it is incomplete, and tracked in the corresponding issue.

**Pull request closed without merging**
