### PR TITLE
Asymmetrical 8x8 Pawn PSQT

### PR DESCRIPTION
**Pull request by Kurtbusch**
STC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 13323 W: 3015 L: 2818 D: 7490
http://tests.stockfishchess.org/tests/view/5c00a2520ebc5902bcedd41b

LTC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 52294 W: 9093 L: 8756 D:34445
http://tests.stockfishchess.org/tests/view/5c00b2c40ebc5902bcedd596

Some obvious followups to this are to further tune this PSQT, or try 8x8 for other pieces. As of now I don't plan on trying this for other pieces as I think the majority of the ELO it brings is for pawns and kings.

Looking at the new values, the differences between kingside and queenside are quite significant. I am very hopeful that this allows SF to understand and plan pawn structures even better than it already does. Cheers!

(Updated with fully tuned values which passed STC)

Bench: 3826765

### CODE REVIEW

**Comment by MichaelB7** [comment]
Very nice work here !!👍👊

**Comment by protonspring** [comment]
Very cool!. . . it will be fun to try to get it back down to symmetric 4x8 without losing elo. :)

**Comment by derpwaffle21** [comment]
Just a question... why isn't this being committed? I thought it passed both STC and LTC? Or am I missing something here?

**Comment by IIvec** [comment]
>           Just a question... why isn't this being committed? I thought it passed both STC and LTC? Or am I missing something here?

Maintainers do not like adding much new code or many new parameters.

**Comment by ianfab** [comment]
Most likely they just do not always have the time to merge patches within three days or are just waiting to allow people to comment on a patch before merging it. Please be patient, I am pretty sure no maintainer is intentionally ignoring this PR.

**Comment by IIvec** [comment]
OK, I'll wait with my tuning values 
http://tests.stockfishchess.org/tests/view/5c03968d0ebc5902bcee15ac
until one of this get comitted.

**Comment by mstembera** [comment]
I scheduled http://tests.stockfishchess.org/tests/view/5c087db10ebc5902bcee7d6d to gather more information.

**Comment by mstembera** [comment]
The result was:
LLR: -2.96 (-2.94,2.94) [-3.00,1.00]
Total: 31058 W: 5024 L: 5227 D: 20807
In favor of this asymmetric psqt.

**Comment by Kingdefender** [comment]
Maybe I misunderstand, but there is IMO no strong reason that pawn square tables should be symmetrical (also for other pieces I suppose but maye it is stronger for pawns) because pawns can not move freely from file to file, it mainly is a bonus to move forward more for one pawn then another and pawn storms are more likely against short castled kings. (I don't know if you can see that in the bonuses I have not checked that, the bonuses can either encourage or discourage pawnstorms on one side of the board),

**Comment by protonspring** [comment]
IMO, these tables should be symmetric.  However, since this proves to gain elo, it can be committed.

If pawns truly could be symmetric, then certainly someone can simplify it back to 4x8 without losing the elo gain.

**Comment by Vizvezdenec** [comment]
In theory since all pieces apart from pawns can move forward and backward PSQTs should be 4x4. 
4x8 or 8x8 are workaround about our imperfect eval heuristics, imho.

**Comment by Alayan-stk-2** [comment]
> IMO, these tables should be symmetric. However, since this proves to gain elo, it can be committed.
Kingside is not equivalent to queenside.

Assuming this is the case isn't a huge issue, but it's nonetheless suboptimal. Chess is not symmetric between kingside and queenside.

Of course, depending on if the kings end up castling kingside and/or queenside, the dynamics will be different and even having the full 8x8 table is suboptimal as it mostly covers the most common situation. But the way to handle these different dynamics better is certainly not to entirely ignore them.

PSQT as a whole are a bandaid to patch limitations of eval heuristics.

**Comment by FauziAkram** [comment]
when is this getting merged? its been already more than a week

**Comment by Chess13234** [comment]
@xoto10
Moving pawns away from king weakens king safety, but it also  may interact with passed pawn bonuses(which are quite significant for any pawn after 2 moves).

**Comment by Vizvezdenec** [comment]
@mcostalba I think this one should be merged. At least people will have codebase to simplify it and it's a pretty clean elo gainer :)

**Comment by mcostalba** [comment]
@Vizvezdenec patch looks good for me.

**Comment by mstembera** [comment]
@xoto10 I agree since the simplification attempt was already tested and failed.  See my test above.

**Comment by FauziAkram** [comment]
What's happening here?
Can we merge it, so we start to make some tests over this ?

**Comment by snicolet** [comment]
OK, I have merged the patch by popular request in 883367d21749eb91a5a3737338b5a7f507751a5a, congrats :-)

But I would say that I didn't like the new values at all, especially the asymmetrical endgame values:
• on the sixth rank a pawn in d6 is worth 12, and in e6 it is worth 21, that's already strange...
• but on the seventh in d7 it is worth 27, but in e7 it is worth 15, really???

**Comment by Vizvezdenec** [comment]
@snicolet well, look at rook endgame PSQT mess now... It also makes 0 sence. Some black magics, what I can say :)

**Comment by mrobaczyk** [comment]
More chaos is not the way to go I think... We should take some effort and try to make these values more sensible.

**Pull request closed without merging**
