### PR TITLE
Remove shelter RANK_1 values and skip adding to shelter if no friendly pawn

### PR DESCRIPTION
**Pull request by protonspring**
RANK_1 values for the pawn shelter are changed to 0, with the previous values being moved to the Unopposed portion of the pawn storm array.  This is a conceptual simplification because the shelter array now only includes actual friendly pawns (no values are added if there are no friendly pawns on the file).  This also allows easy removal of the rkUs variable.

This is a technical simplification because with RANK_1 values removed, we can skip adding a shelter value if we have no friendly pawn on the file.  This should be faster, but mathematically equivalent to master.

The bench is only different because "BlockedByPawn" is expanded to include the state where ANY enemy pawn is blocked on the file.

GOOD) This is a technical and a conceptual simplification as described.

BAD) The "BlockedByPawn" rule is questionable.  It is better because it detects more blockedbyPawns, but it is also worse because it would set BlockedByPawn if a more advanced friendly pawn blocks an enemy pawn (even if an enemy pawn is closer to our king and unblocked (which can be dangerous)).

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 24673 W: 5115 L: 5000 D: 14558
http://tests.stockfishchess.org/tests/view/5ae937be0ebc5926dba90f32

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 11880 W: 1821 L: 1688 D: 8371
http://tests.stockfishchess.org/tests/user/protonspring

### CODE REVIEW

**Comment by protonspring** [comment]
Also, I want to do the same to pawn storm array which would be even faster, but I haven't figured out yet how to get the values out of RANK_1.

**Comment by jerrydonaldwatson** [comment]
My apologies, but I'm not convinced this is really a simplification:

1) This may be personal preference, but I don't like the extra entries in the StormDanger matrix as the cases (Unopposed, BlockedByPawn, etc.) now have unequal lengths. 

2) We lose a line of code, but this is only because
`if ((b = ourPawns & file_bb(f)))`
saves a line. 

3) We now treat shelter pawns and storm pawns quite differently, which decreases readability IMHO. Previously we used RANK_1 for an absent pawn in both cases, and stored both ranks in rkUs and rkThem. To me it makes more sense if the absence of a shelter pawn is taken care of in the ShelterStrength array rather than in StormDanger[Unopposed][][].   

> This is a conceptual simplification because the shelter array now only includes actual friendly pawns (no values are added if there are no friendly pawns on the file).

However, we are still adding values in StormDanger even if there is no storming pawn. 

This passed SPRT[-3, 1] quite easily but in my opinion we should require it at least to pass [0, 4] for code refactoring / speed-up.

**Comment by protonspring** [comment]
It seems clear that the values in ranks 6 and 7 are important.
http://tests.stockfishchess.org/tests/view/5ae9ca820ebc590b101c0e8b

**Comment by protonspring** [comment]
I do have a question:  You seem to suggest that I've added a branch, but I'm not sure I have.  Master does a 
 similar branch (Rank rkUs = b ? relative .. .)?  Mine is an "if" statement.   Is there a real difference between these two?

**Comment by protonspring** [comment]
Failed 0,4 after 26k games.
http://tests.stockfishchess.org/tests/view/5aeb68c00ebc5903942c756e

**Pull request closed without merging**
