### PR TITLE
Simplify BxN trade logic

### PR DESCRIPTION
**Pull request by pb00068**
STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 14716 W: 2717 L: 2586 D: 9413
http://tests.stockfishchess.org/tests/view/5a0026940ebc590ccbb8a4a8

LTC: 
LLR: 2.94 (-2.94,2.94) [-3.00,1.00]
Total: 115424 W: 14540 L: 14540 D: 86344
http://tests.stockfishchess.org/tests/view/5a005c7c0ebc590ccbb8a4ef

Bench: 5019047

### CODE REVIEW

**Comment by pb00068** [comment]
N.B.: Closed and reopened in order to pass travis build ...

**Comment by mcostalba** [comment]
I am not sure I can "see" the simplification here: original code I can understand at first glance, this patch I needed to read many times..may be I am getting dumb (it is a real possibility), but original version it seems more dumb-proven to me.

**Comment by pb00068** [comment]
I'm pretty neutral about this patch. Let us hear the opinion from others ...

**Comment by ceebo** [comment]
This patch might be better with a comment e.g.:

```
// If history score is good tweak SEE threshold so that all BxN captures pass
```

**Comment by pb00068** [comment]
@ceebo Overmore this patch includes also some rare BxN trades where the exchanges start with a Queens trade (=Bishop behind Queen x-raying the target square, so Queen must start exchange QxQ even if it's the most valuable piece)

**Comment by ceebo** [comment]
@pb00068 Yes when you consider that this test only applies to moves where the SEE sequence begins with a capture I can't actually think of any sequences where the final balance is 2 Rooks for a Queen. If the side with two Rooks starts with a queen capture then that is obviously good. Maybe sequences with balance Bishop for Knight are the only realistic trades that this patch allows. I'm not sure.

**Comment by tthsqe12** [comment]
Not a simplification.

**Comment by pb00068** [comment]
Codewise (= number of lines &instructions) it is a simplification.

After some pondering the crucial point seems to be, if we consider this patch making something more **obsure**, or if it is merely making something more **abstract** , generalizing a concept. 
Instead bothering about all possible exchanges that fullfill pos.see_ge(move, KnightValueMg - BishopValueMg) we could simple see it in the following way: 
- if the move has a particular good score then we handle it as 'good' capture, even when SEE reports a sligthly negative balance. What exchanges exactly fit or not, is in the end very secondary once the patch has proved to work. Just my opinion.
Also for singular extension (= the prime example of abstraction) we don't ask for the type of move, wheter if it's a capture, check or a quiet move etc..

**Comment by pb00068** [comment]
Also test http://tests.stockfishchess.org/tests/view/5a07576b0ebc590ccbb8a89e goes in this direction...

**Comment by vondele** [comment]
@pb00068 yes, inspired by your patch. Personally I think that one is a clear simplification, but given the discussion here, I thought testing with [0,4] was more convincing... maybe the wrong choice ;-)

**Comment by syzygy1** [comment]
I would also see it as a simplification, and even more so @vondele 's patch that is now being tested.

**Comment by lucasart** [comment]
Patch is good. It's both a simplification, and a generalisation. Both going in the right direction.

**Comment by mcostalba** [comment]
I have merged #1305, closing this one.

**Pull request closed without merging**
