### PR TITLE
Precompute pawn shelter/storm masks

### PR DESCRIPTION
**Pull request by protonspring**
This is a non-functional speed-up (on my machine).  I'm doing a PR to see if others see the same.

In the process of playing with a new version of shelter/storm code, this patch ended up being a little faster on my machine.  The ShelterStrength is mathematically equivalent to ShelterWeakness with a new SafetyBase.  The speed-up presumably comes from the precomputed pawn shelter/storm masks.

200 runs of psybench:
base = 1326829 +/- 8929
test = 1355300 +/- 9291
Diff  = +28471

speedup = +.0215
P(speedup > 0) = 1.0000

Bench: 5351765

### CODE REVIEW

**Comment by syzygy1** [comment]
Precomputing the masks is a good find and may indeed explain a speedup.

I wanted to say the patch still needs to pass a test, but it seems the testing guidelines have been updated on this point.

Am I correct in thinking that the other changes are unnecessary and essentially unrelated? (I can't say if they are an improvement or not in the sense of code clarity, but they should probably not be mixed with a speed optimisation.)

If the speedup turns out to be real, I guess the bitboard initialisation should be moved to bitboard.cpp.

**Comment by Hanamuke** [comment]
Very significant speedup, good job !

**Comment by Hanamuke** [comment]
It seems like a [0;4] STC is needed, if there is a 2% speedup it shouldn't struggle to pass.

**Comment by jerrydonaldwatson** [comment]
Yes, let's test this on the framework. Even if it is a 1% speedup it has a good chance to pass.

**Comment by snicolet** [comment]
The [0..4] STC should be against the simplified version of pull request 1551:
https://github.com/official-stockfish/Stockfish/pull/1551

It seems unlikely to me that we can get a 2% speed-up against a function which is not in the hot spot (the result of do_king_safety() is cached).

**Comment by protonspring** [comment]
Something was amiss.  I updated my master and it's not faster anymore.  Also, STC SPRT[0,4] failed.
LLR: -2.96 (-2.94,2.94) [0.00,4.00]
Total: 14324 W: 2864 L: 2972 D: 8488
http://tests.stockfishchess.org/tests/view/5ad601500ebc595700526d62

**Pull request closed without merging**
