### PR TITLE
MSVC native application code had char vs wchar_t type mismatch and didn't compile

### PR DESCRIPTION
**Pull request by maximmasiutin**
### Summary of changes
It now compiles under Microsoft Visual Studio.

In Win32 API, by default, most null-terminated character strings arguments are of wchar_t (UTF16, formerly UCS16-LE) type, i.e. 2 bytes (at least) per character. So, src/misc.cpp should have proper type. Respectively, for src/syzygy/tbprobe.cpp, in Widows, file paths should be std::wstring rather than std::string. However, this requires a very big number of changes, since the config files are also keeping the 8-bit-per-character std::string strings. Therefore, just one change of using 8-byte-per-character CreateFileA make it compile under MSVC.

### Performance comparison
The existing MSVC code in Stockfish seem outdated and did not probably ever was compiled for a long time. However, with these small changes it compiles with the most recent MSVC version. This compiler can be used to debug the application, as it has very decent GUI IDE. Also, even with plan C++ it gives decent performance, comparable to that one by the officially-released Windows .EXE (POPCNT).

command: 
```
bench 2048 1 1000 default movetime
```

MSVC (no architecture like AVX512 specified, just default target basic x64):
```
Total time (ms) : 46032
Nodes searched  : 52812000
Nodes/second    : 1147288
```

Official .exe (POPCNT):
```
Total time (ms) : 46029
Nodes searched  : 56108568
Nodes/second    : 1218982
```

### Fishtest
I have submitted this diff to FishTest at https://tests.stockfishchess.org/tests/view/640dd56165775d3b539cba42 but it will unlikely affect anything. According to Disservin in Discord, "you dont need fishtest that for that local compilation and ci should be enough. also CreateFileA can even crash but no one knows since its not called; im gonna put prio -1 since fishtest is rather full and i dont see any value in this; no windows worker has picked it up :p; though you can open a pr and start a github discussion"

```
LLR: -0.11 (-2.94,2.94) <0.00,2.00>
Total: 2872 W: 760 L: 765 D: 1347
Ptnml(0-2): 17, 281, 839, 288, 11
```

### CODE REVIEW

**Comment by Sopel97** [comment]
It was mention on discord, but reiterating here for completeness.

The support for MSVC was halted due to incorrect codegen with AVX2 that were unable to track down to anything else than a compiler bug. The secondary reason was that MSVC compiles were just terrible, a few % slower than gcc and clang. The tertiary reason was that fishtest didn't use MSVC at all so it wasn't being tested often.

To bring back support for MSVC the following is required:

1. Performance within 1-2% of GCC PGO builds for ALL supported x86 architectures
2. Correct codegen for all supported x86 architectures with the current version of the MSVC compiler.
3. Finding the last MSVC version that was causing issues, or finding a reasonably old one that works and requiring that at compile time.

**Comment by mstembera** [comment]
SF currently compiles fine w/ MSVC 2017 and 2019.  I tested the AVX2 bench and it's correct.  The speed of the binary is irrelevant imo.  The primary benefit of MSVC is its GUI and great debugger integration.  The last issue was simply that the default stack size was too small.  See https://github.com/official-stockfish/Stockfish/pull/3797#issuecomment-978473295  The official thing that has been discontinued is testing by running AppVeyor.  I also tested this patch and it compiles fine w/ the above mentioned versions.  I will be updating to 2022 soon and welcome these fixes if they are required for 2022.  Also see https://github.com/official-stockfish/Stockfish/pull/3797#issuecomment-978865572

**Comment by maximmasiutin** [comment]
@mstembera - for me, it didn't compile under MSVC 2019 without those changes. I just created a new C++ console application project and manually added StockFish .cpp and ,h files. It gave errors in character types. When I fixed these errors (as shown in this commit), it compiled in MSVC 2019. Maybe in your case, you had some other options, like defaulting Win32 API to ANSI version (such as CreateFileA), as MingW does, but I used default options which are UTF16 (such as such as CreateFileW), so my changes were needed.

**Comment by mstembera** [comment]
@maximmasiutin I created my project using 2017 years ago and then upgraded it using 2019 so maybe the options were different.  Both versions (masted and patch) compile for me so I think it's good to make these changes since they are minimal and as you say are needed when creating a new project from scratch w/ defaults.

**Comment by Yery** [comment]
I support this pull request. It is great to have the code compatible with MSVC for those who want it.

**Pull request closed without merging**
