### PR TITLE
Fix handling of empty strings in uci options and reassigning of the log file.

### LINKED ISSUE #3650: "setoption name debug log file value" does not close previous debug log file
Windows 10 

Running stockfish in a command window and issuing the command
   setoption name debug log file value c:\users\jomeg\sf.log
 correctly starts a debug log to that file. However, I'd expect the command
   setoption name debug log file value
to close the file. I expect that because it seems the intension of the uci doc and the code at
misc.cpp#126 which is the code to close the file.

However, the file never closes, and you cannot open another file with the setoption command either.
I know it does not close because any attempt to delete it fails (until stockfish is exited).

I believe the problem is in ucioption.cpp#167, which is...

  if (   (type != "button" && v.empty())
      || (type == "check" && v != "true" && v != "false")
      || (type == "spin" && (stof(v) < min || stof(v) > max)))
      return *this;
      
Since the type of this option is "string" and the value of v is indeed empty (verified by single stepping in a debugger)
the return happens immediately and hence the on_change() function does not get called, and hence the code
misc.cpp#126 to trigger closing the file never happens.

### PR DESCRIPTION
**Pull request by Sopel97**
Fixes #3650

### CODE REVIEW

**Comment by jomega-github** [comment]
> Fixes #3650

Thanks Sopel.

**Comment by man4** [comment]
This seems to break the case when EvalFile is set to blank:
```
setoption name EvalFile value
go infinite
info string ERROR: If the UCI option "Use NNUE" is set to true, network evaluation parameters compatible with the engine must be available.
info string ERROR: The option is set to true, but the network file  was not loaded successfully.
...
```
It's useful to set this to blank in a GUI (e.g. cutechess GUI) so that when you download new dev versions with new nets, you don't have to manually change the EvalFile parameter each time. I thought this was supported functionality (but I could be wrong)

**Comment by Sopel97** [comment]
we can make it ignore attempts to load a net from ""

**Comment by Sopel97** [comment]
I'd think the gui would have an option to just ignore some settings and rely on defaults? This is quite unfortunate, I'll try to come up with a fix.

**Comment by Sopel97** [comment]
@man4 see https://github.com/official-stockfish/Stockfish/pull/3668

**Comment by man4** [comment]
looks good, thanks!

**Pull request closed without merging**
