### PR TITLE
Update AUTHORS for SF8

### PR DESCRIPTION
**Pull request by ppigazzini**

### CODE REVIEW

**Comment by Rocky640** [comment]
Many duplicates...3 Nicolet, 3 Ralph, 3 Oster, 2 Costalba and 2 Lucas

**Comment by ppigazzini** [comment]
Yes, I generated the file according the comment: 'git shortlog -sn | cut -c8-' and manually ordered the first four authors.

There are many duplicates in git but I'm sure only for some nicknames, e.g.:
 - "Lucas Braesch" "lucasart"
 - "Stephane Nicolet" "StÃ©phane Nicolet" "snicolet"

**Comment by Stefano80** [comment]
The same for me, I am listed both ad Stefano80 and Stefano Cardanobile...

**Comment by lantonov** [comment]
Marco Costalba and mcostalba

**Comment by mcostalba** [comment]
@ppigazzini please remove duplicates for this to be merged.

**Comment by ppigazzini** [comment]
@mcostalba I opened a thread to collect info about duplicates before updating AUTHORS file, some duplicates are not easy to spot (e.g. stefano80)
 
https://groups.google.com/d/msg/fishcooking/1FdriZHxnto/KYdx1pPFBwAJ

**Comment by ppigazzini** [comment]
@vondele: thank you, this duplicate was hidden in plain sight :)

**Comment by mcostalba** [comment]
Merged with f5d3f0ded6839f2eaf

**Pull request closed without merging**
