### PR TITLE
Revert "Always remember the ttMove"

### PR DESCRIPTION
**Pull request by joergoster**
This reverts commit 6596f0eac0c1d25a12bfd923907bfc78beedbc90.

Bench: 3610831

### CODE REVIEW

**Comment by joergoster** [comment]
Adding an assert at the end of qsearch() where we assign a mate score ...
```
    // All legal moves have been searched. A special case: If we're in check
    // and no legal moves were found, it is checkmate.
    if (inCheck && bestValue == -VALUE_INFINITE)
    {
        assert(!MoveList<LEGAL>(pos).size());

        return mated_in(ss->ply); // Plies to mate from the root
    }
```
... reveals, that after the patch this assertion does get triggered.

> stockfish: search.cpp:1581: Value {anonymous}::qsearch(Position&, Search::Stack*, Value, Value, Depth) [with {anonymous}::NodeType NT = <unnamed>::NonPV; Depth = int]: Assertion `!MoveList<LEGAL>(pos).size()' failed.
> Abgebrochen (Speicherabzug geschrieben)

As I already wrote in #3171, I didn't look into the details of that patch. I leave this to the author of the patch.

**Comment by syzygy1** [comment]
So this is functional, right? (Even if it might not change bench.)

It might help the discussion if you could give a position where a single-threaded search triggers the assert (I suppose a normal doesn't trigger it).

Is there ever an occasion where the ttMove is first pruned away by movepicker but then later played anyway when it gets generated? That seems weird.

**Comment by joergoster** [comment]
Yes, the original commit was functional, so is the revert. Bench changes as well.

**Comment by syzygy1** [comment]
So if we're in check, we shouldn't throw out the ttMove just because it isn't a recapture.

**Comment by syzygy1** [comment]
Yes, that seems to be the real bug.

**Comment by syzygy1** [comment]
This should fix it:
https://github.com/syzygy1/Stockfish/commit/26e7818590a5563586db90d2c95559b904a3f544

**Comment by syzygy1** [comment]
I guess it is debatable what the preferred fix would be (revert or my proposal).

**Comment by joergoster** [comment]
I'm fine with either one.

**Comment by syzygy1** [comment]
Does the revert also have 3817613 as bench?

**Comment by joergoster** [comment]
No, the revert has 3610831 as bench.

**Comment by syzygy1** [comment]
OK, I would say my fix should _in theory_ be slightly better because it will try the tt move first when in check (when depth <= DEPTH_QS_RECAPTURES), whereas the revert tries the tt move only in the order it is generated.

**Comment by vondele** [comment]
thanks for the discussion here. I have a slight preference for the alternative patch, but let's keep this one open till one or the other fix has been merged.

**Comment by joergoster** [comment]
@vondele Ronald's fix is to be preferred, of course! Feel free to close this one after merging #3199.

**Pull request closed without merging**
