### PR TITLE
Refine rook penalty on closed files

### PR DESCRIPTION
**Pull request by Lolligerhans**
I submit the PR code almost (*) as tested.

### Code
1. I will shortly try replacing the `is_on_open_file()` calls with inlined versions. This may allow to reuse some values from the first check, since they are quite close. I find it more convenient to have functionally relevant parts inside _evaluate.cpp_ (function is only used in this bonus [Edit: also in the new KingOnFile bonus]).
2. Since we now identify "more strongly closed files", it may be worth moving trapped rook into that category; I will also test this change later.
3. (*) I replace the `make_score` of the test w/ a `constexpr` variable. A negligible change I assume (binary _does_ change for me).

If you want results from 1 and/or 2 to be reflected in this commit I can add them once present.

### Commit
1. Anticipating vdv adding a "closes #xyz". ;)
2. LTC first since nobody will care about STC.
3. As usual, the ascii board can get jumbled when the commit is no represented w/ monospace fonts; even worse if newlines are ignored. Therefore the same information is added in textual form.

### Test
1. There are some obvious tweaks worth trying: Using only their pieces to block, their pieces+our pawns, their pawn-double attacks, squares they attack more often than us, ...
2. Also, the value `S(10, 5)` was a first guess and might not be optimal. `S(30, 15)` failed STC. It is completely untuned against the existing open file bonuses and biases (lowers) the average rook value. It may be good to tune this bonus together with the existing open file bonuses and some generic offset (to allow tuning to un-bias values, later added on mobility or psq).

I hope that if the "very-closed" states (behind blocked pawn) can be refined enough, the penalty of having rooks on "very-closed" can be increased (especially the mg value) and/or potentially replace the mobility. In the commit message example, blacks rooks maximize mobility on b8, altough they clearly should be placed on a kingside file. (Maybe I dig for my wedged pawn structure tests :P)

### CODE REVIEW

**Comment by Lolligerhans** [comment]
Side note: All tests were using `closedpos.epd`.

**Comment by SFisGOD** [comment]
@Lolligerhans Non-regression for default book

**Comment by SFisGOD** [comment]
It might be interesting to try a version that will make sure that it will only apply for closed positions. See the conditions for closedpos here https://github.com/official-stockfish/books/pull/8

**Comment by Lolligerhans** [comment]
> 
> 
> @Lolligerhans Non-regression for default book

I thought closedpos.epd was considered sufficient, is my memory mistaken here?
I have LTC regression over _noob_3moves.epd_ at prio -1. Will I need to test STC too?

**Comment by locutus2** [comment]
@Lolligerhans 
i think a LTC non-regression is enough. I approved and set prio to 0

**Comment by SFisGOD** [comment]
> I thought _closedpos.epd_ was considered sufficient, is my memory mistaken here?

Can you refer to a commit that only passed closedpos?

**Comment by Lolligerhans** [comment]
@SFisGOD I did not recognize anybody else using this book regularly. :D

**Comment by Lolligerhans** [comment]
> It might be interesting to try a version that will make sure that it will only apply for closed positions. See the conditions for closedpos here [official-stockfish/books#8](https://github.com/official-stockfish/books/pull/8)

I imagine that (for positions where this specific bonus applies, or applies more often), the closedness conditions correlate strongly with the mg/eg distinction represented in the Score of the bonus: Mg ensures a piece count, the bonus applying means that some pawns are blocked. But I think the bonus is sound in endgames or less open positions, too. (Somebody else can try it if they like to :))

**Comment by Lolligerhans** [comment]
The explaining comment in the Bonuses declaration for `RookOnFile` is out of sync with it's new name. I will fix when I add the nonregression to the commit message.

(I assume that I am ought to add said test as well.)

**Comment by Lolligerhans** [comment]
- Added the non-regression to the commit message.
- Removed the explaining comment at bonus score declaration for `RookOnFile` (now `RookOnOpenFile`). It is still explained that the bonus is about open, half-open and closed files in `Evaluate::pieces` where the bonus is applied. I don't think the comment was too helpful at the point of declaration but of course I can add it back.
- The non-regression was underwhelming (about 0.00), but there's already an apparent speedup that makes the added check less expensive. Also, SF-Classic's longeer TC games  (e.g., TCEC or home analysis) tend to end up a lot more closed than 1-minute testing games. I hope testing on closedpos helps especially against positionally superior competition.

**Comment by Lolligerhans** [comment]
> 
> 
> > I thought _closedpos.epd_ was considered sufficient, is my memory mistaken here?
> 
> Can you refer to a commit that only passed closedpos?

@SFisGOD Looking it up I can find some from the initial hype after introducing closedpos:
- Not checking at all https://github.com/official-stockfish/Stockfish/pull/2662
- Checking STC only https://github.com/official-stockfish/Stockfish/pull/2670

In the initial discussion, no procedure was explicitly agreed upon: https://github.com/official-stockfish/Stockfish/issues/2646.

**Pull request closed without merging**
