### PR TITLE
Provide selective search depth info for each pv move

### PR DESCRIPTION
**Pull request by joergoster**
Now we can show for each pv move how deep it has been searched.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Why you removed PvNode condition? This is very important because we want seldepth to be considered only in PV nodes, not in side searches.

Please restore 


`    if (PvNode && thisThread->maxPly < ss->ply)`

If you don't have real  reasons to remove it.

**Comment by mcostalba** [comment]
I think there is something wrong here: maxPly should be associated to RootMove or to thread?

If it is a RootMove property (as I can see) then patch should be rewritten to remove maxPly from threads.

**Comment by joergoster** [comment]
@mcostalba The reason is I want to know how deep ANY branch has been searched.

**Comment by mcostalba** [comment]
Also this is wrong in SMP case:

`rm.maxPly = thisThread->maxPly;`

I understand the idea, but implementation is totally to rewrite, I'd suggest to start figuring out from where you want to store the running maxPly counter (at first glance it should be linked to root move, but I have not analysed deeply).

**Comment by mcostalba** [comment]
@joergoster any branch? well this is a semnatic change that has not been advertized in teh patch message and it is orthogonal to the patch main purpose (to extend SelDepth to MultiPV case), you are instead also changing the meaning of SelDepth....

**Comment by joergoster** [comment]
@mcostalba You're right, the change of meaning of selDepth was not advertized. So if you prefer the 'old' way I have no problem to revert to the old code. The difference is not that big in most cases anyway.

I don't understand your concerns about SMP case here. We are dereferencing from thisThread->rootMoves, right?
```
          RootMove& rm = *std::find(thisThread->rootMoves.begin(),
                                    thisThread->rootMoves.end(), move);
```

Well, somewhere we need to keep track of selDepth. I considered this way to be the cleanest solution. It's also safe in case search gets interrupted in multipv mode, and we must output the information from the previous iteration.

**Comment by mcostalba** [comment]
@joergoster I have rewritten the patch in a way to be more consistent (in particular to associate a new selDepth to each depth in IID, as UCI protocol suggests), please see:

https://github.com/official-stockfish/Stockfish/pull/1168

I have tried to explain the logic in the commit message.

**Comment by joergoster** [comment]
@mcostalba Patch updated with renaming of variables and resetting selDepth at the beginning of the MultiPV loop.
This is how it looks like in MultiPV mode now.
```
info depth 14 seldepth 19 multipv 1 score cp 26 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv e2e4 e7e5 g1f3 b8c6 f1b5 g8f6 e1g1 a7a6 b5c6 d7c6 d2d3 c8g4 h2h3 g4h5
info depth 14 seldepth 20 multipv 2 score cp 13 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv e2e3 g8f6 g1f3 d7d5 d2d4 e7e6 c2c4 f8e7 c1d2 c7c5 d4c5 e7c5 f1d3 b8c6 e1g1 e8g8 b1c3
info depth 14 seldepth 16 multipv 3 score cp 13 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv g1f3 d7d5 d2d4 g8f6 c2c4 e7e6 e2e3 f8e7 c1d2 c7c5 d4c5 e7c5 f1d3 b8c6 e1g1
info depth 14 seldepth 19 multipv 4 score cp 13 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv d2d4 d7d5 e2e3 e7e6 c2c4 g8f6 g1f3 f8e7 c1d2 c7c5 d4c5 e7c5 f1d3 b8c6 e1g1
info depth 14 seldepth 22 multipv 5 score cp -2 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv a2a3 e7e5 d2d4 e5d4 c2c3 d4c3 b1c3 g8f6 e2e4 d7d6 g1f3 b8d7 c1f4 d8e7 d1e2 e7e6 e1c1
info depth 14 seldepth 21 multipv 6 score cp -6 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv b1c3 d7d5 d2d4 g8f6 c1f4 e7e6 e2e3 f8b4 f1b5 c8d7 b5d7 b8d7 g1e2 e8g8 e1g1 b4d6 f4d6
info depth 14 seldepth 18 multipv 7 score cp -10 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv a2a4 e7e5 e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 b2b3 f8e7 c1a3 b8c6 f1c4 e6g6 c3b5 e7d8 d2d3
info depth 14 seldepth 20 multipv 8 score cp -11 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv c2c3 e7e5 d2d4 e5e4 c3c4 g8f6 e2e3 c7c6 c1d2 f8e7 g1e2 e8g8 b1c3 d7d6 d4d5 b8d7 e2g3 c6d5 c3d5
info depth 14 seldepth 21 multipv 9 score cp -13 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv h2h3 d7d5 d2d4 g8f6 e2e3 e7e6 b1d2 c7c5 g1f3 c5c4 f1e2 f8d6 e1g1 e8g8 c2c3
info depth 14 seldepth 21 multipv 10 score cp -15 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv c2c4 e7e5 b1c3 b8c6 g1f3 g8f6 d2d4 e5d4 f3d4 f8b4 e2e3 e8g8 f1d3 c6e5 e1g1 d7d6 d3e2 c8d7 c3d5
info depth 14 seldepth 18 multipv 11 score cp -23 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv f2f4 g8f6 e2e3 d7d5 g1f3 e7e6 f1e2 c7c5 e1g1 f8e7 d2d4 c8d7 f3e5 b8c6
info depth 14 seldepth 22 multipv 12 score cp -28 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv d2d3 e7e5 g1f3 b8c6 e2e4 g8f6 f1e2 d7d5 e4d5 f6d5 c1d2 f8c5 e1g1 d5f6 b1c3 e8g8
info depth 14 seldepth 21 multipv 13 score cp -31 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv h2h4 e7e5 e2e3 b8c6 d2d4 d7d5 f1b5 e5e4 g1e2 g8f6 c2c4 f8b4 c1d2 b4d2 b1d2 e8g8 c4d5 d8d5
info depth 14 seldepth 21 multipv 14 score cp -50 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv g1h3 d7d5 d2d4 g8f6 e2e3 b8c6 f1b5 c8h3 g2h3 e7e6 c1d2 f8e7 c2c4 a7a6 b5c6 b7c6 c4c5 e8g8 e1g1 f8e8
info depth 14 seldepth 21 multipv 15 score cp -50 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv f2f3 e7e5 b1c3 d7d5 d2d4 b8c6 d4e5 d5d4 c3e4 d8d5 c2c3 d5e5 e2e3 d4c3 b2c3 g8f6
info depth 14 seldepth 22 multipv 16 score cp -53 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv b2b3 e7e5 e2e4 g8f6 b1c3 f8c5 g1f3 e8g8 c3a4 c5e7 a4c3 e7b4 d1e2 b4c3 d2c3 b8c6 c3c4 d7d6 c1d2
info depth 14 seldepth 18 multipv 17 score cp -64 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv b1a3 e7e5
info depth 14 seldepth 20 multipv 18 score cp -78 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv g2g3 e7e5 d2d4 e5d4 g1f3 d7d5 d1d4 b8c6 d4a4 g8f6 f3e5 f8d6 e5c6 b7c6 f1g2 e8g8 e1g1
info depth 13 seldepth 20 multipv 19 score cp -65 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv b2b4 e7e5 e2e3 d7d5 c2c4 g8f6 c1b2 f8b4 a2a3 b4d6 d2d4 b8c6 c4c5
info depth 13 seldepth 19 multipv 20 score cp -75 nodes 4108904 nps 1368266 hashfull 950 tbhits 0 time 3003 pv g2g4 d7d5 e2e3 e7e5 b1c3 g8f6 g4g5 f6e4 c3e4 d5e4 h2h4 b8c6 a2a3 a7a6
```

**Comment by mcostalba** [comment]
@joergoster thanks, it looks better now. I have closed my PR https://github.com/official-stockfish/Stockfish/pull/1168

**Pull request closed without merging**
