### PR TITLE
Simplify condition for ThreatByRook

### PR DESCRIPTION
**Pull request by goodkov**
Remove stronglyProtected Queen for ThreatByRook. SliderOnQueen and see_ge() do same as ThreatByRook for Queen.

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 21878 W: 4939 L: 4818 D: 12121 
http://tests.stockfishchess.org/tests/view/5b53a83b0ebc5902bdb815d1

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 35307 W: 5979 L: 5882 D: 23446 
http://tests.stockfishchess.org/tests/view/5b53b60b0ebc5902bdb8174c

Close https://github.com/official-stockfish/Stockfish/pull/1690

Bench: 4834554

### CODE REVIEW

**Comment by snicolet** [comment]
Approved.

Could you please improve the pull request message with the future bench number and other relevant infos? Thanks in advance :-)

**Comment by goodkov** [comment]
Is it  good enough?

**Comment by snicolet** [comment]
Merged via 0d5fe2f156666442b497656ae459f825c771826d, congrats :-) A successful return to the Stockfish project :-)

**Comment by snicolet** [comment]
By the way, for your future work, to keep your master branch up-to-date, my advice would be use the script given in the wiki at the top of the https://github.com/glinscott/fishtest/wiki/Creating-my-first-test page -- it is quite convenient, and is used by everybody else in the Stockfish developper team, I believe.

**Pull request closed without merging**
