### PR TITLE
Reduction Simplification

### PR DESCRIPTION
**Pull request by VoyagerOne**
Simplify reduction formula by removing a parameter.

STC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 35798 W: 6368 L: 6272 D: 23158

LTC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 125375 W: 15827 L: 15839 D: 93709

Bench:  4735038

### CODE REVIEW

**Comment by VoyagerOne** [comment]
Are reduction formula is now quite elegant.
r = log(d) * log(mc) / 2;

**Comment by MichaelB7** [comment]
Elegant yes, but this change will cost a few elo at longer time controls on big hardware.  I would passed. It takes the bench nodes way down and I would be suspicious of a change that is labeled as simplification yet impacts the search so much without thorough testing.

**Comment by syzygy1** [comment]
Isn't this a parameter tweak?

**Comment by VoyagerOne** [comment]
@syzygy1 
How so?  I am removing a parameter.

**Comment by syzygy1** [comment]
@VoyagerOne 
The parameters that I see here are the values of the Reductions[] array that are initialised in Search::init() (which is just invoked once at startup... you are not gaining any speed here as, for example, removing an evaluation feature (as opposed to a digit) from evaluate() would).

You are initialising the parameters differently, so why would this not be a parameter tweak?

**Comment by mcostalba** [comment]
Merged with b915fdc889e7e15

@syzygy1 between:

`x = sin(45.328*y -y^2)/tan(23 +y) + log(y^3-1/sqrt(y^2 + 5))`

and

`x = y/2`

Well, for me the second it is a simplification, even if x is computed off-line. Of course above example it is exagerrated but qualitative argument still stands: a simplification can be everywhere in the code, it simply means that code is easier after the patch than before.

**Pull request closed without merging**
