### PR TITLE
Replace/upgrade Passed Danger Array

### PR DESCRIPTION
**Pull request by protonspring**
This equation seems to do a better job than the current PassedDanger array.

Master values: 3, 7, 11, 20
Equation values: 3, 6, 11, 18

STC -3, 1
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 84301 W: 18155 L: 18156 D: 47990 
http://tests.stockfishchess.org/tests/view/5bda03180ebc595e0ae2518e

LTC -3, 1
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 7940 W: 1358 L: 1217 D: 5365
http://tests.stockfishchess.org/tests/view/5bdc69880ebc595e0ae27d28

LTC 0, 4 (stopped early)
LLR: 0.74 (-2.94,2.94) [0.00,4.00]
Total: 70257 W: 11319 L: 11064 D: 47874
http://tests.stockfishchess.org/tests/view/5bdca8420ebc595e0ae281a9

I like the equation better, but I certainly understand looking at the 4 values in the array may be better.

Either way, it is apparent that there is some ELO to be had here.

Option # 1: Commit this equation, then let others try to pass 0,4 with custom values if they think they can.

Option # 2: Stick the equation values in the array and try to pass 0,4. . also trying other values.

Option # 3: Tune the array.

Option # 4: Apply a 10 fold divisor and tune the array (values 30, 60, 110, 180) which would allow tuning results in between integers since this stuff seems pretty sensitive.

My opinion is also that this would all need to be done at LTC.  The STC test struggled mightily, but the LTC passed crazy fast.

How to proceed?

### CODE REVIEW

**Comment by snicolet** [comment]
I don't understand: 
• the version in the pull request is different from the version which passed the STC test
• you don't give the URL of the LTC tests

**Comment by protonspring** [comment]
I updated the original PR to include the links.  What difference are you seeing?

**Comment by protonspring** [comment]
Oh. . I think the difference is just because master was updated and merged between STC and LTC.

**Comment by snicolet** [comment]
Merged via 3cbb05b1b814ef9c79cc97de3598ba0c24735a97, thanks.

**Pull request closed without merging**
