### PR TITLE
Small cleanups 08

### PR DESCRIPTION
**Pull request by vondele**
start with an empty PR to collect small changes

No functional change

### CODE REVIEW

**Comment by mstembera** [comment]
Lines 194 and 195 in movegen.cpp
```C++
if (    (Pt == BISHOP || Pt == ROOK || Pt == QUEEN)
    && !(PseudoAttacks[Pt][from] & target & pos.check_squares(Pt)))
```
can be simplified to
```C++
if (!(PseudoAttacks[Pt][from] & target & pos.check_squares(Pt)))
```

**Comment by ElbertoOne** [comment]
In #PR2694 a penalty for doubled isolated pawns was introduced (lines 150-153 of pawns.cpp). The condition for giving this penalty included:
`&& popcount(opposed) == 1`, so requiring that the doubled pawns have exactly one opposing pawn.
This popcount check is unnecessary and can be replaced by:
`&& opposed`.
The reason for this is that the penalty that is imposed in case of 2 or more opposing pawns will be cancelled out by the penalty for the opposing side (so both sides have the penalty in this case, giving no change in overall evaluation).
So it is safe to replace the popcount condition with just a check for opposing pawns.
So in that case the code would look like:
```
            if (    opposed
                && (ourPawns & forward_file_bb(Them, s))
                && !(theirPawns & adjacent_files_bb(s)))
                score -= Doubled;
```
No functional change.

**Comment by xoto10** [comment]
> Lines 194 and 195 in movegen.cpp
> 
> ```c++
> if (    (Pt == BISHOP || Pt == ROOK || Pt == QUEEN)
>     && !(PseudoAttacks[Pt][from] & target & pos.check_squares(Pt)))
> ```

Don't the ` Pt ` tests influence the compilation via the template? Perhaps removing them could slow the code down?

**Comment by protonspring** [comment]
Not clear to me why, but this makes a smaller executable and is faster on my machines.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_passedspan4

**Comment by mstembera** [comment]
@xoto10 Line 195 will now also be compiled in for the KNIGHT case.  I haven't measured any speed difference.  Still we can run a simplification test or leave the code as is or simplify it to
```C++
if (Pt != KNIGHT && !(PseudoAttacks[Pt][from] & target & pos.check_squares(Pt)))
```
I'm fine w/ whatever the maintainers decide.

**Comment by MichaelB7** [comment]
> Not clear to me why, but this makes a smaller executable and is faster on my machines.
> 
> [master...protonspring:ps_passedspan4](https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_passedspan4)
```
3 long bench runs " bench 2048 1 28 benchmarks" total runtime 15 minutes
master was faster every time - is it noise? , is it because its longer runs? - who knows ...
 
master
=================================
Total time (ms) : 311742
Nodes searched  : 758254807

Nodes/second    : 2432315
----------------------------------------------------
Total time (ms) : 311349
Nodes searched  : 758254807

Nodes/second    : 2435385
----------------------------------------------------
Total time (ms) : 310892
Nodes searched  : 758254807

Nodes/second    : 2438965
=================================

BB patch
=================================
Total time (ms) : 312419
Nodes searched  : 758254807

Nodes/second    : 2427044
----------------------------------------------------
Total time (ms) : 312294
Nodes searched  : 758254807

Nodes/second    : 2428015
----------------------------------------------------
Total time (ms) : 312705
Nodes searched  : 758254807

Nodes/second    : 2424824

=================================
```
@protonspring  can you try a couple of longer runs  ? 2048 1 28 and see if your gain is maintained?

**Comment by protonspring** [comment]
On my machine, with 3 runs of bench 2048 1 28, the patch is still a little faster.

master: 
Performance counter stats for 'system wide' (2 runs):
1,660,430,888,568      cycles:u             ( +-  0.97% )
2,412,563,037,578      instructions:u       #    1.45  insn per cycle     ( +-  0.00% )
476.851450929 seconds time elapsed                                          ( +-  1.06% )

patch:
Performance counter stats for 'system wide' (2 runs):
1,626,324,938,742      cycles:u             ( +-  0.00% )
2,412,296,229,866      instructions:u       #    1.48  insn per cycle    ( +-  0.01% )
466.565410822 seconds time elapsed                                          ( +-  0.01% )

**Comment by protonspring** [comment]
Types, line 217 is a blank line that no other enumerations have.  Could remove it for consistency.

**Comment by protonspring** [comment]
Since our enums can be implicitly converted to an int, it seems like we can use the base operators instead of the extra Value-Int operators.  This makes exactly the same binary.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_baseoperators4

**Comment by protonspring** [comment]
position.h, line 252.  this assert can be simplified.
-  assert(pieceCount[make_piece(c, Pt)] == 1);
+  assert(count<Pt>(c) == 1);

**Comment by mstembera** [comment]
@protonspring  @MichaelB7 
Looking at the code https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_passedspan4 I would predict a slowdown over a speed up.  Measuring I get nothing above noise level and same size executable.
```
Results for 40 tests for each version:

            Base      Test      Diff      
    Mean    2139841   2131166   8675      
    StDev   91455     90844     110474    

p-value: 0.469
speedup: -0.004
```

**Comment by protonspring** [comment]
timeman.cpp, line 82,  this is a bit easier to read for me:
\- max_scale = 4 + std::min(36, ply) / 12.0;
\+ max_scale = std::min(7, 4 + ply / 12.0);

**Comment by xoto10** [comment]
> timeman.cpp, line 82, this is a bit easier to read for me:
> - max_scale = 4 + std::min(36, ply) / 12.0;
> + max_scale = std::min(7.0, 4.0 + ply / 12.0);

Pros and cons to me, one stresses 4+x, one that ceiling is 7.

**Comment by protonspring** [comment]
Curious about this one.  We barely use msb, and if we do 90% of the time there is one bit set, and almost never more than two (used for frontmost pawns).  Therefore, this simple software implementation of msb is just as fast as master.

https://github.com/protonspring/Stockfish/compare/616eb60008...2fe663a4d7

**Comment by protonspring** [comment]
A small simplification in magics.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_magics5

**Comment by mstembera** [comment]
Just my 2c on software msb()..  I think it's important to keep such low level functions fast because they are used as basic building blocks for all kinds of eval patches people try.  Ex we used to use msb() to calculate pawn span in which case the bits were not sparse.  It is also asymmetrical compared to lsb().  Why should a call to frontmost_sq(WHITE, ) execute completely different code than frontmost_sq(BLACK, ).

**Comment by protonspring** [comment]
position.cpp, line 542

\- if (type_of(piece_on(from)) == KING)
\+ if (pieces(KING) & from)

**Comment by protonspring** [comment]
This is a little faster on my machines:

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_movegen10

**Comment by protonspring** [comment]
To me, it looks like the std::bitset(count) is much faster than our software popcount.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_popcount2

**Comment by mstembera** [comment]
@protonspring When you say "looks like" and "much faster" can you please post some measurements that include a p-value?  As a side I think one of the reasons software popcount is in place is 32-bit compiles.  I don't mind if we don't care about 32-bit any more but in that case many more things should go as well.

**Comment by vondele** [comment]
I would like to emphasize we use this PR for cleanups not speedups. When the two coincide, I'm fine with it of course.

**Comment by mstembera** [comment]
https://github.com/official-stockfish/Stockfish/compare/master...mstembera:Cleanups

**Comment by protonspring** [comment]
We changed that * Score operator recently. As is, i think it is easier to read and is just as fast.

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L707
change pos.captured_piece() to PriorCapture for consistency - we use it like this for bools everywhere in the code and pos.captured_piece() only if we need value of it.

**Comment by pb00068** [comment]
The following comment in movepick.h has to be improved & adapted IMO:

/// LowPlyHistory at higher depths records successful quiet moves on plies 0 to 3
/// and quiet moves which are/were in the PV (ttPv)
/// It get cleared with each new search and get filled during iterative deepening

I'm not a native English speaker, so maybe some other may it do better, anyhow here my proposal:
/// LowPlyHistory gets filled during iterative deepening at higher depths by recording successful
/// quiet moves near the root  (plies 0 to 3).
/// This are best-moves or moves leading to a position which is/were in the PV (ttPv) .
/// For game playing with each new turn the content of plies 2 & 3 get moved to plies 0 & 1

**Comment by xoto10** [comment]
I would modify the current comment like this:

/// At higher depths LowPlyHistory records successful quiet moves near the root and quiet
/// moves which are/were in the PV (ttPv)
/// It is cleared with each new search and filled during iterative deepening

or the reworded one like this:

/// LowPlyHistory is filled during iterative deepening at higher depths by recording successful
/// quiet moves near the root.
/// These are best-moves or moves leading to positions which are/were in the PV (ttPv) .
/// During games the contents of higher plies are moved down by 2 with each new turn

**Comment by protonspring** [comment]
tbprobe.cpp, line 1365: "exsists" is mispelled.

**Comment by protonspring** [comment]
types.h, line 43, we include \<climits\>.  I can't seem to find where we are using this or why it needs to be included.

**Comment by protonspring** [comment]
The Piece increment operator is not really necessary.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_piece7

**Comment by protonspring** [comment]
Some clean-up and simplifications in bitbase.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_bitbase9

**Comment by silversolver1** [comment]
I'm not sure if what I'm about to say is entirely accurate or not but I just want to make sure.
At this point in probcut, do we also need a `&& ttValue != VALUE_NONE` condition? 

https://github.com/official-stockfish/Stockfish/blob/4b10578acbe099482ed40200478df4d775c01af5/src/search.cpp#L883-L885

as in https://github.com/silversolver1/Stockfish/commit/c106557f7fbafb1206373ab19e3384f81008f7a7

**Comment by Vizvezdenec** [comment]
@silversolver1 we don't need it since ttValue < raisedBeta more or less secures that ttValue isn't VALUE_NONE which is extremely high.

**Comment by silversolver1** [comment]
@Vizvezdenec Cool, sounds good, I see what you mean. thanks :)

**Comment by Rocky640** [comment]
Some extra spaces in pawns.cpp
```
            else
                score -=   Isolated
                         + WeakUnopposed * !opposed;
        }

        else if (backward)
            score -=   Backward
                     + WeakUnopposed * !opposed;

        if (!support)
            score -=   Doubled * doubled
                     + WeakLever * more_than_one(lever);
    }
```

```
could be changed to
            else
                score -=  Isolated
                        + WeakUnopposed * !opposed;
        }

        else if (backward)
            score -=  Backward
                    + WeakUnopposed * !opposed;

        if (!support)
            score -=  Doubled * doubled
                    + WeakLever * more_than_one(lever);
    }
```

**Comment by Rocky640** [comment]
In evaluate.cpp, the comment for evaluate_space is outdated since it refers to minor pieces.

Feel free to improve this text, as i am not a native english speaker.

I suggest to replace this
```
  // Evaluation::space() computes the space evaluation for a given side. It is
  // based on the number of safe squares on the central four files on ranks 2--4. Safe
  // squares one, two or three squares behind a friendly pawn are counted
  // twice. Finally, the space bonus is multiplied by a weight. The aim is to
  // improve play on game opening.

  template<Tracing T> template<Color Us>
  Score Evaluation<T>::space() const {

    if (pos.non_pawn_material() < SpaceThreshold)
        return SCORE_ZERO;
```


with something like this
```
  // Evaluation::space() computes a space evaluation for a given side, aiming to improve game
  // play in the opening. It is based on the number of safe squares on the 4 central files
  // on ranks 2 to 4. Completely safe squares behind a friendly pawn are counted twice.
  // Finally, the space bonus is multiplied by a weight which decrease according to occupancy.

  template<Tracing T> template<Color Us>
  Score Evaluation<T>::space() const {

    // Early exit if, for example, both queens or 6 minor pieces have been exchanged
    if (pos.non_pawn_material() < SpaceThreshold)
        return SCORE_ZERO;
```

**Comment by protonspring** [comment]
"decreases"

**Comment by unaiic** [comment]
In movegen.cpp we could simplify this

`if (Type == QUIETS || Type == EVASIONS || Type == NON_EVASIONS)
    {
        *moveList++ = make<PROMOTION>(to - D, to, ROOK);
        *moveList++ = make<PROMOTION>(to - D, to, BISHOP);
        *moveList++ = make<PROMOTION>(to - D, to, KNIGHT);
    }`

into 

`if (Type == QUIETS || Type == EVASIONS || Type == NON_EVASIONS)
    {
        *moveList++ = make<PROMOTION>(to - D, to, KNIGHT);
    }`

as rook and bishop promotions can be replaced with the ones with a queen, leaving the knight as the only underpromotion.

**Comment by mstembera** [comment]
I just wonder why we don't insert the KNIGHT promotion before the ROOK and BISHOP promotions since it's far more common/useful.

**Comment by vondele** [comment]
Thanks, merged in master, I'll open a new issue for follow-ups or forgotten items.

**Pull request closed without merging**
