### PR TITLE
[NNUE] Update default net to nn-9931db908a9b.nnue

### PR DESCRIPTION
**Pull request by sergiovieri**
Net created at: 20200806-1802

Bench: 4390086

passed STC:
https://tests.stockfishchess.org/tests/view/5f2d00b461e3b6af64881f21
LLR: 2.94 (-2.94,2.94) {-0.50,1.50}
Total: 6672 W: 1052 L: 898 D: 4722
Ptnml(0-2): 63, 600, 1868, 730, 75

passed LTC:
https://tests.stockfishchess.org/tests/view/5f2d052a61e3b6af64881f29
LLR: 2.96 (-2.94,2.94) {0.25,1.75}
Total: 7576 W: 573 L: 463 D: 6540
Ptnml(0-2): 8, 392, 2889, 480, 19

### CODE REVIEW

**Comment by sergiovieri** [comment]
> congrats

Thanks! How did you reply before I created the PR though 🤔

**Comment by vondele** [comment]
@sergiovieri thanks! please also update the AUTHORS file. 

Additionally, the commit message (or PR comment) should contain the test results including the link and the bench (actually relative to the up-to-date master (Bench: 4390086).

passed STC:
https://tests.stockfishchess.org/tests/view/5f2d00b461e3b6af64881f21
LLR: 2.94 (-2.94,2.94) {-0.50,1.50}
Total: 6672 W: 1052 L: 898 D: 4722
Ptnml(0-2): 63, 600, 1868, 730, 75 

passed LTC:
https://tests.stockfishchess.org/tests/view/5f2d052a61e3b6af64881f29
 LLR: 2.96 (-2.94,2.94) {0.25,1.75}
Total: 7576 W: 573 L: 463 D: 6540
Ptnml(0-2): 8, 392, 2889, 480, 19

**Comment by locutus2** [comment]
@sergiovieri 
Conrats! And thank you for the great training of nets for SF NNUE! Amazing work!

**Comment by FauziAkram** [comment]
Love it!!
But why the name of the network is 9931db908a9b, which sounds random to me, why can't we leave the name as 20200806-1802.bin this would make us determine what network it is in Sergio's page, while if not for reading in the pull request itself I could never realize that 9931db908a9b is 20200806-1802

**Comment by vondele** [comment]
@FauziAkram having the SHA part of the name  (the 9931db908a9b) has quite some advantages, as does a standard naming format, and a centralized location for uploads and downloads. We're working on extending the format of the file so we can add author name, data, and a short description in the file, so that some of this could be displayed by the engine.

**Comment by vondele** [comment]
merged, thanks!

**Pull request closed without merging**
