### PR TITLE
Refactor elapsed time checks in search

### PR DESCRIPTION
**Pull request by Disservin**
Small improvment of the elapsed time usage in search, makes the code easier to read overall. 
Also Search::Worker::iterative_deepening() now only checks the elapsed time once, instead of 3 times in a row.

Non Regression STC:
https://tests.stockfishchess.org/tests/view/6617005d5a4693796d965c3c
LLR: 2.97 (-2.94,2.94) <-1.75,0.25>
Total: 61024 W: 16002 L: 15806 D: 29216
Ptnml(0-2): 243, 6874, 16102, 7030, 263

### CODE REVIEW

**Comment by vondele** [comment]
looks good needs rebasing.

**Comment by Disservin** [comment]
I also realized that we are also always checking the nodes_searched, even if we don't play in nodestime. I changed this to be only called when actually required, this also seems like a small speedup.

```
./bench_parallel.sh ./stockfish-cleanup-search-elapsed ./stockfish-callbacks 13 100

sf_base =  1227807 +/-   2553 (95%)
sf_test =  1236564 +/-   2514 (95%)
diff    =     8757 +/-   2305 (95%)
speedup = 0.71324% +/- 0.188% (95%)
```

**Comment by peregrineshahin** [comment]
Well we need to check nodes_searched for go nodes x not just when playing nodes time.

> I also realized that we are also always checking the nodes_searched, even if we don't play in nodestime. I changed this to be only called when actually required, this also seems like a small speedup compared to the previous version here.
> 
> ```
> ./bench_parallel.sh ./stockfish-cleanup-search-elapsed ./stockfish-callbacks 13 100
> 
> sf_base =  1227807 +/-   2553 (95%)
> sf_test =  1236564 +/-   2514 (95%)
> diff    =     8757 +/-   2305 (95%)
> speedup = 0.71324% +/- 0.188% (95%)
> ```

**Comment by peregrineshahin** [comment]
I wonder if we should rename the check_time function to should_abort or refactor some logic from it

**Comment by Disservin** [comment]
> Well we need to check nodes_searched for go nodes x not just when playing nodes time.
> 
> >

no that is unrelated. https://github.com/official-stockfish/Stockfish/blob/master/src/timeman.cpp#L34
When we are using nodestime, elapsed needs to know about the total nodes searched. go nodes is unrelated

**Pull request closed without merging**
