### PR TITLE
Retire Material::space_weight()

### PR DESCRIPTION
**Pull request by mcostalba**
This is a nice simplification but could potentially introduce a speed regression so I run a test on it.

Speed bench is not enough IMO because space is computed only in the opening so bench is not representative enough of what really happens.

### CODE REVIEW

**Comment by mcostalba** [comment]
Regression passed:

LLR: 3.91 (-2.94,2.94) [-3.00,1.00]
Total: 65744 W: 13285 L: 13194 D: 39265

Please review for applying. Thanks.

**Comment by lucasart** [comment]
@mcostalba: You may be right about the representativity of bench (frequency of positions where space is actually computed vs. normal game play). But I did some bench measure anyway, and it's fine:

    stat        test     master    diff
    mean   2,459,136  2,468,547  -9,411
    stdev      9,245      5,733  10,624

    speedup      -0.38%
    P(speedup>0)  18.8%

Anyway, that's all the more reason to commit.

**Comment by zamar** [comment]
approved.

**Comment by glinscott** [comment]
Looks good!

**Pull request merged**
