### PR TITLE
[CI] Speedup the ci

### PR DESCRIPTION
**Pull request by Disservin**
Github Actions allows us to use up to 20 workers this way we can launch multiple different checks at the same time and optimize the overall time the CI takes a bit.
One could probably reduce the overall time a bit more by splitting up the tasks and combining slow ones with fast ones.
However for the sake of readability and maintainability, I would advise against this.

The logic of this PR is as follows:

Theres on main workflow which has 3 children.
Sanitizers, Tests and Compiles.

Tasks are sorted into the corresponding workflow, with Tests being the most expensive workflow overall.
The main `stockfish.yml` executes these, with the current configuration it will start 19 runners.

The Sanitizer section it has been simplified in a  more generic way, similar things can be done with other categories too.

Example run can be found here:
https://github.com/Disservin/Stockfish/actions/runs/3405881387

Example run of this pr and the other current open PR can be found here:
https://github.com/Disservin/Stockfish/actions/runs/3405766792

No functional change

### CODE REVIEW

**Comment by vondele** [comment]
The valgrind tests run very quickly, and it displays `unknown testing started` ... as if the option which test to run isn't passed in this scheme

**Comment by Disservin** [comment]
> The valgrind tests run very quickly, and it displays `unknown testing started` ... as if the option which test to run isn't passed in this scheme

Good catch, I forgot to pass the double hyphen

**Comment by vondele** [comment]
This will need a rebase after the recent changes in master. Let me know when it is ready.

**Comment by Disservin** [comment]
Okay, please have a look, I think mainly for superfluous variables.. I think ~13min for a PR check is a good time. Again one could abstract this even more but imo it would harm maintainability.

**Comment by vondele** [comment]
looks good to me, I'll squash on merge.

**Pull request closed without merging**
