### PR TITLE
Remove gain stats

### PR DESCRIPTION
**Pull request by locutus2**
Additionally in futility pruning the margin is raised for compensation.

STC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 48481 W: 9229 L: 9156 D: 30096

LTC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 32058 W: 5134 L: 5031 D: 21893

Bench: 8049739

### CODE REVIEW

**Comment by joergoster** [comment]
Nice simplification. Congrats!

**Comment by VoyagerOne** [comment]
Nice work SG.

**Comment by glinscott** [comment]
Nice, looks good!

**Comment by zamar** [comment]
approved.

**Pull request closed without merging**
