### PR TITLE
Remove restriction of Depth

### PR DESCRIPTION
**Pull request by goodkov**
The quadratic function increase rapidly. The restriction of Depth is useless.
Passed STC
http://tests.stockfishchess.org/tests/view/582b50310ebc5910626b9ea2
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 71511 W: 12691 L: 12655 D: 46165

and passed LTC
http://tests.stockfishchess.org/tests/view/582b79500ebc5910626b9eb6
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 33466 W: 4393 L: 4289 D: 24784

### CODE REVIEW

**Comment by locutus2** [comment]
Congrats too!

**Comment by AlexandreMasta** [comment]
Congrats too!

**Comment by mcostalba** [comment]
@goodkov this patch removes any limit on move pruning in particular we could prune at any depth. This is somewhat uncomfortable for me and even if it does not seems to regress in real games, coudl affect analysis or other usages.

Ths kind of patch is quite aggressive and can be merged only if introduces a real gain abve current (more ocnservative) approach.

Plsae retest woth SPRT[0, 4], for teh moment I am closing this one.

**Comment by goodkov** [comment]
Retest with 10+0.1 or 60+0.6?

**Comment by mcostalba** [comment]
Usually you start with 10+0.1

**Pull request closed without merging**
