### PR TITLE
A Makefile option for the build dir.

### PR DESCRIPTION
**Pull request by abdulbadii**
A Makefile option for the exclusive build directory separated from the source one or else, based on each compile/build CLI eg.
```

make build ARCH=x86-64-ssse3 COMP=clang DIR=clang_build
make profile-build ARCH=x86-64-sse41-popcnt DIR=gcc_PGObuild
etc
```
but modified/tested on Msys2/Mingw64, not confirmed yet on real (Arch) Linux

### CODE REVIEW

**Comment by snicolet** [comment]
The diff is strange in line 1061-1062, please check your tabs for indentation

**Comment by Disservin** [comment]
i haven't taken a look at this but what is the purpose ? You can already specify where the binary is gonna end up using `EXE=/home/user/mypath/stockfish`

**Comment by Disservin** [comment]
mh just needs some extra care in that case.. we can't really change something here which leads to multiple breaks in the "ecosystem" i.e. fishtest and other scripts

**Comment by MinetaS** [comment]
> mh just needs some extra care in that case.. we can't really change something here which leads to multiple breaks in the "ecosystem" i.e. fishtest and other scripts

Of course, no need to rush in hurry. If correctly implemented, there will be an extra option where the default behavior should leave things as is. However, for now the PR already broke CI which doesn't look good to me.

**Comment by snicolet** [comment]
One effect of this patch is to download the nets mulptiple times for multiple builds

**Comment by abdulbadii** [comment]
No effect of this patch concerning the nets download 
it sincerely tries to let it be improved

**Comment by Disservin** [comment]
Closing for now. If you want to continue this then please first try to fix the CI issues on your fork and reopen here for a discussion.

**Pull request closed without merging**
