### PR TITLE
Spend less time if we have found a TB win

### PR DESCRIPTION
**Pull request by SFisGOD**
There is no need to spend lots of time if we have found a TB win so we reduce the allowable total time to 20% of optimum time.

Bench: 3834252

### CODE REVIEW

**Comment by syzygy1** [comment]
Does this cover both the case that the root position is a TB win and the case that a TB win is found in the search? (Probably it does... I did not try to verify.)

How about doing the same or similar in case of a TB loss? (Of course only if the root position is a TB loss or if a full ply was searched so there is no move that can avoid the TB loss.)

Perhaps same if the root position is a TB draw?

**Comment by SFisGOD** [comment]
@syzygy1 This covers TB loss too. I noticed in TCEC that Stockfish usually spends all of its time avoiding the TB loss so this change doesn't really matter that much in that case.

**Comment by vondele** [comment]
CI is failing on this one. 

However, some comments for consideration:
This seem to trigger in the case of having a TB position in the root. These are not the cases relevant for TCEC, I think, since games are adjudicated at that point?

Doing the more general case, i.e. once search has found a TB win would cover these cases, one would wonder if finding a mate score would be useful as well. 

I think we prove winning mate scores (and probably TB wins), but  I'm not so sure about losses. 

If search finds a mate score or a TB win, and the position is not searched well enough, it will miss shortest wins, and in a few rare cases, will actually not be able to find it back in the next move. 

So, not so sure that this patch is a good idea. 

What does seem to happen at TCEC is that search takes something a very long time once a TB score has been found, as if the iteration takes forever to complete. This would need to be understood IMO. Maybe these things are related to https://github.com/official-stockfish/Stockfish/issues/3170 or https://github.com/official-stockfish/Stockfish/issues/2717

**Comment by SFisGOD** [comment]
@vondele Updated. I increased it to 20% for concerns about the rare cases of losing mate score or TB win.

**Comment by vondele** [comment]
one side effect will be that once we have found a TB win, it will become much more rare to see a mate score. Personally, I like to see a #81 or similar to appear in a tournament, it is always mind-boggling to see how an engine can find lines that deep.

**Comment by vondele** [comment]
I'll not merge this one, I think searching for a better mate etc is worthwhile.

**Pull request closed without merging**
