### PR TITLE
Fix syzygy warnings with Intel compiler

### PR DESCRIPTION
**Pull request by mcostalba**
Quick hack, a better job would require to
first move all syzygy code up to SF standard.

No functional change.

### CODE REVIEW

**Comment by zamar** [comment]
Thanks Marco.

Approved.

**Comment by zamar** [comment]
This is needed for SF6.

@glinscott: Can you please approve?

**Comment by glinscott** [comment]
Thanks Marco.  Verified that bench is unchanged with 5 man syzygy.

**Comment by glinscott** [comment]
Oh, yes, approved of course :).

**Comment by zamar** [comment]
@glinscott, @mcostalba: Please merge, I'm not able to do it myself just right now...

**Pull request merged**
