### PR TITLE
Use ByPieceBB instead of ByTypeBB

### PR DESCRIPTION
**Pull request by snicolet**
Only one occurrence of ByTypeBB left in position.cpp

This is work in progress, about 0.6% faster than master.

### CODE REVIEW

**Comment by snicolet** [comment]
@mcostalba:

The only occurrence of "ByTypeBB" left in position.cpp (before we can get rid of the ByTypeBB array in the Position class) in the pointer used as the first parameter of min_attacker() in line 1038 of position.cpp

I have tried to use a color dependent pointer, see lines 1028-1029 and line 1040 of the pull request, but didn't manage to make it work.

In fact line 1028 + line 1040 works, but line 1029 + line 1040 doesn't, and I don't understand why...

**Comment by Rocky640** [comment]
Maybe this would work for your line 1029 ? (I did not try it)
const Bitboard* bb[COLOR_NB] = { &byPieceBB , &(byPieceBB + 8) };

**Comment by syzygy1** [comment]
That this could be faster without redoing large parts of movegen.cpp and eval.cpp (and without yet removing byTypeBB??) surprises me.

**Comment by syzygy1** [comment]
A straightforward replacement of byTypeBB with byPieceBB slows down by about 2% in my C port. This is what I would expect.

Now the question is if it can be made competitive by going through all uses of pieces() and replacing pieces(pt) with pieces(pc) / pieces(c, pt) where that makes sense. I suspect not.

**Comment by snicolet** [comment]
@sizygy1

In evaluate.cpp, all the uses of pieces(Us, pt) are converted at compile time into a single index for byPieceBB because Us is a template parameter so the compiler knows its value.

In movegen.cpp:

• the old code for pieces(stm, pt) was something like
    multiply stm by two, load from memory from byColorBB,
    multiply pt by by two, load from memory from byTypeBB,
    return the AND of the two memory access

• the new code for pieces(stm,pt) is something like
  multiply stm by eight, add pt, multiply by two, load from memory from byPieceBB

Why did you expect the new code to be slower ?

**Comment by syzygy1** [comment]
@snicolet 
What I meant is that the code now sometimes uses e.g. pieces(KNIGHT) where it could instead use pieces(WHITE, KNIGHT), for example if you AND anyway with a subset of the white pieces.

However, there might be fewer instances of this in evaluate.c than I thought.
One example in my code is in evaluate_threats(), but interestingly this is an optimisation that I found and that no longer makes sense with byPieceBB.

Stockfish does this:
pos.pieces(Them) ^ pos.pieces(Them, QUEEN, KING)
to calculate a bitboard of pieces of side Them without queens and kings. What I did was:
pieces(Them) & ~pieces(QUEEN, KING)
which does the same but in fewer operations (with byTypeBB). (I don't know if the compiler can do this by itself.)

However, with byPieceBB the Stockfish approach is better.

Anyway, this should clarify my point. Some expressions that were more efficient with byTypeBB can be replaced with expressions that are more efficient with byPieceBB.

**Comment by syzygy1** [comment]
One reason why I expect byTypeBB to be faster than byPieceBB is that I once converted my own bitboard program and perft calculator from byPieceBB to byTypeBB and it was faster.

Basically the only disadvantage of byTypeBB is that sometimes you have to do an AND with the white or the black pieces. But usually you have to do that AND only once. For example in See() you create stmAttackers once and AND it with each byTypeBB bitboard. So the overhead created by this disadvantage is small and sometimes zero.

The advantage of byTypeBB is that you often need e.g. all queens and rooks and then pieces(ROOK, QUEEN) is just two memory loads plus one OR whereas with byPieceBB it is four loads plus three ORs.

WIth byTypeBB it is also easier to make color-independent code (e.g. a move generation function that works both for white and for black). This advantage may be smaller for Stockfish because of template use.

**Comment by snicolet** [comment]
Commit 2 removes the last appearances of byTypeBB and is about 0.9% faster than master (non-pgo compiles, two long benches at depth 22 running in parallel):

Total time (ms) : 162073
Nodes searched  : 219576748
Nodes/second    : 1354801
testedpatch

Total time (ms) : 163593
Nodes searched  : 219576748
Nodes/second    : 1342213
master

**Comment by snicolet** [comment]
@Rocky640 

Thanks for the suggestion, in fact my bug was not in the extraction of the pointer but in the logic of the SEE algorithm if we use byPieceBB. 

Consider for example the position: White bishop b2 + pawn d4, Black queen a1 + bishop c3 + pawn e5.

When we calculate the SEE value of d4xe5, the sequence runs d4xe5 c3xe5 b2xe5 a1xe5: each of the first three captures introduce a new attacker to the target, which is of the opposite color of the capturing piece. So basically we need the pieces for both colors in min_attacker, in lines 69 and 72 of min_attacker() in position.cpp

**Comment by snicolet** [comment]
@syzygy1 

I now see what you mean, thanks for the exemples. And indeed if we wanted to push the template idea to the extreme, we could try in Stockfish to templetarize completely the move generator as we have done for the eval, and see if it brings a new speed-up (templatarize endgame.cpp seems harder because of the run-time selection of weakside/strongside in most of the endgame functions).

**Comment by mcostalba** [comment]
I suggest to drop all these functions:

```
  Bitboard pieces(PieceType pt) const;
  Bitboard pieces(PieceType pt1, PieceType pt2) const;
  Bitboard pieces(Color c, PieceType pt) const;
  Bitboard pieces(Color c, PieceType pt1, PieceType pt2) const;
```

And instead define only the **native** ones:

```
 Bitboard pieces(Piece pc) const;
 Bitboard pieces(Piece pc1, Piece pc2) const;
```

For instance instead of 

`Bitboard pawns = pos.pieces(strongSide, PAWN);`

Use

`Bitboard pawns = pos.pieces(make_piece(strongSide, PAWN));`

This will allow you to better understand the impact of your patch. These low level inliners should reflect the underlying data layout, should not add additional remapping. Their meaning is just to wrap the corresponding array and they should remain as this to really understand if the patch is worth it or not.

**Comment by syzygy1** [comment]
@snicolet 
I don't think templates are being underused in the move generator at the moment ;-)
But I did find a case in evaluate.cpp that probably can be optimised a little for byPieceBB. See lines 635, 637 and 640. No need to first calculate pieces(ROOK, QUEEN) for both sides only to split them up again in the two if statements.

**Comment by mcostalba** [comment]
@syzygy1 yes, I saw your CFish porting of move generator, you moved the template parameter into the function arguments: I hardly understand how you could have a faster perft in this way that is a clear slow down for me (it was when I implemented the move generator, I tested the template parameters one by one :-)

**Comment by mcostalba** [comment]
@snicolet I have pushed a patch above your current branch to just use native wrappers

https://github.com/mcostalba/Stockfish/commit/pieces_no_type

The common case of query PieceType by compile time type has been templetized so that the corresponding Piece is computed at compile time thanks to make_piece() to be defined constexpr.

I think this is faster, although no speed measurement.

**Comment by snicolet** [comment]
@mcostalba : thanks, I will have a look either tonight or on monday.

**Comment by mcostalba** [comment]
@snicolet I see this is inactive since some time now, if you don't mind I'd like to close it.

**Comment by snicolet** [comment]
OK.

Anyway the idea should be rebased on new master because of the conflicts. I might propose a new version with even less invasive changes and see if the 0.93% speed-up is still there :-)

**Pull request closed without merging**
