### PR TITLE
Clear TB mappings in Search::clear()

### PR DESCRIPTION
**Pull request by noobpwnftw**
This patch will make possible to free mapped TB files with "ucinewgame" command.

Also saving one LOC since Search::clear() is also called during initialization.

No functional change.

### CODE REVIEW

**Comment by Vizvezdenec** [comment]
I guess this is related to this one https://github.com/official-stockfish/Stockfish/issues/1789

**Comment by noobpwnftw** [comment]
@mcostalba The problem is once a TBTable maps its TBFile, the TB file stays memory-mapped and consumes RAM. If one would analyze a few different games without triggering TB initialization by hand or restarting the engine, it will then keep the mappings of all TB files ever hit by search.
Since we can't cleverly decide when to free which unneeded TB file mappings, and it is largely common sense that "ucinewgame" resets the engine to a clean state, I think there is no harm to clear TB mappings there and better than telling user to restart the engine or use setoption SyzygyPath as a hack.

**Comment by mcostalba** [comment]
For a not accessed memory mapped file the OS will discard the allocated RAM as soon as it needs more.

Anyhow, in case you have some quantitative test to prove an improvement with your patch compared to the current master, of course it would be very useful for the discussion.

**Comment by NickolasReynolds** [comment]
@mcostalba If I'm not mistaken, noobpwnftw wrote this patch specifically to address a problem that arose while running Stockfish with 7-piece tablebases as a kibitzer at TCEC for extended periods of time across multiple games. It was noted that after some time, the NPS of the kibitzing Stockfish (which is usually 3x faster than the Stockfish actually competing) would drop precipitously, eventually falling to preposterously low numbers until restarted.

I doubt this problem is within the scope of Fishtest or any other normal testing procedure, as almost no one can replicate noobpwnftw's hardware. Insofar as we believe noobpwnftw to be a faithful actor and competent in this realm -- and assuming the patch has been independently reviewed and determined to be neutral/meaningless in other contexts (we could run a [-3,1] test on Fishtest if you like) -- I think it makes sense to accept the the problem as real and the proposed solution as reasonable.

**Comment by noobpwnftw** [comment]
@NickolasReynolds It is not precisely known for what exactly caused the slowdowns, but the trick of re-initializing TB between multiple games seems did the trick at least for a few days so far. The problem is do we want to make such behavior into "ucinewgame" command or use other ways like re-issuing SyzygyPath or simply restarting the engine.

**Comment by snicolet** [comment]
@noobpwnftw can you confirm the slowdown of the analysis bot for TCEC? This could be important for the upcoming World Championship match between Carlsen and Caruana, as TCEC has the intention to use Stockfish as an online analysis tool.

**Comment by noobpwnftw** [comment]
@snicolet Their eval bot basically inputs FEN, go infinite, stop and loop, it probably didn't do ucinewgame either. As time goes it gradually slowed down and OS starts to use swap, this is not reasonable since the engine only uses 16GB hash and the machine has 1TB physical RAM and does nothing else.
I told them to restart the engine, it didn't help, so it was not some memory leak. Rebooting the machine would work, but then a few days later the problem came back.
Next thing I did when the slowdown happened was to turn OS swap off and then on, drop all caches, without rebooting the machine, it solved the slowdown. In attempt to prevent it happening again, I told them to re-issue SyzygyPath when every new game occurred, and so far it worked fine.

I have no clue how disk-backed file mappings could ever go to swap, and apparently it must be some OS  mechanism since restarting the engine process alone won't solve the problem. But I know if we only keep those file mappings for as long as needed, it'd work fine.

**Comment by mrpond** [comment]
@noobpwnftw how can I contact you privately?

**Comment by snicolet** [comment]
@mcostalba I see no problem in the PR, do you think we can merge it?

**Comment by snicolet** [comment]
Merged via b9f1c9bf3f5ba240423a4f1ca8a2fb0f975a775e, thanks!

**Pull request closed without merging**
