### PR TITLE
Simplify TT replace formula

### PR DESCRIPTION
**Pull request by mcostalba**
And fix the replace description.

No functional change.

### CODE REVIEW

**Comment by mstembera** [comment]
This is a functional change.  The reason bench doesn't change is because there are only 37 positions which is less than the 64 required to roll over the generation counter.  If for example you put 
```for (int j = 0; j < 2; ++j)```
on line 148 in benchmark.cpp so that we run through the positions twice you will get a master bench of 16511015 but this patch will give you 16743613.

Also the comment saying 8 times is correct because the age is already premultiplied by 4 because it's stored only in the upper 6 bits.   Note new_search() increments by 4 not by 1 to account for this.

**Comment by mcostalba** [comment]
I am not able to see why is different

Anyhow I can run a sprt (-3,1) if needed because this version is definitely
much more understandable than the other and a small functional change after
64 moves seems to me really harmless.

**Comment by mstembera** [comment]
After move 64 the age will be computed backwards which will make us likely to select exactly the opposite entry to replace than what we want.  I don't know if [-3,1] would pass because maybe most games are already decided by move 64.  If you can't see the difference look up modulo arithmetic.

**Comment by lucasart** [comment]
@mcostalba: running this as a simplification `(-3,1)` makes sense. I would suggest to use a reasonable hash pressure, like 8MB at STC, not 128MB...

**Comment by zamar** [comment]
Please no.

Generation is cyclic and the current code is carefully written to take this into account...

Most games are decided before 64 moves, so the ELO change probably isn't measurable. But what's the point of replacing perfectly working solution with imperfect one?

**Comment by mstembera** [comment]
@lucasart
I would prefer not to let a bug in because of simplification.  After move 64 the new code is completely broken.  I don't mean some small rounding error but older entries will actually be considered newer and vice versa.

**Comment by mcostalba** [comment]
I think current code is wrong anyhow.

This is current formula:

      bool c2 = (  replace->depth8 - ((259 + generation8 - replace->genBound8) & 0xFC) * 2 * ONE_PLY
                 >   tte[i].depth8 - ((259 + generation8 -   tte[i].genBound8) & 0xFC) * 2 * ONE_PLY);

It can be rewritten in a 100% equivalent form as:

      bool c3 = (  replace->depth8 - ((0x100 + generation8 - (replace->genBound8 & 0xFC)) & 0xFF) * 2 * ONE_PLY
                 >   tte[i].depth8 - ((0x100 + generation8 -   (tte[i].genBound8 & 0xFC)) & 0xFF) * 2 * ONE_PLY);

Here we can see that when generation8 overflows and becomes 0, then if (replace->genBound8 & 0xFC) == 240 and (tte[i]->genBound8 & 0xFC) = 252 then, assuming depths are the same, then condition is false and tte[i] is considered more valuable than replace (as it should be), but when we increase generation8 and we start to fill TT with new values we can have say  generation8 == 8, (replace->genBound8 & 0xFC) == 240 and a newly created tte with (tte[i]->genBound8 & 0xFC) = 4. In this case we have (assuming depth8 == 0 for both entries): 0 - (0x100 + 8 - 240) & 0XFF > 0 - (0x100 + 8 - 4) so that tte is considered less valuable than replace while instead is newer.

So the bottom line is that the formula is wrong, and works only as long as both tte and replace are from the same 'epoc', ie.e from the same subset of 64 generations. As soon as generation8 overflows nad starts again we will have tte from new 'epoc' and replace from old 'epoc' then formula yields wrong condition adn will assume replace is newer than tte while it is not.

It took me some time to figure out this behavior and because I am the only one to have figured out this, I think the correct formula is so ugly and convoluted that is even very complicated to realize it is wrong: so I suggest to replace it because it is wrong anyhow and it is very difficult to spot it.

**Comment by zamar** [comment]
I'm trying to follow you...

Normal example:
==============

generation = 252
tte.genbound8 = 228
replace.genbound8 = 248
tte.depth8 = 0 (doesn't really matter)

tte.depth8 - ((259 + generation8 - tte.genBound8) & 0xFC) * 2 * ONE_PLY =  0 - ((259 + 252 - 228) & 0xFC) = -24
replace.depth8 - ((259 + generation8 - replace.genBound8) & 0xFC) * 2 * ONE_PLY = 0 - ((259 + 252 - 248) & 0xFC) = -4

tte.score = -24 < replace.score = -4

"tte" is much older than "replace", so the result is expected.

Your counter-example:
==================

generation = 8
tte.genbound8 = 240
replace.genbound8 = 4
tte.depth8 = 0 (doesn't really matter)

tte.depth8 - ((259 + generation8 - tte.genBound8) & 0xFC) * 2 * ONE_PLY =  0 - ((259 + 8 - 240) & 0xFC) = -24
replace.depth8 - ((259 + generation8 - replace.genBound8) & 0xFC) * 2 * ONE_PLY = 0 - ((259 + 8 - 4) & 0xFC) = -4

tte.score = -24 < replace.score = -4

"tte" is much older than "replace", so the result is expected.

---
For me the calculations look exactly the same even though we "overflowed"...
---

Checking with your notation, the following calculations seem to work just fine for generation8 (I'm using depth8 = 0 for simplicity):

0 - (0x100 + 8 - 8) & 0xFF = 0
0 - (0x100 + 8 - 4) & 0xFF = -4
0 - (0x100 + 8 - 0) & 0xFF = -8
0 - (0x100 + 8 - 252) & 0xFF = -12
0 - (0x100 + 8 - 248) & 0xFF = -16
0 - (0x100 + 8 - 244)  & 0xFF= -20

**Comment by zamar** [comment]
However I do agree that the current code is cryptic, two many things are done in one place: 
* Calculating two scores
* Handling overflow
* Bit extraction tricks
* Comparing scores
* Choosing which entry to overwrite

So, I'd prefer to have a patch which would be fully functionally identical to the current one, but maybe contain some more code lines and comments...

**Comment by mcostalba** [comment]
I was able to rewrite using a conditional addition instead of & 0XFC trick, this allow to make it more understandable.

Tested that the 2 version are 100% equivalent.

Pull updated.

**Comment by zamar** [comment]
Hi Marco,

I think that your version is identical to the current one (I'm still not 100% sure though, I'd need to spend some more time...)

Which one is simpler I can't really tell though. Someone who hasn't followed this discussion would find both very cryptic... But in the end either of them is fine with me.

BTW, your comment update really isn't right. It's really: depth - 8 * age as the original comment states...
True logic is: depth - ((genbound8 & 0xFC) >> 2) * 8. But we are just optimizing it to depth - genBound8 & 0xFC * 2. Your code is adding age counter (not age). So you could write: "depth + 8 * generation".

**Comment by mstembera** [comment]
Due to the current storage format and overflow issues it is difficult to write a correct version that doesn't appear cryptic.  The original version is cryptic.  I think the new version is at least as cryptic and in addition performs more unnecessary operations.

Also, thank you Joona for going through the examples.

**Comment by mcostalba** [comment]
One more iteration with added comments and some code reshuffle.

**Comment by mstembera** [comment]
It feels like we are replicating what the math was efficiently doing with extra code.
I see nothing wrong with adding comments.

**Comment by zamar** [comment]
I've considered the alternatives and I have to say that I consider the current version simpler than any of the proposed ones.

Once you understand the following (ugly piece of math) calculates the age of the entry, everything becomes straightforward:
(259 + generation8 - replace->genBound8) & 0xFC)

However this is something that we should document a bit better.

@mstembera: As this code was written by you, do you want to create a documentation update patch for this one?

**Comment by mstembera** [comment]
Ok done.
https://github.com/official-stockfish/Stockfish/pull/401
Please let me know if you think of a better way to write it.

**Comment by mcostalba** [comment]
The comment on the hack should be in line just above the hack, not at
function description level, moreover you should explicitly refer that
259=256+3 otherwise your comment just says "warning, this is a hack"  not
how hack works.

**Pull request closed without merging**
