### PR TITLE
Add "how to contribute" section to Readme to help contributors unders…

### PR DESCRIPTION
**Pull request by dsjoerg**
…tand in advance what is required of them.  Just a start based on @mcostalba's recent comment in a PR, clearly this section can expand over time to help even more.

### CODE REVIEW

**Comment by ddugovic** [comment]
I am curious whether maintainers would prefer that contribution guidelines be documented in a separate file (in order to avoid overwhelming the readme file).

**Comment by mcostalba** [comment]
I think current description is too short and incmplete, I'd prefer a link to testing guidelines:

https://github.com/glinscott/fishtest/wiki/Creating-my-first-test

**Comment by zamar** [comment]
Agreed. A link to the testing guidelines would serve much better.

Please either modify the patch or close the pull.

**Comment by dsjoerg** [comment]
OK @zamar, now there is a link to testing guidelines as per @mcostalba's suggestion and also to fishcooking google group.

**Comment by zamar** [comment]
I think that this sort information is much better placed in wiki.

At maximum the readme should then have a single link to wiki page.

**Pull request closed without merging**
