### PR TITLE
Thread voting

### PR DESCRIPTION
**Pull request by mstembera**
Threads vote on the best move to play.

STC 7 threads 10+0.1
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 77576 W: 12614 L: 12192 D: 52770
http://tests.stockfishchess.org/tests/view/56406efd0ebc59227df1717d

LTC 7 threads 20+0.2
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 24992 W: 3720 L: 3511 D: 17761
http://tests.stockfishchess.org/tests/view/564a62ec0ebc5902cdc08218

### CODE REVIEW

**Comment by ajithcj** [comment]
Congrats! Nice idea.

**Comment by mcostalba** [comment]
Current deepest move is clearly not the optimum, and this code perhaps
fills that hole, but it is definitely too complex and obscure, I read
several times and still don't understand what's happening here.

I really hope a much simpler solution (like the one tested by Lucas) do
exist.

**Comment by mcostalba** [comment]
There is still some testing to be done along a line that surely makes more
sense:

https://github.com/lucasart/Stockfish/commit/372314c991040f749124794b0de74999202947b6

**Comment by zamar** [comment]
I agree with @mcostalba.
This patch is way too complex. We would need a very significant gain (> 5 ELO) to justify this complexity. Current results do not indicate this

**Comment by ajithcj** [comment]
@mstembera 
>> I actually first wrote the below which selects the thread that cast the strongest vote but decided to go with the simplest version.

Your original idea seems more logical and simpler. It might even give more ELO. I hope you will test it.

**Comment by zamar** [comment]
Closing as non-committable

**Comment by mstembera** [comment]
@ajithcj 
The change you are referring to has zero impact on elo because it does not change the move played.  Only pv[1] and later may be different.

**Comment by ajithcj** [comment]
@mstembera I thought the original idea is to select bestThread using completed depth, th->idx and th->maxPly.
For example if two threads have the same completedDepth select the one with lower idx and higher maxPly. Wouldn't selecting a different thread also result in a different move? Anyway I hope some version of this patch gets committed. Good luck!

**Comment by ajithcj** [comment]
@mstembera you are most probably right... two threads with the same completedDepth will always select the same move.

**Comment by mstembera** [comment]
@ajithcj 
Just FYI, that's not how it works.  The threads vote on a move(not equally but based on their depth, etc.) and whichever move receives the most votes is the move played.  However, any one of the threads that voted for the elected move will play it. Whichever one of those threads you choose doesn't change the move.

**Pull request closed without merging**
