### PR TITLE
Improve build system

### PR DESCRIPTION
**Pull request by MinetaS**
\<commit description not ready yet\>

No functional change

### CODE REVIEW

**Comment by MinetaS** [comment]
### Checklist

- [ ] Add ARM/AArch64 support with Neon (Advanced SIMD)
- [ ] Add support for other existing architectures (ppc/riscv64/loongarch64/e2k)
- [ ] Add/verify appropriate compiler/linker flags for edge-case uses
- [ ] Add arch-specific paths in non-NNUE code (i.e. Bitboard)
- [ ] Check MSVC compilation
- [ ] fishtest integration
- [ ] GitHub CI integration

**Comment by MinetaS** [comment]
# Full Changelog

This section will be the final commit description. *WIP*

## Makefile

### General

* Removed `COMP`/`COMPCXX` command options and comply with common use cases.
  * Users now set `CXX` and `CXXFLAGS` variables.
  * Compiler is automatically detected by checking predefined macros.
* Removed get_native_properties.sh.
  * `-march=native` is added when `ARCH` is not set.
  * `ARCH_NATIVE` macro is defined for native builds. It conditionally disables some ISA features based on hardware.
* Moved NNUE download script to net.sh.
  * wget is used preferentially as curl is known to have a little overhead occasionally.
* Directories under src/arch/ have its own sub-Makefile.
  * It shows different help text as per `ARCH` variable, which usually contains a list of available build presets.
  * It adds machine-dependent compiler flags. (i.e. `-mavx2`, `-march=armv8-a`)
  * Some architecture families have additional options.
* Minimized command executions.
  * Build speed on Windows MinGW is significantly enhanced.
  * Most of variables are set or appended only at root Make (`MAKELEVEL=0`).
* Unsupported arch presets are no longer allowed. (i.e. x86-32-vnni512)
* Path of `llvm-profdata` is automatically detected based on Clang version when doing profile-build with Clang.
* The lists of source and header files are now set using find command instead of being fixed lists.
* Added `LIBS` variable. It appends `-l` flags at the end of the command.
* Renamed `WINE_PATH` to `EMULATE` as it's not limited to wine. ~~(it's not even used now?)~~

### Make Rules

* strip: Instead of stripping `EXE`, both stockfish and stockfish.exe will be stripped if exist.
* install: Removed - prefix. It should be aborted when mkdir or cp has failed.
* clean: Removed *~ and core as these are not related to the build output.
* objclean: Added *o.tmp.
* profileclean: Removed unnecessary entries.
* format: Now it informs user when clang-format is not installed.
* help: The whole text is exported to an environment variable. It has help-arch as a dependency if `ARCH` is properly set.
* config-sanity: It has config-arch as a dependency if `ARCH` is properly set.
* .depend: Shows message when dependency is updated and Make is restarting.

### i386/AMD64

* Added x86-64-avx512-vnni.
  * Synonym to x86-64-vnni512 and x86-64-vnni256.
  * x86-64-vnni256 is equivalent to "ARCH=x86-64-avx512-vnni NO_AVX512=1".
* Added x86-64-bmi.
  * Few AMD processors support BMI1 only.
* Added x86-64-avx.
  * Targeted Intel Sandy Bridge and Ivy Bridge processors.
* Renamed x86-64-sse41-popcnt to x86-64-popcnt.
  * `-msse4.2` flag is added.
* Removed x86-64-modern.
* Added x86-64-sse41.
  * It's not commonly used and only effective for VIA Nano processors.
* Renamed x86-64-sse3-popcnt to x86-64-abm.
  * Targeted old AMD processors, AMD Family from 10h to 15h.
  * `-msse4a` flag is added.
* Removed x86-32-sse41.
* Removed x86-32-sse2. With modern compilers, x86-32 serves as x86-32-sse2.
* Introduced `NO_AVX512` option - 512-bit SIMD operations will be not used if this variable is set.

### ARM/AArch64

* Removed old Android configurations.

*WIP, but only few things will be changed, mostly compiler flag related*

## Source code

* Architecture-dependent code is separated and moved into the corresponding directories under src/arch/. 
  * Each architecture family shall implement `ArchImpl` struct. Itcomprises common variables and functionalities: `Is64Bit`, `UsePEXT`, `prefetch()`, `popcount()` and `pext()`.
  * Moved non-type-related definitions and macros into common.h file.
  * `Is64Bit` is defined by appropriate combination of conditions instead of `IS_64BIT` macro.
* Replaced `USE_XXX` macros with predefined compiler macros.
* `AffineTransformSparseInput` class is identical to `AffineTransform` instead of being a separate class, when it's not possible to optimize.
* Improved output of `compiler_info()` function.
* Removed unused `Bitboard::pretty` function.
* Removed unused or one-time-use variables.
* Renamed a few variables.

**Comment by Disservin** [comment]
Since this is getting quite large now, can we try to have certain cleanups be their own pr? Like some of makefile changes which are unrelated to the network architecture restructure please?

**Comment by Disservin** [comment]
We discussed the usage of “find” in the past and I think it wasn’t very portable.. I think on windows find already exists and the makefile for me took that find over the posix find because of how the environment variables were set by default

**Comment by MinetaS** [comment]
> Since this is getting quite large now, can we try to have certain cleanups be their own pr? Like some of makefile changes which are unrelated to the network architecture restructure please?

Yes I 100% agree, I'm now trying to reduce any excessive changes that are not directly related to the primary purpose.

But I don't understand what you meant by "some of makefile changes", can you elaborate? This essentially requires complete rewrite of Makefile at least - and I can't find which are unrelated yet.

**Comment by MinetaS** [comment]
Maybe moving out net.sh can be a separate PR? If that's the case I'll prepare one.

**Comment by Disservin** [comment]
> But I don't understand what you meant by "some of makefile changes", can you elaborate?

The usage of `find` would be one thing, though id like to avoid having that altogether.
Then there are a few make rule changes which I don't think are strictly tied to this pr in general, like
> profileclean: Removed unnecessary entries.

what are unnecessary entries?

> format: Now it informs user when clang-format is not installed.

> help: The whole text is exported to an environment variable. It has help-arch as a dependency if ARCH is properly set.

what is the reason behind this?

> .depend: Shows message when dependency is updated and Make is restarting.

could be standalone as well no?

**Comment by MinetaS** [comment]
> The usage of `find` would be one thing, though id like to avoid having that altogether.

`find` substitutes for the previous way of listing source/header files. I thought it was clean and simple rather than manually tracking every single file with long path such as arch/XXX/nnue/YYY.h. Also msys `find` has higher priority in msys shell on Windows. I don't know if we keep supports for other Unix compatible layers and terminals (i.e. Cygwin, Windows Terminal), but if so I'll revert them back.

> what are unnecessary entries?

gcc saves profiling data in profdir so *.gcda and *.gcno are unnecessary. bench.txt is not created anywhere. For *args* and *lt* files, I haven't observed such files are created (maybe I missed), I'll check them again.

> what is the reason behind this?

format uses clang-format but it is often not included in clang package. I think it could help users to know which to install exactly, but no big reason.

Speaking of help, current Makefile calls echo per line, which is very slow on Windows due to the overhead of CreateProcess (no fork). printf also works, there is no difference.

> could be standalone as well no?

When running a rule of CXX_REQUIRED_RULES, it prints which type of compiler is used at the very beginning. When dependency is updated Make restarts itself and prints the same info twice. It is also UX stuff to help users understand why sometimes duplicate message is shown, especially after doing `make clean`.


Nothing is final, I always appreciate any type of feedbacks.

**Comment by vondele** [comment]
> > The usage of `find` would be one thing, though id like to avoid having that altogether.
> 
> `find` substitutes for the previous way of listing source/header files. I thought it was clean and simple rather than manually tracking every single file with long path such as arch/XXX/nnue/YYY.h. Also msys `find` has higher priority in msys shell on Windows. I don't know if we keep supports for other Unix compatible layers and terminals (i.e. Cygwin, Windows Terminal), but if so I'll revert them back.

for devs having some unrelated files in the tree (test.cpp comes to mind), the usage of find might be problematic. I think it is good to list explicitly.

Generally, I agree with Disservin here, splitting things out that could be merged before makes sense to keep the diff between this branch and master small, which will eventually be helpful I think, for you to maintain it until it is ready, and for later review.

**Comment by Disservin** [comment]
> for devs having some unrelated files in the tree (test.cpp comes to mind), the usage of find might be problematic. I think it is good to list explicitly.

for reference we discussed that here, https://github.com/official-stockfish/Stockfish/pull/4790#:~:text=View%20reviewed%20changes-,src/Makefile,-Outdated, needs to be expanded though.

In my dev env on windows I have the msys stuff in my env and use the normal windows shell where the windows find has a higher presence, and I'm not sure fishtest requires msys as the shell.

**Comment by Disservin** [comment]
The echo change would be good to have I think, people commonly have complained about how slow make is on windows.

**Comment by MinetaS** [comment]
> Generally, I agree with Disservin here, splitting things out that could be merged before makes sense to keep the diff between this branch and master small, which will eventually be helpful I think, for you to maintain it until it is ready, and for later review.

Yes indeed, although I was struggling to find out which can be splitted, especially in Makefile. Soon I'll open some PRs where possible, and some lines Disservin pointed out.

**Comment by Disservin** [comment]
Why do you use i386 as the name for the 64 bit targets?

**Comment by Disservin** [comment]
But I think I like where this is going. The function syntax for the arch implementations do tend to be a bit complex but i think that’s probably okay otherwise we would need to alias them with macros.. I also think that this makes it easier for us to have a binary with different simd code paths in future as well ?

**Comment by MinetaS** [comment]
> Why do you use i386 as the name for the 64 bit targets?
> 
> Okay I just saw it's not limited to 64 bits, it's also 32 bit.. but I still I find that name weird
> 
> Just x86 maybe?

Followed gcc convention. Planned to change to x86 later.

**Comment by MinetaS** [comment]
> But I think I like where this is going. The function syntax for the arch implementations do tend to be a bit complex but i think that’s probably okay otherwise we would need to alias them with macros.. I also think that this makes it easier for us to have a binary with different simd code paths in future as well ?

I think it's time to do some cleanup. Submitted a PR here: https://github.com/official-stockfish/Stockfish/pull/5584

**Comment by MinetaS** [comment]
A few people had tested this PR and thankfully reported back some errors - which were fixed later. However, this kind of changes requires extensive testing from a whole variety of platforms/machines, yet I don't know how it can be accomplished within the current state of it, other than merging into master and having a certain testing period. Over three months has passed - and I don't see any further improvements here.

Here are a few milestones that can be achieved one by one:

1. Drop several old Makefile configurations - mostly ancient Android OS.
2. Deduplicate/remove overlapping compiler options.
3. Use implicit Make variables correctly as intended (`CXX`, `CXXFLAGS` and so on; this way we can drop the entire Android stuffs `COMP=ndk`).

Once things are tidied up I'll consider to bring it back later.

**Comment by Disservin** [comment]
Those sound like reasonable things to do.

**Pull request closed without merging**
