### PR TITLE
PawnSafePush Simplification

### PR DESCRIPTION
**Pull request by Rocky640**
PawnSafePush, with the value S(5,5) proved not "necessary"
possibly due to recent changes to MobilityArea and other changes to Connected bonus.

STC: http://tests.stockfishchess.org/tests/view/55b98e060ebc590abbe1bdc8
LLR: 3.22 (-2.94,2.94) [-3.00,1.00]
Total: 98528 W: 18757 L: 18759 D: 61012

Lucas ran the LTC:
LTC: http://tests.stockfishchess.org/tests/view/55c54e1a0ebc591b934bd5af
LLR: 5.30 (-2.94,2.94) [-3.00,1.00]
Total: 204194 W: 31698 L: 31734 D: 140762

Lucas also verified if the older PawnAttackThreat (20,20) could be removed altogether
http://tests.stockfishchess.org/tests/view/55bd63070ebc590abbe1be63
http://tests.stockfishchess.org/tests/view/55bd623b0ebc590abbe1be5f
http://tests.stockfishchess.org/tests/view/55bdc3990ebc590abbe1be6e

### CODE REVIEW

**Comment by mcostalba** [comment]
Always nice when an ad-hoc rule is removed!

**Comment by zamar** [comment]
approved.

**Comment by Nakel** [comment]
There's a drop of 0.3 elo in this little patch, although the difference is very minuscule on STC, but on LTC, it can prove to be somewhat detrimental in the long run. PawnSafePush, after all, is a positional string. I don't think this should be committed. Removing a string just for the sake of clarity or "less code" is not a good idea.

**Comment by Rocky640** [comment]
Nakel,

It is a good thing that you think and express yourself, 
but instead of saying "we should do this or that", 
please learn a few things.

a) SPRT tests are not designed to measure elo difference, they are designed to test an hypothesis in a sequential run of tests, and stop as soon as a conclusion can be reached. 
They are not suitable for ELO measurement.

If you want to measure ELO, you must have a clear stop rule, and you will have an error bound.
Just like when you measure something on your ruler, 1mm +-0.5mm
There is nothing like 1 mm. There is always some error on any measure.
We do such lengthy measurements once in a while after a few successful patches.

b) the goal is not to remove one line of code, the goal is to reduce noise. 

When this parameter was introduced, it was duly tested and worked well, and approved. 
But since then, other adjustments and new features overlapped the same functionality. 

A Pawn Safe push is possible after all, if the square in front is free.
Some of this functionality was covered in a recent, more general MobilityArea patch. 
Another case is when the pawn is part of a phalanx, (and after the push, it will be supported) and that bonus had been increased too after the introduction of the PawnSafePush bonus.
Other cases which overlaps relates to passed pawns, and there is a special section of code just for this.

We want our parameters to be as independent as possible. When many parameters do the same thing, it is time to seek for simplification. It is not true that "more is better". 

c) Eventually the Mobility bonus will be tuned, and the Connected bonus too, and the final result will be better than if we would have kept this "noisy", overlapping bonus.

All this is a proven recipe which is part of SF success.

**Comment by AlexandreMasta** [comment]
Rocky, nice explanation and we all appreciate that. But how can you be sure that the recent modifications really serve this area? BTW pawnsafepush, if I´m not mistaken, is related about the front square is "not protected" by opponent...not if it is just "free". Maybe even this "ad-hoc" rule is just not well tuned now.
Finally, yes, the procedure SF developer team is adopting makes total sense. I just argue three things:

1- If these long term positinal features that are being removed can be detected in our "too fast" (short time controls test) kind of tests.
2- How these long term positional features are indeed being covered by other better and general rules.
3- Isn´t possible that in fact the feature is not well tuned?

Thx and Congrats!

**Comment by glinscott** [comment]
Looks good!

**Comment by Rocky640** [comment]
Good point Alexandre.

The only thing I'm sure is that...I'm not sure of anything. I only have some beliefs with different degree of certitude according to my brain's engine, which is often out of the normal error margins  ;)

Indeed, it is not clear if the 3 factors that I described will completely replace the PawnSafePush functionality. However, Search is ironing out many wrinkles. Some games will be lost, some will be win, but at the end of the day, the test tell us that it currently does not make a statistical difference at the tested time controls, within the test margin of errors.

However it is true that each one of these factors is overlapping in some way, with the PawnSafePush concept, and in the long run, something must be simplified. 
The PawnSafePush, having such a small S(5, 5) is the easiest victim for now, but that can change.

If I remember well, PawnSafePush was tested also with S(5, 15) and S(10,10). 
And here we can say it was tested with S(0, 0), and to be faire, with some odds against the "master".

It is also possible that a simpler PawnFreePush instead of a PawnSafePush would have been just as good, or better, or possibly just as "useless" too. Who knows ? 

Anyway, thank you for your comment, you gave me some ideas..

**Pull request closed without merging**
