### PR TITLE
Small clean-up, march 2021

### PR DESCRIPTION
**Pull request by snicolet**
No functional change

### CODE REVIEW

**Comment by BM123499** [comment]
I believe it's better to lowercase `Us`. Because, when the first letter is uppercase, it usually means that the value is calculated at compile time or an Array.

**Comment by mstembera** [comment]
Lines 237-239 in affine_transform.h should use the _mm_add_epi16() intrinsic instead of the _mm_adds_epi16() intrinsic in order to be consistent with the AVX2 and AVX512 versions.

**Comment by snicolet** [comment]
@mstembera What do you mean exactly? are you saying that the SSSE3 version is buggy and computes a wrong result?

**Comment by mstembera** [comment]
@snicolet No.  SSSE3 just uses the saturation version of the instruction which isn't necessary because we already make sure our nets never saturate.  The results for us will be the same.  The AVX2 and AVX512 blocks use the normal/simple version of the instruction.   (A minor benefit is that the non saturation versions have a slightly better throughput of 0.33 instead of 0.5 on some architectures like Skylake.
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_add_epi16&expand=85
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_adds_epi16&expand=173)

**Comment by snicolet** [comment]
I see, thanks for the explanation :-) 
I will change it.

**Comment by mstembera** [comment]
Sure & thanks.  I'm currently not aware of any.

**Comment by gvreuls** [comment]
https://github.com/official-stockfish/Stockfish/blob/ec42154ef2569a58dae2164e328d5bbffcb2aee9/src/evaluate.cpp#L57

This line is superfluous, it's the namespace the NNUE code resides in so it doesn't have to be specified explicitly.

**Comment by mstembera** [comment]
Cleanup fix_FRC() by removing unnecessary relative stuff.  Also optimize by returning early if no relevant bishops are present.  No functional change.  https://github.com/mstembera/Stockfish/commit/ea3326c0c93928e1bb351d1b9bdc8d4832f3f963

**Comment by snicolet** [comment]
@mstembera Thanks for the fix_FRC clean-up. 

Now with the new code and `penalty2` being so close from `penalty3`, it raises the question wether the `pos.piece_on(SQ_C3) == W_PAWN` conditions could be simplified. But this would need complete testing in a long match.

**Comment by mstembera** [comment]
@snicolet I may do something like that and also try unifying the constants with CorneredBishop.  If I do I will open a full PR.

**Comment by BM123499** [comment]
I believe you accidentally changed the name of the function and not where it's used

**Comment by snicolet** [comment]
I have checked that the cleaner fix_FRC() code by @mstembera gives the same node numbers and the same speed than master code, by running two long benches (depth 22) in parallel, with bench restricted to the chess960 positions proposed by @QuackQuackBlah in https://github.com/official-stockfish/Stockfish/pull/3398 .

Results:

```
===========================
Total time (ms) : 12155
Nodes searched  : 16170647
Nodes/second    : 1330369
testedpatch

===========================
Total time (ms) : 12175
Nodes searched  : 16170647
Nodes/second    : 1328184
master
```

So the new version of fix_FRC() seems good to me.

**Comment by noobpwnftw** [comment]
@snicolet maybe `#else` for the rest of the function or it may trigger a warning of unreachable code.

**Comment by Fanael** [comment]
@snicolet I can confirm that it works on windows XP and newer out of the box, can go even lower than that (2000 for sure, maybe even NT 4.0 and earlier) [if you're willing to patch winpthreads](https://fanael.github.io/stockfish-on-windows-98.html#rebuilding-winpthreads).

**Comment by snicolet** [comment]
@noobpwnftw @Fanael thanks!

**Comment by snicolet** [comment]
@Fanael 
Nice page you have there, by the way :-)
https://fanael.github.io/stockfish-on-windows-98.html

**Comment by snicolet** [comment]
Merged via 83eac08e7562d93787f75eccd4b7781c4bd45dd3, thanks all!

**Comment by Vinvin20** [comment]
There seems to be a 10 Elo regression with this "small clean up" : https://nextchessmove.com/dev-builds

**Comment by vondele** [comment]
I've started a regression/progression test https://tests.stockfishchess.org/tests/view/605c2cbbfa3cc97981cfaab0 it was about time anyway.

**Comment by snicolet** [comment]
I have also pushed a LTC non-regression test on fishtest, passed blue:
https://tests.stockfishchess.org/tests/view/605c40fefa3cc97981cfaac1

**Comment by vondele** [comment]
OK, that means no issues, IMO.

**Comment by kaimanox** [comment]
SF

IMHO three "bad" results in a row are quite significant evidence that something has gone wrong on this commit...isn't better to make a quick regression test for this patch only? Thanks

**Comment by vondele** [comment]
has been done, see comment above. Maybe a change at NCM like a system update?

**Comment by kaimanox** [comment]
As far as I understand, an "overall" regression test has been done, not on this single patch. The improvements coming from other patches may counterfeit the problem with this one.

**Comment by vondele** [comment]
both have been done, for the single patch it is mentioned here https://github.com/official-stockfish/Stockfish/pull/3405#issuecomment-808782030

**Comment by kaimanox** [comment]
I understand...well, I may be overworried but I'd do a regression test for each part of this patch...many commits don't seem so "small" to my eyes...10 elo points are months of work for the dev team, IMHO they deserve a double check...

**Pull request closed without merging**
