### PR TITLE
Eval tempo speed up

### PR DESCRIPTION
**Pull request by Stefano80**
Speed-up by precomputing 2*Eval::Tempo in eval.h. Gave 2.5/1000 speed-up (50 benches, delta > 0 over 6 sigma) on my machine.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
I really cannot believe this, I will check the asm output, it is almost
impossible compiler does not precomputes the value itself.

**Comment by lucasart** [comment]
@Stefano80: you don't understand what you're doing. you're "optimizing" a compile time constant?

**Comment by mcostalba** [comment]
Indeed this is the gcc asm out put (I have simplified it a bit removing
evaluate() call becuase it was heavily scrambled due to optimizations):

        1176            else
        1177                ss->staticEval = bestValue =
-(ss-1)->staticEval + 2 * Eval::Tempo;
0x42440c  <+0x02bc>         mov    %r13d,0x2c(%rbp)
0x424410  <+0x02c0>         mov    %r13d,%eax
        1178
        1179            // Stand pat. Return immediately if static value is
at least beta
        1180            if (bestValue >= beta)



And this is MSVC output

        else
            ss->staticEval = bestValue = -(ss-1)->staticEval + 2 *
Eval::Tempo;
000000013F5C7FAC  mov         esi,22h
000000013F5C7FB1  sub         esi,dword ptr [rbx-0Ch]
000000013F5C7FB4  xor         r11d,r11d
000000013F5C7FB7  mov         dword ptr [rbx+2Ch],esi


Here 22h is 34dec that is 2 * Eval::Tempo becuase Tempo = 17

**Comment by zamar** [comment]
Let's not waste anymore time/resources on this one, ok?

I'm closing this request.

**Pull request closed without merging**
