### PR TITLE
History Pruning

### PR DESCRIPTION
**Pull request by VoyagerOne**
Prune moves with negative History and CMH scores at low depth.

STC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 24182 W: 4672 L: 4439 D: 15071

LTC:
LLR: 2.97 (-2.94,2.94) [0.00,5.00]
Total: 12579 W: 1959 L: 1792 D: 8828

### CODE REVIEW

**Comment by VoyagerOne** [comment]
I added the ONE_PLY...I am quite certain this is not a functional change.

SMP Experts:  Please make sure the Thread is pointed correctly for History Stat.

**Comment by Stefano80** [comment]
Congratulations!

**Comment by mcostalba** [comment]
ONE_PLY is fine. Congratulations.

**Comment by glinscott** [comment]
Congratulations, looks good!

**Comment by zamar** [comment]
approved.

**Comment by mcostalba** [comment]
Applied.

**Pull request closed without merging**
