### PR TITLE
Avoid comma operator

### PR DESCRIPTION
**Pull request by vondele**
for some less common idioms, improving readability.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
@vondele sorry but I don't like it. Comma operator is quite common and readibiliy is not improved at all IMO.

**Comment by zamar** [comment]
Personally I agree that combining comma and return statements is a bit weird, so I would be inclined to remove that.

But since @mcostalba is our coding style expert, I guess we should just live with the current syntax.

Leaving this open for further discussion for a little while.

**Comment by vondele** [comment]
@mcostalba I found no good answer to the question 'Why would I use a comma operator here and not elsewhere ?', so since this idiom didn't add clarity in those 5 places, I went for the style used elsewhere in the code.

**Comment by mcostalba** [comment]
@vondele ok, first of all, comma operator should not be a surprise for anyone even with just basic knowledge of C / C++. Indeed it is a C construct that C++ inherited and defines a [sequence point](https://en.wikipedia.org/wiki/Sequence_point).

It is mostly used in for loops, for instance [here](https://github.com/official-stockfish/Stockfish/blob/master/src/syzygy/tbprobe.cpp#L1090), and I think if someone doesn't understand that for loop then he really needs to read some beginner tutorial on C language.

Now the reason why I used commas in the code you mention is, first because semicolon should be normally split on 2 lines, not as you did in sync(), instead commas on a single line are not only OK but the idiomatic way, and then because I wanted to convey the idea that although only one return value is possible in C functions, the 2 values are semantically part of a single return value, for instance in TT, the return value is **semantically** the pair (found, key), if C would allow to return 2 values, like Python, that would definitely being part of the same return statement, but instead I need to _return_ "found" by means of passing it by reference in the function arguments and assigning to it. This is a typical and idiomatic trick used by C functions when more then one value needs to be _returned_, to workaround a semantic limit of the language. In C++ I could return a std::pair, but that seems to me a bit overkill.

**Comment by vondele** [comment]
I understood why you used it there... but I don't see the added value of adopting that notation. It is good for a quiz (see question 8 of https://kukuruku.co/post/i-do-not-know-c/ ), but that's not the purpose of the code.

**Comment by lucasart** [comment]
I prefer @vondele's version.

**Comment by MichaelB7** [comment]
Prefer @vondele's version, but Marco's position has validity and his points are well taken. Considering everything Marco has contributed to Stockfish in its totality, it may be best to defer.

**Comment by Rocky640** [comment]
https://en.wikipedia.org/wiki/Comma_operator
Near the end, see use cases Complex Return and Avoid a block

In evaluate_passed_pawns, we can see an excellent use of the comma operator,

**Pull request closed without merging**
