### PR TITLE
Clean

### PR DESCRIPTION
**Pull request by lucasart**
No functional change.

### CODE REVIEW

**Comment by glinscott** [comment]
Looks good.

**Comment by mcostalba** [comment]
Actually use of Tablebases instead of TB was done on purpose in the cases where we refer to the specific syzygy functions, instead of our ancillary variables. But I understand is just a personal preference.

**Comment by lucasart** [comment]
@mcostalba: that's really weird! my preference would be to use only one name for a namespace, and never write something like `namespace X = Y` to allow refering to the same namespace by two different names.

it's unnecessarly confusing. if you're going to use the namespace a lot, you want a short name that is easy to type and easy to read, so it should be `TB` and not `Tablebases`.

can I push a patch that renames this clumsy `Tablebases` into `TB` everywhere, and removes the namespace alias ?

**Comment by mcostalba** [comment]
Ok, leave you patch as is, but please don't rename Tablebases into TB everywhere, the first is definitely more understandable, the latter comes handy in code but looking up TB people should immediately understand TB = Tablebases

**Comment by lucasart** [comment]
Sorry, I don't see any reason to call it `Tablebases` and not simply `TB`. Everyone understands TB, just like everyone understands `UCI`. That's why we don't call the UCI namespace UniversalChessInterface.

**Comment by zamar** [comment]
I'm fine for either way... TB or Tablebases...

**Comment by lucasart** [comment]
@zamar: so what's your decision. if you don't care either way, just flip a coin!

**Comment by mcostalba** [comment]
It means decision is up to you.

**Comment by lucasart** [comment]
then my decision is TB. for many good reasons:
* it's equally understandable to Tablebases
* it avoids the confusing namespace aliasing in search.cpp, along with the weirdness that it encourages (using one name sometimes, and another sometimes)
* it's less verbose and that makes.code easier to read.

**Comment by mcostalba** [comment]
Please commit current patch, but do not remove Tablespace namespace from
everywhere.

We have TranspositionTable, not TT

We have BItbases, not Bbases

We have Bitboard not BB

Current standard is to prefer long names for global scope entities, and I
think is a sound standard.

TB could be equally understandable for you, but not for a novice
reading the sources for the first time. Many things we give for
granted, especially after dealing with the sources for long time, but the
way you look at the sources is _different_ from the way of newbies,  casual
readers or programmers looking at SF for the first time.

**Comment by zamar** [comment]
Can you guys please try find a some kind of agreement about this?

I have under zero interest about the topic....

**Pull request closed without merging**
