### PR TITLE
Assorted trivial cleanups July 2019

### PR DESCRIPTION
**Pull request by Rocky640**
Opening a new PR for trivial cleanups.
Feel free to comment or contribute.

### CODE REVIEW

**Comment by mrobaczyk** [comment]
There is also a VALUE_ZERO in make_score in pawns.cpp line 237
`Score shelter = make_score(-VALUE_INFINITE, VALUE_ZERO);`

**Comment by snicolet** [comment]
We could use this to document the new UCI options for Elo levels in the Readme.
More generally, the Readme could be cleaned up and updated a lot, it seems.

Any volunteer? :-)

**Comment by Lolligerhans** [comment]
Line 93 in evaluate.cpp declares arrays of size 32 - but all arrays are max 28 elements long
`
constexpr Score MobilityBonus[][32] = {
`

**Comment by Rocky640** [comment]
I think this [32] is intentional because it aligns memory nicely.

**Comment by Lolligerhans** [comment]
I am used to ordering members in structures in order to minimize `sizeof` that structure; but what is the benefit of reserving 128 byte for <= 112 byte arrays?

**Comment by snicolet** [comment]
Cache line

**Comment by Rocky640** [comment]
FYI, readme is already up to date about UCI_LimitStrength and UCI_Elo
https://github.com/official-stockfish/Stockfish/commit/0dbc72d82e7f5f314499b22a04dcef45edcdba9a

**Comment by snicolet** [comment]
Thanks Alain. I thought there had been a clarification by @vondele somewhere (was it in the forum? I can't find the reference right now)  in the last few days about the semantics, because someone was a little bit confused with the of the new commands, and I thought that this would be a good idea to include @vondele answer somehow in the readme.

**Comment by Lolligerhans** [comment]
@Rocky640 evaluate.cpp uses types.h (e.g., for `typename Score`) but depends on bitboard.h including it. AFAIK it is welcomed to directly include any headers used.

**Comment by Rocky640** [comment]
Apparently, changing headers is not so trivial.

See for example this discussion about headers, and finally nothing was committed.
https://github.com/official-stockfish/Stockfish/pull/971

If you want to work on this, double check all the headers and open a new PR.

**Comment by snicolet** [comment]
The frontmost_sq() function in line 380 of bitboard.h should be in 3 lines instead of 1.

**Comment by snicolet** [comment]
No period at the end of the following comment in search.cpp:

// Mark this node as being searched.

Also, how could we make the following comment in pawns.cpp 
only one line lone, instead of two lines long (and remove the period)?

// Passed pawns will be properly scored later in evaluation when we have
 // full attack info.

**Comment by snicolet** [comment]
in tbprobe.cpp, change:

` for (Color c : {WHITE, BLACK})`

to
` for (Color c : { WHITE, BLACK })`

**Comment by Lolligerhans** [comment]
In Evaluation::Pieces there's an empty line between computing `mob` and giving mobility bonus, which seems unnecessary.

**Comment by Rocky640** [comment]
This one had been there forever, I would agree if mob was used only on the next line.

As it is, it is a hint that it is used elsewhere, and indeed, it is used 50 lines below.

**Comment by protonspring** [comment]
All but the 4 base directions can go away.
Seems like a waste to define NORTH_WEST when NORTH+WEST is just as readable and equivalent.

https://github.com/protonspring/Stockfish/tree/ps_directions2

**Comment by snicolet** [comment]
@Rocky640 
Merged via 7efc39d6833a0d999a7bf2f9b5629ceb246accd2, thanks for taking care of that! :-)

**Pull request closed without merging**
