### PR TITLE
TTreplace

### PR DESCRIPTION
**Pull request by mstembera**
STC 2MB
LLR: 2.96 (-2.94,2.94) [-1.50,4.50]
Total: 16353 W: 3216 L: 3066 D: 10071
http://tests.stockfishchess.org/tests/view/55a6d0630ebc590abbe1babd

LTC 8MB
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 134618 W: 21276 L: 20716 D: 92626
http://tests.stockfishchess.org/tests/view/55a74d760ebc590abbe1bad6

STC 16MB
LLR: 2.96 (-2.94,2.94) [-4.00,0.00]
Total: 22549 W: 4257 L: 4178 D: 14114
http://tests.stockfishchess.org/tests/view/55a9a2f90ebc590abbe1bb16

Tuned version of TT replacement policy. (Note if the used multiplier of 8 was any number larger than DEPTH_MAX this would be a non functional patch.)

### CODE REVIEW

**Comment by mcostalba** [comment]
2 comments:

- Replace 8 with 8 * ONE_PLY

- Comment could be rewritten as "TTEntry t1 is considered to be more
valuable than a TTEntry t2 if both are from current search and the depth of t1
is bigger than the depth of t2, or if t1 is from a previous search but its
depth is at least 8 plies deeper than t2"

**Comment by mstembera** [comment]
@mcostalba 
Done.  Thanks.

**Comment by zamar** [comment]
approved.

**Comment by glinscott** [comment]
Looks good!

**Comment by zamar** [comment]
@glincott: Do you mind committing this? I'm currently travelling and unable to access git repo in the near future...

**Comment by zamar** [comment]
@glinscott : Do you mind committing this? I'm currently travelling and unable to access git repo in the near future...

**Comment by mstembera** [comment]
Please read
https://groups.google.com/forum/#!topic/fishcooking/qYFx842EsXA

**Pull request closed without merging**
