### PR TITLE
Lower and simplify the computed midgame passed pawn bonus

### PR DESCRIPTION
**Pull request by tomtor**
STC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 18333 W: 3504 L: 3378 D: 11451

LTC:
LLR: 3.09 (-2.94,2.94) [-3.00,1.00]
Total: 33406 W: 4634 L: 4524 D: 24248

### CODE REVIEW

**Comment by DamasClasicas** [comment]
Nice simplification. Congratulations!

**Comment by lucasart** [comment]
that's stretching a bit the meaning of simplification. looks more like a tuning patch IMO.

**Comment by Rocky640** [comment]
I agree. I would have run this as a [0,4].
But this change cannot harm for sure. 

It would however be more interesting to "simplify" the ebonus as well.

**Comment by tomtor** [comment]
@Rocky640 Changing ebonus as well performs badly in limited local testing, so this suggest that lowering the mbonus compared to the ebonus gives the (small) elo gain of this minor simplification. I suggest to test changing the ebonus in fishtest if you think that would result in a gain.

**Comment by Rocky640** [comment]
Good ! We can always run more tests once this is committed.

Thinking about this a little bit, if we are able to move our blocking piece (which might be quite difficult) it will eventually fall under the unblocked and defended case,
where we currently allocate minimally an extra of 2 * rr when the front square is defended.

Viewed this way, and if this thing is sensitive as hinted by your local tests 
maybe the ebonus in the blocked case should be raised !
So instead of e = rr + r * 2, maybe e = rr + r * 3 
or a bit more with e = 2 * rr 

But maintainers, if I try to change e = rr + r * 2 for e = 2 * rr, 
would this be a simplification ?

**Comment by mcostalba** [comment]
Well, this is more a paramter tweak than anything else.

@tomtor what about giving it a spin at SPRT[0, 4] ?

**Comment by tomtor** [comment]
@mcostalba Sure, no problem, but with the same logic

http://tests.stockfishchess.org/tests/view/57b07e000ebc591c761f622d

should also be [0,4]? (I queued with [0,5])

**Comment by mcostalba** [comment]
@tomtor yes, also http://tests.stockfishchess.org/tests/view/57b07e000ebc591c761f622d seems a parameters tweak to me, so it is OK a SPRT[0, 4]

**Comment by tomtor** [comment]
OK, http://tests.stockfishchess.org/tests/view/57b0851f0ebc591c761f6232 ended Yellow.

I'll try to tweak it some more....

**Comment by MichaelB7** [comment]
3 of the 4 red scores are with crunchy - which I believe is new hardware to fish cooking - we might want to double check his setup...

**Pull request closed without merging**
