### PR TITLE
Remove parts of unnecessary code

### PR DESCRIPTION
**Pull request by noobpwnftw**
No functional change

### CODE REVIEW

**Comment by JackWright347** [comment]
Did I understand correctly that all manually inline assembler-perfomance optimized places in the code that use Intel intrinsic instructions (like _pext_u64, _mm_popcnt_u64, _mm_prefetch) should be dropped?

Are there already benchmark test results from the "purify_cpp" branch versions that no longer call Intel intrinsic instructions in the C++ source code? How do they stack up against their inline assembler optimized predecessors? Thanks!

**Comment by noobpwnftw** [comment]
Intrinsic instructions are naturally inlined by the compiler, benchmarks of the remaining minimal C++ code therefore depends on compiler, and I trust the compiler to do its job optimizing the code whenever necessary.

If there is such necessity that manual inline is required to make it more optimized, then it is a problem of the compiler and it should be improved there instead of adding extra lines of code which makes code maintenance harder.

A few other simplifications:
1. Speculative prefetching should be done intelligently by the CPU, if the outcome is not as expected, then you probably need a better CPU, specially the hardware prefetcher.
2. Thread affinity and large pages should be handled by the operating system, if somehow it does not convert busy and big memory pages into large pages, or place different threads on separate physical CPU cores then you probably need a better OS which does those.

That said, I'm open to suggestions which points out which part of code I removed is considered necessary and should be kept, or recommend any other unnecessary code that I should remove.

**Comment by MichaelB7** [comment]
I belive this patch is the correct approach Stockfish shoud be taking - trust the compiler, amd keep the code cleaner.

**Comment by JackWright347** [comment]
But what we also probably don't want is for Stockfish's ELO numbers to plummet because code maintenance has become easier as everything is written only in C++, and we then start blaming compiler makers for not optimizing efficiently enough.

**Comment by noobpwnftw** [comment]
Of course, so let's see what the exact lines of code should be optimized manually then?
I'm more than happy to reduce this PR to non-exist should all of those lines I removed have good reasons be kept.

**Comment by ppigazzini** [comment]
@noobpwnftw if I'm not horribly wrong, by rules this nice cleanup should be tested in fishtest before opening a PR.

https://github.com/glinscott/fishtest/wiki/Creating-my-first-test#non-functional-changes

"Anything not fitting the above small cleanup category should typically be tested on fishtest, unless the code is not really exercised on fishtest (e.g. syzygy) and doesn't change bench. This approach verifies code correctness (no crashes), and makes sure there are no unexpected side effects or slowdowns."

Feel free to contribute some CPU to our framework to speedup the test of your PR, here are the instructions, let me know if you need some help to setup a worker :)

https://github.com/glinscott/fishtest/wiki/Running-the-worker:-overview

**Comment by noobpwnftw** [comment]
If I'm not horribly wrong, by the rules this nice cleanup fits in:

"Code refactoring and non-functional simplifications are a very wide family of patches and, by their nature, more subjective than other kind of patches. So also the acceptance guidelines rely more on maintainer knowledge, experience and sensibility."

Which precedes your above quote, indicating that this does not need to go through testing. So I will be waiting on this "subjective judgement" or other comments to see how shall we move forward.

**Comment by ppigazzini** [comment]
Unfortunately it seems that I have only incompetent OS/compiler combinations, this nice cleanup is a little slowdown in all my tests :(

- master vs nice_cleanup , both built with `make profile-build ARCH=x86-64 COMP=gcc`:
```
bash bench_parallel.sh ./stockfish_master_x86-64 ./stockfish_nice_cleanup_x86-64 15 10

sf_base =    1297526 +/- 20726
sf_test =     674258 +/- 5508
diff =    -623267 +/- 15308
speedup = -0.480351
```

- master vs nice_cleanup , with master built with `make profile-build ARCH=x86-64-modern COMP=gcc`:
```
bash bench_parallel.sh ./stockfish_master_x86-64-modern ./stockfish_nice_cleanup_x86-64 15 10

sf_base =    1588738 +/- 23866
sf_test =     674313 +/- 5191
diff =    -914425 +/- 18809
speedup = -0.575567
```


Anyway your clever simplification https://github.com/official-stockfish/Stockfish/pull/3586/commits/1d4c677cbedd689790d435b101c10b7e4896559f is on par with master also for my incompetent OS/compiler :)

- master vs clever_simplification , both built with `make profile-build ARCH=x86-64-modern COMP=gcc`:
```
bash bench_parallel.sh ./stockfish_master_x86-64-modern ./stockfish_clever_simplification_x86-64-modern 15 10

sf_base =    1580660 +/- 29342
sf_test =    1582162 +/- 28540
diff =       1502 +/- 4873
speedup = 0.000951
```

**Comment by niklasf** [comment]
The impact on real world performance is catastrophic of course, and I hope for a more measured approach (like https://github.com/official-stockfish/Stockfish/pull/3545). Instead of arguing this, let's have a look at what we can reasonably expect from compilers in the future ...

* Even if compilers were much better at auto vectorization than they are, they still need to know what hardware capabilities they can rely on. So the various at least the build profiles need to stay.
* Optimal prefetching is undecidable, so there will always be programs where cleverly placed manual prefetches are an advantage. Stockfish does not have to be one of them, but when it was tried it was.
* It is extremely unreasonable to expect compilers to be able to magically infer that move generation via magic bitboards can be optimized by replacing it entirely with PEXT.
* Large pages and thread affinity are perhaps the most reasonable part of this patch. But even there, the operating system can only know what's happening after the program is already running, while the authors are in a much better position to know the structure.

Honestly, before the comments, I thought this was a joke pull request and I am still not quite sure.

**Comment by noobpwnftw** [comment]
@niklasf Thanks for your input, I have refined my changes:

1. Build profiles stay
2. Manual prefetch stays
3. PEXT stays
4. LP and thread affinity stay

Now that it basically only removes manual SIMD optimizations within various NNUE related files.

Question:
1. Do you prefer to cleanup those code path on a per function, per file, or a per folder basis?
2. What are the supported list of compilers and their versions should measurements be done for?

**Comment by ppigazzini** [comment]
Same incompetent OS/compiler and archaic CPU combination :(
 
- master vs PR after https://github.com/official-stockfish/Stockfish/pull/3586/commits/cee417f612a1b460f42a600ff0ec0b9d8ef61e28, both built with `make profile-build ARCH=x86-64-modern COMP=gcc`:
```
bash bench_parallel.sh ./stockfish_master ./stockfish_nice_cleanup_cee417f 15 10

sf_base =    1577119 +/- 24863
sf_test =     692997 +/- 4890
diff =    -884122 +/- 20137
speedup = -0.560593
```

**Comment by noobpwnftw** [comment]
According the above result, adding (786 - 25) lines of code made it 2% faster.
Now that I can deduce that adding another (865 - 4) lines might probably make it 100% faster.

I can see a problem here: why it seems easier for people to decide that the former needs to stay but we need to go case by case on the latter?

**Comment by niklasf** [comment]
> I can see a problem here: why it seems easier for people to decide that the former needs to stay but we need to go case by case on the latter?

I didn't mean to say that the 2% improvements need to stay, just that we can't expect improved compilers to figure these out automatically. If you're considering to take the remainig 50% performance hit, it would indeed  be ridiculous to keep them. If you're fighting hard for each percent, simple code like prefetching, and self contained code like thread affinity etc. seems worth it.

> What are the supported list of compilers and their versions should measurements be done for?

Stockfish is completely free to say it's fast only on particular compilers, so ... any really. Preferably in their latest version, so we're not stuck with old versions, with the ususal regression tests to catch cases of fragile auto vectorization. Maybe latest GCC and latest Clang, for decent platform coverage? fishtest would have to be updated accordingly, but all that could be done, ...

But most likely it will be a considerable slowdown. Going loop by loop might show some that can be simplified at no loss (like it turned out for clipped relu), some that can be tweaked slightly to make it easier for the compiler, and some that might be worth keeping handpicked intrinsics for 🤷

**Comment by noobpwnftw** [comment]
As far as I can recall, the clipped relu simplification is a ~2% slowdown with any incompetent compiler at best, a bit more on latest Clang. So it would worth 7.5x more lines of code to take that loss by removing all the aforementioned combined, let alone I do not see how removing one loop optimization among dozens closely related amid slowdowns would make the code any cleaner.

Therefore I wondered if removing all manual optimization is what you really want. If not, what is it exactly?

**Comment by niklasf** [comment]
After some tweaking, based on https://github.com/official-stockfish/Stockfish/pull/3545#issuecomment-864401839, there was no measurable slowdown at all for recent Clang and GCC, so this arguably should and would have been comitted.

**Comment by noobpwnftw** [comment]
Do you consider that list of tested compilers being comprehensive? If so, I will further refine my cleanups.

**Comment by niklasf** [comment]
Personally I would be happy with that, even with a more restricted set.

I don't know what the official policy is, if any exists, but regardless, a major simplification patch like this can potentially be a strong argument to drop support for compilers.

**Comment by noobpwnftw** [comment]
I'm not so sure about it being a major simplification, as per lines of code removed to slowdowns, removing all the aforementioned could've been better even comparing to the tweaked version. Although if it is deemed necessary to cover up potential damages caused by such simplifications with the help of dropping compiler support, I'm all for it.

So arguably here is the refined cleanup taken from the original PR, plus dropping compilers that no longer supported/tested.

Now, who disagrees?

**Comment by Sopel97** [comment]
Since the results presented here https://github.com/official-stockfish/Stockfish/pull/3545#issuecomment-864401839 are very bad for GCC8 I also suggest we remove the support for it, and with it it would allow us to remove ugly hacks: https://github.com/official-stockfish/Stockfish/blob/0470bcef0e1962b4f8da15108170b991d3f90d0e/src/nnue/evaluate_nnue.cpp#L147-L154 https://github.com/official-stockfish/Stockfish/blob/0470bcef0e1962b4f8da15108170b991d3f90d0e/src/nnue/evaluate_nnue.cpp#L196-L203 https://github.com/official-stockfish/Stockfish/blob/0470bcef0e1962b4f8da15108170b991d3f90d0e/src/misc.h#L70-L80 https://github.com/official-stockfish/Stockfish/blob/0470bcef0e1962b4f8da15108170b991d3f90d0e/src/types.h#L60-L62

**Comment by noobpwnftw** [comment]
Any hint on how to disable AppVeyor?

**Comment by ppigazzini** [comment]
```
bash bench_parallel.sh ./stockfish ./stockfish_f7d0382 15 10 NNUE

sf_base =    1189787 +/- 23585
sf_test =    1180644 +/- 22537
diff =      -9143 +/- 10353
speedup = -0.007685
```

**Comment by noobpwnftw** [comment]
So here we are, the tweaked simplification as is, the loose ends of unsupported compilers are taken care of, AppVeyor seems to be the only thing that still uses MSVC, plus we don't ever have a proper project file for it(https://github.com/official-stockfish/Stockfish/pull/3585). As for ICC, do we ever get that tested for? I cannot recall.

Known issues with compilers:
1. GCC8.? : slowdown after this simplification
2. GCC9.0 : crashes without hack, can fix with unaligned loads with a slowdown, keep, fix or drop support?

**Comment by noobpwnftw** [comment]
Now I get you 3x more cleaner code, same minor issues, and I don't see any objections(yet?).

So what is the matter? Do those people have a personal issue with SN or what? Tell me.

**Comment by lucasart** [comment]
I don't think this PR is meant to be take seriously. Just looking at the diff, I see that it's a mix of a dozen different unrelated changes, most of which are obviously not acceptable.

Looks more like a rant, coming from a sense that SF code base has lost its way; it used to be small and beautiful, and is now huge complex.

**Comment by noobpwnftw** [comment]
What exactly is unrelated? What exactly is not acceptable? If you can be more specific, then I can refine my PR.

**Comment by NKONSTANTAKIS** [comment]
I think the goal is reaching clarity via a method used by Socrates.

**Comment by JackWright347** [comment]
If the Socratic Method does not help prevent Stockfish nps slowdown, it is useless.

**Comment by NKONSTANTAKIS** [comment]
It might help nps in a reverse way: by using the same argument that is used for accepting slowdown for reduced LOC, with 3 positive possibilities:

1. The argument to be clarified and well-defined.
2. The argument to be abolished.
3. The slowdowns that are deemed worth it to be accepted, but without using the argument. Here it has to be defined "deemed worth it by whom?". The maintainers judgement? General consensus? Combination of the 2?

I think noobs reasoning for this is that any of the 3 would be much preferable than endless argumentation for supporting subjective preference at close calls.

A metaphor:
Its like a group starting for a top of mountain and when its time for a break some want to drink orange juice and some ice cream. "its packed with vit C that we need", "ice cream is cold and tasty, look at this heat", "But fructose will give us longer lasting energy than glycose", "who cares, sugar boost now and lets do another stop later", "Its idiotic to prefer a factory product over the natural thing", "ok I'm done, going home".
So one guide quit and the guy paying for the refreshments went angry.

**Comment by JackWright347** [comment]
However philosophical, but personally I'm much more pragmatic about it, sorry. You can't argue with the Profiler. If he says that more CPU cycles are consumed, then he is probably right. End of story.

**Comment by NKONSTANTAKIS** [comment]
This PR is not meant to be taken literally. It initiates a step by step procedure for determining which will stay on the boat and what the boat will be.

In 285 AD, Emperor Diocletian decided that the Roman Empire was too big to manage. He divided the Empire into two parts, the Eastern Roman Empire and the Western Roman Empire.

**Comment by JackWright347** [comment]
The advantage Emperor Diocletian had back then in 285 AD was that he did not have to compete in the CCRL 40/15, right?

**Comment by NKONSTANTAKIS** [comment]
Its all about orthodox vs catholic.

**Comment by MRMikaelJ** [comment]
> The advantage Emperor Diocletian had back then in 285 AD was that he did not have to compete in the CCRL 40/15, right?
Is maximum possible nps at ccrl and other key rating lists the goal?

**Comment by JackWright347** [comment]
I see, and Yin vs Yang, I suppose. All right. Now I can understand this PR much better.

**Comment by noobpwnftw** [comment]
So can anyone answer the above listed questions and provide precise instructions on how should this PR be refined?

I'm willingly refining my PR to your very specific demands. If anyone have concerns regarding the changes made, please read above to see if you can find a satisfying reason. If you still have a problem, please raise your concern in detail and tell me what exactly do you want.

**Comment by NKONSTANTAKIS** [comment]
When you are #2 naturally the common goal is to become #1. But when you are #1 with good distance, there are many meritful options:
To increase distance even more.
To preserve energy by running more frugally, aiming for the long run.
To run in a more graceful manner, as also now a lot of photographers shoot you.

Hence a redefinement of the goals are required, and we are at this stage, albeit in a weird way.
Personally I would like SF to go towards maximizing usefulness for chess users. But I am a chess person.
I can understand the different viewpoints of coders, who have coding and not chess as a passion.
However, lets regard that probably 99% of SF's users are clueless about programming.
But ok they can use forks, which offer stuff that SF doesn't, and its not a problem.
The problem is totally between programmers, for different routes of development.

**Comment by noobpwnftw** [comment]
I don't care about your goal, whatever that is.

Here we have very specific decisions to discuss, as simple as: do we accept slowdowns or not, do we drop untested compiler support or not, do you remove this unnecessary code or not.

Now who is responsible for making the calls? Maintainers? You people(as a community!) managed to get rid of one, so now who is going to live with the consequences?

It now seems apparent that when it gets down to that, some of those went silent? If you are not ready to be responsible for what you wish for, then the history of this PR is your education.

**Comment by NKONSTANTAKIS** [comment]
Noob, despite your great contribution, this is not your company, but an open source project. So you are trying but you can't fully dictate structured organization and hierarchy. I am seeing that you are trying it for good cause, but you have gone full tilt mode. You write some hard-hitting stuff which are not quite accurate. The community didn't get rid of SN, but he stepped down on his own will, "feeling out of sync with most modern devs", after a heated argument with another dev.

Anyway, long story short, nobody is getting paid in this project and everybody is free to quit whenever he wants. The key is to enjoy life. That's my opinion. My opinions might be indifferent to you, but I am voicing them because I want and because I can. Even though my motives are towards a solution, I wouldn't shed a tear if I got banned. I hope you sort it all out. Cheers.

Now for practical reasons, and regarding what you seem to care most for, in the past we had just 1 maintainer, but with 2 it seems to be better as the workload is shared. Lets allow SN time to rest, wish him nice health recovery, thank him for his amazing contribution throughout the years, and move on. Lets not be brutal anymore, we are foremost humans, not robots. I think sopel has done by far the most for NNUE, so is the most suitable person to step up, if he also wishes so, but it can work just fine with just vondele.

**Comment by noobpwnftw** [comment]
Because of my great contribution, am I not allowed to write hard-hitting stuff or what? My expression of the situation is accurate however it may sound to you.

Anyway, long story short, you should not imply any different standard to anyone, maintainers are allowed to make mistakes, and I'm allowed to quit, they are not the end of the world.

Now for practical reasons, if I find answers to the questions asked, I will refine this PR and see how shall things move forward.

I've largely been staying on topic discussing strictly technical details and it was you who started to go off-topic.

**Comment by NKONSTANTAKIS** [comment]
Of course you are allowed to voice yourself, and I agree that voicing helps. But silence and vacation time help too. What I am saying might seem out of topic, but it addresses the deeper topic, which led to this PR. Anyway as I have already said what I felt to, and can't help with the technical stuff, I wish you good luck with the refinement, and will try to go silent.

**Comment by Sopel97** [comment]
I think this thread is a big maintanence burden and requires a lot of attention and brain power to keep it going. I'd suggest simplifying it, by removing the hundreds of lines written here. It would be a non-functional simplification. It would also allow us to put more attention to other, more important parts of the project.

**Comment by skiminki** [comment]
> Since the results presented here #3545 (comment) are very bad for GCC8. So I suggest removing the support for it.
> Then it's also not a big step to remove support for GCC9.0, which would allow us to remove ugly hacks: 

I'm not entirely sure what part of this thread is in serious tone and what is not... But there may be half a point in simplifying the compilation environment a bit.

What I've been doing lately is to run all my fishtest worker instances under docker. That's partly because I'm too lazy to keep all my various boxes up to date with compiler environment requirements, etc, so I'd rather just keep one environment up to date and replicate it everywhere. And partly, because I'd rather not run "random" code from the internet on my machines without at least some level of containerization.

If you're seriously looking into simplifying the compilation environments etc, then you might also consider standardized fishtest worker environment. The attached files may be of help. That docker environment contains Ubuntu 21.04 + GCC 10. I run this docker in couple of different Linux variants, and it also runs just fine in Win 10 docker on WSL2. However, the produced image is sizable and probably contains lots of unnecessary stuff. I haven't done any pruning whatsoever for it.

[fishtest-docker.tar.gz](https://github.com/official-stockfish/Stockfish/files/6720671/fishtest-docker.tar.gz)

To set up:
* Check credentials.txt
* modify start-fishtest-worker.sh to point to your local image or local docker repository. I haven't uploaded the images in public repos

**Comment by noobpwnftw** [comment]
What I cannot understand in the original conflict is for one to simply say "simplification of code, not everyone will like it but doing it anyway", what I cannot understand now is no one who have had strong "opinions" to come out and make some calls, you just want the maintainers to do all the dirty work for you.

I have a history of saying unpleasant things, but if you think sitting this out solves anything, then you are no better.

---

Homogeneous environments have their consequences, a more real-life environment is probably better for testing, big contributors should already have their own means of deployments. I think it isn't necessary to standardize it.

**Pull request closed without merging**
