### PR TITLE
Cluster merge master8

### PR DESCRIPTION
**Pull request by vondele**
Merges current SF 11 in the cluster branch. Fixes minor conflicts.

No functional change.

### CODE REVIEW

**Comment by snicolet** [comment]
@vondele Hi Joost, I get this message here on GitHub: "This branch cannot be rebased due to conflicts".

**Comment by vondele** [comment]
@snicolet rebase is likely not possible, just merging should work this branch in the cluster branch should work.

**Comment by snicolet** [comment]
This need some more commits from the start of SF12 development, so I close this PR now...

**Comment by vondele** [comment]
I'll merge this in the cluster branch to get it up to SF11 level.

**Pull request closed without merging**
