### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by vondele**
the recent refactoring has shown some limitations of our testing, hence we add a couple of more tests including:
* expected mate score
* expected mated score
* expected in TB win score
* expected in TB loss score
* expected info line output
* expected info line output (wdl)

No functional change

### CODE REVIEW

**Comment by locutus2** [comment]
@vondele 
Nice but here are some remarks:
- par example for the test in line 153-158 the second move played is not important (i have here in some dev version the pv c6d7 e3e2 f7f5 which also mates in two), so the test 'expect "pv c6d7 f2f1q f7f5" ' could fail.
- also we had problems for the following commands so i would add tests for this also:
  1.  setting position with 'moves'
  2.  using go with searchmoves options.

**Comment by vondele** [comment]
@locutus2 sure, do you mind giving the uci for the examples you want to add for i. and ii. I can add them to the script.

**Comment by Disservin** [comment]
we also had this in the past, not sure if one can easily "test" that...
https://github.com/official-stockfish/Stockfish/issues/4273

**Comment by vondele** [comment]
> we also had this in the past, not sure if one can easily "test" that... #4273

I think this can be captured by requiring the info line to be present in the expected format for each depth. I'll try a change.

**Comment by locutus2** [comment]
@vondele 
Here are three tests one for only 'moves', one for 'searchmoves' and one combination of the both (that combination was the problem i discovered)
```
send "ucinewgame\n"
send "position fen 8/5R2/2K1P3/4k3/8/b1PPpp1B/5p2/8 w - - moves c6d7 f2f1q\n"
send "go depth 18\n"
expect "score mate 1"
expect "pv f7f5"
expect "bestmove f7f5"

send "ucinewgame\n"
send "position fen 8/5R2/2K1P3/4k3/8/b1PPpp1B/5p2/8 w - -\n"
send "go depth 18 searchmoves c6d7\n"
expect "score mate 2"
expect "pv c6d7"
expect "bestmove c6d7"

send "ucinewgame\n"
send "position fen 8/5R2/2K1P3/4k3/8/b1PPpp1B/5p2/8 w - - moves c6d7\n"
send "go depth 18 searchmoves e3e2\n"
expect "score mate -1"
expect "pv e3e2 f7f5"
expect "bestmove e3e2"
```

Also you should fix the pv test for your other test which use the same position which i mentioned in my previous post.

**Comment by locutus2** [comment]
@vondele 
I have seen one of the other tests has been fixed but you miss beginning from line 193 the pv check has also to be fixed because its the same position.

**Comment by locutus2** [comment]
@vondele 
And instead `expect "score mate 2 * pv c6d7"` for the pv fix we can use the stricter `expect "score mate 2 * pv c6d7 * f7f5"` to cover more from the pv.

**Comment by locutus2** [comment]
@vondele 
Also for test beginning from line 199 the pv is also not unique because black has three different moves for second move (variations: Rc4 Bd5#, Rd4 Re8+ or Rxb4 Bd5#). So better only `expect "pv d5e6 c8d8"` is used

**Comment by vondele** [comment]
fixed, thanks for the careful review.

**Comment by locutus2** [comment]
@vondele
Are this tests also done for a PR? Because for your PR all tests passes but i started the instrumented.sh script locally on master and it hangs for the test from line 187-191 because it only delivers the pv d6c7 so our test `expect "pv d6c7 * f7f5" `doesn't match so we should only use pv d6c7. Interestingly it not fails on some way but for me it simply give no output anymore and blocks. But using `expect "pv d6c7 "` completes succesful with 'instrumented testing OK'.

here the output i get:
```
position fen 8/5R2/2K1P3/4k3/8/b1PPpp1B/5p2/8 w - -
go mate 2
info string NNUE evaluation using nn-ae6a388e4a1a.nnue
info string NNUE evaluation using nn-baff1ede1f90.nnue
info depth 1 seldepth 7 multipv 1 score cp 280 wdl 1000 0 0 nodes 41 nps 41000 hashfull 0 tbhits 0 time 1 pv f7f5 e5e6 f5f3 e6e5 f3e3 e5f4
info depth 2 seldepth 7 multipv 1 score cp 280 wdl 1000 0 0 nodes 73 nps 73000 hashfull 0 tbhits 0 time 1 pv f7f5 e5e6 f5f3 e6e5 f3e3 e5f4
info depth 3 seldepth 7 multipv 1 score cp 280 wdl 1000 0 0 nodes 102 nps 102000 hashfull 0 tbhits 0 time 1 pv f7f5 e5e6 f5f3 e6e5 f3e3 e5f4
info depth 4 seldepth 7 multipv 1 score cp 280 wdl 1000 0 0 nodes 136 nps 136000 hashfull 0 tbhits 0 time 1 pv f7f5 e5e6 f5f3 e6e5 f3e3 e5f4
info depth 5 seldepth 7 multipv 1 score cp 280 wdl 1000 0 0 nodes 172 nps 172000 hashfull 0 tbhits 0 time 1 pv f7f5 e5e6 f5f3 e6e5 f3e3 e5f4
info depth 6 seldepth 7 multipv 1 score cp 280 wdl 1000 0 0 nodes 215 nps 215000 hashfull 0 tbhits 0 time 1 pv f7f5 e5e6 f5f3 e6e5 f3e3 e5f4
info depth 7 seldepth 7 multipv 1 score mate 2 wdl 1000 0 0 nodes 384 nps 192000 hashfull 0 tbhits 0 time 2 pv c6d7
bestmove c6d7
```

**Comment by locutus2** [comment]
@Disservin @vondele 
I see but then its the question how this passes because my local output doesn't match this test:
```
send "ucinewgame\n"
 send "position fen 8/5R2/2K1P3/4k3/8/b1PPpp1B/5p2/8 w - -\n"
 send "go mate 2\n"
 expect "score mate 2 * pv c6d7 * f7f5"
 expect "bestmove c6d7"
```

**Comment by vondele** [comment]
If the output is not matched, it will timeout (about 4min) which should result in a failure.

**Comment by Disservin** [comment]
Btw now that I think about it..
https://github.com/official-stockfish/Stockfish/blob/12524dd2baa19ef8a8412dc4022985776099554f/tests/instrumented.sh#L15

This isn't perhaps the best way as running the script will change something on the users system... it should better be a step inside the ci file

**Comment by vondele** [comment]
> This isn't perhaps the best way as running the script will change something on the users system... it should better be a step inside the ci file.

I agree, this belongs outside of the test file (but different PR please).

Now, it seems we have a problem with the return code of the script, need to understand:
```
info depth 7 seldepth 7 multipv 1 score mate 2 wdl 1000 0 0 nodes 384 nps 384000 hashfull 0 tbhits 0 time 1 pv c6d7
bestmove c6d7
timeout
instrumented testing failed on line 290
prompt $ echo $?
0
```

**Comment by Disservin** [comment]
> I agree, this belongs outside of the test file (but different PR please).

Ok, added it to a new PR, I was just thinking that it will require some rebasing when merged locally, though that should be easily resolvable :D

**Comment by vondele** [comment]
Ok, meanwhile, I don't understand why our CI is not failing on this PR. 

Locally it does. This is now the output, seems like somehow expect says in spawns valgrind+stockfish, but this doesn't happen (i.e. no further output):

image

**Comment by vondele** [comment]
So, summarizing the work on this PR here. I believe the added tests are now correct. 
However, in the process it is discovered that the CI actually doesn't run correctly, i.e. in the actions the test is effectively not run. It is specific to running it in the actions the same test locally seems to work. In CI we have this debug output:

```
 spawn ./stockfish
parent: waiting for sync byte
parent: telling child to go ahead
parent: now unsynchronized from child
spawn: returns {3784}

expect: does "" (spawn_id exp3) match glob pattern "Stockfish"? no
expect: read eof
expect: set expect_out(spawn_id) "exp0"
expect: set expect_out(buffer) ""
instrumented testing failed on line 296
```
compared to locally:
```
spawn ./stockfish
parent: waiting for sync byte
parent: telling child to go ahead
parent: now unsynchronized from child
spawn: returns {16146}

expect: does "" (spawn_id exp4) match glob pattern "Stockfish"? no
Stockfish dev-20240413-c55ae376 by the Stockfish developers (see AUTHORS file)
expect: does "Stockfish dev-20240413-c55ae376 by the Stockfish developers (see AUTHORS file)\r\n" (spawn_id exp4) match glob pattern "Stockfish"? yes
expect: set expect_out(0,string) "Stockfish"
expect: set expect_out(spawn_id) "exp4"
expect: set expect_out(buffer) "Stockfish"
send: sending "uci\n" to { exp4 }
...
```

My interpretation of this is that in CI expect spawns stockfish but it (or whatever pipe that connects expect to stockfish) closes on startup, leading to eof. While locally there is no issue. An additional tests shows that expect can spawn things (e.g. using `cat` instead of `stockfish` works) also in CI.

I propose to merge the PR in the current state as the issue under the actions was pre-existing, and local testing is improved. However, the action issue needs debugging & fixing, as right now the actions test less than they could and should.

**Pull request closed without merging**
