### PR TITLE
In Material::probe() search for scalingFunction last (II)

### PR DESCRIPTION
**Pull request by ceebo**
If we find a specialised evaluation function in Material::probe() then
we return immediately. This is justified because evaluation will not
use any of the other values in Material::Entry.

However, if we find a specialised scalingFunction then imbalance will be
used in evaluation and the only reason it has a well-defined value is
because we memset the Material::Entry to zero near the start of probe.

Search for a scalingFunction last to prevent this behaviour. This also
means that we now calculate factor[] for material combinations with a
specialised scalingFunctions. Previously this was not the case.

Tested at STC with SPRT(-3,1) bounds:

LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 73551 W: 13277 L: 13246 D: 47028

Bench: 5670983

### CODE REVIEW

**Comment by ceebo** [comment]
I wrote a new commit message this time to correct my claim that we were accessing information from older material entries. Since I realised this fact my enthusiasm for the patch decreased quite a lot and I am not that keen on running a >100,000 game test for this at LTC.

So how to proceed from here? Forget about this patch, commit now or run at LTC?

**Comment by MichaelB7** [comment]
I think you answered your own question.  Unless someone else has enthusiasm for this patch , I would pass.

**Comment by joergoster** [comment]
@ceebo It seems you're trying to fix two 'shortcomings' at once. Why not testing the change of the imbalance eval alone? See https://github.com/joergoster/Stockfish/commit/685503e052c047b086858503b6282c2bccb8e423

Your second change, moving the 'zero or one pawn' section further up, should be run as a standard [0, 4] or [0, 5] test, imho.

**Comment by ceebo** [comment]
The LTC failed so I'm closing this.

@joergoster If you want to try your version then give it a go. Probably I was silly in moving the factor stuff also.

**Pull request closed without merging**
