### PR TITLE
Retire CheckInfo

### PR DESCRIPTION
**Pull request by mcostalba**
Move its content directly under StateInfo.

No functional change.

### CODE REVIEW

**Comment by snicolet** [comment]
No slowdown observed on my system:

• master:
Total time (ms) : 99929
Nodes searched  : 151984969
Nodes/second    : 1520929

• patch:
Total time (ms) : 99625
Nodes searched  : 151984969
Nodes/second    : 1525570

**Comment by mstembera** [comment]
Looks good here.
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    648514    650551    -2037     
    StDev   249715    250817    4910      

p-value: 0.661
speedup: 0.003
```

**Comment by lucasart** [comment]
No speed difference on my machine. 64-bit bmi2, PGO compiles:
```
$ ./pyshbench ../Stockfish/test ../Stockfish/master 20
run base     test     diff
1   2751653  2757042  5389
2   1732823  1724333  -8490
3   2763537  2763537  0
4   2744144  2758123  13979
5   2759204  2759204  0
6   2745214  2752729  7515
7   2762452  2764622  2170
8   2757042  2746285  -10757
9   1726871  1718439  -8432
10  2759204  2758123  -1081
11  2759204  2765709  6505
12  2763537  2762452  -1085
13  1734531  1712169  -22362
14  2628353  2630317  1964
15  2762452  2758123  -4329
16  1729417  1721381  -8036
17  2757042  2761369  4327
18  1735387  1720540  -14847
19  2761369  2763537  2168
20  2761369  2754884  -6485

base = 2494740 +/- 201148
test = 2492645 +/- 201148
diff = -2094 +/- 3727

speedup = -0.0008
P(speedup > 0) = 0.1354
```

**Comment by mcostalba** [comment]
@snicolet @mstembera @lucasart Thanks for testing!

Merged with 1ee2838214fcb

**Pull request closed without merging**
