### PR TITLE
Variables tuning

### PR DESCRIPTION
**Pull request by FauziAkram**
A combo of 3 successful tuning patches:
1) Shelter Weakness by Fauzi
2) Threats by Alain
3) Passed Pawns by Alain

STC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 51378 W: 11592 L: 11223 D: 28563

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 21631 W: 3888 L: 3661 D: 14082

### CODE REVIEW

**Comment by FauziAkram** [comment]
Thank you all, for all the wonderful congratulations that I have received.
Unfortunately I had to rebase the patch to the current master, so all the comments was lost, but I keep them in my heart :)

**Comment by Stefano80** [comment]
Then congrats again!

**Comment by Vizvezdenec** [comment]
yeah, congrats again (:

**Comment by snicolet** [comment]
That is sometimes the problem with git rebasing and rewriting history: you lose the congratulations in the comments... If you want to keep them in order to warm you up again in 15 years from now ("these were the good old days, when Stockfish was developed by humans"), you can also make a new branch and rebase in that new branch.

Congrats :-)

**Comment by snicolet** [comment]
Merged via https://github.com/official-stockfish/Stockfish/commit/917fe69f84ffcc53783e1ada41833684dc8a2970.

**Comment by DamasClasicas** [comment]
Congratulations Fauzi! 

The road to SF10 has started well. Keep the good work!

**Pull request closed without merging**
