### PR TITLE
Update movegen.h

### PR DESCRIPTION
**Pull request by Cooffe**

### CODE REVIEW

**Comment by mcostalba** [comment]
Sorry, care to explain what it means this PR? Thanks.

**Comment by Cooffe** [comment]
Iam sorry  Mr.mcostalba

Have worked out. Not only should the assessment of the board be assessed
And the activation of the mirror work with the property of Herzelite and Fractal

Sorry if there was something wrong

**Comment by lantonov** [comment]
@Cooffe 
??????????

**Comment by syzygy1** [comment]
I suspect Cooffe is really Cofveve :-)

**Pull request closed without merging**
