### PR TITLE
Update WDL model for current SF

### PR DESCRIPTION
**Pull request by vondele**
This updates the WDL model based on the LTC statistics for the two weeks (3M games).

for old results see:

No functional change.

### CODE REVIEW

**Comment by vondele** [comment]
model:
Figure_4
data:
Figure_3
parameters a,b:
Figure_2
fit for win rate:
Figure_1

**Comment by dubslow** [comment]
If you mean the last two weeks of fishtest, then such data is polluted by the timeloss problem, and in that case this data may not be representative

**Comment by vondele** [comment]
I think the 'time loss problem' is visible as some of the noise near negative evals in the last figure. It hardly affects the shape of the red fit curve, so I think this is more or less OK. The trend in the parameters (a,b) is also as observed in the typical tournaments (large evals needed to have 50% win chance).

**Comment by dubslow** [comment]
Mmmm. I guess my follow up comment would then be "there's no rush, this can wait a few weeks to get better data", altho you've convinced me that at least it's not too far off

**Pull request closed without merging**
