### PR TITLE
Simplify Stat Score Reset - Bench:  3251357

### PR DESCRIPTION
**Pull request by VoyagerOne**
Simplify Stat Score Reset

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 14926 W: 3353 L: 3218 D: 8355
http://tests.stockfishchess.org/tests/view/5ccc567a0ebc5925cf03cf10

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 49153 W: 8471 L: 8397 D: 32285
http://tests.stockfishchess.org/tests/view/5ccc5aed0ebc5925cf03d076

Bench:  3251357

### CODE REVIEW

**Comment by VoyagerOne** [comment]
Note:  Do we need to extend the ss stack for this?

**Comment by joergoster** [comment]
@VoyagerOne Now you must memset up to ss+4 at the beginning of Thread::search().
`  std::memset(ss-7, 0, 12 * sizeof(Stack));`

And yes, I think you must also extend the size of stack[].

I'm still wondering how and why this patch works, though.
Do you happen to know if it has ever been tried to reset ALL statScores between the iterations?

@mcostalba Maybe this https://github.com/official-stockfish/Stockfish/pull/2111 is worth another consideration? ;-)

**Comment by VoyagerOne** [comment]
@joergoster originally it was ss->statScore=0.  Resetting at the grandchild proved to be Elo gainer.

**Comment by Vizvezdenec** [comment]
It was 
ss->statScore=0
into 
ss+1->statScore=0
into 
ss+2->statScore=0
and now into ss+4.
First 2 passed [0;4] with STC + LTC pretty cleanly soon after sf9 release.
Looking at failing appveyor and travis you definitely need some stuff done with stack and then rerun :)

**Comment by joergoster** [comment]
@VoyagerOne @Vizvezdenec Thanks. Resetting statScore with `ss->statScore = 0` when arriving at a new node seems the most logical, at first glance. I will take a closer look.

**Comment by VoyagerOne** [comment]
@vondele 
Are you able to provide some insight on this patch?  How do I go about extending the stack?

**Comment by vondele** [comment]
@VoyagerOne I need the following patch to have this PR pass testing under valgrind:

```diff
diff --git a/src/search.cpp b/src/search.cpp
index 36e73a09c..6f071e294 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -281,7 +281,7 @@ void Thread::search() {
   // The former is needed to allow update_continuation_histories(ss-1, ...),
   // which accesses its argument at ss-6, also near the root.
   // The latter is needed for statScores and killer initialization.
-  Stack stack[MAX_PLY+10], *ss = stack+7;
+  Stack stack[MAX_PLY+12], *ss = stack+7;
   Move  pv[MAX_PLY+1];
   Value bestValue, alpha, beta, delta;
   Move  lastBestMove = MOVE_NONE;
@@ -594,10 +594,8 @@ namespace {
     // starts with statScore = 0. Later grandchildren start with the last calculated
     // statScore of the previous grandchild. This influences the reduction rules in
     // LMR which are based on the statScore of parent position.
-       if (rootNode)
-               (ss + 4)->statScore = 0;
-       else
-               (ss + 2)->statScore = 0;
+    (ss + 2)->statScore = 0;
+    (ss + 4)->statScore = 0;
 
     // Step 4. Transposition table lookup. We don't want the score of a partial
     // search to overwrite a previous full search TT value, so we use a different
```

**Comment by VoyagerOne** [comment]
@vondele 
Thanks!

**Pull request closed without merging**
