### PR TITLE
Update default net to nn-c38c3d8d3920.nnue

### PR DESCRIPTION
**Pull request by linrock**
This was a later epoch from the same experiment that led to the previous master net.
After training, it was prepared the same way:

1. greedy permuting L1 weights with https://github.com/official-stockfish/Stockfish/pull/4620
2. leb128 compression with https://github.com/glinscott/nnue-pytorch/pull/251
3. greedy 2- and 3- cycle permuting with https://github.com/official-stockfish/Stockfish/pull/4640

Local elo at 25k nodes per move (vs. L1-1536 nn-fdc1d0fe6455.nnue):
nn-epoch739.nnue : 20.2 +/- 1.7

Passed STC:
https://tests.stockfishchess.org/tests/view/64a050b33ee09aa549c4e4c8
LLR: 2.95 (-2.94,2.94) <0.00,2.00>
Total: 195552 W: 49977 L: 49430 D: 96145
Ptnml(0-2): 556, 22775, 50607, 23242, 596

Passed LTC:
https://tests.stockfishchess.org/tests/view/64a127bd3ee09aa549c4f60c
LLR: 2.94 (-2.94,2.94) <0.50,2.50>
Total: 235452 W: 60327 L: 59609 D: 115516
Ptnml(0-2): 119, 25173, 66426, 25887, 121

bench 2427629

### CODE REVIEW

**Comment by vondele** [comment]
hmm for whatever reason the CI is failing again on MacOS.

I wonder if something is non-standard on our regexp that it fails to match `bench 2427629` on MacOS ?

**Comment by Sopel97** [comment]
have you tried https://github.com/glinscott/nnue-pytorch/pull/254 ?

**Comment by Sopel97** [comment]
have you tried skipping the first step and only relying on "greedy 2- and 3- cycle permuting with https://github.com/official-stockfish/Stockfish/pull/4640" ?

**Comment by linrock** [comment]
> have you tried skipping the first step and only relying on "greedy 2- and 3- cycle permuting with https://github.com/official-stockfish/Stockfish/pull/4640" ?

i have, it completely froze up on a few occasions and i don't know why. meanwhile, i haven't run into issues running the 3 steps sequentially other than it being resource intensive and taking about an hour per net.

i can give https://github.com/glinscott/nnue-pytorch/pull/254 a try later.

**Comment by ppigazzini** [comment]
> hmm for whatever reason the CI is failing again on MacOS.
> 
> I wonder if something is non-standard on our regexp that it fails to match `bench 2427629` on MacOS ?

Ubuntu extract the same bench

**Comment by vondele** [comment]
yeah, we discussing on discord. 
It is the order of commits as extracted with the loop that is unexpected

**Comment by ppigazzini** [comment]
In local test with this branch the script works fine:
bash --noprofile --norc -eo pipefail ../bench.sh
benchref=2427629
From commit: 9f4cd3bd547a3d337c1789a5a18e86cf377cbc5f
Reference bench: 2427629

**Comment by vondele** [comment]
it might be related to how this branch is merged in master during the CI ?

**Comment by vondele** [comment]
look at the additional output in https://github.com/official-stockfish/Stockfish/actions/runs/5478194778/jobs/9978344031 
(under Extract bench .... step)

**Pull request closed without merging**
