### PR TITLE
Move some code into threads

### PR DESCRIPTION
**Pull request by protonspring**
This is a non-functional code style change that moves some pure thread code into the threads class.

It is a bit more code, but it makes search.cpp cleaner and easier to read by hiding some thread specific functionality.

STC (SMP)
LLR: 2.93 (-2.94,2.94) {-1.50,0.50}
Total: 75896 W: 12073 L: 12026 D: 51797
Ptnml(0-2): 828, 8224, 19872, 8121, 903 
https://tests.stockfishchess.org/tests/view/5ed492e8f29b40b0fc95a74c

### CODE REVIEW

**Comment by vondele** [comment]
I'm wondering about this `th->bestMoveChanges = 0;` statement. It is in the same location as master, but it is not quite logical. Can't it be moved to e.g. `Thread::search()` or `ThreadPool::start_thinking()` (the latter place seems most logical for anything that is an atomic in Thread).

**Comment by xoto10** [comment]
Should we do a threaded non-regression test? I don't expect it to be a problem, but it would be embarrassing if a threading code tidy up caused a regression.

**Comment by vondele** [comment]
@xoto10 the test was threaded, it is not clear from the commit message.

**Comment by vondele** [comment]
@protonspring can you have a look at the bestMoveChanges I made before. Now that the code is refactored, it is a good moment to fix it.

**Comment by protonspring** [comment]
I haven't looked much here, but on first glance, I would set bestMoveChanges to 0 on search, and add another method for ThreadPool::get_bestMoveChanges which gets the total for all threads in the pool.
This would further simplify search.

**Comment by vondele** [comment]
Thanks!

**Pull request closed without merging**
