### PR TITLE
Stat-Eval Simplification Bench: 4457440

### PR DESCRIPTION
**Pull request by VoyagerOne**
Don't modify Eval with search stats at ttHits

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 28344 W: 6148 L: 6040 D: 16156
http://tests.stockfishchess.org/tests/view/5b7d6b4e0ebc5902bdbb1914

LTC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 41084 W: 6769 L: 6680 D: 27635
http://tests.stockfishchess.org/tests/view/5b7d7f5b0ebc5902bdbb1b85

Bench:  4457440

### CODE REVIEW

**Comment by locutus2** [comment]
Congrats!

**Comment by snicolet** [comment]
Approved.

I am off and without computer access  for a few days (till Tuesday), so I will not be able to commit anything on the master branch during that period.

May somebody (Stefan?) could make a temporary branch in the mean time with the approved functional changes so that people wanting to test against the latest functional version get a chance to do so? :-)

**Comment by snicolet** [comment]
Merged via 3ac3b68540e93770e5a806196537c0e9a2d81a67, thanks!

**Comment by VoyagerOne** [comment]
@snicolet 
Thank you!

**Pull request closed without merging**
