### PR TITLE
Makefile bug fix

### PR DESCRIPTION
**Pull request by mstembera**
Properly detect in the Makefile which binary mingw should use on various Linux setups.

### CODE REVIEW

**Comment by KassiasGrandiel** [comment]
Does this version confuse fishtest system?  If so we can't commit it.

**Comment by zamar** [comment]
Unfortunately I think the problem is that the name of mingw compiler varies lately between distributions.

So far we have in this patch:
- x86_64-w64-mingw32-g++
- x86_64-w64-mingw32-g++-posix

However fishtest uses:
- i686-w64-mingw32-c++
- x86_64-w64-mingw32-c++

Until we have more standardization along names, I see it very difficult to officially support mingw on Linux in Makefile.

**Comment by mcostalba** [comment]
The only sound way is to use a Makefile variable that user sets from
outside (or on the make command line)

**Comment by mstembera** [comment]
I have updated the pull request w/ a version I hope should work on all Linux distros.  Also scheduled a fishtest just to make sure it compiles there
http://tests.stockfishchess.org/tests/view/565aee860ebc5902cdc086d5
and asked people to verify here
https://groups.google.com/forum/#!topic/fishcooking/5qB4PFDkyrg

**Comment by zamar** [comment]
People have reported it working on various Linux distros in Fishcooking. So it looks like committable for me.

However the fishtest run was inconclusive...

**Comment by zamar** [comment]
Sorry, you had set the games to 1, so the fishtest run was in fact successful...

I'll commit this next weekend unless someone objects.

**Comment by MichaelB7** [comment]
As long as you are updating the makefile, why not use the -j flag in your
makefile?

As an example two precisely placed -j flags would dramatically cut your
compile time:
================================

profile-build:

$(MAKE) ARCH=$(ARCH) COMP=$(COMP) config-sanity

@echo ""

@echo "Step 0/4. Preparing for profile build."

$(MAKE) ARCH=$(ARCH) COMP=$(COMP) $(profile_prepare)

@echo ""

@echo "Step 1/4. Building executable for benchmark ..."

@touch *.cpp *.h syzygy/*.cpp syzygy/*.h

$(MAKE) *-j *ARCH=$(ARCH) COMP=$(COMP) $(profile_make)

@echo ""

@echo "Step 2/4. Running benchmark for pgo-build ..."

$(PGOBENCH) > /dev/null

@echo ""

@echo "Step 3/4. Building final executable ..."

@touch *.cpp *.h syzygy/*.cpp syzygy/*.h

$(MAKE)*-j* ARCH=$(ARCH) COMP=$(COMP) $(profile_use)

@echo ""

@echo "Step 4/4. Deleting profile data ..."

$(MAKE) ARCH=$(ARCH) COMP=$(COMP) $(profile_clean)


Mike Byrne

**Comment by mstembera** [comment]
We generally try not mixing multiple functionally unrelated changes in one pull request.  I encourage you to create a separate pull request with your changes.

**Pull request closed without merging**
