### PR TITLE
more best thread cases

### PR DESCRIPTION
**Pull request by jcalovski**
Build on best thread selection.

STC 7 threads:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 26881 W: 4161 L: 3941 D: 18779
http://tests.stockfishchess.org/tests/view/58667a830ebc5903140c632f

LTC 7 threads:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 22988 W: 2767 L: 2583 D: 17638
http://tests.stockfishchess.org/tests/view/586722690ebc5903140c636d

### CODE REVIEW

**Comment by joergoster** [comment]
Congrats!

**Comment by lp--** [comment]
Congrats!

**Comment by VoyagerOne** [comment]
Congrats...managed to get an elo gain before the end of the year.

**Comment by locutus2** [comment]
Congrats too!
And happy new year to all.

**Comment by mstembera** [comment]
Congrats!

**Comment by lucasart** [comment]
Nice! But I wonder why you exclude the case where depth and score are both equal. If you include it, the condition is simply:
```
if (th->completedDepth >= bestThread->completedDepth
    && th->rootMoves[0].score >= bestThread->rootMoves[0].score)
```

**Comment by jcalovski** [comment]
There has to be some criteria to justify choosing best thread A over best thread B where score and depth are equal otherwise we nilly willy just alternative between these threads with neither being an "improvement" over the other.

**Comment by mcostalba** [comment]
Merged with 1052ce74f65479e5d5

Slightly edited for readibility. Moreover I think the condition with same score but higher depth makes no sense. I invite you at submit a semplification withoth this condition. In current form someting like:
```

           Depth depthDiff = th->completedDepth - bestThread->completedDepth;
           Value scoreDiff = th->rootMoves[0].score - bestThread->rootMoves[0].score;
 
-          if (   (depthDiff > 0 && scoreDiff >= 0)
-              || (scoreDiff > 0 && depthDiff >= 0))
+          if (scoreDiff > 0 && depthDiff >= 0)
               bestThread = th;

```

**Comment by snicolet** [comment]
Congratulations too!

**Comment by jcalovski** [comment]
thanks :)

**Comment by pb00068** [comment]
Congratulations also from my side!

>Moreover I think the condition with same score but higher depth makes no sense.

@mcostalba: older tests suggest that threads with higher skip-sizes deliver less quality but apart from that the logic of this patch makes sense to me: if 2 different pv's return the same score I would trust the one which was analyzed deeper.

**Comment by mcostalba** [comment]
@pb00068 I net the simplification would pass with SPRT[-3, 1] :-)

**Comment by pb00068** [comment]
Elberto launched the [test](http://tests.stockfishchess.org/tests/view/586a4d090ebc5903140c64b2) and it looks like you're right ;-)

**Comment by jcalovski** [comment]
We all got simplification fever :)

**Pull request closed without merging**
