### PR TITLE
Code style in Razoring and ProbCut

### PR DESCRIPTION
**Pull request by joergoster**
Looks more in style with other code now.

No functional change.

### CODE REVIEW

**Comment by joergoster** [comment]
It also seems to take less CPU cycles when running bench.
Measured with @mcostalba's perf command (see forum).
sudo perf stat -r 10 -a -B -e cycles:u ./stockfish bench > /dev/null

**master**
```
 Performance counter stats for 'system wide' (10 runs):

    14.937.525.406      cycles:u                        ( +-  0,13% )

       3,587316441 seconds time elapsed                 ( +-  0,11% )
```

**patch**
```
 Performance counter stats for 'system wide' (10 runs):

    14.779.092.636      cycles:u                        ( +-  0,15% )

       3,581124105 seconds time elapsed                 ( +-  0,14% )
```

**Comment by tomtor** [comment]
You restored the original razor flow layout.

The reason I changed it is that in my version only a single test is specified for depth == 1 and in this new/original version there is a test for <= 2 * ONE_PLY and a test for == ONE_PLY.

If the compiler optimization results in equivalent of even faster binary code then that's great because I agree that the original form is easier on the eyes.

**Comment by syzygy1** [comment]
I think `depth <= ONE_PLY` instead of `depth == ONE_PLY` would allow the compiler to do a single compare of depth with 2 * ONE_PLY (since depth <= ONE_PLY is equivalent to depth < 2 * ONE_PLY given that ONE_PLY == 1).

Looking at the assembler output is easier than measuring the difference.

**Comment by joergoster** [comment]
Here the perf numbers for 20 concurrent bench runs up to depth 17.

**master**
```
   168.041.509.612    cycles:u                                         ( +-  0,50% )  (100,00%)
   155.123.182.443    instructions:u       # 0,92  insns per cycle     ( +-  0,41% )  (100,00%)

      20,729556393 seconds time elapsed                                ( +-  0,05% )
```
**patch**
```
   167.829.078.969    cycles:u                                         ( +-  0,43% )  (100,00%)
   154.920.417.965    instructions:u       # 0,92  insns per cycle     ( +-  0,33% )  (100,00%)

      20,675620747 seconds time elapsed                                ( +-  0,06% )
```

Very close in performance, with only a tiny advantage for the patch. ;-)

**Comment by lantonov** [comment]
If the percentages are SD, the test has significance P < 0.208
With percentages as SE, significance is P < 0.388
In either case the difference is not significant

**Comment by mcostalba** [comment]
@joergoster thanks for testing! Now it is clear that concurrent bench runs up to depth 17 is not the way to go: you had a bigger error on cycles than on time!

**Comment by joergoster** [comment]
@mcostalba Here are 2 standalone runs.
sudo perf stat -r 20 -a -B -e cycles:u,instructions:u ./stockfish bench 64 1 17 > /dev/null

**master**
```
85.364.761.065   cycles:u                                       ( +-  0,82% )  (100,00%)
78.529.845.943   instructions:u     # 0,92  insns per cycle     ( +-  0,64% )

20,685480237 seconds time elapsed                               ( +-  0,07% )
```

**patch**
```
83.930.776.014   cycles:u                                        ( +-  0,10% )  (100,00%)
77.661.042.407   instructions:u      # 0,93  insns per cycle     ( +-  0,06% )

20,632525369 seconds time elapsed                                ( +-  0,08% )
```

**Comment by joergoster** [comment]
And now 2 much shorter runs.
sudo perf stat -r 5 -a -B -e cycles:u,instructions:u ./stockfish bench 8 1 11 > /dev/null

**master**
```
6.032.454.550   cycles:u                                         ( +-  1,84% )  (100,00%)
5.450.281.795   instructions:u       # 0,90  insns per cycle     ( +-  1,39% )

1,401358747 seconds time elapsed                                 ( +-  0,12% )
```
**patch**
```
5.811.623.626   cycles:u                                         ( +-  0,34% )  (100,00%)
5.331.416.419   instructions:u       # 0,92  insns per cycle     ( +-  0,14% )

1,396839156 seconds time elapsed                                 ( +-  0,10% )
```

**Comment by snicolet** [comment]
> If the percentages are SD, the test has significance P < 0.208
With percentages as SE, significance is P < 0.388
In either case the difference is not significant

@lantonov What are SD and SE? :-)

**Comment by lantonov** [comment]
SD - standard deviation
SE - standard error

**Comment by snicolet** [comment]
@lantonov thanks!

**Comment by snicolet** [comment]
@joergoster Merged via 43682d08f7a85a997ff71fdb68ee6392c5d49b21, congrats!

**Comment by lantonov** [comment]
@snicolet  You are welcome
When these percentages are like 0.04%, 0.05%, 0.06% as in some measurements of cycles and instructions done by Marco, even very small differences become significant

**Pull request closed without merging**
