### PR TITLE
Remove another unnecessary Search::Stack field

### PR DESCRIPTION
**Pull request by DU-jdto**
Removed reduction from the Search::Stack structure and replaced it with a local variable.

### CODE REVIEW

**Comment by lucasart** [comment]
Makes sense. The only reason to have certain things on Search::Stack is to access them across recursion, like to read the parent node value, for example.

**Comment by hxim** [comment]
Nice. But why rename variable to "r"? I think longer name "reduction" is better.

**Comment by mcostalba** [comment]
Yes, please leave 'reduction' instead of 'r'. Thanks.

**Comment by mstembera** [comment]
Nice!

**Comment by DU-jdto** [comment]
I used 'r' because the name 'reduction' conflicts with the name of the function being called. I can use a different name if you'd like, though.

**Comment by mcostalba** [comment]
Ok, I see.

**Comment by zamar** [comment]
Well, for example even just 'red' would be more informative than just 'r'.

Can you please update pull?

**Comment by DU-jdto** [comment]
Done. I'm not that familiar with how this works, will pulling this still only result in a single commit being added to the official-stockfish master?

**Pull request closed without merging**
