### PR TITLE
Rename stages

### PR DESCRIPTION
**Pull request by mcostalba**
Hopefully more clear.

No functional change.

### CODE REVIEW

**Comment by mstembera** [comment]
This is nice!

**Comment by zamar** [comment]
Approved.

One missing space, please fix while phushing:
QSEARCH_NO_CHECKS,QCAPTURES_2,

**Comment by lucasart** [comment]
Just one change I would make:
```
CHECKS -> QUIET_CHECKS
```
to make it more clear (these are quiet checks from the QS, generated separately, not checks resulting from a capture).

**Comment by mcostalba** [comment]
Yes, it would be nice, unfortunately it would create a conflict with this:

endMoves = generate<QUIET_CHECKS>(pos, moves);


Actually I had to give up a couple of good names due to conflicts...

**Comment by mcostalba** [comment]
Thanks. Updated.

**Comment by glinscott** [comment]
Great, looks good!

**Comment by Rocky640** [comment]
I just learned today that starting in c++11 you can use the keyword "class" and write
enum class Stages {MAIN_SEARCH,....};
This forces to use Stages::MAIN_SEARCH instead of simply MAIN_SEARCH

May I suggest to change
enum GenType {
  M_CAPTURES,
  M_QUIETS,
  M_QUIET_CHECKS,
  M_EVASIONS,
  M_NON_EVASIONS,
  M_LEGAL
};
This way, you will have more good names for the Stages ;)

**Comment by mcostalba** [comment]
Yes,  of course you can define enum values inside a struct,  one for each
stage kind, and you even don't need c++11 for this. But try to write the
patch yourself, you will see that fully qualifying the names yields to a
verbose and less readable code.

**Comment by mcostalba** [comment]
Another option is s to wrap a namespaces around the enum,  but also in this
case you need full qualification down in the code,  and I don't
like it in this case.

**Comment by Rocky640** [comment]
I fully agree, this is too verbose.
But how about just renaming the 
enum GenType {  M_CAPTURES,  M_QUIETS,...};

**Comment by mcostalba** [comment]
I still prefer current proposal, I don't like a lot
fixed prefixes.

**Pull request merged**
