### PR TITLE
Bench 6072262

### PR DESCRIPTION
**Pull request by torfranz**
retire small bonus in passed pawn evaluation

STC: http://tests.stockfishchess.org/tests/view/5899824d0ebc59099759f3ee
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 33370 W: 6061 L: 5961 D: 21348

LTC: http://tests.stockfishchess.org/tests/view/5899e3820ebc59099759f415
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 36206 W: 4664 L: 4563 D: 26979

Bench: 6072262

### CODE REVIEW

**Comment by snicolet** [comment]
Congrats too!

**Comment by DamasClasicas** [comment]
Congratulations Franz!!

**Comment by MichaelB7** [comment]
To me any change that changes bench should be tested as such - as a change and not s simplification.   We spend way too much of our limited resources on simplifications and not real ELO improvements. Just my $.02 I know others will disagree which is fine and what makes the world a beautiful place to be.

**Comment by zamar** [comment]
Approved. Will commit.

**Comment by Rocky640** [comment]
@zamar 

If we run the same -3, 1 test many times, it will eventually pass.
This was the case here, and some caution might be taken.

a) A similar simplification was tried not long ago (Dec 2016) and failed.
http://tests.stockfishchess.org/tests/view/584e456d0ebc5903140c5ab6

b) 2 more simplifications on that same bonus were committed after that: #938 and #950

c) And one significant change to passed pawn evaluation: #978

I think that after one failed removal, and 2 successive simplifications, if there was any strength in this bonus, it was washed away after each of those successive changes, and did not stand a big chance for the ultimate removal attempt.

I don't care much about this bonus, but maybe it would be appropriate to retest this #998 against the original unstoppable code before the first simplification #938 ?

**Comment by zamar** [comment]
@Rocky640: Point taken. 

However I feel that this extra bonus is ugly, so I'll remove it anyway. 

After committing feel free to submit a test restoring he original unstoppable code with the usual [0, 5] bounds.

**Pull request closed without merging**
