### PR TITLE
Evasion Pruning Tweak

### PR DESCRIPTION
**Pull request by VoyagerOne**
Use moveCount to decide when to prune for evasion pruning

STC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 24476 W: 4518 L: 4289 D: 15669

LTC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 18362 W: 2476 L: 2298 D: 13588

Bench:  6536884

### CODE REVIEW

**Comment by ianfab** [comment]
Shouldn't the move count be decremented instead of incremented for illegal moves, or am I missing something?

**Comment by VoyagerOne** [comment]
@ianfab 
It certainly should!
Thanks!

**Comment by snicolet** [comment]
@VoyagerOne 

1) Congrats! :-)

2) Since you are attempting simpler/more exact versions, I would suggest to increment moveCount only *after* verifying that the move is legal. This way, the patch would be more robust to changes in the move generator, if we ever decide to emit more/less illegal moves.

````C++

int moveCount = 0;

...

evasionPrunable =    InCheck
                 &&  moveCount > 1
                 &&  bestValue > VALUE_MATED_IN_MAX_PLY
                 && !pos.capture(move);

...

if (pos.legal(move))
    moveCount++;
else
    continue;
````

**Comment by VoyagerOne** [comment]
@snicolet 
I thought about that...but wanted to stay consistent the with the way we do moveCounting with our regular search.

**Comment by snicolet** [comment]
You don't have to stay consistent with buggy code :-)

**Comment by VoyagerOne** [comment]
@snicolet 
Your version maybe even "buggier" since you may severely underestimate the true legal moveCount.

**Comment by snicolet** [comment]
@VoyagerOne 

True :-) 
Seems like there is no reliable way in Stockfish search to know the number of legal moves in the move loop.

**Comment by mcostalba** [comment]
@VoyagerOne  no need to decrement moveCount if move is not legal because it is not used anymore after that point.

Morover this is qsearch and moveCount concept is quite blur because only a fraction of moves are tried. The most precise concept for that variable is to count the moves picked out of the movepicker. So no need to decrements, both practically and also logically.

**Comment by VoyagerOne** [comment]
@mcostalba 

Not sure if I understand your point.  Then why do we decrease it during our regular search? (Line 953)

**Comment by mcostalba** [comment]
@VoyagerOne sorry, my bad. I missed that we are inside a loop there :-)

**Pull request closed without merging**
