### PR TITLE
Function parameter cleanup

### PR DESCRIPTION
**Pull request by mstembera**
Minor cleanup of some function parameters.
No functional change.

### CODE REVIEW

**Comment by Nakel** [comment]
Perhaps evaluate_pieces can be renamed as judgingofpieces?

**Comment by mcostalba** [comment]
Please leave minattackers as is. It is easier for the compiler to inline a
const reference, Google for it, there is a vast literature on this subject.

M oreover passing a const value is not idiomatic because a copy of course
never changes the original value anyhow.

**Comment by mcostalba** [comment]
Finally clean up is the wrong word : I don't see any clean up in your
patch.

So please better specify what is the intent of the patch.

**Comment by mstembera** [comment]
It's my understanding that passing a fundamental type by reference doesn't make sense because the size of the reference is not smaller than the size of the type itself.   You therefore don't save anything in the copying process by using a reference.  You are correct that now the const can also be removed and I have updated the pull request.
Here is a run of fishbench confirming there is no speed regression.  Others can verify.
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    907954    908033    -79       
    StDev   234965    235522    5095      

p-value: 0.506
speedup: 0
```
I do see it simply as a cleanup.

**Comment by zamar** [comment]
I'm fine with either way...

Maybe I slightly prefer the current version of min_attackers().

@mstembera: It's not about copying a pointer vs. copying a value. A smart compiler will inline this function anyhow, in which case nothing gets copied. The point Marco was making that after you change, it becomes more difficult for compiler to inline the function, although I'd expect gcc to able to inline it anyhow...

**Comment by mstembera** [comment]
@Joona
You are correct.  gcc produces completely identical assembly for both versions.
So why are we using a reference?
If you still prefer it though I will update the patch.

**Comment by zamar** [comment]
I understand what you are saying and it kind of makes sense...

However the current status for this patch is:
- My stance: Neutral
- Marco's stance: Against

So unless some other comments come in, the patch in its current form can't be committed.

**Comment by mstembera** [comment]
@mcostalba
Marco, since the generated assembly is identical(which you can verify) that refutes your argument regarding any inlining issues.  Can you then please answer the question why we use a reference?
Thank you.

**Comment by mcostalba** [comment]
Ok for me. Assembly is the same because gcc is smart enough.

I'm fine with the patch.

**Comment by mstembera** [comment]
Cool thanks!
I also noticed that we don't need to include tt.h in benchmark.cpp so I updated this patch if that's ok.

**Comment by zamar** [comment]
OK. Marco seems to be fine with this patch.

So, approved.

**Comment by glinscott** [comment]
Looks good.

**Pull request closed without merging**
