### PR TITLE
Raise endgame PP and material values.

### PR DESCRIPTION
**Pull request by mbootsector**
STC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 136149 W: 25213 L: 24588 D: 86348

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 54637 W: 7533 L: 7238 D: 39866

Bench: 8881097

### CODE REVIEW

**Comment by joergoster** [comment]
Congrats, too!

**Comment by pb00068** [comment]
Impressive, congrats!

**Comment by Rocky640** [comment]
That was smart work !

Now we can probably simplify one dimension in `const Value Passed[][RANK_NB] = {`

Also, it I has been a while since a 60+0.05 SPSA tuning session was run.
Maybe one can do such a SPSA for endgame scores for pieces, Passed and the new LoosePiece bonus ?

**Comment by zamar** [comment]
Surprising that it worked!

As this is a simple parameter tweak, I'll commit this straight away...

**Pull request closed without merging**
