### PR TITLE
Simplify RookOnPawn (popcount -> bool)

### PR DESCRIPTION
**Pull request by protonspring**
This change is the same as master 95% of the time (for bench) and is much faster.

STC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 72004 W: 16050 L: 16028 D: 39926 
http://tests.stockfishchess.org/tests/view/5b5930a80ebc5902bdb898c8

STC (accidental 2nd STC)
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 11706 W: 2698 L: 2556 D: 6452 
http://tests.stockfishchess.org/tests/view/5b59fa850ebc5902bdb8b5f7

bench 4462700

### CODE REVIEW

**Comment by Stefano80** [comment]
I think this is a close call. In general, if one has two design options, the one which makes future changes easier should be preferred.

In this sense, if we will ever would like to change the implementation of our custom `popcount`, removing even one of those calls would make life easier later. In the end, I would see as a simplification. Maybe, it makes sense to remove some more `popcount` calls together and check whether this still passes sprt[-3, 1].

**Comment by protonspring** [comment]
I've tested most of them.  About 1/2 are either better or neutral, and other are much worse.  There are probably 2-3 more that I'll test.  I think it's a great idea to combine all of the ones that pass and see if they pass -3,1 by themselves.  I assume they will since some of them see much better (ps_hinder).

**Comment by goodkov** [comment]
http://tests.stockfishchess.org/tests/view/5b59fa850ebc5902bdb8b5f7
Not LTC
tc   10+0.1

**Comment by protonspring** [comment]
@goodkov You are right.  I'm not sure how I did that.  I submitted an LTC and will report.

**Comment by 31m059** [comment]
@protonspring I would recommend revising the pull request to indicate that both these results are STC.  Two STCs do provide more information (and higher confidence) than one, I think, but the current label of LTC is incorrect.

**Comment by Rocky640** [comment]
LTC had been completed
http://tests.stockfishchess.org/tests/view/5b5a9b840ebc5902bdb8cc12

**Comment by protonspring** [comment]
That took quite some time to pass, so I'm inclined to close this without commit.

**Comment by snicolet** [comment]
Closing without commit is fine with me.

**Pull request closed without merging**
