### PR TITLE
merge official/tune

### PR DESCRIPTION
**Pull request by Cooffe**
Building accumulated

### CODE REVIEW

**Comment by mcostalba** [comment]
I really see no reason to merge, I also see you give no reason, just pick **my** code verbatim and open a PR. Quite rude I'd say.

**Comment by Cooffe** [comment]
She followed these instructions
Every time I want to push the variables through my code
Some problems appear.

Do not hesitate to help me if you kindly
I have accumulations. And a bit complicated on github

thank you very much

**Comment by snicolet** [comment]
@Cooffe Do you know how to use git from a Terminal? 

Just asking to get an estimate of the level of the advices we should give you.

**Comment by Cooffe** [comment]
hi snicolet
I use GitHub Desktop

Build-side link to Visual Studio 2017

I tried to take the test to the test station, but it failed

**Comment by snicolet** [comment]
OK, you use GitHub desktop. I use it too, it is a nice client.

This doesn't answer my question:  
Do you know how to use git from a Terminal?

**Comment by Cooffe** [comment]
You mean the gate of the station /?
http: //tests.stockfishchess


Unfortunately, not

Sorry

**Comment by snicolet** [comment]
@Cooffe 

OK, so I will try to give you simple instructions with pictures :-) You are using GitHub Desktop, so I will use the screenshots from that program -- my pictures are from Macintosh, but if you are using Windows it should not be very different.

Suppose you are working on a current branch "my_tuning_branch". You now want to **merge the "tune" branch written by Marco on top of your current branch**. 

To do that:

1) write your code in "my_tuning_branch":
screen1

2) go to "Branch" menu in Github Desktop, and select "Merge into current branch":
screen2

3) in the small dialog window which appears, type "tune" to select the branch by Marco, then click "Merge into "my_tuning_branch""
screen3

4) After that, you should see a new commit in the history panel on the left:
screen4

You can then follow the instructions in https://github.com/glinscott/fishtest/wiki/Creating-my-first-test

Hope this helps,
Stéphane

**Comment by Cooffe** [comment]
Thank you my mighty

It was a beautiful, clear and simple explanation
But I still fear fallacies through
Work on git windows temporarily until I learn a better format
You have given me truthfully

**Comment by snicolet** [comment]
You're welcome :-)

**Pull request closed without merging**
