### PR TITLE
Small cleanups 02

### PR DESCRIPTION
**Pull request by vondele**
a PR to collect small cleanups

No functional change.

### CODE REVIEW

**Comment by protonspring** [comment]
bitboard.h, line 357 says we move "one step," but we also do NORTH+NORTH or SOUTH+SOUTH.  It could probably just say "moves a bitboard in the given direction."

**Comment by pb00068** [comment]
Strange that this PR as well as the commit now here on github shows Files changed: 0

**Comment by vondele** [comment]
@pb00068 yes, right now it is an empty PR, it will be filled as suggestions arrive

**Comment by Chess13234** [comment]
evaluate.h Tempo can be moved to enum Value and Eval::Tempo can be just called Tempo(for search.cpp/evaluate.cpp and potentially every file without using Eval:: namespace) since its a constant.

```
constexpr Value Tempo = Value(28); // Must be visible to search
```
Moved to types.h
```
enum Value : int {
  VALUE_ZERO      = 0,
  VALUE_DRAW      = 0,
  VALUE_KNOWN_WIN = 10000,
  VALUE_MATE      = 32000,
  VALUE_INFINITE  = 32001,
  VALUE_NONE      = 32002,
  Tempo = 28,

  VALUE_MATE_IN_MAX_PLY  =  VALUE_MATE - 2 * MAX_PLY,
  VALUE_MATED_IN_MAX_PLY = -VALUE_MATE + 2 * MAX_PLY,

  PawnValueMg   = 128,   PawnValueEg   = 213,
  KnightValueMg = 781,   KnightValueEg = 854,
  BishopValueMg = 825,   BishopValueEg = 915,
  RookValueMg   = 1276,  RookValueEg   = 1380,
  QueenValueMg  = 2538,  QueenValueEg  = 2682,

  MidgameLimit  = 15258, EndgameLimit  = 3915
};
```

**Comment by mstembera** [comment]
Simplify PieceValue[]
https://github.com/mstembera/Stockfish/commit/7409180677a482c5b2546a2a39d439e263a3db36

**Comment by Chess13234** [comment]
Replace razoring condition in search.cpp
 '&& depth <2' to 'depth==1', which more accurately reflects the condition(since depth 0 always returns qsearch).

**Comment by protonspring** [comment]
https://github.com/official-stockfish/Stockfish/pull/2555

**Comment by TerjeKir** [comment]
Line 1531 the comment about update_cont_history only mentions -1, -2 and -4, but it seems the code also uses -6?

**Comment by pb00068** [comment]
Search.cpp line 1442
`tte->save(posKey, value_to_tt(bestValue, ss->ply), pvHit, BOUND_LOWER,`

can be replaced with

`tte->save(posKey, value_to_tt(bestValue, ss->ply), false, BOUND_LOWER,`

Makes the code a bit more explicit IMO.

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp#L521
This should be redone in "normal" way - with extra constexpr in 
https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp#L129
I propose name "WeakQueenProtection"

**Comment by SamuraiDangyo** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/Makefile#L412

help recipe  is in .PHONY 2 times

**Comment by protonspring** [comment]
Personally, instead of "map_to_queenside," I would prefer "distance_from_edge" or similar.  This would be a more generic name and could be used in other places (i.e., with ranks) with more clarity.

**Comment by vondele** [comment]
@protonspring not so sure about renaming to distance_from_edge, right now it is file specific. Maybe if you have a use case for the more generic case (that you want to template on Rank and File?)...

**Comment by protonspring** [comment]
> @protonspring not so sure about renaming to distance_from_edge, right now it is file specific. Maybe if you have a use case for the more generic case (that you want to template on Rank and File?)...

Yes.  I'm currently playing with PushToEdges, PushToCorners, etc.  it would be very convenient if map_to_queenside could be used as distance_from edge.
Example: http://tests.stockfishchess.org/tests/view/5e5ae744afe6254521f2ff2f

**Comment by vondele** [comment]
but something like `map_to_queenside(File(rank_of(s)))` is a bit ugly IMO. So you could come up with a templated version of 'distance_to_edge' ? Anyway, I propose you include a prototype implementation in one of those upcoming patches.

**Comment by protonspring** [comment]
Will do. Looks like i will have a patch for equations for all the arrays in
endgame, so i will include it in there.
-- 
Michael T. Whiteley
mobile: 801.707.6886

**Comment by vondele** [comment]
Thanks all for the contributions.

**Pull request closed without merging**
