### PR TITLE
Enable syzygy in the matetrack action

### PR DESCRIPTION
**Pull request by vondele**
now checks correctness of PV lines with TB score.

uses 3-4-5 man table bases, downloaded from lichess, which are cached with the appropriate action.

No functional change

### CODE REVIEW

**Comment by robertnurnberg** [comment]
Lgtm

Do we know how much this increases the runtime of this action?

**Comment by vondele** [comment]
Approx 30s extra. Restoring the TB from cache is fast. About 5s

**Comment by peregrineshahin** [comment]
If PVs gets corrected and extended how can one know the bugs when no TB is used?

**Comment by vondele** [comment]
There is no difference for mate PVs

**Comment by peregrineshahin** [comment]
> There is no difference for mate PVs

Missed that, thanks

**Pull request closed without merging**
