### PR TITLE
Bad outpost

### PR DESCRIPTION
**Pull request by Rocky640**
Propose a simpler version, non functional change
bench: 4366686

### CODE REVIEW

**Comment by vondele** [comment]
OK, let's how this test goes https://tests.stockfishchess.org/tests/view/5f099c3359f6f03532894880 which removes it fully. If this passes, I have a hard time to understand the results in https://github.com/official-stockfish/Stockfish/pull/2803#issuecomment-656863400

**Comment by Rocky640** [comment]
OK, let's wait.

Another non functional rewrite could be
https://github.com/official-stockfish/Stockfish/commit/6b09458ec1dfcf51b9731893434ca2e7609336d3

Recommended functional tests:
a) remove `(b & pos.pieces(Them) & ~pos.pieces(PAWN))`

b) replace SQ_A1 with
    `bitboard QSCorners = (1ULL << SQ_A1)  |  (1ULL << SQ_A8);`

c) replace SQ_A1 with
    `bitboard Corners = (1ULL << SQ_A1)  |  (1ULL << SQ_A8) | (1ULL << SQ_H1)  |  (1ULL << SQ_H8);`

test a) is not done for any other bonus in evaluate.cpp, so most likely not needed here as well.
there were tests for b) or c), but the code which was used was probably a slow down.

**Comment by anshulongithub** [comment]
Shudn't the original patch resist from being simplified cuz it had passed SPRT bounds? How do we ascertain the reliability of SPRT bounds then when compared to simplification bounds? Is it fair to say that a test that passes SPRT shud almost always resist from getting simplified and if not then in what circumstances can it get simplified? Can such a scenario be reasoned about? Or the other way round, does it mean that simplication bounds need to be stricter?

Please advise.

**Comment by NKONSTANTAKIS** [comment]
The impressive performance of the patch is not so much that it passed 4xSTC, which is easier and noisier, but that all 3 versions more or less passed LTC in ~20K games.

So even if the STC simplification passes, its still expected to fail LTC.

@anshulongithub elo-gaining STC bounds are very close to reverse simplification bounds. So if we were just testing 1xSTC a lot of the "elo gainers" would also be reverted. But at LTC most elo-gainers would hold, {0.25, 1.75} is serious.

**Comment by ssj100** [comment]
> The impressive performance of the patch is not so much that it passed 4xSTC, which is easier and noisier, but that all 3 versions more or less passed LTC in ~20K games.
> 
> So even if the STC simplification passes, its still expected to fail LTC.
> 
> @anshulongithub elo-gaining STC bounds are very close to reverse simplification bounds. So if we were just testing 1xSTC a lot of the "elo gainers" would also be reverted. But at LTC most elo-gainers would hold, {0.25, 1.75} is serious.

Except the simplification bounds at both STC and LTC are identical.  That is, the only difference is the time control to pass simplification bounds at STC and LTC.  So your reasoning that "most elo-gainers would hold..." (in the context of an attempt to simplify them away) is solely based on the "increased time control at LTC"?

**Comment by NKONSTANTAKIS** [comment]
There are 2 reasons that our procedure works, one is that passing 2 tests cuts the chance in "half"
for example lets take a -0.5 patch with {-1.5 , 0.5}. It has 50% to pass one but 25% to pass 2 tests.

For STC elo gainer we got {0.5 , 1.5} which is 50% chance is for a +0.5, meaning that by reverting it we lose 0,5 elo, so -0.5 is the exact above example.

So if we were accepting/rejecting solely on 1 STC test, gaining and losing will be the exact reverse, if we count out selection bias.

But fortunately we are not, so doing 2 tests, we both make it harder for elo gainers and simplifications to pass.

2nd reason, and most appropriate to your question, is that LTC elo gainer is {0.25 , 1.75}, meaning that 50% chance to pass is for +1 elo and not for +0.5. This means that even with a single test, reverting an LTC pass will fail most of the times.

But selection bias is against us, so its good that we do 2 tests.

**Comment by SFisGOD** [comment]
I relaunched these tests just for completion and also to see if these two will truly pass.
https://tests.stockfishchess.org/tests/view/5f0835b959f6f03532894796
https://tests.stockfishchess.org/tests/view/5f082e7559f6f03532894786

**Comment by SFisGOD** [comment]
Is there a way to quickly check the distribution of openings in these tests? Like what percentage is French games etc.

**Comment by ssj100** [comment]
> I relaunched these tests just for completion and also to see if these two will truly pass LTC.
> https://tests.stockfishchess.org/tests/view/5f0835b959f6f03532894796
> https://tests.stockfishchess.org/tests/view/5f082e7559f6f03532894786

Well congratulations, this patch has now passed LTC three times.  Let's hope for statistic's sake that the LTC simplification will fail!

**Comment by anshulongithub** [comment]
(7,36) took the least number of games to pass even less than the one that was committed (-7,36), does that mean its the strongest of the 3 versions tried and shud be committed? We definitely want the strongest version of this patch to be committed into SF. @SFisGOD @vondele

**Comment by SFisGOD** [comment]
@anshulongithub I doubt it is stronger but to satisfy your curiosity, I'll submit a parameter tweak test for (7,36) :)

**Comment by anshulongithub** [comment]
@SFisGOD yes let us do that on top of the current master; that indeed will be a very good test. Thank you so much, Johnathan, for your efforts in finding this ELO gainer. I am hoping that that simplification will not pass, its -1.33 at this time.

**Comment by locutus2** [comment]
@Rocky640 
This rewrite would be much better than the original because now its easy understandable what it does.
But i would do for saftey a non-regression test at STC.

**Comment by locutus2** [comment]
Here are my tries to replace this ackward conditional_more_than_two function, all currently running at STC. The first one seems the most promising:

https://tests.stockfishchess.org/tests/view/5f0ab82859f6f03532894945
https://tests.stockfishchess.org/tests/view/5f0ac9ef59f6f0353289495f
https://tests.stockfishchess.org/tests/view/5f0ab23e59f6f0353289493c

**Comment by vondele** [comment]
@locutus2 no need for an additional test I think. However, since there are many related simplification and improvements attempts running right now I won't commit this PR for now.

Also, I'll be away from a keyboard next week, so patches will be pending a couple of days.

**Comment by SFisGOD** [comment]
This simpler version seems to remove the more_than_two part of conditional_more_than_two. It's now always more_than_one. Based on my current tests, the more_than_two part seems to resist removal at LTC. So I think we should be careful before committing this simpler version.

**Comment by anshulongithub** [comment]
@vondele @Rocky640 none of the rewrites have passed for the original implementation, especially cuz that `b & (b - 1) & (b - 2)` has been difficult to reason about and only that implementation has passed. So a non-regression test at both STC and LTC is a prudent thing to do just to be sure.

**Comment by vondele** [comment]
not that Rocky's change is non-functional, i.e. identical to current master. The implementation will not be slower either.

**Comment by anshulongithub** [comment]
STC test for this PR has failed, @vondele 
https://tests.stockfishchess.org/tests/view/5f0b0e9759f6f03532894972
Thanks a lot, @SFisGOD for running this test.

Does this also mean that non-functional patches producing same benches, **in case of eval based changes** can be **not equivalent**?

**Comment by Rocky640** [comment]
> Does this also mean that there is a possibility for non-functional patch which produce the same bench as master, in case of eval based changes can be not equivalent?

When we say "non functional change" it means that it is equivalent.
It should produce exactly the same evaluations on any position.

An identical bench signature is a strong indicator that they are equivalent.
One can also verify that bench run at larger depth gives same results.
One can also try bench on different set of positions.

Here, they were logically equivalent. 
Or if you prefer, same patch, but different code style.

It just happened that this (simple) PR did not pass, which is quite surprising.

**Comment by AlexandreMasta** [comment]
Seems some are trying hard to cripple a nice patch.

**Comment by SFisGOD** [comment]
Following Stefan's suggestion [#2806 (comment)](https://github.com/official-stockfish/Stockfish/pull/2806#issuecomment-657200687) I ran an STC non-regression test for this simpler version. Unfortunately, it failed. 
LLR: -2.93 (-2.94,2.94) {-1.50,0.50}
Total: 38216 W: 7210 L: 7444 D: 23562
Ptnml(0-2): 616, 4420, 9215, 4296, 561
https://tests.stockfishchess.org/tests/view/5f0b0e9759f6f03532894972

None of the simplification attempts so far passed STC and LTC.
My simplification seems promising though.
https://tests.stockfishchess.org/tests/view/5f0a683159f6f03532894915

**Comment by ssj100** [comment]
> > It just happened that this (simple) PR did not pass, which is quite surprising.

What is the chance that an absolutely neutral patch fails the current simplification bounds?  Does STC influence this chance verses LTC?

**Comment by AlexandreMasta** [comment]
> Following Stefan's suggestion [#2806 (comment)](https://github.com/official-stockfish/Stockfish/pull/2806#issuecomment-657200687) I ran an STC non-regression test for this simpler version. Unfortunately, it failed.
> LLR: -2.93 (-2.94,2.94) {-1.50,0.50}
> Total: 38216 W: 7210 L: 7444 D: 23562
> Ptnml(0-2): 616, 4420, 9215, 4296, 561
> https://tests.stockfishchess.org/tests/view/5f0b0e9759f6f03532894972
> 
> None of the simplification attempts so far passed STC and LTC.
> My simplification seems promising though.
> https://tests.stockfishchess.org/tests/view/5f0a683159f6f03532894915
> 
> Also, since this test failed, which removes the non-attacking condition
> https://tests.stockfishchess.org/tests/view/5f0b53a659f6f035328949a8
> 
> I think this shows that the non-attacking condition is essential. Even if the non-attacking condition is not used anywhere else in eval cpp, it doesn't mean that it is not essential here. Also, the non-attacking condition is logical, **a Knight outpost that doesn't attack any non pawn enemies has less value**. See https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/dEXNzSIBgZU

^This. The "rewrite" is not "non functional". You must be more careful of what you "think" it is "non functional". Doesn´t make any sense a "non-functional patch" fail LTC (right now about 3).

**Comment by ssj100** [comment]
> ^This. The "rewrite" is not "non functional". You must be more careful of what you "think" it is "non functional". Doesn´t make any sense a "non-functional patch" fail LTC (right now about 3).

The "rewrite" (apparently non-functional) has only failed once - the STC run.  The others were "functional" if I understand correctly.

**Comment by Rocky640** [comment]
@SFisGOD thanks for running this STC test.

@AlexandreMasta  this PR was non functional (same bench)
All the other tests were functional changes (attempts to simplify and/or generalize this strange SQ_A1 exception).

I will close the PR. Guys, feel free to continue discussion here if you want.

**Comment by adentong** [comment]
I have to say, passing 4 stc 3 ltc and resisting every single simplification attempt is pretty damn impressive

**Pull request closed without merging**
