### PR TITLE
cleanup includes

### PR DESCRIPTION
**Pull request by Disservin**
Reorder a few includes and include "position.h" where it was previously missing. Also make the order of the includes consistent, in the following way.

1. Related header (for .cpp files)
2. A blank line
3. C/C++ headers
4. A blank line
5. All other header files

No functional change

### CODE REVIEW

**Comment by Disservin** [comment]
For now I've only made the order consistent and included "position.h" where it was used. There are still other headers which are implictly included but fixing all of them needs a bit more time and is perhaps better todo in another pr.

**Comment by UniQP** [comment]
This should also fix #4707 because of the `#include <cmath>` in `nnue/evaluate_nnue.cpp`.

**Comment by Disservin** [comment]
> This should also fix #4707 because of the `#include <cmath>` in `nnue/evaluate_nnue.cpp`.

and make the current version of https://github.com/official-stockfish/Stockfish/pull/4760 redundant

**Review by vondele — APPROVED** [review]

**Comment by snicolet** [comment]
Merged via 3c0e86a91e48baea273306e45fb6cf13a59373cf, thanks :-)

**Comment by Disservin** [comment]
@UniQP thanks!

**Pull request closed without merging**
