### PR TITLE
VVLTC search tune

### PR DESCRIPTION
**Pull request by XInTheDark**
Passed VVLTC 1st sprt: https://tests.stockfishchess.org/tests/view/6695189d4ff211be9d4ec00b
LLR: 2.95 (-2.94,2.94) <0.00,2.00>
Total: 38912 W: 9947 L: 9673 D: 19292
Ptnml(0-2): 3, 3599, 11980, 3869, 5 

Passed VVLTC 2nd sprt: https://tests.stockfishchess.org/tests/view/669a2fd74ff211be9d4ec508
 LLR: 2.95 (-2.94,2.94) <0.50,2.50>
Total: 51446 W: 13259 L: 12939 D: 25248
Ptnml(0-2): 1, 4709, 15992, 5011, 10 

Bench: 1227160

### CODE REVIEW

**Comment by FauziAkram** [comment]
This patch is reverting 3 simplifications:
#5454 
#5489 
#5502

**Comment by XInTheDark** [comment]
For each of the PRs in order:
1. it was simply a cosmetic change, obviously the divisor can be re-introduced at any time for tuning purposes. in fact as I have expressed earlier, removing such divisors is simply counterproductive since we know search tunes will happen in the future.
2. it was a small formula tweak. I have also speculated previously that there is bad scaling there - this is backed by a large amount of data. in any case, relative to master, yes I have reverted this simplification. let me know if we need to run yet another VVLTC to test this simple change - personally I don't believe so.
3. this simplification was tested together with a tune. As discussed previously this is problematic because it's 1) an inefficient use of resources and 2) the simplification was not tested separately from the tune. furthermore it was established quite some time ago that VVLTC search tunes take precedence over STC/LTC ones, because search is currently optimized for VVLTC.

**Comment by Vizvezdenec** [comment]
actually testing 3) on top of the tune should 
1) pass easily
2) make it the most bullet-proof simplification in sf history, period
Although imho it can be committed "as is" since what it simplifies away makes absolutely no sense to me anyway.

**Comment by dubslow** [comment]
2) the only relevant data im aware of, which is posted in 5489, clearly says that quadratic has no benefit over linear either at STC or at VVLTC

**Comment by XInTheDark** [comment]
@dubslow that data isn't even relevant any more as of this patch, search params have all completely changed. as I said feel free to run more VVLTC tests simplifying this corrHist or confirming my change or whatever, but I think that's unnecessary for this patch to be merged.

**Comment by XInTheDark** [comment]
also to be noted is that generally higher corrHist values scale well to longer TCs (supported by numerous VVLTC tunes and tests). and using a quadratic formula gives a larger divisor for tuner to tune on, compared to cv / 10 or whatever

**Comment by vondele** [comment]
This conflicts on current master. Please rebase and retest.

**Comment by XInTheDark** [comment]
OK, will open new PR after retest

**Pull request closed without merging**
