### PR TITLE
Enable New Pass Manager for Clang.

### PR DESCRIPTION
**Pull request by gcp**
Clang has a new optimization pass manager activated by
-fexperimental-new-pass-manager. It's been in development
for several years, and by now generally performing better
than the default. It is planned to be the new default in
Clang 13, but even versions before that perform better with it,
and it's stable enough that major software like Firefox has
been using it already:
https://bugzilla.mozilla.org/show_bug.cgi?id=1619461

It's about 1% speedup for Stockfish.

Result of 100 runs
==================
base (...fish_clang12) =    1946851  +/- 3717
test (./stockfish    ) =    1967276  +/- 3408
diff                   =     +20425  +/- 2438

speedup        = +0.0105
P(speedup > 0) =  1.0000

CPU: 4 x Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
Hyperthreading: on

Thanks to David Major for making me aware of this part
of LLVM development.

### CODE REVIEW

**Comment by gcp** [comment]
With this and the ThinLTO fix clang is close to 2% faster on my hardware than GCC 10:

```
Result of 100 runs
==================
base (...ckfish_gcc10) =    1908060  +/- 28912
test (...h_clang12npm) =    1941171  +/- 27715
diff                   =     +33111  +/- 4024

speedup        = +0.0174
P(speedup > 0) =  1.0000

CPU: 4 x Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
Hyperthreading: on 
```

**Comment by MichaelB7** [comment]
2 long concurrent runs,  both pgo builds , both with "flto".  A 0.7% speed pickup for clang over clang, total runtime over 3 minutes, fwiw, I ran a number of shorter concurrent runs and clang was faster everytime with pass manager flag/

OS Sys Windows 10 Pro
gcc.exe (Rev6, Built by MSYS2 project) 10.2.0
clang version 11.0.0 (https://github.com/msys2/MINGW-packages 500eeb8c8d8dc104557c9109cc9e32c203feb4e2)
Target: x86_64-w64-windows-gnu


```
command: 
$ SF-clang bench 256 1 26 >/dev/null && echo "clang" & stockfish bench 256 1 26 >/dev/null && echo "gcc"


Position: 1/45 (rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1)

Position: 1/45 (rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1)

Position: 2/45 (r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 10)

Position: 2/45 (r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 10)

Position: 3/45 (8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 11)

Position: 3/45 (8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 11)

Position: 4/45 (4rrk1/pp1n3p/3q2pQ/2p1pb2/2PP4/2P3N1/P2B2PP/4RRK1 b - - 7 19)

Position: 4/45 (4rrk1/pp1n3p/3q2pQ/2p1pb2/2PP4/2P3N1/P2B2PP/4RRK1 b - - 7 19)

Position: 5/45 (rq3rk1/ppp2ppp/1bnpN3/3N2B1/4P3/7P/PPPQ1PP1/2KR3R b - - 0 14)

Position: 5/45 (rq3rk1/ppp2ppp/1bnpN3/3N2B1/4P3/7P/PPPQ1PP1/2KR3R b - - 0 14)

Position: 6/45 (r1bq1r1k/1pp1n1pp/1p1p4/4p2Q/4PpP1/1BNP4/PPP2P1P/3R1RK1 b - g3 0 14)

Position: 6/45 (r1bq1r1k/1pp1n1pp/1p1p4/4p2Q/4PpP1/1BNP4/PPP2P1P/3R1RK1 b - g3 0 14)

Position: 7/45 (r3r1k1/2p2ppp/p1p1bn2/8/1q2P3/2NPQN2/PPP3PP/R4RK1 b - - 2 15)

Position: 7/45 (r3r1k1/2p2ppp/p1p1bn2/8/1q2P3/2NPQN2/PPP3PP/R4RK1 b - - 2 15)

Position: 8/45 (r1bbk1nr/pp3p1p/2n5/1N4p1/2Np1B2/8/PPP2PPP/2KR1B1R w kq - 0 13)

Position: 8/45 (r1bbk1nr/pp3p1p/2n5/1N4p1/2Np1B2/8/PPP2PPP/2KR1B1R w kq - 0 13)

Position: 9/45 (r1bq1rk1/ppp1nppp/4n3/3p3Q/3P4/1BP1B3/PP1N2PP/R4RK1 w - - 1 16)

Position: 9/45 (r1bq1rk1/ppp1nppp/4n3/3p3Q/3P4/1BP1B3/PP1N2PP/R4RK1 w - - 1 16)

Position: 10/45 (4r1k1/r1q2ppp/ppp2n2/4P3/5Rb1/1N1BQ3/PPP3PP/R5K1 w - - 1 17)

Position: 10/45 (4r1k1/r1q2ppp/ppp2n2/4P3/5Rb1/1N1BQ3/PPP3PP/R5K1 w - - 1 17)

Position: 11/45 (2rqkb1r/ppp2p2/2npb1p1/1N1Nn2p/2P1PP2/8/PP2B1PP/R1BQK2R b KQ - 0 11)

Position: 11/45 (2rqkb1r/ppp2p2/2npb1p1/1N1Nn2p/2P1PP2/8/PP2B1PP/R1BQK2R b KQ - 0 11)

Position: 12/45 (r1bq1r1k/b1p1npp1/p2p3p/1p6/3PP3/1B2NN2/PP3PPP/R2Q1RK1 w - - 1 16)

Position: 12/45 (r1bq1r1k/b1p1npp1/p2p3p/1p6/3PP3/1B2NN2/PP3PPP/R2Q1RK1 w - - 1 16)

Position: 13/45 (3r1rk1/p5pp/bpp1pp2/8/q1PP1P2/b3P3/P2NQRPP/1R2B1K1 b - - 6 22)

Position: 13/45 (3r1rk1/p5pp/bpp1pp2/8/q1PP1P2/b3P3/P2NQRPP/1R2B1K1 b - - 6 22)

Position: 14/45 (r1q2rk1/2p1bppp/2Pp4/p6b/Q1PNp3/4B3/PP1R1PPP/2K4R w - - 2 18)

Position: 14/45 (r1q2rk1/2p1bppp/2Pp4/p6b/Q1PNp3/4B3/PP1R1PPP/2K4R w - - 2 18)

Position: 15/45 (4k2r/1pb2ppp/1p2p3/1R1p4/3P4/2r1PN2/P4PPP/1R4K1 b - - 3 22)

Position: 15/45 (4k2r/1pb2ppp/1p2p3/1R1p4/3P4/2r1PN2/P4PPP/1R4K1 b - - 3 22)

Position: 16/45 (3q2k1/pb3p1p/4pbp1/2r5/PpN2N2/1P2P2P/5PP1/Q2R2K1 b - - 4 26)

Position: 16/45 (3q2k1/pb3p1p/4pbp1/2r5/PpN2N2/1P2P2P/5PP1/Q2R2K1 b - - 4 26)

Position: 17/45 (6k1/6p1/6Pp/ppp5/3pn2P/1P3K2/1PP2P2/3N4 b - - 0 1)

Position: 17/45 (6k1/6p1/6Pp/ppp5/3pn2P/1P3K2/1PP2P2/3N4 b - - 0 1)

Position: 18/45 (3b4/5kp1/1p1p1p1p/pP1PpP1P/P1P1P3/3KN3/8/8 w - - 0 1)

Position: 19/45 (2K5/p7/7P/5pR1/8/5k2/r7/8 w - - 4 3)

Position: 20/45 (8/6pk/1p6/8/PP3p1p/5P2/4KP1q/3Q4 w - - 0 1)

Position: 18/45 (3b4/5kp1/1p1p1p1p/pP1PpP1P/P1P1P3/3KN3/8/8 w - - 0 1)

Position: 19/45 (2K5/p7/7P/5pR1/8/5k2/r7/8 w - - 4 3)

Position: 20/45 (8/6pk/1p6/8/PP3p1p/5P2/4KP1q/3Q4 w - - 0 1)

Position: 21/45 (7k/3p2pp/4q3/8/4Q3/5Kp1/P6b/8 w - - 0 1)

Position: 21/45 (7k/3p2pp/4q3/8/4Q3/5Kp1/P6b/8 w - - 0 1)

Position: 22/45 (8/2p5/8/2kPKp1p/2p4P/2P5/3P4/8 w - - 0 1)

Position: 23/45 (8/1p3pp1/7p/5P1P/2k3P1/8/2K2P2/8 w - - 0 1)

Position: 22/45 (8/2p5/8/2kPKp1p/2p4P/2P5/3P4/8 w - - 0 1)

Position: 23/45 (8/1p3pp1/7p/5P1P/2k3P1/8/2K2P2/8 w - - 0 1)

Position: 24/45 (8/pp2r1k1/2p1p3/3pP2p/1P1P1P1P/P5KR/8/8 w - - 0 1)

Position: 24/45 (8/pp2r1k1/2p1p3/3pP2p/1P1P1P1P/P5KR/8/8 w - - 0 1)

Position: 25/45 (8/3p4/p1bk3p/Pp6/1Kp1PpPp/2P2P1P/2P5/5B2 b - - 0 1)

Position: 25/45 (8/3p4/p1bk3p/Pp6/1Kp1PpPp/2P2P1P/2P5/5B2 b - - 0 1)

Position: 26/45 (5k2/7R/4P2p/5K2/p1r2P1p/8/8/8 b - - 0 1)

Position: 27/45 (6k1/6p1/P6p/r1N5/5p2/7P/1b3PP1/4R1K1 w - - 0 1)

Position: 26/45 (5k2/7R/4P2p/5K2/p1r2P1p/8/8/8 b - - 0 1)

Position: 27/45 (6k1/6p1/P6p/r1N5/5p2/7P/1b3PP1/4R1K1 w - - 0 1)

Position: 28/45 (1r3k2/4q3/2Pp3b/3Bp3/2Q2p2/1p1P2P1/1P2KP2/3N4 w - - 0 1)

Position: 28/45 (1r3k2/4q3/2Pp3b/3Bp3/2Q2p2/1p1P2P1/1P2KP2/3N4 w - - 0 1)

Position: 29/45 (6k1/4pp1p/3p2p1/P1pPb3/R7/1r2P1PP/3B1P2/6K1 w - - 0 1)

Position: 29/45 (6k1/4pp1p/3p2p1/P1pPb3/R7/1r2P1PP/3B1P2/6K1 w - - 0 1)

Position: 30/45 (8/3p3B/5p2/5P2/p7/PP5b/k7/6K1 w - - 0 1)

Position: 31/45 (5rk1/q6p/2p3bR/1pPp1rP1/1P1Pp3/P3B1Q1/1K3P2/R7 w - - 93 90)

Position: 30/45 (8/3p3B/5p2/5P2/p7/PP5b/k7/6K1 w - - 0 1)

Position: 31/45 (5rk1/q6p/2p3bR/1pPp1rP1/1P1Pp3/P3B1Q1/1K3P2/R7 w - - 93 90)

Position: 32/45 (4rrk1/1p1nq3/p7/2p1P1pp/3P2bp/3Q1Bn1/PPPB4/1K2R1NR w - - 40 21)

Position: 32/45 (4rrk1/1p1nq3/p7/2p1P1pp/3P2bp/3Q1Bn1/PPPB4/1K2R1NR w - - 40 21)

Position: 33/45 (r3k2r/3nnpbp/q2pp1p1/p7/Pp1PPPP1/4BNN1/1P5P/R2Q1RK1 w kq - 0 16)

Position: 33/45 (r3k2r/3nnpbp/q2pp1p1/p7/Pp1PPPP1/4BNN1/1P5P/R2Q1RK1 w kq - 0 16)

Position: 34/45 (3Qb1k1/1r2ppb1/pN1n2q1/Pp1Pp1Pr/4P2p/4BP2/4B1R1/1R5K b - - 11 40)

Position: 34/45 (3Qb1k1/1r2ppb1/pN1n2q1/Pp1Pp1Pr/4P2p/4BP2/4B1R1/1R5K b - - 11 40)

Position: 35/45 (4k3/3q1r2/1N2r1b1/3ppN2/2nPP3/1B1R2n1/2R1Q3/3K4 w - - 5 1)

Position: 35/45 (4k3/3q1r2/1N2r1b1/3ppN2/2nPP3/1B1R2n1/2R1Q3/3K4 w - - 5 1)

Position: 36/45 (8/8/8/8/5kp1/P7/8/1K1N4 w - - 0 1)

Position: 37/45 (8/8/8/5N2/8/p7/8/2NK3k w - - 0 1)

Position: 38/45 (8/3k4/8/8/8/4B3/4KB2/2B5 w - - 0 1)

Position: 36/45 (8/8/8/8/5kp1/P7/8/1K1N4 w - - 0 1)

Position: 37/45 (8/8/8/5N2/8/p7/8/2NK3k w - - 0 1)

Position: 38/45 (8/3k4/8/8/8/4B3/4KB2/2B5 w - - 0 1)

Position: 39/45 (8/8/1P6/5pr1/8/4R3/7k/2K5 w - - 0 1)

Position: 39/45 (8/8/1P6/5pr1/8/4R3/7k/2K5 w - - 0 1)

Position: 40/45 (8/2p4P/8/kr6/6R1/8/8/1K6 w - - 0 1)

Position: 41/45 (8/8/3P3k/8/1p6/8/1P6/1K3n2 b - - 0 1)

Position: 40/45 (8/2p4P/8/kr6/6R1/8/8/1K6 w - - 0 1)

Position: 42/45 (8/R7/2q5/8/6k1/8/1P5p/K6R w - - 0 124)

Position: 43/45 (6k1/3b3r/1p1p4/p1n2p2/1PPNpP1q/P3Q1p1/1R1RB1P1/5K2 b - - 0 1)

Position: 44/45 (r2r1n2/pp2bk2/2p1p2p/3q4/3PN1QP/2P3R1/P4PP1/5RK1 w - - 0 1)

Position: 45/45 (bb1n1rkr/ppp1Q1pp/3n1p2/3p4/3P4/6Pq/PPP1PP1P/BB1NNRKR w HFhf - 0 5)

Position: 41/45 (8/8/3P3k/8/1p6/8/1P6/1K3n2 b - - 0 1)

Position: 42/45 (8/R7/2q5/8/6k1/8/1P5p/K6R w - - 0 124)

Position: 43/45 (6k1/3b3r/1p1p4/p1n2p2/1PPNpP1q/P3Q1p1/1R1RB1P1/5K2 b - - 0 1)

Position: 44/45 (r2r1n2/pp2bk2/2p1p2p/3q4/3PN1QP/2P3R1/P4PP1/5RK1 w - - 0 1)

Position: 45/45 (bb1n1rkr/ppp1Q1pp/3n1p2/3p4/3P4/6Pq/PPP1PP1P/BB1NNRKR w HFhf - 0 5)

===========================
Total time (ms) : 205880
Nodes searched  : 496116737
Nodes/second    : 2409737
clang

===========================
Total time (ms) : 207232
Nodes searched  : 496116737
Nodes/second    : 2394016
gcc
```

**Comment by vondele** [comment]
I did a comparison, just with master, in my case clang is 3.5% slower (AMD Ryzen 9 3950X):

```
$ ~/chess/pyshbench/pyshbench.py ./stockfish.master.g++-10 ./stockfish.master.g++-7 10
run       base       test     diff
  1    2302027    2286279   -15748
  2    2308423    2303486    -4937
  3    2302391    2308057    +5666
  4    2310808    2298751   -12057
  5    2300934    2314487   +13553
  6    2291685    2300934    +9249
  7    2299660    2315777   +16117
  8    2284662    2280183    -4479
  9    2368790    2348889   -19901
 10    2287538    2282331    -5207

Result of  10 runs
==================
base (...aster.g++-10) =    2305692  +/- 14684
test (...master.g++-7) =    2303917  +/- 12495
diff                   =      -1774  +/- 7693

speedup        = -0.0008
P(speedup > 0) =  0.3258


$ ~/chess/pyshbench/pyshbench.py ./stockfish.master.g++-10 ./stockfish.master.g++-8 10
run       base       test     diff
  1    2275544    2302027   +26483
  2    2291866    2310257   +18391
  3    2278397    2297298   +18901
  4    2306775    2319287   +12512
  5    2291143    2294398    +3255
  6    2359755    2376535   +16780
  7    2380036    2382181    +2145
  8    2310074    2320768   +10694
  9    2290241    2280005   -10236
 10    2284304    2298387   +14083

Result of  10 runs
==================
base (...aster.g++-10) =    2306814  +/- 21843
test (...master.g++-8) =    2318114  +/- 21324
diff                   =     +11301  +/- 6493

speedup        = +0.0049
P(speedup > 0) =  0.9997

$ ~/chess/pyshbench/pyshbench.py ./stockfish.master.g++-10 ./stockfish.master.g++-9 10
run       base       test     diff
  1    2289159    2258926   -30233
  2    2282869    2263851   -19018
  3    2288439    2255772   -32667
  4    2282869    2277861    -5008
  5    2273587    2274654    +1067
  6    2275722    2261914   -13808
  7    2283227    2260858   -22369
  8    2323735    2323364     -371
  9    2290421    2268620   -21801
 10    2286639    2277326    -9313

Result of  10 runs
==================
base (...aster.g++-10) =    2287667  +/- 8554
test (...master.g++-9) =    2272315  +/- 12109
diff                   =     -15352  +/- 7339

speedup        = -0.0067
P(speedup > 0) =  0.0000


$ ~/chess/pyshbench/pyshbench.py ./stockfish.master.g++-10 ./stockfish.master.clang++-10 10
run       base       test     diff
  1    2286999    2202128   -84871
  2    2298933    2225727   -73206
  3    2278754    2201795   -76959
  4    2289159    2205301   -83858
  5    2314487    2229311   -85176
  6    2353071    2283048   -70023
  7    2294398    2180168  -114230
  8    2292227    2205636   -86591
  9    2286819    2204465   -82354
 10    2364745    2286279   -78466

Result of  10 runs
==================
base (...aster.g++-10) =    2305959  +/- 18299
test (...r.clang++-10) =    2222386  +/- 21961
diff                   =     -83573  +/- 7483

speedup        = -0.0362
P(speedup > 0) =  0.0000

```

I would say both compilers are pretty equivalent in speed nevertheless.

**Comment by gcp** [comment]
Hi Joost, there's some benchmarking in issue #3341. It does look like they're close (at least with clang-12), but when GCC is faster it tends to be a lot faster, so I withdrew the issue to default clang.

But the clang settings change here should be beneficial though, for people that choose to use clang.

**Comment by vondele** [comment]
Do you know what older versions of clang++ support the flag -fexperimental-new-pass-manager flag, and how future versions of clang will deal with the flag? That is, should we be concerned about users of earlier / newer versions of clang where this might have side effects (bugs).

**Comment by gcp** [comment]
Newer versions will Just Work - they default it on internally, and they add a flag to activate the old behavior (legacy pass manager). At some point they may remove the flag, by which point we could remove it here.

The flag has existed since 2016 I think (https://reviews.llvm.org/D28077), so every clang that's newer than 4.0 (or thereabouts) should handle it. Given that we don't default clang, I think that's more than enough margin.

**Comment by vondele** [comment]
OK, both PRs combined give a good speedup here:
```
Result of  10 runs
==================
base (...kfish.master) =    2208553  +/- 19324
test (...ckfish.patch) =    2269327  +/- 23681
diff                   =     +60774  +/- 7046

speedup        = +0.0275
P(speedup > 0) =  1.0000

```

**Pull request closed without merging**
