### PR TITLE
MovePick

### PR DESCRIPTION
**Pull request by VoyagerOne**
Remove pointless code.

No functional change.

### CODE REVIEW

**Comment by mstembera** [comment]
The code is non functional but might have been there for speed reasons.

**Comment by VoyagerOne** [comment]
@mstembera 

Results for 10 tests for each version:

            Base      Test      Diff      
    Mean    2551298   2580705   -29407    
    StDev   38727     15637     35543     

p-value: 0.796
speedup: 0.012

**Comment by KassiasGrandiel** [comment]
When I was testing this against master. 12 times each I got 2219000 2 times independently of each other for the speedup. Could there be a hidden bug?

**Comment by gvreuls** [comment]
The old code is an optimization trick that relies on branch prediction plus cashing winning out on a single memory write. Whether it really does depends on the hardware architecture and the predictability of the written data.

**Comment by mstembera** [comment]
@VoyagerOne Sorry I couldn't test sooner.  I actually get a 0.5% speedup.
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    960775    965964    -5189     
    StDev   249921    251219    3605      

p-value: 0.925
speedup: 0.005
```

**Comment by VoyagerOne** [comment]
@mstembera 
Ironically, you were the one that put the code in. :)
https://github.com/VoyagerOne/Stockfish/commit/6661a3154152ab448b1dc11d882586976f616f92

As you can see the code was used when we used to have multiple countermoves.
That is no longer the case.

**Comment by mstembera** [comment]
@VoyagerOne 
Yes I remember.  There was a similar kind of early out before so when I made the change I timed it both ways and at the time it was a tiny bit faster so I left it.  Probably just compiler noise.

**Comment by VoyagerOne** [comment]
@mstembera 
The early out was necessary to avoid having countermove1 = countermove2.  It was not used as a speedup, it was a necessity.

The now useless code is simply dead and will cause a minor slow down as it provides an extra branch...for the cpu to check.

**Comment by mstembera** [comment]
@VoyagerOne
U'r right.  I missed the real reason back then and again now :)

**Comment by lucasart** [comment]
This is a no brainer. Why does it take so long to merge this patch ?

**Comment by zamar** [comment]
Sorry, I've been busy and although this a nice simplification, it's low priority.

I'll merge this today.

**Pull request closed without merging**
