### PR TITLE
Optimize code in LMR search

### PR DESCRIPTION
**Pull request by ElbertoOne**
The code in LMR search can be optimized. Besides making the code more readable, it also prevents unnecessary calls to the to_sq and pos.piece_on functions. On my machine this results in a speedup of about 0.9%:

Results for 25 tests for each version:

            Base      Test      Diff      
    Mean    2178541   2198456   -19915    
    StDev   16711     16621     2639      

p-value: 1
speedup: 0.009

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Sorry but I fail to see where the simplification is.

Perhaps I am odd, but I find much more readable the original version.

**Comment by ElbertoOne** [comment]
@mcostalba The readability may be a matter of taste.
The speedup however is not. Implementing it this way replaces 6 calls to to_sq(move) with just 1 and 3 calls to pos.piece_on(to_sq(move)) with just 1.
I would appreciate it if someone could verify or disprove the speedup results.

**Comment by mcostalba** [comment]
I think the compiler is able to figure out the temporary local variables
better than us (and does this without manually adding temporaries).

**Comment by CoffeeOne** [comment]
I made a long bench run: Gcc 5.3.0, Windows, fixed clock rate, 100 runs, in total nearly 1 hour!
Build Tester: 1.4.6.0
Windows 10 (Version 10.0, Build 0, 64-bit Edition)
AMD FX(tm)-9590 Eight-Core Processor           
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: Yes
CPU Warmup: Yes
Command Line: bench 16 1 16 default depth
Tests per Build: 100
ANOVA: n/a

                Engine# (NPS)                     Speedup     Sp     Conf. 99%    S.S.
1  (1.695.154,4   ) ---> 2  (1.693.569,0   ) --->  0,094%  9.575,8      No        No 
Engine 1 is your version.
So I can confirm speed gain, but only 0.09%, that's too little to think about it.

**Comment by ElbertoOne** [comment]
@CoffeeOne thanks for the test. I will close the pull request.

**Pull request closed without merging**
