### PR TITLE
Simplify aspiration window widening

### PR DESCRIPTION
**Pull request by XInTheDark**
Instead of scaling based on the current window size, simply widen the window using fixed constant 10.

Simplification STC: https://tests.stockfishchess.org/tests/view/648b10e291c58631ce31c668
LLR: 2.93 (-2.94,2.94) <-1.75,0.25> 
Total: 94752 W: 25238 L: 25089 D: 44425 
Ptnml(0-2): 228, 10346, 26078, 10497, 227

Simplification LTC: https://tests.stockfishchess.org/tests/view/648c017c91c58631ce31db1a
LLR: 2.94 (-2.94,2.94) <-1.75,0.25> 
Total: 248934 W: 67344 L: 67356 D: 114234
Ptnml(0-2): 79, 24038, 76252, 24012, 86

Matetrack scores, courtesy of Viren:
```
Using ./stockfish with 1000000 nodes
Total fens:    6561
Found mates:   3585
Best mates:    2425
```
Negligible regression compared to current master score of 2445 best mates.

Bench: 2584183

### CODE REVIEW

**Comment by RogerThiede** [comment]
Would this have ramifications to users of Stockfish who perform deep analysis, such as MultiPV 5 and greater than 60 depth, or MultiPV 2 and greater than 70 depth?  I would suspect this change could cause significant search strategy changes with high ROI for <40 depth but very low ROI for >70 depth?  Would maintainers even care about use cases other than STC and LTC runs?

**Comment by Disservin** [comment]
> Would this have ramifications to users of Stockfish who perform deep analysis, such as MultiPV 5 and greater than 60 depth, or MultiPV 2 and greater than 70 depth? I would suspect this change could cause significant search strategy changes with high ROI for <40 depth but very low ROI for >70 depth? Would maintainers even care about use cases other than STC and LTC runs?

MultiPV simply makes the engine worse. Concerns for VVLTC are rarely required and your concern isn’t even really testable current stockfish games at tcec even seem to be low depth 40 of a majority of the game. Anyway the depth argument is a wild guess.

Also if you have concerns it’s probably good to check git blame to check which commit added this and see how it scaled there. 

Tuning stockfish for purely analysis isn’t really something that we do.

**Comment by pb00067** [comment]
As I already commented on the testing commit, this simplification is IMO very borderline.
It's just avoiding a single division in a very high-level (non performance critical) part of code.
The number of parameters to tune remain the same.
The residual risk of an eventual regression is IMO to high when comparing it with the amount of simplification.

**Comment by XInTheDark** [comment]
> The residual risk of an eventual regression is IMO to high when comparing it with the amount of simplification.

How would it cause a regression though? The current logic is very much unclear.

**Comment by TheBlackPlague** [comment]
> As I already commented on the testing commit, this simplification is IMO very borderline. It's just avoiding a single division in a very high-level (non performance critical) part of code. The number of parameters to tune remain the same. The residual risk of an eventual regression is IMO to high when comparing it with the amount of simplification.

What is said risk? Where do you find it? How and why do you have said opinion? Please explain.

**Comment by pb00067** [comment]
@TheBlackPlague 
>>What is said risk? Where do you find it? How and why do you have said opinion? Please explain.
SPRT are statistical tests.
We run our sprt tests with parameters that guarantee 95% confidence.
How I understand this, it means that there is a rest risk about 5% that a passed simplification is a false positive and an actual regression (if we consider a single sprt non-regression test).

I can also give a recent example:
elogainig patch  https://github.com/official-stockfish/Stockfish/pull/4453 got a serie of simplifications after its merge in master:
https://github.com/official-stockfish/Stockfish/pull/4469
https://github.com/official-stockfish/Stockfish/pull/4533
https://github.com/official-stockfish/Stockfish/pull/4572

After that the original patch had not worth anymore, see
https://github.com/official-stockfish/Stockfish/pull/4595 
But I was able to reintroduce it once again with 
https://github.com/official-stockfish/Stockfish/pull/4609 

Thus most probably some of the simplifications 4469, 4533 or 4572 were actual regressions.
This is normal and happens statistically.
And that is IMO the reason we should avoid 'micro-optimizations' in non-hot part of the code:
the small risk of regression is IMO bigger than the 'amount of simplification' thus not worth it. 
Anyhow just my personal opinion.

**Comment by pb00067** [comment]
> The current logic is very much unclear.

Raising a value by 33% is a pretty simple & basic mathematical operation, there is nothing unclear.
It just more dymanic than constantly adding 10.

And being dynamic is a **good** thing when failing high consecutive times is due to discovering a move which scores much better than our current best score.
Immagine we are in endgame and thus search reaches high depths.
On MAXDEPTH - 10 suddenly aspiration search begins to fail-high because it detects a mating net.
Now with ` delta += delta / 3; ` it will most probably be able to resolve the mate before reaching MAXDEPTH. By raising delta only by constant 10 there is a risk that SF finishes searching without resolving within aspiration window at all.

**Comment by jhellis3** [comment]
The flat adjustments are not really an issue due to the way the window is widened.  However, I would agree it isn't really a significant enough simplification to warrant the bounds.  Seems more like change for the sake of change that doesn't really do anything.

Just my 2cp.

**Comment by TheBlackPlague** [comment]
> @TheBlackPlague
> 
> > > What is said risk? Where do you find it? How and why do you have said opinion? Please explain.
> 
> SPRT are statistical tests. We run our sprt tests with parameters that guarantee 95% confidence. How I understand this, it means that there is a rest risk about 5% that a passed simplification is a false positive and an actual regression (if we consider a single sprt non-regression test).
> 
> I can also give a recent example: elogainig patch #4453 got a serie of simplifications after its merge in master: #4469 #4501 #4533 #4572
> 
> After that the original patch apparently had no worth anymore, see #4595 But I was able to reintroduce it once again with #4609
> 
> Thus most probably some of the simplifications 4469, 4533 or 4572 were actual regressions. This is normal and happens statistically. And that is IMO the reason we should avoid 'micro-optimizations' in non-hot part of the code: the small risk of regression is IMO bigger than the 'amount of simplification' thus not worth it. Anyhow just my personal opinion.

"Probably" with absolutely 0 proof. How do you prove it was a regression? Have you considered that other changes might've been merged since the simplification? No. Your opinion is literally having no actual logical background.

**Comment by vondele** [comment]
given this is somewhat controversial (e.g. I did expect this to affect matefinding, but it didn't), and no fundamental simplification, I'll close this PR for now.

**Pull request closed without merging**
