### PR TITLE
Tune14 prr

### PR DESCRIPTION
**Pull request by FauziAkram**
Pr #5091 Rebased on the new master.

The original idea started from @TarasVuk with his patch: https://tests.stockfishchess.org/tests/view/6516b3a8b3e74811c8af4203
And the tune was done on top of it: https://tests.stockfishchess.org/tests/view/65db923b90f639b028a53875
and: https://tests.stockfishchess.org/tests/view/65db923390f639b028a53873

The razoring patch by itself does not pass:
https://tests.stockfishchess.org/tests/view/65e9da8b0ec64f0526c3ff71

The tuning patch by itself does not pass:
https://tests.stockfishchess.org/tests/view/65e74d230ec64f0526c3d5c5

While the combination of them passed both tests.

Passed STC:
LLR: 2.93 (-2.94,2.94) <0.00,2.00>
Total: 50496 W: 13211 L: 12868 D: 24417
Ptnml(0-2): 208, 5931, 12627, 6274, 208
https://tests.stockfishchess.org/tests/view/65e656dbb6345c1b93486281

Passed LTC:
LLR: 2.95 (-2.94,2.94) <0.50,2.50>
Total: 78552 W: 20101 L: 19692 D: 38759
Ptnml(0-2): 45, 8690, 21395, 9103, 43
https://tests.stockfishchess.org/tests/view/65e74d140ec64f0526c3d5c3

### CODE REVIEW

**Comment by Disservin** [comment]
@FauziAkram I have merged the tune in #5101 since it was VVLTC and had no additional patch included. Maybe you have a good feeling about some of the value changes and can compare them with the other tune and maybe come up with a new gainer ? ^^ I'll close this in the meantime

**Comment by FauziAkram** [comment]
@Disservin I understand your decision given the present circumstances (after both PRs have been opened), but honestly, I express dissatisfaction regarding what occurred previously. The second test of JMU should have been conducted on top of my passed patch, as I adhered to all your instructions regarding patch combinations, and this PR was valid. Disregarding entirely the efforts and time a developer has invested to generate an elo gainer in now two consecutive elo gainer PRs is not favorable. This is gradually causing me to lose my enthusiasm for this project.

**Comment by Disservin** [comment]
I'm not all too sure about the timeline of things, from looking at fishtest it seems he has started his test before yours has finished. Sure one can wait, but as with any sprts it can take longer than initially expected. Also with any projects there are typically multiple way of doing things and one is more favorable than the other, so in my opinion it is also more favorable to merge a tune which only has tuning changes and not an additional patch included.

**Comment by FauziAkram** [comment]
image
image
This is in reality when the vvltc started, before that it was accepted but with -1 priority and therefore 0 games.
So a day after my second test passed.

Anyway, I will try again to make it work with further tests, but I wanted to point out that the rejection of my last couple of elo gainer PRs has diminished both my morale and motivation, I will try to find it again, otherwise, I will contemplate quitting /taking a long break.

**Pull request closed without merging**
