### PR TITLE
Reformat SEE to better document the function

### PR DESCRIPTION
**Pull request by mcostalba**
This is one of the most difficult to understand but also
most important and critical functions of SF.

This patch rewrites some part of it to hopefully
make it more clear and drop some redundant variables
in the process.

No functional change.

### CODE REVIEW

**Comment by snicolet** [comment]
Looks good to me.
Tested for speed, indistinguishable from master at this point.

**Comment by ceebo** [comment]
I was surprised to hear the speed is indistinguishable. With this patch the lines `stm = ~stm`, `stmAttackers = attackers & pieces(stm)` and the computation `balance -> -balance - 1` are all done unnecessarily if we exit via the condition `balance >= VALUE_ZERO`. In a bench run we exit here 29% of the time.

I downloaded that psybench thingy and I got a small but statistically significant slowdown but my machine is old:

```
Result of  40 runs
==================
base (./master       ) =     861750  +/- 743
test (./stockfish    ) =     860423  +/- 689
diff                   =      -1326  +/- 827

speedup        = -0.0015
P(speedup > 0) =  0.0008

CPU: 2 x Intel(R) Core(TM)2 CPU          4400  @ 2.00GHz
Hyperthreading: off 
```

Getting rid of the `opponentToMove` variable is something that could be good although I like the fact that the current master has no returns inside the while loop.

**Comment by mcostalba** [comment]
0,15% !!!!

Can me measure this? In a reliable way?

Well we are well below noise level here. I could run a a SPRTè-3, 1] if Stephane asks so but to me it would be a total flip coin.

**Comment by ceebo** [comment]
Of course it's not a big deal but that part of the rewrite never makes for fewer instructions, only more. If Stephane thinks it makes the code simpler then it's fine by me.

**Comment by mcostalba** [comment]
@ceebo ok, I have updated the patch according to your comments. Pelase check.

For some reason the bench number is different, but now I have no time to debug it, anyhow the idea seems clear.

**Comment by ceebo** [comment]
@mcostalba A working version is here https://github.com/ceebo/Stockfish/commit/0e05284f28126ce989bb2372fac260a4002d7fae. My comment that `stm = ~stm` was an unnecessary computation in the case of `balance >= VALUE_ZERO` was incorrect. In the above patch `stm = ~stm` floats somewhere in the middle of the loop and is not very pleasing.

**Comment by mcostalba** [comment]
@ceebo thanks. I found the bug and fixed myself. I have rebased the patch series above current master and tested for speed. Now it is even a bit faster than original, but well below what I consider noise level.

Series updated, but still split in 2 for easier review of the new code after @ceebo feedback.

**Comment by mcostalba** [comment]
@ceebo I have pushed yet another version!

This one mixes some element of your work: I hope we can agree on this one

Speed test is the same of the previous and a bit faster than master.

**Comment by ceebo** [comment]
@mcostalba I do prefer the even newer version. I have a comment on this comment:

```
// If it's still not enough then stop, no need to continue.
```

Isn't the sense of that the wrong way around now? How about:
```
// If balance is non-negative after giving away nextVictim then we win.
// The only thing to be carfeul about it is that we should revert stm if
// we captured with the king when the opponent still has attackers.
if (balance >= VALUE_ZERO)
{
    if (nextVictim == KING && (attackers & pieces(stm)))
        stm = ~stm;
    break;
}
```

**Comment by mcostalba** [comment]
@ceebo ok, thanks, I will use your comment. If you don't mind I'd prefer 'stm' to 'we', it is more specific.

**Comment by mcostalba** [comment]
@snicolet I have updated the patch according to Chris valuable feedback, squashed and rebased. Now it's ready to be merged if you agree.

**Comment by snicolet** [comment]
@ceebo, @mcostalba 

I had studied these two functions (`SEE()` and `min_attackers()`) 18 months ago and understood them at the time. But now I have forgotten my analysis, I glance at them again and I find `min_attackers()` the most challenging of the two, especially the comments about the X-Rays.

Would it be possible to improve on the comments in min_attackers (very light editing, if possible) to give an idea of the juggling of bitboards (bb[], stmAttackers, occupied, attackers), maybe with an example in a short sentence ? 

"For instance, if bb[] contains piece BLAH, the target square is BLAH and the side to move has attackers BLAH, then we must update the occupied bitboard by doing BLAH and add the new attackers BLAH because of X-Rays".

(PS: of course this is probably incorrect as it is, just to give a suggestion!)

It would help tremendously, I believe!

**Comment by mcostalba** [comment]
@snicolet done, please check.

**Comment by snicolet** [comment]
Thanks, merged via https://github.com/official-stockfish/Stockfish/commit/a09eee579810fe446e34d0004e5716191310f4e4

**Pull request closed without merging**
