### PR TITLE
Remove the tropism term from kingDanger.

### PR DESCRIPTION
**Pull request by 31m059**
A recent LTC tuning session by @candirufish showed this term decreasing significantly.  It appears that it can be removed altogether without significant Elo loss.

I also thank @GuardianRM, whose attempt to remove tropism from king danger inspired this one.

After this PR is merged, my next step will be to attempt to tune the coefficients of this new, simplified kingDanger calculation.

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 12518 W: 2795 L: 2656 D: 7067
http://tests.stockfishchess.org/tests/view/5befadda0ebc595e0ae3a289

LTC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 164771 W: 26463 L: 26566 D: 111742
http://tests.stockfishchess.org/tests/view/5befcca70ebc595e0ae3a343

LTC 2, rebased on Stockfish 10 beta:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 75226 W: 12563 L: 12529 D: 50134
http://tests.stockfishchess.org/tests/view/5bf2e8910ebc5902bcecb919

Bench: 4001111

### CODE REVIEW

**Comment by snicolet** [comment]
Hmm, it seems that there is some overlap in this simplification with the tuned values in https://github.com/official-stockfish/Stockfish/commit/b92206305fb9a246c4a86a1f5235e47b70fb63ed

So I would ask you to synchronize your master branch on the current master, and test the simplification again at LTC, please :-) (as soon as the fishtest site is back, of course). Thanks in advance!

**Comment by Vizvezdenec** [comment]
@snicolet also it overlaps with my passed STC - I prefer to test for possible elogain first tbh :)
http://tests.stockfishchess.org/tests/view/5bf1a6880ebc595e0ae3c546

**Comment by Kingdefender** [comment]
To be honest, this is a bit surprising. Maybe in general, King Safety could be tuned down for VLTC? Also I notice, the STC of this is much more convincing than the LTC. Compare with Alpha Zero, should we simplify away all pattern recognition. Not really my favorite simplification :)

**Comment by Mindbreaker1** [comment]
At 164k games you are almost certainly giving up Elo.  Not a lot, but something.  And it could be worse at longer time controls.  Please test at VLTC before making this change.

**Comment by 31m059** [comment]
@snicolet Please see the new LTC result, rebased on the Stockfish 10 beta.  If anything, this appears to be an improvement on the earlier result.

**Comment by 31m059** [comment]
@Kingdefender Please allow me to clarify: this does not simplify away king tropism altogether.  We currently use tropism in two places: once with CloseEnemies (linear in middlegame, zero in endgame) and once with king danger (quadratic in middlegame, linear in endgame).  The claim of this patch is that the second is unnecessary, and the first is enough to evaluate accurately.

**Comment by Kingdefender** [comment]
Thanks very much for the explanation. I was not aware of the possible non orthogonal behaviour that is possible this way, that would indeed be an explanation for your results I coould accept :) Stockfish has tried hard to put everything related to king safety in that block, but it may not always be possible/desirable, if you don't want the exponential behaviour for instance (rapidly growing terms I mean).

Thanks again for pointing this out! Have to look more closely at recent changes in evaluation I suppose, and some catching up to do.

**Comment by Vizvezdenec** [comment]
well it's absolutely OK and clean simplification, congrats! I will try my further attemps based on it :)

**Comment by snicolet** [comment]
Merged via 6e66e7aae28ab087ad816589c0d54851993f2e4a, thanks :-)

**Pull request closed without merging**
