### PR TITLE
Change c style casts to cpp static_cast

### PR DESCRIPTION
**Pull request by Disservin**
Change all C Style casts to C++ casts, for better readability and checks by compiler.
Furthermore there should be no difference in the generated assembly and thus no performance hit. 

No functional change
bench: 4156027

### CODE REVIEW

**Comment by dubslow** [comment]
We should be clear about what is what.

First, `int(x)` is *not* a C-style cast. `(int)x` is a C-style cast. You change both styles here in this patch. However, it is stated on the internet that C++ `int(x)` syntax is in fact equivalent to a C style cast, and all the dangers that entails.

Second, based on Discord at least, there's a lot of opinion that `int(x)` is much more readable than `static_cast<int>(x)`. The latter however brings more safety for various reasons.

However, safety matters a lot more for complicated object hierarchies, where as a relatively simple set of enums subclassing `int`, where all we do is upcast to `int`, I don't believe a lot of extra safety is gained, and instead all we get is wasted time for reading eyes to parse what the line of code does.

For non-numeric types "proper" casts should be done, but for specifically numerics, and especially `int` subclasses being upcast back to `int`, I think it's better to select for readability over non-existent safety benefit.

So, for `int` only, I'm -1 on this PR -- altho I would be in favor of getting rid of the various `(int)x` usages that still exist in the codebase in favor of `int(x)`.

**Comment by Disservin** [comment]
Yeah makes sense, didnt think about `int(x)`, though I'd appreciate some general coding standard for sf, which well will not happen very likely idk how other open source project treat this but for example fishtest has an autoformatter iirc and is an entirely different topic.

Though in case a different type of cast is required like `reinterpret_cast` it would be nice to have a matching code style and while `int(x)` achieves the same as `(int)(x)` (C-like cast notation vs Functional notation).
Using `static_cast<int>()` would set a code style for the future and also include checks to be done at compile and avoid potential dangerous conversions.

"C-style casts and functional notation casts are largely functionally equivalent. However, when they do not invoke a converting constructor, C-style casts are capable of performing dangerous conversions between unrelated types and of changing a variable’s const-ness. Attempt to do these things with an explicit C++-style cast, and the compiler will catch the error. Use a C-style or functional notation cast, and it cannot."

Taken from [here](https://rules.sonarsource.com/cpp/RSPEC-871).

**Comment by dubslow** [comment]
See also https://stackoverflow.com/a/332086 . Apparently the "function style cast" `T(something)` is in fact interpreted as a C-style cast, `(T)something`, even tho `T(something, something_else)` is a constructor call. That honestly sounds like a C++ design flaw.

Several commentors do mention that, as an exception, they allow non-C++ casts for numeric types only, while using C++ casts for non-numerics. That is I believe a good choice, and appropriate for Stockfish as well, as I said in my previous comment. (...and `int(x)` notation should always be preferred over `(int)x` spelling.)

**Comment by snicolet** [comment]
I think I prefer the lighter `int(x)` for casting to int.

**Comment by Disservin** [comment]
In light of popular opinion I will close this although the CPP way would be to always use `static_cast`

**Pull request closed without merging**
