### PR TITLE
Misc edits 2

### PR DESCRIPTION
**Pull request by Rocky640**
More edits, followup on comments to pr # 1141

### CODE REVIEW

**Comment by snicolet** [comment]
@Rocky640 

It seems to me that the masking of the 8th rank is not necessary and slower: since bitboard is an unsigned int, the standard says that shifting g8 to the north or g1 to the south should just throw away the bit, and there is no undefined nor implementation dependant behavior in line 590 of evaluate.cpp. Or am I missing something ?

**Comment by Rocky640** [comment]
We must be careful when using things such as s + Up and check the relative rank of s first to avoid ending on the first rank.

But here we are using shift and as you explain, it seems completely safe.

shifting a uint_64 by x such that |x| < 64 should always produce predictable results.
e.g `shift<NORTH_EAST>(SquareBB[SQ_B8])` is always  0
and `shift<NORTH_EAST>(Rank8BB)` is also 0.

**Comment by mcostalba** [comment]
@Rocky640 Not a native speaker, but to me sounds better:

```
ForwardBBRanks, forward_ranks_bb
FileForwardBB, forward_file_bb

```

**Comment by mcostalba** [comment]
@Rocky640 why you changed:

```
    b = pos.pieces(Us, PAWN) & ~TRank7BB;
    b = shift<Up>(b | (shift<Up>(b & TRank2BB) & ~pos.pieces()));

into 

    b  = shift<Up>(pos.pieces(Us, PAWN)) & ~(pos.pieces() | TRank8BB);
    b |= shift<Up>(b & TRank3BB) & ~pos.pieces();
```

**Comment by Rocky640** [comment]
Mainly, I wanted to move the & ~pos.pieces()  from line 3 to line 2.
such that, after those 2 lines, b contains all the possible pawn push.

Also, current master line 2 looks a bit complicated with those nested shifts

Following @snicolet snicolet comment I was about to change this to
```
/// Find squares where our pawns can push on the next move
b  = shift<Up>(pos.pieces(Us, PAWN)) & ~pos.pieces();
b |= shift<Up>(b & TRank3BB) & ~pos.pieces();
```

By the way, what is the meaning of T in TRankxBB ?

**Comment by mcostalba** [comment]
@Rocky640 Meaning of T in TRankxBB is "Template parameter", actually it is not a good name, the concept there is that is a **parametric** constant, i.e. TRank2_BB can mean rank 2 or 7 according to color. But I admit the T is there mainly for historical reasons, may be **P** suffix (as parametric), or **R** (as relative) could be better, but changing all occurrences in SF is huge (and deserves a separated patches) and the advantage is very unclear anyhow.

**Comment by zamar** [comment]
Please resolve the merge conflicts

**Comment by Rocky640** [comment]
Sorry, I will open another request, it will be easier.

**Pull request closed without merging**
