### PR TITLE
Add Stockfish namespace.

### LINKED ISSUE #3350: Adding a stockfish namespace for all symbols.
While including this project into another project, it's easy to get namespace pollution and it's even possible to have conflicts.

Do you think it would be possible to add a namespace for all files?

I acknowledge it can break the build for people who linked to it, so it may be something to do with a major update, but in the long run, I think it would make the code simpler to use by others.

What do you think?

### PR DESCRIPTION
**Pull request by ddobbelaere**
Closes #3350.

I've verified that the binaries are equivalent (using the Perl script of https://stackoverflow.com/a/8141548). 

No functional change.

### CODE REVIEW

**Comment by vondele** [comment]
so, if I understand correctly, the advantage of this patch would be that it would be more easy to use SF as a library, right?

**Comment by ddobbelaere** [comment]
@vondele Yes, absolutely. Note that lc0 encapsulates all namespaces/classes with `lczero` namespace, just saying :)

**Comment by vondele** [comment]
so have you checked if any symbols leak our namespace after this change?

**Comment by ddobbelaere** [comment]
@vondele I don't think so. Everything is wrapped in Stockfish namespace. As such, only this namespace is visible to the outside world, if build as a library or bundled with other sources. Everything else stays the same (e.g. unnamed namespaces stay unnamed). I've checked that the resulting binaries are equivalent (same code and data segments etc.). They still differ because of namespace name mangling.

**Comment by ddobbelaere** [comment]
I've checked manually with `nm stockfish | c++filt | less` and looks good. Sample output:

```
0000000001986960 b Stockfish::Conditions
0000000001872ae0 B Stockfish::cuckooMove
0000000000422ad0 T Stockfish::MainThread::check_time() [clone .part.0]
0000000000410e40 T Stockfish::MainThread::search()
000000000041b290 t Stockfish::MainThread::~MainThread()
000000000041b280 t Stockfish::MainThread::~MainThread()
000000000041b280 t Stockfish::MainThread::~MainThread()
00000000004173e0 T Stockfish::MovePicker::next_move(bool)
00000000004047d0 t Stockfish::MovePicker::next_move(bool) [clone .cold]
000000000188cc20 B Stockfish::RookMagics
000000000196cd24 B Stockfish::Tablebases::ProbeDepth
```

**Comment by snicolet** [comment]
Related discussion in https://github.com/deepmind/open_spiel/pull/496 , where it is advocated to use the UCI protocol instead of recompiling Stockfish as a part of a larger project.

**Comment by ddobbelaere** [comment]
Ok, whatever then, I'll  assume that's a veto...

**Comment by snicolet** [comment]
?

**Comment by ddobbelaere** [comment]
Let me explain it if you don't get it: if the only thing you have to say is that "in general, it's better to use UCI and not link to SF library or bundle with SF sources", but you don't explicitly say this whole PR is a good or bad idea, nor have any good word/thumbs up to spare for it, I'll take that as a no.

**Comment by vondele** [comment]
I think that was just a reference to a comment... we tend to look for consensus, and I'm happy to take various kinds of inputs on PRs, especially of this nature. So, I suggest you leave it open. I could definitely imagine situations where it makes sense to be able to compile in an engine.

**Comment by Sopel97** [comment]
yes please

**Comment by noobpwnftw** [comment]
I also like this change, although I think the function in "main.cpp" shall be explicitly excluded from the namespace. :)
If someone is including that file when linking Stockfish as a library, he must did it wrong.

**Comment by noobpwnftw** [comment]
I also like this change.

**Comment by adentong** [comment]
I don't really have an opinion on this, but I just want to say there's no reason to react so strongly towards snicolet's comments... No one's trying to screw with you or deny your contribution or whatever, so just take it easy

**Comment by ddobbelaere** [comment]
Yes, I'm not too proud on the strong reactions from my part my and want to express apologies to @snicolet.

That being said, I'll also try to provide more elaborate opening posts with movitation in the future. The fact that @vondele had to ask was telling from that perspective :)

**Comment by miguel-l** [comment]
I guess I'm also more inclined to encourage interaction with Stockfish using UCI, since that is the commitment in the front page "Stockfish is a free, powerful UCI chess engine", etc.

That said, I'm also not strongly opposed to a change like this.

**Comment by ddobbelaere** [comment]
This PR is indeed not meant to discourage UCI usage, which is the preferred way of communicating.

However, I think this PR serves "orthogonal" use cases, and is only meant to serve those:
- Easier inclusion/linkage in GPL software.
- "Cleaner" software design by encapsulating all functionality in its logical namespace, like all major C++ projects do.

Specifically in the current NNUE era, we might benefit greatly from this ourselves to e.g. link trainer code (pytorch or whatever) to SF qsearch etc...

**Comment by miguel-l** [comment]
Thanks for sharing your thoughts. I changed my mind somewhat.

Maybe I slightly overreacted and panicked about the thought of possibly turning Stockfish into a library of some sort and having to support that :))

I was originally thinking about existing stuff like fishtest, etc. and couldn't see where this would fit, but with the relatively newer NNUE stuff, I guess this can only help.

**Comment by vondele** [comment]
I think indeed see this as a cleanup that might make future work easier, conceivably a training infrastructure or other similar projects where having multiple binaries talk via UCI is not a good way forward.

**Pull request closed without merging**
