### PR TITLE
Increase MAX_PLY from 128 to 250.

### PR DESCRIPTION
**Pull request by mstembera**
Since @jhellis3 closed this https://github.com/official-stockfish/Stockfish/pull/503
w/o explanation I'm submitting it myself.  Credit to him.

### CODE REVIEW

**Comment by mstembera** [comment]
Just realized @zamar asked for a regression test in https://github.com/official-stockfish/Stockfish/pull/503 so scheduled here
http://tests.stockfishchess.org/tests/view/5662889f0ebc5902cdc088e4

**Comment by joergoster** [comment]
Is there really any practical benefit? I still fail to see a problem when in late endgames and deep searches we sometimes hit MAX_PLY. It sure had no influence on the outcome of game 22 (TCEC).

**Comment by mcostalba** [comment]
I fail to understand the benefit of this patch.

**Comment by mstembera** [comment]
There are cases when we hit this limit.  Here is one such example
http://tcec.chessdom.com/archive.php?se=8&sf&ga=91
I'm sure it happens even more often to users doing long analysis.
I fail to see the reason to artificially limit depth any more than necessary.
With ever faster hardware we will have to increase it sooner or later.

**Comment by zamar** [comment]
The benefit is that if we can set the limit to 250 plies, we have solved this issue practically forever.

But currently the regression test is not doing well, so let's see how things go.

**Comment by mstembera** [comment]
The test failed
LLR: -2.95 (-2.94,2.94) [-3.00,1.00]
Total: 25267 W: 4762 L: 4966 D: 15539
which is rather surprising being that bench is the same so this is a non functional change(at the depths reached on fishtest anyway).  All I could think of is a slowdown due to the subtracts but fishbench gives
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1049437   1049225   212       
    StDev   28798     28656     4348      

p-value: 0.481
speedup: 0
```
Not sure what to make of it?

**Comment by lucasart** [comment]
@zamar @mstembera: depth limit is 127. So what ? Have you ever seen SF finishing depth 127, and playing a bad move that requires more depth (real game positions, not Uri Blass fabricated ones) ?

So the patch solves a non existing problem, adds complexity, and failed the test… Sure `(-3,1)` has 20% chance to fail a zero elo patch. But we've rejected plenty of patches that made sense and *simplified* code because they failed this test, I don't see any reason to make an exception for this one.

**Comment by lucasart** [comment]
Also, there has been no answer on the question I asked about stack usage in the original pull request. Has anyone looked at this ? The PV arrays total size is already a quadratic function of MAX_PLY. Then all the movepicker, search stack stuff...

First, we need to find a position where we can reach depth=250 (eg. a blocked KPsKPs ?). Then we need to be able to force the system to limit the stack size (is it possible on Linux or will the OS dynamically realloc the stack?), and see the lowest stack size needed not to segfault.

**Comment by zamar** [comment]
It failed the regression test, so it won't be committed.

**Pull request closed without merging**
