### PR TITLE
Clean-up Of Fix duplicated moves generation in movepicker.

### PR DESCRIPTION
**Pull request by peregrineshahin**
A clean-up dependent on pr/4405 that uses descriptive naming to better understand/read through the consistent connection between different parts of the code (movegen, movepicker and search).

No functional change

### CODE REVIEW

**Comment by dubslow** [comment]
Great work, thanks.

**Comment by Sopel97** [comment]
I suggest removing the negation from names and instead rewrite everything based on `pos.is_quiet` instead of `pos.is_not_quiet`.

**Comment by peregrineshahin** [comment]
> I suggest removing the negation from names and instead rewrite everything based on `pos.is_quiet` instead of `pos.is_not_quiet`.

Thanks for the suggestion that indeed would be even easier on the eye!
but the problem is we can't really do this without adding another check for `ttMove` here:
```
    // Step 12. A small Probcut idea, when we are in check (~4 Elo)
    probCutBeta = beta + 402;
    if (   ss->inCheck
        && !PvNode
        && depth >= 2
        && ttNonQuiet
        && (tte->bound() & BOUND_LOWER)
        && tte->depth() >= depth - 3
        && ttValue >= probCutBeta
        && abs(ttValue) <= VALUE_KNOWN_WIN
        && abs(beta) <= VALUE_KNOWN_WIN
       )
        return probCutBeta;
```
as we can't assume a `!ttQuiet` instead of `ttNonQuiet` and therefore an extra check for ttMove would be sadly needed...

**Comment by gonzalezjo** [comment]
> NONQUIETS || Type == EVASIONS || Type == NON_EVASIONS

For consistency, it might be better if `NONQUIETS` is `NON_QUIETS`, or `NON_EVASIONS` is `NONEVASIONS`. But that's small.

**Comment by vondele** [comment]
I will go instead with https://github.com/official-stockfish/Stockfish/pull/4405 with the change mentioned in that PR

**Pull request closed without merging**
