### PR TITLE
Enable LTO for clang

### PR DESCRIPTION
**Pull request by syzygy1**
Enable link-time optimization when compiling with clang.

No functional change.

### CODE REVIEW

**Comment by syzygy1** [comment]
It's not entirely clear to me why LTO was not already enabled for clang.

If there are old Linux distributions out there for which LTO is broken, perhaps it is time to update...

**Comment by erbsenzaehler** [comment]
We already do profile-builds when on macos. See line https://github.com/official-stockfish/Stockfish/blob/83c828f31ef3c18dd3718f7935484111872e7ecd/src/Makefile#L305 Maybe we can remove this special case in the process here

**Comment by syzygy1** [comment]
@erbsenzaehler 
I see you were on this before: https://github.com/official-stockfish/Stockfish/pull/907/files

In that discussion @vondele mentions fishtest. Indeed it seems important that we don't break fishtest compiles if we can. But I guess clang is only the default on MacOS, and there LTO is enabled already.

So it seems safe to remove LTO as a special case for MacOS and instead enable LTO for clang more generally...

**Comment by syzygy1** [comment]
Travis shows that there are still clang installations that lack the LLVMgold plugin.

Three options:
- leave things as they are (which is a bit of a shame since clang with LTO is becoming competitive);
- let the Makefile check whether LTO works for clang and disable it otherwise; or
- somehow disable LTO for Travis by tweaking .travis.yml.

**Comment by erbsenzaehler** [comment]
I tried to fix the travis build by using a newer a newer version of clang. While at it, I bumped the gcc version,too. Maybe you can give it a try

https://github.com/erbsenzaehler/Stockfish/commit/07c26f274c6d3947b0a7edf0fb83a102bf22125f

**Comment by syzygy1** [comment]
Thanks, giving it a try!

**Comment by syzygy1** [comment]
@erbsenzaehler Excellent, this fixed the problem for Travis.

**Comment by snicolet** [comment]
Err, I would rather not to bump the gcc version, let's keep this PR clang related as its name says :-)

**Comment by syzygy1** [comment]
You have a point there. I'll bump back the gcc version later today.

**Comment by snicolet** [comment]
Merged with https://github.com/official-stockfish/Stockfish/commit/ef618863325a34c7bcbd56930184b5a3d9aed74a, thanks!

**Pull request closed without merging**
