### PR TITLE
King safety and rook mobility parameters tweak

### PR DESCRIPTION
**Pull request by IIvec**
STC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 19280 W: 3595 L: 3373 D: 12312

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 221405 W: 28940 L: 28220 D: 164245

### CODE REVIEW

**Comment by lucasart** [comment]
What does rook mobility have to do with king safety ? Have both components of the patch been tested independently ?

**Comment by MichaelB7** [comment]
It took 221,000 games to pass LTC with a 0.3% gain.  Indeed, tuned values could just about be retuned after every successful functional patch.  This was not a good use of resources.   The patch itself is irrelevant- there is no gain and there is no loss.  But we did run 221,000 games at LTC.  My recommendation is that we cap LTC runs to pass at 125,000 games or so.  Totally ambivalent whether this patch is committed or not , but I do agree with @lucasart's oberservation why these values were not tested independently.

**Comment by IIvec** [comment]
@lucasart :
King safety values were tested here:
http://tests.stockfishchess.org/tests/view/58ffa5060ebc59035df33f61
Rook mobility values were tested here:
http://tests.stockfishchess.org/tests/view/58cee2520ebc59035df33002
http://tests.stockfishchess.org/tests/view/58d405320ebc59035df3311a

This is a classical combo patch.

@MichaelB7 : there is 1.13 Elo gain in this patch, and this gain is with greater probability than when SPRT passes in fewer number of games.

By the way, is SPRT with cap still an SPRT?

**Comment by Vizvezdenec** [comment]
Tuning patches usually need a lot of game to pass LTC which doesn't make them "bad" patches at all.

**Comment by locutus2** [comment]
Congrats too!

**Comment by AlexandreMasta** [comment]
I think that the king safety part of the patch should be tested separately. It was not tested at LTC and problably, from results, it is the one that is carrying the patch at LTC while the rook mobility bonus is just delaying the outcome.
So you will be sure that the king safety part is enough to be committed, not the whole combo.

**Comment by FauziAkram** [comment]
The patch passed both STC and LTC, so it should be eligible to be merged, if someone else want later to try some other experiment such as reverting back the Rook mobility changes, thinking that it will bring some gain he is free to do it after this patch gets merged, at least that is my point of view.

**Comment by MichaelB7** [comment]
@llvec Thanks for the informative response , was not aware. Congrats on your patch.

**Comment by IIvec** [comment]
@MichaelB7 : Thanks and you are welcome.

**Pull request closed without merging**
