### PR TITLE
CI/CD: play games

### PR DESCRIPTION
**Pull request by vondele**
this action plays games under fast-chess with a `debug=yes` compiled binary.

It checks for triggered asserts in the code, or generally for engine disconnects.

No functional change

### CODE REVIEW

**Comment by Disservin** [comment]
I think it'd be useful to upload the log as an artifact in case something goes wrong and isn't quite reproducable

**Comment by vondele** [comment]
hints on how to do that welcome, but yes that's on option. It is shown in the terminal action output though, so can be obtained already. In many cases, rare bugs can not be reproduced from the game log, as they are at given TC, not depth or nodes, and the state of the Hash is essentially not reproducible.

**Comment by vondele** [comment]
Like this file `https://github.com/official-stockfish/Stockfish/suites/25193636738/logs?attempt=1` is a zip containing the log. Can be obtained from:

image

**Comment by Disservin** [comment]
```
      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: fast-chess-log.txt
          path: fast-chess/fast.log
```

i think this should already work, not entirely sure about the directory structure

> rare bugs can not be reproduced from the game log, as they are at given TC, not depth or nodes, and the state of the Hash is essentially not reproducible.

with the log we also get the last node count, so in theory one should be able to reach the same state by running a series of `go nodes` deduced from the log

**Comment by Disservin** [comment]
ah if we can download the workflow log itself then no need for a separate artifact I think

**Comment by vondele** [comment]
OK, and sorry for editing your message instead of quote-replying ...

**Pull request closed without merging**
