### PR TITLE
rename shift variables.

### PR DESCRIPTION
**Pull request by protonspring**
I know. . I'm a horrible person and this is not the way to contribute to an open source project, but where variable names are explicitly incorrect, I feel morally obligated to at least suggest an alternative.  There are many, but these two are especially egregious.

shift\<Left\> does NOT "shift left," it actually shifts either NORTH_WEST or SOUTH_EAST.
shift\<Right\> does NOT "shift right," it actually shifts either NORTH_EAST or SOUTH_WEST.

### CODE REVIEW

**Comment by mcostalba** [comment]
It is a bit more verbose but it's ok for me :-)

...but consistency is more important than nitpicking, so please change also all the other occurrences (there is one in evaluate.cpp and another in movegen.cpp)

**Comment by snicolet** [comment]
@protonspring Thanks a lot!

Merged via https://github.com/official-stockfish/Stockfish/commit/820c5c25b649d6bdd51bed14a16efdc11719b588

PS: I have slightly edited your commit message.

**Comment by protonspring** [comment]
Np.  You are welcome to do anything you like with my stuff.

**Comment by mcostalba** [comment]
@snicolet nice!

I like pawn_attacks() helper, to be very nitpicking I would think to move it to bitboard.h under 

```
template<Direction D>
constexpr Bitboard shift(Bitboard b)
```

And rename it to **pawn_attacks_bb()** for consistency.

**Comment by snicolet** [comment]
@mcostalba 
Yes, I hesitated between placing it there and was finally attracted by the other attacks_from() in Position.h, but I have no strong opinion about it :-)

**Comment by snicolet** [comment]
And I also forgot to remove all the extra spaces in declarations like the following ones, will clean up these at the first occasion :-(
````
const Direction Up   = (Us == WHITE ? NORTH      : SOUTH);
````

**Comment by protonspring** [comment]
Aren't those white spaces to align the = ?

**Comment by mcostalba** [comment]
@snicolet while there please use upper case for template parameter and eventually add some spaces between function definition:

```diff
 }
 
+
 /// pawn_attacks_bb() returns the pawn attacks for the given color from the
 /// squares in the given bitboard.
 
-template<Color c>
+template<Color C>
 constexpr Bitboard pawn_attacks_bb(Bitboard b) {
-  return c == WHITE ? shift<NORTH_WEST>(b) | shift<NORTH_EAST>(b)
+  return C == WHITE ? shift<NORTH_WEST>(b) | shift<NORTH_EAST>(b)
                     : shift<SOUTH_WEST>(b) | shift<SOUTH_EAST>(b);
 }
 
+
 /// adjacent_files_bb() returns a bitboard representing all the squares on the
 /// adjacent files of the given one.
```


sorry to be nitpicking :-)

**Comment by snicolet** [comment]
@mcostalba Noted fr correction, thanks.

**Pull request closed without merging**
