### PR TITLE
Cm regression

### PR DESCRIPTION
**Pull request by VoyagerOne**
HOLY regression Batman!

LLR: 2.97 (-2.94,2.94) [-1.50,4.50]
Total: 10786 W: 2040 L: 1907 D: 6839

### CODE REVIEW

**Comment by VoyagerOne** [comment]
Please merge this...as soon as convenience.

**Comment by lp--** [comment]
It did not pass LTC

**Comment by VoyagerOne** [comment]
I never tested it at LTC...
Should I?

**Comment by lp--** [comment]
0 elo patch has 20% chance to  pass sprt [-1.5, 4.5] which is statistically insignificant to revert. Of course, in the past maintainers did revert patches on the basis of statistically insignificant results, but this is not preferrable mode of operation. I don't know know what they will decide to do  for this patch on the basis of only STC test.

**Comment by VoyagerOne** [comment]
Ok...I will test it out LTC.

**Comment by lucasart** [comment]
To *prove* regression you need to run an `SPRT(-X,0)` test. `SPRT(-1.5,4.5)` is completely useless, whether to prove an elo gain or a regression.

**Comment by lucasart** [comment]
Basically what you have shown is that your patch:
* passed `SPRT(-3,1)`
* failed `SPRT(-4.5,+1.5)` by retesting it (or testing the revert patch for `SPRT(-1.5,4.5)` which is equivalent).

You do not understand tatistics, and you are just mesuring noise.

**Comment by zamar** [comment]
As already pointed out by others, so far the test results are inconclusive. Thus I'm closing the request.

Please open a new request after gathering conclusive results.

**Pull request closed without merging**
