### PR TITLE
Small tweaks to recent code changes

### PR DESCRIPTION
**Pull request by mcostalba**
No functional change

### CODE REVIEW

**Comment by VoyagerOne** [comment]
The code change in the LMR is somewhat cryptic... IMO.
I like code where you don't have to "think" such as the original.

**Comment by snicolet** [comment]
Line 938: I'm neutral for that change. It is interesting that the generated binary is exactly the same, at least for the Clang compiler.

Line 1024: I agree with VoyagerOne, the original is pedestrian but maybe easier to reason about.

**Comment by joergoster** [comment]
We use this kind of boolean arithmetic in other places, too. Even starters should grasp this very quick, imo.

**Comment by mcostalba** [comment]
@snicolet ok, I have reverted line 1024 to original form. I have added a note in commit message for future reference in case it will turn out useful someday.

**Comment by snicolet** [comment]
Merged via fae57273b20468f534cce5843152a21214b5da05, thanks!

**Pull request merged**
