### PR TITLE
Retire rook contact checks

### PR DESCRIPTION
**Pull request by jcalovski**
Remove rook contact check bonus and in return increase rook checks

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 34114 W: 6363 L: 6265 D: 21486

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 61776 W: 9349 L: 9289 D: 43138

bench: 7681680

Resolves #442

### CODE REVIEW

**Comment by jcalovski** [comment]
Rocky raised some concerns given this comes from a master base prior to the check score bonus, just wanted to point this out so if there is any need to take further action mention it here.

**Comment by mcostalba** [comment]
I am a bit wondering about this patch. Indeed we remove a concept (contact check) that has been there since always and try to balance it with a different concept (safe checks). I am not sure we really need this. Considering it is also a simplification and not an ELO gainer, I would be quite conservative on this patch.

**Comment by jcalovski** [comment]
I leave this one completely to the maintainers and yourself Marco. I don't have any strong objections or opinions either way so do as you may. Although I generally don't think Rook contact checks are of significant threat in most cases whereas Queen contact checks I can understand pose significant mate threat.

**Comment by lucasart** [comment]
@mcostalba: seems fine. what's the risk?

**Comment by zamar** [comment]
Because king safety values were just recently retuned, we need to spin this patch one more time.

I suggest STC [-4, 0]

**Comment by zamar** [comment]
Sorry, I meant LTC [-4, 0]

**Comment by zamar** [comment]
@jcalovski: Can you please reschedule the test one more time at LTC [-4, 0]?

**Comment by Rocky640** [comment]
@zamar 
He did the test a few hours ago, but with [-3,1]. This should be fine isn't it ?
http://tests.stockfishchess.org/tests/view/5614ddff0ebc597e4f23e649

**Pull request closed without merging**
