### PR TITLE
Integrate syzygy in automated testing.

### PR DESCRIPTION
**Pull request by vondele**
extends valgrind/sanitizer testing to cover syzygy code.

To do so, 3 and 4 man tablebases (~4Mb) are included in the tree, the same approach as adopted by python-chess (and source of the files).

related to the thread in #1477

possible follow-ups:
  - verify unchanged bench with TB.
  - include more TB sensitive positions in bench.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Wow!  You really would like to add TB files in master sources?!?!

This is really too aggressive approach.

What could be done (as is done for opening books in fishtest), is to create a specific **branch**, say TB_test and in the trevis script to download from there (as is done in fishtest worker), in this way you don't pollute master with debug stuff (as is done in tune branch).

Actually we can even do even better and do **remove** from master current tests script needed by Trevis

**Comment by vondele** [comment]
yes, I would add that to master. As for the tuning branch, adding this on a different branch only adds overhead in maintenance, and increases the difficulty in use. Directories are perfectly fine to separate sources from e.g. tests within one project. 

If you want to show people SF is a very nice lean implementation, you direct them to read the sources, not have them measure the size of a github repository.

**Comment by mstembera** [comment]
One of the reasons(I can list others) I originally did the integrated 4men was to help TB test coverage.  I can update it if it would be considered.
https://github.com/mstembera/Stockfish/tree/4men
http://tests.stockfishchess.org/tests/view/56080fef0ebc597e4f23e2e9
It adds a large cpp but it's not code just data that will never change so no additional code maintenance.

**Comment by mcostalba** [comment]
TB code is not changed by usual submitters.

People tweaking that code is very few and very rarely. And when it happens, they also fully verify for no functional change.

Adding as a test run for each patch is really overkill and pretending people to clone/download tb men together with sources is really no sense to me.

Regarding the supposed added maintenance because tb are stored in a branch, this is void argument because the files, like opening book never change, so there is no maintenance as there is not in fishtest for the books that are there since years and never touched.

Regarding difficult to use, also this is moot because TB are tested eventually through a trevis ci script, so in a fully automatic way.

**Comment by snicolet** [comment]
Just as a side note, the following article has a KRpp vs KRp position where the defender has to find a critical plan to transpose into a drawn 6 pieces table KRpp vs KR position:
https://en.chessbase.com/post/endgame-tablebases-a-short-history

Could be a good candidate for inclusion in the bench.

**Comment by Nordlandia** [comment]
4-men syzygy help trivially. 5-men is when it start to influencing gameplay.

**Comment by Mindbreaker1** [comment]
I'd love to see another 4-man test.  Maybe comment out any code that is for current 4-man situations unless the 4-man automatically takes precedence.  You really don't need rules of thumb, if you have the truth.
I think this can also accelerate testing, because more games will end sooner.

**Comment by lucasart** [comment]
Please don't merge this! Git is not designed for managing huge binary files. Only source code. This will bloat the repo like hell. Anyway 4men is not remotely enough.

**Comment by Nordlandia** [comment]
@Mindbreaker1 Agreed. 4-men is better than nothing.

**Comment by snicolet** [comment]
My preferred approach would be the following:

a) keep `appveyor.yml` and the test directory in the master branch, because it helps non-professional developers to learn about the system -- it will raise the level of the community to keep our tests scripts it in the master branch.

b) (optional) put `appveyor.yml` in the test directory. Optional, because I don't know if the CI allows to have an `appveyor.yml` file in a subdirectory of a project.

c) put the tablebases in another branch or even another stable website, and let Trevis and our scripts download a zip archive at the start of the automated testing.

The rationale of (c) is that the tablebase are not necessary for compiling Stockfish (for newcomers and hobbyists, not everybody in the world has a fast cable connexion as in Europe), and more generally that we don't want fishtest contributors re-downloading all the tablebase at the start of each test -- Github may not appreciate having 150 machines downloading binaries at the same second, and if I remember well Bojun Guo had problems in his chinese farm with download bandwidth at the start of each test even with current master branch.

So (a) +(c) is a good compromise, in my opinion, between exposure of the test procedures and size of download for the most general cases.

@vondele @mcostalba 
Would it be difficult to rewrite the pull request along these lines? Adding the scripts of WOnder93 given in https://github.com/official-stockfish/Stockfish/commit/8ff2fcf299ac621779dc167ce750ba73aaae90a4 would be a nice plus for automatic verification of correct TB support (up to 4 men for the moment)

Thanks if you could do that :-)

**Comment by mcostalba** [comment]
@snicolet what is your opinion about to download and test TB for each PR/commit?

To me Travis CI is already very slow now and the additional burden of TB download and test for each PR is acceptable only if this really brings in an improvement in testing, but considering that TB related work is seldom and well spaced apart in time (a couple of times per year), I am not sure it is a good idea.

**Comment by WOnder93** [comment]
@mcostalba Perhaps we could have the TB tests trigger only on an explicit command in the commit message. For example: if the commit message contains the string "TB change", then download TBs and run TB tests, otherwise skip that step.

**Comment by Hanamuke** [comment]
Maybe it is simply possible to detect a change in the syzygy repertory ?

**Comment by Stefano80** [comment]
Well Marco, we don't change TB code because it is not testable and we do not want to test it because nobody changes it.

It sounds circular, and we should somewhere break this circle.

**Comment by mcostalba** [comment]
@Hanamuke this is a good idea, for instance something like this in the script:

` git log --name-only -1 HEAD | grep syzygy | wc -l`

**Comment by vondele** [comment]
@snicolet I have created a new PR #1518 where the TB are downloaded as needed by the testing script, which seems to work.

The time needed for the additional testing is small (in fact hard to see a difference compared to the large fluctuations in testing time in travis), I see no need to make the testing procedure more fragile and more complicated to test only from time to time.

**Comment by snicolet** [comment]
@vondele Thanks, my plan is to merge PR #1518 quite rapidly (tell us when you think it is ready), and add the two suggestions in a separate commit soon afterwards

* verify unchanged bench with TB (with a long run)
* include more TB sensitive positions in bench.

Then we can estimate the load we impose on Travis and if we need/want the trick of testing only from time to time.

Thinking about it, we can easily separate the valgrind test (which is fast and can be a bench at depth only 10 as you do) from the syzygy covering run (verifying the bench with tablebases with interesting positions in the bench at higher depths, for instance 22) which could be triggered with the "syzygy in commit name" trick proposed by Hamanuke and Marco.

**Comment by mcostalba** [comment]
@snicolet just to be clear. Proposed tricky checks if at least one changed file is in syzygy directory. It does not rely on commit log message.

**Comment by snicolet** [comment]
Closing, after c959871a59d106aa0294916890c31c475aa195ea has been merged. Thanks!

**Pull request closed without merging**
