### PR TITLE
Edge distance

### PR DESCRIPTION
**Pull request by lucasart**
Instead of crafting a clever formula to calculate the array offset, simply use a
3 dimensional array. Remove the comment while at it, because now the code is
now self-documenting.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Personally I prefer current version.

**Comment by Nazine** [comment]
The current version is indeed quite better.

**Comment by zamar** [comment]
Personally I prefer the new version. But seriously: I'm fine with either way...

**Comment by lucasart** [comment]
So? Will this be merged, or should I close the pull request?

On a side note, I found it rather annoying the way Marco dealt with my previous pull request:
* arguing for the sake of arguing: no nit to small to pick…
* in the end, after trying every possible far fetched arguments, accepting that I was right, and basically committing my patch with his name on it…
* this patch is really the only difference between his version and mine. my patch is the logical one (let the compiler calculate array offsets), but he won't admit it in order to remain self-consistent or whatever…

A better way of dealing with it could have been to: 1/ commit the patch 2/ make the trivial changes (renaming a variable, changing a comment…) Don't you think ?

**Comment by zamar** [comment]
- Don't close it yet.
- Because this is one of those issues which is a question of taste, this pull request will stay open for a while so that everyone can give their input.
- Then based on input we get from people, Gary & I will then make a decision whether it gets committed or not...

The  current status is:  
- Lucas has sent a patch and given a reason why he wants it to get committed.
- Marco has given his input that he prefers the current version.
- Joona has given the input that he prefers the patch to be committed.

So arguments pro and against the patch are welcome, but no personal attacks, please.

**Comment by lucasart** [comment]
arguments pro:
* let the compiler calculate array offset instead of doing it manually, makes code easier to understand.
* code becomes self-documenting, so the comment that was needed to explain the array index calculation formula can be removed.

**Comment by jhellis3** [comment]
Lucas's version is more readable IMHO...

**Comment by glinscott** [comment]
I'm also fine with either approach.  I think the version Lucas has proposed is slightly easier to read.

**Comment by tomtor** [comment]
I agree that Lucas's version is slightly more readable

**Comment by mstembera** [comment]
I think in cases where it's a close call it's nice to give the original author the benefit of the doubt and go with their version.

**Comment by mcostalba** [comment]
In this case the original author is lucas.

**Comment by lucasart** [comment]
Come to think of it, I can find one thing to improve on this patch. Normally, array indices are sorted by increased cardinality. For example, it's `psq[color][pieceType][square]` not `psq[square][pieceType][color]` or any other permutation. This consistency throughout the code means you don't need to think in which order array dimensions are, so it's nice to follow it.

So it should be `Bonus[pieceType][edgeDistance][rank]`, not `Bonus[pieceType][rank][edgeDistance]`.

@mcostalba: was that your problem with this patch ? It's a trivial fix, I can push a commit for it if you want.

**Comment by mcostalba** [comment]
@lucasart please keep it as is, array definition is fine, easier to understand and more closely resembles old values order.

It seems most people think your patch is better so no problmem for me to commit your patch.

**Comment by zamar** [comment]
Okay, so we conclude that the patch will be committed.

Either Gary or I will do this during the weekend.

**Pull request closed without merging**
