### PR TITLE
PGO + LTO + static

### PR DESCRIPTION
**Pull request by mstembera**
Allow cross compilation of Windows binaries on a Linux system that are PGO, LTO, and statically linked.
This is the only way to produce such binaries I know of.  If we could also convince abrok to install mingw-w64 and wine 
$ sudo apt-get install mingw-w64
$ sudo apt-get install wine1.6
after this we would not have to make custom binaries for special purposes any more.

Full credit goes to: pasquale....@gmail.com
who posted the instructions here
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/B4RMSEbm1C0[1-25]

### CODE REVIEW

**Comment by zamar** [comment]
It's a long time since I cross-compiled last time...

CXX=x86_64-w64-mingw32-g++-posix

Is this going to create a 64-bit or 32-bit compile?

**Comment by mstembera** [comment]
It depends on whether you specify a 32 or 64 bit ARCH when invoking make.

**Comment by zamar** [comment]
The change looks fine for me, but I can't verify it as I currently don't have access to Windows computer.

If someone could please verify that the cross compiling works fine with new Makefile, I'd be happy to commit this.

**Comment by ppigazzini** [comment]
The change is working fine for me.

Clean virtual machine with Ubuntu 15.10
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get install mingw-w64
$ sudo apt-get install wine1.6
downloaded Stockfish-master
copied the new Makefile
make profile-build ARCH=x85-64-modern COMP=mingw -j 2
benched against a native Windows compile (mingw 5.20) in Windows 8.1

Results for 25 tests for each version:
             Native        Cross
             Base          Test           Diff      
Mean    1887647    1889870    -2223     
StDev    73626        91908       135823    

p-value: 0.507
speedup: 0.001

**Comment by zamar** [comment]
Reverted the patch, because it confused the build system.

**Comment by mstembera** [comment]
I opened this
https://github.com/official-stockfish/Stockfish/pull/511
which should be more robust but we probably need @glinscott to diagnose the issue is.

**Comment by braich** [comment]
Comparing UNAME with Linux is not enough.  Static + LTO can make broken executable on other Linux distributions e.g. Arch LInux. I've tested archlinux-2015.10.01 with mingw-w64-gcc 5.2.0-1. The resulting executable is broken.

**Comment by braich** [comment]
By the way there is no x86_64-w64-mingw32-g++-posix in archlinux-2015.10.01 with mingw-w64-gcc 5.2.0-1. In arch Linux x86_64-w64-mingw32-g++ is using posix threading model.

**Comment by braich** [comment]
@ppigazzini in Ubuntu 15.10 mingw-w64 is based on gcc 4.9.2. On my system gcc 4.9.2 generates executable that is faster than the one generated by gcc 5.2.0. So can you compare performance of Ubuntu cross-compiled executable with native windows executable compiled [with mingw 4.9.2?]( http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-posix/seh/)

**Comment by braich** [comment]
@mstembera abrok is already using PGO. Citation from [abrok.eu](http://abrok.eu/stockfish/):
"20.Oct.2013: now using profiling while building. resulting in slightly faster executables."

**Comment by ppigazzini** [comment]
@braich

compiler used on windows:
msys + mingw 4.9.2 (x86_64-4.9.2-release-posix-seh-rt_v4-rev4.7z)
msys + mingw 4.9.2 (x86_64-5.2.0-release-posix-seh-rt_v4-rev0.7z)

make directive:
mingw32-make profile-build ARCH=x86-64-modern COMP=mingw -j 7
(with LTO, no static for windows, static for crosscompile)

========================
Results for 25 tests for each version: (Base = 4.9.2 ubuntu ; test = 4.9.2 windows)

            Base      Test      Diff      
    Mean    2389745   2385141   4604      
    StDev   2055      2080      2573      

p-value: 0.037
speedup: -0.002

=========================
Results for 25 tests for each version: (Base = abrok; Test = 4.9.2 windows)

            Base      Test      Diff      
    Mean    2366617   2375508   -8891     
    StDev   5196      4738      7622      

p-value: 0.878
speedup: 0.004

========================
Results for 25 tests for each version:(Base = abrok; Test = 4.9.2 ubuntu)

            Base      Test      Diff      
    Mean    2371087   2381993   -10906    
    StDev   2319      2818      2378      

p-value: 1
speedup: 0.005

========================

I confirm your result, with my Ivy Bridge cpu, mingw 4.9.2 is faster than mingw 5.2.0

Results for 25 tests for each version: (Base = 5.2.0 windows ; Test = 4.9.2 windows)

            Base      Test      Diff      
    Mean    2351522   2374394   -22872    
    StDev   7283      8165      2219      

p-value: 1
speedup: 0.01

**Comment by zamar** [comment]
See #511 for further discussion around this topic.

**Pull request closed without merging**
