### PR TITLE
LMR - LastMove Bench:  3416811

### PR DESCRIPTION
**Pull request by VoyagerOne**
Decrease LMR if prior move is the last move.

Bench: 3416811

### CODE REVIEW

**Comment by ianfab** [comment]
@VoyagerOne Can you please add the test results?

**Comment by locutus2** [comment]
Congrats!

But something i don't understand about this patch. lastMove is only set true if searching a node is finished. So how can a move deeper the LMR condition be triggered because we have done a previous move so lastMove at this node (ss-1 from the view of the current node) should be false.

**Comment by VoyagerOne** [comment]
@locutus2 
Hmmm.... very good point!
According to dbg_hit_on I get about 9% hit.
I need to understand this a bit more...

**Comment by locutus2** [comment]
@VoyagerOne 
I think i understand now. The condition is triggered trough the singular extension search. ss->lastMove is before this set to false then singular search is done. If this fails low we triggers an extension and ss->lastMove is now true. So in the following (now extended) search of this move the condition get triggered. 

In short: All response moves to a singular extended move are searched with less reduction.

**Comment by VoyagerOne** [comment]
@locutus2 
Yeah- This seems similar to https://github.com/official-stockfish/Stockfish/pull/2146/files
So I think I might close this request.

Do you think there is a painless way of trying to achieve my objective of flagging the last move.

**Comment by locutus2** [comment]
@VoyagerOne 
This it not the same. There at the current node less reductions are done. With your idea a level deeper less reductions are done. But this PR should be helpful for you.

Simply move the variable **singularExtensionLMRmultiplier** to the stack and test `(ss-1)->singularExtensionLMRmultiplier`. That should be all.

**Comment by VoyagerOne** [comment]
@locutus2 
Ok, I just submitted at patch for the first scenario.
If this fails I will try initializing with zero (like my original)

Thanks so much for your help!

**Comment by locutus2** [comment]
@VoyagerOne 
Your new version seems to fail. One problem could be that your original version only does less reduction for the responses of the extended move. But the new version does less reduction for the responses of ALL moves at the node where the singular extension occurs (singularExtensionLMRmultiplier is not reset after the singular move).

But you could easily restore the old behavior by checking also `(ss-1)->moveCount == 1` because if a singular move was found it is the first one (the tt move).

**Comment by anshulongithub** [comment]
After the recent merges into master, i think retest of this patch at STC ended in yellow, wanted to check if a speculative LTC shud be run and / or if we wud still like to merge this in. @VoyagerOne please advise.

**Comment by VoyagerOne** [comment]
@anshulongithub 
I think I might eventually close this PR.
There is a very high chance this is indeed a Elo gain.
But the code is ugly and not very logical...
Maybe when I have a bit more motivation, I will try to make more sense of this patch and implement it in a logical and clean way.

**Pull request closed without merging**
