### PR TITLE
Remove FutilityMoveCounts array.

### PR DESCRIPTION
**Pull request by protonspring**
This is a functional simplification that removes the FutilityMoveCounts array with a simple equation using only ints.

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 74187 W: 16223 L: 16205 D: 41759 
http://tests.stockfishchess.org/tests/view/5c75d4c50ebc5925cffd58cd

LTC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 69841 W: 11596 L: 11553 D: 46692 
http://tests.stockfishchess.org/tests/view/5c76308e0ebc5925cffd5d42

Bench 3210218

### CODE REVIEW

**Comment by DU-jdto** [comment]
Should this be retested? It clearly interacts with https://github.com/official-stockfish/Stockfish/commit/82ff04b992a53c757519a6ff61576ebd267c0cee .

**Comment by mcostalba** [comment]
@protonspring coudl you please rebase above current master, squash in a single commit and retest? Thanks.

**Comment by protonspring** [comment]
Sure, but last time I tried to "squash" something I destroyed the whole branch.  Any tips?  I'd probably just make a new PR, but I can try again.

**Comment by protonspring** [comment]
STC Passed again
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 14175 W: 3123 L: 2987 D: 8065 
http://tests.stockfishchess.org/tests/view/5c7ea9530ebc5925cffe052e

**Comment by mcostalba** [comment]
Thanks. I have started the LTC http://tests.stockfishchess.org/tests/view/5c7ebb1d0ebc5925cffe06f2
because bench changed, so let's follow the handbook.

**Comment by 31m059** [comment]
@protonspring Wow.  Excellent work!

LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 14175 W: 3123 L: 2987 D: 8065

LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 9900 W: 1735 L: 1597 D: 6568

**Pull request merged**
