### PR TITLE
AVX-512 was using SIMMD width of AVX-2 in nnue_common

### PR DESCRIPTION
**Pull request by maximmasiutin**
https://tests.stockfishchess.org/tests/view/6429681d77ff3301150cc2a2

### CODE REVIEW

**Comment by maximmasiutin** [comment]
Did not pass the self-test:
```
./cutechess-cli -engine name=Wide cmd=./stockfish-x86-64-vnni512-clang-new -engine name=Old cmd=./stockfish-x86-64-vnni512-clang-old -each proto=uci tc=inf/5+0.1 option.Hash=1024 option.Threads=8 -recover -openings file=UHO_XXL_0.90_1.19.epd format=epd order=random plies=6 -repeat -games 100 -concurrency 1 -ratinginterval 100 -sprt elo0=0 elo1=2 alpha=0.05 beta=0.05
Indexing opening suite...
Started game 1 of 100 (Wide vs Old)
Finished game 1 (Wide vs Old): 1/2-1/2 {Draw by 3-fold repetition}
Score of Wide vs Old: 0 - 0 - 1  [0.500] 1
Started game 2 of 100 (Old vs Wide)
Finished game 2 (Old vs Wide): 1-0 {White mates}
Score of Wide vs Old: 0 - 1 - 1  [0.250] 2
Started game 3 of 100 (Wide vs Old)
Finished game 3 (Wide vs Old): 0-1 {Black mates}
Score of Wide vs Old: 0 - 2 - 1  [0.167] 3
Started game 4 of 100 (Old vs Wide)
Finished game 4 (Old vs Wide): 1-0 {White mates}
Score of Wide vs Old: 0 - 3 - 1  [0.125] 4
Started game 5 of 100 (Wide vs Old)
Finished game 5 (Wide vs Old): 1/2-1/2 {Draw by 3-fold repetition}
Score of Wide vs Old: 0 - 3 - 2  [0.200] 5
Started game 6 of 100 (Old vs Wide)
Finished game 6 (Old vs Wide): 1-0 {White mates}
Score of Wide vs Old: 0 - 4 - 2  [0.167] 6
Started game 7 of 100 (Wide vs Old)
Finished game 7 (Wide vs Old): 0-1 {Black mates}
Score of Wide vs Old: 0 - 5 - 2  [0.143] 7
Started game 8 of 100 (Old vs Wide)
Finished game 8 (Old vs Wide): 1-0 {White mates}
Score of Wide vs Old: 0 - 6 - 2  [0.125] 8
Started game 9 of 100 (Wide vs Old)
Finished game 9 (Wide vs Old): 1/2-1/2 {Draw by insufficient mating material}
Score of Wide vs Old: 0 - 6 - 3  [0.167] 9
Started game 10 of 100 (Old vs Wide)
Finished game 10 (Old vs Wide): 1-0 {White mates}
Score of Wide vs Old: 0 - 7 - 3  [0.150] 10
```

**Comment by vondele** [comment]
so can be closed

**Comment by Sopel97** [comment]
SimdWidth is capped at 32 for legacy reasons. AVX512 is still used correctly regardless of that value.

**Comment by mstembera** [comment]
I believe the legacy reasons had mostly to do w/ loading/saving nets consistently and correctly across architectures but my memory is hazy.  It's not a bad idea to clean this up but it's not as simple as this PR.

**Pull request closed without merging**
