### PR TITLE
Cleanup movepicker.

### PR DESCRIPTION
**Pull request by Sopel97**

### CODE REVIEW

**Comment by Sopel97** [comment]
Sorry, I don't measure code complexity in lines of code. With that said though, I don't consider this a simplification, but a code improvement, and that's I'm testing it with non-regression bounds. I'm also looking for constructive criticism on this change and whether it could be improved further.

**Comment by Vizvezdenec** [comment]
This is not a simplification but a non-functional rewrite.
You yourself said that movepicker is barely readable for people who have never looked at it. 
Some stuff there is what I really like.
For example in current master we have 
https://github.com/official-stockfish/Stockfish/blob/master/src/movepick.h#L131
this things separated by lines but in actual movepicker they are not 
https://github.com/official-stockfish/Stockfish/blob/master/src/movepick.cpp#L59
which doesn't help readability whatsoever and is actually not how we usually do things in code - if function declaration is done with line separation we usually call it also with line separation.
Even in search it's called the same way - 
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L935
I haven't looked at other parts because code change is huge but at least this part probably should be rewritten into a more proper way.

**Comment by lucasart** [comment]
IMO, far too much time is wasted arguing about code formatting. If I were a maintainer, I would automate it, and kill once and for all these futile discussions, so that people focus instead on the *actual* topic.

Sure, no formatting tool is perfect, and no one ever fully agrees on which are the correct parameters to give to the tool.

All the discussions so far on this PR (and countless others…) focus on formatting trivia, instead of the actual code logic. Of course it's easy to criticize code formatting: everyone can offer opinions, and it doesn't require any homework to comment on such topics (whereas understanding the logic of the code and criticizing that, requires to do some homework).

**Comment by Vizvezdenec** [comment]
> 
> 
> Yeah, I don't get it. Spending one's own time is one thing; wasting fishtest resources is another.

Yeah, wasting fishtest resources for NNUE = false tests, for example, where 2000+ lines of code of classical eval give incredible 1,5 elo, and for some reason it's "okay".
I prefer people to try to refactor movepicker as part of the code that is often changed in order to get elo into smth meaningful than people trying to improve classical eval that is used by no one, not even stockfish itself in reality.
I honestly think that we should just delete classical eval alltogether - it will allow to clean massives of code not only in evaluate.cpp, but also in bitboard and position.

**Comment by Sopel97** [comment]
Wierdly, it seems to have failed non-regression. https://tests.stockfishchess.org/tests/view/60e43f13d1189bed718123f2

Can anyone actually measure a slowdown for this patch?

**Comment by ppigazzini** [comment]
In my tests (`bench 16 1 15 default depth [NNUE]`) is on par with master. 

- arch=x86-64-modern - Intel i7 3770k

```
bash bench_parallel.sh ./stockfish_master ./stockfish_3604 15 10 NNUE

sf_base =    1246045 +/- 13164
sf_test =    1252843 +/- 13007
diff =       6797 +/- 4748
speedup = 0.005455

bash bench_parallel.sh ./stockfish_master ./stockfish_3604 15 10
sf_base =    1586069 +/- 29585
sf_test =    1597496 +/- 31368
diff =      11427 +/- 3299
speedup = 0.007205
```

- arch=x86-64-bmi2 - Intel Xeon CPU E5-2680 v3 

```
bash bench_parallel.sh ./stockfish_master ./stockfish_3604 15 10 NNUE

base =    1240468 +/- 5856
test =    1256723 +/- 7880
diff =      16254 +/- 9896
speedup = 0.013104


bash bench_parallel.sh ./stockfish_master ./stockfish_3604 15 10

base =    1504425 +/- 7210
test =    1519106 +/- 12551
diff =      14681 +/- 15436
speedup = 0.009759
```

**Comment by vdbergh** [comment]
I have said this many times. Failing a non-regression test does not mean there is a regression. It seems that currently a neutral patch still has a probability of 23% of failing a non-regression STC+LTC combo (which is an improvement, it used to be 36%). Running only STC the probability is 12.3% which is still rather high.

IMHO for non functional changes the solution is to do just a speed test. For functional changes there is no good solution.

**Comment by ppigazzini** [comment]
Somebody coded also a Chess SPRT Calculator with the pass probability wrt the Elo :)
https://tests.stockfishchess.org/html/SPRTcalculator.html?elo-model=Normalized&elo-0=-2.5&elo-1=0.5&draw-ratio=0.82&rms-bias=30

**Comment by chuckstables** [comment]
> In my tests (`bench 16 1 15 default depth [NNUE]`) is on par with master.
> 
> * arch=x86-64-modern - Intel i7 3770k
> 
> ```
> bash bench_parallel.sh ./stockfish_master ./stockfish_3604 15 10 NNUE
> 
> sf_base =    1246045 +/- 13164
> sf_test =    1252843 +/- 13007
> diff =       6797 +/- 4748
> speedup = 0.005455
> 
> bash bench_parallel.sh ./stockfish_master ./stockfish_3604 15 10
> sf_base =    1586069 +/- 29585
> sf_test =    1597496 +/- 31368
> diff =      11427 +/- 3299
> speedup = 0.007205
> ```
> 
> * arch=x86-64-bmi2 - Intel Xeon CPU E5-2680 v3
> 
> ```
> bash bench_parallel.sh ./stockfish_master ./stockfish_3604 15 10 NNUE
> 
> base =    1240468 +/- 5856
> test =    1256723 +/- 7880
> diff =      16254 +/- 9896
> speedup = 0.013104
> 
> 
> bash bench_parallel.sh ./stockfish_master ./stockfish_3604 15 10
> 
> base =    1504425 +/- 7210
> test =    1519106 +/- 12551
> diff =      14681 +/- 15436
> speedup = 0.009759
> ```

If I'm reading this correctly there is actually a small slowdown of around 0.5 to 1% correct? Would a 0.5-1% slowdown actually result in elo loss/regression? Even if it made it like -0.25 elo worse that would still reduce the pass rate for the LTC non regression test to under 50%, which could explain why it didn't pass. That being said it could also just be bad luck? Idk. Weird.

**Comment by ppigazzini** [comment]
> If I'm reading this correctly there is actually a small slowdown of around 0.5 to 1% correct?

Base is master, so it's actually a small speedup. IMO with that number of samples a difference under 1% is meaningless.

**Comment by ppigazzini** [comment]
> If I were a maintainer, I would automate it, and kill once and for all these futile discussions, so that people focus instead on the _actual_ topic.

It actually helped to use `black` to format the fishtest code.
I played a bit with some styles of `clang-format`, what are you using to automate the formatting of `c-chess-cli` code?

**Comment by lucasart** [comment]
> > If I were a maintainer, I would automate it, and kill once and for all these futile discussions, so that people focus instead on the _actual_ topic.
> 
> It actually helped to use `black` to format the fishtest code.
> I played a bit with some styles of `clang-format`, what are you using to automate the formatting of `c-chess-cli` code?

see #3608

**Pull request closed without merging**
