### PR TITLE
Defer hash table resize and avoid redundant clears

### PR DESCRIPTION
**Pull request by skiminki**
**This is a usability improvement for faster Stockfish initialization.**

Defer hash table resize until the hash is actually needed. That is,
either when 'isready' or a search start command is received. This has
the following benefits:

- Stockfish initializes faster, especially on big hash sizes, since
  setting 'Threads' and 'Hash' will now trigger only 1 hash
  resize. Further, this removes the speed difference related to the
  order of setting "Hash" and "Threads".
- The initial default hash is never allocated in case the user sets
  the hash table size.

Add also tracking for whether the hash is dirty to avoid redundant
clears. This speeds up the initialization further.

With these improvements, Stockfish initialization is improved
drastically in the TCEC "Blue" machine: (176 threads, 128 GB hash)

<pre>Case  Init sequence style (SF ver)   Process launch to search start
===================================================================
 (1)  Default Cutechess (SF-dev)     59.0641s
 (2)  TCEC Cutechess-cli (SF-dev)     8.980s
 (3)  Either (SF-dev + this patch)    4.853s</pre>

The init sequence used in testing is as follows: (Default Cutechess style)

<pre>  uci
  setoption name Hash value 131072
  setoption name Threads value 176
  setoption name OwnBook value false
  setoption name Ponder value false
  ucinewgame
  isready
  position startpos
  isready
  go depth 1</pre>

The TCEC-patched Cutechess sets "Threads" before "Hash", since this
order is much faster on many engines, including SF-dev before this
patch.

Similarly, many regular users will also encounter speedups. The above
init sequence on my box measures the following times for the different
cases: (Intel Core i7-8700k, 12 threads, 16 GB hash)

<pre> (1)  2.347s
 (2)  1.430s
 (3)  0.975s</pre>

This patch makes my chess GUI (chessx) also start the analysis
noticeably faster. Response time improves from approx 2s to 1s from
pressing 'Analyze' to first output. (Same i7-8700k, 11 threads, 16 GB
hash)

No functional change

### CODE REVIEW

**Comment by vondele** [comment]
Don't think this is OK. Pushes all of this logic in the engine, while the GUI or the game manager could be smarter (e.g. respect the order of options given on the commandline in the cutechess-cli case). I didn't see an open issue at cutechess, btw.

Also, depending on how one reads the corner cases of the UCI protocol (isready is not required after setting options, only for initialization), the current patch could lead to a loss on time e.g. since it might resize the hash during the thinking time of the engine, e.g.
```
setoption name Hash value 4242
go wtime 20 winc 1 btime 20 binc 1
```
will not reply with a bestmove in time on my machine.

**Comment by skiminki** [comment]
My rationale for this patch below. I've been using a version of this patch for a while, and I thought that now would be the best time for PR, since SF11 is just released. But I can also understand if you don't want this patch.

**Hash resize**

1. Not all of this patch can be reasonably pushed to the frontends (i.e., GUIs and game managers). The front-ends are not required to understand the semantics of almost any of the options, nor there is a recommended order of setoptions. It would be nice if the UCI protocol recommended that the options are set in the order of the "uci" response, but it does not. For instance, vanilla cutechess sends the options in alphabetical order, as they're pushed through an ordered map to filter out duplicates and unsupported commands (completely within reason). I don't know what chessx does, but it also sends 'Hash' before 'Threads' on my box. 'Threads' is also not a standard option defined by the UCI protocol.
2. UCI protocol, however, is somewhat clear on 'isready', and says that the option is used to synchronize the engine with the GUI after the GUI has sent a command (or multiple) that can take time to complete. E.g. 'isready' should be sent after setting the path to the tablebases. Tablebases are used as an example, but I would also interpret that setting 'Hash', 'Threads', or basically any other option should be followed by 'isready' before a timeouting search command (e.g. 'go wtime').
3. I think it's unreasonable to reset EGTB paths, hash, or threads, and then do 'go wtime' and claim a victory. I would think that clearly 'isready' should be sent before 'go wtime'. However, I admit that this point leaves room for argument.

Anyways, I have tried to consider where and how to fix this usability issue. Ultimately, I think that the UCI protocol should be amended with recommended option ordering and a protocol state machine to specify exactly when 'isready' is needed. But we have to deal with what we have now, and in practice, adding this extra bit of logic in Stockfish would make the analysis experience better for many. Originally, I wrote this patch around a year ago for myself for this reason.

**Redundant hash clears**

Stockfish is the only place where this can be fixed. No amount of GUI smarts can reasonably avoid redundant hash clears. The GUI option ordering can improve the time from case (1) to case (2) as per my commit msg, but going (2) --> (3) requires Stockfish changes. This is because both hash resize and 'ucinewgame' trigger clear.

P.S. This is what I'm referring to: http://wbec-ridderkerk.nl/html/UCIProtocol.html . Not sure whether this is the latest and greatest, but I could find anything better.

**Comment by skiminki** [comment]
<pre>setoption name Hash value 4242
go wtime 20 winc 1 btime 20 binc 1</pre>

> will not reply with a bestmove in time on my machine.

I just realized that this is true with or without my patch. There's no response to 'setoption' by the engine, so the front-end has no knowledge whether the engine is ready on 'go'. This is why isready-->readyok is needed in any case.

**Comment by vondele** [comment]
I think the added logic is not worth it. The major effect can be done by the gui by sending the threads before the hash. The minor part, not doing a clear of the hash twice, hardly matters, at the TC for which a hash of that size is relevant.

**Pull request closed without merging**
