### PR TITLE
Help GCC to optimize msb() to single instruction

### PR DESCRIPTION
**Pull request by nepal**
No functional change.

### CODE REVIEW

**Comment by nepal** [comment]
GCC compiles builtin_clzll to “63 ^ BSR”. BSR is processor instruction "Bit Scan Reverse".
So old msb() function is basically 63 - 63 ^ BSR.
Unfortunately, GCC fails to simplify this expression.

Old function compiles to

        bsrq    %rdi, %rdi
        movl    $63, %eax
        xorq    $63, %rdi
        subl    %edi, %eax
        ret

New function compiles to

        bsrq    %rdi, %rax
        ret

BTW, Clang compiles both function to the same (optimal) code.

**Comment by nepal** [comment]
GCC in question is "gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)"

This change gives about ~0.7% speedup for PGO build

**Comment by mcostalba** [comment]
@nepal Thanks!

BTW this is an example of a well documented and presented patch: the author explained what the patch does, why and supported it with high quality data (in this case asm output).

**Comment by nepal** [comment]
@mcostalba Thanks for feedback - really appreciate it!

**Comment by mstembera** [comment]
Nice!

**Pull request merged**
