### PR TITLE
Fix PGO build for clang

### PR DESCRIPTION
**Pull request by vondele**
fixes issue #167.

Refines an earlier #891 pull request by @MichaelB7 by working around a missing symlink for llvm-profdata on ubuntu and cleaning up intermediate files.

Further testing on OSX and ubuntu (install llvm and clang packages) welcome.

No functional change.

### CODE REVIEW

**Comment by erbsenzaehler** [comment]
This works for me on Ubuntu 16.10 and llvm-profdata-3.8!

Maybe you can add clang-profile-make and clang-profile-use to the phony targets as you did with some other targets not too long ago

**Comment by vondele** [comment]
@erbsenzaehler well spotted, thanks!

**Comment by mibere** [comment]
@vondele 

Line 224

> PROFDATA = $(shell /bin/bash -c 'echo $$(dirname $$(readlink -f $$(which clang)))/llvm-profdata')

Does this work on macOS? By running this in an ordinary shell (Bash) I get:

```
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `echo $$(dirname $$(readlink -f $$(which clang)))/llvm-profdata'
```

**Comment by MichaelB7** [comment]
I'm out of pocket and wasn't able to test the very last change before heading off.  Up until that point , it was working macOS.

**Comment by vondele** [comment]
@mibere the problem seems to be that readlink on OSX doesn't have the option '-f ' 

Outside of a Makefile you don't need '$$' but '$' so

/bin/bash -c 'echo $(dirname $(readlink -f $(which clang)))/llvm-profdata'

Just wondering, the OSX case should actually not end up there, since the 

        ifeq ($(shell which llvm-profdata),)

line before should just work (assuming you have llvm-profdata in your path) and the line causing the trouble should not be called. Do you know why this happens?

I don't have access to OSX right now, so will need some help to find a portable solution.

**Comment by vondele** [comment]
@mibere can you check if this works on the command line (not makefile) on OSX:

/bin/bash -c 'echo $(dirname $(which clang))/$(dirname $(readlink $(which clang)))/llvm-profdata'

**Comment by mibere** [comment]
The command `which llvm-profdata` returns nothing.

`which clang` returns `/usr/bin/clang`

---

The folder of _llvm-profdata_ is _/Library/Developer/CommandLineTools/usr/bin/_

---
The command

`/bin/bash -c 'echo $(dirname $(readlink -f $(which clang)))/llvm-profdata'`

returns

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
/llvm-profdata
```

---

manpage of _readlink_

```
-f format
             Display information using the specified format.  See the FORMATS section for a description of valid formats.

[...]

   Formats
     Format strings are similar to printf(3) formats in that they start with %, are then followed by a sequence of formatting
     characters, and end in a character that selects the field of the struct stat which is to be formatted.  If the % is imme-
     diately followed by one of n, t, %, or @, then a newline character, a tab character, a percent character, or the current
     file number is printed, otherwise the string is examined for the following:

     Any of the following optional flags:

[...]

```

---

The command

`/bin/bash -c 'echo $(dirname $(which clang))/$(dirname $(readlink $(which clang)))/llvm-profdata'`

returns

```
usage: dirname path
/usr/bin//llvm-profdata
```

**Comment by MichaelB7** [comment]
I would have thought that the way it before that last change would work on any Mac as long they Xcode or clang installed and the paths properly set.  It did work for me.

**Comment by mibere** [comment]
For _llvm-profdata_ it is recommended to use Xcode’s _xcrun_ tool.

`xcrun llvm-profdata merge [...]`

**Comment by vondele** [comment]
@MichaelB7 the problem with the first version (/bin/bash -c "compgen -c llvm-profdata") is that it can return multiple matches if the user has installed multiple versions of the tool (e.g. 3.8 along with 3.7), leading to error later on.

@mibere so what does:

```
echo $(which clang)
echo $(readlink $(which clang))
echo $(dirname $(readlink $(which clang)))
echo $(dirname $(dirname $(which clang))/$(readlink $(which clang)))
```

return ?

**Comment by mibere** [comment]
@vondele 

`echo $(which clang)`
->  _/usr/bin/clang_

`echo $(readlink $(which clang))`
nothing (empty new line)

`echo $(dirname $(readlink $(which clang)))`
-> _usage: dirname path_
(followed by an empty new line)

`echo $(dirname $(dirname $(which clang))/$(readlink $(which clang)))`
-> _/usr_

**Comment by vondele** [comment]
@mibere rather strange...well I might have to go back to the first version of the code. Can you check what happens with

```
/bin/bash -c "compgen -c llvm-profdata | head -n 1"
```

Thanks!

**Comment by mibere** [comment]
`/bin/bash -c "compgen -c llvm-profdata | head -n 1"` returns nothing, no output

**Comment by vondele** [comment]
OK... I'm afraid I'll have to give up at this point.

**Comment by mcostalba** [comment]
The problem with your patch is that is definitely too smart, a makefile
patch instead should be as dumb as possible.

If the issue is a mispackage of Ubuntu then this should be fixed upstream.
I will try to manually fix the missing file and if after this the original
patch works then  I will apply that.

**Comment by vondele** [comment]
I agree with that, I'll push that version.

**Comment by mibere** [comment]
@vondele 

Even if I'm unsatisfied with this solution, after adding the path
'/Library/Developer/CommandLineTools/usr/bin/' to **the end** of $PATH your Makefile (branch _clangpgo_) works.

What I don't understand now, why $(MAKE) in the Makefile resolves to
'/Library/Developer/CommandLineTools/usr/bin/make' (instead of '/usr/bin/make')?!
There is no symbolic link between these two files.

Last output of your Makefile:

> Step 4/4. Deleting profile data ...
> /Library/Developer/CommandLineTools/usr/bin/make ARCH=x86-64-modern COMP=clang profileclean
> 

`echo $PATH` returns
`/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Developer/CommandLineTools/usr/bin/`
and `which make` returns `/usr/bin/make`

**Comment by vondele** [comment]
@mibere, yes, seems like OSX is doing something special, but I have no idea what.

**Comment by mcostalba** [comment]
@vondele Merged with fbb2ffacfdf10fc37d8ee2 (original patch by Michael + some additional tweak by you)

Issues on Ubuntu were due to upstream packaging bugs, after fixing llvm-profdata everything worked.

**Comment by mibere** [comment]
Thanks to all involved 👍 

I'm using the new Makefile with this one small change on macOS

```
clang-profile-use:
	xcrun llvm-profdata merge [...]
```

**Pull request closed without merging**
