### PR TITLE
Extract bench according to wiki instructions

### PR DESCRIPTION
**Pull request by ppigazzini**
- loop through the commits starting from the latest one
- read the bench value from the last match, if any, of the template
  in the commit body text

closes https://github.com/official-stockfish/Stockfish/pull/4627

No functional change

### CODE REVIEW

**Comment by ppigazzini** [comment]
In CI it is common for the process to stop immediately when an error occurs. Therefore, using `shell: bash {0}`, may not be the best approach.

We could make the behavior of posix and msys2 shells consistent, this will enable a nice simplification of the break statement in the loop.

```diff
diff --git a/.github/workflows/stockfish_test.yml b/.github/workflows/stockfish_test.yml
index 28218402..708875d1 100644
--- a/.github/workflows/stockfish_test.yml
+++ b/.github/workflows/stockfish_test.yml
@@ -18,38 +18,38 @@ jobs:
             comp: gcc
             run_32bit_tests: true
             run_64bit_tests: true
-            shell: bash {0}
+            shell: bash
           - name: Ubuntu 20.04 Clang
             os: ubuntu-20.04
             compiler: clang++
             comp: clang
             run_32bit_tests: true
             run_64bit_tests: true
-            shell: bash {0}
+            shell: bash
           - name: Android NDK aarch64
             os: ubuntu-22.04
             compiler: aarch64-linux-android21-clang++
             comp: ndk
             run_armv8_tests: true
-            shell: bash {0}
+            shell: bash
           - name: Android NDK arm
             os: ubuntu-22.04
             compiler: armv7a-linux-androideabi21-clang++
             comp: ndk
             run_armv7_tests: true
-            shell: bash {0}
+            shell: bash
           - name: MacOS 12 Apple Clang
             os: macos-12
             compiler: clang++
             comp: clang
             run_64bit_tests: true
-            shell: bash {0}
+            shell: bash
           - name: MacOS 12 GCC 11
             os: macos-12
             compiler: g++-11
             comp: gcc
             run_64bit_tests: true
-            shell: bash {0}
+            shell: bash
           - name: Windows 2022 Mingw-w64 GCC x86_64
             os: windows-2022
             compiler: g++
@@ -115,8 +115,10 @@ jobs:

       - name: Extract the bench number from the commit history
         run: |
-          git log HEAD | grep -o "\b[Bb]ench[ :]\+[1-9][0-9]\{5,9\}\b" | head -n 1 | sed "s/[^0-9]//g" > git_sig
-          [ -s git_sig ] && echo "benchref=$(cat git_sig)" >> $GITHUB_ENV && echo "Reference bench:" $(cat git_sig) || echo "No bench found"
+          for ((n=0; n<100; n++)); do
+            benchref=$(git log HEAD~$n -1 | grep -v '^[[:space:]]*$' | tail -n 1 | grep '\b[Bb]ench[ :]\+[1-9][0-9]\{5,7\}\b' | sed 's/[^0-9]//g') && break || true
+          done
+          [[ -n "$benchref" ]] && echo "benchref=$benchref" >> $GITHUB_ENV && echo "Reference bench: $benchref" || echo "No bench found"

       - name: Check compiler
         run: |
```

**Comment by ppigazzini** [comment]
Tested successfully the version with `shell: bash {0}` replaced by  `shell: bash` in all .yml workflow files.
https://github.com/ppigazzini/Stockfish/actions/runs/5294261506/jobs/9583595004

**Comment by ppigazzini** [comment]
@vondele if your doubts are about the search of the bench value on the last line of the message body, we can easily search for the last line of text that contains the searched pattern, reversing the line of the message body with `tac`:

```bash
benchref=$(git log HEAD~$n -1 | tac | grep -m 1 -o -x '[[:space:]]*\b[Bb]ench[ :]\+[1-9][0-9]\{5,7\}\b[[:space:]]*' | sed 's/[^0-9]//g')
```

**Comment by vondele** [comment]
yes, I think that's best.

**Comment by locutus2** [comment]
> @vondele if your doubts are about the search of the bench value on the last line of the message body, we can easily search for the last line of text that contains the searched pattern, reversing the lines of the message body with `tac`:
> 
> ```shell
> benchref=$(git log HEAD~$n -1 | tac | grep -m 1 -o -x '[[:space:]]*\b[Bb]ench[ :]\+[1-9][0-9]\{5,7\}\b[[:space:]]*' | sed 's/[^0-9]//g')
> ```

I would remove the -x option else this works only if the bench segment is given alone in a single line.

**Comment by ppigazzini** [comment]
> I would remove the -x option else this works only if the bench segment is given alone in a single line.

The CI is here to help to write the new commits according to the instruction.

By the way reading the output should help to deal with the ghosts :)
```bash
git log HEAD | grep "[Bb]ench" | less
```

**Comment by ppigazzini** [comment]
ready for review.

**Pull request merged**
