### PR TITLE
Update authors

### PR DESCRIPTION
**Pull request by mcostalba**
Fishtest is a key factor of SF success.

Thanks to Fishtest we have not only greately
improved ELO but, even more important, we
have enabled a kind of joint development and
testing that it is the herat of on open
source project like SF.

Open sourcing is not just about open code, it is
about commuity development. In case of a chess engine
this has never been possible before due to missing
a strong and strict testing environment that allows
many people to contribute in a safe and coordinate way.

Fishtest is a new way of developing chess engines,
something that has never exsisted before.

No functional change.

### CODE REVIEW

**Comment by mstembera** [comment]
There is nobody more deserving.  Thanks Gary and congrats!

**Comment by nabildanial** [comment]
You only mention on the commit message about Fishtest but no mention of Gary at all?

**Comment by zamar** [comment]
approved. Gary has made significant contributions to Stockfish, so deserves to be listed as an author.

**Comment by glinscott** [comment]
Thanks @mcostalba and @zamar!  SF is a success because of the amazing community, and you two have set the whole thing up by being so patient and helpful.  What a fun project to be part of :).

**Pull request merged**
