### PR TITLE
Endgame Draws

### PR DESCRIPTION
**Pull request by mstembera**
Just like KNNvsK these are simple draws.
I'm not sure what if any kind of testing is appropriate for this.  Please advise.
bench: 3295376

### CODE REVIEW

**Comment by mcostalba** [comment]
I guess these draws are already evaluated upstream somehow. Now I don't remember the details, but the reason why those endgames have never been added is because they are useless, i.e. evaluation is already set at draw in those cases.

**Comment by mstembera** [comment]
Hmm but the bench changed.  Is even something like KBNKNN set as a draw upstream somewhere?  Could someone more familiar point me to where that happens?

**Comment by joergoster** [comment]
@mstembera See here https://github.com/official-stockfish/Stockfish/blob/master/src/material.cpp#L198-L207

**Comment by mstembera** [comment]
@joergoster Thanks!
I'll test this as an elo gain and reopen if it passes.
http://tests.stockfishchess.org/tests/view/5c86bed40ebc5925cffe8a0c

**Comment by JeymsVC** [comment]
@mstembera I attach a file [TB7_stats.txt](https://github.com/official-stockfish/Stockfish/files/2957915/TB7_stats.txt) with the information that you are looking for:  (a) The fields from "white_wins" to "black_wins" contain the total number of positions of the respeticve outcome of the endgame; and (b) The rest contain the information from (a) splitted into white to move (W_) and black to move (B_).

**Comment by mstembera** [comment]
@JeymsVC Thank you!!  That's exactly what I was looking for.

**Comment by Alayan-stk-2** [comment]
I did some more digging : 
- KBKN and KBKB only have DTM 1 wins just like KNNK (so with "weak" side to play an escape is always possible)
- KNNKB has only DTM 1 wins when the bishop side win or when the bishop side king is not in a corner or a square adjacent to a corner. KNN mating out of a corner requires to control 6 squares. For the bishop to be a liability, it would have to restrict its own king movement. In configurations with side-attacking king controlling two squares, the only position for a bishop to block the king would allow it to capture one of the two knights. In configurations with king blocking 3 squares, each enemy knight can only take one square away from the king. For a mate to be possible, the bishop needs to be moved next to the king immediately before it. If the bishop is already there, either the weak side has to move it away or the other side square is not controlled by an enemy knight and a null move would not lead to mate.
- KNNKN has at most DTM 2 wins when the lone knight side king is not in a corner or adjacent to a corner. This involves the strong side having the tentative checkmate set up and the weak side moving the knight on the king escape square. That is, Ne2 here : 8/8/8/8/3n4/5N2/N7/1K1k4 b - - 0 1. "King is not on a border or next to a corner = draw" would be a fullproof but excessive rule, as if enemy king blocks the way from the border (and not in a corner), a checkmate is impossible because for the lone knight to block his king and take out a 6th square, he would necessarily put the strong side king in check. Unlike in KNNKP, it's impossible to force the weak side king into a corner in a winning way even if the additional piece remove stalemate opportunities.

**Comment by MichaelB7** [comment]
I have a hard time appreciating all the interest in 4 men endgame positions since in any serious match we would always have access to 4 men , 5 men , 6 men and even 7 men tablebases.   In fact the 4 men and 5 men take up so little space , we probably should be using the 4 men and possibly the 5 men as well in fishcooking.  What am I missing - why all the interest?

**Comment by Alayan-stk-2** [comment]
Fishtest games are played without TB so SF having this endgame knowledge integrated would make it play slightly better at fishtest which could in turn influence how other parameters/changes are tuned.

**Comment by MichaelB7** [comment]
Wouldn’t it be better to incorporate a minimum syzygy tablenbase of 4 men in fishtest  - so that we are actually testing Stockfish in the way that bears more resemblance to the manner in she would be used in a tournament that counts ?  I would leave the tuning that we already have - but at least going forward we could focus our attention and assets on what would really would improve Stockfish in those games that count.

**Comment by mstembera** [comment]
@JeymsVC  @noobpwnftw FYI and thank you!
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/7XPt3vJztxk

**Pull request closed without merging**
