### PR TITLE
Early mate

### PR DESCRIPTION
**Pull request by syzygy1**
This modifies the in-search TB probing to continue searching for a mate "behind" a TB win (or loss).

It does the following:
- If a TB win or loss value allows an alpha or beta cutoff, the cutoff is taken.
- Otherwise, the search of the current subtree continues. In PV nodes, the final value returned is adjusted to reflect that the position is a TB win (or loss).

The patch also fixes a potential problem caused by root_probe() and root_probe_wdl() dirtying the root-move scores.

This patch removes the limitation of current master that a mate is never found if the root position is not yet in the TBs, but the path to mate at some point enters the TBs. The patch is intended to preserve the efficiency and effectiveness of the current TB probing approach.

An ongoing test of 10,000 games at 10s+0.10s suggests that the patch does not regress against current master. Results will be posted when the test is finished.

Bench with 5-piece TBs (WDL+DTZ): 6268725

### CODE REVIEW

**Comment by mcostalba** [comment]
The most interesting point of this PR is that you accept that a patch that keeps same ELO and improves engine behaviour is a good thing to commit. Please don't forget it....it will come out again shortly.

**Comment by syzygy1** [comment]
I wrote "preserve the efficiency and effectiveness". So I am talking about the absence of unnecessary regressions.

**Comment by syzygy1** [comment]
Result of 10,000 games at 10s+0.10s (6-piece TBs, 4MB hash):
Score of early_mate vs master: 1774 - 1677 - 6549  [0.505] 10000
ELO difference: 3

So there is some confidence that this patch does not lose Elo.
(There should be no Elo gain either.)

More tests are welcome.

**Comment by Atahan-Turkoglu** [comment]
@syzygy1 
BTW, C++ port of Syzygy is %100 equivalent to the original?

**Comment by syzygy1** [comment]
No, the C++ rewrite is less efficient, performing more table lookups than necessary (one probe can result in multiple lookups, one in the table corresponding to the position and others in subtables resulting from captures). My elegant alpha/beta-based capture resolution scheme did not survive. But the current implementation is believed to return correct values.

Functionally there is a difference in that different capture resolutions result in different orderings of the internal piece lists, resulting in different ordering of generated moves. Node counts will therefore be different between Stockfish and Cfish when TBs are used. (This is just noise Elo-wise.)

**Pull request closed without merging**
