### PR TITLE
Rook PSQT Tuned (updated with 3rd LTC)

### PR DESCRIPTION
**Pull request by SFisGOD**
Rook PSQT Tuned

Failed STC (Yellow )
LLR: -2.96 (-2.94,2.94) [0.00,4.00]
Total: 56302 W: 12007 L: 11953 D: 32342
http://tests.stockfishchess.org/tests/view/5be69d210ebc595e0ae3185b

Passed 1st LTC (Green)
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 8745 W: 1480 L: 1301 D: 5964
http://tests.stockfishchess.org/tests/view/5be682960ebc595e0ae31818

Failed 2nd LTC (Red)
LLR: -2.96 (-2.94,2.94) [0.00,4.00]
Total: 19398 W: 3040 L: 3133 D: 13225
http://tests.stockfishchess.org/tests/view/5be69b840ebc595e0ae31856

Passed 3rd LTC (Green)
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 107516 W: 17342 L: 16858 D: 73316
http://tests.stockfishchess.org/tests/view/5bea879a0ebc595e0ae34d80

Bench: 3966061

### CODE REVIEW

**Comment by SFisGOD** [comment]
@mcostalba @snicolet This was tested directly at LTC. However, I scheduled an STC as suggested by vondele.

**Comment by SFisGOD** [comment]
STC is yellow but 2nd LTC failed. I'm leaving this open for discussion purposes.

**Comment by mcostalba** [comment]
The second red LTC is a bad result (the STC is not so sensible IMHO). Eventually you could run a third and final LTC and we will commit according to the result: green or not green.

**Comment by jerrydonaldwatson** [comment]
Congrats!

**Comment by mcostalba** [comment]
thanks. good for me.

**Comment by snicolet** [comment]
Merged via 8a9c298deeee372251d95c867f877a7ac3a7c3fb, thanks!

The values in the rook table now look a bit strange for a human eye
and are hard to explain, especially in the endgame, maybe it would be
nice to simplify them by hand and see if we can pass another (clean)
double green with a more regular array.

**Pull request closed without merging**
