### PR TITLE
Noclear

### PR DESCRIPTION
**Pull request by lucasart**
Please commit as two separate patches, to keep a clean log.

From this as a base, we can test the "last move is capture" condition from VoyagerOne (Anglerfish).

### CODE REVIEW

**Comment by mcostalba** [comment]
Congrats!  A nice result...also search::reset() is nice

**Comment by VoyagerOne** [comment]
Yes..very nice work.

**Comment by locutus2** [comment]
Congrats! And I'am happy to see that the stats now cleared for a new game. Thanks!

**Comment by VoyagerOne** [comment]
Won't this create a functional impact with noClear patch?
As each new game the stats are now reset.

**Comment by glinscott** [comment]
@VoyagerOne - congrats on the great idea to kick this off!

@lucasart - change looks great!  thanks for moving the clear stuff to Search::reset, this looks good to me.

**Comment by mstembera** [comment]
Just wondering if just the stats(not hash) should also be cleared before each bench position?

**Comment by mcostalba** [comment]
Why?

**Comment by zamar** [comment]
Congrats to Lucas & VoyagerOne!

I fully support the idea of Search::Reset(). In fact I was planning to suggest something along these lines before committing the improvement, but luckily Lucas had the same idea!

Approved.

@glinscott: Can you please commit this as I'm still travelling?

**Comment by lucasart** [comment]
@VoyagerOne: The Anglerfish patch can now be written, on top of this one, as:

    if (pos.captured_piece_type())
        Search::reset();

Can be tested on top of this one, perhaps with a smaller resolution to be fair: may I suggest SPRT(-1,4) + SPRT(0,5) ?

**Comment by VoyagerOne** [comment]
But this will clear TT... correct?  We don't want to do that...

**Comment by mstembera** [comment]
@mcostalba
Although bench is synthetic it seems good to have it simulate actual game play as closely as possible(since we use it to test speed optimizations and PGO builds use it to collect branch prediction data).  The problem of course is that in a game consecutive positions are very similar differing only by two moves.  Therefore stats  remain very relevant from one position to the next.  In bench each subsequent position is completely different.  I was therefore wondering whether it's better to clear stats between bench positions or not?    (I believe clearing TT each time would be bad because it fills the TT with 0 keys which then use a specially optimized code path that is only used very briefly at the start of any actual game.)

**Comment by lucasart** [comment]
@mstembera: I agree with you. Bench should call `Search::reset()` before each position. But let's keep this separate from this pull request. I thought the same as you when I wrote the code, but chose not to change the existing logic (`TT.clear()` is called only at the beginning of bench currently).
Once this one is merged, you can send a separate pull request that calls `Search::reset()` before each bench position.

**Comment by mstembera** [comment]
@lucasart 
The only thing is that I would NOT want Search::reset() to include TT.clear() in that case.  Should Search::reset() and TT::clear() be kept separate and orthogonal?

**Comment by lucasart** [comment]
No. I think `TT.clear()` belongs in `Search::reset()`. If you don't clear the TT, you don't restore a clean search state and you get results that depend on what's in the TT. bench positions are not successive positions like you get in real games. Next position is completely different from previous one, so TT accumulated for position 1,2,…,N is not pertinent for position N+1.

**Comment by lp--** [comment]
So why would you want to reset if it does not help to simulate actual game
play for profile optimization, but in fact goes even further away  from
it?  If you really want to simulate actual game play why not include sets
of successive positions and to run bench through actual time management to
have statistics gathering in positions which matter?

Also reset after every position makes bench worse for automatic game
analysis,  and likely useless for statistics gathering

**Comment by mstembera** [comment]
@lp
I never said I wanted to reset the stats because I'm not expert enough in that part of the code to make the right decision.  I only wanted to point out there is a choice to be made so that someone knowledgeable(like Lucas is) could decide which is better.  Yes running bench in a more game simulation manner would be good but I'm not sure how much code that would add and if it would be justified?

@lucasart
Yes TT data from one bench position is not pertinent to another.  However and empty TT is not pertinent to a bench position either.  In both cases you will not get any TT hits.  However, if you don't clear the TT at least the search logic through the TTcluster and the replacement policy will get exercised more or less as they would in a game.  If you clear the hash all that time critical code will be mostly skipped.  This is because we treat entries w/ 0 key as special/empty and early out.  It's easiest to understand if you look at TranspositionTable::probe() and what it does as soon as it encounters an entry w/ key==0.  A cleared hash is a very unnatural state in a game and only happens on the first move which we actually simulate well by having it be cleared just for the first bench position.

If you like TT::clear() inside of Search::reset() that's ok because the calls to Stats::clear() can still be made individually if needed.

**Comment by mcostalba** [comment]
We use bench mainly to validate non functional change patches and as a
signature for a given commit.

There is no need to clear each position for this.

Regarding pgo,  it is your assumption that it  helps but you have no backed
up this with any number, so it just remain an assumption with zero value.
For instance my assumption is that clearing each position is_totally_
irrelevant for pgo.

Any patch, if not a simplification, should be applied with a measurable and
quantitative reason, not just because "I think....""

**Comment by lp--** [comment]
@mstembera 
It adds 3 or 4 lines of code + fens (if you don't want to read them from file). Some time ago I already such patch but Marco did not accept it.

Actually it may be interesting just to submit test with profile-build going through sets  successive positions, to see if there is measurable gain. As I understand framework already support it.

**Comment by mstembera** [comment]
@mcostalba
Yes we use it mainly to validate non functional patches and that will continue to work properly whether we clear stats or not.

You can call it an assumption but I think it's pretty obvious that PGO can only collect stats on code paths that execute and not on those that don't.  Your opinion about whether bench code paths more closely resemble game play with or without clearing the stats is something I am interested in hearing from you as an expert.

My original question was not to apply any patch because of "I think.." only to open a discussion.

**Comment by Rocky640** [comment]
Back to the Anglerfish patch and VoyagerOne question...
His idea was not to clear the TT, so he can still code as follow on top of lucas patch (once it is commited) isn't it ? 
if (pos.captured_piece_type()) {
 History.clear();  
 CounterMovesHistory.clear();  
 Gains.clear();  
 Countermoves.clear(); 
}
And do we agree on
STC: SPRT(-1,4) and LTC:SPRT(0,5)  ?

**Comment by lucasart** [comment]
guys, can you please not hi-jack pull requests.
please create a discussion thread in fishcooking instead, because none of what is being discussed is relevant to this pull request.

**Pull request closed without merging**
