### PR TITLE
Assorted trivial cleanups

### PR DESCRIPTION
**Pull request by mcostalba**
Addreses https://github.com/official-stockfish/Stockfish/issues/1862

No functional change.

### CODE REVIEW

**Comment by vondele** [comment]
maybe add:
```diff
diff --git a/src/search.cpp b/src/search.cpp
index 756b2d576..e26f9ea45 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1665,7 +1665,7 @@ bool RootMove::extract_ponder_from_tt(Position& pos) {
 
     assert(pv.size() == 1);
 
-    if (!pv[0])
+    if (pv[0] == MOVE_NONE)
         return false;
 
     pos.do_move(pv[0], st);
```

**Comment by Rocky640** [comment]
bitboard.cpp line 187, reference to chess wiki should be changed for
https://www.chessprogramming.org/Magic_Bitboards

movepick.h line 88
https://www.chessprogramming.org/Butterfly_Boards

line 92
https://www.chessprogramming.org/Countermove_Heuristic

**Comment by protonspring** [comment]
Lines 467+ in position.cpp. . . we have . . "WHITE | KING_SIDE," . . . "BLACK | QUEEN_SIDE," etc.

Woudn't it be better to just do WHITE_OO, WHITE_OOO, BLACK_OO, BLACK_OOO ?

**Comment by mcostalba** [comment]
@protonspring thanks. Updated.

**Comment by protonspring** [comment]
movegen.cpp, line 114:

emptySquares = (Type == QUIETS \|\| Type == QUIET_CHECKS ? target : ~pos. pieces());

Is a bit unclear if you don't have order of operations memorized.  I suggest adding a paren after CHECKS for clarity:

emptySquares = (Type == QUIETS \|\| Type == QUIET_CHECKS) ? target : ~pos .pieces();

**Comment by mcostalba** [comment]
Well, IMO this is even more confusing:
`
emptySquares = (Type == QUIETS || Type == QUIET_CHECKS) ? target : ~pos .pieces();`

Because it seems:    

`a = (b) ? x : y;`

Now, what it means?

```
(a = (b)) ? x : y;

or

a = ((b) ? x : y);
```

A full explicit solution would be the latter, i.e. writing:

`emptySquares = ((Type == QUIETS || Type == QUIET_CHECKS) ? target : ~pos .pieces());`

But I really don't like it. So I prefer to keep as is.

**Comment by snicolet** [comment]
There are extras spaces in line 118 of pawns.cpp
```
            && popcount(phalanx)   >= popcount(leverPush))
```

**Comment by mcostalba** [comment]
@snicolet thanks. Fixed.

**Comment by Rocky640** [comment]
evaluate.cpp line 216, after last commit, the following comment about the kingRing should be deleted
` It is set to 0 when king safety evaluation is skipped.`

**Comment by Rocky640** [comment]
endgame.cpp line 134, extra space at the end of line
evaluate.cpp line 206, , extra space at the end of line

**Comment by protonspring** [comment]
Lines 45+ in movegen.cpp disorient me.  We make a step direction which is opposite from the king movement direction, then we go from kto to kfrom.  Wouldn't it be more clear to change the step direction so that KING_SIDE -> EAST, then just use a negative step?   I don't know about everyone else, but this is much easier for me to read:

    const Direction step = Chess960 ? kto > kfrom ? EAST : WEST
                                    : KingSide    ? EAST : WEST;

    for (Square s = kto; s != kfrom; s -= step)
        if (pos.attackers_to(s) & enemies)
            return moveList;

**Comment by protonspring** [comment]
Lines 96+ in movegen.cpp, we have:

    // Compute our parametrized parameters at compile time, named according to
    // the point of view of white side.

"parametrized" should be "parameterized," but I'm not sure this comment is even needed.  If it is needed, we could probably just say:

    // Compute some compile time parameters relative to the white side

**Comment by protonspring** [comment]
In movegen.cpp, lines 108+

    Bitboard pawnsOn7    = pos.pieces(Us, PAWN) &  TRank7BB;
    Bitboard pawnsNotOn7 = pos.pieces(Us, PAWN) & ~TRank7BB;

I'm not sure, but wouldn't be one less operation to do:

    Bitboard pawnsOn7    = pos.pieces(Us, PAWN) &  TRank7BB;
    Bitboard pawnsNotOn7 = pos.pieces(Us, PAWN) ^ pawnsOn7;

**Pull request merged**
