### PR TITLE
My tuning branch

### PR DESCRIPTION
**Pull request by Cooffe**

### CODE REVIEW

**Comment by Cooffe** [comment]
**I would like help
I have a dual configuration
It is up to those who are good at solving it**

**Comment by Cooffe** [comment]
I would like help
I have a dual configuration
It is up to those who are good at solving it

**Comment by Cooffe** [comment]
I would like help
I have a dual configuration
It is up to those who are good at solving it

**Comment by snicolet** [comment]
@Cooffe Hmm, maybe the fishcooking forum is a good place to get help :-)

**Pull request closed without merging**
