### PR TITLE
Add basic github workflow

### PR DESCRIPTION
**Pull request by Sopel97**
What works:

- ubuntu
  - all x86-64 archs
    - clang
    - gcc
  - valgrind
  - sanitizers

What doesn't work (naively tried):

- x86-32 (might work if we apt get a 32 bit compiler version?)

What needs to be tried:

- windows (should be possible to setup mingw)
- macos (not gonna bother)

Notes:

- go depth 20 in game.exp requires ~1M nodes which is a lot for valgrind/tsan speeds - takes A LONG time

Ran to completion here https://github.com/Sopel97/Stockfish/actions/runs/949608070

#3487

### CODE REVIEW

**Comment by vondele** [comment]
so, this looks good and timely in my eyes. 

We can definitely reduce the `go depth 20` in game.exp if that's the bottleneck.  Can be 10 or so. 

Having mingw is probably more important than macos, at least we break that more often.

for the 32bit builds, one needs to apt-get the g++-multilib, IIRC.

**Comment by vondele** [comment]
as part of this commit one probably can remove the travis. It looks like this covers essentially the same functionality.

**Comment by vondele** [comment]
maybe we could restrict the Valgrind and extensive (Valgrind, sanitizer) CI testing to linux+gcc 
and just do build + bench on linux+clang, msys2, and macos2. 
Also github actions have a limited budget (about 2000min/month, windows is 2x run time, macOS 10x run time).

**Comment by Sopel97** [comment]
hmm, I can't find any such limit described here https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration

Yes, doing valgrind and sanitizer run only on GCC is an option, but we should still limit the depth there. I'll try to get 32 bit builds working.

**Comment by vondele** [comment]
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

**Comment by xoto10** [comment]
I'm guessing we might hit the limits, but the excess charges don't seem too bad. There's also https://github.com/sponsors

**Comment by Sopel97** [comment]
I've made all the requested changes, but I'm hitting 

> GitHub Actions has encountered an internal error when running your job.

which I suppose is something that is on their end. I'll retry in a few hours.

**Comment by vondele** [comment]
another minor nit would be the badge displayed from the Readme.md which refers to travis.

**Comment by Sopel97** [comment]
passed here https://github.com/Sopel97/Stockfish/actions/runs/950472184

**Comment by vondele** [comment]
is the link on the readme as you want, or can we get a badge as well?

Otherwise, this looks good to me and this will revive our CI. If you think you're done, change it from draft to ready to merge, and I'll give it a try.

The format is an improvement of the travis.yml, and this will be a good basis to extend to msys2 testing, and probably allows for building and uploading binaries for pushes to master. Obviously can be done at a later stage.

**Comment by Sopel97** [comment]
the link that I've added in the readme points to this repo's actions which should be populated as soon as it finishes a run

**Comment by ppigazzini** [comment]
@Sopel97 in fishtest we use this link for the badge "https://github.com/glinscott/fishtest/workflows/CI/badge.svg"

**Comment by vondele** [comment]
merged in 07e6ceacd623402a8b83c834e95db77efaad3782

**Comment by ppigazzini** [comment]
I followed the Github instructions, so I suppose that are changed in the meanwhile, "CI" is the "name" of the actions in fishtest

https://github.com/glinscott/fishtest/blob/master/.github/workflows/main.yaml

```
# This is a basic workflow for fishtest
name: CI
```

**Comment by vondele** [comment]
yes, the badge already shows with the name 'Stockfish' probably another name could be considered.

**Comment by ppigazzini** [comment]
@Sopel97 @vondele GitHub has a button to create the markdown for the workflow status badge.

https://github.com/official-stockfish/Stockfish/actions/workflows/stockfish.yml
Under "..." menu select "Create status badge"

In this case it's suggested the redirection to the single workflow and not the whole actions:
```
[![Stockfish](https://github.com/official-stockfish/Stockfish/actions/workflows/stockfish.yml/badge.svg)](https://github.com/official-stockfish/Stockfish/actions/workflows/stockfish.yml)
```

**Pull request closed without merging**
