### PR TITLE
Fix bench bug, the hash and the histories weren't cleared between games.

### PR DESCRIPTION
**Pull request by Hanamuke**
Fix issue #1500

Bench:5816276

### CODE REVIEW

**Comment by mcostalba** [comment]
Why this should fix the bench? This should not matter because data is cleared anyhow before any bench.

**Comment by Hanamuke** [comment]
Data is cleared before the bench, but not between the positions of the bench. For example with master, the bench would change if you modified the order of the positions. It makes it hard to debug a supposedly non functional patch because you never know if the bench of a position changed because of your patch, or because it affected the positions benched before.

With the patch, ucinewgame is sent before each position, instead of only at the beginning of the bench.

**Comment by mstembera** [comment]
Just FYI.  Starting each position with a clear hash is a bit unrealistic because that only happens once on the very first position in a real game.  On the other hand in a real game successive positions are very similar (therefore you get TT hits from previous position searches) which is not the case with our bench positions.

**Comment by Hanamuke** [comment]
@mstembera Exactly. I don't really have argument in favor of the master version though. I think clearing hash everytime is good for cnosistency when benchmarking speed. It is also good to not have baffling outputs when  testing a patch on a set of positions (idk if someone does that). An exmple where is migth be useful too is when you try to write a non functionnal patch but it somehow changes bench. You'd be happy if the position(s) for which the bench is wrong don't pollute the other positions of the bench. 

Well anyway, clearly not of high priority, but i just think that's how it makes sense.

**Comment by mcostalba** [comment]
Sorry but you didn't explain why bench should be different at every run with current master (indeed it is not).

I think your patch is not only useless but also misleading because underlying a limit of current master that in reality does not exist.

**Comment by Hanamuke** [comment]
@mcostalba by reproducable i was refering to issue #1500 .  With master, you will get  a different bench weither you bench a position alone or after other positions in the same bench command. I've detailled what to do to reproduce the problem.

The commit message is indeed misleading, for those who haven't read the issue, i'm to blame for that i guess, i'll modify it.

**Comment by mcostalba** [comment]
I read #1500 : I don't understand what the issue is.

Could you please write all the steps (one by one) to reprodce the _issue_ with current master?

**Comment by mcostalba** [comment]
Ok, maybe I have understood: you say that after a bench, TT and history are not cleared so that running a position before and after a bench gives different results.

Well, first of all this is NOT an issue, because after  running any command the state is not preserved, this is not only acceptable, but also it should be like this, think running a long analyses and then running again, you want the second seqrch to be much faster.

Second, even if we assume this to be an issue (but is not), your patch is wrong: you shoud put the "ucinewgame" command at the end of the total list. For instance if you run bench with your patch applied and then run a search on the last position of the bench list, then it will give different output info:

```
bench 128 1 12 current
go depth 12
```

So I'd suggest close the issue (because it is noty an issue) and hence close this one.

**Comment by Hanamuke** [comment]
Just to explain the issue one last time.
I run ./stockfish bench
-> i get 95686 nodes explored for position 3/42
The default setting are 16 1 3 and the position 3/42 has fen 
8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 11.

If i run 
./stockfish
position fen 8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 11
bench 16 1 13 current
I get 103162 nodes

Since the patch is just moving a line down, in a code path unused in search, i don't see why not merge unless we seek master's behaviour ; not that it is up to me anyway.

**Comment by mcostalba** [comment]
@Hanamuke ok, have you read my comment?

With your patch applied you still have different numbers for:

```
./stockfish
position fen 8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 11
bench 16 1 13 current <-- first run
go depth 13  <-- second run different number
```

**Comment by Hanamuke** [comment]
Doing go is different from doing bench since bench does ucinewgame, wo i agree that it's not a problem, but i get it, i close.

**Comment by Kingdefender** [comment]
I have always found it more logical to do testpositions only with a cleared hash so that result for every position is reproducible. This was changed one time just because results got 'better' if the engine could retain hash and testpositions were somehow related. It is just bad science. Maybe you catch more bugs this way, but then you have to find were originally the bug reared its head first.

**Pull request closed without merging**
