### PR TITLE
MobilityAreaRewrite

### PR DESCRIPTION
**Pull request by Rocky640**
Same as test which passed STC and LTC.
No functional change. Same Bench # 7600729

It is easier to read, and a bit faster
Results for 10 tests for each version:

Base      Test      Diff
Mean    1316237   1325032   -8795
StDev   30570     31026     1563

p-value: 1
speedup: 0.7 %

### CODE REVIEW

**Comment by mstembera** [comment]
gcc 5.1.0
profile-build ARCH=x86-64-modern COMP=mingw
1% faster than original patch.
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    926977    935854    -8877     
    StDev   304289    305771    4748      

p-value: 0.969
speedup: 0.01
```

**Comment by glinscott** [comment]
Nice, congratulations!!

Please include the STC and LTC testing results in the pull request though :).

**Comment by glinscott** [comment]
Oops, I see that the other pull request has the STC and LTC stuff - ignore my previous comment :).

**Comment by Rocky640** [comment]
Not necessary anymore, since a simpler version will be pulled.

**Pull request closed without merging**
