### PR TITLE
Remove recapture square

### PR DESCRIPTION
**Pull request by protonspring**
Removes the recapture square in movepick.cpp.

I honestly don't understand this code well, but it doesn't seem like this recapture square helps at all.

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 26926 W: 5907 L: 5796 D: 15223 
http://tests.stockfishchess.org/tests/view/5c2d47f30ebc596a450bb15e

LTC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 52729 W: 8743 L: 8673 D: 35313 
http://tests.stockfishchess.org/tests/view/5c2d6c550ebc596a450bb5ee

bench 3269822

### CODE REVIEW

**Comment by DU-jdto** [comment]
With this, no moves are searched at all once depth <= DEPTH_QS_RECAPTURES (when not in check). Interesting that this isn't a regression. Note that we're still generating and scoring the captures even though we're not going to be using them, so we could save speed by not doing so.

**Comment by protonspring** [comment]
I can make a test to NOT generate or score captures if we're in QCAPTURE_INIT and depth < DEPTH_QS_RECAPTURES.

Should I test -3,1 against master, or 0,5 against this patch?

**Comment by DU-jdto** [comment]
Sorry, I just submitted this: http://tests.stockfishchess.org/tests/view/5c2e743f0ebc596a450bcc76

I can withdraw it if you'd like to submit something yourself.

**Comment by protonspring** [comment]
Mine is quite different from yours:
http://tests.stockfishchess.org/tests/view/5c2e75c70ebc596a450bccef

**Comment by protonspring** [comment]
Mine is quite different from yours, if it's OK, I submitted mine as well.
http://tests.stockfishchess.org/tests/view/5c2e765c0ebc596a450bccf5

**Comment by DU-jdto** [comment]
I would probably be inclined to test it at LTC as an ELO gainer against this patch. That said, it might be better to wait for someone with authority to weigh in.

**Comment by protonspring** [comment]
I agree.  On the assumption that this will be merged, I'll put it on my list of things to test.  Thx.

**Comment by mcostalba** [comment]
The way this patch does not generate moves if depth <= DEPTH_QS_RECAPTURES is **very** convoluted. It took me 5 minutes to understand that moves are blocked because filter() in MovePicker::select() returns false for every move, if the depth below the threshold. 

If you really want a truncated qsearch it should be coded in a much more straightforward way: directly in MovePicker c'tor assigning a newly defined STOP stage.

Now, do we really want a truncated qsearch? Do we have a clear idea of the implications of this choice?

**Comment by noobpwnftw** [comment]
This patch only removes one out of two conditions when generating qsearch moves, the obscure `depth <= DEPTH_QS_RECAPTURES` is from current master.

**Comment by snicolet** [comment]
@protonspring 

The way the the MovePicker class when called for qsearch (depth <= 0, basically) can be summarized like that:

- for depth 0, generate all captures, then all quiet checks
- for depth -1 to -4, generate all captures
- for depth < -4, finish all the recaptures sequences on the last square used at depth -4

This technics avoids search explosion because the number of recaptures on the last capture square is bounded and almost always very small.

**Comment by snicolet** [comment]
In fact I will re-open this pull request to keep the discussion open on this subject of recapture sequences in qsearch(): the patch in the pull request maybe be too dangerous because of search explosions in some situation, but I suspect there might be some Elo to gain here around these ideas.

Example of a position with a significant search explosion in qsearch:
4rrk1/1p1nq3/p7/2p1P1pp/3P2bp/3Q1Bn1/PPPB4/1K2R1NR w - - 40 21

Two possible ideas to try:

1) **If we want to improve on master and call evaluate() on more quiets positions (with the implicit hypothese that our evaluation function is more precise if there are less capture sequences in the position)** : an idea which could be interesting would be to generalize the "recaptureSquare" parameter to a "recaptureSquares" bitboard (note the plural), where we would accumulate in this bitboard all the capture squares during the first N levels of qsearch, and the next levels would finish all the capture sequences on these squares. This would still be bounded and maybe more precise than what we have in master at the moment.

This idea could be summarized like that:

* for depth 0, generate all captures, then all quiet checks
* for depth -1 to -4, generate all captures
* for depth < -4, finish all the recaptures sequences on the capture squares used at depths from 0 to -4

2) **If we believe that our evaluation function has reached a point where it is precise enough even in the middle of capturing sequences** : then we could try to go full in and truncate as in this patch, and choose the depth accordingly to maybe find an Elo gain.

Feedback about these ideas?

**Comment by DU-jdto** [comment]
I'd certainly be interested to see how the recaptureSquares bitboard idea would go, but I'd be surprised if there were much ELO to be had here. Based on bench testing, only around 2%-3% of qsearches reach DEPTH_QS_RECAPTURES in the first place. I imagine that's the main reason why there's no apparent regression to just truncating the qsearch at that point.

For data, I tested what percentage of DEPTH_QS_RECAPTURES qsearches that are set to fail low upon reaching the moves loop end up beating alpha (in the default bench). With master, it's about 12.75%. With a recaptureSquares bitboard, it's about 20.93%. With no restriction to recaptures at all, it's about 34.55%.

**Comment by mstembera** [comment]
Not sure if I implemented it correctly but here is my attempt
http://tests.stockfishchess.org/tests/view/5c8b16cd0ebc5925cffecc91
of @snicolet idea.

**Comment by lucasart** [comment]
Another solution to the qsearch explosion, is to use the SEE. if you reach the depth limit in QS, you return staticEval + SEE. You probably want to use staticEval = -INF when in check, and clamp the return value to avoid reporting mate scores or out of bounds scores. This should be simpler as it alleviates the need for a specific recapture only move generator logic. This is implemented in Demolito, with the difference that I recurse when in check (more elegant but shouldn't have much eli impact once the depth limit is deep enough).

**Comment by mcostalba** [comment]
Closing this one, current code makes sense, but after truncating the qsearch it becomes totally out of context (very complex for nothing). Moreover I am not sure we wat a truncated qsearch,

**Pull request closed without merging**
