### PR TITLE
[WiP] Allocate thread memory and stack with large pages

### PR DESCRIPTION
**Pull request by skiminki**
Allocate the thread memory and the thread stack using large pages. This
should give a little additional perf bump.

No functional change

### CODE REVIEW

**Comment by skiminki** [comment]
The performance increase seems to be <1% for me in single-threaded tests, almost within noise. Multithreaded tests are too noisy for me to measure, although they could get a bit better performance.

**Comment by snicolet** [comment]
Test with one thread: https://tests.stockfishchess.org/tests/view/5f6f9daa3b22d6afa506903c

**Comment by skiminki** [comment]
The 1-threaded fishtest should actually be representative, because most (all?) machines run multiple tests concurrently. I think it's safe to conclude that this patch is not a win.

I think that aligning threads and their stacks by 2MB may actually be slightly harmful. This could be because we end up adding more pressure to certain parts of the L2/L3 caches, rather than distributing the load more evenly throughout the cache lines. To illustrate, every thread memory starts now at the beginning of the cache sets, and every thread stack now begins from the same fixed location in the cache sets. Even with associativity, this will end up making the cache pressure correlated to certain lines within the sets. Without large pages, there's less correlation due to only 4kB alignment between the thread memory allocs.

I think there's still one more test to try, and that's adding random offset to both the thread memory object and the thread stack. This said, I don't expect huge gains.

**Comment by skiminki** [comment]
One more note. It is possible that large pages are actually never beneficial for thread memory. The small pages effectively add randomization at 4-kB page granularity to physical addresses. This could make the pressure within cache ways spread more evenly. With large pages, that randomization does not exist. L2/L3 cache way is typically larger than 4-kB, but smaller than 2 MB page. But I think it's still worth a test to put this matter to rest, if nothing else.

**Comment by skiminki** [comment]
STC test results for the updated patch:

```
LLR: -2.93 (-2.94,2.94) {-0.25,1.25}
Total: 81000 W: 9198 L: 9214 D: 62588
Ptnml(0-2): 377, 6385, 27018, 6317, 403
Elo | 0.17 [-0.96,1.39] (95%)
```
https://tests.stockfishchess.org/tests/view/5f705c153b22d6afa50690ce

I think we can safely conclude that large pages for the thread object and the stack is not a big win in STC. It is possible that with slightly larger hash sizes there's enough TLB pressure for a measurable gain, but I don't think this is an avenue worth pursuing.

It is possible that there's some more perf to be obtained by putting all the various shared items such as pre-baked tables, material hash, the code, etc, under large pages. However, I wouldn't expect there to be a big Elo potential left.

FYI @vondele 

I'll close this PR.

**Comment by vondele** [comment]
thanks

**Pull request closed without merging**
