### PR TITLE
Assorted cleanup of last patches

### PR DESCRIPTION
**Pull request by mcostalba**
No functional change.

### CODE REVIEW

**Comment by man4** [comment]
If we're getting rid of the default minimumSplitDepth of 0, shouldn't this line
```+  o["Min Split Depth"]       << Option(5, 0, 12, on_threads);```
be
```+  o["Min Split Depth"]       << Option(5, 1, 12, on_threads);```
?

**Comment by lucasart** [comment]
maybe we could even remove the UCI option Min Split Depth. I don't see the point of it. It's tuned to its optimal value, and end users will most likely misunderstand it and think they are improving SF by changing it (doing some NPS measures instead of ELO measures for example...)

**Comment by glinscott** [comment]
Looks good!

**Comment by zamar** [comment]
approved

**Pull request merged**
