### PR TITLE
Parameters Tweak

### PR DESCRIPTION
**Pull request by FauziAkram**
-----CLOSE THIS ONE PLS, I WILL OPEN A NEW ONE WITH A SINGLE COMMIT-----
This patch is a parameters tweak that passed both STC and LTC tests.

STC:
LLR: 2.94 (-2.94,2.94) <0.00,2.00>
Total: 80944 W: 21557 L: 21189 D: 38198
Ptnml(0-2): 192, 8883, 22028, 9103, 266
https://tests.stockfishchess.org/tests/view/63b07fe2d421d8f75795a03b

LTC: 
LLR: 2.95 (-2.94,2.94) <0.50,2.50>
Total: 30440 W: 8296 L: 8007 D: 14137
Ptnml(0-2): 6, 2893, 9143, 3162, 16
https://tests.stockfishchess.org/tests/view/63b167d02ab1290f961644db

### CODE REVIEW

**Comment by dav1312** [comment]
> -----CLOSE THIS ONE PLS, I WILL OPEN A NEW ONE WITH A SINGLE COMMIT-----

Why don't you close this yourself? And why don't you squash the commits and force push?

**Comment by ppigazzini** [comment]
@FauziAkram 
```bash
git checkout fzl10
git fetch -p upstream
git rebase -i upstream/master
# this open the editor
# keep "pick" for the first commit
# replace "pick" with "squash" for other commits
# save and exit
git push -f origin fzl10
```

**Comment by pschneider1968** [comment]
@ppigazzini Thanks for being helpful! 👍

**Comment by FauziAkram** [comment]
> > -----CLOSE THIS ONE PLS, I WILL OPEN A NEW ONE WITH A SINGLE COMMIT-----
> 
> Why don't you close this yourself? And why don't you squash the commits and force push?

I didn't know there is the option to close it by myself, but now I just found it at the end of the page.
Sorry for not being an expert, I try to do my best.

**Pull request closed without merging**
