### PR TITLE
Remove depth for best thread

### PR DESCRIPTION
**Pull request by jcalovski**
STC 3 threads:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 25206 W: 4135 L: 4021 D: 17050
http://tests.stockfishchess.org/tests/view/569f6e340ebc595aa8e28c48 

LTC 7 threads: 
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 40639 W: 5555 L: 5461 D: 29623
http://tests.stockfishchess.org/tests/view/56a313350ebc590247cdf7e8

Resolves #583

### CODE REVIEW

**Comment by joergoster** [comment]
Congrats!

**Comment by pb00067** [comment]
Test http://tests.stockfishchess.org/tests/view/5699fcc20ebc594a0871d8cc
is suggesting that thread quality depends on according skip-size in the half-density-map.
Thus IMO it is necessary to test this also with higher number of threads (bigger skip-sizes),
but let maintainers decide.

**Comment by mcostalba** [comment]
completedDepth is used to avoid reporting a stale score, perhaps after a
fail high/low, so IMO this patch seems to introduce a logic bug, the fact
that the bug as no ELO impact does not change its nature as a bug.

**Comment by jcalovski** [comment]
Interesting and valid comments. Let me know if there's anything further you need me to test out or alternatively close this PR.

**Comment by zamar** [comment]
Looks suspicious, but I need to take a longer look during the weekend...

**Comment by zamar** [comment]
Unfortunately, I consider this change to be too risky. We don't want to commit stuff like just for the sake of removing one line of code.

The only situation we would be willing to commit the patch is if it could demonstrate an ELO gain.

Thus I'm closing the pull request, but feel to reopen if an ELO gain can be proven.

**Pull request closed without merging**
