### PR TITLE
Another set of tuned values after one million games

### PR DESCRIPTION
**Pull request by snicolet**
Another set of tuned values, obtained by a long session of one million games
by user "candirufish".

STC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 15810 W: 3687 L: 3458 D: 8665
http://tests.stockfishchess.org/tests/view/5b2d32f60ebc5902b2e55d9e

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 102118 W: 18146 L: 17651 D: 66321
http://tests.stockfishchess.org/tests/view/5b2d372c0ebc5902b2e55e0a

Bench: 4557946

### CODE REVIEW

**Comment by snicolet** [comment]
Merged via efd4ca27c4d7abad41e0469aa9b3b26b12068914, congrats :-)

**Comment by double-beep** [comment]
Congrats @candirufish! You are the master of values!

**Comment by tomtor** [comment]
Congrats!

Please note that the current 2100000 game tuning run

http://tests.stockfishchess.org/tests/view/5b2eb6df0ebc5902b2e57514

is getting closer to the maximum number of games fishtest can handle with
the current 250 game batch size implementation. It is currently allready a
bit slower then usual.



Op za 23 jun. 2018 20:18 schreef double-beep <notifications@github.com>:

**Comment by double-beep** [comment]
Is @candirufish written in the `AUTHORS` file?

**Pull request closed without merging**
