### PR TITLE
Dbg_pring_formatting

### PR DESCRIPTION
**Pull request by Chess13234**
Change dbg_print to use a  better format and floating point percents.
Example New:
Total:6934970 Hits:226545 Hit rate:3.2667% 
Total:6934970 Mean:50.2187
Example master:
Total 6807287 Hits 220536 hit rate (%) 3
Total 6807287 Mean 52.6394

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
I prefer the old one.

- Adding ':' just increases the clutter

- 3% it is better than 3.2667% for the intended usage

**Comment by Chess13234** [comment]
@mcostalba  What is the intended usage and why it lacks precision?

**Comment by mcostalba** [comment]
I have always cared about the integer number when I have used dbg_hit(), and I have used it a lot (I don't know about you). I was a caring about 3% instead of 7% or 15% instead of 20%, because that is where the **real** cases for me.

If someone uses dbg_hit to differentiate between 3.1% and 3.2% I am **quite confident** to state that he is very probably misusing this tool and using it without understanding what he is doing. For instance, just change an arbitrarily bench position and the resulting change is very well beyond the decimal point.

I am talking as someone that **has used it for real**. I am not talking about hypothetical cases,

**Comment by Chess13234** [comment]
@mcostalba  How do you distinguish between 0.4% hit rate and 0.1% hit rate? (which is x4 difference)

**Comment by Chess13234** [comment]
@mcostalba "Adding ':' just increases the clutter"
Its makes it easy to distinguish where the number belongs visually:
With old format, any place in the string doesn't give hint where the number belongs, the number "220536" is ambiguosly linked to both "Hits"  and "hit rate"  in a long string:
Total 6807287 Hits 220536 hit rate (%) 3 Total 6807287 Hits 220536 hit rate (%) 3 Total 6807287 Hits 220536 hit rate (%) 3 Total 6807287 Hits 220536 hit rate (%) 3 Total 6807287 Hits 220536 hit rate (%) 3

With new format the ":" signifies relation between  VARIABLE:NUMBER (where variable appears before number, making it linked to number )
Total:6934970 Hits:226545 Hit rate:3.2667% Total:6934970 Hits:226545 Hit rate:3.2667% Total:6934970 Hits:226545 Hit rate:3.2667% Total:6934970 Hits:226545 Hit rate:3.2667% Total:6934970 Hits:226545 Hit rate:3.2667%

**Comment by Chess13234** [comment]
Speaking of real-world usage here is the current dump of error rate of experimental lazy eval vs earlier 0.04% test:
nfo depth 31 seldepth 40 multipv 1 score cp 37 upperbound nodes 128824638 nps 1313049 hashfull 1000 tbhits 0 time 98111 pv d2d4 e7e6
info depth 31 currmove d2d4 currmovenumber 1
Total:3477908 Hits:145 Hit rate:0.00416917% 
Total:3513080 Hits:145 Hit rate:0.00412743% 
Total:3559256 Hits:145 Hit rate:0.00407389% 
Total:3621510 Hits:146 Hit rate:0.00403147% 
Total:3685814 Hits:147 Hit rate:0.00398826% 
Total:3730493 Hits:148 Hit rate:0.0039673% 
Total:3768570 Hits:148 Hit rate:0.00392722% 
Total:3799457 Hits:148 Hit rate:0.00389529% 
Total:3838388 Hits:149 Hit rate:0.00388184% 
Total:3882425 Hits:149 Hit rate:0.00383781% 
Total:3933620 Hits:149 Hit rate:0.00378786% 
Total:3972431 Hits:149 Hit rate:0.00375085% 
Total:4010996 Hits:150 Hit rate:0.00373972% 
Total:4048333 Hits:150 Hit rate:0.00370523% 
Total:4096661 Hits:155 Hit rate:0.00378357% 
Total:4134965 Hits:155 Hit rate:0.00374852% 
Total:4169226 Hits:156 Hit rate:0.0037417%

**Comment by snicolet** [comment]
@Chess13234 You can use dbg_mean_of() with boolean variables to get what you are looking for, for the rare cases when the precision of dbg_hit() is not enough for you.

bool A = .... ;      // a condition
bool B = .... ;      // a condition
bool C = .... ;      // a condition

dbg_mean_of(A);            // probability that A is true
dbg_mean_of(A == B);   // probability that A and B are equivalent
dbg_mean_of( !A || B);   // probability that A implies B
if (A) dbg_mean_of(B);   // conditional probability of B, given A

**Comment by Chess13234** [comment]
@snicolet  Its far simpler to just allow doubles in dbg_hit_on

**Comment by snicolet** [comment]
Except that Marco opposes the change, and that he has good reasons to do so.
I propose you a solution, if you don't use it, what can I do? :-)

**Comment by snicolet** [comment]
I agree. I have been routinely using dbg_mean_of() instead of dbg_hit() for four years now, and it has served me well.

**Comment by Chess13234** [comment]
The whole argument for using only integers in dbg_print() to 
force low precision results seems bizzare, as if its the job
of stockfish is to regulate programmers to prevent "misusing this tool" instead of giving unambiguous, precised results and leaving humans to interpret them.

Maybe there was some previous incident, thread or issue I am not aware of, where dbg_hit_on was used as argument for something on the ground of low percent difference?
@mcostalba seems certain dbg_hit_on was misused somehow in the past, but it was returning integers from the 
first commit to now.
https://github.com/official-stockfish/Stockfish/commit/61f41a057dd84a38e5cc9c58b37a30bfa00e253a

**Comment by Chess13234** [comment]
Another example of real-world usage:
This data was obtained with patched dbg_print

Error rate in current master(v outside ltb -400,400 LTy=1500) for captures in Lazy Eval(disabled and measured 'lazyv'=value of lazy eval,
 'v'=final eval value at end of eval):
method:
dbg_hit_on(abs(lazyv)>lty&& ( type_of(pos.captured_piece())==PIECE_TYPE),
((lazyv>lty  && v<ltb )||(lazyv<-lty && v>-ltb ))
);
per 100m nodes(command:go nodes 100000000) from start position:
PAWN:Total:204160 Hits:370 Hit rate:0.18123% 
KNIGHT: Total:261415 Hits:357 Hit rate:0.136564% 
BISHOP: Total:198606 Hits:232 Hit rate:0.116814%
ROOK: Total:53735 Hits:354 Hit rate:0.658788% 
QUEEN: Total:1526399 Hits:50 Hit rate:0.00327568% 
Average capture:Total:2250900 Hits:1363 Hit rate:0.0605536% 
(using dbg_hit_on(abs(lazyv)>lty&& ( (pos.captured_piece())),
((lazyv>lty  && v<ltb )||(lazyv<-lty && v>-ltb ))
);
Average non-capture: Total:546986 Hits:1656 Hit rate:0.30275% 
using:
dbg_hit_on(abs(lazyv)>lty&& ( (!pos.captured_piece())),
((lazyv>lty  && v<ltb )||(lazyv<-lty && v>-ltb ))
);

**Comment by Alayan-stk-2** [comment]
> @Chess13234 You can use dbg_mean_of() with boolean variables to get what you are looking for, for the rare cases when the precision of dbg_hit() is not enough for you.

I had done this the other day when I wanted to get a % which was in the low range, but it feels more like a hacky workaround. At least one decimal number would be nice.

However, arguably that the dbg numbers are based on bench make the % more unreliable than this rounding for % > 2 (and make displaying the double up to 7 numbers after the . meaningless)

**Comment by mcostalba** [comment]
@Chess13234 I am sorry but I am not a native speaker so perhaps I was not clear enough. I will try to repeat in a possibly more clear way:

If you use dbg_hit on bench position and you value the decimals to make conclusions then you are doing the wrong thing because you can't get any conclusion out of it considering that the bench positions are totally arbitrary and the decimals are like **random numbers**: if you change the bench positions you change them too.

So, to summarize you concerns:

1. How do you distinguish between 0.4% hit rate and 0.1% hit rate? (which is x4 difference and both will appear as 0%): 

Yes, and **it is good that both are zero**.


2. The whole argument for using only integers in dbg_print() to force low precision results seems bizzare, as if its the job of stockfish is to regulate programmers to prevent "misusing this tool" instead of giving unambiguous, precised results and leaving humans to interpret them. 

Your statement about "unambiguous, precised results" it shows that **you have not understood the point**, please take a bit of time to **re-read it** instead of keeping writing something else.

3. @mcostalba seems certain dbg_hit_on was misused somehow in the past, but it was returning integers from the first commit to now.

This of course is totally out of you dreams. Where did I have say that dbg_hit_on was misused in the past?

Please give more value to the details, details are important, words are important. One word is not the same of another, even if they appear to be similar...

**Comment by Chess13234** [comment]
@mcostalba "considering that the bench positions are totally arbitrary and the decimals are like random numbers:"
That bench position is the starting position. 
The decimals have meaning. Is it really hard to allow it to display 0.2% and 0.01% instead of 0 and 0?
"Yes, and it is good that both are zero."
Its bad.Why would anyone be deliberately wanting to reduce displayed information down to integers?
Why you insist that sub 1% data is meaningless? 
According to this logic Stockfish losing on 0.1% of positions
 and 0.9% of position is the same thing.

"t you have not understood the point, "
I don't see the point of arguing that dbg_hit_on returning integers while dbg_mean_of returns doubles, and people here complaining that they had to use convoluted solutions involving booleans and dbg_mean_of because dbg_hit_on results doesn't have precision required for sub 1% rates. 

" Where did I have say that dbg_hit_on was misused in the past?" You hinted at this in "If someone uses dbg_hit to differentiate between 3.1% and 3.2% I am quite confident to state that he is very probably misusing this tool and using it without understanding what he is doing."
So i assume you had an argument based on past incidents, however this now appears to be pure conjecture on your part and no misuses have ever occured.

**Comment by snicolet** [comment]
I think that everything has been said about this issue, so I close the pull request to avoid the continuation of the bitter discussion :-)

**Pull request closed without merging**
