### PR TITLE
Simplify KingRing Calculations

### PR DESCRIPTION
**Pull request by protonspring**
This is non-functional and untested.

Removes all branching and I think uses less instructions than master.

An earlier version of this (that also shifted down Rank8) passed STC , but this version uses less instructions and is non-functional.  Do I need to test?

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 83570 W: 18130 L: 18130 D: 47310
http://tests.stockfishchess.org/tests/view/5c2b048f0ebc592815d81fa8

### CODE REVIEW

**Comment by snicolet** [comment]
When I review code, and especially the myriad of simplifications proposed on Github for Stockfish, I always have the grand-father's razor argument in the back of my head: if I had to explain the code line by line to my grand-father (variant: to a classroom of students), which version would be simpler to explain?

Here I think that I would spend less time explaining to my classroom of students what lines 263-270 do in original master rather than the tricky lines 265-267 in the proposed patch. And I would add that the very fact that your first version of your simplification attempt was buggy shows that the simplification is not so simple nor so readable :-)

However the introduction of the `Square ksq = pos.square<KING>(Us);` variable is a good idea and would help readability of lines 265-267 in master, so I favor that!

**Comment by mcostalba** [comment]
@snicolet I could add the `Square ksq = pos.square<KING>(Us);` to my trivial stuff PR.

**Comment by protonspring** [comment]
I never write bugs . . . . . just unintentional features. :)

**Comment by snicolet** [comment]
@mcostalba I'm fine with adding it to your trivial stuff PR :-)

**Pull request closed without merging**
