### PR TITLE
Assorted trivial cleanups, October 2019

### PR DESCRIPTION
**Pull request by snicolet**
Assorted trivial cleanups

### CODE REVIEW

**Comment by mstembera** [comment]
The Thread::best_move_count(Move move) method should be const.

**Comment by Lolligerhans** [comment]
In the new attack span computation pawns.cpp:118
```
e->pawnAttacksSpan[Us] |=  pawn_attack_span(Us, s) &
  ~pawn_attack_span(Us, frontmost_sq(Them, opposed));
```
is shorter with XOR:
```
e->pawnAttacksSpan[Us] |=  pawn_attack_span(Us, s) ^
  pawn_attack_span(Us, frontmost_sq(Them, opposed));
``` 
.

Even shorter is
```
e->pawnAttacksSpan[Us] |=  pawn_attack_span(Us, s) ^
  (opposed ? pawn_attack_span(Us, frontmost_sq(Them, opposed)) : 0);
```
replacing the if-else statements (a similar syntax is used in line 207 already), but it's a matter of taste to keep the if-else alternatively.

These are non-functional.

**Comment by protonspring** [comment]
bitboard.h: 97

We only need to shift once here:
\-  unsigned hi = unsigned(occupied >> 32) & unsigned(mask >> 32);
\+  unsigned hi = unsigned((occupied & mask) >> 32);

**Comment by snicolet** [comment]
signature of futility_move_count () should be `futility_move_count(bool improving, Depth depth)`

**Comment by Rocky640** [comment]
for consistency, in tbprobe.cpp and search.cpp,
replace the !! with a bool() as we do elsewhere.

**Comment by Rocky640** [comment]
in evaluate.cpp line 599 since it is used only once, we might want to remove
`File f = file_of(s);`
and update line 649 as follow
`map_to_queenside(file_of(s));`

**Comment by snicolet** [comment]
@mstembera 
When I try to make thread::best_move_count() a const I get the following warning with Clang:
`./thread.h:59:3: warning: 'const' type qualifier on return type has no effect `

**Comment by snicolet** [comment]
> bitboard.h: 97
> We only need to shift once here:
> - unsigned hi = unsigned(occupied >> 32) & unsigned(mask >> 32);
> + unsigned hi = unsigned((occupied & mask) >> 32);

@protonspring This code is only used on 32 bits machines, and on 32 bits machines the master version is faster.

**Comment by mstembera** [comment]
@snicolet That warning seems like it came from 
```C++
const int best_move_count(Move move);
```
I instead intended
```C++
int best_move_count(Move move) const;
```
I don't have Clang to test atm but I don't get any warnings for the second version from either gcc or MSVC.  Can you confirm?

**Comment by Rocky640** [comment]
evaluate.cpp line 767 contains some blanks
`sf = std::max(0, sf - (pos.rule50_count() - 12) / 4  );`

**Comment by 31m059** [comment]
The AUTHORS list appears to be missing an author, responsible for this Elo-gainer:
https://github.com/official-stockfish/Stockfish/pull/1694

**Comment by protonspring** [comment]
There are about 100 of those if that form is preferred.

**Comment by adentong** [comment]
thread.cpp 73-80 the spacing looks a bit off.

**Comment by protonspring** [comment]
This pieces() method can be removed with a default argument to pieces(PieceType).   Generates exactly the same executable.

diff --git a/src/position.h b/src/position.h
index a0a9a306..cdf74ce1 100644
--- a/src/position.h
+++ b/src/position.h
@@ -83,8 +83,7 @@ public:
   const std::string fen() const;

   // Position representation
-  Bitboard pieces() const;
-  Bitboard pieces(PieceType pt) const;
+  Bitboard pieces(PieceType pt = ALL_PIECES) const;
   Bitboard pieces(PieceType pt1, PieceType pt2) const;
   Bitboard pieces(Color c) const;
   Bitboard pieces(Color c, PieceType pt) const;
@@ -219,10 +218,6 @@ inline Piece Position::moved_piece(Move m) const {
   return board[from_sq(m)];
 }

-inline Bitboard Position::pieces() const {
-  return byTypeBB[ALL_PIECES];
-}
-
 inline Bitboard Position::pieces(PieceType pt) const {
   return byTypeBB[pt];
 }

**Comment by Rocky640** [comment]
https://github.com/official-stockfish/Stockfish/issues/2356

**Comment by protonspring** [comment]
types.h line 344:

\-  // Multiplication of a Score by an boolean

\+ // Multiplication of a Score by a boolean

**Comment by Rocky640** [comment]
tbprobe.pp

       ```
 tbFile = file_of(squares[0]);
        if (tbFile > FILE_D)
            tbFile = file_of(squares[0] ^ 7); // Horizontal flip: SQ_H1 -> SQ_A1
```
can be changed to
` tbFile =map_to_queenside(file_of(squares[0]));
`

**Comment by vondele** [comment]
```diff
diff --git a/src/search.cpp b/src/search.cpp
index 6e59bb541..3667796d5 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -594,7 +594,7 @@ namespace {
     Move ttMove, move, excludedMove, bestMove;
     Depth extension, newDepth;
     Value bestValue, value, ttValue, eval, maxValue;
-    bool ttHit, ttPv, inCheck, givesCheck, improving, doLMR, priorCapture;
+    bool ttHit, ttPv, inCheck, givesCheck, improving, didLMR, priorCapture;
     bool captureOrPromotion, doFullDepthSearch, moveCountPruning, ttCapture;
     Piece movedPiece;
     int moveCount, captureCount, quietCount, singularLMR;
@@ -1153,17 +1153,17 @@ moves_loop: // When in check, search starts from here
 
           value = -search<NonPV>(pos, ss+1, -(alpha+1), -alpha, d, true);
 
-          doFullDepthSearch = (value > alpha && d != newDepth), doLMR = true;
+          doFullDepthSearch = (value > alpha && d != newDepth), didLMR = true;
       }
       else
-          doFullDepthSearch = !PvNode || moveCount > 1, doLMR = false;
+          doFullDepthSearch = !PvNode || moveCount > 1, didLMR = false;
 
       // Step 17. Full depth search when LMR is skipped or fails high
       if (doFullDepthSearch)
       {
           value = -search<NonPV>(pos, ss+1, -(alpha+1), -alpha, newDepth, !cutNode);
 
-          if (doLMR && !captureOrPromotion)
+          if (didLMR && !captureOrPromotion)
           {
               int bonus = value > alpha ?  stat_bonus(newDepth)
                                         : -stat_bonus(newDepth);
```

**Comment by mstembera** [comment]
Line 289 in position.h (inside Bitboard Position::attacks_from(Square s))
```C++
  assert(Pt != PAWN);
```
could be changed to
```C++
static_assert(Pt != PAWN, "PAWN attacks need color");
```
so we catch any bad usage earlier at compile time instead of run time.

**Comment by protonspring** [comment]
http://tests.stockfishchess.org/tests/view/5dab72110ebc590de13a30d8

**Comment by protonspring** [comment]
The conditions for these loops in Thread::clear() are identical and can be combined.

diff --git a/src/thread.cpp b/src/thread.cpp
index 476f1d64..0a6c60cc 100644
\--- a/src/thread.cpp
\+++ b/src/thread.cpp
@@ -72,13 +72,13 @@ void Thread::clear() {

   for (bool inCheck : { false, true })
          for (StatsType c : { NoCaptures, Captures })
\+          {
                  for (auto& to : continuationHistory[inCheck][c])
                          for (auto& h : to)
                                  h->fill(0);

\-  for (bool inCheck : { false, true })
\-         for (StatsType c : { NoCaptures, Captures })
\-      continuationHistory[inCheck][c][NO_PIECE][0]->fill(Search::CounterMovePruneThreshold - 1);
\+                  continuationHistory[inCheck][c][NO_PIECE][0]->fill(Search::CounterMovePruneThreshold \- 1);
\+          }

**Comment by mstembera** [comment]
In movegen.cpp
line 190 can be
```C++
static_assert(Pt != KING && Pt != PAWN, "Unsupported piece type");
```
and line 264 can be
```C++
static_assert(Type == CAPTURES || Type == QUIETS || Type == NON_EVASIONS, "Unsupported GenType");
```
so we catch these sooner at compile time instead of run time.

**Comment by snicolet** [comment]
Merged via 90c0385724a0d9b6c0737bc2711ad77e315d17ac, thanks to all!

**Comment by Lolligerhans** [comment]
Some empty array Elements in PSQT: https://github.com/Lolligerhans/Stockfish/commit/9e686f341425b63b120444c27fb4d5d1424305bc.

**Pull request merged**
