### PR TITLE
Move endcaptures at the beginning of moves array

### PR DESCRIPTION
**Pull request by mcostalba**
Revert to old move ordering and picking logic but with an added optimization (took from the previous  patch) that should improve cache access.

No functional change,

### CODE REVIEW

**Comment by mcostalba** [comment]
This is possibly the only good idea in the movepicker speed optimization patch. So just extract and test it. I have a small speed up in my local tests, but I would like a confirmation from other people. Thanks.

**Comment by gogamoga1** [comment]
2 different PGO, both for master and commit

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1736489   1697867   38622     
    StDev   4955      6897      3259      

p-value: 0
speedup: -0,022

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1737887   1700001   37886     
    StDev   9689      8756      3279      

p-value: 0
speedup: -0,022

major slowdown

**Comment by snicolet** [comment]
I have make some speed tests with the following non-pgo builds:

**master-ronald** = current master, with patch 438805aee853de93b2ed0f24a51fae873509b885 "Integrate next_stage() logic into next_move() "

**master-previous** = master without Ronald's patch (so after commit ace8e951d70c2986a0af83effcc0d2b2312d29e3 "Simplify code for pinaware SEE")

**SF-endcap** = the version in this PR, which is master-previous but with Marco's bad captures at beginning of array

=============

Results (each comparison using parallel long runs):

A) SF-endcap versus master-previous : no speed difference (speed-up ≈ 0.1%)

Total time (ms) : 175162
Nodes searched  : 236653841
Nodes/second    : 1351056
SF-endcap

Total time (ms) : 175378
Nodes searched  : 236653841
Nodes/second    : 1349392
master-previous

B) master-ronald vs master-previous : master-previous is 2,1% slower than master-ronald

Total time (ms) : 171398
Nodes searched  : 236653841
Nodes/second    : 1380726
master-ronald

Total time (ms) : 175095
Nodes searched  : 236653841
Nodes/second    : 1351573
master-previous

C) master-ronald vs SF-endcap : master-ronald is 1.9% faster than SF-endcap
  (this confirm tests (A) and (B))

Total time (ms) : 171726
Nodes searched  : 236653841
Nodes/second    : 1378089
master

Total time (ms) : 175016
Nodes searched  : 236653841
Nodes/second    : 1352184
testedpatch

=====================

Conclusion: the speed of Ronald's patch does not come from the caching
improvement.

Question @syzygy1 : where does it comes from? :-) 
•Inlining?
•Avoiding a switch?
•etc

**Comment by syzygy1** [comment]
@snicolet: reducing the number of branches by having a single switch. Just look at SF's current move selection and follow the flow of control.

My main reason for moving bad captures to the front was to make it possible to have one single big per-thread array for generated moves (which I believe gave a measurable speedup in my experimental C port of Stockfish). That is not part of this patch (and I have much better things to do than to annoy Marco with it), but I thought moving bad captures to the front was anyway a nice idea. In principle it should also allow for a small reduction of the MAX_MOVES value (assuming the current value takes into account that extra room must be reserved for the bad captures).

I think in my own private (never released and not very strong) engine I place bad captures immediately behind the array of captures and then skip to the end of that bad captures array to generate quiet moves (and go back to the bad captures later). So it seems easy to miss that one can simply copy the bad captures over the captures that the engine has already looked at. (But I'm sure there are many programs that do it this way.)

I wonder if some speed up is possible by removing the killers and ttmove from the quiet moves in one go. Maybe not, because SF prunes a lot, but who knows. And perhaps one could sort quiets one by one instead of in one step, but that has probably been tested a lot already.

At the risk of the introduction of a slowdown: SF is partitioning the quiets using a function that is not guaranteed to give the same order across platforms. (But all platforms likely implement it in the same way.)

**Comment by mcostalba** [comment]
Thanks for testing. I am closing this one.

**Pull request closed without merging**
