### PR TITLE
Use per-thread counterMoveHistory

### PR DESCRIPTION
**Pull request by mcostalba**
Drops a scalability bottleneck due to memory contention
of a single shared table across threads. The effect starts
to be sensible with a high number of threads. Specifically
we have a small regression with 7 threads both at 60 and
180 seconds TC:

10000 @ 60+0.6 th 7
ELO: -2.46 +-3.2 (95%) LOS: 6.5%
Total: 9896 W: 1037 L: 1107 D: 7752

5000 @ 180+0.6 th 7
ELO: -1.95 +-4.1 (95%) LOS: 17.7%
Total: 5000 W: 444 L: 472 D: 4084

We have a regression because counterMoveHistory table is
quite big and it takes time for a single thread to fill it.
Sharing the table yields to a higher fill rate and better
quality of moves and up to 7 threads the benefits of sharing
more then compensate the loss in speed due to contention.
Interestingly even with a 3X longer TC, so with more time
for the single thread to catch up, the improvment is quite
limited and below noise level. It seems we really need much
longer TC to saturate the table.

When we move to high threads number it's another story:

5000 @ 60+0.6 th 22
ELO: 3.49 +-4.3 (95%) LOS: 94.6%
Total: 4880 W: 490 L: 441 D: 3949

2000 @ 60+0.6 th 32
ELO: 8.34 +-6.9 (95%) LOS: 99.1%
Total: 2000 W: 229 L: 181 D: 1590

As expected the speed-up more than compensates the filling
rate, and we expect that with tournament TC, where single
thread is able to saturate the table, the difference will
be even stronger. For instance for TCEC 9 super-final time
control will be 180 minutes + 15 seconds and this scalability
improvement seems definitely the way to go.

So, summarizing:

GOOD:
 - Measured big improvement in high core scenario

 - Suitable for TCEC 9 superfinal (big hardware, very long TC)

 - Consistent and natural patch that extends to counterMoveHistory
   what we already do for remaining history tables, that are all per-thread

 - Non functional change for the common case of a single core

 - Very simple (just 6 lines modified, no added ones)

BAD:
 - Small regression (within 2-3 ELO) with few threads and short TC

bench: 6024713

### CODE REVIEW

**Comment by DamasClasicas** [comment]
Yeah, a very good change specially in computers with lot of cores!

Congratulations Marco!!

**Comment by ajithcj** [comment]
>> Interestingly even with a 3X longer TC, so with more time
for the single thread to catch up, the improvment is quite
limited and below noise level.

I suspect that the gain comes when we use machines with multiple numa nodes(>2).
I suspect the 7-thread test used machines with 1 or 2 numa nodes. The 32-thread test *had* to use machines with 3 or more numa nodes. Accessing a table on another node is a lot more expensive than accessing on the same node.

**Comment by syzygy1** [comment]
The gain on numa machines is probably not explained by the table being on the same node as the thread, because no attempt is made to enforce that, but by the table being accessed only by a single thread. If two threads on different nodes write to and read from the same table, they will continuously invalidate each other's cache lines resulting in lots of data being forwarded between nodes. If each thread has its own table, no data is forwarded between nodes as long as the data fits in the nodes' cpu caches.

If a table is accessed by multiple threads, but all on the same node, then that will probably do as well as this patch in terms of memory delays (and probably better because the shared L2 or L3 will be used more efficiently). Even better still is having that table on the same nodes as those threads, because that makes the cache misses cheaper. And letting multiple threads share a table also seems beneficial in that the table has better quality information.

Ulrich Drepper's paper "What every programmer should know about memory" discusses NUMA and other memory topics and is very interesting.

**Comment by mcostalba** [comment]
Merged with 4fbba64e4670dd5b3

For now just commit this one that seems comparable strength of NUMA on 32 cores. We defer to a later step correct handling of more than 64 processors on Windows (that seems the real reason to exists for NUMA patch).

**Comment by ppigazzini** [comment]
@Marco: if this commit regards the thread_cm code of the below thread, NUMA is a big speedup on Intel (24 physical cores) respect to thread_cm

                                       1 thread       24 threads         48 threads (HT)
thread_cm vs master     -0.068%          +8.057%             +5.278%
numa vs master             -2.836%        +44.299%            +3.431% 

https://groups.google.com/forum/?fromgroups=#!searchin/fishcooking/numa%7Csort:relevance/fishcooking/ezt6MrAuXqs/qIR2HEciEgAJ

**Comment by mcostalba** [comment]
@ppigazzini it is very difficult to evaluate just by speed, indeed it seemed that on CoffeOne machine NUMA was better in nps but then when testing on fishtest it was at least on par (and possibly inferior), so I made up my mind that speed tests are very misleading and only true fishtest games can be considered reliable. In case you have such a big machine and want to run it on fishtest please tell me and I will setup a proper test 60 seconds, fixed games made to run on your machine, with such big speed difference also a 1000 games is enough, so I can push a high priority test with 24 or 48 threads and then you connect your machine to be sure it will be picked up correctly.

**Comment by ppigazzini** [comment]
@mcostalba: this Intel machine is used h24 to crunch numbers, I cannot use it for fishtest.

NUMA vs CM AMD @ 32 cores - speedup = +7%
NUMA vs CM Intel @ 24 cores - speedup = +32%

IMO it's important for the NUMA vs. CM 32 test to add the CPU information

**Comment by mcostalba** [comment]
Yes, it would be useful to know which machines ran the numa vs thread_cm
fishtest.

**Comment by lp--** [comment]
Result for numa vs thread_cm before it was prematurely stopped.
sterni1971-32cores                                    1016                90   75    851        
CoffeeOne-57cores-448	5 hours ago	363 / 1000	26	33	304

sterni1971 +5.17 +- 8.85
CoffeeOne   -6.74 +- 14.81

For both machines we don't know if numa patch correctly recognize hardware and bind  threads to nodes as it should  do 

master vs thread_cm were run we small amount of games. All tests except one showed neutral result.
One statistically significant  test  had 2000 games and 32 threads and run only on one machine --  sterni1971

For me it looks like sterni1971 has substantially non-uniform memory so we can see some difference. Not sure how non-uniform  CoffeeOne is.

**Pull request closed without merging**
