### PR TITLE
Use intrinsics only for LSB/MSB

### PR DESCRIPTION
**Pull request by lucasart**
The NO_BSF does not cover any real life use-case today. The only compilers that
can compile SF today, with the current Makefile and no source code changes, are
either GCC compatible (define `__GNUC__`) or MSVC compatible (define `_MSC_VER`). So
they all support LSB/MSB intrinsics.

Note the (legacy) MSVC/WIN32 case, where we use a 32-bit BSF/BSR solution, as
64-bit intrinsics aren't available there.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Makefile should be updated too for consistency

**Comment by snicolet** [comment]
> Makefile should be updated too for consistency

What do you mean? For the ARM case?

**Comment by lucasart** [comment]
There is no impact in ARM case. That's because the compiler is GCC or Clang, hence defined `__GNUC__`.

**Comment by snicolet** [comment]
Merged via edf4c07d251f1d6c709d47969bfe1452194d9430.
Thanks !

**Pull request closed without merging**
