### PR TITLE
KingSafety081

### PR DESCRIPTION
**Pull request by fbv-sf**
Hi

This test passed both time controls

King safety is all over the board

STC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 130209 W: 23516 L: 23581 D: 83112

LTC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 33541 W: 4563 L: 4460 D: 24518

Regards

### CODE REVIEW

**Comment by hazzl** [comment]
Especialy if they look like they might add ELO at longer time controls!

**Comment by zamar** [comment]
approved.

**Comment by fbv-sf** [comment]
Thank you. I have to do some thing more on this?

**Comment by joergoster** [comment]
Congrats!

**Comment by snicolet** [comment]
@fbv-sf : to answer your question (something more on this?) you may want to

a) maybe re-order the code to move lines 285-289 just before the return statement, to improve locality and compute the `minKingPawnDistance` value just before it is used. If you re-order the code, please check if there is no slow-down :-)

b) give the new bench number at the end of the pull request message, as it has changed!

Hope this helps, Stéphane

**Comment by zamar** [comment]
Just a second...

After taking a second look for this, for me it looks like that shelter_storm() function can't manage situations when king is on the 5th rank or higher.

So this patch may break the existing code...

**Comment by fbv-sf** [comment]
Is not the opposite?

The shelter bonus must apply not matter the rank?

This i what i had in mind when i saw the condition and recalled some games where stockfish king behaved  like he was invulnerable on the middle of the board.

I can tell you the STC test took way too many games to pass, but LTC was very good.
On my local tests, the more time i gave to the game the better. 

But how can we be sure? another test? Or just move on?

**Comment by KassiasGrandiel** [comment]
The bench is 8644370

**Comment by zamar** [comment]
I need to take a longer look at some point during the Easter...

The question is if shelter_storm() is going to behave nicely in all cases...

**Comment by mcostalba** [comment]
Patch seems safe. I have tested with:

```
  Value bonus = shelter_storm<Us>(pos, ksq);

  if (relative_rank(Us, ksq) > RANK_4)
  {
      auto s = test.size();
      test.insert(shelter_storm<Us>(pos, ksq));
      if (s != test.size())
          std::cerr << test.size() << std::endl;
  }
```

where:
`    std::set<Value> test;`

and after running a bench (with debug on) I counted 77 different values, so it seems code is safe and shelter_storm returns sensible numbers.

**Comment by zamar** [comment]
Thanks for verification, @mcostalba!

I was concerned about ShelterWeakness and StormDanger arrays, because values in some cases are defined only up to the fifth rank or so. But the default zero-initialization seems to do the trick in this case, so it should be safe to commit the patch...

**Pull request closed without merging**
