### PR TITLE
Update Stockfish::Eval::NNUE::Layers ClippedReLU

### PR DESCRIPTION
**Pull request by JackWright347**
optimize & eliminate compiler warning C6294 ill-defined for-loop: initial condition does not satisfy test. Loop body not executed.

### CODE REVIEW

**Comment by JackWright347** [comment]
as discussed here https://github.com/official-stockfish/Stockfish/issues/3577

**Comment by vondele** [comment]
@JackWright347 can you squash tthis in a single commit, and provide a commit message that describes the changes. Any particular reason to combine these different changes in one PR?

**Comment by JackWright347** [comment]
> 
> 
> @JackWright347 can you squash tthis in a single commit, and provide a commit message that describes the changes. Any particular reason to combine these different changes in one PR?

@vondele Will do. I'll try to squash them and provide a single message. The reason for the other changes (initialize uninicialized variables properly, wrap GCC specific pragmas etc.) was that the C++ compiler and the warning level I used for testing spit out quite a lot of easily avoidable warnings (and in case of unchecked sprintf buffer in src/nnue/evaluate_nnue.cpp in the current master even hard errors with compilation abort). You don't see them when you go over the current Makefile but they are still not good and easy to fix, so I did that right away.

**Comment by JackWright347** [comment]
@vondele Hi, I tried to use git squash command but it didn't work with the following error message:
"Unable to sqash. Squashing replays all commits up to the last one required for the sqash. A merge commit cannot exist among those commits." So I made a new branch /feature/constexpr_clippedrelu in my fork and opened a new PR 3644 with only one combined description of all changes, as requested, and I close this PR now as a duplicate.

**Pull request closed without merging**
