### PR TITLE
Distinct iteration paths

### PR DESCRIPTION
**Pull request by pb00068**
I let the numbers speak:

http://tests.stockfishchess.org/tests/view/566926a00ebc592d552a3f66
STC 5+0.1, threads 7
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 6026 W: 1047 L: 901 D: 4078
state: accepted

http://tests.stockfishchess.org/tests/view/566ac2390ebc592d552a3fd5
LTC: 20+0.2, threads 7
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 19739 W: 2910 L: 2721 D: 14108
state: accepted

http://tests.stockfishchess.org/tests/view/566c12e90ebc592d552a4019
STC 5+0.1, threads 20
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 2493 W: 462 L: 331 D: 1700
state: accepted

This one refers to an older commit, but the logic behind was already the same:
http://tests.stockfishchess.org/tests/view/56605eaa0ebc5902cdc08883
STC: 10+0.1, threads 3
ELO: 1.04 +-3.5 (95%) LOS: 71.8%
Total: 10000 W: 1370 L: 1340 D: 7290

### CODE REVIEW

**Comment by mstembera** [comment]
Congrats!!

**Comment by Yery** [comment]
Congrats! But would be nice to see the 20 thread also at slightly longer time control.

**Comment by mcostalba** [comment]
You should also add a description... Numbers alone don't explain what your
patch does.

**Comment by pb00068** [comment]
With joy I try to explain what I think that it does and explain my thoughts which leaded me to this patch.
This is a little long story:
When Jörg Oster tried his test no_altering (Don't alter the search depth of the helper threads), I tried to explain his failing with following: "...if all helper-threads never skip iterations,
I have the feeling, that their trees become to similar. So the danger might be, that they begin to analyze to much already analyzed ground."
Given that this my assumption was right then the converse argument must be that skipping iterations helps to keep the search-trees different between the threads which should give a benefit.
Thus we must try to keep them as different as possible but at the same time most sensible as possible. I also became aware that the current formula produces iteration skips in non-determinant almost unpredictable way. For instance it could happen that thread 1 skipped iteration on ply 10 and not on ply 11 whilst thread 2 did it in the opposite way. But after 2 halfmoves played on the board it could happen that these skips between these threads on those plies were again inverted. This leads to a certain degree of convergence in the trees (move histories) which is apparently counterproductive.
This is the reason why I take the game-ply into account in my formula.
As someone explained in the forum: we have trees in our meadow and we are responsible to make the wind. If we produce random wind the entropy grows to much and the trees remain to similar. Thus we needed a strict order/arragement for deciding which plies to skip and which not. The idea of distinct iteration paths was born.   
Initially I thougth that I have to apply a low density for ply/iteration skipping,
because otherwise I assumed the helper threads would fall behind to much in depth in regard to the main thread. To my surprise it wasn't the case. I saw that they more or less keept up with main-thread's depth also on longer tc. So the idea of half-density was born.
To be continued ...

**Comment by mcostalba** [comment]
Thanks for the explanation (hopefully maintainers will copy-paste into
commit log message).

At this point, giving the nature of the patch and that is very iteration
depth dependent I am wondering about a test at long TC with many threads,
just to have a bit more confidence that we don't have surprises at longer
TC.

**Comment by mcostalba** [comment]
I have pushed a commit above your patch series to cleanup a bit the code.

https://github.com/mcostalba/Stockfish/commit/ed99d2688f8c74c345af5b11

Pelae apply above your series before to merge upstream.

**Comment by mstembera** [comment]
Just my opinion but I think leaving the HalfDensityMap in the 0b form instead of the 0x form illustrates what is happening much more clearly.

**Comment by mcostalba** [comment]
Yes, but is not standard.

**Comment by mcostalba** [comment]
BTW I still don't understand why indices <= 6 and > 24 are treated differently

**Comment by pb00068** [comment]
A little bit patience, explanation about indices <= 6 and > 24 coming soon.

**Comment by pb00068** [comment]
I hope I did it right (applying and pushing the Reformat), @mcostalba ?

**Comment by zamar** [comment]
Something is wrong with the pull request. I'm not able to view the changes... Also github complains that there are merge conflicts.

**Comment by zamar** [comment]
The idea is interesting and sounds reasonable. Last time I looked the code was pretty messy and complicated, I wonder if we can simplify...

Anyhow, please correct the pull request first.

**Comment by zamar** [comment]
I've rescheduled the patch: 20 threads, 30+0.3, 8000 games.

Just to get some idea around how this scales.

**Comment by zamar** [comment]
Did you try just skipping every other ply? Does the matrix approach really make a difference compared to this?

**Comment by pb00068** [comment]
Sorry, what do you mean exactly with skipping every other ply?

**Comment by zamar** [comment]
if ((RootDepth + Threadidx) % 2) continue;

**Comment by pb00068** [comment]
Zamar, pleasy read (again) my description of the path above with attention. You will understand that your proposal leaves several aspects apart. I dare to predict that it would not bring that result.

**Comment by lp--** [comment]
I think if you do forced push to github (with -f), github  comments  to your commits (not pull request) will be removed.  But if you do simple  revert of last commit and normally push it I think it should be ok.

**Comment by pb00068** [comment]
I hope now I did the reformat properly.

**Comment by lantonov** [comment]
Congratulations! Matrices are needed because the 2 halves of a Hadamard matrix are orthogonal.

**Comment by glinscott** [comment]
Really nice idea!  Pull request looks good now :).  Approved.

**Comment by pb00068** [comment]
Hi all,

yesterday I verified if we would benefit from starting with bigger iteration skips.
So I made a quick test using only the 6 bit long half-density patterns (= the hardcoded HalfDensityMap) on 7-cores. The result seemed negative (but has to be verified with more games).
So I took a look again at the generated numbers for the for 8 bit long patterns (= the ones used for the threads with idx > 24 ) and I realized that these numbers already begin with 8-ply long giant-skips (=8 consecutive 1 followed by 8 consecutive 0). 
Even worser threads with idx 31 and above begin with 16-ply long 'monster' skips.
Such giant steps are surely counterproductive, so the formula has to be revised for big number of cores. I know it will become very hard to test it, since on fishtest I have never seen a machine with more than 24 cores, but there is a clear evidence that we must do something in that range.
I also propose to change the comment by removing the remark to Hadamard-matrixes.
The hint gives the patch bit of mathematical fashion, but seen in a sober light, our current matrix has almost nothing to do with them. Even the property of half-density is no dogma,
and it might be sensible to use some quasi-half-dense patterns before proceeding to bigger skips.

**Comment by lantonov** [comment]
Removing the reference to Hadamard matrices makes me lost about your idea. Is it to have as few overlapping threads as possible?

**Comment by pb00068** [comment]
In some way yes. From my perception the route of march must be keeping the iteration paths as distinct as possible (only partially overlaps) and with increasing cores (idx) proceed gradually from smaller skips to bigger ones.

**Comment by lantonov** [comment]
If your matrix core (idx) vs ply is build on the idea that each core must take exactly half of the plies and these half sets (of plies) should not overlap, it can be a Hadamard matrix, but also some of the many matrices of the so-called fractional designs, used in engineering. There are 1/2, 1/4, 1/8, 1/16, etc. fractional designs. Translated to our situation, these means that in 1/2 fractional, each core takes odd or even plies, in 1/4 fractional one core takes 1, 5, 9 .... ply, etc. In short, this is a ply modulo core.

**Comment by pb00068** [comment]
The problem with most of these algorithms is, that they are on exponential basis and do not fit the requirements I expressed in my posting before. And fractions 1/4 and below are not interesting, otherwise http://tests.stockfishchess.org/tests/view/56619c850ebc5902cdc088b9
would have brought positive results.

**Comment by ElbertoOne** [comment]
Result of the LTC test with 20 threads:
ELO: 8.86 +-3.7 (95%) LOS: 100.0%
Total: 8000 W: 1076 L: 872 D: 6052

Congratulations!

**Comment by KeepthePeace** [comment]
The Elo gain obviously looks great with 20 cores. That said, has it not been mentioned that with greater than 24 cores there will be issues with this patch concerning possible Elo regression ("counterproductive")?! As stated by pb00068:

"So I took a look again at the generated numbers for the patterns used for the threads with idx > 24 and I realized that these numbers already begin with 8-ply long giant-skips (=8 consecutive 1 followed by 8 consecutive zeros). 
Even worse, threads with idx 31 and above begin with 16-ply long 'monster' skips. Such giant steps are surely counterproductive, so the formula has to be revised for big number of cores. I know it will become very hard to test it, since on fishtest I have never seen a machine with more than 24 cores, but there is a clear evidence that we must do something in that range".

I have 28 cores\56 threads, so this concerns me. Of course, I'm way in the minority. But what can be done to ensure that this patch doesn't cause possible regression when running Stockfish on dual-socket systems like mine?! If anything, obviously this patch should be an Elo gain...

**Comment by pb00068** [comment]
To be on the more sure side, for the moment I would propose following change (non-functional for threads <= 24):

          int d = rootDepth + rootPos.game_ply();
          int idxMod = idx % 24;

          if (idxMod <= 6)
          {
              if (((d + idxMod) >> (msb(idxMod + 1) - 1)) % 2)
                  continue;
          }
          else
          {
              // Table of values of 6 bits with 3 of them set
              static const int HalfDensityMap[] = {
                      0x07, 0x0b, 0x0d, 0x0e, 0x13, 0x16, 0x19, 0x1a, 0x1c,
                      0x23, 0x25, 0x26, 0x29, 0x2c, 0x31, 0x32, 0x34, 0x38
              };

              if ((HalfDensityMap[idxMod - 7] >> (d % 6)) & 1)
                  continue;
          }

Practically thread idx 25 would work together with idx 1, thread idx 26 helps idx 2 and so one.
@KeepthePeace: would you be eventually be disposed to do some test on your machine for us? 

@Approvers, I think also your opinion is required now...

**Comment by KeepthePeace** [comment]
@pb00068 Yes absolutely. I'm going to install the fishtest worker in the next few days. It looks like there aren't a whole lot of dual-socket machines in Fishtest.

**Comment by mcostalba** [comment]
This is a good idea.

Still not clear why cannot be applied also for idx <= 6

**Comment by pb00068** [comment]
@mcostalba: Our hardcoded HalfDensityMap if currently for patterns of length 6 and it is not possible to fit in the 4bit-long patterns there. If you for instance incorporate the 0011 pattern in the our 6-bit map then the sequence you obtain over longer distance is not the desired 0011001100110011... it would become something like 001100001100001100.

P.S.: Should I commit my proposal into this pull-request?
I also propose to rename the variable d in p, since ply renders the idea more than depth in my opinion. 
Exists there a time-plan when this pull-request will be merged into master?
I ask because on fishtest there are going on smp-tests, which results may be meaningless (at least to be repeated) once this pull-request will be merged.

**Comment by mcostalba** [comment]
Ok to rename d in p. Joona wanted to test with 20 cores and results are
more than positive so I think this patch is ready to be merged now.

I also see that in fishtest there are some meaningless  SMP test like this
one:

http://tests.stockfishchess.org/tests/view/5670c4df0ebc592d552a41af

Here again I want to sensibilize approves that if we wanted robot-approvals
we would have made it automatically: an approver should put some 'human
brain' in his action.

**Comment by pb00068** [comment]
@mcostalba Should I push the proposed change upstream?

**Comment by mcostalba** [comment]
This would be untested. IMO let's wait that someone with the hardware does
the test, eventually, if successful, you may want to open a new pull
request as a second and separate patch.

**Pull request closed without merging**
