### PR TITLE
change scope of some variables

### PR DESCRIPTION
**Pull request by hxim**
Change scope of some variables.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
This could be a speed regression. I did some tests in the past before to
put definitions where they are, at least for  the most performance critical

**Comment by hxim** [comment]
My speed measurements:

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1510808   1512758   -1950     
    StDev   3306      2098      4709      

p-value: 0,661

**Comment by zamar** [comment]
To be honest, I'm not a great fan of starting to change variable scope (without a good reason).

It's an endless road where people have different opinions, and it's not clear what's best for code readability. I'm not even certain what my current preference is...

**Comment by hxim** [comment]
@zamar 
I think local variables accessed only inside of some block are declared inside that block everywhere else. So it makes sense to be consistent also here.

**Comment by zamar** [comment]
@hxim: No this is not always the case. It's easy to find a counter example: nullValue in search().

This is an area where we just have to be sensible. There are cases when for readability both ways are fine (define variable in the beginning of the function or inside a local block).

If I committed this, I would open the door for dozens of similar requests. So let's not go for this...

**Comment by mstembera** [comment]
Just FYI, Stroustrup himself recommends limiting variable scope to its necessary minimum.
C++ 3rd edition section 6.3.2.1

https://books.google.com/books?id=CJw3BAAAQBAJ&pg=PA135&lpg=PA135&dq=variable+scope+bjarne&source=bl&ots=Jgik4NjakC&sig=AL-PloapC9FejsBnn3UY_NxTF74&hl=en&sa=X&ei=stO0VNnGG8PzoATk24CICw&ved=0CDsQ6AEwBA#v=onepage&q=variable%20scope%20bjarne&f=false

**Comment by mcostalba** [comment]
It is written "to avoid accidental misuse of a variable".

We don't accidentally misuse any variable, so that guideline does not apply.

What instead applies is that the general guidelines of use of a language
should be taken always with a grain of salt and while the brain is
connected: they are "general suggestion", not dogmas. They should always be
evaluated on a case by case basis that it is always more valuable than a
general scope rule.

A newbie mistake is to read those suggestions and start to strictly follow
them, quickly forgetting the root cause of the suggestion (or even not
understanding it at all) and then start coding "driven by mnemonics"
instead of by his judgment....this is a sad pattern I have seen many
times...

**Comment by hxim** [comment]
OK. I see most variables scope is limited to necessary minimum, but there are some exceptions.
So what is the reason for these exceptions. Is it performance or code readability or both or is it a case by case sometimes performance and sometimes readability?

**Comment by mcostalba** [comment]
As I said, on very tight loops, I measured a speed impact when bringing
variable definition in, but this probably depends a lot on the specific
compiler and the specific code.

**Comment by zamar** [comment]
I can already see where this discussion heading: Endless debates about best practices, arguing for specific variables which scope is right etc.

Going forward let's just use some common sense. If you are working on a specific area, you can adjust variable scope as part of your patch, but I won't approve a patch which just changes variable scope for a specific set of variables without a very good reason.

Case closed.

**Pull request closed without merging**
