### PR TITLE
Make MultiPV search stop properly with "go mate x" command.

### PR DESCRIPTION
**Pull request by joergoster**
Currently, search doesn't stop properly in MultiPV mode and 'go mate x' command.
Even when the mate in x is already found, the search simply continues.

The reason is that in a MultiPV search 'bestValue' at this point refers to the last PV line searched. But we must check against the 1st PV line!
This fixes https://github.com/official-stockfish/Stockfish/issues/2168.

After the recent bugfix when picking the best thread with the shortest mate,
we can now also do this in a MultiPV search when searching for a 'mate in x'.

No functional change. (except when searching for a 'mate in x')

### CODE REVIEW

**Comment by joergoster** [comment]
The sample position from https://github.com/official-stockfish/Stockfish/issues/2168 now stops correctly.

> info depth 42 seldepth 52 multipv 1 score mate 24 nodes 5818127 nps 1941964 hashfull 64 tbhits 0 time 2996 pv g4h5 h8g8 h5h6 d7d6 c6c5 d6d5 c5c4 d5d4 c3d4 d8d4 c4c5 d4d5 c5c6 d5d6 c6c7 d6d7 c7b8 d7b7 b8c8 b7b8 c8c7 b8b7 c7c6 b7b6 c6c5 b6b5 c5c4 b5b4 c4c3 d2d1n c3d2 b2b1n d2c1 b4c4 c1b1 c4b4 b1a2 d1c3 a2a3 b4a4 a3b3 a4a3 b3a3 c3b5 a3b2 h2h1q h6g7
> info depth 42 seldepth 19 multipv 2 score cp 0 nodes 5818127 nps 1941964 hashfull 64 tbhits 0 time 2996 pv g4h4 h8g8 h4h6 d7d6 c6c5 d6d5 c5c4 d5d4 c3d4 d8d4 c4c5 d4d5 c5c6 d5d6 c6c7 d6d7 c7c6
> info depth 42 seldepth 30 multipv 3 score cp -783 nodes 5818127 nps 1941964 hashfull 64 tbhits 0 time 2996 pv g4d7 d8d7 b7b8q h8h7 b8b4 d7d6 c6c7 d6e6 b4f8 h7g6 f8g8 g6f5 g8h7 f5f4 h7c2 h2h1q c2d2 f4f5 d2b2 h1h2 c7b7 f5g5 b2d2 g5g6 d2d3 g6f6 d3d8 f6g7 d8g5 e6g6
> bestmove g4h5 ponder h8g8

And a simpler position (MultiPV = 3):
4k3/8/8/8/8/8/8/3QK3 w - - 0 1 (Mate in 8)

> info depth 21 seldepth 18 multipv 1 score mate 8 nodes 172311 nps 2426915 tbhits 0 time 71 pv d1d6 e8f7 e1f2 f7e8 d6c7 e8f8 f2e3 f8e8 e3f4 e8f8 f4f5 f8g8 f5f6 g8h8 c7g7
> info depth 21 seldepth 18 multipv 2 score mate 9 nodes 172311 nps 2426915 tbhits 0 time 71 pv e1e2 e8e7 e2e3 e7f6 d1d6 f6g5 d6d7 g5g6 e3f3 g6h6 d7f7 h6g5 f7e6 g5h5 f3f4 h5h4 e6g4
> info depth 21 seldepth 18 multipv 3 score mate 9 nodes 172311 nps 2426915 tbhits 0 time 71 pv e1f2 e8e7 f2e3 e7f6 d1d6 f6g5 d6d7 g5g6 e3f3 g6h6 d7f7 h6g5 f7e6 g5h5 f3f4 h5h4 e6g4
> bestmove d1d6 ponder e8f7

**Comment by joergoster** [comment]
Please also note, that [this](https://github.com/official-stockfish/Stockfish/commit/d5f883ab29d43b35746ff605cf13c3722df56041) patch was already broken by the [voting](https://github.com/official-stockfish/Stockfish/commit/d96c1c32a2fa109e7cc6cd07f6029cd13977121e) patch, if I'm not mistaken. So it seems there is no further harm done by moving the check for Limits.mate down again.

**Comment by snicolet** [comment]
Leaving this open for the moment to let the discussion live...

**Comment by joergoster** [comment]
Are there any concerns about this patch? It looks like a simple fix to me.

**Comment by joergoster** [comment]
After some thinking I believe I can come up with an alternative patch which will still allow to stop if _any_ thread has found a mate in x. As soon as some testing is done I will open another PR and you can choose which one to commit.

**Comment by snicolet** [comment]
Is there any interaction between this and the recent chenge in master introduced in a8de07cc26999e2fef7298a63bfe349aaa4650fa ?

**Comment by joergoster** [comment]
@snicolet No. This patch only takes care that the search with multiple PV lines will stop after leaving the MultiPV loop if a mate in x (as specified in Limits.mate) is found. See also the explanations/remarks in the mentioned issue.

**Comment by joergoster** [comment]
And just to document that the current voting scheme doesn't guarantee that the thread with the shortest mate is picked.
_3 Threads, 1 GB Hash_

```
 +---+---+---+---+---+---+---+---+
 | r |   | b |   |   | r | k |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   | n |   | p | b |   |
 +---+---+---+---+---+---+---+---+
 |   |   | p |   | p |   | p |   |
 +---+---+---+---+---+---+---+---+
 | p |   |   |   |   |   | P |   |
 +---+---+---+---+---+---+---+---+
 | P | p |   |   | B |   | N | Q |
 +---+---+---+---+---+---+---+---+
 |   | q |   |   |   |   | P |   |
 +---+---+---+---+---+---+---+---+
 |   |   | R |   |   | P |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   | R |   |   | K |   |
 +---+---+---+---+---+---+---+---+

Fen: r1b2rk1/3n1pb1/2p1p1p1/p5P1/Pp2B1NQ/1q4P1/2R2P2/3R2K1 w - - 8 34
Key: 38B4CA1067D4F477
Checkers: 
ucinewgame
isready
readyok
go mate 17 searchmoves d1d7
```
...

> info depth 68 seldepth 36 multipv 1 score mate 18 nodes 742116164 nps 5146722 hashfull 1000 tbhits 0 time 144192 pv d1d7 c8d7 g4f6 g7f6 g5f6 b3a3 g1g2 a3a1 h4f4 a1f6 f4f6 e6e5 c2c1 d7h3 g2h3 a8a6 c1h1 c6c5 f6a6 g8g7 h3g2 f8e8 e4d5 e8e7 a6d6 e7e6 d5e6 g7f6 e6d5 f6f5 d5f7 g6g5 d6g6 f5g4 f2f3
> bestmove d1d7 ponder c8d7

Although the search stopped obviously because one thread has resolved the mate in 17, this thread has not been picked as best.

**Comment by joergoster** [comment]
@snicolet @mcostalba Just for your info, I won't open another PR on this.

**Comment by joergoster** [comment]
Branch and PR comment updated.

**Pull request closed without merging**
