### PR TITLE
More enhancements for the `eval` command

### PR DESCRIPTION
**Pull request by Sopel97**
- make everything be from white point of view
- include adjusted NNUE output
- show parts of the evaluation in each square
- improve readme

Example:
```
./stockfish
Stockfish 220621 by the Stockfish developers (see AUTHORS file)
position fen 3Qb1k1/1r2ppb1/pN1n2q1/Pp1Pp1Pr/4P2p/4BP2/4B1R1/1R5K b - - 11 40
eval
info string NNUE evaluation using nn-190f102a22c3.nnue enabled

 Contributing terms for the classical eval:
+------------+-------------+-------------+-------------+
|    Term    |    White    |    Black    |    Total    |
|            |   MG    EG  |   MG    EG  |   MG    EG  |
+------------+-------------+-------------+-------------+
|   Material |  ----  ---- |  ----  ---- | -0.73 -1.55 |
|  Imbalance |  ----  ---- |  ----  ---- | -0.21 -0.17 |
|      Pawns |  0.35 -0.00 |  0.19 -0.26 |  0.16  0.25 |
|    Knights |  0.04 -0.08 |  0.12 -0.01 | -0.08 -0.07 |
|    Bishops | -0.34 -0.87 | -0.17 -0.61 | -0.17 -0.26 |
|      Rooks |  0.12  0.00 |  0.08  0.00 |  0.04  0.00 |
|     Queens |  0.00  0.00 | -0.27 -0.07 |  0.27  0.07 |
|   Mobility |  0.84  1.76 |  0.01  0.66 |  0.83  1.10 |
|King safety | -0.99 -0.17 | -0.72 -0.10 | -0.27 -0.07 |
|    Threats |  0.27  0.27 |  0.73  0.86 | -0.46 -0.59 |
|     Passed |  0.00  0.00 |  0.79  0.82 | -0.79 -0.82 |
|      Space |  0.61  0.00 |  0.24  0.00 |  0.37  0.00 |
|   Winnable |  ----  ---- |  ----  ---- |  0.00 -0.03 |
+------------+-------------+-------------+-------------+
|      Total |  ----  ---- |  ----  ---- | -1.03 -2.14 |
+------------+-------------+-------------+-------------+

 NNUE derived piece values (white side) [order: material, positional, total]:
+-------+-------+-------+-------+-------+-------+-------+-------+
|       |       |       |   Q   |   b   |       |   k   |       |
|       |       |       | +11.1 | -3.59 |       |       |       |
|       |       |       | +0.37 | +1.92 |       |       |       |
|       |       |       | +11.5 | -1.66 |       |       |       |
+-------+-------+-------+-------+-------+-------+-------+-------+
|       |   r   |       |       |   p   |   p   |   b   |       |
|       | -4.71 |       |       | -0.83 | -0.95 | -3.67 |       |
|       | +1.62 |       |       | -0.16 | -0.21 | +0.80 |       |
|       | -3.09 |       |       | -1.00 | -1.17 | -2.87 |       |
+-------+-------+-------+-------+-------+-------+-------+-------+
|   p   |   N   |       |   n   |       |       |   q   |       |
| -0.72 | +3.29 |       | -3.45 |       |       | -11.4 |       |
| -1.10 | +0.03 |       | -0.70 |       |       | +8.57 |       |
| -1.82 | +3.32 |       | -4.15 |       |       | -2.92 |       |
+-------+-------+-------+-------+-------+-------+-------+-------+
|   P   |   p   |       |   P   |   p   |       |   P   |   r   |
| +0.55 | -0.84 |       | +0.57 | -0.85 |       | +0.60 | -4.77 |
| +0.54 | -0.15 |       | -0.22 | +1.11 |       | -0.36 | +1.67 |
| +1.10 | -1.00 |       | +0.35 | +0.25 |       | +0.23 | -3.09 |
+-------+-------+-------+-------+-------+-------+-------+-------+
|       |       |       |       |   P   |       |       |   p   |
|       |       |       |       | +0.59 |       |       | -0.78 |
|       |       |       |       | +1.61 |       |       | +1.93 |
|       |       |       |       | +2.20 |       |       | +1.14 |
+-------+-------+-------+-------+-------+-------+-------+-------+
|       |       |       |       |   B   |   P   |       |       |
|       |       |       |       | +3.36 | +0.53 |       |       |
|       |       |       |       | +0.54 | +0.99 |       |       |
|       |       |       |       | +3.90 | +1.52 |       |       |
+-------+-------+-------+-------+-------+-------+-------+-------+
|       |       |       |       |   B   |       |   R   |       |
|       |       |       |       | +3.34 |       | +4.60 |       |
|       |       |       |       | +0.60 |       | +0.42 |       |
|       |       |       |       | +3.94 |       | +5.02 |       |
+-------+-------+-------+-------+-------+-------+-------+-------+
|       |   R   |       |       |       |       |       |   K   |
|       | +4.48 |       |       |       |       |       |       |
|       | -0.70 |       |       |       |       |       |       |
|       | +3.77 |       |       |       |       |       |       |
+-------+-------+-------+-------+-------+-------+-------+-------+

 NNUE network contributions (white side)
+------------+------------+------------+------------+
|   Bucket   |  Material  | Positional |   Total    |
|            |   (PSQT)   |  (Layers)  |            |
+------------+------------+------------+------------+
|  0         |  -  0.68   |  +  0.59   |  -  0.09   |
|  1         |  -  0.18   |  +  1.56   |  +  1.37   |
|  2         |  -  0.47   |  +  1.75   |  +  1.28   |
|  3         |  -  0.56   |  +  1.96   |  +  1.39   |
|  4         |  -  0.46   |  +  1.85   |  +  1.38   |
|  5         |  -  0.36   |  +  2.11   |  +  1.75   |
|  6         |  -  0.50   |  +  2.05   |  +  1.55   | <-- this bucket is used
|  7         |  -  1.87   |  +  1.77   |  -  0.09   |
+------------+------------+------------+------------+


Classical evaluation       -1.00 (white side)
NNUE evaluation            +1.55 (white side)
NNUE evaluation (adjusted) +1.69 (white side)
Final evaluation           +2.53 (white side) [with scaled NNUE, hybrid, ...]
```

### CODE REVIEW

**Comment by snicolet** [comment]
It seems redundant to have the triplets (material, positional, total) in each box: keeping just (material, position) would make the boxes lighter and easier to read, in my opinion.

**Comment by Sopel97** [comment]
While I agree that it would slightly less crowded, I added the total so that less mental arithmetic is required. I'm happy to make the change if more people think the same as you.

**Comment by vondele** [comment]
as a third option, just the total would work as well ... ?

**Comment by Sopel97** [comment]
Just the total is the current behaviour, but I like the separated output. For example on the sample output one can see the black queen having a positional factor very positive for white, I think it's interesting information to have.

**Comment by ddobbelaere** [comment]
_Sorry for the possible digression here..._

Interesting! As a chess player, some of the individual terms are hard to understand though...
I wonder if this an artefact about how the piece values are inferred. Contrary to classical eval, NNUE is non-linear, hence the sum of all inferred total piece values is not equal to the total NNUE evaluation.

I wonder if the following would make sense: take the derivative of all terms (material/positional) w.r.t. the piece value (viewed as a real number instead of binary 0/1) and "normalize" the gradient (i.e., make sure that the sum of its terms equals the total NNUE evaluation). Probably just a useless theoretical consideration in this context, as this would involve a significant change of the codebase just to have this feature (if it indeed does make "more" sense).

**Comment by Sopel97** [comment]
I could see it being problematic for evals of 0 or very close to 0

**Comment by vondele** [comment]
I'll close this PR. I don't think we want to extend the eval command more.

**Pull request closed without merging**
