### PR TITLE
Remove Redundant IFs:  Bench- 6258930

### PR DESCRIPTION
**Pull request by VoyagerOne**
Remove Redundant IF Statements
Bench:  6258930
Non-functional Change

### CODE REVIEW

**Comment by mcostalba** [comment]
Please set on 2 lines, like this:

```c++
        // Can ttValue be used as a better position evaluation?
        if (   ttValue != VALUE_NONE
            && (tte->bound() & (ttValue > eval ? BOUND_LOWER : BOUND_UPPER)))
            eval = ttValue;

```


and

```c++
            // Can ttValue be used as a better position evaluation?
            if (   ttValue != VALUE_NONE
                && (tte->bound() & (ttValue > bestValue ? BOUND_LOWER : BOUND_UPPER)))
                bestValue = ttValue;

```

**Comment by mcostalba** [comment]
Moreover you need parenthesis between && and & due to[ operator precedence](http://en.cppreference.com/w/c/language/operator_precedence)

**Comment by VoyagerOne** [comment]
@mcostalba 
Thanks!  Made the changes...

**Comment by zamar** [comment]
@VoyagerOne: Please make sure that the travis check passes...

**Pull request closed without merging**
