### PR TITLE
Update Elo estimates for terms in search.

### PR DESCRIPTION
**Pull request by FauziAkram**
This updates estimates from 1yr ago https://github.com/official-stockfish/Stockfish/pull/3868, and later on I will do some addition tests to update also the missing terms.
All tests run at 10+0.1 (STC), 25000 games.
Book used: UHO_XXL_+0.90_+1.19.epd

Values are rounded to the nearest non-negative integer.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

1st Link | Elo Estimation | Link of Simplification test | Elo 2 (Based on the simplification   test, which is more than 25k games) | Link of LTC | Elo3 (LTC)
-- | -- | -- | -- | -- | --
https://tests.stockfishchess.org/tests/view/639f41d562ce83166fd27c39 | 2 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f41e362ce83166fd27c3e | 2 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f41e862ce83166fd27c41 | 0 | https://tests.stockfishchess.org/tests/view/639f6aed62ce83166fd282ff | 0 | https://tests.stockfishchess.org/tests/view/639fab4862ce83166fd28df3 | 2
https://tests.stockfishchess.org/tests/view/639f430662ce83166fd27c6b | 0 | https://tests.stockfishchess.org/tests/view/639f751862ce83166fd284a9 | 1 |   |  
https://tests.stockfishchess.org/tests/view/639f438062ce83166fd27c7f | 7 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f447562ce83166fd27ca0 | 4 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f44e062ce83166fd27cb8 | 1 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f457062ce83166fd27ccf | 40 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f460062ce83166fd27ce4 | 35 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f46ad62ce83166fd27cfd | 10 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f5f2862ce83166fd280f7 | 9 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f5fde62ce83166fd28114 | 4 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f606b62ce83166fd2812e | 120 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f611d62ce83166fd28145 | 8 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f61a262ce83166fd28160 | 2 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f621e62ce83166fd2817a | 11 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f62a762ce83166fd28193 | 0 | https://tests.stockfishchess.org/tests/view/639faacc62ce83166fd28ddc | 2 |   |  
https://tests.stockfishchess.org/tests/view/639f634a62ce83166fd281aa | 13 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f63b762ce83166fd281c4 | 4 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f72b462ce83166fd2843e | 100 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f734862ce83166fd28455 | 94 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f73db62ce83166fd2846e | 0 | https://tests.stockfishchess.org/tests/view/639fa8fd62ce83166fd28d87
https://tests.stockfishchess.org/tests/view/639f747362ce83166fd28489 | 0 | https://tests.stockfishchess.org/tests/view/639dfaee11c576d919dc2d69 | 1 |   |  
https://tests.stockfishchess.org/tests/view/639f755862ce83166fd284b8 | 117 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f75bc62ce83166fd284c4 | 13 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f762f62ce83166fd284da | 10 |   |   |   |  
https://tests.stockfishchess.org/tests/view/639f76da62ce83166fd284ff | 3 |   |   |   |  

</body>

</html>

### CODE REVIEW

**Comment by dubslow** [comment]
I'm curious to know the value of the verification part of the null move pruning, what is it worth without the verification?

**Comment by vdbergh** [comment]
> I'm curious to know the value of the verification part of the null move pruning, what is it worth without the verification?

It is not worth anything. But if you omit it then the engine is no longer capable of handling zugzwang.

**Comment by Vizvezdenec** [comment]
> > I'm curious to know the value of the verification part of the null move pruning, what is it worth without the verification?
> 
> It is not worth anything. But if you omit it then the engine is no longer capable of handling zugzwang.

well, it can solve _some_ zugzwangs, but number is much much lower than with verification search.
This is one of few parts of code where patches were accepted with simplification bounds and better results on zugzwang test suites.

**Comment by vondele** [comment]
Just a note, compared to the earlier tests, these test are done with a different book, so some change in numbers is mostly due to the book change. However, it might make sense to start documenting these numbers with UHO books, as 8moves becomes increasingly insensitive to engine improvements and changes.

**Comment by Vizvezdenec** [comment]
I think we need to list elo in UHO book.
Usual drawish book isn't smth that we use for simplifications anyway and with UHO elo difference is pretty clean in what is worth a lot and what is worth not that much.

**Comment by FauziAkram** [comment]
Indeed all the tests was done using the book: UHO_XXL_+0.90_+1.19.epd

I added the note in the draft of the PR itself.

**Pull request closed without merging**
