### PR TITLE
Generalize transform2

### PR DESCRIPTION
**Pull request by Chaneybenjamini**

### CODE REVIEW

**Comment by vondele** [comment]
@Fanael can you have a look if this patch works for you as a replacement of https://github.com/official-stockfish/Stockfish/pull/3928 ?

**Comment by Fanael** [comment]
:+1:

**Comment by vondele** [comment]
looks good to me. @Chaneybenjamini can you please add an entry to the `AUTHORS` file, I'll merge afterwards.

**Comment by Chaneybenjamini** [comment]
I added myself. Thank you for your help with this PR.

**Pull request closed without merging**
