### PR TITLE
Endgame malus for having a king in a pawnless flank

### PR DESCRIPTION
**Pull request by snicolet**
Original idea by "ElbertoOne", while "FauziAkram" suggested to put a small midgame penalty too.

STC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 71808 W: 13038 L: 12610 D: 46160

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 150874 W: 19828 L: 19221 D: 111825

Bench: 5745112

### CODE REVIEW

**Comment by stockfishdeveloper** [comment]
Congrats!
Have the PawnlessFlank variables been tuned?

**Comment by FauziAkram** [comment]
Congratulations and thanks for the credits :)

**Comment by mcostalba** [comment]
Merged with 818b4a126d1

**Comment by DamasClasicas** [comment]
Congratulations!!

**Pull request closed without merging**
