### PR TITLE
[NNUE] Add std_aligned_alloc() for Android

### PR DESCRIPTION
**Pull request by mstembera**
Fix by @AlexB123
See https://github.com/official-stockfish/Stockfish/issues/2860
bench: 4578298

### CODE REVIEW

**Comment by vondele** [comment]
@mstembera this doesn't look right as we have a recursive function call now. Maybe `std_aligned_alloc` is a bad choice for our function if it pre-exists on android? With a very quick search I couldn't find any info about this on Android, maybe we need some more feedback from somebody testing this branch?

**Comment by mstembera** [comment]
@vondele Nice catch.  I didn't even notice the duplicate name.  Yes feedback from an android developer would be good.  From the original issue it does look like we chose a name android already uses.  I'm also trying to confirm if it's an Android thing or an ARM thing from @AlexB123.

**Comment by vondele** [comment]
if must be an OS issues, not a processor issue. However, if I understand the issue, that wasn't encountered or our nnue-player-wip branch.

**Comment by WOnder93** [comment]
I don't think the compiler error from https://github.com/official-stockfish/Stockfish/issues/2860#issuecomment-666578648 really implies that there is a function in Android header with the same name. Probably the compiler simply saw `std::aligned_alloc` and tried to find a function in scope with a similar name, which happened to be the SF's `std_aligned_alloc`.

**Comment by AlexB123** [comment]
Hello! I managed to make the engine without errors using this lines https://github.com/mstembera/Stockfish/commit/af6473aa5bc5f7adbc912658aa8c3671ce9ad967

Unfortunately when i mark the "Use NNUE" box, engine crashes instantly, with path to nn.nnue network and without network.
I'm not sure but this issue may have to do with Network loading, or -std=c++17 (instead of -std=c++11).
You can see for yourself.
[SF-310720-armv8.zip](https://github.com/official-stockfish/Stockfish/files/5007479/SF-310720-armv8.zip)

**Comment by vondele** [comment]
with those lines of the patch, the engine will build but indeed just crash (i.e. enter an infinite recursive loop) once that call is executed (which should happen on ticking the 'Use NNUE' box). So, what is need is figuring out how android supports the c++17 function std::aligned_alloc()... since you have android access, ideally you can help us with that.

**Comment by AlexB123** [comment]
> 
> 
> with those lines of the patch, the engine will build but indeed just crash (i.e. enter an infinite recursive loop) once that call is executed (which should happen on ticking the 'Use NNUE' box). So, what is need is figuring out how android supports the c++17 function std::aligned_alloc()... since you have android access, ideally you can help us with that.
I would be very glad to help you guys, unfortunately i'm not a programmer, and my knowledge regarding android engines is limited. :(
Also, I don't have a lot of free time, so I never tried to do it seriously. Only an expert who knows very well how the NDK's Clang works can help you.

**Comment by vondele** [comment]
I'll close this PR as this is not the right solution. We'll keep the issue open.

**Pull request closed without merging**
