### PR TITLE
Assorted trivial cleanups 6/2019

### PR DESCRIPTION
**Pull request by mcostalba**
No functional change.

### CODE REVIEW

**Comment by Rocky640** [comment]
cannot safely advance to the next row => 
cannot safely advance

constexpr Score WeakUnopposed = S( 13, 27); 
remove an extra space => S(13, 27);

**Comment by Rocky640** [comment]
outposts: we can avoid score division at line 310, since it is slower than multiplication.
this is non functional change

so use
`constexpr Score Outpost = S( 18,  6);`

and line 306-310

```
            if (bb & s)
                score += Outpost * (Pt == KNIGHT ? 4 : 2);

            else if (bb & b & ~pos.pieces(Us))
                score += Outpost * (Pt == KNIGHT ? 2 : 1);
```

**Comment by ddugovic** [comment]
`search.cpp` twice implements the same `!(pos.blockers_for_king(~us) & from_sq(move))` whereas for readability I would prefer `inline bool Position::gives_discovered_check(Move m) const` within `position.h`.

**Comment by Rocky640** [comment]
in pawns.cpp, 
`backward =  !(ourPawns & pawn_attack_span(Them, s))`
can be further improved with
`backward =  !(neighbours & forward_ranks_bb(Them, s))`

because under the hood, it would save a call to adjacent_files_bb

**Comment by mcostalba** [comment]
Thanks updated. I have introduced the is_discovery_check_blocker() helper, not using gives_discovered_check() name because it is not what it does: it just checks if the moved piece is a blocker, not necessarily giving discovery check, for instance it could be a KING that moves along the diagonal of the attacking piece, so still covering the opponent KING.

**Comment by Rocky640** [comment]
In evaluate.cpp, a spcae is missing before the colon
`constexpr Bitboard LowRanks = (Us == WHITE ? Rank2BB | Rank3BB: Rank7BB | Rank6BB)`

**Comment by mstembera** [comment]
Lines 5695 and  1283 in search.cpp
``` C++
// Never assume anything on values stored in TT
```
should probably be
```C++
// Never assume anything about values stored in TT
```

**Comment by Rocky640** [comment]
In evaluate.cpp, 
`b = pawn_attacks_bb<Us>(b) & pos.pieces(Them);`
can be replaced with
`b = pawn_attacks_bb<Us>(b) & nonPawnEnemies;`

(because b does not contains squares attacked by their pawns, see 2 lines above)

**Comment by mstembera** [comment]
Fix min_attacker() type from int to PieceType.
https://github.com/mstembera/Stockfish/commit/1d648ed04d4e18fee2ad9958d3d0ca05196aff0c

**Comment by xoto10** [comment]
The comment `// Move count based pruning (~30 Elo)` at line 960 in search.cpp is now very inaccurate, see  [stc](http://tests.stockfishchess.org/tests/view/5d1210b90ebc5925cf0b0942) and [ltc](http://tests.stockfishchess.org/tests/view/5d122d370ebc5925cf0b0b4a) and related discussion.
It should be removed or the number changed to something like `(~3 Elo)`. (Actual figure appears to be quite tc sensitive, may be more valuable at longer tc.)

**Comment by mcostalba** [comment]
Thanks. Updated.

**Comment by protonspring** [comment]
+++ b/src/search.cpp
@@ -360,8 +360,7 @@ void Thread::search() {

   // Evaluation score is from the white point of view
\-  contempt = (us == WHITE ?  make_score(ct, ct / 2)
\-                          : -make_score(ct, ct / 2));
\+  contempt = make_score(ct, ct / 2) * (us == WHITE ? 1 : -1);

**Comment by snicolet** [comment]
Merged via 4ae5a7b45a430aea5f4b21f9455b4db74ed1c44a, thanks!

**Pull request closed without merging**
