### PR TITLE
use std::sort()

### PR DESCRIPTION
**Pull request by lucasart**
No functional change.

### CODE REVIEW

**Comment by lucasart** [comment]
@mcostalba: Yes, I know, you could replace the last two `std::swap` with `std::max_element()` and `std::sort()` using lambdas. But I'm not convinced it would be more readable. So prefer the humble solution for now.

**Comment by VoyagerOne** [comment]
FYI:  std::sort() is not stable

**Comment by jhellis3** [comment]
If performance isn't really an issue here, just use std::stable_sort...

**Comment by lucasart** [comment]
@VoyagerOne: do you think stability is required here ? If so, can you please expose the bug, and open a pull request ?

**Comment by KassiasGrandiel** [comment]
Is the code that this replaces a stable sort? If so we need to use std::stable_sort

**Comment by mcostalba** [comment]
The problem with sort is that implementation is compiler dependent, but I
have still not looked at that part of code so I don't know if final item
order is important.

**Pull request merged**
