### PR TITLE
Determine Opposite Colors Mathematically

### PR DESCRIPTION
**Pull request by protonspring**
This is a non-functional speed-up.  Master has to access SquareBB twice while this patch determines opposite_colors just using the values of the squares. It doesn't seem to change the overall speed of bench, but calling opposite_colors(...) 10Million times:

master: 39.4 seconds
patch: 11.4 seconds.

The only data point I have (other than my own tests), is a quite old failed STC test:
LLR: -2.93 (-2.94,2.94) [-1.50,4.50]
Total: 24308 W: 5331 L: 5330 D: 13647
Ptnml(0-2): 315, 2577, 6326, 2623, 289 
http://tests.stockfishchess.org/tests/view/5e010256c13ac2425c4a9a67

### CODE REVIEW

**Comment by protonspring** [comment]
It would be more code, this would be much clearer with a square_color() method.  Then opposite_colors would just check it square_color(s1) != square_color(s2);

**Comment by protonspring** [comment]
This could also be added now that we have a method that quickly determines square color:

http://tests.stockfishchess.org/tests/view/5e28b69ec3b97aa0d75bc2aa

**Comment by snicolet** [comment]
Merged via f3c83ed46cdc2062c30551f457ac53ad635794ea, thanks!

**Comment by silversolver1** [comment]
@protonspring Sorry to necro an older patch, but I was looking at the current KXK endgame and I came across these lines:
`|| (   (pos.pieces(strongSide, BISHOP) & ~DarkSquares)`
`&& (pos.pieces(strongSide, BISHOP) &  DarkSquares)))`
Do you think this would be somewhere worth using opposite_colors instead?

**Comment by protonspring** [comment]
I don't think so.  If you did opposite_colors you would first have to check
if there were in fact two bishops first, then do opposite_colors on
pos.square<BISHOP>(strongSide)[0], etc.  That doesn't seem as clean as what
is there.

**Comment by silversolver1** [comment]
@protonspring Cool that makes sense, I forgot that we would have to first check for the existence of both bishops before we could call opposite_colors. Thanks.

**Pull request closed without merging**
