### PR TITLE
Don't filter root moves if MultiPV mode is enabled.

### PR DESCRIPTION
**Pull request by gcp**
Fixes issue #1275.

### CODE REVIEW

**Comment by joergoster** [comment]
If it only were that easy. See https://github.com/official-stockfish/Stockfish/pull/1252

**Comment by ceebo** [comment]
I tried your patch on position 8/8/6k1/7q/3N4/8/1BK5/8 b - - 0 1 with MultiPV = 2. The only winning move is Qh1 but it appeared in the output only a handful of times up to depth 32.

**Comment by gcp** [comment]
>If it only were that easy. See #1252

Right now the output is completely broken and and there won't be any multipv output at all, making Stockfish strongly non-compliant. 

The fact that in some positions it can no longer find the best moves when EGTB is disabled is secondary. Right now it can't even deal with the most trivial ones.

**Comment by gcp** [comment]
>I tried your patch on position 8/8/6k1/7q/3N4/8/1BK5/8 b - - 0 1 with MultiPV = 2. The only winning move is Qh1 but it appeared in the output only a handful of times up to depth 32.

If you run current master Stockfish on that position, it claims there is only 1 legal move. If you ask for the second best move, it just breaks and fails to output the 2nd line.

With this patch, it will understand how many legal moves there are (24), won't break and output the variations the user asks for, but it won't necessarily generate the best move (this happens in a lot of positions, not only in those that are in EGTB).

Why on earth is the first scenario preferable, or even acceptable?

**Comment by ceebo** [comment]
> Why on earth is the first scenario preferable, or even acceptable?

The MultiPV behaviour of current master is not acceptable.

In my opinion the MultiPV behaviour of PR #1252 is acceptable and preferable to the behaviour here.

**Comment by gcp** [comment]
>The MultiPV behaviour of current master is not acceptable.

For that, we are in agreement.

>In my opinion the MultiPV behaviour of PR #1252 is acceptable and preferable to the behaviour here.

Unfortunately, it is a rather big patch and has been pending for over a month (I know that is not your fault).

Maybe the maintainers are willing to unbreak the engine with a 1-liner until they figure out what they want to do.

**Comment by mcostalba** [comment]
This is just a band-aid, the issue should be fixed properly in other ways. PR #1252 adds even more kludge above an already complex TB implementation and it is very invasive and design is questionable (overriding search tree results while still in the middle of the search it means to introduce a discontinuity between sub-tree TT values and parents nodes TT values, this is far from elegant and clean approach).  PR #1257 at the moment has fixed all the reported issues and is much more simpler both as design and as implementation but unfortunately I am the author of PR #1257 and being also the maintainer that stops me from pushing it harder, so I wait the dust will settle down and then I will reopen a new round of discussions on TB.

For the moment it is ok to commit this band-aid.

**Comment by mcostalba** [comment]
Merged with 86ac50403d58ce

**Pull request closed without merging**
