### PR TITLE
Update default net to nn-7b23f384897e.nnue (for snicolet only)

### PR DESCRIPTION
**Pull request by SFisGOD**
About 5 Elo gained for SALC positions and passed non-regression using default book.

STC:
LLR: 2.94 (-2.94,2.94) {-0.25,1.25}
Total: 14768 W: 3089 L: 2826 D: 8853
Ptnml(0-2): 211, 1611, 3510, 1808, 244
https://tests.stockfishchess.org/tests/view/5fbb9b2c67cbf42301d6b15e

LTC:
LLR: 2.95 (-2.94,2.94) {0.25,1.25}
Total: 17432 W: 2463 L: 2197 D: 12772
Ptnml(0-2): 73, 1497, 5328, 1727, 91
https://tests.stockfishchess.org/tests/view/5fbbcd7267cbf42301d6b175

Non-regression LTC using default book
LLR: 2.98 (-2.94,2.94) {-0.75,0.25}
Total: 199736 W: 8431 L: 8491 D: 182814
Ptnml(0-2): 137, 7549, 84562, 7477, 143
https://tests.stockfishchess.org/tests/view/5fbc13f767cbf42301d6b1b5

Bench: 4087476

### CODE REVIEW

**Comment by SFisGOD** [comment]
@snicolet This patch is the non-invasive version but I would like to ask if you are more open to using multiple nets? This one is a hack version for just using the output layer and sharing the rest of the net https://tests.stockfishchess.org/tests/view/5fbc955d67cbf42301d6b1eb

For endgames, I tried this one but it fails so bad using default book https://github.com/SFisGOD/Stockfish/compare/027626db1e...2a29cca605
https://tests.stockfishchess.org/tests/view/5fbe8ed267cbf42301d6b2ca

While if you use the net for endgames only, it passed 3 LTCs now. This one is the latest.
https://tests.stockfishchess.org/tests/view/5fbe14ae67cbf42301d6b296

What is your opinion on this? Thank you.

**Comment by MichaelB7** [comment]
My $02, , the fact that you ended with this statement, leads me to believe that your gut is telling you this correct.  I believe your gut  is correct.
**"Maybe I should just collect the best nets for different class of positions and post it on a wiki or maybe a Stockfish issue will suffice, so people will have a choice depending on their needs."**

**Comment by snicolet** [comment]
I'll completely agree with Joost's opinion on the subject, whatever his advice are.

**Comment by SFisGOD** [comment]
Thanks snicolet.

**Comment by snicolet** [comment]
Maybe indeed starting a page in the wiki, or re-using one of the pages that is seldom used at the moment (for instance https://github.com/glinscott/fishtest/wiki/Hot-research-topics , we can even change the title of course) would be a good idea and help the community forward, in a non-intrusive way. Of course we would then have to write clear instructions for how to change the UCI options to choose the various eval files.

Thanks for the various tests and all the hard work you put in it :-)

**Pull request closed without merging**
