### PR TITLE
Solving the GHI Problem.

### PR DESCRIPTION
**Pull request by Hanamuke**
As of now, the Transposition Table doesn't care about the history of the positions, which is a problem because it matters for draw detection, be it repetition or 50 moves rule. See https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/C8KmIEJ8B8Y for the discussion.

It causes master to find a draw in this position for instance, whereas my patched version is aware that there is in fact no repetition: 
FEN: 3r2k1/pr6/1p3q1p/5R2/3P3p/8/5RP1/3Q2K1 b - - 0 51

I simply add rule50 to the key before fecthing and storing entries in the hash table.
Pros : TT is now rule50 aware, ghi seems to be solved
Con : Some positions that were transpositions before are now stored at a different address, TT filling rate increases, and TT hitrate decreases (very slightly).

Credit to Stefan for the original idea of solving the GHI problem by tempering with hash keys.

STC : http://tests.stockfishchess.org/tests/view/5b8928710ebc592cf2747cef
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 79641 W: 16844 L: 16834 D: 45963 

LTC : http://tests.stockfishchess.org/tests/view/5b8a5acb0ebc592cf27499bb 
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 23167 W: 3789 L: 3672 D: 15706 

Continuations :
-As of now, my patched passed non regression despite having FORGOT TO FIX THE PREFETCH, which is now completely useless (I plan to fix this)

-Since TT is now rule50 aware, including rule50 into the evaluation will be more efficient than before, maybe some foretress detection techniques would now work better.

Bench : 4481548

### CODE REVIEW

**Comment by Hanamuke** [comment]
Btw, i expect either fixing to pass [0;5], or prefetch removal to pass [-3;1] should fixing fail

**Comment by syzygy1** [comment]
I'm sure the GHI problem has no measurable Elo cost, so I'm equally sure this patch is a regression. I would be very hesitant to commit it if all we know is that an STC/LTC simplification test (surprisingly) failed to detect the regression.

**Comment by syzygy1** [comment]
Also, it only partially solves the problem. The set of future possible paths avoiding a repetition depends on the full history of the position and not just on the value of the 50-move counter.

**Comment by CoffeeOne** [comment]
According to the LTC test, it looks more like a Elo gain, not a regression. But of course the test could be a fluke.
@Hanamuke Maybe put the fixed version to a 40000 games LTC test, to have some statistics about gaining / losing Elo?
There are not very much tests running at the moment, so I think this should be ok.

**Comment by syzygy1** [comment]
Maybe I am too pessimistic. The GHI problem obviously hurts sometimes, for example by hiding 50-move draws, but it is not really possible to compare with an engine "without GHI problem" as the GHI problem simply comes with the detection of transpositions.

Hashing in the 50-move counter probably hurts most in the endgame, but that is also where it might help. And perhaps @Hanamuke is right that not having transpositions between positions with different 50-move counter can gain Elo by taking into account the 50-move counter in the evaluation.

An example where the patch will hurt is KBNvK. Normally the mate in 30 moves (say) is found much earlier than at depth 59, but this patch will prevent that. Also a position like Fine #70 will be solved not before depth 25 to 26 or so.

So I really don't think this change should be committed if it only passes as a simplification, because it is not a simplification.

**Comment by syzygy1** [comment]
OK, the reason why this does not hurt is that it (almost) does not do anything. The 50-move counter is hashed into the low bits of the hash key, which are ignored when probing the TT code. This is why the excludedMove is first shifted by 16 bits. Only because the value is hashed in with "+" instead of "^" does the bench change.

**Comment by Hanamuke** [comment]
@syzygy1 it says in tt.h
`// The 32 lowest order bits of the key are used to get the index of the cluster`
The high order bits are used as key inside the clusters

I used [-3;1] because i consider this a bugfix, but i receive the argument. My position it's worth trading <1 Elo for more robustness, that's not for me to decide of course. Fixed game elo test is probably a good idea anyway.

**Comment by syzygy1** [comment]
@Hanamuke 
The full quote is:
https://github.com/official-stockfish/Stockfish/blob/2bfaf454551ae5a9d99d271d0d87d2a6c829c7e4/src/tt.h#L85-L88
Unless clusterCount is really big, the right shift will kill the low bits of key. In particular if clusterCount is a power of 2 (the normal case). If it is not a power of 2, the effect will still be practically negligible.

Try replacing "+" in your patch with "^" and see what happens.

**Comment by Hanamuke** [comment]
Yes you are right

**Comment by syzygy1** [comment]
I think it is generally better to XOR them in than to add them. Since XOR is associative, this gives the compiler more freedom to rearrange things. (And adding is probably more sensitive to linear dependencies than xor'ing.)

Adding/XORing them into the same bits as excludedMove is probably not the best idea either, as it would probably create some simple collisions.

I expect the patch to fail quickly once the 50-move counter is hashed in correctly. Of course it is worth a try.

**Comment by Hanamuke** [comment]
@syzygy1 it's not even worth a try, hash performance degradation is colossal, took me 4 times the nodes to reach depth 30. It was lucky that this patch solved the position above because upon retesting, it doesn't solve it anymore with new master. Changing higher bits does solve it but the performance is too bad. Unless i get a great idea, that's all for now.

**Comment by snicolet** [comment]
@syzygy1 
Good catch!

**Comment by MichaelB7** [comment]
I can confirm this patch gains Elo.  I suspect it might just be saying “no draw code is better than the draw code we have”.    Perhaps we should try to simplify away all draw code and then methodically add it back in.  I would suggest adding the 50 move rule  first as it appears that it is the 3x position repetition is the problem child.

**Comment by Hanamuke** [comment]
@MichaelB7 It didn't seem to gain elo at STC. If we can understand in what conditions the patch is good maybe something can be done (TC, hash size [power of two or not also]). LTC test does suggest an elo gain but as ronald mentionned it will probably be bad with bigger hash sizes, where the impact will be bigger, so it can't be merged like this (and not without [0;5] anyway)

**Comment by Stefano80** [comment]
(0,4) VLTC is very expensive

**Comment by NKONSTANTAKIS** [comment]
Maybe just 5k fixed games or such with very big hash then?

**Comment by Hanamuke** [comment]
I'm busy with an esport tourney right now but later i'll try to implement something that uses the TT padding to store draw information instead of having multiple entries, as AGE suggested.

**Comment by syzygy1** [comment]
The original patch provably does nothing for small TT, so any perceived advantages is just imagination.

It has also been established beyond doubt that if the hash is so big that the patch actually has an effect (because the bits it fiddles with are not just thrown away), it hurts performance in an awful way.

So all "I feel that this works" is based on nothing.

**Pull request closed without merging**
