### PR TITLE
Update types.h

### PR DESCRIPTION
**Pull request by saproj**
Make enum Score an int instead of enum. The overloaded division operator for Score is not used. Other operators work the same way they work for int.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Care to explain why this?

**Comment by saproj** [comment]
This change leads to shorter and simpler code. And functionality is not affected.

**Comment by mcostalba** [comment]
Is not shorter, is not simpler...but instead is broken.

Care to explain why you removed the disabling of multiply overload and the special division overload?

**Comment by saproj** [comment]
> Is not shorter

13 removed lines: "+16 −29".

>, is not simpler...

Less operator overloading stuff. Built-in type.

> but instead is broken.

Really?

> Care to explain why you removed the disabling of multiply overload and the special division overload?

Division is not used, multiplication disabling's only purpose is protection from writing wrong code. I added a comment advising against dividing or multiplying Score.

Slightly better bench results under Windows 10 64-bit, gcc 6.2, 30 runs:
> base =    1709215  +/- 4393
> test =    1713276  +/- 4950
> diff =      +4061  +/- 3881
> 
> speedup        = +0.0024
> P(speedup > 0) =  0.9797

**Comment by mcostalba** [comment]
@saproj  You wrote a comment as protection against multiplication overflow? You don't care about division protection because _now_ is not used?

I am sorry, I just see that your patch weakens type safety in a way that leads to subtle and difficult to detect bugs. Moreover it introduces an inconsistency compared to the other similar types that are all defined as enums. This difference is totally artificial and not needed in any way, it is just a gratuitous departure from the usual conventions. So I am closing it.

**Pull request closed without merging**
