### PR TITLE
Doubled pawn simplification

### PR DESCRIPTION
**Pull request by snicolet**
Doubled pawn simplification

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 36094 W: 6558 L: 6463 D: 23073

LTC:
LLR: 2.94 (-2.94,2.94) [-3.00,1.00]
Total: 102352 W: 13417 L: 13404 D: 75531

Bench: 8716243

### CODE REVIEW

**Comment by joergoster** [comment]
Congrats!

**Comment by Rocky640** [comment]
Well done !

**Comment by DamasClasicas** [comment]
Congratulations! Well done!!

**Comment by mcostalba** [comment]
Merged with 16c603ce9baa4

**Pull request closed without merging**
