### PR TITLE
Adjust lazy thresholds 15% higher

### PR DESCRIPTION
**Pull request by mstembera**
STC https://tests.stockfishchess.org/tests/view/63f2f5a3e74a12625bccc22d
LLR: 2.94 (-2.94,2.94) <0.00,2.00>
Total: 25256 W: 6840 L: 6552 D: 11864
Ptnml(0-2): 62, 2684, 6856, 2956, 70 

LTC https://tests.stockfishchess.org/tests/view/63f31bc2e74a12625bccc7e7
LLR: 2.94 (-2.94,2.94) <0.50,2.50>
Total: 107432 W: 28719 L: 28284 D: 50429
Ptnml(0-2): 43, 10290, 32630, 10695, 58 

bench: 4229532

### CODE REVIEW

**Comment by mstembera** [comment]
Perhaps these lazy thresholds should be tuned together with the 1781 constant on https://github.com/official-stockfish/Stockfish/blob/037ef3e18dc7f5455cc671995ae38d5b4d1fce4a/src/evaluate.cpp#L1059 since they together select which eval gets chosen.

**Comment by peregrineshahin** [comment]
It was pointed out at discord that the branch used in the test against master does not have the bug fix https://github.com/official-stockfish/Stockfish/commit/2c36d1e7e7374b8babb3cc503c0bc07ceb83dbf8
leaving those results corrupt because the fix loses elo?

**Comment by peregrineshahin** [comment]
I'm not sure what do you mean
testing with a previous version without the bug fix means that your results are corrupt since if you had a non-gaining elo patch but the speedup before the bugfix then any test surely will pass if it does not regress respectively.

Also it is very suspicious that changing classical eval param would gain us elo at this point..

**Comment by dubslow** [comment]
Well, it's easy enough to test this again. I wish the bugfix LTC regression test went longer, because its elo is right on the edge of the error bar, quite unfortunate

**Comment by mstembera** [comment]
I have submitted https://tests.stockfishchess.org/tests/view/63f51a06e74a12625bcd18cc

**Comment by mstembera** [comment]
Closing since retest failed.

**Pull request closed without merging**
