### PR TITLE
Combo

### PR DESCRIPTION
**Pull request by SFisGOD**
This combo consists of the following tweaks:
1. dynamic contempt - SFisGOD (http://tests.stockfishchess.org/tests/view/5c7002b70ebc5925cffce99c)
2. time reduction - vondele (http://tests.stockfishchess.org/tests/view/5c7012460ebc5925cffceb4d)
3. multi-cut pruning  - joergoster (http://tests.stockfishchess.org/tests/view/5c6fcc1f0ebc5925cffce3f0)
4. contempt value - gvreuls and xoto (http://tests.stockfishchess.org/tests/view/5c7942560ebc5925cffd9285)

STC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 70956 W: 15853 L: 15408 D: 39695
http://tests.stockfishchess.org/tests/view/5c79a6750ebc5925cffd9ebb

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,3.50]
Total: 111858 W: 18889 L: 18400 D: 74569
http://tests.stockfishchess.org/tests/view/5c79b3590ebc5925cffda0b2

Bench: 3516334

### CODE REVIEW

**Comment by mcostalba** [comment]
Thanks for your patch, but....

Combos are patch interned to group parameters tweaks and are tested at double [0, 4]. Please read [this](https://github.com/glinscott/fishtest/wiki/Creating-my-first-test#parameter-tweaks-tests) for a detailed explanation.

So please drop from your patch the below change:

```C++
          else if (cutNode && singularBeta >= beta)
              return singularBeta;
```

and retest with double SPRT[0, 4], we can assume all the remaining stuff is a parameter tweak.

Eventually test the above change **alone** with the standard condition: SPRT[0.5, 4,5] + SPRT[0, 3.5]

Finally allow me to write a small comment. I appreciate your efforts and time dedicated to improve SF, but please consider that you are **not** doing a service to our community when muddying the waters and messing up the tests:

1. You have mixed assorted stuff under the _combo_ scenario, but combo patches have to satisfy quite strict conditions (for a reason) and you just ignored these rules

2. You **invented** your own test conditions: [0, 4] + [0, 3.5] is not documented anywhere and is not part of the official list of conditions.

Doing so you do not help the work of the maintainers and do not help other contributors to understand how to proceed in the various cases. So please don't.

**Comment by Vizvezdenec** [comment]
I think we already had quite a lot of patches committed passing [0;4] and [0;3.5]
Actually this one is by snicolet at least:
https://github.com/official-stockfish/Stockfish/commit/ff97a9fdb936a73de774df062f35d454a4a9af00
About combo I don't really know - on one hand it's true, it's not entirely parameter tweak but recently we were committing stuff like this I think.
I understand that this is not entirely "strictly good" patch, but overall it's okaying - we are not really swimming in oceans of elo.
From my opinion the most concerning is contempt change, actually.
Because contempt is a thing which we don't usually touch as a self-play elogainer and set it to highest non-regressing value vs 0. Imho, squashing contempt into combos opens a big pandora box to squeeze basically any parameter tweak into SF in following way:
1) get a "good" parameter tweak that barely not passes SPRTs;
2) change contempt on top of it (+1/-1/-5);
3) enjoy one run of it being lucky enough passing SPRTs.
The problem is that we need to "retune" contempt after each of this changes - current value 24 was tested as non-regression vs 0, but 25 was never tested vs anything apart from 24.

**Comment by Alayan-stk-2** [comment]
For parameters tweaks, [0;4] and [0;3.5] is not officially documented but having harder to pass LTC for parameters tweaks than for deeper code change doesn't make much sense. I opened issue #1919 about this inconsistency and it has just been sitting there, but it seems that the change has been unofficially adopted considering the patch by snicolet and others.

I agree with @Vizvezdenec about not mixing in contempt in combo patches, this opens too much of a potential for abuse to squeeze unrelated changes.

This combo also contains a dynamic contempt change, but arguably dynamic contempt + contempt should be tested together without other elements interfering and we should make sure that an apparent progress isn't just the result of lowering the effective contempt (the goal rather should be to get SF playing just as well while being more contemptuous and thus being more effective against weaker engines).

**Comment by mcostalba** [comment]
@Vizvezdenec well, firstly the patch of this PR is **not** a parameter tweak. Secondly currently parameter tweaks have [0, 4] + [0, 4] until some new parameter set is **official** chosen.

@Alayan-stk-2 eventually if you also post the quantitative table, computed by the @vondele tool for the 2 cases, current parameters and proposed new, as we have done for standard tests, we can move that thing on....otherwise I'd say it will remain sit there for a long time: any change of parameters should be backed by strong quantitative arguments.

**Comment by Alayan-stk-2** [comment]
@mcostalba Optimal values for parameters often change slightly as other eval terms/parameters are changed, or as search pruning/reduction/extensions change. Hence ideally, parameters changes should be not too expensive at testing, and the degree of confidence for progress can be slightly lower.

While with the new bounds for regular elo-gainers, there is a slight degree of confidence difference, parameter tweak testing is still more expensive when it comes to resources and remains strict in confidence.

[0, 4] + [0, 3.5] would not address the resource usage (it would slightly increase) or the confidence (it would remain the same). This is mostly about consistency, having harder to pass LTC for parameter tweaks is weird. FYI, I made computations with the tools using [0, 4] + [0, 4] here : https://github.com/official-stockfish/Stockfish/issues/1859#issuecomment-452422016

Parameters combo patches can work around the "doesn't make a big enough difference by itself" element, but combo patch testing is a can of worms in itself when it comes to resources usage. For example if parameter tweak A and B gains +0.5 elo while parameter tweak C loses -0.5 and was just a lucky yellow alone, the +0.5 combo will be likely to fail yellow. And then another combo is tested which will add a parameter tweak D which got a yellow, and if it still fails the person trying to get a combo passing may randomly try to remove A, B or C, etc.

I used the tool to evaluate 3-staged patch testing (for example https://github.com/official-stockfish/Stockfish/issues/1859#issuecomment-453751997 ) but there didn't seem to be much interest in this topic so I stopped beating a dead horse.

**Comment by 31m059** [comment]
@mcostalba, I have the utmost respect and gratitude for your work on Stockfish.  Your dedication and contribution to this project is unparalleled.  But please allow me to respectfully disagree about this PR.

As mentioned previously, there was this [0, 4] -> [0, 3.5] commit:
https://github.com/official-stockfish/Stockfish/commit/ff97a9fdb936a73de774df062f35d454a4a9af00 by @snicolet

@snicolet also appeared to endorse [0, 4] -> [0, 3.5] here:
https://github.com/snicolet/Stockfish/compare/800031c...bb06275
While not "official," I think it's perfectly understandable that @SFisGOD followed a procedure endorsed by a maintainer.

Regarding @Vizvezdenec's comment that
>About combo I don't really know - on one hand it's true, it's not entirely parameter tweak but recently we were committing stuff like this I think.

This is a small sample of commits since Stockfish 9 that were [0, 4] but not numerical tweaks, such as code reordering, swapping one variable for another, or potential but unclear simplifications:

- https://github.com/official-stockfish/Stockfish/commit/489357d7b221179a0fc116df706df5e937f991fa by myself
- https://github.com/official-stockfish/Stockfish/commit/313f4037339142f0c3488f511c57ca7a400ea8a5 by miguel-l
- https://github.com/official-stockfish/Stockfish/commit/bf01bd07551dd4e2d68d82b305cc5d89a4c23bb0 by snicolet and xoroshiro
- https://github.com/official-stockfish/Stockfish/commit/b2961aded6cd2807a8c4899e090e28fcb2161310 by VoyagerOne
- https://github.com/official-stockfish/Stockfish/commit/1093047e7d72ed0c82e143c2cc0af9ef7b0380ed by Rocky640

So I think it is very understandable that @SFisGOD submitted his tests this way.  Certainly he did not invent these conditions, and there is a precedent of maintainer approval for these bounds.  As both you and @snicolet are maintainers and seem to disagree with each other on this issue, I respectfully hope the two of you can come to an agreement.  Until then, the rest of us may be confused.

**Comment by mcostalba** [comment]
I missed the test by @snicolet, and I can't comment for him. But a change to a SPRT parameter rule requires an official discussion with an official decision afterwards, it cannot be done implicitly.

And currently the rules are [this ones](https://github.com/glinscott/fishtest/wiki/Creating-my-first-test#parameter-tweaks-tests)

I will open a new issue to openly discuss about a parameter change for tweaks as I did for standard test.

Regarding 3-staged patch, my personal opinion is that I found it too complicated in practice. It is already difficult to manage a 2 stage one (as we can see from this thread).

Regrading combo patch, please stick with the [rules](https://github.com/glinscott/fishtest/wiki/Creating-my-first-test#parameter-tweaks-tests), these kind of tests are very strict. They cannot be used as a "bag of patches" because the risk of introducing neutral or even regressive stuff is very high and because we spend  **a lot of resources** on simplifications, that are nothing more but removing neutral/useless stuff, it would be really nonsense to pour back them in through the "combo patch" backdoor.

Regarding to this specific PR, I also agree with @Vizvezdenec on contempt: we should avoid to throw a contempt tweak in a combo. Contempt, by its nature, it is better to be tested alone.

**Comment by SFisGOD** [comment]
STC retest passed: (no LTC test submitted) 
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 168557 W: 37420 L: 36591 D: 94546
http://tests.stockfishchess.org/tests/view/5c7a893a0ebc5925cffdaca9

But contempt=25 failed stc non-regression test:
LLR: -2.95 (-2.94,2.94) [-3.00,1.00]
Total: 148333 W: 29036 L: 29466 D: 89831
http://tests.stockfishchess.org/tests/view/5c7a7fe90ebc5925cffdac91

So, I'm closing this PR.

**Comment by noobpwnftw** [comment]
Why are you testing on different contempt values as non-regressions? I don't think that it is something we need to re-check once a while.

**Comment by noobpwnftw** [comment]
https://github.com/official-stockfish/Stockfish/pull/1806
Here are the reasoning behind why 24 was chosen in the first place, if you think the time has changed and it needs to be refined, start with non-regression on 24 first, only then try smaller values if the test failed.

**Pull request closed without merging**
