### PR TITLE
Minsplitdepth2 maxslaves7 fix

### PR DESCRIPTION
**Pull request by ajithcj**
Reduce minimumSplitDepth to 2. But use fewer slaves while splitting at lower depths. Test passed

STC 3 Threads:
LLR: 2.97 (-2.94,2.94) [0.00,5.00]
Total: 11351 W: 2008 L: 1838 D: 7505

STC 7 Threads:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 2587 W: 485 L: 353 D: 1749

LTC 7 Threads:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 20538 W: 2769 L: 2584 D: 15185

### CODE REVIEW

**Comment by ajithcj** [comment]
I've used a function as suggested by @glinscott

**Comment by zamar** [comment]
As we have seen in the other branch, this patch exposes an existing bug in Stockfish, so that with a high number of threads we get occasional hangs.

Thus we have to place this patch on hold. Please leave the pull request open anyhow. We'll proceed after we've identified (and hopefully fixed) the cause for the underlying issue...

**Comment by zamar** [comment]
Okay,

We are back to business... The underlying SMP issue has (likely) been fixed.

Now unfortunately the fix and this patch work in the same area.
So we need to respin this patch one more time at STC 7 Threads. If it passes, we can commit.

@ajithcj: Please schedule the patch again.

**Comment by ajithcj** [comment]
@zamar, I've submitted the test again. Please review and approve...

**Comment by lucasart** [comment]
Can the other pull request #418 be closed now? What is the difference between the two?

**Comment by ajithcj** [comment]
@lucasart, #418 can be closed... I didn't do so as most of the discussions were on that thread.#419 uses a function(as suggested by Gary) instead of inline lambda(from Marco's template).



     On Saturday, September 12, 2015 2:11 AM, lucasart <notifications@github.com> wrote:
   

 Can the other pull request #418 be closed now? What is the difference between the two?—

**Pull request closed without merging**
