### PR TITLE
Small cleanups 07

### PR DESCRIPTION
**Pull request by vondele**
Starting with an empty PR to collect suggestions for small cleanups.

No functional change.

### CODE REVIEW

**Comment by joergoster** [comment]
`TtHitAverageWindow` and `TtHitAverageResolution` are really ugly. Either `ttHitAverageWindow` or `TTHitAverageWindow`. YMMV, of course.

**Comment by vondele** [comment]
it is, however, consistent with PvNode.... which arguably could be PVNode

**Comment by MichaelB7** [comment]
PV is two words and should be capitalized as well. No different than TT.   The Pv is just as ugly as Tt.

**Comment by MichaelB7** [comment]
I can do a global replaced by case for all sources if so desired rather easily.  I have a script for that.

**Comment by protonspring** [comment]
Position.h, line 399:  The |=s is a lookup, so we'd like to avoid it.  This saves one and is a little faster on my machines.

- byTypeBB[ALL_PIECES] |= s;
- byTypeBB[type_of(pc)] |= s;

+byTypeBB[ALL_PIECES] |= byTypeBB[type_of(pc)] |= s;

**Comment by TerjeKir** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L541

There's a random extra space in this line behind [iterIdx], and also between +  6 for this and the previous line.

**Comment by xoto10** [comment]
I think the stat_bonus function should return 0 for depths above 15 rather than a (ok, very small) negative number:
```
   // History and stats update bonus, based on depth
   int stat_bonus(Depth d) {
-    return d > 15 ? -8 : 19 * d * d + 155 * d - 132;
+    return d > 15 ? 0 : 19 * d * d + 155 * d - 132;
   }
```

At very high depths I'm uncomfortable that the current code will consistently push down the score of a good move and also award positive "penalties" to all other quiet moves (e.g. pushing a pawn at tcec?) https://github.com/official-stockfish/Stockfish/blob/c527c3ad44f7465c79cef93f1e8cfebd998dc627/src/search.cpp#L1693

I have requested a couple of fixed length tests with larger values above depth 15:
-6000: https://tests.stockfishchess.org/tests/view/5eae382a6ffeed51f6e328e4 (currently -1.2 +/- 2.2 Elo)
-700: https://tests.stockfishchess.org/tests/view/5eae386c6ffeed51f6e328e6 (currently -0.6 +/- 2.2Elo)
They are yet to finish but appear to confirm what we would expect - any effect of the change suggested here is too small to measure on fishtest, hence I am suggesting it here.

**Comment by vondele** [comment]
@xoto10 I'll not use this PR for any patches that can change bench. That piece of code has been looked at many times (why give a zero bonus for good moves, it is actually not much different from -8). So far, all tests seem to indicate that it just doesn't matter. Rationalizing this hasn't happened however.

**Comment by xoto10** [comment]
A comment change, evaluate.cpp line 314:
-                // Penalty according to number of pawns on the same color square as the
+                // Penalty according to number of our pawns on the same color square as the

**Comment by Lolligerhans** [comment]
Would there be interest in replacing the use of `max` to define a minimum value with something more intuitive? Like `at_least(v, min)` which just wraps `std::max`? Or `clam<min,max>(v)` since often the boundaries are compile-time constants.

I will build something if this is considered a fine change.

**Comment by vondele** [comment]
@Lolligerhans std::max is clear enough, as it is just the standard name for this.

**Comment by Rocky640** [comment]
search,cpp lines 353 and 356 
`for (int i=0; i<4; ++i)`
should be
`for (int i = 0; i < 4; ++i)`

**Comment by xoto10** [comment]
pawns.cpp line 211:
```
-      File d = File(edge_distance(f));
+      int d = edge_distance(f);
```

**Comment by vondele** [comment]
GCC versions < 5 do not support std::is_trivially_copyable from the C++11 standard, remove the line as a workaround.

**Comment by protonspring** [comment]
This is a little faster:
https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_blockedcount4

master nps 1633705
patch nps 1637886

**Comment by Fanael** [comment]
`x^0.5` is the square root of `x`, so this is IMO clearer:

```diff
diff --git a/src/timeman.cpp b/src/timeman.cpp
index f794ab13..2d118d13 100644
--- a/src/timeman.cpp
+++ b/src/timeman.cpp
@@ -80,7 +80,7 @@ void TimeManagement::init(Search::LimitsType& limits, Color us, int ply) {
   // game time for the current move, so also cap to 20% of available game time.
   if (limits.movestogo == 0)
   {
-      opt_scale = std::min(0.007 + std::pow(ply + 3.0, 0.5) / 250.0,
+      opt_scale = std::min(0.007 + std::sqrt(ply + 3.0) / 250.0,
                            0.2 * limits.time[us] / double(timeLeft));
       max_scale = 4 + std::pow(ply + 3, 0.3);
   }
```

**Comment by xoto10** [comment]
I agree std::sqrt() is clearer than std::pow(, 0.5), but using pow() means that the root used can be varied as a parameter change, and therefore combo'd with other parameter changes. If we use sqrt() then changes to that become a code change, and combo's are no longer available.

**Comment by mstembera** [comment]
Line 664 in position.cpp can have the | changed to ||.  The speedup isn't enough to measure but clearly the second attacks_bb doesn't always have to be evaluated.
```C++
return   (attacks_bb<  ROOK>(square<KING>(~sideToMove), b) & pieces(sideToMove, QUEEN, ROOK))
      || (attacks_bb<BISHOP>(square<KING>(~sideToMove), b) & pieces(sideToMove, QUEEN, BISHOP));
```

**Comment by protonspring** [comment]
In pawns.cpp, lines 98+, if we do stoppers first, we can simplify opposed to:
opposed    = stoppers & file_bb(s);

https://github.com/protonspring/Stockfish/compare/83c9e59...e636989

**Comment by mstembera** [comment]
Position::castling_rights(Color c)  in position.h should return CastlingRights instead of int.

**Comment by joergoster** [comment]
In tt.cpp, line 106, there is a missing blank.
`  for (std::thread& th : threads)`

**Comment by protonspring** [comment]
I went through the MSVC build and added casts to remove all of the "possible loss of data" warnings.

https://github.com/official-stockfish/Stockfish/compare/master...protonspring:ps_casting3

**Comment by protonspring** [comment]
Both edge distances return an int.  We can consolidate them both to one method:

inline int edge_distance(int i) { return std::min(i, 7-i); }

**Comment by protonspring** [comment]
I don't think the enum for Depth does anything (Depth is typdefed to int) and it can be removed.

LLR: 2.93 (-2.94,2.94) {-1.50,0.50}
Total: 33968 W: 6652 L: 6523 D: 20793
Ptnml(0-2): 509, 3805, 8247, 3894, 529 
https://tests.stockfishchess.org/tests/view/5ec587e6377121ac09e10276

**Comment by mstembera** [comment]
Line 594 in position.cpp can be simplified from
```C++
&& (rank_of(from) == relative_rank(us, RANK_2))
```
to
```C++
&& (relative_rank(us, from) == RANK_2)
```

**Comment by snicolet** [comment]
> In pawns.cpp, lines 98+, if we do stoppers first, we can simplify opposed to:
> opposed = stoppers & file_bb(s);
> 
> [protonspring/Stockfish@83c9e59...e636989](https://github.com/protonspring/Stockfish/compare/83c9e59...e636989)

I think that the master version is best:
a) it is more readable
b) the definition of opposed and stoppers are independent, which is a good thing for the compiler and for maintainability of the code

**Comment by mstembera** [comment]
In movegen.cpp we don't need to redundantly pass in target for each call to generate_all() because it is derived only from the GenType and Position which we are already passing in.
https://github.com/mstembera/Stockfish/commit/0b952f7a197535f41c8e423af817c372e483b704

**Comment by vondele** [comment]
I've merged most of the suggested changes. I'll open a new PR, in case I have overlooked non-controversial changes, please repost.

**Pull request closed without merging**
