### PR TITLE
Fix undefined behaviour (1).

### PR DESCRIPTION
**Pull request by vondele**
avoids decrementing a variable beyond its defined range.

failed SPRT testing at STC, but as discussed, is likely noise, as game play is not influenced:

LLR: -2.95 (-2.94,2.94) [-3.00,1.00]
Total: 43548 W: 7555 L: 7783 D: 28210

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
I think ot is more robust to define the enum as ints:

```
enum File : int {
  FILE_A, FILE_B, FILE_C, FILE_D, FILE_E, FILE_F, FILE_G, FILE_H, FILE_NB
};

enum Rank : int {
  RANK_1, RANK_2, RANK_3, RANK_4, RANK_5, RANK_6, RANK_7, RANK_8, RANK_NB
};

```

This will guard also against future usages, because your change is quite subtle and is not immediate for a casual reader, you really don't want to let explicit the workarounds to handle the artefacts of  looping on an unsigned index.

**Comment by vondele** [comment]
@mcostalba your suggestion would also fix this issue, but somehow, since ranks and files have natural ranges, it could also make sense to keep to enum of finite range. Either fix is fine with me.

**Comment by syzygy1** [comment]
Just want to correct myself. I wrote: "even though the equivalent change of the Move enum was never tested that way...". But actually this is one of the other two "undefined" tests!

My confusion is caused by this thread:
https://groups.google.com/forum/?hl=en#!topic/fishcooking/Ey8pWMV-Uts
I thought at least the problem mentioned there had been fixed already, but it is the same problem as we have here.

Still I maintain that if we are sure the underlying type picked by gcc (and perhaps clang) does not change, then running tests (other than perhaps some benchmarks) should not be necessary.

**Comment by mcostalba** [comment]
Merged with 40b1b271782

**Pull request closed without merging**
