### PR TITLE
Change data file extension to nnue

### PR DESCRIPTION
**Pull request by nguyenpham**
For issue: https://github.com/official-stockfish/Stockfish/issues/2849

### CODE REVIEW

**Comment by stockchess** [comment]
prob my mistake but should both files be called nn-c157e0a5755b.nnue - lines 45 and 97

**Comment by vondele** [comment]
@nguyenpham can you check why your commit includes other things ? 

Also can you check if the initialization at line 45 is needed? We should specify the net at only one place.

**Comment by nguyenpham** [comment]
The initialization of the variant fileName at line 45 is completely redundant/useless at the moment. However, I guess it may use for training code later. Thus I just rename the file extension for that variant as a reminder. Let another cleanup task to decide to keep or remove that initialization later.

I am struggling to find why the PR including other things even it shows there are only a few changes in code.

**Comment by nguyenpham** [comment]
I closed this PR to try again from a clean fork. Will remove the initialization for the variant fileName too.

**Pull request closed without merging**
