### PR TITLE
Assorted cleanups

### PR DESCRIPTION
**Pull request by FauziAkram**
Assorted cleanups

Tests used to change the elo worth of some functions:

https://tests.stockfishchess.org/tests/view/65c3f69dc865510db0283eef
https://tests.stockfishchess.org/tests/view/65c3f935c865510db0283f2a
https://tests.stockfishchess.org/tests/view/65d1489f1d8e83c78bfd7dbf
https://tests.stockfishchess.org/tests/view/65ce9d361d8e83c78bfd4951
https://tests.stockfishchess.org/tests/view/65cfcd901d8e83c78bfd6184

No functional change

### CODE REVIEW

**Comment by Disservin** [comment]
@pb00067 I get your suggestion but a) I don’t like all the many comment changes in this pr, it‘s also why it wasn’t merged. b) I see the value from the default argument but I think it will attract bugs which will be noticed only when it’s too late.

**Comment by FauziAkram** [comment]
> a) I don’t like all the many comment changes in this pr, it‘s also why it wasn’t merged. b) I see the value from the default argument but I think it will attract bugs which will be noticed only when it’s too late.

@Disservin Which are the changes that you don't like, so I will revert them.
Basically, there are currently 4 changes:

1) Elo worth updates.
2) Capitalize the first letter of the comment.
3) Let the sentence complete in the same row as long as the length of the sentence allows it.
4) the comment about 20% time is outdated due to tuned merged patches, so changed it to a more general "percentage".

**Comment by Disservin** [comment]
I already said that I won’t merge arbitrary comment changes. I’ll only merge something where the comment is fundamentally wrong.

**Comment by FauziAkram** [comment]
@Disservin So that means that I need to revert number 1,2,3. Right?

**Comment by Disservin** [comment]
Yes, though the elo worth updates can be kept, also remove your reordering of the includes. Regarding 4) i later gotta check what we do. It's probably easier to start fresh and add the new changes

**Pull request closed without merging**
