### PR TITLE
Small speed up in pawns.cpp

### PR DESCRIPTION
**Pull request by Rocky640**
No functional change. Simplification. 

Results for 5 tests for each version:

Base      Test      Diff
Mean    1481627   1493056   -11429
StDev   28364     27468     3298

p-value: 1

### CODE REVIEW

**Comment by glinscott** [comment]
Interesting, we never use that condition?

**Comment by Rocky640** [comment]
Yes we do, but I added 
| lever 
on line 150.
if (   (passed | isolated | connected | lever)

**Comment by glinscott** [comment]
Ah, ok!  Makes sense :).  Looks good, we can merge this post SF6 release.

**Comment by dyross** [comment]
Why not:

```cpp
if ( (passed || isolated || connected || lever)
```

**Comment by Rocky640** [comment]
Good point, indeed, these are bool. Both ways will give the same result.

I will leave this to the maintainers, they are experts at these micro-optimization stuff.

If they go for the ||, they can remove the parenthesis too.
and then, the following order might be a little bit more efficient (just guessing here)
if (   lever || isolated || passed || connected || (ourPawns & pawn_attack_span(Them, s)))

**Comment by dyross** [comment]
I'm not expert on micro-optimization, and it actually seems from this link that it might be better your way:

http://stackoverflow.com/a/18646357/374506

**Comment by lucasart** [comment]
@Rocky640: Good patch.

* it's a non functional change
* it's a small simplification
* it's a mesurable speedup

    stat        test     master    diff
    mean   2,435,438  2,417,920  17,517
    stdev      7,902      5,510   7,930
    
    speedup       0.72%
    P(speedup>0)  98.6%

@glinscott @zamar @mcostalba: can you merge before SF6 RC2 ?

**Comment by zamar** [comment]
IMO SF7 stuff.

During freeze only bugfixes go in.

**Comment by zamar** [comment]
Why did you close this?

Reopening. Waiting for SF6 to be releaed.

**Comment by zamar** [comment]
I cannot reopen this as the relevant branch has been deleted... Please submit a new patch.

**Comment by Rocky640** [comment]
My mistake. Reopened as #234

**Pull request closed without merging**
