### PR TITLE
simplify code

### PR DESCRIPTION
**Pull request by guliashvili**
no need of memset

### CODE REVIEW

**Comment by mcostalba** [comment]
Thanks.

**Comment by guliashvili** [comment]
Thanks. Why don't we merge it?

**Comment by zamar** [comment]
Sorry guys,

I have a gap here... I'd expect the following to clear only the first element of the array:
int age[4096] = {0}

But that doesn't seem to be the case. Why is it working? Can you give me some reference, please?

**Comment by Rocky640** [comment]
http://stackoverflow.com/questions/629017/how-does-array100-0-set-the-entire-array-to-0

**Comment by zamar** [comment]
Thanks for the reference. You always learn something new.

approved.

**Comment by glinscott** [comment]
Looks good!

**Comment by guliashvili** [comment]
^_^ my first "contribution" .
btw it's really hard to understand whole project. where from do you guys suggest me to start?

**Comment by mcostalba** [comment]
https://chessprogramming.wikispaces.com/

**Comment by zamar** [comment]
I'm trying to merge your patches, but currently it says in github:
guliashvili wants to merge 1 commit into official-stockfish:master from unknown repository.

Can you please make your SF repo visible in github, so that we can fetch the patches from there?

**Comment by guliashvili** [comment]
Sorry I had some problems.
I created new pull request. I'll close this one
https://github.com/official-stockfish/Stockfish/pull/411

**Pull request closed without merging**
