### PR TITLE
Pawn extension

### PR DESCRIPTION
**Pull request by MichaelB7**
Pawn extension when pawn is pushed to the 7th or 8th rank, my preliminary results indicates it might be worthy of additional testing on fishtest.  Please advise if there is interest in further testing.  

```
3000 rounds and 9000 games completed...
time control: 1500+25
Date: 12/06/16 : 17:29:36
9000 game(s) loaded
Rank Name                      Rating   Δ     +    -     #     Σ    Σ%     W    L    D   W%    =%   OppR 
---------------------------------------------------------------------------------------------------------
   1 Stockfish 051216-PE POP   3132   0.0    4    4  6000 3412.0  56.9 1667  843 3490  27.8  58.2  3084 
   2 Stockfish 051216 POPCNT   3129   3.4    4    4  6000 3361.5  56.0 1624  901 3475  27.1  57.9  3086 
   3 Komodo 10.2 64-bit        3039  89.9    4    4  6000 2226.5  37.1  774 2321 2905  12.9  48.4  3131 
---------------------------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by snicolet** [comment]
Yes, of course, welcome in the big Stockfish boat! :)

Please read and follow the advices in https://github.com/glinscott/fishtest/wiki/Creating-my-first-test to help others to keep track of your changes: synchronize your master branch with the official one, create a clean, new branch from there and test your changes from this branch in fishtest. If the tests passes, you can open a real pull request for Marco.

**Comment by mcostalba** [comment]
Good luck!

**Comment by MichaelB7** [comment]
Thanks  - just submitted the run.  I had recreate the branch to generate the run with "just" those changes.  Noobie user error ;>)

**Comment by snicolet** [comment]
Hmm, it is strange that your master branch in the test is not from a git repository called "Stockfish" but from a git repository called "Macfish":
http://tests.stockfishchess.org/tests/view/5848acf30ebc5903140c5881

**Pull request closed without merging**
