### PR TITLE
Standardize Comments

### PR DESCRIPTION
**Pull request by FauziAkram**
Comments improvement, mainly, I've noticed a mix of comment styles in our chess engine code: double slashes (//) and triple slashes (///). To enhance code consistency and readability, I propose we standardize on double slashes (//) for comments for better consistency and clarity.
Non-Functional change.

### CODE REVIEW

**Comment by vondele** [comment]
I believe the two vs. three slashes has to do with the scope or visibility of the functions that are being commented (maybe somebody can explain). 

I don't have particularly strong opinion of that one, it has not been particularly useful for me, but maybe others like this.

**Comment by Disservin** [comment]
A somewhat more useful change for modern ide's is to move the comment above the function directly above the function without a space between so that ide's can properly display the description. I think that is kinda required by all ide's (a topic/pr on it's own).
Regarding the triple slashes vs double slashes I find it rather weird and not clear on first sight, so I'm fine with enforcing double slashes throughout the code.

**Comment by vondele** [comment]
so let's remove the blank line between comments and functions as part of this PR as well. It makes sense to have good IDE integration. @FauziAkram can you do that?

**Comment by FauziAkram** [comment]
@vondele Unfortunately, I'm afraid I can't do it for now.

**Pull request closed without merging**
