### PR TITLE
Stockfish 16.1 release candidate

### PR DESCRIPTION
**Pull request by Disservin**
Todo:

- [x] draft release notes

- [x] finish progression tests:

    https://tests.stockfishchess.org/tests/view/65d666051d8e83c78bfddbd6
    https://tests.stockfishchess.org/tests/view/65d666051d8e83c78bfddbd8

- [x] watch out for release blocking issues
- [x] update WDL model

Bench: 1303971

### CODE REVIEW

**Comment by dav1312** [comment]
> The elo gain from 16 to 16.1 will be higher than 15 to 16 was.

SF 16 vs SF 15 https://tests.stockfishchess.org/tests/view/6494097ddc7002ce609c99b7
```
new_tc	60+0.6
threads	1
book	UHO_XXL_+0.90_+1.19.epd
```
```
Elo: 47.03 ± 1.3 (95%) LOS: 100.0%
Total: 60000 W: 20247 L: 12174 D: 27579
Ptnml(0-2): 26, 2938, 16102, 10805, 129
nElo: 103.71 ± 3.0 (95%) PairsRatio: 3.69
```

SF 16.1 vs SF 16 https://tests.stockfishchess.org/tests/view/65d666051d8e83c78bfddbd6
```
new_tc	60+0.6
threads	1
book	UHO_4060_v3.epd
```
```
Elo: 27.66 ± 1.6 (95%) LOS: 100.0%
Total: 41960 W: 12357 L: 9024 D: 20579
Ptnml(0-2): 47, 3353, 10930, 6520, 130
nElo: 56.39 ± 3.4 (95%) PairsRatio: 1.96
```

**Comment by mstembera** [comment]
@dav1312 I was comparing the currently running progression tests to the 1 thread progression chart at https://github.com/official-stockfish/Stockfish/wiki/Regression-Tests where it shows that 15 to 16 was less than 20 elo.

**Comment by PGG106** [comment]
Different books, 8moves vs uho, if you look at the column for the uho book in the page you sent you'll see this
```
Elo: [47.03] ± 1.3
Ptnml: 26, 2938, 16102, 10805, 129
nElo: 103.71 ±3.0
PairsRatio: 3.69
```
47 > 27

**Comment by dav1312** [comment]
> @dav1312 I was comparing the currently running progression tests to the 1 thread progression chart at [Wiki: Regression Tests ()](https://github.com/official-stockfish/Stockfish/wiki/Regression-Tests) where it shows that 15 to 16 was less than 20 elo.

You can't compare completely different books. That is why I sent you the data and links directly, you are looking at the wrong test.

**Comment by mstembera** [comment]
Ok that makes sense.  Thanks for pointing out the book difference.  I think comparing the results from these various books that are actually not comparable on the same chart like this one https://docs.google.com/spreadsheets/d/e/2PACX-1vQqw86SXD_-zzP39DzfjBQ1eLBGyZMPyVLPuZDTY7zSNxBvxxj9CUXpd_AHRKy1aCpCCXGsznolmMVs/pubchart?oid=1631702142&format=image causes misinterpretation.

**Comment by robertnurnberg** [comment]
One thing to add on the TODO list: `[] update WDL model`. We can do this at the very last minute (to have the model as accurate as possible), as it will only changing the 8 coefficients in the two polynomials.

**Comment by Disservin** [comment]
@robertnurnberg yes good point, I can merge that together with the merge of sf 16.1

**Comment by Disservin** [comment]
merged with e67cc979fd2c0e66dfc2b2f2daa0117458cfc462, thank you all!

**Pull request closed without merging**
