### PR TITLE
[RFC] On the resolution to the SSSE3-based affine layer computation inexactness.

### PR DESCRIPTION
**Pull request by Sopel97**
This branch currently contains code that detects the problem when loading a network and prints diagnostics on standard output. (Only checks on affected architectures)

The affected architectures are non-VNNI >=SSSE3 architectures, and in some cases NEON.

In the current official network there is a single quadruplet of weights that are causing the problem. 

There are 6 possible solutions that I see, all with drawbacks...

1. Detect during training and push (clip) the weights towards compliance.
Issue 1.A.: The weight relations that may cause problems are mostly implementation defined, and I'm not actually sure if it's the same for all layer sizes and all current implementation in Stockfish. Do we want to tie the trainer with the constraints caused by the precise inference SIMD implementation?

2.  Apply a randomized algorithm during loading the network. Permute inputs/outputs of all layers until no problematic weight relations are found. (idea sparked by Andrew Grant)
Issue 2.A.: Not guaranteed to find a solution at all. Requires a reasonable failure threshold. Loading a compatible network may fail depending on architecture. Could be resolved by doing the checks regardless of the architecture, though that would complicate the detection logic as it would need to handle all cases.
Issue 2.B.: Not that trivial to implement.

3. Rely only on detection when loading the network. Fail hard on issue found.
Issue 3.A.: Loading a compatible network may fail depending on architecture. Could be resolved by doing the checks regardless of the architecture, though that would complicate the detection logic as it would need to handle all cases.

4. Rely only on detection when loading the network. Warn on issue found.
Issue 4.A.: Users may experience [slightly] different results based on architecture. Could be resolved by doing the checks regardless of the architecture, though that would complicate the detection logic as it would need to handle all cases.

5. Disallow official networks that exhibit the problem.
Issue 5.A.: Potentially loses Elo by hitting good networks.
Issue 5.B.: Inherits issues from either 3. or 4. for non-official networks.

6. Fix the inference code.
Issue 6.A.: ~5%(?) speed loss on affected architectures. Note that VNNI is getting more and more common.

Personally, I'm most inclined towards solutions 2 and 5(+3). Solution 5 could be temporary and later reinforced by solution 2 to allow more networks. It might not be feasible to perform the check in an architecture-agnostic way.

I have only scanned a few recent networks with this detection. It is possible that we have silently hit this problem in the past. It would be interesting to know what % of the networks actually exhibit this issue. If the % is small (<5%) I'm leaning towards solution 5(+3).

### CODE REVIEW

**Comment by dubslow** [comment]
What's the cost of "manually fixing a net post-facto"? I.e. don't modify training and testing, but if a net is found which is strong but which causes the problem, how hard is it to post-facto adjust the problematic weights to be within bounds? Is it likely to cost tens or hundreds of elo, or ~nil elo?

**Comment by Sopel97** [comment]
> What's the cost of "manually fixing a net post-facto"? I.e. don't modify training and testing, but if a net is found which is strong but which causes the problem, how hard is it to post-facto adjust the problematic weights to be within bounds? Is it likely to cost tens or hundreds of elo, or ~nil elo?

By applying solution 2. outside of the engine. Would not impact strength.

**Comment by Sopel97** [comment]
I'm also thinking that a two-stage solution may be a good candidate. Implement randomized network permutation as a python script in the trainer repo (could reside in the model, actually. It should also be much easier to code it in pytorch), and add verification command to stockfish. This way it the randomized algorithm could be automated by a simple glue-script.

**Comment by dubslow** [comment]
> Adjusting weights (clipping) could have a measurable strength loss, especially if in smaller layers.

worth testing, no?

the basic idea, as i see it, is that this is the first time this issue has ever cropped up, so given the available data I'm inclined to believe it is rather rare. if it's sufficiently rare, and if adjusting weights was shown to not have a measurable strength reduction, just manually doing so as needed *may* be less effort than writing new code, be it in the trainer or in the engine proper. should be explored at least, imho.

**Comment by mstembera** [comment]
While we are brainstorming I thought I would offer a possible 7th solution to the 6 above...
7.  Put the fast implementations behind a LOW_PRECISION or TRUNCATED_PRECISION #define so they can be enabled w/ a command line compile option.  I currently don't have a favorite.

**Comment by ddobbelaere** [comment]
Personally I think fixing the SF code (6.) is the right thing to do. It's a bug in SF, so it has to be fixed there.

All the other options are workarounds and feel hacky. In the long run, they might even harm. Who says that an unconstrained training process will not yield us more than the speed loss we should accept?

**Comment by silversolver1** [comment]
I was trying to draft a separate comment but I realized that I just ended up mostly agreeing with @ddobbelaere 's comment. 

In any case, to summarize what I also thought, IMO 6 is the most valid. The reason is this: option 3 will probably lead us to things like hardware-specific nets and I'm not sure that's viable or desirable. Or even easily maintainable really (plus would we bundle backup nets or something? Although that's kind of interesting actually. But if the engine were to just fail hard on a (default) net incompatible with a certain architecture, I think that would be putting too much burden on the average user, as they probably simply wouldn't understand - and then the complication of getting another net, where to get it, whether this new net is strong enough etc, are all resulting complications). 

Also I do feel most of the solutions are workarounds. It's possible we should just eat the speed loss (although I'm not sure how much elo a 5% slowdown is, or if it is a different % value)

But yeah, these are just my thoughts, hope this helps :)

**Comment by mbabigian** [comment]
Fishtest showed fixing this bug cost 1.67 Elo at ridiculous non-use case TCs. At any use case TC the difference becomes unmeasurable.  Clipping and or randomizing has an unknowable impact on future net development.  

In addition, fixing nets after the fact creates another problem.  During net training we test (triage) dozens of nets and then submit the the strongest net that passes our "quick test." Imagine testing 30 nets during training and the strongest by far is a net that hits the bug, but because the test is run with a bugged stockfish, that net does horrible and is discarded without ever getting to the "let's fix it for submission to Fishtest" stage.  The entire training pipeline would remain bugged and unreliable in this example - potentially throwing away the best nets before the fix and submission to Fishtest.

I still think an assembly language guru staring at the inline code long enough could probably find a way to get the speed back somewhere.  Why not leave if for some future contributer to improve?

From a human psychology standpoint the level of effort being made (while amazing and appreciated) to avoid applying the bug fix, suggests a decision was made long before this RFC was posted. Indicating that fixing the code was never actually a serious option.   My preference is for 6, but if I were to bet money, I'd wager on any option other than 6 being chosen.  It is always best to question your own objectivity.  I will be doing just that, as I noodle over this further.

**Comment by vondele** [comment]
nice to see the requirements on the weights with the current implementation spelled out explicitly with this PR. While some of the solutions (e.g. permutation of the weights) would allow us to keep the current implementation, it seems more sustainable to go with the bug fix (https://github.com/official-stockfish/Stockfish/pull/4391), as implementation defined weight constraints would be painful to maintain in the trainer. 

The only simple approach would be along the lines of option 1, i.e. quantize the network to use 7-bit values for the weights, so that saturation won't happen with any implementation or permutation. If a 7-bit quantized trainer is implemented and a corresponding net is trained, we could consider reverting the fix. Right now, we have no such trainer, and thus no data on potential Elo gain or cost of using 7 bit quantized nets.

**Pull request closed without merging**
