### PR TITLE
More regular use of mp.see_sign()

### PR DESCRIPTION
**Pull request by snicolet**
New helper MovePicker::see_sign() now always returns the sign of the SEE 
for the last move generated by the MoverPicker class.

No functional change

### CODE REVIEW

**Comment by snicolet** [comment]
The main point of this patch is that it simplifies the use of mp.see_sign() in search.cpp.

I have verified that the first commit doesn't introduce a slow down. The second commit is a speed optimization which brings around 0.5% on my system.

**Comment by mcostalba** [comment]
@snicolet thanks for the PR.

If you don't mind I would apply only first commit because second one simply does not worth it: 0,5% speed up is not enough to add complexity (and in this case it is really not obvious what the code does, at least for me).

Moreover I would wait for some speed test to confirm a non regression, for instance some of the changes pos.see_sign -> mp.see_sign apply where there are no captures possible, so it is a free slowdown, nevertheless I would leave as is for easier understanding.

**Comment by syzygy1** [comment]
It might make sense to simply expose the logic behind mp.see_sign() in search().

So, instead of hiding behind mp.see_sign() what is really being done, one could test in search() whether the last capture was a bad capture and, if not, whether the last capture was a good capture. For the reader that would make it perfectly clear what is going on.

The reader does not need to know that this is equivalent to the former invocation of see(). It already makes perfect sense to prune bad captures and moves that are not good captures and have negative see.

So one would need two (I'd say inline) methods mp.last_is_bad_capture() and mp.last_is_good_capture(), or something like that.

Just an idea...

**Comment by snicolet** [comment]
@mcostalba : applying only the first commit is fine with me.

The second commit used the fact that in case of ALL_EVASION and negative SEE value we stored this SEE value in m.value

Here is how I do my speed tests at the moment:

• Mac OS X 10.9 with Clang on a quad core machine
• idle machine during speed testing, no internet, no anti-virus
• use deterministic, non-pgo builds for **master** and **testedpatch**
• launch both **master** and **testedpatch** in parallel on bench at depth 22 (bench at depth 22 takes approximatively three minutes on my system at the moment). 

Running two long runs in parallel seems better to me than running lots of shorter runs sequentially multiple times and taking an average, because (a) any martian slowdown of my computer will hit both runs at the same time and (b) I want to eliminate as much as possible the noise of the OS in launching and forking tasks.

I use the following script to launch both in parallel:

````
#!/bin/sh

# change directory to the path of the script
cd "${0%/*}"

# name of my testing directory
testdir=./fishtest-master-for-local-tests/worker/testing

# two bench runs in parallel
$testdir/testedpatch bench 16 1 22 > /dev/null && echo "testedpatch"  &
$testdir/master      bench 16 1 22 > /dev/null && echo "master"

# end of it
echo
echo "... done"
echo
````

Results of commit 1 (*without* commit 2) against master: 
commit 1 is 0.07% slower than master, which is why I said
it didn't introduce a measurable slowdown on my system.

===========================
Total time (ms) : 181114
Nodes searched  : 246621380
Nodes/second    : 1361691
master

===========================
Total time (ms) : 181242
Nodes searched  : 246621380
Nodes/second    : 1360729
testedpatch

**Comment by mcostalba** [comment]
@snicolet running 2 tests in parallel is interesting, I have never see it. Have you validated this approach, I mean, have you run the same master in parallel and verified the speed is the same?

@syzygy1 I think you have a point here, indeed SEE function is in Position class and there is no reason why search should delegate it to MovePicker, search could very well call see_sign() directly. I think that the patch addresses an immediate convenience more than a logical or flow issue. So I have open an alternative PR #796....it is amazing how much a little renaming can do. Proper naming is essential in software development.

**Comment by vdbergh** [comment]
> @snicolet running 2 tests in parallel is interesting, I have never see it. Have you validated this approach, I mean, have you run the same master in parallel and verified the speed is the same?

The standard scripts also does this I think. The idea was introduced by Lucas and it seems sound.

**Comment by snicolet** [comment]
@mcostalba : I beg to disagree with Ronald's proposal and your PR #796 there.

Compare the two rules if we try to explain how to improve the chess algorithm in search.cpp to someone new to SF code:

• "You can always use **mp.see_sign()**, it will always give the sign of the last generated move"
• "You can use **mp.capture_see_sign()** to check the sign of the SEE when the move is a capture, otherwise you can call **pos.see_sign()**"

You claim that the second rule is better than the first: that's fine, it is 0.07% faster than the first.

Then people will start using the second rule in qsearch (isn't it faster after all ?), and you will realize that you should have named your new helper **mp.non_qsearch_captures_see_sign()**, because it doesn't work in qsearch even though there are captures in qsearch (but the beginner doesn't know that the stages in move picker for qsearch and non-qsearch don't have the same name, and why should he?)

Then people will start using the second rule in probcut, and you will realize that you should have named your new helper **mp.non_probcut_and_non_qsearch_captures_see_sign()**.

In fact your current helper, and the renaming in PR #796 doesn't change that fact, exposes implementation details of the move picker class, and it just shouldn't.

Please apply the commit 1 of this PR instead, it is fast enough, simple and easy to understand instead :-)

Hope this helps, Stéphane

**Comment by mcostalba** [comment]
@snicolet Thanks for your comment, I will let this open for sometime so to allow other people to comment on which is better.

Please people, this is not a majority vote, quantity will **not** win, quality of the argument (even a single one) will do.

Regarding your argument I would like to clarify that:

-  0.07% faster for me has zero value, I even don't consider this

- mp.non_qsearch_captures_see_sign() cannot work because MovePicker do not use SEE in qsearch(), the beginner will stop shortly or having his PR rejected and closed.

**Comment by snicolet** [comment]
> "MovePicker do not use SEE in qsearch()"

Yes it does, when we generate evasions.

**Comment by snicolet** [comment]
@mcostalba Why wouldn't we apply commit 1 of this PR now? This would allow to also keep the speed-up without refactoring VoyagerOne's code for the passed STC-LTC there: http://tests.stockfishchess.org/tests/view/57d829ec0ebc59030fbe52a1

**Comment by mcostalba** [comment]
Obolseted by 01ee509a5c33e11d7d6

Closing the PR.

**Pull request closed without merging**
