### PR TITLE
Use Movepick SEE value in search

### PR DESCRIPTION
**Pull request by mcostalba**
This halves the calls to the costly pos.see_sign()

Non functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Can someone please verify speed improvement of this patch? Thanks.

I am sorry but I don't have a reliable laptop (uncontrollable CPU throttling), I have measured more than 50% less calls to see_sign().

**Comment by joergoster** [comment]
It's a clear gain for me.
AMD FX-8120, gcc-Version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~14.04) 
standard build (non-pgo)
```
Result of  50 runs
==================
base =    1446372  +/- 1320
test =    1454227  +/- 1335
diff =      +7855  +/- 1835

speedup        = +0.0054
P(speedup > 0) =  1.0000

CPU: x86_64
```

**Comment by Krgp** [comment]
This is what I (i7 4790k Windows 10 x64 standard - _non pgo_ ) got 

Master vs **PR791**

Results for 50 tests for each version:

            Base      Test      Diff      
    Mean    2557943   2584178   -26235    
    StDev   3860      7000      9402      

p-value: 0.997
speedup: 0.01

**PR791** vs Master

Results for 50 tests for each version:

            Base      Test      Diff      
    Mean    2582405   2557796   24609     
    StDev   6832      5299      9248      

p-value: 0.004
speedup: -0.01

1% Speedup on my machine

**Comment by pb00068** [comment]
Just as additional info: Stefan Geschwentner's test is going well so far on STC 
http://tests.stockfishchess.org/tests/view/57d110440ebc59030fbe5078
and this patch requires more than just the sign of see.

**Comment by snicolet** [comment]
The following implementation of Mark's idea stores the last move generated by the MovePicker object in a class variable, which allows MovePicker::see_sign() to always return a argumented result (instead of +1/-1/DONTKNOW), so that line 961 of search.cpp stay simple:
https://github.com/snicolet/Stockfish/commits/last_move_of_move_picker

Maybe we can extend this technique to always return the true value of the move see (while keeping the speed advantage), so that Stefan's code is not affected ?

**Comment by mcostalba** [comment]
This is also possible, but adding 'move' to MovePicker members is not free.

I suggest I commit my wimple patch then we speed test against yours and
check which is best.

Committing my patch helps further tests IMO.

**Comment by mcostalba** [comment]
@pb00068 Stefan Geschwentner's should be rewritten like this:

```
          else if (   depth < 3 * ONE_PLY
                   && pos.see_sign(move) < VALUE_ZERO)
              continue;
          else if (   depth < 6 * ONE_PLY
                   && (pos.see_sign(move) < -PawnValueMg * 2 * int(depth - 2 * ONE_PLY) / ONE_PLY)
                  continue;       
```

Not only to allow this optimization, but also because it is much better anyhow. So no problem :-)

**Comment by VoyagerOne** [comment]
@mcostalba 
You should add this logic to SEE pruning in Q-search.
Line: 1310

**Comment by mcostalba** [comment]
In qsearch we don't use see in movepicker

**Comment by mcostalba** [comment]
Merged with 602d7fbb07e2cb

@snicolet could you please rebas eyour version above current master?

I also suggest to evaluate something like:

```
int MovePicker::see_sign(Move move) const
{
    return  stage == GOOD_CAPTURES ?  1
          : stage == BAD_CAPTURES  ? -1 
          : pos.see_sign(move);
}

```
So to avoid adding 'move' to members.

**Comment by snicolet** [comment]
@mcostalba 
Pull request raised there: https://github.com/official-stockfish/Stockfish/pull/793

**Pull request closed without merging**
