### PR TITLE
Use intrinsics only for LSB/MSB

### PR DESCRIPTION
**Pull request by lucasart**
The NO_BSF does not cover any real-life use case today. The only compilers that
can compile SF today, with the current Makefile and no source code changes, are
GCC, Clang, MSVC, ICC. All of them support LSB/MSB intrinsics. It's the
compiler's job to figure out what to do of these intrinsice. If hardware LSB/MSB
are available on the target architecture, it will use those, otherwise it will
generate its own code.

No functional change.

### CODE REVIEW

**Comment by syzygy1** [comment]
Are you sure about ARM? (I have no idea myself, but ARM clearly is very much a real-life use case.)

**Comment by syzygy1** [comment]
If the intrinsics are available on ARM, then I guess it suffices to check that it generates decent code.

**Comment by lucasart** [comment]
ARM is not a compiler. Please be more specific, and explain what use case is broken here, that is covered by the current makefile.

**Comment by syzygy1** [comment]
What do you not understand about the question.

**Comment by snicolet** [comment]
Since you are both online at the same time and up for a ping-pong match, there is a chat application over there: http://chatwing.com/stockfish :-)

**Comment by protonspring** [comment]
Looks like ARM processors include a CLZ instruction with compiler support for CTZ (rbit + clz).

After some searching around. . . it certainly looks like any half-decent compiler/processor build in the past 20 years likely addresses clz and/or ctz.

**Comment by lucasart** [comment]
The only compilers available for ARM are GCC and Clang. Either you use the Android NDK (which is a pain in the arse in my experience), and you configure a GCC or Clang cross-compiler. Or you use the simple Linux cross compiler: arm-linux-gnueabi-gcc (much easier than NDK, works like a charm). Either way the intrinsics are available.

Ideally the Makefile should be changed to target instead armv8-a, which is 64-bit so will run much faster than armv7 compiles. And to use arm-linux-gnueabi-gcc instead of the NDK version (which anyway is very user specific as you have to configure your own as you install this).

**Comment by snicolet** [comment]
Marco, what compiler do you use when testing for 32 bits support? Would you still be able to compile for 32 bits if we removed the fallbacks?

**Comment by mcostalba** [comment]
build failed: https://ci.appveyor.com/project/mcostalba/stockfish/build/1.0.1380/job/hsq1gikkfaxyc02s

**Comment by lucasart** [comment]
@mcostalba: fixed. please check.

**Comment by lucasart** [comment]
Eventually we can get rid of all the 32-bit support, which will simplify the code enormously. Only 1.93% of Windows are 32-bit today according to this link: http://store.steampowered.com/hwsurvey/?platform=pc (all of which are in reality 64-bit hardware with a 32-bit OS installed, but we won't get people to change their OS, so we have to go with that).

**Comment by mcostalba** [comment]
Here are some performance tests (on Linux with 64 and 32 bit binary, gcc)

```
Lucas 64

 Performance counter stats for 'system wide' (5 runs):

    13.120.839.598      cycles:u                              ( +-  0,06% )
    17.234.878.408      instructions:u # 1,31  insn per cycle ( +-  0,08% )

       4,921344131 seconds time elapsed                       ( +-  0,33% )

Master 64

 Performance counter stats for 'system wide' (5 runs):

    13.066.288.375      cycles:u                              ( +-  0,06% )
    17.204.180.102      instructions:u # 1,32  insn per cycle ( +-  0,02% )

       4,899954875 seconds time elapsed                       ( +-  0,30% )




Lucas 32

 Performance counter stats for 'system wide' (5 runs):

    18.872.755.297      cycles:u                              ( +-  0,15% )
    25.766.785.927      instructions:u # 1,37  insn per cycle ( +-  0,02% )

       7,129245365 seconds time elapsed                       ( +-  0,30% )


Master 32

 Performance counter stats for 'system wide' (5 runs):

    18.827.772.037      cycles:u                              ( +-  0,09% )
    25.750.165.554      instructions:u # 1,37  insn per cycle ( +-  0,02% )

       7,147617360 seconds time elapsed                       ( +-  0,89% )

```

It seems a bit slower to me....I will test also on windows mingw 32.

**Comment by lucasart** [comment]
@mcostalba: I don't understand what you're measuring. On Linux, with gcc or clang, with 32 or 64 bit, this PR is identical to master: the NO_BSF path is not used.

**Comment by mcostalba** [comment]
@lucasart you are right! Why I get different numbers? I will redo the tests...hmmmm

**Comment by lucasart** [comment]
The real question is: when is the NO_BSF path actually used ? As pointed out by AppVeyor earlier, it is used for making 32-bit Windows compiles using MSVC. That seems to be the only use case today. And such compiles are not official ones anyway: they are not supported in the Makefile, not used in any Fishtest scenario, and the method for building win32 official compiles is mingw (which results in faster binaries).

**Comment by mcostalba** [comment]
@lucasart another scenario is ARM

**Comment by mcostalba** [comment]
BTW I see it would be possible to add android to Trevis CI, although not immediate:

Here few examples:

https://github.com/google/flatbuffers/blob/master/.travis.yml
https://github.com/googlesamples/android-ndk/blob/master/.travis.yml
https://github.com/leinardi/androidthings-pio/blob/master/.travis.yml


....I will open an issue

**Comment by lucasart** [comment]
@mcostalba: Yes, and for ARM compiles (using either GCC or Clang) the 64-bit intrinsics work just fine. I know this because I've already compiled my engine like that (for ARMv7=32-bit and ARMv8-a=64-bit). Just compile same as Linux, replacing "g++" by "arm-linux-gnueabi-gcc -static" (and specify the march parameter like armv7 or armv8-a).

**Comment by snicolet** [comment]
I am fine with committing the current state of the pull request, if everybody confirm me that we still have the following to compile 32 bits on Windows and Linux

• Linux : Clang and GCC work for 32 bits =>  Is that correct?
• Windows : Clang, GCC and MSVC work for 32 bits =>  Is that correct?

For ARMv7 (32bits), Lucas says that we can still compile on Linux, is there a way to compile for ARMv7 on Windows?

**Comment by snicolet** [comment]
Another aspect, which could be the subject of another pull request: would it be worthwhile to add an ARM target in the Makefile? If even for us it wasn't obvious how to compile for ARM, then it might be even more confusing for newcomers and the Makefile could help.

**Comment by mcostalba** [comment]
Here are the tests with mingw 32 bit. I have repeated the test 3 times, but the first one is probably the best, with lowest stddev.

There is a very small slowdown, probably because our 32 bit routines (from chessprogrammingwiki)  are better and more chess-engine optimized than gcc intrinsics.

Anyhow it does not seem a sensible slowdown.

```

Results for 10 tests for each version:

            Base      Test      Diff      
    Mean    873017    866778    6239      
    StDev   9680      8716      18128     

p-value: 0,365
speedup: -0,007


Results for 10 tests for each version:

            Base      Test      Diff      
    Mean    869123    869883    -760      
    StDev   16818     13713     12786     

p-value: 0,524
speedup: 0,001


Results for 10 tests for each version:

            Base      Test      Diff      
    Mean    867338    865553    1785      
    StDev   20312     26084     12456     

p-value: 0,443
speedup: -0,002


$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\mingw\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/mingw/bin/../libexec/gcc/i686-w64-mingw32/5.1.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c/mingw510/i686-510-posix-dwarf-rt_v4-rev0/mingw32 --with-gxx-include-dir=/mingw32/i686-w64-mingw32/include/c++ --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,objc,obj-c++,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-sjlj-exceptions --with-dwarf2 --disable-isl-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=i686 --with-tune=generic --with-libiconv --with-system-zlib --with-gmp=/c/mingw510/prerequisites/i686-w64-mingw32-static --with-mpfr=/c/mingw510/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw510/prerequisites/i686-w64-mingw32-static --with-isl=/c/mingw510/prerequisites/i686-w64-mingw32-static --with-pkgversion='i686-posix-dwarf-rev0, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw510/i686-510-posix-dwarf-rt_v4-rev0/mingw32/opt/include -I/c/mingw510/prerequisites/i686-zlib-static/include -I/c/mingw510/prerequisites/i686-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/c/mingw510/i686-510-posix-dwarf-rt_v4-rev0/mingw32/opt/include -I/c/mingw510/prerequisites/i686-zlib-static/include -I/c/mingw510/prerequisites/i686-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw510/i686-510-posix-dwarf-rt_v4-rev0/mingw32/opt/lib -L/c/mingw510/prerequisites/i686-zlib-static/lib -L/c/mingw510/prerequisites/i686-w64-mingw32-static/lib -Wl,--large-address-aware'
Thread model: posix
gcc version 5.1.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)

```

**Comment by lucasart** [comment]
@mcostalba: For mingw32, the NO_BSF path should not be used and this PR should be identical to master. The only way you have a difference is if you're using MSVC or ICC, and 32-bit Windows. But mingw32 is basically gcc for 32bit windows, so shouldn't define MSC_VER. Am I missing something ?

**Comment by protonspring** [comment]
Can we do the same thing for popcount ?

**Comment by gcp** [comment]
>Today, only 1.93% of Windows are 32-bit according to this link: 

This survey is very biased towards people who are active "gamers". Contrast: https://hardware.metrics.mozilla.com/#goto-os-and-architecture which shows about 20% of users still on 32-bi.

**Comment by mcostalba** [comment]
You are right, I will retest with no_bsf

**Comment by lucasart** [comment]
@protonspring: Yes, the same applies to popcount. We should use compiler intrinsics. It's the compiler's job to generate whatever is the fastest code for the target architecture (which may be a hardware popcnt if it exists or software workaround like SWAR popcount). Now it's worth noting that od versions of GCC generate very poor software popcount on popcount devoid machines. This may have been fixed in new versions of GCC (meaning use SWAR popcount).

**Comment by mcostalba** [comment]
I was not able to check again, if you feel is urgent please feel free to commit, otherwise I will run another speed test later this week.

**Comment by lucasart** [comment]
The only impact of this PR is for MSVC on WIN32. And I doubt you would see a material slowdown even there, because we're replacing software LSB by 32-bit hardware BSF solution (ok, there's some branching involved, but still). In any case this use case corresponds to no official use whatsoever. No fishtest compiles are MSVC+WIN32, no official compiles are MSVC+WIN32, the Makefile doesn't support MSVC anyway. So this 32-bit BSF code is just provided for compatibility, just to make sure we don't alienate the 1% of developpers that still use WIN32+MSVC.

**Comment by mcostalba** [comment]
@lucasart I am planing to test with ARCH=x86-32-old

**Comment by syzygy1** [comment]
You'll have to test with MSVC or you will not be testing the patch. The patch changes nothing for gcc and clang, not even for x86-32-old.

**Comment by lucasart** [comment]
@mcostalba @snicolet: Oops. I deleted the branch accidently. Were you going commit or not ? Let me know, I can easily rewrite the code.

**Comment by snicolet** [comment]
Yes, I was considering committing, but waiting for some tests by Marco.

**Comment by mcostalba** [comment]
Here are the results. Sorry for the delay:

Tested with:
mingw32-make.exe build debug=no ARCH=x86-32-old COMP=mingw

```
Results for 10 tests for each version:

            Base      Test      Diff      
    Mean    830228    835765    -5537     
    StDev   14517     13830     20338     

p-value: 0,607
speedup: 0,007

$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\mingw\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/mingw/bin/../libexec/gcc/i686-w64-mingw32/5.1.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c/mingw510/i686-510-posix-dwarf-rt_v4-rev0/mingw32 --with-gxx-include-dir=/mingw32/i686-w64-mingw32/include/c++ --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,objc,obj-c++,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-sjlj-exceptions --with-dwarf2 --disable-isl-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=i686 --with-tune=generic --with-libiconv --with-system-zlib --with-gmp=/c/mingw510/prerequisites/i686-w64-mingw32-static --with-mpfr=/c/mingw510/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw510/prerequisites/i686-w64-mingw32-static --with-isl=/c/mingw510/prerequisites/i686-w64-mingw32-static --with-pkgversion='i686-posix-dwarf-rev0, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw510/i686-510-posix-dwarf-rt_v4-rev0/mingw32/opt/include -I/c/mingw510/prerequisites/i686-zlib-static/include -I/c/mingw510/prerequisites/i686-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/c/mingw510/i686-510-posix-dwarf-rt_v4-rev0/mingw32/opt/include -I/c/mingw510/prerequisites/i686-zlib-static/include -I/c/mingw510/prerequisites/i686-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw510/i686-510-posix-dwarf-rt_v4-rev0/mingw32/opt/lib -L/c/mingw510/prerequisites/i686-zlib-static/lib -L/c/mingw510/prerequisites/i686-w64-mingw32-static/lib -Wl,--large-address-aware'
Thread model: posix
gcc version 5.1.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)

```

So it seems not regressive, maybe even a bit faster.

**Comment by lucasart** [comment]
@mcostalba: Thanks... But you're still not testing the patch, which is non functional with GCC (hence mingw32). The only impact of this patch is on MSVC/WIN32. Any other possible scenario it's the same code as master (even ICC which defines `__GNUC__`, even ARM which uses GCC or Clang hence defines `__GNUC__`).

**Pull request closed without merging**
