### PR TITLE
Remove check for non-pawn material in futility pruning

### PR DESCRIPTION
**Pull request by Stefano80**
STC:

LLR: 3.29 (-2.94,2.94) [-3.00,1.00]
Total: 28407 W: 5336 L: 5210 D: 17861

LTC:

LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 143212 W: 19630 L: 19676 D: 103906

bench: 7919041

### CODE REVIEW

**Comment by mcostalba** [comment]
The reason of non-pawn material check is to skip null search in case of only pawns becuase these positions are prone to zugzwang.

Your patch instead goes in the opposite direction: now we are even more prone to zugzwang . 

Perhaps this is ok, but it would be more consistent to remove the check also in null search condition and verify it passes. Because if removing the check in null search does not pass, then it is incorrect to remove in the former condition, i.e. in your patch.

**Comment by Stefano80** [comment]
Hi Marco,

I dont follow you, you say: if null move search is bad with only pawns, then also FP must be. But the test proves the opposite.

Btw: what does FP have to with zugzwang? And if this is the reason for the check, why do we allow the opponent to have pieces?

**Comment by mcostalba** [comment]
No the test does not prove anything.

zugzwang is a very rare and impact can be small for our LTC, but can make
the engine blind and this can lead to lose a game in real TC conditions.

If removing the non-pawn condition in null search passes SPRT[-3, 1] than
you have a point, otherwise we can deduce that the (negative) effect of
your patch is to small to be dedected by LTC.

**Comment by Stefano80** [comment]
Hi Marco,

I really dont see what futility pruning has do with zugzwang (and btw I also dont see why zugzwang should only happen if we have no pieces). I just cannot see it. If you some argument, please explain them to me.

If you say that you will never commit this patch alone without removing the same condition also from null search, I will just close the PR, since it does not make sense at all for me.

Alternatively, I can take the zugzwang positions from chessprogramming wiki and check that the patch does not break anything there, better to be safe than sorry. If this is an option for you, I'll keep the PR open till I find the time for that.

**Comment by zamar** [comment]
I have a feeling that there was a good reason for this condition... I can't remember the details, but I'm a bit reluctant to take this away as a simplification.

**Comment by Stefano80** [comment]
Hi Joona, give me sometime, I'll try to find out when the condition has
been introduced. I will have time for that in the end of the week...
Il 04/lug/2016 03:29 AM, "Joona Kiiski" <notifications@github.com> ha
scritto:

**Comment by AlexandreMasta** [comment]
I remember that something like this was already done or proposed before and was a consensus that it would make SF blind to zugzwang in some positions.
Nice catch by Marco and Joona.

**Comment by Stefano80** [comment]
Hi,

I took the test suite for [zugzwang](http://www.stmintz.com/ccc/index.php?id=392369) posted on  [chessprogramming](https://chessprogramming.wikispaces.com/Zugzwang) and compared the results of master and branch with 1s thinking time.

They made always the same move, apart of position 21, where they chose a different route for mating the king.

I think that many here underestimate the fact that:
1) the patch is not really about null move search
2) zugzwang happens also without pawns

Of course, there will be some very exotic position where this patch fails and master not, but I thought that we care about Elo and not exotic positions.

The line I want to remove has been added back in 2010 in commit 50e094ef8db36ba1c1020b12594506f62532df17 as a refactoring of the now retired function ok_to_do_nullmove(pos) which was already back then deemed to have "remained there for ages". This was the pre-fishtest age.

So, these are my final considerations.

**Comment by stockfishdeveloper** [comment]
@Stefano80:  +1
I agree we need ELO rather than a "perfect" engine. I'm thinking those 7 positions out there won't affect the strength at all...
Ok, so we lose a game because of this every 10 years... How many will we win because of this in that time?

My two cents.
stockfishdeveloper

**Comment by AlexandreMasta** [comment]
We wont Win any, because this change is a regression at LTC as you can see
by the curve and negative test results. It only passed due to
simplification SPRT boundary.
Em 5 de jul de 2016 14:41, "stockfishdeveloper" <notifications@github.com>
escreveu:

**Comment by MichaelB7** [comment]
Agree with Joona.

**Comment by Stefano80** [comment]
Hi,

I also checket the [Lasker-Reichhelm Position ](https://github.com/official-stockfish/Stockfish/files/356081/Lasker-Reichhelm.Position.txt) at depth 30. This is a classical, more complex pawn-only zugzwang.

No difference in results for any depth. Solution is found consistently starting with depth 20. Branch find the solution a bit faster.

**Comment by mcostalba** [comment]
@Stefano80 Step 7. Futility pruning was once called static null search pruning. It was added above current null search to prune nodes even without performing a null search. It was a kind of null search shortcut. That's the reason the conditions of Step 7 and following Step 8 are largely similar. It is largely accepted that null search is risky when no pawns are on the board (rare case), and because two conditions are twins and very bound together you want to use same condition also for Step 7. Maybe what your patch does is neutral but IMO is not a simplification because blurs even more the logical and original link that there is between Step 7 and Step 8. If pawn condition is valid for null search makes sense to keep same condition also here: it can be harmful and eventually can avoid pruning a wrong node in some cases.

**Comment by Stefano80** [comment]
I find it a pity that you closed it. I was planning to make some further
investigation to prove or reject your claims about what this part of SF is
doing, but obviously there is no interest in the community.
Il 13/lug/2016 08:51, "Marco Costalba" <notifications@github.com> ha
scritto:

**Pull request closed without merging**
