### PR TITLE
Simplify evaluation constants

### PR DESCRIPTION
**Pull request by cj5716**
Passed STC (<0, 2> by accident):
LLR: 2.95 (-2.94,2.94) <0.00,2.00>
Total: 346016 W: 89529 L: 88756 D: 167731
Ptnml(0-2): 1012, 41074, 88027, 41919, 976
https://tests.stockfishchess.org/tests/view/6659d6ecf426908fcc6b6929

Passed LTC:
LLR: 2.96 (-2.94,2.94) <-1.75,0.25>
Total: 89862 W: 22887 L: 22734 D: 44241
Ptnml(0-2): 45, 9999, 24694, 10144, 49
https://tests.stockfishchess.org/tests/view/665a6ebb062b2c3cf814fde8

Bench 1384563

### CODE REVIEW

**Comment by vondele** [comment]
seems to have wrong bench, and overlaps with https://github.com/official-stockfish/Stockfish/pull/5327

**Comment by cj5716** [comment]
will do

**Comment by cj5716** [comment]
rebased LTC submitted: https://tests.stockfishchess.org/tests/view/665bd39f44e8416a9cdc1909

**Comment by MinetaS** [comment]
CI requires "Bench xxxx" line at the bottom of commit message if there are functional changes.

**Comment by cj5716** [comment]
Closed in favour of <https://github.com/official-stockfish/Stockfish/pull/5361>

**Pull request closed without merging**
