### PR TITLE
Add "silent" switch to the "go" command.

### LINKED ISSUE #3344: "bench" is IO limited
STR:

1) On a Windows machine, launch the stockfish.exe executable, either by clicking in Explorer or launching from cmd.exe (Command Prompt)
2) Type "bench".
3) Launch the same executable from a mingw shell (e.g. mingw64.exe)
4) Type "bench".

Observe results from 2 and 4 are not within run error, on Windows 10 I see 16% difference.

### PR DESCRIPTION
**Pull request by Sopel97**
If specified then most output will be supressed. "bestmove" line will not be supressed so it should still conform to the UCI protocol.

Used in bench,

Fixes #3344

### CODE REVIEW

**Comment by Torom** [comment]
I don't know if this is intentional. The info strings `info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled` or `info string classical evaluation enabled` are still printed.

**Comment by Sopel97** [comment]
Right. I forgot about the depth 0 output. Fixed.

About the `info string`. I think it should stay as it's not really part of the "go" command.

**Comment by vondele** [comment]
I don't think this warrants an additional option. Simple approaches are to redirect IO, or just do a bench that is a little deeper.

**Comment by Sopel97** [comment]
Therefore #3344 should be closed as not an issue.

**Comment by vondele** [comment]
so closing as discussed.

**Pull request closed without merging**
