### PR TITLE
Correct handling of KQKRPs endgame.

### PR DESCRIPTION
**Pull request by jhellis3**
IIRC, the current code for this endgame was committed following a
particularly embarrassing TCEC game. The current code is fine in that
provides correct evaluations for the positions it addresses; however,
there are holes in its coverage allowing Stockfish to search around the
code, effectively rendering it useless.

These changes effectively fill in the holes the current approach and
also add specialized knowledge for the unique cases of Rook and Knight
pawns which were either being handled incorrectly or not at all.
Inspiration for these changes was another game in the latest TCEC
highlighting the insufficiency of the current code. The specific
position is the first FEN listed in the notes.

Bench: 9180815

### CODE REVIEW

**Comment by glinscott** [comment]
Very nice, clear code!  The comments about the positions that are handled by the new code are great.  Looks good to me.

**Comment by lucasart** [comment]
Have we tried to remove KQKRPs endgame entirely ?

**Comment by jhellis3** [comment]
Given that such positions have shown up in TCEC twice now, I don't see how it could be considered useless even if there is no apparent Elo benefit.

**Comment by zamar** [comment]
I think that this patch is not committable without further proof:

- 70 extra lines of code.
- Expected 0 ELO gain.
- Imperfect rules. A rule which is right only in 98% of time can cause more damage than do good.

- Have you checked how many false positives your rules have?

**Comment by jhellis3** [comment]
-Imperfect rules:  While the rules may be imperfect, they are far more effective than the current code.  The reason for this is that, where they do err, they err on the side of a draw.  A false draw is very easily  resolved by the search because the pawn or the rook is typically shortly won.  On the other hand, false win/loss scores are very difficult to resolve with search because in order for SF to understand that the position is not a win/loss and only a draw, it must search until it hits the 50 move rule in every line not covered by the code (good luck with that). 

Regarding the specialized code for the knight and rook pawns, I am fairly confident the code is as accurate as it can reasonably be made without TBs.  The code for relative rank 2 does contain many false draw scores, but in my testing these have always been quickly resolved by search (again the same can not be said of false win/loss scores).

**Comment by zamar** [comment]
Sorry, but I'll have to say 'no'.

One of our primary goals is to keep code simple, clean and elegant. The focus should be removing specialized evaluation code, rather than writing new code.

If any ELO gain can be proven, then I'll reconsider my position.

**Comment by jhellis3** [comment]
"The focus should be removing specialized evaluation code, rather than writing new code."

I think this is a rather unfortunate perspective.  There is no efficient way to handle such positions with generalized code.  And sometimes it pays to do the "right" thing even at the cost of Elo.  Lucas has already shown that null move verification costs Elo, but SF does it anyway because otherwise it is incapable of handling certain positions.  We know from experience that is endgame occurs in actual gameplay, and we know that SF currently fails horribly at it.  There is no general solution to this problem (other than TBs).

However, the code addressing just the rank2 pawns is no more complex than the existing code.   Would you be willing to accept that, as at least SF would then be able to handle the positions the current code addresses correctly?

**Comment by glinscott** [comment]
@zamar - in general, I totally agree with less code == better.  I think the endgame heuristics are the one place where that rule doesn't serve us well though.  Yes, we could eliminate them all with virtually no elo impact, but that doesn't mean we should.

They should still be tested to see that they don't cause regressions, but other than that, they are just around to prevent SF giving silly scores in endgames.  It probably won't change the theoretical outcome of the game.  Although clearly, there is value in having 100% accurate endgame information, as TBs are quite valuable.

**Comment by zamar** [comment]
@jhellis3: null move verifications solves a huge number of positions with very little extra code and very small ELO decrease. We have TBs which provide 100% correct information for endgames like this.

@glinscott: About this patch I'm worried about 2 things:
- Imperfect heuristics can hurt more than one might thought. They can lead the search to a wrong direction in midgame.
- We are opening a door for everybody to get their favourite imperfect endgame heuristic into SF. Because these are 0 ELO changes, there is no way to objectively evaluate them.

**Comment by jhellis3** [comment]
Not everyone has/uses TBs, I do not.  And by that logic we could remove all endgame knowledge from SF that is less than 6 pieces.  

The search already goes wrong in the midgame because SF's eval is by default wrong.  The "imperfect" heuristic is both far better than what we have now and far better than nothing.  Hell, the eval itself is nothing more than an imperfect heuristic to guide search (which is why it gets this endgame very wrong).  This comment also tells me you have not downloaded and actually tested the changes, because if you had, you would see that my comment about search correcting the eval quickly is accurate. 

There is really zero risk here.  If SF is in an antecedent position where it is able to go up a Queen for a Rook if it chooses, it is not going to lose the game, period.  It may, however, draw the game by entering into this endgame which it will not avoid because it can not see it as a draw, as it has done twice in TCEC now.

**Pull request closed without merging**
