### PR TITLE
Re-order object files in makefile

### PR DESCRIPTION
**Pull request by MichaelB7**
This is to provide a hint to the complier on proper ordering.  Picked up 1% on macOS using PGO clang.  Not sure if anyone else will see the same , but it's worth a shot.

### CODE REVIEW

**Comment by mcostalba** [comment]
Can you share some document that gives some kind of rationale behind this change? 

Otherwise I am going to close it, sorry, no voodoo here.

**Comment by MichaelB7** [comment]
Go ahead and close it.   I have only been compiling crafty for twenty years and it worked in crafty.  No voodoo here.

**Comment by MichaelB7** [comment]
@mcostalba  it's already closed - but here is a web source if interested.

"Object file reordering is an Project Builder feature that lets you change the order in which object files are linked. Using this technique, you can position source files used most frequently by your application so that they are linked into the executable first; you can also position files that refer to one another contiguously in the executable."

http://www.nextop.de/NeXTstep_3.3_Developer_Documentation/Concepts/Performance/G_LinkOptimization.htmld/index.html

**Comment by mcostalba** [comment]
@MichaelB7 thanks for providing the link.

Interesting reading, but we are talking of 1995 technology here!

Today we have LTO and profiling that have been developed to do exactly that but much better, moreover even if you decide to manually optimize linking order, this can change in a random way when you add new changes:

_"since further development (i.e., adding new routines or changing which routines call what other routines) can affect the optimal procedure order."_

So my suggest (that probably you will ignore) is to forget about thise low level details and leave them to the compiler that has a better understanding and information than you to sort it out, moreover it sorts it out at every compile stage, instead your manual order, apart from being done by hand and "by heart"  would remain fixed with any future modification.

**Pull request closed without merging**
