### PR TITLE
Color changed to a bool (bColor)

### PR DESCRIPTION
**Pull request by protonspring**
non-functional simplification.

This makes the code a bit easier to read/understand.
The bitwise NOT (~) operator for changing sides/colors is a bit strange.

removes a bit of code.

It seems a bit slower, but I'm not sure.  Is this interesting at all?

### CODE REVIEW

**Comment by protonspring** [comment]
This code is quite a bit slower and lost SPRT 190/260.

**Comment by protonspring** [comment]
Fixed a few bugs.  I won't make any changes until someone says if this is worth anything or not.

**Comment by MichaelB7** [comment]
I would pass.  See no reason to commit.

**Comment by protonspring** [comment]
Thanks for the comment.  The only benefit would be removing 4-6 lines of
code and increased readability.  If those are not worth a commit, i will
move on.

**Comment by protonspring** [comment]
I found the last bug.  Identical bench and speed.  Should i make a prettier
patch?

**Comment by protonspring** [comment]
I'll make a nicer patch.  sorry for all of the confusion.

**Pull request closed without merging**
