### PR TITLE
Save/Load Hash File

### PR DESCRIPTION
**Pull request by Zerbinati**
Save/Load Hash File
Capability of saving the full hash to file
"Daniel Jose Original Code"

### CODE REVIEW

**Comment by Rocky640** [comment]
For full credits and discussion
http://www.talkchess.com/forum/viewtopic.php?topic_view=threads&p=724927&t=64720

Looks like a nice to have feature.

@Zerbinati : please format code SF style.  You are missing some line breaks and spacing is not consistent with surrounding code.

**Comment by Zerbinati** [comment]
If you can help me I'm not an expert thank you

Il 30 lug 2017 02:19, "Rocky640" <notifications@github.com> ha scritto:

**Comment by mibere** [comment]
Yes, it's a nice and new feature and should be implemented - at least there is no reason in my option to reject it.

**Comment by joergoster** [comment]
Really? Without any testing of its functionality and benefit?

**Comment by mibere** [comment]
Of course the code has to be verified and working. But the feature as such should be added to SF. There are already two known top engines with persistent hash, why not add this to SF too?

**Comment by hero2017** [comment]
I agree completely. This is a feature I've also suggested to DON's engine years ago and it's one I've always used with all the engines that provide it. However, except for DON's engine and the last time I tested it this is broken on the other engines like Komodo. After analyzing a position to for example, a depth of 40 and saving the hash...if I was to restart the engine and load the hash from the same position it would still take almost the same amount of time to reach depth 40 again. That's the only reason why I haven't used it for a while now.


But the feature itself is something I've been waiting for SF to add for years now and I don't think I'm the only one. Anyway that's my 2 cents' worth.

________________________________

**Comment by beyondCritics** [comment]
I see the following problems:
1.)  TranspositionTable::load does not check for the existence of the hash file. The spirit of the UCI protocol demands silent and gracefully recover in this case.
2.) I see no versioning scheme. If someone is able to change the hash table format later, this will introduce incompatibilities and may render user collections of hash files useless, This is not nice.
3.) As it is now, a typical use case for an engine would be, that the user configures some scenario once and later on uses it many times, with a single mouse click. This patch breaks that use case, the user has to manipulate a loaded engine. This obstructs automation. I can not manipulate a loaded engine from within scid. IMHO a better way would be, to assicate the hash file name fully with the engine configuration

**Comment by mibere** [comment]
SF is the strongest engine, but other engines are better and more innovative regarding features. The acceptance of new features and suggestions for SF is too conservative in my opinion.
And, the acceptance of new features and suggestions should not be decided by one or two people, but by the community and users (-> voting).
Usage, features, purposes, ... are more important than code readability - the end-user is not interested in code readability or complexity. Refusing user requests just because of code changes, a bad excuse.

**Comment by beyondCritics** [comment]
4.) This patch does not respect coding style, as already pointed out. @mibere: Have you already read this http://tirania.org/blog/archive/2010/Dec-31.html ?
5.) This patch is not minimal,since it mingles two completely different changesets together: Saving/Loading a hashfile and retaining the generation counter during position changes. Please read https://github.com/glinscott/fishtest/wiki/Creating-my-first-test
6.) If the gui allows the user to load a hash file during a search, he could trigger undefined behaviour. If the gui does not allow the user to manipulate a loaded engine (as scid does), he can currently not use this feature from within the gui.

**Comment by lucasart** [comment]
I think the only good idea here is to not clear TT between positions, as ucinewgame can be sent.

But there is no need for an extra UCI option for that: just don't clear TT when UCU_Analyse mode is true.

**Comment by beyondCritics** [comment]
Indeed, i think that not clearing the hash table in analysis mode is of tremendous usefulness for the chess playing community. It allows them, to use stockfish like a "lens" and concentrate efforts there they think it is the most useful, may it be the case or not. A more or less skilled player can grind out results more swiftly, if he is able to show stockfish the right solutions upfront, thus he will be rewarded for thinking on behalf of its own, generally a rare thing.
If this feature will find its way into main stockfish, i should be approriatly advertised, so that experts can elaborate on that.

**Comment by lucasart** [comment]
that said, when you are going through moves, or variations, in a sequential manner, in analysis mode, I don't see why the GUI would send ucinewgame at all. So it would be more a GUI problem.

By the way, have we even verified that GUI do this? If so, which one? And why can't the GUI be fixed instead ? Or are we just wasting time discussing how to remedy a inexistent GUI bug? So much hand waiving and BS on talkchess…

**Comment by joergoster** [comment]
@lucasart @beyondCritics I think the only interesting part of this patch is to NOT age the TT entries when going through the moves (of one root position) in analysis mode. Although I must admit, I didn't try by now if it's really of benefit.

OTOH, clearing the hash after setting up a NEW position, even when analyzing, or on a 'ucinewgame' in cli-mode, is fully intentional and must be kept as is imho! I fail to see the logic to NOT clear the hash if I want to analyse a different position ...

**Comment by mcostalba** [comment]
This is more a feature request than a PR.

It is just few lines of code, there is no file consistency check, configuration, testing, etc..

**Comment by AlexandreMasta** [comment]
As long as the feature **## does not affect performance**, is independent, usefull and clear enough I see no reason to not have it.

**Comment by beyondCritics** [comment]
Testers and Developers will tend to dislike the "Inhibit aging" feature, since it affects testing negatively. It could affect performance of "chess analysts" negatively during studying of e.g epd-files, although its benefits should outweigh the disadvantages for them i think. I would suggest to add an option for this.

**Comment by beyondCritics** [comment]
I tested this epd-file with "inhibited aging" and a Hash of 256 MB, but it became clear quickly that the loss of performance with this usage is rather critical. E.g. after analyzing a bunch of different root positions i came back to the first and stockfish couldn't solve it anymore, sticked with 1.Be2 instead of the best 1.Nd2.

**Comment by beyondCritics** [comment]
I tested the [tony-dcc-caleb.epd ](http://www.talkchess.com/forum/viewtopic.php?topic_view=threads&p=725478&t=64306) epd-file with "inhibited aging" and a Hash of 256 MB, but it became clear rather quickly that the loss of performance with this usage is rather substantial. E.g. after analyzing a bunch of different root positions i came back to the first and stockfish couldn't solve it anymore, sticked with 1.Be2 instead of the best 1.Nd2.

**Comment by beyondCritics** [comment]
I tested the [tony-dcc-caleb.epd](http://www.talkchess.com/forum/viewtopic.php?topic_view=threads&p=725478&t=64306) epd-file with "inhibited aging" and a Hash of 256 MB from within the "scid" gui, but it became clear rather quickly that the loss of performance with this scenario is rather substantial. E.g. after analyzing a bunch of different root positions i came back to the first and stockfish couldn't solve it anymore, sticked with 1.Be2 instead of the best 1.Nd2.

**Comment by zamar** [comment]
I don't think that this feature is in the scope of Stockfish project. But I'll leave up to @mcostalba to decide.

**Comment by mcostalba** [comment]
As already stated, permanent hash file is not so trivial if you want to do it properly (TT version and size, hash signature, endianess, thread safe, etc..) and test it properly (big hash files, save and restore through GUI, some performance measurements, SMP, etc..) and especially if you want to prove it is somehow useful and not just a marketing gimmick (test cases and examples that show it improves and how much compared to standard).

So at best this is just a feature request, at worst it is not useful at all even if implemented correctly (and in that case it will be also a huge and not trivial patch).

So I will close it.

**Comment by hero2017** [comment]
I think that's one reason why we have so many clones of SF. They have features and enhancements that SF always refuse to include, always for one reason or another. Not even a simple Large Pages feature. Really disappointing. But I guess it's ok. For myself and this reason alone, I always use a clone instead for being able to load/save hash, for large pages, and cerebellum book support. As long as clones exist SF can stay bare bone and concentrate on its strength only.

________________________________

**Pull request closed without merging**
