### PR TITLE
Remove references to splitpoints (code and comments)

### PR DESCRIPTION
**Pull request by snicolet**
Remove references to splitpoints (code and comments)

No functional change.

### CODE REVIEW

**Comment by zamar** [comment]
approved.

**Comment by lucasart** [comment]
While you're at it, can you remove the unused UCI option "Min Split Depth" ?

Thanks.

**Comment by zamar** [comment]
@snicolet: Please resolve conflicts with master. Should be straightforward.

**Comment by snicolet** [comment]
Closing this, I've opened a pull request against the new master:
https://github.com/official-stockfish/Stockfish/pull/478

**Pull request closed without merging**
