### PR TITLE
Loop optimization

### PR DESCRIPTION
**Pull request by johndoknjas**
Bench: 5332964 (non-functional speedup)

Probably done tinkering with this PR now. Somewhat successful in implementing vondele's suggestion (trying to use a pragma to get the behaviour of this PR's first commit bffd980). From my measurements on pyshbench the speedup is around 0.22%, which isn't as much as bffd980, but still seems to be measurable. Verification on other computers is needed though. 
I also ran two stc tests for this patch - unfortunately neither passed, although at least in both cases the LOS was above 50%.

Pyshbench:

Result of 1350 runs
------------------
base (master) = 1312602  +/- 2042
test (patch) = 1315518  +/- 2072
diff = +2916  +/- 1100

speedup        = +0.0022
P(speedup > 0) =  1.0000       

(Note that this probability should likely be somewhere in the 90s, and not 100% - from my and Lorenz's discussion in #test-discuss, this probability calculation seems to be a bug with pyshbench).

Fishtests:

Red STC:
https://tests.stockfishchess.org/tests/view/62bac6255e9263e1847fdfa4
LLR: -2.93 (-2.94,2.94) <0.00,2.50>
Total: 93120 W: 25061 L: 25097 D: 42962
Ptnml(0-2): 396, 9837, 26151, 9759, 417

Yellow STC:
https://tests.stockfishchess.org/tests/view/62bb97505e9263e1847fff04
LLR: -2.93 (-2.94,2.94) <0.00,2.50>
Total: 157048 W: 42481 L: 42403 D: 72164
Ptnml(0-2): 663, 16588, 43976, 16602, 695

### CODE REVIEW

**Comment by Torom** [comment]
**pyshbench**

clang 13.0.1
```
Result of  50 runs
==================
base (...es/stockfish) =    1461159  +/- 1471
test (...ptimizations) =    1459377  +/- 1497
diff                   =      -1782  +/- 2225

speedup        = -0.0012
P(speedup > 0) =  0.0584

CPU: 4 x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Hyperthreading: on
```

gcc 12.1.0
```
Result of  50 runs
==================
base (...tockfish_gcc) =    1426392  +/- 1345
test (...izations_gcc) =    1436077  +/- 1335
diff                   =      +9685  +/- 1806

speedup        = +0.0068
P(speedup > 0) =  1.0000

CPU: 4 x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Hyperthreading: on
```

**perf**

master clang 13.0.1
```
 Performance counter stats for 'system wide' (50 runs):

    11.623.810.056      cycles:u                                                      ( +-  0,09% )
    19.675.138.965      instructions:u            #    1,68  insn per cycle           ( +-  0,08% )

           2,69696 +- 0,00191 seconds time elapsed  ( +-  0,07% )
```

patch clang 13.0.1
```
 Performance counter stats for 'system wide' (50 runs):

    11.639.835.163      cycles:u                                                      ( +-  0,07% )
    19.761.297.062      instructions:u            #    1,69  insn per cycle           ( +-  0,06% )

           2,69065 +- 0,00138 seconds time elapsed  ( +-  0,05% )
```

master gcc 12.1.0
```
 Performance counter stats for 'system wide' (50 runs):

    11.805.774.804      cycles:u                                                      ( +-  0,05% )
    19.375.851.416      instructions:u            #    1,63  insn per cycle           ( +-  0,06% )

           2,73472 +- 0,00142 seconds time elapsed  ( +-  0,05% )
```

patch gcc 12.1.0
```
 Performance counter stats for 'system wide' (50 runs):

    11.976.555.956      cycles:u                                                      ( +-  0,07% )
    19.012.889.102      instructions:u            #    1,61  insn per cycle           ( +-  0,05% )

           2,72427 +- 0,00175 seconds time elapsed  ( +-  0,06% )
```

**Comment by vondele** [comment]
I think that's a bit invasive for not passing LTC. I would be curious to know if the same can be achieved with a gcc pragma? 
https://gcc.gnu.org/onlinedocs/gcc/Loop-Specific-Pragmas.html

**Comment by johndoknjas** [comment]
@vondele Well, that worked quite well to say the least :) With these two pragma statements, it appears to shave off over 1% of Stockfish's total instructions. If we include the code after line 400, then the speedup for this patch should be somewhere in the ballpark of 1.2% (on GCC).

**Comment by vondele** [comment]
could you test this version of the patch again on fishtest?

**Comment by mstembera** [comment]
There are several gcc unroll options listed here https://gcc.gnu.org/onlinedocs/gcc-3.4.4/gcc/Optimize-Options.html
Perhaps they can be useful.

**Pull request closed without merging**
