### PR TITLE
Assorted headers cleanup

### PR DESCRIPTION
**Pull request by mcostalba**
Mostly comments fixing and other small things.

No functional change.

This is possibly my last patch before release, pelase apply because are mostly comments and I think some of them can be useful to clarify some tricky part.

### CODE REVIEW

**Comment by zamar** [comment]
Are you sure that this change is fine? Intel linux compile is not affected?

-# if !defined(NO_PREFETCH) && (defined(__INTEL_COMPILER) || defined(_MSC_VER))
-# include <xmmintrin.h> // Intel and Microsoft header for _mm_prefetch()
-# endif

+#if !defined(NO_PREFETCH) && defined(_MSC_VER)
+# include <xmmintrin.h> // Intel and Microsoft header for _mm_prefetch()
+#endif

**Comment by zamar** [comment]
Otherwise looks good.

As a side note, I think the "unlikely" macro can be removed, there is no point in it... If there is a special need to highlight this, a simple comment will do.

**Comment by mcostalba** [comment]
Yes you are right, I have fixed teh macro and verified with Intel C++ on Linux it works correctly.

I have also retired  "unlikely" macro. Pull request have been updated now.

**Comment by glinscott** [comment]
Looks good.

**Comment by zamar** [comment]
approved.

**Pull request merged**
