### PR TITLE
Solution to "En passant to block checking piece #3270"

### PR DESCRIPTION
**Pull request by BM123499**
It solves the issue #3270 without slowing down or speeding up the generation of moves. It now checks if it was a discovery attack instead of the double pushed pawn is the attacking piece. It now solves the issue because if it's not a discovery check, it could be either pawn attack (legal) or the attacker passes through the En Passant square (illegal). It may show as a possible move in other illegal fens, but those moves will be considered illegal.

### CODE REVIEW

**Comment by MichaelB7** [comment]
Your patch is 1% slower on my machine running bench to depth to 26.  This patch appears to fix "something" which was not broken.   The obvious question is:  

- _**Why slow down the move generator just to be able to generate all "legal moves" in a position that itself is illegal?**_ 

 I have to give this patch a thumbs down. Sorry.

**Comment by BM123499** [comment]
@MichaelB7 I indeed trying to change what's not broken. Due to its nature, for legal position, if there is a check with an En Passant square either the attacking piece is the advanced pawn or it was a discovery attack. I now check if it's a discovery attack.
If you check the [assembly code](https://godbolt.org/z/Pxcbxh), you will see that no increase on the number of instructions. Furthermore, it has less instructions when there is no optimization. Unless I've done something wrong, I see no reason for changing the speed.

**Comment by MichaelB7** [comment]
> @MichaelB7 I indeed trying to change what's not broken. Due to its nature, for legal position, if there is a check with an En Passant square either the attacking piece is the advanced pawn or it was a discovery attack. I now check if it's a discovery attack.
> If you check the [assembly code](https://godbolt.org/z/Pxcbxh), you will see that no increase on the number of instructions. Furthermore, it has less instructions when there is no optimization. Unless I've done something wrong, I see no reason for changing the speed.

My question is why?   I do not understand the why since I do not see any benefit.

**Comment by BM123499** [comment]
> My question is why? I do not understand the why since I do not see any benefit.

@MichaelB7. Well. In my opinion, being able to analyze an apparently legal position but unreachable just by changing a signal and a exclamation point is a small benefit. It's a very specific point and don't change the analysis of a normal game, but it can analyze a (very) few more unusual position (and apparently legal) set by someone. It is imperceptibly, but it is still. They may don't accept my change, and it is totally understandable, but I thought I could share my idea.

**Comment by Sopel97** [comment]
fuck this put it on fishtest as a simplification

**Comment by MichaelB7** [comment]
It is passes as a simplification, even though it is not , I have no issue with it.

**Comment by vondele** [comment]
@BM123499 it will need at least a non-regression test on fishtest. If there is no slowdown, this should pass.

Would you need to change the comment on top?

Generally, I see no need to support illegal fens. If it just works with equivalent code, it can be considered however.

**Pull request closed without merging**
