### PR TITLE
Update evaluate_nnue.cpp

### PR DESCRIPTION
**Pull request by Satyam-Vy**
removed unnecessary comments

### CODE REVIEW

**Comment by Disservin** [comment]
This is rather common in c++ apps and not really an unnecessary comment

**Comment by Satyam-Vy** [comment]
Hey! I am new to open-source and github , but I have an interest in cpp and
contributing to open-source. if there is any discord for the repository i
am up to join it.

Warm Regards
Satyam Vyas

**Comment by ppigazzini** [comment]
> Hey! I am new to open-source and github , but I have an interest in cpp and contributing to open-source. if there is any discord for the repository i am up to join it. Warm Regards Satyam Vyas

https://discord.com/invite/awnh2qZfTT

**Comment by snicolet** [comment]
Current comment seems fine to me too, closing the PR.

**Pull request closed without merging**
