### PR TITLE
Atomic signals

### PR DESCRIPTION
**Pull request by lucasart**
https://github.com/official-stockfish/Stockfish/pull/465

### CODE REVIEW

**Comment by zamar** [comment]
Looks good to me. But let's wait for Marco's comments.

**Comment by mcostalba** [comment]
I am fine with it, but please use load(std::memory_order_relaxed) also in check_time() 

Thanks.

**Comment by zamar** [comment]
@mcostalba: I can't see any good reason to use it in check_time(). That code is not speed critical. I think it's better to limit the use of std::memory_order_relaxed to really hot path only, don't you think?

**Comment by glinscott** [comment]
Looks good to me too!

**Comment by mcostalba** [comment]
@zamar ok, then. It was just for consistency, but it's ok, it has no
practical impact.

**Comment by zamar** [comment]
OK. We finally approve on the final version :-)

I've resolved the merge conflicts, and submitted the final test:
http://tests.stockfishchess.org/tests/view/562bff240ebc5964d3445f9d

If this doesn't show a significant regression, we can commit.

**Pull request closed without merging**
