### PR TITLE
[Issues] Probabilistic crashes on macOS with Xcode builds

### PR DESCRIPTION
**Pull request by Hengyu**
# Crash with macOS builds

_Sorry, this was my mistake. I want to post this in the **Issues**._

## Summary

I am trying to build the current Stockfish with Xcode 9.1 on macOS (without makefile).
The build succeeded. But when I test it, it will crash with some probability. 

## Setup

Here is the setup for my project:
1. Xcode 9.1, macOS High Sierra, MacBook Pro 2016.
2. Everything in Xcode compiling options remains unchanged. 
    - I am not familiar with `Makefile` thus *not* change the build settings in Xcode with respect to the instructions in `Makefile`.
    - Xcode uses clang and llvm to compile the source code.
3. The test is single-threaded. 

## Workflow of the test

The details can be found in [uci.cpp](https://github.com/official-stockfish/Stockfish/pull/1311/files#diff-9e544a2ba018bea83f86711c6b8f1871) which I added two functions named `performMove(const string& move)` and `infiniteMove()`.

The test goes as follows:
1. Ask the engine the best move for the current position periodically (1000 milliseconds). 
2. Update the best move and use the request the engine with the new position.
3. The engine will stop this test if the game is over.
    - But the engine will crash with a probability.

## Crash

From statistics, crashes usually happen in three places:

1. `bool Position::is_draw(int ply) const` in `position.cpp` line 1082.
2. `Value search(Position& pos, Stack* ss, Value alpha, Value beta, Depth depth, bool cutNode, bool skipEarlyPruning)` in `search.cpp` line 500.
3. `void Position::do_move(Move m, StateInfo& newSt, bool givesCheck)` in `position.cpp` line 675.

The error message is `EXC_BAD_ACCESS` which means the engine is trying to access a memory that is already been deallocated.

## Differences

I modified the original source code for testing purpose. You can compare the code differences via https://github.com/official-stockfish/Stockfish/compare/master...Hengyu:macOS.

There are two main differences:
1. Commented some `cout` to make the command clean.
2. Added functions in `uci.cpp` for infinite move testing.

## Another Problem

If I use two or more threads in the engine and open the thread sanitizer in Xcode, it will complain data races in `TTEntry`.

## At Last

I am not sure whether this is caused by compiling options. Because I am not using `Makefile`. And I am using the default compiling options in Xcode. Here are two screenshots of options in Xcode.

### CODE REVIEW

**Comment by syzygy1** [comment]
Since this is not a pull request, it doesn't make much sense to leave this open.

As to the issue you are reporting, if SF crashes after you have modified it, then you should probably just fix your modification.

If you can get Stockfish to crash on **legal** input, i.e. input fully conforming to the UCI protocol, then there is a problem that should and will be fixed.

That the TT has data races is known and accepted.

**Comment by snicolet** [comment]
I think that Ronald is right here: since your post is not about a pull request to add to the current master, the pull request should be closed, and since the post is not about an issue/bug with the current master code, it should not go to the "Issues" section of github either.

What you are asking is debugging help for changes that you are doing in your branch, and the best place to find help would be in the fishcooking forum, IMHO : https://groups.google.com/forum/?fromgroups=#!forum/fishcooking

**Comment by Hengyu** [comment]
Please close this pull request. Thanks.

**Comment by MichaelB7** [comment]
You can close it.  No need to get a maintainer involved.

**Pull request closed without merging**
