### PR TITLE
[Cluster] merge master

### PR DESCRIPTION
**Pull request by vondele**
merges master into cluster.

### CODE REVIEW

**Comment by WOnder93** [comment]
Isn't this actually a cherry-pick? This will duplicate the commits in the cluster branch, instead of doing a just a merge commit as before.

**Comment by snicolet** [comment]
@WOnder93 Just curious: what is the better git command you think we should have used?

**Comment by vondele** [comment]
@WOnder93 same question here.. this was a
```
git merge upstream/master
git rebase -i cluster
```
in a branch branched from clusterNodes2

**Comment by noobpwnftw** [comment]
Maybe no rebase?

**Comment by WOnder93** [comment]
Yes, if you did just `git checkout cluster; git merge upstream/master` without the rebase, then this would generate a merge commit, same as the previous merges of `master` into `cluster` did.

IMHO, a somewhat cleaner workflow would be to always rebase the whole `cluster` branch on `master` like we do with the `tune` branch (although that would likely cause more work with conflict resolution). However, at this point we are probably too far down the merging road so it is better to just stay consistent and always do a simple merge.

BTW, you can get a nice GUI view of a repo's git tree using `gitk --all` (the `gitk` utility is easily installable on most Linux distros) or a similar view in the console using `git log --all --oneline --graph`.

**Pull request merged**
