### PR TITLE
Simplify !(PvNode || cutNode) to allNode

### PR DESCRIPTION
**Pull request by TarasVuk**
Passed STC:
LLR: 2.94 (-2.94,2.94) <-1.75,0.25>
Total: 108992 W: 28178 L: 28039 D: 52775
Ptnml(0-2): 356, 12428, 28762, 12621, 329
https://tests.stockfishchess.org/tests/view/66c73a51bf8c9d8780fda532

No functional change

### CODE REVIEW

**Comment by peregrineshahin** [comment]
Nice! It is worth mentioning that the node-type system in Stockfish is based on expectations since we are activly searching.
we expect a node to be a `PvNode` which might end up as `allNode` with a transposition table and re-searching relative to the final proof of the tree, but this information is useless info in practice, I don't believe we need to prefix every node type (`PvNode`, `cutNode`, `allNode`) to be `expectedPvNode`, `expectedCutNode`, `expectedAllNode`.
While this is not a simplification it's a nice refactor.
apart from that please fix the title `Simplify (PvNode || cutNode) to allNode` ->  `Simplify !(PvNode || cutNode) to allNode`

**Comment by peregrineshahin** [comment]
Read this https://en.m.wikipedia.org/wiki/De_Morgan%27s_laws
That's no better definition, when it's the same definition according to basic logic, you might argue that it would sound simpler to read but it's a matter of taste and not worth a real conversation.

> You can think of a better definition of `allNode`.
> 
> ```c++
>     const bool allNode = !PvNode && !cutNode;
> ```
> 
> Moreover, we always call `PvNode` with `cutNode` set to false.
> 
> ```c++
> assert(!(PvNode && cutNode));
> ```

**Comment by Sopel97** [comment]
please rewrite this PR to avoid double negation and give a meaningful name instead of `allNode`

**Comment by cj5716** [comment]
allNode _is_ the right name for the predicted node state, though?

**Comment by Sopel97** [comment]
all what?

**Comment by PGG106** [comment]
the node is an all-node, wdym all what? it's just All

**Comment by Sopel97** [comment]
it's clearly not an all node, it's a not pv and not cut node

**Comment by PGG106** [comment]
if you go by knuth node types, nodes are either pv, cut or all, if it's not pv nor cut and as you suggest it's not an all-node either, then you need a 4th new node type.

**Comment by Sopel97** [comment]
I was not aware of this nomenclature. What a terrible name.

**Comment by PGG106** [comment]
they are very old (and dare i say outdates) names
cpw link: https://www.chessprogramming.org/Node_Types#ALL

**Comment by Sopel97** [comment]
I'd rather name them failLowNode because the reason why they are named "all" is not true in stockfish

**Comment by cj5716** [comment]
my preferred naming would be predictedCutNode and predictedAllNode

**Comment by peregrineshahin** [comment]
> my preferred naming would be predictedCutNode and predictedAllNode

But you would need to also do, predictedPvNode as I pointed out earlier, the context of the fact that we are actively searching and these does not represent the final tree state of the same node is obvious... we are working with a chess engine, we can't know future before it happens....

**Comment by peregrineshahin** [comment]
i.e. Knuth's type system refers to the types of nodes after the proof is established (no search going on) and yet no body ever conplained why we call a PvNode as is while in the next iteration it could be changed to some other state/type, because we are indeed continually changing the PVs.

**Comment by cj5716** [comment]
I don't think SF's PV node follows the Knuth definition, because we explicitly disallow "PV" aka "not-from-zero-window" nodes from being predicted cut nodes with an assert even though a predicted cut node can also be from non-zero-window

Idk

**Comment by peregrineshahin** [comment]
Stockfish doesn't follow Knuth's type system for any node not because of that but because it's useless in the context of chess engines.

that's mixing dd's work with regards to LMR cutNodes and general math/abstract stuff knuth refered to.

DD explained that his classification does not reflect the abstract final view of the tree and falls under the engineering work only.

The Knuth talk is about tree.
The Stockfish and DD idea is about search.

**Comment by cj5716** [comment]
right, so we use predictedPvNode because we predict it will be exact (hence doing full window search). I get your reasoning now

**Comment by peregrineshahin** [comment]
Yes, predicting that the node will be in the final principle variation of the "proof".

**Comment by vdbergh** [comment]
It is not Don Dailey's definition. The node classification occurred in much older engines, e.g. GnuChess 5 http://ftp.gnu.org/pub/gnu/chess/gnuchess-5.07.tar.gz . What DD did is to observe is that the node classification works nicely with PVS since it will automatically correct certain errors caused by pruning. I see no point really in changing the current simple definition - with has some nice theoretical properties - unless Elo gain can be demonstrated.

**Comment by peregrineshahin** [comment]
> It is not Don Dailey's definition. The node classification occurred in much older engines, e.g. GnuChess 5 http://ftp.gnu.org/pub/gnu/chess/gnuchess-5.07.tar.gz . What DD did is to observe is that the node classification works nicely with PVS since it will automatically correct certain errors caused by pruning. I see no point really in changing the current simple definition - with has some nice theoretical properties - unless Elo gain can be demonstrated.

There is no changing of definitions in this PR though, it follows the DD definitions which if you don't change the naming of some people might find wrong and confusing because it is theoretically incorrect as it is just a predicting flag as DD pointed out.
That being said, since we are in the context of a `searcher` we don't need to be precise in the naming.

**Comment by xu-shawn** [comment]
Why is @EarlyEdition no longer blocked in this repo? Did he make a new account or something? He is no longer on my blocklist either.

**Comment by peregrineshahin** [comment]
We don't do parallelism with tree splitting instead only the hashtable is shared between threads.
what you keep suggesting is what the PR already has.
You criticize Knuth's definition which is the only correct definition as outdated and link me ancient SF code?
Expressing opinions is one thing, trolling/negative IQ is another.

**Pull request closed without merging**
