### PR TITLE
Simplify backward pawns scoring

### PR DESCRIPTION
**Pull request by lucasart**
**STC**
```
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 52322 W: 10011 L: 9945 D: 32366
```
**LTC**
```
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 14143 W: 2334 L: 2203 D: 9606
```
bench 7976423

### CODE REVIEW

**Comment by Krando** [comment]
This is stupendous! Costalba, who himself is the undisputed master of simplification, faces a serious threat from Braesch to a crown that he has held since the days of Romstad.

**Comment by locutus2** [comment]
Congrats for this simplification!

**Comment by zamar** [comment]
approved.

**Comment by Krando** [comment]
Mind my indulgence, but why hasn't this yet been accepted?

**Pull request closed without merging**
