### PR TITLE
Mobility+outpost3

### PR DESCRIPTION
**Pull request by joergoster**
New values for Mobility and Outposts.
Both are the result of a SPSA tuning session with a custom book, 50k iterations each.

Passed STC
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 57644 W: 11805 L: 11431 D: 34408

and LTC
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 69138 W: 11698 L: 11323 D: 46117

After an additional tuning session of the mobility values, tuning the delta values, with following result.
40k games at 9+0.05:
ELO: 4.13 +-2.2 (95%) LOS: 100.0%
Total: 40000 W: 8581 L: 8106 D: 23313

and LTC
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 36518 W: 6049 L: 5782 D: 24687

bench: 8567402

### CODE REVIEW

**Comment by glinscott** [comment]
Awesome!  Looks good.

**Comment by locutus2** [comment]
Congrats! Nice to see another succesful patch!

**Comment by mcostalba** [comment]
Congrats! Always nice to see a successful tuning patch, not easy because
that area has already been tuned to death along many years :-)

**Comment by zamar** [comment]
approved. Will be merged in the near future.

**Comment by jhellis3** [comment]
Err... could this patch be retested with more logical Queen mobility values.

EX: Current Patch:   16, 26, 26, 26, 15, 20, 21, 22, 23
       Logical Patch:   16, 19, 19, 20, 20, 20, 21, 22, 23

And instead of 30, 43, 38..... 30, 38, 38

**Comment by zamar** [comment]
Good point.

Why do queen mobility values look like that? Is it a mistake or intentional?

**Comment by joergoster** [comment]
Thanks. Indeed, it's not easy to improve upon existing values.

@jhellis3 @zamar Only because these values don't meet your expectations, they are illogical? Do you really think, the values must steadily increase with higher mobility?
But I admit, at first I was also a bit surprised ... ;-)

Here https://github.com/joergoster/Stockfish/commit/6db3aa7693afb7a631a773cf96a02bbb80494843 you can find the original values obtained from SPSA. As you can see, I already 'normalized' the values for higher mobility.

When is the queen the strongest? When it has highest mobility, which can obviously be only the case on an empty or almost empty board? I don't think so.
The queen must have sufficient mobility, while being able to defend our own pieces, and attacking as many opponent's pieces as possible at the same time. I think this is a reasonable explanation why we see this kind of local maximum with a mobility of 7. It's also possible that other eval terms kick in at this point like threats, king attacks, etc., which might also result in a lower weight of mobility.

Anyways, everybody is free to submit their own tests and trying to improve further.

**Comment by zamar** [comment]
@joergoster: 

I'm afraid: I think that the most likely explanation for those lower queen mobility values is 'random noise'.

We should try first to make those values to follow the standard pattern and see if the test still passes...

I'm not happy to introduce such 'oddities' in SF's codebase until there is no other choice.

**Comment by joergoster** [comment]
@zamar OK, I will submit a new test later in the afternoon with further normalized values.

**Comment by locutus2** [comment]
For such parameter sequences like mobility where the values should increasing perhaps its better 
to tune the differences of the values. So you could set zero as lower bound and get an increasing sequence for the original values.

**Comment by joergoster** [comment]
@locutus2 Nice idea. Maybe I will try this out of curiosity to see, where this leads to.

**Comment by DU-jdto** [comment]
@joergoster But in such cases it's not that the extra mobility is bad in and of itself, but rather that the other features that you describe are lacking. As such, it would seem to me that the conceptually correct approach would be to have a monotonic mobility evaluation and to account for other important factors elsewhere in the evaluation.

**Comment by mcostalba** [comment]
@locutus2 The way parameters are defined can surely influence tuning success. Tuning the difference as you suggested could be an option (this take care of the previous value, but not of teh next), a generalization, for monotonic sequences would be tuning at "slices" that takes care also of teh next value, I will write a post on the forum...

**Comment by joergoster** [comment]
@zamar I have just pushed a final test at LTC with updated values. I think you can delete the old one now. Thanks.

**Comment by zamar** [comment]
@joergoster: Your new mobility test passed. Please make sure that this pull request is up to date, so that we can merge.

**Comment by joergoster** [comment]
@zamar Initial comment updated, should be fine for merging. Thanks.

**Pull request closed without merging**
