### PR TITLE
Small clean-up, April 2021

### PR DESCRIPTION
**Pull request by snicolet**
Start with an empty commit

### CODE REVIEW

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1085 - proposition to change comment to "continuation history based pruning" since countermove heuristic has nothing to do with it and also it uses followup move history.
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1631 - same there
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1050 - rename variable into smth more suitable. ceiledPvNode (?)

**Comment by snicolet** [comment]
do_null_move()/undo_move_move() in https://github.com/official-stockfish/Stockfish/pull/3419https://github.com/official-stockfish/Stockfish/pull/3419

**Comment by snicolet** [comment]
Add Douglas Matos Gomes in the AUTHORS file (see https://github.com/official-stockfish/Stockfish/pull/3427)

**Comment by mstembera** [comment]
Line 58 in thread.h
```int id() const { return idx; }```
should change to
```size_t id() const { return idx; }```
to fix MSVC warning "thread.h(58): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data".

**Comment by pb00068** [comment]
Pull #3458 removed the only usage of pos.see_ge() moving pieces that don't belong to the side to move.
Thus now also the implementation of see_ge can be simplified by replacing line 1081
`Color stm = color_of(piece_on(from));`
with
`Color stm = sideToMove; `

**Comment by pb00068** [comment]
The comment in parenthesis '**except the king**' in position.cpp line 1095
```
// Don't allow pinned pieces to attack (except the king) as long as
// there are pinners on their original square.
```
 is an remnant of an implementation (see #808) where we needed a special condition regarding the king
`if ( captured != KING` 
 preventing the king from moving into check (capturing into a checked square).
It should be removed.

Background:
At that time the king handling was based on the content of stmAttackers.
Now the king is handled relaying on attackers instead of stmAttackers,
so the special condition captured != KING is not needed anymore.

**Comment by xoto10** [comment]
evaluate.cpp line 930
```
-    // If scale factor is not already specific, scale down via general heuristics
+    // If scale factor is not already specific, scale up/down via general heuristics

```

**Comment by xoto10** [comment]
As mentioned near the top of this PR.
 
evaluate.cpp line 1201:
```
-     << "    Winnable | " << Term(WINNABLE)
+     << " Win Scaling | " << Term(WINNABLE)

```
or alternatively:
```
-     << "    Winnable | " << Term(WINNABLE)
+     << "  Win / Draw | " << Term(WINNABLE)

```

**Comment by BM123499** [comment]
On Makefile, the line 100 can be merged with previous one:
https://github.com/official-stockfish/Stockfish/blob/b62af7ac1e78c1b35103dfe6110201d0b810aee0/src/Makefile#L99-L101

As well in line 844:
https://github.com/official-stockfish/Stockfish/blob/b62af7ac1e78c1b35103dfe6110201d0b810aee0/src/Makefile#L843-L845

**Comment by Sopel97** [comment]
https://github.com/official-stockfish/Stockfish/commit/58054fd0fa6294510fc8cf76b0ba9673d5094c10#r50684713

**Comment by snicolet** [comment]
after the simplifications the line numbers have changed, so I can't find the comments/variables anymore (if still relevant)

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1028
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1531
this are relevant and comments should be changes - both of this heuristics have nothing to do with countermoves heuristic and are continuation history based pruning in fact.

**Comment by snicolet** [comment]
Closed via f90274d8ce1aad4ad0595aacbceb74b6cbe306a8, thanks everybody!

@dsmsgms I've added your name to the AUTHORS file 🙂
@Sopel97 I've used Stockfish's coding style for export_net() 🙂

**Pull request closed without merging**
