### PR TITLE
Big king safety 2

### PR DESCRIPTION
**Pull request by locutus2**
All king safety related terms (shelterweakness, stormdanger, attackunits, ..) was tuned together. Additionally for attack units a finer granularity (factor 4) is used.

STC
ELO: 9.22 +-3.1 (95%) LOS: 100.0%
Total: 19514 W: 4340 L: 3822 D: 11352

LTC
LLR: 2.96 (-2.94,2.94) [0.00,6.00]
Total: 6399 W: 1192 L: 1056 D: 4151

Bench: 8224782

### CODE REVIEW

**Comment by Karlon** [comment]
That is just amazing!

**Comment by mcostalba** [comment]
Congratulations again!

One technical comment: I have reviewed all the parameter changes and there
are no big changes apart from attackUnits minimum that jumps from 20 to 77!

So, before applying your patch, I did a

dbg_hit_on(attackUnits < 0);

Just before accessing KingDanger[] array and to my surprise I got 36% !!!

It means that in 2.407.264 cases out of 6.520.342 the information in
attackUnits  is lost due to std::max(std::min(attackUnits, 99), 0)

So I guess there was a possible huge hidden bug in king safety: we were
discarding all the information calculated in 36% of cases!

**Comment by mcostalba** [comment]
This makes me also think that perhaps the dynamic range of KingDanger[]
array is too limited, IOW only 100 possible values perhaps are too few and
we should make it bigger...

**Comment by Karlon** [comment]
The developers of Komodo will surely be keeping an intrigued eye on this stupendous discovery!

**Comment by locutus2** [comment]
@marco
for the new king safety patch i get even a higher value of 43% (on bench). Their are only two sources of negative attack units: shelter score and missing attacking queen. I think especially the latter skew this result. I measured the same for positions with attacking queen (28%) and without attacking queen (77%). So in an queenless game we have a high chance no penalty from attak units is applied.

The maximum of the kingAttackerWeights is not increased, because i have scaled the attack units by factor 4. The old value would be 80, so its slightly decreased. The really interresting are the KingAttackerWeights (the old values scaled rough (rounded) to the new one, factor ~ 2):

        knight bishop rook queen
old   4        4          6      10         
new 6         2          5      5

So the knight get an 50% increase in weight, the rook a slightly increase and bishops and queens weight is reduced by 50 %.

Also bishop and queen checks bonus are reduced. Knight and rook checks instead are increased.

So overall it seems knight and rook was in old king safety undervalued and bishop and queen overvalued.

Further interesting is the penalty for undefended squares is raised from 3*4=12 to 19 (+58).

I think with the king danger array you are right. I had thinking before my tuning myself about this, but i wouldn't make run more complicate.

**Comment by locutus2** [comment]
Sorry, the rook king attacker weight is a little bit decreases not increased.

**Comment by mcostalba** [comment]
@Stefan 
Interesting analysis. Actually your comment bewteen queen and queenless games made me remember of this important parameter that is correated somehow:

    // Init king safety tables only if we are going to use them
    if (pos.non_pawn_material(Us) >= QueenValueMg)

Actually the whole king safet is skipped if the _attacking_ side is without Queen-equivalent pieces.

**Comment by zamar** [comment]
@mcostalba:

issue1: 20 -> 77, but we divide attackunits by 4 before applying. So the change is actually minimalistic, right?

issue2: dbg_hit_on(attackUnits < 0) has 36% hit right. I think that this is expected. Opponent has no attack, but we have perfect shelter, so we get a negative value. The value of his attack is zero. For me this makes perfect sense...

**Comment by zamar** [comment]
Patch approved.

**Comment by glinscott** [comment]
Wow, congratulations!!  Great job :).  Approved.

**Pull request closed without merging**
