### PR TITLE
Candidate passed pawns

### PR DESCRIPTION
**Pull request by locutus2**
Detect safe candidate passers.

STC: http://tests.stockfishchess.org/tests/view/5882395c0ebc5915193f78b3
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 53569 W: 9925 L: 9570 D: 34074

LTC: http://tests.stockfishchess.org/tests/view/5882b4fb0ebc5915193f78e2
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 77576 W: 10387 L: 10014 D: 57175

Bench: 5325829

### CODE REVIEW

**Comment by locutus2** [comment]
Some Travis CI on linux builds fails.
`The command "if [[ "$COMPILER" == "g++-6" ]]; then make clean && make ARCH=x86-64 sanitize=yes build > /dev/null && ../tests/instrumented.sh --sanitizer; fi" exited with 0.

Done. Your build exited with 1.`

I have no linux system, so can somebody look at this.

**Comment by Rocky640** [comment]
Just to further clarify.

!(stoppers ^ lever ^ leverPush)

is parsed as
!((stoppers ^ lever) ^ leverPush)

and is equivalent to 
!((stoppers ^ (lever | leverPush))

I prefer the last one for readability, but once we get used to it, current code is probably just fine.

**Comment by snicolet** [comment]
Exclusive-or is associative: https://en.wikipedia.org/wiki/Exclusive_or

**Comment by vondele** [comment]
@locutus2 the failing bit in travis CI is (look for the red lines):

signature mismatch: reference 6406285 obtained 5325829

With the current scheme of extracting the bench in the travis script it must be part of the git commit messages, not just the pull request comments.

**Comment by locutus2** [comment]
@vondele 
Thank you, i commited the bench in a message and now the tests are passed.

**Comment by mcostalba** [comment]
Merged with 471f7a1b5c4da03a7

**Pull request closed without merging**
