### PR TITLE
Time is not a global

### PR DESCRIPTION
**Pull request by vondele**
only mainThread needs Time, keep it there.
Removes dependency of timeman on thread.
Removes duplicated startTime.

No functional change.

### CODE REVIEW

**Comment by mstembera** [comment]
I recently tried a local patch(that didn't work out but) used the helper threads to check and stop time when any one of them reached a new global max depth.  Continuing to allow that leaves the possibility of not having the main thread be special in the future which would be really nice.

**Comment by vondele** [comment]
@mstembera I agree that it would be an interesting design of not having the main thread special in the future. To do that properly (well defined, no races) that needs quite careful design. While global variables make quick hacks possible, they are usually in the way of a good (re)design. I think it is better to make really clear in the code structure what the main thread is doing differently, so that an eventual redesign becomes easier.

As a side note, I've not rebased this patch yet, because I think #1214 is the better variant.

**Comment by mcostalba** [comment]
@vondele I think that setting up the available time and checking it during the search are 2 different task and also by design should remain split.

Compute available time given search limits is a well defined, closed and isolated functionality that makes sense to be implemented in a dedicated class, designed just for this. Indeed compute available time has nothing to do with the logic and design of a search Thread that instead aims at searching,  dealing with the dynamics along the search (Time is setup just once at the beginning of the search). Checking for available time during search it is different and makes sense to be done by threads. In our implementation only main thread does this, and actually check_time() is a MainThread member.

I would not change current share of duties because I think it is what makes more sense from a design point of view.

**Comment by mcostalba** [comment]
When I read

`mainThread->time.elapsed()`

I feel there is something wrong here. Why thread? Time elapsed is a thread property? And the other threads do not elapse time?

No, really, Time is a traversal property of the Search as a whole, it is not in the Thread playing field. Thread is just instrumental in checking it and stop the search just because it _is_ the only entity with dynamic behavior that do search.

**Comment by vondele** [comment]
admittedly the patch is not yet optimal. However, note that time.elapsed is a bit a misleading name, as it can be milliseconds, but also nodes (so timeman depends on threads). It is more 'resources_consumed' and that is being monitored by the mainThread. Right now only the mainThread takes any decisions related to time(resources), so why not make that clear.

However, I'll close this variant of the patch since I anyway like the other more.

**Pull request closed without merging**
