### PR TITLE
Adding warning for unknown tokens `setoption token option `

### PR DESCRIPTION
**Pull request by LovelyChess**
Sometimes we may accidentally use this code to clear the hash, but we do not get any warning.
 `setoption Clear Hash`

### CODE REVIEW

**Comment by MinetaS** [comment]
There are no reasons to add a specialized case. Missing options are handled in one single, comprehensive way.

https://github.com/official-stockfish/Stockfish/blob/8d3457a9966f8c744ab7f8536be408196ccd8af9/src/uci.cpp#L112-L116

**Comment by MinetaS** [comment]
Also, UCI protocol defines that `setoption` must have `name` field.
No reason for chess engines to handle commands without `name`.

```
* setoption name <id> [value <x>]
                this is sent to the engine when the user wants to change the internal paramters
```

**Comment by LovelyChess** [comment]
```cpp
    if (Options.count(name))
        Options[name] = value;
    else
        sync_cout << "No such option: " << name << sync_endl;
```

@Minetas , when we use unknown field in stockfish then we receive a warning, its defined by stockfish authors a long time ago

For example, NNUE:

```
setoption NNUE value 0
No such option
```

But we do not get any warning for clear hash:

`setoption Clear Hash`

**Comment by vdbergh** [comment]
Nitpicking the "No such option" error when there is no name is also a violation of the UCI protocol. It should be "info string No such option".

**Comment by LovelyChess** [comment]
Thanks @vdbergh  , I think It should be  like this code , correct ?

 ```cpp
   if (Options.count(name))
        Options[name] = value;
    else
        sync_cout << "info string No such option"<< sync_endl;
```

**Comment by LovelyChess** [comment]
I added vdbergh suggestion to this pull.  Thanks @vdbergh 

_Example 1_
```
setoption Use NNUE
Info string no such option: Use
No such option: NNUE
```

_Example 2_
```
setoption Clear Hash
Info string no such option: Clear
```

**Comment by Craftyawesome** [comment]
> I want from @Craftyawesome to compare this.

I'm not a maintainer or even contributor. IDK why you want me in particular. Also IDK the stance of the actual devs/maintainers on more error correction.

With that said, it feels wrong to have Info string on only one of the errors, even though you only added one. I don't know what UCI mandates here. I would also prefer a more specific message. And having two error messages is strange, maybe wrap the rest in that if or break. Also you are too indented.

**Comment by LovelyChess** [comment]
> I would also prefer a more specific message. And having two error messages is strange

Thanks, I agree with you that the message should be specific, but I think it is not strange to have two errors.

I added specific message to this pull.

```
setoption Use NNUE value 0
No such token: Use
No such option: NNUE
```

**Comment by chess-com** [comment]
> Nitpicking the "No such option" error when there is no name is also a violation of the UCI protocol. It should be "info string No such option".

`info string` Almost used in the **ChessBase** engine 
```
info string License is valid
Don Dailey, Larry Kaufman and Mark Lefler
using hardware POPCNT

setoption name thread value 4
info string thread not recognized
```

It's better to choose a special message for **Stockfish**  ⚡

**Pull request closed without merging**
