### PR TITLE
Cluster merge master12

### PR DESCRIPTION
**Pull request by vondele**
Merge branch 'master' into clusterMergeMaster12
    
    fixes minor merge conflicts
    
    looks good:
    
    Score of cluster vs master: 15 - 1 - 134  [0.547] 150
    Elo difference: 32.5 +/- 17.5, LOS: 100.0 %, DrawRatio: 89.3 %
    
    for 4 threads against 4x4 threads at 10+0.1s

### CODE REVIEW

**Comment by snicolet** [comment]
Github says there are still some conflicts?

**Comment by vondele** [comment]
Not here, strangely. I can look at it tonight.

**Comment by snicolet** [comment]
I have followed the hints for command-line merge provided by Github, and the resulting branch for me is https://github.com/snicolet/Stockfish/commits/cluster

This compiles fine on my system, but obviously I don't have a MPI compiler suite.

If you can try this branch tonight and double-check that 
(1) it compiles OK for you
(2) it is the intended code

I would force-push this branch to replace the official-stockfish/cluster branch :-)

**Comment by vondele** [comment]
I will do so tonight, it looks right. 

It should be rather easy to test on your Mac as well.
```
brew install mpich
make clean && make -j ARCH=x86-64-avx2 build COMPILER=mpicxx
mpirun -np 4 ./stockfish bench
```
(assuming you have brew and xcode installed)

**Comment by vondele** [comment]
your branch works for me

**Comment by snicolet** [comment]
Merged via 43c887d3672617d939b01b6af6aec767dbe1ba55, thanks! :-)

**Pull request merged**
