### PR TITLE
Assorted trivial cleanups 4/2019

### PR DESCRIPTION
**Pull request by mcostalba**
Restore a bunch of #include <algorithm>

We include headers in files that use them, we
don't rely on indirect including.

No functional change.

### CODE REVIEW

**Comment by ElbertoOne** [comment]
Note: on line 934 of search.cpp a space can be added between "else if" and the brace "("

**Comment by joergoster** [comment]
In bitbase.cpp, do we want to extend/clarify the comment in line 30?
`  // There are 24 possible pawn squares: the first 4 files and ranks from 2 to 7`

by changing to
```
  // There are 24 possible pawn squares: files A to D and ranks from 2 to 7.
  // Positions with the pawn on files E to H will be mirrored before probing.
```

**Comment by joergoster** [comment]
Change the comment in lines 378/379 in bitboard.h regarding frontmost_sq() and backmost_sq() to
```
/// frontmost_sq() and backmost_sq() return the most/least advanced square in the given bitboard
/// corresponding to the most/least significant bit relative to the given color.
```
which seems to be a bit more precise.

**Comment by mstembera** [comment]
Since KingFlank[FILE_NB] on line 37 in bitboard.cpp is fully initialized at compile time it could be constexpr as in
```C++
constexpr Bitboard KingFlank[FILE_NB] = {
```

**Comment by mstembera** [comment]
semiopen_file() on line 43 in pawn.h should probably return bool instead of int.  Also line 359 in evaluate.cpp then no longer needs to cast the result to bool.

**Comment by mcostalba** [comment]
Thanks, updated.

**Comment by protonspring** [comment]
The KingFlank to constexpr is in my constexpr PR.

**Comment by protonspring** [comment]
The PopCnt16 arrays is not used if USE_POPCNT is defined.  However, the array is still initialized regardless.  Thus, if we're using USE_POPCNT, this array is just sitting here, wasting memory (64kb).  Wouldn't it be better to wrap the declaration (bitboard.h), instantiation, and initialization (bitboard.cpp) with #ifndef USE_POPCNT, #endif ?

**Comment by protonspring** [comment]
The rank_bb and file_bb methods in bitboard.h are simple enough to be one liners like the distance methods.

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp#L778
&& pos.non_pawn_material(WHITE) == BishopValueMg
&& pos.non_pawn_material(BLACK) == BishopValueMg
can be replaced with pos.non_pawn_material() == 2 * BishopValueMg
less lines, same logic (we already check that it's pos.opposite_bishops() so this 2 bishops can't be on the same side), doesn't hurt readability, one less comparison so a tiny speedup.

**Comment by protonspring** [comment]
Extra line in movegen.cpp, line 221.

**Comment by Rocky640** [comment]
evaluate.cpp line line 189, comment is no longer exact after #2074


might be changed for
    // attackedBy2[color] are the squares attacked by at least 2 units of a given color,
    // including some x-rays. But diagonal x-rays through pawns are not computed.

**Comment by mcostalba** [comment]
Thanks. Updated.

**Comment by joergoster** [comment]
Clarify the comment of the qsearch() function.

```
  // qsearch() is the quiescence search function, which is called by the main
  // search function with depth zero, or recursively with depth less than ONE_PLY.
```

The last part is quite misleading because depth is ALWAYS less than ONE_PLY, no matter if qsearch() is being called from the main search or recursively!

Better change to something like
```
  // qsearch() is the quiescence search function, which is called by the main search
  // function with zero depth, or recursively with further decreasing depth per call.
```

**Comment by Rocky640** [comment]
pawns.cpp line 170 needs better spacing.

**Comment by protonspring** [comment]
I don't think pawns.h needs to include "types.h"

**Comment by mstembera** [comment]
Line 318 in position.h of advanced_pawn_push(Move m)
could be changed from
```C++
        && relative_rank(sideToMove, from_sq(m)) > RANK_4;
```
to
```C++
        && relative_rank(sideToMove, to_sq(m)) > RANK_5;
```
because to_sq() performs fewer operations than from_sq().  This is non functional.

**Comment by Rocky640** [comment]
According to #2090  discussion, using the ternary operator is not a problem
In evaluate.cpp we can replace
```
 if (bb & s)
                score += Outpost * (Pt == KNIGHT ? 4 : 2)
                                 * (1 + bool(attackedBy[Us][PAWN] & s));

            else if (bb &= b & ~pos.pieces(Us))
                score += Outpost * (Pt == KNIGHT ? 2 : 1)
                                 * (1 + bool(attackedBy[Us][PAWN] & bb));
```

with

```
 if (bb & s)
                score += Outpost * (Pt == KNIGHT ? 4 : 2)
                                 * (attackedBy[Us][PAWN] & s ? 2 : 1);

            else if (bb &= b & ~pos.pieces(Us))
                score += Outpost * (Pt == KNIGHT ? 2 : 1)
                                 * (attackedBy[Us][PAWN] & bb ? 2 : 1);
```

**Comment by mcostalba** [comment]
Thanks. Updated

**Comment by protonspring** [comment]
In pawns.cpp, BlockRanks doesn't need to depend on Color because it's not possible for a WHITE king to be on Rank7 or 8 and block an enemy pawn.

constexpr Bitboard BlockSquares = (Rank1BB \| Rank2BB \| Rank7BB \| Rank8BB) & (FileABB \| FileHBB);

Then, 
-  Value safety = (shift(theirPawns) & (FileABB \| FileHBB) & BlockRanks &  ksq)
+ Value safety = (shift(theirPawns) & BlockSquares & ksq)

**Comment by MichaelB7** [comment]
ucioption.cpp has quite a few double blanks rows: 

52-53
81-82
108-109
142-143
153-154

It appears to be hit and miss when looking at other files, let me know if they should be removed and I'll check them all.

**Comment by Rocky640** [comment]
in evaluate.cpp, line 674 should read
`} // r > RANK_3`

**Comment by Rocky640** [comment]
in pawns.cpp, line 169 is missing a space before the =

**Comment by protonspring** [comment]
This is more my preference than anything. . If we add a few constructors to the ExtMove enum:
\+ ExtMove() {}
\+ ExtMove(Move m) : move(m) { }

We can simplify a MovePicker constructor:
\- refutations{{killers[0], 0}, {killers[1], 0}, {cm, 0}}
\+ refutations{killers[0], killers[1], cm}

This is a bit more code, but it's MUCH easier to read.

**Comment by adentong** [comment]
pawns.h line 41 there is an extra semi-colon at the end

**Comment by mstembera** [comment]
To be consistent with line 862 in position.cpp should we not also add
```C++
prefetch2(thisThread->pawnsTable[st->pawnKey]);
```
after line 790?

**Comment by 31m059** [comment]
In `Evaluation::king()`, we have two different accesses to `KingFlank[file_of(ksq)]` (line 461, line 482).  It probably makes slightly more sense to only perform the array access once:

`const Bitboard flank = KingFlank[file_of(ksq)];`

and use this multiple times as needed.

**Comment by mcostalba** [comment]
Thanks, updated!

@MichaelB7 Thanks for pointing out. Usually we use double space before a /// and single before a //, but it really depends on context. I would leave it as is.

@protonspring any ExtMove c'tor forces movelist array in MovePicker to be initialized before to be used and we really don't want it (we just use a small part of it).

@31m059 I doubt it makes any difference, the compile should already optimize it and even if not it is anyhow hot cached the second time it is used. I avoid to use temporary variables just to speed up things, because the compiler already does that job for us.

**Comment by protonspring** [comment]
Pawns.cpp, line 100, we can save an operation by changing:

phalanx = neighbours & rank_bb(s) 

TO

phalanx = neightbours & rank_bb(r)

**Comment by mstembera** [comment]
@mcostalba I'm not against removing prefetch2() but since it could be a slowdown I started
http://tests.stockfishchess.org/tests/view/5cbfa0f00ebc5925cf028947
to make sure.

**Comment by protonspring** [comment]
Pawns.cpp, lines 80-81.  There are extra spaces in the assignments.

**Comment by joergoster** [comment]
In search.h, can we drop 'perft' from bool use_time_management?
```
  bool use_time_management() const {
    return !(mate | movetime | depth | nodes | perft | infinite);
  }
```
We immediately return after calculating perft numbers, so we never get to call `use_time_management()` in that case.

**Comment by joergoster** [comment]
If we also zero-initialize `int tbRank = 0;` in our RootMove struct, we can delete
```
    else
    {
        // Assign the same rank to all moves
        for (auto& m : rootMoves)
            m.tbRank = 0;
    }
```
at the end of `Tablebases::rank_root_moves()`.

**Comment by mcostalba** [comment]
Merged with 4e72e2a96475461

**Pull request closed without merging**
