### PR TITLE
Further simplify unstoppable

### PR DESCRIPTION
**Pull request by joergoster**
by finally moving it into passed pawns eval.

Tested for no regression:
STC
LLR: 3.25 (-2.94,2.94) [-3.00,1.00]
Total: 57109 W: 10023 L: 9947 D: 37139

LTC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 21511 W: 2800 L: 2680 D: 16031

Bench: 5255881

### CODE REVIEW

**Comment by Rocky640** [comment]
Many small steps were required to make this work, 
a) the recent work by jcalovsky (removing the scoring by relative rank)
b) testing the removal of this code (it was clearly red)
c) testing if the condition npm(Us)+npm(Them)==0 (pawn only endgame)
   could be improved for something else
d) testing to give a bonus to each passed pawn, instead of a one time bonus for having some passed pawns
e) choosing to score also the pawns on rank 2 or 3
f) choosing the bonus S(0, 20) instead of S(0, 45)

And probably some local tuning too...
As a bonus, seems like a small elo improvement, and this code finally moved where it belongs.

Well done Jörg !

**Comment by ajithcj** [comment]
Nice simplification. Congrats !!

**Comment by DamasClasicas** [comment]
Well done! Congratulations!!

**Comment by VoyagerOne** [comment]
Congrats as well.  Nicely done.

**Pull request merged**
