### PR TITLE
Stockfish 13 release candidate

### PR DESCRIPTION
**Pull request by vondele**
Bench: 3766422

-----

Release message to be drafted

### CODE REVIEW

**Comment by vondele** [comment]
Consider our master branch the current release candidate. We welcome additional testing.

TODOs:
- [ ] draft release message
- [ ] update CPU contributors list

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/pull/3357
I would like this to be committed before this.
This is obviously non-functional but fixes obvious description mistake - we probably don't want wrong comments to be in release (I know that this is mostly my fault :D)

**Comment by vondele** [comment]
this can be fixed after IMO. Right now, only critical changes, this is not.

**Comment by snicolet** [comment]
Top CPU contributors updated in b46813f9b74c9edcb830b32d877469ed428072ad

**Comment by noobpwnftw** [comment]
Compared to SF12, there is a 5%-20% speedup in NNUE due to specialized inference code, tiling and continuous incremental updates. Classical evaluation and hybrid method are improved to handle closed positions better and also correct some NN eval inaccuracies. Most elo gainers are from search improvements, of course, which typically wins twice as many as loses in a match against SF12.

More importantly, with this release we would have our performance on various rating lists realigned to reflect more recent comparison among derivatives and other engines which may have different release schemes.

**Comment by noobpwnftw** [comment]
Not sure if the recent full blown scam is worth mentioning, I think not, those may be settled elsewhere.

**Comment by vondele** [comment]
> Not sure if the recent full blown scam is worth mentioning, I think not, those may be settled elsewhere.

a blog entry for starters a statement on Fat Fritz 2
https://blog.stockfishchess.org/post/643239805544792064/statement-on-fat-fritz-2

**Comment by vdbergh** [comment]
Can we schedule a regression test? Previous releases (with some exceptions) have always been around 100 normalized Elo (measured with the 8 moves book). E.g SF11/SF10 https://tests.stockfishchess.org/tests/view/5e2258dd346e35ac603b7d8c amounted to a jump of 
102.99 nElo (as listed on https://tests.stockfishchess.org/tests/stats/5e2258dd346e35ac603b7d8c ).

The last regression test https://tests.stockfishchess.org/tests/stats/6000a2616019e097de3ef77d indicated a jump of 87.55 nElo of master against  SF12. So by this metric it seems we are almost there.

**Comment by vondele** [comment]
@vdbergh feel free to schedule the proper regression tests for this, using current master. I plan no functional changes any more. 

I have also seen that in normalized Elo (the proper metric IMO) we're doing very well indeed.

**Comment by vdbergh** [comment]
I scheduled the single core test. https://tests.stockfishchess.org/tests/view/602bcccf7f517a561bc49b11 but I need to run now. I did not know what are the TC and Hash size for the 8 core test so that one isn't scheduled yet.

**Comment by vondele** [comment]
The results for LTC SMP are here https://tests.stockfishchess.org/tests/view/602bd7b27f517a561bc49b1e 
Looking good IMO, nElo of about 90, wins about 6 times more game pairs than it loses against SF12...

**Comment by mstembera** [comment]
Why release now before reaching the normal 50 elo gain?

**Comment by vondele** [comment]
This will become clearer with the release notes, but the above mentioned blog entry is related.

**Comment by vondele** [comment]
OK, I have the final link for the release notes: https://lichess.org/blog/YCvy7xMAACIA8007/fat-fritz-2-is-a-rip-off

expect a release tomorrow if all goes well.

**Comment by osteslag** [comment]
> …the final link for the release notes: https://lichess.org/blog/YCvy7xMAACIA8007/fat-fritz-2-is-a-rip-off

As madenning as the rip-off is, that link is hardly the *release notes* for Stockfish 13, is it?

**Comment by noobpwnftw** [comment]
> > …the final link for the release notes: https://lichess.org/blog/YCvy7xMAACIA8007/fat-fritz-2-is-a-rip-off
> 
> As madenning as the rip-off is, that link is hardly the _release notes_ for Stockfish 13, is it?

It would likely to be a link which will be included in the release notes.

**Comment by Technologov** [comment]
Please make sure it compiles on non-SSE 32-bit processor; such as AMD Athlon (x86 & MMX code only) and 32-bit binaries are released and can work on it. Thanks !

**Comment by snicolet** [comment]
If you have access to such systems, could you please compile them for us? thanks in advance :-)

**Pull request merged**
