### PR TITLE
Update default net to nn-56a5f1c4173a.nnue

### PR DESCRIPTION
**Pull request by SFisGOD**
SPSA 1: https://tests.stockfishchess.org/tests/view/60fd24efd8a6b65b2f3a796e
Parameters: A total of 256 net biases were tuned (hidden layer 2)
New best values: Half of the changes from the tuning run
New net: nn-5992d3ba79f3.nnue

SPSA 2: https://tests.stockfishchess.org/tests/view/60fec7d6d8a6b65b2f3a7aa2
Parameters: A total of 128 net biases were tuned (hidden layer 1)
New best values: Half of the changes from the tuning run
New net: nn-56a5f1c4173a.nnue

STC:
LLR: 2.94 (-2.94,2.94) <-0.50,2.50>
Total: 140392 W: 10863 L: 10578 D: 118951
Ptnml(0-2): 347, 8754, 51718, 9021, 356
https://tests.stockfishchess.org/tests/view/610037e396b86d98abf6a79e

LTC:
LLR: 2.95 (-2.94,2.94) <0.50,3.50>
Total: 14216 W: 454 L: 355 D: 13407
Ptnml(0-2): 4, 323, 6356, 420, 5
https://tests.stockfishchess.org/tests/view/61019995afad2da4f4ae3a3c

Closes https://github.com/official-stockfish/Stockfish/pull/3633

Bench: 4801359

### CODE REVIEW

**Comment by SFisGOD** [comment]
@vondele It would be nice to merge this as soon as possible :)

**Comment by MichaelB7** [comment]
Congrats again, you are the net master!

**Comment by jhellis3** [comment]
Truly remarkable. Congrats! :)

**Comment by lp--** [comment]
LTC test should be purged. p-value is too high

**Pull request closed without merging**
