### PR TITLE
Simplify outpost evaluation

### PR DESCRIPTION
**Pull request by lucasart**
**STC**
```
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 114149 W: 21986 L: 22032 D: 70131
```
**LTC**
```
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 52232 W: 8468 L: 8396 D: 35368
```
bench 6716940

### CODE REVIEW

**Comment by ajithcj** [comment]
Congrats! 
Now, it may be a good idea to retune BISHOP and KNIGHT psqt(especially rank3)

**Comment by lucasart** [comment]
@ajithcj: I doubt it. PSQT is *very* well tuned, and this patch preserves approximately the same average outpose value. Maybe outpost bonuses can now be tuned successfully, but don't expect much, for outposts are worth very little elo.

**Comment by zamar** [comment]
approved.

Well done!

**Comment by ajithcj** [comment]
@lucasrt, in old system, outposts were allowed even on rank 3. 
In the new system outposts are given equal bonuses on all files from a-h.
Thats why I said some compensation may be needed in the psqt tables.

**Comment by jcalovski** [comment]
Nice one Lucas

**Comment by glinscott** [comment]
Big simplification!  Looks great :).

**Comment by lucasart** [comment]
@ajithck: why don't you do some preliminary measures with `dbg_mean_of()` ? let's discuss when you have some data.

**Pull request closed without merging**
