### PR TITLE
Deepest move

### PR DESCRIPTION
**Pull request by mbootsector**
STC: 
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 26930 W: 4441 L: 4214 D: 18275

LTC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 7783 W: 1017 L: 876 D: 5890

Bench: 8004751

Since the tests I have made a change to PV reporting, but that should not affect playing strength.

### CODE REVIEW

**Comment by glinscott** [comment]
This is a really interesting idea!!  I'm trying to think through all the implications and it seems fine.

**Comment by zamar** [comment]
I feel that I'm nitpicking on every patch, but again from SMP perspective this seems racy... There is no guaranteed synchronization across threads.

**Comment by glinscott** [comment]
@zamar - aren't we sure that all threads are done at this point?

Although I do see a potential race between completedDepth and rootMoves[0] from that thread.

**Comment by zamar** [comment]
@glinscott: Okay, you are right. The logic nowadays is that we wait for all threads to finish before printing the bestmove (in YBW it was other way around)...

This guarantees that threads are synchronized (searching atomic flag), so it should be fine from SMP perspective...

**Comment by glinscott** [comment]
Ok, there is a small race between completedDepth and the depth rootMoves[0] might be searched to, but rootMoves[0] will be strictly greater than or equal to completedDepth, so this seems fine to merge to me.

Congratulations!

**Comment by mcostalba** [comment]
Yes it is a nice idea. I am trying to  generalize it but my patch is still
buggy.

Not sure if multi pv is broken after this patch.

**Comment by mstembera** [comment]
Since multi PV is only used for analysis and reduced skill levels I think we could just put the new code inside of a  if (1 == Options["MultiPV"])  condition.

**Comment by lucasart** [comment]
@zamar @glinscott @mcostalba: can we consider this patch approved, and scheduled for merging ? I would like to test something with this as a base.

**Comment by mcostalba** [comment]
I have no problems with committing this, just please don't hack out the
multi pv case : better to leave it (temporary)  broken, eventually just add
a FIXME note.

Many people is already doing  tests above this one, so it won't remain in
this form for a long.





Oease don Monday, November 2, 2015, lucasart <notifications@github.com>
wrote:

**Comment by glinscott** [comment]
Yes, looks good to merge for me as well.

**Comment by zamar** [comment]
approved.

**Pull request closed without merging**
