### PR TITLE
Ponder shouldn't be using std::out directly

### PR DESCRIPTION
**Pull request by dpedley**
I think I found a spot where the sync_cout define wasn't being used.

### CODE REVIEW

**Comment by vondele** [comment]
I don't think this change is correct. The thread grabs the lock when it starts the line (bestmove), and only releases it when the ponder move has been printed. in between it can use a normal `std::cout`

**Comment by dpedley** [comment]
@vondele to clarify... it does look like because of the order, the code will function the same with or without the change. I'm not sure the change is incorrect though? Seems like some nice clean up to me.

I made the change in a fork to fix another problem. I was hoping to help clean up the `official-stockfish` while I was working on it.

**Comment by kuzkry** [comment]
Hi. I think this change is incorrect in the current shape as here we've got the case where [`std::ostream& operator<<(std::ostream& os, SyncCout sc)`](https://github.com/official-stockfish/Stockfish/blob/d21e421ad74cff3b157d156d6ea8fdee3634e75b/src/misc.cpp#L288) performs a double call to `std::mutex::lock()` (without releasing the mutex in between) and that's undefined behaviour.

**Comment by dpedley** [comment]
One more try, this is how I changed the flow locally to account for the locking issue.

Again this is just clean up, no functional changes.

**Comment by vondele** [comment]
Thanks, but I will stay with the current code, while different I see no significant benefit of this version.

**Pull request closed without merging**
