### PR TITLE
Use a scalable logic for reduction modifications based on history.

### PR DESCRIPTION
**Pull request by Stefano80**
Use a scalable logic for reduction modifications based on history.

Replace the current logic in which reductions can be only decreased by one ply for moves with a good history. Modify reductions based on the sum of thread and countermoves history multiplied by a factor tuned per SPSA. Further tuning of the current very small offset could lead to further ELO gain.

Passed STC:

LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 11140 W: 2117 L: 1944 D: 7079

and LTC:

LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 11155 W: 1572 L: 1416 D: 8167

Bench: 7822264

### CODE REVIEW

**Comment by Stefano80** [comment]
Thanks.

@VoyagerOne : I were going for some other simplification, so feel free to try it out.

**Comment by zamar** [comment]
@Stefano80: This patch adds 4 new constants - all of which are quite weird (17, 18, 11, 262144).

We should really try to find something simpler...

**Comment by VoyagerOne** [comment]
I agree with zamar.

We have a risk of burying our self in a local minimum.
Meaning if we ever try to tune History Stats we now need to considered four more parameters...

**Comment by VoyagerOne** [comment]
Here is a simplified formula that is very close.
(h+cmh) / 14980

**Comment by zamar** [comment]
@VoyagerOne: Yeah, Something like that looks much more manageable - Only one easily tunable constant.

**Comment by Stefano80** [comment]
I agree about one of the constants (11), which could be safely removed. The denominator 262144 is just the resolution (2^18), so I really would not bother about that. The other ones: decreasing them by 1 made the difference between failing in 100k games and passing in 11k games, so I would'nt remove them if it is not proven that is safe. If you like, I can test whether (16,16,0) also would pass and if it does, then we go with the formula proposed by VOne. Or alternatively, you commit and then I try to simplify it (I already have several attempts in mind) in different ways.
 
Two further questions:
@zamar : what dou you mean with "weird", when talking about numbers?
@VoyagerOne : you write: "We have a risk of burying our self in a local minimum." And why not with 16,16,0? which is just what you are proposing?

**Comment by zamar** [comment]
As a general rule, one should always go for the minimum number of tunable variables (i.e. minimum number of degrees of freedom).

Your formula has 4 tunable variables (or 3 if you treat 2<<18 as a resolution constant).

While formula: (h+cmh) / 14980 has only one tunable variable (= 14980).

That's why the latter is much preferable...

**Comment by zamar** [comment]
I've submitted a test to see how the simplified version does:
http://tests.stockfishchess.org/tests/view/56937c200ebc594a0871d779

**Comment by sf-x** [comment]
@zamar Why does this test (http://tests.stockfishchess.org/tests/view/56937c200ebc594a0871d779) use (0,5) bounds?

**Comment by zamar** [comment]
@sf-x: Because it's done against master...

**Comment by VoyagerOne** [comment]
@Stefano80 
The way I see it, adding a weight to history or cmh means that the way we score stats in not optimal.  (Which is definitely true)

When we score moves in move picker, it is simply m.value=cmh+h

Ideally we want to use the same score as the numerator in your formula.
Adding weights tells us that the way we score cmh and h, needs to be looked at.  As they are not in "harmony".

**Comment by Stefano80** [comment]
@zamar : the formula (h+cmh) / 14980 is actually (1*h + 1*cmh + 0) / 14980, so it has three tunable variables, exactly as mine. Actually, it is my formula with constants 16,16,0. You just dont write them because they are the identity elements of the corresponding operations.

I think the only worthy comparison would be against the (slightly changed) original formula  

if (   thisThread->history[pos.piece_on(to_sq(move))][to_sq(move)] > h_threshold
     && cmh[pos.piece_on(to_sq(move))][to_sq(move)] > cmh_threshold)

r = std::max(DEPTH_ZERO, r - reduction * ONE_PLY);

with h_threshold = cmh_threshold = VALUE_ZERO and reduction = 1. My formula is a simplification of this formula since it has the same number of constants and operators but reduces the cyclomatic complexity by 1. Furthermore, my formula is a continuous function of h,cmh as opposed to the original one.

Interestingly the patch you submitted if performing ca. the same as the LMR_history 19,18 which has approximately the same distance from the patch in my pull request, which is consistent (but should not be overinterpreted).

@VoyagerOne : I find your observation about the two cmh+h formulas not being in harmony actually very good. Bad luck Christmas holidays are over, and I have to go back to very little SF fun!

**Comment by Stefano80** [comment]
Btw: on my page it says "continuous-integration/appveyor/pr — AppVeyor build failed".

What does it mean?

**Comment by zamar** [comment]
@Stefano80:

Formula: (h+cmh) / 14980 has exactly one tunable variable... 14980

Of course you could say that the formula is identical to:

(1 * h + 1 * cmh + 0 * h *cmh + 0 * h^2 * chm + 0 * cmh ^ 2 *h + 0 * h^3 + 0 * cmh^3 + 0) / 14980,

so that it has in fact 8 tunable variables, but what's the point... It's easy to introduce pointless degrees of freedom, but difficult to keep them as few as possible...

**Comment by mcostalba** [comment]
It's an experiment I am doing to have automatic test compile also under
Windows, but it doesn't work so I will remove.

**Comment by Stefano80** [comment]
Hi Joona,

given that your even simplier version than mine performed so well, I feel too would be better to commit that. Feel free to close this, or if you think is better I commit your changes to this branch.

**Comment by Stefano80** [comment]
@mcostalba : ah ok, interesting

**Comment by Stefano80** [comment]
@zamar : I pushed your version to git.

**Comment by zamar** [comment]
I'll merge it when I get a chance...

**Pull request closed without merging**
