### PR TITLE
Extending halfdensity-map by skip-size-5 block

### PR DESCRIPTION
**Pull request by pb00068**
ELO: 1.74 +-3.5 (95%) LOS: 83.7%
Total: 10000 W: 1324 L: 1274 D: 7402 tc=10+0.1  th = 31
http://tests.stockfishchess.org/tests/view/5777d7560ebc5972faa1657b

ELO: 5.10 +-3.5 (95%) LOS: 99.8%
Total: 12000 W: 1993 L: 1817 D: 8190 tc=3+0.03  th = 31
http://tests.stockfishchess.org/tests/view/5774bd640ebc5972faa16514

### CODE REVIEW

**Comment by mcostalba** [comment]
I understand this is very resource intensive to test, but OTH just because it is resource intensive, very probably this code will never change after being merged, so better to do a deep test now once and for all. Can you please re-spin 10K games at  tc=20+0.1 th = 31?  I am worried that due to very high number of threads, very low TC and relatively low number of games  we are measuring mainly noise.

**Comment by lucasart** [comment]
But this result does not prove an elo gain:
```
ELO: 1.74 +-3.5 (95%) LOS: 83.7%
Total: 10000 W: 1324 L: 1274 D: 7402 tc=10+0.1 th = 31
```
You need to pass an `SPRT(0,X)` for that. Or, for a fixed game test, you should have `LOS > 95%`. Testing now at LTC is equivalent to respinning a failed STC. It's cheating statistics.

A better way to test is to use a larger number of games, to reduce type II error for small gains. Or, even better, to use SPRT. Maybe `SPRT(0,6)` would be the right tradeoff for these very expensive 31 threads test.

**Comment by mcostalba** [comment]
We have this slightly negative test result here:

10000 @ 30+0.3 th 7
ELO: -2.88 +-3.4 (95%) LOS: 4.6%
Total: 10000 W: 1176 L: 1259 D: 7565

It could be just noise but...

**Comment by pb00068** [comment]
The additional test asked for this pull is http://tests.stockfishchess.org/tests/view/57849a0f0ebc5972faa16881 and it take some while to finish.

The result you mention Marco is from testing a high-density approach vs. the current half-density approach. I don't know if these results give us any valuable information also about this pull request...

**Comment by mcostalba** [comment]
@pb00068 it seems we don't have clear results with increasing TC (anyhow TC still well below real games TC), so I am not so confident to apply this patch because gain is not clear at all, indeed the risk of regression is not negligible. So sorry but I am going to close this one.

**Pull request closed without merging**
