### PR TITLE
FastMove

### PR DESCRIPTION
**Pull request by mstembera**
20K
ELO: 8.22 +-3.0 (95%) LOS: 100.0%
Total: 20000 W: 4203 L: 3730 D: 12067

STC
LLR: 2.96 (-2.94,2.94) [-1.50,4.50]
Total: 23266 W: 4662 L: 4492 D: 14112

LTC
LLR: 2.95 (-2.94,2.94) [0.00,6.00]
Total: 12470 W: 2091 L: 1931 D: 8448

Spend much less time in positions where one move is much better than all other alternatives.  We carry forward pv stability information from the previous search to identify such positions.  It's based on my old InstaMove idea but with two significant improvements.
1) Much better instability detection inside the search itself.
2) When it's time to make a FastMove we no longer make it instantly but still spend at least 10% of normal time verifying it.

Credit to Gull for the inspiration.
BIG thanks to Gary because this would not work without accurate PV!

### CODE REVIEW

**Comment by glinscott** [comment]
Very impressive, congratulations!!  Nobody has managed to crack the easy move problem, even after many, many (many) tries.  And this has passed three tests.

We might want to encapsulate the FastMovePV update/check in it's own little struct/class.  Right now the code is a bit tricky to read.

**Comment by zamar** [comment]
Well done!

But how does this interact with pondering? Have you considered that?

**Comment by mstembera** [comment]
@Gary
Thanks for the praise and suggestion.  I just committed a functionally equivalent version
wrapped in its own struct.

@Joona
Thanks.  Yes, I initially disabled fast move w/ ponder on(see second patch commit) but then realized
saving time on "only" moves was still valuable of course.  I also couldn't find any conflicts in the combined logic to keep it from working properly.  Most importantly if a potential fast move becomes unstable while we're pondering it will still be detected.  Of course optimal time parameter tuning might
be different for ponder. Unfortunately, afaik cutechess doesn't support ponder to measure elo but
I did test it under the Fritz GUI and watched it play a few games w/ ponder on.  I'm by no means an expert on pondering so if you or someone else can point out a specific ponder issue please do.

**Comment by zamar** [comment]
@mstembera:

I need to analyse your code in more detail to fully understand it. I'll do it at some point this week.

The scenario I'm mostly concerned is:
- We do move (search 1)
- We start pondering a move (search 2)
- Our ponder move is wrong, so we stop, and start another search (search 3)

Is this scenario covered?

**Comment by AlexandreMasta** [comment]
This commit has to be very carefully made. We so many examples in previous TCEC when Gull made its "insta loss"  moves, because of this kind of "fast move" implementation.

**Comment by mstembera** [comment]
@Joona 
Yes that should be fine as long as each search makes a separate call to id_loop() which I believe it does.

Regarding Gull, I got my inspiration from watching it play but I never looked at its implementation so likely its very different.

**Comment by glinscott** [comment]
Thanks for doing the refactoring!  That is looking much better.

**Comment by locutus2** [comment]
Congrats! Nice to see finally a succesful easy move patch.

**Comment by joergoster** [comment]
Finally a successful easy move patch! Congrats!
Many, and I mean really many, have tried before and failed.

**Comment by zamar** [comment]
Please merge master into this branch, and run one extra quick sanity test in fishtest to prove that merge was fine...

**Comment by AlexandreMasta** [comment]
Congratz! 

I think that anyway with the awesome safeguard patch made by Joona Kiiski (a patch that negates blunders due to time restriction) committed long time ago there will be no problem with this new patch.

Cheers!

**Comment by jhellis3** [comment]
Perhaps I am missing something, but this would appear to suffer from the same problem that the old easy move code did at high depths/time controls.  It will reach a high depth due to hash, but not meet the 10% time use requirement for that iteration. Thus, it will continue that iteration (which it may not complete) using the max available time.   Either the % time condition needs to be worked around, or it needs to be allowed to cutoff the search in the middle of an iteration in order to be effective at high depths/TCs (where it is most apparent to humans).

**Comment by mstembera** [comment]
@Joona
Merged and test scheduled.

@locutus2
Thanks. Yes testing at longer TC would be interesting.
I could be just luck but at least LTC passed faster than STC.

@jhellis3
This patch doesn't care about what absolute depth is reached.  Afaik SF branching factor is around 1.5x.  Most actual verification times I measured are closer to 15% but 10% is a guaranteed minimum. If some iteration really blows up then worst case we just don't save any time on that move.  Cutting off the search in the middle of an iteration seems like a bad idea to me but in any case if this gets applied I hope you can improve it.

**Comment by jhellis3** [comment]
I understand it is depth independent, but depth is, generally, a product of time, cpu resources, and hash size.  Perhaps an example will make what I am talking about more clear.  Consider TCEC like conditions, where we have ~4 mins per move for optimal time.  That is 240 seconds, and 10% of that is 24 seconds. Now, lets say we pass through that code at 22 seconds.  Then it may be up to 1 minute or more before we make the "easy" move.  While this is much better than 4 minutes, it is still quite slow from a human perspective.  Unfortunately, that is not the worst case.  The worst case is when we don't even complete the iteration meaning that we hit the max available time limit on what we have judged to be an easy move.  To be fair this should be the case less often than the previous implementation due to the lower threshold, but I imagine it will still happen a fair amount.

Anyway, I think it is great we now have an implementation of easy move which actually gains Elo.  I just wish it we could be certain it would be consistently as effective for the perceptual side of the problem (as humans are ultimately who are using the product and watching/playing the games).

**Comment by sf-x** [comment]
Ever since Stockfish stopped taking TT cutoffs in PV nodes, reaching (previous depth - 2) is not, unlike before, near instantaneous. So @jhellis3 's problem is purely imaginary.

**Comment by mstembera** [comment]
For those still reading here is a drinking game suggested by a friend.
When you watch SF play(maybe on TCEC) whenever it makes a fast move u take a drink.
This gets more fun as clocks get low and moves are more frequent :)
Thanks for the many congratulations!

**Pull request closed without merging**
