### PR TITLE
Move King tropism code to evaluate_king

### PR DESCRIPTION
**Pull request by Rocky640**
Same bench as master...7038730

and also tested with
bench 256 1 18 default depth
the bench is 60570522, identical to master too.

### CODE REVIEW

**Comment by Rocky640** [comment]
We have a few S(0, x) and S(x, 0) defined as const, so to keep consistency, 
I also replaced the make_score(7 * popcount(b), 0);  
with CloseEnemies * popcount(b);

But curiously, the following version 
(which I prefer and which seems to me identical to this PR) 
has bench 6913129 which is different from master, 
and I fail to see why.

https://github.com/Rocky640/Stockfish/tree/MoveKingTropism

**Comment by AlexandreMasta** [comment]
Why to change something that is not broken?

**Comment by snicolet** [comment]
The different bench in the version you prefer comes from the initial estimation of attackUnits:

````
        attackUnits =  std::min(72, ei.kingAttackersCount[Them] * ei.kingAttackersWeight[Them])
                     +  9 * ei.kingAdjacentZoneAttacksCount[Them]
                     + 21 * popcount(undefended)
                     + 12 * (popcount(b) + !!ei.pinnedPieces[Us])
                     - 64 * !pos.count<QUEEN>(Them)
                     - mg_value(score) / 8;
````

The last line has `mg_value(score) / 8`, so if you modify the score before this, the bench will change.

**Comment by snicolet** [comment]
Have we some speed test for the non-functionnal-change version? In particular, I'm curious to know if the compiler optimizes `make_score( x * A, 0)` and `x * S(A ,0)` to the same thing.

**Comment by mcostalba** [comment]
Merged with 2b57b61cb1a9f

I have added a couple of assert to replace a commented part.

**Comment by mcostalba** [comment]
Thus king tropism stuff greatly overlaps with standard king safety.

I understand king tropism is a simplified for of king safety (https://chessprogramming.wikispaces.com/King+Safety#King%20Tropism) so it should be used when king safety is not used so I will submit a test along these lines, although I am not sure test will succeed because it will introduce a discontinuity when real king safety kicks in.

Anyhow I don't like this king tropism stuff so much :-)

**Pull request closed without merging**
