### PR TITLE
trivial cleanups

### PR DESCRIPTION
**Pull request by mstembera**
Credit to @protonspring from
https://github.com/official-stockfish/Stockfish/pull/2341

No functional change.
bench: 4810202

### CODE REVIEW

**Comment by adentong** [comment]
Why don't we just make this is a trivial cleanup PR

**Comment by mstembera** [comment]
@adentong I'm fine with whatever @snicolet wants to make things easier for him.

**Comment by snicolet** [comment]
evaluate.cpp, line 522: put comment on a single line

```
// Bonus for restricting their piece moves, greater when square is occupied

**Comment by mstembera** [comment]
@vondele To make it easier, should I close this PR so you can open one your self and manage it as you see fit?

**Comment by vondele** [comment]
@mstembera just leave it open for the time being... I'll either go through the comments here, or if you feel like it, you can add additional commits taken good suggestions into account.

**Comment by vondele** [comment]
@amchess : At line 716 and 725,  !PvNode is always true

**Comment by mstembera** [comment]
@vondele I did as you suggested.  However, I'm a bit confused about your last comment since it doesn't specify a file and I'm not sure how @amchess is involved?  I think these trivial cleanup PR's work smoother if owned directly by the maintainers.

**Comment by vondele** [comment]
@mstembera agreed, I've created https://github.com/official-stockfish/Stockfish/pull/2532 

I'll thus close this one...thanks!

**Pull request closed without merging**
