### PR TITLE
Assorted renaming

### PR DESCRIPTION
**Pull request by mcostalba**
Also define make_score() as constexpr to evaluate at compile
time all the bonus table defined through S() macro:

No functional change.

### CODE REVIEW

**Comment by lucasart** [comment]
looks good, and uncontroversial. why don't you merge it ?

**Comment by mcostalba** [comment]
@lucasart I'm waiting for Joona's greenlight

**Comment by lucasart** [comment]
SF is a bureaucracy now ;-)

**Comment by vondele** [comment]
Ah, after the races we now found a deadlock ;-)

@mcostalba in fishcooking @zamar suggested a week ago he's waiting for you..

https://groups.google.com/d/msg/fishcooking/oQjNkpGEVhk/VOU8UHdQBQAJ

**Comment by mstembera** [comment]
@mcostalba 
For whatever reason the constexpr  never made it into make_score() in types.h.
Can you still commit?

**Pull request closed without merging**
