### PR TITLE
Reformat FastMove

### PR DESCRIPTION
**Pull request by mcostalba**
Align to SF coding style.

No functional change.

P.S: This is just a quick band-aid, more is needed to make the code understandable but it will require functionality change.

### CODE REVIEW

**Comment by zamar** [comment]
Thanks Marco,

I agree that the current implementation is quite messy, but it's a starting point...

Just to be on the safe side, have you checked somehow that your patch doesn't accidentally cause a functional change? (bench is useless when it comes to time management patches)

If you haven't then running [-,4 0] LTC SPRT is the way to go.

Thanks again.

**Comment by mcostalba** [comment]
I have queued a [-3, 1] test that includes this pathc (that should be 100% no funtional change) + another one that slightly affect functionality but simpifies (just a bit) the mess:

http://tests.stockfishchess.org/tests/view/550403010ebc5902160ec16a

Finger crossed....  :-)

**Comment by mstembera** [comment]
The reformatting looks good.   

I did however write update() the way I did for a specific reason which was not to miss a certain class of easy moves. Here is a synthetic example position just for illustration:

8/2kp4/ppp5/6Pq/6P1/4B3/8/2K5 w - - 0 1

If we play Bf4+ black has several possible responses which might cause pv[1] to be unstable but pv[2] will always stay stable as g4xh5 and is clearly an easy move regardless of what black does.  With the simplified update() this will no longer work properly.

**Comment by mstembera** [comment]
To sum up stableCnt should keep incrementing as long as pv[2] doesn't change and not be affected by what pv[0] or pv[1] do.    g4xh5 may still get filtered out(unfortunately) when we actually get to playing it if black responded differently than we predicted because we only store one expected position key(we could store multiple keys as an improvement) but at least it has a chance and should not be filtered out based on instability.

**Comment by mcostalba** [comment]
I know, that's  why I wrote update() in another commit,  but if it pass
simplification test I will pull request as is because it is simpler and
clearer.

**Comment by mstembera** [comment]
How about this?

```c++
void update(Position& pos, const std::vector<Move>& newPv) {

    assert(newPv.size() >= 3);

    // 3rd ply must be stable
    stableCnt = (newPv[2] == pv[2]) ? stableCnt + 1 : 0;

    if (!std::equal(newPv.begin(), newPv.begin() + 3, pv))
    {
        std::copy(newPv.begin(), newPv.begin() + 3, pv);

        StateInfo st[2];
        pos.do_move(newPv[0], st[0], pos.gives_check(newPv[0], CheckInfo(pos)));
        pos.do_move(newPv[1], st[1], pos.gives_check(newPv[1], CheckInfo(pos)));
        expectedPosKey = pos.key();
        pos.undo_move(newPv[1]);
        pos.undo_move(newPv[0]);
    }
}
```
I think we can have our cake and eat it too :)

**Comment by mcostalba** [comment]
Apart that eventually should be written:

 stableCnt += (newPv[2] == pv[2]);


but the point is that this logic is obscure and tricky and covers a corner
case. Perhaps in your example it works, but what about the general case?

IMO it is much more natural to assume that any change in the pv up to depth
3 resets the easy move: this is easy to understand and the natural choice.

To have good maintainable code it is important not only that code is clear
and simple, but also that the ideas behind the code are clear and simple:
your easy move detector is already _very_ complicated for what it has to
do, so please avoid to make it even more complicated if is not strictly
necessary.

**Comment by glinscott** [comment]
Cool, thanks Marco, looks good.

**Comment by mstembera** [comment]
>Apart that eventually should be written:

>stableCnt += (newPv[2] == pv[2]);

I'm a bit confused by this.  We need stableCnt to be set to 0 not add 0 if the above condition is false
so I believe 
stableCnt = (newPv[2] == pv[2]) ? stableCnt + 1 : 0;
is correct.


>but the point is that this logic is obscure and tricky and covers a corner
>case. Perhaps in your example it works, but what about the general case?

Your version covers only the common case.  My suggested version also covers 
the common case as well as the corner case with even less code.  I think 
that makes it more general.  If you can think of any case that your version 
handles correctly and mine doesn't please point it out.  I already gave an 
example where the opposite is true.

>IMO it is much more natural to assume that any change in the pv up to depth
>3 resets the easy move: this is easy to understand and the natural choice.

I respect your opinion of what you consider natural.  I consider caring only 
about a change in the actual easy move we are going to make more natural.

>To have good maintainable code it is important not only that code is clear
>and simple, but also that the ideas behind the code are clear and simple:
>your easy move detector is already _very_ complicated for what it has to
>do, so please avoid to make it even more complicated if is not strictly
>necessary.

I agree.  I don't mean to make it more complicated and I am first to
admit I like all your other changes you made to it including the 
non functional changes in update().  If someone reads your current 
version of update() though they will think that it is a necessary condition 
for pv[0] and pv[1] to be stable when in reality this is incorrect.
IMO if we want to be clear and understandable we must be correct first.

**Comment by mcostalba** [comment]
I think your update() is "unnecessary risky":

unnecessary, because test shows does not increase ELO

risky, because you include corner cases for which you gave an example, but nothing prevents to exist a counter example for which  newPv[2] == pv[2] while previous PV changed and easy move is bad.

The point is easy move is always a (calculated) risk, so we should try it only when we are fully sure, border line cases should be avoided (if ELO does not change). So my implementation is a simplification in a broader sense, both as code and as concept: PV head changed somehow? if yes then no easy move. Very easy, natural and understandable.

Perhaps your version catch some good corner case but for what? To risk falling in some bad choice? To make code less understandable? To make logic more complex? For no ELO gain?

It does not worth it, IMO.

**Comment by mstembera** [comment]
Some easy moves depend on what our opponent does(category 1) and some don't(category 2).  Both categories are equally valid even if the second is a lot more rare.   That is why crippling the implementation to remove category 2 can pass no regression.  There is no known additional risk associated with category 2 compared to category 1 only imaginary risk based on no data.  I think if you want to change functionality you need something more tangible.  I have asked you to provide even one single  example showing a problem yet all you say is there could be.  I already made my points above in the thread as best I can so I won't repeat.   I also posted an implementation that I believe is simplest/shortest(even with the comment getting it's own line), just as easy to understand, and keeps the original more correct and general functionality.  We both failed convincing each other of our opinions(that's ok nothing personal) so maybe we can leave it to the other maintainers to referee our proposed versions.

**Comment by hxim** [comment]
@mstembera 
I understand why you don't want check if pv[1] == newPv[1] as you explained with your example. But why you don't check if pv[0] == newPv[0]? I think you should. Do you have explanation / example for that case too?

**Comment by mstembera** [comment]
@hxim
Yes.  You ask good questions.  Let's say you have two different ways to deliver check and you are going back and forth deciding which to play.  Regardless of which you choose your opponent will respond to the check and then you will have some easy move like say recapturing a queen.  Here is a synthetic example position of this type just for illustration.

7r/1pk5/p7/7q/6P1/3R1P2/3R4/2K5 w - - 0 1

You could play Rd3c3+ or Rd2c2+ but either way  on your next turn you will have an easy move gxh5.  These types of positions will also no longer be detected.  The ONLY thing that needs to be stable is the 3rd ply because that is the only move we will ever be making under reduced time.  It really is that simple.

**Comment by mstembera** [comment]
If it's preferable another unbiased way used in the past to select between two functionally different versions of the same patch has been to run a head to head match.  40K(or more if anyone prefers) games at either STC or LTC would be ok by me.

**Comment by mcostalba** [comment]
This makes no sense in this specific case, you will end up measuring only
noise.

Because you are the original patch author and strongly prefer your version
then I will use it, although  I think it uselessly complicates the code.

I will update the pull request.

**Comment by mcostalba** [comment]
Ok, pull request updated. I'm ready to merge after approaval.

**Comment by zamar** [comment]
approved.

**Comment by mstembera** [comment]
Thanks Marco

**Comment by glinscott** [comment]
Merge away :).

**Pull request merged**
