### PR TITLE
Extension for Queen Exchange

### PR DESCRIPTION
**Pull request by SFisGOD**
Extension for Queen Exchange

STC (Yellow)
LLR: -2.95 (-2.94,2.94) [0.00,5.00]
Total: 54635 W: 11762 L: 11628 D: 31245
http://tests.stockfishchess.org/tests/view/5bea8d300ebc595e0ae34e3a

LTC: (Green)
LLR: 2.94 (-2.94,2.94) [0.00,5.00]
Total: 9333 W: 1548 L: 1391 D: 6394
http://tests.stockfishchess.org/tests/view/5bed91e30ebc595e0ae38258

LTC 2: (Yellow)
LLR: -2.96 (-2.94,2.94) [0.00,5.00]
Total: 44742 W: 7205 L: 7154 D: 30383
http://tests.stockfishchess.org/tests/view/5bef59d80ebc595e0ae3a006

Bench: 3874748

### CODE REVIEW

**Comment by mcostalba** [comment]
Only tuning patches are recently been accepted with LTC only. But this is a full patch that adds a completely new extension. Maybe there are not many lines of code but the concept is important: we don't have many extensions in SF and in the past we dropped them one by one, once the test resources allowed us to properly measure their real benefit

So I would be more confident if you submit another LTC at [0, 5]

**Comment by 31m059** [comment]
LTC 2: failed yellow
LLR: -2.96 (-2.94,2.94) [0.00,5.00]
Total: 44742 W: 7205 L: 7154 D: 30383
http://tests.stockfishchess.org/tests/view/5bef59d80ebc595e0ae3a006

What should we do?  Run a third as a "tiebreaker"?

**Comment by mcostalba** [comment]
I am sorry but I think we should drop it

**Comment by NKONSTANTAKIS** [comment]
Another example indicating the need for higher confidence. Much more efficient than using multiple tests.

**Comment by Alayan-stk-2** [comment]
Based on the two LTC put together : 
Probability of this not being a regression : 94,4%
Probability of this being a 1+ elo gainer : 67%
Probability of this being a 2+ elo gainer : 24%

And when I write "elo", it means "elo", not "bayes elo". According to the table in the test creation page, 2 elo at LTC ~= 4 bayes elo.

With Bayes elo, you get the same non-regression probability and : 
1+ elo gainer : ~84%
2+ elo gainer : ~67%
3+ elo gainer : ~48%
4+ elo gainer : ~24%

**Pull request closed without merging**
