### PR TITLE
History Stat Comparison

### PR DESCRIPTION
**Pull request by VoyagerOne**
Adjust LMR by comparing history stats with opponent (prior ply).

STC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 27754 W: 5066 L: 4824 D: 17864

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 216596 W: 28157 L: 27343 D: 161096

Bench:  5437729

### CODE REVIEW

**Comment by VoyagerOne** [comment]
Note- 
I am highly confident this idea can be improved and bring even more ELO...right now its just in the early stages.

This comparison metric maybe useful for other areas in the search... such as history pruning, futility pruning, etc...

Also shout-out to all those who contribute CPU resources.

**Comment by stockfishdeveloper** [comment]
Congrats!

**Comment by FauziAkram** [comment]
Congrats

**Comment by stockfishdeveloper** [comment]
@VoyagerOne  How did you test the new correction factor?

**Comment by VoyagerOne** [comment]
@stockfishdeveloper 
Accidentally changed it in this commit.  I reverted it back...

**Comment by VoyagerOne** [comment]
... I also accidentally just closed this commit when replying to your comment... 
sigh...

**Comment by stockfishdeveloper** [comment]
Honestly I've done much dumber things!

**Comment by mcostalba** [comment]
Merged with e77f38c43102634

Slightly edited for code style conventions.

**Comment by rals** [comment]
Nice idea. Congrats.

**Pull request closed without merging**
