### PR TITLE
Simplification of SEE following the DRY-principle

### PR DESCRIPTION
**Pull request by pb00068**
PGO-Results for 20 tests for each version (gcc 4.8.1 Win7-64 i7-3770 @ 3.4GHz x86-64-modern):

            Base      Test      Diff      
    Mean    2056695   2062983   -6288     
    StDev   10585     11707     2060      

p-value: 0,999
speedup: 0,003

no functional change

### CODE REVIEW

**Comment by gogamoga1** [comment]
PGO

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1653814   1659038   -5224     
    StDev   9028      14608     15976     

p-value: 0,628
speedup: 0,003

**Comment by pb00068** [comment]
@snicolet Could you also do a speed-test on PGO-builds please? I think those are more significant

**Comment by snicolet** [comment]
I can't manage to make profile based compiles on Mac OS X, sorry.

**Comment by pb00068** [comment]
I think this obsolete due PR 822

**Comment by lucasart** [comment]
@pb00068: I prefer your patch. I think you should reopen this PR.

**Comment by mcostalba** [comment]
@pb00068 can you please rebase above current master and explain why it should merged it? Thanks.

**Comment by pb00068** [comment]
I just reopened this on suggestion from Lucas. (At the time when I opened this it was up2date with master). Since you see no point in merging this I'm closing this definitely.

**Comment by mcostalba** [comment]
@pb00068 I merged the other patch becuase it passed SPRT[0, 5] but of course I am fully available to apply a new patch if qualifies according to usual conditions. If you think your patch should be considered for a PR, please feel free to rebase, reopen and explain your arguments.

**Pull request closed without merging**
