### PR TITLE
Simplify the KPsK condition

### PR DESCRIPTION
**Pull request by WOnder93**
The expression resulting from commit 6c197c3964ca ("Corrects a
functional change in a cleanup patch.") can be simplified a bit.

No functional change.

### CODE REVIEW

**Comment by ddugovic** [comment]
That doesn't look equivalent: [4k3/4P3/3PK3/8/8/8/8/8 w - - 0 1](https://lichess.org/editor/4k3/4P3/3PK3/8/8/8/8/8_w_-_-_0_1) should not be a draw.

**Comment by WOnder93** [comment]
@ddugovic I believe it handles that position correctly:
1. `(FileABB | FileHBB) & passed_pawn_span(weakSide, weakKing)` is an empty bitboard in this case.
2. `~((FileABB | FileHBB) & passed_pawn_span(weakSide, weakKing))` is a full bitboard.
3. `strongPawns & ~((FileABB | FileHBB) & passed_pawn_span(weakSide, weakKing))` == `strongPawns`.
4. `!(strongPawns & ~((FileABB | FileHBB) & passed_pawn_span(weakSide, weakKing)))` is false, because `strongPawns` is non-zero (non-empty).
5. `SCALE_FACTOR_NONE` is returned.

But maybe I'm missing something still :)

**Comment by ddugovic** [comment]
Ah, you are correct... there are many operations but this condition checks if there are any strong-side pawns except for A-file or H-file pawns which are within the king's pawn-attack span.

**Comment by WOnder93** [comment]
(Corrected KPvK -> KPsK in the commit message)

**Comment by syzygy1** [comment]
Yesterday I saw that this was possible too, but I didn't propose it because it increases the number of operations in the normal case (where there is at least one pawn in one of files B-G).

**Comment by WOnder93** [comment]
That's true... So what should be the next step? Should I test this for non-regression on fishtest? Or just cancel the PR?

**Comment by vondele** [comment]
testing on fishtest makes little sense, this is almost not executed, except when near on in this endgame. I guess the current version is a tiny bit faster for the endgame. So I would leave as is.

**Comment by WOnder93** [comment]
OK, fine by me :)

**Pull request closed without merging**
