### PR TITLE
Assorted Trivial cleanups - August 2019

### PR DESCRIPTION
**Pull request by protonspring**
This is a non-tested, non-functional simplification of shelter.  I didn't see a trivial fixes PR, so I posted here.

Is a test needed?

### CODE REVIEW

**Comment by MichaelB7** [comment]
I think you have here the first trivial fix for Aug. Just rename this to “Assorted trivial cleanups (August  2019)” and I would think you’re good to go.

**Comment by protonspring** [comment]
In endgame, lines 150+, the "Them" can be removed.  it is only used in where (Us == WHITE).  Just replace Them with the appropriate color.  If agree, I'll add it to the PR.

**Comment by vondele** [comment]
```diff
diff --git a/src/search.cpp b/src/search.cpp
index 7f421b9cd..3eee9ac8d 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1091,7 +1091,7 @@ moves_loop: // When in check, search starts from here
           if ((ss-1)->moveCount > 15)
               r -= ONE_PLY;
 
-          // Decrease reduction if move has been singularly extended
+          // Decrease reduction if ttMove has been singularly extended
           r -= singularLMR * ONE_PLY;
 
           if (!captureOrPromotion)
```

**Comment by vondele** [comment]
at least for me, easier to read
```diff
diff --git a/src/search.cpp b/src/search.cpp
index 7f421b9cd..43e7cfb8d 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1046,7 +1046,7 @@ moves_loop: // When in check, search starts from here
               if (!pos.see_ge(move, Value(-(31 - std::min(lmrDepth, 18)) * lmrDepth * lmrDepth)))
                   continue;
           }
-          else if (  (!givesCheck || !extension)
+          else if (   !(givesCheck && extension)
                    && !pos.see_ge(move, Value(-199) * (depth / ONE_PLY))) // (~20 Elo)
                   continue;
       }
```

**Comment by MichaelB7** [comment]
LOL  verbiage wise, as it was written is clearer ->
 "if one is false , process" compared to " if both are true , do not process"
but I have no preference either way, I just found it amusing...😊

**Comment by adentong** [comment]
There are some unnecessary brackets on lines 1308/1309 in position.cpp.

**Comment by protonspring** [comment]
I believe those extra parenthesis clarify order of operation.  They aren't necessary, but are nice for clarity.

**Comment by adentong** [comment]
|| castlingRightsMask[castlingRookSquare[cr]] != (cr)
              || (castlingRightsMask[square<KING>(c)] & (cr)) != (cr)
is what we have right now. I was more referring to the brackets around cr. It used to (c | s) so having the brackets were good for clarity. But now that's its just cr we can remove the brackets around it so it'd look more like this:
              || castlingRightsMask[castlingRookSquare[cr]] != cr
              || (castlingRightsMask[square<KING>(c)] & cr) != cr

**Comment by protonspring** [comment]
fyi, parenthesis = \(  \), brackets = \[  \], braces = \{  \} (I think)

**Comment by snicolet** [comment]
Add the following line in the AUTHORS file:
````
Jean Gauthier (OuaisBla)
````

**Comment by snicolet** [comment]
The change in "simplify futility" would fail if ONE_PLY was not equal to 1.

**Comment by protonspring** [comment]
Evaluate: lines 750+

int v = ((eg > 0) - (eg < 0)) * std::max(....)

This is a bit tricky for me, but it could be:

int v = clamp(eg, -1, 1) * std::max(..)

This is more clear to me, but I'm often wrong about simplifications.  If someone else could confirm, I'll add it to this branch.

**Comment by MichaelB7** [comment]
@protonspring - I find yours clearer.  Hopefully , some others weigh in as well.

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp#L538
    // Bonus for restricting their piece moves
    b =   attackedBy[Them][ALL_PIECES]
       & ~stronglyProtected
       &  attackedBy[Us][ALL_PIECES];

    score += RestrictedPiece * popcount(b);
Can be redone as
    // Malus for our piece moves being restricted
    b =   stronglyProtected
       &  attackedBy[Us][ALL_PIECES];

    score -= RestrictedPiece * popcount(b);
One shorter line of code, exactly the same logic, one less ~ operator. The only thing that is "counter-intuitive" is that all other evaluation terms in threats are done with += score, but I don't think it matters. What do you think @snicolet

**Comment by adentong** [comment]
Since it's no longer August, maybe we should either merge this or update the name?

**Comment by snicolet** [comment]
I have merged some of the changes in e5cfa14f40a38d99d11a9c048c34858e3145fbcd, thanks!

**Pull request closed without merging**
