### PR TITLE
Update types.h

### PR DESCRIPTION
**Pull request by ali-al-zhrani**

### CODE REVIEW

**Comment by lucasart** [comment]
please ban this troll

**Comment by vondele** [comment]
@ali-al-zhrani see https://github.com/glinscott/fishtest/wiki/Creating-my-first-test on how to test your patches and how to structure your pull requests.

**Comment by AlexandreMasta** [comment]
@vondele this is not the first time this guy does that. He is a confirmed troll.

**Comment by vondele** [comment]
Well he's also contributing time in fishtest, search for ali in http://tests.stockfishchess.org/users

Doesn't mean that this is a proper pull request of course, and it should be closed. However, why not point people to the right place for reference.

**Comment by ali-al-zhrani** [comment]
# Thank you vondele
For your generosity, kindness and understanding
I have a problem at http://tests.stockfishchess.org/users
My definition is still hanging on my old warehouse
In every way I try to be reformed
And I still can not. It seems to me that it is an intractable problem

**Comment by ali-al-zhrani** [comment]
Thank you for your advice AlexandreMasta & lucasart

**Pull request closed without merging**
