### PR TITLE
Merge History LMR Formula

### PR DESCRIPTION
**Pull request by VoyagerOne**
Merge History LMR Formula

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 41713 W: 7589 L: 7504 D: 26620

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 41353 W: 5484 L: 5391 D: 30478

Bench:  8946983

### CODE REVIEW

**Comment by snicolet** [comment]
Congrats!

(note: we don't usually put a point at the end of one-line comments)

**Comment by VoyagerOne** [comment]
@snicolet 
Thanks!  

I feel the comment is practical since we explain all the other reduction features.  I will let a maintainer to decide...

**Comment by lp--** [comment]
Congrats on passing.

However, I am wondering about this tuning patch 
http://tests.stockfishchess.org/tests/view/571b6c060ebc59301a35481e

which showed high probability of being elo gain in short LTC test 60+0.06
ELO: 5.49 +-5.0 (95%) LOS: 98.5%
Total: 5000 W: 713 L: 634 D: 3653

It touches the same code as current  patch. IMO that tests should be tested first in normal LTC [0, 4] ]sprt run before commiting this test

**Comment by VoyagerOne** [comment]
@lp-- 
Yes the results looks very strong for that test.  However, the error bars are still very large at 5000 games.

If you like, you can submit an ELO test lmrUnion vs. fmh-lmrB.  Set number games to 20K.

**Comment by lp--** [comment]
@VoyagerOne 
It has to be sprt [0, 4]. 20K test is not likely to reach required confidence level.  I will submit it a liitle later when I have a chance, if someone will not do it before me. I am quite surprised that a number of speculative LTC tests have been done but no sprt LTC for this patch, which already had positive pre-selection at LTC.

**Comment by VoyagerOne** [comment]
@lp-- 
At a certain amount of games and there is obviously no improvement I think you should stop the test because:

1.  The patch failed at STC.
2.  There are already two LTC tests in the framework.
3.  It seems that lmrUnion may have added some elo and you are not testing against it.

**Comment by mcostalba** [comment]
@VoyagerOne  I have applied the PR.

Please for the future try to:

- Open a PR against current master (rebase in case master has advanced in the meantime)

- Squash all the commits in a single one

- Properly edit commit message 

In this case I have done all the above 3 steps for you, but it is appreciated if you, as the PR author, could take care of it.

**Comment by Jekaa** [comment]
r = std::max(DEPTH_ZERO, r - std::max(rHist, VALUE_ZERO) * ONE_PLY);

**Pull request closed without merging**
