### PR TITLE
Fix gcc pgo build on Windows

### PR DESCRIPTION
**Pull request by syzygy1**
This fixes the "std::length_error" problem.

No functional change.

### CODE REVIEW

**Comment by snicolet** [comment]
Looks good to me, thanks!

**Comment by AndyGrant** [comment]
I can confirm that this fixes PGO builds on my windows box. Much cleaner solution than tweaking the flags.

**Comment by mcostalba** [comment]
@syzygy1 nice catch!

**Comment by gvreuls** [comment]
This works perfectly. Great workaround.

**Comment by CoffeeOne** [comment]
Windows msys2 with gcc7.3: works like a charm. 👍

**Comment by ChessMan3** [comment]
Works perfect for me, gcc 7.2.0 & gcc 7.3.0

**Comment by snicolet** [comment]
Approved. Great!

**Comment by snicolet** [comment]
Merged via https://github.com/official-stockfish/Stockfish/commit/860223c5e6b2df53af0415dbbbfdd4834f083708

**Pull request closed without merging**
