### PR TITLE
Only show TB initialization info if path has changed.

### PR DESCRIPTION
**Pull request by joergoster**
Alternative to https://github.com/official-stockfish/Stockfish/pull/2811

No functional change.

### CODE REVIEW

**Comment by joergoster** [comment]
Just as a side note: this will only work until C++20 ... but this seems still far ahead. ;-)

**Comment by lucasart** [comment]
But ucinewgame calls this, regardless of whether path has changed. `Tablebases::init(Options["SyzygyPath"]); // Free mapped files}`
This isn't exactly no-op, so I don't see why we would want to hide it

**Comment by MichaelB7** [comment]
Often , I look for the TB initiation in logs , when debugging tournaments scripts for new runs.

**Comment by vondele** [comment]
I tend to agree with this... as a forgetful user, I might send the option SyzygyPath a second time, and would be surprised if there is no output. So I'll close this.

**Comment by joergoster** [comment]
@lucasart Wow, I'm still on your personal agenda?

There is so much discussion going on and questionable stuff being committed, but you only pop up here after such a long time.
I'm still undecided whether I should feel honored or angry.

**Comment by joergoster** [comment]
Just 2 small finalizing remarks, then I will leave this at rest.

@lucasart This is _exactly_ the kind of issue we don't want to show to the user. Or why don't we inform about TT.clear() and Threads.clear() either? Most of the users don't understand or don't even care!

@vondele As a forgetful user, I can only recommend you to use a GUI. Oh wait, we already do ...

**Pull request closed without merging**
