### PR TITLE
Fast SEE 2% Speedup?

### PR DESCRIPTION
**Pull request by VoyagerOne**
Results for 7 tests for each version:

            Base      Test      Diff      
    Mean    2288059   2335019   -46960    
    StDev   116844    78995     110832    

p-value: 0.664
speedup: 0.021

I am hoping somebody can do a speed test.  As I seem to get a lot of noise... difficult for the p-value to go above .60.

### CODE REVIEW

**Comment by KassiasGrandiel** [comment]
I think you need to rebase to latest master

**Comment by VoyagerOne** [comment]
@KassiasGrandiel 
I am at the latest functional change master.
"Small passed pawn simplification "

**Comment by mcostalba** [comment]
This should be tested with sprt (0,5) because adds some code so we need a
reason for this.

Disclaimer : I am very against this kind of "optimizations"  because
clutter the code for no real reason. But I try to remain objective.

**Comment by zamar** [comment]
My take on this:

- If it's a "no functional change", then benchmarks from people are the only things we need. So no SPRT runs, please.

- However, I agree with @mcostalba that this change really uglifies the code, so the speed up needs to be significant. So I'd say, if you can get systematically from different kind of systems around 2% speed up, then that's good enough, for the patch to merged... If it's less than that, then it isn't worth it.

**Comment by nabildanial** [comment]
If it is somehow pass both STC and LTC SPRT runs, why wouldn't you want to commit this patch (even though it adds some lines)?

**Comment by zamar** [comment]
@nabildanial: Because 1% speed up might pass SPRT with lucky runs. But there are no lucky runs in benchmarks.

Why would choose an inaccurate measurement, when you can do an accurate one?

I will send my benchmark results when I have some extra time to take them...

**Comment by VoyagerOne** [comment]
@mcostalba @zamar 

Note I can "un-uglify" the code, the parameter in the SEE is not necessary and the added code will just be in position.cpp

At this point, I am just curious to see if their is a significant speedup for other users.

**Comment by joergoster** [comment]
Only a small speedup on my AMD box with standard builds:
```
Engine                          | Nodes/second
fastSEE                         | 1621678.0 +- 2897.56
baseSEE                         | 1617472.0 +- 2323.68

Differences                     | 4558.0 +- 1444.0
Variance of the mean            | 288.8 ( 6.34 %)
Speed up                        | 0.28 %
```

And no difference with pgo builds:
```
Engine                          | Nodes/second
fastSEE-pgo                     | 1878118.0 +- 1959.12
baseSEE-pgo                     | 1878118.0 +- 3390.38

Differences                     | -941.0 +- 2590.0
Variance of the mean            | 518.0 ( -55.05 %)
Speed up                        | -0.05 %
```

**Comment by VoyagerOne** [comment]
@joergoster 
Thanks for your results.
Are the position(s) you test all have queens?  
The speedup is applicable only if there are queens in a test position.

**Comment by VoyagerOne** [comment]
14 out of 30 positions in bench do not have any Queens.

**Comment by lucasart** [comment]
@VoyagerOne: Lots of positions than happen in real games have no queen. Even more so positions that occurr deep in the search tree, and they are the most important as they account for most of the nodes searched. So there is no reason to make an exception, and run a queenless bench for this patch.

**Comment by MichaelB7** [comment]
+1

**Comment by VoyagerOne** [comment]
@lucasart
There are several positions that have 5-men / 6-men queen-less positions in bench.  The NPS increase dramatically when there are only a few men.  This high NPS may hide any gain of this patch leading to noise.

**Comment by CoffeeOne** [comment]
Hello,
I made a bench run, too. gcc5.3.0, Windows 10. normal (non profile) build.
This machine gives reliable bench runs, no Power Save, no Turbo, ...
Result:
Build Tester: 1.4.6.0
Windows 10 (Version 10.0, Build 0, 64-bit Edition)
AMD FX(tm)-9590 Eight-Core Processor           
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: Yes
CPU Warmup: Yes
Command Line: bench 16 1 15 default depth
Tests per Build: 100
ANOVA: n/a

                Engine# (NPS)                     Speedup     Sp     Conf. 95%    S.S.
1  (1.730.665,2   ) ---> 2  (1.725.596,6   ) --->  0,294%  7.241,9      Yes       No 
Build 1 is current master.
Current Master is 0.3% faster.

I use normal bench positions, too. How (which positions) did you measure a 2% speedup?

**Comment by VoyagerOne** [comment]
@CoffeeOne 
Thanks for running your test.  Based on your results I will close this.

My results were from normal bench with Fishtest.  The results were quite noisy...but noticed as the p-value increased so did the speedup.

**Pull request closed without merging**
