### PR TITLE
Simplify README

### PR DESCRIPTION
**Pull request by Disservin**
The UCI protocol is rather technical and has little value in our README. Instead
it should be explained in our wiki. "Contributing" is moved above "Compiling
Stockfish" to make it more prominent.

Also move the CONTRIBUTING.md into the root directory and include it in the
distributed artifacts/releases.

### CODE REVIEW

**Comment by dav1312** [comment]
Note that you renamed the commands wiki page but didn't update the link in the readme and now you are moving the contributing file but are not updating the links either

**Comment by Disservin** [comment]
> Note that you renamed the commands wiki page but didn't update the link in the readme and now you are moving the contributing file but are not updating the links either

The readme doesnt link to the commands anymore, but I should remove the old link variable(or whatever it is called) and yeah i'll fix the link to the readme and check which links need to be adjusted in the wiki

**Comment by snicolet** [comment]
It is quite nice to have moved the CONTRIBUTING.md file in the main repo, thanks :-)
Does it break anything if we make the `.github` repo private after that?

**Comment by snicolet** [comment]
merged via 4f7fe255c7ac9cf705350cabfc231d87a3e75018, thanks :-)

**Pull request closed without merging**
