### PR TITLE
New mobility bonus

### PR DESCRIPTION
**Pull request by Rocky640**
Tuned the global mobility factor for each piece, as well as some +- delta,

The master mobility factor was {266,334} and tuning gave
{267, 362} +S(-2,-2) for the Knight
{249, 328} +S(	0,-2) for the Bishop
{298, 353} +S(1,1) for the Rook
{265, 358} +S(2,-1) for the Queen

Passed STC
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 49402 W: 9367 L: 9037 D: 30998

and LTC
LLR: 2.97 (-2.94,2.94) [0.00,5.00]
Total: 26831 W: 3871 L: 3658 D: 19302

Unfortunately, LTC was done with [0, 5] instead if [0,4]
Please advise.

### CODE REVIEW

**Comment by joergoster** [comment]
Nothing wrong with passing (0, 5) bounds, I guess! ;-)
Congrats!

**Comment by lucasart** [comment]
good job.

**Comment by zamar** [comment]
approved.

**Comment by locutus2** [comment]
Congrats too!

**Comment by glinscott** [comment]
Congrats!  Looks good.

**Comment by mcostalba** [comment]
Good job! Congrats...hopefully also all the remaining weights will fall down, one by one.

**Comment by Rocky640** [comment]
// Evaluation weights, indexed by the corresponding evaluation term 
  enum { PawnStructure, PassedPawns, Space, KingSafety }; 
  const struct Weight { int mg, eg; } Weights[] = { 
     {214, 203}, {193, 262}, {47, 0}, {330, 0} 

a) KingSafety is a no brainer.
      replace
      KingDanger[i] = make_score(t / 1000, 0) * Weights[KingSafety];
      with
      KingDanger[i] = make_score(t * 330 / 256000, 0);
      (or something prettier)

      and remove all refs to KingSafety
      no functional change, same bench

     this one make sense, we used to  always tune MaxSlope, Peak, and KingSafety together. 

b) Space:
    replace
    return make_score(bonus * weight * weight, 0);
    with
    return make_score(46 * bonus * weight * weight / 256, 0);

    and remove all refs to Space
    possibly not exactly the same bench
 
b)' or possibly this
     return make_score(  bonus * weight * weight / 4,  0);

c) PassedPawns
    just multiply the mbonus by 3/4 , this should work easily.

    We could make a test for b) + c)  or b') + c)
    What do you think ?

d) PawnStructure, 
    This one will need more work. Pawn tuning is always difficult.
    I might try the same approach as I did with Mobility.

**Pull request closed without merging**
