### PR TITLE
Small cleanups 12

### PR DESCRIPTION
**Pull request by snicolet**
Start with an empty PR to collect small cleanups.

No functional change

### CODE REVIEW

**Comment by snicolet** [comment]
The hybridation of evals can be rewritten as
```
  Value v = Value(0);

  if (Eval::useNNUE)
  {
      if (abs(eg_value(pos.psq_score())) * 16 > NNUEThreshold1 * (16 + pos.rule50_count()))
          v = Evaluation<NO_TRACE>(pos).value();

      if (abs(v) * 16 < NNUEThreshold2 * (16 + pos.rule50_count()))
          v = NNUE::evaluate(pos) * 5 / 4 + Tempo;
  }
  else
      v = Evaluation<NO_TRACE>(pos).value();
```

Maybe clearer because there is only one point where we call the (somewhat complicated) `NNUE::evaluate(pos) * 5 / 4 + Tempo`

**Comment by snicolet** [comment]
@vondele Seems like the Travis-CI results are back in our pull requests. I followed the points 1 and 3 suggested by user "javeme" in this post comment (revoking access and authorizing it again): https://travis-ci.community/t/github-pr-is-being-built-but-result-is-not-shown/7025/2 and it worked.

**Comment by Fanael** [comment]
No need to include the entirety of `<iostream>` when only `std::istream` is used in that header:
```diff
diff --git a/src/nnue/nnue_common.h b/src/nnue/nnue_common.h
index a9d8e5af..9b3323e4 100644
--- a/src/nnue/nnue_common.h
+++ b/src/nnue/nnue_common.h
@@ -22,7 +22,7 @@
 #define NNUE_COMMON_H_INCLUDED

 #include <cstring>
-#include <iostream>
+#include <istream>

 #if defined(USE_AVX2)
 #include <immintrin.h>
```

**Comment by Vizvezdenec** [comment]
add comment to line 1572 of search
Smth like
//countermove based pruning
by analogy to usual search.

**Comment by Fanael** [comment]
`kpp_board_index` is never modified, so it should be `const`:
```diff
diff --git a/src/nnue/evaluate_nnue.cpp b/src/nnue/evaluate_nnue.cpp
index e6619089..71c9f23e 100644
--- a/src/nnue/evaluate_nnue.cpp
+++ b/src/nnue/evaluate_nnue.cpp
@@ -31,7 +31,7 @@

 namespace Eval::NNUE {

-  uint32_t kpp_board_index[PIECE_NB][COLOR_NB] = {
+  const uint32_t kpp_board_index[PIECE_NB][COLOR_NB] = {
    // convention: W - us, B - them
    // viewed from other side, W and B are reversed
       { PS_NONE,     PS_NONE     },
diff --git a/src/nnue/nnue_common.h b/src/nnue/nnue_common.h
index 7bc905dc..8afea186 100644
--- a/src/nnue/nnue_common.h
+++ b/src/nnue/nnue_common.h
@@ -113,7 +113,7 @@ namespace Eval::NNUE {
     PS_END2     = 12 * SQUARE_NB + 1
   };

-  extern uint32_t kpp_board_index[PIECE_NB][COLOR_NB];
+  extern const uint32_t kpp_board_index[PIECE_NB][COLOR_NB];

   // Type of input feature after conversion
   using TransformedFeatureType = std::uint8_t;
```

**Comment by Fanael** [comment]
Don't set the *output* buffer in `MemoryBuffer`, because the embedded net is read-only, and so is the stream:
```diff
diff --git a/src/evaluate.cpp b/src/evaluate.cpp
index 67154751..cba5b53d 100644
--- a/src/evaluate.cpp
+++ b/src/evaluate.cpp
@@ -98,7 +98,7 @@ namespace Eval {
             {
                 // C++ way to prepare a buffer for a memory stream
                 class MemoryBuffer : public basic_streambuf<char> {
-                    public: MemoryBuffer(char* p, size_t n) { setg(p, p, p + n); setp(p, p + n); }
+                    public: MemoryBuffer(char* p, size_t n) { setg(p, p, p + n); }
                 };
 
                 MemoryBuffer buffer(const_cast<char*>(reinterpret_cast<const char*>(gEmbeddedNNUEData)),
```

**Comment by locutus2** [comment]
In following commit https://github.com/official-stockfish/Stockfish/pull/3091 two lines were forgotten to delete (see my comment there). Perhaps we could remove them here.

**Comment by pb00068** [comment]
tt.cpp line 43:

`  || d - DEPTH_OFFSET > depth8 - 4)`

I consider this bad style since it handles with 2 offsets where one single is more than sufficient.
Better would be following form:

`  || d  > depth8 + DEPTH_OFFSET)`

with adapting DEPTH_OFFSET accordingly.
Side note: eventually also cluster branch which uses another value for DEPTH_OFFSET needs to be adapted

**Comment by xoto10** [comment]
Whitespace change in thread.cpp
```
diff --git a/src/thread.cpp b/src/thread.cpp
index b46fce5e..2fbf745d 100644
--- a/src/thread.cpp
+++ b/src/thread.cpp
@@ -224,16 +224,16 @@ Thread* ThreadPool::get_best_thread() const {
         votes[th->rootMoves[0].pv[0]] +=
             (th->rootMoves[0].score - minScore + 14) * int(th->completedDepth);
 
-          if (abs(bestThread->rootMoves[0].score) >= VALUE_TB_WIN_IN_MAX_PLY)
-          {
-              // Make sure we pick the shortest mate / TB conversion or stave off mate the longest
-              if (th->rootMoves[0].score > bestThread->rootMoves[0].score)
-                  bestThread = th;
-          }
-          else if (   th->rootMoves[0].score >= VALUE_TB_WIN_IN_MAX_PLY
-                   || (   th->rootMoves[0].score > VALUE_TB_LOSS_IN_MAX_PLY
-                       && votes[th->rootMoves[0].pv[0]] > votes[bestThread->rootMoves[0].pv[0]]))
-              bestThread = th;
+        if (abs(bestThread->rootMoves[0].score) >= VALUE_TB_WIN_IN_MAX_PLY)
+        {
+            // Make sure we pick the shortest mate / TB conversion or stave off mate the longest
+            if (th->rootMoves[0].score > bestThread->rootMoves[0].score)
+                bestThread = th;
+        }
+        else if (   th->rootMoves[0].score >= VALUE_TB_WIN_IN_MAX_PLY
+                 || (   th->rootMoves[0].score > VALUE_TB_LOSS_IN_MAX_PLY
+                     && votes[th->rootMoves[0].pv[0]] > votes[bestThread->rootMoves[0].pv[0]]))
+            bestThread = th;
     }
 
     return bestThread;
```

**Comment by noobpwnftw** [comment]
https://github.com/official-stockfish/Stockfish/blob/0405f3540366cc16245d51531881c55d3726c8b5/src/evaluate.h#L46-L47
These declarations can be removed after https://github.com/official-stockfish/Stockfish/commit/fc27d158c012341593518a05abf51903ecbcb495.

**Comment by mstembera** [comment]
Could someone w/ Linux test adding
```C++
#if defined(MADV_RANDOM)
  madvise(mem, allocSize, MADV_RANDOM);
#endif
```
after line 374 in misc.cpp ?

**Comment by Fanael** [comment]
That flag only changes the behavior of I/O readahead for memory-mapped files, it's doesn't do anything for anonymous mappings, it's highly unlikely there would be any effect.

**Comment by Fanael** [comment]
The difference is within one standard deviation of one another, i.e. completely statistically insignificant, on my machine:
```
 Performance counter stats for './stockfish bench 512 1 20' (10 runs):

         27 591,87 msec task-clock                #    0,999 CPUs utilized            ( +-  0,15% )
             3 361      context-switches          #    0,122 K/sec                    ( +- 20,07% )
                 6      cpu-migrations            #    0,000 K/sec                    ( +- 13,60% )
             4 164      page-faults               #    0,151 K/sec                    ( +-  4,47% )
   116 214 376 474      cycles                    #    4,212 GHz                      ( +-  0,09% )
     1 877 785 153      stalled-cycles-frontend   #    1,62% frontend cycles idle     ( +-  0,43% )
    45 142 960 964      stalled-cycles-backend    #   38,84% backend cycles idle      ( +-  0,19% )
   190 989 991 025      instructions              #    1,64  insn per cycle
                                                  #    0,24  stalled cycles per insn  ( +-  0,00% )
    17 179 423 860      branches                  #  622,626 M/sec                    ( +-  0,01% )
     1 049 740 901      branch-misses             #    6,11% of all branches          ( +-  0,13% )

           27,6143 +- 0,0383 seconds time elapsed  ( +-  0,14% )

 Performance counter stats for './stockfish-madv-random bench 512 1 20' (10 runs):

         27 524,41 msec task-clock                #    0,999 CPUs utilized            ( +-  0,11% )
             2 612      context-switches          #    0,095 K/sec                    ( +-  0,13% )
                 3      cpu-migrations            #    0,000 K/sec                    ( +- 22,22% )
             4 365      page-faults               #    0,159 K/sec                    ( +-  2,47% )
   116 091 040 393      cycles                    #    4,218 GHz                      ( +-  0,10% )
     1 864 868 874      stalled-cycles-frontend   #    1,61% frontend cycles idle     ( +-  0,52% )
    45 010 676 206      stalled-cycles-backend    #   38,77% backend cycles idle      ( +-  0,15% )
   190 982 562 859      instructions              #    1,65  insn per cycle
                                                  #    0,24  stalled cycles per insn  ( +-  0,00% )
    17 177 755 233      branches                  #  624,092 M/sec                    ( +-  0,00% )
     1 050 265 501      branch-misses             #    6,11% of all branches          ( +-  0,13% )

           27,5404 +- 0,0304 seconds time elapsed  ( +-  0,11% )
```

**Comment by mstembera** [comment]
@Fanael I was hoping it would prevent prefetching cache lines sequentially for the TT.   Thanks for testing!

**Comment by Vizvezdenec** [comment]
In line of how we threat static eval add !ss->inCheck to
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1163 and 
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1233

**Comment by locutus2** [comment]
Fix indention in capture LMR code in search.cpp:
```
diff --git a/src/search.cpp b/src/search.cpp
index 9c5fb58b..7c29816d 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1218,14 +1218,14 @@ moves_loop: // When in check, search starts from here
           }
           else
           {
-            // Increase reduction for captures/promotions if late move and at low depth
-            if (depth < 8 && moveCount > 2)
-                r++;
-
-            // Unless giving check, this capture is likely bad
-            if (   !givesCheck
-                && ss->staticEval + PieceValue[EG][pos.captured_piece()] + 213 * depth <= alpha)
-                r++;
+              // Increase reduction for captures/promotions if late move and at low depth
+              if (depth < 8 && moveCount > 2)
+                  r++;
+
+              // Unless giving check, this capture is likely bad
+              if (   !givesCheck
+                  && ss->staticEval + PieceValue[EG][pos.captured_piece()] + 213 * depth <= alpha)
+                  r++;
           }

           Depth d = std::clamp(newDepth - r, 1, newDepth);
```

**Comment by snicolet** [comment]
Merged via 9a64e737cfef639f202787161498ba94466ad730, thanks!

**Pull request closed without merging**
