### PR TITLE
All quiets

### PR DESCRIPTION
**Pull request by loco-loco**
Merging  GOOD and BAD quiets stages into a single one, ALL_QUIETS.

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 58613 W: 10779 L: 10723 D: 37111

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 33608 W: 4539 L: 4436 D: 24633

Bench after merging upstream/master "Unsafe checks":
9441294

### CODE REVIEW

**Comment by mstembera** [comment]
Congrats!

**Comment by DamasClasicas** [comment]
Bravo Loco! Congratulations!!

**Comment by mcostalba** [comment]
Merged with 969982406ce85e

Just slightly edited to better readability.

**Comment by snicolet** [comment]
Congrats!

**Comment by lp--** [comment]
Congrats!

**Comment by pb00068** [comment]
Congrats!

**Pull request closed without merging**
