### PR TITLE
Use moveCount history for reduction.

### PR DESCRIPTION
**Pull request by vondele**
passed STC:
http://tests.stockfishchess.org/tests/view/599f08cc0ebc5916ff64aace
LLR: 2.97 (-2.94,2.94) [0.00,5.00]
Total: 9638 W: 1889 L: 1720 D: 6029
elo =    6.093 +-    4.238 LOS:   99.8%

passed LTC:
http://tests.stockfishchess.org/tests/view/599f1e5c0ebc5916ff64aadc
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 28308 W: 3742 L: 3533 D: 21033
elo =    2.565 +-    2.049 LOS:   99.3%

Bench: 5747429

### CODE REVIEW

**Comment by mcostalba** [comment]
@vondele congratulations!

Care to explain what is the logic here? I red the code but it is not obvious, some comment in the commit message and eventually in the code would be appreciated.

**Comment by vondele** [comment]
I read it as: less reduction for moves with larger moveCount if your opponent did an unexpected (== high moveCount) move in the previous ply... unexpected moves might need unexpected answers.

The way to influence reduction() is through a lower 'effective moveCount'. One can imagine that other approaches could refine this idea.

**Comment by locutus2** [comment]
@vondele 
The question is if the reaction on the previous move count or the general decrease of move count is the key part of the success. If we use the current move count instead of the previous move count this equals an average  decrease of move count with the factor 15/16. This could we backport in the lmr formula: `r = log(d)*(log(mc)-0.0645)/1.95`. This formula generates less average reduction (measured on my big bench for depth 13 and 16) as your patch. So i reduce the correction term until reductions was the roughly the same (`log(d)*(log(mc)-0.05)/1.95`). I will schedule a test.

**Comment by vondele** [comment]
@locutus2 I think the history bit is key. Many tweaks on reduction have been tried before.

The current patch is inspired by the (stalled) tuning run here: http://tests.stockfishchess.org/tests/view/599ec8800ebc5916ff64aab5 where there seems to be quite some gradient wrt (ss-1)->moveCount

**Comment by crossbr** [comment]
"if your opponent did an unexpected (== high moveCount) move in the previous ply... unexpected moves might need unexpected answers."
I wonder if how this performs against an opponent other than SF might be different than (possibly even better than) how this performs when SF plays against itself, if against non-SF opponents there are more unexpected moves from the opponent than from SF, especially against very good engines like Komodo and Houdini.

**Comment by Vizvezdenec** [comment]
@crossbr I actually think that ponder ratio for SF is higher the better opposing engine is since the weaker opposing engine is the less probability it has to find move that SF thinks is the best...

**Comment by mcostalba** [comment]
@vondele the correction is indeed very tiny: nothing until 16 and after only 1, just in the rare case of more then 32 moves it becomes 2 less.

Have you tried with /8 or even /4 ?

**Comment by vondele** [comment]
@mcostalba yes, a few other versions were tried (with additional terms at higher ply depth). +1/8, -1/8, 1/32 (see test history).

1/16 (or more precisely 7 / 128) is the current standing of the tuning test.

**Comment by mcostalba** [comment]
@vondele thanks. It is impressive that such tiny change has such visible impact to pass a SPRT[0, 5] !!

**Comment by VoyagerOne** [comment]
@vondele or @locutus2 

An interesting experiment will try and tune that 1/16 based off of depth.

**Comment by VoyagerOne** [comment]
Also you can try to tune the parameter if prior move is PV.
So one parameter for PV and another for non-PV.

**Comment by mcostalba** [comment]
Merged with 5ef94eb970bc1e4f95e

**Comment by pb00068** [comment]
Hi @vondele , 
your explanation for this patch probably reflects your initial idea behind it, but I'm not able to belief that this it's the way it works. 
I would be able to comprehend following arguing (in fact it was the following I interpreted at first glance):
if the search just detected a new best move in previous ply at a high movecount, then this is a surprise and might need unexpected answers (= follow moves now need to be analyzed with less lmr).
The problem here I see in the fact, that previous move is not 'unexpected' at all, it's simply a further move being analyzed in an all-node. It's not proven at all to be a particular good one (that would be indeed unexpected), at least I miss the point were the patch verifies for this. Do I miss something?

**Comment by pb00068** [comment]
Probably now I found by myself the missing part of explanation: 

- if previous node is being analyzed at a high movecount, then previous node is an all-node (or PV node in rare case) so far. 
- all-node's children are expected cut-nodes
- we are on such a children node and here the movecount is already big enough to trigger lmr-reductions too.  Thus this node failed so far creating the expected cut-off, so previous move must be effectively an unexpected good one.

Is this interpretation correct?

**Comment by mcostalba** [comment]
Another possibility is something like this:

`((ss-1)->moveCount / 16) * 4`

So that it triggers only late moves but it gives bigger bonus when it happens.

**Pull request closed without merging**
