### PR TITLE
Add uninstall target to Makefile

### PR DESCRIPTION
**Pull request by jubalh**
Let the user easily uninstall stockfish.

### CODE REVIEW

**Comment by mcostalba** [comment]
Indeed a better patch would be to remove also 'install' target.....

**Comment by jubalh** [comment]
@mcostalba What do you mean?

**Comment by mcostalba** [comment]
This is just one file


Make install / uninstall IMO make sense for  more complex scenarios, here
in most cases sf binary remains in src directory, and in the rare cases
user wants to move to some global bin/ directory can just move it by
himself. But this is just my point of view.

**Comment by jubalh** [comment]
Of course it is, but not everybody reads the Makefile to see what exactly he has to do. A person types make help, and sees that there is a make install, so he thinks "ah its the usual workflow". I think this is a good thing, because many people like their default workflow. But to make the removal also easier for them I would also add the make uninstall. so they dont have to go reading the Makefile to see that it just copies one file.

I would say, including this cant hurt ;)

**Comment by lucasart** [comment]
What does it mean to install a chess engine ? There is no standard in this regard that is observed by most GUIs. The only standard I know is that an engine is a single file (an executable) and in the GUI you select it, and that's all. make install / uninstall is useless IMO. And it *can* hurt: because we have this useless install target, people send us pull request to "fix" it for whatever exotic distro they are using, or send us pull requests for adding uninstall and other useless cruft.

**Comment by jubalh** [comment]
To install a chess engine means to place it in a standard path. Like installing every other program. If you install it like that you have all stuff at the same location and dont have to think "Where did I install engine X again?"

**Comment by zamar** [comment]
This topic was discussed in the past.

Lucas and Marco strongly object this kind of change, so although I personally agree with you, I'll have to close this pull request and not to commit it.

**Comment by mcostalba** [comment]
@joona I am only slightly negative toward teh patch, not strongly negative.
I only think it is useless, but considering that we have make install, for
consistency makes sense to add also make uninstall.

Of course I consider both are useless, but at least let them be *consistently
*useless :-)

**Comment by jubalh** [comment]
I understand your point. But since install is already there, and it helps *some* people, and is not really creating more work for you, I think adding uninstall is better than removing install.

**Pull request closed without merging**
