### PR TITLE
Search optimization

### PR DESCRIPTION
**Pull request by IIvec**
Eval and search work together. Better eval needs improvements in search
too.

### CODE REVIEW

**Comment by IIvec** [comment]
Please help me to send this to fishtests. I get this message:
Invalid URL u'Stockfish/commits/master': No schema supplied

**Comment by IIvec** [comment]
@Stefano80 : I'm running some testings on my computer too. And I'm also using my intelligence and my faith.

**Comment by Stefano80** [comment]
But why are'nt you testing with SPRT and following testing guidelines?

**Comment by IIvec** [comment]
@Stefano80 & VoyagerOne : I'm sorry. I'm new here. I don't know how thing went wrong.
1) Should I use only SPRT?
2) Should I use less changes?
3) I'll check what went wrong with official master.

**Pull request closed without merging**
