### PR TITLE
doEvenDeeperSearch + tuning

### PR DESCRIPTION
**Pull request by FauziAkram**
Credit for the main idea of doEvenDeeperSearch goes to @Vizvezdenec (If you want to write a brief about the patch, you are more than welcome)
Tuning done by me @FauziAkram 

Passed STC:
LLR: 2.93 (-2.94,2.94) <0.00,2.00>
Total: 330048 W: 87672 L: 86942 D: 155434
Ptnml(0-2): 1012, 36739, 88912, 37229, 1132
https://tests.stockfishchess.org/tests/view/638a1cadd2b9c924c4c621d2

Passed LTC:
LLR: 2.95 (-2.94,2.94) <0.50,2.50>
Total: 216696 W: 57891 L: 57240 D: 101565
Ptnml(0-2): 72, 21221, 65152, 21790, 113
https://tests.stockfishchess.org/tests/view/638c7d52a971f1f096c68fe2

### CODE REVIEW

**Comment by Vizvezdenec** [comment]
Expansion of existing logic of doDeeperSearch - if value from LMR is really really good do full depth search not 1 ply deeper but rather 2 instead.

**Comment by FauziAkram** [comment]
With this pull request passing, I will move from position 16 to position 14 in the list of contributors of Stockfish with 30 successful patches (All of them functional and Elo gaining) 😄

**Comment by dav1312** [comment]
Please set the version to dev

**Comment by vondele** [comment]
> Please set the version to dev

I'll do that in an independent commit before merging anything else.

**Comment by vondele** [comment]
> With this pull request passing, I will move from position 16 to position 14 in the list of contributors of Stockfish with 30 successful patches (All of them functional and Elo gaining) smile

which is great.  At point you should also learn to rebase / squash your PRs so that they contain a single commit ... helps the maintainer, thanks!

**Comment by vondele** [comment]
This patch is causing https://github.com/official-stockfish/Stockfish/issues/4276 
So might need a revert and a better solution.
I'll leave it in master for a little while so we can judge our options.

**Pull request closed without merging**
