### PR TITLE
Adjust LMR with correction history

### PR DESCRIPTION
**Pull request by xu-shawn**
A positive constant increase in base reduction is applied to counter the decrease in average reduction from this tweak.

Passed STC:
LLR: 2.98 (-2.94,2.94) <0.00,2.00>
Total: 109216 W: 28415 L: 27989 D: 52812
Ptnml(0-2): 310, 12848, 27911, 13184, 355
https://tests.stockfishchess.org/tests/view/6760bb0e86d5ee47d9542f26

Passed LTC:
LLR: 2.95 (-2.94,2.94) <0.50,2.50>
Total: 66918 W: 17073 L: 16694 D: 33151
Ptnml(0-2): 33, 7175, 18666, 7550, 35
https://tests.stockfishchess.org/tests/view/6761e10f86d5ee47d95431fa

bench 1079115

### CODE REVIEW

**Comment by mstembera** [comment]
Congrats!  Perhaps I'm a bit old school but I really dislike returning auto.  Not being able to immediately know what is being returned unnecessarily eats up brain cycles while reading code.  Curious what others think.

**Comment by xu-shawn** [comment]
Maybe it would be better to give correction score a type alias? that could also save the template for eval correction

**Comment by Disservin** [comment]
correction value is just a dumb int, no need for any template or big abstraction imo

**Comment by ehsanrashid** [comment]
why use std::abs()
r -= std::min(std::abs(correctionValue) / 32768, 2048);

is it not better to use the raw value ?

**Comment by cj5716** [comment]
std::abs tells us the magnitude of the correction (ie, how unstable the position is)

**Pull request closed without merging**
