### PR TITLE
‏

### PR DESCRIPTION
**Pull request by lilas2027**
--------------------

_Thanks. It can be interesting to try to visualize the NNUE networks, but I would say that fits more as a starting point for a discussion (e.g., on our discord, see the readme) than as part of the code, so I am closing this._

----------------------

_Originally posted by @ianfab in https://github.com/fairy-stockfish/Fairy-Stockfish-NNUE/issues/9#issuecomment-1143710083_

### CODE REVIEW

**Comment by lilas2027** [comment]
**@vondele why delete my idea in discussions ?**

There are two main ways to try to understand how a neural network recognizes a certain pattern. If you want to know what kind of pattern significantly activates a certain feature map you could 1) either try to find images in a dataset that result in a high average activation of this feature map or you could 2) try to generate such a pattern by optimizing the pixel values in a random image.

**Comment by vondele** [comment]
because obviously this is a trolling PR, with made by somebody who is repeated creating new user names to do so.

**Comment by lilas2029** [comment]
Your information is not deep, that photo was a neural network pattern but you thought it was spam, Unfortunately if I say milk is white 🥛 you say it is black !, I honestly wanted to help you but you closed all my account 😥

**Comment by vondele** [comment]
please stop creating new accounts to comment here.

**Comment by ianfab** [comment]
And just to be very clear, I neither endorse nor tolerate his behavior. I just try to be polite when rejecting PRs, that's all. I don't want to be associated with this spam in any way.

**Comment by dav1312** [comment]
Totally not multi accounts... dude you are really really bored aren't you...? Just stop already and grow up
@lilas2020 @lilas2027 @lilas2029

**Comment by Joachim26** [comment]
Unfortunately, @dav1312 , you are on my list as well...

**Comment by lilas2020** [comment]
Thanks @dav1312 , But my all accounts are restricted , That's why I created this new account only to answer questions 😔

**Comment by lilas2020** [comment]
My only wish is to be able to put my idea into the discussions 💡 This is a great idea 💥  I can prove it ❤️

**Pull request closed without merging**
