### PR TITLE
Use emplace_back instead of push_back

### PR DESCRIPTION
**Pull request by UniQP**

### CODE REVIEW

**Comment by mcostalba** [comment]
Ok for me. Please format the commit message as following:

----------------------------------
Use emplace_back in TB code

No functional change.
---------------------------------------

**Comment by UniQP** [comment]
@mcostalba done

**Comment by snicolet** [comment]
@UniQP 
This looks like a good candidate for SF-11 dev after SF 10 is out. What I would like to see is a proof that the patch is non-functional in the presence of tablebases: probably a count of tablebase hits on bench, with/without the patch, would be sufficient. Do you have such information available?

**Comment by UniQP** [comment]
@snicolet I rebased the branch to the current master and executed bench with and without the PR:
[sf_9-274-g7b6fa353.log](https://github.com/official-stockfish/Stockfish/files/2621968/sf_9-274-g7b6fa353.log)
[sf_9-275-g191a7d8e.log](https://github.com/official-stockfish/Stockfish/files/2621969/sf_9-275-g191a7d8e.log)

I also filtered the tbhits from both logs:
[tbhits_sf_9-274-g7b6fa353.log](https://github.com/official-stockfish/Stockfish/files/2621970/tbhits_sf_9-274-g7b6fa353.log)
[tbhits_sf_9-275-g191a7d8e.log](https://github.com/official-stockfish/Stockfish/files/2621971/tbhits_sf_9-275-g191a7d8e.log)

The number of tbhits are equal in both logs.

**Comment by snicolet** [comment]
@UniQP Thanks, I will merge it!

**Comment by snicolet** [comment]
Merged via 340e9ea5096fb1c8e4a0914827f1af1d30075039, thanks!

**Pull request closed without merging**
