### PR TITLE
Fix NNUE build on macOS

### PR DESCRIPTION
**Pull request by daylen**
Fixes the two issues mentioned in https://github.com/official-stockfish/Stockfish/issues/2823#issuecomment-663904905.

Specifically:

1. Makefile: Updates the min macOS version to 10.15 from 10.9, because aligned_alloc is only available in 10.15+.
2. On macOS, `aligned_alloc` is in the global namespace. Remove `std::` from `std::aligned_alloc`. This still builds on Linux.

Testing:
- Compiled with clang on macOS 10.15 `make build ARCH=x86-64-bmi2`
- Compiled with GCC on Ubuntu 18.04.3 `make build ARCH=x86-64-avx512`

### CODE REVIEW

**Comment by vondele** [comment]
@daylen the Makefile change is fine with me, the other one seems to cause problems, and I would indeed expect that we need to use the 'std::' bit. Without std:: I assume we might be picking up (or not, @MichaelB7) the C11 and not the C++17 version:
https://en.cppreference.com/w/c/memory/aligned_alloc
https://en.cppreference.com/w/cpp/memory/c/aligned_alloc

We already have similar functionality in misc.cpp based on posix_memalign... not sure we want to go this route, but maybe that's an option to consider.

**Comment by vondele** [comment]
Meanwhile, after updating appveyor to use C++17, also MSVC doesn't provide aligned_alloc:
error C2039: 'aligned_alloc': is not a member of 'std'
They seem to provide a hack
https://docs.microsoft.com/en-us/troubleshoot/cpp/c2653-c2039-error-reference-function
maybe that is a workaround?

**Comment by mstembera** [comment]
I get errors as well.
MSVC 
w/ std::
Error	C2039	'aligned_alloc': is not a member of 'std'	
w/o std::
Error	C3861	'aligned_alloc': identifier not found

mingw/gcc 10.1.0 in Windows
w/ std::
error: 'aligned_alloc' is not a member of 'std'
w/o std::
error: 'aligned_alloc' was not declared in this scope

I tried the 
namespace std
{
    #include <cstdlib>
};
trick in various places w/o success.  I'm stuck for now.

**Comment by erbsenzaehler** [comment]
msvc does not support std::aligned_alloc. Instead we should use _aligned_malloc and _aligned_free

https://developercommunity.visualstudio.com/content/problem/468021/c17-stdaligned-alloc%E7%BC%BA%E5%A4%B1.html

I do not have a Windows installation to test this

**Comment by vondele** [comment]
So, it looks like we should implement wrappers std_aligned_malloc std_aligned_free that by default use C++17, but do the needed thing on windows and macos (and possibly other systems that don't fully support C++17). Anybody wants to try?

**Comment by vondele** [comment]
@daylen I have updated travis on the branch to use an osx image based on xcode12.

**Comment by vondele** [comment]
I have given the wrapper a try https://github.com/official-stockfish/Stockfish/pull/2839 it includes the makefile changes by @daylen it might not cover all cases yet (mingw ?).

**Comment by vondele** [comment]
@daylen the CI we have on osx is now green. I'll close this PR. Thanks for the input!

**Pull request closed without merging**
