### PR TITLE
Add some more information on the UCI protocol

### PR DESCRIPTION
**Pull request by vondele**
Improve README.md: provide a link, and document some non-standard options.

fixes https://github.com/official-stockfish/Stockfish/issues/3446

No functional change

### CODE REVIEW

**Comment by erbsenzaehler** [comment]
Two things I would like to bring up.

1)There is a newer version of the uci protocol available at https://www.shredderchess.com/download.html
Not sure what the differences are.
2)Could we start every section with a capital letter to keep consistency with the surrounding paragraphs?

**Comment by niklasf** [comment]
1) I recently created an HTML version of the latest text file, in case you'd like to use that: https://backscattering.de/chess/uci/
2) The sections are exactly the names of the commands.

**Comment by mstembera** [comment]
Nice.  Do we document anywhere how UCI commands can be passed directly to SF from the command line when launching it?

**Comment by vondele** [comment]
I've provided a link to the original document now, and fixed capitalization. Will merge shortly.

**Comment by Sopel97** [comment]
I really like @niklasf 's document. Maybe we could put it as `UCI.md` and link to it from the readme?

**Comment by vondele** [comment]
saw this a little too late. I decided to link to the original doc for now, I think that link has been around for many years, and somehow it is the original source for the protocol.

**Pull request closed without merging**
