### PR TITLE
Added COMP=icx, removed COMP=icc

### PR DESCRIPTION
**Pull request by maximmasiutin**
This pull request is same as https://github.com/official-stockfish/Stockfish/pull/4464 but also removes icc support.

It is alternative within the three following pull requests:
1) https://github.com/official-stockfish/Stockfish/pull/4464 - added icx, updated icc, added git params for Makefile (for Windows)
2) https://github.com/official-stockfish/Stockfish/pull/4468 - (current one) added icx, removed icc, added git params for Makefile (for Windows)
3) https://github.com/official-stockfish/Stockfish/pull/4474 - added icx, removed icc, modified the way to display git data for Makefile to work for Windows
4) https://github.com/official-stockfish/Stockfish/pull/4475 - added icx, removed icc, no changes to address the issues of git parameters in Makefile for Windows

### CODE REVIEW

**Review by ddobbelaere — COMMENTED** [review]
Why is this part that `GIT_SHA` and `GIT_DATE` can be overriden by environment variables sneaking in? I personally don't like it, as it's bound to lead to mistakes if set manually.

**Comment by maximmasiutin** [comment]
@ddobbelaere The Makefile uses shell commands on Windows to call git and extract these values, however, these shell commands do not work on Windows. So we use a script for Windows to call git, save these values to files, then read them as environment variables and call make:

```
git rev-parse --short HEAD 1>gitsha.txt
set /P GITSHA=< gitsha.txt
git show -s --date=format:'%Y%m%d' --format=%cd HEAD 1>gitdate.txt
set /P GITDATE=< gitdate.txt
make build -DGIT_SHA=%GITSHA% -DGIT_DATE=%GITDATE%
```

Alternatively, we have to find a way to make these commands to work from Makefile.

**Comment by maximmasiutin** [comment]
@ddobbelaere - Anyway, your concerns are justified. I also thought that way :-(

**Comment by maximmasiutin** [comment]
@ddobbelaere @vondele - I have addressed your concerns and disabled passing the parameters, making them automatically generating for Windows, but it required source code update - see the pull request https://github.com/official-stockfish/Stockfish/pull/4474

If you accept one of the pull requests, I will close the other two. Wanted to show alternatives.

**Comment by ddobbelaere** [comment]
Thanks for your efforts. To me, it just seemed more logical to address this part in a separate PR, as it is completely unrelated to the icx compiler. Maybe some other people can weigh in.

**Comment by maximmasiutin** [comment]
> Thanks for your efforts. To me, it just seemed more logical to address this part in a separate PR, as it is completely unrelated to the icx compiler. Maybe some other people can weigh in.

OK, I made a separate PR only to add icx and remove icc, without any Windows-related modifications to the makefile. Here it is: https://github.com/official-stockfish/Stockfish/pull/4475

**Comment by maximmasiutin** [comment]
A separte pull request to address Makefile issues is at https://github.com/official-stockfish/Stockfish/pull/4476

**Comment by maximmasiutin** [comment]
Closed, as there are alternative versions available, whilst this one will unlikely be accepted.

1. https://github.com/official-stockfish/Stockfish/pull/4464
2. https://github.com/official-stockfish/Stockfish/pull/4474
3. https://github.com/official-stockfish/Stockfish/pull/4475

**Pull request closed without merging**
