### PR TITLE
Show coordinate when displaying text board

### PR DESCRIPTION
**Pull request by nguyenpham**
I always feel difficult to board coordinate when working with chessboard even after many years. Showing coordinate on text board can help much, reduce mistakes, and frustrated for both newcomers and who are similar to me.

coordinate

### CODE REVIEW

**Comment by vondele** [comment]
@nguyenpham can you push another commit updating the AUTHORS file?

**Comment by Chess13234** [comment]
I have a function in Goldfish to print the entire board using wide characters, is there interest in using something like it(it also includes coordinates)?
It looks like this:
```
      PSQ Score:0.000000    8┃ｒ┃ｎ┃ｂ┃ｑ┃ｋ┃ｂ┃ｎ┃ｒ┃8
                             ┣━━╋━━╋━━╋━━╋━━╋━━╋━━╋━━┫
                            7┃ｐ┃ｐ┃ｐ┃ｐ┃ｐ┃ｐ┃ｐ┃ｐ┃7
                             ┣━━╋━━╋━━╋━━╋━━╋━━╋━━╋━━┫
                            6┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃6
                             ┣━━╋━━╋━━╋━━╋━━╋━━╋━━╋━━┫
                            5┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃5
                             ┣━━╋━━╋━━╋━━╋━━╋━━╋━━╋━━┫
                            4┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃4
                             ┣━━╋━━╋━━╋━━╋━━╋━━╋━━╋━━┫
                            3┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃3
                             ┣━━╋━━╋━━╋━━╋━━╋━━╋━━╋━━┫
                            2┃Ｐ┃Ｐ┃Ｐ┃Ｐ┃Ｐ┃Ｐ┃Ｐ┃Ｐ┃2
                             ┣━━╋━━╋━━╋━━╋━━╋━━╋━━╋━━┫
                            1┃Ｒ┃Ｎ┃Ｂ┃Ｑ┃Ｋ┃Ｂ┃Ｎ┃Ｒ┃1
                             ┣━━╋━━╋━━╋━━╋━━╋━━╋━━╋━━┫
Side To Move:WHITE            A  B  C  D  E  F  G  H
FEN:rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
____________________________________________________________________
```
https://github.com/Chess13234/Goldfish/blob/Goldfish/src/position.cpp#L74

**Comment by vondele** [comment]
@Chess13234 no, I wouldn't move to unicode for this.

**Comment by nguyenpham** [comment]
Updated AUTHORS as request :)

**Comment by vondele** [comment]
Thanks!

**Pull request closed without merging**
