### PR TITLE
Remove and replace DoubledIsolated penalty by Doubled

### PR DESCRIPTION
**Pull request by ElbertoOne**
The values for both penalties were very close, so DoubledIsolated can be removed and replaced by Doubled.

Passed STC (simplification): https://tests.stockfishchess.org/tests/view/5ec7c18e2a585b485af54407
LLR: 2.97 (-2.94,2.94) {-1.50,0.50}
Total: 105360 W: 20175 L: 20136 D: 65049
Ptnml(0-2): 1803, 12230, 24572, 12275, 1800

Passed LTC:
LLR: 2.94 (-2.94,2.94) {-1.50,0.50}
Total: 15440 W: 1978 L: 1877 D: 11585
Ptnml(0-2): 92, 1405, 4667, 1422, 134

Bench: 4862947

### CODE REVIEW

**Comment by vondele** [comment]
@ElbertoOne this will need the correct bench added to the commit messages for it to pass CI.

I will also wait with merging to see if any of the Elo gainers related to doubled pawns that are running right now pass.

**Comment by ElbertoOne** [comment]
@vondele I don't know why the tests are failing. When I run bench, the bench number as in the PR is shown (4862947). I added it to several commit messages.

**Comment by vondele** [comment]
@ElbertoOne I looks in the commit message for something in the form `Bench: 4862947` not just the number.

**Comment by locutus2** [comment]
@vondele 
My doubled tests so far failed all. I have further ideas but i will test them on top of this PR. So from my viwepoint you can commit this.

**Comment by vondele** [comment]
@locutus2 OK, I'll merge shortly.

**Comment by vondele** [comment]
Thanks!

**Pull request closed without merging**
