### PR TITLE
Values from an SPSA-session on king safety.

### PR DESCRIPTION
**Pull request by NicklasPersson**
STC:
ELO: 3.21 +-2.1 (95%) LOS: 99.8%
Total: 40000 W: 8181 L: 7812 D: 24007

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 47765 W: 8091 L: 7785 D: 31889

Bench: 8589262

### CODE REVIEW

**Comment by mcostalba** [comment]
Congrats! You are realy squeezing everything out of king safety :-)

I'd guess that * 31 / 256 instead of / 8 could be simplified....

**Comment by locutus2** [comment]
Congrats too!
I'am happy that my starting big king safety tuning is so fruitful and that you have the patience to tune again and again with success.

**Comment by NicklasPersson** [comment]
Thanks, your generalizations of Stormdanger and ShelterWeakness has really given some ELO by now.

**Comment by zamar** [comment]
approved.

Well done :)

**Pull request closed without merging**
