### PR TITLE
[WIP] Use a separate net for endgame

### PR DESCRIPTION
**Pull request by SFisGOD**
Use external eval file for endgame net

Bench: 3633561

### CODE REVIEW

**Comment by SFisGOD** [comment]
For testing appveyor

**Comment by vondele** [comment]
Sorry, this is not an acceptable patch. This adds 20MB for a O(1) Elo gain, duplicates all kind of stuff in Makefile, CI, breaks fishtest.  I'm fine with exploring ideas, and we'll learn from those experiments, but the final piece of software needs to be good.

**Comment by SFisGOD** [comment]
@vondele It's not my intention to convince you. Perhaps I should have commented that I'm not trying to convince you to commit this. I will do that next time in order to be more clear.

**Comment by vondele** [comment]
anyway, a patch in this direction needs a single net file, and corresponding updates on trainer.

**Comment by SFisGOD** [comment]
@vondele What if I can manage to produce a single net file. Will I wait for you guys to update the trainer?

**Comment by vondele** [comment]
It is not difficult to make it a single file (cat a.nnue b.nnue > c.nnue and adjust the reading code, probably hardly needed). Additionally, since these nets are identical except for the last few layers, makes no sense to duplicate things in this way.

It is important to have trainer and SF in sync if you aim long term. A trained must be directly usable in SF. If SF uses a different architecture, that architecture must be made available in the trainer.

**Comment by mstembera** [comment]
Keeping things in sync when we don't share the same files is much harder than it would be if we did.  I know it was decided only the player would be brought over initially as to do things in small steps.  Is it time to bring over the trainer?

**Pull request closed without merging**
