### PR TITLE
Clarify KRKP

### PR DESCRIPTION
**Pull request by protonspring**
This is a non-functional code style change.  I keep getting confused whether wksq is "white" king square of "weak" king square.

I find it much easier to read/understand with these variable names and without the normalize adjustments.  I did not test this because it makes exactly the same binary.

### CODE REVIEW

**Comment by snicolet** [comment]
Good idea! and using `rookSquare` and  `pawnSquare` would be logical then, I suppose.

**Comment by protonspring** [comment]
It's not really less code 'cause we're just moving the relative square work.  I can certainly understand if some prefer to normalize everything.   It's much easier for me without them and was curious if others felt the same way.

**Comment by protonspring** [comment]
Yes. . my binary is the same size, but there are small differences.  I will wait for a few opinions, and maybe test after TCEC stuff is done.

**Comment by protonspring** [comment]
I'm thinking about going through the endgames and making consistent and clear variable names like weakKing, strongKing, etc. .  Do you really prefer "pawnSquare" as opposed to "pawnSq?"  I think shorter is better, but I'll do whatever you like.

**Comment by snicolet** [comment]
Yes, I really prefer `pawnSquare` to `pawnSq`, especially if we have `strongSide`, `weakSide`, `strongKing`, `weakKing`, etc.  Once we have chosen a style, consistancy is important.

So it would be a nice project to rename all the variables (and do only renaming, let us work step by step) and then get feedback from the other people about this changes?

**Comment by protonspring** [comment]
ok. will do. thx.

**Pull request closed without merging**
