### PR TITLE
Add Microsoft Visual C++ build support

### PR DESCRIPTION
**Pull request by JackWright347**
Add full Microsoft Visual C++ 2019 support. It will build either "Windows x64 for Haswell CPUs" (the most go-to x64 version) or the old-fashioned "Windows 32 (x86)" configurations from Stockfish master with all necessary flags automatically. In addition, the correct NNUE evaluation file is automatically downloaded into the working directory of the built executable as a post-build step.

### CODE REVIEW

**Comment by NightlyKing** [comment]
I would prefer not to support every compiler that there is. GCC and clang produce the fastest binaries for our project and can easily be used in fishtest. Mingw works as well. Why would we burden ourselves with more and more compilers that we don't need? Time spent keeping all compilers working is time that isn't spent on improving Stockfish itself.
On that note, it would mean that the stuff that we already have in place for MVSC should be removed.

**Comment by Sopel97** [comment]
MSVC support is required for appveyor builds currently. But I agree we should either remove it completely or support it better. The reason why I don't like supporting MSVC that much is that it was always giving worse codegen and we never optimized for it.

**Comment by lucasart** [comment]
Doesn't MSVC++ have a compiler than can be used from the command line ? These `.vcxproj` and `.sln` files don't belong in the code base. They are not source files, but IDE config files. Once you accept that, people will want to commit editor config file for every editor & IDE out there...

**Comment by JackWright347** [comment]
You do not need an IDE. You don't even have to install it. 
For automation there are freely available build tools "Build Tools for Visual Studio"

These Build Tools allow you to build Visual Studio projects from a command-line interface.
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

Also available as Chocolatey software management automation package
https://community.chocolatey.org/packages/visualstudio2019buildtools

How to use Buildtools to compile .vcxproj and .sln from the command line without IDE
https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160

**Comment by vondele** [comment]
I also think we shouldn't merge such a patch. Probably with our CI now covering windows via msys2 (which is what we use to build and test on fishtest as well), we could consider removing appveyor.

**Pull request closed without merging**
