### PR TITLE
LMR Simplification

### PR DESCRIPTION
**Pull request by ElbertoOne**
LMR simplification that also gives a slight ELO gain, especially at LTC:

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 32402 W: 5967 L: 5866 D: 20569

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 15103 W: 2103 L: 1975 D: 11025

Bench: 8504941

### CODE REVIEW

**Comment by ElbertoOne** [comment]
Thanks everyone for the congratulations!

**Comment by mstembera** [comment]
Congrats!

**Comment by DamasClasicas** [comment]
Very nice! Congratulations!!

**Comment by mcostalba** [comment]
It took me a while to understand which was the simplification. Indeed the
only thing this patch does is to spare one std::max()

I can also commit it, more to reward the effort than for the actual
content. But please the PR should be squashed to a single commit (not 28!)
and rebased (not merged) above current master. Thanks.

**Comment by snicolet** [comment]
@ElbertoOne: just to help you with the rebasing/squashing part and the intricates of git, I usually find that the easiest strategy to generate a clean pull request before committing is basically to (a) synchronize my master branch with the one in official-stocking, (b) create a new minimal branch over that with just a clean state of my changes and (c) then create a new pull request. I know there may be smarter/trickier ways to do that with git, I just describe a pedestrian way:

(a) I use the script I gave in the following forum discussion to synchronize my master branch, maybe you could find it useful too (it avoids the messages "Merge remote-tracking branch 'refs/remotes/official" in your master branch):
https://groups.google.com/forum/#!msg/fishcooking/11XDIkvzw-0/V1iEtJMmBgAJ

(b) Just manually create the new branch, applying the final, clean state of the patch

(c) Create a new pull request from the new, clean branch. You can put a link to https://github.com/official-stockfish/Stockfish/pull/685 if you want to keep track of the original cheers and round of applause :-)

Hope this helps,
Stéphane

**Comment by ElbertoOne** [comment]
@snicolet Many thanks. I will do that.

**Pull request closed without merging**
