### PR TITLE
Skip quiet clean - Bench: 5900851

### PR DESCRIPTION
**Pull request by VoyagerOne**
If we can moveCountPrune and next quiet move has negative stats, then go directly to the next move stage (Bad_Captures). Reduction formula is tweaked to compensate for the decrease in move count that is used in LMR.

STC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 6847 W: 1276 L: 1123 D: 4448

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 48687 W: 6503 L: 6226 D: 35958

Bench: 5900851

### CODE REVIEW

**Comment by VoyagerOne** [comment]
@mcostalba 
@zamar 

I tidy up the code based on @snicolet suggestions.
Please merge this patch...so I can try out some ideas to approve on this.
The code is not set in stone...so reformatting / restructuring can always be apply later.
I believe this patch is around 4 ELO.

**Comment by VoyagerOne** [comment]
Not sure why the benches are not matching... :(

**Comment by MichaelB7** [comment]
excellent patch!

**Comment by anshulongithub** [comment]
Hi @VoyagerOne @Zamar since the bench of the original patch was different from the one that got committed, does that mean that the one that got committed was different from the original one? If yes, then will it be possible to find out that difference cuz then we won't be getting the actual effect of the original patch. 
Please confirm.

**Comment by snicolet** [comment]
@anshulongithub The bench was different because of the functional change commit of March 17.

**Comment by anshulongithub** [comment]
Thank you @snicolet for providing the reason for why the benches were different.

**Pull request closed without merging**
