### PR TITLE
Small clean-up, May 2021

### PR DESCRIPTION
**Pull request by xoto10**
Start with whitespace change

### CODE REVIEW

**Comment by xoto10** [comment]
Remove redundant variable:

```
diff --git a/src/evaluate.cpp b/src/evaluate.cpp
index 256bd9944..c3eb6e240 100644
--- a/src/evaluate.cpp
+++ b/src/evaluate.cpp
@@ -1132,15 +1132,14 @@ Value Eval::evaluate(const Position& pos) {
       Value psq = Value(abs(eg_value(pos.psq_score())));
       int   r50 = 16 + pos.rule50_count();
       bool  largePsq = psq * 16 > (NNUEThreshold1 + pos.non_pawn_material() / 64) * r50;
-      bool  classical = largePsq;
 
       // Use classical evaluation for really low piece endgames.
       // One critical case is the draw for bishop + A/H file pawn vs naked king.
       bool lowPieceEndgame =   pos.non_pawn_material() == BishopValueMg
                             || (pos.non_pawn_material() < 2 * RookValueMg && pos.count<PAWN>() < 2);
 
-      v = classical || lowPieceEndgame ? Evaluation<NO_TRACE>(pos).value()
-                                       : adjusted_NNUE();
+      v = largePsq || lowPieceEndgame ? Evaluation<NO_TRACE>(pos).value()
+                                      : adjusted_NNUE();
 
       // If the classical eval is small and imbalance large, use NNUE nevertheless.
       // For the case of opposite colored bishops, switch to NNUE eval with small

```

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/nnue/evaluate_nnue.cpp#L171
add some comments there like 
// if difference in non pawn material is less or equal to difference between a bishop and a knight make positional features more important
This sounds kinda long though so if anyone can come up with smth better it would be nice :)

**Comment by pb00068** [comment]
This was not considered (nor commented) in the last small cleanups (April) so I]m reposting this with some comment more:

Pull #3458 removed the only usage of pos.see_ge() moving pieces that don't belong to the side to move.
Thus now also the implementation of see_ge can be simplified by replacing line 1081
Color stm = color_of(piece_on(from));
with
Color stm = sideToMove; 

This should save some instructions and since see_ge is on the 'hot path' I think it's a good simplification.
Maybe we should leave some comment for the case someone likes to use see_ge for escape-detection again
(in past in LMR after do_move(move) we used pos.see_ge(reverse_move(move)) to detect if the played move actually escapes a capture)

**Comment by BM123499** [comment]
Now that `Search::init()` is not dependent on Threads parameters anymore, it can be moved from `threads.cpp` to `main.cpp`.

**Comment by BM123499** [comment]
This condition:
https://github.com/official-stockfish/Stockfish/blob/f193778446acc6e60d7f0f99c6eb01489f89e962/src/search.cpp#L862

is similar to this condition:
https://github.com/official-stockfish/Stockfish/blob/f193778446acc6e60d7f0f99c6eb01489f89e962/src/search.cpp#L1060

So it can be transformed into a comment

**Comment by xoto10** [comment]
> https://github.com/official-stockfish/Stockfish/blob/master/src/nnue/evaluate_nnue.cpp#L171
> add some comments there like
> // if difference in non pawn material is less or equal to difference between a bishop and a knight make positional features more important
> This sounds kinda long though so if anyone can come up with smth better it would be nice :)

Yeah, I don't find those lines easy to read, but a comment like that just seems to duplicate the code, so I don't think it gains anything.
I would name the A and B variables materialist and positional and keep psqt and output[0] in the calculation of sum, that would remove a couple of variables and a blank line and maybe make it a bit easier to grok.
But we all have different opinions sometimes, so my default thinking at the moment is to just leave it alone ... :-)

**Comment by xoto10** [comment]
> This was not considered (nor commented) in the last small cleanups (April) so I'm re-posting this with some comment more:
> 
> Pull #3458 removed the only usage of pos.see_ge() moving pieces that don't belong to the side to move.
>  ...

Too hard for me, perhaps create a separate pr to discuss it? (unless maintainers have anything they want to say?)

**Comment by snicolet** [comment]
Makefile, line 91, the example should read:
```
make build ARCH=x86-64-avx512 debug=yes sanitize="address undefined"
```

See comments in https://github.com/official-stockfish/Stockfish/pull/3524

**Comment by Vizvezdenec** [comment]
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1135
add comments to what it does.
//Decrease reduction for PvNodes

**Comment by Lolligerhans** [comment]
**evaluate.cpp:462** Identifier `targets` no longer matching the bonus name. I suggest renaming to `contestants`.

**Comment by snicolet** [comment]
In Makefile:

- replace `### 3.5 prefetch` by `### 3.5 prefetch and popcount` in line 514
- remove the comment in line 523 (ie remove `### 3.6 popcnt`)
- add the following comment in line 533: `### 3.6 SIMD architectures`

**Comment by gvreuls** [comment]
Add ``Andreï Vetrov (proukornew)`` to AUTHORS. He was removed when #3463 was reverted but not readded when #3569 was accepted.

**Comment by Sopel97** [comment]
the name `eval_file_loaded` in evaluate.h and evaluate.cpp defies the convention

**Comment by bknox83** [comment]
The references to contempt should probably be renamed to "trend" per #3575 to avoid any confusion.

- evaluate.cpp line 1141
   - `pos.this_thread()->trend = SCORE_ZERO; // Reset any dynamic contempt`

- search.cpp line 361
   - `// Adjust trend based on root move's previousScore (dynamic contempt)`

**Comment by pb00068** [comment]
search.cpp 

- line 1333 convert/simplify

    `ss->ttPv = ss->ttPv || ((ss-1)->ttPv && depth > 3);`
    to
    `ss->ttPv |= (ss-1)->ttPv && depth > 3;`

- line 1337 convert/simplify

   `ss->ttPv = ss->ttPv && (ss+1)->ttPv;`
   to
   `ss->ttPv &= (ss+1)->ttPv;`

**Comment by pb00068** [comment]
Comment about lowply/history in movepick.h line 92:

`/// .. It is cleared with each new search and filled during iterative deepening.`

This description is not accurate anymore since pull #2688,
more correct would be something like this:

`/// LowPlyHistory get populated during iterative deepening and at each new search the data get shifted down by 2 plies`

**Comment by xoto10** [comment]
> search.cpp
> 
> * line 1333 convert/simplify
>   `ss->ttPv = ss->ttPv || ((ss-1)->ttPv && depth > 3);`
>   to
>   `ss->ttPv |= (ss-1)->ttPv && depth > 3;`
> * line 1337 convert/simplify
>   `ss->ttPv = ss->ttPv && (ss+1)->ttPv;`
>   to
>   `ss->ttPv &= (ss+1)->ttPv;`

I'm not 100% sure these are ok for this PR, does anyone have any comments?

**Comment by Sopel97** [comment]
> 
> 
> search.cpp
> 
>     * line 1333 convert/simplify
>       `ss->ttPv = ss->ttPv || ((ss-1)->ttPv && depth > 3);`
>       to
>       `ss->ttPv |= (ss-1)->ttPv && depth > 3;`
> 
>     * line 1337 convert/simplify
>       `ss->ttPv = ss->ttPv && (ss+1)->ttPv;`
>       to
>       `ss->ttPv &= (ss+1)->ttPv;`

It should be okay, since it forces a conversion from bool to int which are guaranteed to be 0 or 1 for false or true respectively. It's common to use bitwise operators instead of logical ones to remove the short circuiting (though compilers sometimes do it themselves when possible like GCC above). Sometimes it's beneficial if it changes the logical value pattern to be more predictable during execution. However it is error prone due to different operator precedence, and hidden conversions to int that need to be taken into account and may result in silent errors where operands are not already boolean. Personally I wouldn't bother with this unless someone did it for the whole codebase and compared the results with some profiler.

**Comment by G-Lorenz** [comment]
I think that this line is redundant:
https://github.com/official-stockfish/Stockfish/blob/237ed1ef8fddea77779e7fdcde8e4195d92f123b/src/search.cpp#L1049
since the condition is already checked here:
https://github.com/official-stockfish/Stockfish/blob/237ed1ef8fddea77779e7fdcde8e4195d92f123b/src/search.cpp#L956-L961

**Comment by xoto10** [comment]
move and excludedMove will be different sometimes with excludedMove set ? I think ?

**Comment by pb00068** [comment]
@G-Lorenz I think line 1049 is, as the comment says, effectively needed to avoid recursive singular search.
Also bench changes when you run and compare it with higher depths ;-)

**Comment by G-Lorenz** [comment]
You are right.
My implementation avoids "pure" recursive singular search (i.e. same move analysed over and over) but performs it when `move!=excludedMove`. It happens, as @pb00068 has proved (Thanks! :-) ). The fact that bench doesn't change at default depth misled me.
I'm going to test it on fishtest.

**Comment by Sopel97** [comment]
the `+1` in https://github.com/official-stockfish/Stockfish/blob/dabaf2220fe0c77400a5f71a91952f510e6a126b/src/nnue/nnue_feature_transformer.h#L391 should be moved to https://github.com/official-stockfish/Stockfish/blob/dabaf2220fe0c77400a5f71a91952f510e6a126b/src/nnue/features/half_ka_v2.cpp#L74, as it tries to approximate the exact function
```
  int HalfKAv2_hm::update_cost(StateInfo* st) {
    int cost = 0;
    for (IndexType i = 0; i < st->dirtyPiece.dirty_num; ++i) {
      cost += st->dirtyPiece.from[i] != SQ_NONE;
      cost += st->dirtyPiece.to[i] != SQ_NONE;
    }
    return cost;
  }
```
Using the exact function is worse, it's slower and reduces the number of ft feature updates by just 0.0001%. The approximation with +1 is ok, though it's less than the actual number of updates for castling moves, but this is fine because there's no such realistic scenario where `removed.size() + added.size()` being 34 (potentially reached when both sides castle) would mean `removed.size() > 32 || added.size() > 32`

**Comment by xoto10** [comment]
@vondele 
I've just realised this PR is still here, quite some time after being started! I have only included the proposed changes that I was comfortable with in the branch, these should all have a 👍 from me on the original comment. Currently all as separate commits, although obv I can squash to 1 commit when required.
Do you want to have a look down the list of commits (or unimplemented suggestions)? How do you want to proceed?

**Comment by vondele** [comment]
yes, I should merge this on a next occasion. Could you base it on master and make sure CI passes, right now fails because of an inconsistent bench.

**Comment by amchess** [comment]
another small cleanup:
in evaluate.cpp, line 1088
I propose to replace 
if (!Eval::useNNUE)
with
if (useNNUE)
because this variable has been already initialized in the init method.

**Pull request closed without merging**
