### PR TITLE
Do not store thisThread in pos.

### PR DESCRIPTION
**Pull request by vondele**
to describe the position, thread information is not needed. Remove it from Position and instead make it available as a thread_local variable, which simplifies both accessing this information, as well as constructing positions.

No functional change.

### CODE REVIEW

**Comment by vondele** [comment]
seem it needs so debugging.

**Comment by vondele** [comment]
ugh, and a compiler that supports C++11 on iOS....

**Comment by vondele** [comment]
As this patch effectively bumps the required xcode version to 8 on OS X this might need some additional discussion. xcode 8 has been released sept. 2016.

**Comment by mcostalba** [comment]
thread_local was a clear speed regression when I have tried it some time ago, actually I've tried it twice in the last 3 years and always was a regression.

**Comment by vondele** [comment]
@mcostalba with threads 1 it seems a little faster in my local testing.

How do you suggest to test speed with Threads > 1 ... a regular regression test or [-4,0] or .. ?

**Comment by mcostalba** [comment]
@vondele why [-4, 0] ? Regression are tested with [-3, 1].

But first I suggest you do some local test on your PC so you get an idea. I am quite confident that with gcc 5 compilers we have a regression.

**Comment by vondele** [comment]
@mcostalba I tested with gcc 5 locally, but I'll have a look on a different machine as well. 

@zamar recently requested a [-4,0] test http://tests.stockfishchess.org/tests/view/59097a720ebc59035df3422f which I assume was to reduce the cost. However, I have no problem to run at [-3,1]

**Comment by snicolet** [comment]
I don't like it that this patch prevents me from compiling Stockfish on my 3 years old Mac.

**Comment by joergoster** [comment]
@vondele Could you also have a look at #1101 ? Thanks.

**Comment by vondele** [comment]
I have tested and find a speedup of 0.2% with gcc 5.4 on ubuntu. I added http://tests.stockfishchess.org/tests/view/590d928d0ebc59035df3434c to check further.

**Comment by vondele** [comment]
@snicolet is it possible to 'easily' upgrade xcode on such a system or does it need a full OS upgrade.

**Comment by mcostalba** [comment]
@vondele test should be smp not single thread.

**Comment by vondele** [comment]
@mcostalba even in the single thread case the TLS lookup happens since SF always has two threads, no ? However, it makes sense to also test with more threads, will add a further test.

**Comment by lucasart** [comment]
@vondele: I tried that already and the PR was rejected. Agree that thread_local is the right solution from the pov of code organization. And it works perfectly fine on Linux (and probably Android and MacOSX). The problem was that TLS lookup sucks horribly on Windows. Until Windows improves and is able to implement a zero cost TLS model, we can't use it. So it's really a Windows test you need.

**Comment by vondele** [comment]
@lucasart I agree that it looks like a windows problem. But interestingly, the bigpen0r-15cores worker is not only contributing to the loss win difference a lot, but also displays crashes.

**Comment by vondele** [comment]
Just to have the hard numbers, I went through all results separated them wrt to Linux / Windows (most workers were still online). 

1 Thread:
http://tests.stockfishchess.org/tests/view/590d928d0ebc59035df3434c
  Linux:
    Total:  10253  W:  1815  L:  1885  D:  6553
    elo =   -2.372 +-    4.034 LOS:   12.5%

  Windows:
    Total:  1491  W:  218  L:  317  D:  956
    elo =  -23.103 +-   10.533 LOS:    0.0%

5 Threads:
http://tests.stockfishchess.org/tests/view/590d9b200ebc59035df3434f
  Linux:
    Total:  4080  W:  564  L:  593  D:  2923
    elo =   -2.470 +-    5.669 LOS:   19.7%

  Windows:
    Total:  2693  W:  327  L:  457  D:  1909
    elo =  -16.785 +-    7.059 LOS:    0.0%


It might also be that the detour via mingw makes the thread_local number look worse on windows than they are supposed to be.

So, this form of the patch is not acceptable. I'll leave it open for a while, in case there are further comments / insights.

**Pull request closed without merging**
