### PR TITLE
Update Makefile (#2731)

### PR DESCRIPTION
**Pull request by unaiic**
Clean and organize uppercase and spaces; also set 64 bit as standard

### CODE REVIEW

**Comment by stockchess** [comment]
suggest add -flto change  #2731

**Comment by unaiic** [comment]
Ok, will take a look at it.

**Comment by unaiic** [comment]
Could someone please check that it works for MinGW with `-flto` under Windows?

**Comment by stockchess** [comment]
works great with mingw/mys2 thx

**Comment by unaiic** [comment]
It is ready then. Thank you too!

**Comment by unaiic** [comment]
@vondele As they reference the same file, could it be merged along with #2760 as one?

**Comment by vondele** [comment]
Thanks... try to keep PRs limited to one item, and of code you have written specifically, that makes it easier for me to merge.

**Comment by unaiic** [comment]
Ok, got it. Thank you for your time and patience!

**Pull request closed without merging**
