### PR TITLE
Give a reduced bonus for threats by hanging pawns

### PR DESCRIPTION
**Pull request by ajithcj**
Give a reduced bonus for threats by hanging pawns
Passed STC:
LLR: 2.96 (-2.94,2.94) [-1.50,4.50]
Total: 105539 W: 20389 L: 20001 D: 65149

and LTC:
LLR: 2.95 (-2.94,2.94) [0.00,6.00]
Total: 9629 W: 1577 L: 1432 D: 6620

### CODE REVIEW

**Comment by zamar** [comment]
Makes sense to me.

approved.

**Comment by glinscott** [comment]
Interesting, I guess if the pawn is hanging, there is a lot of complexity still to be resolved by the qsearch.  Nice idea!  Approved :).

**Comment by mcostalba** [comment]
This patch is really badly formatted. I would like to ask the maintainers to please enforce people to, at least, format correctly their patches before to open a pull request. It is not correct quickly bunch up stuff relying on 'someone' that will do it later. If we have a lot of people working on SF it is _also_ because code is kept clean and readable, but this not comes automatically. Thanks.

**Comment by ajithcj** [comment]
@mcostalba, I have raised a separate pull request for better formatting and comments.

**Pull request closed without merging**
