### PR TITLE
Avoid unnecessary string copies

### PR DESCRIPTION
**Pull request by UniQP**
No functional change

### CODE REVIEW

**Comment by Disservin** [comment]
Why not string_view ?

**Comment by UniQP** [comment]
> Why not string_view ?

In all 3 cases, we already have a `string` object at hand, so there's no point in creating a `string_view`.

**Comment by snicolet** [comment]
This is optimizing code which is not in the hot path

**Comment by dubslow** [comment]
`const` references good, an extra `std::move` is less good

**Comment by UniQP** [comment]
> so let's keep the const, skip the std::move. Can you update the PR?

Done.

**Pull request closed without merging**
