### PR TITLE
Optimize make_index() using templates and lookup tables

### PR DESCRIPTION
**Pull request by mstembera**
https://tests.stockfishchess.org/tests/view/634517e54bc7650f07542f99
LLR: 2.94 (-2.94,2.94) <0.00,2.00>
Total: 642672 W: 171819 L: 170658 D: 300195
Ptnml(0-2): 2278, 68077, 179416, 69336, 2229 

A similar version also tested yellow here:
https://tests.stockfishchess.org/tests/view/634516a34bc7650f07542f56

No functional change
bench: 4156027

### CODE REVIEW

**Comment by mstembera** [comment]
I don't understand why the 32 bit link step fails.  If anybody has any idea please let me know.  I already tried force pushing to run it again but it failed again.

**Comment by Disservin** [comment]
I dont know why it fails but I think you forgot to remove `    // Orient a square according to perspective (rotates by 180 for black)
    static Square orient(Color perspective, Square s, Square ksq);` from `half_ka_v2_hm.h` but this is probably not the reason it fails

**Comment by mstembera** [comment]
@Disservin Thanks for catching that.  It's now removed.  However as you suspected it still fails.

**Comment by Disservin** [comment]
I also find it weird that the Explicit template instantiations is before the definition, usually they come afterwards but I think this makes no difference. Maybe try to move the template definition into the header ? I also dont see why embedding `EmbeddedNNUEData` fails mhhh very weird

**Comment by Disservin** [comment]
btw you can test the ci in your own fork, just push to master and disable all the other CI checks its both faster and I think more convient

**Comment by mstembera** [comment]
@Disservin I moved the instantiations after the definitions as you suggested.  That also matches what we do in pawn.cpp and movegen.cpp.  Also tested moving the definitions to the header but that generates "undefined reference" linker errors even for 64 bit targets.   Also of note is that the x86-32 build works but only the general-32 doesn't.  Really weird since I didn't touch gEmbeddedNNUESize or gEmbeddedNNUEData or anything in evaluate.cpp or incbin.

**Comment by Disservin** [comment]
Yea right very weird, with templates that you want to use elsewhere (in a different file) you either have to write the definition in the header or define the instantiations in the cpp, doing both won’t work. I also ran master ci again locally which doesn’t fail and my pr also didn’t fail … I also don’t know what could break it at this point

**Comment by Disservin** [comment]
very intersting... that `-flto` breaks the compilation on 32 in this case

**Comment by mstembera** [comment]
@Disservin Yes.  It looks like there were issues with -flto and incbin from the beginning.  See https://github.com/official-stockfish/Stockfish/pull/3070
@vondele @snicolet Please advise on how you wish to proceed w this -flto issue.

**Comment by MinetaS** [comment]
Can you add `-ffat-lto-objects` to CXXFLAGS for gcc/mingw and test again with LTO?

(It's an old workaround in 2014 and may not work with this case though)

**Comment by mstembera** [comment]
@MinetaS Thanks for the suggestion.  It fails the same as before.

**Comment by MinetaS** [comment]
I wonder how this hasn't broken the entire codebase yet.
INCBIN uses top-level inline assembly which is totally not compatible with LTO.
We were lucky that INCBIN definition and the usages of symbols are located in one partition; however this patch might break that implicit assumption, probably due to templates.

The simple solution would be putting either `-flto-partition=one` or `flto-partition=none`.
This can take away vondele's temporary solution as well - which removed LTO for i386 architectures.

But I don't know much about LTO, so it may be required to test if it degrades performance.

**Comment by mstembera** [comment]
@MinetaS Thank you again!  I can confirm that adding ```-flto-partition=one``` after the -flto gets rid of the issue.  On my machine speed remains unaffected while the resulting binary is about 28K bigger for bmi2 builds.   I pushed the new Makefile.

**Comment by MinetaS** [comment]
Yes, different partitioning algorithms in WPA phase produce different binary.
Still I wanted to make sure performance impact is negligible.

Non-regression STC is currently in place now:
https://tests.stockfishchess.org/tests/view/634aacf84bc7650f0755188b

The test is running around -0.7~-1.0 Elo but will likely end with blue.

**Comment by mstembera** [comment]
@vondele Thanks for merging.  FYI, I only changed the one -flto place in the Makefile to make this patch pass but the proper full fix is what @MinetaS tested here https://tests.stockfishchess.org/tests/view/634aacf84bc7650f0755188b  I assume he will open a PR.

**Comment by vondele** [comment]
I see, yes, probably best to have a PR with @MinetaS full fix.

**Pull request closed without merging**
