### PR TITLE
Simplify Connected Pawn Scoring

### PR DESCRIPTION
**Pull request by protonspring**
This is a functional simplification that simplifies connected scoring of pawns.

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 37472 W: 8318 L: 8228 D: 20926 
http://tests.stockfishchess.org/tests/view/5cae74ef0ebc5925cf00f8a5

LTC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 43035 W: 7366 L: 7281 D: 28388 
http://tests.stockfishchess.org/tests/view/5caea3b50ebc5925cf00fe1e

bench 3494958

### CODE REVIEW

**Comment by mcostalba** [comment]
If I rewrite your formula as:

`int v = phalanx ? 3 * Connected[r] :  2 * Connected[r];`

and I compare it with master:

`int v = phalanx ? Connected[r] + Connected[r + 1] :  2 * Connected[r];`

This smells a lot like a parmeter tweak to me.

**Comment by protonspring** [comment]
Here are a few things I like about this:
1) The conditional is removed.
2) 3 * Connected[r], is more simple than Connected[r] + Connected[r+1] because we only need to access the array once.
3) limiting access to the Connected array for the current rank of the pawn.  Using Connected[] values for RANK_8 for pawns on RANK_7 is a bit strange.
4) The strange inverted values of master's Connected ranks 3 and 4 are fixed.
5) It's prettier. :)

The changes to the connected array values are only to allow this simplification and be as close to master as possible.

**Comment by ddugovic** [comment]
I like that this patch uses fewer symbols (although the ternary operator was OK and I don't understand its removal).

(I trust that a modern compiler optimizes `Connected[r] + Connected[r+1]` in terms of array accesses.)

**Comment by mcostalba** [comment]
@protonspring ok. What do you think of:

`int v = (phalanx ? 3 : 2) * Connected[r];`

**Comment by protonspring** [comment]
No problem at all with that.  Should i update the branch?

**Comment by Rocky640** [comment]
`int r = relative_rank(Us, s);` could be moved near `File f = file_of(s);`
 and line 120 can become
` else if (stoppers == square_bb(s + Up)  && r >= RANK_5) `

**Comment by Rocky640** [comment]
It will compile with
`int v = Connected[r] * (phalanx ? 3 : 2);`

**Comment by mstembera** [comment]
```int v = (phalanx ? 3 : 2) * Connected[r];```
has a branch where as 
```int v = (2 + bool(phalanx)) * Connected[r];```
does not.

**Comment by protonspring** [comment]
Yes.  That's why I did it that way first.  I presume an addition is faster than a ternary '?' . . correct?

**Comment by mstembera** [comment]
Yes generally that is the case.

**Comment by mstembera** [comment]
@mcostalba Do you mind if we go with the branchless version?

**Comment by 31m059** [comment]
@protonspring @mstembera If I had to guess, I would say that a compiler can optimize `boolean_variable ? constant1 : constant2` easily.  But I'm not sure how to check.

**Comment by vondele** [comment]
this obviously yields the same code:
https://godbolt.org/z/PZjAr6

**Comment by ddugovic** [comment]
Ah, those compiler flags `-O3 -march=native -mbmi2` (in Makefile) were what I overlooked (when I tried the same on Compiler Explorer).  Even `-O2 -march=native -mbmi2` produces the same assembly.

**Comment by mstembera** [comment]
@vondele Thanks for the link.  I'm now indifferent to which version gets used.

**Comment by mcostalba** [comment]
Merged with a2cdb6e5d2b33de

@vondele thanks for the godbolt.org link, didn't know it. Awsome!

**Pull request closed without merging**
