### PR TITLE
Magic::index()

### PR DESCRIPTION
**Pull request by mstembera**
Make magic_index() a member of Magic since it uses all it's members and keep us from having to pass the function pointer around to init_magics().
No functional change.
bench: 5725676

### CODE REVIEW

**Comment by mstembera** [comment]
Maybe we could go further and make init_magics() a static member function of Magic and the RookMagics and BishopMagics arrays static variable members of Magic.  Comments?

**Comment by mcostalba** [comment]
@mstembera it's fine for me, Instead moving RookMagics and BishopMagics inside the classs does not seem a good idea to me...

**Comment by snicolet** [comment]
Do we have any speed information for this patch?

**Comment by mstembera** [comment]
@snicolet  I measure no meaningful difference.
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    992463    993607    -1144     
    StDev   88118     86979     4210      

p-value: 0.607
speedup: 0.001
```

**Comment by snicolet** [comment]
@mstembera 
Thanks for testing this. I get the same conclusion (indistinguishable speeds) on my system.

**Comment by MichaelB7** [comment]
Ditto here , I get about the same conclusion on my system - maybe 0.1% faster.  Patch is fine.

**Pull request closed without merging**
