### PR TITLE
Lazy smp log

### PR DESCRIPTION
**Pull request by IIvec**
The SPRT LTC test on 3 threads was like this:

LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 25653 W: 3730 L: 3521 D: 18402

The ELO STC test on 3 threads was like this:

ELO: 6.79 +-3.4 (95%) LOS: 100.0%
Total: 13716 W: 2435 L: 2167 D: 9114

The ELO STC test on 23 threads was like this:

ELO: 0.77 +-5.3 (95%) LOS: 61.1%
Total: 4970 W: 765 L: 754 D: 3451

and it's maybe a good time to include this to master to simplify further testings.
Of course, if accepted i ask mbootsector to be credited as the author.

### CODE REVIEW

**Comment by jcalovski** [comment]
Correct me if i'm wrong but this pull request should be against the lazy_smp branch

**Comment by IIvec** [comment]
Thank you jcalovski! I opened both pull requests and let maintainers decide.

**Comment by mcostalba** [comment]
Sorry but it does not work like this.

If you want to open a pull request the test should be of SPRT type, please
read fishtest testing rules.

**Comment by IIvec** [comment]
OK.

**Comment by mcostalba** [comment]
Applied.

**Pull request closed without merging**
