### PR TITLE
Assorted Trivial Fixes and simplifications - Nov, 2019

### PR DESCRIPTION
**Pull request by protonspring**
Moving all piece values to constexpr.

LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 20229 W: 4418 L: 4294 D: 11517 
http://tests.stockfishchess.org/tests/view/5db6c8f00ebc5902d1f36a99

### CODE REVIEW

**Comment by protonspring** [comment]
Can I add this in?  We don't need to check for Pt == BISHOP again.

https://github.com/protonspring/Stockfish/tree/ps_bishops7

**Comment by protonspring** [comment]
this one?

https://github.com/protonspring/Stockfish/compare/e8fca71...6046024

**Comment by protonspring** [comment]
This one?
https://github.com/protonspring/Stockfish/tree/ps_squarebb104

**Comment by Lolligerhans** [comment]
`evaluate.cpp:128` Line contains only whitespace.

**Comment by protonspring** [comment]
@Lolligerhans Yes. Line 128 in evaluate.cpp is a blank line.  I see nothing else in my version.  Could you be more specific?

**Comment by Rocky640** [comment]
@protonspring he means in the latest commit  "Rank-based outpost" there are some useless white spaces

**Comment by protonspring** [comment]
I'm good with that and will implement something as soon as the overlords give the go-ahead.

**Comment by Lolligerhans** [comment]
The psqt `Bonus` array can be hidden to avoid confusion with the `psq` array https://github.com/Lolligerhans/Stockfish/commit/270a36d2186ad86343f375a441b8021ed4721419

**Comment by Chess13234** [comment]
Can this be added?
https://github.com/Chess13234/Stockfish/commit/6d06bb03bff01d4b4d5e5f8ed6ea85a8298ff792

**Comment by Lolligerhans** [comment]
The tt cluster size can be derived from the entry size to allow for easier changes in the entry structure.
https://github.com/Lolligerhans/Stockfish/commit/0dd81409a852dcf1b719bad91720e26435c7c044

- I also moved the code into the `Cluster` struct.
- You may omit some of my additional `static_assert()`s.
- The division does not find the smallest possible clustersize, but I assume it is good enough.
- Added comment on top of the `struct Cluster`

**Comment by Lolligerhans** [comment]
Fixed namespaces and asserts: https://github.com/Lolligerhans/Stockfish/commit/1a4fd45ebe74051154b71b85e9ccc8840f77c198

**Comment by Chess13234** [comment]
Popcnt16 can be isolated for space and init time savings.
https://github.com/official-stockfish/Stockfish/compare/master...Chess13234:PopCNT16_ifndef

**Comment by Lolligerhans** [comment]
The various `#define S(mg,eg) make_score(mg,eg)` can be replaced with `constexpr auto S = make_score;`. This is easier to understand and modify (both when modifying `S` and `make_score`) and less dangerous. Remember to also remove the `#undef S`s.

In psqt.cpp the surrounding namespace can be unnamed (as suggested previously) (in the other instances they already are).

**Comment by Lolligerhans** [comment]
using `constexpr mg_value()` and `constexpr eg_value()` (rather than inline) allows for `constexpr operator*` and `constexpr operator/` (for Score).

This can help defining new bonuses more naturally and may be used for example in outposts where both operands are compiletime constants:
`
score += Outpost * (Pt == KNIGHT ? 2 : 1);
`
Possible implementations could look like this: https://github.com/official-stockfish/Stockfish/compare/master...Lolligerhans:constexpr. There is a version w/ template class and another w/ template member function. The template parameter is the Phase to extract (MG/EG). These Versions are a bit longer in code but somewhat better to read and modify.
At last I added a version changing style as little as possible, even removing two lines.

Since they introduce some class shenanigans at least the two longer version should probably be tested in a non-regression (or similar) before being merged.

**Comment by protonspring** [comment]
> 
> 
> Popcnt16 can be isolated for space and init time savings.
> [master...Chess13234:PopCNT16_ifndef](https://github.com/official-stockfish/Stockfish/compare/master...Chess13234:PopCNT16_ifndef)

I've suggested this before, but it was deemed too messy.

**Comment by protonspring** [comment]
My I replace all of the (Us == WHITE ? BLACK : WHITE) with a simple ~Us ?

**Comment by Lolligerhans** [comment]
I find it difficult to read lines with `Us` and `~Us` but much easiert to define `Them = ~Us` first.

**Comment by Lolligerhans** [comment]
evaluate.cpp:789
For the early exit test, the values of `mg `and `eg` are averaged:
`(mg_value(score) + eg_value(score)) / 2`
The division seems obsolete when LazyThreshold is doubled and the subsequent division `pos.non_pawn_material() / 64` is adjusted to `pos.non_pawn_material() / 32`.

**Comment by protonspring** [comment]
> 
> 
> Using `constexpr mg_value()` and `constexpr eg_value()` (rather than inline) allows for `constexpr operator*` and `constexpr operator/` (for Score).
> 
> This can help defining new bonuses more naturally and may be used for example in outposts where both operands are compile time constants:
> `score += Outpost * (Pt == KNIGHT ? 2 : 1);`
> 
> Possible implementations could look like this: [master...Lolligerhans:constexpr](https://github.com/official-stockfish/Stockfish/compare/master...Lolligerhans:constexpr). There is a version w/ template class and another w/ template member function. The template parameter is the Phase to extract (MG/EG). These Versions are a bit longer in code but somewhat better to read and modify.
> At last I added a version changing style as little as possible, even removing two lines.
> 
> Since they introduce some class shenanigans at least the two longer version should probably be tested in a non-regression (or similar) before being merged.

I actually like this, but I'll need weigh-in from a maintainer before I add it to this branch.

**Comment by adentong** [comment]
@snicolet Maybe we should merge this since it's December already.

**Comment by protonspring** [comment]
I could also "typedef Value V" which would replace all of the #define Value V and #undef V's.

**Comment by Rocky640** [comment]
line 665 tbprobe.cpp just use
squares[i] ^= 56; // Vertical flip: SQ_A8 -> SQ_A1

line 354 types.h just use
return Square(s ^ 56); // Vertical flip SQ_A1 -> SQ_A8

I don't think we need to define special constant for this or other mirror/color operator.
It is just a formula like any other.

**Comment by Rocky640** [comment]
tbprobe.cpp, comment near line 803 shoudl read as follow


```
    // swapped and still get the same position).
    //
    // In case we have at least 3 unique pieces (including kings) we encode them

```

**Comment by Rocky640** [comment]
similar to endgame.cpp
 bool verify_material

we can, in position.cpp use
```
#ifndef NDEBUG
bool Position::pos_is_ok() const {
    constexpr bool Fast = true; // true (default) or false (full verification) ?
...
}
#endif
```

and change declarations in position.h as follow
```
 void flip();

  // Position consistency check, for debugging
  #ifndef NDEBUG
  bool pos_is_ok() const;
  #endif
```

**Comment by protonspring** [comment]
Should that be an #ifdef instead of an #ifndef ?

**Comment by Rocky640** [comment]
line 236 movegen,cpp
` if (Type != CAPTURES && pos.can_castle(CastlingRights(OO | OOO)))`
can be replaced with
` if (Type != CAPTURES && pos.can_castle(ANY_CASTLING))`

**Comment by Rocky640** [comment]
position.h


```
inline bool Position::castling_impeded(CastlingRights cr) const {
  return byTypeBB[ALL_PIECES] & castlingPath[cr];
}

inline Square Position::castling_rook_square(CastlingRights cr) const {
  return castlingRookSquare[cr];
}

```

not a big deal, maybe we should add an assert
because castlingPath and castlingRookSquare can only be one of
WHITE_OO, WHITE_OOO,BLACK_OO, BLACK__OOO

(they are undefined for any castling combination or 0)

**Comment by Rocky640** [comment]
Thanks, please do the same in
`inline bool Position::castling_impeded(CastlingRights cr) const {`

**Comment by Rocky640** [comment]
followup to #2467 
in search.cpp, replace
`// Update pawn hash key and prefetch access to pawnsTable`

to
`// Update pawn hash key`

**Comment by protonspring** [comment]
@Rocky640 I assume you meant line 855 in position.cpp.  Let me know if I am mistaken.

**Comment by Chess13234** [comment]
In bitboard.h there is line 387
#else  // Compiler is neither GCC nor MSVC compatible

#error "Compiler not supported."

Yet earlier at line 299
#ifndef USE_POPCNT
assumes there is some other compiler that doesn't have builtin popcount - in case of USE_POPCNT being undefined all these supported   compilers already support the built-in intrinsic and the 65KB popcount array is useless.

**Comment by snicolet** [comment]
Part of the proposed changes merged via 384bff4264f199ded8fa28d241ce0e7dc021a97c, thanks to all! :-)

**Pull request closed without merging**
