### PR TITLE
Ternary operator for killers update

### PR DESCRIPTION
**Pull request by FauziAkram**
Same bench
Using a ternary operator to make the code more concise.
Instead of an if statement. A ternary operator is a conditional operator that takes three operands: a condition, a value to return if the condition is true, and a value to return if the condition is false.

LLR: 2.95 (-2.94,2.94) <-1.75,0.25>
Total: 72920 W: 19508 L: 19338 D: 34074
Ptnml(0-2): 200, 7523, 20806, 7769, 162
https://tests.stockfishchess.org/tests/view/63953a3588432ad6ae3a056c

### CODE REVIEW

**Comment by Sopel97** [comment]
It appears to be a neccessary evil to get the compiler to generate cmovs instead of jumps.

**Comment by FishChess** [comment]
The if statement has 2 lines, converting to Ternary expressions is not a good idea

**Comment by dsmsgms** [comment]
It doesn't change anything useful, also my compiler stops inlining the function after the patch.

**Comment by vondele** [comment]
I prefer the original code.

**Pull request closed without merging**
