### PR TITLE
Integrate syzygy in automated testing.

### PR DESCRIPTION
**Pull request by vondele**
extends valgrind/sanitizer testing to cover syzygy code.

To do so, 3 and 4 man tablebases (~4Mb) are included in the tree, the same approach as adopted by python-chess (and source of the files).

No functional change.

### CODE REVIEW

**Comment by vondele** [comment]
This is again a proposal, to invite discussion on the proper approach.

**Comment by lucasart** [comment]
Syzygy can be tested, but not like that. You need a specific file with FENs (thousands ideally), that give you a good coverage of endgames (eg. 3-10 pieces, random positions). Bench position set is really not adequate for that.

As for including the Syzygy tables in the repo, I think this is problematic. Git is not designed to handle large binary files.

**Comment by vondele** [comment]
@lucasart. Sure it is not perfect, and it would be useful to add an additional FEN file, I would appreciate if you could give me a pointer to it. For the automatic testing it must be possible to run through it in a few seconds (under valgrind that's minutes). 

Nevertheless, with the added commit (rootpos in TB), coverage of syzygy directory is now up to 88%, which is not bad (similar to src/) and up from 3%
coverage_syzygy

This kind of testing found a bug in the past (876f07cbeea5b583ca75685cefa0fd4be1e904a4) so has some value. Obviously, is very far from complete testing of the syzygy code, and automatic testing only complements local testing.

For the binary files, github warns at 50Mb per file and blocks 100Mb per file, the recommendation is to keep the repo below 1Gb. The added files are in total 4Mb, individual files 300Kb max. It certainly is still reasonable, and not worth the hassle to put this online elsewhere IMO.

**Comment by mcostalba** [comment]
@vondele this is an overkill IMO.

It adds an useless (see later) burden on all forks and clones and local repos without any real advantage.

It is (almost) useless because syzygy patches are very rare and when they happen, the author needs to test them in a different way anyhow, bench number is not a good way to test for functional equivalence in TB sources. For instance for testing my syzygy code porting and following changes I used a parallel debug branch that was performing a  double call of each syzygy API function, one calling the original and one the modified and verifying that result was the same. This is more powerful than bench because evaluates correctly also patches that change bench number but are functional equivalent (this is due to some pos.do:move() done inside TB code). Moreover the API cross-check test is even deeper because we can test DTZ not only at root, as usual search does, but in every inner node, like WDL: I have found some subtle bug in original syzygy code in this way.

So, IMO, this patch adds nothing but a bunch of MB and a false sense of security.

**Comment by vondele** [comment]
Ok, closed.

**Pull request closed without merging**
