### PR TITLE
Refactor tbprobe.cpp

### PR DESCRIPTION
**Pull request by WOnder93**
This involves:
 * replacing the union hacks with simply reusing the EntryPiece arrays
   for the no-pawns case
 * converting the hash table to std::array, simplifying some functions
 * thanks to previous changes, removing the ugly memsets
 * simplifying the template logic for WDL/DTZ distinction
   (now we distinguish based on an enum type, not the entry classes)

No functional change.

### CODE REVIEW

**Comment by jjoshua2** [comment]
@WOnder93 Sorry to thread jack, but it looks like you understand the syzygy bases well with such an extensive rewrite, and was wondering if you could look at this [syzygy seg fault](http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=753950&t=66797)

**Comment by WOnder93** [comment]
@jjoshua2 Well, actually I have no previous knowledge about inner workings of the Syzygy TBs, I'm just good in general C++ :) The rewrite is pretty much just a code style change...

That said, I guess I could look at that segfault briefly tomorrow or during next week (7-men syzygy sure sound interesting ;) but I can't promise I will have the time, the will, or success :)

**Comment by lucasart** [comment]
Code looks nice. But how did you verify that this is indeed a non functional change ?

**Comment by snicolet** [comment]
Thanks for the patch, I will look at it after the beginning of the TCEC super-finale.

In other words, I think that I will make a code freeze from now for a period of about 2-3 weeks for all the features related to tablebase, time management, etc, because I don't want to introduce any bug that we wouldn't have the time to fix before we sent the executable for the super-finale. Only the trivial usual evaluation or search patches during the freeze :-)

**Comment by vondele** [comment]
@WOnder93 I assume that fixes (the more tricky part) of the open issue #1470 ...

@lucasart a while ago I proposed a patch to integrate TB testing in the CI ... unfortunately was rejected, with the argument that nobody changes this code, etc. It would have answered this question automatically. I still think TB testing needs to be part of CI, and I can revive the patch if needed

Improved testing is the way to address what @snicolet brought up. Testing should be such that the development version is free of these common bug concerns (and IMO that releasing should be as easy as pushing a button). While some code freeze for a release is good and normal, I don't feel we should have the TCEC schedule dictate these things for SF. Either something like TCEC uses dev versions, and these (rare) bugs could happen, or they use releases, which are possibly a bit more robust. If we feel like the last little bit of elo is important for TCEC, it must also be important for other users as well, and we release more frequently.

**Comment by Stefano80** [comment]
I also would support TB testing either in Travis or in fishtest. We need a concept for that.

**Comment by snicolet** [comment]
@vondele 

Yes, I am interested in testing the integrity of tablebase support in the CI.

I should have, in particular and if possible, a feature which output some "exhaustive probe statistics" for the syzygy files, running our probing routine over all the positions in each file and reporting how many wins/draw/losses it has found. 

I sort of remember that @mcostalba had written something like that during the rewrite of the original code, maybe he can give advices? -- how much time did it take to run the validation code for the 6 men databases, and how much time would it take for the 7men database?

And of course Ronald can probably help with the continuous integration validation idea, too... @syzygy1 ? :-)

**Comment by vondele** [comment]
@snicolet I think one should start small... initially just have the code pass through the usual testing and verify, for example, that changes are non functional.

For reference, the original patch was 
https://github.com/vondele/Stockfish/commit/5205054803d3e82d17e18ab9f102520887a028b5

**Comment by WOnder93** [comment]
@lucasart I didn't test it (yet), I opened the pull request to invite people that have the necessary instruments to test it and/or to review the code. I expect this to take some time, of course.

@vondele Yes, it started as an effort to fix those problems (although I detected them through cppcheck) and it quickly grew to a larger rewrite as I realized it is not so simple :) I will mention the issue in the commit message when I get to squash the commits (the diff looks nicer when the last commit is included anyway).

I agree that TB testing in the CI would be nice. Maybe even a simple script that could be run manually when necessary would suffice.

I happen to have 6-men syzygy on my machine, so I'll try running an STC match between this patch and master to test for possible regression. I will also try to come up with some simpler test. (Maybe just running bench with syzygy for master and patch would do the trick...?)

**Comment by vondele** [comment]
@WOnder93 yes, running a bench with with syzygy for master and patch would go a long way to show it is non-functional. 

Notice that the patch I mentioned has such a simple script, although it doesn't verify the bench. See 
https://github.com/vondele/Stockfish/commit/5205054803d3e82d17e18ab9f102520887a028b5#diff-8d62cf7de62914b563096c1ad1b48ae3

**Comment by WOnder93** [comment]
@vondele I just ran the benches with 6-men syzygy and they were indeed the same (5352264; without syzygy they were 5318575) :champagne:

Yes, I see now that the script is just a small part of the Travis run, not all of it, as I thought at first. Maybe it would be nice if it just downloaded the 2-3-4-man bases automatically into a temp directory instead of bundling them with Stockfish code...

**Comment by mcostalba** [comment]
@WOnder93 bench excerzise very lightly TB. Can you please run with a much deeper bench?

`./stockfish bench 128 1 22`

and report TB hits? (you can read them on PV line info

**Comment by WOnder93** [comment]
@mcostalba Done, both benches are 197880875. The TB hits also seem the same, I attach full bench logs for reference:
[bench-master.log](https://github.com/official-stockfish/Stockfish/files/1800323/bench-master.log)
[bench-tbprobe_cleanup.log](https://github.com/official-stockfish/Stockfish/files/1800324/bench-tbprobe_cleanup.log)

**Comment by WOnder93** [comment]
I would like to note that after the patch the WDL and DTZ entries reduced in size quite a bit. On my machine (64-bit, GCC, Linux) I get:
```
        WDL    DTZ
before: 120 B  160 B
after:  112 B  120 B
```
This likely does not bring any measurable speed up, but it's still good to see that the union trick can be removed without the entries gaining in size.

**Comment by vondele** [comment]
@WOnder93 patch also passed CI with TB tests enabled.

Concerning 2-3-4man TB as part of the repo or download from elsewhere, my 2c:
+ it is only 4Mb, so no big deal on github, it is only useful for devs, other programs (python-chess) already do the same.
+ stored in tests/data so doesn't interfere with the routine of most.
+ makes travis testing simple and more robust.
+ it makes it easy to also test from the command line (without travis) or internet connection
+ no extra instructions needed for new devs.

**Comment by syzygy1** [comment]
@snicolet 
The tricky part is correctly calculating the WDL/DTZ value of a position based on what the "raw" table probes return. Tricky, because a bug can easily go unnoticed for a long time (Marco in fact found one, unsurprisingly related to en passant). This patch doesn't touch that part of the code, I think. If this patch contains a bug, it will probably be noticed quickly.

**Comment by vondele** [comment]
@WOnder93 actually, manually doing the CI, I overlooked an error under valgrind:

```
==4221== Thread 2:
==4221== Conditional jump or move depends on uninitialised value(s)
==4221==    at 0x1681B3: void* (anonymous namespace)::init<((anonymous namespace)::TBType)0>((anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0>&, Position const&) (tbprobe.cpp:1095)
==4221==    by 0x1664A5: Tablebases::WDLScore (anonymous namespace)::probe_table<((anonymous namespace)::TBType)0, Tablebases::WDLScore>(Position const&, Tablebases::ProbeState*, Tablebases::WDLScore) (tbprobe.cpp:1133)
==4221==    by 0x165452: Tablebases::WDLScore (anonymous namespace)::search<false>(Position&, Tablebases::ProbeState*) (tbprobe.cpp:1200)
==4221==    by 0x163A5D: Tablebases::probe_wdl(Position&, Tablebases::ProbeState*) (tbprobe.cpp:1359)
==4221==    by 0x148354: Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool, bool) (search.cpp:617)
==4221==    by 0x14A22D: Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool, bool) (search.cpp:1019)
==4221==    by 0x14A22D: Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool, bool) (search.cpp:1019)
==4221==    by 0x14A22D: Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool, bool) (search.cpp:1019)
==4221==    by 0x14A22D: Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool, bool) (search.cpp:1019)
==4221==    by 0x14A22D: Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool, bool) (search.cpp:1019)
==4221==    by 0x14A22D: Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool, bool) (search.cpp:1019)
==4221==    by 0x14A22D: Value (anonymous namespace)::search<((anonymous namespace)::NodeType)0>(Position&, Search::Stack*, Value, Value, Depth, bool, bool) (search.cpp:1019)
==4221==  Uninitialised value was created by a heap allocation
==4221==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4221==    by 0x16AD65: __gnu_cxx::new_allocator<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0> >::allocate(unsigned long, void const*) (new_allocator.h:111)
==4221==    by 0x169D8C: std::allocator_traits<std::allocator<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0> > >::allocate(std::allocator<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0> >&, unsigned long) (alloc_traits.h:436)
==4221==    by 0x167EC1: std::_Deque_base<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0>, std::allocator<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0> > >::_M_allocate_node() (stl_deque.h:602)
==4221==    by 0x1698A1: std::_Deque_base<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0>, std::allocator<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0> > >::_M_create_nodes((anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0>**, (anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0>**) (stl_deque.h:727)
==4221==    by 0x16784E: std::_Deque_base<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0>, std::allocator<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0> > >::_M_initialize_map(unsigned long) (stl_deque.h:701)
==4221==    by 0x165D98: std::_Deque_base<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0>, std::allocator<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0> > >::_Deque_base() (stl_deque.h:492)
==4221==    by 0x164BE7: std::deque<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0>, std::allocator<(anonymous namespace)::TBEntry<((anonymous namespace)::TBType)0> > >::deque() (stl_deque.h:888)
==4221==    by 0x1614F5: (anonymous namespace)::HashTable::HashTable() (tbprobe.cpp:287)
==4221==    by 0x16BCBE: __static_initialization_and_destruction_0(int, int) (tbprobe.cpp:330)
==4221==    by 0x16BD2B: _GLOBAL__sub_I__ZN10Tablebases14MaxCardinalityE (tbprobe.cpp:1652)
```
you might want to check this.

**Comment by WOnder93** [comment]
@vondele Thanks! It turns out I made some wrong assumptions about default constructors... please try verifying the new version, hopefully it is fixed now.

I hope I am right that the `Atomic` wrapper was actually not necessary and the MSVC build passes (at least with GCC it seems useless as we don't use the copy constructor/assignment anywhere).

**Comment by WOnder93** [comment]
OK, I ran the syzygy valgrind test myself and discovered another missing variable initializations. It now passes at least on my side.

**Comment by mcostalba** [comment]
@WOnder93 I had a time of checking your patch: I like it :-)

I am wondering if we can integrate directly PairsData as member instead of using a pointer. I have pushed [this patch](https://github.com/mcostalba/Stockfish/commit/tb) to better clarify it.

**Comment by Hanamuke** [comment]
@syzygy1 Will you consider applying those changes to your tb repository, in some way or another ?

**Comment by Hanamuke** [comment]
@WOnder93 there are a lot of places where const or static const could be replaced by constexpr.

**Comment by WOnder93** [comment]
@mcostalba It should be OK... maybe there is some performance benefit in having more frequently used fields in a separate cache line but I'm not sure if that's the case here (the entries are not cache-line aligned anyway...).

@Hanamuke Indeed, but IMHO those should be handled in a separate patch/PR as they are more rudimentary changes (and should be easier reviewed separately).

**Comment by mcostalba** [comment]
@WOnder93 at this point I think it makes sense to bite the bullet and remove the 2 largely equivalent EntryPiece structures, see [this one](https://github.com/mcostalba/Stockfish/commit/tb)

**Comment by snicolet** [comment]
Genuine question: can anybody explain me the removal of the Atomic wrapper in this commit 
https://github.com/official-stockfish/Stockfish/pull/1477/commits/493a45501d6129ffd2198fe13af67d50096e01e9

Why was the wrapper necessary before and why is it no longer necessary?

**Comment by WOnder93** [comment]
@snicolet The `std::atomic<...>` types have the copy constructor and copy assignment disabled (I don't know the exact reasons, but I believe it is to prevent misuse). Thus, also any type containing an atomic type also has copy constructor disabled by default.

The wrapper works around that by defining an explicit copy constructor, but the copying is not performed anywhere in the code (and it wasn't even before, AFAIK). I would say that during the TB code rewrite (c0bb0415394179e9c771cc96a9da6724fc14c167) @mcostalba began with code that needed the copy constructor and then after some changes it was not needed anymore but he forgot to remove the wrapper.

**Comment by WOnder93** [comment]
@mcostalba OK, I pushed it into the PR (if you don't mind). If there are no more comments, I will squash the commits into two (one for my changes and one for Marco's extension) and @snicolet can then merge it when he feels like it :)

**Comment by mcostalba** [comment]
@WOnder93 please feel free to squash all in a single (your) commit, I don't mind and for @snicolet is easier to merge.

**Comment by snicolet** [comment]
Can anybody give me a step-by-step procedure to check the correctness of the patch?
Something like:

• download tablebase from Blah
• run this command in master, look at this number
• run this command in patch, look at this number

Then, as I said, I will commit after the end of the freeze (no need to rush, and you have time to still improve on the patch) :-)

**Comment by snicolet** [comment]
@WOnder93 Thanks for the clarifications about the Atomic wrapper.

On a somewhat related subject, do you know if this version of the patch removes the GCC 8.0 warning of issue https://github.com/official-stockfish/Stockfish/issues/1470 ?

**Comment by WOnder93** [comment]
@snicolet I don't have GCC 8.0 at hand, but it should fix the first two warnings, the third one is related to `position.cpp`.

As for testing the correctness of the patch, you can do two things:
 * Checkout the branch from this PR, merge @vondele's branch from #1490, build SF, and run `../tests/instrumented.sh --valgrind` (it should print **`instrumented testing OK`** at the end).
 * Run `bench 128 1 22` with syzygy for both the PR and master (I have a script for it at home, I'll post it later) &ndash; in this step you can use the TBs from @vondele's patch (but there likely won't be many TB hits) or your own 6/5-men TBs if you have them.

**Comment by WOnder93** [comment]
All commits squashed and rebased to master.

**Comment by WOnder93** [comment]
@snicolet I have put my bench calculation scripts [here](https://gist.github.com/WOnder93/b5fcf9c989b4a1715684d5c82367cdbe).

To verify that this PR is a non-functional change:
1. Make sure you have branches `master` and this PR (`tbprobe_cleanup`) pointing to the right commits.
2. Download the scripts into `src` inside your Stockfish repo and make them executable (`chmod +x *.sh`).
3. Run this command if you want to use tablebases from #1490:
   ```
   export SYZYGY_PATH=../tests/data/syzygy
   ```
   Or, if you want to use TBs located at `<path>`:
   ```
   export SYZYGY_PATH='<path>'
   ```
4. After that, run this (it will take a long time, this is a deep bench):
   ```
   BENCH_ARGS='128 1 22' ./check_benches.sh master tbprobe_cleanup 2>/dev/null`
   ```
You should see two equal numbers printed. (Of course, now we have a problem of how to prove that the script itself is correct :)

**Comment by mcostalba** [comment]
@WOnder93 @snicolet I have further worked on TB code and you can find the full series [here](https://github.com/mcostalba/Stockfish/commits/tbc), split in several commits for easier review and rebased above this current branch.

Verified no functional change.

**Comment by mcostalba** [comment]
This morning I have added another [commit](https://github.com/mcostalba/Stockfish/commit/0aedf680c67bd2b29) to improve hash table implementation (please see log message). This is interesting to me because it greatly reduces lookup steps on average while at the same time reducing table size!

**Comment by WOnder93** [comment]
@mcostalba Looks good! But I think you should open a new pull request for those after this one gets merged so that our work doesn't get mixed up in a single commit :) It is not good to change too many different things in a single commit anyway.

**Comment by mcostalba** [comment]
@WOnder93 yes, I will open a PR above your patch, but technically I think I have to wait your work is merged (about one month form now, waiting for TCEC), so in this way I can anticipate my series and receive feedback already now.

**Comment by snicolet** [comment]
Refactor tbprobe.cpp

This involves:
 * replacing the union hacks with simply reusing the EntryPiece arrays
   for the no-pawns case
 * Merging the PairsData structure with the EntryPiece/-Pawn structs
   (with credit to Marco: @mcostalba)
 * simplifying some HashTable functions
 * thanks to previous changes, removing the ugly memsets
 * simplifying the template logic for WDL/DTZ distinction
   (now we distinguish based on an enum type, not the entry classes)
 * removing the unneeded Atomic wrapper

-----------------------------

For reference, here is a manual way to check that patches concerning
table bases code are non-functional changes:

0) Download the Syzygy table bases (up to 6 men).
1) Make sure you have branches master and the pull request pointing to 
   the right commits.
2) Download the bench calculation scripts from the following URL:

        https://gist.github.com/WOnder93/b5fcf9c989b4a1715684d5c82367cdbe
        
   and copy into src inside your Stockfish repo.
3) Make the scripts executable (chmod +x *.sh).
4) Run the follwing command to use TBs located at <path>:

       export SYZYGY_PATH='<path>'
       
5) After that, run this (it will take a long time, this is a deep bench):

       BENCH_ARGS='128 1 22' ./check_benches.sh master tbprobe_cleanup 2>/dev/null`

==> You should see two equal numbers printed. 
    (Of course, now we have to trust that the script itself is correct :)
    
-----------------------------

Closes https://github.com/official-stockfish/Stockfish/pull/1477

No functional change.

**Comment by snicolet** [comment]
Merged via 8ff2fcf299ac621779dc167ce750ba73aaae90a4
Thanks! :-)

**Pull request closed without merging**
