### PR TITLE
Add initiative to trace

### PR DESCRIPTION
**Pull request by ceebo**
No functional change

### CODE REVIEW

**Comment by snicolet** [comment]
Looks good to me

**Comment by ceebo** [comment]
> Looks good to me

Thanks. Here is sample output on a position that occurs inside bench. Note how the initiative completely cancels out the rest of the eval. This happens at 3% of all positions in bench. If such positions were to occur close together in search then I would worry that the engine is walking around blind. Maybe it makes sense to ensure that initiative is at least -abs(eg) / 2 so that at most half of the regular eval gets cancelled out? If the maintainers thought that this feature was weird enough to be called a bug it could be tested at SPRT(-3,1).


```
position fen 8/4r3/3K4/8/8/2R5/8/3k4 b - - 0 19
eval
      Eval term |    White    |    Black    |    Total    
                |   MG    EG  |   MG    EG  |   MG    EG  
----------------+-------------+-------------+-------------
       Material |   ---   --- |   ---   --- |  0.15  0.35 
      Imbalance |   ---   --- |   ---   --- |  0.00  0.00 
          Pawns |   ---   --- |   ---   --- |  0.00  0.00 
        Knights |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
        Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
          Rooks |  0.15  0.08 |  0.11  0.08 |  0.04  0.00 
         Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
       Mobility |  0.24  0.71 |  0.24  0.71 |  0.00  0.00 
    King safety | -0.37 -0.33 | -0.45 -0.33 |  0.09  0.00 
        Threats |  0.21  0.37 |  0.00  0.00 |  0.21  0.37 
   Passed pawns |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
          Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
     Initiative |   ---   --- |   ---   --- |  0.00 -0.72 
----------------+-------------+-------------+-------------
          Total |   ---   --- |   ---   --- |  0.49  0.00 

Total Evaluation: -0.08 (white side)
```

**Comment by snicolet** [comment]
@ceebo In fact `-abs(eg) / 2` was how it was capped in the first version of evaluate_initiative(), but it was later changed to `-abs(eg)` as part of an Elo gaining patch.

https://github.com/snicolet/Stockfish/commit/7ea5659c5fe0325f1b6ee5fec06ecd0f066e81c3
https://github.com/snicolet/Stockfish/commit/eefbe967c2a1ea1f1e39e5cfff1c38e451a9be2e

In my opinion, reverting to `-abs(eg) / 2` should be tested with SPRT([0..4]) bounds.

**Comment by ceebo** [comment]
OK. Thanks for the info.

**Pull request merged**
