### PR TITLE
Tuned weights

### PR DESCRIPTION
**Pull request by absimaldata**
More accurate evaluation weights

Performed better at STC

LLR: 1.32 (-2.94,2.94) [0.00,4.00]
Total: 190043 W: 37433 L: 36675 D: 115935

Passed LTC

LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 30157 W: 4540 L: 4303 D: 21314

### CODE REVIEW

**Comment by joergoster** [comment]
Congrats!

**Comment by Rocky640** [comment]
Well done, and congrats also to snicolet who discovered this new threat weight.

**Comment by zamar** [comment]
approved.

**Comment by glinscott** [comment]
Looks great!

**Comment by absimaldata** [comment]
Thank you.

**Comment by absimaldata** [comment]
@zamar Just a humble request, if it is possible to use my real profile name instead of 'absimaldata' on abrok.eu/stockfish commit ? Would you please ?

**Comment by zamar** [comment]
What is committed, is committed, and there is no way to change that.

We just cherry-pick commits from other people's repositories. If you change
your git settings, they'll be automatically reflected in your commits.

**Comment by absimaldata** [comment]
@zamar Oh ok, thanks, but i dont know what went wrong, I updated my profile name 2 days back only lol, still not updated maybe.

**Comment by Ivoz** [comment]
@absimaldata you need to run

    $ git config --global user.name "John Doe"

And then only commits made *after* that change (you could re-make older ones with things like `--amend` if you wanted) will use the new value.

**Pull request closed without merging**
