### PR TITLE
Remove operators for color

### PR DESCRIPTION
**Pull request by protonspring**
This is a non-functional and untested simplification.  The increment operator for color isn't really necessary and seems a bit unnatural to me.

### CODE REVIEW

**Comment by snicolet** [comment]
This needs some test to check that there is not speed penalty, depending on what code the compiler emits for the alternate form..

**Comment by protonspring** [comment]
I tried to use godbolt, but the compiler doesn't seem to recognize the new form.

Are you wanting a -3,1 test on the framework, or godbolt code?

**Comment by Sopel97** [comment]
https://godbolt.org/z/XmG1wL
tldr: if you don't care about msvc then it's the same codegen. clang has stupidly high limit on unrolling so pretty much no problem

**Comment by snicolet** [comment]
A -3,1 test in the framework would be fine

**Comment by Rocky640** [comment]
@protonspring 
Before running a [-3, 1] test, while being there, can you also prettify the following line
`for (CastlingSide s = KING_SIDE; s <= QUEEN_SIDE; s = CastlingSide(s + 1))`
for
`for (CastlingSide s : { KING_SIDE, QUEEN_SIDE })`

**Comment by protonspring** [comment]
STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 47027 W: 10589 L: 10518 D: 25920
http://tests.stockfishchess.org/tests/view/5d3472d10ebc5925cf0e8d3e

**Comment by snicolet** [comment]
Could we retest the PR version in isolation? thanks :-)

**Comment by protonspring** [comment]
Dang it.  I accidentally committed some kingSquares changes (which perform very poorly).  Let me revert. sry.

**Comment by Rocky640** [comment]
The proposed change to CastlingSide  in bool function pos_is_ok is harmless.
pos_is_ok is only called in debug mode and inside some assert calls

**Comment by snicolet** [comment]
@protonspring @Rocky640 
I was confused when I saw the commit "single kingSquares", which was not inteneted to be part of the pull request if I understand correctly. I am fine with the changes for Color and CastlingSide, which is indeed not in the critical path of SF.

**Comment by snicolet** [comment]
Merged via aec918a2b6ee931826ef19db1726950976da7ffe

**Comment by Rocky640** [comment]
@snicolet That was busy day !

**Pull request closed without merging**
