### PR TITLE
Tuned some Classical Parameters in Evaluation

### PR DESCRIPTION
**Pull request by FauziAkram**
Tuned some Classical Parameters in Evaluation.

The following tests shows that it improves the classical evaluation enough to pass both elo gain tests (around +3 Elo both in STC and LTC).
And it improved the overall engine a little bit (enough to pass the non-regression test with a positive score)

Please let me know if any other test is needed in order to merge this patch:

STC , Elo gain, NNue=False :
LLR: 2.94 (-2.94,2.94) <0.00,2.50>
Total: 34584 W: 9045 L: 8753 D: 16786
Ptnml(0-2): 248, 4028, 8474, 4268, 274
https://tests.stockfishchess.org/tests/view/6200595fbf46cb834cbd9e57

LTC , Elo gain, NNue=False :
LLR: 2.95 (-2.94,2.94) <0.50,3.00>
Total: 30376 W: 7626 L: 7350 D: 15400
Ptnml(0-2): 43, 3340, 8155, 3598, 52
https://tests.stockfishchess.org/tests/view/6200fd17bf46cb834cbdb88d

STC , Non-regression, NNue=True:
LLR: 2.94 (-2.94,2.94) <-2.25,0.25>
Total: 40856 W: 10928 L: 10778 D: 19150
Ptnml(0-2): 172, 4600, 10775, 4668, 213
https://tests.stockfishchess.org/tests/view/62028717bf46cb834cbdfd7a

LTC , non-regression, nnue=true, rebased on the new master (on the time of the test)
LLR: 2.95 (-2.94,2.94) <-2.25,0.25>
Total: 71480 W: 19035 L: 18940 D: 33505
Ptnml(0-2): 71, 7388, 20719, 7499, 63
https://tests.stockfishchess.org/tests/view/62050929d71106ed12a439f1

### CODE REVIEW

**Comment by Rocky640** [comment]
for the record, the author made one tuning with nnue=true
https://tests.stockfishchess.org/tests/view/61fc791cd508ec6a1c9f4b4a

and another one with nnue=false
https://tests.stockfishchess.org/tests/view/61fc791ad508ec6a1c9f4b48

Question to the author, which set of data did you keep ? Or did you average both

also, for the record, 

Elo gain test with nnue=true did not worked
https://tests.stockfishchess.org/tests/view/6200580bbf46cb834cbd9e0a

but nnue=true passed Non regression STC.
https://tests.stockfishchess.org/tests/view/62028717bf46cb834cbdfd7a

**Comment by FauziAkram** [comment]
Hi @Rocky640 long time no see, we all been missing you.
Yes I made two tuning sessions, as based on my tuning experience over the year works better, then I used many interpolation between the values, at the end, the one ending passing easily is the version that is using:
- 3/5 of weight coming from the tuning of nnue=false
- 1/5 of weight coming from the tuning of nnue=true
- 1/5 of weight coming from the original values before tuning

**Comment by locutus2** [comment]
Congrats, nice tuning!

But to the testing method:
For the non-regression test with NNUE=true a LTC have to be prefered because that is our main TC and STC more like a filter (a STC non-regression could be skipped in this case). And also NNUE=true is our main focus and NNUE=false a side topic, so NNUE=true have to handled with more care IMHO.

**Comment by FauziAkram** [comment]
@locutus2  ok dear, here is the LTC non-regression with nnue=true, rebased on the new master (on the time of the test)
This test also passed, and also with positive score.

LLR: 2.95 (-2.94,2.94) <-2.25,0.25>
Total: 71480 W: 19035 L: 18940 D: 33505
Ptnml(0-2): 71, 7388, 20719, 7499, 63
https://tests.stockfishchess.org/tests/view/62050929d71106ed12a439f1

and new Bench:4620970

**Comment by FauziAkram** [comment]
@snicolet Hi dear, fishtest is completely empty, can you please merge this change so i can make some other tests on top of it?
Or is there something blocking the merging of this patch?

**Comment by Karma-Tron** [comment]
I wonder why this isn't merged?

**Comment by dav1312** [comment]
> I wonder why this isn't merged yet?

Probably because classical is considered "frozen"

**Comment by Karma-Tron** [comment]
> > I wonder why this isn't merged yet?
> 
> Probably because classical is considered "frozen"

Perhaps, but it is also beneficial with nnue=true

**Comment by FauziAkram** [comment]
This pull request is now eclipsed by the new pull request 
https://github.com/official-stockfish/Stockfish/pull/3958
you can close it

**Pull request closed without merging**
