### PR TITLE
Add ispc generic architecture

### PR DESCRIPTION
**Pull request by borg323**
This adds a new architecture that instead of processor dependent hand vectorized code uses Intel's open source ispc (Implicit SPMD Program Compiler) with higher level input code. The objective is be able to write experimental evaluation functions in this higher level description and get decent performance, before resorting to low level coding.
The transformer mention in the original title was a joke, but this is the infrastructure I would use if I was actually doing it.

### CODE REVIEW

**Comment by vondele** [comment]
So, interesting. Without any simd intrinsics this outperforms our base implementation:

```
Result of  10 runs
==================
base (./stockfish.general-64   ) =     391398  +/- 2439
test (./stockfish.ispc.native  ) =     752237  +/- 5170
diff                             =    +360838  +/- 4973

speedup        = +0.9219
P(speedup > 0) =  1.0000
```

**Comment by locutus2** [comment]
I have measured this also on my machine (AMD Ryzen 5 2600, gcc 9.2.1) and can confirm your values.
In addition i had also measured for the standard modern version (popcount + sse stuff) and the avx2 version (the fastest for me):

make profile-build ARCH=general-64 COMP=gcc
Total time (ms) : 15346
Nodes searched  : 4935616
Nodes/second    : 321622

make profile-build ARCH=ispc
Total time (ms) : 7751
Nodes searched  : 4935616
Nodes/second    : 636771

make profile-build ARCH=x86-64 COMP=gcc
Total time (ms) : 6627
Nodes searched  : 4935616
Nodes/second    : 744773

make profile-build ARCH=x86-64-avx2 COMP=gcc
Total time (ms) : 5676
Nodes searched  : 4935616
Nodes/second    : 869558

So for ispc to catch the moden version its need around 17% speed increase and for the avx2 version around 36%.

But as a baseline this is really impressive and a good starting point for borgs experiments.

Later on if we will have a working new network structure which is roughly on par with master we need anyway a manually optimized SIMD version of the new network so that also the other common compilers are supported. That is necessary else we couldn't test the new architecture at fishtest (most will not use ispc) . Then we can also get this speed gains. But it will be also interesting how the ispc compilers develops and if it can close the speed gap.

But really exciting times!

**Comment by mstembera** [comment]
Most exciting to me is the mention of transformer.  Can we know more?

**Comment by mstembera** [comment]
Would transformers even be useful for SF?

**Comment by vondele** [comment]
@mstembera this was part of a April 1st announcement on discord... https://discord.com/channels/435943710472011776/436248884335869967/1091618927190216804

The PR is real though.

**Comment by mstembera** [comment]
@vondele Thanks for the link.  I wasn't aware.  
April 1st aside LC0 has switched to transformers so there must be some merit for it at least.  Anyone know if there is any available info explaining it?

**Comment by vondele** [comment]
The standard link on transformers would be https://arxiv.org/abs/1706.03762 
I think Leela team sees significantly better performance in 1node/move setup with transformers.

**Comment by mstembera** [comment]
What I'm really wondering (and communicating poorly) is if the LC0 team has published anything about how transformers apply specifically to chess.

**Comment by mstembera** [comment]
This seems interesting https://github.com/Ergodice/lczero-training/blob/attention-net-body/README.md

**Comment by vondele** [comment]
so, this was an interesting experiment, but given the performance not for merging in master. I'll close this for now, but thanks anyway.

**Pull request closed without merging**
