### PR TITLE
WeakQueen parameter tweak.

### PR DESCRIPTION
**Pull request by vondele**
New tuned values.

passed STC
http://tests.stockfishchess.org/tests/view/5834573c0ebc5903140c507b
LLR: 3.16 (-2.94,2.94) [0.00,4.00]
Total: 157415 W: 27917 L: 27227 D: 102271

passed LTC
http://tests.stockfishchess.org/tests/view/58388d2b0ebc5903140c523b
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 95405 W: 12350 L: 11959 D: 71096

Bench: 4912054

### CODE REVIEW

**Comment by mcostalba** [comment]
@vondele congrats and thanks.

Can you please squash all commits in a single one and write the log message (what you wrote at the beginning of this PR)?

I am now experimenting with a new feature of github that allows direct merge and commit of PR without a standard merging but committing above the master (what I usually do manually with every PR til today). For this to work I need a PR as a single commit and with proper commit title and commit message. Thanks.

**Comment by DamasClasicas** [comment]
Congratulations Vondele!! 

Keep your nice work!!

**Comment by VoyagerOne** [comment]
Congrats on your first elo gaining patch!

**Comment by vondele** [comment]
@mcostalba is this what you wanted ? 

I'm not sure rebasing and forcing the push (which is what I did), is really good for things that live on github, it kind of rewrites history (for example the pull request now doesn't seem to show the comments made on the branch before). They can still be found though (https://github.com/vondele/Stockfish/commit/cd2c8e2b92a46c08060cd0af9693e01521809186)

An additional issue is the 'Bench : XXX' line in the commit message, if you have multiple patches queued against master, the proper value depends on the order you decide to merge them.

**Comment by atumanian** [comment]
> I'm not sure rebasing and forcing the push (which is what I did), is really good for things that live on github, it kind of rewrites history (for example the pull request now doesn't seem to show the comments made on the branch before). They can still be found though (vondele@cd2c8e2)
Yes, this is a problem. To work around it, you can create a new branch on the one you have been working on. Then rebase it on the master branch and use it in the pull request. The old branch is kept unchanged, so your history is preserved.

> An additional issue is the 'Bench : XXX' line in the commit message, if you have multiple patches queued against master, the proper value depends on the order you decide to merge them.
Don't include the bench number in the commit message; include it only in the message for the pull request.

**Comment by vondele** [comment]
@atumanian that sounds like a good workflow.

**Pull request merged**
