### PR TITLE
Make razor_margin[4] ONE_PLY value independent

### PR DESCRIPTION
**Pull request by HiraokaTakuya**

### CODE REVIEW

**Comment by lucasart** [comment]
Patch is wrong: If ONE_PLY value is changed, you will read outside the bounds of the array.

Current code is already ONE_PLY independent, so I don't understand what you're trying to do.

**Comment by HiraokaTakuya** [comment]
If ONE_PLY is 2, razor_margin[3 * ONE_PLY] is razor_margin[6].
It's outside the bounds of the array.
Why is current code is already ONE_PLY independent?

**Comment by lucasart** [comment]
Why not ?

**Comment by HiraokaTakuya** [comment]
Current code : razor_margin[3 * ONE_PLY]
If ONE_PLY is 2, It's outside the bounds of the array.

My patch code : razor_margin[3]
If ONE_PLY is 2, It is "not" outside the bounds of the array.

**Comment by Kingdefender** [comment]
Hello, 

This patch as proposed by Hiraoka Takuya seems correct to me. 

As an aside, it does not seem very likely to me that Stockfish will go back to fractional plies smaller than a half move, so maybe the ONE_PLY constant could go altogether? It seems more likely that search could go to increasing by a full move, eventually.

Also the tuned Razor margin does not go up very clearly with depth, Maybe you could instead use here (I believe this is Michel van den Bergh's patch) the value 483, that is not so different from 554 what it is now. Then you could change the code to  ```&& eval + razor_margin[DEPTH_ZERO] <= alpha)``` 

Or maybe this razoring margin should not be depth dependant but just something a bit larger than two pawns, and since search does not know what phase it is in, uses the larger valueof a pawn in the endgame plus a little bit for positional eval error. I have a suspicion, search could be made more dependant on phase because the number of meaningful captures changes during the game (in my opinion).

Eelco

**Comment by mcostalba** [comment]
Merged with b77bae0529ea6.

BTW the condition is never triggered!

This patch surprised me because changing ONE_PLY value, I got teh same bench number even before the patch, OTH the patch is defenetly correct, so what was happening?

Indeed to my surprise the condition is always true 100% of cases! and for any value of the index, not only 3!!!

So I am going to remove that dead code.

**Comment by mcostalba** [comment]
See eccccba0ce4e2

**Comment by lucasart** [comment]
Sorry, I read the diff wrong! Indeed it was the master that had the 3 * ONE_PLY, which is wrong.

**Comment by HiraokaTakuya** [comment]
No problem.

**Pull request closed without merging**
