### PR TITLE
Avoid some redundant scaling function calls.

### PR DESCRIPTION
**Pull request by mstembera**
Opening since Marco is willing to hear people comment.
No functional change.
Posted by Mohammed Li here:
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/N-PHfN0O79o
w/ some comments already.  Should this get committed credit should go to him.

### CODE REVIEW

**Comment by Thanar2** [comment]
I am in favor of this change (removing an unnecessary duplicate function call). One of the things I have worked on in the past when optimizing Stockfish is using profiling to make a function call graph/histogram, to identify potential code hotspots. Removing these unnecessary function calls generally makes it easier to find other optimizations with this method, and improve Stockfish in the future.

**Comment by jcalovski** [comment]
I'm all for it.

**Comment by lucasart** [comment]
If Marco said this optimization was useless, you can believe that he measured it. If Marco is wrong, the correct way to refute it, is to provide evidence that it is a speed-up. People making general arguments about what they think compilers can or cannot do, or posting thumbs up on a pull request. Well, that does not have much value...

**Comment by MichaelB7** [comment]
Yes, it is a useless simplification - but most simplifications are useless to a certain extent.  Definitely better coding.  I'm for it since it follows the SF guidelines.

**Comment by mcostalba** [comment]
Merged with 0c076f11361

I have edited a bit to fit 80 column width

**Pull request closed without merging**
