### PR TITLE
Use special rule for BlockedByKing

### PR DESCRIPTION
**Pull request by protonspring**
Use special rule for BlockedByKing

Simplification: remove BlockedByKing from storm array and use a special rule.

The BlockedByKing section in the storm array is substantially similar to the 
Unopposed section except for two extreme values V(-290), V(-274). Turns out
removing BlockedByKing and using a special rule for these two values shows
no Elo loss. All the other values in the BlockedByKing section are apparently
irrelevant. BlockedByKing now falls under unopposed which (to me) is a bit
more logical since there is no defending pawn on this file. Also, retuning
the Unopposed section may be another improvement.

GOOD) This is a simplification because the entire BlockedByKing section of
the storm array goes away reducing a few lines of code (and less values to
tune). This also brings clarity because the special rule is self documenting.

BAD) It takes execution time to apply the special rule. This should be negli-
gible because it is based on a template parameter and is boiled down to two 
bitwise AND's.

STC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 33470 W: 6820 L: 6721 D: 19929
http://tests.stockfishchess.org/tests/view/5ae7b6e60ebc5926dba90e13

LTC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 47627 W: 7045 L: 6963 D: 33619
http://tests.stockfishchess.org/tests/view/5ae859ff0ebc5926dba90e85

Closes https://github.com/official-stockfish/Stockfish/pull/1574

Bench: 5512000

-----------

How to continue after this patch?

This patch may open the possibility to move the special rule to evaluate.cpp
in the evaluate::king() function, where we could refine the rule using king
danger information. For instance, with a king in H2 blocking an opponent pawn
in H3, it may be critical to know that the opponent has no safe check in G2
before giving the bonus :-)

### CODE REVIEW

**Comment by protonspring** [comment]
Moving forward (assuming this is applied sometime), it would be interesting if this rule could expand to the 3rd rank, or to FILE_B, or FILE_G.  If the theory is the same, I'm not sure I see a reason why it ONLY applies to outermost files and ONLY RANK_1 or RANK_2.

**Comment by Rocky640** [comment]
I don't think so. On the h file, king cannot be attacked from the right. And further away, say h3, it is either more exposed, or we are closer to endgame.

BTW, to make Travis happy, you need to add your bench in the last comment that is committed.

**Comment by protonspring** [comment]
Thank you much for this.  I always worry i am bothering everyone with too
many tests.

**Comment by Stefano80** [comment]
Is this functionally equivalent to the patch that passed the test? From the comment is unclear whether this is the case.

**Comment by protonspring** [comment]
Yes. There is no functional difference between v6 and v7.

**Comment by Stefano80** [comment]
Ok thank you!

**Comment by vondele** [comment]
... & (ksq + Up) is off the board maybe?

**Comment by snicolet** [comment]
@vondele 
Bug corrected in 06e0134cbc9bcf16d01738c491ec53869a5205b6, thanks!

**Pull request closed without merging**
