### PR TITLE
Further limit shuffle extensions.

### PR DESCRIPTION
**Pull request by vondele**
closes https://github.com/official-stockfish/Stockfish/issues/2389

Bench: 5000602

### CODE REVIEW

**Comment by joergoster** [comment]
So this is fix 4 then? Or already 5? And if this happens on another position? How many fixes will it take until this crappy shuffle patch will finally get reverted?
There was NEVER!, NEVER EVER a single patch accepted or kept that was causing so many problems.

**This is simply ridiculous!**

**Comment by vondele** [comment]
reverting it is of course an option. 

As it is elo gaining, not a problem for games play, neither for infinite analysis, or finite time analysis, and is an attempt to fix a serious problem, it should be done cautiously.

**Comment by vondele** [comment]
So, there are a number of things I can do:

* test if the code after this PR can be removed with a [-3, 1] VLTC test. 
* propose a different way to limit shuffle extensions. One simple way to ensure the current rootDepth iteration does not take too long is to limit it wrt to the previous rootDepth iteration. That's rather easy and guarantees search will proceed more regularly also in pathological cases.

**Comment by vondele** [comment]
trigger CI

**Comment by vondele** [comment]
closing in favor of  #2394

**Pull request closed without merging**
