### PR TITLE
Add Custom uci runtime variables

### PR DESCRIPTION
**Pull request by Chess13234**
This patch adds 8 int UCI variables that can be used in any code inside Stockfish.
This simplifies the workflow of testing and tuning integer variables locally(instead of compiling statically e.g. `#define` it allows the affected values to be dynamically set at runtime).
UCI variables can be used with build scripts that allow building one stockfish binary to test with thousands of different variables set by e.g. cutechess-cli(option.A=x) or another UCI interface.

No functional change.

### CODE REVIEW

**Comment by joergoster** [comment]
We already have the amazing 'tune' branch written by Marco for tuning purposes. https://github.com/official-stockfish/Stockfish/tree/tune
I also fail to understand how adding some variables as UCI options and inserting some #include directives should be of any help.

**Comment by Chess13234** [comment]
@joergoster This is for local testing mainly, but can be used for tuning.
Example:
You want to test locally which value Var X should take.
Before:
You make 1000 compiles of stockfish with one variable `#define`d to one of 1000 values and run them through some test script(e.g. with cutechess)
After:
You make the Variable X load UCI variable A.
You compile a single stockfish binary and run tests with 1000 values of Variable X by sending these values as UCI variable A,(e.g. by option.A=x)

**Comment by snicolet** [comment]
@Chess13234 

It is not a problem to make mistake, you will learn from them and progress... It is if you shy away from what you don't know that you will forever stay a beginner :-) 

And you don't even have to use git a lot to help us, you just have to use the **sync-with-official.sh** script given in https://github.com/glinscott/fishtest/wiki/Creating-my-first-test. It is used by everybody else in the community because it makes it much more easier for approvers to check that your master is actually up-to-date with official master. A win/win for everybody, and considered polite practice too -- a step to help the work of the community (they deserve that step of yours, as they are just unpaid volunteers giving their time) :-)

**Comment by Chess13234** [comment]
@snicolet I don't see how this script will help.
I work with custom Stockfish builds that are modified(similar to the current pull request for testing) and are not the final patch i'm editing in on github(my workflow is vastly different than any of you i think).
Here is example of code i have(why would you want this on github):
 `   // Step 9. Null move search with verification search
if(base!=0){
    if ( pos.nulldistance_count()>1
  && (ss->ply >= thisThread->nmp_ply || ss->ply % 2 != thisThread->nmp_odd)
&&  eval >=  beta+(base/(depth/ONE_PLY)) 
)
    {
        assert(eval - beta >= 0);

        // Null move dynamic reduction based on depth and value
        Depth R = ((823 + 67 * depth / ONE_PLY) / 256 + std::min((eval - beta) / PawnValueMg, 3)) * ONE_PLY;

        ss->currentMove = MOVE_NULL;
        ss->contHistory = thisThread->contHistory[NO_PIECE][0].get();

        pos.do_null_move(st);

        Value nullValue = -search<NonPV>(pos, ss+1, -beta, -beta+1, depth-R, !cutNode, true);

        pos.undo_null_move();

        if (nullValue >= beta)
        {
            // Do not return unproven mate scores
            if (nullValue >= VALUE_MATE_IN_MAX_PLY)
                nullValue = beta;

            if (abs(beta) < VALUE_KNOWN_WIN && (depth < 12 * ONE_PLY || thisThread->nmp_ply))
                return nullValue;

            // Do verification search at high depths. Disable null move pruning
            // for side to move for the first part of the remaining search tree.
            thisThread->nmp_ply = ss->ply + 3 * (depth-R) / 4;
            thisThread->nmp_odd = ss->ply % 2;

            Value v = search<NonPV>(pos, ss, beta-1, beta, depth-R, false, true);

            thisThread->nmp_odd = thisThread->nmp_ply = 0;

            if (v >= beta)
                return nullValue;
        }
    }
}else{

 if (   !PvNode
        &&  eval >= beta
        &&  ss->staticEval >= beta - 36 * depth / ONE_PLY + 225
        && (ss->ply >= thisThread->nmp_ply || ss->ply % 2 != thisThread->nmp_odd))
    {
        assert(eval - beta >= 0);

        // Null move dynamic reduction based on depth and value
        Depth R = ((823 + 67 * depth / ONE_PLY) / 256 + std::min((eval - beta) / PawnValueMg, 3)) * ONE_PLY;

        ss->currentMove = MOVE_NULL;
        ss->contHistory = thisThread->contHistory[NO_PIECE][0].get();

        pos.do_null_move(st);

        Value nullValue = -search<NonPV>(pos, ss+1, -beta, -beta+1, depth-R, !cutNode, true);

        pos.undo_null_move();

        if (nullValue >= beta)
        {
            // Do not return unproven mate scores
            if (nullValue >= VALUE_MATE_IN_MAX_PLY)
                nullValue = beta;

            if (abs(beta) < VALUE_KNOWN_WIN && (depth < 12 * ONE_PLY || thisThread->nmp_ply))
                return nullValue;

            // Do verification search at high depths. Disable null move pruning
            // for side to move for the first part of the remaining search tree.
            thisThread->nmp_ply = ss->ply + 3 * (depth-R) / 4;
            thisThread->nmp_odd = ss->ply % 2;

            Value v = search<NonPV>(pos, ss, beta-1, beta, depth-R, false, true);

            thisThread->nmp_odd = thisThread->nmp_ply = 0;

            if (v >= beta)
                return nullValue;
        }
}




}`

**Comment by Chess13234** [comment]
The point i'm making of course the patch doesn't exist locally at all. The script assumes I have the patch, but in fact the patch is edited in on github directly(with file edit functionality). I.e. there is no legit "final patch branch" to commit to git.

**Comment by snicolet** [comment]
@Chess13234 If you refuse to help us, then I don't see why we should help you. Thanks for the discussion.

The patch is useless, closing.

**Pull request closed without merging**
