### PR TITLE
Simplify and extend skipping of plies with threads

### PR DESCRIPTION
**Pull request by vondele**
replaces the HalfDensity array with a compact and equivalent formula.
The result is identical for less than 20 threads, but extends the logic to more.

Bench: 6072262

### CODE REVIEW

**Comment by pb00068** [comment]
Extending the the same logic to more threads was tried in past and was not accepted, see  #727
It looks like greater skip-sizes do well on very short tc but not better (maybe also worser) at longer tc's. Anyhow it's a very difficult terrain to test, since LTC-tests with so many threads are extremely resource taxing in terms of electric power. For the rest I find the current implementation easier to read & more self-explaining.

**Comment by vondele** [comment]
@pb00068 #727 added another 10 lines to the matrix, and as you point out, it was difficult to obtain statistically meaningful results at 31 threads to support that extension. As you also said in that PR, the current way of handling is 'just a fall-back-mechanism which allows us to have a map of finite size.'

It is easy to implement that fall-back mechanism (i.e. reuse skipsizes for threads>20) also in the current simplification (which would make it non-functional at any thread count), but there is no data that supports the need for the fall-back either, so I went for the simple form.

**Comment by pb00068** [comment]
@vondele 

> As you also said in that PR, the current way of handling is 'just a fall-back-mechanism which allows us to have a map of finite size.'

This was actually an earlier statement from me on a earlier commit.
Looking at the partial result of http://tests.stockfishchess.org/tests/view/57849a0f0ebc5972faa16881 and other results of tests with greater skip-sizes suggest IMO that this fall-back-mechanism isn't a bad thing after all.

**Comment by vondele** [comment]
With the latest commit the branch is now fully equivalent to master (afaict). 

However, I don't think the two tests referenced above by @pb00068 are conclusive about the value of the fall-back: both the positive outcome and the negative outcome are for 10000 games only, and both are within error bars equal to zero.

I would prefer the version of the PR without the fall-back.

**Comment by snicolet** [comment]
I have to admit that if I read the following function in a program, I would be at a complete loss to understand what it does, and how it works:

````
bool skip_ply(int idx, int ply) {
     int ones=0;
     while (ones*(ones+1)<idx) ones++;
     return ones==0 ? false : ((ply+idx-1)/ones-ones)%2==0;
   }
````

**Comment by lp--** [comment]
To me also current master looks simpler

**Comment by vondele** [comment]
@snicolet well it codes exactly the logic that is now hardcoded in a 20 lines table.

However, I agree that this needs a few comment lines. 'ones' is the number of plies that are executed consecutively (i.e. the ones in the table). As in the old table that grows slowly (square of that ones-block size is roughly the number of threads), which the while loop counts. The next line just yields true of false in blocks of 'ones' which is basically what the result of the integer division yields.. even or odd.

I'll be travelling and email from computers in the next week, so I'll rejoin the discussion later.

**Comment by mcostalba** [comment]
@vondele coding style has many issues, it is easier to directly write here a normalized version than to point all the issues:

```
  // Skip half of the plies in blocks depending on the thread idx
  bool skip_ply(int idx, int ply) {

    if (idx)
        idx = (idx - 1) % 20 + 1; // Cycle after 20 threads

    int ones = 0;
    while (ones * (ones + 1) < idx)
        ones++;

    return ones && ((ply + idx - 1) / ones - ones) % 2 == 0;
  }
```

And also:

```
  // Skip plies for helper threads
  if (skip_ply(idx, rootDepth / ONE_PLY + rootPos.game_ply()))
      continue;
```

**Comment by zamar** [comment]
I'm fine with this change as long as:
- The code is cleaned up (per @mcostalba suggestion)
- A simple regression test (e.g. with 7 threads) is done. It could e.g. be 10k games with 15+0.1.

**Comment by snicolet** [comment]
In C++11, the sign of the modulus operator a%b is always the same as a (when b is non-zero), so we don't need the test `if (idx)` in the line
````
idx = (idx - 1) % 20 + 1; // Cycle after 20 threads
````

**Comment by pb00068** [comment]
Hm, a [simplified version](https://github.com/vondele/Stockfish/commit/34daec0013626869c10665d3e251133eb1b9cade) of this patch producing an equivalent HalfDensity array was tested at 11 threads and [failed](http://tests.stockfishchess.org/tests/view/58a892770ebc59035df322d3)...

**Comment by vondele** [comment]
I have pushed an updated version (still non-functional) including the suggestions by @mcostalba and @snicolet. 

I'll start a regression test as requested as requested by @zamar. 

Concerning the failed test of the simplification (as mentioned by @pb00068), this simplification was not (exactly) equivalent. Admittedly, it was surprising to see it fail.

**Comment by vondele** [comment]
@locutus2 thanks should be fixed now:
http://tests.stockfishchess.org/tests/view/58b007d90ebc59035df325da

**Comment by vondele** [comment]
The additional test finished as : 

ELO: -2.19 +-3.5 (95%) LOS: 11.4%
Total: 10000 W: 1330 L: 1393 D: 7277

which is still consistent with zero with the given error bars. There was one worker with 178 time-outs. 

I've verified once more that the current patch is functionally identical to master.

**Comment by mcostalba** [comment]
@vondele I suggest to post the debug code when you verify it, for instance I have verified your patch is equivalent to the original with this snippet:

```
  for (int game_ply = 1; game_ply < 512; ++game_ply)
      for (Depth rootDepth = ONE_PLY; rootDepth <= DEPTH_MAX; rootDepth += ONE_PLY)
          for (int idx = 1; idx < 512; ++idx)
          {
              const Row& row = HalfDensity[(idx - 1) % HalfDensitySize];
              bool c1 = (row[(rootDepth / ONE_PLY + game_ply) % row.size()]);
              bool c2 = skip_ply(idx, rootDepth / ONE_PLY + game_ply);

              if (c1 != c2)
                  std::cout << game_ply << ", " << rootDepth / ONE_PLY << ", " << idx << std::endl;
          }
```

**Pull request closed without merging**
