### PR TITLE
For template numeric options.

### PR DESCRIPTION
**Pull request by Kozlov-Sergey-Aleksandrovitch**

### CODE REVIEW

**Comment by AndyGrant** [comment]
Surely you are joking

**Comment by Hanamuke** [comment]
At the very least, please remove the two useless files from your commit and add a description ...

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Why to remove 2 files?

cmd file is used to build easy.
gitignore file is used to dismiss useless local files.

**Comment by snicolet** [comment]
The current master code seems fine to me, as it it 100% compatible to what we have had in Stockfish for years and compliant with the UCI "specification".

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Отъебись, краснокожий.

**Comment by snicolet** [comment]
> Отъебись, краснокожий.

I have tried to translate this with Google translate, and got "Fuck off, redskin".

Closing.

**Pull request closed without merging**
