### PR TITLE
Introduce lazy evaluation

### PR DESCRIPTION
**Pull request by Stefano80**
After we have taken into account all cheap evaluation terms, we check whether the score exceeds a given threshold. If this is the case, we return a scaled down evaluation.

STC:
LLR: 3.35 (-2.94,2.94) [0.00,5.00]
Total: 12575 W: 2316 L: 2122 D: 8137

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,5.00]
Total: 67480 W: 9016 L: 8677 D: 49787

Bench: 5367704

### CODE REVIEW

**Comment by Stefano80** [comment]
Original patch (only cosmetic changes for the pull request)

https://github.com/Stefano80/Stockfish/commit/bc016dcf0eced79bf67b9c7f770e9878bca0e79a

STC test:
http://tests.stockfishchess.org/tests/view/5873dbe70ebc5915193f7312

LTC test:
http://tests.stockfishchess.org/tests/view/5873ef6b0ebc5915193f7320

**Comment by Rocky640** [comment]
I would merge your two functions into one.
Something like...

const Value lazyThreshold = Value(1500);
Score lazy_score(Position pos, Score score)
{
  if (      std::max(mg_value(score), eg_value(score))  >=  -lazyThreshold
     &&  std::min(mg_value(score), eg_value(score)) <=  lazyThreshold)
      return SCORE_ZERO;

   Value v = (mg_value(score) + eg_value(score)) / 2;  
   return (pos.side_to_move() == WHITE ? 1 : -1) * (3 * lazyThreshold + v) / 4;  
}

Score lazyScore = lazy_score(pos, score);
if (lazyScore)
    return lazyScore;

This could lead to a simplification (which would need to be tested, since different bench)

Score lazy_score(Position pos, Score score)
{
   Value v = (mg_value(score) + eg_value(score)) / 2; 
   if ( v >= - lazyThreshold && v <= -lazyThreshold)
        return SCORE_ZERO;

   return (pos.side_to_move() == WHITE ? 1 : -1) * (3 * lazyThreshold + v) / 4;  
}

**Comment by Rocky640** [comment]
I would merge your two functions into one.
 Something like this (untested)

const Value lazyThreshold = Value(1500);
Score evaluate_lazy_score(Position pos, Score score)
 {
  int sign =  std::max(mg_value(score), eg_value(score)) < -lazyThreshold ? -1
                 : std::min(mg_value(score), eg_value(score)) > lazyThreshold ?  1
                  : 0;
  if (!sign) 
      return SCORE_ZERO;

 Value v = (mg_value(score) + eg_value(score)) / 2;
 return (pos.side_to_move() == WHITE ? sign : -sign) * (3 * lazyThreshold + abs(v)) / 4;
 }

 if (Score lazyScore = evaluate_lazy_score(pos, score))
    return lazyScore;

This could lead to a small simplification (which would need to be tested, since different bench)
Something like this...

Score evaluate_lazy_score(Position pos, Score score)
 {
 Value v = (mg_value(score) + eg_value(score)) / 2;
 int sign =   v < -lazyThreshold ? -1
                  : v >  lazyThreshold ?  1
                  : 0;
  if (!sign) 
      return SCORE_ZERO;

 return (pos.side_to_move() == WHITE ? sign : -sign) * (3 * lazyThreshold + abs(v)) / 4;
 }

**Comment by vondele** [comment]
@mcostalba I think your approach to get the bench doesn't work for pull requests (see failure here, which gets as a reference the master bench), might be that travis just patches the master branch (without commit), so the 'git log' is still at the master status. The proposal in #960 would work.

**Comment by ceebo** [comment]
A similar idea to Rocky640 with merging the two functions into one.

But also I don't like to use "abs" when it's not necessary. Apply the sign detection to Threshold and leave the sign of v alone. Completely untested code follows. With any luck it won't affect bench but I'm not sure.

```
Value lazy_eval(Score score) {

        if (mg_value(score) > Threshold && eg_value(score) > Threshold)
                signedThreshold = Threshold;
        else if (mg_value(score) < -Threshold && eg_value(score) < -Threshold)
                signedThreshold = -Threshold;
        else return VALUE_ZERO;

        Value v = (mg_value(score) + eg_value(score)) / 2;
        return v + (signedThreshold - v) / 4;

}

...

Value lazy_value = lazy_eval(score);
if (lazy_value != VALUE_ZERO)
        return pos.side_to_move() == WHITE ? lazy_value : -lazy_value;
```

**Comment by Rocky640** [comment]
Trying to figure out some implications...
This idea will change the engine in many ways.

For example, this 1500 is about one rook + one pawn (or one bishop + one knight)
This is a huge advantage indeed, and most of the other evaluation factors will probably favor the strong side too (more pieces means usually more mobility, more threats, and so on).

Let's say that one side is up by a queen.
If the score after the material evaluation is roughly S(2650, 2650)
lazy_eval will be 1500 + (2650 - 1500) / 4 which is 1500 + 1150/4 = 1787

But if we would have evaluate the full thing, final score is probably higher than 2650, let's say 2700.

So the engine will output something like 7.20 instead of 10.88... quite a change. 
When there are some adjudication rules, this might produce longer games.
Also, people will ask... "why is the score only + 7 ?"
Internally, 1787 is fine, but we might have to eventually recalibrate our output by reverse engineering the formula.

I also wonder how this will change the quality of the analysis by the engine 
when it has a huge advantage, Engine might find its way to a win, but might exhibit less spectacular finishes.

This is quite a breakthrough by Stefano. Congratulations. 
This will keep a few people busy for a while.

This opens many areas for research. Here are a few questions that comes to mind.
a) should we add more lazy_eval stages ?
b) which are the most costly chunks (in computational time) in evaluate 
    compared to average magnitude of score change.
c) or more simply, how much ELO is brought by each evaluation chunks ?
    (we are somewhat limited because evaluate_pieces is needed for almost anything else after)
d) should we include some kind of lazy passed pawn eval in the first stage lazy eval ?
e) should we apply lazy eval only to leaf nodes in search ?
f) are there cases where we do not want to apply lazy eval ?

**Comment by mcostalba** [comment]
@vondele thanks for reporting the issue with bench number in PR branches. It should be fixed now.

**Comment by IIvec** [comment]
Lazy eval simply prove that SF evaluation is not optimal. 
But, is it the best way to improve it to commit a patch which is a small Elo gain, but it will be a break on a long run?

**Comment by IIvec** [comment]
This opens many areas for research. Here are a few questions that comes to mind.
a) should we add more lazy_eval stages ?

Why not a continuous version?

**Comment by Rocky640** [comment]
And everywhere differentiable ? ;)

By multi stage lazy, which Stefano already thought of, I meant something like this
https://github.com/Stefano80/Stockfish/commit/fb9bfad8e1efed39c1c5821b9eef8683447b8080
If there is any benefit there, we would just need to find the ultimate order for each eval subroutines, or group them differently and check the lazy evaluation at one or two more points.

**Comment by IIvec** [comment]
Just one more comment from my side:
This patch is only a time saver when evaluation is high.
This test shows how bad this evaluation actually is:
http://tests.stockfishchess.org/tests/view/58763dae0ebc5915193f7409

**Comment by Stefano80** [comment]
Hi,

some remarks to be comments by @IIvec and @Rocky640 

1) Optimality comes with a prize. The patch shows that the prize is in some cases too high.
2) Multi-stage is interesting. I noticed that the probability of eval < 1000 given lazy_eval > 1500 is very low and so I came to the idea of this test (numbers are representative). In the following stages you could lower the threshold. I only suspect that the time one is saving is not so much after the first stage.
3) The idea of moving some passed pawn evaluation earlier is quite cool.
4) I dont think that making lazy_eval only on the leaves or something like that could work, since the TT would become quite incosistent, but who knows.

**Comment by lucasart** [comment]
@mcostalba: are you going to merge this? I'm waiting to schedule tests on top of it.

**Comment by mcostalba** [comment]
I am quite puzzled by this patch mainly because I think it does not scale to longer TC. On the other hand this is just the first cut and more work is ongoing.

So my plan is to commit this one, wait for some further test on followup ideas and refinements and when I see it is all more or less quiet I will submit a SPRT[-3, 1] at very long TC, something like 120 or even 180 seconds to try to remove it all.

**Comment by Mindbreaker1** [comment]
There is no reason a different calculation method could not be better in large advantage situations that would do poorly if applied in other situations. Saying it is only 2500 Elo is meaningless.  I am sure there are many things in Stockfish that if applied in different situations than directed, would harm strength.  Endgame values vs middlegame values for example.  If you just chose the middle value of each of these pairs middlegame-endgame values it would probably loose hundreds of Elo.

**Comment by Rocky640** [comment]
Here is one STC result
http://tests.stockfishchess.org/tests/view/5876efc30ebc5915193f7459
It will fix my rants about the output changes.

**Comment by Stefano80** [comment]
Hi @mcostalba,

I made some easy experiments to understand why it works well at STC and why it works less well at LTC (also said that +2 logistic Elo at LTC is not that bad). I want to share with you all.

Experiments done:
- track rate of lazy evaluation over depth. No effect on start position (around 4% or in bench, around 7%).
- compare rate of lazy evaluation in opening and endgame (I have a balanced endgames suite I use for this kind of stats). No effect, always around 4%.
- track rate of lazy evaluations over hash size. No effect in either or the tests.

I have some theories which are not immediately falsified by the previous observations. The truth is probably a linear combination of them:
- at LTC less time is used for evaluation and more time for something else. Does anybody have ideas on how to generate data about this?
- at LTC the time advantage does not count much. This could well be, and could be tested on the framework by computing Bayes-Elo difference for master branch with nodestime say 110 vs 100 and 660 vs 600 (or something similar).
- balanced positions are more common at LTC, pushing down lazy evaluation rate. This could be done locally with cutechess-cli in debug mode. This is somewhat corroborated by the difference between lazy eval rate from starting position and bench.

**Comment by locutus2** [comment]
If the root position reach a search value above the threshold (~600 cp) lazy eval kicks in. But on fishtest we use only 400 cp for adjudication a win. So if the lazy eval version has more problems then master in winning this "winning" positions this were hided by the early adjudication. I think some test without winning adjudication (or way higher adjudication threshold) is recommended.

**Comment by VoyagerOne** [comment]
Maybe an idea is to do lazy eval only at nonPV nodes.

**Comment by Rocky640** [comment]
@locutus2 
Since fishtest adjudication is given only if BOTH engines scores >=400 cp
it would suffice to make a lazy eval version with the uci output truncated to always be in the (-399, 399) range and test this against current master

**Comment by Rocky640** [comment]
Another classical idea is to call evaluate with some (alpha , beta) window, and use the lazy_eval if it is safely outside this window (for example, by a 200 cp margin).

**Comment by locutus2** [comment]
@Rocky640 
That's  a nice way to avoid adjudicated wins. I like it!

@Stefano80 
Would you start such a test at STC?

**Comment by IIvec** [comment]
Can't we simply reduce time usage when eval is high and problem solved?

**Comment by Stefano80** [comment]
Hi @locutus2 , I did once a test without adjudication. You just need to always write 0 cp in the output, or something like that. I dont think it will make any difference, but feel free to test it.

**Comment by Stefano80** [comment]
Hi @IIvec : it will not work, lot of tests have been tried in that direction.

**Comment by IIvec** [comment]
Hi @Stefano80 : thank you for the information.

**Comment by stockfishdeveloper** [comment]
Perhaps we could use statistics to determine how good an eval has to be to be x percent sure of winning it.
But then we're moving into the realm of machine learning......

**Comment by ddugovic** [comment]
Maybe combine @Rocky640 's and @VoyagerOne 's ideas to maximize performance: for non-PV node evaluation, use an (alpha, beta) window.

**Comment by mstembera** [comment]
Congrats!
Wonder if using game phase to combine mg and eg (instead of averaging) in lazy_eval() would be a good idea?

**Comment by mcostalba** [comment]
Merged with de02768af7b37c903e3227

**Pull request closed without merging**
