### PR TITLE
King safety tuning with values obtained by SPSA.

### PR DESCRIPTION
**Pull request by NicklasPersson**
STC
ELO: 1.38 +-2.1 (95%) LOS: 90.1%
Total: 41981 W: 8529 L: 8362 D: 25090
http://tests.stockfishchess.org/tests/view/54bebaa00ebc5946cd385822

LTC
ELO: 2.07 +-2.1 (95%) LOS: 97.3%
Total: 34859 W: 5967 L: 5759 D: 23133
http://tests.stockfishchess.org/tests/view/54bf79d30ebc594f7529270e

Bench: 8514821

These test was done against branch HighKingSafety.

### CODE REVIEW

**Comment by mcostalba** [comment]
Congrats! You are squeezing every bit out of king safety :-)

For people not following these tests closely: this patch succeed against
another already proved good (against master) patch.

**Comment by NicklasPersson** [comment]
Thanks, and I am planning to continue squeezing but it gets harder and the gold rush with these parameters is probably over. There is still probably a lot of ELO to be gained with these parameters but optimizing 113 dependent parameters is not easy.

**Comment by lucasart** [comment]
@glinscott @zamar @mcostalba: It would make life a lot easier if you created a SF6 branch, for maintenance only, and started committing patches for SF7 to the master branch. It's becoming very hard to test anything, because master needs to be rebased by merging several patches (and we don't even know which ones will be merged or not...)

**Comment by zamar** [comment]
The only problem is that I wouldn't want to lose abrok.eu compiles for SF6 (that's where most people go anyway).

So maybe the best thing is to create a temporary sf7_dev branch and merge it after SF6 is out...

**Comment by mcostalba** [comment]
@zamar I am not sure the added complexity worths it. I would say it is better to define a strict and short deadline for SF 6 out and respect it.

**Comment by glinscott** [comment]
Are we open for merging now?

**Comment by zamar** [comment]
Sure, just remember to commit "Restore develoment version" patch first, to
remove "6" from Version string.

**Comment by zamar** [comment]
Done.

**Pull request closed without merging**
