### PR TITLE
Simplify king ring determination

### PR DESCRIPTION
**Pull request by protonspring**
Replaces a file_of and a compare with a single AND.  This is a non-functional simplification.

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 13530 W: 2972 L: 2835 D: 7723
http://tests.stockfishchess.org/tests/view/5be0dd590ebc595e0ae2d6b5

### CODE REVIEW

**Comment by mstembera** [comment]
@protonspring Nice.  Why is
```C++
if (pos.square<KING>(Us) & (Rank1BB | Rank8BB))
```
different?

**Comment by mstembera** [comment]
Ah I see now.  If say the white king is on the 8th rank.

**Comment by protonspring** [comment]
Yes. It doesn't change the bench, but it seems to hurt elo.  How often is
the King on the 8th rank with enough material to trigger the condition?

Seems super duper rare, but is enough to hurt.

**Comment by protonspring** [comment]
Or.  Maybe it does more shifting which is slower? I don't know.  it seems
like it shouldn't affect anything at all.

**Comment by protonspring** [comment]
It's a simplification because it's the same functionality with less code/operations.  A single AND operation is more simple than a file_of() (which is an AND in and of itself) and a compare. 1 is less than 2.  It's not really difficult.

**Comment by mcostalba** [comment]
The AND is between a billboard and  a Square and it is not a simple AND but an overloaded operation, in particular there is a look up involved (see types.h)

The compare is against a compile time constant so it is equivalent to a compare by 0 (what you call a "removed compare").

It would be interesting to see the assembly output in both cases. Speculating on possible microptimizations is very slippery: compiler + CPU scheduling easily overrule what we think is faster.

Please note that I am not advocating current version is faster than your, just that it is far from clear your is faster and that anyhow (considering that you don't want to try a SPRT) the only reason to commit is because of a possible readability simplification, and in this latter case my opinion is that new version is not more readable than master.

**Comment by protonspring** [comment]
No offense, but any chance you could not post on my pull requests?

**Comment by snicolet** [comment]
I second Marco's opinion. 
Closing.

**Pull request closed without merging**
