### PR TITLE
Threats simplified

### PR DESCRIPTION
**Pull request by Rocky640**
Using less parameters and code to compute Threats
Includes also a few spacing edits. 

Run as a simplification.

Passed STC 10+0.1
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 18879 W: 3725 L: 3600 D: 11554

Passed LTC 60+0.4
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 74116 W: 11001 L: 10958 D: 52157

### CODE REVIEW

**Comment by joergoster** [comment]
Congrats!

**Comment by jcalovski** [comment]
Nice one!

**Comment by zamar** [comment]
Nice. approved.

**Comment by VoyagerOne** [comment]
You know this patch is good when Lucasart congratulates you.  :)

Nice work.

**Comment by lucasart** [comment]
@Rock640: Actually, 60+0.4 is the new standard now. Marco decided to increase the length of LTC:
https://github.com/glinscott/fishtest/pull/68
I can't say I agree with that, but it's another discussion…

**Comment by glinscott** [comment]
Great!  Looks good.

**Comment by mcostalba** [comment]
Applied.

**Pull request closed without merging**
