### PR TITLE
Code style in evaluate.cpp

### PR DESCRIPTION
**Pull request by mcostalba**
Many lines involved but mainly for code reformatting.

This is just triviality. I will submit any specific reformat on
its own PR.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
I have added other 2 commits, mainly to isolate out and easing review of the most interesting change that is using scores instead of values in passed pawns evaluation.

If series is accepted I can squash it in a single commit before to merge.

**Comment by snicolet** [comment]
Looks good to me, will apply.

The only minor point is that I prefer "KingProtector" to "FarKing", because KingProtector makes it obvious that this is for the defense of king, while "FarKing" is generic and we don't know if it is for attack or defense. Of course I understand that you tried to remove the negative numbers, but the name is important too as a motivation for newcomers to work on this ("FarKing" is abstract, "KingProtector they understand at once). What do you think?

I have checked that the speed is the same than current master on my system:

````
Total time (ms) : 90554
Nodes searched  : 188535606
Nodes/second    : 2082024
testedpatch
------------------------
Total time (ms) : 90690
Nodes searched  : 188535606
Nodes/second    : 2078901
master
```

**Comment by Rocky640** [comment]
a) You have a //FIXME that will have to be removed...

b) The following comment is no longer true.
 // Order of evaluations should be preserved

Maybe replace this comment with
 // Minors and majors must be evaluated first
And make only one long operation out of 855 to 858 just like you do for 863 to 865.

c) FarKing is weird.  FarFromOurKing is more descriptive but KingProtector is fine.

d) Passed[RANK_NB] and PassedRank[RANK_NB]  are confusing. 
    Since we have a PassedFile[FILEPNB], I would rename the first to PassedRank,
    and the second to PassedDanger (with some analogy to our KingDanger units)

**Comment by mcostalba** [comment]
@snicolet @Rocky640 thanks for your feedback!

I have addressed your comments, please check.

**Comment by mcostalba** [comment]
Finally I have reformatted tracing output, the most sensible change is that now pawns evaluation is split for white and black as for the other pieces. This is what should have be done already.

**Comment by joergoster** [comment]
Awesome! Maybe you want to run a SPRT(-4, 0)@STC test just to be on the safe side, considering the amount of changes?

**Comment by Rocky640** [comment]
Three more comments
a)
// Add a bonus for safe slider attack threats on opponent queen
Some people thought it was for actual attacks on queen, which is not.

Maybe call the bonus UnsafeQueen with the following comment
// Add a bonus for potential to harass the enemy queen with a safe slider attack
or simply
// Bonus for potential to harass the enemy queen with a safe slider attack

"// Add a" is useless elsewhere too.

b) opponent => enemy (for consistency

c) the kingRIng comment is rather verbose, and does not even hint that it can be 0 in late endgame.

**Comment by mcostalba** [comment]
@Rocky640 thanks for the feedback. Done.

**Comment by mcostalba** [comment]
Test passed :-)

http://tests.stockfishchess.org/tests/view/5a8953af0ebc590297cc83ab

**Comment by snicolet** [comment]
Thanks, merged via https://github.com/official-stockfish/Stockfish/commit/67f5f54a29b5d5d2bd9e43bfcc3a95bcc142d664

**Comment by snicolet** [comment]
Just for future reference: we have to remember of a subtile point here about the order of the pieces scoring.

In C++ the order of X = A() - B() + C() - D() is compiler dependent, this means that with this patch we can no longer be sure that pieces are evaluated in the order knight -> bishop -> rook -> queen.

In current master this is not important because evaluation of major doesn't rely on the minor attacks being calculated, but I just write it down there as a reminder if people would like to include such a feature and get surprised if different compilers giving different benches.

**Comment by Rocky640** [comment]
When I compile this I have a few warnings
They will all disappear if we rename the int initiative for something else.


evaluate.cpp: In member function 'Score {anonymous}::Evaluation<T>::initiative(V
alue) const':
evaluate.cpp:761:9: warning: declaration of 'initiative' shadows a member of 'th
is' [-Wshadow]
     int initiative =   8 * outflanking
         ^
evaluate.cpp: In instantiation of 'Score {anonymous}::Evaluation<T>::initiative(
Value) const [with Trace::Tracing T = (Trace::Tracing)0u]':
evaluate.cpp:865:40:   required from 'Value {anonymous}::Evaluation<T>::value()
[with Trace::Tracing T = (Trace::Tracing)0u]'
evaluate.cpp:894:42:   required from here
evaluate.cpp:765:22: warning: declaration of 'initiative' shadows a member of 't
his' [-Wshadow]
                     -136 ;
                      ^
evaluate.cpp: In instantiation of 'Score {anonymous}::Evaluation<T>::initiative(
Value) const [with Trace::Tracing T = (Trace::Tracing)1u]':
evaluate.cpp:865:40:   required from 'Value {anonymous}::Evaluation<T>::value()
[with Trace::Tracing T = (Trace::Tracing)1u]'
evaluate.cpp:908:42:   required from here
evaluate.cpp:765:22: warning: declaration of 'initiative' shadows a member of 't
his' [-Wshadow]

**Comment by snicolet** [comment]
> They will all disappear if we rename the int initiative for something else.

`bonus` ?
`complexity` ?
`potential` ?
`dynamism` ?

**Comment by Rocky640** [comment]
I was thinking of `int i`
but int complexity is OK ;)

Your original idea was to do something about initiative, but as it is in current master, 
we can view this as the endgame prospects once all the pieces are exchanged, and we are down to king and pawns. The stronger side can eventually "threaten" to drive the game to such a king and pawn endgame where there is still some life in the position.

**Comment by mcostalba** [comment]
@Rocky640 which compiler do you use?

I don't understand why Trevis CI did not catch this, we compile with -Wshadow (and even with -Werror) but I checked Trevis CI compile log and tehy are clean, both g++ and clang

**Comment by Rocky640** [comment]
make profile-build ARCH=x86-64-modern COMP=mingw

Not sure which mingw though. I think it is 4.8.1
I only use this to compile sf and I think I never updated this for 3 years.

**Comment by joergoster** [comment]
@Rocky640 @mcostalba No warnings with gcc7.2.0 / Linux

**Comment by mcostalba** [comment]
@Rocky640 could you please run:

$ g++ -v

**Comment by Rocky640** [comment]
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=C:/Program\ Files/mingw-w64/x86_64-4.9.2-posix-seh-rt_v3-rev
1/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.2/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.9.2/configure --host=x86_64-w64-mingw32 --bu
ild=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysr
oot=/c/mingw492/x86_64-492-posix-seh-rt_v3-rev1/mingw64 --with-gxx-include-dir=/
mingw64/x86_64-w64-mingw32/include/c++ --enable-shared --enable-static --disable
-multilib --enable-languages=ada,c,c++,fortran,objc,obj-c++,lto --enable-libstdc
xx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-
lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --
enable-version-specific-runtime-libs --disable-isl-version-check --disable-cloog
-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootst
rap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --di
sable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 -
-with-libiconv --with-system-zlib --with-gmp=/c/mingw492/prerequisites/x86_64-w6
4-mingw32-static --with-mpfr=/c/mingw492/prerequisites/x86_64-w64-mingw32-static
 --with-mpc=/c/mingw492/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mi
ngw492/prerequisites/x86_64-w64-mingw32-static --with-cloog=/c/mingw492/prerequi
sites/x86_64-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='x8
6_64-posix-seh-rev1, Built by MinGW-W64 project' --with-bugurl=http://sourceforg
e.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw492/x86_64-492-posix-seh-rt
_v3-rev1/mingw64/opt/include -I/c/mingw492/prerequisites/x86_64-zlib-static/incl
ude -I/c/mingw492/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2
 -pipe -I/c/mingw492/x86_64-492-posix-seh-rt_v3-rev1/mingw64/opt/include -I/c/mi
ngw492/prerequisites/x86_64-zlib-static/include -I/c/mingw492/prerequisites/x86_
64-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw492/x86_64-492
-posix-seh-rt_v3-rev1/mingw64/opt/lib -L/c/mingw492/prerequisites/x86_64-zlib-st
atic/lib -L/c/mingw492/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 4.9.2 (x86_64-posix-seh-rev1, Built by MinGW-W64 project)

**Comment by mcostalba** [comment]
I guess this is a compiler bug, because the option should apply only to variables, not between a variable and a function:

```
-Wshadow=local

    Warn when a local variable shadows another local variable or parameter. This warning is enabled by -Wshadow=global.
```
Indeed in newer compilers there is no more warning. Anyhow I guess it is appropiate to rename the variable anyhow.

**Comment by mcostalba** [comment]
It is 4.9.2, not sure the warning is correct (it shadows a member not a variable), indeed in newer compilers there is no warning. Anyhow I think it is appropriate to rename the variable.

**Comment by snicolet** [comment]
@Rocky640  
Warning problem fixed via https://github.com/official-stockfish/Stockfish/commit/6c898a10be75bc2c295a7dca7f72e51e76ec8293

**Pull request closed without merging**
