### PR TITLE
Allow inCheck pruning.

### PR DESCRIPTION
**Pull request by VoyagerOne**
Allow inCheck pruning.

STC:
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 14140 W: 2625 L: 2421 D: 9094

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 11558 W: 1555 L: 1379 D: 8624

Bench:  5256717

### CODE REVIEW

**Comment by mcostalba** [comment]
Merged with ab26c61971c2f73

This is a bit tricky because we don't want to prune the only legal evasions, even if with negative SEE. So add an assert to avoid this subtle bug to slip in later.

**Comment by VoyagerOne** [comment]
@mcostalba 
We already check to make sure that we play at least 1 legal move 
bestValue > VALUE_MATED_IN_MAX_PLY

we never shallow prune are first legal move.

**Comment by mcostalba** [comment]
As a related topic, I am really disappointed that fixing the move count failed:

http://tests.stockfishchess.org/tests/view/57e77c630ebc59763f358e1a

Indeed we are now mixing oranges and apples in moveCount variable, because it is incremented always at the beginning of the move cycle, then it is decremented if the move is not legal **but has not been pruned before!**

So for instance suppose we have these sequences of legal (L) and not legal (I) moves:

```
L, I, I, L, L  -> moveCount = 3
L, I (pruned), I, L, L  -> moveCount = 4 !
L, I, I, L(pruned), L  -> moveCount = 3 !!
```

If moveCount == legalMoveCount then second and third cases are wrong
If moveCount == pesudoLegalMoveCount then all cases are wrong

This is a current inconsistency, the easiest fix is to consider moveCount == pesudoLegalMoveCount and drop the 

`ss->moveCount = --moveCount;`

After checking for legality. As a side effect we probably increase pruning/LMR reductions.

Unfortunately there is an assert if I just remove the decrement...

**Comment by Kingdefender** [comment]
Already closed, but is it prudent to add some assert that we don't do value based pruning when in check. Because static eval is now VALUE_NONE, but there is no guarantee that is a very high number. This also affects 'improving' condition, so movecount pruning, but not so much probably.

**Pull request closed without merging**
