### PR TITLE
Retire ThreadBase

### PR DESCRIPTION
**Pull request by mcostalba**
Now that we don't have anymore TimerThread, there is
no need for this long class hierarchy.

No functional change.

### CODE REVIEW

**Comment by mcostalba** [comment]
Big simplification of thread code. Another fallout of lazy smp: we don't need anymore to
differentiate between sleeping at split points and at search finished.

I am testing with SPRT[-5, 0] just to be safe, as suggested by Joona:

http://tests.stockfishchess.org/tests/view/563f18de0ebc59227df170df

**Comment by zamar** [comment]
approved (assuming that the test passes).

**Comment by mcostalba** [comment]
It passed now:

LLR: 2.97 (-2.94,2.94) [-5.00,0.00]
Total: 30990 W: 4945 L: 4942 D: 21103

Gary?

**Comment by zamar** [comment]
@mcostalba: Gary is on vacation, go ahead and commit.

**Pull request merged**
