### PR TITLE
Introduce one_or_more(Bitboard b)

### PR DESCRIPTION
**Pull request by vondele**
The idiom !!b is confusing newcomers (e.g. Stefan needs explaining here https://groups.google.com/d/msg/fishcooking/vYqnsRI4brY/Gaf60QuACwAJ).

In analogy to more_than_one, introduce one_or_more.

No functional change.

### CODE REVIEW

**Comment by Rocky640** [comment]
I like the idea. More readable and may help avoid coding mistakes.

But  we can also replace all those  `!!b` with `bool (b)`

If we introduce a new function for this, I would prefer "at_least_one"
it seems more direct to me.

**Comment by Stefano80** [comment]
I also like it! But I prefer one_or_more, it sounds more like SF

**Comment by MichaelB7** [comment]
“One or more” is better 😊

**Comment by syzygy1** [comment]
How about replacing "!!b" with "b != 0" instead? I find that easier to read than "one_or_more(b)".

And I think in most places where !!b occurs, we are testing that it is "not zero" rather than "one or more".

Either way, the inexperienced reader will still have to realise that true == 1.

**Comment by tthsqe12** [comment]
The & is also confusing (not an address?). Could you make a function squares_in_both? The && is also confusing...

**Comment by mcostalba** [comment]
The most natural IMO is bool(v) or alternatively b != 0

one_or_more() is a not idiomatic ad-hoc and custom wrapper: people will lookup it to understand what it does anyhow.

**Comment by vondele** [comment]
@mcostalba so went for the solution with bool().

**Pull request merged**
