### PR TITLE
Pawns Tuning

### PR DESCRIPTION
**Pull request by FauziAkram**
A simple tuning of Pawns parameters, and some PSQT changes.

Passed STC:
LLR: 2.94 (-2.94,2.94) {-0.25,1.25}
Total: 219424 W: 43681 L: 43103 D: 132640
Ptnml(0-2): 4014, 25760, 49669, 26172, 4097
https://tests.stockfishchess.org/tests/view/601bce167f517a561bc491eb

Passed LTC:
LLR: 2.94 (-2.94,2.94) {0.25,1.25}
Total: 317312 W: 42525 L: 41579 D: 233208
Ptnml(0-2): 2447, 30157, 92636, 30835, 2581
https://tests.stockfishchess.org/tests/view/601c21557f517a561bc49227

### CODE REVIEW

**Comment by FauziAkram** [comment]
@Vizvezdenec is this a new rule?

**Comment by FauziAkram** [comment]
@vondele do you want me to close this pull request and open a new one with just a few commits?

**Comment by snicolet** [comment]
@FauziAkram 
Yes, a pull request with just one commit would be fine :-)

**Comment by Lolligerhans** [comment]
@FauziAkram `git merge --squash` can automatically create single commit. It is hardly any different for vondele.

**Comment by vondele** [comment]
I do actually prefer PRs that have a single commit. I tend to `git rebase -i` PRs so that's a little more work if there are multiple commits.. let me have a look to `git merge --squash` however.

**Comment by vondele** [comment]
I'll merge based on https://github.com/official-stockfish/Stockfish/pull/3337

**Pull request closed without merging**
