### PR TITLE
Updated top CPU contributors as of 2023-04-12

### PR DESCRIPTION
**Pull request by maximmasiutin**
I opened https://tests.stockfishchess.org/users and sorted by CPU Hours, then exported columns 1,4,5 to a coma-separated file with just 3 columns, and used the following Perl script to produce the output text:

```
#!/usr/bin/perl

print <<EOF;
Contributors to Fishtest with >10,000 CPU hours, as of 2023-04-12.
Thank you!

Username                                CPU Hours     Games played
------------------------------------------------------------------
EOF

while (<>)
{
   if (/\s*([^,]+),([^,]+),([^,]+)\s*/)
   {
       if ($2 > 10000) {printf "%-32s%17d%17d\n", $1, $2, $3;}
   }
}
```

Should I improve the script to use username aliases, i.e. combine values of "ChessDBCN" and "ChessDB_CN_WorkerPool" into one entry "noobpwnftw"?

### CODE REVIEW

**Comment by dubslow** [comment]
tbh the contirbutors page likely has some bugs, i wouldn't want to crystalize its bad data into git history

**Comment by peregrineshahin** [comment]
Please mind that the Top CPU Contributor is not accurate anymore with delta updates for some introduced bug, but probably is with a manual restart (I'm not sure.) better ask @ppigazzini if these values can be trusted as of now.

**Comment by vondele** [comment]
Note that there is already a script generating this list, and I run this from time to time. Please check commit history before making these PRs.

**Comment by maximmasiutin** [comment]
Yes, I see that the numbers decreased:

Was on 2022-11-19:

technologov                              14570711        760073590

Is on 2023-04-12:

technologov                              12511693        677314808


Maybe we should run a small Python code on the server to extract the data directly from the database?

**Comment by maximmasiutin** [comment]
> there is already a script generating this list, and I run this from time to time. Please check commit history

The commit history `git log "Top CPU Contributors.txt"` does not show or mention any script. It only shows updated data.

**Pull request closed without merging**
