### PR TITLE
Use acquire() and release() for spinlocks

### PR DESCRIPTION
**Pull request by mcostalba**
It is more idiomatick than lock() and unlock()

No functional change.

### CODE REVIEW

**Comment by zamar** [comment]
Let's commit this renaming after "noSleep" patch.

**Comment by mcostalba** [comment]
Ok, I will rebase on top of new master once you'll commit nosleep

**Comment by glinscott** [comment]
Cool, looks good.

**Comment by zamar** [comment]
Nosleep has been commited.

@mcostalba: Feel free to rebase and merge...

**Pull request merged**
