### PR TITLE
Eval tweak (Vizvezdenec)

### PR DESCRIPTION
**Pull request by unaiic**
STC https://tests.stockfishchess.org/tests/view/5fbc64c067cbf42301d6b1d6
LLR: 2.97 (-2.94,2.94) {-0.25,1.25}
Total: 53360 W: 5223 L: 5024 D: 43113
Ptnml(0-2): 184, 3877, 18390, 4014, 215

LTC https://tests.stockfishchess.org/tests/view/5fbc97f267cbf42301d6b1ee
LLR: 2.96 (-2.94,2.94) {0.25,1.25}
Total: 126472 W: 5111 L: 4766 D: 116595
Ptnml(0-2): 50, 4032, 54749, 4333, 72

bench: 3500558

Eval tweak from Vizvezdenec.

### CODE REVIEW

**Comment by unaiic** [comment]
https://github.com/Vizvezdenec/Stockfish/commit/e339915e7eb2dd26e105d16a085a3312ff8a4675#commitcomment-44536524

**Comment by unaiic** [comment]
@vondele I guess this one is failing Travis due to the recent commits... Bench mismatch seems to be the reason.

**Comment by vondele** [comment]
yes, that's likely. CI probably started after the merge to master. 
Can you rebase it, adjusting the bench?

**Comment by unaiic** [comment]
Sorry for the delay @vondele. I have no time right now so I created a new PR: #3240

**Pull request closed without merging**
