### PR TITLE
add bench info to perft info

### PR DESCRIPTION
**Pull request by FishChess**
Hi, I added 3 features that is already in bench info to perft info 

**_1- Total time (ms)_**
**_2- Nodes searched_**
**_3- Nodes/second_**

output perft example :

```
===========================
Total time (ms) : 552
Nodes searched  : 119060324
Nodes/second    : 215688992
```

### CODE REVIEW

**Comment by noobpwnftw** [comment]
Your patch diff looks horrible.

**Comment by MinetaS** [comment]
Why do we need these features?

**Comment by vondele** [comment]
Not needed indeed.

**Comment by FishChess** [comment]
> Not needed indeed.

@romstad recognize that this is a necessary commit to show **perft speed**, but you ignore it, I am surprised by @vondele 

What is the logical reason to ignore perft speed info?

_https://github.com/Disservin/chess-library_

_We all know that perft speed is the most necessary for an engine_

**Comment by Disservin** [comment]
Btw this functionality already exists. You just need to call bench with perft and it will show you the perft speed.

**Pull request closed without merging**
