### PR TITLE
Prune evasions when we can castle

### PR DESCRIPTION
**Pull request by lucasart**
**STC**
http://tests.stockfishchess.org/tests/view/551f2d360ebc590d17226842
http://tests.stockfishchess.org/tests/view/55230d9f0ebc590d172268cb

**LTC**
http://tests.stockfishchess.org/tests/view/5523b4f10ebc590d172268e4

bench 7911336

### CODE REVIEW

**Comment by Nazine** [comment]
Marco Costalba condemns this patch.

**Comment by mcostalba** [comment]
I would prefer STC and LTC results to be copied directly instead of a link
given because the link could become stale sometime in the future.

**Comment by zamar** [comment]
approved.

**Comment by glinscott** [comment]
Nice, looks good!

**Pull request closed without merging**
