### PR TITLE
Return below TB win score when Mate/TB win is unproven

### PR DESCRIPTION
**Pull request by windfishballad**
Currently SF catches if a mate score is not proven due to not being sure 50 moves rule in not breached when the mate is recovered from a TT hit. It does not do it for TB wins outputs which are similar to mate outputs (why have custom TB win output if 
not proven ?).

Besides just displaying terminal results only when proven, internally it is also non-natural for search to prefer unproven TB win over unproven mate.

- Update bound to 100-r50c for Mates since if 100th ply without reset delivers mate, it should count as win according to:
https://www.fide.com/FIDE/handbook/LawsOfChess.pdf paragraph 9.3 [this is consistent with Position::is_draw as well which returns false if st->rule50 >99 but position is checkmate].

- Return score lower than TB_WIN for unproven mate

- Add similar treatment for TB wins (TB win in <= 100 ply is good since a TB win line necessarily contains a reset - > 101 - r50c is because TB win in n plies is VALUE_MATE_IN_MAX_PLY-n-1 while mate in n plies in VALUE_MATE-n).

Will be testing STC non-regression bounds locally with TB7 (and no resign/draw adjudication) and update PR with result.

### CODE REVIEW

**Comment by peregrineshahin** [comment]
can confirm this does not show a TB score with no TB for the position in https://github.com/official-stockfish/Stockfish/issues/4413

**Comment by windfishballad** [comment]
@cj5716 Formatting fixed, ty !
@peregrineshahin See below; (TB_WIN_IN_MAX_PLY-1)/NormalizeToPawnValue=9185
info depth 85 seldepth 87 multipv 1 score cp 9185 nodes 28458432149 nps 204232951 hashfull 19 tbhits 0 time 139343 pv c1a2 h1h2 d1e2 h2g2 ...

**Comment by peregrineshahin** [comment]
unsurprisingly enough current master cannot reproduce the 20000 for the position below anymore
```
position fen 8/8/8/5N2/8/p7/8/2NK3k w - - 0 1
go infinite
```
still, the fix holds IMO.
so the current master shows cp 0 and the old master showed a GHI 20000, we need a new master that actually finds the win :)

**Comment by vondele** [comment]
> Will be testing STC non-regression bounds locally with TB7 (and no resign/draw adjudication) and update PR with result.

Did you have any results for that match ?

**Comment by windfishballad** [comment]
> > Will be testing STC non-regression bounds locally with TB7 (and no resign/draw adjudication) and update PR with result.
> 
> 
> 
> Did you have any results for that match ? 

Will run it soon and post - I lent my big machine to Stoofvlees for WCCC, as soon as it's over.

**Pull request closed without merging**
