### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by bknox83**
Adding some svg icons and relevant additional information to the readme. These are very easily customizable with additional information, colors, badge types, and icons if any accessibility concerns come up. Built using https://shields.io/

A note on the Discord badge currently showing "widget disabled" - a Discord server admin will need to enable the widget setting (if that's something we want to do) so that it shows the number of users online. `Server Settings -> Widget -> Enable Server Widget`

I also noticed that our Discord invite links in the readme are from a "deleted user" - probably not a big deal so no updates there, but maybe something we can change in the future. Also applies to our invite link on https://stockfishchess.org/get-involved/

### CODE REVIEW

**Comment by vondele** [comment]
`Server Settings -> Widget -> Enable Server Widget` should be enabled now.

**Comment by Disservin** [comment]
https://discord.gg/GWDRS3kU6R

this is a link from me now, the server owner. Let me know if something is wrong with it, I am currently traveling and have little time to look, also thanks @vondele for enabling the widgets.

**Comment by bknox83** [comment]
Updated the Discord invite links in the readme and it appears that the users are now showing up from the widget!

**Comment by snicolet** [comment]
The Readme.md file is completely unreadable now...

Would it be possible to experiment with the Markdown syntax for reference links?
https://www.markdownguide.org/basic-syntax/#reference-style-links

**Comment by dav1312** [comment]
> The Readme.md file is completely unreadable now...
> 
> Would it be possible to experiment with the Markdown syntax for reference links? [markdownguide.org/basic-syntax/#reference-style-links](https://www.markdownguide.org/basic-syntax/#reference-style-links)

I told him that on [Discord](https://discord.com/channels/435943710472011776/1021674792484614175/1021687731803406389) but he ended up not using it idk why

**Comment by bknox83** [comment]
I’ll take a look at that link and get an update out there.

**Comment by bknox83** [comment]
Thanks all for the suggestions! I feel like there are several formatting updates that I'd like to make the RT page now as well after learning about this format! 😄

**Comment by snicolet** [comment]
Excellent, thanks! 
I would even go as far as putting the URL references at the bottom of the document (if that works, haven't tested)

**Comment by bknox83** [comment]
Any complaints if I update all links in the readme to this format and add them to the bottom or just keep it contained to the new badge information?

**Comment by vondele** [comment]
> Any complaints if I update all links in the readme to this format and add them to the bottom or just keep it contained to the new badge information?

having it consistent is definitely good.

**Comment by TheBlackPlague** [comment]
> Any complaints if I update all links in the readme to this format and add them to the bottom or just keep it contained to the new badge information?

Maybe have it be center aligned?

**Pull request closed without merging**
