### PR TITLE
Rewrite bishop diagonal and pawnless flank

### PR DESCRIPTION
**Pull request by Rocky640**
2 unrelated changes tested [3, 1]
a) I first establish the bench if we remove lazyeval or use the pawnstorm score in kingdanger (see SBD_1)
b) I show that replacing the | s by a psqt change, 
    and moving the pawnless flank logic to pawns.cpp (where it belongs IMHO)
    would give exactly the same bench (see SBD_2)
c) I revert the changes made in a) (see SBD_3)

Passed STC
http://tests.stockfishchess.org/tests/view/5a244be80ebc590ccbb8b726
LLR: 2.94 (-2.94,2.94) [-3.00,1.00]
Total: 10879 W: 1981 L: 1844 D: 7054

Passed LTC
http://tests.stockfishchess.org/tests/view/5a245f050ebc590ccbb8b72e
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 174900 W: 22210 L: 22287 D: 130403

### CODE REVIEW

**Comment by lucasart** [comment]
Your patch:
1/ bunches unrelated changes
2/ contains a non simplification (which you don't mention in your patch comment)
3/ tries to hide 2/ by drowning the diff in gratuitous code refactoring

**Comment by Rocky640** [comment]
The 2 changes looked harmless to me, so I was trying to save resources.

The |s change would not change the bench if it was not from the lazyeval.
Nothing to worry at all here.

The second one of them is a (not so gratuitous) refactoring: I think that moving the PawnLessFlank code to pawns.cpp is a good thing for further improvements.  This bonus is some sort of hybrid of "no shelter" which is a middlegame bonus, and have also some relation with the minkingpawndistance which is only endgame. 
Some better formula will eventually suggests itself.
Furthermore, by moving this to pawns.cpp, it is computed only when a pawn or a king move, instead of being computed on (almost) each call to evaluate.cpp.

When this bonus was introduced, it was not clear if only king and pawns would be involved, but after many months, it is clear that it will remain more or less in the current form, and therefore belongs to pawns.cpp

**Comment by MichaelB7** [comment]
The patch is obfuscated, looks you have two or three patches to test separately.  Combining unrelated in changes in one patch is not best practice, as one change can mask the detriment of an unrelated change.   I do appreciate the effort.

**Comment by mcostalba** [comment]
@Rocky640 this is really to complex to be a simplification, in particular this does not address a single item (as is requested by a simplification).

As already stated many times, we can't add unrelated stuff on the shoulders of a (simplification) path. We should test unrelated stuff in an independent and disjoint way.

Could you please reformat your work in a series of **small** unrelated patch and test them (eventually, if it makes sense)?

**Pull request closed without merging**
