### PR TITLE
Limit the king distance factor when evaluating passed pawns

### PR DESCRIPTION
**Pull request by Rocky640**
Limit the king distance factor when evaluating passed pawns
Passed STC
http://tests.stockfishchess.org/tests/view/5a6bf7290ebc590d945d5a3a
LLR: 3.31 (-2.94,2.94) [0.00,5.00]
Total: 23987 W: 5550 L: 5281 D: 13156

and LTC
http://tests.stockfishchess.org/tests/view/5a6c57710ebc590297c36af2
LLR: 2.97 (-2.94,2.94) [0.00,5.00]
Total: 16926 W: 3014 L: 2820 D: 11092

bench: 5059457

### CODE REVIEW

**Comment by ElbertoOne** [comment]
Awesome! Nice work.

**Comment by Rocky640** [comment]
The AppVeyor build failed. Anyone has an idea on why ? In position.h, it does not like std::min even after I added  #include <algorithm>

**Comment by locutus2** [comment]
@Rocky640 
I think that helps you:
https://stackoverflow.com/questions/5004858/stdmin-gives-error

**Comment by joergoster** [comment]
@Rocky640 Why not cap the distance in evaluation part?

**Comment by Rocky640** [comment]
@locutus2: thanks, it is more informative than the first article I googled. So we have a windows.h somewhere that have this peculiar "hidden" side effect in position.h. However we do not have this problem with std::min or std::max in positions.cpp or evaluate.cpp

@joergoster: agree, it is closer to where it is used, and it will allow some more refined experiment involving "real" distance. It should also fix my AppVeyor problem, see note below.

**Comment by locutus2** [comment]
@Rocky640 
The problem was in compiling misc.cpp. This is the only file which includes windows.h. But its includes also thread.h which include position.h. So we have windows.h and the use of std::min in the same compilation unit and the error occurs.

**Pull request merged**
