### PR TITLE
Optimise NNUE Accumulator updates

### PR DESCRIPTION
**Pull request by cj5716**
Passed STC:
LLR: 2.94 (-2.94,2.94) <0.00,2.00>
Total: 86176 W: 22284 L: 21905 D: 41987
Ptnml(0-2): 254, 9572, 23051, 9963, 248
https://tests.stockfishchess.org/tests/view/662e3c6a5e9274400985a741

closes #5202

No functional change

### CODE REVIEW

**Comment by mstembera** [comment]
Congrats!

**Comment by mstembera** [comment]
Does the ```assert([&]()``` run even in release builds which is not what we want ?

**Comment by Disservin** [comment]
> Does the `assert([&]()` run even in release builds which is not what we want ?

i'm not quite sure what you are asking? any assert is not run in release build and is not included in the binary? 
This lambda runs in the assertion because at the theres a function call `()`

**Comment by mstembera** [comment]
I was thinking the lambda assert overrides the normal default assert and maybe does not compile out in release builds like a normal assert does?

**Comment by ddobbelaere** [comment]
There is no such thing as a 'lambda assert'. The called lambda function is passed as an argument to `assert`, which is in fact a macro that does nothing if `NDEBUG` is defined. See https://en.cppreference.com/w/cpp/error/assert

**Comment by mstembera** [comment]
Ah my apologies I obviously can't read.  Ty.

**Pull request closed without merging**
