### PR TITLE
Prevent potential out of bound access on QMI array.

### PR DESCRIPTION
**Pull request by gonlem**
Prevent potential out of bound access on QueenMinorsImbalance array with hypothetical FEN positions including more than 12 minor pieces. 

No measurable slowdown. No functional change.

### CODE REVIEW

**Comment by AndyGrant** [comment]
12+ minors is an illegal FEN position...
I see no need to make this change

**Comment by gonlem** [comment]
You are right ! One side cannot have more than 12 minors (4 starting minors + 8 promotions). I was counting both side minors but the QMI array is only indexed by one side minors count...
In short, I need more sleep...

**Comment by lucasart** [comment]
a better patch would be to change the upper bound of the array. no need to introduce a branch slowing down the program with `std::min()`.

**Comment by lucasart** [comment]
@gonlem: it's 2 minors plus 8 promotions, not 4 minors. it's only for 1 side. so the current upper bound is correct, and this PR should be closed, because it's useless.

**Comment by gonlem** [comment]
@lucasart : Each side starts the game with 4 minors (2 knights and 2 bishops) but the current bound already covers that. Beside, std::min() does not introduce any measurable slowdown, it is only calculated when the rare case of this imbalance.

I'm perfectly fine to close this PR (it was based on the erroneous assumption that the QMI array was indexed by both sides minors count)

**Comment by gonlem** [comment]
@lucasart : I'll add that I understand your point about the theorical slowdown of std::min(). Thank you for the advice. 

What's also bothering me with the current code is the fact that the QMI array values are undefined beyond index 4. The current implementation looks a little odd in this aspect.

**Comment by AndyGrant** [comment]
Those values are guaranteed to be 0.

**Comment by mcostalba** [comment]
Thanks for the patch, but as already pointed out, the patch does not adds any real value. So I will close it.

**Pull request closed without merging**
