### PR TITLE
Improve dbg_mean_of()

### PR DESCRIPTION
**Pull request by mcostalba**
Add variance and improve formatting.

Thanks to people in this thread:
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/ILD4fw6eoLI

No functional change.

### CODE REVIEW

**Comment by Stefano80** [comment]
Very nice. Something interesting: I measured the precision benchmarking against the stats of our random number generator (I initialized the seed at 0 and I add 1 at each search call) and I got after 85M samples

Total 84557983  Mean -0.515  (must be -0.500) and Variance 1398094.968 (must be 1398101.25)

The imprecision in the mean estimation is huge! Does it depend on the dbg_mean_of or on the random number generator?

By the way, I would like to merge a small extension a further improvement, as soon as I am finished. Can you give some hours before merging?

**Comment by mcostalba** [comment]
Of course but please this little function is not a stats library :-)

Let's keep it small and simple...

**Comment by Stefano80** [comment]
Hi @mcostalba , I don't know whether this is right way to do, it but I opened a PR on your fork for proposing some changes, see https://github.com/mcostalba/Stockfish/pull/281.

**Comment by vdbergh** [comment]
@Stefano80 This is a really nice idea with many potential applications! Some suggestions: instead of printing the variance it is perhaps better to print the standard deviation (since it has the same units as the mean) and instead of the covariance it is perhaps better to print the correlation coefficient (as it is dimensionless).

**Comment by mstembera** [comment]
I would also prefer standard deviation over variance as more natural to interpret.  Same for correlation over covariance as it's nicely bound from -1 to +1 and independent of scale and bias.

**Comment by lucasart** [comment]
I don't understand the practical use case for variance. Typically, you use these functions for counting occurrences of a certain condition, or for estimating the average of an eval term. I have never used it to calculate a variance. I look at the discussion, and there is no mention of an actual **use case**. Just calculating variance for the sake of it: https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/ILD4fw6eoLI

Sure, there may be rare cases, where you need a variance. But when that happens, you can easily modify the code to do it: average squares minus squared average, this is trivial to code, and everyone knows how to do that.

I don't think it's justified to add such debug code in the master branch, without a **general** use case for it. The problem is that you open a can of worms with that: you give them variance, and now they ask for standard deviation, correlation, what next ?

**Comment by mcostalba** [comment]
@lucasart Yes, I agree. This is quickly getting out of hands.

In case we have real use cases we can grow this debug function, and for real use cases I mean something you ***already*** used, not something that could be used in the future.

Personally I have sometime used dbg_mean_of() but never for variance or siblings so, to be consistent with the above I am going to close my own PR because does not represent a usage case I have experienced.

I am ready to reconsider if people present real examples of SF testing where variance and friends were actually needed.

**Comment by Stefano80** [comment]
Hi @mcostalba ,

actually I do it all the time: write down values to files, export to python make statistics. I think the use case in which I would have really make good use of this feature was the removal of MVV/LVA and replacement by MVV+rank.

I had already removed LVA and wanted to find out how to replace it. In capture scoring I wrote down pos.see(m) and a bunch of other variables to a file (relative rank, relative file, aggressor value and so on....). Then I imported them to python and made some stats to check the variables which had the most correlation with pos.see(m) (back then with bench, since cutechess did not support cerr redirection to a file) and discovered that relative rank was one of the best. So I came up with the idea of using relative rank.

See http://tests.stockfishchess.org/tests/view/55424d1c0ebc5938ea1962b4

I think this a real good case for covariances (I am neutral about covariances or correlations, although I think covariances are easier to mantain), for the variance of a single variable I have some doubts.

Btw, exactly in the same way, I discovered that we could replace all scale factor templates by a simple formula and only lose 20 Elo (http://tests.stockfishchess.org/tests/view/5571f7c20ebc5940ca5d7039).

@vdbergh : thanks for the appreciation, but maybe we could keep calm... :-)

**Comment by lucasart** [comment]
@Stefano80: The use case you describe has nothing to do with variance. What you were trying to do is, if I generalize it, a parametric estimation `y = f(x1,…,xn)`. For advanced, and specific, statistics such as this, it is the *correct* way to dump into a file and use a python script (or a statistical language like R, or a spreadsheet, or whatever you like to use).

**Comment by Stefano80** [comment]
@lucasart : not with variance, but with covariances, which the version for which I opened a PR on Marco's fork.

**Comment by mcostalba** [comment]
@Stefano80 Thanks for reporting a real example. Indeed I see that you can hardly replace the dumping to file of a bunch of variables and off-line stats computation with a simple dbg_mean_of() perhaps a little bit grown up.

**Comment by lucasart** [comment]
@Stefano80: To estimate `y = ax + b`, you need covariance, and variance , and mean. And the one variable regression is only a particular case, where you can do it like that. To do a multilinear regression, you need some more complex matrix calculations. Besides, there are more things to a regression than estimating parameters: confidence intervals, goodness of fit, come to mind. Really it's best to do this in a GNUmeric spreadsheet, a statistical software, or a python script, not in `C++`.

**Comment by Stefano80** [comment]
Hi @mcostalba : if I say you that it would have helped me, why you dont believe me? I just had to compute all covariances and pick the highest. 
Actually, with a bit more than I have committed, I would have done the whole job in one pass: if I would have had the full covariance matrix of N variables instead of the covariance of only  two variables, I would have solved the problem in one pass. But I am strongly confident that your unchallenged C++ skills could solve also this problem in the same number of lines than my covariance patch proposal. :-)
The problem with dumping variables in a file instead of online computing the covariance matrix is that the file becomes very soon very large and you have to somehow manage it. This actually excludes to use this workflow in tournament conditions using cutechess (unless you start tweaking with random sampling and so on).
I repeat: having the full covariance matrix for ten or so variables would have solved the problem in one pass. This does not mean that you have to commit anything, but please believe me since I report what I have done.

@lucasart : I know it all too, thank you very much. I was reporting one single case in which this specific patch would have done the job, as Marco asked.

**Comment by mcostalba** [comment]
@Stefano80 I agree it makes more sense to eventually figure out a complete solution than add in a half tought crippled one.

So let's leave dbg_mean_of() as is and try to figure out a new function called dbg_stats_of() with N variables as input.

Can you please write a possible implementation of that function, say with 5 variables, It should be compatc and slim, otherwise if it is too complex it is better to simply dump all and do a post-processing analysys with proper tools.

Once you have written your toy implementation that helps me to fugure out the formulas involved, I will try to rewrite it in a more general terms...

**Comment by Stefano80** [comment]
Thanks Marco, I'll do the next days.
Il 28/ago/2016 01:52 PM, "Marco Costalba" <notifications@github.com> ha
scritto:

**Comment by mcostalba** [comment]
@Stefano80 ok, I have created a possible skeleton here:

https://github.com/official-stockfish/Stockfish/pull/774

**Pull request closed without merging**
