### PR TITLE
Remove followupmoves.

### PR DESCRIPTION
**Pull request by mbootsector**
STC: http://tests.stockfishchess.org/tests/view/5501d0f30ebc5902160ec0fd
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 34891 W: 6904 L: 6808 D: 21179

LTC: http://tests.stockfishchess.org/tests/view/550328540ebc5902160ec133
LLR: 3.10 (-2.94,2.94) [-3.00,1.00]
Total: 182653 W: 29866 L: 29993 D: 122794

### CODE REVIEW

**Comment by glinscott** [comment]
With the new countermoves, FollowupMoves have a fair bit of overlap.  I think simplification bounds are a good fit here.  Approved!

**Comment by zamar** [comment]
approved.

**Comment by mbootsector** [comment]
This test http://tests.stockfishchess.org/tests/view/5511028a0ebc5902160ec40b is almost the same, and probably better... Less work for if you merge that instead.

**Comment by zamar** [comment]
Test  http://tests.stockfishchess.org/tests/view/5511028a0ebc5902160ec40b failed.

We will merge this during the next weekend or so...

**Comment by mstembera** [comment]
Just FYI
http://tests.stockfishchess.org/tests/view/5511028a0ebc5902160ec40b
should have probably been [-3,1] not [0,6] but it finished yellow anyway.

**Pull request closed without merging**
