### PR TITLE
Make reductions double valued

### PR DESCRIPTION
**Pull request by Stefano80**
Move to double-valued reductions array with some related changes:
- simplify init by removing rounding and offsets
- retire offset in history contribution
- slightly reduce reductions change for cut nodes ans moves escaping a capture

The main advantage is a smoother behaviour of reductions.

STC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 35598 W: 6649 L: 6553 D: 22396

LTC:
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 9253 W: 1303 L: 1167 D: 6783

### CODE REVIEW

**Comment by nabildanial** [comment]
Congrats! Big ELO gain on LTC, on top of that, nice scaling!

**Comment by Stefano80** [comment]
Some additional remarks:
- this patch conflicts with https://github.com/official-stockfish/Stockfish/pull/755, it must be decided how to proceed.
- several versions of double-valued reductions were tested as SPRT [0.00 5.00], trying to find the correct parameter. They were more or less non functional (in the sense that the logic was exactly the same). Some of them came very close to pass (thus supporting the idea that the smoother behaviour is worth something). One could argue that it has been overtested.
- one could try the same type of simplification without going to doubles. It would look not so nice, but it could be tried.
- double-valued reductions open an ocean of new possibilities (very fine tuning, use of see information, fine dependency on improving to name just a few), and I think this is what makes the patch really worth to be committed.

**Comment by MichaelB7** [comment]
Impressive - will fold it tonight ( personal fork). Passed in under 10,000 games at LTC - virtually unheard of.    Well deserved acclaims.

**Comment by Stefano80** [comment]
Thanks, but check for instance http://tests.stockfishchess.org/tests/view/578658710ebc5972faa168da
(and that was [0.00 5.00]!!!)

**Comment by VoyagerOne** [comment]
Very nice work.  
I am happy to see that we can get rid of that numerator "correction factor".

IMO, these type of LMR patches is what make SF scale so well.

**Comment by VoyagerOne** [comment]
Trying to derive ELO from sprt can be very misleading.

It is not uncommon for patches to pass [0, 5] in less than 10k, with no ELO gain, or even a regression.

I had several patches that got to 2.85 in < 5,000 games (just a few more wins to pass) only to plummet and fail 10k games later.

**Comment by MichaelB7** [comment]
That's true - seen that too.  But still very promising.

**Comment by mcostalba** [comment]
@Stefano80 This is definitely not SPRT[-3, 1] material.

The only place where double is used is to replace 2 * ONE_PLY with 1.90, remaining stuff has nothing to do with using double.

So I'd suggest to test the reduction tweaks alone (without introducing useless double) and eventually to test the use of float (not double) alone.

All the tests should be SPRT[0, 5]

Perhaps there is a value in this patch but clearly it is not commitable as is, nor I guess is intended to be committed considering that is written in a very sketchy and not polished way.

**Comment by Stefano80** [comment]
Hi @mcostalba ,

you missed the main point.

Currently in master: you round in reductions initialization and add this number with the history contributions, which is floored. Since the two numbers are quite small, you make very large errors. These errors are reduced by adding the number as doubles and rounding at the end.

This alone almost passed SPRT [0.00 5.00]

https://github.com/Stefano80/Stockfish/compare/f2f3a06...c9859a5

By the way, I think it is just much more natural to keep everything as a float or double, and rounding and maximizing with zero in the very end, than doing it in the intermediate steps. If you want to reconsider your decision in view of this: good. If you really want, I could test the reductions init simplification alone without doubles with SPRT [-3.00 1.00]. I will not retest anything with [0.00 5.00]

Please give it a second thought, since I really think that you missed what the patch is about.

**Comment by mcostalba** [comment]
@Stefano80 I am sorry but using float instead of integer is not a simplification in any way. The fact that you spare a line of code in init (but you add the rounding later on during search) does not qualify for a simplification in any reasonable way apart from dumbly and blindly counting lines (withouth considering the content).

Moreover now master is changed and test would need to be redone anyhow. If what bothers you is this line:

```
int rHist = (val - 10000) / 20000;
r = std::max(DEPTH_ZERO, r - rHist * ONE_PLY);
```

You can easily rewrite to avoid the rounding error:

```
r = std::max(DEPTH_ZERO, (r * 65536 - (val - 10000) * 3 * ONE_PLY) / 65536);
```

In case you (or someone else) wants to test the above, this is a SPRT[0, 4]

**Comment by mcostalba** [comment]
@Stefano80 Another solution that is much better and also in line with current logic would be to rise ONE_PLY value to something much bigger like 256, so that when mixing plies and another quantity you can operate on higher precision.

This solution requires a careful audit of ONE_PLY to be sure we do not introduce bugs. So a preliminary test would be to just change ONE_PLY value and confirm bench does not change.

**Comment by Stefano80** [comment]
Hi @mcostalba ,

setting ONE_PLY also only to 2 changes the bench from 6554900 to 148381. It would cost some amount of work to get it right, so even if I like the solution, I will not do it. (As an explanation: I dont enjoy low-level programming, it's really not my strength as you will have noticed. But I understand of trees and algorithms). (And btw this shows that current logic, or its implementation, is at least suboptimal if not buggy).

I don't want to discuss this topic further. I will mantain the doubleValuedReductions branch and if you eventually feel like harvesting this ELO mine, be welcome to encourage me to open a new PR.

**Comment by mcostalba** [comment]
@Stefano80 yes, make ONE_PLY independent it will take some time: I have pushed a [branch ](https://github.com/mcostalba/Stockfish/commit/b2b71752b6f37fcdf9e92b4e1) that just starts to do the conversion, but more work is needed.

Regarding harvesting your ELO: there is no proved ELO gain in a SPRT[-3, 1]

**Comment by mcostalba** [comment]
Now the [branch](https://github.com/mcostalba/Stockfish/commit/oneply) is finished and SF is ONE_PLY independent for values 1, 2, 4, 8 above that there is still some change to be investigated (I think is some rounding error).

I will run a test to verify there is no regression and then I will open a PR because I think this work is important and gives consistency to the code. I think is also the base above which to rewrite the heterogeneous formulas involving depth.

Diving in the low level detail of the code I found many interesting things and I realized SF starts to suffer from continues add-on tweaks more or less bolted on existing code. It time for some deep consistency improvement to allow future work to be based on solid grounds.

**Comment by Stefano80** [comment]
Thanks Marco, I will study your work and see how to take advantage from the new infrastructure.

**Comment by tomtor** [comment]
See: https://github.com/mcostalba/Stockfish/pull/278

which did test OK for me with ONE_PLY = 16

**Comment by Stefano80** [comment]
Btw Marco, I think the title of the PR is misleading. This is all about having the possibility of using non integer depths, and this will immediately break ONE_PLY independency.

**Comment by mcostalba** [comment]
No I don't think so, at least thi sis not what I intended and indeed I have
added this line:

assert(depth / ONE_PLY * ONE_PLY == depth);

Exactly to guard against that case.

The reason of the PR is mainly to give consistency to Depth usage in the
code. I think this will be beneficial in multiple ways, some of them still
unkown :-)

**Comment by AlexandreMasta** [comment]
Will this not be merged? Seems like a big improvement at longer TCs.

**Comment by Stefano80** [comment]
Hi Alexandre, Marco is not convinced of the mantainability of the double valued reductions array, if I understand it correctly.

He is trying an alternative solution more of its taste, but his tests were not successful yet. Here are the tests:

http://tests.stockfishchess.org/tests/view/57b8c6b90ebc59030fbe460e
http://tests.stockfishchess.org/tests/view/57b949830ebc59030fbe4643
http://tests.stockfishchess.org/tests/view/57b949890ebc59030fbe4645
http://tests.stockfishchess.org/tests/view/57b8cb370ebc59030fbe461b

**Comment by mcostalba** [comment]
@AlexandreMasta this patch series is tested with SPRT[-3, 1] so it is not proved to be any improvement at all.

@Stefano80 My patch series has nothing to do with your patch because you aim at reducing rounding errors in heterogeneous formulas, what I have not tried to do.

**Comment by AlexandreMasta** [comment]
@mcostalba @Stefano80 as we know the patch is TC sensitive, why not just test it at LTC with SPRT [0.00 5.00] ? This patch is adding nice elo in my tests.

**Comment by Stefano80** [comment]
@AlexandreMasta : we have to learn the art of recognizing lost battles. Patch removed code and passed quickly LTC, but Marco has its good reasons not to merge it. I don't agree, but I don't think that arguing will help. Let us see how this ONE_PLY stuff can help us.

**Comment by AlexandreMasta** [comment]
@Stefano80 Ok. Trust Marco. He knows what he is doing, if he saw something wrong and wants to improve this is totally fine.

**Pull request closed without merging**
