### PR TITLE
Almost passed tuning attempts.

### PR DESCRIPTION
**Pull request by Stefano80**
Collect and give a second try to some almost passed tuning attempts and one-line tweaks from the last month.

Passed STC

LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 8800 W: 1814 L: 1646 D: 5340

and LTC

LLR: 3.01 (-2.94,2.94) [0.00,5.00]
Total: 13886 W: 2239 L: 2063 D: 9584

To make it clear: it was tested as an improvement and not as a tuning patch.

### CODE REVIEW

**Comment by Stefano80** [comment]
@burak13: the point is that there is almost no new logic in the patch. So, I think it is fine to test some more ideas together. They probably were 0.5 - 1 ELO worth taken alone, so they had less than 50% to pass. But if you take 6 of them as I did, than you end up with +5 ELO and can pass.

**Comment by AlexandreMasta** [comment]
@Stefano80 I will try to be objective here. That´s why I will not expose many ideas that for me are obvious and my english makes it a pain for me. But let´s begin:
Sure your thought proccess is flawed. With your "logic" seems that we can put any failed patch in (nice lol). Although you are trying to support your claim with "mathematical assumptions", because they are considering "probabilities" alone, and without context. So...every patch has a probability. That´s what you are considering alone. So you consider same thing losing with red or yellow. A loss is a loss simple as that right?
But the problem is that we have a context. We can see when something is hard to be beaten even if the result in the end is same NUMERICALLY. We can see this in every competitive sport just as an example. We can say that Jose Aldo is a great fighter even if he loses against McGregor as another no-name. And we are humans that can think out of the box and fixed models. Because we can make more LINKS of information and even if many times we can´t explain using a "tool" of a language as physics or mathematics to explain ourselves in an universal scientific language, we can have a vision of the truth. It is clear that we can understand that tempo patch is much weaker at LTC. The probability of this patch being good at longer time controls are sooo small that I bet for a fixed number of games trying to remove only it at LTC. I will "probably" win (and you may know this).

With low depth the tempo increased shows better performance, some patches act like this. Because low depth = low evaluation. But with deeper plies the evaluation is more accurated and it shows to be bad.

That´s the problem here. BTW One cannot remove it now with normal SPRT test because the removal patch will surelly fail at STC!!!! Obvious...as the patch with tempo 20 PASSED relatively fast at this TC. So you were trying to be smart there. "I see what you did". PLs don´t repeat "If you think tempo should be 17 go and measure whether decreasing this is a ELO gain." Not with the normal test. But that would be fine because a mix of failed tests are not normal too.

Otherwise let´s try to make a simple experiment...lets now make a simple fixed game test only with tempo 17 and 20 at LTC. Lets say...fixed 20000 or 40000 games, giving nice confidence, just testing this change alone at LTC. If 20 tempo wins you are right. A deal? I will not test it myself, cause I don´t have a repo. Remember that I didn´t even expose all my ideas about the subject.

**Comment by AlexandreMasta** [comment]
BTW that´s what made you choose yellow patches...CONTEXT.

**Comment by lucasart** [comment]
See here:
http://tests.stockfishchess.org/tests/view/56218b7d0ebc590be39e1aa7

**Comment by AlexandreMasta** [comment]
@lucasart Lucas...you just need to exclude the tempo stuff and your patch will pass.

**Comment by Stefano80** [comment]
@lucasart : 
1) watch your language. I just collected work from other people, which you are calling a mess. (Btw a +5 ELO mess).
2) your argument that fixed time per move tc is now broken is actually completely invalid. Because the problem is that we use time management in the first place in the case of fixed time per move, where we actually do not have anything to manage apart of sending stop signal at appropriate time.
3) So let us follow your method for tuning patches with 20 parameters. Let us *always* search which one of the 20 pars gave the ELO gain. Maybe with SPRT 0,1...
@AlexandreMasta : I do not understand you. Fork and test the tempo = 17, 100000 games at 40+0.4. You will probably find out that it is neutral. I dont have the time to do it, but I think mantainers would be ok with this.

**Comment by lucasart** [comment]
@Stefano80: SPRT(0,1) is out of question. As an exercise, I let you calculate the expected stopping time of this test, for different values of the elo parameter...

**Comment by lucasart** [comment]
@Stefano80: This patch is not a contribution. You are just giving homework to SF maintainers. Throwing random combinations at fishtest is easy. Now, we need to bissect this mess of a patch, in order to understand what is useful in it, and separate it from the cruft, and the harmful stuff. This is exactly what I am doing now: a dichotomic search to break down the patch into a smaller part that retains the elo gain.

**Comment by AlexandreMasta** [comment]
@Stefano80 At least others parameters were found through SPSA tuning...and the tempo stuff (20) was found with what???

**Comment by Stefano80** [comment]
@AlexandreMasta : I tried to make tempo dependent on game phase and it turned out that for middlegame a much higher value would be good

http://tests.stockfishchess.org/tests/view/54d767960ebc5913ea64042b

@lucasart : your bissection attempts have until now already wasted more resources than my patch. 

@zamar @glinscott : I suggest we do the following
1) we merge this patch
2) we fix SF such that time management is not used when in fixed time per move mode
3) we test tempo = 17 at 40+0.4 SPRT [0, 4]

**Comment by mcostalba** [comment]
@stefano80 could you please point out which are the original tests you are
referring to with your patch.. Perhaps I have missed something but I would
like first to be sure.  Thanks.

**Comment by lucasart** [comment]
Unfortunately, bisecting is not guaranteed to work, due to the grey nature of testing:
* say we have a combo patch P of N patches that passes.
* we split P = P1 + P2, where P1 and P2 have N/2 patches.
* If we are lucky, exactly one of (P1, P2) will pass, and we've halved the problem to a combo of N/2 patches.
* If we are a bit unlucky, P1 and P2 will pass. We have 2 patches of N/2 to bissect.
* If we are very unlucky, P1 and P2 will fail. Now the question is: ok, there's probably an elo gain in P, but there are `2^N - N - 3` possible subsets of P remaining to test...

Stefano is proposing to swallow the pile whole, without asking questions: there may be useless or harmful stuff in it, but as long as the total is positive let's commit and not ask questions... We have never worked like that in the past, as far as I can remember.

**Comment by mcostalba** [comment]
I have asked him to list the original tests

**Comment by Stefano80** [comment]
@mcostalba : here you go. All patches apart of the first two are tuning patches.

Max half time
http://tests.stockfishchess.org/tests/view/5619864d0ebc597e4f23e7bc

King support qcc
https://github.com/snicolet/Stockfish/compare/55b46ff...1101796

Tune imbalance
http://tests.stockfishchess.org/tests/view/5618b71d0ebc597e4f23e76f

Tempo
http://tests.stockfishchess.org/tests/view/56133d800ebc597e4f23e5bc

Tune search
http://tests.stockfishchess.org/tests/view/5602942c0ebc5976a2d6dffe

Delta increment
http://tests.stockfishchess.org/tests/view/5603dc5a0ebc597e4f23e1d3

Mobility 3
https://github.com/joergoster/Stockfish/compare/68fbb1e...86c33a5

Razoring
https://github.com/absimaldata/Stockfish/compare/d926b89...bbee590

**Comment by Stefano80** [comment]
@lucasart : you may ask questions, of course. But most of patches are tuning patches, and you never ask questions about them.  The patch is a tuning patch with 2 lines of code added for max half time and king support qcc and some changes for the razoring tuning. Just ask as many questions as you wish. But please be polite to me, as I am to you.

**Comment by mcostalba** [comment]
Ok, in this case patch is not valid according to our guideline.

Indeed combo patches can be done with at maximum 2 original patches.

This rule is to avoid mixing good and bad stuff an relying that on average
bad staff is masked out.

**Comment by mcostalba** [comment]
This is a relevant link (called unin patch)

https://github.com/glinscott/fishtest/wiki/Fishtest-faq

Indeed I will move this text to
https://github.com/glinscott/fishtest/wiki/Creating-my-first-test

**Comment by Stefano80** [comment]
@mcostalba : I know the guideline, very well. This is a TUNING patch + max half time. And it's worth something like 5 ELO for 2 lines of code.

**Comment by mcostalba** [comment]
@Stefano80 sorry, but I don't understand. I count 8 patches in your post,
not 2

**Comment by mcostalba** [comment]
Perhaps I miss something but our guideline says:

Among parameter tweaks a special sub-case is the so called "union patch" or
"combo patch", that is a bundling of patches that failed SPRT but with
positive or near positive score. Sometime retesting the union as a whole
passes SPRT. Due to the nature of the approach and because of each
individual patch failed already, a union has some constraints:

   - Maximum 2 patches per union
   - Each patch shall be trivial, like a parameter tweak. Patches that
   add/remove a concept/idea/feature shall pass individually.


So here the question is very simple. Does this union patch complies with
the above guideline?

**Comment by AlexandreMasta** [comment]
The fact is clear. The tuning patches was not strong enough to pass alone. Now they are together and are really giving that extra stuff to be able to pass. This is understandable, as the most of them didn´t pass by little (many yellow at LTC with great struggle). 

The only real problem I see is the tempo as it was implemented, because it failed hard at LTC. This tempo patch is only helping the other stuff to pass STC and with framework parameters of testing, that is what it is doing. That little push to pass STC. Then it is bad for LTC...but other stuff carries it on in this stage.

**Comment by Stefano80** [comment]
@mcostalba : 6 of this 8 patches are just tuning patches: numbers have been changed but nothing else. If people would have run a HUGE spsa session instead of many small ones, this is exactly what you would have obtained. 1 of them (king support qcc) is also a very minor tweak. There is one new idea, which is max_half_time (if you want to call a new idea). So in fact, when I think of it, this does not comply completely, because you have indeed a new idea which has been added in addition to some parameter tuning. Everything boils down to whether you cal max_half_time a new idea or a parameter tuning. Please consider that https://github.com/official-stockfish/Stockfish/commit/8fd34d7763072fc3ec7216729c1f7b7354bfa470 was commited although the gain was much smaller, and code changes were way more invasive.

@AlexandreMasta : I think, you are really overestimating tempo. This has probably almost no effect on LTC.

From my side, all arguments are on the table: @zamar @glinscott make a decision, I will not discuss it anymore.

**Comment by AlexandreMasta** [comment]
@Stefano80  Well, I congratz you to have this successfull patch. It is possible to have this kind of stuff happening. We have many tuning things that don´t have the strenght to pass alone but are indeed little improvements. I think that SF team has to be aware of it. Since you don´t add code and are using tune sessions and preview tests right, I really think that the stuff is totally valid. You are adding elo to the engine with this patch, this IS a FACT. 

Repeating myself just to make my point clear is that the only real problem is that tempo stuff was used merely to make all thing pass faster at STC.

The rest is undeniable, we have an elo gain patch here and should not be discarded totally.

**Comment by mcostalba** [comment]
@Stefano80 well, for starter the time management patch should be really
removed from the set and tested alone. Mixing time management and parameter
tweaks is really a no-no, independently from union patch rules.

Second, if we have a rule may be we want to stick with it, not changing
upon our convenience.

Third these are _already_ tested (and failed) patches, so that's why in
combo we want at max 2 of them. The correct approach should be to test 2 of
them in a single bunch, for various combination of patches, so to pick only
the good ones and leave the others off.

**Comment by mcostalba** [comment]
Another possible approach is to start a huge SPSA session of say 100.000
games, starting with the patch values. But only parameter tweaks, no other
code, as it should be in a valid SPSA session.

**Comment by Stefano80** [comment]
Let us forget about max_half_time. You are saying: "we cannot commit as it is, but if we first run a SPSA session and then commit, then it's fine for me." It sound funny, let us do it...

**Comment by mcostalba** [comment]
yes, it may sound funny, but we may also assume that after 100.000 games
maybe teh random /bad parameter have returned to their orgiinal values.

**Comment by Stefano80** [comment]
But the other pars come from SPSA sessions in the first place. Anyway, if I find some time, I will submit this. In the meantime, mantainers please decide what to do with these 5 ELO lying around...

**Comment by FauziAkram** [comment]
My suggestion on this case would be to rn an ELO measurement of this patch with VLTC 120sec+ something.

If it gives at least +1.5 ELO then to merge this, and if other people are able to find any improve on these values, they can always make more tests after the patch got merged.

**Comment by lantonov** [comment]
Combo patches really gain Elo because individual patches are rarely independent. Especially tuning patches. I can explain combining of patches from a probabilistic point of view in the forum when I have more time. It takes a lot of writing and some background in probability e.g. the principle of exclusion-inclusion and conditional probability.

**Comment by IIvec** [comment]
@Stefano80: I just want to congratulate you on this brave and great attempt. Keep up a good work. Unfortunately or fortunately (I'm not sure about this), maintainers will decide and let them to do so.

@Everybody: We can't call portions of the code harmful only because they can probably be improved. Using that language we claim that Stockfish is full of harmful things.

**Comment by glinscott** [comment]
I'd be comfortable with merging a bunch of tuning patches that were outside our resolution to measure.  However, I don't think we can merge the TM portion of this patch.  If we exclude that, and it passes, I'd be okay with merging.  Before doing so let's make sure @zamar is okay with it as well.

**Comment by zamar** [comment]
Yes, merging a bunch of tuning patches together is totally fine.
Mixing it with time management is no-no.

**Comment by Stefano80** [comment]
Hi,

so I throw out max_half_time and retest at 0,4. Fine with you?

**Comment by glinscott** [comment]
Yes, that's fine, thanks.

**Comment by Stefano80** [comment]
New tests finished. Passed STC

LLR: 3.07 (-2.94,2.94) [0.00,4.00]
Total: 15124 W: 2974 L: 2756 D: 9394

And LTC

LLR: 2.95 (-2.94,2.94) [0.00,4.00]
Total: 21577 W: 3507 L: 3289 D: 14781

**Comment by glinscott** [comment]
Great, thanks!  New version looks good to me.

**Comment by IIvec** [comment]
I'm not against this patch, but delta values (deltaIncrement test) didn't pass STC. I'm now trying to improve that.

**Comment by Stefano80** [comment]
Good luck Ilvec. To mantainers: anyone going to merge soon?

**Comment by IIvec** [comment]
@Stefano80 : Thank you!
@Maintainers : Yes, please merge this, as we already discussed that this will be accepted, and that we can test against this things we think are not optimal.

**Comment by mstembera** [comment]
@Stefano80 
Congrats!  Do u mind declaring int razor_margin[4] as const?

**Comment by glinscott** [comment]
There were some merge conflicts I had to resolve manually.  Can you double check I did so properly?  Thanks.

**Pull request closed without merging**
