### PR TITLE
Replace arithmetic ADD with bitwise OR.

### PR DESCRIPTION
**Pull request by mstembera**
This is similar to https://github.com/official-stockfish/Stockfish/pull/132  See description there.
No speed difference but more self documenting.
No functional change.

### CODE REVIEW

**Comment by syzygy1** [comment]
I am rather certain that the change of make_piece to use OR instead of ADD slows down a bit and leads to more generated instructions.

The reason for changing make_piece to do an addition was that it is more natural for array indexing calculations.

See https://github.com/official-stockfish/Stockfish/pull/784#r77446032 for a longer explanation and some assembly output.

The same might apply to make_square() and make_move() if they are used in index calculations (probably not). But there is some value in keeping things consistent. (And also in not mixing or-operations with additions because it limits the compiler more in rearranging stuff.)

**Comment by mstembera** [comment]
OK I was not aware of the interplay w/ addressing modes.  If you think this https://github.com/official-stockfish/Stockfish/pull/132 should also be reverted since it's used for indexing feel free.

**Comment by MichaelB7** [comment]
I reverted  #132 and ran two concurrent benches to a depth of 25 ( bench 16 1 25):
Reverting #132 on my current fork:
===========================
Total time (ms) : 377376
Nodes searched  : 666914467
Nodes/second    : 1767241
===========================
As is:
Total time (ms) : 382323
Nodes searched  : 666914467
Nodes/second    : 1744374
==================
reverting is 1.3% faster on my PGO compiled versions -  reverting was faster on every single position

**Comment by syzygy1** [comment]
I don't see a reason for reverting #132. The calculated KPK bitbase index is still further manipulated (divided by 32 and AND'ed with 31 to get to the right bit), so I don't see how adding could be faster. Even if it were faster, it would only make a very small difference on KPK (and KPKP) positions.

So I'm afraid the 1.3% only confirms that measuring speed up in a reliable way is very difficult. (I don't doubt that the "reverted" binary is faster, but the speed up will most likely disappear or even become a slow down after the next patch.)

**Pull request closed without merging**
