### PR TITLE
Keep more pawns when attacking

### PR DESCRIPTION
**Pull request by snicolet**
Passed STC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 26157 W: 4928 L: 4689 D: 16540

and LTC:
LLR: 2.96 (-2.94,2.94) [0.00,5.00]
Total: 28121 W: 4400 L: 4174 D: 19547

Bench: 7337800

### CODE REVIEW

**Comment by joergoster** [comment]
Well done!

**Comment by zamar** [comment]
0) We have definitely found a good idea
1) There is general chess knowledge that backs this up.
2) Unfortunately from software design perspective, the solution is quite terrible. 
3) SF's eval is a linear evaluation interpolated with MG/EG score.
4) Now adding a completely new layer on the top of this evaluation function must be justified by something greater than just +2 ELO gain...

How to proceed from here?
A) Show that this patch add more than just 2 elo points. E.g. if it adds 4-5 elo points, I would happily commit it.
B) Try to integrate the idea with the standard linear evaluation system...
C) Improve the idea/framework, so that it becomes 4-5 elo points increase.

**Comment by lucasart** [comment]
Another problem is that this violates eval symmetry (used to skip eval calls after null move). This can be fixed, but requires to rework some code:
* separate eval in 2 functions: symmetric and asymmetric
* store symmetric eval on the search stack, not the entire eval. and recompute asymmetric eval even after null move.

Once the boiler plate code is merged, we can add this kind of asymmetric knowledge, without screwing up the existing search logic.

**Comment by AlexandreMasta** [comment]
How about trying to anchor it with the value of the pawn (half pawn) that changes from mg to eg?

**Comment by Rocky640** [comment]
A few lines above, we have
ScaleFactor sf = ei.mi->scale_factor(pos, strongSide);

This "sf" will be used in the final eval that we return, 
so it seems that we are already breaking the eval symmetry:
we always scale from the strongside point of view.

Then we have many lines of code which will change the sf according to different criteria.
So maybe the author can adapt his idea and change the sf before the line:

  // Interpolate between a middlegame and a (scaled by 'sf') endgame score

**Comment by snicolet** [comment]
@lucasart : this does not break eval symmetry. Please do not add noise to the discussion :-)

**Comment by locutus2** [comment]
@snicolet:
I have experimented a bit with your patch and come up with following which at least at local test seems promising.

int x = pos.count<PAWN>(WHITE) + pos.count<PAWN>(BLACK);
v -= v * (14 - x) / 28;

Its use a multiplicative instead of a additive penalty, so we could avoid the if statement and get simpler code.

**Comment by snicolet** [comment]
@zamar: I understand your concerns about the eval design perspective and the tuning problem(s) the current patch might exhibit...

We have first order pieces/pawns values for midgame and endgame, second order corrections in the imbalance() function for correlations between pairs of pieces, and lots of positional (structural) bonuses on top of that, but I didn't know where to start to add correction values to the pieces/pawns values based on the attacking/defending potential of the positional bonuses, so I probably took a wrong road :-(

@Rocky640: as you see, I have tested in Fishtest the version where we count only pawns from the attacking (strongSide) color -- using strongSide doesn't automatically break eval antisymmetry, btw --, but it failed to show an Elo gain. Maybe somehow keeping the defending player pawns on the board helps the attacking player, because more pawns mean more opportunities to create new weaknesses.

@locutus2: thanks for this nice and elegant idea, as usual :) I will test it in the framework, alongside with a version where I have put the score correction before the linear interpolation between MG/EG score, to go towards direction B of Joona's suggestions.

**Comment by zamar** [comment]
The patch is not commitable 'as is', so I'm closing this pull request.

However feel free to continue discussion and/or experimentation around this area.

**Pull request closed without merging**
