### PR TITLE
Recursive hell of vars

### PR DESCRIPTION
**Pull request by proukornew**
Variables had different behavior via recursive dependency hell.
If there is no environment variable -> sometimes variable treated as local with correct behavior. 
If there is environment variable      -> variable treated as global with multiple extending.

E.g. 
CXXFLAGS="-march=native -DNNUE_EMBEDDING_OFF" make COMP=mingw ARCH=x86-64-modern -j3 profile-build CXX=x86_64-w64-mingw32-g++.exe

Was:
x86_64-w64-mingw32-g++.exe -march=native -DNNUE_EMBEDDING_OFF -**Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2** -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate=profdir -pedantic -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2   -c -o bitboard.o bitboard.cpp

Now:
x86_64-w64-mingw32-c++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate=profdir -march=native -DNNUE_EMBEDDING_OFF -pedantic -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2   -c -o bitboard.o bitboard.cpp
...

### CODE REVIEW

**Comment by dubslow** [comment]
Is there any particular reason that this patch hasn't been merged?

**Comment by vondele** [comment]
I'm not convinced that introducing yet another variable is a good solution for the problem. Additionally, if this is introduced without documentation it doesn't help. I believe the proper solution is to make CXXFLAGS behave as expected.

**Comment by proukornew** [comment]
@vondele > is a good solution

**Comment by proukornew** [comment]
@vondele , check this.

**Comment by proukornew** [comment]
ping @vondele

**Pull request closed without merging**
