### PR TITLE
Rewrite time formula

### PR DESCRIPTION
**Pull request by mcostalba**
Time management is really too complex, our aim is
to simplify it, but for the time being at least rewrite
in an understandable way.

No functional change.

### CODE REVIEW

**Comment by zamar** [comment]
approved.

**Comment by lp--** [comment]
I am wondering if it will be more clear to move pv_instability_factor=1 + mainThread->bestMoveChanges  to the same place where you now define improvingFactor   removing code from timeman.ccp and timeman.h long lines of https://github.com/lp--/Stockfish/compare/tm_scaling...tm_min

But that of course would be very small functional change(mostly because of rounding) and would have to be tested. It is likely to pass, but to accept it or not is a matter of taste. So what is your opinion?

**Comment by mcostalba** [comment]
@lp-- Sorry but I don't understand the context of your question. Which code are you addressing? Is it some code in my patch or in master branch?

**Comment by lp--** [comment]
@mcostalba My simplification is applicable to both. Here I rebased it to your patch:
https://github.com/lp--/Stockfish/compare/356147d...e1972e5

Now with your changes it looks to me even better, so I submitted it for test -- framework is empty anyway

**Pull request merged**
