### PR TITLE
Simplify some passed-pawn determination

### PR DESCRIPTION
**Pull request by protonspring**
EDITED: supported is {0,1,2} NOT {0,1,2,3}, but the patch is still valid.
.
.
Because lever is {0,1,2} and supported is {0,1,2,3}, this condition in master is always true if lever is 0 or 1, thus the !more_than_one.  Furthermore, because of the -1, the condition in master is true if there is any support at all, thus the bool(supported).  This change is non-functional.

This -1 in passed pawns doesn't make sense to me, but allows this simplification nevertheless.  It would make sense that if we have as much support as lever, then we can pass, but it does not make sense to me that if we have 1 support pawn and 2 levers that we should be able to pass.  Trying to remove the -1 fails.

STC
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 23934 W: 5359 L: 5242 D: 13333 
http://tests.stockfishchess.org/tests/view/5b6b31740ebc5902bdb9e0c8

### CODE REVIEW

**Comment by snicolet** [comment]
Hi Mike, thanks for the patch.

Two remarks:

a) what do you mean exactly by the first sentence?

> because lever is {0,1,2} and supported is {0,1,2,3}, this condition in master is always true if lever is 0 or 1

I don't understand the part 

> because supported is {0,1,2,3}

b) the condition in master is clear: exclude the case levers=2, support=0. By contrast, your code is more convoluted, so it is not immediately obvious to me that it is a simplification.

**Comment by Stefano80** [comment]
Wouldnt ` (!more_than_one(lever) | supported)` do the trick too due to automatic casting?

**Comment by protonspring** [comment]
Here is a truth table for master:
              Support
Lever          0               1            2           3
-----------------------------------------------
   0    |         X               X             X          X
   1    |         X               X             X          X
   2    |                          X             X          X

thus, the popcount(supported) >= popcount(lever) -1 is ONLY false when lever = 2 and Support = 0  as you've stated.  This change is mathematically equivalent and probably faster.

Regarding clarity, if we're really just excluding levers==2 and supported== 0: 
For levers == 0 or 1 , isn't !more_than_one(lever) more clear than popcount(levers) ?
For supported == 0, isn't bool(supported) more clear than popcount(supported) ?

To me, the multiple popcounts suggest that there are multiple possibilities that could satisfy this condition when, in fact, there is only one exclusion.

**Comment by protonspring** [comment]
@Stefano80 I think you are right since more_than_one returns a bool, this is probably equivalent:
(!more_than_one(lever) | supported)

**Comment by Stefano80** [comment]
Well I would find this version definitely simpler than master.

@snicolet: your thoughts?

**Comment by snicolet** [comment]
> Here is a truth table for master (lever / supported):
support 0 1 2 3
Lever 0 | X X X X
Lever 1 | X X X X
Lever 2 | 0 X X X

Hmm, can you show me a position where one one of our pawn is supported three times?

**Comment by protonspring** [comment]
It's not often and doesn't happen in bench, but anything like this would do it:

. . P . .
. PPP .

If I get time later today, I'll try to find an actual FEN.

**Comment by protonspring** [comment]
Wait. . I just realized that "supported" is limited to "neighbours."  My bad. . so supported is 0, 1, 2. (so sorry!)

**Comment by snicolet** [comment]
If we want to test as a speed gain, let's test with 0..4, or otherwise let's close this PR :-)

**Comment by protonspring** [comment]
I will test it 0,4.  When it fails i will close the pr.

**Comment by protonspring** [comment]
0,4 test failed yellow
LLR: -2.95 (-2.94,2.94) [0.00,4.00]
Total: 51940 W: 11104 L: 11066 D: 29770 
http://tests.stockfishchess.org/tests/view/5b8ee0a10ebc592cf274e94e

**Pull request closed without merging**
