### PR TITLE
Threat Simplified

### PR DESCRIPTION
**Pull request by Rocky640**
Do not compute threats on weak pieces by the Queen in evaluate_threats

Passed STC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 13627 W: 2607 L: 2473 D: 8547

and LTC
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 19146 W: 2950 L: 2827 D: 13369

### CODE REVIEW

**Comment by Rocky640** [comment]
Of course, I have great insights and theories about everything. I'm such a smart person.
The only problem is that I'm right only 1% of the time ;)

**Comment by Rocky640** [comment]
However, I confess that I'm really good to predict the outcome of tests.
I always predict they will fail, and I'm right 95% of the time.

**Comment by zamar** [comment]
It's an interesting finding!

It's debatable if this really qualifies as a simplification.
However on the positive:
- introduces certain symmetry (queen is now systematically excluded from the Threat Bonus calculation).
- Makes it possible to retune the threat table.

So I think we can go ahead and commit this change as a simplification...

However we should fix comments:
from:
// Major on Defended
// Major on Weak
to:
// Rook on Defended
// Rook on Weak

**Comment by zamar** [comment]
approved.

**Comment by zamar** [comment]
No objections has been raised in 6 days. Committing.

**Pull request closed without merging**
