### PR TITLE
New Year Update

### PR DESCRIPTION
**Pull request by Rocky640**
Updated author list, top contributors and copyright year
bench: 4747984

### CODE REVIEW

**Comment by Rocky640** [comment]
For the authors, as suggested by @ppigazzini
I ran the command  git shortlog -s | cut -c8-
and updated manually the existing list.

Any new entry was verified to match an existing commit.
A few more were added by manually inspecting marco's repository and current repository.

However I could not confirm the following output from
git shortlog -s | cut -c8-

double-beep
Kurt
Mira
Nooby
Sergei Ivanov (is this same as svivanov72 ?)
Tom Truscott
Tracy Emery (basepr1me)
unknown

**Comment by snicolet** [comment]
Thanks, there is now a duplicate `Justin Blanchard`

**Comment by snicolet** [comment]
https://github.com/basepr1me/

**Comment by Rocky640** [comment]
Yes, i saw his repo, but cannot match a sf commit with this author

**Comment by Alayan-stk-2** [comment]
The two chessdbcn accounts should have their stats merged and attributed to noobpwnftw.

P.S. : Am I the only one to think that these copyright notices in the header are clunky ?

**Comment by noobpwnftw** [comment]
Nooby is a duplicate of me.

**Comment by svivanov72** [comment]
Yes I confirm that Sergei Ivanov is me.

**Comment by Rocky640** [comment]
with command
git shortlog *> author.log 

we can see the commits by author, so I was able to confirm all the remaining authors.
most likely explanation: many github accounts deleted, or renamed.

author "unknown" is related to a 2008 commit, so was probably marco
and was not included.

author kurt is same a Jared Kish (Kurtbusch) and was not added.

So list should be complete now.

**Comment by snicolet** [comment]
typo: Tracy Emery -> Tracey Emery

**Comment by mrobaczyk** [comment]
Could we probably merge ChessDB_CN_WorkerPool account into ChessDBCN in the database? ;)

**Comment by snicolet** [comment]
Merged via 09bef14c76e119103cc1a9404cbde7e249205deb, thanks! :-)

**Pull request closed without merging**
