### PR TITLE
Retire CenterBind

### PR DESCRIPTION
**Pull request by lucasart**
And compensate in the PSQT.

STC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 27714 W: 5161 L: 5052 D: 17501

LTC:
LLR: 2.95 (-2.94,2.94) [-3.00,1.00]
Total: 36354 W: 5008 L: 4909 D: 26437

### CODE REVIEW

**Comment by Rocky640** [comment]
With chirurgical precision. Congrats !

**Comment by mstembera** [comment]
Nice!  Maybe I'm not reading it correctly but the CenterBindMask ranks(from whites perspective) are 5,6, & 7 but those changed in the psqt are 4,5, & 6 assuming the 1st/top row(index 0) is rank1 and so on.  In any case it works so not a real issue maybe just a future tuning opportunity.

**Comment by lucasart** [comment]
@mstembera: PSQT adjustment needs to be for the pawns that are targetting CenterBind squares. So 1 rank lower, and 4 files wide in the center.

**Comment by mstembera** [comment]
@lucasart  Ah thanks for explaining.

**Comment by mcostalba** [comment]
Congrats!

I am very happy this worked and I will open a post on the forum because
this fixes a typical case in evaluation: a new eval term (CenterBind)
introduced to compensate a sub-optimal tuning in another part of code
(psqt).

**Comment by joergoster** [comment]
Didn't pass a while ago: http://tests.stockfishchess.org/tests/view/55cd1c390ebc591b934bd6cb

**Comment by vdbergh** [comment]
What Lucas is doing more or less systematically is the following: (1) Remove a feature. (2) Make some random change (likely placebo) elsewhere. (3) Run SPRT(-3,1) (4) If it fails go back to (2) (perhaps after waiting awhile so that people have forgotten).

Repeating regular tests is more or less harmless since they have  a lot of margin. However for non-regression tests it is disastrous. It is simply cheating statistics.

**Comment by mcostalba** [comment]
PSQT coefficent where different.

**Comment by mcostalba** [comment]
For code long term maintainability it is more disastrous to keep in an
(almost) useless term.

**Comment by vdbergh** [comment]
@mcostalba
The different PSQT terms are the "random changes" I was talking about. You cannot know that such random chances are not simply placebos. 

Assume you have a -1 elo regression. If you run a SPRT(-3,1) often enough it will pass for for purely probabilistic reasons, with or without random changes elsewhere.

Non-regression tests are all about proving (within a certain level of confidence) that something is not a regression. Lucas' practice kills this principle.

In your last comment it seems you are simply sanctioning running  SPRT(-3,1)'s indefinitely until they pass.

**Comment by lucasart** [comment]
@vdbergh: I tried 3 versions in total
* version 1: remove CenterBind
* version 2: remove CenterBind and compensate by adding 50% of the CenterBind bonus to the PSQT
* version 3: remove CenterBind and compensate by adding 25% of the CenterBind bonus to the PSQT

All 3 of them passed STC.

I only scheduled 2 versions at LTC:
* version 2: failed `sprt(-3,1)` at LTC, after a very long run (218k games)
* version 3: passed `sprt(-3,1)` at LTC, relatively quickly (36k games)

**Comment by lucasart** [comment]
@vdbergh: Apart from trolling pull requests and forum discussions, what are you contributing to Stockfish ? When I look here, I don't see you:
https://github.com/official-stockfish/Stockfish/graphs/contributors

**Comment by vdbergh** [comment]
@lucasart
It seems you are unable to keep a discussion at a scientific level.
 
Whether or not a test passes STC and the number of games is irrelevant statistically. You cannot change the interpretation of a test after the fact. You know this.

For my contributions look here

http://tests.stockfishchess.org/users

(entry vdbergh). Also don't forget that I am the originator of the use of the SPRT in chess engine development and the author of the chi^2 test on fishtest.

What are you contributing actually? Except for showering people that do contribute with gratuitous insults?

**Comment by mcostalba** [comment]
Do you mind to add some quantitative data to your argumentations?  How much
is altered the sprt regression test running 2 times the same test?

Some number would be better than a bag of words.

**Comment by Stefano80** [comment]
@mcostalba : actually, lucas should provide evidence that running twice the same test with some small differences does not compromise the validity of the test. 

@vdbergh : "Whether or not a test passes STC and the number of games is irrelevant statistically." is not  true (more precisely: is only true in the context of non-bayesian hypothesis testing). In this case is most probably safe to commit, given that STC passed three times.

**Comment by vdbergh** [comment]
@stefano80

Mixing sequential testing and Bayesian statistics is very dangerous for people that have no background in statistics. For example if we were to accept Bayesian principles on sight then LOS based stopping of tests would be ok. And we know it is not.   

@mcostalba 

The result depends on the values of drawelo and I am too lazy to look up the current values (it is not my patch remember). But I recall that you consider the regression risk of the current SPRT(-3,1) **barely acceptable.**  I assume you have not changed your mind about this.

Anyway assume that a -1 elo patch has 8% probability of passing (I think this is in the right ballpark). Then running the test twice the pass probability becomes 15%. Running it three times we get 22% etc...

**Comment by zamar** [comment]
Now everbody, please calm down.

- The patch passed and it will be committed.
- Traditionally we allow three attempts (different variations) in the same area. Then you need to leave the code alone for some time, preferrably around 4-6 months, before trying again.

- We allow this same rule for both standard tests and regression tests. There is a good reason for this. Regression tests remove code and features. If an evaluation term has a value of 1 elo point, it "deserves" to be removed. Removing it, improves orthogonality and makes it easier to implement something better in the area in the future.

- However @vdbergh also has a point. We humans have a tendency that we "want" things to be in a certain way. If we want to remove a certain feature or piece of code, and we keep running regression tests every 6 months against that same piece of code, then eventually the test will pass. This is cheating statistics, and it should be avoided. On the other hand, over the time, compiler changes, context around the code changes, so when enough changes have taken place, it's completely fine to try again... So please use some common sense here!

Over and out. I'll commit the patch soon.

**Comment by vdbergh** [comment]
@zamar 

The motivation behind the SPRT(-3,1) was to avoid -1 elo regressions. Even at the 36% risk of 0 elo patches failing. I always considered this misguided. So I am suprised that -1 elo regressions are now considered ok. I don't think this was ever stated anywhere.

You are now giving people a license to run three identical SPRT(-3,1) tests in a row (when is a variation truly different?). If this is really what you mean what you mean, why not making it official here https://github.com/glinscott/fishtest/wiki/Creating-my-first-test ? This would avoid further discussions in the future.

Running three SPRT(-3,1) in a row of course reduces the risk of a zero elo patch failing to 5%. But it also increases the risk of -1 elo patch passing to 22%. There is simply no free lunch in no-regression testing. The best one can do is being explicit about everything.

**Comment by zamar** [comment]
I'm not giving people license to run 3 identical regression tests in a row. The variations need to be genuine.

I know that there are no free lunches. It's just practically impossible to formulate rules that will work correctly in every situation... 3 tries / 4-6 month at one area is just an absolute maximum. And still it can be abuse, if people try to cheat on statistics.

**Comment by VoyagerOne** [comment]
My only concern and question here is:  
Why is the hash set to 64 and not the default of 128, to test this patch?

**Comment by AlexandreMasta** [comment]
@VoyagerOne Because Lucas creates his own rules. As Vdberg pointed...he is always creating new conditions for his tests to sneak in a patch.

**Pull request closed without merging**
