### PR TITLE
Add tempo also to NNUE eval.

### PR DESCRIPTION
**Pull request by locutus2**
STC:
LLR: 2.93 (-2.94,2.94) {-0.50,1.50}
Total: 10608 W: 1507 L: 1358 D: 7743
Ptnml(0-2): 94, 945, 3074, 1100, 91
https://tests.stockfishchess.org/tests/view/5f2c5921b3ebe5cbfee85b8b

LTC:
LLR: 2.94 (-2.94,2.94) {0.25,1.75}
Total: 7536 W: 556 L: 448 D: 6532
Ptnml(0-2): 9, 383, 2881, 481, 14
https://tests.stockfishchess.org/tests/view/5f2c6f4461e3b6af64881e95

Bench: 4746616

### CODE REVIEW

**Comment by mstembera** [comment]
Congrats!
I wonder if side to move is encoded for NNUE? I know @nodchip mentioned that castling rights for example aren't right now.

**Comment by locutus2** [comment]
@mstembera 
I haven't looked in the code but as i  understand the description only the combinations of pieces with the kings are considered as input features.

**Comment by mstembera** [comment]
I'm not against this PR but it seems like in the longrun the holistic solution is to encode missing features.

**Comment by sf-x** [comment]
> I wonder if side to move is encoded for NNUE? I know @nodchip mentioned that castling rights for example aren't right now.

It isn't. The board is flipped horizontally so that the same side is always to move.

**Comment by Lolligerhans** [comment]
> 
> 
> > I wonder if side to move is encoded for NNUE? I know @nodchip mentioned that castling rights for example aren't right now.
> 
> It isn't. The board is flipped horizontally if needed so that the same side is always to move.
Wouldn't that mean that it _is_ implicitly encoded?

**Comment by vondele** [comment]
Thanks!

**Pull request closed without merging**
