### PR TITLE
Tweak Pawn PSQT

### PR DESCRIPTION
**Pull request by SFisGOD**
Average values of Asymmetrical 8 by 8 Pawn PSQT (PR#1839 by Jared Kish)

STC (Yellow)
LLR: -2.95 (-2.94,2.94) [0.00,4.00]
Total: 114999 W: 25338 L: 25049 D: 64612
http://tests.stockfishchess.org/tests/view/5c040c5a0ebc5902bcee2072

LTC (Green)
LLR: 2.96 (-2.94,2.94) [0.00,4.00]
Total: 86168 W: 14535 L: 14106 D: 57527
http://tests.stockfishchess.org/tests/view/5c05020e0ebc5902bcee390c

PR#1839 revealed that we can still improve the Pawn PSQT. The average values from 8x8 Pawn PSQT seem to be enough to pass a [0,4] LTC test.

Bench: 3435513

### CODE REVIEW

**Comment by GuardianRM** [comment]
At the moment, we cannot say with sufficient confidence that the 8x8 tables can be simplified. I think it is worth waiting for the results of the settings http://tests.stockfishchess.org/tests/view/5c03968d0ebc5902bcee15ac
and check them against the current 8x8 settings. 
Then, it’s probably worth checking out this or updated 8x4 patch, as a simplification in LTC.

**Comment by snicolet** [comment]
So now we have two conflicting pull requests improving the pawn PSQT:
• https://github.com/official-stockfish/Stockfish/pull/1839 introducing a special case for pawns psqt, in the form of asymmetrical 8x8 table
• this pull request, using the average values for queenside and kingside, restoring symmetry and also gaining Elo as sqprt[0..4] (but with a yellow STC).

My personal preference would be to commit the simpler version (this PR). @mcostalba What's your opinion?

**Comment by MichaelB7** [comment]
My $.02 - agree with @GuardianRM and then perhaps test as a simplification this 8x4 against the patch passing at (0,5). Either way , this is a good problem to have. Good work by both.  😊

**Comment by Vizvezdenec** [comment]
This PR has it cons - one SPRT passed (can be just lucky) and actually LTC passing in more games (with less expected elo perf).
While Kurt SPRT passed LTC 3(!!) times so is even more safe than our usual patch to be an elo gainer. I'm strongly onto running [-3;1] LTC SPRT of this patch vs 8x8 PSQT patch and commit based on this data.

**Comment by ElbertoOne** [comment]
I think as a general rule [0,5] patches are preferred to [0,4] patches, which in turn are preferred to [-3,1] patches.
So my take is that PR #1839 should be preferred here. This PR can be run as a simplification against PR #1839

**Comment by Vizvezdenec** [comment]
Sure, 1st passes of Kurt patches were with different set of params, but it's just a proof that this asymmetric PSQT can get elo with different set of parameters.
And 2nd variation passed SPRTs _cleanly_, w/o any speculative LTC, and faster.

**Comment by mstembera** [comment]
I scheduled http://tests.stockfishchess.org/tests/view/5c087db10ebc5902bcee7d6d to gather more information.

**Comment by mstembera** [comment]
The result was:
LLR: -2.96 (-2.94,2.94) [-3.00,1.00]
Total: 31058 W: 5024 L: 5227 D: 20807
In favor of the original asymmetric psqt.

**Pull request closed without merging**
