### PR TITLE
Reformat lazy smp code

### PR DESCRIPTION
**Pull request by mcostalba**
Just a first quick pass. Probably Skill and MultiPV
need some work too.

No functional change.

### CODE REVIEW

**Comment by ajithcj** [comment]
@mcostalba, Is it fine to run any new patches against this branch? I've never run tests against any branch other than master...  were there any functional changes that went into master after lazy branch was commited?
What is the bench for this branch?

**Comment by mcostalba** [comment]
Please run any lazy smp related
patch against this branch.

Any other patch should be still run against master.

**Comment by mstembera** [comment]
Thanks for the reformat & cleanup Marco.  Do you have to wait for approval to merge this(and the easy move bug fix) since it's not the master branch and these are just bug fixes and none functional changes?  Obviously formal approvals will be needed when/if this becomes master.

**Comment by mcostalba** [comment]
Yes, because things are moving fast here (the binary for TCEC has already a
fix not included in lazy_smp branch) I will go in a more informal way, like
we did for C++11 branch.

Of course maintainers are always free to ask me to revert at any time.

**Comment by ElbertoOne** [comment]
"I am not testing anything, I grab the latest build from abrok.eu at the start of Stage 3 " said Martin Thoresen on TCEC chat this morning. So this means no lazy smp in stage 3 of TCEC?

**Comment by mstembera** [comment]
@ElbertoOne 
To be clear we aren't/wouldn't ask Martin to test anything or do any extra work.  Only to allow the maintainers to specify a binary from a different location other than abrok (as we did for the final of last season).

**Pull request merged**
