### PR TITLE
NMP Tweaks

### PR DESCRIPTION
**Pull request by VoyagerOne**
NMP Tweaks

STC:
LLR: 2.96 (-2.94,2.94) [0.50,4.50]
Total: 19675 W: 4430 L: 4169 D: 11076
http://tests.stockfishchess.org/tests/view/5d52bc0e0ebc5925cf108300

LTC:
LLR: 2.95 (-2.94,2.94) [0.00,3.50]
Total: 73895 W: 12496 L: 12114 D: 49285
http://tests.stockfishchess.org/tests/view/5d52dcbc0ebc5925cf108552

Bench:  4126385

### CODE REVIEW

**Comment by VoyagerOne** [comment]
I understand there are some concerns with scaling of this patch.
I am open for any suggestions...

**Comment by Alayan-stk-2** [comment]
I think this should be committed. It still passed cleanly at LTC, and the short STC may have just been a fluke. And even if the gain may become too small at VLTC, it would take stronger standard of proof to believe in a regression.

In the end, if we start worrying so much about TC scaling that we'd refuse a clean STC+LTC patch like this, then the time controls used for testing (and the way bounds put more emphasis on STC perf) should be changed.

**Comment by anshulongithub** [comment]
The developers who understand this code, please confirm. @VoyagerOne @locutus2 @xoto10 @MortenLohne, in @xoto10's PR there were discussions that some changes from a similar patch (nmpImp2) which had this change `-(improving * 55)` wud affect the big gain that we got from that tuning patch. 
I am all for this patch, but before we commit, we shud confirm that it is also improvement at VLTC even if it is small. For a patch that is an ELO gainer, I wanted to confirm the following:
1) It shud also improve at VLTC and i understand that we cannot test for all patches but in this case since this might be interacting with the recent tuning changes which affect the strength at VLTC, we need to make sure that then this change is not affecting the level that was reached by tuning in a regressive way. 
2) Also if it's not tested at VLTC, then we shud be able to logically reason about why it will be an improvement even at VLTC conditions and will not affect the strength that was reached after the recent tuning patch was committed.

**Comment by VoyagerOne** [comment]
@snicolet 
What's the verdict for this patch?

**Comment by MichaelB7** [comment]
The patch passed and it should be committed.  Just my $.02. Not sure why it was not committed earlier today, but I’m sure they have a reason and it was not simply overlooked.

**Comment by Kingdefender** [comment]
I think Stéphane just waiting if anyone has suggestions if it is useful to do more tests before committing?
It is none of my business but because I was quoted, I don't see any reason to single out this patch from others? You can always try to improve it. If you think it may be worse at VLTC or more threads, you can always test it later or do a regression test, after committing. But to get statistical significance, it is always a large effort so before that I think you would need to have some evidence of regression, in specific cases for instance.

**Comment by adentong** [comment]
Looking at this test http://tests.stockfishchess.org/tests/view/5d5c3a480ebc5925cf111c04, it seems that the second round of tuning will also bring more elo. So perhaps this patch can wait until after the second round of tuning has been committed, then it can be retested against that. Just my 2 cents.

**Comment by snicolet** [comment]
Note that "the second round of tuning" has not been committed yet, because it sounds like a lot of the tuned values introduce complexity which may well be just random noise of the tuner.. :-(

**Comment by mstembera** [comment]
This patch passed before the second round tuning tests so if anything those changes should have to pass on top of this patch not the other way around.  Or am I missing something?

**Comment by adentong** [comment]
@mstembera You're right of course, but it's a matter of priority imo. Since the second round of tuning and this patch clearly affect each other, and the tuning may bring much more elo than this one, personally I'd wait until the tuning is finished and proven to be a good elo gainer before moving on to this patch. But of course how well the tuning will do is all speculation at this point and certainly there's no harm in committing this first.

**Comment by snicolet** [comment]
The null-move pruning research has stalled on the framework, so I commit this pull request now. Merged via 0e295fee25a41962d234c0833e1f7ca29e4c2189, congrats!

**Comment by VoyagerOne** [comment]
@snicolet 
Thank you.

**Pull request closed without merging**
