### PR TITLE
Remove cap from initiative contribution

### PR DESCRIPTION
**Pull request by Stefano80**
Allow initiative contribution to change endgame evaluation sign.

[STC](http://tests.stockfishchess.org/tests/view/59316d540ebc59035df34f31)
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 22720 W: 4212 L: 4094 D: 14414

[LTC](http://tests.stockfishchess.org/tests/view/5931aeb30ebc59035df34f4b)
LLR: 2.96 (-2.94,2.94) [-3.00,1.00]
Total: 44447 W: 5802 L: 5712 D: 32933

Bench: 6140304

### CODE REVIEW

**Comment by snicolet** [comment]
@Stefano80 

You should push another commit without "Take NNN" on the same line as the "Bench: 6140304" information. As it is, the "0" in "Take 0" is confusing travis-ci for its extracting of the bench number :-)

**Comment by Stefano80** [comment]
I amended the commit and forced a push, thank you Stephane for noticing...

**Comment by snicolet** [comment]
I also suggest to shorten the comment (and to remove the "." at the end of the sentence) in the following lines:

````
    // We find the attacking side by extracting the sign of the endgame value
    int value = ((eg > 0) - (eg < 0)) * initiative;
````

**Comment by Stefano80** [comment]
Hi @snicolet , I just notice that now it does not really make sense to have an extra variable and shortened everything. Is it better now?

**Comment by mcostalba** [comment]
@Stefano80 the cap is in place to ensure the endgame score will never change sign after the bonus. How do you address that?

**Comment by Stefano80** [comment]
I don't understand the question. I don't obviously address the problem, since I want     to remove the cap. The test proved that the cap is indeed useless.

**Comment by mcostalba** [comment]
@Stefano80  in this case please mention in the comment that sign can change, like:

`// Return the bonus or malus for the attacking side`

**Comment by Stefano80** [comment]
OK, will do in the afternoon
Il 04/giu/2017 10:32 AM, "Marco Costalba" <notifications@github.com> ha
scritto:

**Comment by Stefano80** [comment]
Hi @mcostalba , I added the comment as you suggested.

**Comment by zamar** [comment]
For me this does not qualify as a simplification.

Sure, the actual code is a little bit simpler, but the system will behave in unexpected way when you allow endgame score to change sign.

So we may end up in situations where e.g. white would prefer to have a score -4cp instead of +4cp before initiative calculation is applied, because -4cp might become +2cp and +4cp might become -2cp.

I'll leave this open for a little while for further discussion, but my current thinking is to reject the patch.

**Comment by Stefano80** [comment]
Hi @zamar , this confused me a little bit too, when I first made the test, and when I see it pass so easily (also at LTC, where usually imprecise evals dont go well). 

The initiative cap causes SF to evaluate a position with endgame value 100 (half-a-pawn!) and initiative -100 (which _is_ actually in range) exactly as good as a position with endgame value 0 and initiative -100. This is obviously bad, and could happen really when comparing positions in the same search subtree.

As soon as I thought of this, I found the new version much clearer.

**Comment by theo77186** [comment]
I have checked for `initiative < -abs(eg)` using `dbg_hit_on` and it seems that (at least with bench 16 1 20), there is about 2.9% of positions that can cause sign flipping with this patch. The question is: is the sign flipping in 2.9% of positions acceptable?

    Total 60163208 Hits 1719129 hit rate (%) 2
    ===========================
    Total time (ms) : 59267
    Nodes searched  : 105981775
    Nodes/second    : 1788208

**Comment by snicolet** [comment]
@Stefano80 

An initiative value of -100 means that the endgame is "very drawish" (no king separation, fewer pawns, symmetrical pawn structure, pawns on the same flank, etc.). It is true that the current implementation of evaluate_initiative() maps a prior eval of 0 and and prior eval of 100 to the same draw value, which is exactly what it was intended to do (in fact it will map any prior value in the range [-100..100] to a draw value when initiative is -100).

Joona's point is that after the patch, a prior value of -1 will be mapped to +99 and a prior value of +1 will be mapped to -99, which is indeed a little bit unsettling and even more "obviously bad" that the situation you are describing :-)

But on the other hand, as @theo77186 remarked, such situations are very rare — and I suspect that the 2.9% of sign changes are typically much milder that that, anyway: the following code fragment shows that the evaluation after the sign changes is in the range [-23...23] 50% of the time:

````
    if (initiative < -abs(eg))
       dbg_mean_of( abs(initiative) - abs(eg) <= 23 );

    ==> Total 106192 Mean 0.508117
````

On balance, I think that we should accept the patch, based on the following considerations:
- evaluation is fuzzy and imprecise anyway, especially in the [-23..23] range (-23 is one tenth of a pawn!), and Stockfish is able to draw any drawish position in that range, even against itself
- the patch passed the STC and LTC tests with more wins than losses, and we should trust the statistics more than our intuition on evaluation matters
- applying the patch may open opportunities to add more drawing knowledge in evaluate_initiative() — only time will tell.

**Comment by zamar** [comment]
The patch does not qualify as a simplification for reasons that I've explained above.

Regarding @snicolet points my answers are as follows:
- evaluation() is fuzzy and imprecise, but committing something that makes it even more fuzzy and imprecise is not good.
- SPRT gives a boolean result (true, false). Whether something passed with more wins than losses matters very little from statistical perspective. People misuse this information a lot.
- Initiative is worth maybe 2-3 ELO points. Making a tweak that affects <5% cases is unlikely to make a meaningful impact (magnitude of 0.1-0.2 ELO points). It's very unlikely that this would open up any new possibilities.

Based on these considerations, I reject the patch.

**Comment by mstembera** [comment]
Agree w/ the above.  I scheduled
http://tests.stockfishchess.org/tests/view/593842d60ebc59035df3514d
at [0,4] so we can be sure we're not missing an elo gain.

**Comment by Stefano80** [comment]
Hi, I don't want to argue too much, @zamar, but you're implicitly stating that the revert of this patch would qualify as a simplification because it fixes fuzzy behaviour. This is not how SF was run in the last years...

**Pull request closed without merging**
