### PR TITLE
Search tweak

### PR DESCRIPTION
**Pull request by unaiic**
STC https://tests.stockfishchess.org/tests/view/5f2d606a61e3b6af64881f88
LLR: 2.95 (-2.94,2.94) {-0.50,1.50}
Total: 8440 W: 1191 L: 1048 D: 6201
Ptnml(0-2): 59, 754, 2467, 865, 75

LTC https://tests.stockfishchess.org/tests/view/5f2d84ad61e3b6af64881fbd
LLR: 2.95 (-2.94,2.94) {0.25,1.75}
Total: 21896 W: 1557 L: 1406 D: 18933
Ptnml(0-2): 33, 1185, 8378, 1302, 50

bench: 4224326

All credit to @Vizvezdenec, the original author of the idea

### CODE REVIEW

**Comment by silversolver1** [comment]
if i may propose a solution to this, i don't think simply being the person to submit someone else's code constitutes authorship rights. consider the following two cases:

1) someone can't or doesn't have time to submit LTC and someone else submits for them
2) only one approver is online and they're submitting a test so a non-approver resubmits the test for them (STC or LTC) so that the approver can then start it without having to wait

in neither of these situations does being the person to technically obtain the test result qualify them as being the author of the code. the person who actually authored the code is the one who gets to commit, not anyone else (unless the actual author is not able to for some reason)

similarly, here, i don't think a copy-paste job warrants a commit. and the whole "i will mention or credit in merge"? what exactly does that mean? what exactly are you giving them credit for? someone else actually wrote the patch, they should be getting the entire credit, and the merge, not you.

so as an actual solution, if this is to be committed, i think @Vizvezdenec should get commit rights. it would be one thing if this were an actual variation of someone's idea but it is literally just copy paste as the person in question has already admitted

to add to that, if this were really just re-testing someone's idea, then why not be open about it from the beginning? if you were really doing this for someone else but conveniently just "forgot to say it" a bunch of times, then why attempt to get merge rights and your name on the patch as you are doing right now? it doesn't add up, does it?

**Comment by Vizvezdenec** [comment]
Honestly...
1) I don't care much. I have a lot of commits either way;
2) unaiic should get credits at least for finding that test and retrying it because I was NOT planning to do so because I didn't think that this type of stuff will change a lot with eval change. But he proved my thoughts wrong and should get his credit for this;
3) I myself did submit older ideas of other people, namely jerrydonaldwatson, one of them passed. It's an okay thing to do if original author isn't planning to resubmit his 3 months old tests for w/e reason.

**Comment by silversolver1** [comment]
indeed for some reason it seems that you in particular do not care but this sets a very bad precedent that copy pasting and stealing other peoples' work is ok. if that is acceptable to you, then what else can i say?

**Comment by Vizvezdenec** [comment]
Gonna like how you are answering only to 1) and completely ignore 2) and 3) which are actually not a personal opinion but more or less facts.
Tweaking numbers / submitting other people older tests is basically where everyone started. For example, myself. 
Just stop this already. You are making an issue out of almost nothing.

**Comment by vondele** [comment]
trying and refining ideas of other people is acceptable, if credit is given, and if this is not done while these people are working on it. So yes coming up with own ideas is excellent, but picking up where others have stopped is fine as well. 

Let's close this discussion.

**Comment by silversolver1** [comment]
very well. of course i still don't agree but at least i've said my part which is all i can really do here.

**Comment by vondele** [comment]
@silversolver1 one comment on stealing and code ownership. There is an important aspect here... all code we are talking about is licensed by the authors under GPL (as distributed stockfish derived work, etc.), these changes are derived work from that as well. We're rather talking about good style. Yes, @unaiic should give credit where it is due, and give people the time to work on/develop their ideas, but that's a matter of communicating that.

**Pull request closed without merging**
