### PR TITLE
Disable TB probing at PV nodes

### PR DESCRIPTION
**Pull request by lucasart**
* preserves the ELO gain of TB (see below test results).
* resolves some glitches: finding mates, showing PVs.
* significantly less code, and less download/disks-pace usage, because we only need WDL tables now.

**1/ Disable TB at Root**

*conditions*

    syzygy 5-men
    tc=4+0.04, hash=16, contempt=10, openings=book5.epd, concurrency=7
    resign movecount=3 score=700
    draw movenumber=40 movecount=8 score=20
    sprt(-4,0)

*result*

    tbroot vs master: 3887 - 3846 - 7642  [0.501] 15375
    ELO difference: 1
    SPRT: llr 2.96, lbound -2.94, ubound 2.94 - H1 was accepted 

**2/ Disable TB at PV nodes**

*conditions*

    syzygy 5-men
    tc=5+0.05, hash=16, contempt=10, openings=book5.epd, concurrency=7
    resign movecount=3 score=700
    draw movenumber=40 movecount=8 score=20
    sprt(-4,0)

*result*

    tbpv vs master: 1793 - 1711 - 3756  [0.506] 7260
    ELO difference: 4
    SPRT: llr 2.95, lbound -2.94, ubound 2.94 - H1 was accepted 

**2/ Disable TB at PV nodes + NO ADJUDICATION**

*conditions*

    syzygy 5-men
    tc=5+0.05, hash=16, contempt=10, openings=book5.epd, concurrency=7
    resign movecount=3 score=700
    draw movenumber=40 movecount=8 score=20
    sprt(-4,0)

*result*

    tbpv vs master: 5533 - 5531 - 10991  [0.500] 22055
    ELO difference: 0
    SPRT: llr 2.96, lbound -2.94, ubound 2.94 - H1 was accepted

### CODE REVIEW

**Comment by lucasart** [comment]
edit: resign and draw disabled in the last test, obviously. copy/paste mistake…

**Comment by Nazine** [comment]
rejected.

**Comment by zamar** [comment]
* As pointed out in fishcooking forum, we lose perfect play, and are not able to win some endgames anymore.
* There should be better ways to address this problem than dropping WDZ bases...

**Comment by mcostalba** [comment]
Perhaps it could make sense to just disable TB at PvNode, but leaving the
filter at root moves.

**Comment by zamar** [comment]
First I'd rather try to see if we can make the following trick work (as I said in Fishcooking):

* When you access syzygy bases, and get a winning score:
- If the score is above beta, you just fail high, and return immediately.
- Otherwise, you just set bestValue = alpha = "winning score" and let the search carry on... There are some complications, but it should be possible...

This should provide long PV in most circumstances, not miss any mates, still provide proper winning scores, etc.

But it can be a bit tricky to get right...

**Pull request closed without merging**
